### ISSUE TITLE
Microsoft office on new computer

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#100]
Is there Microsoft office somewhere that I can put on the new computer?

**Comment by kubu4** [comment]
UW offers Microsoft software: https://softy.cac.washington.edu/microsoft/officewin.html

**Comment by kubu4** [comment]
You'll want a 64-bit version of Microsoft Office.

**Comment by grace-ac** [comment]
Okie dokie! Thanks!

**Comment by grace-ac** [comment]
Does it need to be a UW email to get it? 

I am already using my UW account to have Microsoft on my own computer.

**Comment by grace-ac** [comment]
Yes - sorry for not explaining initially.

I try to sign in using my UW account and it says: 
![capture](https://user-images.githubusercontent.com/14934314/31639734-16fbc368-b28f-11e7-8e6f-5a789bba90df.PNG)

Then I select the create a new account option, and then this pops up: 
![capture1](https://user-images.githubusercontent.com/14934314/31639740-23f2aca8-b28f-11e7-91f1-1fb0d61ecc3e.PNG)

And then I went back to sign in again, but then the whole thing happens again.

**Comment by kubu4** [comment]
Which version did you download and install. No sign in to Microsoft should be needed.

**Comment by grace-ac** [comment]
Oh wow. Sorry I clicked on the wrong link!!

**Comment by grace-ac** [comment]
As an update: i had to leave and didn't download to computer. I still hadn't found the right version by the time I left.

**Comment by kubu4** [comment]
Installed Office Professional 2016 64-bit (Access, Excel, Power Point, Word).
