### ISSUE TITLE
Blast Hemato transcriptome to UniProt/Swiss-prot database

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1001]
Take https://owl.fish.washington.edu/halfshell/genomic-databank/hemat_transcriptome_v1.5.fasta

and locally blast against Swiss-prot protein database
https://d.pr/i/PM8KAa

generating a table output with one hit per query.

---

A blast tutorial... https://github.com/sr320/fun-gen/blob/master/Jupyter/03-Local-Blast.ipynb

from https://github.com/sr320/fun-gen

**Comment by afcoyle** [comment]
I've been working through the blast tutorial before tackling the main project, and ran into an issue I just can't quite fix! 

I'm on the last step, and keep getting the following error: Command line argument error: Argument "out". File is not accessible:  `/home/afcoyle/bioinfo/analyses/Ab_4-uniprot_blastx.tab'

It seems like my permissions are wrong, but I can't figure out how to fix em (tried something earlier, apparently didn't work!)

The relevant code is below (directories are differently ordered from tutorial, could be important?)


afcoyle@DESKTOP-D31GIKM:~/bioinfo$ blastx \
> -query /home/afcoyle/bioinfo/Ab-4denovo_CLC6_a.fa \
> -db /home/afcoyle/bioinfo/uniprot_sprot_r2018_08 \
> -out /home/afcoyle/bioinfo/analyses/Ab_4-uniprot_blastx.tab \
> -evalue 1E-20 \
> -num_threads 4 \
> -max_target_seqs 1 \
> -outfmt 6

And here's the directory I'm working in:
afcoyle@DESKTOP-D31GIKM:~/bioinfo$ ls
Ab-4denovo_CLC6_a.fa  uniprot_sprot_r2018_08.phr  uniprot_sprot_r2018_08.psq
uniprot_sprot.fasta   uniprot_sprot_r2018_08.pin

Any help on this would be really (really) appreciated!!

**Comment by kubu4** [comment]
The first thing I notice is that you don't have line continuation characters after each line. Your code should look like this:

```shell
blastx \
-query /home/afcoyle/bioinfo/Ab-4denovo_CLC6_a.fa \
-db /home/afcoyle/bioinfo/uniprot_sprot_r2018_08 \
-out /home/afcoyle/bioinfo/analyses/Ab_4-uniprot_blastx.tab \
-evalue 1E-20 \
-num_threads 4 \
-max_target_seqs 1 \
-outfmt 6
```

Give that whirl and let us know how it goes.

**Comment by afcoyle** [comment]
Still getting the same error, sadly! Thanks for the correction though!

**Comment by kubu4** [comment]
Sorry I didn't catch this before! You don't have a directory called `analyses`. As such, it can't access a file in a directory that doesn't exist.

**Comment by afcoyle** [comment]
Ahhh perfect, fixed it!!! Thanks so much!

**Comment by sr320** [comment]
Lets leave open until notebook post..

**Comment by kubu4** [comment]
Sorry! Forgot problem wasn't dedicated GitHub Issue.

**Comment by afcoyle** [comment]
Alright, I think I finished up with this! Ended up running two blasts - one with the same formatting as the tutorial blast, another with max_hsps = 1. Links to the results are in my lab notebook for 9/21!

**Comment by sr320** [comment]
can you put url here?

**Comment by afcoyle** [comment]
Sure thing, here you go!

https://afcoyle.github.io/Hemat-transcriptome-results/

**Comment by sr320** [comment]
Great! Can you get Jupyter installed, set up a GitHub Repo and redo this using these tools. (publishing the jupyter notebook in the repo). Ideally this would be set up where I could download the repo and reproduce the results.

**Comment by afcoyle** [comment]
Alright, I think I finished this up! Here's the GitHub link: https://github.com/afcoyle/jupyter-notebook/tree/master/hematodinium-blast-data

Script for reproducing my results is in hematodinium-script.ipynb

Some of the intermediate files (the unzipped Swiss-prot file and the resulting database) aren't present- apparently they're too large to be pushed to GitHub. If that's an issue and there's a way to fix it, please let me know!

One last note: I ran the blast twice, once with a line for max_hsps, once without. The resulting data are in two files - hemat_uniprot_nomaxhsps_blastx.tab and hemat_uniprot_maxhsps_blastx.tab. 

Anyway, I hope that's what you were looking for! Let me know if there are any issues, and if not, I'm ready to tackle another project!
