### ISSUE TITLE
Blast Hemato transcriptome to UniProt/Swiss-prot database

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1007]
Take https://owl.fish.washington.edu/halfshell/genomic-databank/hemat_transcriptome_v1.5.fasta

and locally blast against Swiss-prot protein database
https://d.pr/i/PM8KAa

generating a table output with one hit per query.

A blast tutorial... https://github.com/sr320/fun-gen/blob/master/Jupyter/03-Local-Blast.ipynb

from https://github.com/sr320/fun-gen

**Comment by crmateo** [comment]
I'm having a bit of trouble downloading stand-alone BLAST. How do I add the program to absolute paths / variables? Also just to double check, which packages from the link in the blast tutorial do I need? I downloaded all except those specifying a non-mac os.

**Comment by kubu4** [comment]
>  non-mac os

Ah! Which operating system are you using? Windows 10? If yes, follow the Microsoft instructions for installing the Windows Subsystem for Linux (it's basically an app, but requires a bit of configuration before it can run):

- https://docs.microsoft.com/en-us/windows/wsl/install-win10

After you do that, select "Ubuntu" for your installation (if there are multiple versions, just pick the one with the highest number; 20.04, maybe?).

Then, use this Linux "app" to do all of your bioinformatics work.

Anyway, once you get the Ubuntu app installed on Windows, let us know here, and we can help you get BLAST downloaded/installed.

**Comment by crmateo** [comment]
I'm using Mac os! 

No wonder I had so much trouble! So I should be installing Ubuntu before following the instructions in the link to the BLAST tutorial? How do I go about this for Mac os?

**Comment by kubu4** [comment]
Sorry!! Misread your post above! Ignore my post. I'll help later this afternoon, if no one else has responded.

**Comment by sr320** [comment]
Not necessary to add to path to run.
Just provide the absolute path of the program.

What specifically is your "trouble"?

**Comment by kubu4** [comment]
> ...which packages from the link in the blast tutorial do I need?

For a Mac, you'd want this one:

ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.10.1+-x64-macosx.tar.gz

**Comment by sr320** [comment]
Is this complete?

**Comment by sr320** [comment]
@crmateo - this should be helpful ... https://youtu.be/i2RcnuT5DRY
