### ISSUE TITLE
Stage Geoduck Slides

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1008]
male histology (https://github.com/SamGurr/Pgenerosa_histology/tree/master/Male_hist_photos_10x) and female histology (https://github.com/shellytrigg/paper-GeoduckReproDev_pH/tree/master/data/histology/Female_Gonad/IMG/Cropped)

**Comment by shellytrigg** [comment]
@sr320 @grace-ac Kaitlyn had already staged all of these slides and here's [her notebook post](https://genefish.wordpress.com/2019/03/06/kaitlyns-notebook-20190123-geoduck-histology/) and 
[results spreadsheet](https://docs.google.com/spreadsheets/d/1ylVosCF3xVTM44xgBz8iFW01DKJdxG83DHr1mEXbFjc/edit#gid=0).

**Comment by grace-ac** [comment]
I'm getting started on this today. 

@shellytrigg did you say there are more images to stage?

**Comment by shellytrigg** [comment]
@grace-ac all the female images are now here: [https://github.com/shellytrigg/paper-GeoduckReproDev_pH/tree/master/data/histology/Female_Gonad/IMG/Originals](https://github.com/shellytrigg/paper-GeoduckReproDev_pH/tree/master/data/histology/Female_Gonad/IMG/Originals)

**Comment by shellytrigg** [comment]
the images in the directory linked in Steven's comment above are the cropped version of the originals I linked. We used the cropped images for the imageJ analysis because the dark corners of the originals were interfering with the color thresholding. I think it's fine if you use either the cropped or the original images because I bet you would get the same results.

**Comment by grace-ac** [comment]
ok cool! thanks!

**Comment by sr320** [comment]
What is the status of this?

**Comment by grace-ac** [comment]
going through males for the second time,  then starting on females today. will be done by end of day Monday 12/21

**Comment by grace-ac** [comment]
@shellytrigg : here's my notebook post with the results: https://grace-ac.github.io/geoduck_staging/ 

I have not looked at or compared the results to what Kaitlyn did, but I'd be happy to do so if it would be helpful to you! Let me know if you have any questions about what I did
