### ISSUE TITLE
Develop outline for diploid / triploid manuscript

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1014]
Determine what data we have and how it fits

(associated with this work: https://figshare.com/articles/Characterization_of_Epigenetic_and_Subcellular_Responses_to_Desiccation_Heat-Stress_Exposure_in_Diploid_and_Triploid_Pacific_Oysters/11620932)

**Comment by sr320** [comment]
@kubu4 can provide links to any data you might have here?

**Comment by kubu4** [comment]
It's all here:

https://github.com/RobertsLab/gigas_ploidy
