### ISSUE TITLE
Review Oyster manuscript

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1015]
Have a look at https://docs.google.com/document/d/1OaYNzlOJr5QibCYt8--GMNGvXlzHPR9_daCkNUVkj-U/edit 

and provide comments / suggestions

**Comment by sr320** [comment]
@mattgeorgephd you have a chance to look at this?

**Comment by mattgeorgephd** [comment]
Comments included in document. Sorry for the delay!
