### ISSUE TITLE
align salmon RNAseq data to genome

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#1016]
@kubu4 can you do the following with the Atlantic salmon RNAseq data:

raw reads directory: https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/FASTQS/RAW_data_TS_salar/
raw reads files: *P_31*.fastq.gz

1. Trim reads using default settings for Illumina adapters
2. Align trimmed reads to genome (HISAT2)
    - genome file: https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/GENOMES/v2/RefSeq/GCF_000233375.1_ICSASG_v2_genomic.fa
     - GTF: https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/GENOMES/v2/RefSeq/GCF_000233375.1_ICSASG_v2_genomic.gtf.gz
3. Run multiqc
4. Generate transcript count data (Stringtie)

Let me know if there is any other info you need to do this. I have all these files on Mox already so let me know if you want the Mox paths instead of the Gannet paths.

**Comment by kubu4** [comment]
Mox locations would be ideal.

**Comment by kubu4** [comment]
Just wanted to clarify this:

> raw reads files: P_31.fastq.gz

Should this actually be `*P_31_*.fastq.gz`?

**Comment by shellytrigg** [comment]
yes it should actually be  `*P_31_*.fastq.gz?`

mox locations: 

- Raw data:  /gscratch/srlab/strigg/data/Ssalar/FASTQS/RAW/expression_data
- Genome: /gscratch/srlab/strigg/data/Ssalar/GENOMES/chr1-29MT/GCF_000233375.1_ICSASG_v2_genomic.fa
- GTF: /gscratch/srlab/strigg/data/Ssalar/GENOMES/GCF_000233375.1_ICSASG_v2_genomic.gtf

**Comment by shellytrigg** [comment]
One thing to note is that I removed the unplaced genomic sequence form the genome file but did not remove these from the GTF file. See this post for more details: https://shellytrigg.github.io/171th-post/ . I'm not sure if this will affect anything in this analysis.

**Comment by shellytrigg** [comment]
I believe the unplaced sequences are denoted with the chromosome notation "NW_*" as opposed to "NC_*" .

**Comment by kubu4** [comment]
What is meant by "unplaced" sequence?

**Comment by shellytrigg** [comment]
"sequence found in a genome assembly that is not associated with any chromosome" 
https://www.ncbi.nlm.nih.gov/grc/help/definitions/

**Comment by sr320** [comment]
Maybe @shellytrigg you already know this... but is Chile using unplaced sequences also, what is common in the literature. One option is not including these.

**Comment by shellytrigg** [comment]
@sr320 I don't know if Chile is using unplaced sequences, but you and I discussed this back in Aug 2019 and we determined they should be removed (https://shellytrigg.github.io/171th-post/). I don't know what is common in literature but can do some looking.

**Comment by shellytrigg** [comment]
just wanted to add that Chile did not include unplaced sequences because the DEG data they shared only contained the main chromosomes

**Comment by kubu4** [comment]
> Generate transcript count data (Stringtie)

@shellytrigg Do you happen to have a specific example of how you'd like this done? Or, more to the point, what type of data are you wanting to get from StringTie (e.g. TPM, FPKM, etc?). Do you need a specific file type/format for any subsequent downstream analysis?

**Comment by kubu4** [comment]
To add to my above comment in hopes of clarifying why I'm asking.

StringTie will generate a GTF file by default and it will give TPM and FPKM, but that info will be "buried" in the final GTF field and parsing that out is kind of a pain.

Alternatively, StringTie can be run with a different option and the TPM and FPKM values will be put in their own columns.

Regardless, StringTie alone does not provide a counts of reads aligned to a given transcript. There are other programs that can do this (e.g Kalisto, Salmon, SAMtools - I think).

With all of that said, what do you want from me???!!! :smile:

**Comment by shellytrigg** [comment]
If you can produce a file with both TPM and FPKM that would be great!

I'm wanting to compare your output to the nf-core NextFlow RNAseq pipeline that I'm trying to run, which produces an output with both TPM and FPKM, [here's some example data](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20201027/results/stringtieFPKM/SRR4238351_subsampAligned.sortedByCoord.out.gene_abund.txt). I'm not sure if this output is produced through StringTie or another function(s) the pipeline calls.  If found this documentation https://nf-co.re/rnaseq/1.4.2/output#stringtie, but I'm still not entirely clear.

The downstream analysis I'm interested in doing is matching DEGs to genes that overlap with DMRs and looking for expression pattern correlations with DMR patterns (e.g. hyper or hypo methylation). If you can produce the file containing the TPM and FPKM, I think I can take care of the stats for finding DEGs.

**Comment by kubu4** [comment]
Hey @shellytrigg 

Here are the StringTie alignments results you wanted:

- [Pool26_16_gene-abund.tab](https://gannet.fish.washington.edu/Atumefaciens/20201104_ssal_RNAseq_stringtie_alignment/Pool26_16_gene-abund.tab)

- [Pool26_8_gene-abund.tab](https://gannet.fish.washington.edu/Atumefaciens/20201104_ssal_RNAseq_stringtie_alignment/Pool26_8_gene-abund.tab)

- [Pool32_16_gene-abund.tab](https://gannet.fish.washington.edu/Atumefaciens/20201104_ssal_RNAseq_stringtie_alignment/Pool32_16_gene-abund.tab)

- [Pool32_8_gene-abund.tab](https://gannet.fish.washington.edu/Atumefaciens/20201104_ssal_RNAseq_stringtie_alignment/Pool32_8_gene-abund.tab)


Here're the deets:

- tab-delimited

- FPKM is in column 8

- TPM is in column 9

- Samples were aligned to a version of the transcriptome that only included the same chromosomes used in your genome FastA.


I'll get a combined MultiQC report generated sometime today (currently have trimming and HISAT2 in separate MultiQC reports).

Since my notebook entry isn't ready yet, here's the SBATCH script used if you need/want to check things out:

```shell
#!/bin/bash
## Job Name
#SBATCH --job-name=20201104_ssal_RNAseq_stringtie_alignment
## Allocation Definition
#SBATCH --account=coenv
#SBATCH --partition=coenv
## Resources
## Nodes
#SBATCH --nodes=1
## Walltime (days-hours:minutes:seconds format)
#SBATCH --time=10-00:00:00
## Memory per node
#SBATCH --mem=200G
##turn on e-mail notification
#SBATCH --mail-type=ALL
#SBATCH --mail-user=samwhite@uw.edu
## Specify the working directory for this job
#SBATCH --chdir=/gscratch/scrubbed/samwhite/outputs/20201104_ssal_RNAseq_stringtie_alignment


### S.salar RNAseq StringTie alignment.

### Uses BAM alignment files from 20201103 and transcriptome
### GTF provided by Shelly (presumably GTF is from NCBI).


###################################################################################
# These variables need to be set by user

## Assign Variables

wd=$(pwd)

# Set number of CPUs to use
threads=27

# Input/output files
bam_dir="/gscratch/scrubbed/samwhite/outputs/20201103_ssal_RNAseq_hisat2_alignment/"
bam_md5s=bam_checksums.md5
genome="/gscratch/srlab/sam/data/S_salar/genomes/GCF_000233375.1_ICSASG_v2_genomic.fa"
gtf_md5=gtf_checksums.md5
ncbi_transcriptome="/gscratch/srlab/sam/data/S_salar/transcriptomes/GCF_000233375.1_ICSASG_v2_genomic.gtf"
chr_only_transriptome="GCF_000233375.1_ICSASG_v2_genomic_NC-chr-only.gtf"
# Paths to programs
stringtie="/gscratch/srlab/programs/stringtie-2.1.4.Linux_x86_64/stringtie"

# Programs associative array
declare -A programs_array
programs_array=(
[stringtie]="${stringtie}"
)

###################################################################################

# Exit script if any command fails
set -e

# Load Python Mox module for Python module availability
module load intel-python3_2017

# Subset transcriptome with NC_ only entries to match Shelly's genome
# Only lines beginning with "NC_"
grep "^NC_" "${ncbi_transcriptome}" >> "${chr_only_transriptome}"


# Run StringTie
for bam in "${bam_dir}"*.bam
do
  # Parse out sample name by removing all text up to and including the last period.
  sample_name_no_path=${bam##*/}
  sample_name=${sample_name_no_path%%.*}

  # Exectute StringTie
  # Use list of of chromosome IDs (ref_list)
  # Output an abundance file with TPM and FPKM data in dedicated columns
  ${programs_array[stringtie]} \
  ${bam} \
  -G ${chr_only_transriptome} \
  -A ${sample_name}_gene-abund.tab \
  -p ${threads}

  # Generate BAM MD5 checksums
  md5sum "${bam}" >> "${bam_md5s}"
done


# Generate GTF MD5 checksum
md5sum "${ncbi_transcriptome}" >> "${gtf_md5}"
md5sum "${chr_only_transriptome}" >> "${gtf_md5}"

# Capture program options
for program in "${!programs_array[@]}"
do
	{
  echo "Program options for ${program}: "
	echo ""
  # Handle samtools help menus
  if [[ "${program}" == "samtools_index" ]] \
  || [[ "${program}" == "samtools_sort" ]] \
  || [[ "${program}" == "samtools_view" ]]
  then
    ${programs_array[$program]}
  fi
	${programs_array[$program]} -h
	echo ""
	echo ""
	echo "----------------------------------------------"
	echo ""
	echo ""
} &>> program_options.log || true

  # If MultiQC is in programs_array, copy the config file to this directory.
  if [[ "${program}" == "multiqc" ]]; then
  	cp --preserve ~/.multiqc_config.yaml .
  fi
done


# Document programs in PATH (primarily for program version ID)
{
date
echo ""
echo "System PATH for $SLURM_JOB_ID"
echo ""
printf "%0.s-" {1..10}
echo "${PATH}" | tr : \\n
} >> system_path.log
```

**Comment by shellytrigg** [comment]
awesome, this is great! Thanks @kubu4 !

**Comment by kubu4** [comment]
Combined trimming (Fastp) and genome alignment (HISAT2) MultiQC report is here:

https://gannet.fish.washington.edu/Atumefaciens/20201106_ssalar_multiqc_fastp-hisat2/multiqc_report.html
