### ISSUE TITLE
Problem with rrtools install

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1018]
I thought I would post this here in the likely event this is not a rrtools issue but rather user (me) issue..

getting this message after install as per instructions `devtools::install_github("benmarwick/rrtools")`

```
* installing *source* package ‘xfun’ ...
** package ‘xfun’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘xfun’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/xfun’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/xfun’
Error: Failed to install 'rrtools' from GitHub:
  (converted from warning) installation of package ‘xfun’ had non-zero exit status
```

my gut is telling this is something Mac-specific with Command-line tools...

**Comment by shellytrigg** [comment]
how about this? https://ma.ttias.be/mac-os-xcrun-error-invalid-active-developer-path-missing-xcrun/

**Comment by sr320** [comment]
I think you are on the right track... I just have to install Xcode from the Mac App Store beforehand... downloading now.
