### ISSUE TITLE
RNA 6000 Pico Kit expiry?

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#1020]
I want to run my RNA samples on the Bioanalyzer to check the quality. I noticed that there is an unopened RNA 6000 Pico Kit received in 2019, but the quick start guide says that kits only last 4 months. Is the kit still viable? Any ideas @kubu4 ?

**Comment by kubu4** [comment]
Personally, I'd be comfortable using both of the kits (expiry dates of Feb 2020 and June 2020).

**Comment by yaaminiv** [comment]
@kubu4 Do you recommend running a blank chip (no sample) just to make sure the reagents haven't degraded? Or should I just go ahead and run samples

**Comment by kubu4** [comment]
If I were to run a test chip, I wouldn't run it blank. I'd use a couple of test RNA samples.

With that said, assuming I had plenty of my actual samples, personally, I'd just run the assay without a test assay first.
