### ISSUE TITLE
Proceed with male Cv sperm extractions? 

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#1021]
I tried checking the female Cv DNA/RNA quality on the BioAnalyzer, but couldn't get a clean DNA run + [am not sure if I can use a year-old kit for the RNA](https://github.com/RobertsLab/resources/issues/1020). @sr320 Should I still proceed with male Cv DNA/RNA extractions even though I can't check female sample quality?

**Comment by sr320** [comment]
sure - not time-critical though
