### ISSUE TITLE
Isolate RNA from hemolymph pellets

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#1022]
@kubu4 can you isolate RNA from the 6 samples listed below that are in a box on the bottom shelf of the -80C in box labeled "Hemolymph pellets for RNA isolation"

- 021 H
- 022 H
- 041 H
- 044 H
- 14H
- 15H

![PXL_20201106_160002194](https://user-images.githubusercontent.com/4720221/98389484-f8be9980-2008-11eb-8ca9-5cbddadeb5c0.jpg)

**Comment by kubu4** [comment]
Besides isolating RNA, is there anything else you want/need done (e.g. quantification, DNase, etc)?

**Comment by shellytrigg** [comment]
Yes, DNase treatment (or and method to remove the DNA) and quantification please.

**Comment by kubu4** [comment]
Alrighty, all done.

Notebook: https://robertslab.github.io/sams-notebook/2020/11/19/RNA-Isolation-and-Quantification-P.generosa-Hemocytes-from-Shelly.html

All samples were stored in the [-80<sup>o</sup>C](https://docs.google.com/spreadsheets/d/1Qsvz3QTURlPF_hX05BQxjom3484WuMfqQ1ILl9LEljU/edit#gid=2006985773) in [Shellfish RNA Box #8, slots E7 - F3](https://docs.google.com/spreadsheets/d/1ax6C-muxUTXxFEtfWdswBvueLhmxZzmwZcO2ur-0q-Q/edit#gid=1794729843).

Summary table:

| Sample | Concentration(ng/uL) | Elution_vol(uL) | Yield(ng) |
|--------|----------------------|-----------------|-----------|
| 021 H  | 176                  | 15              | 2640      |
| 022 H  | 382                  | 15              | 5730      |
| 041 H  | 102                  | 15              | 1530      |
| 044 H  | 580                  | 15              | 8700      |
| 14 H   | 194                  | 15              | 2910      |
| 15 H   | 124                  | 15              | 1860      |
