### ISSUE TITLE
Bash code chunks not executing in RMarkdown

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#1024]
Suddenly, I'm unable to run bash code chunks in RMarkdown notebooks. This seems to be the same issue that @shellytrigg encountered in the summer, and I don't know whether that was ever fully resolved?  Here's what I see in RStudio when I try to run bash code: 

![image](https://user-images.githubusercontent.com/17264765/98742936-191d8980-2364-11eb-9dc5-3841b85bd6fa.png)

The issue popped up today, then I subsequently updated both RStudio and my OS (thinking that could fix the issue), so I am now using MacOS Catalina Version 10.15.7, and RStudio Version 1.3.1093.

**Comment by shellytrigg** [comment]
@laurahspencer I was never able to resolve this issue. I am also using MacOS Catalina 10.15.7 and my bash chunks in Rmd look exactly like that, with no green arrow to execute the chunk. I am also unable to run zsh chunks in Rmd. I am able to execute commands through the terminal tab in Rstudio but not as chunks.

**Comment by kubu4** [comment]
Please post link to Rmd file. I'd like to play around a bit.

**Comment by laurahspencer** [comment]
@shellytrigg I may have found the issue - in my RStudio RMarkdown preferences, if the box "show output inline for all R Markdown documents" is NOT checked, then it doesn't let me run bash. When checked, it does!  See my current settings below. 

Oddly, for chunks that I created when that box was not checked, changing my settings does not automatically enable the code to run. But, I simply need to remove the word "bash" from curly brackets, then re-add "bash" back, and the chunk becomes executable.  

Check your preferences, and see if that fixes your issue too? 

![image](https://user-images.githubusercontent.com/17264765/98754433-8ee11f80-237b-11eb-871d-c663643dce39.png)

**Comment by laurahspencer** [comment]
Actually, any change to bash chunks will make it executable (after changing my settings)

**Comment by shellytrigg** [comment]
@laurahspencer yes that works! The green arrow appears and the bash chunks are now executable. A+ Thank you!
