### ISSUE TITLE
Removing course notes from servers

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1025]
I was informed that we had course notes visible from a past student on eagle that should not have been public. Likely never the intent of the student- but our archiving system scraped them up and must have been googleable.

I removed the directory...
https://d.pr/i/jS9fMe

but we should search to confirm the files are not elsewhere.
Interestingly they appear not to be in the original location only the archive...

**Comment by sr320** [comment]
related, I would be curious to know if we could find out what files are "popular" on our servers that might help point these things out..

**Comment by kubu4** [comment]
I'm not entirely sure I understand the issue. The `trilobite` folder is a publicly accessible folder. We can change that, if you want.

**Comment by kubu4** [comment]
To clarify., `trilobite` has always been a publicly accessible folder. This is not a recent change or anything.

**Comment by kubu4** [comment]
> course notes visible from a past student on eagle that should not have been public.

I know this isn't really the issue, but now I'm curious. Why would should course notes not have been public?

**Comment by kubu4** [comment]
Never mind about why the notes should be a problem - just saw the Slack discussion.

**Comment by kubu4** [comment]
> related, I would be curious to know if we could find out what files are "popular" on our servers that might help point these things out..

I don't think we can do this for historical access, as I believe we'd have to have configured the Apache HTTP backend to explicitly log this type of activity. I don't think this set up by default.

> but we should search to confirm the files are not elsewhere.

Similar to the Slack discussion, I'm not finding anything.
