### ISSUE TITLE
BLAST to GOslim: too many GOslim terms for the number of initial contigs...? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1028]
### Jupiter notebook: [here](https://github.com/RobertsLab/paper-tanner-crab/blob/master/notebooks/transcriptomev3.1-BLAST-to-GOslim.ipynb)      

The crab transcirptome BLAST output starts with 48,551 rows:    
![Screen Shot 2020-11-16 at 12 18 58 PM](https://user-images.githubusercontent.com/14934314/99303825-638c8380-2806-11eb-9e9c-e5022289129a.png)

After taking BLAST output to GOslim terms for biological processes, there are 198,745 total counts for the biological process GOslim terms, which is about 4x as many BLAST result rows:       
![Screen Shot 2020-11-16 at 12 19 53 PM](https://user-images.githubusercontent.com/14934314/99303840-6a1afb00-2806-11eb-8e34-6542b152d8a5.png)

### What happens in the code to get to that many more number of biological processes? 

The counts for each biological process (cell 36 in above screenshot) are used in my crab paper results in the GOslim pie and in getting the list of contains from the transcirptome that are associated with the GOslim "stress response"... and the numbers aren't making sense to me...

**Comment by kubu4** [comment]
Each row in your BLAST output likely has more than one GO term, so you'll end up with more rows than you input because each GO term for each BLAST result gets put into its own row.

**Comment by grace-ac** [comment]
ahhhh ok. that makes sense.
