### ISSUE TITLE
Troubleshooting optical signal error on BioAnalyzer

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#1029]
I ran 2 BioAnalyzer chips today and for a handful of samples, the optical signal was too high (screenshots of results below). @grace-ac and I did some digging and within the BioAnalyzer troubleshooting guide, we found one mention of this error in for the protein detection assay. The error may be associated with insufficient dilution of the ladder or samples.

@kubu4 Have you encountered this error before? I made 1:20 dilutions to run on the BioAnalyzer so the sample concentrations are less than 10 ng/µL and shouldn't bee too high. Is there something else I need to consider, or should I just dilute the samples again?

Chip 1:

![Capture](https://user-images.githubusercontent.com/22335838/99311449-7bb5d000-2811-11eb-8175-a54b57341122.PNG)
![Capture2](https://user-images.githubusercontent.com/22335838/99311452-7c4e6680-2811-11eb-8054-d0ef8f5c2518.PNG)
![Capture3](https://user-images.githubusercontent.com/22335838/99311453-7c4e6680-2811-11eb-992b-c097359d1b94.PNG)

Chip 2:

![Capture4](https://user-images.githubusercontent.com/22335838/99311456-7ce6fd00-2811-11eb-83a7-2a775c3fed65.PNG)
![Capture5](https://user-images.githubusercontent.com/22335838/99311460-7ce6fd00-2811-11eb-9026-c7aa123acba6.PNG)
![Capture6](https://user-images.githubusercontent.com/22335838/99311463-7ce6fd00-2811-11eb-8c83-1d2df0c9ebdf.PNG)

**Comment by kubu4** [comment]
I'm not entirely sure what the sample context is here, but all of the problematic samples look like they have a PCR product in them (e.g. extremely narrow peak, with very high fluorescence). It's those peaks that are the problem. Figure out how to eliminate those and you'll be good to go!

**Comment by yaaminiv** [comment]
Oh whoops! Forgot to mention that they are *C. virginica* DNA samples! I used the Zymo Microprep kit to extract DNA from gonad tissue, and made 1:20 dilutions to run on the BioAnalyzer. Where would the PCR product come from if I haven't done PCR with these samples...

**Comment by kubu4** [comment]
I didn't say there are PCR products present, just that those peaks appear similar to what one would expext to see if a sample had a PCR product present.

Many of the samples look VERY wonky; which leads me to believe maybe something went wrong with gel matrix and/or chip loading. I'd double check everything (check the syringe clip position) and try again. If it fails again, I'd prepare a new gel matrix.

**Comment by kubu4** [comment]
A couple of other things:

1. See pg. 44 of the [Agilent Bioanalyzer User Guide](https://github.com/RobertsLab/resources/blob/master/equipment_manuals/Agilent%202100-Bioanalyzer_Maintenance-Troubleshooting_USR_ENG.pdf) in regards to spikes. Basically, either the machine got bumped or the gel-dye matrix wasn't prepped correctly.

2. Are these DNA samples sheared/digested/degraded in any fashion? If not, then you shouldn't be using the High Sensitivity kit. For unaltered gDNA, you really should be using an agarose gel to evaluate size/integrity. If you want to use the Bionalyzer, you could use the DNA 12000 assay, but that only goes up to 12000bp, which should be far smaller than the DNA you'd be expecting from gDNA.

**Comment by yaaminiv** [comment]
> Are these DNA samples sheared/digested/degraded in any fashion?

They aren't. Previously, I ran my *C. gigas* DNA samples on the BioAnalyzer before sending it for WGBS, so I was trying to do the same thing with my *C. virginica* DNA. So should I use an agarose gel? Do you usually run gels every time you extract DNA to check for size/integrity before sending it for sequencing?

**Comment by kubu4** [comment]
If sending the DNA directly for WGBS no need to check size/integrity - the facility will do this. It's also highly unlikely that the DNA is degraded to a size below the desired average fragment size for library prep.

If I wanted to check size/integrity of gDNA, I would do so on an agarose gel due to the limitations of the Bioanalyzer DNA assays listed above.

**Comment by yaaminiv** [comment]
> If sending the DNA directly for WGBS no need to check size/integrity - the facility will do this. It's also highly unlikely that the DNA is degraded to a size below the desired average fragment size for library prep.

oh good to know!
