### ISSUE TITLE
subsetting a bam file

### ISSUE THREAD

**Issue by mgavery** [RobertsLab/resources#1030]
I need to subset a bam file.  I'm looking for the first 1 million mapped reads (more or less, doesn't matter).  I've tried samtools view -s, but I'm not doing it right because my output is larger and doesn't have the right header.  Does anyone have a quick way to do this?

Thanks!!

**Comment by kubu4** [comment]
I think you need this:

`samtools view -F 4 file.bam > mapped.bam`

The `-F` option does this:

- `-F INT   only include reads with none of the FLAGS in INT present [0]`

The `4` means this:

- `read unmapped (0x4)`

So, the full command above is only including reads that _do not_ have the unmapped flag set.

**Comment by kubu4** [comment]
Sorry, here's the full-fledged command you probably want (duh!):

`(samtools view -H input.bam; samtools view -F 4 input.bam  | head -1000000) | samtools view -bo output.bam`

Here's what's happening:

1. The commands surrounded by `()` do something in `bash` to allow you skip creating intermediate files (they create a subshell).

2. `samtools view -H input.bam;`: This preserves the header from the `input.bam`. This will _not_ get subsetted, but should not be an issue for any downstream tools. NOTE: The `;` in the command is important! Don't leave it out.

3. `samtools view -F 4 input.bam  | head -1000000`: From my post above, this will pull out only reads that _do not_ have the unmapped flag set. These results will get piped to the `head` command which will then grab the first 1M entries.

4. `| samtools view -bo output.bam`: This takes the output from the subshell command and compresses back to a BAM file (`-b`) and allows you to specify the name of the output file (`-o`).

**Comment by kubu4** [comment]
> I've tried samtools view -s, but I'm not doing it right because my output is larger and doesn't have the right header.

I'd like to add that it's always helpful to post the actual commands you've tried. Seeing the commands will also help clarify potentially ambiguous language (e.g. "my output is larger" - Are you referring to file size? Number of lines? Did you remember to compress the output to BAM?).

**Comment by mgavery** [comment]
mgavery$ ./samtools view -c CP1_mt.sorted.million.bam 
1000000

yay!!!!!!! Thank you!

ps I didn't do any of that header stuff or compress to bam ;). I will post my ridiculous attempt next time
