### ISSUE TITLE
Assess Hawaii oyster samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1035]
Lets fully document what we have- I believe we did a quick triage as deadline was approaching. 

Lets add information to this repo https://github.com/RobertsLab/project-oyster-oa

**Comment by kubu4** [comment]
I've added a bunch of relevant info regarding the diploid/triploid stuff.

Had forgotten about samples they sent to us in Dec. 2019. Trying to get deets from them via email.

**Comment by sr320** [comment]
For clarity -
how many different sequence data sets do we have?

**Comment by kubu4** [comment]
- 3N high pH - n=6
- 2N high pH n=6
- 3N low pH n=6
- 2N low pH n=6

**Comment by sr320** [comment]
I mean totals efforts... is there not more than 1 sequencing submission?

**Comment by kubu4** [comment]
No. You might be thinking of Ronit's stuff (which is also a ploidy comparison).

**Comment by yaaminiv** [comment]
@kubu4 Where can I find the raw data for the Hawaii samples? I want to trim the data and run it through `bismark`, but I can't find the file location on the [Nightingales spreadsheet](https://docs.google.com/spreadsheets/d/1_XqIOPVHSBVGscnjzDSWUeRL7HUHXfaHxVzec-I-8Xk/edit#gid=0).

**Comment by yaaminiv** [comment]
never mind; found it!
