### ISSUE TITLE
Lab notebook check / audit

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1038]

**Comment by shellytrigg** [comment]
some lab notebooks aren't pushing to genefish

**Comment by shellytrigg** [comment]
lab notebook back up:

- how can we best do this? 
- can it be automated?

**Comment by shellytrigg** [comment]
will address first lab meeting 2021

**Comment by kubu4** [comment]
> lab notebook back up:

> how can we best do this?
> can it be automated?

Just adding for reference. All GitHub-based notebooks are backed up regularly (daily) to Gannet, via a `git pull` command.
