### ISSUE TITLE
Trim Ronit's BS data 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1039]
For reference... https://github.com/FelixKrueger/Bismark/blob/master/Docs/README.md#ix-notes-about-different-library-types-and-commercial-kits

**Comment by kubu4** [comment]
Trimmed files are here:

https://gannet.fish.washington.edu/Atumefaciens/20201130_cgig_fastp_ronit-ploidy-wgbs/

Can be all trimmed files are labelled: `*fastp-trim*.fq.gz`

**Comment by kubu4** [comment]
@sr320 I trimmed 10bp from the 5' end of each read. Just realized that the Bismark docs suggest doing the same for 3' end, but it's not necessarily needed. Should I redo and trim 3' ends?

Sorry for not catching this earlier.

**Comment by kubu4** [comment]
Since editing the code to make this adjustment is very easy, and the job runs relatively quickly (~3hrs), I just went ahead and did another trimming with 10bp from 5'/3' ends. Will post here when complete.

**Comment by kubu4** [comment]
Updated trimming with 10bp removed from 5' and 3' ends:

https://gannet.fish.washington.edu/Atumefaciens/20201202_cgig_fastp-10bp-5-3-prime_ronit-ploidy-wgbs/

All trimmed files are labelled: `*fastp-trim*.fq.gz`
