### ISSUE TITLE
Extracting DNA/RNA from Cv sperm in seawater

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#1040]
I want to use the Zymo Microprep kit to extract DNA and RNA simultaneously from *C. virgincia* sperm samples. The sperm samples are in seawater. Based on the [kit manual](https://github.com/RobertsLab/resources/blob/master/protocols/Commercial_Protocols/ZymoResearch_quick-dna-rna_microprep_plus_kit_20190411.pdf), I assume I'd pellet the sperm cells, remove the supernatant, and proceed with adding the DNA/RNA Lysis Buffer.

@kubu4 or @grace-ac, anything to add based on your experience with the crab hemolymph samples beyond [this lab notebook post](https://robertslab.github.io/sams-notebook/2019/04/11/RNA-Isolation-and-Quantification-Crab-Hemolypmh-Using-Quick-DNA-RNA-Microprep-Plus-Kit.html)? I assume that extracting RNA from the crab samples in hemolymph may be similar to trying to extract DNA/RNA from these sperm cells in seawater!

**Comment by kubu4** [comment]
Are the samples frozen? Any sort of preservative?

My initial concern is that the cells were not pelleted _before_ freezing. Freezing generally lyses cells, which will greatly reduce your yield (if you decide to pellet the cells prior to DNA extraction).

With that being said, what is the sample volume? Are we talking 1mL of sea water or like 100uL? If the volume is small enough, you can process using the Zymo kit (see the manual for info on handling cells in liquid).

If the volume is too large, I'd do an extraction using DNAzol instead.

**Comment by yaaminiv** [comment]
> With that being said, what is the sample volume? Are we talking 1mL of sea water or like 100uL?

Sperm cells were shipped in 100 µL of seawater (no preservative). To clarify, I could follow this protocol?

<img width="1131" alt="Screen Shot 2020-11-30 at 7 55 26 AM" src="https://user-images.githubusercontent.com/22335838/100632261-7b253b00-32e1-11eb-8316-fc90b2ad3562.png">

**Comment by kubu4** [comment]
That's what I would do.
