### ISSUE TITLE
installing package MetStaT in R 4.0

### ISSUE THREAD

**Issue by emmats** [RobertsLab/resources#1042]
I'm trying to replicate @shellytrigg 's ASCA pipeline in R v. 4.0.3. It seems that MetStat cannot be installed in this current version of R. Has anyone else dealt with this? Thanks!

**Comment by sr320** [comment]
I believe Shelly used https://rud.is/rswitch/

full convo - https://d.pr/i/0ZdYaY

**Comment by emmats** [comment]
You can also get it directly from github:

#install_github is in the library devtools   
install_github("cran/MetStat")
