### ISSUE TITLE
Request to map a C. gigas RNA-Seq dataset to include mitochondrial genes

### ISSUE THREAD

**Issue by mgavery** [RobertsLab/resources#1045]
I am wondering if anyone has a C. gigas RNA-Seq dataset they've mapped to the "original" genome (GCF_000297895.1) using STAR?  I am specifically interested in where the reads are mapping on the mitochondrial genome (NC_001276.1).    If yes, would you mind subsetting the BAM to just the mito contig and sharing with me?

**Comment by kubu4** [comment]
Just want/need some clarification. Your issue title seems to be asking for help mapping data, but the content of your issue seems to be asking if we have a BAM file. 

Would you like someone over here to do some mapping? We'd be happy to.

In regards to the content of your issue, do you need/want a BAM file specifically generated by STAR? If the answer is yes, I doubt we have that. I don't think anyone has previously used STAR for RNAseq alignments in the lab.

Finally, if you are just looking for a "generic" (i.e. not software-specific) BAM file of RNAseq alignments to the NCBI _C.gigas_ mt genome, we probably have something floating around somewhere, but we'd have to poke around a bit.

**Comment by mgavery** [comment]
> Would you like someone over here to do some mapping? We'd be happy to.

Yes, I would like to request some mapping ...unless someone already has RNA-Seq data mapped to the genome 

> In regards to the content of your issue, do you need/want a BAM file specifically generated by STAR? If the answer is yes, I doubt we have that. I don't think anyone has previously used STAR for RNAseq alignments in the lab.

It doesn't have to be STAR, but does need to be an aligner that uses genome as a reference (versus transcripts only)
 
> Finally, if you are just looking for a "generic" (i.e. not software-specific) BAM file of RNAseq alignments to the NCBI _C.gigas_ mt genome, we probably have something floating around somewhere, but we'd have to poke around a bit.

Yes, that would be great! As long as it's mapped to the genome and not just genes

For context, here is my single cell data mapped to the mitochondrial genome (NC_001276.1).  I have a ton of reads mapping outside of genes.  I want to see if this peak exists in other datasets.  

Thanks!
![Pacific_oyster_scRNA-Seq_r2_-_Google_Docs](https://user-images.githubusercontent.com/4512578/101513691-52c8bc80-3931-11eb-9f8e-2d5040234575.png)

**Comment by kubu4** [comment]
Hey @mgavery . I'm set up to do the mapping, but I'm unable to find `GCF_000297895.1` version of the genome anywhere. Can you please provide a link? Preferably, an NCBI directory which would also have a corresponding GTF file.

The NCBI assembly accession `GCF_000297895.1` indicates it was "replaced" and now only seems to link to here: https://www.ncbi.nlm.nih.gov/assembly/GCF_000297895.1/

No archival versions as far as I can tell.

**Comment by kubu4** [comment]
I'll also add that the "replaced" version I linked above, as well as the NCBI "current version" (https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/297/895/GCA_000297895.1_oyster_v9/GO_TO_CURRENT_VERSION/GCA_000297895.2_ASM29789v2_genomic.fna.gz) do _not_ have any FastA headers labeled with any variation(s) of mitochondria...

**Comment by kubu4** [comment]
I found the FastA and GTF files you're working with posted in Issue #1033. Though I had seen them somewhere before. Working on mapping.

**Comment by kubu4** [comment]
Alrighty, all done! Here ya go:

- mt BAM: [https://gannet.fish.washington.edu/Atumefaciens/20201208_cgig_STAR_RNAseq-to-NCBI-GCF_000297895.1_oyster_v9/Aligned.sortedByCoord.out.NC_001276.1.bam](https://gannet.fish.washington.edu/Atumefaciens/20201208_cgig_STAR_RNAseq-to-NCBI-GCF_000297895.1_oyster_v9/Aligned.sortedByCoord.out.NC_001276.1.bam)

- mt BAM index file (for IGV): [https://gannet.fish.washington.edu/Atumefaciens/20201208_cgig_STAR_RNAseq-to-NCBI-GCF_000297895.1_oyster_v9/Aligned.sortedByCoord.out.NC_001276.1.bam.csi](https://gannet.fish.washington.edu/Atumefaciens/20201208_cgig_STAR_RNAseq-to-NCBI-GCF_000297895.1_oyster_v9/Aligned.sortedByCoord.out.NC_001276.1.bam.csi)

Notebook will be finished later this morning. I can post a link in this issue later, if you'd like. I've put the script I used to run this at the bottom of this response.

Here's IGV screencap:

![IGV screencap of C.gigas RNAseq mapped to C.gigas mt genome using STAR](https://github.com/RobertsLab/sams-notebook/blob/master/images/screencaps/20201208_cgig_STAR_RNAseq-to-NCBI-GCF_000297895.1_oyster_v9_mt_IGV.png?raw=true)

Overall, I think it looks very similar to the IGV image you posted above. Interesting.


---

SBATCH script (GitHub):

- [20201208_cgig_STAR_RNAseq-to-NCBI-GCF_000297895.1_oyster_v9.sh](https://github.com/RobertsLab/sams-notebook/blob/master/sbatch_scripts/20201208_cgig_STAR_RNAseq-to-NCBI-GCF_000297895.1_oyster_v9.sh)

```shell
#!/bin/bash
## Job Name
#SBATCH --job-name=20201208_cgig_STAR_RNAseq-to-NCBI-GCF_000297895.1_oyster_v9
## Allocation Definition
#SBATCH --account=coenv
#SBATCH --partition=coenv
## Resources
## Nodes
#SBATCH --nodes=1
## Walltime (days-hours:minutes:seconds format)
#SBATCH --time=10-00:00:00
## Memory per node
#SBATCH --mem=120G
##turn on e-mail notification
#SBATCH --mail-type=ALL
#SBATCH --mail-user=samwhite@uw.edu
## Specify the working directory for this job
#SBATCH --chdir=/gscratch/scrubbed/samwhite/outputs/20201208_cgig_STAR_RNAseq-to-NCBI-GCF_000297895.1_oyster_v9


### C.gigas RNAseq alignment to NCBI genome FastA file from Mac GCF_000297895.1_oyster_v9_genomic.fasta.
### Mackenzie Gavery asked for help to evaluate RNAseq read mappings to mt genome.


###################################################################################
# These variables need to be set by user

# Working directory
wd=$(pwd)

# Set number of CPUs to use
threads=28

# Initialize arrays
fastq_array=()

# Input/output files
fastq_checksums=fastq_checksums.md5
genome_fasta_checksum=genome_fasta_checksum.md5
gtf_checksum=gtf_checksum.md5
rnaseq_reads_dir=/gscratch/srlab/sam/data/C_gigas/RNAseq
gtf=/gscratch/srlab/sam/data/C_gigas/transcriptomes/GCF_000297895.1_oyster_v9_genomic.gtf.wl_keep_mito_v7.sorted.gtf
genome_dir=${wd}/genome_dir
genome_fasta=/gscratch/srlab/sam/data/C_gigas/genomes/GCF_000297895.1_oyster_v9_genomic.fasta

# Paths to programs
multiqc=/gscratch/srlab/programs/anaconda3/bin/multiqc
samtools="/gscratch/srlab/programs/samtools-1.10/samtools"
star=/gscratch/srlab/programs/STAR-2.7.6a/bin/Linux_x86_64_static/STAR


# Programs associative array
declare -A programs_array
programs_array=(
[multiqc]="${multiqc}" \
[samtools_index]="${samtools} index" \
[samtools_sort]="${samtools} sort" \
[samtools_view]="${samtools} view" \
[star]="${star}"
)

###################################################################################

# Exit script if any command fails
set -e

# Load Python Mox module for Python module availability
module load intel-python3_2017

# Load GCC OMP compiler. Might/not be needed for STAR
module load gcc_8.2.1-ompi_4.0.2


# Make STAR genome directory
mkdir --parents ${genome_dir}

# Populate RNAseq array
fastq_array=(${rnaseq_reads_dir}/*.fastq)

# Comma separated list required for STAR mapping
# Uses tr to change spaces between elements to commas
fastq_list=$(tr ' ' ',' <<< "${fastq_array[@]}")



# Create STAR genome indexes
# Overhang value is set to "generic" 100bp -
# this value is unknown and is the suggested default in
# STAR documentation.
${programs_array[star]} \
--runThreadN ${threads} \
--runMode genomeGenerate \
--genomeDir ${genome_dir} \
--genomeFastaFiles ${genome_fasta} \
--sjdbGTFfile ${gtf} \
--sjdbOverhang 100 \
--genomeSAindexNbases 13

# Run STAR mapping
# Sets output to sorted BAM file
${programs_array[star]} \
--runThreadN ${threads} \
--genomeDir ${genome_dir} \
--outSAMtype BAM SortedByCoordinate \
--readFilesIn ${fastq_list}

# Index BAM output file
${programs_array[samtools_index]} \
Aligned.sortedByCoord.out.bam

# Extract mt alignments
# -h: includes header
${programs_array[samtools_view]} \
--threads ${threads} \
--write-index \
-h \
Aligned.sortedByCoord.out.bam NC_001276.1 \
-o Aligned.sortedByCoord.out.NC_001276.1.bam

# Generate checksums for reference
# Uses bash string substitution to replace commas with spaces
# NOTE: do NOT quote string substitution command
for fastq in ${fastq_list//,/ }
do

	# Generate MD5 checksums for each input FastQ file
	echo "Generating MD5 checksum for ${fastq}."
	md5sum "${fastq}" >> "${fastq_checksums}"
	echo "Completed: MD5 checksum for ${fastq}."
	echo ""
done

# Run MultiQC
${programs_array[multiqc]} .

# Generate checksums for genome FastA and GTF
echo "Generating MD5 checksum for ${genome_fasta}."
md5sum "${genome_fasta}" > "${genome_fasta_checksum}"
echo "Completed: MD5 checksum for ${genome_fasta}."
echo ""

echo "Generating MD5 hecksum for ${gtf}."
md5sum "${gtf}" > "${gtf_checksum}"
echo "Completed: MD5 checksum for ${gtf}."
echo ""


# Capture program options
echo "Logging program options..."
for program in "${!programs_array[@]}"
do
	{
  echo "Program options for ${program}: "
	echo ""
  # Handle samtools help menus
  if [[ "${program}" == "samtools_index" ]] \
  || [[ "${program}" == "samtools_sort" ]] \
  || [[ "${program}" == "samtools_view" ]]
  then
    ${programs_array[$program]}
  fi
	${programs_array[$program]} -h
	echo ""
	echo ""
	echo "----------------------------------------------"
	echo ""
	echo ""
} &>> program_options.log || true

  # If MultiQC is in programs_array, copy the config file to this directory.
  if [[ "${program}" == "multiqc" ]]; then
  	cp --preserve ~/.multiqc_config.yaml multiqc_config.yaml
  fi
done

echo ""
echo "Finished logging program options."
echo ""

echo ""
echo "Logging system PATH."
# Document programs in PATH (primarily for program version ID)
{
date
echo ""
echo "System PATH for $SLURM_JOB_ID"
echo ""
printf "%0.s-" {1..10}
echo "${PATH}" | tr : \\n
} >> system_path.log

echo "Finished logging system PATH"
```

**Comment by kubu4** [comment]
Thinking about this a bit more and looking at the actual coding sequences, it seems like the mt GTF is utilizing the standard codon table to identify codons. Is that possible? Ideally, it should use the invertebrate codon table.

Here's a screencap showing the usage of TGA as a termination codon. If the invertebrate codon table was used, TGA should encode for tryptophan:

![IGV screencap showing standard stop codon usage instead of invertebrate mt tryptophan codon](https://github.com/RobertsLab/sams-notebook/blob/master/images/screencaps/20201208_cgig_STAR_RNAseq-to-NCBI-GCF_000297895.1_oyster_v9_mt_IGV_stop-codon.png?raw=true)

So, it could be possible that the translation is incorrect and might explain why there're are high regions of coverage in "non-coding" regions.

**Comment by mgavery** [comment]
Thanks so much!   What tissue is this?

I'm not sure how the codon table would affect the gtf?  Could you explain that a little more?  

I think I have to spend a little more time with this paper ([Milbury and Gaffney 2005](https://link.springer.com/article/10.1007/s10126-005-0004-0)).  It's describing C. virginica, but a lot of comparisons to gigas.  The gtf I use has been limited to protein coding genes (Cell Ranger, the 10x software, required this), but maybe these are ribosomal genes or transfer RNAs and I just lost track of them in the shuffle.  I'll need to check the original gtf.

Anywho, this is really helpful to see the similarity here.  Thank you SO much!!

**Comment by kubu4** [comment]
Tissue: mantle

In regards to codon table.

I'm wondering if the wrong codon table was used, then coding regions will be misidentified. In the example above, I highlighted a "stop codon" marked by the GTF, which is _not_ a stop codon in invertebrate mitochondria. Knowing this means that the identified coding region in the GTF is _not_ correct. That codon should encode a tryptophan and thus, the protein should be longer.

Knowing that the wrong codon table was likely used (these programs usually default to the standard, veterbrate codon table), that also means that the GTF only used AUG (ATG) as the only start codon when open reading frames were identified. I think mitochondria have more than one possible start codon.

So, I think the GTF is not indicating the proper reading frames because the software used (Cell Ranger) didn't utilize an alternative codon table for the mitochondrial sequences.

Does that help with my thought process on that?

**Comment by mgavery** [comment]
Thanks!

I see what you're saying, but I didn't think STAR/Cell Ranger was doing any "interpretation" of the gtf.  I thought these aligners were just finding reads that mapped to regions annotated as genes/exons/introns.  I would think that the kind of issue that you mention, with incorrect starts/stops, would be a problem with the annotation itself (v. the aligner)?

**Comment by kubu4** [comment]
> would be a problem with the annotation itself 

Yes! That's what I'm saying. Whatever software generated the GTF annotated is leading to an (possibly) incorrect interpretation of the alignments due to incorrect identification of open reading frames. I wasn't sure how the GTF was produced, so was thinking it was created with Cell Ranger (not familiar with that software).

Sorry, had phrased things

**Comment by mgavery** [comment]
I'm with ya!  

Just wanted to follow up with a screen shot showing all the available annotations available for the mt genomes.  This first track that ends in "toss" is stuff that didn't make it into [the Cell Ranger 'mkref' file](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/tutorial_mr) (since that had to be filtered for protein coding genes).  Looks like the peaks align with rRNA genes.  
![IGV](https://user-images.githubusercontent.com/4512578/101957034-81ef6000-3bb5-11eb-9d51-16c15da01b5c.png)

**Comment by mgavery** [comment]
here is the gtf:
[GCF_000297895.1_oyster_v9_genomic.gtf.wl_toss.gtf.zip](https://github.com/RobertsLab/resources/files/5681700/GCF_000297895.1_oyster_v9_genomic.gtf.wl_toss.gtf.zip)
