### ISSUE TITLE
Problems Building Kallisto index

### ISSUE THREAD

**Issue by afcoyle** [RobertsLab/resources#1046]
I tried building my kallisto index and ran into some issues.

First, I tried building the index with the cbai/hemat v.2.0 transcriptome, which includes both pooled libraries and individual crab. I got the following error, which is apparently thrown by the computer running out of RAM. Tried again with restarting/closing all apps, no dice:

terminate called after throwing an instance of 'std::bad_alloc'

The cbai/hemat v.3.0 transcriptome, which just includes pooled libraries, is roughly half the size of v.2.0 (920,000 kb vs 420,000 kb). I was able to build an index for it, but it did take quite some time (around 36 hours). 

Since I'll also need to build an index for the 2.0 transcriptome, any suggestions for the best method to get the computing power necessary?

Here's the code I used to build the line, taken from the kallisto manual. Didn't find any options to specify memory use - maybe that'd help?

kallisto index -i  cbai_hemat_index_v3.0.idx cbai_hemat_transcriptome_v3.0.fasta

**Comment by kubu4** [comment]
You'll need to use a better computer. We have a few available, but I'd suggest diving into using the high performance computing (HPC) cluster that we have access to. It's called Mox.

Here's our dedicated wiki with instructions on how to get access and explanations of how it's organized, how to use it, etc.:

https://github.com/RobertsLab/hyak_mox/wiki

Please let me (us) know when/if you need help working with Mox! There's definitely a learning curve, but all processing is MUCH, MUCH faster and it'll free up your personal computer!

**Comment by afcoyle** [comment]
Fantastic, thanks a bunch!

**Comment by sr320** [comment]
@afcoyle for reference what are the specs on the machine you are using?

**Comment by afcoyle** [comment]
Processor: Intel i7 (4-core)
16GB RAM
Running Windows 10 (although I've been doing most of this through WSL)
System is x64

**Comment by ocattau** [comment]
I am having the same issue as Aidan did when he was building the index and it took +36 hours. Does this mean that I cannot build an index without Mox even if I am using a brand new MacBook?

**Comment by kubu4** [comment]
Correct. Follow that link above for instructions on how to get started with Mox.

**Comment by sr320** [comment]
@afcoyle you mentioned you did this on emu ? or other bird...
where is a notebook post @ocattau might be able to look at?

**Comment by afcoyle** [comment]
Yep, I used roadrunner! Looking back, I didn't make a notebook post specifically for logging on to Roadrunner, but I think [this script would potentially be pretty helpful for creating that kallisto index!](https://github.com/afcoyle/hemat_bairdi_transcriptome/blob/main/scripts/3_1_download_libraries_run_kallisto.ipynb)

As far as actually getting on to Roadrunner, Sam made an account for me and then I just used ssh to get in!
