### ISSUE TITLE
Running TA Samples at Pt Whitney

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1049]
Ryan has samples, about a hundred
> We took samples every M/W/F from each of the 4 header tanks and weekly from each of the 16 replicate culture tanks for 8 weeks. So that comes to 96 (header tank) + 128 (culture tanks) = 224. I'm not sure we need to run all of these samples and I'd be curious to get your input on that.

What would it take to get these analyzed out at Pt Whitney in terms of time, reagents....?

AND do we have a clear protocol to follow?

**Comment by shellytrigg** [comment]
Here is an [SOP for using the titrator at Pt. Whitney](https://github.com/RobertsLab/project-geoduck-oa/blob/master/protocols/Mettler_T5_Titrator_vPW.md) and here is a [demo video of doing the pH calibration](https://drive.google.com/file/d/1F-5-ihHY50HTw-wkb0OWeeG9JgW0UI2m/view?usp=sharing) which might also help to visualize how to run the samples. 

Each run can accommodate 8 samples + 1 junk seawater sample (this goes in position 1 and protects your samples against bubbles that could get introduced into the tubing between runs, see SOP below). CRMs only need to be run once at the start of each day after calibration, and you need a total of ~120mL each day. Each run takes about 2 hours so it's possible to get 4 runs completed in one day or more depending on how long your day can be. 

For 100 samples, it would be about 3 days (~4 runs/day) and you'd need 1x 500mL bottle of CRM. I'm not sure what the current inventory is at Pt. Whitney. If there is a full bottle of HCl titrant, that should be plenty for running 100 samples. If more CRM or titrant needs to be ordered, remember that we have a credit with the Dickson lab (see below)

> Ok so you have 4 titrant bottle credits so you will pay $200/bottle
>  instead of $225/bottle for 4 titrant bottles. You have 23 CRM bottle
> credits so you will pay $33/bottle for 23 CRMs instead of
> $53/bottle.
> 
>
