### ISSUE TITLE
In vitro luciferase assay

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#105]
Lets see what it would take to get this In vitro luciferase assay going...
found 
https://www.nature.com/articles/ncomms7513

This should ultimately allow us to see how methylation impacts expression

**Comment by kubu4** [comment]
Without going in to specifics we'd need:

- a cell culture line for transfection
- a means to culture cell line (incubators, hemacytometer(s), microscope(s))
- the luciferase assay from Promega
- a means to measure luciferase output (don't know wavelength emission off-hand, but a plate reader would be needed)
