### ISSUE TITLE
Dungeness genome annotation file(s)?

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1050]
Mac mentioned that some work has been done regarding annotating the genome. Would you happen to have the annotation files stashed somewhere?

If yes, can you please tell me where I can find them?

I guess since this is really NOAA stuff, please don't post a link; just tell me a path to the files on whichever server they're on.

Thanks!

**Comment by laurahspencer** [comment]
I’ll check to see if Rebecca Maher, who was working on annotating the genome, has anything ready to go. I’ll get back to you!

**Comment by kubu4** [comment]
No need. Just figured if you had something already, I'd take a look. Thanks!

**Comment by laurahspencer** [comment]
FYI @kubu4 we now have the annotation file (.gff) for the Dungeness crab - it's on Gannet in homes/charlie/Cmagister/
