### ISSUE TITLE
Zymo index primers causing issues with read priming in Zymo Pico Methyl library prep

### ISSUE THREAD

**Issue by hputnam** [RobertsLab/resources#1054]
The primers Zymo designed for us are causing priming of read 2 to fail potentially due to adapter sequences. This results in a spike of poly G as shown by 100% GC content. Are you seeing this in any of the libraries where you used the adapters that Zymo designed for you?
![Screen Shot 2020-12-03 at 4 10 05 PM](https://user-images.githubusercontent.com/5198996/102094399-45f40f00-3df0-11eb-9039-7afa2db724a1.png)

**Comment by kubu4** [comment]
We just did a MiSeq run last week with a set of index primers using sequences provided by Zymo and things looked fine:

![Selection_140](https://user-images.githubusercontent.com/4514104/102094794-96ab3e00-3dd7-11eb-99d3-39a0fbaad1c6.png)

**Comment by hputnam** [comment]
Sorry I forgot to add it would have to be on NexSeq or NovaSeq to show the high % GC content due to the two color chemistry issue https://sequencing.qcfail.com/articles/illumina-2-colour-chemistry-can-overcall-high-confidence-g-bases/

**Comment by kubu4** [comment]
Here's a run from a NovaSeq run from Shelly did using the Zymo index primers. Looks like there's a little bit of that happening, but certainly nothing like you're seeing:

https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/analyses/20190722/multiqc_data/multiqc_report.html

![Selection_141](https://user-images.githubusercontent.com/4514104/102095618-965f7280-3dd8-11eb-87b4-f1fa2c405355.png)

**Comment by hputnam** [comment]
@kubu4 can you direct me to the primer set from that run, so I can compare it with the onese they designed for me? Thanks!

**Comment by kubu4** [comment]
It looks like you have access to the [Roberts Lab Primer Database](https://docs.google.com/spreadsheets/d/14m2kkFhxcoKWWIGoAD_7VOVsAg9wilME2UcSLqfnqLI/edit?usp=sharing), so I'll just list range of SRIDs:

- 1733 - 1717

**Comment by kubu4** [comment]
Also, here's link (PDF) to primer sequences provided by Zymo via email communication with Shelly:

https://github.com/RobertsLab/resources/blob/master/protocols/Commercial_Protocols/ZymoResearch_PicoMethylseq_IndexAlternatives.pdf

**Comment by kubu4** [comment]
@hputnam Did you ever get a response from Zymo regarding the poly G? @yaaminiv just looked at some WGBS data we received and saw the same result (Issue #1065 )
