### ISSUE TITLE
C.magister MBD-BSseq MiSeq samples failing FastQC processing?

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1055]
Hey @mgavery, would you have any insight into what's happening here? I ran FastQC on the MiSeq FastQs and some of the files failed to process:

```
Failed to process file CH01-14_S2_L001_R2_001.fastq.gz
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: Midline 'CCCCCTTTT' didn't start with '+'
--
Failed to process file CH01-38_S4_L001_R1_001.fastq.gz
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: ID line didn't start with '@'
--
Failed to process file CH03-15_S6_L001_R1_001.fastq.gz
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: Midline 'TGTCGGAAGAGCAGGAAGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTT' didn't start with '+'
--
Failed to process file CH03-04_S5_L001_R1_001.fastq.gz
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: Midline 'CCCCCGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGFFGGGGGGGG' didn't start with '+'
--
Failed to process file CH07-24_S14_L001_R1_001.fastq.gz
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: ID line didn't start with '@'
--
Failed to process file CH10-11_S20_L001_R2_001.fastq.gz
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: Midline 'GGTGAGAGGTTATCGTG8E,CFF,,CFC8E,CFFGG00-J@@F,+C,-@,,;1:2B<<,,,86+CEATTGAC,C6C8E,CFFG2B<-J@@FF,6-@,0' didn't start with '+'
--
Failed to process file CH10-11_S20_L001_R1_001.fastq.gz
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: Midline 'ACCTCCTATACGCCCACTFFG:000000000-J7M5M:1:2108:12450:2743 1:N:0:20' didn't start with '+'
```

I haven't encountered this before, but it seems to suggest that there's something wonky with the FastQ file formatting? These are the only files that were problematic. All others were processed without issue.

**Comment by mgavery** [comment]
Ugh.  I haven't seen this before either.  It's a file transfer issue. I tested CH01-14_S2_L001_R2_001.fastq.gz and I can run FastQC on the file that's on the server, but not the file on my computer.  I will download the files with issues again - this will be the "short term" (still will take a day) solution so we can run our QC and get these libraries sent out for sequencing.  I'll find a better solution in the coming weeks and get a QC'd copy of the data to you. @laurahspencer, I want to make sure you see this as well.

**Comment by laurahspencer** [comment]
Yes, I also encountered issues with these samples when I ran them through
TrimGalore yesterday. (I was going to trouble shoot today, but I’m relieved
that I don’t have to diagnose the issue!) Thanks for looping me in.

**Comment by kubu4** [comment]
@mgavery It would be killer if you could generate MD5 checksums for each file while their on NOAA servers and then generate and compare MD5 checksums after you download them to your computer to make sure they match. We'll do the same after transfer to Gannet.

Thanks and sorry!

**Comment by mgavery** [comment]
I agree. I'm in a tight spot with limited access to stuff, but trying to find a better solution.  I'll keep you both updated

**Comment by mgavery** [comment]
@laurahspencer, I think it would be good know mapping rate/bisulfite conversion rate for at least a few of the samples - just to get a general idea.  Would you mind continuing to process a few samples that don't have file issues in the meantime?

**Comment by laurahspencer** [comment]
Yep! I’ll move forward with the other samples. FYI it’s taking me longer
than I had hoped since I’m relearning how to do things on Mox, BUT I should
hopefully get Bismark to run today.

**Comment by laurahspencer** [comment]
@kubu4 did you see that Mac re-transferred the MiSeq data to Gannet?

**Comment by kubu4** [comment]
No. Thanks for the heads up. How'd you find out?

**Comment by laurahspencer** [comment]
I have my ways (email :grimacing:)
