### ISSUE TITLE
Getting raw counts for DESeq2

### ISSUE THREAD

**Issue by afcoyle** [RobertsLab/resources#1056]
I'm trying to work on a differential expression analysis. I got abundance estimations from Kallisto, then built a matrix using the Trinity abundance_estimates_to_matrix.pl script. Now I'm trying to read in the resulting matrix into R for DESeq2 analysis following this: https://github.com/sr320/nb-2019/blob/master/C_bairdi/11-Deseq2.Rmd

I keep getting an error message when running DESeqDataSetFromMatrix (line 48), as my counts aren't integers, but Kallisto isn't giving me raw integer counts - it's giving me estimated counts to 3 or 4 decimal places. Can I simply round the counts from Kallisto, or is there another course of action that'd be better?

Documentation for building matrix: https://github.com/afcoyle/hemat_bairdii_transcriptome/blob/main/Scripts/Running_Kallisto.ipynb

**Comment by kubu4** [comment]
Please post `R` code which is leading to error message.

**Comment by afcoyle** [comment]
library(DESeq2)

data <- read.table("output/kallisto_output_transcriptome_v3.0/kallisto.isoform.counts.matrix",
                              header = TRUE, sep = "\t")

names(data)[1] <- "target_ID"

rownames(data) <- data$target_ID

data <- data[,-1]

deseq2.colData <- data.frame(day = factor(c(2, 2, 0, 2, 17)),
                   temp = factor(c("Low", "High", "Amb", "All", "All")))

rownames(deseq2.colData) <- colnames(data)

deseq2.dds <- DESeqDataSetFromMatrix(countData = (data),
                                     colData = deseq2.colData,
                                     design = ~ day)

The last function - DESeqDataSetFromMatrix() - returns the following:
 Error in DESeqDataSet(se, design = design, ignoreRank) : 
  some values in assay are not integers

**Comment by kubu4** [comment]
@sr320's suggestion from Issue #943 is to round the counts to integers.

**Comment by afcoyle** [comment]
Fantastic, thanks!!
