### ISSUE TITLE
Reading in GO terms output

### ISSUE THREAD

**Issue by afcoyle** [RobertsLab/resources#1059]
I was able to pull GO terms from my accession IDs using [this script from Sam](https://github.com/RobertsLab/code/blob/master/script-box/uniprot2go.sh). However, I'm having a hard time figuring out what to do with them next. A good next step seems to be getting them into [this format](https://gannet.fish.washington.edu/Atumefaciens/20200422_cbai_DEG_basic_comparisons/D9-D12/edgeR.169728.dir/salmon.gene.counts.matrix.D12_vs_D9.edgeR.DE_results.P0.05_C1.D12-UP.subset.GOseq.enriched.flattened) so I can follow [this old script from Sam](https://robertslab.github.io/sams-notebook/2020/04/27/GO-to-GOslim-C.bairdi-Enriched-GO-Terms-from-20200422-DEGs.html) to get GOslim terms.

Assuming that's even the right way to do things, I need to read my GO terms back into R so I can match them back to their transcript IDs. However, I really can't figure out how to do that. [My GO terms are tab-separated, but each accession ID is placed at the end of the prior ID's GO terms](https://github.com/afcoyle/hemat_bairdii_transcriptome/blob/main/output/signif_accession_ids/Amb_vsLow_GO_IDs.txt). Essentially, my data looks like this: 

Accession ID1    GO_term1;GO_term2;GO_term3AccessionID2    GO_term1;GO_term2AccessionID3   GO_term1.....

I've been trying to figure out how to read it into R, but just can't figure out a way to split the text string 6 characters prior to each tab.

At its core, there are really two questions here:
1: Am I following the right path - once I have all my GO terms, is the next step reading the back into R?
2: If yes to 1, how in the heck do I do that?

Also here's a direct link to my text file in case that's easier to look at!
[Amb_vsLow_GO_IDs.txt](https://github.com/RobertsLab/resources/files/5731709/Amb_vsLow_GO_IDs.txt)

**Comment by kubu4** [comment]
@afcoyle Sorry for the hassle. I've fixed the `uniprot2go.sh` script.

It will now print properly and will be more easily readable/parsable (e.g.):

```
P58797	GO:0005737;GO:0016607;GO:0005634;GO:0003723;GO:0006406
P12345	GO:0005759;GO:0005739;GO:0005886;GO:0016212;GO:0004069;GO:0030170;GO:0006103;GO:0006531;GO:0009058;GO:0006536;GO:0006869;GO:0006457
P01400	GO:0005576;GO:0090729;GO:0009405
```

Of course, this doesn't address your other questions...

**Comment by afcoyle** [comment]
Oh fantastic - I'll re-run those accession ID terms through.

And alright, for the input file, I'll have those GO terms (i.e. the code chunk you put above), plus a file with [DESeq2 output](https://github.com/afcoyle/hemat_bairdii_transcriptome/blob/main/graphs/amb_v_low_day02/Amb_vsLow_DEGlist_wcols.txt). Columns are baseMean, log2foldchange, lfcSE, stat, pvalue, and padj. Here's a snippet (lines might be messed up, but are fine in actual file):

`baseMean	log2FoldChange	lfcSE	stat	pvalue	padj
TRINITY_DN14422_c0_g1_i18	39.653057852891	-22.2350708335868	3.86181320505028	-5.75767642114562	8.5279623976477e-09	9.50513709206038e-07
TRINITY_DN2405_c0_g1_i70	106.53029433178	-23.5792635381745	3.57017049693615	-6.60452030467725	3.98806551603211e-11	2.33911361479951e-08
TRINITY_DN48751_c1_g1_i2	140.515795104151	-23.9550609662227	3.52524296756931	-6.79529359723536	1.08092169635044e-11	1.30703070333019e-08
TRINITY_DN527_c7_g1_i18	155.792478163666	10.6733207262969	2.53711526406581	4.20687261531531	2.58928995178331e-05	0.00100037231104064
TRINITY_DN3195_c0_g1_i17	62.9789277419759	-22.8654831982992	3.92496500929215	-5.82565274955735	5.6889797480412e-09	7.68458044249401e-07
TRINITY_DN5235_c0_g2_i2	25.4059509744958	-21.6354458116496	3.81398579774792	-5.67266029790277	1.40596856385747e-08	9.76433093142601e-07
`

The goal: Get an output file of enriched GO terms that looks like [this](https://gannet.fish.washington.edu/Atumefaciens/20200422_cbai_DEG_basic_comparisons/D9-D12/edgeR.169728.dir/salmon.gene.counts.matrix.D12_vs_D9.edgeR.DE_results.P0.05_C1.D12-UP.subset.GOseq.enriched.flattened). Here's a snippet of that too:

`category	over_represented_pvalue	under_represented_pvalue	numDEInCat	numInCat	term	ontology	over_represented_FDR	gene_ids
GO:0003964	3.76867388185919e-56	1	86	241	RNA-directed_DNA_polymerase_activity	MF	6.50925352874719e-52	TRINITY_DN11983_c0_g1
GO:0003964	3.76867388185919e-56	1	86	241	RNA-directed_DNA_polymerase_activity	MF	6.50925352874719e-52	TRINITY_DN12244_c0_g1
GO:0003964	3.76867388185919e-56	1	86	241	RNA-directed_DNA_polymerase_activity	MF	6.50925352874719e-52	TRINITY_DN12348_c0_g1
GO:0003964	3.76867388185919e-56	1	86	241	RNA-directed_DNA_polymerase_activity	MF	6.50925352874719e-52	TRINITY_DN1377_c0_g1`

**Comment by kubu4** [comment]
> And alright, for the input file, I'll have those GO terms (i.e. the code chunk you put above), plus a file with DESeq2 output. 

What input file(s) do you have _now_ (i.e. don't provide "future" files as the starting files you want us to look at)?

With that said, going with what you posted above, I don't see any SwissProt IDs (SPIDs), which will be needed to get GO terms. Where are you getting SPIDs?

**Comment by afcoyle** [comment]
I believe I've already got GO terms! I cross-referenced my [DESeq2 output for DEGs](https://github.com/afcoyle/hemat_bairdii_transcriptome/blob/main/graphs/amb_v_low_day02/Amb_vsLow_DEGlist_wcols.txt) (looks like this):

```baseMean	log2FoldChange	lfcSE	stat	pvalue	padj
TRINITY_DN14422_c0_g1_i18	39.653057852891	-22.2350708335868	3.86181320505028	-5.75767642114562	8.5279623976477e-09	9.50513709206038e-07
TRINITY_DN2405_c0_g1_i70	106.53029433178	-23.5792635381745	3.57017049693615	-6.60452030467725	3.98806551603211e-11	2.33911361479951e-08
TRINITY_DN48751_c1_g1_i2	140.515795104151	-23.9550609662227	3.52524296756931	-6.79529359723536	1.08092169635044e-11	1.30703070333019e-08
TRINITY_DN527_c7_g1_i18	155.792478163666	10.6733207262969	2.53711526406581	4.20687261531531	2.58928995178331e-05	0.00100037231104064
```

with the [annotated transcriptome from Genomic Resources](https://gannet.fish.washington.edu/Atumefaciens/20200519_cbai_diamond_blastx_transcriptome_v3.0/20200518.C_bairdi.Trinity.blastx.outfmt6) (looks like this):

```TRINITY_DN88417_c0_g2_i1	sp|Q10002|APN1_CAEEL	51.5	262	125	1	595	1374	118	379	1.5e-76	288.5
TRINITY_DN88417_c0_g2_i2	sp|Q10002|APN1_CAEEL	51.5	262	125	1	542	1321	118	379	1.5e-76	288.5
TRINITY_DN88419_c0_g1_i1	sp|Q8NI99|ANGL6_HUMAN	35.1	74	38	1	8	199	394	467	8.9e-06	50.8
TRINITY_DN88462_c0_g1_i3	sp|Q26061|FRI_PACLE	75.0	60	14	1	140	319	3	61	3.5e-20	99.0
TRINITY_DN88462_c0_g1_i4	sp|Q26061|FRI_PACLE	72.2	97	26	1	8	298	4	99	2.7e-35	149.1
```

and subset the portion between the |two lines| to produce a [newline-separated file of just the accession IDs for DEGs](https://github.com/afcoyle/hemat_bairdii_transcriptome/blob/main/output/signif_accession_ids/Amb_vsLow_DEG_IDs.txt) (looks like this):
```O96647
G3V909
P02402
O66679
P42824
```
and then used that file as input into your script to [get GO terms](https://github.com/afcoyle/hemat_bairdii_transcriptome/blob/main/output/signif_accession_ids/Amb_vsLow_GO_IDs.txt), which gives me a file that looks like this:

```O96647	GO:0005840;GO:0003735;GO:0006412
G3V909	GO:0005737;GO:0005783;GO:0005794;GO:0000139;GO:0030176;GO:0016020;GO:0005634;GO:0035497;GO:0001228;GO:0003700;GO:0042802;GO:0046982;GO:0000978;GO:0000977;GO:0043565;GO:1990837;GO:0000976;GO:0031625;GO:0030968;GO:0001654;GO:0043065;GO:1903893;GO:0045944;GO:1990440;GO:0007601
P02402	GO:0005840;GO:0003735;GO:0006414
O66679	GO:0005829;GO:0008686;GO:0005525;GO:0003935;GO:0000287;GO:0030145;GO:0008270;GO:0009231
```

I suppose really, I'm a little confused about what the next stage is now that I have this file of GO terms. I assumed the next step was to get GOslim terms using GSEAbase, but upon some further thought, should I first perform an enrichment analysis using topGO or GO-MWU, and then analyze that using GSEAbase?

**Comment by kubu4** [comment]
> should I first perform an enrichment analysis using topGO or GO-MWU, and then analyze that using GSEAbase?

I'd say yes. I'll also add GOseq as an enrichment analysis option. I don't have any skin in the game in regards to which package to use, but GOseq is built-in to the Trinity pipeline, so I'm more familiar with the resulting output and how to manipulate it for downstream analysis (ie.g. GO to GOslim).

**Comment by sr320** [comment]
is this ready to close?

**Comment by afcoyle** [comment]
Yep! Still need to actually run an enrichment analysis, but the question is answered!
