### ISSUE TITLE
Create a release of your lab notebook

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#1060]
With 2020 now in the past, it's a good time to create an "end of 2020" robust archive of your lab notebook up to this point. 

For info on how to do this, see this issue from last year: https://github.com/RobertsLab/resources/issues/806

Here's an example of a release that Laura created last year: 
https://github.com/laurahspencer/LabNotebook/releases/tag/v2019

When you have created your release, please post the URL on this issue

**Comment by afcoyle** [comment]
Here's a link to mine!

https://github.com/afcoyle/afcoyle.github.io/releases/tag/v2020

**Comment by grace-ac** [comment]
Here's my notebook release link:
https://github.com/grace-ac/grace-ac.github.io/releases/tag/v2020

**Comment by yaaminiv** [comment]
https://github.com/yaaminiv/yaaminiv.github.io/releases/tag/v2020

**Comment by meganewing** [comment]
https://github.com/meganewing/meganewing.github.io/releases/tag/v2020

**Comment by kubu4** [comment]
https://github.com/RobertsLab/sams-notebook/archive/v2020.tar.gz

**Comment by shellytrigg** [comment]
https://github.com/shellytrigg/shellytrigg.github.io/releases/tag/v2020

**Comment by mattgeorgephd** [comment]
https://github.com/mattgeorgephd/mattgeorgephd.github.io/releases/tag/v2020

**Comment by sr320** [comment]
https://github.com/sr320/nb-2020/archive/v1.0.zip

https://github.com/sr320/nb-2020/archive/v1.0.tar.gz

**Comment by laurahspencer** [comment]
[https://github.com/laurahspencer/LabNotebook/releases/tag/v2021](https://github.com/laurahspencer/LabNotebook/releases/tag/v2021)

**Comment by kubu4** [comment]
I think that's everyone. Have added to https://github.com/RobertsLab/resources/wiki/Lab-Notebooks#archive
