### ISSUE TITLE
Genefish not syncing my lab notebook

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#1061]
Since I migrated my lab notebook here https://shellytrigg.github.io/notebook/ , it has no longer been syncing with Genefish and my posts no longer show up on the slack lab notebook channel. 

@sr320 is there a way to fix this?

**Comment by yaaminiv** [comment]
My posts also no longer sync with Genefish or show up on the Slack lab notebook channel, but I haven't changed my lab notebook URL (yaaminiv.github.io)

**Comment by sr320** [comment]
should be fixed now...
