### ISSUE TITLE
System for tagging papers!

### ISSUE THREAD

**Issue by afcoyle** [RobertsLab/resources#1062]
I'm currently working to set up a good organizational system using Paperpile, and would love some organizing tips for labels!

My current system is largely improv-ed, and is as follows:

- Tag each species on the genus level and a higher level (ex: looking at the impacts of hematodinium on Tanner crab would be tagged with "Syndinea", "Hematodinium", "Brachyura", and "Chionoecetes")

- Tag subject matter (ex: "Phylogeny", "Physiology")

- Tag physical parameters (ex: "Salinity", "Temperature")

- Tag study methods (ex: "Survey", "In Vitro")

It's a bit cluttered, but that might just be necessary. Anyway, if anyone has any better systems, tips, or anything else, I'd love to hear them!

**Comment by sr320** [comment]
I would venture this is the best way folks have seen to date? I simple rely on search
