### ISSUE TITLE
How to manage Google Doc notifications for personal and UW email addresses?

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1063]
Looking for some suggestions/examples of how other people do this.

I'm just realizing that I've been tagged in comments in Google Docs that have been shared with my UW email address, but I don't get any notification about these.

Do you have this problem? Do I need to turn on a setting in UW Google Docs in order to be notified?

FYI, I have all email sent to my UW email address forwarded to my personal Gmail address, but it seems like there aren't any email notifications from Docs that are shared to my UW address.

**Comment by laurahspencer** [comment]
Have you logged on to your UW Google Drive and enabled notifications?

![image](https://user-images.githubusercontent.com/17264765/104056578-95d2b580-51a5-11eb-92f4-e2c47dc127dc.png)

**Comment by kubu4** [comment]
Thanks for this. Good to double-check. I _did_ have this checked, so that's not the issue.

**Comment by kubu4** [comment]
No real solution to this. Does anyone else operate in this fashion (i.e. forward emails from UW email address to personal Gmail address)?

**Comment by kubu4** [comment]
No solution found.

**Comment by kubu4** [comment]
I think I figured out the issue. It turns out I blocked emails from `comments-noreply@docs.google.com`. I did this intentionally at some point because I was receiving spam/phishing emails from "fake" Google Docs. I have now unlbocked that email address in Gmail.
