### ISSUE TITLE
Mox disk quota exceeded

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#1064]
I'm trimming Hawaii data on Mox using [this script](https://github.com/RobertsLab/project-oyster-oa/blob/master/code/Hawes/01-trimgalore.sh). I encountered a disk quota exceeded error which stopped the job. Is there any way to get more disk space?

![Screen Shot 2021-01-07 at 11 24 30 AM](https://user-images.githubusercontent.com/22335838/103944355-5db96d00-50e8-11eb-8ee2-a946b2a08a69.png)

**Comment by kubu4** [comment]
Address the second error message you see there (regarding non-existent directory) and then re-run to see if that fixes things.

**Comment by yaaminiv** [comment]
> Address the second error message you see there (regarding non-existent directory) and then re-run to see if that fixes things.

Ah, sorry wrong screenshot! I fixed the directory paths in the script, reran, and still got the same error message:

![Screen Shot 2021-01-07 at 1 08 01 PM](https://user-images.githubusercontent.com/22335838/103945015-61012880-50e9-11eb-8dd8-f074cd19fe70.png)

**Comment by kubu4** [comment]
Is that the entirety of the slurm output? Would like to see more lines, if possible.

**Comment by yaaminiv** [comment]
> Is that the entirety of the slurm output? Would like to see more lines, if possible.

That's the end of the slurm output. Here's everything before the error:

![Screen Shot 2021-01-07 at 1 12 13 PM](https://user-images.githubusercontent.com/22335838/103945364-f7354e80-50e9-11eb-9d87-b57c1f1228fd.png)

**Comment by kubu4** [comment]
Looked into this and it looks like the `/gscratch/scrubbed` is actually over quota (which is like 200TB!). I'll delete some very large files to free up some space for you. One sec...

**Comment by kubu4** [comment]
Not sure how quickly this will update. Checking the `/gscratch/scrubbed/usage_report.txt` hasn't shown any change since I deleted some of my stuff.

I've also notified UW IT about this issue. Will report back when they respond.

**Comment by yaaminiv** [comment]
Thanks @kubu4! Is it worth running the script before you hear back from UW-IT to see if I can write out files?

**Comment by kubu4** [comment]
It certainly won't hurt anything. Worst case is that it runs for a long time, but dies before it completes everything.

**Comment by kubu4** [comment]
UW IT reply:


 
> --
> 01/08/2021 8:31 AM PST - Matt | Additional Comments
> Hi Sam,It looks like about 3 users have consumed about 90% of the available scrubbed space -- we've contacted them and > asked them to clean up.If space isn't freed up soon, we'll take more aggressive action.Thanks,-Matt
