### ISSUE TITLE
Interpreting MultiQC report for trimmed data

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#1065]
## Question: Are issues with per sequence GC content, overrepresented sequences, sequence length distributions, and per tile sequence quality scores reasons to re-trim data/not progress with `bismark` alignment?

It's been a while since I've looked at MultiQC reports for trimmed data, so I want to make sure that I didn't miss anything when reviewing the [MultiQC report for the trimmed Hawaii data](https://htmlpreview.github.io/?https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/Haws_01-trimgalore/multiqc_report_1.html) to look at sample quality post-trimming.

The per sequence GC content failed for all samples. Most samples had slight abnormalities or very unusual overrepresented sequences. All samples had slightly abnormal sequence length distributions, and most had slightly abnormal per tile sequence quality scores.

![Screen Shot 2021-01-14 at 11 32 08 AM](https://user-images.githubusercontent.com/22335838/104649274-5a366080-5669-11eb-879d-ce1af29fe70a.png)

![Screen Shot 2021-01-14 at 11 32 28 AM](https://user-images.githubusercontent.com/22335838/104649278-5b678d80-5669-11eb-8b64-30b2ea82b4c9.png)

![Screen Shot 2021-01-14 at 11 32 56 AM](https://user-images.githubusercontent.com/22335838/104649281-5b678d80-5669-11eb-9b50-0483e1427a6c.png)

![Screen Shot 2021-01-14 at 11 33 04 AM](https://user-images.githubusercontent.com/22335838/104649285-5c002400-5669-11eb-8624-b0d6e85512a7.png)

In looking at some of the [FastQC reports from Sam](https://robertslab.github.io/sams-notebook/2020/12/06/FastQC-MultiQc-C.gigas-Ploidy-pH-WGBS-Raw-Sequence-Data-from-Haws-Lab-on-Mox.html), I noticed that the per sequence GC content remained the same before and after trimming for several samples. Many of the samples with overrepresented sequences were the 2nd paired files, and had a sequence with no hit.

![Screen Shot 2021-01-14 at 2 21 41 PM](https://user-images.githubusercontent.com/22335838/104661516-85c34600-567d-11eb-893f-c55b36bc06df.png)

Per sequence GC content, sequence length distribution, and overrepresented sequences were potential problem areas with the [coral MethCompare data as well](https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200311/WGBS_MBD/FASTQC/multiqc_report.html). I also looked at my [*C. virginica* gonad methylation data MultiQC report](http://owl.fish.washington.edu/Athaliana/20180409_fastqc_Cvirginica_MBD/multiqc_data/multiqc_report.html#fastqc_adapter_content). Most samples had slightly unusual per sequence GC content and per base sequence content, and all samples had slighty unusual sequence length distribution. So is this an issue to worry about?

**Comment by hputnam** [comment]
I am working on this with Zymo now. They have asked me to upload raw data so they can try to trouble shoot. Here is my conversation with illumina about this issue. "Also, I have a suspicion about the cause of the poor/unexpected read 2 performance: in the past, I have seen similar library preparation approaches omit the first base of the adapter (the base that touches the insert sequence) on the p7 end. When the read 2 primer binds, the last base does not basepair, so we get poor synthesis from the read 2 primer. I wanted to check the primer sequences from Zymo to see if this base is missing. This base is commonly missing when libraries are prepared with TruSeq-style adapter sequences added via PCR, which is what we see in the workflow. Adding in the extra base during library prep completely rescues the read 2 performance. I can’t say for certain if this is the issue without seeing the sequences, though I think it is pretty likely. "

**Comment by laurahspencer** [comment]
I'm interested to see what ya'll find out what might have caused poly-G tails in your data.  I also have poly-G tails in my QuantSeq (aka TagSeq) libraries. Various threads online indicate that Poly-G tails may be due to diminishing signal during sequencing, which is read as a "G" in two-color sequencing systems (like what NovaSeq uses, which is what sequenced my libraries).  Based on my online research, poly-G tails seemed to not be a big issue, and therefore could simply be trimmed. 
- https://www.biostars.org/p/294612/
- https://www.biostars.org/p/359760/

**Comment by hputnam** [comment]
@laurahspencer yes, I think they can be trimmed without issue. The biggest issue for us is we are losing a substantial fraction of our reads, thus data loss and $$$$ loss.

**Comment by yaaminiv** [comment]
> The biggest issue for us is we are losing a substantial fraction of our reads, thus data loss and $$$$ loss.

How much of your data are you losing? I did some rough calculations [here](https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/Haws_01-trimgalore/trimmed-data-2/poly-G/fastqc_sequence_counts_plot-trim2v3.csv) and manually trimming the poly-G tail leads to 1-3% read loss in my samples.

> can you please send me your adapter/barcode sequences.

Here is a file with adapter sequences trimmed out of my data (obtained from `fastqc` trimming reports): https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/Haws_01-trimgalore/adapter-sequences.txt

**Comment by kubu4** [comment]
You should also consider the loss of number of bases from each read. The poly G is present after adapter removal, which indicates it's a part of the "sequence" data that you'd want. So, you're losing the equivalent number of bases from each read with that poly G sequence.

**Comment by kubu4** [comment]
Response from Zymo:

> Hi, Sam.

 

> We were looking into your question. Was it a small percentage of the reads? We checked some FastQC stats over here and observed something similar. I wonder if it has to do with the 2-channel chemistry used in the newer Illumina NovaSeq. We found this blog post describing a very similar issue, https://www.dna-ghost.com/single-post/2018/01/23/Be-careful-the-poly-G-sequence-from-NextSeq-run

 

> That would explain it. And if it is only a smaller number of reads that are affected, then trimming or filtering out should be good enough to resolve any issues.

 

> Best Regards,

> -Keith

**Comment by sr320** [comment]
resolved?

**Comment by hputnam** [comment]
Not on my end. While the NovaSeq and NextSeq systems with the 2 color chemistry show this issue, they are not ultimately responsible. Zymo is looking at the data now.
