### ISSUE TITLE
Where to put software-specific tips/tricks/usage?

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1066]
We've come across some instances of helpful info for using software, but aren't sure where to put this info so that people can find it. The [code](https://github.com/RobertsLab/code) repo?

Here are some of the examples:

- Using "snippets" in Atom text editor to autocomplete markdown-formatted text.

- Using `TrimGalore` might (usually?) require two rounds of trimming to remove all adaptor sequences.

- Putting `set -e` at the top of SLURM scripts so that a script will exit if it encounters an error.

Thoughts and suggestions are definitely welcome!

**Comment by yaaminiv** [comment]
The code repo makes sense for `trimgalore`. Maybe the hyak/mox repo for the `set -e` tip?

The "snippets" information may make sense with some other information (ie. downloading Atom, setting up Jupiter Notebooks) in the onboarding wiki

**Comment by kubu4** [comment]
Per lab meeting today, will explore using https://readthedocs.org/ as a possibility.
