### ISSUE TITLE
Update dates in Nightingales

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1075]
Pick either Submission date or receipt date and estimate for all samples and convert to common format.

**Comment by drlawson** [comment]
Can do. What is nightingales?

**Comment by kubu4** [comment]
@drlawson Send me an email (samwhite AT uw DOT edu) with your preferred email address for accessing Google Docs (some people use their UW address, but many also use their personal Gmail address) and I'll give you editing access to the Nightingales spreadsheet (which is what is referenced in this issue).

**Comment by drlawson** [comment]
Okay I'm about to start working on this project :) I was looking at the data sheet and had a couple questions. I see that some have only a submission date, some have only a receipt date, and some have neither/are missing information (such as those that only have the sequence ID). (1) Should I make a new column labeled "Date" and put the submission OR receipt date there (if the samples only have one or the other)? (2) If they have neither, should I assume that they have not been sequenced aka there is no date to be estimated? (3) Should I do anything with the rows that are missing information/appear not to have been sequenced or just leave them? Thanks! Also once I have done this should I leave the submission and receipt dates there or remove them from the datasheet?

**Comment by drlawson** [comment]
Sorry one more thing. Is there a preferred format between mm/dd/yyyy, mm/dd/yy, and yyyymmdd?

**Comment by drlawson** [comment]
Just converted all dates to common format (yyyymmdd)

**Comment by sr320** [comment]
Can you indicate that format is to be used going forward in the DMP section of handbook?

**Comment by drlawson** [comment]
yep. done :)
