### ISSUE TITLE
Write permissions for Nightingales + Google Sheet

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#1085]
@kubu4 Can I get write permissions for Nightingales on owl? I tried moving files I downloaded to Nightingales and got "Permission denied" output:

![Screen Shot 2021-01-29 at 10 54 46 AM](https://user-images.githubusercontent.com/22335838/106315640-67824c00-6220-11eb-98fd-124966077f97.png)
 
I'm also unable to edit  the [Google Sheet](https://docs.google.com/spreadsheets/d/1_XqIOPVHSBVGscnjzDSWUeRL7HUHXfaHxVzec-I-8Xk/edit#gid=0).

**Comment by kubu4** [comment]
Yes, as long as you promise to use `rsync` to transfer the files... 😄 

You should be all set.

**Comment by yaaminiv** [comment]
Done 😂 Thanks!

![Screen Shot 2021-01-29 at 11 02 29 AM](https://user-images.githubusercontent.com/22335838/106316386-7c131400-6221-11eb-9aef-a81c82f38d86.png)
