### ISSUE TITLE
Generate table describing crab RNA-seq data

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1088]
A simple table describing crab libraries.
We had a few but cannot seem to find.

Particularly ones that illustrate single crabs, repeated samples

**Comment by sr320** [comment]
taking ABC to FRP number and all qPCR data-
@grace-ac can we meet on this soon?

**Comment by afcoyle** [comment]
Been poking around post-pubathon, and found a couple possibly helpful sheets!

[This one](https://docs.google.com/spreadsheets/d/1d17yg5F5gKKC66O8QkTIlPxljJeuX7ZsG46pkBr1lNQ/edit#gid=848044428) and [this one](https://docs.google.com/spreadsheets/d/1hXMY1rg5qYNTsqvO7PXbRgM7LF06ntEp27N2Efc9gSo/edit#gid=0)

Seems like you could cross-reference them to get qPCR data plus crab ID (A/B/C) and day for most samples. However, that assumes that the last column of the latter one (qpcr_sq) is the one we want for qPCR info.

seem

**Comment by afcoyle** [comment]
Alright, a few issues (and possible solutions):

1: Looks like the order for the latter columns in the C_bairdi_RNAseq doc is pretty dang messed up (well, for the whole sheet honestly). I can't see version history, but seems worth reverting to something that makes more sense.

2. The middle 3 digits in the column with Unique IDs (6###_###_##) are probably the same as the Genewiz IDs, meaning we can just take the [existing table of those two](https://github.com/afcoyle/hemat_bairdi_transcriptome/blob/main/scripts/1_1_download_libraries_run_kallisto.ipynb) to figure out what's what. Want to get confirmation on that though first!
