### ISSUE TITLE
Send Illumina New Geoduck Tissue for Genome

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#109]
Will have to confirm with Cindy exactly where to ship and to who's attention

**Comment by sr320** [comment]
Brent suggest foot tissue is a good one for High Quality DNA

**Comment by sr320** [comment]
I take it no response from Cindy?

**Comment by kubu4** [comment]
Correct.

**Comment by sr320** [comment]
Aparna Natarajan
499 Illinois Street, Suite 210
San Francisco, CA 94158-2509

**Comment by kubu4** [comment]
Sent:
- foot
- ctenidia
- adductor muscle

Included note to try foot first

**Comment by kubu4** [comment]
Provide pulverized tissue to Illumina.

**Comment by kubu4** [comment]
Sent pulverized foot and ctendia.
