### ISSUE TITLE
Develop protocol for setting up Github Lab Notebook

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#110]

**Comment by kubu4** [comment]
Linking to this open issue so we can address them simulatneously: https://github.com/RobertsLab/onboarding/issues/1

**Comment by grace-ac** [comment]
http://owl.fish.washington.edu/scaphapoda/grace/Github-noteboook.mov

**Comment by sr320** [comment]
Done 
https://github.com/RobertsLab/onboarding/wiki/Lab-Notebooks
