### ISSUE TITLE
what are BLASTx outfmt 6 column names? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1109]
I'm googling and searching through GitHub looking for answer, but in case anyone has the quick answer: 

**What are the column names for the second and fourth columns in this BLASTx outfmt 6 file: https://gannet.fish.washington.edu/Atumefaciens/20200608_cbai_diamond_blastx_v2.1_v3.1/cbai_transcriptome_v3.1.blastx.outfmt6**

In my notebook [transcriptomev3.1-BLAST-to-GOslim.ipynb](https://github.com/RobertsLab/paper-tanner-crab/blob/master/notebooks/transcriptomev3.1-BLAST-to-GOslim.ipynb) I separate the columns by '|' so that there ends up being 14 columns in total. I found the majority of the column names from this wiki post: [here](http://www.metagenomics.wiki/tools/blast/blastn-output-format-6).

Here's the first row of that initial `blastx` output:     
```
TRINITY_DN5604_c0_g2_i1	  sp|B0KTG8|TRI1_PSEPG	30.0	360	168	12	279	1319	56	344	2.3e-28	129.0 
```

But, because of the '|' separation, 1 column (contained sp|B0KTG8|TRI1_PSEPG) became three, and I know that columns V2, uniprot_acc_id, and V4 together make up the 'sseqid' column, but I'm not sure what columns V2 and V4 are... 

| qseqid                  | V2 | uniprot_accession_id | V4         | pident | length | mismatch | gapopen | qstart | qend | sstart | send | evalue  | bitscore |
|-------------------------|----|----------------------|------------|--------|--------|----------|---------|--------|------|--------|------|---------|----------|
| TRINITY_DN5604_c0_g2_i1 | sp | B0KTG8               | TRI1_PSEPG | 30.0   | 360    | 168      | 12      | 279    | 1319 | 56     | 344  | 2.3e-28 | 129.0    |

**Comment by kubu4** [comment]
http://www.metagenomics.wiki/tools/blast/blastn-output-format-6

**Comment by kubu4** [comment]
Ha! Sorry! Same link you looked at!

**Comment by kubu4** [comment]
V2: SwissProt
V4: gene id

**Comment by grace-ac** [comment]
THANKS! that was quick!
