### ISSUE TITLE
TITRATOR: Trouble with the first steps of protocol

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#111]
So, the manual that I'm following is - [here](https://github.com/RobertsLab/resources/blob/master/equipment_manuals/CompactTitrator_Usermanual.pdf). Specifically, section 5.2.

IN SHORT: I am unsure how to get the Rondolino to respond using the touchscreen. The manual instructions at section 5.2 do not include the Rondolino. They are specific to a manual stand, which we do not have.
---------------------------------------------------------------------------------------------------

In more detail (mostly for my memory of how I tested things out):

In the very beginning, this protocol specifies using a Manual Stand, which we don't have. We have the Rondolino TTL1. 
![screen shot 2017-11-01 at 2 27 39 pm](https://user-images.githubusercontent.com/14934314/32299449-de1ca6b2-bf12-11e7-9c1d-f74eb9b94308.png)

There IS a Rondolino TTL 1 option:
![first](https://user-images.githubusercontent.com/14934314/32299475-f4ea02c2-bf12-11e7-9cca-18ac193cc46a.JPG)

After selecting it, it takes you to this screen where you select the stirrer output. There are three options and I have tried them all:
![secomd](https://user-images.githubusercontent.com/14934314/32299650-8ec8941c-bf13-11e7-9454-6ee0695a7778.JPG)

Then, to test out a response from the Rondolino, I go to the home screen > manual > sample changer:
![third](https://user-images.githubusercontent.com/14934314/32299681-b682d74c-bf13-11e7-9f00-a47bb392d733.JPG)

I notice the sample changer selected is not the Rondolino TTL 1:
![fourth](https://user-images.githubusercontent.com/14934314/32299727-e02484a6-bf13-11e7-8f14-23a04a09998b.JPG)

So I click to see the other options:
![fifth](https://user-images.githubusercontent.com/14934314/32299745-ed446912-bf13-11e7-8a0b-1bb3431fe434.JPG)

And the Rondolino is not there.

To see if maybe the other names work, I selected each of the four individually and selected "Start" to attempt to change samples, but it would always come up with this error:
![img_0009 2](https://user-images.githubusercontent.com/14934314/32299941-a79a7a86-bf14-11e7-9f7b-20abb1cbd487.JPG)

**Comment by kubu4** [comment]
Is the Rondolino turned on?

**Comment by grace-ac** [comment]
Yup! It's turned on and lifts up, and then rotates to position 0. But I can't get it to where I can control the Rondolino using the touchscreen. I see that there are options of rotating it to certain positions on the touchscreen.

But maybe I'm only supposed to use the blue buttons on top:
![img_0010 2](https://user-images.githubusercontent.com/14934314/32300486-f8fb7734-bf16-11e7-8efc-75adf9a247a1.JPG)

That just seems strange to me, though, since there's a "Sample Changer" option in the "Manual" section.

Perhaps I'm only supposed to use the touchscreen to control the stirrers and sensors...

**Comment by kubu4** [comment]
Did you follow the Operating Instructions for the Rondolino? Step #5 (pg. 4 of Operating Instructions) indicate that you have to tell the titrator that you'll be using an external stand.

Here's the [Rondolino Operating Instructions PDF](http://bikeitech.com/DATAS/es_free2/f_496e8294ef676.pdf) I used as reference. It may not be the current version, though and may differ from what was provided.

**Comment by grace-ac** [comment]
Yes I did! Here is what the manual says:
![img_0021 3](https://user-images.githubusercontent.com/14934314/32301634-ff32ee16-bf1b-11e7-882c-fb32bb218ce9.JPG)

I select Rondolino TTL
![titrationstand](https://user-images.githubusercontent.com/14934314/32301694-43356940-bf1c-11e7-80e1-f6d47b1d4ecc.JPG)

I select stirrer output:
![stirreroutput](https://user-images.githubusercontent.com/14934314/32301732-679d252a-bf1c-11e7-9616-0667b164e4b8.JPG)

I have tried each of these options:
![img_0017](https://user-images.githubusercontent.com/14934314/32301810-b521b54a-bf1c-11e7-8930-d095a4f2f79b.JPG)

And none of them seem to allow me to communicate with the Rondolino itself.

I can communicate with the stirrer connected to the titrator itself, and when I tell that to perform, the Rondolino will change. So maybe this whole issue isn't an issue. I was just under the impression that there was a way to directly control the Rondolino using the titrator touchscreen.

**Comment by grace-ac** [comment]
I just don't want to mess anything up because I know this equipment is very important!

**Comment by kubu4** [comment]
I looked at this a bit this morning and here are a couple of things:

- Titrator model is: Excellence Titrator T5
    - Knowing the above, the [excerpt from the manual you posted here](https://github.com/RobertsLab/resources/issues/111#issuecomment-341267560) doesn't apply.

- The info [I posted here](https://github.com/RobertsLab/resources/issues/111#issuecomment-341264491) says to set up the titrator as having an external stand (i.e. <em>not</em> a Rondolino TTL). Did you try that in the hardware set up options? Your screen cap of the hardware setup screen in the very first post shows this as an option.

- However, this may be a moot point, as the [excerpt from the manual you posted here](https://github.com/RobertsLab/resources/issues/111#issuecomment-341267560) and the [Rondolino Operating Instructions PDF that I posted](http://bikeitech.com/DATAS/es_free2/f_496e8294ef676.pdf) both indicate that you need to make to make these changes within a Method. This suggests that you <em>cannot</em> operate the Rondolino in manual mode.

- In section 5.2.1 of the manual excerpt [you posted above](https://github.com/RobertsLab/resources/issues/111#issue-270466706), the third bullet point has not been satisfied yet (connect a USB printer). In my brief time playing around this morning, you cannot run some methods without this (it kicks out an error message when trying to run some methods)! However, there are alternative options that might be better (e.g. PDF writer), but I don't have the time to figure out how to enable these things. Maybe this is where the LabX Software comes into play??

- Finally, the manual you linked in your first post is not the manual for our titrator model. Although the core functionalities are likely very similar (if not the same), it would be good to obtain a PDF version of a manual for our specific model (supposedly, a digital manual should have been supplied on a CD).

**Comment by grace-ac** [comment]
I deleted the incorrect manual and uploaded the correct one. The CD had multiple manuals, so I picked the wrong one. 

I will look more at the Rondolino Operating instructions PDF you posted to see what I can figure out.

I will also look into what the LabX Software is all about. 

Thank you for looking at this this morning!

**Comment by grace-ac** [comment]
Some thoughts. 
I'm wondering if we maybe have the wrong connecting cable between the Titrator and Rondolino.

We have this one:
![screen shot 2017-11-02 at 10 37 06 am](https://user-images.githubusercontent.com/14934314/32341123-d0620024-bfb9-11e7-8a75-025cdae841e9.png)


While the Manual for our Titrator has this information, which makes me think it should be connected the COM 2 (....???)
![screen shot 2017-11-02 at 10 44 53 am](https://user-images.githubusercontent.com/14934314/32341513-eb3b9b34-bfba-11e7-8b14-81181dd23dff.png)

Furthermore since our Rondolino is called a "Sample Changer" on its Manual...
![img_0034 4](https://user-images.githubusercontent.com/14934314/32341582-229bf772-bfbb-11e7-9ad1-9197d5944df7.JPG)

**Comment by grace-ac** [comment]
Another thought:
I think the [PDF you have about the Rondolino](http://bikeitech.com/DATAS/es_free2/f_496e8294ef676.pdf) is with a different titrator. 
![screen shot 2017-11-02 at 11 07 31 am](https://user-images.githubusercontent.com/14934314/32342616-25735104-bfbe-11e7-97de-ef7046436dae.png)


In the paper manual that came with the Rondolino, those instructions fall under the DL58/DL55/etc. Titrator:
![img_0035 4](https://user-images.githubusercontent.com/14934314/32342461-aabc65a4-bfbd-11e7-8ac1-d3d5d35c50cb.JPG)

I think ours might fall under the T50/T70/T90 category, because ours is a "T5"...? 
![img_0036 3](https://user-images.githubusercontent.com/14934314/32342479-b535ba62-bfbd-11e7-9166-e0e62f95f1a4.JPG)

**Comment by grace-ac** [comment]
This is what I can get it to do. I can change the amount of time it stirs, etc. The nobs on top of the Rondolino only rotate the sample changer 180˚, or it changes the settings regarding Rinsing and Conditioning. maybe this is all it does. I thought that it would rotate from position to position. 

Link to video of what it can do: https://www.youtube.com/watch?v=-JUTxx9S34g&feature=youtu.be

**Comment by grace-ac** [comment]
The protocol from Hollie includes the use of LabX software.

**Comment by grace-ac** [comment]
Final update on this issue for today: Steven is looking into seeing if Jackie knows how to use it and can show us.

**Comment by kubu4** [comment]
I'm starting to get lost on what issue you're having any more.

I mentioned this above:
>"...indicate that you need to make to make these changes within a Method. This suggests that you cannot operate the Rondolino in manual mode."

Have you tried running a Method with "External Stand" selected? Additionally, you might have an issue because this requirement has not been satisfied:
>"In section 5.2.1 of the manual excerpt you posted above, the third bullet point has not been satisfied yet (connect a USB printer)."

When I tried this earlier by using a Method and then selecting "External Stand", the titrator successfully detected the Rondolino. However, one of the methods I tried wouldn't run because there was no printer attached.

**Comment by sr320** [comment]
Big picture is titrator manual does not elude to Rondolino - and Rondolino
manual does not include instruction for our titrator.
There is some general part names that are not clear to me.

I would say though we need a printer based on manual

**Comment by kubu4** [comment]
>Big picture is titrator manual does not elude to Rondolino - and Rondolino
manual does not include instruction for our titrator.

I guess I don't see this as a problem.

>I would say though we need a printer based on manual

Based on my brief testing this morning, I agree. However, there are options listed in the various Methods to use something other than a USB printer. So, a printer might not be needed; might just need to set up a different option?

**Comment by kubu4** [comment]
A Mettler Toledo rep will be scheduling a visit to set everything up and show us how to use this thing. I'll let people know when that's happening.

**Comment by sr320** [comment]
I am going to close for now.. .in the hopes the rep comes soon. otherwise we can re-open

**Comment by kubu4** [comment]
Tentative for Monday. Waiting confirmation.
