### ISSUE TITLE
Lost on how to move through BLAST/MEGAN

### ISSUE THREAD

**Issue by afcoyle** [RobertsLab/resources#1110]
Alright, so I'm trying to filter my libraries taxonomically, and I'm pretty lost. From the chat in class today, sounds like the best plan would be to run DIAMOND BLASTx on Mox and then filter taxonomically with MEGAN6. 

First, what would my input file to BLASTx be? The transcriptome of mixed C. bairdi/Hematodinium? All pooled and individual libraries of C. bairdi/Hematodinium? If so, concatenated into a single file or separate? The libraries of C. bairdi/Hematodinium used in the downstream analyses?

Second, I just wanted to verify that I'll be able to run MEGAN6 from the command line (according to the manual, you need the paid Ultimate Edition, but it sounds like the lab generally uses the command line - figured there might be something up there)

Third, I read through the manual, but I'm unsure as to what MEGAN6 outputs, and how I get from the MEGAN6 output to something I can pseudoalign the libraries to

Any help here would be really appreciated!

**Comment by sr320** [comment]
Have you had a look  at https://www.researchsquare.com/article/rs-90268/v1 ?
I would presume @kubu4 has it laid out pretty well?

**Comment by sr320** [comment]
Might be a good SH topic.  I feel you are over-engineering here.  

You have a list of DEGs and you want to determine what subset is likely Hematodinium?

**Comment by afcoyle** [comment]
Ahh fantastic, that definitely answers the first question! I figured I'd just be running BLASTx once - it makes way more sense that I'm doing it for each individual library.

However, I'm still a bit confused on the third question. It sounds like MEGAN6 produces an .rma6 file, which can't be converted to .fastq, and kallisto only accepts .fastq files. How do I get from the output of MEGAN6 to kallisto (or some other method of alignment/pseudoalignment)?

And I totally might be! But I've got a fairly long list of enriched GO terms, and it'd be nice to see what's Hematodinium and what's not.

Basically, [here's my GO-MWU output](https://github.com/afcoyle/hemat_bairdii_transcriptome/blob/main/output/GO-MWU_output/elev0_vs_elev2_indiv/MWU_BP_elev0_vs_elev2_indiv_pvals.csv), which shows a whole bunch of GO terms at 10% FDR. I'd love to limit this enrichment analysis to only Hematodinium, but sounds like I need to do that earlier in the pipeline.

On a side note, I compared Elevated Day 0 and Elevated Day 2 individual libraries (same 3 crabs, so essentially looking at gene expression pre-exposure to warm water and post-exposure), and saw [a lot of enriched GO terms](https://github.com/afcoyle/hemat_bairdii_transcriptome/blob/main/graphs/GOMWU_output/elev0_vs_elev2_indiv.png). When I repeated that with Ambient Day 0 and Ambient Day 2 , I got [barely any enrichment](https://github.com/afcoyle/hemat_bairdii_transcriptome/blob/main/graphs/GOMWU_output/amb0_vs_amb2_indiv.png). So it does seem like something neat is going on!

**Comment by kubu4** [comment]
> However, I'm still a bit confused on the third question. It sounds like MEGAN6 produces an .rma6 file, which can't be converted to .fastq, and kallisto only accepts .fastq files. How do I get from the output of MEGAN6 to kallisto (or some other method of alignment/pseudoalignment)?


Here's how to get from DIAMOND BLASTx to RMA6:

https://robertslab.github.io/sams-notebook/2020/03/18/Transcriptome-Annotation-C.bairdi-Using-DIAMOND-BLASTx-on-Mox-and-MEGAN6-Meganizer-on-swoose.html

---

Here's how to get from FastQ from RMA6:

https://robertslab.github.io/sams-notebook/2020/03/30/RNAseq-Reads-Extractions-C.bairdi-Taxonomic-Reads-Extractions-with-MEGAN6-on-swoose.html

---

Here's how to get the taxonomic-specific reads from FastQs (use these for RNAseq analysis):

https://robertslab.github.io/sams-notebook/2020/04/13/Data-Wrangling-Arthropoda-and-Alveolata-Day-and-Treatment-Taxonomic-RNAseq-FastQ-Extractions.html

**Comment by afcoyle** [comment]
Fantastic, thanks so much for the help!
