### ISSUE TITLE
ID DNA methylation machinery in Geoduck genome

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1116]
in other words identify homologs in geoduck genome.

Here is a list if helpful

Gene
--
dnmt1
dnmt3a
dnmt3b
dnmt3l
mbd1
mbd2
mbd3
mbd4
mbd5
mbd6
mecp2
Baz2a
Baz2b
UHRF1
UHRF2
Kaiso
zbtb4
zbtb38b
zfp57
klf4
egr1
wt1
ctcf
tet1
tet2
tet3

also https://d.pr/i/GoW7ux

**Comment by kubu4** [comment]
Any SP IDs available?

**Comment by sr320** [comment]
no

**Comment by kubu4** [comment]
Do these gene names correspond to SP entries?

**Comment by sr320** [comment]
very likely there are human and mouse SP entries with these names.


One option might be looking at complete genome of closely related taxa,
scrape those sequences based on these IDs, and using blast to find
homologs..

There might be some form of "homolog" finder. I know NCBI has
https://www.ncbi.nlm.nih.gov/homologene

**Comment by kubu4** [comment]
Also, what format are you looking for? GFF? Just list of geoduck gene IDs? SP IDs?

I can pull out genes very easily from GFF using that gene ID list.

**Comment by sr320** [comment]
geoduck gene IDs.
for the paper we want to describe the completeness / lack of completeness
we have in the genome concerning the genes involved in DNA methylation.
Ultimately I imagine a supplemental table in the manuscript.

**Comment by shellytrigg** [comment]
I'm wondering if we can just grep the gene names from this file [https://osf.io/4etsu/](https://osf.io/4etsu/) ?

**Comment by kubu4** [comment]
Yes, that's what my plan is/was.

**Comment by kubu4** [comment]
Here's a list of IDs which match that list:
PGEN_.00g104080
PGEN_.00g104170
PGEN_.00g116950
PGEN_.00g186870
PGEN_.00g192900
PGEN_.00g202750
PGEN_.00g209890
PGEN_.00g209900
PGEN_.00g243700
PGEN_.00g249090
PGEN_.00g283000
PGEN_.00g283010

And, here's the list of genes from the supplied list that _don't_ have any matches:

dnmt1
dnmt3a
dnmt3b
dnmt3l
mbd1
mbd2
mbd3
mbd4
mbd5
mbd6
mecp2
Baz2a
Baz2b
UHRF1
UHRF2
Kaiso
zbtb4
zbtb38b
zfp57
klf4
egr1
wt1
ctcf
tet1
tet2
tet3

Here's how I pulled these out:

Pull out matches:

```bash
while read -r line; do grep -i "|${line}" Panopea-generosa-vv0.74.a4.gene.gff3 | awk -F'[=;]' '{print $2}'; done < ../../data/P_generosa/20210219_methylation_list.txt | sort -u
```

No matches in GFF:

```bash
while read -r line; do if grep -ivq "|${line}" Panopea-generosa-vv0.74.a4.gene.gff3; then echo "${line}"; fi; done < ../../data/P_generosa/20210219_methylation_list.txt
```

I'll post a notebook entry later.

GFF is here: 

https://gannet.fish.washington.edu/Atumefaciens/20190928_Pgenerosa_v074.a4_gensas_annotation/Panopea-generosa-vv0.74.a4.gene.gff3

**Comment by sr320** [comment]
Can you please create a table with Geoduck gene, blast hit, and evalue?

**Comment by kubu4** [comment]
I've included both types of BLAST that were run on the data (BLASTp and DIAMOND BLAST). Do you want a spreadsheet instead/in-addition-to what's pasted below?

| Gene_ID         | BLASTp_evalue | DIAMOND_evalue |
|-----------------|---------------|----------------|
| PGEN_.00g104080 | 1.05E-98      | 5.40E-102      |
| PGEN_.00g104170 | 3.09E-96      | 1.20E-109      |
| PGEN_.00g116950 | 6.40E-21      | 2.80E-20       |
| PGEN_.00g186870 | 1.25E-116     |                |
| PGEN_.00g192900 | 2.32E-19      |                |
| PGEN_.00g202750 | 9.46E-82      | 2.60E-63       |
| PGEN_.00g209890 | 4.37E-19      | 9.20E-09       |
| PGEN_.00g209900 | 3.14E-32      | 8.00E-29       |
| PGEN_.00g243700 | 6.24E-58      | 2.20E-23       |
| PGEN_.00g249090 | 4.19E-18      | 2.60E-06       |
| PGEN_.00g283000 | 5.03E-10      |                |
| PGEN_.00g283010 | 0             | 7.30E-224      |

**Comment by sr320** [comment]
The gene ID (tophit?) also needs to be included - that corresponds to the initial gene list.

**Comment by kubu4** [comment]
The methylation machinery homolog?

**Comment by sr320** [comment]
Yes - but specifically what the evalues correspond to.

**Comment by kubu4** [comment]
Yep. Just wanted clarification on "gene ID" definition. Will do.

**Comment by kubu4** [comment]
Sorry for delay on this.



Updated table:

| Gene_ID         | gene_name | BLASTp_evalue | DIAMOND_evalue |
|-----------------|-----------|---------------|----------------|
| PGEN_.00g104080 | Baz2b     | 1.05E-98      | 5.40E-102      |
| PGEN_.00g104170 | Baz2b     | 3.09E-96      | 1.20E-109      |
| PGEN_.00g116950 | mbd5      | 6.40E-21      | 2.80E-20       |
| PGEN_.00g186870 | ctcf      | 1.25E-116     |                |
| PGEN_.00g192900 | UHRF1     | 2.32E-19      |                |
| PGEN_.00g202750 | mbd2      | 9.46E-82      | 2.60E-63       |
| PGEN_.00g209890 | mbd2      | 4.37E-19      | 9.20E-09       |
| PGEN_.00g209900 | mbd4      | 3.14E-32      | 8.00E-29       |
| PGEN_.00g243700 | egr1      | 6.24E-58      | 2.20E-23       |
| PGEN_.00g249090 | egr1      | 4.19E-18      | 2.60E-06       |
| PGEN_.00g283000 | dnmt1     | 5.03E-10      | 8.20E-28       |
| PGEN_.00g283010 | dnmt1     | 0             | 7.30E-224      |


Tab-delimited, if this is easier to transfer somewhere else:

```
gene_ID          gene_name  BLASTp_evalue  DIAMOND_evalue
PGEN_.00g104080  Baz2b      1.05e-98       5.4e-102
PGEN_.00g104170  Baz2b      3.09e-96       1.2e-109
PGEN_.00g116950  mbd5       6.40e-21       2.8e-20
PGEN_.00g186870  ctcf       1.25e-116
PGEN_.00g192900  UHRF1      2.32e-19
PGEN_.00g202750  mbd2       9.46e-82       2.6e-63
PGEN_.00g209890  mbd2       4.37e-19       9.2e-09
PGEN_.00g209900  mbd4       3.14e-32       8.0e-29
PGEN_.00g243700  egr1       6.24e-58       2.2e-23
PGEN_.00g249090  egr1       4.19e-18       2.6e-06
PGEN_.00g283000  dnmt1      5.03e-10
PGEN_.00g283010  dnmt1      0.0            7.3e-224
```

**Comment by shellytrigg** [comment]
Nice @kubu4 ! What about DNMT3a and DNMT3b? 

![Screen Shot 2021-02-25 at 9 33 30 AM](https://user-images.githubusercontent.com/4720221/109327872-a8fd1b80-780d-11eb-88a2-264ac79ef1de.png)

**Comment by kubu4** [comment]
Bottom of the list above, but I'll check out what you have there. Thanks.

**Comment by kubu4** [comment]
Also, I used the list provided in the first post, so that probably explains the difference between what you saw.

@sr320 and @shellytrigg Do you want me to do a bit of a "fuzzy" search, and re-run excluding the variants (e.g. search for `dnmt` instead of `dnmt1`)?

**Comment by kubu4** [comment]
Hmm, never mind my comment immediately above this. I'll investigate and report back.

**Comment by shellytrigg** [comment]
Human homolog Uniprot IDs

P26358
Q9Y6K1
Q9UBC3
Q9UJW3
Q9UIS9
Q9UBB5
O95983
O95243
Q9P267
Q96DN6
P51608
Q9UIF9
Q9UIF8
Q96T88
Q96PU4
Q86T24
Q9P1Z0
Q8NAP3
Q9NU63
O43474
P18146
P19544
Q8NI51
Q8NFU7
Q6N021
O43151

**Comment by shellytrigg** [comment]
https://github.com/hputnam/Geoduck_Meth/issues/16

**Comment by kubu4** [comment]
Per Pub-a-Thon today, have decided that we will drop this from paper, due to lack of need (i.e. annotated list of genes is available to anyone who wants to search through them) and incomplete genome.
