### ISSUE TITLE
Run Blobtools on geoduck genome

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1118]
https://blobtoolkit.genomehubs.org

**Comment by sr320** [comment]
Status?

**Comment by kubu4** [comment]
Working on this at the moment, actually. Hopefully have something running tomorrow. They suggested I use the newest version of the pipeline (which is more modular), however, that modularity altered the way in which you have to organize input/output directories compared to how it was setup before.

With that said, the developers think I shouldn't have any of the issues I had before (namely, dealing with the fact that Hyak does not have an internet connection) once I get my script setup to generate, and move between, the new required directory structures for the pipeline.

**Comment by kubu4** [comment]
Update: 

Remarkably, this has been running without issue all day! Received a lot of great help from the developer to _finally_ get this running! With that said, it's definitely going to take a while to run (days - weeks)...

P.S. I probably just jinxed it by making this comment.

**Comment by kubu4** [comment]
The current pipeline run died yesterday at the BUSCO step. Have submitted issue to BlobToolKit GitHub page.

**Comment by kubu4** [comment]
BUSCO issue has been addressed by developer (https://github.com/blobtoolkit/pipeline/issues/16). Making recommended changes/installations and getting ready to run again.

**Comment by kubu4** [comment]
Got two additional issues resolved quickly and the pipeline has successfully completed!

Now, to try to remember how to use BlobTools for actually viewing the results...

**Comment by kubu4** [comment]
Viewing is happening! Getting closer...

![image](https://user-images.githubusercontent.com/4514104/128205090-7cb714e1-1a59-4bed-aa8f-6b0641fe9092.png)
