### ISSUE TITLE
Provide new Cg genome

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#1119]
@sr320 Where can I find the revised Cg genome? I'd like to try aligning my WGBS to it

**Comment by sr320** [comment]
https://www.ncbi.nlm.nih.gov/assembly/GCF_902806645.1

**Comment by sr320** [comment]
@mgavery might be able to provide more insight into exactly what file she is using

**Comment by mgavery** [comment]
I'm not using the latest that you referenced above, Steven.  The analysis started prior to this release so I'm still on the old genome.  ..as a note, I don't see the mitochondria in the new roslin genome (maybe I missed it though), so you might want to check and add that if you're interested in mapping there.

**Comment by sr320** [comment]
full list https://www.ncbi.nlm.nih.gov/assembly/organism/29159/all/

**Comment by yaaminiv** [comment]
@sr320 Did you say you aligned Ronit's data to the Roslin genome? Is there already a bisulfite-converted genome somewhere on gannet/mox?

**Comment by sr320** [comment]
I have one at `/gscratch/srlab/sr320/data/Cgig-genome/roslin`

**Comment by yaaminiv** [comment]
Roslin genome + mitochondrial sequence: https://gannet.fish.washington.edu/spartina/project-oyster-oa/Haws/data/cgigas_uk_roslin_v1_genomic-mito.fa
