### ISSUE TITLE
Need chemicals for histology fixation

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#112]
2 boxes of PAXgene tissue fixative containers. Last time we ordered this it cost $298.68/box; however it currently is listed for $200/box on [PreAnalytix's site](https://www.preanalytix.com/products/tissue/fixation-stabilization/paxgene-tissue-fix-container)

We might also need the Stabilizer; I don't see any listed on our inventory or chemical sheet, but we might have a bottle or two left from previous kits.  @grace-ac, do you know how many bottles we still have, if any?

Fixative info: 
![PAXgene tissue fix kit](https://cloud.githubusercontent.com/assets/14934314/22384223/3dde0aee-e482-11e6-9ac3-9b38e58c7bc4.JPG)

**Comment by kubu4** [comment]
Please see Purchasing section on Resources wiki for placing orders. Thanks!

**Comment by laurahspencer** [comment]
roger that, thanks!

**Comment by sr320** [comment]
@grace-ac can you please coordinate purchasing of this?

**Comment by grace-ac** [comment]
Just want to check: @laurahspencer did you do anything for this? I see that sam asked you to look at the purchasing protocol.

**Comment by laurahspencer** [comment]
I have not. Let me know if you have questions - thanks!

**Comment by grace-ac** [comment]
We have four unused bottles of the Stabilizer. 

The [Roberts Lab Inventory](https://docs.google.com/spreadsheets/d/11RA_mlLB-3m_GySnTTuDazDdOi0bCxJu2VERuX9Qfx8/edit#gid=486596965) sheet has several tabs at the bottom. The tab labeled "Shelf Rm 213" lists what's on the shelf to the left of the door. There is a box of Stabilizer on that shelf. I labeled it with sharpie what's inside to make it easier! :)

**Comment by laurahspencer** [comment]
Aha! Tabs!

**Comment by grace-ac** [comment]
Is the unit cost for one box $190.95? That's what it says on the [Purchasing log](https://docs.google.com/spreadsheets/d/1DHXiiEzWhh0XHnEMvKz4TX10e69ErOWHv5Jo-ouk6x8/edit#gid=0) from the last time it was purchased on 1/30/17.

**Comment by laurahspencer** [comment]
The cost for a box of 10 fixative containers listed online is ~$200, https://www.preanalytix.com/products/tissue/fixation-stabilization/paxgene-tissue-fix-container

**Comment by grace-ac** [comment]
budget number @sr320 ?
