### ISSUE TITLE
Confirm stats in Table2 in Geoduck Genome paper are correct

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#1122]
@kubu4 can you please confirm the numbers in Table 2 in the [geoduck genome ms](https://docs.google.com/document/d/10Wmr_ceODWreZfS8WPekvoBwD2xEqlq28iSitapHTHA/edit?ts=60267367) are correct?

Or should they match the numbers listed here [https://github.com/RobertsLab/code/blob/master/notebooks/sam/20191203_swoose_pgen_v074.a4_genome_feature_counts.ipynb](https://github.com/RobertsLab/code/blob/master/notebooks/sam/20191203_swoose_pgen_v074.a4_genome_feature_counts.ipynb)?

**Comment by kubu4** [comment]
They do not look correct in the manuscript. Will change.
