### ISSUE TITLE
Get WG reseq quote for oysters

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1124]
See what it cost to do a wg reseq on the haws samples...

**Comment by yaaminiv** [comment]
For how many samples? 24 samples were used for WGBS, but I don't think there's any left from those

**Comment by yaaminiv** [comment]
@kubu4 To confirm, did you send all of the Cg Hawaii ctenidia you extracted for WGBS?

**Comment by kubu4** [comment]
I can check, but I interpreted this issue as meaning "ask Zymo to perform additional sequencing on the existing libraries."

As such, I've confirmed that they still have the libraries. We just need to decided on the number of reads we'd like per sample and then get an official quote.

@sr320, is this what you had in mind or did you want to have new libraries made from the same samples and subsequently sequenced?

**Comment by yaaminiv** [comment]
>  I interpreted this issue as meaning "ask Zymo to perform additional sequencing on the existing libraries."

@kubu4 Are these bisulfite-converted libraries, or is this the DNA before bisulfite conversion? Additional sequencing on the existing libraries would work well as long as they're not bisulfite-converted!

**Comment by kubu4** [comment]
Ah! Gotcha! I saw the "reseq" and thought the idea was to just re-sequence them.

They are bisulfite sequencing libraries, so no go.

I'll look at my notebook regarding remaining DNA and report back.

**Comment by kubu4** [comment]
There's DNA leftover from all but one sample. 

Here's how much of each sample was used for WGBS:

https://robertslab.github.io/sams-notebook/2020/08/24/Sample-Submitted-C.gigas-Diploid-Triploid-pH-Treatments-Ctenidia-to-ZymoResearch-for-WGBS.html

Here's how much was isolated initially:

https://robertslab.github.io/sams-notebook/2020/08/21/DNA-Isolation-and-Quantification-C.gigas-High-Low-pH-Triploid-and-Diploid-Ctenidia.html

Here's the primary sample sheet:

https://drive.google.com/file/d/1wd0iHe78s_1u7NYa9HUlRIOX59QpAtXA/view

The ctenidia for a given sample was used in its entirety for DNA isolation.

**Comment by yaaminiv** [comment]
Sample concentrations: 24 samples sequenced for WGBS. Of those samples, 18 have at least 1000 ng of DNA remaining. Three samples have 280 ng, 600 ng, and 780 ng of DNA. 2 samples do not have any DNA left

UW: To sequence prepare and sequence these 22 samples to a minimum of 30x, it would be ~$9,475. 

Genewiz: Hasn't provided a quote, working on getting one.

**Comment by sr320** [comment]
@yaaminiv are we moving on this?

**Comment by yaaminiv** [comment]
I'm waiting on a quote from Genewiz. Will follow up today unless you want to move forward with UW quote.
