### ISSUE TITLE
ID and purchase UV bulb for PCR Stattion

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#113]

**Comment by sr320** [comment]
@grace-ac can you please order?

**Comment by grace-ac** [comment]
Should I have Lisa order directly from the company?

or is from something like this ok:
https://www.soslightbulbs.com/product/light-bulbs/uv-germicidal/germicidal-bulbs/sankyo-denki-g15t8-15w-18-uv-germicidal-lamp/ 

The above link was the top google search result of the product.

**Comment by sr320** [comment]
Is it available from a uw preferred vendor?

**Comment by kubu4** [comment]
I don't think so. Grainger has it, but only in packs of 24.

**Comment by sr320** [comment]
@grace-ac - your call then 👍

**Comment by grace-ac** [comment]
budget number @sr320 ?

**Comment by sr320** [comment]
61-0221
