### ISSUE TITLE
bleach or ethanol rinse on sonicator between  uses?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1131]
I'll be using sonicator on oyster larvae. between samples, should i rinse of tip of sonicator with a 10% bleach solution or ethanol? or something else?

**Comment by kubu4** [comment]
Wipe off sonicator "horn" with lab tissue, then soak in 10% bleach solution for a few minutes, then rinse thoroughly with distilled water.

**Comment by grace-ac** [comment]
cool! thanks!
