### ISSUE TITLE
Location of animal bitmaps

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#114]
@kubu4 you compiled a bunch of organism graphics we were going to use for NGS discovery...
I saw them recently but cannot recall where. I would like to use some for Mac's paper.

Do recall where they live?

**Comment by kubu4** [comment]
Eagle/photo/Taxa_SVG_Images

**Comment by sr320** [comment]
Thanks!
now also 
https://drive.google.com/drive/u/0/folders/1p0wRJK0eser8hqeY4qdJ2fUZoadtjsDg
