### ISSUE TITLE
Get Hawaii Cg sample distribution in sequencing lanes

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#1142]
@kubu4 Do you know how many libraries were pooled into sequencing lanes for the Hawaii data, how many sequencing lanes there were, and what sequencer was used?

**Comment by kubu4** [comment]
Single lane, single flowcell on NovaSeq.

FYI, sequencer info is in Nightingales.

Number of flowcells, lanes (if not indicated in the filename - which it is _not_ for Zymo samples) can be found like this:

```bash
for fastq in *.fq.gz
do
  zcat ${fastq} \
  | grep '@' \
  | awk -F ":" '{print $3, " " , $4}'
done \
| sort -u
```

The code above pulls out the header line from each FastQ (designated by `@`) and then pulls out the flowcell ID and lane number (fields 3 and 4, respectively). Then, it sorts unique lines. If there are multiple flowcell IDs and/or multiple lanes, then the samples were sequenced across multiple flowcells and/or lanes.

**Comment by kubu4** [comment]
> FYI,

Sorry, after reading this, I think the usage of this could come off as condescending. That was not my intention!

**Comment by yaaminiv** [comment]
Did not come off that way at all! I always forget about the Nightingales spreadsheet, so thanks for the reminder!
