### ISSUE TITLE
Help using `sed` to replace fasta headers

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#1147]
I've concatenated the Oly genome contigs into 30 large contigs, and now want to change the headers to include just the start and end contig (e.g. >Contig0:Contig5000). I have code to generate new headers, but am having difficulty with `sed` to actually replace them in the fasta. Here's the error I get for each attempted header replacement: 

```
sed: 1: "s|> Contig0 Contig1 Con ...": unterminated substitute pattern
sed: 1: "s|>Contig5314 Contig531 ...": unterminated substitute pattern
sed: 1: "s|>Contig11179 Contig11 ...": unterminated substitute pattern
sed: 1: "s|>Contig21263 Contig21 ...": unterminated substitute pattern
(etc.)
``` 
To trouble shoot, I've extracted the headers from the original fasta and the concatenated fasta:

[Olurida_v081_concat2_headers.txt](https://github.com/RobertsLab/resources/files/6126142/Olurida_v081_concat2_headers.txt)
[Olurida_v081_headers.txt](https://github.com/RobertsLab/resources/files/6126140/Olurida_v081_headers.txt)

And here is the code. Anyone have any ideas how to fix the `sed` line? You can view the old and new header names generated in the for-loop by un-commenting out "echo $old" and "echo $new". 

```
%%bash 

# Edit fasta in place. 
# Note: This script assumes contigs are numerically sorted 

n_contigs_old=$(grep ">" Olurida_v081_headers.txt | wc -l) #number of contigs in original fasta 
d="${n_contigs_old//[^[:digit:]]/}" #Return ID of last/highest number contig
digits=$(echo ${#d}) #number of digits in the last contig
n_contigs_new=$(grep ">" Olurida_v081_concat2_headers.txt | wc -l) #number of contigs in concatenated genome
n=$(seq 1 1 $n_contigs_new) #vector of 1:# of contigs in concat. genome

# loop over each new contig header, paste first and last ID # together and replace concat header with new ID 
for i in $n
do
old=$(grep ">" Olurida_v081_concat2_headers.txt | sed "${i}q;d")
start=$(echo $old | grep -o -E '[0-9]{1,6}' | head -n 1) #If needed, change the 6 to match the value in $digits 
end=$(echo $old | grep -o -E '[0-9]{1,6}' | tail -n 1) #If needed, change the 6 to match the value in $digits 
new=$(echo ">Contig"$start":"$end)
sed -i -n "s|$old|$new|" Olurida_v081_concat2_headers.txt
#echo $old
#echo $new
done
```

**Comment by kubu4** [comment]
Here's a notebook entry where I've done it :

https://nbviewer.jupyter.org/github/RobertsLab/code/blob/master/notebooks/sam/20191105_swoose_pgen_v074_renaming.ipynb#Change-scaffold-names-and-file-names

Basically, use FastA index file as source of FastA header info.

Then do a bunch of "fancy" stuff with another array and pipe output of loop to `sed` using a special "file" (which doesn't really exist).

My example also loops through a bunch of different file types, so you can ignore that element of things.

If you have questions (which is likely), just post 'em here!

**Comment by kubu4** [comment]
Oh, and my usage does _not_ utilize the "edit-in-place" abilities of `sed`, as this "breaks" the ability to trace changes to a file. I'd recommend writing to a new file with a modified name which provides some indication of difference between original source file and the new one you end up creating.

**Comment by kubu4** [comment]
Can you share the FastA and FastA index file when you have the chance so we can test things?

**Comment by kubu4** [comment]
Also, can you please provide an example of your desired output?

I don't really follow this:

> now want to change the headers to include just the start and end contig (e.g. >Contig0:Contig5000)

**Comment by laurahspencer** [comment]
Thanks for pointing me to your script- I should have checked with you earlier!  Since I invested so much energy to write this script, I decided to trouble shoot. I have a script that is now working - it required me to remove all the spaces in the fasta headers first, since that was an issue (I actually remove all horizontal spaces, but it's easiest to just remove all from the file). 

My headers looked like this: 
`> Contig0 Contig1 Contig2 Contig3 Contig4 Contig5 Contig6 Contig7 Contig8 Contig9 Contig10 Contig11 Contig12 Contig13 Contig14 Contig15 Contig16 Contig17 Contig18 Contig19 Contig20`.  
But I wanted them to look like this: `>Contig0:Contig20`. 

Here is the script I'm using to concatenate the contigs with N1000 added between each: 

`! awk -v i=5314 -f merge_contigs.awk.txt Olurida_v081.fa > Olurida_v081_concat.fa`

Where i=the # of contigs to paste together, and "merge_contig.awk.txt" contains the following (found online, and modified slightly): 

```
function print_n(n)
 {
    text = ""
    for(j=0;j<n;j++) text=text"N"
    return text
 }

BEGIN {n=1} 
$0 ~ "^>" { 
    if(n<=i) {
        header = header" "substr($0,2)"";
        if(n > 1) seq=seq""print_n(1000)
        n++;
    } 
    else {
        print ">"header"\n"seq; 
        n=1; 
        header=substr($0,2); 
        seq=""
    } 

    next;
} 
{seq=seq$0} 
END {print ">"header"\n"seq;}
```

And here's my script to edit the headers: 

```
%%bash 

cat ../references/Olurida_v081_concat.fa | tr -d "[:blank:]" > ../references/Olurida_v081_concat_rehead.fa #remove all horizontal white spaces between contigIDs

n_contigs_old=$(grep ">" ../references/Olurida_v081_concat.fa | wc -l) #number of contigs in original fasta 
d="${n_contigs_old//[^[:digit:]]/}" #Return ID of last/highest number contig
digits=$(echo ${#d}) #number of digits in the last contig
n_contigs_new=$(grep ">" ../references/Olurida_v081_concat_rehead.fa | wc -l) #number of contigs in concatenated genome
n=$(seq 1 1 $n_contigs_new) #vector of 1:# of contigs in concat. genome

# loop over each new contig header, paste first and last ID # together and replace concat header with new ID 
for i in $n
do
old=$(grep ">" ../references/Olurida_v081_concat_rehead.fa | sed "${i}q;d")
start=$(echo $old | grep -o -E '[0-9]{1,6}' | head -n 1) #If needed, change the 6 to match the value in $digits 
startID=$(echo ">Contig"$start)
end=$(echo $old | grep -o -E '[0-9]{1,6}' | tail -n 1) #If needed, change the 6 to match the value in $digits 
new=$(echo ">Contig"$start":"$end)
sed -i .bak "s|$startID.*|$new|" ../references/Olurida_v081_concat_rehead.fa # edit fasta in place, but save back-up. 
done
```
