### ISSUE TITLE
rsync from hyak to gannet

### ISSUE THREAD

**Issue by mattgeorgephd** [RobertsLab/resources#1154]
I'm having trouble using rsync.

I used the following code:
rsync --archive --progress --verbose mngeorge@mox1:/gscratch/srlab/mngeorge/sbatch_scripts /Users/mattg/Dropbox/github/mattgeorgephd.github.io/mattgeorgephd.github.io/notebook/sbatch_scripts

and got this error:

receiving incremental file list
rsync: mkdir "/Users/mattg/Dropbox/github/mattgeorgephd.github.io/mattgeorgephd.github.io/notebook/sbatch_scripts" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(657) [Receiver=3.1.2]

Looking through other issues, I should probably be transferring to gannet instead:
https://github.com/RobertsLab/resources/issues/422#issue-368767461

Could someone please set me up with a gannet login. Also, what is wrong with my rsync command? The directory seems to exist in both locations... Thanks!

**Comment by kubu4** [comment]
1. The rsync error you're getting is most likely due to insufficient space on the destination HDD.

2. You already have an account on Mox. Your login should be your UW NetID. You should have received an email from Gannet awhile ago. I think your account was created when Steven's class was starting. I'm guessing your password is the same as the class password. If you don't know your password, just let me know and I'll change it. Please do _not_ attempt to login if you don't know your password - Gannet will block your IP address after a few incorrect attempts. It becomes a hassle to unblock your IP address and allow access again.

**Comment by kubu4** [comment]
Also, just realized if you haven't used gannet, you probably don't know how to access. Sorry!

Via the web (provides a graphical user interface "desktop"):

https://gannet.fish.washington.edu:5001/

Via ssh/rsync:

`gannet.fish.washington.edu`

Your directory can be accessed here via ssh/rsync:

`/volume2/web/panopea`

Finally, all files are publicly viewable (this also provides the ability to get URLs for linking/sharing) here:

https://gannet.fish.washington.edu/panopea/

And, finally, finally, please don't forget to add readme files to each directory you create. The readme files should describe as many of the files in the directory as possible and, at a minimum, provide an overview of the directory's contents.

**Comment by kubu4** [comment]
If you are just syncing sbatch scripts, then I guess it seems unlikely that you'd be low on space. Try this and see what happens:

```shell
cd /Users/mattg/Dropbox/github/mattgeorgephd.github.io/mattgeorgephd.github.io/notebook
rsync --archive --progress --verbose mngeorge@mox1:/gscratch/srlab/mngeorge/sbatch_scripts .
```

The biggest change I've made above is changing the destination directory syntax. With my change, the directory and its contents of `/gscratch/srlab/mngeorge/sbatch_scripts` will get synced to `/Users/mattg/Dropbox/github/mattgeorgephd.github.io/mattgeorgephd.github.io/notebook/sbatch_scripts`.

Your original code would have created another `sbatch_scripts` directory within your existing `sbatch_scripts` directory. So, you would've ended up with `/Users/mattg/Dropbox/github/mattgeorgephd.github.io/mattgeorgephd.github.io/notebook/sbatch_scripts/sbatch_scripts`

**Comment by mattgeorgephd** [comment]
Thanks a lot Sam! - this is really helpful. haha, I was wondering why new directories were being created by rsync.

**Comment by mattgeorgephd** [comment]
> 1. The rsync error you're getting is most likely due to insufficient space on the destination HDD.
> 2. You already have an account on Gannet. Your login should be your UW NetID. You should have received an email from Gannet awhile ago. I think your account was created when Steven's class was starting. I'm guessing your password is the same as the class password. If you don't know your password, just let me know and I'll change it. Please do _not_ attempt to login if you don't know your password - Gannet will block your IP address after a few incorrect attempts. It becomes a hassle to unblock your IP address and allow access again.
> 
> EDITED: Fixed computer name typo.

Yeah - I'm not sure what my password is. If you could create one for me that would be great...

**Comment by mattgeorgephd** [comment]
> If you are just syncing sbatch scripts, then I guess it seems unlikely that you'd be low on space. Try this and see what happens:
> 
> ```shell
> cd /Users/mattg/Dropbox/github/mattgeorgephd.github.io/mattgeorgephd.github.io/notebook
> rsync --archive --progress --verbose mngeorge@mox1:/gscratch/srlab/mngeorge/sbatch_scripts .
> ```
> 
> The biggest change I've made above is changing the destination directory syntax. With my change, the directory and its contents of `/gscratch/srlab/mngeorge/sbatch_scripts` will get synced to `/Users/mattg/Dropbox/github/mattgeorgephd.github.io/mattgeorgephd.github.io/notebook/sbatch_scripts`.
> 
> Your original code would have created another `sbatch_scripts` directory within your existing `sbatch_scripts` directory. So, you would've ended up with `/Users/mattg/Dropbox/github/mattgeorgephd.github.io/mattgeorgephd.github.io/notebook/sbatch_scripts/sbatch_scripts`

Thanks a lot Sam! - this is really helpful. haha, I was wondering why new directories were being created by rsync.

**Comment by kubu4** [comment]
Check Slack DM for new pw.
