### ISSUE TITLE
Get WGBS quote from UW

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1157]
Presuming UW does WGBS - please get quote for 40 samples. 
This would be for geoduck.

**Comment by kubu4** [comment]
Are we doing library prep? I don't think they do bisuflite library construction, but I'll double-check to confirm.

**Comment by sr320** [comment]
Check and see if they do. Can get quote for both routes if they do...

**Comment by kubu4** [comment]
Yep, email's out.

**Comment by kubu4** [comment]
Confirmed they do _not_ perform BS-seq libray prep.

For sequencing quote, which species (genome size would be ideal) and how much coverage are we interested in?

**Comment by sr320** [comment]
> For sequencing quote, which species (genome size would be ideal) and how much coverage are we interested in?
see above (geoduck); 30x

**Comment by kubu4** [comment]
Oh, and also, we looking at multiplexing all 40 samples together? Or, some other multiplexing breakdown? Or, individual sequencing?

**Comment by sr320** [comment]
Not sure it really matters to me. multiplex together?

**Comment by kubu4** [comment]
The primary impact would be an increase in cost if sequencing was split across multiple lanes.

**Comment by sr320** [comment]
would want lowest cost option.

**Comment by kubu4** [comment]
2 x 150bp, 30x coverage = $17,500

And, as per Zymo's suggestions for BS-seq analysis, shorter reads sometimes produce better alignments, so here's an option for that approach (would require running two flow cells).

2 x 100bp, 30x coverage = $35,000 _or_ $30,000 (latter would use two different flow cells types)

**Comment by hputnam** [comment]
We can prep at URI for ~$70 per sample and just found a new location where we have a quote for 1 NovaSeq lane at $4500 for an estimate of ~$7300 for library prep an d1 lane. The we could check the coverage and run another at $4500 if we need a second lane. We also have enough barcodes for dual index of the 40 samples, so could pool all.
