### ISSUE TITLE
sample submission guidelines for RNAseq (JPG lab work) 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1158]
I'm extracting RNA from _O. lurida_ larvae and gill tissue for Jackie Padilla-Gamino's lab. 

They're having me send the samples for sequencing to the University of Texas at Austin. 

### Their [sample input guidelines](https://wikis.utexas.edu/display/GSAF/Sample+Input+Guidelines) say that they want RNA samples to be "10 ul > 1 ng/ul". Does that mean the samples should have RNA concentrations greater than 1 ng/ul and eluted in 10 ul? Finding it confusing... 
 
**I contacted the sequencing facility with questions about this and other sample submission things already, but thought I'd post here in case someone has a quick answer!**

**Comment by kubu4** [comment]
>  Does that mean the samples should have RNA concentrations greater than 1 ng/ul and eluted in 10 ul?

Yes. Also, you'll want to elute in a volume >10uL, as you will not recover the full elution amount from the column.

**Comment by grace-ac** [comment]
Awesome! Thanks @kubu4 !
