### ISSUE TITLE
Submit annotation for Ostrea genome to NCBI

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1159]
https://www.ncbi.nlm.nih.gov/datasets/genomes/?acc=GCA_903981925.1

**Comment by kubu4** [comment]
So, this genome was actually submitted to ENA. Interestingly, it looks like NCBI pulls that info in. So, to add the annotation, I'll probably have to do so via ENA. I have no idea if NCBI can/will pull that info as well eventually, nor how long it would take, but can look into it.

**Comment by sr320** [comment]
per other issue - first try going straight to NCBI - I will drop you some emails in slack if run into any issues.

**Comment by kubu4** [comment]
OK, response from ENA is that they can only "update" annotations on assemblies which were originally submitted with annotations. So, if we wanted to "add" annotations, they would cancel our previous submission and I'd just submit the genome and annotation info simultaneously.

So, with that being the case, I'll just create a new submission to NCBI which will include annotations!

**Comment by sr320** [comment]
Lets see what NCBI says - seems like they might say just give them the annotations. That way would not have to go through complete resubmission?

**Comment by kubu4** [comment]
Sure, sounds good.

**Comment by kubu4** [comment]
Here's email response from NCBI (I name-dropped Nuala in the original request, but didn't seem to carry any weight/recognition).

What do you think we should do:

1. Have NCBI annotate genomes?

OR

2. New ENA submission with annotations?

> Hello,
>
> 1. To add your own annotation to the two assemblies, you would need to work through ENA as this counts as submitter updating their records. Please contact ENA for guidance.
> Once you have annotation added to the records, it will be reflected on the NCBI site. 
> 
>2. NCBI provides our own eukaryotic annotation pipeline:
>
> https://www.ncbi.nlm.nih.gov/genome/annotation_euk/
> 
> We annotate applicable assemblies regardless of the original submission route. But that would not be your own annotation. For example, Pecten maximus was submitted through ENA without annotation, but it was annotated by NCBI:
> 
>https://www.ncbi.nlm.nih.gov/assembly/GCF_902652985.1
> 
>Here is the link to the annotation policy page:
>https://www.ncbi.nlm.nih.gov/genome/annotation_euk/policy/
> 
>The page also links to the request form in case you want to pursue NCBI annotation.
> 
> 
>Best regards,
> 
>Majda Valjavec-Gratian, Ph.D.
>NCBI Customer Services

**Comment by sr320** [comment]
Go ahead and move forward with getting our annotations in - does EBI or NCBI - your call

**Comment by sr320** [comment]
decided to stand down on Ostrea genome
