### ISSUE TITLE
Get Olympus Fluorescent Scope Functioning

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1161]
We have Friedman's scope in the lab that is "broken" - Can you identify and schedule to have the Olympus rep come out and let us know what it would take to make it operational?

**Comment by kubu4** [comment]
Sure. Are there more details than "broken"? Anyone know the model/serial number offhand?

**Comment by sr320** [comment]
Doubtful- @mgavery might know more; can get someone in lab to send model info

**Comment by mgavery** [comment]
Sorry, I don't have any other info about the scope

**Comment by kubu4** [comment]
Who has identified it as "broken"? Any idea(s) of what's not working (e.g. can't see anything through left ocular, green fluorescence filter not working, laser not turning on, objectives don't rotate, etc)?

**Comment by sr320** [comment]
Carolyn

**Comment by kubu4** [comment]
OK, I'll reach out to her.

We borrowed a broken scope or it broke after we borrowed it?

**Comment by mgavery** [comment]
I borrowed the scope to use for larval stuff last March.  The scope itself works, but it's also has capacity to do fluorescence and that part is broken ..and was broken when I borrowed it.

**Comment by kubu4** [comment]
Update. Retrieved the additional components (primarily the mercury lamp) from the Friedman Lab. Will contact Olympus rep to get things set up and tested (mercury lamp won't power on). No filters laying around, though...

@mgavery - Which emission wavelength(s) are you interested in? Will need to relay info to Olympus rep as well, since filters are M.I.A.

**Comment by mgavery** [comment]
<img width="654" alt="Banners_and_Alerts_and_Microsoft_Word_-_DeliveryDiscussionB_doc" src="https://user-images.githubusercontent.com/4512578/112694088-f9808c80-8e3e-11eb-951a-30c7d5682a89.png">

**Comment by mgavery** [comment]
Sorry, and also FITC, which the internets tell me is: "excitation and emission spectrum peak wavelengths of approximately 495 nm/519 nm"

**Comment by kubu4** [comment]
Thanks. Email has been sent  to Olympus.

**Comment by kubu4** [comment]
Rough estimate via email is $5000 - $6000. This is the cost of a new lamp and the filters. What is the budgeted amount for this? Should I continue pursuing this or is this cost out of reach?

**Comment by sr320** [comment]
Can you run by Carolyn and see if she those numbers make sense to her.. and if so we will move forward.

**Comment by kubu4** [comment]
After clarification at lab meeting today, just wanted to add that since the scope will be used at SAFS, there's always the option to use the functional Nikon scope in Carolyn's lab. We'd likely have to spend some money to purchase needed filters, but the cost should be less than the costs associated with purchasing a new light source/filters for the Olympus.

If this is the path we want to take, Carolyn has indicated she'd be happy to walk @mgavery (or, anyone else) through using the Nikon.

**Comment by kubu4** [comment]
Carolyn has confirmed that costs associated with new light source/filters are what she would expect.

**Comment by sr320** [comment]
Let's move forward with repairs

**Comment by kubu4** [comment]
Do we have any interest in purchasing a new setup? The repair rep is trying to upsell me, by throwing out the idea that the current scope is very old and is prone to irreparable failure. A completely new fluorescent scope setup would be $18,000.

Any interest in going this route or just stick with getting current scope setup with the necessary fluorescence components?

**Comment by sr320** [comment]
I suggest sticking with current

**Comment by kubu4** [comment]
Update: Scope was picked up by Olympus repair rep yesterday.

**Comment by kubu4** [comment]
Email from rep:

> 
> So as I said the price for the LED light source is in the region of $4600 and the cost for the appropriate filters that will give you > the correct wavelengths of light to work your tests will be around $2000. 

I can go ahead and get the parts ordered if you would like to get this moving now I have figured it all out

Give the go-ahead?

**Comment by sr320** [comment]
sure

**Comment by sr320** [comment]
@kubu4 can you remind me what budget this was put on?

**Comment by kubu4** [comment]
Hasn't been put on any budget yet. We'll get invoiced and then pay.

**Comment by sr320** [comment]
just wanted to follow up status...

**Comment by kubu4** [comment]
Last update was June 22nd; repair person was going to check in with supplier regarding ETA, but I never heard back.

Just pinged again and will report back.

**Comment by kubu4** [comment]
Update: Part is currently in customs. Expectation is that it will clear customs soon and is expected to be delivered by the end of the week. Not sure how long it will be after receipt of the part (presumably, fast).

**Comment by kubu4** [comment]
Scope has been delivered and is set up with the other scopes in FTR 213.

Manual for the light source is here: https://github.com/RobertsLab/resources/blob/master/equipment_manuals/CoolLED_pE-300_manual_20210901.pdf


![PXL_20210901_165336936](https://user-images.githubusercontent.com/4514104/131714254-9a2f62a7-2f30-4c59-a6d6-3af732e6fcd6.jpg)

**Comment by sr320** [comment]
@kubu4 do you have an invoice for what they did - specifically around

> cost for the appropriate filters that will give you > the correct wavelengths of light to work your tests will be around $2000.

**Comment by kubu4** [comment]
Invoice: [97892bcb-1674-4be1-aa57-5b1f98eeff33.pdf](https://github.com/RobertsLab/resources/files/8179952/97892bcb-1674-4be1-aa57-5b1f98eeff33.pdf)

**Comment by kubu4** [comment]
> cost for the appropriate filters that will give you > the correct wavelengths of light to work your tests will be around $2000.

The cost for each filter was $825 (not including shipping).
