### ISSUE TITLE
Running Blast locally - a bioinformatic exercise

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1167]
Take https://owl.fish.washington.edu/halfshell/genomic-databank/hemat_transcriptome_v1.5.fasta

and locally blast against Swiss-prot protein database
https://d.pr/i/PM8KAa

generating a table output with one hit per query.

A blast tutorial... https://github.com/sr320/fun-gen/blob/master/Jupyter/03-Local-Blast.ipynb

from https://github.com/sr320/fun-gen

Useful? Youtube tutorial https://youtu.be/i2RcnuT5DRY

**Comment by ocattau** [comment]
[hemat_transciptome_blastx_5.12.21.xlsx](https://github.com/RobertsLab/resources/files/6468733/hemat_transciptome_blastx_5.12.21.xlsx)

**Comment by kubu4** [comment]
Nice job! Quick note about using Excel. Excel has the propensity to try to interpret and reformat certain strings, and this has been documented with gene accession IDs. So, it's best practice to refrain from transferring (most? any? all?) data to Excel.
