### ISSUE TITLE
Make NaOH for Titrations

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#117]

**Comment by grace-ac** [comment]
Ok. So before I do it, here is what I think I'll be doing (based on what @kubu4 said yesterday):

In a beaker, put 4g of the NaOH solid.
Add 500ml of Nanopure water
dissolve (should I use a magnet stirrer? or is stirring it by hand sufficient?)

Pour into graduated cylinder and add remaining 500ml to reach 1L 

Result: 0.1 mol/g of NaOH solution

Pour into the 1L titrant bottle.

**Comment by sr320** [comment]
Looks good - use magnetic stirrer

**Comment by kubu4** [comment]
Be sure to wear gloves! If you have short sleeves, I recommend wearing a lab coat.

**Comment by grace-ac** [comment]
Yes thank you! I looked up the chemical properties/dangers of NaOH earlier :)

**Comment by grace-ac** [comment]
Done! The bottle in 228 contains 0.1 mol/L of NaOH. The bottle is labeled with the contents, my initials, and the date.
