### ISSUE TITLE
Develop protocol for molecule delivery

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1170]
Develop system for getting morpholino into oyster eggs via endoporter (lipid transporter). This will involve tagging morpholino so we can visualize success

**Comment by mgavery** [comment]
Here are notes that might be helpful.  Please request access.  I am happy to chat about this, just let me know

[https://docs.google.com/document/d/1C46MyJNQIWiASbBUGyBIUEAVJ3yKAibXkovgq-gZRXg/edit]

**Comment by ocattau** [comment]
Thanks Mac! I just requested access.
