### ISSUE TITLE
help understanding nanodrop and bioanalyzer results from oyster larvae RNAextractions

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1171]
Having trouble determining if these results are ok...  or if there's something wrong with the samples... or maybe with the way I loaded the bioanalyzer chip... Trying to figure out next steps. 

The sequencing facility these samples will be sent to said that they are happy to take the samples' Qubit and Nanodrop results, but they didn't seem too worried about Bioanalyzer results. They said I could spot check some samples, and that they'd run Bioanalyzer on a subset of samples once they arrive. 

Samples are from _O. lurida_ larvae - I extracted RNA using the Zymo kit. All samples have RNA according to Qubit. I've only extracted 10 samples so far, and those 10 I ran on Nanodrop and Bioanalzyer. 

## NanoDrop results
The [manual](http://tools.thermofisher.com/content/sfs/manuals/nd-1000-v3.8-users-manual-8%205x11.pdf) says that for RNA, things are good if:     
- 260/280 ratio is ~2  ("generally accepted as pure")       
- 260/230 ratio is 1.8-2.2 ("commonly")       

The results for the 10 _O. lurida_ larvae RNA samples I've extracted thus far are:       
| Sample Id  | 260/280  | 260/230  |
|------------|----------|----------|
| PW A 20    |     1.98 |      2.2 |
| C 120 B 14 |     2.07 | 2.34* |
| C 120 A 20 |     2.11 | 2.37* |
| C 120 B 20 |      2.1 |     2.18 |
| DB A 20    |        2 |     2.28 |
| PW A 14    |     2.02 |     2.16 |
| C 15 A 14  |     2.02 |        2 |
| PW B 14    | 1.86* |     1.74 |
| C15 B 14   |     1.98 |     2.15 |
| DB A 14    | 2.14* |      2.2 |   

## Bioanalyzer results
Ran the same 10 samples on RNA Pico chip, used a ladder aliquot from Hollie for 2016 from the -80. I did not denature the RNA before running on the chip - didn't think about it until after I saw @kubu4 notebook post about Tanner crab RNA on bioaanlzyer (post: [here](https://robertslab.github.io/sams-notebook/2018/08/01/bioanalyzer-tanner-crab-rna-isolated-with-rneasy-plus-mini-kit.html))... maybe if I had denatured the RNA first, things would be more clear in the results? I also have one sample that was a blank that was just the reagents. 

There were some errors for some of the samples:     
   | Sample Id | Error flagged                                                                 |
|-----------|-------------------------------------------------------------------------------|
| C120 A20  |                                        unexpected baseline signal, code 4,501 |
| C120 B20  | unexpected baseline signal, code 4,501;  unexpected in pre region, code 4,501 |
| C15 A14   |                                    unexpected signal in 5s region, code 4,501 |
| DB A14    |                                    unexpected signal in 5s region, code 4,501 |
| BLANK     | unexpected baseline signal, code 4,501;  unexpected in pre region, code 4,501 |

According to the [manual](https://github.com/RobertsLab/resources/blob/master/equipment_manuals/Agilent_2100-Bioanalyzer_User-guide_20210203.pdf) some are critical issues, some are not:          
![Screen Shot 2021-03-31 at 1 08 55 PM](https://user-images.githubusercontent.com/14934314/113205231-e5fc6980-9222-11eb-952c-c23a78431a20.png)

I'm struggling to find any info on how to troubleshoot that specific error code (4,501) or what it exactly means... I looked through the [troubleshooting manual](https://github.com/RobertsLab/resources/blob/master/equipment_manuals/Agilent_2100-Bioanalyzer_Maintenance-Troubleshooting_USR_ENG.pdf) and it doesn't mention any of those errors.... But I can see that there is some overlap with what my sample electropherograms look like and what some of the troubleshooting guide images show on pages 76 and 80...   

#### Electropherogram:       
![electropherogram](https://user-images.githubusercontent.com/14934314/113203548-088d8300-9221-11eb-917d-280c1dd24c38.PNG)

#### Gel:     
![Capture3](https://user-images.githubusercontent.com/14934314/113203636-222eca80-9221-11eb-852b-fb6718a2b444.PNG)

**Comment by kubu4** [comment]
NanoDrop is good.

Bioanalyzer looks like chip wasn't prepared properly. Things to check:

1. Was ladder prepared/stored properly (e.g. Was ladder denatured before use? Was it aliquoted into single use volumes?)

2. Were chip reagents allowed to warm to room temperature (min. of 30mins on benchtop) prior to use?

3. Was plunger set at the proper position for the type of chip you were using?

Anyway, lots of variables at play with the Bioanalyzer that could lead to these types of results. Those are the three easiest (and most likely cause of issues) to address.

**Comment by kubu4** [comment]
>  used a ladder aliquot from Hollie for 2016 from the -80

Sorry, just saw this. Yes, this ladder was denatured prior to aliquoting, so you can ignore this as a possible concern.

So, it probably boils down to reagent prep and/or plunger position.

Denaturing your sample is good to do, but skipping this step wouldn't cause the results you're seeing.

**Comment by kubu4** [comment]
> Would you recommend I try denaturing extracted RNA at 70C for 2 minutes as well

Yes, you should do this, but it's not critical.

**Comment by grace-ac** [comment]
Ok! Thanks so much!

**Comment by grace-ac** [comment]
Yep! I just saw that you specified you had the plunger clip at the top position when you ran the tanner crab samples, and the plunger when I used it had the clip at the bottom position. I'll look into that - thanks!

**Comment by grace-ac** [comment]
Reopening - Have nanodrop results for all 56 samples, some ratios for 260/230 are super low, which the [manual](http://tools.thermofisher.com/content/sfs/manuals/nd-1000-v3.8-users-manual-8%205x11.pdf) suggests could indicate "the presence of co-purified contaminants".    

Link to my sample spreadsheet: [here](https://docs.google.com/spreadsheets/d/1kawaIvhVcB75wwHPVequIx56XELuvLVKYS8Mb4XL0Zc/edit?usp=sharing)      
The Nanodrop results are in columns "nd_260/280" and "nd_260/230". I highlighted the samples that look to me to have too low of the 260/230 ratio in a light red. 

I'm trying to determine if there are any samples that need to be re-extracted, hoping to send off all 56 this week for sequencing. Or maybe there's a different protocol or kit that can be used to clean out the contaminants of my already extracted samples? 

**Sequencing facility needs samples to be at least 25ul in volume, 2 ug @ > 40 ng/ul.**

**Comment by kubu4** [comment]
Usually not a big deal, however the rest of your samples look fine. Knowing that, I'd probably consider an attempt to clean them up. What does the spectral output (i.e. the graphs) look like for those samples? That will give you some info on what the potential contaminants are.

As far as clean up goes, an ethanol precipitation is usually sufficient to clean up most stuff.

**Comment by grace-ac** [comment]
Ok! I have the folders of spectral outputs in google drive [here](https://drive.google.com/drive/u/0/folders/1nCndVdquLik-Xto6radr_EtuISTEPNHx) in folders by date of extraction, with each image labeled with the sample number. I'll look through those and the manual to see what I can figure out! Thank yoU! 

**Also another question** --> for library prep and sequencing, is it a problem if my samples have different volumes? They are all more than 25ul, but because for some I've had to re-run qubit or nanodrop, they aren't all the same.

**Comment by kubu4** [comment]
> samples have different volumes? They are all more than 25ul

> Sequencing facility needs samples to be at least 25ul

Seems to fit the requirements.

**Comment by grace-ac** [comment]
This is the ethanol precipitation protocol, right? @kubu4  https://github.com/RobertsLab/resources/blob/master/protocols/ethanol_precipitation_DNA.md

**Comment by kubu4** [comment]
Yes.

**Comment by grace-ac** [comment]
THANKS!

**Comment by grace-ac** [comment]
@kubu4  - how much 70% EtOH to wash with? doesn't say in protocol: https://github.com/RobertsLab/resources/blob/master/protocols/ethanol_precipitation_DNA.md

**Comment by kubu4** [comment]
1mL should be fine.

**Comment by grace-ac** [comment]
all the qubit results came back as "TOO LOW" ... I'm hoping that maybe the RNA wasn't resuspended properly. Would incubating them at a warm temperature potentially help if that's the issue? 

When I initially attempted to resuspended, I pipet to mix and did a little burst of vortex. Maybe I should have used warm water initially to resuspend...

**Comment by kubu4** [comment]
> Would incubating them at a warm temperature potentially help if that's the issue

It's worth a shot, but your RNA is most likely gone - lost during one of the wash steps.

Unless you can still see a pellet. Can you still see a pellet?
