### ISSUE TITLE
Location / Documentation for Jensen Samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1172]
Do we have any documentation on what Pam dropped off in terms archival samples, specifically the contents of the flash drive? 

We are aware of https://github.com/RobertsLab/project-hematodinium/blob/master/notes/PCJ-073020.md

**Comment by kubu4** [comment]
I've never opened the flash drive, which she left on my desk.

**Comment by sr320** [comment]
no rush, but next time you are in can you put on the cloud somewhere?

**Comment by grace-ac** [comment]
Is there a way to just upload folders that contain files onto gannet? 

So far it seems like I have to create folders and then put the files into the folders. The contents of the USB are lots of folders within folders and lots of files.

**Comment by grace-ac** [comment]
Ignore the above! Dragging and dropping folders works.

**Comment by grace-ac** [comment]
URL for Pam's USB info: https://gannet.fish.washington.edu/hematodinium/

**Comment by sr320** [comment]
Thanks!
Note  I changed the "Contacts.." word doc to an encrypted PDF and renamed `README` will drop  password in slack
