### ISSUE TITLE
Explore crab genomic DNA sequence

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1175]
note their is circular DNA

**Comment by kubu4** [comment]
Link to assembly info text file:

https://gannet.fish.washington.edu/Atumefaciens/20200917_cbai_flye_nanopore_genome_assembly/cbai_genome_v1.0_info.txt

Has following columns:

| #seq_name | length | cov. | circ. | repeat | mult. | alt_group | graph_path |
|-----------|--------|------|-------|--------|-------|-----------|------------|

`circ.` contains `Y` or `N` to indicate whether or not a contig was deemed to be circular.

`seq_name` should be the contig names used in the assembly FastA.

Circular contigs could be BLASTed to identify potential taxa.

Also, I've done some taxonomic assignment and extraction of NanoPore _reads_. These are in FastA format and could be BLASTed against the assembly FastA to find out which contigs they match with...

https://robertslab.github.io/sams-notebook/2020/10/07/NanoPore-Reads-Extractions-C.bairdi-Taxonomic-Reads-Extractions-with-MEGAN6-on-201002558-2729-Q7-and-6129-403-26-Q7.html

**Comment by afcoyle** [comment]
Goals: 
- How much (and what) is _Hematodinium_
- ID circular sequences

Steps:
- BLAST genome against nt db or something similar
- BLAST known hematodinium sequences against genome (using Alveolata sequences)
- For circular contigs, could see what matches post-BLAST, or pull those seqs and BLAST separately
