### ISSUE TITLE
where on gannet to put Pam's crab/hematodinium info? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1177]
where on gannet should I put the info from Pam? should I make a new folder? 

Here's a sneak peak on what's on the USB drive:

![Screen Shot 2021-04-06 at 2 37 01 PM](https://user-images.githubusercontent.com/14934314/113781551-b697a200-96e5-11eb-9801-8699abc8d244.png)

**Comment by sr320** [comment]
Does not matter - somewhere where you have a url.

**Comment by grace-ac** [comment]
i'll post url in #1172
