### ISSUE TITLE
Can I use 8 reps Zymo Quick DNA/RNA Micropprep Plus Kit? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1179]
I messed up some samples of Jackie's, and she only bought enough of the kit preps for 60 reps. I need 8 more reps-worth of the kit for my last extractions tomorrow. 

Is it ok if I use 8reps of the zymo kit in 213? Jackie will reimburse/replace whatever of SRLab's stuff I use! I'm keeping track. 

Want to make sure no one is planning on extracting anything soon!

**Comment by grace-ac** [comment]
our lab has between 150+reps of the kit btw... so I'm assuming my using 8 isn't going to mess anyone up

**Comment by sr320** [comment]
Sure
