### ISSUE TITLE
DIA Protocol Step 3a-b 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#118]
QUESTION FOR 3A: do I just put the paths to these files in a .txt file and then upload that to GitHub?
[Step 3a](https://github.com/RobertsLab/resources/blob/master/protocols/DIA-data-Analyses.md#step-3a-create-two-text-files-that-indicate-path-for-1-the-reference-peptide-list-in-silico-protein-digestion-and-2-spectra-data-mzml-files). 
![capture3](https://user-images.githubusercontent.com/14934314/32622498-e4438b34-c537-11e7-932e-5270b12e6c32.PNG)

- The reference peptide list is in the folder "grace" on the desktop.
- The .mzML files are in downloads. 

QUESTION FOR 3B: The link to the example doesn't work and I'm having a generally difficult time understanding what this step calls for. What is the mass spectrometry method file?
[Step 3b](https://github.com/RobertsLab/resources/blob/master/protocols/DIA-data-Analyses.md#step-3b-generate-isolation-scheme-file)
![capture2](https://user-images.githubusercontent.com/14934314/32622473-d2e91a0c-c537-11e7-9617-6e15297236fb.PNG)

**Comment by kubu4** [comment]
>QUESTION FOR 3A: do I just put the paths to these files in a .txt file and then upload that to GitHub?

Yes, paths to those files in a .txt file.

No, do not upload to GitHub.

>QUESTION FOR 3B: The link to the example doesn't work and I'm having a generally difficult time understanding what this step calls for. What is the mass spectrometry method file?

I think this is the correct URL for the isolation scheme file: https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_PECAN_20170228/PECAN-inputs/2017-03-03-isolation-windows.csv

Please confirm prior to updating link in protocol, though.
