### ISSUE TITLE
Create and provide url to lab notebook

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1181]
see https://robertslab.github.io/resources/Lab-Notebooks/ 
and also examples at 
https://d.pr/i/H1PDvo

**Comment by ocattau** [comment]
Here you go! https://ocattau.github.io/

For the last few weeks, I am going to post my geoduck developmental timing attempts and any progress I have made with BLAST tools and onboarding

**Comment by kubu4** [comment]
Nice work! Your officially a lab member!
