### ISSUE TITLE
Visualizing sibship / parentage data from Colony

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#1184]
Does anyone have or know of code that one could use to visualize the output from [Colony](https://www.zsl.org/science/software/colony)?  Perhaps a pedigree / dendogram like plot?  I've played with the [`rcolony`](https://rdrr.io/rforge/rcolony/) program a bit, but I don't think it's going to work with the version of Colony that I have (2.0.6.6).  Here's what one of the Colony files looks like, which provides the best guess at clustering based on father and mother IDs: 

![image](https://user-images.githubusercontent.com/17264765/115323963-e1e6ac00-a13d-11eb-9549-7918499a5fea.png)

I have this data in R and have plotted individuals by father ID ~ mother ID, color coded by populatio, shape by pCO2 exposure, and size by probability. But I think there could be a much easier way to visualize this data.

![image](https://user-images.githubusercontent.com/17264765/115324130-325e0980-a13e-11eb-8fd4-d8ccf33b44d6.png)

Attached is the R object used to make that scatter plot, should anyone be extra curious 

[best-cluster-adult.zip](https://github.com/RobertsLab/resources/files/6340012/best-cluster-adult.zip)

**Comment by mgavery** [comment]
Hi, just saw this, not sure if still relevant - maybe check with Jay Dimond?  I've seen some dendrograms he's made recently for abalone data.  Not sure if it was from COLONY output

**Comment by sr320** [comment]
I would hope @jldimond follows this religiously and is merely taking his time to compose a response 😄

**Comment by jldimond** [comment]
Haha yes, religiously, of course! 

Sorry, I don't have any ideas for dealing with Colony, or with this kind of pedigree data. The dendrograms I made that @mgavery is referring to were based on genomic data using a relatedness matrix with the [StAMPP](https://cran.r-project.org/web/packages/StAMPP/index.html) package.

**Comment by laurahspencer** [comment]
Alright, thank ya'll

**Comment by jldimond** [comment]
@laurahspencer - just thinking about this earlier while mtn biking - have you tried plotting a distance matrix of the father and mother ID data? Something like: plot(hclust(dist(x)))
