### ISSUE TITLE
Curate videos/photos/materials for SEAS Open House

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#1189]
SEAS Open House is May 19-22. They're looking for recorded videos/content that can live on their landing page for the duration of the event, as well as some live/interactive events to engage with K-12 students. Some ideas discussed during lab meeting:

- Look through archived media to retool
- Pt. Whitney hatchery tour or 360 camera
- Rework geoduck FFAR videos

Content should be easily accessible for the lab after the Open House

**Comment by sr320** [comment]
lets compile options here..
https://youtu.be/EGzxtekC-3A
https://www.youtube.com/watch?v=8-BzLq4Kn50
https://youtu.be/z1LI8O7aT2o
https://youtu.be/Kvisz5X-iWU
https://youtu.be/tKy_N1dpNhE

**Comment by sr320** [comment]
I have added some at https://robertslab.github.io/resources/Digital-Media/#videos

I think it makes sense to have a text caption for each one that describes what it is. That would also visually break up the stack of videos

**Comment by laurahspencer** [comment]
Hey folks- I made a couple interactive plotly figures. If anyone feels like figuring out how to embed them into the open house page, that'd be awesome. Otherwise I'll mess around with it this weekend. 

Files: 
[seas-open-plotly.zip](https://github.com/RobertsLab/resources/files/6480919/seas-open-plotly.zip)

**Comment by sr320** [comment]
Do you have a url where this lives like  http://plot.ly/~chris/1638?

**Comment by laurahspencer** [comment]
I could make that- will do in a bit

**Comment by laurahspencer** [comment]
https://plotly.com/~lhs3/15/
https://plotly.com/~lhs3/17/

**Comment by sr320** [comment]
See https://robertslab.github.io/Open-House-2021/Ostrea/

**Comment by sr320** [comment]
Nice job everyone!
