### ISSUE TITLE
Send Scallop Gonads out for Histology

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#119]
Natalie has Histo blocks that correspond to what @ksil91 is currently sequencing.
Please confirm which samples correspond and send out for Histo.
Brent would be the first point of conact.

**Comment by grace-ac** [comment]
I have samples in 209. Will send out on Monday

**Comment by sr320** [comment]
Need to confirm these match With what @ksil91 is looking at first

**Comment by grace-ac** [comment]
Oh right! i have a spreadsheet. I'll check it out now

**Comment by grace-ac** [comment]
They match!

@ksil91 did [RNA Extractions](https://benchling.com/ksil91/f/VasEYsRt-rangewide-common-garden/etr-blBzoO4l-scallop-rna-extractions/edit) for 16 of the scallops. 

Should I have histology made for only those 16? Or should all 91 be made? 
According to the [Purchase Log](https://docs.google.com/spreadsheets/d/1DHXiiEzWhh0XHnEMvKz4TX10e69ErOWHv5Jo-ouk6x8/edit#gid=0), it looks like 46 samples cost $492.

**Comment by ksil91** [comment]
For the full transcriptome assembly (not gene expression) I submitted 11 gonad samples from the 36 hour exposure treatments (which ones are listed on the sheets [here](https://docs.google.com/spreadsheets/d/1h0jDalmaQvLUx0thYtOYV1ZTDxN1wVHX45mqls_Ji70/edit?usp=sharing).
I will also be doing Quant-Seq to get gene expression info on those samples and some other. Here's the full list of what I'm planning to do gene expression on:
From T1:
312, 36, 372, 370, 310, 39, 305, 311, 360, 53, 58, 391, 390, 309, 234, 38, 393, 381, 308, 233, 50, 386, 376
From T2 (after 6 weeks) (depending on results from T1):
363, 63, 45, 375, 246, 48, 392, 362, 44, 377, 388, 240, 66, 373, 236, 51, 374, 364, 37, 389

**Comment by grace-ac** [comment]
All packed up and ready to go. Budget number for shipping @sr320 ?

**Comment by sr320** [comment]
65-2861

**Comment by ksil91** [comment]
Are the results of the histology from these somewhere?
@sr320 @grace-ac

**Comment by sr320** [comment]
I presume the slides are in the lab... 
I briefly looked at https://docs.google.com/spreadsheets/d/1BIbDleJPEiKrmx7JwNIPwg2pM-thuZ39upmenldx4pA/edit#gid=0 

and did not see - but many samples do not have taxa

**Comment by kubu4** [comment]
They're listed on there (drawer 1, row 4). If the database is correct, they have not been imaged. However, the database doesn't have links to any slide images, of which we definitely have many of other species; just not sure about the scallops.

**Comment by kubu4** [comment]
Sorry, slide case 1, slots 71-100 is where the majority of the slides are stored.

**Comment by ksil91** [comment]
Would is be possible to have these imaged by early March? I have 2 distinct clusters for gene expression in gonads which I assume is sex driven and therefore should be controlled for. Natalie has rough estimates of sex for some of the samples, but it would be nice to check these out. I'm not including the gonad samples in the dissertation, but will be in the manuscript write up starting in March.
