### ISSUE TITLE
Quote out a BAM

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1193]
What would a Big Amazing Machine (desktop) look like?
In other words something close on spec to Mox (at least in terms of memory)
I would be interested in having the conversation on the benefits have have this machine for direct access?

**Comment by sr320** [comment]
I am a bit biased but would see a value in having one of these https://d.pr/i/8Z6XE6 plugged in the lab.

**Comment by kubu4** [comment]
Just tossing this out here real quick before spending more time:

Dell server tower with 2 x 2.2GHz (10 cores each = 20 cores) with 96GB RAM and 2 x 2TB HDDs:

~$4500.00


![image](https://user-images.githubusercontent.com/4514104/116586929-d1b59600-a8ce-11eb-88ef-4685f3d453bb.png)

**Comment by kubu4** [comment]
With 192GB of RAM, the price comes out to be ~$6000.00

**Comment by sr320** [comment]
Thanks! I would not spend more time. Lets maybe chat at Science Hour.. or lab meeting

**Comment by sr320** [comment]
Lets move ahead with this. At lab meeting lets confirm we are not missing any features.

**Comment by kubu4** [comment]
> we are not missing any features.

I guess we should probably decide _which_ features we want (as well as max budget) - there're an insane amount of options...

**Comment by sr320** [comment]
We do not have to get crazy with features, but thinks like making sure remote desktop is a simple option. Which might mean Windows? What would be your preferred OS situation?

**Comment by kubu4** [comment]
> What would be your preferred OS situation

Personally, I'd like to avoid Windows. I think it would really limit usage of that computer. macOS or Ubuntu would be ideal. And, if our primary concern is using remote desktop software, it seems like macOS would be the way to go. However, I'm not sure how RStudio Server is built and whether or not it will run properly on macOS...

**Comment by sr320** [comment]
I thinking we go with both, a linux and a mac.

**Comment by kubu4** [comment]
Well, if we bump things up to 384GB RAM, we're looking at ~$12,000.

Also, prices above from the earlier configuration date seems to have increased ~10 -15% since then...

**Comment by kubu4** [comment]
I also just found an option for 512GB of RAM for ~$12,000. It's a "workstation" setup (instead of "server" setup) and uses "persistent memory". Much cheaper than standard RAM.

**Comment by kubu4** [comment]
That configuration mentioned above with 192GB RAM is ~$6000.

**Comment by kubu4** [comment]
Yes. I'll see what I can pull up with the workstation. I guess the persistent memory allows for some solid savings. BRB...

**Comment by sr320** [comment]
Let move forward on this Monday. on 65-9135, needing to get product and invoice in June.

**Comment by sr320** [comment]
Lets get monitor, ssds, workstation,
$889.33 - 65-0193
$6000 - 65-9135
rest 65-2861

**Comment by kubu4** [comment]
Ordered yesterday.

**Comment by kubu4** [comment]
Update: Computer has shipped, as well as external HDDs. Monitor is the only thing that was delayed until June 29th.
