### ISSUE TITLE
Provide info on lab alarms

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#12]
_From @sr320 on January 8, 2017 19:58_

Add content to

https://github.com/sr320/LabDocs/wiki/Alarm-Information

with alarm info.

_Copied from original issue: sr320/LabDocs#420_

**Comment by kubu4** [comment]
_From @seanb80 on January 9, 2017 19:39_

Updated.

**Comment by kubu4** [comment]
_From @seanb80 on January 9, 2017 19:43_

the alarm to the second freezer is currently disabled and I'm not sure why. I can try to turn it back on with the same settings as the first freezer, or we can continue to run with the system as it currently is, which assumes that if the power to freezer 1 is off, the power to all of them is off, and vice versa.

**Comment by kubu4** [comment]
FYI: The second phone number in the Sensaphone call calls my cell. Since my
cell is an out-of-state area code, the number sequence has to utilize the
UW's long distance passcode for our lab account.

That's why it's somecrazy number sequence instead of a normal phone number.

**Comment by kubu4** [comment]
_From @sr320 on January 9, 2017 19:46_

So there is no way to get notifications based on a temperature- or
indirectly know when freezer internal temp alarms go off?

**Comment by kubu4** [comment]
We disabled the alarm on freezer 2 because it was annoying. It triggers an alarm state in a the opposite fashion as intended: it calls when the temp returns to normal, instead of when it increases above a certain threshold.

**Comment by kubu4** [comment]
_From @sr320 on January 9, 2017 19:49_

Related - go ahead and label the numbers it calls-- the first one is me.

**Comment by kubu4** [comment]
Sensaphone only responds to alarm states created by the freezers. It doesn't monitor freezer temps.

So, individual freezer settings would need to be changed to trigger an alarm state at a specific temp.

**Comment by kubu4** [comment]
_From @seanb80 on January 19, 2017 18:38_

The VWR freezer is set to trigger the alarm at a high temp of -70* and a low temp of -90*, the Revco freezer is not currently set to alarm due to the aforementioned annoyance factor.

**Comment by kubu4** [comment]
_From @sr320 on February 14, 2017 3:49_

Still want to get avtech info

**Comment by kubu4** [comment]
_From @seanb80 on February 17, 2017 20:28_

I've updated the wiki with Avtech information from Jon. Will update it further once I get shown how to change/update the alarm programming.

**Comment by kubu4** [comment]
The program for accessing/setting the Avtech is installed on the Windows computer that used to be in the conference room. Can't remember what it's called, but likely has Avtech in the name.

**Comment by kubu4** [comment]
_From @seanb80 on February 17, 2017 22:36_

Ah, found it! Thank you. There's an external facing IP address that we can use to monitor current temperatures and, with login credentials, change settings on the Avtech. 

Do we want the IP there, or would it be better to keep it off of public stuff?

**Comment by sr320** [comment]
is there anything to do here?

**Comment by kubu4** [comment]
Think it's good.
