### ISSUE TITLE
Analyze Histo from C gigas OA trial

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#120]

**Comment by grace-ac** [comment]
I have all the images taken 
[Pre-OA](https://drive.google.com/drive/folders/0B_Kednl1tNImX0MyY0tTdlBrRjg?usp=sharing)
[Post-OA](https://drive.google.com/drive/folders/0B_Kednl1tNImT3ZlVnNlb2JfNVE?usp=sharing)

I found this paper a while back with some gonad histology examples. 
[Fabioux et al. 2005](https://drive.google.com/drive/folders/0B_Kednl1tNImazZ5NWdxYUlfNnc)

I'll start looking at it more closely and will also look for other papers.

**Comment by grace-ac** [comment]
Fabioux used the reproductive scale from [Steele and Mulcahey 1999](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/390C7CEBAEBF16A7003F3D56CA77C2BF/S0025315498000836a.pdf/gametogenesis-of-the-oyster-crassostrea-gigas-in-southern-ireland.pdf)

**Comment by sr320** [comment]
Check and see what they used-
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0036353

**Comment by grace-ac** [comment]
[Franco et al 2008](https://ac.els-cdn.com/S0040816608000025/1-s2.0-S0040816608000025-main.pdf?_tid=edc860e4-c8ca-11e7-ae6b-00000aacb35e&acdnat=1510616136_c2aba0666b1392eb9bae7f3f862ec7e1) for fine scale early stages of MALES ONLY. Looks like it'll be useful!!!

Additionally, they used [Enriquez-Diaz et al 2009](https://link.springer.com/content/pdf/10.1007%2Fs10499-008-9219-1.pdf). This is the most descriptive it gets:

![screen shot 2017-11-13 at 3 40 39 pm](https://user-images.githubusercontent.com/14934314/32755273-4ef3d958-c889-11e7-84d2-a3b80d2537f2.png)

---------

The papers that those parameters are based on are these:
Kennedy, A., & Battle, H. (1964). CYCLIC CHANGES IN THE GONAD OF THE AMERICAN OYSTER, CRASSOSTREA VIRGINICA (GMELIN). Canadian Journal of Zoology, 42(2), 305-321.

Mann, R. (1979). Some biochemical and physiological aspects of growth and gametogenesis in Crassostrea gigas and Ostrea edulis grown at sustained elevated temperatures *. Journal of the Marine Biological Association of the United Kingdom, 59(1), 95-110.

But I can't get access to online copies of those two. Even with going through the UW libraries.

**Comment by sr320** [comment]
Go ahead and try giving it a first pass of classification

**Comment by grace-ac** [comment]
Link to my attempts so far: [Cgigas_histo-classification](https://docs.google.com/spreadsheets/d/1ObTeYRQwELWhLLdVcAzt4SWPJgtj0u2QmoAxfjgFqtw/edit#gid=0)

**Comment by sr320** [comment]
Can you make a figure?

**Comment by grace-ac** [comment]
Here's what I've done so far. Just some labeled images that point out cell-types I think I'm identifying correctly in order to determine the stage they're in:
![gigas-histo-fig-test](https://user-images.githubusercontent.com/14934314/32919155-aaa02d0e-cad9-11e7-8f38-8d98982163f8.png)

The staging is based on [these](https://user-images.githubusercontent.com/14934314/32755273-4ef3d958-c889-11e7-84d2-a3b80d2537f2.png) 

And the cell-type differentiation is based on comparison to these histology images from Fabioux et al. 2005:
[Female-histo](http://owl.fish.washington.edu/scaphapoda/grace/gigas-female_cell-types.png)
[Male-histo](http://owl.fish.washington.edu/scaphapoda/grace/gigas-male_cell-types.png)

**Comment by sr320** [comment]
👍 

How about a figure show sex ratios (i.e. pie chart)

**Comment by grace-ac** [comment]
![pre-oa-pie](https://user-images.githubusercontent.com/14934314/33036742-338745c8-cde4-11e7-9e84-16edf7b45fe0.png)
![post-oa-pie](https://user-images.githubusercontent.com/14934314/33036788-598a4720-cde4-11e7-9b0b-62d3f6b12dc8.png)
