### ISSUE TITLE
how best to concentrate an extracted RNA sample?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1203]
I have a sample of extracted RNA that's currently in 33ul of H20. Wanting to concentrate it per the sequencing facility's request to about 27ul so that the RNA concentration (ng/ul) in the sample will be closer to the other samples. 

What's the best way to do that? The only time I've tried concentrating anything was by using the lyophilizer...

**Comment by kubu4** [comment]
Ethanol precipitation is the "standard". SpeedVac is a good option (preferably refrigerated). There are RNA concentration kits available.

**Comment by grace-ac** [comment]
ok thanks! I'll look into the kits!

**Comment by kubu4** [comment]
> Wanting to concentrate it per the sequencing facility's request to about 27ul so that the RNA concentration (ng/ul) in the sample will be closer to the other samples.

This seems a bit odd to me. The better option would be to dilute the other samples to match the sample with the lowest concentration.

**Comment by grace-ac** [comment]
yeah they told Jackie they want all the samples to be about 50ng/ul... and this one is the only one out of 54 that is below 50ng/ul.

**Comment by sr320** [comment]
I would think messing with this one sample, one is more likely to mess it up / lose it.

**Comment by kubu4** [comment]
> all the samples to be about 50ng/ul

Ah, I see. This bit threw me off:

>  to about 27ul

**Comment by kubu4** [comment]
> get them as close to the same concentration as best as you can

So, they don't require 50ng/uL. I'd dilute all samples to match one with lowest concentration (assuming that concentration falls within their acceptable range). This way, no chance of losing any sample, since you're just adding buffer (or DEPC H<sub>2</sub>O).

**Comment by grace-ac** [comment]
@kubu4 is it typically desired/needed for all samples to have roughly the same final volume? I diluted them, but they need to be diluted further, and just adding more H20 would be sooooo nice and easy instead of trying to normalize the final volumes with all of them. 

the facility's website just says at least 25ul total volume. Doesn't provide a maximum. But the samples will be sent in a 96-well plate so I know that the max for each well is like 350ul or something.

If I were to add more H20 to get the desired concentration, the range of final volumes in the samples would be from ~40ul to about ~90ul.

I asked two other people but they haven't gotten back to me... but no worries if you don't see this/can't respond!

**Comment by kubu4** [comment]
Different volumes shouldn't matter; concentration is usually all that matters, as long as the minimal sample volume is satisfied.
