### ISSUE TITLE
Download and QC Cv gonad data

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#1209]
- WGBS: FastQC, maybe Bismark
- RNA-Seq: FastQC

All metadata can be found at [this link](https://github.com/RobertsLab/project-oyster-comparative-omics/tree/master/metadata)

**Comment by yaaminiv** [comment]
WGBS (4060):

> The DNA methylation sequencing data is now available. The attached Excel table contains a brief library preps methods description as well as links to download the fastq file data. I also attached a “download_links.psl” file, which contains code for downloading all the links simultaneously.
 
> In addition, we ended up running a more thorough QC of the sequence data as we are testing a new pipeline to make sure the quality and metrics all looked good. If you are interested, you can view all of those analysis results in the attached HTML file (MultiQC style format). You can click through the various figures or just hover over particular plots or samples for more information. There are explainers built into the report if you’d like, but the takeaway is that the data looked good for all samples.

**Comment by yaaminiv** [comment]
RNA-Seq (4059):

> The attached HTML file contains download links for all of your project samples’ fastq files. There are instructions for bulk data download included in the “Downlad data” section of the file as well. I also attached a PDF with some methods descriptions related to the sample processing and sequencing. Please let me know if you have any other questions, and I will be happy to help.

**Comment by kubu4** [comment]
@yaaminiv - Can you please contact Zymo and request md5 checksums for the FastQ files?

**Comment by yaaminiv** [comment]
Requested MD5 checksums and Bismark parameters used. Will report back when I get them.

**Comment by yaaminiv** [comment]
md5sums for WGBS data: https://github.com/RobertsLab/project-oyster-comparative-omics/blob/master/metadata/zr4060_md5.csv

Bismark parameter information from Zymo:

> Regarding the Bismark settings, the following might be a good description: “Index files were constructed by bismark_genome_preparation command using the entire reference genome. --non_directional and all other default parameters were applied while running Bismark.”

**Comment by yaaminiv** [comment]
md5sums for RNA-Seq data: https://github.com/RobertsLab/project-oyster-comparative-omics/blob/master/metadata/4059_md5sum.txt

**Comment by yaaminiv** [comment]
please put Bismark output in this folder: https://gannet.fish.washington.edu/spartina/project-oyster-comparative-omics/bismark-output-zymo/ thanks!

**Comment by sr320** [comment]
Status?

**Comment by kubu4** [comment]
All data has been downloaded. 

Still need to:

- Run FastQC
- add to nightingales spreadsheet
- submit to NCBI SRA

I should be able to get the first two things finished today.

Submitting to NCBI might be finished by the end of the week...

**Comment by kubu4** [comment]
@yaaminiv - When you have a sec, can you please point me to (or, provide me with) info on sequencing sample names and corresponding metadata (experimental treatment(s), sex, tissue, age, etc)? I've looked through some of the files in that repo linked above, but am having difficulty figuring out how to match up the original sample names listed for DNA/RNA extractions with the names of the sequencing filenames.

**Comment by yaaminiv** [comment]
> When you have a sec, can you please point me to (or, provide me with) info on sequencing sample names and corresponding metadata (experimental treatment(s), sex, tissue, age, etc)? 

The sample ID in the [sample information document I sent to Zymo](https://github.com/RobertsLab/project-oyster-comparative-omics/blob/master/metadata/4060_SampleInformation.xlsx) matches with the sample ID in the sequencing sample names! The sample ID consists of two parts, a number and a letter (ex. 3F or 31M). The number corresponds to the "sample" column and the letter corresponds to the "sex" column in [this spreadsheet](https://github.com/RobertsLab/project-oyster-comparative-omics/blob/master/metadata/Virginica-Final-DNA-RNA-Yield.csv). Female samples are gonad tissue, and male samples are sperm. I don't have age information from Alan/Katie, but ask.

**Comment by kubu4** [comment]
Thanks! Don't need ages, if they're adults.

**Comment by yaaminiv** [comment]
> Don't need ages, if they're adults.

They certainly are adults!
