### ISSUE TITLE
Sources of C. gigas RNA to make RNA probes for in situ hybridization

### ISSUE THREAD

**Issue by mgavery** [RobertsLab/resources#1211]
I am looking for one or a few good sources of C. gigas RNA (or tissue if preserved for RNA).  The desired source would be early embryos, but female and male gonad tissue would probably also work.  Does anyone have any good quality RNA from these sources to spare?

**Comment by kubu4** [comment]
See what you can find here:

https://docs.google.com/spreadsheets/d/1Qsvz3QTURlPF_hX05BQxjom3484WuMfqQ1ILl9LEljU/edit#gid=2006985773

Shellfish RNA boxes (links to individual box inventories are in the sheet above) would be the place to look first.
