### ISSUE TITLE
need to edit out end of DNA isolation video

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1215]
I'll do this later, but in case someone has an easy way to do it:

we need to edit out the end of the DNA isolation video (the part with opening the beer) to make it more family friendly 

DNA isolation video: https://www.youtube.com/embed/z3D1NTwh0hk

**Comment by sr320** [comment]
I might have did it in Youtube - it might take a few hours to render though

**Comment by sr320** [comment]
looks like it is edited now.

**Comment by grace-ac** [comment]
perfect - thanks! glad you kept the bottle cap message haha
