### ISSUE TITLE
Jumpstart and move ahead with bittercrab.science

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1217]
https://bittercrab.wordpress.com/

Let jumpstart this with your effort such that we increase knowledge, engagement and opportunities.

**Comment by afcoyle** [comment]
Sounds good! Any thoughts on the general format this should take (podcast-centric vs. article-centric), good people to talk to, good ways to get this out there?

Beyond that, any general restrictions or requirements I should know about? If I remember right, this was originally part of the conditions of the funding - is that still in effect?

**Comment by sr320** [comment]
Lets shoot for at least one text and one audio per week.. trying to keep as super efficient. Can chat at SH, leveraging IFTTT is way to go. No restrictions
