### ISSUE TITLE
expected bacteria in hatchery water

### ISSUE THREAD

**Issue by emmats** [RobertsLab/resources#122]
I need to make a fasta file of sequences from bacterial taxonomic groups that one would expect to find in Taylor hatchery water. Any candidates? I can go through the literature and choose them, but I am wondering if anyone has information on the Taylor hatchery more specifically.

**Comment by sr320** [comment]
Not specifically but  here are some resources...

Metagenomic Profiling of Microbial Composition and Antibiotic Resistance Determinants in Puget Sound
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0048000

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Metagenomic_Profiling_of_Microbial_Composition_and_Antibiotic_Resistance_Determinants_in_Puget_Sound_1FBB4682.png" alt="Metagenomic_Profiling_of_Microbial_Composition_and_Antibiotic_Resistance_Determinants_in_Puget_Sound_1FBB4682.png"/>

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/PubMed_Central__Figure_2__PLoS_One__2012__7_10___e48000__Published_online_2012_Oct_29__doi_ _10_1371_journal_pone_0048000_1FBB4742.png" alt="PubMed_Central__Figure_2__PLoS_One__2012__7_10___e48000__Published_online_2012_Oct_29__doi_ _10_1371_journal_pone_0048000_1FBB4742.png"/>

Metagenome Sequence Accession

Sequence data for the Puget Sound dataset is available through the Metagenomics RAST (MG-RAST) server (http://metagenomics.anl.gov/) under the MG-RAST identification numbers 4460178.3, 4460179.3, 4460180.3, 4460182.3, 4460188.3, 4460189.3 and 4460190.3.



---

Metagenomic 16S rRNA Sequencing Analysis of Pacific Oyster (Crassostrea gigas) Microbiota from the Puget Sound Region in the United States
http://genomea.asm.org/content/5/23/e00468-17.full

>>This is the first study analyzing Pacific oyster microbiota in the Puget Sound estuarine system using a next-generation sequencing method. Taxonomic analysis indicated that Tenericutes, Chlamydiae, Proteobacteria, and Firmicutes were the most abundant phyla. Small numbers of operational taxonomic units (OTUs) belonging to the Vibrio genus were detected in all the oyster microbiome samples.
Accession number(s).Raw sequences were deposited to the NCBI SRA database under accession no. SRP075291. Filtered and assembled sequences are also publicly available on the MG-RAST server under the project ID mgp15218 and MG-RAST ID mgm4666675.3 to mgm4666698.3.

**Comment by emmats** [comment]
That should be a good start. Thanks!
