### ISSUE TITLE
Inquiry about Manila clam DNA

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#1221]
Question from @mfisher5. Do we have any Manila clam tissues/DNA she could potentially use? 

> I'm venturing into the shellfish world to do some DNA metabarcoding of green / Dungeness crab stomachs, and was hoping to connect with someone in Steven's lab who has worked with Manila clam. Even though I'll be using nonspecific COI primers to get a broad description of diet, one of the big questions around green crab is whether they are consuming any Manila clam - so I would like to  test my nonspecific primers on some Manila clam DNA. I was talking to Michelle McCartha this morning about her attempt at a TaqMan assay for Manila clam with Steven / Bonnie Becker, and learned that she was working with Steven for that work. Instead of my doing a single extraction, my hope is that a spare DNA sample  may still be floating around Steven's lab. Do you have an idea of who in Steven's lab has worked on Manila clam in the past, and what Steven's personal / lab policy is around sharing DNA outside of the lab?

**Comment by kubu4** [comment]
Check -80C inventory.

**Comment by kubu4** [comment]
>  Instead of my doing a single extraction, 

Also, doing the extraction will be faster/easier then having us search for samples and then coordinating a hand-off of some sort.

**Comment by sr320** [comment]
Not sure that assay was Manila - but we did do Manila many years ago.. though we would likely only have RNA.

My suggestion, like Sam, would just have them grocery store > extraction.
