### ISSUE TITLE
Issue running bedtools in Jupyter

### ISSUE THREAD

**Issue by mattgeorgephd** [RobertsLab/resources#1229]
I'm trying to get bedtools to run in a jupyter notebook and I've having some trouble. I think my main issue is I don't quite understand how all the environments are interacting, but more on that later.

I'm running on a Windows machine - bedtools only works on linux/macOS. I have followed the installation instruction for bedtools found here: https://bedtools.readthedocs.io/en/latest/

I started by opening up bash, downloaded the package, and then compiled using gcc:

>$ wget https://github.com/arq5x/bedtools2/releases/download/v2.30.0/bedtools-2.30.0.tar.gz
>$ tar -zxvf bedtools-2.30.0.tar.gz
>$ cd bedtools2
>$ make

This worked well, and then I moved the bin files I generated to my usr/ directory and made it executable:

>$ cp /mnt/c/WINDOWS/system32/bedtools2/bin usr/local/bin
>$ sudo chmod a+rx usr/local/bin/bedtools

From here, I can call bedtools in bash and it works great.

The issue I get is when I try and call the executable files within a python notebook, I get an error that states that which ever file I designate in the bin folder is not a recognized command:

![Screenshot 2021-06-02 12 14 09](https://user-images.githubusercontent.com/70529576/120539150-3071a200-c39c-11eb-9fe6-bde232f41cb6.png)

I had similar issues when I first started running bash commands in Jupyter, but was able to fix this by installing POSIX.

**Comment by sr320** [comment]
@kubu4 Is there value in setting up Linux within Windows?

**Comment by kubu4** [comment]
Per @sr320 , you'll need/want to install and use the Linux Subsystem for Windows. There should be some GutHub Issues and/or Slack conversations regarding how to install.

**Comment by mattgeorgephd** [comment]
I've seen some mention of using cygwin (https://www.cygwin.com/) on forums, but after installing I'm a bit lost. I'll take a look through some of the past github issues.

**Comment by kubu4** [comment]
Follow instructions here: https://ubuntu.com/wsl

**Comment by mattgeorgephd** [comment]
The Linux Subsystem works great. Thanks Sam!
