### ISSUE TITLE
Mettler Toledo Titrator DT1000 temp probe

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#123]
Provide attached quote to Lisa Smith when submitting SAFS purchasing form.

Quote is for $415.71.
[sq320773540 bs_mhm UofWA PT1000.pdf](https://github.com/RobertsLab/resources/files/1471775/sq320773540.bs_mhm.UofWA.PT1000.pdf)

Please get budget(s) from @sr320.

**Comment by sr320** [comment]
61-1553
