### ISSUE TITLE
Upgrade the NASs with NICs

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1234]

**Comment by kubu4** [comment]
What are you thinking here? Upgrading them to 10Gbps NICs? If so, we'll need Michael Parker to upgrade the ethernet switches, as they are "only" 1Gbps switches.

Regardless, the NICs in all of the Synology NAS are already 1Gbps (possible Gannet has 10Gbps NIC?).

**Comment by sr320** [comment]
Then lets maybe first investigate why speed is not going above 100MB if in fact the NIC is >1Gbps.

**Comment by kubu4** [comment]
Ah. So, 100MB/s is ~ the same as 1Gbps.

MB = megabytes

Gb = giga _bits_ (_not_ bytes).

Technically, 1Gbps = 125MB/s, but that's the theoretical conversion, which doesn't account for other network traffic/latency stuff.

**Comment by kubu4** [comment]
I know this is closed, but I just noticed something related to this that I'll add here for posterity.

Transfers from Owl are _significantly_ faster when "pulling" from a remote location. E.g. Using `rsync` to move data from Owl to Mox is ~5x faster if the `rsync` command is initiated on Mox...

**Comment by kubu4** [comment]
Never mind! The info in the above post does _not_ hold true!

Even more strange is that I was transferring files _from the same directory_ to Mox (one initiated on Mox and the other initiated on Owl) and they exhibited that difference in speeds. However, I decided to kill the slow sync and initiate from Mox, but the speeds were still slow! From the same exact directory on Owl.

**Comment by kubu4** [comment]
Haha, well, I take back my _last_ message! Initiating from Mox does indeed have an average of ~5x transfer speeds from Owl!
