### ISSUE TITLE
Cannot create Rmd on Rstudio server (raven)

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1236]
get the following

<img width="373" alt="image" src="https://user-images.githubusercontent.com/4442039/121910741-f382a500-cce3-11eb-9dc9-9b72c79bcf2e.png">

and not sure what getOption refers to.

**Comment by kubu4** [comment]
This is likely related to Microsoft Open R and the CRAN snapshot that's currently loaded. Let me work on this...

**Comment by sr320** [comment]
Can you remind me why we are running Microsoft?

**Comment by kubu4** [comment]
> Can you remind me why we are running Microsoft?

It runs R multi-threaded (unlike standard R).

**Comment by kubu4** [comment]
I've installed `rmarkdown 2.8`. Restart your R session and see if you can access it.

If not, do the following:

1. [Download this file](https://cran.r-project.org/src/contrib/rmarkdown_2.8.tar.gz) to the following directory:

`~/R/x86_64-pc-linux-gnu-library/4.0`

2. Install via RStudio GUI:

![image](https://user-images.githubusercontent.com/4514104/121914798-73f6d500-cce7-11eb-8121-3862a17e88c8.png)

Then use the `Browse...` button to find that file in that directory and click the `Install` button.

**Comment by sr320** [comment]
thanks that worked.

**Comment by kubu4** [comment]
> Can you remind me why we are running Microsoft?

Also, Microsoft Open R is setup to be more reproducible. It utilizes a CRAN snapshot system. This way, any time you're using it, you're only using packages that were available on CRAN at the time of the snapshot. In this case, Microsoft Open R defaults to a CRAN snapshot from July 2020. 

To change the snapshot date, you need to use the `checkpoin()` library and specify the desired CRAN date.

So, these two things allow a user to keep track of which packages they were using at any given time.

Of course, installing the `rmarkdown` package the way we just did breaks this system...

**Comment by sr320** [comment]
related what about 

```
Warning in install.packages :
  package ‘methylKit’ is not available (for R version 4.0.2)
``` 

can we run two versions of R?

**Comment by sr320** [comment]
going down `BiocManager` path.. this might work..

**Comment by sr320** [comment]
no go - will start new issue
