### ISSUE TITLE
Characterize larval and juvenile geoduck transcriptomes

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1241]
Take our RNA-seq data, map onto genome, and describe the gene repertoire expressed at different stages.

Step 1: ID all relevant datasets

Step 2: QC data

Step 3: Map to genome to get expression / count data.

Step 4: Functional annotation of genes

**Comment by ocattau** [comment]
I now have my output file with count data and an index file, I documented it in my notebook. What is the next step?

**Comment by ocattau** [comment]
Here is my latest output https://github.com/ocattau/ocattau.github.io/blob/master/_posts/2021-12-11-goslims.md
