### ISSUE TITLE
Describe provenance of Geoduck RNA-seq on NCBI SRA

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1247]
Thinking about geoduck RNAseq (NS and Hiseq) provide a description of the relationship of
https://sr320.github.io/Illumina-Summary/

to what is on SRA - (Notebook post is fine and likely already exists :)

**Comment by kubu4** [comment]
Notebook entry is here:

https://robertslab.github.io/sams-notebook/2016/12/21/sample-submission-geoduck-tissue-gdna-for-illumina-pilot-sequencing-project.html

The TL;DR is that we sent tissue to Illumina and they did everything else. All tissue from single geoduck.

**Comment by sr320** [comment]
Thanks! I am looking for how to match these with SRAs

**Comment by kubu4** [comment]
I don't think I understand fully what you're looking for. The info is in nightingales spreadsheet.

**Comment by kubu4** [comment]
![image](https://user-images.githubusercontent.com/4514104/124955676-12671500-dfcc-11eb-8032-15fa40214ee2.png)

**Comment by kubu4** [comment]
The last column in the screencap above is the SRA BioProject accession.

**Comment by kubu4** [comment]
Sorry for being a dolt (still getting my head into "work mode"). I just realized what you're looking for! BRB...

**Comment by kubu4** [comment]
Do you want accessions which lead to this NCBI page (NCBI "Run"):

![image](https://user-images.githubusercontent.com/4514104/124971248-cfae3880-dfdd-11eb-8a55-8fbfdb92e78c.png)


or do you want accessions which lead to this NCBI page (NCBI "Accession"):

![image](https://user-images.githubusercontent.com/4514104/124971400-fa988c80-dfdd-11eb-9324-35ee9a1c9c8c.png)

**Comment by kubu4** [comment]
Or, this NCBI page (NCBI "Run Selector"):

![image](https://user-images.githubusercontent.com/4514104/124971646-4e0ada80-dfde-11eb-8494-636f95b2da7f.png)

**Comment by kubu4** [comment]
Now that I've posted all that above,  I'll just put together a notebook which links to each one! How about that??!!  :)

**Comment by kubu4** [comment]
New notebook entry is below. Let me know if you want me to make any changes.

https://robertslab.github.io/sams-notebook/2021/07/12/Summary-Geoduck-RNAseq-Data.html

**Comment by sr320** [comment]
So cross-referencing with https://sr320.github.io/Illumina-Summary/

looks like

NR-21-Larvae-d5
and
Geoduck-larvae-day5-RNA-EPI-99

are not in SRA?

**Comment by kubu4** [comment]
They are. I just neglected to incorporate them... Sorry!

**Comment by sr320** [comment]
Could you also go ahead and list seq platform in the table also?

**Comment by kubu4** [comment]
Update has been pushed. Might take a few mins to update.
