### ISSUE TITLE
Trim and identify isoforms in Yaamini's C.virginica data

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1249]

**Comment by kubu4** [comment]
@sr320  StringTie files are here:

https://gannet.fish.washington.edu/Atumefaciens/20210716_cvir_stringtie_GCF_002022765.2_isoforms/

Each sample has the following sets of associated files:

- `cov_refs.gtf`: GTF of fully covered transcripts which match the _C.virginica_ reference genome.
- `.gtf`: GTF of all transcripts/isoforms identified by StringTie in _C.virginica_ reference genome.
- `.sorted.bam`: Sorted BAM file of alignments.
- `.sored.bam.bai`: Corresponding BAM index file.

I'll get a notebook post up soon.

**Comment by kubu4** [comment]
Never mind! Caught an error. I've edited the above post to remove the link to the files. Will update with new link when error is resolved.

**Comment by kubu4** [comment]
Alrighty, this has completed (properly) and I've provided the updated URL in the [post above](https://github.com/RobertsLab/resources/issues/1249#issuecomment-883387983).

Also, I noticed something when glancing at the data. Alignment rates are consistently low/lower in _males_, compared to the _females_. Not sure of what this means, but figured I'd share it.

Here's a table. The letter `M` or `F` in the sample name column indicates sex.

| Sample | Overall Alignment Rate |
|--------|------------------------|
| S23M   | 16.51%                 |
| S48M   | 19.93%                 |
| S13M   | 20.66%                 |
| S6M    | 22.04%                 |
| S9M    | 24.54%                 |
| S12M   | 26.33%                 |
| S7M    | 28.05%                 |
| S59M   | 38.13%                 |
| S31M   | 38.90%                 |
| S54F   | 39.25%                 |
| S29F   | 39.57%                 |
| S52F   | 41.24%                 |
| S53F   | 41.60%                 |
| S64M   | 42.08%                 |
| S41F   | 43.26%                 |
| S35F   | 43.95%                 |
| S36F   | 44.49%                 |
| S22F   | 45.04%                 |
| S39F   | 45.80%                 |
| S44F   | 45.89%                 |
| S19F   | 46.90%                 |
| S76F   | 47.24%                 |
| S50F   | 47.80%                 |
| S3F    | 48.89%                 |
| S16F   | 50.29%                 |
| S77F   | 50.31%                 |

**Comment by yaaminiv** [comment]
I remember Zymo saying that the RNA samples were all somewhat degraded when they were received. My guess is that the low alignment rates in males could be because the sperm RNA degraded faster.

**Comment by kubu4** [comment]
That seems like an obvious explanation. However, trimming also removes low-quality reads. So, even if initial RNA was degraded, I'd only expect the degradation to impact library creation and/or potential number of reads. 

Since alignments were performed post-trimming, the only reads left should be the good ones (i.e. ones that would be expected to align).

The other aspect of this, of which I don't know anything about, is whether or not these alignment percentages (for all the samples; not just M vs F) are expected when aligning RNAseq to a genome...
