### ISSUE TITLE
crab tissue/RNA to send to Justin at USGS? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1251]
Justin Greer (a collaborator of Maya Groner's) is wondering if we have any tanner crab tissue or RNA that he can use. He's starting a project and is wanting to test out primers. 

I know Pam brought over tissue samples, and I also know that there's quite a bit of extracted RNA from my stuff in the -80. I just wanted to ask first, because I'm not sure what @afcoyle wants to use. 

I'm working on cleaning up some box maps of what the samples in the -80 are. Here's a link, it's a bit messy currently, but here's a google sheet of what's in the -80 (I did not include boxes with the supernatant): https://docs.google.com/spreadsheets/d/1i0cFOEM-v67zSenz3ouM-aqXXM8nm28ujHGNqlBe7L0/edit?usp=sharing

**Comment by afcoyle** [comment]
At the moment I don't have any plans in particular for the tissue samples, but I also haven't really thought about possible uses. Would love to chat about that sometime soon (maybe during/after the qPCR chat that'll hopefully be sometime this week?)
