### ISSUE TITLE
how to get around Mac OS 'sudo access' problem

### ISSUE THREAD

**Issue by ocattau** [RobertsLab/resources#1255]
I am attempting to reinstall all the programs I lost when my laptop got stolen this week. I already have homebrew installed via the command line, but now I am trying to install kallisto with Jupyter with

 \`\`\`!ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"\`\`\`\

- [ Warning: The Ruby Homebrew installer is now deprecated and has been rewritten in
Bash. Please migrate to the following command:
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

==> Checking for `sudo` access (which may request your password).
Password:] 

In Jupyter notebooks, I cannot enter my password because it would be in a separate line of code which doesn't work when I type in my password. It does work if I use the command line but I would like to figure out how to install things from Jupyter and not always the command line. Has someone already had to deal with this?

**Comment by sr320** [comment]
Generally speaking I would not use Jupyter to install - as you point out, you cannot interact with pw.
Use command-line to install.
