### ISSUE TITLE
Send out oyster samples for histo

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1267]
Diploid / Triploid

Time 0 - about 15 each

**Comment by mattgeorgephd** [comment]
To embed, mount, section, and H&E stain 6 cassettes (24 oysters, 4 gonad sections per cassette) will be $103.20 through UW Pathology. Request form is attached.  

[20210910_PRS_Work_order_form.xlsx](https://github.com/RobertsLab/resources/files/7146604/20210910_PRS_Work_order_form.xlsx)

@sr320 - which budget number should we use?
@kubu4 - as you have submitted samples before, could you look over my order form and make sure everything is correct?

**Comment by sr320** [comment]
62-2795

**Comment by mattgeorgephd** [comment]
Samples submitted to PRS
