### ISSUE TITLE
Determine if SAFS has spec to you in physiology assays

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1268]

**Comment by kubu4** [comment]
I'm 99% certain the plate reader we have in FTR228 can handle kinetic assays. However, I can't currently remember what filters are available for measuring various wavelengths. You'd have to check the plate reader and see what's currently installed and what extra filer we have.

**Comment by mattgeorgephd** [comment]
As an update to this: The plate reader in FTR228 can run kinetic, but only for 10 min. It also does not have a filter that is in the 400 nm range.

**Comment by kubu4** [comment]
Bummer about the filers (you checked both, correct?).

Also, the manual doesn't indicate a 10min limit for an kinetic assay. It _does_ indicate that the maximum time _between_ measurements is 10mins...:

> You can give the number of repeat measurements (up to 100) and the delay between each measurement (0 to 600 s). You need to also select the label by clicking the label button and then selecting from the label dialogue.

**Comment by mattgeorgephd** [comment]
Ahh, ok - thank you for the clarification.

Yes, I checked all the filters that were with the machine, as well as the old run log to see if anyone had run one within the desired range.

Given that the machine might be able to handle the kinetic assay - would it be possible to order a filter? I couldn't find a 412 nm on the website (https://www.perkinelmer.com/category/filters-filtration-products)

**Comment by kubu4** [comment]
Presumably you can put any desired light filter that fits into the slots of either of the filter slides. I don't know the specifications (i.e. diameter of the slots in the filter slides).

I believe there's also a filter "wheel", but can't totally remember (haven't used it in years, and used infrequently when I did use it).

I'll shoot an email to Chris Monson and see if he can remember more about it. I think he was using it with some regularity in late 2019. I'll report back.

**Comment by kubu4** [comment]
Response from Chris:

> Hi Sam, 
The plate reader currently has the excitation filters: F355 nm, F485 nm, P405 nm, P450 nm, P490 nm, and emission filters: F460 nm, F535 nm, D545 nm, D572 nm, D615 nm, D642 nm, D665 nm installed. These are the ones that were there when I began using it. I installed an emission filter at 590+/-10 nm and an excitation filter at 555+/-38 nm as well. I'm not sure which filter slides they are on. The F-filters are for fluorometry, the D-filters are for time-resolved fluorometry, and the P is for photometry, from what I can tell.

That P405 filter is _extremely_ close to your assay's peak absorbance... I'd say do a test run with the standards or something and see how it it works. Virtually all of these assays (including qPCR fluorophores) actually absorb in a range of wavelengths. Anyway, I wouldn't be surprised if this works just fine.

**Comment by mattgeorgephd** [comment]
This is great news! A test of the P405 nm filter seems like it might be worth while. I was a little hesitant to use the 405 given we don't have the absorbance spectrum (I can't find it published anywhere, not sure how wide the band is) - so if the assay doesn't work it would be difficult to troubleshoot if it was the spec or reagents. Given we have extra tissue, it can't hurt to try. Thank you for reaching out to Chris @kubu4.

**Comment by kubu4** [comment]
My pleasure!
