### ISSUE TITLE
Adding buffer solutions to MyChem

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#127]
The only Mettler-Toledo buffer solution listed is pH 4.006

We have pH 4.01, 7.00, and 9.21.

Is it ok if I select the pH 4.006 and then in the note section say that we actually have 4.01, 7.00, and 9.21? All in one submission?
![screen shot 2017-11-15 at 2 17 33 pm](https://user-images.githubusercontent.com/14934314/32863288-cf72b496-ca0f-11e7-9c25-fcbcbfaf7309.png)

**Comment by kubu4** [comment]
If a chemical is not found, then you have to manually add it. Please do that, since an associated catalog number is useful.

**Comment by grace-ac** [comment]
Ah ok. I thought that would be the case, but I couldn't find a manually add option. 

Just discovered it is the "Chemical Not Found" button.
