### ISSUE TITLE
Assign unique-sample-id to all histology samples

### ISSUE THREAD

**Issue by afcoyle** [RobertsLab/resources#1270]
Delaney found in the handbook that there's a discrepancy between the histology sample instructions and the actual data table.

According to the [histology data management protocol](https://robertslab.github.io/resources/Data-Management/#histology-data-management-plan), all samples should be dealt with as follows:

`Each sample should have a unique-sample-ID which is: experiment-date_organism-label_tissue`

However, none of the samples in the [histology data table](https://docs.google.com/spreadsheets/d/1BIbDleJPEiKrmx7JwNIPwg2pM-thuZ39upmenldx4pA/edit#gid=0) have that unique-sample-ID. 

There's now a column for those unique-sample-ID values to be added to the data table! Generally, it should be pretty straightforward (concatenating a few columns). One complication: the unique-sample-IDs are also present in the image names at http://owl.fish.washington.edu/hesperornis/ with names assigned as follows:

 `[FULLTIMESTAMP]-[unique-sample-ID]-[magnification].jpeg` e.g. 20180924-angasi013-10x.tif

If those images are present for the sample, the unique-sample-id should match whatever convention is used for those image names so they can be cross-referenced

**Comment by drlawson** [comment]
@afcoyle working on completing this now! I see that there are 13 different images for "Angasi001," how do I know which image ID to choose? Also there seem to be 5 "O. angasi 1" rows in the histology database - do you think the unique-sample-ID should be the same or different for each of these 5 rows?

Also - if the tissue is missing in the histology database what would you suggest putting on the end of the unique-sample-id?

Let me know what you think, thank you!! :)

**Comment by afcoyle** [comment]
Honestly, I have no clue on any of those questions - I've done zero work with the histology data. I think @sr320 might be the person to ask on this one!

**Comment by laurahspencer** [comment]
Those Angasi histo images/slides are mine - there are multiple images from the same slide at different magnifications, capturing different locations on the slide, etc.

**Comment by drlawson** [comment]
@afcoyle All of the unique sample ids are updated, the image ids are added to the best of my ability but i was unable to match the o lurida images to the samples due to the naming used in the files - so i just put the link to the file in the image_id column :)
