### ISSUE TITLE
Update Personnel Page 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1280]
@drlawson can you generally try to update...
and @ocattau, @AHuffmyer, and @ChrisMantegna can add profiles.

edit https://github.com/RobertsLab/website/blob/master/People.md

**Comment by AHuffmyer** [comment]
Can do! @drlawson would you like us to send you our bio .md text or directly add to the People.md file?

**Comment by drlawson** [comment]
Adding to the people.md file should be fine! :)

**Comment by sr320** [comment]
@AHuffmyer you can just directly edit People.md

thanks!

**Comment by ocattau** [comment]
done!

**Comment by sr320** [comment]
believe just need @zbengt 's update to close out

**Comment by zbengt** [comment]
Sorry I spaced on this, finished! I think @ChrisMantegna just needs to add hers.
