### ISSUE TITLE
Re-run pH Calib on Titrator?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#129]
I changed the pH values from 4, 7, 10, to 4.01, 7, 9.21 in the method. 

Should I run the method to re-calibrate the pH sensor now?

OR 

Should I wait until Temperature sensor arrives and just focus on looking though the SOP?

**Comment by sr320** [comment]
Focus on SOP

**Comment by kubu4** [comment]
Updates to SOP should include information on pH probe storage procedures:

- temporary storage (i.e no longer than one week)
- medium term storage (i.e. no longer than one month)
- long term storage (i.e. > one month)

Will also need info on Rondolino settings (e.g. what setting to turn dial to for conditioning/rinsing).

**Comment by kubu4** [comment]
SOP will also need info on checking rinse water volume before beginning any procedures.

**Comment by grace-ac** [comment]
Is the "Burette Rinse" shortcut the method that purges the acid line of bubbles @kubu4 ? I didn't take notes while Brian was here. 
Hollie's SOP has something called "PURGE" which I'm assuming is what they named their shortcut.

**Comment by kubu4** [comment]
Yes.

**Comment by grace-ac** [comment]
Here's what I've done so far: https://github.com/RobertsLab/resources/blob/master/protocols/External_Protocols/OA-titration-updatingSOP 

I mainly focused on the first two sections. 
I don't think my pH storage information is completely accurate. 

I read through the last two sections and I can't visualize what the data will look like coming out of LabX, so I don't think I'll understand until I go through it when we re-calibrate.

- What is CRM? Is that their specific name for what they analyzed?
- Were we thinking of doing 50g OA samples rather than their 100g?

**Comment by kubu4** [comment]
I've renamed the file (appended ".md") so that markdown formatting is rendered on GitHub. Updated link is here: https://github.com/RobertsLab/resources/blob/master/protocols/External_Protocols/OA-titration-updatingSOP.md

**Comment by grace-ac** [comment]
Temperature Probe arrived today!

**Comment by grace-ac** [comment]
What are the "CRM"s in the protocol?

**Comment by kubu4** [comment]
CO2 Reference Materials.

They are bottles of sea water that have been precisely measured in regards to pH, alkalinity, and some other complicated ocean acidification type stuff.

They are currently stored in 228 near the titrator (the boxes should have a sticker with something like "Batch Number").
