### ISSUE TITLE
Surplus equipment in FTR 234

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1296]

**Comment by kubu4** [comment]
All lab equipment will need to be cleaned/decontaminated and then accompanied by this completed form:

https://www.ehs.washington.edu/system/files/resources/lab_equip.pdf

Then, contact Jon Wittouck about transfer to SAFS surplus closet.

**Comment by kubu4** [comment]
All lab equipment has been decontaminated and relocated to FTR212. Jon Wittouck is aware and coordinating pickup.
