### ISSUE TITLE
Update proposal database

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#13]
_From @sr320 on November 18, 2016 0:54_

Sort this https://github.com/sr320/LabDocs/blob/master/Proposal_database.md
in reverse chronological order and 
Add any not included....  (will have to chat about how to ID all non-funded...

_Copied from original issue: sr320/LabDocs#349_

**Comment by kubu4** [comment]
_From @grace-ac on December 6, 2016 22:58_

Sam taught me how to do this! sorted by date in reverse chronological order.

**Comment by kubu4** [comment]
_From @sr320 on December 6, 2016 23:5_

Now we have to update- I will get you that info soon

**Comment by kubu4** [comment]
_From @sr320 on December 9, 2016 18:43_

You seemed to have deleted half of them? 

this is what it was prior to edits.


| Agency                     | Year | Title                                                                                                                                              | Funded (y/n) | Linkout                                                                            |
|----------------------------|------|----------------------------------------------------------------------------------------------------------------------------------------------------|--------------|------------------------------------------------------------------------------------|
| EPA                        | 2009 | Integrated Approach to Assess Emerging Threats to Puget Sound Ecosystem Health                                                                     | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/EPA_Emerg2009.pdf)     |
| EPA                        | 2008 |                                                                                                                                                    | y            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/Gavery_EPA.pdf)        |
| EVOS                       | 2009 | High Density DNA Sequencing to Detect Population Structure of Pacific Herring                                                                      | y            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/Exxon_Herring.pdf)     |
| JGI                        | 2008 | Genome Sequencing of Cycloclasticus pugetii, a Widely Distributed Marine PAH-Degrading Bacterium                                                   | y            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/JGI_2008.pdf)          |
| NIH                        | 2007 | Searching for Olfactory Receptor Genes                                                                                                             | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/NIH_2007.pdf)          |
| NOAA                       | 2013 | Using Shotgun Proteomics to Obtain Hemolymph Markers for Determining Sex and Stage of Gonad Maturation in Oysters                                  | -            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/Proteomic_CgRepro.pdf) |
| NOAA                       | 2007 | Sea scalllops as sentinels of deepwater pollution                                                                                                  | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/COHH_Scallop.pdf)      |
| NOAA Aquaculture           | 2013 | Alleviating Regulatory Impediments to Native Shellfish Aquaculture                                                                                 | y            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/OlyNOAA_2013.pdf)      |
| NOAA ODRP                  | 2007 | Oyster Herpes Virus: Understanding Differential Susceptibility, Transmission Dynamics and Host-Pathogen Interactions                               | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/OSRP_2007.pdf)         |
| NOAA Saltonstahl Kennedy   | 2008 | Threats to Bivalve Aquaculture and Fisheries: The Influence of Emerging Diseases and Environmental Change                                          | y            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/OA_NOAA_SK.pdf)        |
| NPRB                       | 2008 | Regulation of diapause in Neocalanus                                                                                                               | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/NPRB_Copepod.pdf)      |
| NRAC                       | 2005 |                                                                                                                                                    | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/NRAC_QPX2005.pdf)      |
| NSF                        | 2012 | DNA methylation as a mechanism to increase adaptive potential in invertebrates                                                                     | y            | [FigShare](http://dx.doi.org/10.6084/m9.figshare.97107)                                        |
| NSF                        | 2010 | Climate Change and Sea Fan Resistance to Disease: Assessing the impacts of temperature and acidification on cnidarian immunity using genomic tools | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/NSF_Coral_2010.pdf)    |
| NSF                        | 2010 | Ecosystem Effects and Biological Responses to Crude Oil Contamination of Apalachicola Bay, Florida                                                 | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/NSF_OilResp.pdf)       |
| NSF                        | 2010 |                                                                                                                                                    | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/NSF_OA2010.pdf)        |
| NSF                        | 2010 | Exploring the Determinants of Microbial Diversity on Aquatic Organic Aggregates                                                                    | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/NSF_Biodiv.pdf)        |
| Royalty Research Fund (UW) | 2010 | Sequencing-based approach for characterizing DNA methylation in the Pacific oyster (Crassostrea gigas)                                             | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/RRF_Cg_Epi2010.pdf)    |
| Royalty Research Fund (UW) | 2010 | Salmon senescence as a model for aging                                                                                                             | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/RRF_Senesc2010.pdf)    |
| Royalty Research Fund (UW) | 2013 | Maturation processes in the marine mollusc, Panopea generosa                                                                                       | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/RRF_Geoduck2013.pdf)   |
| Royalty Research Fund (UW) | 2009 | Proteomic response of Pacific oysters to environmental stress                                                                                      | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/RRF_Prot2009.pdf)      |
| USDA                       | 2004 | Characterization of Gonadal Differentiation and Isolation of Factors Involved in Reproductive Development in Marine Bivalves                       | n            | [FigShare](http://dx.doi.org/10.6084/m9.figshare.97672)                                        |
| USDA                       | 2004 | Functional Genomics of Agriculturally Important Organisms                                                                                          | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/USDA_Fun_2004.pdf)     |
| USDA                       | 2011 | Epigenomic Variation In The Pacific Oyster                                                                                                         | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/USDA_Cg_Epi2011.pdf)   |
| USDA                       | 2005 | The role of myostatin in shellfish growth                                                                                                          | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/USDA_shell_myo.pdf)    |
| USDA                       | 2002 | Isolation and characterization of factors regulated during larval competence and metamorphosis in the bay scallop, Argopecten irradians            | y            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/USDA_postdoc.pdf)      |
| USDA-NRSP8                     | 2014 | Resource coordination workshops focused on oysters and other shellfish            | y            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/NRSP8_Oyster.pdf)      |
| UW                         | 2009 | Managing Puget Sound Ecosystem Health: A Natural and Human Dimensions Approach                                                                     | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/EnvIns_Social.pdf)     |
| Washington SeaGrant        | 2014 | Crossbreeding and Selection for Resistance to Ocean Acidification in Pacific Oysters                                                               | y            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/DavisWSG_2014.pdf)     |
| Washington SeaGrant        | 2009 | Effects of ocean acidification on declining Puget Sound molluscan calcifiers                                                                       | y            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/OA_WSG_2009.pdf)       |
| WH SeaGrant                | 2007 | Characterizing the Ecology of Roseovarius crassostreae, the Causative Agent of Juvenile Oyster Disease                                             | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/WHSG_JOD.pdf)          |
| WH SeaGrant                | 2009 | Integrated biological approaches to assessing the effects of ocean acidification                                                                   | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/WHSG_OA.pdf)           |
| WH SeaGrant                | 2007 | Impact of microbial community composition and temperature on Vibrio parahaemolyticus                                                               | n            | [PDF](http://eagle.fish.washington.edu/trilobite/Proposal_Database/WHSG_COHH_vibrio.pdf)  |

**Comment by kubu4** [comment]
_From @grace-ac on December 9, 2016 18:50_

yup - accidentally only copy and pasted half of the table! fixed now!

**Comment by kubu4** [comment]
_From @sr320 on December 20, 2016 18:14_

Now there are links missing :)

**Comment by kubu4** [comment]
_From @grace-ac on December 20, 2016 18:46_

The links are there! I just checked. The database that's in lab docs https://github.com/sr320/LabDocs/blob/master/Proposal_database.md

**Comment by kubu4** [comment]
_From @sr320 on December 20, 2016 18:52_

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/LabDocs_Proposal_database_md_at_master_·_sr320_LabDocs_1E09B55E.png" alt="LabDocs_Proposal_database_md_at_master_·_sr320_LabDocs_1E09B55E.png"/>

**Comment by kubu4** [comment]
_From @grace-ac on December 20, 2016 18:56_

Oh weird, just the one is missing- i get it :)

**Comment by kubu4** [comment]
_From @sr320 on December 20, 2016 18:58_

Well quite a few... 
see https://github.com/sr320/LabDocs/issues/349#issuecomment-266089266
for what it was.

Not big deal at all, just some flaw in how it is being edited...

**Comment by kubu4** [comment]
_From @grace-ac on December 28, 2016 21:18_

Should finally be correct: https://github.com/sr320/LabDocs/blob/master/Proposal_database.md

**Comment by kubu4** [comment]
_From @sr320 on December 28, 2016 22:51_

Please add  a few more...

Awards Title: A novel proteomic-based approach to identify and mitigate factors responsible for shellfish mortality events
Source of support: Washington Sea Grant
2018

 Title: Assessing the capacity for evolutionary adaptation to ocean acidification in geoduck
Source of support: NOAA OA Program
2018

 Title: Developing genomic resources to support restoration and protection of the Olympia Oyster in Puget Sound
Source of support: JISAO - NOAA
2017

Title: Using satellite pop-up tags to track movements of sablefish during spawning and changes in vertical position in the water column
Source of support: NOAA
2017

Title: Sablefish Reproductive Life History and Genetics Source of Support: NOAA / JISAO Award 
2013


These are funded.

**Comment by kubu4** [comment]
_From @grace-ac on December 28, 2016 23:15_

Updated:
https://github.com/sr320/LabDocs/blob/master/Proposal_database.md

**Comment by kubu4** [comment]
_From @sr320 on January 3, 2017 18:11_

I need to get pdfs and ID rejected proposals...

**Comment by sr320** [comment]
done for now
