### ISSUE TITLE
ID lncRNAs in RNA-seq data set

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1302]
data: https://github.com/hputnam/Express_Compare

**Comment by sr320** [comment]
see
https://nf-co.re/lncpipe
https://link.springer.com/content/pdf/10.1007%2F978-1-4939-9045-0_13.pdf

**Comment by zbengt** [comment]
Just checking my understanding of where to start with the express compare data. The raw data has already been processed through HISAT and Kallisto. Is the idea for me to take data from the HISAT processing, filter for length >200, and then use Kallisto for classification and quantification?

**Comment by sr320** [comment]
For this the raw reads would first need to be assembled.

**Comment by sr320** [comment]
pretend like all you have is raw data

**Comment by sr320** [comment]
> Located on Putnam Lab Bluewaves under /data/putnamlab/erin_chille/Express_Compare. Need access.

Data is available at NCBI. download from there and ID lncRNA.  see https://github.com/hputnam/Express_Compare

**Comment by zbengt** [comment]
Think I locked myself out of Gannet by accident. Got this "kex_exchange_identification: read: Connection reset by peer
Connection reset by 128.95.149.52 port 22" after 3 password mistakes (forgot that second scallop)

**Comment by sr320** [comment]
Maybe work on Raven (Rstudio) in mean time

**Comment by kubu4** [comment]
@zbengt DM me your IP address via Slack and I'll unblock you from Gannet.
