### ISSUE TITLE
Find rDNA Array in oysters

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1304]

**Comment by mgavery** [comment]
This is not consistent with Xu et al. (2001), which says 1 chrom, but still confusing to me.  Most of the rRNA in the gtf are 5s rRNA and not sure what Xu et al. probed for? I don't think it was 5s.  Why the heck is the nomenclature of this stuff so annoying!?!?!
[01XurDNAFISHVeliger.pdf](https://github.com/RobertsLab/resources/files/7312955/01XurDNAFISHVeliger.pdf)
?!

**Comment by mgavery** [comment]
Ok, I think I'm getting closer.  The 5s is a separate from the major rDNA array - There is one chromosome (Chr 9) that has an annotation of "large", "5.8" and "small" rRNA.  I think this is this one..

**Comment by mgavery** [comment]
Towards getting single copy gene regions - GIles ran BUSCO (mollusca database)on the Roslin genome.  One of the outputs is the genomic locations of single copy genes.  I've attached the bed file of single copy regions (to use for normalization of copy number) as well as a short summary and the full table from bus
[single_copy_busco.mollusca.bed.txt](https://github.com/RobertsLab/resources/files/7515450/single_copy_busco.mollusca.bed.txt)
[short_summary.txt](https://github.com/RobertsLab/resources/files/7515452/short_summary.txt)
[full_table.tsv.zip](https://github.com/RobertsLab/resources/files/7515458/full_table.tsv.zip)

**Comment by mgavery** [comment]
We have a start then for the location of the mito, rRNA and single copy genes.  The next step would be to get ahold of a few WGS datasets for gigas, map to the genome + mito and take a look.  Is there small variation in the single copy regions? What does copy # look like for mito and ribo?

**Comment by mgavery** [comment]
Giles mapped 20 WGS C.gigas samples (from NCBI/SRA) to the Roslin genome, then used bedtools "coverage" to get depth at each bp for the single copy genes identified using BUSCO.  One of the 5087 genes was an outlier in terms of coverage, but after filtering that gene the coverage was pretty normally distributed across the 5086 genes.  

This plot is showing mean depth of coverage for each of the 5086 genes per individual (ID is how they were ID'd in SRA. 
[meanCov_singlecopyGenes_Cgigas.pdf](https://github.com/RobertsLab/resources/files/9365158/meanCov_singlecopyGenes_Cgigas.pdf)

**Comment by mgavery** [comment]
box plot of same data
![BoxPlot_meancovbygene](https://user-images.githubusercontent.com/4512578/185214922-8a16dd89-33a3-4d03-860f-db980b419716.png)

**Comment by mgavery** [comment]
The next step will be to do the same thing for the mitochondrial genes and the ribosomal genes.

Ultimately, the single copy depth (mean across all genes) will be used as the denominator and either the ribo or mito depth will be the numerator.  Then we can look at copy number variation of these regions across the 20 individuals.

**Comment by mgavery** [comment]
There were 62 milllion basepairs covered by the 5087 single copy genes.  These depth files per bp are really big.  I think it's good to start with our hypothesis driven question (mito and ribo CNV), but might be totally useful to look at other regions.  One strategy would be to peruse some bam files in a genome browser for places with crazy depth first and target those regions.

**Comment by mgavery** [comment]
<img width="1133" alt="Plot_Zoom" src="https://user-images.githubusercontent.com/4512578/189974829-42e5e4b1-b303-43f5-b516-4fd29c540219.png">

**Comment by mgavery** [comment]
@sr320 , can you provide access to bam files for WGBS data? I can run pipeline on them

**Comment by sr320** [comment]
@yaaminiv can you point Mac to the bam files for your Haws data which I am presuming is gigas WGBS..

**Comment by yaaminiv** [comment]
@mgavery Can be found at this link! https://gannet.fish.washington.edu/spartina/project-oyster-oa/Haws/bismark-2/
