### ISSUE TITLE
Analyze Oyster gonad Histo slides

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1308]

**Comment by sr320** [comment]
coordinate with @mattgeorgephd for details.

**Comment by mattgeorgephd** [comment]
Hi @drlawson. I placed the samples on the shelf above the desk in the back of FTR 209. Here is a picture of the box and a slide diagram.

![20211008_095518](https://user-images.githubusercontent.com/70529576/136712062-cdfa6c87-b12c-4e4d-9fb3-2f7705004db2.jpg)

![histology_cassette_diagram](https://user-images.githubusercontent.com/70529576/136712063-0dd421be-c1bd-4807-8392-a127965c4569.jpg)

**Comment by drlawson** [comment]
@mattgeorgephd https://drlawson.github.io/Updated-Oyster-Pics-for-Matt/ here is my notebook entry containing important images, links to all the images I took, and the link to the staging sheet for the samples. Let me know what you think/if you need anything else from me :)

**Comment by mattgeorgephd** [comment]
@drlawson Thanks for your help on this! Your analysis and notebook entry were great! 

We might have some more samples sectioned in the future - I'll keep you posted when/if we get samples back.

**Comment by mattgeorgephd** [comment]
Hey @drlawson! We have received a second batch of histology slides (n=37) for analysis if you are up for it. The samples are oyster gonad, in the same orientation as the previous set.

Here is a picture and slide diagram. I will leave them in FTR 209 on the shelving in the back, right-hand corner.

![picture](https://github.com/mattgeorgephd/NOPP-gigas-ploidy-temp/blob/main/202107_EXP2/histology/2022-03-03%2012.02.24.jpg?raw=true)

![histology_cassette_diagram](https://user-images.githubusercontent.com/70529576/136712063-0dd421be-c1bd-4807-8392-a127965c4569.jpg)

**Comment by drlawson** [comment]
awesome! I'll swing by to pick these up friday or saturday :) do either of you @mattgeorgephd @sr320 know if the microscope I was using before is available for me to also take home? If not I'll write about it in the slack real quick. thanks!

**Comment by drlawson** [comment]
@mattgeorgephd just picked up the boxes and microscope - I left the box with the old samples in the lab :) I’ll start working on this this week!

**Comment by mattgeorgephd** [comment]
@drlawson I've added you as a collaborator on the NOPP-gigas-ploidy-temp repo. Please work within the [histology folder](https://github.com/mattgeorgephd/NOPP-gigas-ploidy-temp/tree/main/202107_EXP2/histology).

**Comment by drlawson** [comment]
hi @mattgeorgephd, I'm working on staging those samples. Instead of D and T like last time the samples have the letters N, M, R, and X. What do those signify? Which are diploid and which are triploid? I ask because I was using a slightly different staging method for triploids last time :) Thanks!

**Comment by mattgeorgephd** [comment]
@drlawson sorry for the confusion, here is the key.

M, N = diploid
R, X = triploid

**Comment by sr320** [comment]
@mattgeorgephd is this completed?
