### ISSUE TITLE
Resubmit Oly Gene Expression Paper

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#131]
What are the next steps and procedures for getting this done?

**Comment by kubu4** [comment]
Steps needed are here: https://github.com/RobertsLab/paper-Olurida-gene/issues/22

Biggest hurdle is fixing the map (or removing it??).

Need justification statement for adding Brent as author after initial submission.

Need to email editor and CC Brent. Then, Brent needs to reply to the editor to confirm author addition.

**Comment by sr320** [comment]
I will email editor and cc Brent with statement.

Go ahead and remove map.

**Comment by kubu4** [comment]
Once email exchange has been completed with editor, we can resubmit. Post here once that's been completed. Thanks!

**Comment by sr320** [comment]
Email exchange complete (I believe).

**Comment by kubu4** [comment]
Re-submitted.

**Comment by kubu4** [comment]
Accepted!

![selection_026](https://user-images.githubusercontent.com/4514104/34305598-cd8fe5e4-e6f3-11e7-9f0e-66abdcc24048.png)
