### ISSUE TITLE
R and GitHub no longer connected... 2FA required? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1340]
I got a new laptop  (YAY!!!!!!!), but now my R and Github are no longer connected... 

When I try to commit and push to my github repo from R, it makes me log in to GitHub from R, then it says: 

<img width="991" alt="Screen Shot 2021-11-08 at 11 05 25 AM" src="https://user-images.githubusercontent.com/14934314/140803257-60591797-826a-4f3b-8cf2-11cee2a1e5c2.png">

I went to the [link suggested](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication)... and it says a whole bunch of stuff about 2FA...  **Is 2FA required now to commit and push to my own github repo?**

I'll keep looking into this in the meantime

**Comment by sr320** [comment]
Need a personal access token
see https://github.com/RobertsLab/resources/discussions/1107

**Comment by grace-ac** [comment]
Ah! Thanks!!

**Comment by grace-ac** [comment]
I got a PAT, but I don't know where i'm supposed to put it in to get R to connect to Github... same issue is still happening where R is asking for my GitHub login, and then it tells me that same message that's in the screenshot above

**Comment by sr320** [comment]
Use your PAT as your password

**Comment by grace-ac** [comment]
oooooh got it. it worked! thanks!
