### ISSUE TITLE
any newer kits people like for RNA from cells?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1341]
I'm going to order some extraction kits for getting RNA from sea star coloemocytes that are preserved in RNAlater in -80. 

I'm thinking of sticking with the Zymo Quick DNA/RNA Microprep Plus Kit (link: [here](https://www.zymoresearch.com/products/quick-dna-rna-microprep-plus-kit)). 

Before I order, curious if anyone has another kit that they think would work better? I'm assuming I'm making a good choice with the zymo quick dna/rna since this project will be similar to the crab extractions I did.

**Comment by sr320** [comment]
could always try diff kits methods we have, and see what works best.. though imagine it will be similar to crabs..

Note before we just used Tri-Reagent https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0133053#sec002
