### ISSUE TITLE
Data Science organization in R studio

### ISSUE THREAD

**Issue by ocattau** [RobertsLab/resources#1343]
Here is an example of what my data from the larval geoduck sequencing looks like, I want to filter by est_counts (anything > 10) and then filter by protein name. The end goal is to annotate this table with candidate genes for gonad development. Is there a good program and/or visual representation of the data that would help me sort by important proteins? I can't manually go through all 1.5M genes so any help with large datasets in R would be helpful! 

<img width="1340" alt="Screen Shot 2021-11-10 at 11 00 04 AM" src="https://user-images.githubusercontent.com/81712104/141176400-bf2c468e-ba53-4b20-b040-151be9f06ac8.png">

**Comment by AHuffmyer** [comment]
How are you determining which proteins are "important"?

**Comment by AHuffmyer** [comment]
So the way I am interpreting this is that you want to filter by est_counts > 10 and then sort by protein name alphabetically? Tidy can definitely do this!

**Comment by ocattau** [comment]
I suppose the larger the est_counts the more important it would be, but at the same time the #1 hit is Craniofacial development protein 2 (p97 bucentaur protein) which I am not sure is very helpful. But yes something like tidy to sort this data as much as possible.

**Comment by AHuffmyer** [comment]
Cool, here is an example script you could play with. If there are more steps you would like to go through to sort/filter/name let me know!  

df%>%
  filter(est_counts>10)%>% #filter by est_counts greater than 10
  arrange(desc(est_counts)) #arrange list by greatest to least for est_counts

**Comment by sr320** [comment]
You need a bit more explanation of what an end product would look like..
Also post the url for the GitHub repo.. 

In `dpylr` you could `filter` by est_counts then

**Comment by ocattau** [comment]
https://github.com/ocattau/code

**Comment by sr320** [comment]
try a bit more organization, with `code`, `data`, and `analyses` directories. Readme file etc.. 
see https://sr320.github.io/course-fish274-2021/materials/project-structure/

**Comment by ocattau** [comment]
I am having issues with PAT right now but what I want to know if what is the next step? Do I manually go through all the different genes and look at their functions? Is there a program to do this?

**Comment by sr320** [comment]
Step 1 (after organizing repo) - create a table of GO terms found and count of each..
That would be done in R / Tidyverse.
