### ISSUE TITLE
PAXgene tissue fix: wrong order??

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#135]
I ordered PAXgene tissue fix. I used the same Cat. ID as @kubu4  did when it was ordered previously: 765312. Additionally, I double-checked the Cat. ID as well as sent Lisa a direct link to the product with the Cat. ID. https://www.qiagen.com/us/shop/sample-technologies/dna/genomic-dna/paxgene-tissue-fix-container-50-ml/#orderinginformation 

However, this is what arrived today. Two of these cylindrical containers. The packing slip says it's the same Cat. ID, and that it is PAXgene TissueFIX Cont. (50ml) Kit. 

![img_0195 2](https://user-images.githubusercontent.com/14934314/33042419-a47457fa-cdf6-11e7-9fc2-017555acd508.JPG)

Should I open this thing and see what's inside?

**Comment by grace-ac** [comment]
This is what's inside:
![img_0196 2](https://user-images.githubusercontent.com/14934314/33043594-d3ce2e32-cdfa-11e7-8d1c-4f88e94e5e45.JPG)

**Comment by sr320** [comment]
sure open

**Comment by grace-ac** [comment]
This is correct. I thought it came in a box, but the box is folded up inside and you have to open the cylinder to get to it.
