### ISSUE TITLE
RNA extraction for PSMFC-mytilus-byssus-pilot project

### ISSUE THREAD

**Issue by mattgeorgephd** [RobertsLab/resources#1352]
The lab experiments for the PSMFC mussel project are finished and we are ready to start RNA extractions.

@kubu4 - Below are some background on the project and the RNA extraction sample list. Let's setup a meeting this week or early next to discuss.

Useful links:
1. PSMFC-mytilus-byssus-pilot [Github Repo](https://github.com/mattgeorgephd/PSMFC-mytilus-byssus-pilot)
2. Summary of progress so far - [PSMFC semi-annual report](https://github.com/mattgeorgephd/PSMFC-mytilus-byssus-pilot/blob/main/reports/20211115_PSMFC_Semi-annual_report.pdf)
3. Sample list with -80C locations - [RNA extraction sample list](https://docs.google.com/spreadsheets/d/1PDVSGuCGeYQr6Rdl6u5M4L5vcQS1EgUQl7UjvLYDlBg/edit#gid=0)

**Comment by kubu4** [comment]
Can you provide more detail on RNA extractions? Specifically tissue preservation method (e.g. flash frozen, RNAlater, etc).

Also, the progress report suggests you collected multiple tissue types, but there aren't any tissues listed in that RNA extraction list. Please provide an explicit list of samples that need extracting (i.e. tube labels).

Does any tissue need to be saved or can/should all of it be used for RNA isolation?

Finally, do we have the necessary supplies for all of the high priority extractions?

**Comment by mattgeorgephd** [comment]
@kubu4 All good points. I've updated the [RNA extraction sample list](https://docs.google.com/spreadsheets/d/1PDVSGuCGeYQr6Rdl6u5M4L5vcQS1EgUQl7UjvLYDlBg/edit#gid=1588435954) that includes tube IDs and locations. 

As far as sampling went, a piece of the gill, a piece of mantle, and the entire foot from each mussel were flash frozen. Sample tubes were labeled with the mussel ID (e.g., G01) and the tissue type (-G, -M, or -F; e.g., G01-G). More tissue than will be necessary for extractions was collected. Please remove the necessary tissue for RNA extractions and save the remaining tissue for later DNA analysis.

We plan on starting by extracting RNA from the gill and foot tissue of a subset of animals from various treatments (labeled "High" priority in the RNA extraction sample list). There are 120 high priority samples.

The RNA extractions will be performed using our [RNAzol protocol](https://github.com/RobertsLab/resources/blob/master/protocols/rna_isolation_rnazol_rt.md) after homogenization using the handheld tissue grinder. We have more than enough materials on hand to complete the extractions (multiple unopened RNAzol bottles on shelf 3 in the -20 in FTR 209). For gill tissue, around ~20 mg can be subsampled from each tube and homogenized using the pestle. For the foot samples, the entire foot was sampled, but RNA is needed only from the bottom 1/3 of the foot. This means samples will need to be cut at the red line (see picture below) before being homogenized.

![mussel13-_with_labels_copy-resized](https://user-images.githubusercontent.com/70529576/144796353-f0028564-becd-4cc4-949b-c0b84fda5280.png)

The RNA we are after will be found in the distal depression (the white-colored area that produces the adhesive plaque). The outer cuticle of the foot may be to difficult to homogenize with a pestle alone, so a small tissue grinder would be ideal. Please save the rest of the foot.

**Comment by kubu4** [comment]
Thanks for the additional info.

> This means samples will need to be cut at the red line (see picture below) before being homogenized.

This is a bit of a concern to me. Unless the foot samples were stored flat and straight, I believe it will be very difficult to identify the different sections of foot without entirely thawing the samples and stretching them out to be able to inspect them; which is not good when it comes to RNA integrity/preservation.

Have you done this procedure before (isolating RNA from a portion of foot tissues)? If yes, do you have any tips on how to tackle this without thawing the tissue?

Also, are you wanting to isolate RNA from only a portion of the mussel foot tissue (i.e. wanting to save tissue for DNA)?

**Comment by mattgeorgephd** [comment]
The goal with the foot extractions is to preferentially extract RNA from the "phenol gland" that is in the white area below the red line. In my experience, the foot will thaw in 1-3 mins out of the freezer, allowing for a quick cut and then homogenization + extraction. 

I you want to start with the gill extractions first, we can work through a few foot extractions together when I get back from vacation.

**Comment by kubu4** [comment]
>  the foot will thaw in 1-3 mins out of the freezer

This is my concern; not the ability to perform the actual dissections.

If thawing isn't a concern for you, then I'm good to go.

**Comment by kubu4** [comment]
> have more than enough materials on hand to complete the extractions (multiple unopened RNAzol bottles on shelf 3 in the -20 in FTR 209)

Related, do you know if we also have sufficient Qubit reagents for quantification?

**Comment by mattgeorgephd** [comment]
Good catch! I checked the draw and we are running low on tubes and RNA dye. I'll order some more.

**Comment by kubu4** [comment]
Also, where are the pestle and pestle tubes stored for homogenization (they're not listed in inventory - at least as far as I can see)? We used to keep them stored on the shelves above the "RNA bench" back in the corner of FTR 209 (next to the biosafety cabinet/hood), but I feel like they got moved a few months ago during lab cleanup.

**Comment by mattgeorgephd** [comment]
Most of the RNA extraction supplies (1.7 ml tubes, 0.5 ml tubes, DEPC water, handheld automatic homogenizer - the last item might have wandered to 213 if Olivia has been using it) are in the biosafety hood in FTR 209. A glass beaker with used pestles that need to be autoclaved are in the chemical hood.

**Comment by kubu4** [comment]
Alrighty, all high priority RNA isolations are complete.

Here's summary notebook post:

https://robertslab.github.io/sams-notebook/2022/01/13/Project-Summary-Matt-George-PSMFC-Mytilus-Byssus-Project.html

This Google Sheet has all the info:

https://docs.google.com/spreadsheets/d/1HizNOIfhSjppHDQrWLGiJhuDZKO8c-qm9JAz0Z5QIIQ/edit?usp=sharing

Finally, I've submitted a Pull Request to the project repo which has a CSV version of that Google Sheet to help keep things in a singular location.
