### ISSUE TITLE
Install SRA-toolkit on Raven

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1356]
I tried to do this but might have messed up... 
First I used apt-get... worked but appeared to be older version without fasterq-dump. (I can successfully download but want fasterq-dump.)

Installed again current version in shared directory, however doing interactive set-up fails to make command happy.

https://d.pr/i/zv2S4M

**Comment by sr320** [comment]
update - I ran
`sudo apt-get --purge remove sra-toolkit`

**Comment by kubu4** [comment]
Okay, it's all working now. SRA ToolKit (`fastq-dump`) is here:

`/home/shared/sratoolkit.2.11.2-ubuntu64/bin/fastq-dump`

You can test command with this very small SRA file:

`/home/shared/sratoolkit.2.11.2-ubuntu64/bin/fastq-dump -X 2 SRR390728`

It will create the following file in your _current working directory_:

`SRR390728.fastq`

The only thing I really did was do set the database configuration, [per these instructions}(https://github.com/ncbi/sra-tools/wiki/03.-Quick-Toolkit-Configuration) and change to download files to the user's current working directory.
