### ISSUE TITLE
Analyze Cg 2015 Proteomics data in Skyline

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#136]

**Comment by grace-ac** [comment]
[Step 4c](https://github.com/RobertsLab/resources/blob/master/protocols/DIA-data-Analyses.md#step-4c-add-background-proteome)

I see the FASTA file in my downloads and in my folder on desktop.
![capture](https://user-images.githubusercontent.com/14934314/33098650-01662eee-cec3-11e7-929a-11b5d26b07d4.PNG)

But I don't see it when I go through Skyline to upload the background proteome.
![capture1](https://user-images.githubusercontent.com/14934314/33098666-0fc45dee-cec3-11e7-8005-db7658954bca.PNG)

**Comment by sr320** [comment]
Maybe change "Save as type"  to fasta?
if an option.

**Comment by kubu4** [comment]
Everything looks fine so far to me. You're at Step 4c - 4, right? You have to supply a name for the protein database file and then save it.

Once you do that, then you'll click on "Add" and you can then select your FASTA file.

**Comment by grace-ac** [comment]
Yes, I'm at that step.

However, you can't add a FASTA file without selecting a file using the "Create" button. And the file isn't there :( 
![capture](https://user-images.githubusercontent.com/14934314/33099273-2ae9a8ac-cec5-11e7-9081-1f39ac2aaddc.PNG)

**Comment by grace-ac** [comment]
And the file was already saved as a FASTA
![capture1](https://user-images.githubusercontent.com/14934314/33099304-54d000c6-cec5-11e7-9b08-218bf2e02d5c.PNG)

**Comment by grace-ac** [comment]
Steven came and showed me! you're right Sam, you have to sort of name where the file is going to be, and THEN select it...

**Comment by grace-ac** [comment]
[Step 4e](https://github.com/RobertsLab/resources/blob/master/protocols/DIA-data-Analyses.md#step-4e-adjust-transition-settings-in-skyline) 
![capture3](https://user-images.githubusercontent.com/14934314/33100077-f7dd878c-cec7-11e7-85a7-bff7d3e33e3e.PNG)

The link at [Step 3b](https://github.com/RobertsLab/resources/blob/master/protocols/DIA-data-Analyses.md#step-3b-generate-isolation-scheme-file) is broken. Additionally, @kubu4 addressed this question in #118 and provided this link: https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_PECAN_20170228/PECAN-inputs/2017-03-03-isolation-windows.csv

Is that the correct link, @sr320 ?

**Comment by sr320** [comment]
No, that is for different project

**Comment by grace-ac** [comment]
On [Step 5](https://github.com/RobertsLab/resources/blob/master/protocols/DIA-data-Analyses.md#step-5-within-skyline-analyses)

Emma provided the isolation windows in #138 

Currently working through ~100 peptides to check that Skyline chose the correct peaks.

**Comment by grace-ac** [comment]
@yaaminiv when you have a moment, it would be great if you could take a look at it with me

**Comment by yaaminiv** [comment]
@grace-ac I'll drop by after I get out of class (around 3:30)

**Comment by grace-ac** [comment]
Sent @emmats  my error-rate spreadsheet. 

http://owl.fish.washington.edu/scaphapoda/grace/2018-01-10_errorchecking.xlsx

**Comment by emmats** [comment]
I've looked at it! What do you want from me?

**Comment by grace-ac** [comment]
I was told that I should check with you before moving forward! Do the error rates look ok? @emmats

**Comment by emmats** [comment]
This is Rhonda's DIA dataset? ~35% error rate seems OK, I guess. There's not much we can do about it. What are your plans for analysis?

**Comment by grace-ac** [comment]
I think I will be following what Laura has done with her geoduck DIA analysis. So I think my next steps are to follow her [04-SRM Data Analysis.ipynb](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/blob/master/notebooks/SRM/04-SRM%20Data%20Analysis.ipynb) notebook.
