### ISSUE TITLE
address reviewer comments for oyster paper

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1361]
"Although not a hard deadline please try to submit your revision within the next 35 days." < -- early/mid Feb

**Comment by sr320** [comment]
can you attach reviewer comments?

**Comment by grace-ac** [comment]
Google Doc with reviewer comments : https://docs.google.com/document/d/1EEtqDcnw_GaNPg1kymhtE9FNQIWaT191nxMqSrn_VYQ/edit?usp=sharing
