### ISSUE TITLE
Download Cv Larval data and add to Nightingales

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1362]
Please grab larval data described at https://github.com/epigeneticstoocean/2018_L18_OAExp_Cvirginica_DNAm

**Comment by kubu4** [comment]
That repo doesn't exist...

List of repos is here:

https://github.com/epigeneticstoocean/

Nothing jumps out to me as being a DNA methylation project.

**Comment by kubu4** [comment]
Sorry, there are things that do jump out as DNA methylation, but not sure exactly what I'm looking for.

**Comment by sr320** [comment]
Sorry - did not realize it was private .. brb

**Comment by kubu4** [comment]
Update:

All date available in the Lotterhos Lab GlobusConnect endpoint `2018OALarvae_DNAm_discovery/RAW/` has been transferred to https://owl.fish.washington.edu/nightingales/C_virginica/2018OALarvae_DNAm_discovery/

However, a cursory review of the data has revealed that there are three missing FastQs (I've confirmed that this was not an issue with the file transfer and have confirmed that these files are _not_ present in the Lotterhos Lab GlobusConnect endpoint listed above):

```shell
2018OALarvae_DNAm_discovery]$ diff <(ls -1 *.gz) <(cd second_lane/ && ls -1 *.gz)
1d0
< CF01-CM01-Zygote_R1_001.fastq.gz
28d26
< CF08-CM04-Larvae_R2_001.fastq.gz
36d33
< EF03-EM03-Zygote_R2_001.fastq.gz
```

I've contacted the Lotterhos Lab to see if they can provide the missing files.

Will update when I hear back.

**Comment by sr320** [comment]
any update?

**Comment by kubu4** [comment]
Nope.

**Comment by sr320** [comment]
@kubu4 do we have everything now?

**Comment by kubu4** [comment]
Technically, no.

However, I think Alan has indicated that these will sort of be lost forever, since he's unable to get them from Genewiz's archives.

**Comment by sr320** [comment]
👍
