### ISSUE TITLE
Decide on plan for increasing Owl (nightingales) storage

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1363]
Owl, which is primarily used for our sequencing data storage at this point, will be ~99% full after today. That leaves ~500GB.

We should make a decision on how to proceed. Here are some ideas:

- delete stuff (lots of stuff) from Owl to allow us to continue using `owl/nightingales`
- transfer all of nightingales to a new, larger storage location (this would likely require purchase of a new server)
- create a "secondary" nightingales location on gannet. This would result in different data being in two different locations. Could be confusing/annoying.

**Comment by sr320** [comment]
Is there a way to see current directory / space allocation on owl?

**Comment by kubu4** [comment]
Running a storage analysis/report now. Will report back with results when complete.

**Comment by kubu4** [comment]
Update: Storage analysis still running.

**Comment by sr320** [comment]
as predicted here is current space hogs

![e](https://cdn-std.droplr.net/files/acc_524195/4hC65c)

and my personal drive details

![me](https://cdn-std.droplr.net/files/acc_524195/jbMrS8)

for posterity my list... (deleting about ~6TB now) https://d.pr/n/ZN3uG9

**Comment by sr320** [comment]
The following directories can be deleted in `halfshell`
```
bu-serine-wd
working-directory
bu-alanine-wd
bu-caviar-wd
scratch
```
