### ISSUE TITLE
extend UW netID?

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#1365]
@sr320 I got an email that my UW netID (yaaminiv) is expiring 2/2/22, which includes my Google Drive with drafts of publications I'm still working on and `mox` access. is it worth trying to extend access to my netID? I could always ping someone to run `mox` jobs, and can work on transferring permissions for any Google Doc materials.

**Comment by sr320** [comment]
Yes - let's try to extend. Can you make that request or do I?

**Comment by yaaminiv** [comment]
I believe you need to do so. Let me see if I can find any protocol information

**Comment by laurahspencer** [comment]
Me too please!

**Comment by yaaminiv** [comment]
@sr320 Here's information for provisioning access: https://itconnect.uw.edu/connect/productivity-platforms/provisioning-request-tool/

**Comment by sr320** [comment]
issue is, when I try to provision you... you already have access and no way to extend

**Comment by sr320** [comment]
I would certainly back everything up in any event.

**Comment by laurahspencer** [comment]
That seems very strange - just emailed the help desk to see what the options are

**Comment by yaaminiv** [comment]
I did as well, but will back everything up

**Comment by kubu4** [comment]
> That seems very strange

Doesn't seem all that strange to me. You're no longer "paying customers", so no reason to provide you with any UW benefits any more.

I'd guess the most permanent way to create an "extension" would be for @sr320 to "hire" you. Then, you'd become employees of the university and would recover access to your various UW IT accounts.

**Comment by yaaminiv** [comment]
@sr320 Looks like you need to contact IT yourself!

<img width="900" alt="Screen Shot 2022-01-20 at 4 14 44 PM" src="https://user-images.githubusercontent.com/22335838/150423200-c36da7a6-0620-4dbb-a477-2a8b73488b9e.png">

**Comment by sr320** [comment]
I have provisioned Google services for Yaamini and Laura. You should be
getting email confirmation.

**Comment by yaaminiv** [comment]
> I have provisioned Google services for Yaamini and Laura. You should be getting email confirmation.

Got the confirmation and agreed to terms/conditions. Thanks!

**Comment by laurahspencer** [comment]
Me too, thanks!
