### ISSUE TITLE
Sea star cell extracted RNA: Nanodrop 260/230 almost zero... what to do next? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1367]
I'm extracting RNA from sea star cells that are in 500 ul of RNAlater. On Wednesday I extracted RNA from two extra samples I have - E14 and E16. QUESTIONS AT BOTTOM OF THIS POST. 

I'm using the Zymo Quick DNA/RNA Miniprep Kit (D7003)                    
( I meant to buy Microprep (D7005), but accidentally bought Miniprep. This means that my lowest elution volume is 50ul as opposed to 15ul for the Microprep kit. I can purchase the filter tubes for the MIcroprep and use the reagents I have already to be able to elute to 15ul. I am thinking I'll do that because the samples are just some cells and the eluted RNA is too dilute.)

I followed the protocol for dealing with samples in RNAlater (page 9 of this protocol: [here](https://files.zymoresearch.com/protocols/_d7003t_d7003_quick-dna-rna_miniprep_plus_kit.pdf)).      
```
Add 1 volume of nuclease-free water (or PBS) to 1 volume liquid sample (1:1) and mix. Then add 4 volumes DNA/RNA Lysis Buffer to 1 volume sample/water (or PBS) mixture (4:1). Mix again and proceed to purification, page 8 
```

![IMG_6242](https://user-images.githubusercontent.com/14934314/150576133-98382e6c-a951-486b-b9f3-9d47990d075c.JPG)

I did the above in 15ml tubes. 

During the RNA Purification Step 2b, the column filters had white stuff accumulating:         
![IMG_6246](https://user-images.githubusercontent.com/14934314/150576301-fb09f10e-61c3-4a02-9048-e1fdccd77f2f.JPG)

### Results:      
Qubit (RNA High Sensitivity):     
E14 --> 5.04 ng/ul      
E16 --> TOO LOW

Nanodrop:       
E14 —> 260/280: 2.71; 260/230: 0.08;  RNA ng/ul: 7.66 --> total RNA in sample =  ~367.68 ng
E16 —> 260/280: 2.24; 260/230: 0.09; RNA ng/ul: 1.39 --> total RNA in sample =   ~66.72 ng

The 260/280 values are kind of high... but they're still 2-"ish".

The 260/230 values are nearly zero... which "may indicate presence of co-purified contaminants."

## QUESTIONS:

1. I do think I need the green and yellow filter tubes for the Microprep Kit (D7005) - my samples eluted in 50ul are too dilute. I need ~90. I have 98 sets of filter tubes (both green and yellow) for the Miniprep. Are there any Microprep tubes in lab that I can swap with my Miniprep tubes (if anyone would use the mini prep tubes....)? Otherwise, I'll order the Microprep tubes. I don't think I can return the Miniprep tubes, but the Microprep filter tubes can be ordered separately from the kit, so it won't be tooooo much $.

2. For the nearly zero values for the 260/230, that seems like there are likely some contaminants. Is this something I should try to resolve? Or could a sequencing facility take care of that in addition to library prep and sequencing?

**Comment by kubu4** [comment]
I'll address a few things, including your two questions at the end:

> This means that my lowest elution volume is 50ul

You don't need to elute with 50uL. You can use smaller volume (and probably should). It's definitely safe to go down to at least 25uL. However, if you want to elute with less than that, I'd definitely go with the microprep kit, as the exposed area of the column resin is significantly smaller and is also not as deep, which allows for better elution with smaller volumes

The image you posted of the sample in the 15mL conical tube doesn't appear to be at the volume I'd expect when following the protocol. E.g.

Sample vol = 500uL
+ 1 volume (500uL) water = 1000uL (1mL)
+ 4 volumes (4000uL) lysis buffer = 5000uL (5mL)


Did you perform the DNase step?

Now, to answer your questions:

1. Don't know if we have any microprep kits. If we do, they'd be on the shelves with the rest of the kits.
2. Don't worry too much about the 260/230. Also, can you please post screen shot of absorbance plot(s)?

**Comment by grace-ac** [comment]
Thanks @kubu4 !

The person I was chatting with at Zymo said the lowest elution volume was 50ul, like the protocol says, but if 25ul would work, then I think that'd be fine for our samples! 

> The image you posted of the sample in the 15mL conical tube doesn't appear to be at the volume I'd expect when following the protocol

The image posted is for the RNA purification step 2b. But was taken partway through the process. 

For the RNAlater processing, I did do the volumes you indicated above, performed in a 15ml tube - total volume was 5ml. 

I used a second 15ml tube for the process of RNA Purification step 2b, where 1 volume of ethanol is added to the sample and then filtered through the green tube. That was 10ml total, and I filtered through the green filter tube 700ul at a time. Sorry if that is confusing wording... hope it makes sense!! 

> Did you perform the DNase step?

Yep! I did it according to the Miniprep protocol which is a little different than the Microprep protocol. The Miniprep DNAse Reaction Mix is 5ul reconstituted DNAse I and 75ul DNA Digestion Buffer. Whereas the Microprep is 5ul of reconstituted DNAse I and 35ul of DNA Digestion Buffer. 

> Don't know if we have any microprep kits. If we do, they'd be on the shelves with the rest of the kits.        

If the tubes I have can be used to elute down to 25ul, then I think I'm ok without the Microprep tubes... possibly. Not quite sure on that yet. I didn't see any Microprep kits when I was in lab earlier this week, so if I do need them, I'll order them separately. 

> Don't worry too much about the 260/230. Also, can you please post screen shot of absorbance plot(s)?

Yep! Here's the absorbance plot for E14:       
![2022-01-19_E14](https://user-images.githubusercontent.com/14934314/150583063-0e4aa9ac-12b9-40c6-808a-5f3c276e7dec.PNG)

E16:          
![2022-01-19_E16](https://user-images.githubusercontent.com/14934314/150583091-cfee0705-d50a-44fb-a3af-dfa39e58c0b9.PNG)

Report:       
![2022-01-19_report](https://user-images.githubusercontent.com/14934314/150583174-59f25910-d2f5-463d-a57a-b6e54510ccb0.PNG)

**Comment by kubu4** [comment]
The other thing I should have added to this is that you should pellet the cells and remove the RNAlater, if possible.

Also, how many cells are estimated to be in the samples? You may not be able to get much RNA...

Oh, finally, I wouldn't bother with the NanoDrop any more. The NanoDrop is very unreliable for samples with low concentrations (i.e. <10ng/uL) and will always have a skewed 260/230 ratio (i.e. close to 0).

**Comment by kubu4** [comment]
Here's a link to some RNA isolation I performed on sea star coelomic fluid. Might be helpful:

https://robertslab.github.io/sams-notebook/2014/04/16/rna-isolation-colleens-sea-star-coelomycetes-samples.html

**Comment by grace-ac** [comment]
Oh thank you!! I hadn't seen that post before - I didn't realize those cells were processed by you. 

Since I have the zymo micro prep kit, I think I'll try that instead of the Trizol. I don't know how many cells are in my samples, do you have any suggestions on how much DNA/RNA Lysis buffer might be a good amount to try? The protocol says:    

| Mammalian     | Add DNA/RNA Lysis Buffer |
|---------------|--------------------------|
| ≤ 5x106       | ≥ 300 μl                 |
| 5x10^6 - 10^7 | ≥ 600 μl                 |

Maybe just going for 600ul is a safe bet...?

**Comment by grace-ac** [comment]
awesome. Worked fine! One sample had "TOO LOW"... but it's likely we don't have cells in all our samples. 

Thanks so much for all of your help and suggestions @kubu4 !!!
