### ISSUE TITLE
Confirm reproducibility of Hawaii code

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#1371]
Need to check the following scripts are easy-to-follow and reproducible:

- [methylKit](https://github.com/RobertsLab/project-oyster-oa/blob/master/code/Haws/04-methylKit.Rmd)
- [DSS](https://github.com/RobertsLab/project-oyster-oa/blob/master/code/Haws/04-DSS.Rmd)

Should also go back to raw data and check samples were correctly labelled/treatments were correctly inputted into code

**Comment by sr320** [comment]
@yaaminiv where are coverage files?  
https://github.com/RobertsLab/project-oyster-oa/blob/9bdeabebf8b29f36af2bfc1060a84fd80720ed08/code/Haws/04-DSS.Rmd#L42

**Comment by yaaminiv** [comment]
> where are coverage files?
> https://github.com/RobertsLab/project-oyster-oa/blob/9bdeabebf8b29f36af2bfc1060a84fd80720ed08/code/Haws/04-DSS.Rmd#L42

https://gannet.fish.washington.edu/spartina/project-oyster-oa/Haws/bismark-2/

**Comment by yaaminiv** [comment]
@sr320 is the DSS code reproducible/does it make sense? or should I revert back to `methylKit`?

**Comment by sr320** [comment]
not to me.  - I suggest back to methyl kit
