### ISSUE TITLE
Try WEKA for DML identification with Hawaii data

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#1372]
Identify DML related to ploidy, pH, and potentially their interaction. 

To try WEKA, you'll need the `methylKit` `unite` output. The output is in the following RData file: https://gannet.fish.washington.edu/spartina/project-oyster-oa/Haws/project-oyster-oa.RData

Should be able to write out the output after loading the RData.

**Comment by sr320** [comment]
Ok that was pretty cool, did not know about Rdata file.. I load in a lot of objects (https://d.pr/i/RyjvCZ)

is `union_1x` something close? 

![union](http://gannet.fish.washington.edu/seashell/snaps/nb-2022__RStudio_Server_2022-01-28_09-35-04.png)

if so what are columns?

**Comment by sr320** [comment]
>Here's the specific line in my code for unite. Note that with methylKit I did a separate unite for pH and ploidy: https://github.com/RobertsLab/project-oyster-oa/blob/master/code/Haws/04-methylKit.Rmd#L154

omg I am learning so much in this issues!! I had no idea you could link to a specific line of code.
