### ISSUE TITLE
Gfortran issue when installing packages in R v4.1.2

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1373]
When installing a couple packages, I am getting the following error in R v4.1.2: 

`make: gfortran: No such file or directory`

It seems that either gfortran is not installed on my computer or that R can't find it. Has anyone had this issue with the most recent version of R? I'm having trouble finding a current solution for fixing the problem. 

Thanks!

**Comment by kubu4** [comment]
Are you on a Mac?

If yes, give this a read/shot:

https://www.cynkra.com/blog/2021-03-16-gfortran-macos/

**Comment by kubu4** [comment]
If on Linux (assuming Ubuntu), you can install like so (via command line):

`sudo apt-get install gfortran`

**Comment by AHuffmyer** [comment]
Thanks Sam! I'm on a Mac - I couldn't find the Makevars file that the link referenced... But then I searched on YouTube and found this video: https://www.youtube.com/watch?v=piUnVKTUMGw. It shows how to download the gfortran installer from the GitHub release - it was way easier than I expected. Problem solved!

**Comment by kubu4** [comment]
In regards to the Makevars file, if you don't have one already present, you'd have to create it.
