### ISSUE TITLE
Log coral manuscript products

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1377]
Please take 
papers list at https://e5coral.org/publications
and enter into this [spreadsheet](https://docs.google.com/spreadsheets/d/1LqzTvVUav81qi3A2gkLxcHBNl-g-RM6X2-I4L7MpitQ/edit#gid=0)

(all cells will not be populated)

**Comment by sr320** [comment]
you think you can tackle this before TUESDAY 15th?

**Comment by drlawson** [comment]
Definitely!!! I’ll comment here when it’s finished :) will work on it tomorrow and Thursday to get it done

**Comment by drlawson** [comment]
all done - I am surprised that there was not code available for the Wond & Eirin-Lopez (2021) paper, I wonder if I am just missing it somewhere. I checked in a bunch of difference places throughout the paper and did not find it. Also, Cheema et al. 2020 and Lugo Charriez et al. 2020 seem to provide access to some data, but are missing other important data. Let me know what you think and if you think I missed anything. Thanks!
