### ISSUE TITLE
Computer in FTR 209 (woodpecker) disk full

### ISSUE THREAD

**Issue by mattgeorgephd** [RobertsLab/resources#1378]
Hey Sam - The C drive on woodpecker is getting pretty full. I emptied the trash and bought us some time, but it will probably need to be addressed soon.

**Comment by sr320** [comment]
Just curious, what are you using woodpecker for?

**Comment by kubu4** [comment]
Thanks for the heads up. What constitutes "pretty full" and is it impacting what you need to use it for?

**Comment by mattgeorgephd** [comment]
It was at 100 mb this morning, running slow. After emptying trash we are at 2 GB. I didn't want to delete anyone's data, so I figured I would just give you a heads up.

**Comment by kubu4** [comment]
Update: Ran Windows Disk Cleanup and freed up ~500GB of space.
