### ISSUE TITLE
Isolation Windows for 2015 Experiment

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#138]
@emmats we are trying to run through Skyline ourselves and have the following question

At Step 4e:
https://github.com/RobertsLab/resources/blob/master/protocols/DIA-data-Analyses.md#step-4e-adjust-transition-settings-in-skyline

What are the isolation windows that we paste in?

**Comment by emmats** [comment]
[isolationscheme.txt](https://github.com/RobertsLab/resources/files/1493320/isolationscheme.txt)
Skyline has a new thing where it pulls your isolation windows from your data. Try selecting "Results only". If that doesn't seem to work, try the attached.

**Comment by grace-ac** [comment]
The link worked as far as I can tell! Moving on to Step 5.
