### ISSUE TITLE
C. virginica genes with multiple DML

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#1386]
@sr320 Is there a way to output a list of genes with multiple DML, and which feature (exon/intron) they're in? Thinking of ways we can test the hypothesis that high methylation in exons and introns acts antagonistically and wouldn't lead to high levels of expression.

**Comment by sr320** [comment]
Good idea. Short answer is yes. Just a matter of how many iterations of intersectbed it would take.

**Comment by sr320** [comment]
Do you have a specific DML file you are interested in ?

**Comment by yaaminiv** [comment]
How about male OA DML and female OA DML?
