### ISSUE TITLE
Install multiQC on raven

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1390]

**Comment by kubu4** [comment]
This will need to be installed on an individual basis, as it utilizes `conda` to install. This also allows you to keep it in an dedicated environment when you want to use it, which helps avoid dependency conflicts that can get introduced when installing other `conda` packages.

**Comment by sr320** [comment]
I tried this in shared directory - without any luck (and github means to install)

**Comment by kubu4** [comment]
I've downloaded it and it can be found here:

`/home/shared/MultiQC.v1.12.dev0`

So, `cd` to that directory, and then follow the instructions for installation here:

https://github.com/ewels/MultiQC#installation

**Comment by kubu4** [comment]
> I tried this in shared directory - without any luck (and github means to install)

What do you mean by this? Error message? Nothing happened at all?

**Comment by sr320** [comment]
`conda: command not found`

**Comment by sr320** [comment]
and with Github

```
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
``

**Comment by kubu4** [comment]
> conda: command not found

Looks like you need to install Anaconda. Universal install is a bit annoying to configure and I'm also not sure how the base environment functions across all users. Has potential to be headache if everyone ends up using the same base conda install and is modfiying it any time they want a new package. Or, is a headache if they need to ask me to install any time they need a new package.

**Comment by sr320** [comment]
Seems like Github install would be simplest - surprised that did not work.

**Comment by kubu4** [comment]
Seems like it, but you have too have Python configured correctly on your user account. So, installing (and using Anaconda) ends up being easiest. It gets Python set up in a way that most users can start using right away without any other configuration.

**Comment by sr320** [comment]
resigned to use different computer
