### ISSUE TITLE
Access to Mox for A. Huffmyer

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1391]
If possible, I'd like to get access to using Mox. Let me know what information is needed! 

Ariana

**Comment by kubu4** [comment]
Do you have a UW Net ID? If yes, please post. 

If not, @sr320 do you know how to obtain a UW Net ID so we can get her access to Mox?

**Comment by AHuffmyer** [comment]
UW Net ID: ashuff@uw.edu

**Comment by AHuffmyer** [comment]
If I can't get access thats ok - it would just be handy for our work with the Science Incubator folks when we get to the data analysis stage.

**Comment by kubu4** [comment]
Done. If you haven't already, read-through The Handbook on Mox:

https://robertslab.github.io/resources/mox_Adding-a-User/

**Comment by AHuffmyer** [comment]
Thank you!!
