### ISSUE TITLE
Set up account/access to Raven for A. Huffmyer (for RStudio use)

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1392]

**Comment by AHuffmyer** [comment]
UW Net ID: ashuff@uw.edu

**Comment by kubu4** [comment]
Done. See Slack for U/P.

RStudio Server can be accessed here: http://172.25.149.12:8787/

Note: You'll need to be running Husky OnNet to access.

**Comment by AHuffmyer** [comment]
Thank you Sam!
