### ISSUE TITLE
Instruction for ceabigr raven users

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1393]
Should we provide instructions -  particularly  what drive to use?

**Comment by kubu4** [comment]
One issue I just realized is that users will need to user Husky OnNet in order to access Raven. Not sure how this works with Non-UW personnel.

I'll send email to UW-IT with inquiry about this.

**Comment by kubu4** [comment]
I will create new user home directories on 8TB HDD.

I have created some instructions on accessing RStudio Server:

https://github.com/sr320/ceabigr/wiki/RStudio-Server-Instructions

Will post in CEABIGR Slack.
