### ISSUE TITLE
Resolve problem with Scallop slides @ dpmg

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#140]
email 

On Monday, November 27, 2017, Nancy Sarmento <nsarmento@dpmginc.com> wrote:
>
> >
> > Hope you can have Grace get in touch with me.  I've tried the number on
> > form but no one answers.  Over half of her cassettes washed so I am unable
> > to write a number on slides as we cut.  I checked pictures we take before
> > cassettes are put on the processors and the numbers had already washed.

> > If you could pass on the message for her to call me.  I'm not sure if she
> > would like me to cut the washed cassettes or do only the ones that have a
> > visible number.
> >
> > Thanks for your help,
> > Nancy

**Comment by grace-ac** [comment]
Oh sorry @sr320 - I didn't see that my name was in here!

**Comment by sr320** [comment]
Brent requested a subsample analyzed
