### ISSUE TITLE
Review proofs / generate hi quality images for crab paper

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1404]
https://d.pr/f/8O1Y3l

**Comment by grace-ac** [comment]
AQ2 --> ADF&G is referenced in sentence 4 of the Introduction 


For hi quality images -->

### Fig 1: 
[allterms.GOslim-pie-transcriptome-v3.1.pdf](https://github.com/RobertsLab/resources/files/8136491/allterms.GOslim-pie-transcriptome-v3.1.pdf)

Link to GitHub repo location of pdf: https://github.com/RobertsLab/paper-tanner-crab/blob/master/analyses/BLAST-to-GOslim/allterms.GOslim-pie-transcriptome-v3.1.pdf

### Fig 2:     
[tempinfluenced-infectionDEGs-heatmap.pdf](https://github.com/RobertsLab/resources/files/8136497/tempinfluenced-infectionDEGs-heatmap.pdf)

Link to Github repo location of pdf: https://github.com/RobertsLab/paper-tanner-crab/blob/master/analyses/pheatmap/tempinfluenced-infectionDEGs-heatmap.pdf

### Fig 3:
I'm trying to fix this one!! For some reason when I save to PDF, the colors get faded and the orientation is wonky. Here's link to script: https://github.com/RobertsLab/paper-tanner-crab/blob/master/scripts/heatmaps-single_crab-over-time.Rmd 

Line 171 is where the pdf saving code is

Here's what the pdf looks like:
[individual-crab-over-time.pdf](https://github.com/RobertsLab/resources/files/8136517/individual-crab-over-time.pdf)


Link to pdf:  https://github.com/RobertsLab/paper-tanner-crab/blob/master/analyses/pheatmap/individual-crab-over-time.pdf

**Comment by grace-ac** [comment]
Fig 3 is kind of fixed. 
[individual-crab-over-time.pdf](https://github.com/RobertsLab/resources/files/8144287/individual-crab-over-time.pdf)

**Comment by sr320** [comment]
Fig 3 - make bars narrower

**Comment by grace-ac** [comment]
Fig 1:      
[fig1.pdf](https://github.com/RobertsLab/resources/files/8144781/fig1.pdf)

Fig 2      
[fig2.pdf](https://github.com/RobertsLab/resources/files/8144782/fig2.pdf)

Fig 3      
[fig3.pdf](https://github.com/RobertsLab/resources/files/8144783/fig3.pdf)
