### ISSUE TITLE
Get Titrator Running Samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#141]

**Comment by kubu4** [comment]
Have updated LabX Method to include DT1000 temp sensor. Full method now matches LabX method provided by @hputnam.

**Comment by kubu4** [comment]
Email sent to @hputnam for SOP clarification and additional documents (R script, Excel calibration calculator).

**Comment by kubu4** [comment]
@yaaminiv, @laurahspencer, @ksil91 -

Please provide spreadsheets with sample name & info for all the water samples.

**Comment by kubu4** [comment]
Also, can someone please tell me what the final concentration of mercuric chloride is in these water samples? Need the info for EH&S hazardous waste disposal. Thanks!

**Comment by laurahspencer** [comment]
@kubu4 here is info on water samples collected last winter; first and second tab: https://docs.google.com/spreadsheets/d/1NimY1gQFM8eR_wdkM5__nEw3JwEhihmIBHiOqXnBYJ4/edit?usp=sharing

If you need to use our samples to test the titrator I would prefer you use bottles from 2/15/2017, since it seems we are missing some water chem measurements from that day. 

For HgCl concentration: 
50ul injected into 4oz bottles (~118mL); I don't know what the HgCl concentration is, however. 

Also FYI here's an old issue where Hollie & Sean discuss her samples: https://github.com/sr320/LabDocs/issues/493

**Comment by kubu4** [comment]
@laurahspencer - Publicly viewable (not publicly editable).

**Comment by laurahspencer** [comment]
It should now be publicly viewable.

**Comment by hputnam** [comment]
Here are the Dickson SOP 1 recommendations
"Add mercuric chloride — Mercuric chloride is added to poison the sample; the recommended minimum amount is about 0.02% by volume of a saturated aqueous solution. Thus to poison a 250 cm3 sample requires 0.05 cm3 (50 μl) of saturated mercuric chloride (or 0.10 cm3 of a 50% saturated solution). Maximum amount is 0.1% by volume of a saturated aqueous solution, or a smaller percentage than measurement precision of CT and ƒ(CO2)."

The mercuric chloride was prepared at Manchester and I believe was a saturated solution. We added the smallest volume we could from the permanent repeated pipette. From the volume added (50µl) and sample size (120ml) you could report a % by volume of saturated aqueous mercuric chloride if that is what is helpful for EH&S hazardous waste disposal.

**Comment by kubu4** [comment]
@hputnam - SOP question. After running pH calibration method, the SOP you sent says to view the data in (LabX): Data > Results > My Latest Results > Results Details section. However, I'm not seeing that. I get three result outputs from each of the three pH calibration buffers. As such, there's no calibration slope information contained in any of them because each result is only tied to that specific pH calibration buffer and is not associated with the other two pH calibration buffers that were run in the method.

But, I <em>can</em> see the calibration data in the titration report that gets generated from running the calibration method. The calibration slope and zero point info is available there, so it's not a big deal that I don't get that in the Results area of LabX, but wondering if you had any insight why I'm getting different behavior in regards to results output.

**Comment by hputnam** [comment]
@kubu4 ... my thoughts... 1) This may have been a hold over from an update in the software that changed the format of the output tabs and now just needs to be corrected in SOP, 2) people may have pulled the individual values from there and plotted own slope in excel so only needed the 3 data points and the temp, or 3) this could have been an error in directions in the SOP.

I would change SOP to be what you would like for future use. If there is a way to get an automated output that populates a csv file that could be used for plotting probe characteristics in R, that would be the best case. It really depends on how much you want to track all the calibration data. I prefer to track it, as it gives you an indication if the probe performance is declining before you have used expensive acid and CRMS on samples with a bad probe resulting in lost data and $.

**Comment by kubu4** [comment]
@hputnam - You stay up late!

Anyway, I think it's a change in LabX interface design. I've found the aggregated calibration data in: Data > Results Sets > Results Details tab. This tab has the Zero point and the slope.

Individual voltages for each buffer can be found in: Data > Results Sets > Measured Values Tab - Check "Calibration1" box.

Currently not seeing a way to automatically export data - has this ever been possible? I'm not going to worry about this aspect yet, as we just want to this thing processing samples, but if you have any insight into this, we'd certainly appreciate any ideas you have.

**Comment by hputnam** [comment]
I think auto export of the calibration would be icing on the cake. We always did it by hand as we wanted to be thinking about the probe performance in real time. The export to csv for the sample data is the critical piece, as you can then feed directly into the R script and run TA calculations in near real time. Immediate calculation is a must for the CRMs and daily calculations would be ideal for the samples. In theory at some point you would not need to poison samples and could run them immediately for near real time feedback for the OA system parameters (depending on the location of the titrator).

**Comment by kubu4** [comment]
It turns out that auto export is an add-on functionality that you must purchase separately from LabX! I'm getting a list of all available add-ons and their pricing. Will share when I receive this info.

**Comment by hputnam** [comment]
Is the extra for auto export, or manual csv export capacity?

**Comment by kubu4** [comment]
I'm pretty sure it's for both auto and manual CSV exporting!

Just got the product info:

Part number: 11153105
List price: $575

**Comment by hputnam** [comment]
Was this your original product number for LabX Titration Express? 30097754

**Comment by kubu4** [comment]
Yep.

**Comment by hputnam** [comment]
Thanks! Good to know... I thought I had specified this on the quote given its essential nature.

**Comment by kubu4** [comment]
I don't know about you, but our experience with our Mettler-Toledo rep has been mediocre. Normally, I'm not looking for up-sells on products, but I specifically asked about getting data out of the machine (with or without the software) as CSV files. He never mentioned that there were any add-on modules for the software, let alone modules specifically for data export!

**Comment by sr320** [comment]
Lets get a small batch of @hputnam 's samples through and we can close this issue 👍

**Comment by kubu4** [comment]
Ran some CRMs yesterday and had some issues. Will continue on Monday.

**Comment by ksil91** [comment]
Sorry for the delay, was in Peru with no internet.

Here is a sheet with water samples from my oly larvae experiment:
https://docs.google.com/spreadsheets/d/1956gc8fbR-nibRM0kbh9Psu-WEEHFy0rXrR0ewC427U/edit?usp=sharing
The samples marked "High" priority are the ones I definitely need. The "Low priority" are from a preliminary experiment that I will only write up if the primary experiment falls through somehow. Please test the water samples on some of the "Low priority" samples before doing the High priority ones, and if possible also take a pH reading of the sample when doing the titration. My boxes of water samples are sorted and labelled into the "Primary" (High priority) samples and "Maybes" (Low priority), with lists of the samples in each box.

I am checking with Natalie about a list of water samples for the scallop experiment and will post that here when I hear back from her.

**Comment by kubu4** [comment]
@hputnam - I've done a few runs with seawater, to check consistency of measurements, and I'm having issues. We're using the LabX method you provided, but all of the samples I've tried to measure result in this:

![snipaste_2018-01-29_12-10-46](https://user-images.githubusercontent.com/4514104/35532077-d1d7d482-04ed-11e8-98f3-044d33ba88bf.png)


![snipaste_2018-01-29_12-13-02](https://user-images.githubusercontent.com/4514104/35532085-d51bb33e-04ed-11e8-910d-283491c977b5.png)


It's supposed to terminate at 235mV:

![snipaste_2018-01-29_12-53-45](https://user-images.githubusercontent.com/4514104/35533882-b29c5a56-04f3-11e8-97e4-6a1ead4a296e.png)



But just keeps going until it hits max volume:

![snipaste_2018-01-29_12-54-57](https://user-images.githubusercontent.com/4514104/35533894-bc1e34d2-04f3-11e8-8033-167b1ceebd6f.png)



Have you encountered this behavior before? I could set a lower max volume, but it also doesn't resolve the issue of the results not determining a titrant consumption value.

Regardless, I guess all the data is actually present in the Results > Measured Values tab, so maybe all of my consternation is moot?

**Comment by kubu4** [comment]
Dropping a teaser; full deets a bit later today (or tomorrow).

Had Mettler technician out today to help troubleshoot. He made some nice changes and suggestions to the method being used.

Also, we received our license for the export feature and I think I know how to use it.

Things are looking up!

**Comment by hputnam** [comment]
Exciting! Are the changes and suggestions in line with the SOP? I think there is some balance between what is typical for the Mettler folks to improve outcomes and what is happening for this SOP specifically.  Obviously if the changes improve the precision and accuracy WRT the CRMs this is worth the change. Am super interested to see details and outcomes!

**Comment by kubu4** [comment]
OK, here it is: http://onsnetwork.org/kubu4/2018/02/01/titrator-setup-functional-methods-data-exports/

That describes the changes made and talks about what's to come.

Here's the TL;DR summary. 

The original method did not adhere to the Dickson specs; the new method does. Here're some of the changes:

- Changed method template to Endpoint (EP) instead of Equivalence Point (EQP)
- Template change fixes problem with titration Termination control and Consumption calculation (although, this is/wasn't needed)
- Fixing Consumption calculation resolves exit state of "Not OK"
- Increased stirring speed and duration to match Dickson degassing spec
- Add initial titration to pH=3.5. (200mV) before degassing to match Dickson spec
- Improve titration precision by removing user-defined, incremental titrant addition; replaced by feedback-loop to reduce titrant additions (both rate and volume) when approaching endpoint values.

**Comment by kubu4** [comment]
OK, I have a very lengthy post on titrator progress. @hputnam, when you have a sec, can you please look through my notebook entry (specifically the graphs towards the end) and let me know if you have any thoughts on any/all of the data I've layed out there?

http://onsnetwork.org/kubu4/2018/03/06/progress-report-titrator/

**Comment by hputnam** [comment]
I will check this out. I will be in Seattle on Monday and Tuesday (3/19, 3/20), so maybe we can chat in person as well.

**Comment by kubu4** [comment]
I have begun collecting sample data, as of 3/16/2018. 

Raw data is/will be stored here: https://github.com/RobertsLab/titrator/tree/master/data/titration_data/sample_data

Scripts are continually being groomed/updated to improve workflow for analysis.

Daily analyses will be posted in my notebook and hosted (i.e. data/scripts) will be hosted in my folder on Owl.

**Comment by kubu4** [comment]
@yaaminiv - Is the spreadsheet that @laurahspencer posted [here](https://github.com/RobertsLab/resources/issues/141#issuecomment-358092149), also for your samples?

Also, starting March 20th of those samples, the salinity numbers are kinda crazy (e.g. 566). There are some additional numbers that are in the "Notes" column that might be the expected salinity? Also, there are some numbers that are in the "Time" column that might also be the expected salinity values (but, there are other numbers in parentheses in the same cell)?

@yaaminiv - If this is the spreadsheet I should reference for your samples, could you please update the spreadsheet to accurately reflect what the "Salinity", "Time", and "Notes" columns contain? I'm guessing it would be best to create two Salinity columns, each with a units designation to help distinguish the two measurements? It would also be good to fix the content in the "Time" and "Notes" columns to contain just that specific info for each respective column.

**Comment by yaaminiv** [comment]
@kubu4 Yup, that's the spreadsheet! I can go through today and clarify everything

**Comment by kubu4** [comment]
@yaaminiv - Actually, no rush on updating the spreadsheet. Doesn't impact me collecting data. It will need updating once it gets to the point that you want to generate TA values for your samples, though.

**Comment by yaaminiv** [comment]
@kubu cleaned up the spreadsheet!
