### ISSUE TITLE
how to send samples for RNA seq

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1412]
I have finished extracting RNA from sea star samples and RNA is in ~60 samples, though not all likely have enough - have to look more into that. In proposal we said we'd spend ~$7,000 for 32 libraries for prep and seq. 

We have a person at FHL that does all the ordering for us and it just now occurred to me that sending off for seq would be included in that. 

**she leaves for vacation tomorrow through Mar 21.** 

From what I recall, we get a quote from sequencing facility (we specified Genewiz), and then send the samples off after everything's been approved... **is the quote/approval process something that can happen today with the person at FHL so that I can send off samples this week?** 

Hope that all made enough sense. I'm looking at Genewiz website, too

**Comment by kubu4** [comment]
I'll admit, I'm a little confused on what information you're asking for here.

Won't the timing all depend on how quickly Genewiz responds? 

> We have a person at FHL that does all the ordering for us

Is there not anyone designated to place orders while that person is out? That's a remarkably long time to _not_ have the ability to place orders.

**Comment by grace-ac** [comment]
Yeah... I'm frazzled! Her leaving tomorrow snuck up on me 

That's a great question! I'll ask that now, which may solve this whole issue.

My main question is if I have to pause this whole Genewiz process til after she gets back, but I'll find out first is someone will be there to replace her.

**Comment by grace-ac** [comment]
In order to get a quote, I would need access to the sea star budget stuff, right?

**Comment by grace-ac** [comment]
ok, everything's fine. She's able to get a quote now, so we'll see what happens. Thanks for responding, @kubu4 ! I was stressed. closing issue now.
