### ISSUE TITLE
Obtain relative expression values for geoduck tissues

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1423]
Using geoduck genome get expression values for 
heart, gonad, ctenedia, juvenlies and larvae samples... 

file locations..

Heart 
```
/home/shared/8TB_HDD_01/sr320/ncbi/SRR12218868_1.fastq /home/shared/8TB_HDD_01/sr320/ncbi/SRR12218868_2.fastq 
```

Gonad
```
/home/shared/8TB_HDD_01/sr320/ncbi/SRR12218869_1.fastq /home/shared/8TB_HDD_01/sr320/ncbi/SRR12218869_2.fastq \
/home/shared/8TB_HDD_01/sr320/ncbi/SRR12226692_1.fastq /home/shared/8TB_HDD_01/sr320/ncbi/SRR12226692_2.fastq \
```

ctendia
```
/home/shared/8TB_HDD_01/sr320/ncbi/SRR12218870_1.fastq /home/shared/8TB_HDD_01/sr320/ncbi/SRR12218870_2.fastq \
/home/shared/8TB_HDD_01/sr320/ncbi/SRR12226693_1.fastq /home/shared/8TB_HDD_01/sr320/ncbi/SRR12226693_2.fastq \
```

juvenile (amb)
```
/home/shared/8TB_HDD_01/sr320/ncbi/SRR12207404_1.fastq /home/shared/8TB_HDD_01/sr320/ncbi/SRR12207404_2.fastq \
/home/shared/8TB_HDD_01/sr320/ncbi/SRR12207405_1.fastq /home/shared/8TB_HDD_01/sr320/ncbi/SRR12207405_2.fastq \
/home/shared/8TB_HDD_01/sr320/ncbi/SRR12227930_1.fastq /home/shared/8TB_HDD_01/sr320/ncbi/SRR12227930_2.fastq \
```

juvenile (sl)
```
/home/shared/8TB_HDD_01/sr320/ncbi/SRR12207406_1.fastq /home/shared/8TB_HDD_01/sr320/ncbi/SRR12207406_2.fastq \
/home/shared/8TB_HDD_01/sr320/ncbi/SRR12207407_1.fastq /home/shared/8TB_HDD_01/sr320/ncbi/SRR12207407_2.fastq \
/home/shared/8TB_HDD_01/sr320/ncbi/SRR12227931_1.fastq /home/shared/8TB_HDD_01/sr320/ncbi/SRR12227931_2.fastq \
```

larvae
```
/home/shared/8TB_HDD_01/sr320/ncbi/SRR12212519_1.fastq /home/shared/8TB_HDD_01/sr320/ncbi/SRR12212519_2.fastq \
/home/shared/8TB_HDD_01/sr320/ncbi/SRR12227929_1.fastq /home/shared/8TB_HDD_01/sr320/ncbi/SRR12227929_2.fastq \
/home/shared/8TB_HDD_01/sr320/ncbi/SRR8788211_1.fastq /home/shared/8TB_HDD_01/sr320/ncbi/SRR8788211_2.fastq \
```

**Comment by kubu4** [comment]
There are 26 FastQs listed above, but there are 34 FastQs in `/home/shared/8TB_HDD_01/sr320/ncbi/`. 

Should I only work with the 26 listed above?

**Comment by sr320** [comment]
Yes, just the ones listed, and note at then end we are just want to compare the 6 samples....

(also, there are 28 above?)

**Comment by kubu4** [comment]
Thanks.

Yep, 28; sorry about that.

**Comment by kubu4** [comment]
The Nextflow RNAseq pipeline finished and as I was going through the MultiQC outputs, this jumped out to me as sort of interesting:

![image](https://user-images.githubusercontent.com/4514104/160424009-bd1531fc-0e69-4ab2-a44c-a2eb803787e4.png)


Here's the full report if you want to peruse:

https://gannet.fish.washington.edu/Atumefaciens/20220323-pgen-nextflow_rnaseq-tissues/multiqc/star_salmon/20220321-pgen-nextflow_rnaseq-tissues-2666621_multiqc_report.html

Also, to clarify, do you want a count data matrix (e.g. from `salmon`) or do you want adjusted expression values (e.g. from `DESeq2` using `salmon` count data)?

**Comment by sr320** [comment]
Thanks - I was thinking more HISAT.. similar to what was done in oysters.

**Comment by kubu4** [comment]
Here're the TPM values for all genes in all tissues:

https://gannet.fish.washington.edu/Atumefaciens/20220323-pgen-nextflow_rnaseq-tissues/star_salmon/salmon.merged.gene_tpm.tsv
