### ISSUE TITLE
Installing dDocent on hummingbird

### ISSUE THREAD

**Issue by jldimond** [RobertsLab/resources#143]
I'm in the process of installing dDocent on humminbird. It has several dependencies that I've been installing and I'm almost there. But there are a couple of sticky points, notably samtools and trimmomatic. Here is what dDocent tells me when I try to run it:

```
hummingbird:~ srlab$ ddocent
dDocent 2.2.16

Contact jpuritz@gmail.com with any problems

 
Checking for required software
The dependency pearRM is not installed or is not in your $PATH.
The dependency trimmomatic is not installed or is not in your $PATH.
The version of Samtools installed in your $PATH is not optimized for dDocent.
Please install at least version 1.3.0
```

But Trimmomatic is in my $PATH! Why isn't it being found by ddocent?
```
hummingbird:~ srlab$ which trimmomatic
/usr/local/bin/trimmomatic
```

As for samtools, there is an older version that it does not seem to like, and it is the version that is called by default:
```
hummingbird:~ srlab$ which samtools
/usr/local/bioinformatics/rsem/sam/samtools
hummingbird:~ srlab$ samtools

Program: samtools (Tools for alignments in the SAM format)
Version: 0.1.19-44428cd
```
But I did also install a newer version (1.6) and it is in my $PATH. Should I prepend that version in order for it to be found? I have never had to do this and just want to check that that is what I should try.

Any tips would be appreciated! Thanks.

**Comment by sr320** [comment]
Technically you are not showing us it is your $PATH.
provide output for 
`echo $PATH`

**Comment by jldimond** [comment]
Following [these](http://www.htslib.org/download/) install instructions, I installed samtools 1.6 as follows:

```
cd samtools-1.6  
./configure --prefix=/usr/local/bin
make
make install
```

This installed to /usr/local/bin/bin, which I then added to $PATH just to make sure it was being found.

```
hummingbird:~ srlab$ echo $PATH
/Users/srlab/miniconda2/bin:/Users/srlab/bin:/usr/local/bioinformatics/vsearch-1.11.1-osx-x86_64/bin:/usr/local/bioinformatics/bismark_v0.14.2:/usr/local/bioinformatics/bedtools-2.22.1/bin:/usr/local/bioinformatics/cufflinks-2.2.1.OSX_x86_64:/usr/local/bioinformatics/FastQC:/usr/local/bioinformatics/tophat-2.0.13.OSX_x86_64:/usr/local/bioinformatics/signalp-4.1:/usr/local/bioinformatics/Trinotate:/usr/local/bioinformatics/ngsplot/bin:/usr/local/bioinformatics/stacks/bin:/usr/local/bioinformatics/rsem/sam:/usr/local/bioinformatics/fastx_toolkit/bin:/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bioinformatics/rsem:/usr/local/bioinformatics/bowtie2:/usr/local/bioinformatics/bowtie:/usr/local/bioinformatics/hmmer:/usr/local/bioinformatics/trinity:/usr/local/bioinformatics/ncbi-blast/bin:/usr/local/bioinformatics/anaconda/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/ncbi/blast/bin:/Users/srlab/edirect:/Users/srlab/myscripts/:/Users/srlab/rainbow_2.0.4/:/Users/srlab/vcflib/bin:/Users/srlab/usr/local/share/trimmomatic/adapters:/Users/srlab/usr/local/Cellar/trimmomatic/0.33:/usr/local/Cellar/trimmomatic/0.33:/usr/local/share/trimmomatic/adapters:/usr/local/share/trimmomatic:/usr/local/Cellar/trimmomatic:/usr/local/Cellar/samtools/1.2:/usr/local/bin/bin
```

**Comment by kubu4** [comment]
For samtools, as you correctly surmised, you'll need to prepend the newer version to $PATH in order for it to be called by dDocent. When programs look at the system $PATH, they will always use the first one found.

**Comment by kubu4** [comment]
For trimmomatic, looking at the [code for dDocent](https://github.com/jpuritz/dDocent/blob/master/dDocent), the code is looking for ```trimmomatic*jar```. That's why it doesn't "find" trimmomatic in your system $PATH. Not entirely sure how to quickly resolve this one...

**Comment by kubu4** [comment]
Actually, I think I figured it out. The installation of Trimmomatic that is in your $PATH is a Homebrew installation.

You'll want to prepend this to your $PATH: ```/usr/local/bioinformatics/Trimmomatic/trimmomatic-0.30.jar```

That will allow dDocent to recognize the Trimmomatic install.

**Comment by jldimond** [comment]
Yeah, that did the trick, thanks!
