### ISSUE TITLE
R Plotting on Raven broken

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1432]
All basic plotting appears to be broken on Raven. Possibly related to Circos install (which modified Freetype libraries).

**Comment by ChrisMantegna** [comment]
Sure can - it's here: https://github.com/sr320/nb-2022/tree/main/C_virginica

**Comment by kubu4** [comment]
Hmm, I ran it without any errors:

![image](https://user-images.githubusercontent.com/4514104/158230358-ddf8188c-61b9-4bf0-bee6-a3bfff2ff484.png)


Maybe close your project and restart your session and see if that helps.

**Comment by kubu4** [comment]
Confirmed with @ChrisMantegna at Science Hour today that things are working.
