### ISSUE TITLE
Revise Geoduck Genome Feature Tracks

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1435]
Given the renaming - https://robertslab.github.io/sams-notebook/2019/11/05/Data-Wrangling-Rename-Pgenerosa_v074-Files-and-Scaffolds.html

The genome feature tracks do not "align" with genome. In otherwords cannot use bedtools etc. 
https://robertslab.github.io/resources/Genomic-Resources/#panopea-generosa

Presume it might just be a `sed`

**Comment by kubu4** [comment]
When you have a sec, can you please provide an example of code/error(s)?

Looking at renaming notebook, `sed` command is only utilizing lists of scaffold names (old and new), so wouldn't have any impacts on coordinates.

**Comment by sr320** [comment]
The genome scaffold names were revised but genome feature tracks scaffold names were not.. they need revising.

**Comment by kubu4** [comment]
Ah! Gotcha! 

The issue is that the links on the Handbook weren't updated with renamed files. Will update shortly...

**Comment by kubu4** [comment]
I've just updated GFF subset files URLs (and added a bunch of additional ones).

However, it looks like I never updated the scaffold names in the all-encompassing GFF. I'll get that resolved a bit later tonight. Will post here when complete.

**Comment by kubu4** [comment]
Lab Handbook has been updated with correct URLs for all GFFs.
