### ISSUE TITLE
Add shell packages to Raven

### ISSUE THREAD

**Issue by mattgeorgephd** [RobertsLab/resources#1437]
I need the following shell packages added to Raven:

[HISAT2](http://daehwankimlab.github.io/hisat2/)
[StringTie 2](https://ccb.jhu.edu/software/stringtie/)

**Comment by kubu4** [comment]
Hisat2: `/home/shared/hisat2-2.2.1/hisat2`

Stringtie: `/home/shared/stringtie-2.2.1.Linux_x86_64/stringtie`
