### ISSUE TITLE
Process Crab samples (1st Sampling)

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#144]
I presume RNAlater samples are still in our 4C from the first sampling?
As we are approaching 1 month we should process.

Samples could be spun down and placed in -80, but possible need to be split for DNA?

**Comment by kubu4** [comment]
Yes, still in fridge.

**Comment by grace-ac** [comment]
Halfway there! I got the green-capped ones done. Pellets and supernatant are in cardboard boxes in the -80 and in [-80 inventory spreadsheet.](https://docs.google.com/spreadsheets/d/1Qsvz3QTURlPF_hX05BQxjom3484WuMfqQ1ILl9LEljU/edit#gid=2006985773) 

I'll finish the other half (pink-capped) tomorrow.

**Comment by grace-ac** [comment]
finished. spun down pink-capped samples today and placed in -80 ([tray 14](https://docs.google.com/spreadsheets/d/1Qsvz3QTURlPF_hX05BQxjom3484WuMfqQ1ILl9LEljU/edit#gid=2006985773))
