### ISSUE TITLE
sea star RNAseq question from Genewiz

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1441]
## Azenta (previously Genewiz) sent me this email:  

Attachments they sent me: 

[Sample QC 30-666390649  1-3, 11-15, 18-23, 25-26, 31-32.pdf](https://github.com/RobertsLab/resources/files/8399548/Sample.QC.30-666390649.1-3.11-15.18-23.25-26.31-32.pdf)
[Sample QC 30-666390649   4-10, 16-17, 24, 27-30.pdf](https://github.com/RobertsLab/resources/files/8399549/Sample.QC.30-666390649.4-10.16-17.24.27-30.pdf)
[Sample QC report of_30-666390649_220330103725.pdf](https://github.com/RobertsLab/resources/files/8399551/Sample.QC.report.of_30-666390649_220330103725.pdf)

Please review the attached QC data from our Qubit and Tape Station.
Note that our requirements include RIN>6, and a quantity of 100ng of RNA per sample minimum. We found that 11 of your samples had RINs less than 6, suggesting some degradation (see samples with a “2” in QC note column). Additionally, 5 samples had total RNA quantities less than 100ng (marked with a “1” in the QC note column).

Please advise on how you would like to proceed. Your options are the following:

1.) Resubmit samples that you expect to have higher quality/quantity for those that do not meet our requirements (please note that this would reset the turnaround time of your project.)
2.) Proceed with rRNA depletion instead of PolyA selection (rRNA depletion is generally better for low-quality samples). rRNA depletion would still be done at best effort (the results cannot be guaranteed) for the low quantity/quality samples. Additionally, if you choose this option we will need to generate new pricing for you and the current promotion would no longer be applicable.
3.) Omit the low quality/quantity samples from the pipeline
4.) Proceed with the current samples at best effort using the contracted PolyA selection method.

---
My thoughts so far:

Option 1 is possible - I have 10 more samples that had high enough quantity of RNA, but I'm not sure that they'd be helpful analyses-wise as the samples we sent were chosen in order to get a good look at the different treatment groups. Also the samples won't be able to be sent until I'm back from FHL (I'll be there April 4-16), so I'd have to ask Drew about that. We want to get data back I think before May... so I'd have to see what she thinks about pushing that timeline out. 

Option 2 I think isn't a good idea because I believe that would require more $ and our budget doesn't have much more for this part of the project.

Between options 3 and 4, I think option 4 of continuing with seq "at best effort" is good... ? 

Any thoughts @sr320 ? @kubu4 ? I'll email Drew about this too, but wanted to get your input first before I take this over to her.

**Comment by sr320** [comment]
Happy to provide advice, but probably most efficient means is to find a time both @kubu4 and I are available.
For example probably I would need more background on experiment - 
do you have a spreadsheet of all available samples (with description) and their RNA status?

@mattgeorgephd can you share with us minimum sample parameters to go into tag-seq?

**Comment by grace-ac** [comment]
ok great! sounds good. i have a spreadsheet with info on the samples, and i'll add in the QC stuff from Azenta. 

i have a dr appt at 11, but i'll be around after that til 3:40pm today. 

just checked slack and see @kubu4 probably won't be at science hour, so i can message you two directly to find a time to talk about it!

**Comment by mattgeorgephd** [comment]
For tag-seq I submitted a total of ~2.6 ug RNA per sample @ a concentration of ~45 ng/ul, making sure each sample volume was at least 60 ul.

[UT-Austin](https://wikis.utexas.edu/display/GSAF/Sample+Input+Guidelines) recommends 2 ug @ > 40 ng/ul, RIN>7   (At least 50 ul's) for tag-seq. However, they do state that they will accept samples total RNA as 500 ng @ > 10 ng/ul.
 
Due to low extraction yield, I submitted one sample that was 610 ng @ 12 ng/ul. The data came back fine.

**Comment by kubu4** [comment]
I would do one of the following:

1. Send in additional RNA for those that are <100ng. Don't worry about RIN values for any samples. Proceed with PolyA.

OR

2. Possibly just drop the 5 samples <100ng. Don't worry about RIN values for any samples. Proceed with PolyA.

**Comment by grace-ac** [comment]
thanks for input! we're proceeding with the samples we sent at best effort using PolyA
