### ISSUE TITLE
Create improved version of geoduck gene annotations

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1443]
Add protein names, GO information

**Comment by sr320** [comment]
Tab-delimited file - not a GFF.

One table with best predictive identification.

**Comment by kubu4** [comment]
Would you like GO terms for sequences which _don't_ have a BLAST match? E.g. No BLAST result, but has Pfam and/or InterProScan info - which we can get GO terms for.

**Comment by sr320** [comment]
no need

**Comment by kubu4** [comment]
Believe it or not, this is complete! Let me know what you think.

https://gannet.fish.washington.edu/Atumefaciens/20220419-pgen-gene_annotation_mapping/20220419-pgen-gene-accessions-gene_id-gene_name-gene_description-alt_gene_description-go_ids.tab

Columns in file:

- `gene_ID`: Gene ID from our [_Panopea generosa_ (Pacific geoduck)](http://en.wikipedia.org/wiki/Geoduck) genome.

- `SPIDs`: Semicolon-delimited list of SPIDs from UniProt. One SPID in this list is a match corresponding to the our original BLAST annotations.

- `UniProt_gene_ID`: Gene accession from UniProt.

- `gene`: Abbreviated gene name from UniProt.

- `gene_description`: Human-readable gene description from UniProt.

- `alternate_gene_description`: Human-readable alternate gene description from UniProt.

- `GO_IDs`: Semicolon-delimited GO IDs from UniProt.


Notebook:

https://robertslab.github.io/sams-notebook/2022/04/19/Data-Wrangling-Create-Primary-P.generosa-Genome-Annotation-File.html

Jupyter Notebook:

https://nbviewer.org/github/RobertsLab/code/blob/master/notebooks/sam/20220419-pgen-gene_annotation_mapping.ipynb

**Comment by kubu4** [comment]
Oh, and I've already added this file the Genomic Resources page in The Handbook.
