### ISSUE TITLE
Switching Acid: Query on Alkalinity / Titrator code 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1446]
_via email_

We've adapted yours and Nyssa's code and gotten it all working on our similar setup, but the one thing we are still stuck on is what values to enter when we switch a bottle of acid.

This is the code we've adapted, and we see that you guys have changed 3 values related to the acid with new bottles, but based on the document we got for the acid, we can't figure out what the values we change should be. (lines 108-116).

[The document they sent us](https://d.pr/f/Q5pGgR) about the new acid batch (where we are trying to find the numbers to copy into R).

https://github.com/shellytrigg/P_generosa/blob/master/Water_Chemistry/analysis/titrator/TotalAlkCalc_wParsing.R

**Comment by kubu4** [comment]
This line needs to be altered: https://github.com/shellytrigg/P_generosa/blob/8001e70509bc67e64bcfa96c64256a6f3fa2e596/Water_Chemistry/analysis/titrator/TotalAlkCalc_wParsing.R#L112

Use this equation provided with documentation:

![image](https://user-images.githubusercontent.com/4514104/162273882-ac3eba4f-e9ee-4ffc-b72f-5e80de3b1697.png)


So, that line noted above would look like this for Batch A23:

` d<-1.02878 -(0.0001108*mean(Data$Temperature[mV], na.rm=T)) - (0.000004*(mean(Data$Temperature[mV], na.rm=T)^2)) `
