### ISSUE TITLE
bio and picture for Sam and Shanelle

### ISSUE THREAD

**Issue by drlawson** [RobertsLab/resources#1451]
We need pictures and bios of you guys on the lab website please! :)

**Comment by drlawson** [comment]
This is a reminder for me: I need to add my capstone link/proposal and graduation year to the website - please add any other random website updates that need to occur below :)

**Comment by afcoyle** [comment]
Ooh might be good to update the website with a more current lab group photo (if we have one)!

**Comment by kubu4** [comment]
@sr320 Is there a repo for adding info or should we send directly to you? Not sure how the website is handled.

**Comment by drlawson** [comment]
Shanelle messaged hers directly to me through slack. Why don't you do the same and if I need to put it somewhere else then I'll be able to do that. I have to go in and remind myself how exactly to edit that page because it's been a couple months, but it shouldn't be too difficult :)

**Comment by sr320** [comment]
Robertslab/website

**Comment by drlawson** [comment]
Just uploaded Shanelle's image and bio, as well as my capstone links to the website. My changes haven't showed up yet on the website but they have been committed :) Shanelle said she is going to start making a lab notebook this weekend (I directed her to the lab notebook page in the handbook), and I will add that when she makes it

**Comment by drlawson** [comment]
@sr320 Is it normal that my changes to the website code on Github have not shown up on the website 10 minutes after committing? I just want to make sure I didn't miss a step. Thanks :)

**Comment by sr320** [comment]
Will not automatically update/ I have to do that

**Comment by kubu4** [comment]
added bio and pic
