### ISSUE TITLE
Generate Circos Plot for gigas-WGBS-ploidy-desiccation project

### ISSUE THREAD

**Issue by mattgeorgephd** [RobertsLab/resources#1455]
Here is a link to the [Github Repo](https://github.com/mattgeorgephd/gigas-WGBS-ploidy-desiccation) for the project.

Circos has been installed in RStudio on [Raven](http://172.25.149.12:8787/). It is located in:
` /home/shared/circos-0.69-9/bin/circos `

Previous GitHub issues about Circos: #710, #1422, #1430 

Circos tutorial can be found [here](http://www.circos.ca/documentation/tutorials/). Here is a visual [guide](http://circos.ca/guide/).

Here is an example of what we are looking for (methylation pattern or CpG chromosome location):

![circos_example](https://user-images.githubusercontent.com/70529576/164280844-db6b2c1b-02ce-4762-be4d-02aa51d45482.jpg)

Here is a link to the [paper](https://academic.oup.com/gbe/article/12/11/1994/5898196)

Here is a link to the genome index file for c. gigas that Circos will need:
`https://gannet.fish.washington.edu/panopea/Cg-roslin/cgigas_uk_roslin_v1_genomic-mito.fa.fai`

You can import using the following wget code:
```
#mkdir sequences/

cd sequences/

wget -r \
--no-directories --no-parent \
-P . \
-A cgigas_uk_roslin_v1_genomic-mito.fa.fai https://gannet.fish.washington.edu/panopea/Cg-roslin/ \
--no-check-certificate
```
Overall goal: learn how to generate a Circos plots that visualize "differentially methylated loci" (DML) location (across chromosomes) as a function of ploidy (diploid/triploid) and treatment (desiccation/control).

**Comment by drlawson** [comment]
Hey matt! Can you add me as a collaborator on the repo where I can put my analyses?

**Comment by mattgeorgephd** [comment]
> Hey matt! Can you add me as a collaborator on the repo where I can put my analyses? 

Invite sent!
