### ISSUE TITLE
dplyr package maxes out at 30 observations

### ISSUE THREAD

**Issue by ocattau** [RobertsLab/resources#1458]
So I am trying to filter my data by array and whenever I use dplyr to filter the data it won't build a new dataset larger than 30 observations. This is the script to my [data](https://github.com/mattgeorgephd/NOPP-gigas-ploidy-temp/blob/main/202107_EXP2/citrate_synthase/CS%20script%20samples%201-23.Rmd)  
-when I get to line 35 and I try to build dataset "positive" it maxes out at 30 regardless of what I put in the array
-quickview2 only has 3 data points for the set (when it should be 10)
-please help!

**Comment by kubu4** [comment]
When I run this, it dies at line 15:

```r
names(CS)[7]<-'Label'
```

Error:

```r
Error in names(CS)[7] <- "Label" : object 'CS' not found
```

As the error message indicates, the `CS` object isn't present, so I expected it to fail at this point. Are you able to get past this line?

**Comment by kubu4** [comment]
Alrighty, so I did some rearranging (and delineation into smaller chunks) and fixed that first error I was encountering. Changed code to:


```r
    ```{r}
    CS<-CS_1[-c(811,812),] #clean data
    names(CS)[7]<-'Label'
    names(CS)[6]<-'A'
    CS$Label<-rep(wells, 10) #label all replicates
    ```
```

You can fix your `filter()` function like so:

```r
mydata<-filter(CS, CS$Label %in% samples)
```

Please double check it, of course!

**Comment by ocattau** [comment]
Cool thanks Sam! I knew it would be some easy fix :)
