### ISSUE TITLE
sea star RNAseq data ready - where should it go?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1459]
Sea star RNAseq data from azenta (FKA Genewiz) is ready on their server! 

I've been given a link and log-in credentials to access  

Feeling real rusty on this... but I'm assuming first step is to transfer data to a roberts lab bird?  which one?

**Comment by sr320** [comment]
see https://robertslab.github.io/resources/Data-Management/#ngs-data-management-plan
