### ISSUE TITLE
Order MethylMiner Kits

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#146]
@kubu4 go ahead and order 2 of these kits on 61-1553.
Order directly and go ahead and rush if an option.. 
I would prefer this for Qiagen samples - otherwise will use for other Cv samples

ThermoFisher
cat # ME10025, $600

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/MethylMiner_Methylated_DNA_Enrichment_Kit_-_Thermo_Fisher_Scientific_1FDEE214.png" alt="MethylMiner_Methylated_DNA_Enrichment_Kit_-_Thermo_Fisher_Scientific_1FDEE214.png"/>

**Comment by kubu4** [comment]
Ordered.
