### ISSUE TITLE
transferring RNAseq data from Azenta (FKA Genewiz) server to owl

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1460]
I have log in credentials to access sea star RNAseq data from Azenta (FKA Genewiz), and I want to move it to owl/nightingales/P_helianthoides

I have instructions from azenta [here](https://f.hubspotusercontent00.net/hubfs/3478602/Sell%20Sheet%20Collateral%20Library/NGS/NGS%20User%20Guides/NGS_sFTP-Data-Download-Guide_Option%201_Nov03_2020.pdf). 

I was attempting method C. Command Line for transferring the files, but am stuck on Step 5:     

<img width="848" alt="Screen Shot 2022-05-02 at 2 20 30 PM" src="https://user-images.githubusercontent.com/14934314/166329679-ea448414-3610-4d7c-8a7f-44f219cdc4f4.png">

When I type `lcd`, it doesn't show anything. I think my working directory is the remote server where the data is stored... ? How do I set `lcd` to the nightingales/P_helianthoides directory on owl?         

<img width="559" alt="Screen Shot 2022-05-02 at 2 30 07 PM" src="https://user-images.githubusercontent.com/14934314/166330888-aac633bd-8361-4c17-83d6-0f576040778b.png">

There are other methods for download, where I can download the data and then rsync to owl, so maybe that'd be the better route?

**Comment by kubu4** [comment]
If you want to download the data directly to Owl, then you'd need to follow these commands from within Owl. I.e. you need SSH into Owl, and then follow the Command Line instructions.

**Comment by grace-ac** [comment]
awesome! I tried that earlier, but wasn't granted access. 

I tried to ssh into owl, (using my correct login, grace and put in my correct password), but permission was denied. 

Is there something I'm missing? 

<img width="554" alt="Screen Shot 2022-05-02 at 2 45 10 PM" src="https://user-images.githubusercontent.com/14934314/166332734-6589ad4f-4d58-43a7-a6e0-7cb54c022d3a.png">

**Comment by kubu4** [comment]
I changed some permissions. Please see if you can login to Owl via SSH again.

**Comment by grace-ac** [comment]
same message as before - Permission denied. I checked my password and username again, and I'm putting in the correct username and password

**Comment by kubu4** [comment]
Changed your user group. Please try again and report back. Thanks for your patience!

**Comment by grace-ac** [comment]
it worked!! thank you sam!!

**Comment by grace-ac** [comment]
even after ssh into owl,  the same error still comes up when I try to set `lcd` :          
<img width="570" alt="Screen Shot 2022-05-03 at 9 13 25 AM" src="https://user-images.githubusercontent.com/14934314/166492971-1fcd0923-2b46-4d4c-beb3-5a3e7675f579.png">

**Comment by kubu4** [comment]
I don't see the `lcd` command in the screenshot above.

Also, I see you ran this command (after you've FTP'd into Genewiz):

```shell
ls <P_helianthoides>
```

That throws an error because there isn't a folder on the Genewiz server names `<P_heliantoides>`.

**Comment by kubu4** [comment]
Also, to add, in the screenshot above, it looks like you navigated to `nightingales/P_heliantoides` before you initiated the FTP session. With that being the case, there's no need to run the `lcd` command from your FTP session, since you're already in your desired location on Owl. The `lcd` command is only needed if you want to change directories on Owl _after_ you've started your FTP session.

**Comment by grace-ac** [comment]
issue resolved!!! For future reference: 
I SSH into owl directory I want the files to be moved to (nightingales/P_helianthoides)

Then followed the `sftp` protocol provided by azenta

then did the `tmux` thing that Sam showed me so that the process can keep going even if i close my laptop. 

to exit the tmux window, do contol+b then d. to get back in, do `tmux attach -t 0` where "0" is the session name for the thing that's running.

don't think i'm using the best terminology to describe this, so here are screenshots: 
<img width="564" alt="Screen Shot 2022-05-04 at 11 18 25 AM" src="https://user-images.githubusercontent.com/14934314/166800665-4d7a7185-f6e8-4100-826c-056e0fdaebf4.png">

<img width="560" alt="Screen Shot 2022-05-04 at 11 18 33 AM" src="https://user-images.githubusercontent.com/14934314/166800796-2b684a07-64a5-4956-a441-f9558b043c16.png">

**Comment by grace-ac** [comment]
@kubu4 I accidentally scrolled down while in the tmux window... do I have to re-start it? Also the file that's at 36% has been at 36% for over an hour 

<img width="580" alt="Screen Shot 2022-05-04 at 1 10 19 PM" src="https://user-images.githubusercontent.com/14934314/166817877-ecd0ed61-6284-45da-8f6b-6c15a45f5567.png">

**Comment by kubu4** [comment]
Just press `Enter` key to get back to the prompt.

> Also the file that's at 36% has been at 36% for over an hour

Don't know. Just have to wait it out and see what happens. FTP connections (in my experience) seem to be fairly unstable. It can be a frustrating experience.

Also, FTP will not be able to "continue" a download. So, if that transfer fails on that file, you _don't_ want to run `mget *` again! This will start downloading _every file_ again...

If that transfer fails, you'll want need to figure out which files successfully downloaded and then run `mget` with a pattern that only matches the remaining files you want (including the file which failed).

**Comment by grace-ac** [comment]
got it! thanks! hopefully things keep moving

**Comment by grace-ac** [comment]
I'm thinking it may have become interrupted... the progress has not gone further in 7+ hours :( 

how do I quit/end the session in tmux? (sidenote: I'm trying hard to stop scrolling when I'm in the tmux window!!) 

So far only half of the files for the first library (out of 32 libraries) has been transferred. 

<img width="573" alt="Screen Shot 2022-05-04 at 8 32 28 PM" src="https://user-images.githubusercontent.com/14934314/166860099-f217a425-f613-4604-917f-578b8f9b379f.png">

**Comment by kubu4** [comment]
Type `exit`

**Comment by grace-ac** [comment]
gah it keeps getting interrupted. it's been stuck for the past hour or two.

thinking of doing this from a computer at FTR instead...

**Comment by kubu4** [comment]
You actually ARE doing this on a computer from FTR - Owl.

However, it might be best to abandon FTP and try a different transfer method...

**Comment by grace-ac** [comment]
@sr320 @kubu4 to download the data, I need macOS 10.12 or higher.     
Can I update Ostrich to 10.12?     
Or would you rather I use genefish in ftr 230 which is already OS 10.12

**Comment by sr320** [comment]
Use the one in FTR 230

**Comment by grace-ac** [comment]
I have all the fastq and md5 files for all 32 libraries on genefish. Should I check the md5 now before moving files to owl? trying to find/remember how to do that 

sidetone: the files will remain on azenta servers until may 28th and i head out to marrowstone tomorrow

**Comment by kubu4** [comment]
Yep! Check MD5s after all transfers (unless transfer is via rsync). Do you know how to do this automatically?

**Comment by grace-ac** [comment]
Ok cool! I do not know how, though I'm sure I've done it at some point!   
I looked through the code snippets and such on the robertslab.github.io, but didn't see anything there.

**Comment by kubu4** [comment]
Are the files on a Mac or Linux computer?

**Comment by grace-ac** [comment]
they're on mac - genefish.

**Comment by kubu4** [comment]
I was afraid you were going to say that... One sec...

**Comment by kubu4** [comment]
Can you please check to see if genefish (I don't know how to get into genefish - lab computer sheet has genefish greyed out, so not sure if the info on there is accurate any more - otherwise I'd check) has `md5sum` installed?

Run this command: `which md5sum`

If it returns nothing, then it is _not_ installed.

**Comment by grace-ac** [comment]
it returned nothing

**Comment by kubu4** [comment]
I guess I should just post both options, regardless.

Option 1 (requires `md5sum` to be installed on computer):

```shell
for file in *.md5
do
md5sum --check ${file}
done
```

---

Option 2 (use if `md5` program is only option):

```shell
for checksum_file in *.md5
do
# Gets filename without any suffixes
filename=$(basename --suffix .fastq.gz.md5 ${checksum_file})
# Generates MD5 checksum and compares to provided checksum in MD5 file
diff <(md5 "${filename}.fastq.gz" | awk '{print $4}') <(awk '{print $1}' ${checksum_file})
done
```

---

So, Option 2 is what is needed to handle the difference between MD5 checksum programs on Linux and Mac. The two operating systems format the output differently, making it difficult to do an easy check. So, we have to generate the checksums for the FastQ files and use `awk` to parse out just the checksum, and then use `awk` on the provided MD5 file to parse out the provided checksum from that file. Then, we use the `diff` program to compare the two values.

If they match, _nothing_ will be returned (that's good)!

If they _don't_ match, then they didn't download properly _OR_ there's a problem with the code I provided (this is the more likely problem; particularly if _none_ of the comparisons match).

**Comment by grace-ac** [comment]
dang! ok, so I should try to do Option 2, and I do it for each .md5 file?

**Comment by kubu4** [comment]
Run code provided in Option 2.

**Comment by grace-ac** [comment]
Ran code: Each file had this: 

```
basename: illegal option -- -
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
md5: .fastq.gz: No such file or directory
0a1
> b06f7ad61a429daba9fce4ae64de7977
basename: illegal option -- -
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
md5: .fastq.gz: No such file or directory
0a1
> 8e1819cfb90c86eda68c6f160e4b408f
basename: illegal option -- -
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
md5: .fastq.gz: No such file or directory
0a1
> 566b8ea6beff860f9eb4d6e24717a298
```

**Comment by kubu4** [comment]
Replace `--suffix` with `-s` and give it another rip.

Ugh, Macs! 😉

**Comment by sr320** [comment]
You could just go ahead and move to final destination (linux) then md5 :)

**Comment by grace-ac** [comment]
can't quite tell if it's still working on it.  hasn't changed in ~10 minutes. 
![Screen Shot 2022-05-24 at 3 45 33 PM](https://user-images.githubusercontent.com/14934314/170144365-347f68cf-d702-49f0-ab6f-5ea5952a5954.png)

**Comment by kubu4** [comment]
It'll take awhile.

No new prompt (or error messages) means it's still running.

**Comment by grace-ac** [comment]
it's finished and it just went right back to the $ prompt! so I'm guessing that means it worked?

**Comment by kubu4** [comment]
Yep! No errors, means all good!

**Comment by grace-ac** [comment]
woohoo! thanks sam!!

**Comment by kubu4** [comment]
My pleasure!

**Comment by grace-ac** [comment]
I've only ever done `rsync` to/from Mox. Do I need to ssh into owl first? 

Just tried to do from gene fish to nightingales on owl: 
00-fastq is the directory that contains all the .fastq.gz and .md5 files. 

```
rsync --archive --progress --verbose --relative ./00-fastq grace@owl_128.95.149.83:/nightingales/P_helianthoides
```

Here's what was returned:    
```
 ssh: Could not resolve hostname owl_128.95.149.83: nodename nor servname provided, or not known
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.2/rsync/io.c(453) [sender=2.6.9]
```

**Comment by sr320** [comment]
@grace-ac When you get a chance can you put all of these protocols in handbook?

**Comment by grace-ac** [comment]
@sr320 absolutely!

**Comment by kubu4** [comment]
> grace-ac When you get a chance can you put all of these protocols in handbook?

BTW, some of this might already exist in code repo (can't check ATM)... This starts to get back into how much we put in Handbook versus leave in code repo... But, I digress.

**Comment by sr320** [comment]
> how much we put in Handbook versus leave in code repo

Handbook should be go to source for everything

**Comment by kubu4** [comment]
Your code would have to be something like this:

```bash
rsync --archive --progress --verbose PSC*.fastq.gz <owl username>@128.95.149.83:/volume1/web/nightingales/P_helianthoides/
```

Replace `<owl_username_>` with whatever username you use to login to owl (even replace the `<` and the `>`).

**Comment by kubu4** [comment]
> Handbook should be go to source for everything

Agreed, but there're a _lot_ of random code snippets in that code repot...

**Comment by grace-ac** [comment]
thank you @kubu4 ! It's working.

**Comment by grace-ac** [comment]
how do I append the md5 checksums to the checksum file? they are all currently on gene fish , but they need to be added to nightingales. there's already a checksum file in the [ /nightingales/P_helianthoides/](http://owl.fish.washington.edu/nightingales/P_helianthoides/) folder on owl.

**Comment by kubu4** [comment]
If you transferred the files via `rsync` then you can be confident that the transfers were successful, without file corruption. So, the easiest thing to do is to `ssh` into owl and navigate to `/nightingales/P_helianthoides/`.

Then, do the following:

```shell
for fastq in PSC*.fastq.gz
do
  md5sum "${fastq}" >> checksums.md5
  echo "Generated checksum for ${file}."
  echo ""
done
```

It will take awhile, but you should start seeing the message pop up on the screen as it completes each file.

**Comment by grace-ac** [comment]
is it working? it doesn't list file names, just what's seen in screenshot below


![Screen Shot 2022-06-15 at 4 32 32 PM](https://user-images.githubusercontent.com/14934314/173959226-0fccdc8b-0469-4379-9260-5b9c924635f0.png)

**Comment by grace-ac** [comment]
it worked!! all good. thanks @kubu4 !!

![Screen Shot 2022-06-15 at 4 47 37 PM](https://user-images.githubusercontent.com/14934314/173960601-f48c27b9-8242-447e-8c63-ab531ccdb55f.png)

**Comment by kubu4** [comment]
Yep, my bad on part of that code.

CHALLENGE: Can you figure out what I did wrong?

**Comment by grace-ac** [comment]
would it have shown the file names if it didn't have the "." after ${file} ?

**Comment by kubu4** [comment]
Close, but not quite right.

The issue here is that the `echo` statement uses the variable `${file}`. However, the variable `${file}` is not defined, so that means that the variable `${file}` is empty. So, when the `echo` statement prints, it just prints an empty space when it gets to the `${file}` variable.

Basically, I should've used the variable that the for loop is referring to: `${fastq}`
