### ISSUE TITLE
RNeasy Plus Mini Kit

### ISSUE THREAD

**Issue by jldimond** [RobertsLab/resources#147]
According to the lab inventory, there is an RNeasy Plus Mini Kit that was received in late 2013. A few questions:

1. Has any of it been used?
2. Can I use it?
3. Is it worth using given its age? The manual states "The RNeasy Plus Mini Kit should be stored dry at room temperature (15–25ºC) and is stable for at least 9 months under these conditions."

**Comment by kubu4** [comment]
I would not use it, unless you're just trying out samples as a test.

**Comment by jldimond** [comment]
OK, thanks. I will go for a new kit.
