### ISSUE TITLE
Rstudio frozen only in one Rproject

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1473]
Rstudio freezing when I try to work in https://github.com/grace-ac/paper-pacific.oyster-larvae/blob/master/paper-pacific.oyster-larvae.Rproj 

As soon as I open the Rproject, I can't do anything. I can't even use the drop down menus at the top. 

I've uninstalled and reinstalled R studio, I've updated R. 

All my other Rprojects work fine. 

Any thoughts? I found a comment thread that suggests potential corruption of a .Rproj.user folder, ([online discussion](https://community.rstudio.com/t/rstudio-desktop-unresponsive-in-project/5224)), but I don't see one of those.

**Comment by sr320** [comment]
Have you tried on raven?

**Comment by grace-ac** [comment]
nope! will do now

**Comment by sr320** [comment]
I did a clean pull from Github and there were no issues ... https://d.pr/i/dHVExI

**Comment by grace-ac** [comment]
awesome! i just did that too and it's all fixed. not sure what happened to make it freeze like that initially. thanks!
