### ISSUE TITLE
Add HiSat workflow to handbook

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1477]
https://github.com/RobertsLab/resources/blob/master/docs/bio-Gene-expression.md

**Comment by kubu4** [comment]
What are you looking for with this? Looking at that page, it seems like we're just sharing examples of times when each of those programs were used. Is that all?

**Comment by sr320** [comment]
I would like it built out so it is somewhat of a complete guide, pointing to code elsewhere is fine.

**Comment by sr320** [comment]
Along same line - https://github.com/RobertsLab/resources/issues/1476#issuecomment-1155895750 should be integrated into said page in handbook.

**Comment by kubu4** [comment]
Check it out: https://robertslab.github.io/resources/bio-Gene-expression/#alignment-hisat2
