### ISSUE TITLE
Current favorite C/T SNP caller from bisulfite methylation data 

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#1479]
What are folks using these days to identify C/T SNPs from bisulfite methylation data?  I need to identify loci that are C/T SNPs in my MBD-Seq data, to quantify then and possibly remove them from my differential methylation analysis. 

I see that some folks have used BSnpr (Issue #1394, Discussion #1389), but recently @ksil91 recommended using the [Epidiverse/SNP pipeline](https://github.com/EpiDiverse/snp). Thoughts? Scripts?

**Comment by sr320** [comment]
I am trying BSnpr but it is very finicky.
does not like lots of contigs, does not one contig with long line, ....

**Comment by sr320** [comment]
@yaaminiv can you provide an example where you were able to get it to work for your data?

**Comment by yaaminiv** [comment]
My understanding is that BSnper is good, but Epidiverse/SNP acts more like GATK and may be more robust. 

@sr320 I didn't have any issues using BSnper for Manchester and Hawaii data...here's my code: https://github.com/RobertsLab/project-gigas-oa-meth/blob/master/code/07-BS-SNPer.ipynb

**Comment by sr320** [comment]
@yaaminiv thanks! I added you code to  handbook https://robertslab.github.io/resources/bio_DNA-methylation/#bs-snpr
