### ISSUE TITLE
Raven access? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1481]
Can i get Raven access for doing FastQC with sea star rnaseq data?

**Comment by kubu4** [comment]
Follow the instructions here and I'll get you an account: https://github.com/sr320/ceabigr/wiki/RStudio-Server-Instructions

**Comment by grace-ac** [comment]
got it! 

UW NetID: graceac9

**Comment by kubu4** [comment]
See Slack for info.
