### ISSUE TITLE
Download and QC RNAseq data PRJNA316738

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1482]
Lake trout data..

**Comment by kubu4** [comment]
Where do you want this data to be stored?

**Comment by sr320** [comment]
Gannet would be fine

**Comment by kubu4** [comment]
This just completed. 

Data is here: https://gannet.fish.washington.edu/Atumefaciens/20220706-snam-fastqc-fastp-multiqc-rnaseq-PRJNA316738/

Raw FastQs: `*.fastq`

Trimmed FastQs: `*trimmed*.fq.gz`
