### ISSUE TITLE
Git Push from Raven

### ISSUE THREAD

**Issue by afcoyle** [RobertsLab/resources#1487]
Hi all, I just did a bunch of work on Raven (using RStudio), and am now trying to get it back to Github! Encountering some problems

Option 1: Push directly from RStudio. Doesn't work, as I don't have a PAT set up (plus can't config my username without accessing the command line). I could set up a PAT, but that requires installing the package "usethis", and I don't have access to install packages on Raven

Option 2: Remote in to Raven, and just commit + push as usual from the command line. Also doesn't work, as my password isn't working for some reason! 

Any suggestions on what to do here?

**Comment by sr320** [comment]
You need a PAT. You can install packages (but you do not need to).

**Comment by sr320** [comment]
See https://github.com/sr320/ceabigr/discussions/18

**Comment by kubu4** [comment]
As an aside, it would be ideal if you could share screenshots of messages (error messages and anything else that pops up when encountering problems). It will help us troubleshoot more effectively.

**Comment by afcoyle** [comment]
Nope - I'm actually having problems even accessing Raven right now! When I try to log in through the web RStudio portal, I'm getting an "internet out" error. Is this a temporary outage for Raven, or is the issue on my end?

**Comment by sr320** [comment]
Probably you- I was just on. Can you screenshot error?

**Comment by afcoyle** [comment]
Ooh nope, I bet that's the issue! Alright setting up VPN now, will update on outcome after trying that

**Comment by afcoyle** [comment]
Alright update, now able to get on Raven remotely (thanks Steven)! 

However, still running into an issue. When I try to make a commit through the GitHub interface, it doesn't recognize me as having the authority to commit things (because it doesn't recognize my email). 

![image](https://user-images.githubusercontent.com/71358918/176038771-905802c1-29a1-41e1-8edb-3256a6349ead.png)

**Comment by sr320** [comment]
You need to run those two commands replacing what is in quotes.

**Comment by sr320** [comment]
You also have a distinct terminal window within RStudio.
