### ISSUE TITLE
Get test data run using epidiverse:SNP

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1488]
https://github.com/EpiDiverse/snp

**Comment by kubu4** [comment]
Need to do some additional testing, but it looks promising...

![image](https://user-images.githubusercontent.com/4514104/177651623-f7a8d97b-6c1f-4ecf-8a23-f699aa6ca66d.png)

**Comment by kubu4** [comment]
Alrighty, got it running!

Two critical things to make it run properly.

1. Command needs to look like this, with _no space_ after the comma and before the `docker` (as mentioned in #1485):

```shell
NXF_VER=20.07.1 /home/shared/nextflow run epidiverse/snp -c nxf.config -profile test,docker
```

2. To avoid a permissions issue with the subsequent output files, you also need to create (and call; shown above with: `-c nxf.config`) a supplementary config file. In my example above (and here), I've called the file `nxf.config`. It can be any name you'd like. The file should look like this:

```
$cat nxf.config 
docker {
	fixOwnership = true
}
```
```

**Comment by sr320** [comment]
Fxxking space! 😭
