### ISSUE TITLE
Run Oly BS data through Epidiverse:SNP

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1489]
sorted bams: https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/020320-oly/

genome: http://owl.fish.washington.edu/halfshell/genomic-databank/Olurida_v081.fa

**Comment by kubu4** [comment]
Should I use the deduplicated sorted bams?

**Comment by sr320** [comment]
Yes

**Comment by sr320** [comment]
In the event you want to start with "simpler" genome, here it is crammed into 14 contigs

https://gannet.fish.washington.edu/seashell/bu-github/paper-oly-mbdbs-gen/data/bgdata/Olurida_v081-mergecat98.fa

and the corresponding bam files (dedup, sorted) inside https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/070322-olymerge-snp/

**Comment by kubu4** [comment]
Don't want to jinx things, but using this reduced dataset, the pipeline has already gotten past the section where it was previously dying...

**Comment by kubu4** [comment]
@sr320 Would like to test pipeline with different data (i.e. different species). When you have a sec, can you please point me to a different set of Bismark, deduplicated BAMs and the corresponding genomes?

**Comment by sr320** [comment]
more bams....

geoduck are in this dir 
https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/1231/

and CEABiGR (cvir)

https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/071521-cvBS/

**Comment by sr320** [comment]
Genomes are on genomic resources page

**Comment by kubu4** [comment]
I was able to successfully run the `epidiverse/wgbs` pipeline on a couple of the Oly BSseq FastQ samples (using the reduced genome). I then used the subsequent BAMs from those two samples as input to the `epidiverse/snp` pipeline and things look very different:

![image](https://user-images.githubusercontent.com/4514104/179315350-1047638f-893d-4bf1-8bbf-c04d093df948.png)


Possible that Bismark-processed BAMs are screwy?

To answer, I'm about to test Bismark BAMs from geoduck...

**Comment by kubu4** [comment]
Well, here's the result of the `epidiverse/snp` pipeline when using the geoduck Bismark analysis:

![image](https://user-images.githubusercontent.com/4514104/179322334-b2003dfc-1f54-4fd8-b802-17fb6d89be8f.png)

It seems like something funky happened with the Oly Bismark analysis.

**Comment by kubu4** [comment]
I'll run all of the Oly (zr1394) FastQs through both pipelines and see how it turns out. Will probably take a couple of days to run. Will report back when complete.

**Comment by kubu4** [comment]
Remarkably, I was able to run all 18 Oly samples through the `epidiverse/wgbs` _and_ the `epidiverse/snp` pipelines! Started with the trimmed zr1394 FastQs ([from 20180503](https://owl.fish.washington.edu/Athaliana/20180503_oly_methylseq_trimgalore/)). However, the substitution results are all similar to what the looked like using the Bismark BAMs!

[You can poke around here](https://gannet.fish.washington.edu/Atumefaciens/20220716-olur-zr1394-all-epidiverse-snp/), but now I'm baffled. Will re-check the "successful" run which produced the normal looking substitutions bar plots and make sure I ran things correctly and report back. Ugh!

**Comment by kubu4** [comment]
Hmmm, just realized the "successful" Oly samples utilized the _un_trimmed reads and the trimming was performed via the `epidiverse/wgbs` pipeline...

**Comment by kubu4** [comment]
Here's an overview of the various comparison's I've run to date (all Oly data uses reduced genome):

| Oly Bismark                                                                                                                                                                                                                       | Geoduck Bismark                                                                                                                                                                                                                                    | Oly EpiDiverse Adaptor Trim                                                                                                                                                                                                               | Oly EpiDiverse Adaptor and 10bp 5’ Trim                                                                                                                                                                                                                         |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ![Substitions barplot showing almost only C>T subsitutions](https://gannet.fish.washington.edu/Atumefaciens/20220713-olu-epidiverse-snp-all/snps/stats/zr1394_1_s456_trimmed_bismark_bt2.deduplicated.sorted/substitutions.0.png) | ![Subsitutions barplot showing expected distribution of SNPs](https://gannet.fish.washington.edu/Atumefaciens/20220715-pgen-epdiverse-snp-bismark/snps/stats/EPI-205_S26_L004_R1_001_val_1_bismark_bt2_pe.deduplicated.sorted/substitutions.0.png) | ![Substituions barplot showing better, but still skewed SNP distributions](https://gannet.fish.washington.edu/Atumefaciens/20220720-olur-zr1394_all_untrimmed-nextflow_epidiverse-snp-conda/snps/stats/zr1394_1_s456/substitutions.0.png) | ![Substitutions barplot showing similar skewing to default EpiDiverse trimming](https://gannet.fish.washington.edu/Atumefaciens/20220721-olur-zr1394_all_untrimmed-nextflow_epidiverse-snp-conda-trim_10bp_5prime/snps/stats/zr1394_1_s456/substitutions.0.png) |
