### ISSUE TITLE
Column and method Info from 2017 DIA & SRM run 

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#149]
@emmats can you provide some column and method details from the DIA & SRM runs for my paper (and likely @yaaminiv's paper too)? Going off of your 2017 geoduck paper, it looks like we should include the following (you'll see I already have some of the SRM info, copied from your Evernote entry back in July):

DIA:
* Analytical column length
* Trap length
* Column packing material (in your paper you used C18 beads ((Dr. Maisch HPLC, Germany, 0.3 μm))
* Column flow rate during packing 
* Chromatography solvent/gradient details from method. E.g. in your paper you list _a gradient of 5−80% ACN over 90 min._

SRM: 
* Analytical column length: 30 cm
* Trap length: 3 cm 
* Packing material & flow rate during packing: (I assume the same as in DIA)
* Pertinent solvent gradient/methods information

Feel free to check out the [draft paper](https://docs.google.com/a/uw.edu/document/d/1LEzRkAWbgG62Ju3qxKnpDVLUAPlknxGWsARVRzEzvMg/edit?usp=sharing) I'm working on if you'd like to review my DIA & SRM methods thus far. I'm not sure how detailed the methods section will ultimately be; at the moment I'm erring on the side of quite detailed. 

Thanks!

**Comment by yaaminiv** [comment]
Most of that information is in my [draft paper](https://docs.google.com/document/d/1giP16iXWPE7oDSNI7fyLV3p_1jqsXuuxlH7cJQAwhLM/edit#heading=h.7vvlns7jaib) (I believe)

**Comment by laurahspencer** [comment]
Thanks! So it looks like the analytical and trap column lengths are the same in DIA as they were for SRM (30cm, 3cm). For DIA, you have info for column equilibration, but It looks like we still need the 90-min DIA method info.  Same for SRM (if applicable...?).

**Comment by emmats** [comment]
I will work on this soon. I'm in the lab with high school students today!

**Comment by sr320** [comment]
is this issue still open? (ie not resolved?)

**Comment by laurahspencer** [comment]
Nearly complete, I'm resolving as comments in draft paper.
