### ISSUE TITLE
Review ceabigr summary stat calculations..

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1490]
I am pretty sure calculations including mean, max, and possibly stdev are incorrect...

See screen recording.. all samples have count of 1...  thus mean should equal 1, max would be 1.
https://d.pr/i/QZo38o

**Comment by kubu4** [comment]
Gah! Sorry! I think I've identified issue in code. The code doing the calcs is this:

```r
transcript_counts_per_gene_per_sample <- transcript_counts %>%
  rowwise() %>% 
  mutate(
    sum_transcript_counts = sum(c_across(where(is.numeric))),
    median_transcript_counts = median(c_across(where(is.numeric))),
    mean_transcript_counts = mean(c_across(where(is.numeric))),
    max_transcript_counts = max(c_across(where(is.numeric))),
    min_transcript_counts = min(c_across(where(is.numeric))),
    std_dev_transcript_counts = sd(c_across(where(is.numeric)))
  )
```

I interpreted this as each of these commands (`sum`, `median`, etc) as _only_ working on the original data piped in (`transcript_counts`). However, I think the each command successively works on the original data, _plus_ the new column of data by each preceding function...

I think it's an easy fix.

Thanks for catching and sorry I didn't catch this previously!

**Comment by kubu4** [comment]
Alrighty, these should be fixed! Quick glance and the calcs look much better.

FYI, modified code above to look like this:

```r
# Perform calculations
transcript_counts_per_gene_per_sample <- transcript_counts %>%
  rowwise() %>% 
  mutate(
    sum_transcript_counts = sum(c_across(where(is.numeric) & -any_of(count_calcs))),
    median_transcript_counts = median(c_across(where(is.numeric) & -any_of(count_calcs))),
    mean_transcript_counts = mean(c_across(where(is.numeric) & -any_of(count_calcs))),
    max_transcript_counts = max(c_across(where(is.numeric) & -any_of(count_calcs))),
    min_transcript_counts = min(c_across(where(is.numeric) & -any_of(count_calcs))),
    std_dev_transcript_counts = sd(c_across(where(is.numeric) & -any_of(count_calcs)))
  )
```

Used the '-any_of()` function with a vector of column names that I wanted to skip when doing the calculations.
