### ISSUE TITLE
Determine if inherent issue with Oly MBD data and Epidiverse SNP

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1493]
Query developer to determine what might cause discrepancy in oly and duck data. Oly is MBD while duck is WGS, but not clear why that would influence. Also they might have other explanation..

![plot](http://gannet.fish.washington.edu/seashell/snaps/2022-08-03_10-32-11.png)

**Comment by kubu4** [comment]
Have reopened [issue on `EpiDiverse/snp` repo](https://github.com/EpiDiverse/snp/issues/9). Will report back if developer responds.
