### ISSUE TITLE
Designing new primers for mussel heat stress

### ISSUE THREAD

**Issue by zbengt** [RobertsLab/resources#1496]
Find new primers to use for qPCR of FISH 541 lab samples. Using [this lab notebook post](https://zbengt.github.io/2022-08-02-Mussel_HeatStress_Primers/) to keep track.

**Comment by zbengt** [comment]
Dorothy's project indicates that the primers we already have for MT10, MT20, small HSP24.1, SQSTM1, HSC70, HSP90, and GADD45 gamma should be sufficient. Look at [this lab notebook post](https://zbengt.github.io/2022-08-02-Mussel_HeatStress_Primers/) (Update 08-05-2022).

**Comment by sr320** [comment]
What about melt curve for these primers? Please check to assess. 
GADD45
https://owl.fish.washington.edu/scaphapoda/qPCR_data/cfx_connect_data/sam_2022-07-27%2010-02-05_BR006896.pcrd

HSC70 & sHSP24
https://owl.fish.washington.edu/scaphapoda/qPCR_data/cfx_connect_data/sam_2022-07-27%2011-15-14_BR006896.pcrd

MT10 & MT20
https://owl.fish.washington.edu/scaphapoda/qPCR_data/cfx_connect_data/sam_2022-07-27%2012-31-17_BR006896.pcrd

HSP90 & SQSMT1
https://owl.fish.washington.edu/scaphapoda/qPCR_data/cfx_connect_data/sam_2022-07-27%2013-23-11_BR006896.pcrd

Ferritin (did not amplify)
https://owl.fish.washington.edu/scaphapoda/qPCR_data/cfx_connect_data/sam_2022-07-27%2014-17-42_BR006896.pcrd

**Comment by mattgeorgephd** [comment]
@zbengt re: discussion during science hour, papers w/ primers for mussel foot proteins (mfp). Mfp-1, -3, and -5 from _M. galloprovincialis_ are likely the most similar to _M. trossulus_.

_Mytilus galloprovincialis_ - [Boortoletto et al 2021](https://www.isj.unimore.it/index.php/ISJ/article/view/651), [Miki et al 1996](https://pubmed.ncbi.nlm.nih.gov/8652732/), [Inoue et al 1996](https://febs.onlinelibrary.wiley.com/doi/full/10.1111/j.1432-1033.1996.0172u.x)

_Mytilus californianus_ - [DeMartini et al 2017](https://royalsocietypublishing.org/doi/full/10.1098/rsif.2017.0151), [Zhao & Waite 2006](https://pubs.acs.org/doi/full/10.1021/bi061677n?casa_token=EY2dUNGm5_QAAAAA%3AzL7c9WTSMN3G7EOEYmuFj6_Mvr0IewuXL78pfnTNC04t7u-e5sWP_QDyw7OvgRZTE9YrXnQhCYhswg), [Floriolli et al 2000](https://link.springer.com/content/pdf/10.1007/s101269900032.pdf)

_Mytilus coruscus_ - [Li et al 2020](https://www.sciencedirect.com/science/article/pii/S0048969720328643?casa_token=tQhBh_aiH40AAAAA:p5ls82lgVhCqG300mA083R6JyHe2XXY0_l4057d96wy5kEQhDmrGs2Qd64N7o9EzdZDCAB4D), [Zhao et al 2017](https://www.int-res.com/abstracts/meps/v565/p67-77/), [Qin et al 2016](https://www.sciencedirect.com/science/article/pii/S1874391916302548?casa_token=j5Vw8nHziiYAAAAA:Dctj2IwMXFdIG4b-ASmzj78GDoCX_vmQh1ww0SWUtaNjU6x6rGOienDkKm_GFCOvZBPhGlqO)
