### ISSUE TITLE
Install STAR on Raven

### ISSUE THREAD

**Issue by mattgeorgephd** [RobertsLab/resources#1499]
Install STAR aligner on Raven

Link to manual:
https://physiology.med.cornell.edu/faculty/skrabanek/lab/angsd/lecture_notes/STARmanual.pdf

**Comment by mattgeorgephd** [comment]
Also khmer please!

Link:
https://pypi.org/project/khmer/

**Comment by kubu4** [comment]
STAR is here: `/home/shared/STAR-2.7.10a/bin/Linux_x86_64_static/STAR`

For `khmer`, you'll need to do this in an Anaconda environment. Activate conda and then follow the `khmer` instructions for "Quick Install".

NOTE: You may need to install `pip` in your conda environment prior to trying to install `khmer`.  If you encounter any problems/questions/etc installing `khmer`, just create a new issue and we'll get things straightened out.
