### ISSUE TITLE
Review/confirm BSseq library construction

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#150]
Stuff we need:

- TruSeq DNA Methylation Index PCR Primers, 12 indices, 10 rxns per index ($950)
- TruSeq DNA Methylation Kit, 96 reactions ($5405)
- Ampure beads, 5mL ($320)
- Dynamag-2 ($598)

Below are some links to info/data from some previous BSseq projects, for reference:

A previous project of in-house TruSeq Methylation library construction: http://onsnetwork.org/kubu4/2015/12/31/data-received-oly-2brad-illumina-sequencing-from-genewiz/

ZymoResearch library construction & sequencing from MBD-enriched DNA: http://onsnetwork.org/kubu4/2016/02/03/data-received-ostrea-lurida-mbd-enriched-bs-seq/

**Comment by sr320** [comment]
exploring Zymoresearch as on option

**Comment by kubu4** [comment]
Zymo quote is $827/sample (total $8270 for these 10 samples). We send them MBD enriched DNA, they do the rest (i.e. bisulfite treatment, library construction, sequencing).

- 50bp PE
- 20 million reads per sample.

**Comment by kubu4** [comment]
Updated quote from Zymo, with 5% discount:

$7856.50
