### ISSUE TITLE
Access request

### ISSUE THREAD

**Issue by magobu** [RobertsLab/resources#1500]
Hi Steven,
Just requesting access to your lab's node in the cluster.
Thanks!

**Comment by magobu** [comment]
Thank you. For the set up now, I'm folowing the instructions on the link Steven gave me [Robert's Lab Handbook](https://robertslab.github.io/resources/mox_Adding-a-User/), and on the "for the users", when I open my "Manage UW netid resources" and click on the "Computing services", there are no options for Hyak or Lolo services to check under "inactive services" category. Is this mean that I should wait to be added to the group?

**Comment by kubu4** [comment]
Alrighty, you've been added to our lab's computing group. Follow instructions in the Roberts Lab Handbook you linked above. If you have any other questions/problems/etc., please feel free to create a new issue.

**Comment by magobu** [comment]
Great! thanks :)

Marta Gómez-Buckley
PhD Candidate
Fish Systematics and Biodiversity Lab
School of Aquatic and Fishery Sciences
University of Washington
