### ISSUE TITLE
Berdahl-sockeye-salmon tagseq

### ISSUE THREAD

**Issue by mattgeorgephd** [RobertsLab/resources#1501]
Progress:
1. Previous [issue](https://github.com/RobertsLab/resources/issues/1410) regarding RNA extraction
2. Completed RNA extractions from the liver, gonad, and brain of 30 sockeye salmon. Sample list and plate map available [here](https://www.dropbox.com/s/snq453edfxeor6t/Berdahl_sockeye_salmon.xlsx?dl=0).
3. Due to RNA quality concerns - submitted gonad samples ONLY to UT Austin on 5/24/2022. Quote available [here](https://www.dropbox.com/s/znk1cikjtrj9v6n/GSAF_Quote_Job_JA22192_2022-05-09.pdf?dl=0). GSAF sample manifest available [here](https://www.dropbox.com/s/9yuso7jhkazikrt/GSAF%20Sample%20Manifest_Job%23JA22192_2022-05-12.pdf?dl=0).
4. Received sequencing data from UT Austin on 7/14/2022. Ran fastqc and multiqc on [untrimmed](https://gannet.fish.washington.edu/panopea/berdahl-sockeye-salmon/multiqc_report.html) and [trimmed](https://gannet.fish.washington.edu/panopea/berdahl-sockeye-salmon/multiqc_report_trimmed.html) fastq files.  
5. Aligned to O. Nerka genome assembly - [transcripts FASTA](https://www.ncbi.nlm.nih.gov/data-hub/genome/GCF_006149115.2/). Bowtie2 average alignment rate =  65.91 +/- 4.87; Hisat2 = 50.14 +/- 5.81.

Opinions on how to proceed? Should we submit the remaining samples?

**Comment by kubu4** [comment]
Are there any details on how libraries were constructed (i.e. did they use a kit? If yes, which one?)? How was trimming performed?

**Comment by kubu4** [comment]
Glancing at the trimmed data, I'd think you might still want (need?) to trim the first ~15bp?

![image](https://user-images.githubusercontent.com/4514104/183443981-660532c9-0b4c-4db5-8c72-b2394b886a3d.png)

**Comment by mattgeorgephd** [comment]
@kubu4 Good catch. I'm running the following code, but is doesn't look like the ```-q 15``` is working. Any ideas?

```
for F in *.fastq
do
# strip .fastq and directory structure from each file, then
# add suffice .trim to create output name for each file
results_file="$(basename -a $F)"

# run cutadapt on each file
/home/shared/8TB_HDD_02/mattgeorgephd/.local/bin/cutadapt $F -a A{8} -a G{8} -a AGATCGG -q 15 -m 20 -o \
/home/shared/8TB_HDD_02/mattgeorgephd/berdahl-sockeye-salmon/trim-fastq/$results_file
done
```

**Comment by mattgeorgephd** [comment]
Figured it out - need to use the ```-u 15``` instead!

**Comment by mattgeorgephd** [comment]
After hard trimming, merging by lane, and switching to this [sockeye salmon assembly](https://www.ncbi.nlm.nih.gov/assembly/GCF_006149115.2) hisat2 achieved an average alignment rate of 88.66% +/- 2.21 sd. Giving the go ahead to UT Austin to run the rest of the samples.

**Comment by sr320** [comment]
go forward with other tissues..

**Comment by mattgeorgephd** [comment]
Request approved through the GSAF to run remaining samples under new Job # [JA22330](https://ut-austin-gsaf.force.com/s/gsaf-job-info-tool)
