### ISSUE TITLE
my folder question

### ISSUE THREAD

**Issue by magobu** [RobertsLab/resources#1502]
I have added a folder (martagb) to the group-specific storage space. I was going to transfer my raw data there, but I wanted to check first that space wise this was okay. My raw data consists of eight large .gz files totaling ~200gb. I tried   <mmlsquota -j srlab gscratch --block-size G> to check for space on that group's storage, but it gives me this error message:

mmlsquota: Name "--block-size" is not allowed.

   It contains a dash (-) as its first character.

Best,
Marta

**Comment by kubu4** [comment]
Yes, your file sizes are fine.

But, to get into the "nitty gritty", here are two tips:

1. To see available space in our user group, you can just view this file:

`/gscratch/srlab/usage_report.txt`

That's an auto-updated file generated by Mox.

2. If you're worried about space, use `/gscratch/scrubbed/`. This has virtually unlimited storage amounts. However, data/files are automatically deleted once they are older than 30 days.

**Comment by magobu** [comment]
Thanks Sam!
