### ISSUE TITLE
Mussel heat stress experiment methods

### ISSUE THREAD

**Issue by zbengt** [RobertsLab/resources#1504]
Starting methods in [this doc](https://docs.google.com/document/d/10QEJBxxuIshe86aFV_8EuL5WKzX9SvJT_2HosNxuZqQ/edit?usp=sharing)

@sr320 - Not including respirometry correct? Are the protocols for cDNA synthesis and qPCR somewhere? We wrote our own up based on what you taught us in class/wrote on the board.

**Comment by kubu4** [comment]
> Are the protocols for cDNA synthesis and qPCR somewhere? 

Yes. In the handbook.

**Comment by sr320** [comment]
> Not including respirometry correct?

I would include respirometry
