### ISSUE TITLE
Trinity error on Raven: no module name numpy

### ISSUE THREAD

**Issue by mattgeorgephd** [RobertsLab/resources#1506]
Hey Sam! Figured out the last issue, got a new Trinity error for you ;). Looking through the issues on the trinity github I think maybe we need to [update to python3](https://github.com/trinityrnaseq/trinityrnaseq/issues/730)?

Python --version returns "Python 2.7.17"

### running this code: 
```{bash}
export PATH=/home/shared/samtools-1.12:$PATH
export PATH=/home/shared/jellyfish-2.3.0/bin:$PATH
export PATH=/home/shared/bowtie2-2.4.4-linux-x86_64:$PATH
export PATH=/home/shared/salmon-1.4.0_linux_x86_64/bin:$PATH

mkdir trinity_out/

/home/shared/trinityrnaseq-v2.12.0/Trinity --seqType fq \
--left sequences/SRR6051615_1.fastq \
--right sequences/SRR6051615_2.fastq \
--max_memory 256G \
--CPU 48 \
--output home/shared/8TB_HDD_02/mattgeorgephd/PSMFC-mytilus-byssus-pilot/trinity_out/

```
### I get this error:
```
Error encountered::  <!----
CMD: /home/shared/trinityrnaseq-v2.12.0/Analysis/SuperTranscripts/Trinity_gene_splice_modeler.py --trinity_fasta /home/shared/8TB_HDD_02/mattgeorgephd/PSMFC-mytilus-byssus-pilot/home/shared/8TB_HDD_02/mattgeorgephd/PSMFC-mytilus-byssus-pilot/trinity_out/read_partitions/Fb_0/CBin_30/c3083.trinity.reads.fa.out/Trinity.tmp.fasta.filt --out_prefix /home/shared/8TB_HDD_02/mattgeorgephd/PSMFC-mytilus-byssus-pilot/home/shared/8TB_HDD_02/mattgeorgephd/PSMFC-mytilus-byssus-pilot/trinity_out/read_partitions/Fb_0/CBin_30/c3083.trinity.reads.fa.out/Trinity.tmp.fasta.filt.ST --incl_cdna 2>tmp.41254.1660256084.stderr

Errmsg:
Traceback (most recent call last):
  File "/home/shared/trinityrnaseq-v2.12.0/Analysis/SuperTranscripts/Trinity_gene_splice_modeler.py", line 11, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'

--->

Trinity run failed. Must investigate error above.
warning, cmd: /home/shared/trinityrnaseq-v2.12.0/util/support_scripts/../../Trinity --single "/home/shared/8TB_HDD_02/mattgeorgephd/PSMFC-mytilus-byssus-pilot/home/shared/8TB_HDD_02/mattgeorgephd/PSMFC-mytilus-byssus-pilot/trinity_out/read_partitions/Fb_0/CBin_30/c3083.trinity.reads.fa" --output "/home/shared/8TB_HDD_02/mattgeorgephd/PSMFC-mytilus-byssus-pilot/home/shared/8TB_HDD_02/mattgeorgephd/PSMFC-mytilus-byssus-pilot/trinity_out/read_partitions/Fb_0/CBin_30/c3083.trinity.reads.fa.out" --CPU 1 --max_memory 1G --run_as_paired --seqType fa --trinity_complete --full_cleanup   failed with ret: 65280, going to retry.
```

**Comment by mattgeorgephd** [comment]
I was able to get `Trinity_gene_splice_modeler.py` to be called after activating conda in the terminal. Will try and rerun after activating in code chunk.

```
eval "$(/opt/anaconda/anaconda3/bin/conda shell.bash hook)"
conda activate

/home/shared/trinityrnaseq-v2.12.0/Analysis/SuperTranscripts/Trinity_gene_splice_modeler.py
```

**Comment by kubu4** [comment]
You'll want to have an Anaconda environment active before running Trinity. That will give you "access" to Python3.

On a side note, I'd use more than two FastQ files to perform a transcriptome assembly.

I'd recommend downloading all (yes, literally _all_) of the RNAseq from NCBI:

![image](https://user-images.githubusercontent.com/4514104/184253126-902d8b86-fd5d-4455-ae05-67166660681f.png)


Here's how to do so using the accession list format posted in the screenshot above:

1. Use sratoolkit to download SRA files from accession list (my example here is on Mox):
 ```shell
/gscratch/srlab/programs/sratoolkit.2.11.3-centos_linux64/bin/prefetch \
--option-file /gscratch/srlab/sam/data/S_namaycush/RNAseq/SraAccList-PRJNA316738.txt
```

2. Convert SRA files to FastQ

```shell
for file in *.sra; do /gscratch/srlab/programs/sratoolkit.2.11.3-centos_linux64/bin/fasterq-dump "${file}"; done
```

Then, to pop them all into Trinity, you can either concatenate all of the `*R1` files and concatenate all of the `*R2` files, or you can provide Trinity with a comma-separated list of the `*R1` FastQs and a comma separated list of the `*R2` FastQs. The latter approach will be faster, as you won't have to wait for the machine to concatenate all of them. If you want to do the latter approach, you can create lists of the files and supply them to Trinity something like this (you'll have to modify FastQ filename patterns, etc):

```shell
# Create array of fastq R1 files
R1_array=("${reads_dir}"/*R1*.fq.gz)

# Create array of fastq R2 files
R2_array=("${reads_dir}"/*R2*.fq.gz)

# Create comma-separated lists of FastQ reads
R1_list=$(echo "${R1_array[@]}" | tr " " ",")
R2_list=$(echo "${R2_array[@]}" | tr " " ",")

# Run Trinity
## Running as "stranded" (--SS_lib_type)
${trinity_dir}/Trinity \
--seqType fq \
--SS_lib_type RF \
--max_memory ${max_mem} \
--CPU ${threads} \
--left "${R1_list}" \
--right "${R2_list}"

```

**Comment by kubu4** [comment]
To make that SRA search simpler (and get some additional records), enter this into the SRA search:

`txid6551[Organism]`

A little bit easier to type, since I didn't include text from the screenshot above (sorry about that!).

**Comment by mattgeorgephd** [comment]
Nice! Thanks for the tip on downloading all the SRAs - Steven had suggested that but I was still having trouble getting it to run with one. If I run all 47 will that take days!?

**Comment by kubu4** [comment]
It will take a long time, yes. Possibly days. That's certainly not unusual.

**Comment by kubu4** [comment]
Also, I neglected to add this part in my Trinity code above. Add this after you populate the arrays in order to have a record of the input files used, as well as the corresponding MD5 checksums (having the record of input files is really the important part):

```shell
# Create list of fastq files used in analysis
## Uses parameter substitution to strip leading path from filename
for fastq in "${!R1_array[@]}"
do
  {
    md5sum "${R1_array[${fastq}]}"
    md5sum "${R2_array[${fastq}]}"
  } >> input_fastqs.md5
done
```
