### ISSUE TITLE
Stacks version

### ISSUE THREAD

**Issue by magobu** [RobertsLab/resources#1507]
Just checking if the program Stacks is loaded in the cluster and if it is a higher version than 2.5
Thanks!

**Comment by kubu4** [comment]
All of installed programs are located here:

`/gscratch/srlab/programs`

Looks like we have Stacks v2.4.1

**Comment by magobu** [comment]
Should I upload the newer version? If so, could you give me some guidance on how to do this?
Thanks!

**Comment by kubu4** [comment]
Insatalled newest version of Stacks here:

`/gscratch/srlab/programs/stacks-2.62`

**Comment by magobu** [comment]
Thanks very much, Sam!

Marta Gómez-Buckley
PhD Candidate
Fish Systematics and Biodiversity Lab
School of Aquatic and Fishery Sciences
University of Washington
