### ISSUE TITLE
Mussel RNAseq library

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1508]
Consider getting corresponding RNAseq library for tag-seq

**Comment by mattgeorgephd** [comment]
Attempting _de novo assembly_ w/ trinity using 48 available SRA for _M. trossulus_ on ncbi.

@kubu4 Joined file is 300GB! Running on Raven stalled, switching to mox. Could you look over my [.sh script](https://gannet.fish.washington.edu/panopea/PSMFC-mytilus-byssus-pilot/202208_PSMFC-mytilus-byssus-pilot_trinity.sh) before I run.

**Comment by kubu4** [comment]
> Joined file is 300GB!

There are definitely going to be some very large files generated during the process, so this isn't much of a concern. Although it's really of no consequence since the job didn't complete, out of curiosity, which file?

> Running on Raven stalled,

What do you mean by this? Any error messages? If yes, please share them.

Basically, just trying to troubleshoot now, as you'd likely encounter the same issues on Mox as Raven.

**Comment by mattgeorgephd** [comment]
Run on Raven got stuck at `-reading Kmer occurrences...` during inchworm. No error, just stuck for 7 days. Looking through github issues for Trinity, only reference I could find to anything like this was someone else also running a large assembly with 40+ files. Suggestion from admin was run on a bigger computer...

**Comment by kubu4** [comment]
> just stuck for 7 days

Why do you think it was "stuck"? Was the job not using any CPUs/memory any more? Were files no longer being updated?

**Comment by mattgeorgephd** [comment]
Yeah, files were not being updated. Memory usage was high, but stable. Looking the [output of your run](https://gannet.fish.washington.edu/Atumefaciens/20210317_cbai_trinity_RNAseq_transcriptome-v4.0/slurm-1743615.out) I think this step should be fairly quick...

**Comment by sr320** [comment]
@mattgeorgephd I recommend getting it running on mox (if not already running).

**Comment by kubu4** [comment]
Alrighty, I've made some changes to your script. Hopefully it'll run.

Some of the changes made:

- changed account/partition to `srlab`

- set max memory to 100G

- fixed array naming (both arrays were named `left_array`

I've attached it here. I had to rename it using `.txt` in order for GitHub to allow me to upload it here. Feel free to change it back - it won't affect anything.
[202208_PSMFC-mytilus-byssus-pilot_trinity.txt](https://github.com/RobertsLab/resources/files/9397574/202208_PSMFC-mytilus-byssus-pilot_trinity.txt)

**Comment by mattgeorgephd** [comment]
@kubu4 Thanks for your help!

**Comment by kubu4** [comment]
Also, for kicks, I'd re-run your Trinity script that you used on Raven (albeit, change max memory to 100GB) and just let it run. Trinity will continue where it left off. Might as well just let it do it's thing until it finishes (or, we restart the computer some day). Couldn't hurt.

**Comment by mattgeorgephd** [comment]
Hey @kubu4. I'm getting the following error on mox:

``
Trinity version: Trinity-v2.12.0
-ERROR: couldn't run the network check to confirm latest Trinity software version.

which: no samtools in (/gscratch/srlab/programs/trinityrnaseq-v2.12.0/trinity-plugins/BIN:/gscratch/sw/intel-201703/compilers_and_libraries_2017.2.174/linux/mpi/intel64/bin:/gscratch/sw/intel-201703/compilers_and_libraries_2017.2.174/li$Error, cannot find samtools. Please be sure samtools is installed and included in your PATH setting.
``

In my sbatch script, I has specified the samtools directory as:

```
# Paths to programs
trinity_dir="/gscratch/srlab/programs/trinityrnaseq-v2.12.0"
samtools="/gscratch/srlab/programs/samtools-1.10/samtools"
```

and set up the program array as so:

```
# Programs array
declare -A programs_array
programs_array=(
[samtools_faidx]="${samtools} faidx" \
[trinity]="${trinity_dir}/Trinity" \
[trinity_stats]="${trinity_dir}/util/TrinityStats.pl" \
[trinity_gene_trans_map]="${trinity_dir}/util/support_scripts/get_Trinity_gene_to_trans_map.pl" \
[trinity_fasta_seq_length]="${trinity_dir}/util/misc/fasta_seq_length.pl"
)
```

The sbatch script is located in /gscratch/srlab/mngeorge/sbatch_scripts/202208_PSMFC-mytilus-byssus-pilot_trinity.sh

**Comment by kubu4** [comment]
The key to the error message is this part:

> `Please be sure samtools is installed and included in your PATH setting.`

You have to have samtools in the system $PATH for Trinity to use it.

This is sort of "behind the scenes" thingy, if you will.

If you want, you can add the following to your `~/.bashrc` file:

```
# Custom PATH

export PATH="/usr/lusers/samwhite/bin:\
$PATH:\
/gscratch/srlab/programs/bowtie2-2.3.5.1-linux-x86_64:\
/gscratch/srlab/programs/Augustus-3.3.2/bin:\
/gscratch/srlab/programs/FastQC:\
/gscratch/srlab/programs/jellyfish-2.3.0/bin:\
/gscratch/srlab/programs/salmon-1.1.0_linux_x86_64/bin:\
/gscratch/srlab/programs/samtools-1.10:\
/gscratch/srlab/programs/pcre2-10.37:\
/gscratch/srlab/programs/R-4.1.1/bin:\
/gscratch/srlab/programs/tree-1.8.0:\
/gscratch/srlab/programs/graphviz-2.40.1/bin"
```

This will add `samtools` to your system $PATH (and, some other stuff which Trinity might need, like `salmon` and `jellyfish`).

**Comment by kubu4** [comment]
Oh! In the example above, be sure to change 

`/usr/lusers/samwhite/bin` to `/usr/lusers/mngeorge/bin`

**Comment by mattgeorgephd** [comment]
Thanks! This worked after adding the paths to the ~/.bash_profile.

After running overnight I got this error during jellyfish:

```
CMD finished (0 seconds)
CMD: touch right.fa.K25.stats.ok
CMD finished (0 seconds)
-sorting each stats file by read name.
CMD: head -n1 left.fa.K25.stats > left.fa.K25.stats.sort && tail -n +2 left.fa.K25.stats | /usr/bin/sort --parallel=40 -k1,1 -T . -S 50G >> left.fa.K25.stats.sort
CMD: head -n1 right.fa.K25.stats > right.fa.K25.stats.sort && tail -n +2 right.fa.K25.stats | /usr/bin/sort --parallel=40 -k1,1 -T . -S 50G >> right.fa.K25.stats.sort
/usr/bin/sort: write failed: ./sortfQcKBT: Disk quota exceeded
Thread 5 terminated abnormally: Error, cmd: head -n1 left.fa.K25.stats > left.fa.K25.stats.sort && tail -n +2 left.fa.K25.stats | /usr/bin/sort --parallel=40 -k1,1 -T . -S 50G >> left.fa.K25.stats.sort died with ret 512 at /gscratch/srl$Error, thread exited with error Error, cmd: head -n1 left.fa.K25.stats > left.fa.K25.stats.sort && tail -n +2 left.fa.K25.stats | /usr/bin/sort --parallel=40 -k1,1 -T . -S 50G >> left.fa.K25.stats.sort died with ret 512 at /gscratch/srl$
CMD finished (543 seconds)
Error, 1 threads errored out at /gscratch/srlab/programs/trinityrnaseq-v2.12.0/util/insilico_read_normalization.pl line 997.
Error, cmd: /gscratch/srlab/programs/trinityrnaseq-v2.12.0/util/insilico_read_normalization.pl --seqType fq --JM 100G  --max_cov 200 --min_cov 1 --CPU 40 --output /gscratch/srlab/mngeorge/outputs/202208_PSMFC-mytilus-byssus-pilot_trinit$        main::process_cmd('/gscratch/srlab/programs/trinityrnaseq-v2.12.0/util/insilico_...') called at /gscratch/srlab/programs/trinityrnaseq-v2.12.0/Trinity line 3422
        main::normalize('/gscratch/srlab/mngeorge/outputs/202208_PSMFC-mytilus-byssus-...', 200, 'ARRAY(0x1adaa08)', 'ARRAY(0x1adaa38)') called at /gscratch/srlab/programs/trinityrnaseq-v2.12.0/Trinity line 3362
        main::run_normalization(200, 'ARRAY(0x1adaa08)', 'ARRAY(0x1adaa38)') called at /gscratch/srlab/programs/trinityrnaseq-v2.12.0/Trinity line 1384
```

To big? The slurm out is at /gscratch/srlab/mngeorge/outputs/202208_PSMFC-mytilus-byssus-pilot_trinity/slurm-3896268.out

**Comment by kubu4** [comment]
Error is due to running out of disk space.

Move job over to `/gscratch/scrubbed`.

Create a directory for yourself there and then any subdirectories you might want. This drive has virtually unlimited space. However, data gets deleted every 31 days, so don't leave anything in there that you haven't backed up to Gannet
