### ISSUE TITLE
Obtain cost for Metagenomics Library Sequencing

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#151]
We want to generate a metagenomics library (filter paper from larval experiment). 
Determine what costs would be (from Nickerson Core) to construct library and sequence.

**Comment by kubu4** [comment]
A single samples and library? Single/paired-end? Sequencing length? Desired number of reads?

**Comment by sr320** [comment]
Single library- a lane
See what cost are for different read options- and any associated time frames

**Comment by kubu4** [comment]
Finally heard back from them!

>Hi Sam,

>Does your lab have the capability to prepare your own sequencing libraries? I ask because it is much more cost effective to just have us perform sequencing for small projects like this rather than have use do the library prep. Additionally, the wait time for library prep is currently ~3 months, but we can turn around sequencing in 1 - 4 weeks depending on which sequencer you would like us to use.

>For library prep there are two cost components: 1) Project initiation and sample QC is $700 for 1-48 samples and 2) Library prep itself is $63 per sample. 

>Our standard high throughput sequencing run is 2x75bp, and this is the only read length that we offer by the lane. This is run on the HiSeq 4000 and the cost per lane is $2515. 

>If you would like a different read length, the most cost effective options for a single sample project would be to use the NextSeq or MiSeq sequencers. The best choice depends on how many reads you need. 

>MiSeq
50 cycle: $954
150 cycle: $1332
300 cycle: $1924
500 cycle: $2647
600 cycle: $3300

>NextSeq
High Output 75 cycle: $1678
High Output 150 cycle: $3236
High Output 300 cycle: $5359
Mid Output 150 cycle: $1513
Mid Output 300 cycle: $2604

**Comment by sr320** [comment]
So we need to do the library prep, unless there is another core you were reaching out to?

**Comment by kubu4** [comment]
I'll call when the other place opens (9AM) and see if I can get ahold of anyone.

**Comment by kubu4** [comment]
Eh, I left a message. Not expecting any sort of response at this point.

**Comment by sr320** [comment]
can you ID what library kit we need to purchase and cost?

**Comment by kubu4** [comment]
What type of sequencing do you want to do? MiSeq or NextSeq?

**Comment by sr320** [comment]
NextSeq - I presume this kits are different?

**Comment by kubu4** [comment]
Yes.

**Comment by kubu4** [comment]
We also need to decide (kits are sold based on the following criteria):

- Mid or High output
- Cycle numbers

**Comment by kubu4** [comment]
NextSeq 500/550 High Output v2 kit (75 cycles) 
FC-404-2005
$1,450.00 


NextSeq 500/550 High Output v2 kit (150 cycles) 
FC-404-2002
$2,780.00 


NextSeq 500/550 High Output v2 kit (300 cycles) 
FC-404-2004
$4,450.00 


NextSeq 500/550 Mid Output v2 kit (150 cycles) 
FC-404-2001
$1,060.00 


NextSeq 500/550 Mid Output v2 kit (300 cycles) 
FC-404-2003
$1,700.00 


TG NextSeq 500/550 High Output Kit v2 (75 cycles)
TG-160-2005
$1,668.00 


TG NextSeq 500/550 High Output Kit v2 (150 cycles)
TG-160-2002
$3,197.00 


TG NextSeq 500/550 High Output Kit v2 (300 cycles)
TG-160-2004
$5,118.00

**Comment by kubu4** [comment]
Doh! Ignore post above!!!

**Comment by kubu4** [comment]
Library prep kit:

TruSeq DNA PCR-Free Low Throughput Library Prep Kit (24 samples) 
20015962
$630.00

**Comment by kubu4** [comment]
Actually, we might need this:

TruSeq Nano DNA Low Throughput Library Prep Kit (24 samples) 
20015964
$630.00 

This kit only  requires 100ng - the TruSeq kit above requires 1ug.

If we can't get 100ng, we'll need to use the Nextera Kit - which is only for running on the MiSeq.
