### ISSUE TITLE
Globus Connect Personal

### ISSUE THREAD

**Issue by magobu** [RobertsLab/resources#1510]
I noticed that Globus Connect Personal is loaded in the srlab programs folder. Would it be possible to get guidance on how to do the transfer of my files directly grom globus to the cluster, bypassing having to download them to my local Mac and then to the cluster? It would be so much faster and cleaner if I could do it that way. The version of GCP I am using is 3.1.6 Build 655

**Comment by kubu4** [comment]
Have you used Globus Connect before? If yes, then what I'm going to type will make some sense. If not, then you'll need to play around with it to understand it a bit first (can't really help much with that part). Additionally, I haven't used it in quite some time, so the "directions" below are just a rough guess on how to do it.

1. Set up a directory where you'll store your data on Mox.
2. Change to your new directory on Mox.
3. Start globusconnectpersonal on Mox: `/gscratch/srlab/programs/globusconnectpersonal-3.1.4/globusconnectpersonal`
4. Start Globus Connect Personal on your computer.
5. Try to find way to add that Mox directory as an endpoint in your Globus Connect Personal account.
6. Transfer files from initial Globus endpoint to newly created Mox endpoint.

I'll attempt to mess around with a bit in hopes of providing more specific guidance, but I have some other tasks I need to prioritize, so I might not get around to this before next week.

**Comment by kubu4** [comment]
Read through this page: https://docs.globus.org/how-to/globus-connect-personal-linux/

Specifically, you'll want to pay attention to the sections describing how to work _without_ the graphical user interface (GUI)!

Also, you'll need to create a config file which specifies which directory on Mox you want to set up as an endpoint and provide the correct permissions for that endpoint. There's a section detailing this on that page as well.

**Comment by magobu** [comment]
Thanks Sam. I'll research this with the info you gave me. I have used
globus connect and I can transfer files between globus to other computers,
but the part that requires creating a 'collection' and finding the 'path'
to it (point 5 on your list) for mox has been elusive. The slack page uw
has for the cluster help was not able to help me with this.
Sorry to ask so many questions!!

Marta Gómez-Buckley
PhD Candidate
Fish Systematics and Biodiversity Lab
School of Aquatic and Fishery Sciences
University of Washington

**Comment by kubu4** [comment]
> Sorry to ask so many questions!!

No problem! Happy to help when I'm able!

I couldn't resist, so I did some more playing around. Here are more specific instructions:

1. Log into Mox.
2. Activate anaconda (this might fail, let me know if it does and don't bother going to the next step): `conda deactivate`
3. Setup Globus collection: `/gscratch/srlab/programs/globusconnectpersonal-3.1.4/globusconnectpersonal -setup --no-gui`
4. Follow the instructions (copy/paste URL into browser, get code from webpage, enter code in Mox terminal, provide name for collection).
5. Add desired Mox directory to config file and set permissions. Here's an example from mine:

```
$cat ~/.globusonline/lta/config-paths

~/,0,1
/gscratch/scrubbed/samwhite/,0,1
```

The config file does two things:

-  `~/,0,1`: Makes your home directory readable/writeable by Globus.
-  `/gscratch/scrubbed/samwhite/,0,1`: Makes my directory on `/gscratch/scrubbed/` readable/writeable by Globus.

6. Start Globus Connect Personal: ``/gscratch/srlab/programs/globusconnectpersonal-3.1.4/globusconnectpersonal -start`. Nothing will happen after you hit enter. The cursor will simply flash - this is good.
7. Login to your Globus Connect Personal account via a web browser.
8. Click on Collections and you should now see your collection (name provided in Step 4), and it should have a green stack of papers(?) next to it; the green indicates that the connection is activate.
9. Click on the collection name.
10. Click on "Open in File Manager" (on the right side of the screen).
11. Navigate to the directory you setup in Step 5. NOTE: You'll have to navigate up a directory out of your home directory in order to get to the `/gscratch` partition.
12. Transfer data from other Globus Endpoint to Mox!

**Comment by magobu** [comment]
Great! but I'm stuck on step  2 :(  

To activate anaconda I should be in /gscratch/srlab/programs/ correct? I'm getting this message

[lapita@mox2 programs]$ conda activate
-bash: conda: command not found
[lapita@mox2 programs]$ 

 I'm missing the right command for this step??

**Comment by kubu4** [comment]
Figured that might be an issue. Run the following and let me know what it says:

`/gscratch/srlab/programs/anaconda3/condabin/conda activate`

**Comment by magobu** [comment]
I get this 👎 

[lapita@mox2 martagb]$ /gscratch/srlab/programs/anaconda3/condabin/conda activate
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:

  - bash

  - fish

  - tcsh

  - xonsh

  - zsh

  - powershell

See 'conda init --help' for more information and options.
IMPORTANT: You may need to close and restart your shell after running 'conda init'.





[lapita@mox2 martagb]$

**Comment by kubu4** [comment]
Okay, thanks.

Run this and follow any prompts (probably enter `y` or `yes` to any questions that you're prompted with):

` /gscratch/srlab/programs/anaconda3/condabin/conda init bash`

Please let me know what happens.

**Comment by magobu** [comment]
Here: (Am I in the right folder to do this?)

[lapita@mox2 martagb]$ md5sum GBS-Plate-2_S196_L004_R1_001.fastq.gz

5912f606b09b79e70d53a1d1e3f4dad2  GBS-Plate-2_S196_L004_R1_001.fastq.gz

[lapita@mox2 martagb]$ /gscratch/srlab/programs/anaconda3/condabin/conda init bash

no change     /gscratch/srlab/programs/anaconda3/condabin/conda

no change     /gscratch/srlab/programs/anaconda3/bin/conda

no change     /gscratch/srlab/programs/anaconda3/bin/conda-env

no change     /gscratch/srlab/programs/anaconda3/bin/activate

no change     /gscratch/srlab/programs/anaconda3/bin/deactivate

no change     /gscratch/srlab/programs/anaconda3/etc/profile.d/conda.sh

no change     /gscratch/srlab/programs/anaconda3/etc/fish/conf.d/conda.fish

no change     /gscratch/srlab/programs/anaconda3/shell/condabin/Conda.psm1

no change     /gscratch/srlab/programs/anaconda3/shell/condabin/conda-hook.ps1

no change     /gscratch/srlab/programs/anaconda3/lib/python3.7/site-packages/xontrib/conda.xsh

no change     /gscratch/srlab/programs/anaconda3/etc/profile.d/conda.csh

modified      /usr/lusers/lapita/.bashrc



==> For changes to take effect, close and re-open your current shell. <==



[lapita@mox2 martagb]$

**Comment by kubu4** [comment]
Interesting. Okay, close your terminal window and then re-connect to Mox. Then run `conda activate` and let me know what it says.

**Comment by magobu** [comment]
Okay, I did that and it returns the prompt

(base) [lapita@mox2 ~]$ conda activate
(base) [lapita@mox2 ~]$

**Comment by kubu4** [comment]
Ah! Great! You're all set!

This part `(base)` means conda is already activated (which it will be by default now - if you need/want to get out of conda, run `conda deactivate` and you'll be back to "normal").

So, now you should be able to continue at Step 3 above!

**Comment by magobu** [comment]
Wow! Thanks for all your help! I'll let you know if it works for the rest of the steps!

**Comment by magobu** [comment]
I'm on step 5 and I need some clarification. You gave me the example of what it would look in your case ($cat ~/.globusonline/lta/config-paths) I'm not sure what mine should be. The end goal for me would be to transfer the files to gscratch/srlab/martagb

**Comment by kubu4** [comment]
Then your `config-paths` file should look like this:

```
~/,0,1
/gscratch/srlab/martagb/,0,1
```

**Comment by magobu** [comment]
So I should  write the first line (~/,0,1) first and then the one below? I'm trying one line first and both at the same time, but I always get this below, so is it a matter of being in the wrong directory?

(base) [lapita@mox1 ~]$ ~/,0,1
-bash: /usr/lusers/lapita/,0,1: No such file or directory
(base) [lapita@mox1 ~]$

**Comment by kubu4** [comment]
You need to enter that info into the `config-paths` file.

You can do that like this:

```bash
echo "~/,0,1" >> ~/.globusonline/lta/config-paths
echo "/gscratch/srlab/martagb/,0,1" >> ~/.globusonline/lta/config-paths


/
```

**Comment by magobu** [comment]
That worked!! 💯  Thanks Sam :)
