### ISSUE TITLE
Run Ballgown on Lake Trout samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1512]
as follow up to https://github.com/RobertsLab/resources/issues/1505

interested in both differentially expressed isoforms and genes.

**Comment by kubu4** [comment]
Is there a GitHub repo for this project? I think it might make it easier for us to find/track/use subsequent data.

**Comment by sr320** [comment]
please use https://github.com/RobertsLab/project-lake-trout

**Comment by kubu4** [comment]
Heads up on this.

When p-value _and_ q-value thresholds are set (0.05 for both), there are no differentially expressed genes (DEGs) nor differentially expressed transcripts (DETs) when comparing lean vs. siscowet.

I've done the same analysis, but eliminated the q-value threshold (i.e. just filtering based on p-values <= 0.05) and then there are DEGs and DETs.

I'm in the process of doing the DEG and DET analyses with different treatment conditions (e.g. parasitized vs. non-parasitized, parasitized vs. non-parasitized within subspecies) using both p-value and q-value thresholds. Will report back when I have those.

Analyses files have been uploaded to the repo, but I haven't updated the READMEs yet to explain files.

Anyway, just wanted to pass along these initial results so you could consider implications and/or how else you'd like to proceed.

I still plan on doing the same transcript counts/coefficients of variation stuff we did with CEABIGR, as that will likely be useful, regardless of DEG/DET results.

**Comment by sr320** [comment]
Thanks - lets put a hold on this for now, after documenting what has been done to date. Might pivot to target genes

**Comment by kubu4** [comment]
I've updated all the README files in the repo to describe all files in the repo.

**Comment by sr320** [comment]
@kubu4 can you compare non-parasitized leans to non-parasitised siscowets? Maybe you did already?
