### ISSUE TITLE
Determine isoform expression change / predominance

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1513]
for CEABiGR - we need a metric that describes a delta isoform expression. 

For example for gene X is isoform 3 predominant and under certain conditions does isoform 2 become more predominant elsewhere?

To start, I think this should be independent of treatment. 

Q 1 
@kubu4 Do we have expression data of isoforms attached to genes?

Once we do, I could see obtaining the mean coefficient of variation of isoforms on a per gene basis?
Maybe we have this?

at a very simple level we could identify which given isoform is expressed at the highest level for a gene in each library.
and if we needed a quantitive metric / threshold we could determine the percent difference from mean.

Other ideas welcome.

**Comment by kubu4** [comment]
>  Do we have expression data of isoforms attached to genes?

Yep! (sorry for delay!!).

This file has everything:

https://raw.githubusercontent.com/epigeneticstoocean/2018_L18-adult-methylation/main/data/whole_tx_table.csv

> Once we do, I could see obtaining the mean coefficient of variation of isoforms on a per gene basis?
> Maybe we have this?

Close. We have files like these (transcript coefficients of variation by treatment, sex, etc):

https://raw.githubusercontent.com/epigeneticstoocean/2018_L18-adult-methylation/main/analyses/transcripts_treatment_fpkm_CoV_df.csv

The `t_id` column (transcript ID) could (easily?) be used to merge with the corresponding genes in `whole_tx_table.csv` linked above,
