### ISSUE TITLE
get 2015 Pycno transcriptome to owl/halfshell/genomic-databank

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1515]
I think this is the 2015 _P. helianthoides_ transcriptome:     
https://github.com/sr320/eimd-sswd/blob/master/data/Phel_transcriptome.fasta 

What's best way to get it to owl.fish.washington.edu/halfhshell/genomic-databank? 

EDIT: it's actually from 2014.

**Comment by sr320** [comment]
```
ssh sr320@owl.fish.washington.edu
cd /volume1/web/halfshell/genomic-databank
curl -O https://raw.githubusercontent.com/sr320/eimd-sswd/master/data/Phel_transcriptome.fasta
```

and to confirm it is there...
```
head Phel*
```

(Note I have moved the file to `genomic-databank` directory.

**Comment by grace-ac** [comment]
yay thanks @sr320 !
