### ISSUE TITLE
job submission issue

### ISSUE THREAD

**Issue by magobu** [RobertsLab/resources#1516]
HI, I have an error message when I try to submit a job:

```
ERROR: Unable to locate a modulefile for 'gscratch/srlab/programs/stacks-2.62'
/var/spool/slurm/d/job3603507/slurm_script: line 54: process_radtags: command not found
```

This is the script for the job submission:

```
 GNU nano 2.3.1                                               File: radtags1                                                                                                     

#!/bin/bash

## Job Name

#SBATCH --job-name=radtags1

## Allocation Definition

## The account and partition options should be the same except in a few cases (e.g. ckpt queue and genpool queue).

#SBATCH --account=srlab
#SBATCH --partition=srlab

## Resources

## Total number of Nodes

#SBATCH --nodes=1

## Number of cores per node

#SBATCH --ntasks-per-node=28

## Walltime (3 hours). Do not specify a walltime substantially more than your job needs.

#SBATCH --time=3:00:00

## Memory per node. It is important to specify the memory since the default memory is very small.

## For mox, --mem may be more than 100G depending on the memory of your nodes.

## For ikt, --mem may be 58G or more depending on the memory of your nodes.

## See above section on "Specifying memory" for choices for --mem.

#SBATCH --mem=100G

## Specify the working directory for this job

#SBATCH --chdir=/gscratch/srlab/martagb/jobs

##turn on e-mail notification

#SBATCH --mail-type=ALL

#SBATCH --mail-user=lapita@uw.edu

## export all your environment variables to the batch job session

#SBATCH --export=all

module load gscratch/srlab/programs/stacks-2.62

process_radtags -P -p ./raw-data1/  -b ./barcodes/barcode_plate1.txt -o ./samples1/ -c -q --index_index --renz_1 Nsil --renz_2 Mspl
```
This is my first job I submit, so any help is appreciated! I tried the Slack page for the UW cluster group and they said: "Since you're using a module I would confer with the module's author on that. Group created modules are only supported by the teams that create them."
THANKS :)

**Comment by sr320** [comment]
What is the contents of your slurm output file... 

should be in `/gscratch/srlab/martagb/jobs`


(ALSO it would be good to working in `/gscratch/scrubbed/`)

**Comment by magobu** [comment]
The content of the slurm output file is: 

GNU nano 2.3.1                          File: slurm-3603507.out                                                            

ERROR: Unable to locate a modulefile for 'gscratch/srlab/programs/stacks-2.62'
/var/spool/slurm/d/job3603507/slurm_script: line 54: process_radtags: command not found

**Comment by sr320** [comment]
I suggest using the full path for `process_radtags`

**Comment by magobu** [comment]
Sorry, I don't undertand what you mean. Where would I enter the full path for the command process_radtags and which would that be?

**Comment by kubu4** [comment]
> ERROR: Unable to locate a modulefile for 'gscratch/srlab/programs/stacks-2.62'

We do not have a Stacks module. So, you need to remove the following from your SBATCH script:

`module load gscratch/srlab/programs/stacks-2.62`

And then, as @sr320 pointed out, you'll need to use the full path to the program you want to run. E.g. to run `process_radtags`, you need to do the following:

`/gscratch/srlab/programs/stacks-2.62/process_radtags`

**Comment by kubu4** [comment]
HOWEVER, what I posted above will actually lead to another error (I just checked it out), so don't bother going forward just yet. I'll post an additional command you'll need to have in your script before you proceed.

BRB...

**Comment by sr320** [comment]
@magobu it might be good to talk to folks or alumni in Hauser / Knaish lab that have used stacks on mox.

**Comment by magobu** [comment]
Okay, that makes sense @kubu4 . Thanks!
Now for doing this job in  /gscratch/scrubbed/ , that means that I have to have all my folders/files for the job moved or copied to the scrubbed folder?

@sr320 thanks for the suggestion. I'll check with them!!

**Comment by kubu4** [comment]
In your script, replace your `module load` line with this:

`module load gcc/10.1.0`

Then, you'll have your `process_radtags` command (NOTE: I've reformatted for easier reading. You can copy/paste this into your script and it will still run properly).

```shell
/gscratch/srlab/programs/stacks-2.62/process_radtags \
-P \
-p ./raw-data1/ \
-b ./barcodes/barcode_plate1.txt \
-o ./samples1/ \
-c \
-q \
--index_index \
--renz_1 Nsil \
--renz_2 Mspl
```

**Comment by magobu** [comment]
Alright! I submitted with those modifications and seems to be runing! I didn't get a "fail" submission email right away!

Sorry, I was so excited that I forgot to do it the scrubbed way!

**Comment by magobu** [comment]
AAAGGGG! I got another fail!!!
But this time, the error message is about some unrecognized restriction enzyme so I'll try and figure this out with Hauser's lab. 
Thanks for being so patient with me!!

**Comment by sr320** [comment]
also check out https://marineomics.github.io/RADseq.html

**Comment by kubu4** [comment]
Your restriction enzyme names have typos in them.

They should be `NsiI` and `MspI`.

The way you have them written in your script is using numbers (`1`) instead of Roman numerals (`I`).

**Comment by kubu4** [comment]
From the `process_radtags` help menu:

```
  Restriction enzyme options:
    -e [enz], --renz-1 [enz]: provide the restriction enzyme used (cut site occurs on single-end read)
    --renz-2 [enz]: if a double digest was used, provide the second restriction enzyme used (cut site occurs on the paired-end read).
    Currently supported enzymes include:
      'aciI', 'ageI', 'aluI', 'apaLI', 'apeKI', 'apoI', 'aseI', 'bamHI', 
      'bbvCI', 'bfaI', 'bfuCI', 'bgIII', 'bsaHI', 'bspDI', 'bstYI', 'btgI', 
      'cac8I', 'claI', 'csp6I', 'ddeI', 'dpnII', 'eaeI', 'ecoRI', 'ecoRV', 
      'ecoT22I', 'haeIII', 'hhaI', 'hinP1I', 'hindIII', 'hpaII', 'hpyCH4IV', 'kpnI', 
      'mluCI', 'mseI', 'mslI', 'mspI', 'ncoI', 'ndeI', 'ngoMIV', 'nheI', 
      'nlaIII', 'notI', 'nsiI', 'nspI', 'pacI', 'pspXI', 'pstI', 'pstIshi', 
      'rsaI', 'sacI', 'sau3AI', 'sbfI', 'sexAI', 'sgrAI', 'speI', 'sphI', 
      'taqI', 'xbaI', or 'xhoI'
```

**Comment by magobu** [comment]
Yes, I'll have to check with the Stacks program developers what the solution would be if my enzymes are not listed.

**Comment by magobu** [comment]
> also check out https://marineomics.github.io/RADseq.html

Great, thanks!

**Comment by kubu4** [comment]
> would be if my enzymes are not listed

Your enzymes are listed... `nsiI` and `mspI`. You need to use this formatting in your script. Your original enzyme name formatting is incorrect.

**Comment by magobu** [comment]
AAAhhhh!! thanks for catching that @kubu4 
Also, can I try this in the non-scrubbed mode, please!

**Comment by kubu4** [comment]
First, make your directories on scrubbed:

`mkdir --parents /gscratch/scrubbed/martagb/jobs/radtags1/samples1`

That will create your folders on `scrubbed`.

Then, I've updated your script to run the job on `scrubbed` and put the output in `/gscratch/scrubbed/martagb/jobs/radtags1/samples1`. Your input files can remain where they are, however, you'll need to provide the full path to their location in the script below. I was able to adjust the location to your barcode plate file, but I didn't know which `raw_data` directory you wanted to use. Your original script referenced a directory called `raw-data1`, but that directory doesn't exist:

```shell
[samwhite@mox2]$ ls /gscratch/srlab/martagb/
barcodes  jobs	raw_data  raw_dataP1  raw_dataP2  samples  samples1
```

I've also updated your `process_radtags` command to use the verbose arguments to make it easier to follow what the options are actually doing. I've also added the `--threads` argument to allow you to use all 28 CPUs on the node. This will allow your job to run much faster. I also updated your restriction enzyme name formatting to match how they're listed in the help menu.



```shell
#!/bin/bash

## Job Name
#SBATCH --job-name=radtags1

## Allocation Definition
## The account and partition options should be the same except in a few cases (e.g. ckpt queue and genpool queue).
#SBATCH --account=srlab
#SBATCH --partition=srlab

## Resources
## Total number of Nodes
#SBATCH --nodes=1

## Walltime (3 hours). Do not specify a walltime substantially more than your job needs.
#SBATCH --time=3:00:00

## Memory per node. It is important to specify the memory since the default memory is very small.
## For mox, --mem may be more than 100G depending on the memory of your nodes.
## For ikt, --mem may be 58G or more depending on the memory of your nodes.
## See above section on "Specifying memory" for choices for --mem.

#SBATCH --mem=200G

## Specify the working directory for this job
#SBATCH --chdir=/gscratch/scrubbed/martagb/jobs/radtags1/samples1

##turn on e-mail notification
#SBATCH --mail-type=ALL
#SBATCH --mail-user=lapita@uw.edu

## export all your environment variables to the batch job session

#SBATCH --export=all

# Load updated GCC compiler needed for Stacks to run properly
module load gcc/10.1.0

# Run Stacks' process_radtags with various options
/gscratch/srlab/programs/stacks-2.62/process_radtags \
--paired \
--in-path <NEED FULL PATH TO DIRECTORY> \
--out-path /gscratch/scrubbed/martagb/jobs/radtags1/samples1 \
--barcodes /gscratch/srlab/martagb/barcodes/barcode_plate1.txt \
--clean \
--quality \
--index_index \
--renz_1 nsiI \
--renz_2 mspI \
--threads 28
```

**Comment by magobu** [comment]
I submited with all the changes and with the correct path and folder name for the raw data folder (raw_dataP1) and when I submitted it it gives me the same error about the not recognizing the enzymes!!
I'm sending a message to the Stacks google group to see what they say. I'm also checking with Anita Way (Hauser's student) to see if she have some tips. Thanks again!

**Comment by kubu4** [comment]
No need to message them yet. Just noticed there's a typo in the enzyme arguments. It should look like this:

```
--renz11 nsiI \
--renz12 mspI \
```

You originally had underscores instead of hyphens.

Make those changes and give it another go.

**Comment by magobu** [comment]
Aha! @kubu4  I realized that I was looking at the wrong slurm output message. The one I got after I did the las run actually has a different error message. Here:
Processing paired-end data.
Using Phred+33 encoding for quality scores.
Unable to open directory '/gscratch/srlab/martagb/raw_data_P1/' for reading.
I believe I should get rid of the last /

Should I. leave the enzyme arguments like they were since they seem to have passed this last run?

**Comment by kubu4** [comment]
> I believe I should get rid of the last /

That's not the problem. You need to fix the path. You don't have a directory called `raw_data_P1`. You need to change the path in your script to:

`/gscratch/srlab/martagb/raw_dataP1/`

---

> Should I. leave the enzyme arguments like they were since they seem to have passed this last run?

I'd change them, that way they match the usage indicated in the documentation.

**Comment by magobu** [comment]
Okay, narrowing it down after fixing typo for raw_dataP1  next error message is on the barcode text file 

Processing paired-end data.
Using Phred+33 encoding for quality scores.
Found 2 paired input file(s).
Searching for single and paired-end, indexed barcodes.
Error opening barcode file '/gscratch/srlab/martagb/barcodes/barcode_plate1.txt/'

**Comment by kubu4** [comment]
> Error opening barcode file '/gscratch/srlab/martagb/barcodes/barcode_plate1.txt/'

My bad. Change path to this (there was an errant slash at the end of that, which shouldn't be there):

`/gscratch/srlab/martagb/barcodes/barcode_plate1.txt`

**Comment by magobu** [comment]
:) Next error

Processing paired-end data.
Using Phred+33 encoding for quality scores.
Found 2 paired input file(s).
Searching for single and paired-end, indexed barcodes.
Invalid barcode on line 1: 'Ancor_00000AC2_PNG'

I checked the text file and had that odd first line, still after I removed it it gives me similar error mesage with the actual barcode on first line Processing paired-end data.
Using Phred+33 encoding for quality scores.
Found 2 paired input file(s).
Searching for single and paired-end, indexed barcodes.
Invalid barcode on line 1: 'shima_000ESH24_IND'

The actual first line is 'TAATTG	shima_000ESH24_IND'

I'm checking with Anita to see what's wrong with that barcode text file!! It may be some spacing that is wrong

**Comment by kubu4** [comment]
Looking at your data, it looks like you have combinatorial barcodes. This means your barcodes file is not formatted correctly.

See the Stacks manual for formatting requirements and how to identify combinatorial barcodes.

https://catchenlab.life.illinois.edu/stacks/manual/#barcode

To see what type of barcoding you have, you can examine your FastQ files like so:

```shell
[samwhite@mox2 raw_dataP1]$ zcat GBS-Plate-1_S195_L004_R1_001.fastq.gz | head
@A00589:435:HVTMWDSX3:4:1101:1145:1000 1:N:0:TAGCGTCCAC+TTGCTCACCA
NCCTAATGCATTTGATCACGATTCGTTTTTTATCGTCAGCCCTAATTAAACAGGACAAAAGTTTAAACCAAGGTCAAATAAGGTCTCAATCAGGGCTAAATCTACTTTAAATCATCAACCTGGACTGAAATCTGGCTTAAACCTTGCCAAC
+
#FF::FFFFFFFFFFFFFFFFFFF:F,FFFFF:FFFFFF:FF:FFFFFFFF:,FFFFFFF,FFFFFFFFFF:F:F:FFFFF:FF:FFF,FFFF::FFF:FF,:FF,FFFFFFFFF::FF:FFFF,FFFFFFFFFFFF:FFFFF,:FFFFFF
@A00589:435:HVTMWDSX3:4:1101:1796:1000 1:N:0:TAGCGTCCAC+TTGCTCACAA
NCCTGCTTGCATGCTGTCCACTCGCGTGGACATCTGGAAAAGCACAATTTCCTCCCAATCTAAAATCAATACTTGAAAATTTTCACCTCAACAGTGATCATTAGATGTTACTTGATGCCAAAATATTTTTTTTATCTGCAGGAGTCTCCTC
+
#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFF:FFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,,FFFFFFFFFFFF:,FFFFFFFFFFF:FFF
@A00589:435:HVTMWDSX3:4:1101:2428:1000 1:N:0:TAGCGTCCAC+TTGCTCACCA
NGTAGCAACATGCATAAAATTCAAAAAAATGCAACAAAAAGACAAGGAAACCCACAAACACATAAAGAATGAAAAAAAAAAAAGGTTGAAAAGAAGAGGATAACATTTCACTTTGTCGCTGTGTTGTCGCTTGTTTTTTATTTTTGTCTGT
```

**Comment by magobu** [comment]
Thanks, yes I had inspected my .gz files and checked with the barcode types on the stacks manual, that's why I got the --index_index flag, but maybe because I'm running a plate at a time I should chose a different flag?? I'll keep trying

**Comment by kubu4** [comment]
Your barcodes file is not formatted correctly. Fix the barcodes file and that should resolve the error.

**Comment by magobu** [comment]
So I have finaly resolve the issue and have submitted the first job that was not rejected instantly. When I check the job it says that is pending and gives me this reason: (QOSGrpMemLimit). Is this becuse someone else has a job running and there's not enough memory for both jobs to run on the srlab account, or it is something else? should I cancel the job and wait?
![image](https://user-images.githubusercontent.com/42585702/187013082-ab538167-9406-47d1-b37b-19f5cdb641cc.png)

**Comment by kubu4** [comment]
Yep! If you want to have your job run without waiting for that other job to finish, you'll need to change your SBATCH script to use less than 120GB of memory. Changing that and resubmitting the job will allow your job to run on our smaller computing node (we have two nodes).

If you do this, don't forget to cancel your existing job:

`scancel 3609929`

**Comment by magobu** [comment]
👍

**Comment by magobu** [comment]
Hi @kubu4, I am trying to run the denovo_map.pl in the Stacks pipeline and it is not working. the fail message is saying that it is not recognizing this comand . Here is the script I'm using:
```
#!/bin/bash
#SBATCH --job-name=denovo
#SBATCH --account=srlab
#SBATCH --partition=srlab
#SBATCH --nodes=1
#SBATCH --time=120:00:00
#SBATCH --mem=120G
#SBATCH --chdir=/gscratch/srlab/martagb/
#SBATCH --mail-type=ALL
#SBATCH --mail-user=lapita@uw.edu
#SBATCH --export=all


module load gcc/10.1.0

/gscratch/srlab/programs/stacks-2.62/denovo_map.pl -M 1 -n 3 -o /gscratch/scrubbed/martagb/stacks \
--popmap gscratch/srlab/martagb/Eviota_popmap \
--samples /gscratch/scrubbed/martagb/jobs/radtags1 --rm-pcr-duplicates --paired
```
Is the denovo_map.pl in the gcc/10.1.0 module you created?
Thank you

**Comment by kubu4** [comment]
Please copy/paste error message.

**Comment by magobu** [comment]
/var/spool/slurm/d/job3752158/slurm_script: line 16: 
/gscratch/srlab/programs/stacks-2.62/denovo_map.pl: No such file or directory

**Comment by kubu4** [comment]
The script isn't in the location you specified (thus, the error message indicating such).

The script is here:

`/gscratch/srlab/programs/stacks-2.62/scripts/denovo_map.pl`

**Comment by magobu** [comment]
Ah! Thanks Sam, this should be my last inquiry! I am going to join the MERlab cluster. I'll transfer my files there. Your help getting me started in this new world for me of the supercomputer has been incredible!! I have learned a lot!

**Comment by kubu4** [comment]
Always happy to help! Feel free to hit us up for help any time!

**Comment by kubu4** [comment]
> gcc/10.1.0 module you created?

Just wanted to respond to this so you have a bit more background info.

This module is made available by the UW IT team. They have compiled a number of "core" modules that users might need/want to use on the cluster.

For example, the cluster has a default version of the GCC compiler (a type of program that is used to "build" other programs and make sure the system is compatible with what the program needs to run properly). As it turns out, Stacks requires a newer version of the GCC compiler than what's installed by default on the cluster. So, I looked at the modules available on Mox (`module avail`) and found a number of GCC versions. I selected the one with the highest version number.

So, when you load that module (`module load gcc/10.1.0`) the cluster will now use _that_ version of GCC for all subsequent GCC operations instead of the older, default version.

Anyway, UW IT realizes that they need to have a "stable" system, so they choose default versions of various programs that they test and make sure all work together, but they also recognize that creating a "stable" system will ultimately limit users ability to use the system, so they provide various modules to help users customize their working environments.

**Comment by magobu** [comment]
Thanks for that info! I had an idea that this was something created within
your own lab. Makes sense to me now! I thought I would have to start from
scratch when I submitted jobs from the MERlab.

Marta Gómez-Buckley
PhD Candidate
Fish Systematics and Biodiversity Lab
School of Aquatic and Fishery Sciences
University of Washington
