### ISSUE TITLE
QC CEABIGR larval samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1517]
Assess samples and provide brief summary / metadata info.

**Comment by kubu4** [comment]
Metadata for the sequencing aspect of these samples is here:

https://github.com/epigeneticstoocean/2018_L18_OAExp_Cvirginica_DNAm/blob/main/data/L18_larvae_meta.csv

However, I can't seem to find any specific info regarding the actual experimental conditions (e.g. what were "exposed" conditions for larvae and zygotes). Presumably you have this somewhere?

Also, for QC, you want these trimmed/FastQC, right?

**Comment by sr320** [comment]
>trimmed/FastQC, right?

Yes please

**Comment by kubu4** [comment]
Trimmed files are here:

https://gannet.fish.washington.edu/Atumefaciens/20220826-cvir-larvae_zygote-BSseq-fastp_trimming/

`*fastp-trim*.fq.gz`

MultiQC report:

https://gannet.fish.washington.edu/Atumefaciens/20220826-cvir-larvae_zygote-BSseq-fastp_trimming/multiqc_report.html
