### ISSUE TITLE
CFX Maestro for Mac

### ISSUE THREAD

**Issue by zbengt** [RobertsLab/resources#1518]
I downloaded and installed CFX Maestro from the link you (Sam) sent during pub-a-thon yesterday and I'm getting this error: 

“CFX Maestro” needs to be updated. The developer of this app needs to update it to work with this version of macOS. Contact the developer for more information.

Basically will not allow the app to open. I'm going to try it on the mac in the conference room in the meantime.

**Comment by kubu4** [comment]
CFX Maestro for Mac only supports through Sierra.

However, if you can't install on your laptop, no need to install on other computers. It's already installed on the Windows computer in 209 and, of course, on the qPCR machine computer in 228.

Sorry!

**Comment by LbetweenS** [comment]
你好，我想问一下哪里可以找到cfx maestro for mac的安装包啊。每次连接仪器都要先打开虚拟机再使用win版本的cfx好不方便。万分感激！

**Comment by kubu4** [comment]
Unfortunately, this is not freeware software, so we don't have the authorization to distribute it. You'll need to contact Bio-Rad to obtain a copy.
