### ISSUE TITLE
rsync to gannet from mox

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#1519]
trying to copy output from [this script 20220826_BS_Salmo.sh](https://gannet.fish.washington.edu/metacarcinus/mox_jobs/20220826_BS_Salmo.sh) over to gannet and getting the following error:

(base) [strigg@mox1 ~]$ rsync --archive --progress --verbose /gscratch/scrubbed/strigg/analyses/20220826 shellytrigg@gannet.fish.washington.edu:/metacarcinus/Salmo_Calig/analyses
shellytrigg@gannet.fish.washington.edu's password: 
sending incremental file list
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]

I am able to upload files through the GUI but prefer to rsync since it's a decent amount of data

Note that I am not connected to the UW VPN because I no longer have privileges. In the past I have done this successfully when gannet is mounted on another computer (e.g. https://github.com/RobertsLab/resources/issues/1052), but I'm not sure if my permissions are different now?

**Comment by kubu4** [comment]
Your problem is this part:

> /metacarcinus/Salmo_Calig/analyses

That's not the correct path. 

It needs to be:

`/volume2/web/metacarcinus/Salmo_Calig/analyses`

**Comment by shellytrigg** [comment]
solved! thanks @kubu4
