### ISSUE TITLE
qPCR plate caps vs film

### ISSUE THREAD

**Issue by zbengt** [RobertsLab/resources#1520]
I've been using caps to seal qPCR plates. Wondering if the optical film is better? Worse? Does it matter?

**Comment by kubu4** [comment]
> Does it matter?

No.

Why are you asking?

**Comment by zbengt** [comment]
Great, just curious. Only have enough caps for one more run so was planning to switch to film after I run out.

**Comment by kubu4** [comment]
Don't forget to order more caps, please.
