### ISSUE TITLE
Determine if Oly BS library was spiked with control DNA

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1522]
Deep dive to check documentation from 2015 :)

Specifically https://github.com/RobertsLab/project-olympia.oyster-genomic/wiki/MBD-BSseq-December-2015

**Comment by kubu4** [comment]
Are you wanting to know if it was actually used, or if there's potential carryover in the sequencing data? In regards to the latter, I'd guess this gets filtered out during the demultiplexing/QC stage(s) while coming off the sequencer, so there _shouldn't_ by any in the sequencing data.

If it was used, are you wanting to know the conversion rate(s) determined by the spike-in?

**Comment by sr320** [comment]
I am just trying to determine if it was used, ie were the libraries spiked with lambda DNA?

We need to evaluate bisulfite conversion efficiency.

**Comment by sr320** [comment]
For more context - I am currently aligning data to one strain used for BS control with no mapping, thus want to confirm if in fact a control was used what the exact strain would have been (if used)

**Comment by kubu4** [comment]
Gotcha.

Awaiting response from Zymo.

However, Illumina sequencing usually uses a PhiX spike-in. Sequence is available from NCBI:

ftp://ftp.ncbi.nlm.nih.gov/genomes/Viruses/enterobacteria_phage_phix174_sensu_lato_uid14015/NC_001422.fna

**Comment by sr320** [comment]
thanks - went ahead and started that alignment also...

**Comment by sr320** [comment]
Note - my take was you made library...

**Comment by kubu4** [comment]
Nope. We did MBD enrichment and then sent them off to Zymo for the rest.

**Comment by kubu4** [comment]
Zymo has indicated there was no spike-in. Here's email response:

> Hi Sam,
>
>I hope you are well.
>
> We use PhiX spike-in when sequencing bisulfite libraries but for a different purpose than evaluating bisulfite conversion efficiency. The PhiX from Illumina that I know of can’t be used for this purpose because it is a library rather than unamplified DNA: https://support.illumina.com/bulletins/2017/02/what-is-the-phix-control-v3-library-and-what-is-its-function-in-.html
> 
>
> We calculate bisulfite conversion rate based on cytosines in non-CpG context. For species that have non-CpG methylation this approach doesn’t work well though. Therefore, several years ago we started including synthetic spike-in control in DNA samples prior to library preparation which we use for bisulfite conversion rate calculation, in addition to our standard method of calculating bisulfite conversion rate. Unfortunately, the work on zr1394 was done before we started including this synthetic spike-in.
>
>
>PhiX spike in data is filtered out after the sequencing run and it is not included into FASTQ files.
>
>Please feel free to e-mail me with any questions or concerns.
>
>Kind regards,
>
>Daria
