### ISSUE TITLE
Get GO slim terms for oyster annot file 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1523]
File needing GO slim terms - https://github.com/RobertsLab/project-sc-RNAseq/blob/main/output/t25-blast-GO-unfolded.tab

**Comment by mattgeorgephd** [comment]
Here is the file that I have been using for c gigas

https://gannet.fish.washington.edu/spartina/project-oyster-oa/Haws/GO-annotation/GO-GOslim.sorted

**Comment by kubu4** [comment]
> Here is the file that I have been using for c gigas

Thanks. Already have an R script to plug the GO terms file into.

**Comment by kubu4** [comment]
Alrighty, I've pushed the three output files and the Rmd file to the repo.

- `t25blast-goslims.BP.GOslims.csv`

- `t25blast-goslims.CC.GOslims.csv`

- `t25blast-goslims.MF.GOslims.csv`

They're formatted like so:

| GOslim     | Count | Percent            | Term                       | go_terms                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|------------|-------|--------------------|----------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| GO:0000278 | 18    | 0.899550224887556  | mitotic cell cycle         | GO:0000070;GO:0000132;GO:0000281;GO:0007052;GO:0007076;GO:0007346;GO:0010458;GO:0031536;GO:0034184;GO:0040001;GO:0044772;GO:0090307;GO:1902412                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| GO:0000910 | 4     | 0.199900049975012  | cytokinesis                | GO:0000281;GO:0032467;GO:1902412                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| GO:0002181 | 1     | 0.0499750124937531 | cytoplasmic translation    | GO:0017183                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| GO:0002376 | 65    | 3.24837581209395   | immune system process      | GO:0001787;GO:0001866;GO:0002244;GO:0002548;GO:0002639;GO:0002780;GO:0002827;GO:0002860;GO:0002891;GO:0006955;GO:0030099;GO:0030218;GO:0030316;GO:0030593;GO:0033005;GO:0034340;GO:0035011;GO:0035162;GO:0035206;GO:0035754;GO:0035855;GO:0036035;GO:0042098;GO:0042271;GO:0042742;GO:0042832;GO:0043032;GO:0043152;GO:0045087;GO:0045578;GO:0045579;GO:0045582;GO:0045638;GO:0045671;GO:0045672;GO:0045954;GO:0048821;GO:0050829;GO:0050830;GO:0050832;GO:0050862;GO:0050870;GO:0051607;GO:0060215;GO:0060216;GO:0060217;GO:0060218;GO:0060370;GO:0061844;GO:0071425;GO:1900100;GO:1902036;GO:2001206 |
| GO:0003012 | 11    | 0.549725137431284  | muscle system process      | GO:0006937;GO:0014819;GO:0030432;GO:0086005;GO:0098914;GO:0098915;GO:0100001;GO:1901078;GO:1905000;GO:1905025                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| GO:0003013 | 10    | 0.499750124937531  | circulatory system process | GO:0003085;GO:0014916;GO:0045906;GO:0086005;GO:0086091;GO:0098914;GO:0098915;GO:1905000;GO:1905025                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| GO:0003014 | 0     | 0                  | renal system process       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| GO:0003016 | 0     | 0                  | respiratory system process |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |

**Comment by sr320** [comment]
thanks! can you provide link to code... I am curious of how to do myself and looking to get on slim term per GOID (not summarized)

**Comment by kubu4** [comment]
https://github.com/RobertsLab/project-sc-RNAseq/blob/main/code/go-goslim-t25blast.Rmd

**Comment by AHuffmyer** [comment]
This is amazing Sam! Just used it for my scripts and worked like a charm.
