### ISSUE TITLE
Issue with a slurm job

### ISSUE THREAD

**Issue by magobu** [RobertsLab/resources#1526]
Hi,
When I submit this job to Slurm, 

  GNU nano 2.3.1                       File: Marta_denovo.sh                                                     

#!/bin/bash
#SBATCH --job-name=denovo
#SBATCH --account=srlab
#SBATCH --partition=srlab
#SBATCH --nodes=1
#SBATCH --time=90:00:00
#SBATCH --mem=110G
#SBATCH --chdir=/gscratch/srlab/martagb/
#SBATCH --mail-type=ALL
#SBATCH --mail-user=lapita@uw.edu
#SBATCH --export=all

module load gcc/10.1.0

/gscratch/srlab/programs/stacks-2.62/scripts/denovo_map.pl -M 1 -n 3 -o /gscratch/scrubbed/martagb/stacks \
--popmap gscratch/srlab/martagb/Eviota_popmap \
--samples /gscratch/scrubbed/martagb/jobs/radtags1 --rm-pcr-duplicates --paired

I get this message back:

 GNU nano 2.3.1                      File: slurm-3923873.out                                                    

Unable to find '_BINDIR_/ustacks'.

I did run the first step of the Stacks' pipeline (process_radtags) with no issue, but it looks like the 'ustacks' component within the denovo_map.pl step is not in the correct folder??

Thanks in advance for the help :)

**Comment by sr320** [comment]
Why is 

`GNU nano 2.3.1 File: Marta_denovo.sh`

at the top of your slum script?

**Comment by magobu** [comment]
Oh! That's just the header part of the nano file, not part of the script

**Comment by sr320** [comment]
It is best to use markdown formatting to delineate what is actual code or output and what is not, to avoid such confusion..

see https://d.pr/i/dCfih7


So to confirm,  the entire contents of your slurm output file was 

```
Unable to find '_BINDIR_/ustacks'.
```

?

**Comment by sr320** [comment]
@kubu4 am I off base here...?

---
My suggestion (note I bin this into stacks software issue)

is that you need to change 

perl script `/gscratch/srlab/programs/stacks-2.62/scripts/denovo_map.pl`

beginning 

```
#!/usr/bin/env perl
#
# Copyright 2010-2021, Julian Catchen <jcatchen@illinois.edu>
#
# This file is part of Stacks.
#
# Stacks is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Stacks is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Stacks.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use POSIX;
use File::Temp qw/ mktemp /;
use File::Spec;
use constant stacks_version => "_VERSION_";

use constant true  => 1;
use constant false => 0;

my $dry_run      = false;
my $exe_path     = "_BINDIR_";
my $out_path     = "";
my $popmap_path  = "";
my $sample_path  = "";
my $db           = "";
my $min_cov      = 0;
my $sample_id    = 1;
my $gzip         = false;
my $paired       = false;
my $resume       = false;
my $force_reexe  = false;
my $genetic_map  = false;
my $time         = "";

my @parents;
my @progeny;
my @samples;
```


You need to change the line 
from 
```
my $exe_path     = "_BINDIR_";
```

to indicate your installation directory 
(I gleaned this from https://rpubs.com/mendiomi/869617)

I suggest trying 

```
my $exe_path     = "/gscratch/srlab/programs/stacks-2.62/;
```

**Comment by kubu4** [comment]
Certainly possible. But, Stacks can be installed in a way that configures that automatically. Possibly will eliminate similar downstream issues?

**Comment by sr320** [comment]
@magobu before we get two far down this path--- it is my understanding from Luke you need a different installation of stacks? and this version of stacks will not work for you?

**Comment by kubu4** [comment]
Installation has been fixed/updated.

Paths to programs _and_ scripts are here now: `/gscratch/srlab/programs/stacks-2.62/bin`

**Comment by magobu** [comment]
Okay, thanks! I'll try that now.

**Comment by kubu4** [comment]
Oh, and for reference, I did the following:

1. Uninstall Stacks: `make uninstall`
2. Configure installation path (prefix) for Stacks: `/.configure --prefix /gscratch/srlab/programs/stacks-2.62`
3. Build Stacks: `make -j 28` (the `-j 28` specifies number of processors/threads to use)
4. Install Stacks in location specified in Step 2: `make install`.

Usually, Step 4 isn't needed/required by most software, as the binaries are compiled in Step 3. However, Stacks uses the `make install` step to set various paths for the binaries built in Step 3; this is unusual for most programs. When I initially compiled Stacks, I did _not_ do Step 4, as it is usually not needed (and, actually leads to problems/errors when doing so on Mox).

**Comment by magobu** [comment]
Well, the issue of the installation seems to be fixed! Now I have to figure out why my Eviota_popmap file is not opening when I have it there!

```
Unable to open population map, 'gscratch/srlab/martagb/Eviota_popmap', No such file or directory

```

**Comment by sr320** [comment]
you are missing `/`

location is `/gscratch/srlab/martagb/Eviota_popmap`

**Comment by sr320** [comment]
specifically in your batch file

```
/gscratch/srlab/programs/stacks-2.62/scripts/denovo_map.pl -M 1 -n 3 -o /gscratch/scrubbed/martagb/stacks 
--popmap gscratch/srlab/martagb/Eviota_popmap 
--samples /gscratch/scrubbed/martagb/jobs/radtags1 --rm-pcr-duplicates --paired
```

should in fact be
```
/gscratch/srlab/programs/stacks-2.62/scripts/denovo_map.pl -M 1 -n 3 -o /gscratch/scrubbed/martagb/stacks 
--popmap /gscratch/srlab/martagb/Eviota_popmap 
--samples /gscratch/scrubbed/martagb/jobs/radtags1 --rm-pcr-duplicates --paired
```

**Comment by sr320** [comment]
helpful hint here...
When you get error such as 
`Unable to open population map, 'gscratch/srlab/martagb/Eviota_popmap', No such file or directory`

in your terminal go to that location and see if the file is there. often when you do that you will find the error in the code itself. 

(also you will find that >50% of errors will likely be a missing `/` or missing ` `.  🥲 )

**Comment by magobu** [comment]
Thanks for the reloading of Stacks and the corrections. I got the job running (it's been there for >12 hours now). I want to send another job (same de novo job but for plate 2). Is this okay? I checked the squeue and looks that there aren't other jobs sent at the moment from srlab. 

> helpful hint here... When you get error such as `Unable to open population map, 'gscratch/srlab/martagb/Eviota_popmap', No such file or directory`
> 
> in your terminal go to that location and see if the file is there. often when you do that you will find the error in the code itself.
> 
> (also you will find that >50% of errors will likely be a missing `/` or missing ` `. 🥲 )

Sorry @sr320, can you clarify what is the secon common error you are referring to on this message? Is it just a missing  '.'?

**Comment by kubu4** [comment]
> I want to send another job (same de novo job but for plate 2). Is this okay?

Yes, of course! No need to ask. Thanks for the consideration, though!

> can you clarify what is the secon common error you are referring to on this message? Is it just a missing '.'?

He's just providing examples of common types of omissions that people make which lead to the the `No such file or directory` error. 

The only problem in your command was that missing leading `/`.
