### ISSUE TITLE
Add Presentations info / links

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1530]
to
https://github.com/RobertsLab/website/blob/master/Products.md

I am adding folks I am pretty sure have done presentations..

**Comment by larkenr** [comment]
added PCSGA conference, UPS science seminar, and NOAA physiology presentation

**Comment by sr320** [comment]
re-opening to capture other folks assigned here...

**Comment by AHuffmyer** [comment]
Added Benthics talk and MCR LTER talk

**Comment by ChrisMantegna** [comment]
added NWStraits Commission presentation
