### ISSUE TITLE
node not available

### ISSUE THREAD

**Issue by magobu** [RobertsLab/resources#1531]
Hi, could I use a different node that is not out for maintenance when I submit my job to slurm?
```
JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
           3937176     srlab denovo_s   lapita PD       0:00      1 (ReqNodeNotAvail, Reserved for maintenance)
```
Thanks

**Comment by kubu4** [comment]
You can not. Mox/Klone is taken offline for maintenance on the first Tuesday of every month.

If you think your job will finish before Tuesday at 9AM, then you can adjust the runtime of your job in the header of your SBATCH script to finish before that day/time and then run your script.

If you do that, don't forget to cancel your first job:

`scancel 3937176`

**Comment by sr320** [comment]
Why is it out for maintenance? And can you please post your slurm script?

**Comment by magobu** [comment]
Okay. thanks for letting me know @kubu4 and @sr320 here is the script:
```#!/bin/bash
#SBATCH --job-name=denovo_sigillata
#SBATCH --account=srlab
#SBATCH --partition=srlab
#SBATCH --nodes=1
#SBATCH --time=240:00:00
#SBATCH --mem=110G
#SBATCH --chdir=/gscratch/srlab/martagb/
#SBATCH --mail-type=ALL
#SBATCH --mail-user=lapita@uw.edu
#SBATCH --export=all


module load gcc/10.1.0

/gscratch/srlab/programs/stacks-2.62/bin/denovo_map.pl -M 1 -n 3 -o /gscratch/scrubbed/martagb/stacks/sigil_denovo_test \
--popmap /gscratch/srlab/martagb/sigil_popmap.txt \
--samples /gscratch/scrubbed/martagb/sigillata --rm-pcr-duplicates --paired

**Comment by sr320** [comment]
@magobu make sure you are on the mox email list as they remind users about scheduled maintenance and when maintenance is complete.
