### ISSUE TITLE
Splice up EPIMAR video

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1535]
Take zoom recording (~4 hours) and split up into individual talks, based on program. 
Options on mac include Quicktime and iMovie.

**Comment by sr320** [comment]
Here is a how-to example using the large screen in lab connected to Mac mini.

https://gannet.fish.washington.edu/seashell/snaps/LQ-Screen_Recording_2022-10-18_at_1.07.07_PM.mov

**Comment by DoroLar** [comment]
Hi. I watched the video earlier, but I am wondering if there is a specific recording you would like me to split up.

**Comment by sr320** [comment]
Good question - All talks on EPIMAR page (should be open) need to be split out. I have started. Finished videos are on desktop with LastName. "Raw" videos are in download folder or already sitting in iMovie

**Comment by DoroLar** [comment]
Hey Professor. I apologize for not communicating with you for some time. This past week, I was sick with the flu. Where can I find the EPIMAR page? I have looked and I cannot find it.

**Comment by sr320** [comment]
Should be on in the Download folder on the mac mini with the very large screen. Could even still be open on second monitor.

**Comment by DoroLar** [comment]
The screen is only showing an image. How can I enter?

**Comment by sr320** [comment]
Ask Olivia or Zach (in today) or I will be in Tuesday and Thursday

**Comment by DoroLar** [comment]
Hello Professor. I am currently going through the process of splicing the recordings, but there is already a video dragged down. How can I remove this so that I may drag the other video down?
