### ISSUE TITLE
Submit waste pick-up request for mercuric chloride bottles

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1536]
with regard to bottles counted - need to request pick up

**Comment by sr320** [comment]
let me know what info is needed. we have some counts.

**Comment by kubu4** [comment]
Counts and volumes would be great.

**Comment by kubu4** [comment]
Submitted.

**Comment by kubu4** [comment]
EH&S has provided a bunch of carboys and has requested we transfer all liquid from the individual bottles to the carboys. The carboys are pre-labelled with appropriate info/warnings in FTR 228.

If we do _not_ want to keep the bottles, they can be emptied into the carboys (shake bottles to remove as much liquid as possible), and then dried in a fume hood. After that, the can be disposed of as lab glass waste.

@sr320 - Do we have anyone that can tackle this or should I handle it?

**Comment by sr320** [comment]
Let's give @Noahk22 the opportunity

**Comment by Noahk22** [comment]
Ok cool, when should I come in and handle it?

**Comment by kubu4** [comment]
All waste containers were picked up by EH&S today.
