### ISSUE TITLE
What to do when program is looking for another program under a diff name

### ISSUE THREAD

**Issue by jldimond** [RobertsLab/resources#154]
So ddocent is looking for pear read merger as "pearRM", but it is installed as "pear". What is the best course of action? What is the proper way to change the name of a program? Alternatively, is it better to edit the code in ddocent?

**Comment by kubu4** [comment]
Please post the error message you get. That will make troubleshooting easier.

**Comment by sr320** [comment]
I would also suggest contacting John- and asking for advice as this is a
“bug” - post an issue if the software is on GitHub

**Comment by jldimond** [comment]
```
Checking for required software
The dependency pearRM is not installed or is not in your $PATH.
The file listing adapters (included with trimmomatic) is not installed or is not in your $PATH.
/usr/local/bin/ddocent: line 93: [: 16a: integer expression expected

Please install all required software before running dDocent again.
hummingbird:~ srlab$ which pear
/usr/local/bin/pear
```
I made sure this was in my $PATH

The manual install notes do say "**PEAR needs to be installed as pearRM in your $PATH"

Sure, I will contact Jon. Just wanted to see if you all thought it might be an easy fix.

**Comment by sr320** [comment]
Ok so
Sounds like you should...
"**PEAR needs to be installed as pearRM in your $PATH"

However I am not sure exactly how to do this but imagine Sam might

**Comment by kubu4** [comment]
I'll address the main issue shortly, but it looks like using Anaconda (i.e. Conda, Bioconda) is the easier way to go: http://ddocent.com/bioconda/

**Comment by jldimond** [comment]
Yes, I thought it sounded much easier to do the conda install, but it wasn't working for me, which is why I've ended up doing it manually. I've forgotten why I had trouble with the conda method - it was a while ago now.

**Comment by kubu4** [comment]
For renaming pear, I think you can rename /usr/local/bin/pear to your desired name:

```sudo mv /usr/local/bin/pear /usr/local/bin/pearRM```

Make sure the renamed file actually will run pear by entering:

```/usr/local/bin/pearRM```

This should spit out the abbreviated manual for pear.

If that works, you need to re-source your system $PATH:

```source /etc/bashrc```

Then, check your system PATH to see if it worked:

```which pearRM```

**Comment by jldimond** [comment]
Thanks I will try tomorrow...

**Comment by kubu4** [comment]
OK, I just did the renaming and it works to run pear (sorry I didn't just try it before posting the instructions). So, you don't need to do it. However, you need to re-source your system PATH.

However, there's a caveat to all of this. The ```/usr/local/bin``` directory is available to all users on hummingbird. Renaming files here could impact other users if they are expecting pear to be in the PATH, and not pearRM...

**Comment by kubu4** [comment]
I didn't fully think this through last night. No need to rename the executable file. Instead, create a symbolic link with your desired name that points to the original target. The symbolic link also ends up in your PATH. 

I've done this on hummingbird and verified I can run pear, so I think the only thing you might need to do is re-source the ```/etc/bashrc``` file from your user profile. Here's what I did:

1. Rename pearRM back to original pear

```sudo mv /usr/local/bin/pearRM /usr/local/bin/pear```

2. Create symobolic link called pearRM that points to pear:

```ln -s /usr/local/bin/pear /usr/local/bin/pearRM```

3. Re-source /etc/bashrc to update PATH:

```source /etc/bashrc```

4. Verify pearRM is in system PATH:

```which pearRM```

5. Run pearRM to make sure it actually runs pear:

```pearRM```

This spits out the abbreviated pear manual, so we're good to go and we retain the original software name!

**Comment by jldimond** [comment]
Awesome! I will try it out later and let you know if I have any problems. Thanks!
