### ISSUE TITLE
Git revert not working...

### ISSUE THREAD

**Issue by ChrisMantegna** [RobertsLab/resources#1541]
Welp, I was not careful and 'synced' to the main branch that I forked from and now my repo has been replaced with Steven's. I attempted to undo the commit to get back to my own posts but was unsuccessful. How do I undo the last '64 commits to catch up to the main branch' and get my own content back? My local copy of the repo is my own and up to date prior to the mistake, but I'm not sure how to use that to overwrite the remote one (if that's possible).

This is the repo: https://github.com/ChrisMantegna/ChrisMantegna.github.io
Please tag others as you see fit.
Thanks!

**Comment by kubu4** [comment]
> My local copy of the repo is my own

If I'm understanding everything correctly, then I'd first try pushing your local repo, although I suspect that Git won't like this, due to the fact that the remote repo has changes that you don't have locally. Anyway, try that and please report back

**Comment by ChrisMantegna** [comment]
@kubu4 - you would be correct. It wouldn't let me push because of the remote changes.

**Comment by kubu4** [comment]
For kicks, can you please paste message you received after attempting to push?

**Comment by ChrisMantegna** [comment]
I've attempted it enough that I can no longer push - my push/ pull tab is now registering the changes from the remote repo. That is new - it only let me try to push.

![image](https://user-images.githubusercontent.com/81385272/199525841-9a559574-871f-47ba-b583-8a8517b7d1b6.png)

**Comment by ChrisMantegna** [comment]
Ok. Today's lesson - double down on the wrong thing and you may just get it right... I did that and it gave me a mix of my stuff and Steven's stuff. It won't take long to delete his stuff and keep my own. For example, this folder is completely my own stuff. Thanks, @kubu4 !
![image](https://user-images.githubusercontent.com/81385272/199530411-912edc5d-0e14-4728-b0be-5042862036c3.png)

**Comment by kubu4** [comment]
Great job! Glad it all worked out!
