### ISSUE TITLE
fix tables and link to notebook posts 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1544]

**Comment by ocattau** [comment]
New Issue: how to edit home page if you used Aidan's notebook to fork https://ocattau.github.io/notebook-2/

- I cannot find where in the config file or anywhere else on the github page where I could edit out all of Aidan's personal information

**Comment by kubu4** [comment]
You need to edit this file:

https://github.com/ocattau/notebook-2/blob/master/index.html

**Comment by sr320** [comment]
Also, generally speaking-  I will often just use text search in editor to find page with said text (eg Atom)

**Comment by sr320** [comment]
>  issue that is only occasionally relevant in my posts where the images are rendered but the table is not

can you provide link to raw markdown page?

**Comment by ocattau** [comment]
https://github.com/ocattau/notebook-2/blob/master/_posts/2022-08-20-MD1_moleculardelivery.md

**Comment by sr320** [comment]
My approach would be look at code and see what is different in what renders and what does not....
see https://raw.githubusercontent.com/ocattau/notebook-2/master/_posts/2022-08-20-MD1_moleculardelivery.md

looking at https://ocattau.github.io/notebook-2/2022-08-20-MD1_moleculardelivery/ only 48 hour section renders. 
What is different??? 

There is a space above table. Try that and see if that fixes it.

(other potential future problem could be actions (https://github.com/ocattau/notebook-2/actions) as Zach has problem with link checker-  he deleted that action as it takes post down if links do not work)

**Comment by kubu4** [comment]
What was the fix?

**Comment by ocattau** [comment]
The fix ended up being super easy it's dumb. I just needed to add a blank space in between the table and the title/header :)
