### ISSUE TITLE
Virginia MBDSeq Lab Protocol

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#155]
Here's my understanding of how the lab time would be split up:

**Wednesday**:
Isolate DNA - Use E.Z.N.A. Kit (Omega)
Quantify DNA - Use Qubit dsDNA Kit (Invitrogen/ThermoFisher)

**Thursday**:
Shear DNA to target fragment length (~500bp) - Use NOAA sonicator
Verify shearing - Use Seeb Lab Bioanlyzer with DNA 12000 Kit (Agilent)
Enrich for MBD - Use MethylMiner Kit (Invitrogen/ThermoFisher)

**Friday**:
Quantify DNA - Use Qubit hsDNA Kit (Invitrogen/ThermoFisher)
Bisulfite treatment - EZ DNA Methylation Gold Kit (ZymoResearch)
Verify bisulfite conversion - Use Seeb Lab Bioanalyzer with RNA Pico 6000 Kit (Agilent)

I do have a some questions:

1.  The MethylMiner protocol has different instructions depending on how much DNA we're working with. Does the quantify of DNA I work with depend on how much we isolate, or are we trying to isolate a fixed amount?
2. MethylMiner elution strategies pg. 12: are we doing a single elution or a stepwise elution?

**Comment by kubu4** [comment]
Wednesday looks good.

Thursday looks mostly good. MBD is a 2 -3 day procedure (usually 3 days).

We won't be doing any bisulfite conversion.

1. We generally start with as much input DNA as possible, as post-MBD recovery usually yields 1 - 15% of the input DNA.

2. Single elution.

**Comment by yaaminiv** [comment]
To clarify: we won't be using the EZ DNA Methylation Gold Kit? And the processes I start Thursday will take until Friday, maybe Saturday to complete?

**Comment by kubu4** [comment]
Correct, no bisulfite conversion (i.e. EZ DNA Methylation Gold Kit).

I would not start MBD on Thursday for two reasons:

1. I don't work on Fridays, so you'd be flying solo on the second day.
2. Yes, possible you'd have to come in on Saturday to finish.

Of course, if you're comfortable, you're more than welcome to give it a go!

**Comment by yaaminiv** [comment]
Gotcha! Revised schedule:

**Wednesday**:
Isolate DNA - Use E.Z.N.A. Kit (Omega)
Quantify DNA - Use Qubit dsDNA Kit (Invitrogen/ThermoFisher)

**Thursday**:
Shear DNA to target fragment length (~500bp) - Use NOAA sonicator
Verify shearing - Use Seeb Lab Bioanlyzer with DNA 12000 Kit (Agilent)

**Tuesday-Wednesday**:
Enrich for MBD - Use MethylMiner Kit (Invitrogen/ThermoFisher)
Quantify DNA - Use Qubit hsDNA Kit (Invitrogen/ThermoFisher)

**Comment by kubu4** [comment]
Further revised schedule!

MBD only on the actual DNA samples that need to be sequenced!

Next Thursday - Shearing and quantification

Tues-Thurs - MBD and quantification.

**Comment by kubu4** [comment]
Oh yeah, what time works for you for shearing next Thursday?

**Comment by yaaminiv** [comment]
So I isolate and quantify on Wednesday, shear on Thursday, and based on what we can shear and quantify, do MBD?

I'm free all day until 4 p.m. for shearing
