### ISSUE TITLE
Sequencing data: GenBank and SRA

### ISSUE THREAD

**Issue by afcoyle** [RobertsLab/resources#1550]
I'm looking to upload a bunch of crab sequencing data to GenBank for the sequencing publication! However, since we both used all available sequencing data at some point in our work, Grace already uploaded all of my relevant files in the experiment to SRA when writing her paper. I'm not completely clear on the difference between SRA and GenBank - does this require a re-upload? 

Internal IDs for the relevant files are below:

72
73
113
118
127
132
151
173
178
221
222
254
272
280
294
334
349
359
425
427
445
463
481
485
304428
329774
329775
329776
329777
380820
380821
380822
380823
380824
380825

**Comment by sr320** [comment]
No further upload is needed.  Can  you provide your to all of the data used in your paper and we can phrase language.

**Comment by afcoyle** [comment]
Sorry, do you mean I should put a link in my paper to where Grace's data is stored, or that I should put the link here?

**Comment by sr320** [comment]
here

**Comment by afcoyle** [comment]
This should do the trick!

https://www.ncbi.nlm.nih.gov/Traces/study/?acc=SRP256457&o=acc_s%3Aa

If not, it's at https://www.ncbi.nlm.nih.gov/Traces/study/ with the accession ID SRP256457
