### ISSUE TITLE
Confirmation of ethics approval (or that it wasn't needed)

### ISSUE THREAD

**Issue by afcoyle** [RobertsLab/resources#1551]
I'm addressing some issues with the paper I'm writing up, and they're requiring confirmation that ethics approval was not required for this study (or that we obtained approval). Here's the specific language:

`If ethics approval was obtained for the study, please update and include the following statement in your manuscript: 'The studies involving animals were reviewed and approved by [full name and affiliation of ethics committee]. Then send your revised manuscript files via email reply in PDF and an editable format.`

`If ethics approval was not required for this study, please provide further evidence via email return within one week. This can be in the form of a letter from your institution or ethics committee, along with a copy of the letter translated into English if necessary. Please also include details of this reasoning within your manuscript and send your revised manuscript files via email reply in PDF and an editable format.`

How do I go about getting proof of ethical approval (or evidence that it wasn't needed)?

**Comment by AHuffmyer** [comment]
I think this would only be required if you needed a taxa specific permit - like IACUC for fish/vertebrates. Or if you needed permitting/approval for a human studies project. Typically for invertebrates this wouldn't be needed, but if you had any collection permits you could include that information.

**Comment by mattgeorgephd** [comment]
Ethics approval isn't required for inverts outside of some cephalopods. If you need a letter you could hit up the UW office of animal welfare.

https://www.washington.edu/undergradresearch/students/ethics/
