### ISSUE TITLE
Notebook posts adding date into URL and changes if date header is changed

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1552]
In the E5 project notebooks (https://urol-e5.github.io/) I noticed that the notebook post URL's contain a date from the header. For example, `https://urol-e5.github.io/2022/11/06/E5-Moorea-Adult-Stressor-Experiment.html`. So, if you change the date in the header, the URL also changes and any links to the post will be broken. We will need to change this format so that the date is not included in the URL so that posts will have a more permanent URL that can be linked even if the header changes.

**Comment by kubu4** [comment]
Change the `permalink` line in the `_config.yml` to set the URL format you desire (i.e. without date).
