### ISSUE TITLE
Approach for power analysis

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1553]
We recently got reviewer response - but at a loss of how to approach / carry out. Anyone have suggestions?

>  I was hoping that authors would add a clear power analysis for their mQTL study. Authors imply their results have false negatives (‘underpowered’) but how about false positives?

**Comment by AHuffmyer** [comment]
I have looked at using the `pwr` package in R for this (tutorial here https://www.statmethods.net/stats/power.html). There are functions you can use depending on the type of statistical test you are running. You will enter the expected effect size (e.g., Cohen's D), the statistical significance cut off (0.05) and your sample size (n). The functions will then return a power value that is your probability of detecting the specified effect with your sample size. You can solve for any of the variables - for example you can specify a desired effect size, significance, and power and solve for the number of replicates you would need. Tutorials/examples are here: https://www.r-bloggers.com/2021/05/power-analysis-in-statistics-with-r/ and https://www.statmethods.net/stats/power.html.

**Comment by mattgeorgephd** [comment]
For a quick and dirty analysis I found this website helpful when preparing the USDA grant

http://powerandsamplesize.com/Calculators/Compare-2-Means/2-Sample-Equality
