### ISSUE TITLE
gfortran paths in R unresolved with Mac OS 13

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1555]
I recently got a new computer that is running Mac OS 13 with an Apple M1 processor. Unfortunately the Apple processors are different than Intel based systems and change some of the system file paths for command line tools. 

I am trying to install/load the WGCNA package and am getting issues with R not being able to find `gfortran` directories and files. For example, when I load WGCNA and dependencies (such as preprocessCore), I get the following error:  

```
Error: package or namespace load failed for ‘WGCNA’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/preprocessCore/libs/preprocessCore.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/preprocessCore/libs/preprocessCore.so, 0x0006): Library not loaded: /opt/R/arm64/gfortran/lib/libquadmath.0.dylib
  Referenced from: <36F88879-3BFB-3718-9C6E-5231ABED8B20> /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/preprocessCore/libs/preprocessCore.so
  Reason: tried: '/opt/R/arm64/gfortran/lib/libquadmath.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/R/arm64/gfortran/lib/libquadmath.0.dylib' (no such file), '/opt/R/arm64/gfortran/lib/libquadmath.0.dylib' (no such file), '/usr/local/lib/libquadmath.0.dylib' (no such file), '/usr/lib/libquadmath.0.dylib' (no such file, not in dyld cache) 
```

When I locate this missing file in terminal by running `locate libquadmath.0.dylib`, I see that these files indeed exist on my computer at these locations: 

```
/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libquadmath.0.dylib
/usr/local/gfortran/lib/libquadmath.0.dylib
```

I've tried a few hints on the internet but nothing as worked. Basically, I need to tell R to look in a different folder than where it is looking now to load gfortran. 

Has anyone experienced similar problems with R directories?

**Comment by kubu4** [comment]
I'd recommend installing R4.2.2: https://cran.r-project.org/bin/macosx/big-sur-arm64/base/R-4.2.2-arm64.pkg

That build is specifically for M1 Macs.

See this page for additional notes for the Fortran stuff:

- https://cran.r-project.org/bin/macosx/

That page will tell you to go here to get the Apple silicon gfortran and a plethora of instructions on how to set it up:

- https://mac.r-project.org/tools/

**Comment by AHuffmyer** [comment]
Thanks Sam! I'll check out those links. I am using R 4.2.2, so hopefully they fix the issue in a future R version.

**Comment by AHuffmyer** [comment]
Sam solved my problem! Following the steps here: https://mac.r-project.org/tools/. 

I downloaded the [gfortran-12.0.1-20220312-is-darwin20-arm64.tar.xz](https://mac.r-project.org/tools/gfortran-12.0.1-20220312-is-darwin20-arm64.tar.xz) file into my home directory. Then I unpacked it with `sudo tar fxz gfortran-12.0.1-20220312-is-darwin20-arm64.tar.xz -C /`. Finally `export PATH=$PATH:/opt/R/arm64/gfortran/bin`. 

WGCNA now loads!
