### ISSUE TITLE
Option for targeted DNA methylation analysis

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1557]
Please check with UW core facility to see if they have any recommendations for sequencing technologies / approaches where we could get DNA methylation information for targeted region / gene.

**Comment by kubu4** [comment]
Alrighty, I (nicely) pestered the UW PacBio folks, which is who I was waiting on, and they finally got back to me.

The quick and dirty:

- Neither of the UW core facilities offer BS-seq or targeted methylation sequencing.

Technically, PacBio sequencing can detect methylation, but there's not a means to do targeted sequencing. So, there'd be a lot of "extra" sequencing data if we opted for that route.

Finally, although I haven't had a chance to read/review it, it looks like you can do targeted methylation sequencing using the NanoPore (big thanks to the UW PacBio people for the suggestion)!

https://nanoporetech.com/knowledge-exchange/methylation-detection-with-nanopore-sequencing-rrms

**Comment by sr320** [comment]
Can you check with nanopore core https://sites.google.com/uw.edu/uwnanopore/service-rates?authuser=1
on options?

We have 40 samples but are only interested in sequencing ~4kb region of genome.

**Comment by sr320** [comment]
What is the technology for library prep? How do you get a single region?

**Comment by sr320** [comment]
Please go ahead and get an official quote.

**Comment by kubu4** [comment]
> What is the technology for library prep? How do you get a single region?

NanoPore offers a Cas9 kit which performs some cleavage and the adds some adapter tailing to the excised region.

However, the person I spoke to suggested that Cas9 is a pain (finicky and labor intensive), but he didn't make clear what the alternative is. I've asked for some additional clarification/insight.

**Comment by sr320** [comment]
> NanoPore offers a Cas9 kit which performs some cleavage and the adds some adapter tailing to the excised region

so this is something we would have to do or they would do as part of the quote?

**Comment by kubu4** [comment]
They do all of this (it's part of library prep). We just submit DNA.

**Comment by kubu4** [comment]
Official quote: 
- $7914.41

**Comment by sr320** [comment]
> Official quote:
> $7914.41

can we get a quote reducing the samples from 40 to 20?

**Comment by kubu4** [comment]
Updated quote request submitted.

**Comment by kubu4** [comment]
They just got back to me today (with an apology for the delay):

- $5260.03
[Estimate NSC0075 White 2023-05-09.pdf](https://github.com/RobertsLab/resources/files/11456041/Estimate.NSC0075.White.2023-05-09.pdf)

**Comment by sr320** [comment]
awaiting Rick greenlight.

**Comment by sr320** [comment]
@kubu4 Rick says this is a go.. can you find out what they want as starting material?

**Comment by kubu4** [comment]
From their website:

>For DNA submission, please run a standard or pulsed-field gel, BioAnalyzer, or TapeStation to visualize DNA quality and length before submitting. If your sample looks degraded, re-extract the sample or plan for shorter read lengths.

>Additional guidelines:

>Total material requirements for whole-genome sequencing are 6 µg.
Minimum volume is 10 µL.
Ideal concentration range is 60 ng/µL to 120 ng/µL.
For best results, use a high molecular weight DNA extraction protocol.
Do not use DNA isolation protocols containing glycogen.
Extraction methods should preserve long fragment lengths and avoid repetitive mechanical pipetting or spin columns.
We strongly recommend using an RNase during DNA extraction.
Ideal submissions are RNA- and protein-free.
Ensure that your elution buffer does not contain residual denaturants (salts, phenol) or detergents (Triton, SDS).
Avoid freeze–thaw cycles, and do not expose to high temperatures (>65°C) for more than 1 hour.
Ship DNA in LoBind microcentrifuge tubes or LoBind PCR plates (Eppendorf). Pad and insulate your samples to minimize shearing during shipping.

**Comment by kubu4** [comment]
Just a heads up, the quote is good through 8/7/2023, so samples will need to be submitted very soon. Do you know the status of the samples? We'll need Rick to fill out a sample sheet manifest. I'll track it down and get it uploaded here.

**Comment by kubu4** [comment]
Sample manifest is attached.

[UW-NSC Sample Submission Form.xlsx](https://github.com/RobertsLab/resources/files/12217550/UW-NSC.Sample.Submission.Form.xlsx)

**Comment by kubu4** [comment]
Oof, just got off the phone with the core facility. They are unable to perform multiplexing to get sufficient sequencing depth. They don't know why, but they basically said they won't be able to go forward with this project, unless we wanted to run samples on individual flow cells (which would increase the costs substantially).

Suggestion/question from core facility was whether or not we could do bisulfite sequencing and then targeted qPCR... They were just tossing out ideas.
