### ISSUE TITLE
Skyline Question

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#156]
Why would something like this happen in Skyline? A new graph is created below the normal one.
![capture](https://user-images.githubusercontent.com/14934314/34897605-b06a9c64-f7a3-11e7-8af8-e87144d70bf5.PNG)

Most other tabs look like this:
![capture1](https://user-images.githubusercontent.com/14934314/34897623-d1b346be-f7a3-11e7-87da-db6ce4bb7fa5.PNG)

**Comment by grace-ac** [comment]
@yaaminiv

**Comment by yaaminiv** [comment]
Can you click on the plus (+) sign next to the peptide?

**Comment by grace-ac** [comment]
![capture3](https://user-images.githubusercontent.com/14934314/34897949-765c1276-f7a5-11e7-88cc-483eaa4497aa.PNG)

**Comment by yaaminiv** [comment]
Looks like it's splitting precursors in one pane and other transitions in the bottom pane. You probably need to mess around with your view settings...?

**Comment by grace-ac** [comment]
okay cool, thanks! thought i'd ask in case you've seen something like this before.
