### ISSUE TITLE
Create Master data table for CEABIGR

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1566]
Create a CSV where every row is an oyster that has all data we have (at individual organism level). 
(will have >90k columns)

**Comment by kubu4** [comment]
I think I need a bit more info on what your wanting. For example, here's what I was picturing:

| oyster.ID | gene.01.fpkm | gene.02.fpkm | transcript.01.fpkm | transcript.02.fpkm | gene.01.mean.methylation | gene.02.methylation |
|-----------|--------------|--------------|--------------------|--------------------|--------------------------|---------------------|
| 01       | 1            | 1            | 1                  | 1                  | 1                        | 1                   |

Do you also want number of sequencing reads, post-trimming sequencing reads, sex, treatment conditions, number of bisulfite sequencing reads, number of post-trimming bisulfite sequencing reads, number of CpGs, number of methylated CpGs, number of methylated CpGs at different coverages, number of methylated genes based on percentage of CpGs methylated (e.g 75%)?

There are probably some (many?) more possible columns that I'm not listing at the moment.

What do you think?

**Comment by sr320** [comment]
Great question - 
Lets do it iteratively...
Start with
all gene fpkm
all transcript fpkm
all gene methylation
all gene coefficient variation

**Comment by kubu4** [comment]
Is there any incentive to organize this data via something other than a CSV (.e.g. create a SQLite database, create GenomicRanges() objects), or will this create too much "friction" for accessing/using the data since most of us don't have experience accessing data through other means? Just thinking a massive CSV seems unwieldly...

**Comment by sr320** [comment]
Lets start with massive CSV and see where we get.

**Comment by kubu4** [comment]
Here's initial CSV table (~51MB):

https://github.com/sr320/ceabigr/blob/main/output/comprehensive.csv?raw=true

- transcript FPKM
- gene FPKM
- gene methylation

Working on adding coefficients of variation.

Code:

https://github.com/sr320/ceabigr/blob/main/code/comprehensive-csv.Rmd

**Comment by kubu4** [comment]
Regarding CoV...

Since this is calculated per gene across all samples, there is no CoV on a _per sample_ basis (which is how the comprehensive CSV is organized). 

I'm not coming up with any good ideas ATM for how to add this info into that comprehensive CSV.

Would you have any suggestions?

**Comment by sr320** [comment]
you are correct . one oyster would not have any gene cov as only one value 

I will start playing with this and see what happens. 
thanks!

**Comment by sr320** [comment]
can you add columns for sex and treatment?

**Comment by sr320** [comment]
got it https://github.com/sr320/ceabigr/blob/main/output/45-oyster-table/oyster-wide.csv

**Comment by kubu4** [comment]
Dang, sorry! Somehow I missed the notification for the additional columns!
