### ISSUE TITLE
R - Subtract two columns in all data frames in a list and put output in new column

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1567]
I have a list of data frames.

Each data frame has two columns.

For each data frame, I want to subtract the second column from the first.

For each data frame, I want the output to be put in a column called `delta`.

How do I do this??? I know how to do this on a single data frame using `mutate()`, but `mutate()` doesn't work on lists.

It seems like this should be "easy" using `lapply()`, but I still have difficulty wrapping my head around creating functions for `lapply()` to use; plus this is complicated because I don't fully understand how to call columns from each data frame in the list... Ugh.

If you want a list of data frames to test, you can download and then load this R object - it's the list of data frames I'm actually working with.: 

https://github.com/sr320/ceabigr/blob/main/output/40-gene-methylation/methylation.transposed.rownames.list.RData?raw=true

**Comment by AHuffmyer** [comment]
Would it be most straightforward to convert the list to a data frame then do mutate() and save as a new object in a loop of your lists?

**Comment by kubu4** [comment]
I'm not sure how to begin implementing your suggestion.

If you don't mind, would you be able to clarify/elaborate a bit on that approach?

**Comment by AHuffmyer** [comment]
Could be something like this: 

```
list_vector<-c(list1, list2, list3)

for (list in list_vector) {
  
    ### Convert to data frame
    df <- as.data.frame(list)

    ### Mutate difference 
    df <- df %>%
            mutate(new_column=column1-column2)
    
    ### Write file of results 
    write_csv(df, file = paste0("path_of_file/results_", list, ".csv"))
    
}
```

This is highly simplified, but could be a way to approach it in a loop.

**Comment by kubu4** [comment]
Thanks! That helps! I'll give it a shot if no one chimes in with a more direct way of working with the existing list. Basically, I was hoping the command should be a clean "one-liner".

**Comment by kubu4** [comment]
Well, I finally was able to register for ChatGPT and it solved this issue!

```r
methylation.transposed.rownames.list <- lapply(methylation.transposed.rownames.list, function(df) {
  df$delta <- abs(df[,1] - df[,2])
  return(df)
})
```

**Comment by AHuffmyer** [comment]
Thats a simple awesome solution!

**Comment by kubu4** [comment]
I'd like to add that the key to this solution is the `return(df)` aspect.

I had a _very_ similar solution, but was getting _just_ the `delta` column and not the rest of the data frames.
