### ISSUE TITLE
Download coral SRA data (RNAseq and WGBS)

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1569]
With an eye toward running through CEABiGR pipelines

64 samples total - PRJNA744403

https://www.ncbi.nlm.nih.gov/bioproject/?term=PRJNA744403

**Comment by kubu4** [comment]
These are all downloaded and converted to FastQ. I'm in the process of gzip-ing them (which is going to take awhile).

After that completes, I was going to run these through QC, too. Or should I skip that part?

Also, do you have any preference on where they're stored (i.e. should I put them in Nightingales)?

**Comment by sr320** [comment]
QC sounds good - I would put an gannet - as not our own data no requirement to do Nightingales.

**Comment by AHuffmyer** [comment]
@kubu4 I am trying to download these RNAseq SRA files to our URI server to do some analysis. I looked at your notebook but I'm a bit confused on how to downloaded files from SRA to the remote server.

**Comment by sr320** [comment]
@sr320 I have a notebook too :) 


https://sr320.github.io/Apulcra/
```
/home/shared/sratoolkit.2.11.2-ubuntu64/bin/fasterq-dump.2.11.2 \
--outdir /home/sr320/ncbi  \
--split-files \
--threads 27 \
--mem 100GB \
--progress \
SRR8601366
```

**Comment by kubu4** [comment]
@AHuffmyer - Can you clarify which part you're confused by. 

Step 2 in my notebook post shows the command:

```shell
/gscratch/srlab/programs/sratoolkit.2.11.3-centos_linux64/bin/prefetch \
 --option-file /gscratch/srlab/sam/data/NCBI-BioProject-PRJNA744403-coral_metagenomics/SraAccList-PRJNA744403.txt
```

**Comment by AHuffmyer** [comment]
Thank you both! @sr320's script works for me!

**Comment by AHuffmyer** [comment]
Actually, I now have a follow up question. @sr320 for your script, did you find a way to download many files at once reading in names from a text file? 

@kubu4 I used your approach and it resulted in a folder for each SRR# and inside of that is a .sra, that I then need to split/convert into the fastq files using your loop in your notebook. However, it looks like your script doesn't have a recursive setting the look for the .sra files within the directories that are created in the download. Did you have this problem?

**Comment by sr320** [comment]
@AHuffmyer technically Sam is doing it correctly using prefetch first, then converting. 
can you provide a uRL to what you are trying to do?

**Comment by sr320** [comment]
also `fasterq-dump` can take a list of accessions.

**Comment by kubu4** [comment]
The method @sr320 uses allows you to supply a list of accessions. Not sure how that list is delimited, but the help menu says you can do that.

**Comment by sr320** [comment]
something like this should work if you want to skip prefetch

```
for i in $(cat ../data/acc_list01.txt); do echo $i; date; 
/home/shared/sratoolkit.2.11.2-ubuntu64/bin/fasterq-dump.2.11.2 \
--outdir /home/sr320/ncbi  \
--split-files \
--threads 48 \
--mem 100GB \
--progress \
-S $i; done
```

where `../data/acc_list01.txt` looks like 

```
SRR8601367 
SRR8601368 
SRR8601369
```

running now to confirm

**Comment by AHuffmyer** [comment]
Thank you both this is so helpful! I am trying to download the E5 Deep Dive samples from this project: https://www.ncbi.nlm.nih.gov/sra?linkname=bioproject_sra_all&from_uid=744403 for RNAseq to URI's server. And I also need to learn how to remote download from NCBI anyways. @sr320 I will try your code this morning!

**Comment by kubu4** [comment]
@AHuffmyer - Can you show us the code you've used and plan on using?

Also, @sr320 's code should be able to be simplified by doing something like this:

```shell
/home/shared/sratoolkit.2.11.2-ubuntu64/bin/fasterq-dump.2.11.2 \
--outdir /home/sr320/ncbi  \
--split-files \
--threads 27 \
--mem 100GB \
--progress \
SRR8601366 \
SRR8601367 \
SRR8601369
```

**Comment by sr320** [comment]
@kubu4 actually that does not seem to work... first thing I tried

**Comment by kubu4** [comment]
Oh! Interesting! Help menu suggests that should work. Sorry!

**Comment by kubu4** [comment]
Ah! When using `sratoolkit.2.11.2-ubuntu64` with a space-delimited list of accessions (like [in my comment above](https://github.com/RobertsLab/resources/issues/1569#issuecomment-1470170536)), the resulting error is generated:

`
fasterq-dump.2.11.2 int: string unexpected while executing query within virtual file system module - multiple response SRR URLs for the same service 's3'`

Turns out, if we use an upgraded version, the command works! Quick test on Raven seems to have worked (or, at least, didn't throw an error):

```
/home/shared/sratoolkit.3.0.2-ubuntu64/bin/./fasterq-dump \
--outdir /home/shared/8TB_HDD_02/sam/ \
--progress \
SRR8601366 \
SRR8601367
```

**Comment by kubu4** [comment]
I think this depends on how SRA Tool Kit was configured. If it's configured with a designated cache directory _and_ the "Tools" menu indicates to _use_ that cache directory, then the `fasterq-dump` command automatically handles recursion into directories.

This is why I was able to run the `fasterq-dump` command without anything "extra".

See this SRA Tool Kit page for more info:

https://github.com/ncbi/sra-tools/wiki/05.-Toolkit-Configuration

**Comment by AHuffmyer** [comment]
Oh perfect! I'll run that next and let you know how it works.

**Comment by AHuffmyer** [comment]
That makes sense. I will also try something like this `fasterq-dump --outdir ../raw --split-files SRR*` to see if it could handle directories as well.

**Comment by kubu4** [comment]
Also, if you can't (or don't want to mess around with the SRA Tool Kit configuration stuff), you can recursively parse through directories for specific files like so:

```bash

# Enable recursive globbing
shopt -s globstar

# Run fasterq-dump on any SRA file
 for file in **/*.sra
do
  fasterq-dump "${file}"
done
```

**Comment by AHuffmyer** [comment]
My notebook post on this topic is here: https://ahuffmyer.github.io/ASH_Putnam_Lab_Notebook/E5-Deep-Dive-RNAseq-Count-Matrix-Analysis/
