### ISSUE TITLE
Ubuntu/ Microsoft Device Setup

### ISSUE THREAD

**Issue by ChrisMantegna** [RobertsLab/resources#1570]
Hey @kubu4 !
I need your help again setting up Ubuntu on my computer. I wiped everything and forgot to add Ubuntu back before R, and now RStudio will not install/ call any packages. I've hit the usual suspects (per Google searches) of changing 'Global Options' settings and ensuring I install all of the base packages and such, so now the general Google concensus is that Ubuntu should have been installed first.  

I cannot locate the GH Issue where we went through this the first time in summer 2021, so I am asking again...
Thanks,
Chris

**Comment by kubu4** [comment]
Installing Ubuntu on Windows has become even easier than before. Follow the instruction(s) here:

https://learn.microsoft.com/en-us/windows/wsl/install

However, you should be able to run R and RStudio on Windows _without_ Ubuntu installed. If you can post some error messages and/or screenshots, that would help.

Finally, you can always use the RStudio installation we have on Raven by going here on your web browser (remember - you'll need Husky OnNet running _before_ you visit this address):
http://raven.fish.washington.edu:8787

**Comment by ChrisMantegna** [comment]
I'm on Raven now - figured I'd fight with my own machine tomorrow. :)
I can install R and Rstudio, but none of the packages from tidyverse to ggplot2 will install correctly and then load. I'll add screenshots tomorrow when I go back to it.
