### ISSUE TITLE
Add three coral species to Genomic Resources Page

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1571]
Add these genomes to Genomic Resources page
https://robertslab.github.io/resources/Genomic-Resources/

Pocillopora verrucosa genome v1.0 : http://pver.reefgenomics.org/ : https://www.ncbi.nlm.nih.gov/data-hub/genome/GCA_014529365.1/
Montipora capitata v3 - http://cyanophora.rutgers.edu/montipora/ : https://www.ncbi.nlm.nih.gov/data-hub/genome/GCA_006542545.1/
Pocillopora acuta v2 - http://cyanophora.rutgers.edu/Pocillopora_acuta/ :

Focus is getting genome and indexes such that can use for genome browsers (urls) 
Add any available genome track files also (eg gene gffs ) 

Can host all files on gannet of owl (eg http://owl.fish.washington.edu/halfshell/genomic-databank)

**Comment by kubu4** [comment]
Genomes and corresponding HiSat2 index files have been added.

The two NCBI genomes did not have any annotation files (i.e. no GFF).

The _P.acuta_ had a GFF and that has also been added.

**Comment by sr320** [comment]
But are there not annotations on other url for each genome?

**Comment by kubu4** [comment]
> But are there not annotations on other url for each genome?

Correct. No GFFs for either on NCBI.

**Comment by kubu4** [comment]
Oh, wait. There are two URLs?! I see! Sorry. Will report back later after I visit those...

**Comment by kubu4** [comment]
Alrighty, have them _all_ up there, with HiSat2 indexes, GFFs, and GTFs!
