### ISSUE TITLE
Cod Sampling Preparation

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1572]
On Feb 7 (Tuesday) will be going down to OR to sample cod. 

- [ ] confirm how much good RNA-later we have
- [ ] have a liquid nitrogen dewer / shipper ready for trip 
- [ ] have cooler with dry ice 
- [ ] ethanol for alcohol bath 
- [ ] any other general supplies for sampling tissue

**Comment by kubu4** [comment]
> ethanol for alcohol bath

I'm not sure what this is. Like a dry ice/ethanol bath? Basically, need to know what ethanol proof you need/want. Also, what volume are you wanting?

> have cooler with dry ice

What time will you be leaving? Might need to load up cooler the day before departure.

**Comment by kubu4** [comment]
> sample cod

Any idea on how many samples you'll be collecting?

Also, is that a facility which will have sampling tools available or do you need to bring the whole kit and kaboodle for sampling?

Should someone get tubes pre-labelled/filled with RNAlater?

**Comment by sr320** [comment]
> What time will you be leaving?
Thursday afternoon - so can prep Thursday AM

> how many samples you'll be collecting? 
@laurahspencer is finding out.

> do you need to bring the whole kit and kaboodle for sampling
I would like to have everything just in case. 

> Should someone get tubes pre-labelled
at least labelling

**Comment by kubu4** [comment]
> have a liquid nitrogen dewer / shipper ready for trip

To clarify, does "ready" mean filled with LN2, or does "ready" mean make sure a dewar is available (i.e. not already in use; not necessarily filled with LN2)?

**Comment by sr320** [comment]
> To clarify, does "ready" mean filled with LN2, or does "ready" mean make sure a dewar is availab

Filled with LN2

**Comment by laurahspencer** [comment]
There are 158 fish to sample (unless loads die in the next couple weeks)

**Comment by sr320** [comment]
> There are 158 fish to sample

and probably want to be prepared to sample 3-4 tissues/tubes per fish.

**Comment by mattgeorgephd** [comment]
Just a heads up: when I was regularly sampling tissue from 72 oysters (6 tubes per individual, 432 total), the smaller dewar couldn't fit all of the 2 ml cryotubes tubes by itself.

**Comment by kubu4** [comment]
> and probably want to be prepared to sample 3-4 tissues/tubes per fish.

If someone can generate a spreadsheet with a a sample/tube labelling scheme, then we can get someone started on labelling tubes.

Also, are samples going into RNAlater or being snap frozen in LN2? If the former, then getting tubes pre-filled with RNAlater would be critical, as well.

**Comment by laurahspencer** [comment]
We’re actually leaving on Tuesday the 7th (not Thursday). Steven perhaps we should leave early enough to get oriented to the lab Tuesday afternoon, so we’re ready to sample first thing Wednesday morning?  5-hr drive, so would need to leave by late morning. I can come in next week or Monday the 6th to help prep if needed.

I’ll create a sampling spreadsheet later today.

**Comment by kubu4** [comment]
> have cooler with dry ice

What size cooler are we talking? Beer cooler? Or a "standard" polystyrene cooler that companies use to ship reagents (i.e. sort of small)?

**Comment by laurahspencer** [comment]
Created a [spreadsheet](https://docs.google.com/spreadsheets/d/1CAWLv5P9ANri1YTfuivIAKSuGGffHRud4BGwx3y5rNs/edit?usp=sharing) but we have some details to work out.  Hoping to have a quick planning meeting with folks at Hatfield this week.  Depending on when that meeting happens, I can come in Thursday or next Monday to help prep things.  

In the meantime I'll try to answer any outstanding questions: 
- Definitely going to snap-freeze tissues with LN. May also want to preserve duplicate tissue samples in RNALater, TBD.  **How much RNAlater do you have in stock at the lab?**  
- Currently planning on sampling 2 tissues (liver, head-kidney) for RNASeq. May add a third or even fourth (TBD).  NOAA staff will also provide pre-filled vials of ethanol to collect fin clips for DNA.   
- Bigger cooler the better, or multiple smaller coolers. I expect we'll need to transfer samples on dry ice back to Seattle.

**Comment by kubu4** [comment]
@sr320 - Do we have someone (i.e. Dorothy) available for labelling tubes and/or assessing RNAlater quantities?

**Comment by laurahspencer** [comment]
> Do we have someone (i.e. Dorothy) available for labelling tubes and/or assessing RNAlater quantities?

I can prep the vials unless you have someone with time on their hands.  I can swing by the lab tomorrow to check on RNAlater, too, if no one is in today/tomorrow.

**Comment by sr320** [comment]
@kubu4 can you just go ahead and order RNALater in the event we can have arrive by Tuesday AM?

**Comment by laurahspencer** [comment]
At the lab- no RNAlater in the chemical cabinet, so definitely need to order.  

@kubu4 can you also order more of these tubes and screw caps please?  

![IMG_4927](https://user-images.githubusercontent.com/17264765/215912822-20a515ac-74f6-4abd-938f-c0c806b4e127.jpg)
![IMG_4928](https://user-images.githubusercontent.com/17264765/215912820-abd05308-9ebe-4bc9-b3ae-d2ad31ed756c.jpg)

**Comment by kubu4** [comment]
Oof, delivery estimate for RNAlater is showing as 2/8/2023 (from Fisher)...

**Comment by laurahspencer** [comment]
Is there a delivery estimate for those screw-cap tubes?  

There are plenty of 1.7 mL snap-top tubes - some multicolored, many clear - however I remember having issues with some snap-top tubes and freezing in LN. They would occasionally pop open (or even explode). @mattgeorgephd which tubes did you use recently when you froze in LN? Were they the clear 1.7 mL snap-top tubes that are abundant in the Roberts lab?

**Comment by sr320** [comment]
Please query @mgavery to see if she might be able to lend us supplies.

**Comment by mgavery** [comment]
I have 2 mL snapcap tubes that I like for LN sampling (because they don't pop), but they're at Manchester - might be able to check with Montlake folks though.  If you're doing a dry ice/EtOH bath, then maybe popping won't be as much of an issue?  Let me know, happy to ask around.  How much RNAlater do you need?

**Comment by kubu4** [comment]
Popping is definitely a concern. Don't use snapcap tubes. Plus, opening them later (after freezing) frequently results in the caps snapping off at the hinge...

@laurahspencer - No ETA provided yet for tubes.

**Comment by laurahspencer** [comment]
Mac hooked us up with some RNAlater. I'm picking it up Monday morning from the NOAA phys. group at Montlake. Now we just need to figure out the tube situation.

**Comment by kubu4** [comment]
Just got shipping confirmation - tubes are set to be delivered Monday.

**Comment by laurahspencer** [comment]
Great! Thank you!
