### ISSUE TITLE
CFX Maestro password for the qPCR computer

### ISSUE THREAD

**Issue by zbengt** [RobertsLab/resources#1576]
CFX Maestro is asking for a password on the upstairs qPCR computer. Tried the password for the computer and it didn't work. Does anyone know the password?

**Comment by kubu4** [comment]
For `admin` account, there is no password. Leave the password field blank and then click 'Ok` (or `Enter` - not entirely sure what the confirmation button says).

**Comment by zbengt** [comment]
Thanks Sam!
