### ISSUE TITLE
R namespace load failed

### ISSUE THREAD

**Issue by mattgeorgephd** [RobertsLab/resources#1577]
Hi!

I keep getting the following error when I try to load `library(tidyverse)`:

`Error: package or namespace load failed for ‘tidyverse’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘cli’ 3.3.0 is already loaded, but >= 3.4.0 is required`

This is off a fresh re-install of R 4.2.2, RStudio 12.0, and Rtools42. The problem doesn't seem to be limited to tidyverse, as I get similar errors with other packages - so maybe something more fundamental like where my packages are loading from?

Any help appreciated.

**Comment by kubu4** [comment]
Try to remove the package:

```r
remove.packages("cli")
```

Restart R and RStudio (Quarto). It'd be best to actually restart your computer.

Then, reinstall that package:

```r
install.packages("cli"
```

Let us know how it goes!

**Comment by mattgeorgephd** [comment]
This seems to help done the trick! Thanks @kubu4.
