### ISSUE TITLE
Crab Project: Next steps

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#158]
Need information on samples (from Pam) in order to select some for RNA extraction

**Comment by grace-ac** [comment]
We have the spreadsheet - http://owl.fish.washington.edu/scaphapoda/grace/011918_NPRB-crab-data.xlsx

Need to select samples to pool
Pulled from NPRB Proposal:

"from Day 9, 5 infected crabs and 5 uninfected crabs (n = 2 RNA combined samples); 

from Day 12, 5 crabs per diseased state (infected or uninfected) from each of the 3 temperature treatments (n = 6 RNA combined samples); and, 

from Day 25, 5 crabs per diseased state (infected or uninfected) from each of the 3 temperature treatments (n = 6 RNA combined samples) totaling 14 pooled RNA samples (Table 1). 

The 14 RNA samples will be sent to the University of Washington (UW) Northwest Genomics Center for library construction and transcriptome sequencing on the Illumina HiSeq 4000 platform. Samples from individual crabs not included in pooling will be retained for qPCR and expression analysis (see below)."

**Comment by grace-ac** [comment]
Crabs are ALL MALES. 133 crabs have 3 samples. 22 of those crabs are mature. 91 are immature. 

In this scenario, I chose to stick with immature. When possible, I chose samples that belonged to the same crab, but because the crabs were split into three temperatures after the initial sampling, it wasn't possible to do it between all three samples dates. 

The large numbers (1 through 14) represent the 14 "pooled" samples. Because of the massive die-offs in the warm temperature tanks, there are only 2 infected and 1 uninfected samples per the final two sampling dates. 

![crab-samples](https://user-images.githubusercontent.com/14934314/35411937-7bbed7ec-01cf-11e8-9697-2f758c614b8e.png)

**Comment by grace-ac** [comment]
There are many extra samples, so I will do a trial run of RNA extraction. I am reading through the [protocol](https://github.com/RobertsLab/resources/blob/master/protocols/rna_isolation_rnazol_rt.md).  I think the linked protocol is the correct one.

**Comment by sr320** [comment]
great
