### ISSUE TITLE
Gannet rsync error

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1582]
While I can easily ssh into gannet... 
when I try rsync from mox 

```
[sr320@mox1 becker]$ rsync -avz sr320@gannet.fish.washington.edu:/volume2/web/Atumefaciens/hputnam-Becker_E5/WGBS_Becker_E5/Becker_WGBS/reference_genome .
sr320@gannet.fish.washington.edu's password: 
Permission denied, please try again.
```

any suggestions?

**Comment by kubu4** [comment]
Hmmm, any chance you entered your Mox password instead of Gannet's?

Also, you could try rsync-ing _from_ Gannet to Mox (i.e. ssh into Gannet and then rsync to desired Mox directory).
