### ISSUE TITLE
Fix Genomic Resources page (Pocillipora verrucosa?)

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1587]
There is a section that is likely Cladxxx that is labelled P verr. Plus there are some formatting issues..

**Comment by kubu4** [comment]
Can you clarify what issues you're seeing? I see that the strikethrough formatting didn't work (e.g. tildes are visible, and nothing has a strikethrough).

Also, what is

> Cladxxx

**Comment by kubu4** [comment]
Ah! Think I see the other issue.

Fixed that heading for _C.goreaui_.

**Comment by sr320** [comment]
got it! https://github.com/RobertsLab/resources/commit/6e3a6930ff7c30eedfb44cfbbd5a626e36d23a17
