### ISSUE TITLE
Get UW quote for low coverage WGS

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1589]
See what UW cost / options is for handing them over 160 tissue samples (fish fin), for 2-4x whole genome coverage (Pacific Cod) - short read sequencing technology.

**Comment by sr320** [comment]
genome is ~650Mb.

**Comment by kubu4** [comment]
>  tissue samples

They do not perform any nucleic acid extractions.

They only accept DNA/RNA.

**Comment by sr320** [comment]
Can you get a quote with us sending them DNA?

**Comment by kubu4** [comment]
Quote:

- $20,421
