### ISSUE TITLE
How to use facet_wrap to group data in ggplot2

### ISSUE THREAD

**Issue by ocattau** [RobertsLab/resources#1590]
Here is my code for my CS paper figure: looking at ploidy differences across the three treatment groups 

```{r}
Full_data3<-read.csv(file="https://raw.githubusercontent.com/ocattau/CS-manuscript/main/raw-data/Full_data3.csv") 

boxplot3<-ggplot(data=Full_data3, aes(x=factor(trt), y=CS_activity))+
  geom_boxplot(aes(x=factor(trt), y=CS_activity))+
  theme_minimal()+geom_point(data=Full_data3, alpha=0.5)+
  ylab(expression('CS activity nmol' (min^-1) (mg^-1)))+
  xlab("Treatment Group") + scale_y_continuous(limits=c(0,8))+facet_wrap(~ploidy)
boxplot3

```

The issue is that the ggplot2 is printing blank space where the old data used to be and the names are overlapping. Is there a better way to code this boxplot? 

Here is my image 

![image](https://user-images.githubusercontent.com/81712104/221013668-a0fdc79e-a6f5-405d-97fc-0685729d4ad9.png)

**Comment by AHuffmyer** [comment]
You can also remove the parentheses around min and mg on your y axis. Since you have the -1 exponent it implies that the units are nmol per min per mg.

**Comment by ocattau** [comment]
Got it thanks!
