### ISSUE TITLE
ggplot label help

### ISSUE THREAD

**Issue by ocattau** [RobertsLab/resources#1591]
With my new figure, it is almost perfect but the heat + desiccation label on the x-axis is too long and doesn't look very good. I could always change it to diagonal or smaller text but I would prefer if  "heat +" was on one line and "desiccation" on the other. Anyone know how to do this? 

```{r}
boxplot3<-ggplot(data=Full_data3, aes(x=factor(trt_short), y=CS_activity))+
  geom_boxplot(aes(x=factor(trt_short, level=c("control", "heat only", "heat + desiccation")), y=CS_activity))+
  theme_minimal()+geom_point(data=Full_data3, alpha=0.5)+
  ylab(expression('CS activity nmol' (min^-1) (mg^-1)))+
  xlab("Treatment Group") + scale_y_continuous(limits=c(0,8))+facet_wrap(~ploidy2)
```

![image](https://user-images.githubusercontent.com/81712104/221268257-15254ebf-2abe-41a6-8dad-b6e8da47bc7c.png)

**Comment by mattgeorgephd** [comment]
Try the following with the `stringr` package

library(stringr)

`scale_x_discrete(labels = function(x) str_wrap(x, width = 10))` 

where the width is the number of characters wide you want before wrapping to the next line

**Comment by ocattau** [comment]
Thanks!
