### ISSUE TITLE
why did i elute RNA in 95C water? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1592]
I'm getting back into extracting RNA from sea star coelomocytes and in looking at the [protocol I used last year](https://docs.google.com/document/d/11paxsz0wDixpnt2pAAOYXUON9yDMJuOsCR99q8hOWGA/edit), I see that I eluted RNA using 95C heated water... but I can't find anywhere where I might have gotten that suggestion to do it... It's not in the kit manual [Quick DNA/RNA Microprep Plus D7005](https://files.zymoresearch.com/protocols/_d7005t_d7005_quick-dna-rna_microprep_plus_kit.pdf)... or any of my notes

A colleague is asking for my rationale behind doing this and since I can't find where I got that info, I'm not sure how I heard about it... **Any thoughts on this?** I submitted a question to Zymo techs to see what they think, too.

**Comment by mattgeorgephd** [comment]
The [EZNA Mollusc DNA extraction kit](https://docs.google.com/document/d/1_qi5NZfPaGzD9gh-u01s8uGYy2OMPolZeltc9XMIE9M/edit?usp=sharing) we have been using suggests heating the elution buffer to 70C. It is definitely possible to elute without heating, but I think they suggest warming the buffer to a temperature below the melting temperature for whichever nucleic acid you are aiming for to speed up molecular motion and increase efficiency with which it comes off of the column.

**Comment by grace-ac** [comment]
Thanks @mattgeorgephd ! Yeah, I'm thinking I must have taken that temp from Yaamini's DNA extraction protocol... but RNA is different than DNA! So moving forward I think I'll stick with room temp water to elute.  I tried the heated water last year because i was getting really low yields from my samples and was trying different things. Thanks!
