### ISSUE TITLE
Kallisto count matrix merge for DESeq2

### ISSUE THREAD

**Issue by zbengt** [RobertsLab/resources#1599]
Looking for the scripts we discussed last week to merge count matrices (abundance.tsv) from kallisto for oyster lncRNA analysis in DESeq2. Only found ballgown scripts in ceabigr. Is [this](https://github.com/laurahspencer/red-king_RNASeq-2022) Laura's crab repo that should show this? Want to make sure I'm looking in the right place.

**Comment by kubu4** [comment]
I missed lab meeting last week, so am not really up to date on what you need/want.

Can you describe what you file(s) you currently have and what file(s) you need?

In the mean time, here's a CEABIGR kallisto lncRNA Rmd file (not sure if it helps):

https://github.com/sr320/ceabigr/blob/main/code/13-lncRNA-kallisto.Rmd

**Comment by zbengt** [comment]
I basically ran the code you linked and got abundance.tsv's for each library. At pub-a-thon we talked about merging these abundance.tsv's for DESeq2 and there being a preferred way to do this in one of Laura's crab repo's.

**Comment by kubu4** [comment]
>  merging these abundance.tsv

Can you describe the final format you're looking to have after merging? Also, what do you mean by merging? Joining (i.e. putting files side-by-side) or concatenating (stacking files on top of each other)?

What type of file(s) do you need for DESeq2?

**Comment by kubu4** [comment]
Also, take a look at this document from Laura's crab repo (the one you linked above):

https://htmlpreview.github.io/?https://github.com/laurahspencer/red-king_RNASeq-2022/blob/main/notebooks/02-DESeq2-etc-RKC.html

**Comment by zbengt** [comment]
Ah yes! This was what I was looking for, sorry I missed. Thank you! I'll follow up if I still have questions.

**Comment by laurahspencer** [comment]
Looks like you have separate gene count matrices for each library, which you want to merge into one matrix for DESeq2.  Check out this notebook, where I use tximport to do just that with output from Salmon (a program similar to Kallisto). 

https://github.com/laurahspencer/red-king_RNASeq-2022/blob/main/notebooks/01-Importing-Salmon-Counts.Rmd

**Comment by zbengt** [comment]
Thanks Laura! I was just checking out how to use tximport with kallisto TSVs [here](https://bioconductor.org/packages/devel/bioc/vignettes/tximport/inst/doc/tximport.html#kallisto_with_TSV_files), so good to know I'm on the right track.

**Comment by sr320** [comment]
And here is an example using trinity perl script
https://github.com/sr320/ceabigr/blob/c0e27ef9804535cead51c01edd4e45ed98612add/code/14-RNA-kallisto.Rmd

**Comment by zbengt** [comment]
Notebook post with solution [here](https://zbengt.github.io/2023-03-09-Mergin-Kallisto_Abundance/). Counts needed to be rounded before input in DESeq2 similar to closed issue #1056.

**Comment by sr320** [comment]
And lets please never see `setwd` again. 😄

**Comment by zbengt** [comment]
Sorry 😄
