### ISSUE TITLE
How to register for conferences with Treq

### ISSUE THREAD

**Issue by ocattau** [RobertsLab/resources#1600]
I am registering for the NSA convention in Baltimore at the end of the month and I need to use Treq so that I won't have to put the convention on my credit card (~$2000). Has anyone successfully used Treq to pay for hotel and flight reservations? If so how do you get an invoice for flights?

**Comment by kubu4** [comment]
I'd email an admin person for assistance with this. Possibly Lisa Smith (autumn _at_ uw.edu)?

**Comment by sr320** [comment]
Actually it's not SAFS but college- olivia has contact

**Comment by ocattau** [comment]
Yep [eFAST@uw.edu](mailto:eFAST@uw.edu)

**Comment by sr320** [comment]
see https://robertslab.github.io/resources/Purchasing-and-Reimbursement/#travel for clarification
