### ISSUE TITLE
Table related error using UpsetR

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1603]
I am trying to make an upset plot using UpsetR

getting an error

```
Error in start_col:end_col : argument of length 0
7.
`[.tbl_df`(data, , start_col:end_col)
6.
NextMethod(`[`)
5.
`[.spec_tbl_df`(data, , start_col:end_col)
4.
data[, start_col:end_col]
3.
as.data.frame(data[, start_col:end_col])
2.
Remove(data, first.col, last.col, Set_names)
1.
upset(test2, sets = c("h", "l", "g"), mb.ratio = c(0.55, 0.45),
order.by = "freq")
```

See full code including me making a plot with provided `movies` data as well was my `test2` df. 

https://github.com/sr320/paper-geoduck-gene-exp/blob/main/code/02-upset.md

**Comment by kubu4** [comment]
I'd try to convert your data to a data frame. The `str()` function shows that the example data is a data.frame, but your is something else.

**Comment by sr320** [comment]
thanks! was able to convert to integer to match `movies` - but still throwing error. 
https://d.pr/i/CXzp8D

**Comment by kubu4** [comment]
Try to convert your data to a data frame.

See how when you run the `srt()` function on `movies` the output is this? 

`## 'data.frame':    3883 obs. of  21 variables:`

Yours has this weird output:

```r
str(test2)

## spc_tbl_ [34,947 × 4] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
```

**Comment by sr320** [comment]
makes sense.. cannot figure out how to do so - internet suggests this is a type of dataframe.

**Comment by kubu4** [comment]
Try:

```r
test2.df <- as.data.frame(test2)
```

**Comment by sr320** [comment]
Perfect! thanks 

That did it 💯
