### ISSUE TITLE
qubit RNA HS Standard 2 calibration error

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1606]
I'm extracting RNA from sea star coelomocytes and running 1ul of sample on the qubit using a Qubit RNA HS Kit, with the goal of sending RNA that meets sequencing facilities requirements for RNAseq. 

My first two rounds of samples on the qubit last week looked great in terms of the standards RFU output were as expected: Standard 1 ~80 and Standard 2 ~1750, which is consistent with last year's approx. standard readouts.

The qubit I've run this week using the same kit reagents had standard 1 readout of 80 RFU, but standard 2 was 150 RFU... and an error popped up on the screen saying there was a calibration error. I used a new aliquot of Standard 2 from the same kit for today's qubit, but the same error occurred. I ran the samples anyway since they were already ready and it used my good standards from the last week for calibration that were stored. 

I'm trying to figure out what could be happening. I use all reagents at room temp and once working solution is added, I cover with foil to protect from light, and I let the tubes incubate for 2 mins after vortexing before running with qubit RNA hs on the qubit machine, I make sure there aren't any bubbles in the tubes, I make sure lids are closed, I don't label the side of the tubes... 

Any thoughts on what I might try to fix this issue?

**Comment by kubu4** [comment]
I'd lean towards a mistake with the buffer/dye master mix.

Make a new buffer/dye solution and run standards again.

**Comment by grace-ac** [comment]
just ran standards alone and they looked great! so must have made some pipetting errors with the master mix on my last two rounds of qubit. thanks @kubu4 ! will re-run my samples with new master mix
