### ISSUE TITLE
List of genes expressed in geoduck single-cell library

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1607]
Where would I find this?

**Comment by mgavery** [comment]
https://docs.google.com/spreadsheets/d/1hM1M2Ekx1_v11Vs5iF1TK9qyOWBNJ5DQ/edit#gid=1974135280

shared with your UW email

**Comment by sr320** [comment]
I have that - is that not just top markers? I am looking for all genes present - in totality

**Comment by mgavery** [comment]
https://drive.google.com/file/d/1iWcSWNo0aZO_02oZgjzY7e0XVmZEo6wE/view?usp=share_link
