### ISSUE TITLE
Create exon expression table 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1609]
Using CEABIGR data - take one individual and create a table where row is genes, and columns are exon count data..(eg exon01, exon02, econ03 ....)

**Comment by kubu4** [comment]
I've finally gotten things figured out regarding formatting (thanks ChatGPT), but am realizing that the Ballgown exon tables aren't actually "expression" values (i.e. not FPKM or similar). Instead, the Ballgown exon expression tables only have read counts and variations/related stats (e.g. unique reads, mean coverage, coverage standard deviation).

Will read counts work for what you want to do, or should I see if I can calculate FPKM from the exon read count data?

**Comment by sr320** [comment]
read counts are fine.

**Comment by kubu4** [comment]
Alrighty, here's a link to the raw, tab-delimited file (~52MB):

- https://github.com/sr320/ceabigr/blob/main/output/19-exon-expression/S12M-exon_expression.tab?raw=true

It's organized by gene and has read count per exon per gene.

As requested, it's just for a single sample (S12M), but can be adjusted to handle all samples (obviously).

Here's the R Markdown file used to generate the file above: 

- https://github.com/sr320/ceabigr/blob/main/code/19-exon-expression.Rmd
