### ISSUE TITLE
Start NovaSeq de novo Assembly on Linux bird

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#161]

**Comment by kubu4** [comment]
Do we have an available toaster? Tried copying all files over last night and they filled up the internal HDD on Roadrunner.

**Comment by sr320** [comment]
Location of ns MP libraries: http://owl.fish.washington.edu/halfshell/working-directory/17-09-01/

**Comment by sr320** [comment]
Is there one connected to hummingbird

**Comment by kubu4** [comment]
Yes, but I think Jay is using Hummingbird for stuff, so don't want to pull it off of there.

**Comment by kubu4** [comment]
Do you just want the NovaSeq stuff assembled? I was actually going to create a massive scaffold of all the geoduck Illumina data (BGI, HiSeq, and NovaSeq). There actually might be enough space if we just use the NovaSeq data.

**Comment by sr320** [comment]
Just novaseq
