### ISSUE TITLE
Windows machine not running Rstudio on Raven?

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1616]
We are getting errors on Jupyterlab and raven Rstudio server instances from a windows machine that programs cannot be run... 

Why would your computer os matter for RStudio Server instance, any others have this issue?

**Comment by kubu4** [comment]
Any error messages and or screenshots which could be shared?

**Comment by kubu4** [comment]
Have different browsers been tried?

I access RStudio Server via Windows and haven't had any issues (using Brave Browser; haven't tried other browsers).

**Comment by sr320** [comment]
Getting mysterious errors related to Windows OS even when executing code in cloud instances Jupyter Hub and Raven.

When I try to execute bash code in RStudio

`~/sarahtanja/applications/ncbi-blast-2.13.0+/bin/blastx -h`
I get the error message 
`cannot execute binary file: Exec format error`

This [stackoverflow post](https://stackoverflow.com/questions/66970902/getting-the-error-bash-program-cannot-execute-binary-file-exec-format-erro) indicates this error is related to Windows OS not executing Linux applications... but that doesn't make sense for this because Jupyter Hub and Raven are Linux OSs...

**Comment by sr320** [comment]
nevermind - fixed=---- 

had installed mac program on jupyterlab and that what was throwing error

**Comment by kubu4** [comment]
Just to add, many programs (including BLAST) are already installed on `raven`. E.g.

`/home/shared/ncbi-blast-2.11.0+/bin`
