### ISSUE TITLE
Security certificate expired? 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1617]
Is it possible the security certificate expired on gannet...

code that work yesterday is now throwing

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL peer certificate or SSH remote key was not OK: [gannet.fish.washington.edu] SSL certificate problem: certificate has expired
```

have a work around thanks to ChatGPT

```
#reading in annotation table and saving as object
library(httr)
url <- "https://gannet.fish.washington.edu/seashell/snaps/uniprot_table_r2023_01.tab"
response <- GET(url, config(ssl_verifypeer = FALSE))
spgo <- read.csv(text = rawToChar(response$content), sep = "\t", header = TRUE)
```

but would be great to have cert back for easy read.csv

**Comment by kubu4** [comment]
Yep, it's expired. I have updated certificates for all three bird servers.

I'll try to get them updated in a bit.

**Comment by kubu4** [comment]
I've added new certificate to gannet. Please test when you have a sec. Looks good to me when accessing files via web browser.

**Comment by kubu4** [comment]
All certificates for Eagle/Owl/Gannet have been updated for 2023.

**Comment by sr320** [comment]
throwing errors today ... 
```
ERROR: cannot verify gannet.fish.washington.edu's certificate, issued by ‘CN=InCommon RSA Server CA,OU=InCommon,O=Internet2,L=Ann Arbor,ST=MI,C=US’:
  Unable to locally verify the issuer's authority.
To connect to gannet.fish.washington.edu insecurely, use `--no-check-certificate'.
```

**Comment by kubu4** [comment]
Which command(s) is throwing that error?

**Comment by kubu4** [comment]
`wget`?

**Comment by sr320** [comment]
curl and wget throwing errors .. note I am able to get around with relevant flags to ignore security,

**Comment by kubu4** [comment]
Thanks. Looking into it...

**Comment by sr320** [comment]
Not a priority - as can work around just providing FYI..

**Comment by kubu4** [comment]
This is now resolved with the help of CoE IT. Required an intermediate certificate (not clear why this hasn't been needed previously), but certificate errors from `wget`/`curl` are resolved.
