### ISSUE TITLE
Photo of NOAA qPCR machine and property tag

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1618]
Hi!

NOAA is auditing their equipment and they need a photo of the qPCR machine (CFX Connect), as well as a photo of the property tag on the qPCR machine - barcode with code `CD0004175914`.

Could someone in lab please do this and send me the photos (or, post them here)?

**Comment by DoroLar** [comment]
![Image of NOAA ](https://user-images.githubusercontent.com/110635215/229915276-d18b0960-2fa3-4a5c-8f64-245d66b9befa.jpg)

**Comment by kubu4** [comment]
Thanks! Could you please take a close up of the bar code, too?

**Comment by sr320** [comment]
would this work or do you need higher resolution? https://d.pr/i/3oFy7X

**Comment by kubu4** [comment]
Don't know. NOAA just asked for picture of the barcode and a picture of the machine. They didn't indicate if barcode had to be scannable from the image.

**Comment by sr320** [comment]
Just send them that.
