### ISSUE TITLE
Confirm absence of sea star -80 box

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1627]
Just doing some QC and noted that in the freezer inventory sheet the following is not present - @grace-ac this makes sense?

```
Pycnopodia Exp. #1 2021-09-08 Grace Crandall, Alyssa Gehman, PSC, RNAlater (500ul) -80C	coelomocytes	sunflower sea star
location
13	4	5
```

**Comment by grace-ac** [comment]
i think that makes sense!! I also removed another box from rack 14 that i didn't remove from the spreadsheet, so i'll do that now. when i'm back at safs april 24th i'll confirm all my sea star boxes and the spreadsheet are correct
