### ISSUE TITLE
Add users to mox

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1629]
Please add the following users to mox...
```
zbengt
ocattau
scryan
sggarcia
cnmntgna
schulh2
skalleyc
stanja
cvaldi
jwinter2
yerrace
```

**Comment by kubu4** [comment]
Done.

They will now need to follow the instructions linked below to add Hyak/Mox in their computing services:

https://robertslab.github.io/resources/mox_Adding-a-User/
