### ISSUE TITLE
Access to Linux machine

### ISSUE THREAD

**Issue by jldimond** [RobertsLab/resources#163]
Unfortunately I spent all that time and energy trying to get dDocent to work on Hummingbird when the program is actually only designed to run on Linux. This was not made clear enough in the installation documentation. Sorry to have also wasted others' time with the troubleshooting issues. Ugh.

So I'd like to try the program on one of the Linux machines. Can someone provide me with a username and pw for one of the Linux machines (e.g. roadrunner or emu)?

**Comment by sr320** [comment]
I am going to assume srlab and the corresponding pw will work...

**Comment by jldimond** [comment]
Oh, shoot...I used robertslab instead of srlab! Nevermind...

But does anyone have a preference for which machine I use?

**Comment by sr320** [comment]
@kubu4 is playing with one of the.  just make sure someone else does not have a job running (ie `top`)

**Comment by kubu4** [comment]
I have stuff going on both, but you can use either one. Please install programs to /home/shared.

**Comment by jldimond** [comment]
@kubu4 , can you help me figure out how to install miniconda to /home/shared? This is what I have tried:
```
Miniconda2 will now be installed into this location:
/home/srlab/miniconda2

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/home/srlab/miniconda2] >>> /home/shared/miniconda2
mkdir: cannot create directory ‘/home/shared/miniconda2’: Permission denied
```

Apparently I don't understand how to properly specify a different location. I tried to create a test directory in /home/shared, and it will only work with `sudo`. But how do I use `sudo` at the installation prompt - it does not work, for example:

```
Miniconda2 will now be installed into this location:
/home/srlab/miniconda2

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/home/srlab/miniconda2] >>> sudo /home/shared/miniconda2
ERROR: Cannot install into directories with spaces
```
I will keep working at it but if you have any ideas, let me know! 
Thanks.

**Comment by jldimond** [comment]
This is on emu, by the way.

**Comment by jldimond** [comment]
OK, got it. Just have to `sudo` at the start of the installation:

`sudo bash ../srlab/Downloads/Miniconda2-latest-Linux-x86_64.sh`

**Comment by kubu4** [comment]
Glad you got it working.

However, I think you've stumbled across a more general issue:  requiring ```sudo``` to write to the ```/home/shared``` folder. This shouldn't be needed, based on the permissions shown (```users``` group has write permissions).

Additionally, I have recently installed programs in that folder without requiring ```sudo```; now I can't even create a single file.

Hopefully a restart will resolve this issue, but I won't restart it until no one's using it.

**Comment by jldimond** [comment]
I started a ddocent run - I'll let you know when it finishes.

**Comment by jldimond** [comment]
@kubu4, I'm done for now with analyses if you want to restart emu.
