### ISSUE TITLE
Coral RNA QC results

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1632]
@kubu4 Can you provide the recent QC report from Azenta?

**Comment by sr320** [comment]
thanks - are they asking for input for way forward?

**Comment by kubu4** [comment]
@sr320 - Some samples have low RIN score. Another sample has insufficient sample amount.

Proceed with sequencing, despite low RIN scores?

Send additional RNA for sample with insufficient RNA or skip it?

**Comment by sr320** [comment]
In reference to below...

they are doing both RNAseq and miRNA on same sample - is  this with respect to some portion?

They are asking for green light on per sample basis for both RNA-seq and miRNA?

![leg](http://gannet.fish.washington.edu/seashell/snaps/Monosnap_Sample.QC.report.of_30-789513166_230414063433.pdf_2023-04-26_11-14-13.png)

![pic](http://gannet.fish.washington.edu/seashell/snaps/Monosnap_Sample.QC.report.of_30-789513166_230414063433.pdf_2023-04-26_11-12-18.png)

**Comment by hputnam** [comment]
I called and discussed both with them before the QCd the samples. They asked I call back after I see the QC and speak with the project manager Sarah Cunningham. I will do that now.  My preference is to move forward with all of them given we were able to quantify the RNA for POR 76 with the qubit here at URI. If that is ok with you, I will call and walk them through the connection between the samples and the RNASeq and smallRNAs.

**Comment by sr320** [comment]
I agree that we should just move forward with all of them (or as many as possible)

**Comment by hputnam** [comment]
Just as a note, the main sample of concern for low quantity is POR-76.

**Comment by kubu4** [comment]
@hputnam and @sr320 . Just received this email from Azenta regarding two samples from sRNA-seq. I'm assuming go forward with sequencing and omit the two failed samples, but wanted to confirm.

> Hi Samuel,
> 
>  
> 
> I hope your day is going well! Our team completed library preparation for your small RNA-seq project. We attempted to create libraries from               POR-71-S1-TP2 > and POR-76-S1-TP2 at best effort but were unable to generate libraries from these two samples. Given this information, please let me know how you would like to proceed:
> 
>  
> 
> Option 1: Omit samples from processing
> 
> Option 2: Close project with charges for library preparation ($4,410)
> 
>  
> 
> We look forward to hearing from you!
> 
>  
> 
> Kind regards,
> 
>  
> 
> Sarah Cunningham, Ph.D.

**Comment by sr320** [comment]
yes - go forward

**Comment by kubu4** [comment]
Small RNA-seq data has arrived (project `30-852430235`). I've transferred and confirmed successful data transfer via MD5 checksums.

All files provided by Azenta are here (including MD5 checksum file for each FastQ):

https://owl.fish.washington.edu/nightingales/A_poculata/

HTML report:

https://owl.fish.washington.edu/nightingales/A_poculata/Azenta_30-852430235_Data_Report.html

**Comment by hputnam** [comment]
Thanks! @kubu4 Just FYI, these are not Apoculata, but Porites spp, Acropora pulchra, and Pocillopora spp

**Comment by kubu4** [comment]
Gah! Thanks. I'll be moving files around to get files into proper species directories! Thanks! I'll post updated links in this thread.

Plus, just got notification this morning that the regular RNA-seq data is ready for download. So, I'll get those downloaded as well...
