### ISSUE TITLE
Interested in helping with FFAR offspring data

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1638]
I would like to get involved and help with analyzing FFAR offspring data as we discussed at our "state of the lab" meeting. How would one get involved with this project?

**Comment by sr320** [comment]
draft -https://docs.google.com/document/d/1aIho7R27-cXpDpuRKlQY_p-3Bi7-HlZMNQcTtH_bigI/edit

repo - https://github.com/shellywanamaker/paper-GeoduckTransgen_var.pH

note I checked in with Shelly and she is happy to have assistance with this.
