### ISSUE TITLE
Volunteering to help and get involved with USDA project

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1639]
Matt - I would love to get involved and help with the USDA Pt. Whitney project. Let me know how I can be helpful!

**Comment by sr320** [comment]
Probably a good kick-off might be joining us out there early May for spawning? based on how that goes there will be a better feel for next steps.

**Comment by sr320** [comment]
A summary of progress to date at https://mattgeorgephd.github.io/tagview/#usda-srgarp-gigas-carryover

**Comment by AHuffmyer** [comment]
Great! I know the schedule can be hard to estimate, but do you have a range of days you expect spawning?

**Comment by sr320** [comment]
I believe the target is next week. @mattgeorgephd you have a day in mind. Wednesday works best for me.

**Comment by mattgeorgephd** [comment]
Next Wednesday works well for me!

**Comment by AHuffmyer** [comment]
Great! My calendar is crazy for next week but I could be out there from 8am-11am on Tuesday (the 2nd) and Wednesday (the 3rd) or after 2:30pm on Monday (the 1st).

**Comment by sr320** [comment]
Lets do Wednesday

**Comment by AHuffmyer** [comment]
I'll try to move some things around so I can stay longer that day!

**Comment by AHuffmyer** [comment]
I'm able to be out at Pt. Whitney anytime between 8am and 1pm Wednesday, looking forward to it! Let me know what time you'd like to start in the morning.

**Comment by mattgeorgephd** [comment]
I'll try and be out there at 8. The larval chambers will need a bit of setup. They are built but will need to be plugged in/calibrated. Will take probably two hours.

In the meantime, if you and Steven could assess broodstock ripeness then we can determine if we can go forward with spawn or delay.

**Comment by mattgeorgephd** [comment]
No practical experience, but I've read about it :). Matt H said he is up to help, although he is not as good as Nate who can apparently tell if they are ready by their hand weight.

https://marine-aquaculture.extension.org/wp-content/uploads/2019/05/Oyster-Hatchery-Manual.pdf

**Comment by sr320** [comment]
@mgavery or @ocattau might have a protocol for fertilization based on single-cell work

**Comment by mgavery** [comment]
[Oyster_fert_dev_dissociation_protocol.docx](https://github.com/RobertsLab/resources/files/11369459/Oyster_fert_dev_dissociation_protocol.docx)

**Comment by mattgeorgephd** [comment]
I'm available Wednesday (5/10) to try for a spawn.
