### ISSUE TITLE
Create tissue specific geoduck lncRNA expression matrix

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1642]
analogous to:
https://gannet.fish.washington.edu/Atumefaciens/20220323-pgen-nextflow_rnaseq-tissues/star_salmon/salmon.merged.gene_tpm.tsv

**Comment by kubu4** [comment]
Expression matrix is here:

- [transcript_count_matrix.csv](https://gannet.fish.washington.edu/Atumefaciens/20230504-pgen-lncRNA-expression/transcript_count_matrix.csv)

Looks like this:

    | transcript_id | ctenidia | gonad | heart | juvenile | larvae |
    |---------------|----------|-------|-------|----------|--------|
    | MSTRG.1.1     | 34       | 16    | 13    | 93       | 6      |
    | MSTRG.2.1     | 18       | 5     | 2     | 9        | 2      |
    | MSTRG.3.1     | 15       | 9     | 48    | 171      | 60     |
    | MSTRG.22.1    | 4        | 24    | 7     | 27       | 22     |
    | MSTRG.9.1     | 3        | 133   | 1     | 1681     | 245    |
    | MSTRG.11.1    | 88       | 123   | 77    | 144      | 95     |
    | MSTRG.12.1    | 3        | 81    | 12    | 47       | 50     |
    | MSTRG.25.1    | 6        | 47    | 8     | 0        | 1      |
    | MSTRG.27.1    | 4        | 79    | 9     | 12       | 4      |

Jupyter Notebook (GitHub):

- [20230504-pgen-lncRNA-expression.ipynb](https://github.com/RobertsLab/code/blob/master/notebooks/sam/20230504-pgen-lncRNA-expression.ipynb)

Jupyter Notebook (NB Viewer):

- [20230502-pgen-lncRNA-identification.ipynb](https://nbviewer.org/github/RobertsLab/code/blob/master/notebooks/sam/20230504-pgen-lncRNA-expression.ipynb)

---

Summary of process:

- Use tissue-specifc BAMs [from HISAT2 alignments](https://robertslab.github.io/sams-notebook/2023/04/26/Transcript-Alignments-P.generosa-RNA-seq-Alignments-for-lncRNA-Identification-Using-Hisat2-StingTie-and-gffcompare-on-Mox.html)

- Use ["canonical" lncRNA GTF representing all lncRNAs found across all tissues](https://robertslab.github.io/sams-notebook/2023/05/02/lncRNA-Identification-P.generosa-lncRNAs-using-CPC2-and-bedtools.html) as input to [`StringTie`](https://ccb.jhu.edu/software/stringtie/).

- Use [`StringTie`](https://ccb.jhu.edu/software/stringtie/)'s expression estimation feature to generate read coverage and expression (FPKM) for each lncRNA.

- Use [`StringTie`](https://ccb.jhu.edu/software/stringtie/)'s Python script (`prepDE.py3`) to generate tissue/sample-specific count matrix.
