### ISSUE TITLE
Ordering or making siRNA's, which one is recommended and how do you do it?

### ISSUE THREAD

**Issue by graceleuchtenberger** [RobertsLab/resources#1647]
Hi all,
I'm going to try to pilot some gene knockdown stuff this summer using siRNA's, where hopefully I can knock down some marine mussel foot protein expression and measure how strong the byssal threads are after that (paired with some gene expression of course). I've seen some papers where authors have ordered them from companies, but I've also seen people make and insert them with plasmids. **If I just want to test out knockdowns on one or two genes, do you think ordering them might be more economical (time wise, money wise, etc.)? Also, what company is best to order them from, or to order starting plasmid materials from? And what kind of siRNA should I order?** Each company seems to have multiple kinds of siRNA to order, and multiple companies have siRNA options. 
Thanks so much for your help,
Grace

**Comment by sr320** [comment]
@mgavery where did you order morpholinos?

**Comment by sr320** [comment]
I think IDTDNA is good resource https://www.idtdna.com/pages/applications/gene-knockdown

**Comment by mgavery** [comment]
GeneTools is the morpholino company

**Comment by sr320** [comment]
Find a couple of papers that do something similar (like from class) to
model- in terms of design here is one
https://www.mdpi.com/1422-0067/24/4/3661
-- 

Steven B. Roberts, Professor Associate Director - Graduate Program
Coordinator School of Aquatic and Fishery Sciences University of Washington
Fisheries Teaching and Research (FTR) Building - Office 232 1140 NE Boat
Street - Seattle, WA 98105 robertslab.info - ***@***.*** - @sr320
vm:206.866.5141 - cell:360.362.3626 schedule a zoom call:
https://d.pr/gsgxVJ

**Comment by graceleuchtenberger** [comment]
Thank you Mackenzie and Steven!
