### ISSUE TITLE
Need DNA Kit for Histology Blocks

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#165]
I need to extract DNA from some Oly gonad in histology blocks. I'm guessing I need this [PAXgene kit](https://www.qiagen.com/us/shop/sample-technologies/dna/genomic-dna/paxgene-tissue-dna-kit/#orderinginformation) (or at least that's what PAXgene indicates).  @kubu4 you extracted RNA from my Oly blocks last fall, any insight/advice?

**Comment by kubu4** [comment]
No real tips. Just gouge out the amount of tissue (grams) specified in the manufacturer's protocol.

For purchasing, follow the [wiki guide](https://github.com/RobertsLab/resources/wiki/Purchasing)
