### ISSUE TITLE
Coral lncRNA count matrix

### ISSUE THREAD

**Issue by zbengt** [RobertsLab/resources#1650]
I have my list of lncRNAs [here (merged_final_lncRNAs.gtf)](https://github.com/course-fish546-2023/zach-lncRNA/blob/main/output/merged_final_lncRNAs.gtf) from the conclusion of lncRNA discovery workflow [here](https://github.com/course-fish546-2023/zach-lncRNA/blob/main/code/09-count-matrix.Rmd).

What I want now is a count matrix of lncRNAs, using this GTF that lists the selected transcript IDs. I'm getting tripped up using StringTie to do this, since I have been doing everything with bash. @kubu4 I know you've already done this for geoduck in python, so just hoping you can help me translate what to do next from your previous work.

**Comment by kubu4** [comment]
Follow along with the steps in this Jupyter Notebook:

https://nbviewer.org/github/RobertsLab/code/blob/master/notebooks/sam/20230504-pgen-lncRNA-expression.ipynb

It's all done using Bash, so you don't need to do it in a Jupyter Notebook if you don't want to. A regular old Bash script will work.

The _only_ exception would when you actually generate the count matrix using the StringTie Python script `prepDE.py`. For that, (if you're wanting to do this in `R`/`RStudio`), then you'd need to use this command (like you do for your CPC2 chunk) before calling the `prepDE.py` cript:

 `eval "$(/opt/anaconda/anaconda3/bin/conda shell.bash hook)"`

Anyway, look through that Jupyter Notebook and then let me know if you have questions about specific sections.

**Comment by kubu4** [comment]
Also, I finally got things tweaked to run the entire pipeline (all the way through the count matrix) using a SLURM script. You can run this script on Mox:

https://github.com/RobertsLab/sams-notebook/blob/master/sbatch_scripts/20230505-pver-stringtie-Pver_genome_assembly_v1.0-isoforms-lncRNA.sh

You'll need to change the output directory to your own.

Also, for reference, it'll take about 10hrs to run on Mox.

Here's the output directory if you want to use/peruse it:

https://gannet.fish.washington.edu/Atumefaciens/20230505-pver-stringtie-Pver_genome_assembly_v1.0-isoforms-lncRNA/

Of course, you can also use that as a Bash script, too. Doesn't need to be run on Mox, but if you run it on a different computer, you'll need to change the paths to the programs to match those on whatever computer you're running it on.

And, on a related note, I've nearly figured out how to run this via a container. Once that's figured out, I could just share the container file with you and you'd be able to run the command on whatever computer you had (as long as it had the `apptainer` programs installed), and you wouldn't have to modify paths or anything like that!

**Comment by zbengt** [comment]
Thanks Sam! And running via a container sounds very cool! Would love to see how you did that. Sounds like a great way for us to solidify our pipelines for more widespread use.

**Comment by kubu4** [comment]
A brief overview of the containerization process:

https://robertslab.github.io/sams-notebook/2023/04/28/Containers-Apptainer-Explorations.html
