### ISSUE TITLE
Help needed transferring large files from Globus to owl

### ISSUE THREAD

**Issue by mattgeorgephd** [RobertsLab/resources#1654]
Hello! I have some large files that I need to get onto owl from globus. In previous issues (issue #914) it looks like people used the desktop app to download the files before adding them to owl. Given the file sizes I'm working with, this isn't an option on any computer I own (see picture below). Any suggestions would be appreciated!

![image](https://github.com/RobertsLab/resources/assets/70529576/2f1227b1-db01-41dc-aa9b-bef0e1f2370b)

**Comment by sr320** [comment]
I can do the transfer to UW desktop... wanna send me instructions / credentials in slack?
