### ISSUE TITLE
Gannet file links not working

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1659]
For a given webpage ...

https://gannet.fish.washington.edu/seashell/bu-github/deep-dive/D-Apul/data/Amil/ncbi_dataset/data/GCF_013753865.1/

why does clicking on given file eg 

https://gannet.fish.washington.edu/seashell/bu-github/deep-dive/D-Apul/data/Amil/ncbi_dataset/data/GCF_013753865.1/sequence_report.jsonl

give a 403 error?

**Comment by kubu4** [comment]
Permissions issue. You're currently the only user with access:

![image](https://github.com/RobertsLab/resources/assets/4514104/4de08b7e-39a1-4749-9698-8689b4cc547a)
