### ISSUE TITLE
ID method for Oly gonad diff. methylation analysis

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#166]
Need to determine which method to use to measure diff. methylation in my Oly samples. I am preparing 16 samples total (8 per treatment), but might not run them all.  I currently am not planning on targeting any genes, rather using the analysis to ID global differences and diff. methylated regions. 

What method is reasonable? I thought RRBS might be an option but according to [Kurdyukov 2016](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4810160/pdf/biology-05-00003.pdf) it's $2500/sample. I see [Jay](https://www.biorxiv.org/content/early/2017/03/22/119156) used EpiRadSeq on ~25 samples and was able to obtain SNP data, too. [Jiang 2016 paper](http://rdcu.be/FMIv) looked at gigas methylation between parent/offspring via fluorescent-labeled methylation-sensitive amplified polymorphism (F-MSAP), and @sr320 you also mentioned ELISA?

Note: if all goes as planned, I will want to analyze larval samples later on, which are frozen and will have much less tissue.  I presume it's best to use the same technique for both adult gonad and larvae, if possible.

**Comment by sr320** [comment]
Source of funding is relevant here. But MBD-BS is preferred - see https://yaaminiv.github.io/Virginica-MBDSeq/

Could also to MBD-seq (no BS)- in this instance reads are analyzed like RNA-seq. Might be able to get away with less sequencing depth. (reduce cost)
See https://d.pr/f/q65jJv . (MeDIP ~ MBD : just different Antibodies to pull down DNA)

First step regardless is HMW DNA..

**Comment by jldimond** [comment]
EpiRAD worked OK but for my next analyses I am shooting for MBD.
