### ISSUE TITLE
Location of Functional annotation of Crassostrea virginica genes

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1660]
Is there an annotation of eastern oyster genes somewhere?.. Specifically looking for a file with gene ontology.

**Comment by kubu4** [comment]
I don't think there is... Glanced through old notebook posts and don't see anything.

**Comment by yaaminiv** [comment]
I think I have a file...will find it later today

**Comment by yaaminiv** [comment]
Here's my old nb where I did some annotation for the first Cv gonad methylation paper: https://github.com/epigeneticstoocean/paper-gonad-meth/blob/master/code/12-blastx-to-GOslim.ipynb

Here's a link to a file with mRNA IDs and GOterms only: https://gannet.fish.washington.edu/spartina/paper-gonad-meth/analyses/2018-12-02-Gene-Enrichment-Analysis/_blast-sort.tab

Here's a link to mRNA IDs, GOterm, and Uniprot Accession: https://gannet.fish.washington.edu/spartina/paper-gonad-meth/analyses/2018-12-02-Gene-Enrichment-Analysis/_blast-GO-unfolded.tab
