### ISSUE TITLE
Getting partial header string out of fasta

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1661]
I have two cells derived from fasta header

full header 
```
lcl|NC_035780.1_prot_XP_022327646.1_1 [gene=LOC111126949] [db_xref=GeneID:111126949] [protein=UNC5C-like protein] [protein_id=XP_022327646.1] [location=join(30535..31557,31736..31887,31977..32565,32959..33204)] [gbkey=CDS]
```

primary 
```
lcl|NC_035780.1_prot_XP_022327646.1_1
```

the primary and I need converted to gene id eg `LOC111126949`.

So how do I pull out `LOC111126949` from the full header text?

**Comment by sr320** [comment]
For more context.... I am trying to annotate C virginica genes to GO.

**Comment by kubu4** [comment]
Haven't tested, but this is ChatGPT's solution:

```bash
line='lcl|NC_035780.1_prot_XP_022327646.1_1 [gene=LOC111126949] [db_xref=GeneID:111126949] [protein=UNC5C-like protein] [protein_id=XP_022327646.1] [location=join(30535..31557,31736..31887,31977..32565,32959..33204)] [gbkey=CDS]'

gene=$(echo "$line" | grep -o '\[gene=[^]]*\]' | grep -oP '(?<=\[gene=)[^]]*')

echo "$gene"
```

Explanation:

The first grep command extracts the portion of the line enclosed in square brackets and starting with [gene= up until the closing square bracket ].

The second grep command uses a positive lookbehind (?<=\[gene=) and a negated character class [^]]* to match the desired text after the equal sign until the next closing square bracket.

By running the above script, the value LOC111126949 will be extracted and stored in the gene variable. You can replace the line variable with the actual content of your file, and the script will process each line accordingly.
