### ISSUE TITLE
Generate transcriptome from iso-seq data

### ISSUE THREAD

**Issue by mattgeorgephd** [RobertsLab/resources#1662]
Project: [PSMFC-mytilus-byssus-pilot](https://github.com/mattgeorgephd/PSMFC-mytilus-byssus-pilot)

Background: We have tag-seq data from the gill and foot (feet?) of mussels (_Mytilus trossulus_) exposed to different environmental conditions. No genome is currently available for _M. trossulus_. Alignment of sequences with _M. edulis_ and _M. galloprovincialis_ genomes were poor (20-30%). Alignment with a _de novo transcriptome_ from publicly available _M. trossulus_ SRA data was also poor. We submitted pooled RNA from the gill and feet (run as separate samples, each on one SMRT cell) of all mussels used in treatments for iso-seq through [PacBio at UW](https://pacbio.gs.washington.edu/).

Here is the information from the PacBio website regarding iso-seq data:
1.  Data are grouped into folders by SMRT cell. Folders are named by the unique identifiers you supply for each sample. For each SMRT cell we provide the files from the entire raw data output folder, including all information required for de novo assembly.
2. Link to [table](https://pacbio.gs.washington.edu/documents/Raw_Data_files.pdf) describing folder contents
3. Raw reads in PacBio's BAM (subreads.bam) format.
4. All associated metadata files required for import of data into PacBio's SMRT Link software.
5. For sequencing projects where we provide additional secondary analyses, we will include a pdf report and the final output files for the specific analysis with all FASTQ and FASTA files compressed by gzip. SMRT Link, a GUI tool for analysis of raw PacBio reads, is available for [download](https://urldefense.com/v3/__https://www.pacb.com/support/software-downloads/__;!!K-Hz7m0Vt54!kUncc8SkyaD8sAydYfvWWpcTs3FBnsQVuzMRxt0kYOTZI_J58JkY4Sj_FjknkCyLte7xf-9CFXmSzFPM$) including the SMRT Analysis toolkit, which can perform de novo assembly and resequencing. 
6. PacBio also provides the latest pre-release versions of individual tools for command line use through [Bioconda](https://urldefense.com/v3/__https://github.com/PacificBiosciences/pbbioconda__;!!K-Hz7m0Vt54!kUncc8SkyaD8sAydYfvWWpcTs3FBnsQVuzMRxt0kYOTZI_J58JkY4Sj_FjknkCyLte7xf-9CFSqPizZ_$).

Looks like the place to start is trying to get SMRT link up and running and try and generate transcriptome...

**Comment by mattgeorgephd** [comment]
Useful information:
https://nf-co.re/isoseq

![](https://raw.githubusercontent.com/nf-core/isoseq/1.1.4/docs/images/Isoseq_pipeline_metro.png)

**Comment by sr320** [comment]
thanks - based on files they would have done "additional secondary analyses" - @mattgeorgephd do you know what this would be or what you asked them to do?

**Comment by mattgeorgephd** [comment]
Emailed them to ask. Looks like they run a pipeline to compute CCS, remove primers/concatemers, and convert to FASTA (left side of the above workflow).

**Comment by mattgeorgephd** [comment]
Pipeline that UW PacBio uses: https://github.com/ben-lerch/IsoSeq-3.0

![](https://cloud.githubusercontent.com/assets/12494820/11380910/c9775812-92ad-11e5-97e3-5c3849ce6fea.png)

**Comment by sr320** [comment]
@kubu4 can you give this a shot on Mox.. just let me know what file you want to start with and I will move to mox.. 

maybe the bam in the CSS folder? 

![files](http://gannet.fish.washington.edu/seashell/snaps/Monosnap_Stevens_Office_2023-07-10_09-33-54.png)

**Comment by kubu4** [comment]
If we're unable to get the actual parameters used by UW, then I think we should start with the `m64076_230426_223230.subreads.bam` file. Starting with that will allow us to start at the very beginning of the pipeline.

**Comment by kubu4** [comment]
Is there any way for me to browse the data that was sent? Specifically, I think I'd like to see manifest files (?) - or something that has the barcoding adapter sequences and primer sequences.

**Comment by kubu4** [comment]
Can you please upload the PDF report we looked at in the IsoSeq folder? Thanks!

**Comment by kubu4** [comment]
Okay, spoke with Katie at the UW PacBio facility (she acknowledged that she's _way_ behind on her emails).

The _de novo_ transcriptome is the `hq` (high quality) FastA in the IsoSeq folder _without_ a number. However, this is a combination of both tissues. If we want tissue-specific transcriptomes, we'll have to do some work on our end to get them.

With that being said here's a brief summary of why there are six "biosamples":

- Each RNA sample (gill, foot) gets an external and internal set of primers. The primers are called "biosamples". So, for two RNA samples, there should be a total of 4 biosamples.
- The foot RNA sample didn't generate sufficient cDNA to get enough reads, so a second round of cDNA synthesis was performed (and sequencing), which led to an additional 2 biosamples. Thus, a total of 6 biosamples for this project.
- Each biosample is then clustered - producing a `hq`  FastA file with the corresponding biosample number in the filename.
- The `hq` FastA with _no number_ is a union of all the other clustered biosamples.

NOTE: Katie indicated that the biosamples with a small number of clustered sequences (i.e. < 15,000) can be ignored. Unfortunately, I can't totally recall the rationale behind this - has something to do with the sequencing chemistry and primers... However, it's not clear if these biosamples were included in the `hq` FastA with _no number_. I suspect they were.

![PacBio summary metric table. Red "X" indicates biosamples that can be ignored.](https://github.com/RobertsLab/resources/assets/4514104/815d7627-5ef8-4924-a650-305a04039520)

**Comment by sr320** [comment]
At this point lets call the `hq` fasta as the transcriptome - I will get some basic stats for it.

**Comment by sr320** [comment]
added @ https://robertslab.github.io/resources/Genomic-Resources/#mytilus-trossulus
