### ISSUE TITLE
Hood alarm in 209 is going off

### ISSUE THREAD

**Issue by zbengt** [RobertsLab/resources#1664]
The hood alarm in 209 is going off (I assume from the power outage). Took this picture:

![IMG_8733](https://github.com/RobertsLab/resources/assets/91245841/36d1428b-b4ce-4233-b54e-d61cf298f3a3)

Figured I wouldn't touch anything until I ran it past someone who knows what they're doing.

**Comment by kubu4** [comment]
Stopped alarm by pressing "RESET" button.

Also, turned fan speed to "Low", since hood is not currently in use.
