### ISSUE TITLE
How to Install Git in Windows

### ISSUE THREAD

**Issue by Noahk22** [RobertsLab/resources#1666]
When I was trying to create a project in R studio using a github url, after I pressed version control I received the error message in the screenshot posted below. Can anyone recommend how to proceed?

![Screenshot 2023-06-29 132047](https://github.com/RobertsLab/resources/assets/137379415/60bd4e55-9e0a-4251-85fe-4971fd8097d2)

**Comment by kubu4** [comment]
Honestly, it'll probably be best to rely on using the installation of RStudio on Raven. I've [set up an account for you](https://github.com/RobertsLab/resources/issues/1668).

To access RStudio:

1. If off-campus, start Husky OnNet.
2. Visit the following URL: http:raven.fish.washington.edu:8787

- You can safely ignore the browser security warning.
3. Enter login credentials for Raven.

_However_, if you really want to integrate `git` and RStudio on your Windows computer, we'll be happy to figure that out, too! But, the solution proposed above is faster, easier, and more reliable (more storage than personal computers and significantly faster processors).

**Comment by sr320** [comment]
I agree

**Comment by sarahtanja** [comment]
I got it on my PC by following [this tutorial](https://support.posit.co/hc/en-us/articles/360049776974-Using-RStudio-Server-in-Windows-WSL2) from POSIT Support:
https://support.posit.co/hc/en-us/articles/360049776974-Using-RStudio-Server-in-Windows-WSL2
