### ISSUE TITLE
Download WGS Cod Data

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1669]
Will send credentials / instructions via email

**Comment by laurahspencer** [comment]
@sr320 or @kubu4 do either of you have the Novogene QC report of each sample DNA concentration/quality prior to library prep?  I don't see it alongside the raw data on [nightengales](https://owl.fish.washington.edu/nightingales/G_macrocephalus/H202SC23041287/)

**Comment by kubu4** [comment]
It's in nightingales:

https://owl.fish.washington.edu/nightingales/G_macrocephalus/H202SC23041287/02.Report_X202SC23041287-Z01-F001.zip

**Comment by kubu4** [comment]
Oh, sorry! Never mind!

That does not appear to have been included.

Usually that data is provided separately, prior to sequencing, to see if the customer wants to move forward or not. It's not usually provided with the sequencing data.

**Comment by laurahspencer** [comment]
Gotcha.  My guess is that either Steven or Ingrid received it and gave Novogene the go-ahead. Ingrid mailed the samples in, but Steven managed the billing.  I've emailed Ingrid to see if she knows!
