### ISSUE TITLE
RNA isolation - questions

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#167]
I am looking at this [protocol](https://github.com/RobertsLab/resources/blob/master/protocols/rna_isolation_rnazol_rt.md). 

I am not going to be using tissue. I'll be using crab hemolymph. 
Do I still need to do the mortar and pestle part of the protocol? 

Should anything else be adjusted because I'm not using tissue? 

I would like to a test run with some of the extra hemolymph samples we have sometime soon - tomorrow, Thursday morning, or next week...

**Comment by kubu4** [comment]
You should follow the manufacturer's protocol for isolating total RNA from cell cultures. 

To answer your question, no mortal/pestle should be needed.

**Comment by grace-ac** [comment]
Okay thank you! I found this on the mrcgene.com protocol for RNAzol RT:

C. Liquid Samples. Homogenize/lyse liquid samples using 1 ml of RNAzol® RT per 0.4 ml of a liquid sample. For processing a small volume sample, mix the sample with 1 ml of RNAzol® RT and supplement the mixture with water to approach the sample + water volume of 0.4 ml.
