### ISSUE TITLE
total RNA extractions Zymo Quick DNA/RNA Miniprep : inhibitor cleanup & purification

### ISSUE THREAD

**Issue by sarahtanja** [RobertsLab/resources#1670]
[QB23229_Eukaryote Total RNA Pico_DE04105615_2023-06-13_15-55-44.pdf](https://github.com/RobertsLab/resources/files/11911278/QB23229_Eukaryote.Total.RNA.Pico_DE04105615_2023-06-13_15-55-44.pdf)

I just got a message from the sequencing lab (UT Austin) that all 20 of my samples failed library prep despite normalized quantity and good quality RIN scores :cold_sweat:  

They said they've seen this before and it means there are some type of inhibitors in my samples and that I need to purify and clean up the RNA after extraction. 

The samples are adult coral fragments that were frozen on LN2, pestled on LN2, and run through a bead bashing step and a Zymo spin column extraction with a DNase I RNA Purification step. 

Looking for advice on how to purify RNA further, detect contaminants, and understand Bioanalyzer results.

**Comment by kubu4** [comment]
If you're able, can you please check samples on NanoDrop? 260/280 and 260/230 ratios will be very informative.

**Comment by yaaminiv** [comment]
I ran into this issue before with coral samples, and after talking with Zymo reps I tried their PCR inhibitor kit: https://www.zymoresearch.com/collections/onestep-pcr-inhibitor-removal-kits Definitely helped with inhibition but I had some bad RNA quality and couldn't sequence for other reasons (so I can't confirm that this will solve all your issues and get your samples sequenced).

If you used specifically Zymo products, it may be helpful to contact a rep and talk to them about the specific inhibition the facility is seeing!

**Comment by AHuffmyer** [comment]
I have not done extractions on adult coral tissue, but I will contact Putnam Lab folks to see if anyone has had this problem before!

**Comment by hputnam** [comment]
What species, Porites? We had this problem with inhibitor carryover in the extraction and could detect it in the nanodrop traces. I will look for our notebooks to see what we did to troubleshoot

**Comment by hputnam** [comment]
example extractions 

https://kevinhwong1.github.io/KevinHWong_Notebook/20201022-DNA-RNA-Extractions-Porites-July-Bleaching-Experiment/

tagseq posts
https://kevinhwong1.github.io/KevinHWong_Notebook/20201203-Tag-Seq-prep-for-Porites-July-Bleaching-Experiment/

https://kevinhwong1.github.io/KevinHWong_Notebook/20210121-Nanodrop-results-on-Tag-Seq-samples/

**Comment by hputnam** [comment]
“ Hi Heather,

Thank you for bringing this to our attention. We have two hypotheses for low purity issue: 1) natural phenol in the symbionts in the corals and 2) carry over from the kit.

In comparing the nanodrop results to some of those from our prior job (JA20267), it looks like our prior job prepped and sequenced ok, even though some of those samples also had low purity (supporting the hypothesis of carry over from the kit).
https://kevinhwong1.github.io/KevinHWong_Notebook/20210121-Nanodrop-results-on-Tag-Seq-samples/

In light of our limited samples and the success of the prior library prep even with some lower purity, we would like to move forward with library prep and sequencing. 

Please let us know if we can provide any further information. 

Thank you! ”

**Comment by sarahtanja** [comment]
Thanks you everyone for all the advice! These are whole adult fragments of Montipora, both skeleton and tissue. 

I modified (my protocol)[https://sarahtanja.github.io/quarto-blog/posts/dna-rna-extraction-protocol/] from open lab posts by Kevin Wong, Emma Strand, and M.E. Schedl from the Putnam Lab. I think the biggest deviations are: I crushed the whole fragment in LN2, used a bead-beating tube for 40 minutes to get at bacterial DNA for microbiome studies, and I incubated the proteinase-K digestion at 55C to speed it up. 

I am using the Zymo Quick-DNA/RNA miniprep kit (spin column to get both DNA and RNA from one sample). 

My new tasks:
Add One Step PCR Inhibitor Removal Kit clean-up 
Run Nandodrop

Thanks everyone... I will update this issue when I do the two steps above.

**Comment by sarahtanja** [comment]
Update! 

I got samples back this morning and ran them through the [Zymo OneStep PCR Inhibitor Removal Kit](https://www.zymoresearch.com/products/onestep-pcr-inhibitor-removal-kit) Yaamani suggested. 

Sadly, the Zymo OneStep PCR Inhibitor Removal Kit didn't so the trick. All of the samples had good 260/280 ratios of around 1.9, indicating there isn't protein contamination. But... they ALL have low 260/230 ratios, indicating contamination by salts.

| sample ID | ng/uL | 260/280 | 260/230 |
|-----------|-------|---------|---------|
| 1-CA2a    | 63.88 | 1.92    | 1.40    |
| 1-CH2a    | 26.87 | 1.97    | 0.79    |
| 1-PA2a    | 41.26 | 2.07    | 1.15    |
| 1-Ea      | 44.54 | 1.98    | 1.25    |
| 1-PH1a    | 30.24 | 1.97    | 1.64    |

This seems very similar to the Putnam Lab posts, and I suspect I'm dealing with kit carryover issues... possibly phenols, which seem to denature polymerases and reverse transcriptases according to [this paper](https://www.sciencedirect.com/science/article/pii/S0003269718312545).

It seems a possible solution is adding lysis buffer wash steps or adding ethanol washes....

As a note, my DNA samples from this same extraction process successfully went through PCR & library prep for 16S rRNA sequencing.

**Comment by AHuffmyer** [comment]
Hi Sarah! These 260/230 values are very similar to a round of extractions we did recently. You can see Jill's post about it [here:](https://github.com/JillAshey/JillAshey_Putnam_Lab_Notebook/blob/master/_posts/2023-07-25-MiniprepPlus-DNA%3ARNA-extractions-McapLarvae.md)

We added another round of washes to try to remove carryover salts but it didn't help. Last time I sent samples to UT Austin for TagSeq we had similar values and they didn't have a problem sequencing. I am going to contact them next week to ask them about this problem specifically and see what they require. I'll let you know what I find out.

**Comment by kubu4** [comment]
> they didn't have a problem sequencing

Agreed. We've almost always had "poor" 260/230 values (regardless of RNA isolation method), but we've never encountered any issues with any downstream usage (reverse transcription, high-throughput sequencing, etc).

Curious what UT Austin will have to say.

**Comment by yaaminiv** [comment]
Sucks that the clean up kit didn't solve your issue! I do agree with @AHuffmyer and @kubu4 about 260/230 values, but I've found UT Austin to be more picky than other facilities.

If you think you have an issue with phenols, can you use a phenol-free extraction kit? Phenol-free extraction kits are crucial for TagSeq, but it looks like you're doing RNA-Seq so perhaps this is a moot point.

**Comment by sarahtanja** [comment]
Some recent things I learned from emails with Zymo:

> - The Zymo Quick-DNA/RNA Miniprep Plus is a phenol-free kit  
> - Additional wash steps do not further help purify the sample (the wash buffer may in fact contaminate the sample if not fully centrifuged out of the column before elution.. aka residual buffer in the elution)
> - Increasing the volume of the last wash would not help further purify the sample, but risk leaving residual buffer in the elution

Zymo has suggested that I try TRI Reagent and the [Direct-zol DNA/RNA Miniprep](https://urldefense.com/v3/__https://www.zymoresearch.com/collections/direct-zol-rna-kits/products/direct-zol-dna-rna-miniprep__;!!K-Hz7m0Vt54!hR2-lkKEDNSp8jnMNOSVR-eH6FDvAmxFQ8SAc6nqkmfQy-HeMxMt7PXcmGztye4mcxtq1kZOth9DhA$) followed up with the [RNA Clean & Concentrator-5](https://urldefense.com/v3/__https://www.zymoresearch.com/products/rna-clean-concentrator-5__;!!K-Hz7m0Vt54!hR2-lkKEDNSp8jnMNOSVR-eH6FDvAmxFQ8SAc6nqkmfQy-HeMxMt7PXcmGztye4mcxtq1kbGQCmqcA$), which they say removes phenols. 

If phenols are not present in the kit, and they are what is contaminating/inhibiting my sample... they must be coming from the coral samples themselves? Is that what I'm learning here? 

I've reached out to UT Austin's GSAF but have not gotten a response. 
I'd really like to hear what Ariana finds out from her talk with them!

**Comment by sarahtanja** [comment]
Oh! And to clarify, I am trying to have these sequenced via TagSeq at UT Austin GSAF

**Comment by mattgeorgephd** [comment]
Here is the RNAzol + Direct-Zol [protocol](https://github.com/mattgeorgephd/USDA-SRGARP-gigas-carryover/blob/153fc74313f52a7d8075f3879c9e91ab902c8683/protocols/RNA_extraction_protocol_3.0.docx) we used for RNA extractions with whole juvenile oysters. I'm not sure if steps 13-15 are required, or if you can just skip to 16 (I think I saw one of @kubu4 's protocols that skipped precipitation). Reagent volumes will need to be adjusted per amount of starting material in accordance with each kits recommendations.

**Comment by sarahtanja** [comment]
12 new samples failed library prep again for TagSeq at UT Austin.

Samples all had:
260/230 values at ~1.8 
260/280 values at ~2.0

UT Austin GSAF checks 10% of samples with Bioanalyzer, and the 2 samples out of 12 checked had RIN scores of 8 and 9.

These samples were extracted with Zymo DNA/RNA mini prep, a phenol-free kit and purified with RNA clean & concentrator. 
I made modifications to the extraction to increase sample purity from guanidine salts, which became my top suspect for the TagSeq library prep failure.  

I've asked to meet with UT Austin to talk about options... possibly switching from TagSeq to RNA seq. Currently waiting to hear back from them...

https://sarahtanja.github.io/quarto-blog/posts/rna-woes/

**Comment by kubu4** [comment]
Thanks for updating us on this saga. So sorry this is a continuing problem. It's frustrating to do all that work and still have things fail.

When they say the samples failed library prep, are you able to provide what data/metric(s) they're using to make the decision that a library prep has "failed?" It'd be nice to see that data ourselves; not only for future reference, but to also form our own conclusions.

If it's any consolation, I love how your notebook is setup! Going to copy many things in my own Quarto notebook.

**Comment by AHuffmyer** [comment]
Hmmm so they failed because of high RIN scores? I thought RIN>7 was good... I have the same question as Sam - why exactly did they fail?

**Comment by kubu4** [comment]
> Hmmm so they failed because of high RIN scores? I thought RIN>7 was good

I think the facility was saying the samples failed _despite_ having good RIN scores.
