### ISSUE TITLE
Extract RNA from oyster experiment

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1674]
Extract RNA from oyster experiment / sampling on July 6 - (https://wp.me/p1QK1L-1tT)

There are 16 samples.
https://github.com/sr320/lsamp-2023/blob/main/data/sampling-data.csv

In -80 maybe? rack 12 or 13 column 2 / row 3..... (sorry did not doc properly) box should say 
"NOAH oysters"

We took ctendia and mantle - only extract ctnedia (gill) which is denoted with "*" on tube.

**Comment by sr320** [comment]
@AHuffmyer that would be great - but Sam is probably starting this in 1 minute :)

We will be doing more this summer.. I will be in tomorrow making cDNA if you are coming in (and maybe more RNA if needed)

**Comment by AHuffmyer** [comment]
Haha! Sounds great. I wont be in tomorrow but will definitely stay tuned for more opportunities this summer! Thanks!

**Comment by kubu4** [comment]
Done. Notebooks here:

Isolation:

https://robertslab.github.io/sams-notebook/2023/07/12/RNA-Isolation-C.gigas-Ctenidia-from-Noah's-Heat-Mechanical-Stress-Project.html

Quantification: 

https://robertslab.github.io/sams-notebook/2023/07/13/RNA-Quantification-C.gigas-RNA-from-Noah's-Heat-Mechanical-Stress-Project.html
