### ISSUE TITLE
Generate cDNA from Oyster poly IC pilot 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1675]
link to data sheet https://docs.google.com/spreadsheets/d/1VKN9vogT6q5IpOo-PoB9WNeFUT3k_BCQ8_P7_DY81oM/edit#gid=0

repo link - https://github.com/mattgeorgephd/USDA-SRGARP-gigas-carryover

**Comment by sr320** [comment]
location in -80 

> Either 4-4-4 or 5-2-4

**Comment by kubu4** [comment]
@mattgeorgephd - Would you happen to know what difference (if any) there is between these two tubes?
![PXL_20230719_195239304](https://github.com/RobertsLab/resources/assets/4514104/6cc9f0d4-44b1-423c-82ac-1f626a170f2b)

**Comment by mattgeorgephd** [comment]
Not sure. Date for T8 is listed as 4/26 - I think Grace L. and undergrads may have done that extraction. If I had to guess, I would say tube with larger volume is intermediary step they saved in case of poor quality column step, but you'd have to ask grace. Maybe run both on nano?

**Comment by kubu4** [comment]
Thanks. I'll ask Grace and report back.

**Comment by graceleuchtenberger** [comment]
Hi all, I'm not entirely sure what the difference is, but I'm guessing Matt's explanation is right. I think that the first one (with more liquid) may have been from the first half of the protocol (RNAzol), but the second tube with less liquid is from the end of the DNA spin column protocol, meaning it's the pure stuff.

**Comment by graceleuchtenberger** [comment]
Sorry, I thought we labeled them better. That's my bad.

**Comment by kubu4** [comment]
@graceleuchtenberger 

Can you explain the differences between these two tubes. It may be hard to see, but one is labelled `D2I` and the other is `D2`. The `D2` sample has a large volume and a white precipitate present. The `D2I` sample has a small volume, but is completely clear.

Are either of these RNA?

![PXL_20230721_174901439 MP](https://github.com/RobertsLab/resources/assets/4514104/1684490c-bf22-4701-967a-6583ea6f1838)


It seems safe to assume that `D2I` is the RNA, as it matches tube labeling in the sample sheet linked above.

However, the other samples I was going to process (`T1-MgCl2`, `T2-MgCL2`, `T8-MgCl2`, `T14-MgCl2`, and `T15-MgCl2` - as labelled in the sample sheet above) have tubes with small, clear volumes (presumably the RNA) that are labelled with just the `T#` designation - no `MgCl2` appended. Is it safe to assume these tubes are the RNA?

**Comment by graceleuchtenberger** [comment]
Yes, I would say so. If it's around 100 uL of clear liquid, then it's the final RNA product

**Comment by kubu4** [comment]
Alrighty, cDNA has been made. Stored in same -80<sup>o</sup>C box as RNA.
