### ISSUE TITLE
Identify option(s) for new Synology NAS server

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1678]

**Comment by kubu4** [comment]
Easiest (and cheapest) option is to get expansion unit:

[Synology RX1217; 12 bay](https://www.amazon.com/dp/B01K1JSNSU/?coliid=I1K4I7P9TA00EC&colid=VPHLBAPFD7NC&psc=1&ref_=list_c_wl_lv_ov_lig_dp_it): ~$1300

This would seamlessly integrate with Gannet and wouldn't require an additional DNS/URLs/logins/etc.

We should probably use the same 16TB HDDs that we already have in Gannet. Those are ~$260 each. If we filled up the expansion unit, that would be 12 x $260 = $3120.

Of course, we could start with less than all 12 and expand over time.

**Comment by sr320** [comment]
sounds good - Lets go with that option - 12 bay expansion and the 12 16TB drives

**Comment by kubu4** [comment]
Items have been ordered.
