### ISSUE TITLE
Permission issue on mox for samtools

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1679]
trying to run samtools.

getting `/gscratch/srlab/programs/samtools-1.10/: Permission denied`

tried the following 

```
sudo chmod 777 /gscratch/srlab/programs/samtools-1.10/


sudo chown -R sr320 /gscratch/srlab/programs/samtools-1.10/
```

both cases

`Operation not permitted`

**Comment by kubu4** [comment]
Mox doesn't allow the use of `sudo`.

In any case, when looking at permissions, everything looks fine:

![screenshot showing output of ls -l command for samtools](https://github.com/RobertsLab/resources/assets/4514104/cfeaa8a7-b290-47e4-9b47-b92a04af48a0)


What command did you try to run?

If I do:

` /gscratch/srlab/programs/samtools-1.10/samtools`

I'm presented with the options menu (as expected).

**Comment by sr320** [comment]
my bad 
I was trying to run

```
find *.bam | \
xargs basename -s .bam | \
xargs -I{} /gscratch/srlab/programs/samtools-1.10/ \
sort --threads 28 {}.bam \
-o {}.sorted.bam
```

when in fact I should have been running

```
find *.bam | \
xargs basename -s .bam | \
xargs -I{} /gscratch/srlab/programs/samtools-1.10/samtools \
sort --threads 28 {}.bam \
-o {}.sorted.bam
```

thanks!
