### ISSUE TITLE
Mic for Podcast

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#168]
Laura recommended the USB microphone the original Podcast issue #21 . I rented it from UW student technology loan program and it was so easy and is good quality.

### Does the USB Microphone (Samson Meteor Mic) have to be purchased from a specific vendor?

I found this on Amazon: [link to mic](https://www.amazon.com/Samson-Meteor-Studio-Microphone-Titanium/dp/B00FQE337M/ref=sr_1_3?ie=UTF8&qid=1517942668&sr=8-3&keywords=samson%2Bmeteor%2Bmic%2Busb%2Bstudio%2Bmicrophone&th=1)

It's $63.50 and you can get a 3-year protection plan for $3.32.

Here is a link to [my notebook from yesterday](https://github.com/grace-ac/grace-ac.github.io/blob/master/_posts/2018-02-05-Podcast.md) regarding the creation and publication of a podcast.

**Comment by sr320** [comment]
Go ahead and order. no protection plan..
no specific vendor required.

**Comment by sr320** [comment]
actually order 2
