### ISSUE TITLE
Recommend / add content for incoming lab member modules

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1680]
at https://github.com/RobertsLab/tusk/tree/main/modules

can be simple list of material or actual content. 

New qmd can be created.

**Comment by zbengt** [comment]
Content from environmental data science class that should be a pretty comprehensive start-up for using GitHub...

Creating a Github Account:
https://fish549.github.io/website/references/github_signup.html

Installing Git on Windows (we’ll get the Mac option too):
https://fish549.github.io/website/references/git_install_windows.html

Getting a personal access token (PAT):
https://fish549.github.io/website/references/github_pat_creation.html

Organization (Research Compendia)
https://fish549.github.io/website/lectures/week_01/lec_03_orgs_styles.html#1

Intro to using Github: https://fish549.github.io/website/lectures/week_02/lec_04_intro_github.html

Version control: https://fish549.github.io/website/lectures/week_02/lec_05_intro_git.html

Remote repositories:
https://fish549.github.io/website/lectures/week_02/lec_06_git_remotes.html

**Comment by sr320** [comment]
create a checklist of things need access to.. 
raven
slack
lab calendar
lab inventory 
mox
github organization
keys

**Comment by sr320** [comment]
Project management -
best practices
before collecting data
running code on dummy data - review with lab

have protocols 

resources for project management 
eg list of equipment - locations 
tools and equipment based on the questions trying to ask. 

alternative protocols.
