### ISSUE TITLE
Select primers for C.gigas polyIC qPCRs

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1686]
- VIPERIN
- some normalizing gene(s)

Anything else?

**Comment by sr320** [comment]
Viperin is priority

other include

srID | Primer | gene
-- | -- | --
1833 | Cg_IRF2_F | IRF-2
1832 | Cg_IRF2_R | IRF-2
1831 | Cg_DICER_F | DICER
1830 | Cg_DICER_R | DICER
1827 | Cg_cGAS_F | cGAS
1826 | Cg_cGAS_R | cGAS
1835 | Cg_SACSIN_F | SACSIN
1834 | Cg_SACSIN_R | SACSIN


and 

Interleukin-17

**Comment by kubu4** [comment]
Gah! Just realized I spaced and didn't run IL-17. In the meantime, here're results from yesterday's qPCRs:

https://robertslab.github.io/sams-notebook/2023/07/26/qPCR-C.gigas-polyIC.html

**Comment by kubu4** [comment]
Pinging @sr320 so that you see this - didn't want to put in Slack.

qPCR analysis is complete for the diploids. R Project here:

https://github.com/RobertsLab/code/tree/master/r_projects/sam/20230822-cgig-polyIC-qPCR

---

Code is here:

https://github.com/RobertsLab/code/blob/master/r_projects/sam/20230822-cgig-polyIC-qPCR/code/01-qPCR-analysis.Rmd

---

Figures are here:

https://github.com/RobertsLab/code/tree/master/r_projects/sam/20230822-cgig-polyIC-qPCR/output/01-qPCR-analysis/figures

---

## Box Plots (delta Cq)

Box plots of delta Cq (i.e. normalize to Actin). T-test identified only a single gene (marked with orange asterisk) as significantly different between Control/Injected: DICER

![boxplots comparing 6 different genes - orange asterisk above Cg_DICER indicates statistically different between Control and Injected](https://github.com/RobertsLab/code/blob/master/r_projects/sam/20230822-cgig-polyIC-qPCR/output/01-qPCR-analysis/figures/diploid.delta-Cq.boxplots.jpg?raw=true)

---

## Fold Change (2<sup>-(ddCq)</sup>)

Fold change in gene expression of Injected individuals, relative to control samples.

![Bar plots showing fold change for each gene. Value > 1 means "upregulated"; value < 1 means "downregulated".](https://github.com/RobertsLab/code/blob/master/r_projects/sam/20230822-cgig-polyIC-qPCR/output/01-qPCR-analysis/figures/diploid.delta-delta-Cq.fold-change.barplots.jpg?raw=true)

**Comment by sr320** [comment]
thanks - can you add to your notebook?

**Comment by kubu4** [comment]
Notebook:

https://robertslab.github.io/sams-notebook/2023/08/22/qPCR-Analysis-C.gigas-Matt-George-Poly-IC-Diploids.html
