### ISSUE TITLE
Viewing GitHub repo page views and downloads for last year in GitHub

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1687]
GitHub traffic will only show the page views, downloads, and traffic from the last 14 days on GitHub repos. Has anyone found a way to show this data over a longer period of time? I'm assembling some project metrics and would love to add repository views/download metrics.

**Comment by sr320** [comment]
maybe something like

https://docs.github.com/en/rest/metrics/statistics?apiVersion=2022-11-28

?

**Comment by sr320** [comment]
could get total commits / issues a la 
https://repo-tracker.com/track
see
https://d.pr/i/GeVgJT

**Comment by AHuffmyer** [comment]
Thank you! Repo-tracker is pretty cool and very useful. I haven't tried adding an API to Git before, I'll play around with it and let you know how it works.
