### ISSUE TITLE
peristaltic pump set-up to borrow? other suggestions?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1688]
Hi All! 

We're trying to filter 5 L of seawater through multiple different membrane sizes (0.8um and 0.22um). We have a peristaltic pump but the filter holders and tubing aren't currently working. 

We're looking for suggestions of something we can buy or borrow that would help us filter this much volume. 

We'll be processing around 50 samples (5 L /sample). 

Thanks!!

**Comment by sr320** [comment]
We have some metering pumps you could try... 
https://d.pr/i/fjzR1e

But sound like the filter holders and tubing is problem, not the pump? Or you just need more?

Suggest pre-filtering as much as possible

**Comment by grace-ac** [comment]
We're thinking the filter tubing is probably not air-tight... the water is not processing very fast without filters, and once filters are added, the water trickles out. 

Also the fuse just blew on the pump... 

Is there a different method that people use for large-scale filtration? Any equipment that anyone knows of that we could borrow?

**Comment by kubu4** [comment]
Can you post pic(s) of setup?

Also, what do you mean by this:

> the water is not processing very fast without filters

If not filters, how is the water being "processed?"

**Comment by grace-ac** [comment]
Without having filters inside the system - like just trying to get water through the system, we were able to get a little bit. But once the filters were put in place (in the blue filter holders in the video attached below) to attempt to actually filter a sample, the flow got even worse.   

Here's a video of some folks here trying it out the other day:       
[here](https://drive.google.com/file/d/1cp5QhEAiTQCFo7hZap5KAqS3wBwaXbnZ/view?usp=sharing)

**Comment by kubu4** [comment]
For reference, I know when the Friedman Lab did large scale filtering (liters), it took _hours_ to filter one "jug". Also, they were filtering via vacuum pump using large side-arm flasks.

**Comment by grace-ac** [comment]
maybe this link is better: [https://drive.google.com/drive/folders/1cSBbHYHemtBd5jUKTV5YJEtZD1mWEcNh?usp=sharing](https://drive.google.com/drive/folders/1cSBbHYHemtBd5jUKTV5YJEtZD1mWEcNh?usp=sharing)

**Comment by kubu4** [comment]
Thanks for video.

Have they done this before?

In my opinion, a peristaltic pump is not designed for this (maybe why the fuse blew?); it just doesn't generate enough pressure.

However, If you _have_ to keep trying the peristaltic pump, I'd recommend "priming" the tubing with water first, so there isn't any air in the tubing. That could help.

Regardless, the best approach is going to be vacuum filtering. It's much stronger and will go much faster. Since you're capturing two different filter sizes, you'd have to perform the filtering in two stages, which is a bummer.

**Comment by sr320** [comment]
@grace-ac your setup seems reasonable - maybe pumping too fast. It will take a LONG time. It was entire days at hatchery. As Sam mention you could trying vacuum - but key is patience and prefiltering best you can. I assume you ran through with freshwater with no problem and when you do raw seawater you run into issues as filters get clogged?

**Comment by sr320** [comment]
Also I just noticed your pulling the water with the pump??? I would push water through filters..

**Comment by grace-ac** [comment]
ah, ok. Yeah with freshwater, there was a little bit of flow, and then seawater was a trickle/nothing. 

we tried to push through the filter as well, and that helped a little, but i think it wasn't much of a difference. 

would something like this be a potential option?  We don't know if we can use it yet - the USGS folks aren't here, but we'll ask Monday.     
![IMG_5248](https://github.com/RobertsLab/resources/assets/14934314/3d9b806a-65aa-43ba-9e88-0e949a0c24bc)

**Comment by grace-ac** [comment]
I guess that photo isn't super clear... but I think there's a rubber stopper that goes in that bottle that has two holes in the top that would create a seal, and the water would go through it.... I don't know what it's called or exactly how to describe it... but the intern that's with us this summer was thinking that'd be a good option!

**Comment by grace-ac** [comment]
something like this I think is what Andrew (intern for the sea star work this summer) was thinking: [https://www.southernlabware.com/vactraptm-polypropylene-2l-red-bin-1-4-id-tubing.html?gclid=EAIaIQobChMI3bizytWygAMV7iOtBh2LXQlmEAQYAiABEgLM0PD_BwE](https://www.southernlabware.com/vactraptm-polypropylene-2l-red-bin-1-4-id-tubing.html?gclid=EAIaIQobChMI3bizytWygAMV7iOtBh2LXQlmEAQYAiABEgLM0PD_BwE)

**Comment by sr320** [comment]
@ChrisMantegna what did you use?

**Comment by ChrisMantegna** [comment]
We used these pumps - they have a both a vacuum side and a pressure side, so you could push or pull liquid depending on what you need. 
![image](https://github.com/RobertsLab/resources/assets/81385272/0eb748fd-493d-42aa-9ee4-04445fc243e2)
![image](https://github.com/RobertsLab/resources/assets/81385272/5e3d5a61-fd17-416a-9144-2f0d49749297)

**Comment by grace-ac** [comment]
Hey @ChrisMantegna ! Thanks for that info! We're hoping to do 50 samples, filtering 5 L of seawater for each, over the course of a month at different time points. 

If you have any cat numbers for any of those supplies or a general list of equipment that you used, that'd be very helpful! I only have experience filtering the 700ml for eelgrass eDNA most recently. 

Also, is this system something that's at Friday Harbor or at UW? If at UW, would be able to borrow? 

Thanks so much!

**Comment by ChrisMantegna** [comment]
No problem! It's all here at FHL- I'll grab numbers/ info/ pictures if there aren't any numbers, and put the list together tonight/ early tomorrow.

**Comment by ChrisMantegna** [comment]
Ok - turns out there are almost no real numbers on anything but the pump, and that number is in photo of the manual page. I have REU presentation run- throughs until after lunch, I'll run over to the stockroom and take pictures of the equipment after that.

**Comment by grace-ac** [comment]
ok! thanks so much Chris! So these supplies are owned by the FHL stockroom?

**Comment by grace-ac** [comment]
closing! we got our setup all figured out!!
