### ISSUE TITLE
Additional storage for Owl?

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#169]
We're using ~85% of the available space on Owl (~7TB remain).

Should we start considering acquiring another expansion unit to add to Owl?

**Comment by sr320** [comment]
I am leaning toward new unit.. 
Let me take a pass and try deleting some stuff..

**Comment by kubu4** [comment]
I added a high priority label to this. We've consumed 88% of Owl's space (~6TB still available).

This is still ample space, but we should likely consider getting a solution in place relatively soon to minimize the disruptions to people's current workflows.

**Comment by kubu4** [comment]
Rough pricing:

~$3000 - Synology blade
~$4800 - 12 x 10TB HDDs

We can shave this down by using smaller HDDs (decrease pricing by ~$1200/TB HDD size).

**Comment by kubu4** [comment]
Amazon S3 costs:

$0.023/month/GB (i.e. $23/month/TB)

Gets complicated to evaluate full costs over time, as the S3 option is dynamic, based upon storage being used. Early on, could be relatively cheap.

Also, not as easy to interact with - requires installation/usage of third-party command line tools to mount S3 drive locally (actually, there might be a web interface, too). Finally, there might be a bit of a learning curve in order to establish a publicly viewable/readable file index.

**Comment by sr320** [comment]
NAS probably makes sense; but I found this interesting:
https://itconnect.uw.edu/servicecategory/servers-and-storage/

**Comment by kubu4** [comment]
Hmmm, definitely interesting! Had no idea they had all of these options!

**Comment by sr320** [comment]
Agree- seems like it _might_ be worth assessing our real need/use case and
asking them what UW service they recommend and price...
the SAN caught my eye.

First pass:
Decent speed file transfer ability
Public file server

**Comment by kubu4** [comment]
Spoke to UW IT today, described our needs - they suggested this: 

https://itconnect.uw.edu/service/wfs/

Comes online later this month, but the support person described this as being designed to pretty much handle our exact situation (although, he's opening a ticket to confirm HTTP support).

Storage costs are $0.05GB/month (i.e. $50/month/TB).

**Comment by kubu4** [comment]
One big caveat I see with using a UW storage service is how would data migration be handled if the lab was no longer at UW? The NAS solution (and, Amazon S3) allows the lab to pick up and leave with all of its data.

**Comment by kubu4** [comment]
Never mind on the UW service; won't function as public file server.

**Comment by kubu4** [comment]
Here's one of the Synology blade options:

[Synology 12bay NAS RackStation RS3618xs (Diskless), RS3618xs](https://smile.amazon.com/dp/B07B2XD3R7/?coliid=I3PPCATNML0X8J&colid=VPHLBAPFD7NC&psc=1&ref_=lv_ov_lig_dp_it)
- $2600
- 12 bays
- quad core 2.4GHz
- 8GB RAM (upgradeable to 64GB)

[16GB RAM module](https://smile.amazon.com/dp/B01LJUOL4A/?coliid=I2Z8C8J3P4CXLX&colid=VPHLBAPFD7NC&psc=1&ref_=lv_ov_lig_dp_it)
- $360

**Comment by kubu4** [comment]
I'm not entirely sure what you're asking. It'd be fine with me if we upped it to 32GB of RAM. :smile: 

I guess the caveat with that would be that it'd be best to purchase the RAM modules in pairs. So, we should get two 16GB RAM modules. With that being the case, we'd just install both of them and leave in the existing RAM (guessing it's 2 x 4GB RAM modules), for a total of 40GB of RAM. 

Alternatively, there is an 8GB RAM module (for ~$210). We could get two of those and add them, for a total of 24GB of RAM.

**Comment by sr320** [comment]
Go ahead and get two 16GB modules - split cost of rack and ram: 66-3828
and 61-0221

**Comment by kubu4** [comment]
Cool. What about HDDs? How much initial storage do we want (remember that data will be RAID'd, so we'll only get about half the capacity of the HDDs)?

**Comment by sr320** [comment]
I suppose I was waiting on your recommendations :)
Maybe fill 6 bays? What is HDD unit size for our current system? maybe
makes sense to maintain same drive size?

**Comment by kubu4** [comment]
> What is HDD unit size for our current system?

Eagle: 3TB
Owl: 4TB
Owl expansion: 8TB

> maybe makes sense to maintain same drive size?

Sounds good.

Thinking about 6 x 4TB 7200RPM, 128MB cache [Toshiba's](https://smile.amazon.com/Toshiba-Performance-Desktop-Internal-HDWE150XZSTA/dp/B013JPKUU2/ref=sr_1_2?s=pc&ie=UTF8&qid=1524673125&sr=1-2&keywords=HDD&refinements=p_n_feature_keywords_two_browse-bin%3A6799355011&th=1): 

$113 x 6 = $678

**Comment by sr320** [comment]
I am thinking bigger- what about
WD Red 8TB NAS Hard Disk Drive - 5400 RPM Class SATA 6 Gb/s 128MB Cache 3.5
Inch - WD80EFZX

**Comment by kubu4** [comment]
I'd lean towards the 8TB version of the Toshiba I linked above. Same price as that WD Red, but is 7200RPM.

**Comment by sr320** [comment]
Sounds good
