### ISSUE TITLE
Two-Way ANOVA in R 

### ISSUE THREAD

**Issue by Noahk22** [RobertsLab/resources#1692]
I was hoping to run a Two-way ANOVA or another type of statistical analysis to compare my treatments. I have attached a link to my data on excel and pictures of my qPCR graphs below. Thank You!

[qPCR-poster-1.csv](https://github.com/RobertsLab/resources/files/12244143/qPCR-poster-1.csv)
![Screenshot 2023-08-02 125523](https://github.com/RobertsLab/resources/assets/137379415/76338428-8c84-4dcc-894f-3e4b1fe89543)
![Screenshot 2023-08-02 125531](https://github.com/RobertsLab/resources/assets/137379415/222f35bf-a084-45e7-abe8-3e527f761b51)
![Screenshot 2023-08-02 125539](https://github.com/RobertsLab/resources/assets/137379415/53bdd2c8-5938-4736-b49a-5bad7d0d440f)
![Screenshot 2023-08-02 125546](https://github.com/RobertsLab/resources/assets/137379415/75d701c1-1eda-4eea-9bd5-43387bce8f7d)

**Comment by sarahtanja** [comment]
[Topic 12 Two factor ANOVA Lecture 15 and 16.pdf](https://github.com/RobertsLab/resources/files/12254570/Topic.12.Two.factor.ANOVA.Lecture.15.and.16.pdf)
Here are some lecture notes for you on Two Factor ANOVA , there is R example code in there!
