### ISSUE TITLE
Jupyter & qiime | Best practices for integrated use?

### ISSUE THREAD

**Issue by sarahtanja** [RobertsLab/resources#1694]
Hello! I am starting a new workflow using qiime2 in a jupyter notebook on the raven server (accessed through a raven_tunnel).

I'm currently doing the following:
- sshing into raven via raven_tunnel
- activating qiime conda env: `conda activate qiime2-2023.5`
- opening jupyter lab inside qiime env: `jupyter lab --no-browser --port=9000`
- confirming the jupyter notebook is using the qiime2-2023.5 kernel
- executing qiime commands using `!qiime ` 

However, this doesn't allow me to do the Python API stuff (like use in-notebook visualization) ex... `from qiime2 import Visualization`

Wondering if other Jupyter & qiime users out there have a better workflow that integrates using qiime2 Python API... instead of the hacky way I'm doing it.

**Comment by kubu4** [comment]
Can you please describe what you're wanting to do (i.e. what commands you're wanting to run after the `import` command), and also provide any error message(s) you're encountering?

**Comment by sarahtanja** [comment]
HI @kubu4 ... I really just wanted to be able to use the `Visualization.load` command to look at the interactive visualization artifacts without having to download the large files and drop them into qiime2view. 

I think I may have solved my own problem... 

I recently did the following:
- ssh raven_tunnel
- conda activate qiime2-2023.5
- jupyter serverextension enable --py qiime2 --sys-prefix
- jupyter lab --no-browser --port=9000

And now I can execute Qiime2 Python API plugins with the Python3 kernel, and the Visualizations are showing up! 

My code is [2_import-sequences.ipynb](https://github.com/sarahtanja/coral-pae-temp/blob/main/analysis/microbiome/code/2_import-sequences.ipynb) 

What I was trying to ask was: When you use qiime & Jupyter do you start Jupyter inside the qiime2 conda env (like I am doing)? OR do you start Jupyter in base conda env, and use a qiime2 kernel?

**Comment by sarahtanja** [comment]
For posterity, I have a notebook post on how I am working with qiime2 in a jupyter notebook and how I set it up on the raven server:
[https://sarahtanja.github.io/quarto-blog/posts/conda-jupyter-start/](https://sarahtanja.github.io/quarto-blog/posts/conda-jupyter-start/)
