### ISSUE TITLE
R studio server access

### ISSUE THREAD

**Issue by shellywanamaker** [RobertsLab/resources#1697]
is it possible to renew RStudio server access for my UW NetID strigg?

**Comment by sr320** [comment]
you sure it is dead? IOW did you use VPN?

**Comment by sr320** [comment]
I just went in to provision Huskynet.. .you should get email soon

**Comment by shellywanamaker** [comment]
great, that worked so that I was able to download the software. i'll confirm R studio server access in a sec once I get this set up. Thanks!

**Comment by shellywanamaker** [comment]
Ok got it installed and tried to connect with my NetID credentials but I'm getting this message now
![image](https://github.com/RobertsLab/resources/assets/4720221/a626a3a5-9472-44e7-9154-7de312c65634)

**Comment by shellywanamaker** [comment]
when I click the link it just brings me [here](https://itconnect.uw.edu/tools-services-support/networks-connectivity/husky-onnet/)

**Comment by sr320** [comment]
You were just provisioned for HuskyNet, so it might take some time / day....

https://d.pr/i/XkYbKv

**Comment by shellywanamaker** [comment]
Ah ok.  I can check again later.

But wanted to document this step that confirmed my access after I accepted terms and conditions

![image](https://github.com/RobertsLab/resources/assets/4720221/4d6c3942-cf40-49ce-8f0a-846c780fa25f)

**Comment by shellywanamaker** [comment]
but on your end does it still show that I haven't accepted terms?

**Comment by sr320** [comment]
> but on your end does it still show that I haven't accepted terms?

nope it shows you accepted for HuskyNet (just not Google, which is not related)

**Comment by kubu4** [comment]
Try to change the server settings so that it's "all Internet traffic" instead of "UW Campus Network Traffic Only."

Not sure how to chan6it, but I know it can be done.

**Comment by shellywanamaker** [comment]
Just tried, there's a 'change server' button with a drop down and I selected 'all internet traffic' but I'm getting the same message I posted above 'need to use sponsored UW netID...'

**Comment by shellywanamaker** [comment]
i contacted UW IT about this because I'm still getting the same message. Will post an update once I get a response

**Comment by shellywanamaker** [comment]
Ok, figured it out with UW-IT help:

All the info is listed on this page but wasn't obvious to me: [https://itconnect.uw.edu/tools-services-support/networks-connectivity/husky-onnet/installing-configuring-and-using-husky-onnet/selecting-a-husky-onnet-server/](https://itconnect.uw.edu/tools-services-support/networks-connectivity/husky-onnet/installing-configuring-and-using-husky-onnet/selecting-a-husky-onnet-server/)

The main issue is that I am using a sponsored UW NetID and when you download and install Big-IP Edge client, the default servers listed are not available to sponsored UW NetIDs. These are listed under the button 'change server'. The default servers are called 'UW Campus Network Traffic Only' and 'All Internet Traffic' which is also the same names of the servers for sponsored accounts which is why it is a little confusing. The differences are the addresses. You can see the actual addresses within the client application by clicking 'view details' and click the 'Miscellaneous' tab. 

To add the server addresses for the sponsored UW NetIDs, you have to first remove the default addresses. And you do this by clicking 'change server' and clicking the red 'X' that is on the right side of the server name. Once you have deleted the addresses, you can type directly into the 'Select server:' text box. The two servers available to sponsored UW NetIDs are:

- UW Campus Network Traffic Only: https://dept-huskyonnet.uw.edu/spon
- All Internet Traffic: https://dept-huskyonnet-ns.uw.edu/spon

I believe that only the 'All Internet Traffic address' will work for connecting remotely (off campus). So for me, I just cut and paste 
https://dept-huskyonnet.uw.edu/spon into the text box and clicked next.
![image](https://github.com/RobertsLab/resources/assets/4720221/70b8a86e-d031-48ee-8372-d2d35e9c7f8a)

 Then I was prompted to enter my UW NetID and password. And it connected! 

Not a very straightforward or intuitive process but is listed (buried) under the steps for selecting a server on the UW IT page.

**Comment by shellywanamaker** [comment]
ok, now to log in to R studio server what credentials do I enter?

**Comment by kubu4** [comment]
It's the same as your login credentials for Raven.

**Comment by shellywanamaker** [comment]
hm...i'm not sure what it is.. sorry it's been a while
