### ISSUE TITLE
Trying to render interactive Jupyter Lab Notebooks in Quarto on Raven

### ISSUE THREAD

**Issue by sarahtanja** [RobertsLab/resources#1699]
I'm poking around trying to get my Jupyter Lab Notebook output (the cool interactive parts) published on my quarto blog. I recently tried downloading quarto to my user on raven:
```
(base) stanja@raven:~/sarahtanja$ ls
coral-pae-temp  programs  quarto-1.3.450-linux-amd64.deb  sarahtanja-coralRNA  sarahtanja-coursework
(base) stanja@raven:~/sarahtanja$ sudo dpkg -i quarto-1.3.450-linux-amd64.deb
[sudo] password for stanja: 
stanja is not in the sudoers file.  This incident will be reported.
(base) stanja@raven:~/sarahtanja$ 
```
... and it says I'm being reported 😬 
So... If anyone is wondering what that was about.. that's what it was about. 
I will update this thread as I figure out how to actually make this work.

**Comment by kubu4** [comment]
Hahaha! Reported!

Anyway, you don't have `sudo` permissions (only @sr320 and myself are allowed to potentially wreck the computer with the `sudo` command 😀).

See if you can find a way a way to install without `sudo` in your home folder. I'll also look into getting it installed for all users tomorrow at some point.

**Comment by sarahtanja** [comment]
Ok so I can't do it without superuser permissions :/

```
(base) stanja@raven:~/sarahtanja/programs$ dpkg --install quarto-1.3.450-linux-amd64.deb 
dpkg: error: requested operation requires superuser privilege
(base) stanja@raven:~/sarahtanja/programs$ 
```

**Comment by kubu4** [comment]
Right. You won't be able to use the Debian package thingy. Follow the instructions on this page for single-user install:

https://quarto.org/docs/download/tarball.html

**Comment by kubu4** [comment]
Alrighty, I've installed Quarto and it should be available for all users!
