### ISSUE TITLE
Send Oly histology cassettes off 

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#170]
I just read that the Oly tissues in histology stabilizer solution shouldn't be held for more than 4 weeks (in the fridge); my oldest samples have been in the fridge far longer, so it'd be great to get those sent off to the histology people.  @kubu4 are you available tomorrow or Wednesday AM to help me prep them for shipment?

**Comment by kubu4** [comment]
Yep, I'm available tomorrow. They'll need to be ready to ship by 2PM.
