### ISSUE TITLE
Running nf-core pipelines on Mox

### ISSUE THREAD

**Issue by shellywanamaker** [RobertsLab/resources#1703]
I'm trying to run nf-core pipelines from Mox and having a heck of time. I successfully ran the RNAseq pipeline back in [2020](https://shellywanamaker.github.io/375th-post/), but needed to upgrade things so am basically starting from scratch. I saw @kubu4  tried this last year and I'm wondering if it's possible for me to use your install.

>I have /gscratch/srlab/programs/nextflow in my path but when I run nextflow -v I get permission denied. Do I need to install >nextflow in my dir?
>
>@kubu4 : Looks like Steven installed it, so I can't change permissions. However, we all have execute permissions, so it seems like >it should work. What's the output of this command: which nextflow
>
>@shellywanamaker: /gscratch/srlab/programs/nextflow
>
>@kubu4: Use this nextflow install instead: /gscratch/srlab/programs/nextflow-21.10.6-all . That's the one that's currently in my >$PATH and I've used it successfully. This notebook entry has a script that I've run semi-recently:
>https://robertslab.github.io/sams-notebook/2022/09/21/BSseq-SNP-Analysis-Nextflow-EpiDiverse-SNP-Pipeline-for-C.>virginica-CEABIGR-BSseq-data.html. In regards to running a pipeline which requires a download step, you'll need to do that using a >"build" node on Mox. The "login" node (which is the terminal you get when you first login to Mox) and "build" nodes are the only >nodes which have internet access. When you actually run a job on an "execute" node, you will no longer have internet access.
>I'll link a notebook post detailing that aspect installing a Nextflow pipeline. Ugh. One sec...
>
>@shellywanamaker: i have used a build node on mox in the past but for running a regular nextflow job like with sbatch, you're >saying it will be offline?
>
>@kubu4: Correct. Execute nodes have no internet access. Here's a link to notebook with installation of a Nextflow pipeline from >nf-core: https://robertslab.github.io/sams-notebook/2022/03/25/>Nextflow-Trials-and-Tribulations-of-Installing-and-Using-NF-Core-RNAseq.html. The quick and dirty solution was install the >pipeline in a conda environment and do not install from a GitHub repo/release. Aaaaaand, this is where a computer nerd would >probably extoll the virtues of using containers... Get the container setup on your own computer and then just copy the container >file to Mox! Sounds simple, but it's also a pain. Of course, learning/doing it this way has long term benefits, but who has time >for all that crap?
>
>@shellywanamaker: I saw in your nb entry that it took 2 days to run. did you try running it with the 'base-srlab_500GB_node.>config' file or just the default .config file?
>
>@kubu4: that used the default .config file. The other config file you mentioned was the the RNA-seq nf-core pipeline..
>
>@shellywanamaker: got it. If the 'base-srlab_500GB_node.config' worked for the RNAseq analysis I'll try to specify it when I run >your EpiDiverse SNP code to see if it runs faster

EDITED BY kubu4 to add formatting to Slack convo.

**Comment by shellywanamaker** [comment]
Got the following error: 

Downloading nextflow dependencies. It may require a few seconds, please wait .. curl: (28) Failed to connect to www.nextflow.io port 443: Connection timed out  
31mERROR: Cannot download nextflow required file -- make sure you can connect to the internet

Alternatively you can try to download this file:                                                                                                                                                               https://www.nextflow.io/releases/v20.07.1/nextflow-20.07.1-one.jar                                                                                                                                                                                                                                                                                                                                                and save it as:                                                                                                                                                                                                /usr/lusers/strigg/.nextflow/framework/20.07.1/nextflow-20.07.1-one.jar

**Comment by shellywanamaker** [comment]
@kubu4 do you think I need to make my own conda environment? or maybe I just need to put something (java?) in my path?

**Comment by kubu4** [comment]
Please provide the command(s) you ran. Also, please let me know which node type you were using when you ran the commands (i.e. login, build, or execute).

**Comment by shellywanamaker** [comment]
linked my script in comment above and used execute node

**Comment by shellywanamaker** [comment]
I'm running it now but I think it's going to throw the same error because the slurm says 'Downloading nextflow dependencies...' and it's not going to be able to do that being offline. In theory, everything should already be downloaded in the conda environment 'epidiverse-snp_env' , correct?

**Comment by kubu4** [comment]
> In theory, everything should already be downloaded in the conda environment 'epidiverse-snp_env' , correct?

Correct...

**Comment by shellywanamaker** [comment]
here is the [slurm file](https://gannet.fish.washington.edu/metacarcinus/Nf-core_tests/slurm-4878782.out). I ran set -ex so every command called is printed. I ran the same script as above but commented out the -c so that it uses the default config file

**Comment by kubu4** [comment]
Actually, this might not be worth trying to troubleshoot for Mox usage. I'd recommend using Raven instead, as it has internet access, so we won't get hung up on this aspect of things like we do for Mox.

Link(s) to helpful code for running on Raven coming momentarily...

**Comment by kubu4** [comment]
Well, I actually haven't abandoned Mox just yet (primarily because my runs on Raven are poorly documented 😖 ).

I ran your script on an execute node (sans the line with `-c /gscratch/srlab/programs/epidiverse-pipelines/snp/config/base-srlab_500GB_node.config \`). It started running without issue:

![image](https://github.com/RobertsLab/resources/assets/4514104/56bb692a-4e4c-4a17-8b43-13745e3214dd)


So, I don't really have any other ideas why the script tries to download files when you run it.

**Comment by shellywanamaker** [comment]
i think it may have something to do with what's in my path versus what's in your path

**Comment by shellywanamaker** [comment]
sorry i mean bashrc not path

**Comment by kubu4** [comment]
> sorry i mean bashrc not path

Certainly a possibility, and I don't have another explanation.

But, we explicitly tell the computer paths to programs - this should take priority over whatever's listed in your `.bashrc` and/or your system `$PATH`. Eh, I don't know.

Ah, the joys of using Nextflow!

**Comment by kubu4** [comment]
Alternatively, I can get the job run for you if you'd like. I know it's not ideal, but could save some time/frustration.

Also, as an aside, it looks like I did a comparison of the default config file and the custom config file for the 500GB node. The default config file ran ~ 50% faster than when using the custom config file (skip to the "RESULTS" section): 

https://robertslab.github.io/sams-notebook/2022/12/15/BS-Seq-Analysis-Nextflow-EpiDiverse-SNP-Pipeline-for-Haws-Hawaii-C.gigas-BAMs-from-Yaamini-Base-Config.html

**Comment by kubu4** [comment]
Okay, I'm starting to remember. For some reason, the Nextflow report linked above truncates the path specified to run Nextflow.

The command was actually:

```bash
# Activate conda environment
conda activate /home/sam/programs/miniconda3/envs/epidiverse-snp-current

# Run Nextflow epidvierse/snp pipeline
/home/shared/nextflow \
run epidiverse/snp \
-c nextflow-docker_permissions.config \
-profile docker \
--input /home/shared/8TB_HDD_01/sam/analyses/20220715-olur-zr1394_all_trimmed-nextflow_epidiverse-wgbs/wgbs/bam/ \
--reference /home/shared/8TB_HDD_01/sam/data/O_lurida/genomes/Olurida_v081-mergecat98.fa \
--take 18
```

The `--take 18` aspect of the code is needed to tell the pipeline to process 18 BAMs. Otherwise, it [only processes 10 BAMs by default](https://github.com/EpiDiverse/snp/issues/6) (GitHub Issue).

**Comment by shellywanamaker** [comment]
> Alternatively, I can get the job run for you if you'd like. I know it's not ideal, but could save some time/frustration.
> 
> Also, as an aside, it looks like I did a comparison of the default config file and the custom config file for the 500GB node. The default config file ran ~ 50% faster than when using the custom config file (skip to the "RESULTS" section):
> 
> https://robertslab.github.io/sams-notebook/2022/12/15/BS-Seq-Analysis-Nextflow-EpiDiverse-SNP-Pipeline-for-Haws-Hawaii-C.gigas-BAMs-from-Yaamini-Base-Config.html

I'd really like to figure it out because the goal is to have it be reproducible. And that's really interesting about the modified config file taking more time than the default. I wonder why that is.

**Comment by shellywanamaker** [comment]
OK, I successfully got the epidiverse-pipelines/snp -profile test to run on Mox!

**Comment by sr320** [comment]
Awesome- you working on a notebook post to share the step-by-step tutorial with others? 😄

**Comment by shellywanamaker** [comment]
I started one but it's extensive so I was going to post here. but I will just organize the nb post better and add the link here
