### ISSUE TITLE
Genome browser for bivalves

### ISSUE THREAD

**Issue by Eric-Ess** [RobertsLab/resources#1706]
Looking for a genome browser that would have the pacific oyster. The one I am familiar with, [ensembl](https://useast.ensembl.org/index.html), does not have invertebrates. What do people use?

**Comment by kubu4** [comment]
Welcome! Great job posting your question to GitHub!

Out of curiosity, what are you looking to do with a genome browser?

With that said, many of us just browse genome features locally (i.e. on our own computers) using [IGV](https://software.broadinstitute.org/software/igv/).

However, the [Pacific oyster genome is hosted on NCBI](https://www.ncbi.nlm.nih.gov/genome/gdv/browser/genome/?id=GCF_902806645.1). NCBI has a ton of features for examining genomes. You can always give that a shot.

**Comment by Eric-Ess** [comment]
Using it to find the location of genes, get FASTA files, that sort of thing. NCBI works great, thank you!

**Comment by kubu4** [comment]
The Roberts Lab Handbook has an entire section dedicated to this story of things (Genomic Resources). Take a look there first.
