### ISSUE TITLE
Update personal info on website

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1707]
Specifically please edit the following page 

- https://github.com/RobertsLab/lab-website/blob/main/people.qmd

**Comment by sr320** [comment]
please note here when complete

**Comment by AHuffmyer** [comment]
Complete

**Comment by shedurkin** [comment]
I added myself (I think correctly) but the website still hasn't updated to show the change (been ~12hrs) -- can I assume that's a cache issue and it'll resolve itself?

**Comment by kubu4** [comment]
@AHuffmyer's changes also haven't been rendered. Odd...

**Comment by sr320** [comment]
I still have safety mechanism where I have to run code :) not automatic yet...

**Comment by sr320** [comment]
updated.. if interested here is what I run on ovid

```
mkdir temp
cd temp
git clone https://github.com/RobertsLab/lab-website.git
cd ..
cp -r temp/lab-website/docs/* .
rm -f -r temp
echo "now done"
```

**Comment by sr320** [comment]
ok sorry about that, forgot to pull locally, render, and push first.

In the future, I will trust folks to _render_, and push and will get git hooks to auto update..

updates 
live now 
https://faculty.washington.edu/sr320/people.html
https://faculty.washington.edu/sr320/dei.html

@meganewing still awaiting your people update..

**Comment by meganewing** [comment]
done -- thanks for the patience (first day off class/work in 4 weeks)!
