### ISSUE TITLE
Annotate Cod Genome

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1708]
https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_031168955.1/

**Comment by laurahspencer** [comment]
Ingrid contacted NCBI and it sounds like they have that genome in their annotation pipeline too

**Comment by sr320** [comment]
done https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_031168955.1/


@kubu4 could you add relevant files to handbook?

**Comment by kubu4** [comment]
Okay, links are up!
