### ISSUE TITLE
Blast and annotate cod transcriptome

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1709]
Using Uniprot-SwissProt and GO information

transcriptome:
http://gannet.fish.washington.edu/seashell/snaps/Gadus_macrocephalus.coding.gene.V1.cds

**Comment by sr320** [comment]
how is this going?

**Comment by shedurkin** [comment]
I was finally able to successfully run the code you added to the project-cod-temperature repo (03-transcriptome-annotation.Rmd), which looks to be analyzing this data file. Did you want me to try to write my own code for blasting, or run another transcriptome?

**Comment by sr320** [comment]
Just drop in url of Rmd here

**Comment by shedurkin** [comment]
https://github.com/RobertsLab/project-cod-temperature/blob/main/code/03-transcriptome-annotation.Rmd
