### ISSUE TITLE
Getting ready to try RNA isolation

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#171]
The [RNA Isolation protocol](https://github.com/RobertsLab/resources/blob/master/protocols/rna_isolation_rnazol_rt.md) calls for isopropanol. I do not see isopropanol in our MyChem inventory or Roberts lab inventory. Do I need to purchase?

**Comment by kubu4** [comment]
It's also called 2-propanol:

>Isopropanol (2-propanol) (SOP)

**Comment by grace-ac** [comment]
Ah, found it. I figured both names would be listed in inventory. Thank you!
