### ISSUE TITLE
Blast and annotate geoduck genes

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1710]
Using Uniprot-SwissProt and GO information

transcriptome: http://gannet.fish.washington.edu/seashell/snaps/Rphil-assembly_v4_NoCont.AGAT_predicted-proteins.fasta

**Comment by meganewing** [comment]
what's the file path for blastdb in raven? 

aka, what would be the raven version of this chunk? 
<img width="368" alt="Screen Shot 2023-10-24 at 1 14 30 PM" src="https://github.com/RobertsLab/resources/assets/66333757/0226b324-f529-469b-a6ee-1223353d8299">

**Comment by sr320** [comment]
/home/shared/ncbi-blast-2.11.0+/bin/blastx

**Comment by meganewing** [comment]
<img width="1418" alt="Screen Shot 2023-10-24 at 1 27 29 PM" src="https://github.com/RobertsLab/resources/assets/66333757/e5396b72-979f-449b-ae19-68d4b559114f">

saying no such file or directory but when I enter the file path into terminal and list its contents I can see it's there. any idea what's going on here?

**Comment by sr320** [comment]
Remember relative paths from class... your pwd is different in two cases.

**Comment by kubu4** [comment]
Basically, your Terminal tab is in a different location than your R console.

Switch to the Console tab (it's next to the Terminal tab) and enter the following:

```r
getwd()
```

This will tell you which directory R is currently in. This is where you'd need to start your relative path(s) from in your Bash chunk up above.

However, you could always specify the absolute path(s) to programs/files and avoid dealing with the differences between R and Bash working directories.

Does that make sense?

**Comment by meganewing** [comment]
my terminal and r console are showing the same wd:

terminal 
<img width="418" alt="Screen Shot 2023-10-24 at 3 18 12 PM" src="https://github.com/RobertsLab/resources/assets/66333757/eaf0310c-f0ee-4ef4-bdc4-dd2bcee1789a">

r console
<img width="458" alt="Screen Shot 2023-10-24 at 3 18 39 PM" src="https://github.com/RobertsLab/resources/assets/66333757/96ffecb9-86f5-4715-b9b6-7cf017056a5b">


and either way, I'm not super sure what the absolute path would be, but when I enter the relative path for the bin blastx is in directly into terminal, it shows me that it exits and the contents. So i'm not sure why when I put that same path into the chunk, its giving me the "no such file or directory" error
<img width="917" alt="Screen Shot 2023-10-24 at 3 21 50 PM" src="https://github.com/RobertsLab/resources/assets/66333757/04de0bac-2c8b-4d2b-b79f-13846f4ab370">

**Comment by kubu4** [comment]
Weird.

Anyway, absolute path (specifically for BLASTx) is this:

`/home/shared/ncbi-blast-2.11.0+/bin/blastx`

**Comment by kubu4** [comment]
Replace the contents of that Bash chunk with  the following:

```bash
pwd

echo ""
echo ""
echo "-----------------------"
echo ""

../../../ncbi-blast-2.11.0+/bin/blastx
```

Then, please post results.

When I run that chunk, it works for me:

![image](https://github.com/RobertsLab/resources/assets/4514104/a1a5515a-506c-4792-baef-974c58e022c5)

**Comment by sr320** [comment]
When you are using Rmd ... your current location is the directory your file is in... 

thus likely xxx/code

To verify this your run `pwd` in bash chunk in Rmd file.

**Comment by sr320** [comment]
> When you are using Rmd ... your current location is the directory your Rmd file is in...

and for reference the Rmd file has to be saved.

**Comment by kubu4** [comment]
> and for reference the Rmd file has to be saved.

Interesting. In my test above, I hadn't saved the Rmd file yet. But, I _had_ used `setwd()` to match @meganewing's, so I think all subsequent commands are run from that directory...

**Comment by sr320** [comment]
that would over ride, but ....

also for reference .. nobody should be using `setwd` in regular coding

**Comment by sr320** [comment]
It should never crash... We can look at in my office today before we go see Mac....

**can you provide a url to the Rmd file you are running code in as well as the line number of the chunk in question?**

**Comment by kubu4** [comment]
> how long should it take to run that chunk through raven?

Which chunk are you referring to? The last one I posted with the `pwd` command?

If that's the one you're referring to, it should be instantaneous.

**Comment by sr320** [comment]
any update?

**Comment by meganewing** [comment]
https://github.com/meganewing/2023-geoduckblast-tutorial
