### ISSUE TITLE
Format Quarto page header?

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1711]
@sarahtanja's notebook looks like this:

![Sarah's notebook page header](https://github.com/RobertsLab/resources/assets/4514104/1fda11a9-076b-4a34-a3bd-9aab6109e1ec)

How do I get the "second" heading that says "Posts?"

Her notebook repo is here, if that's helpful:

https://github.com/sarahtanja/quarto-blog

Mine just duplicate's the "Sam's Notebook"

![kubu4's notebook page header](https://github.com/RobertsLab/resources/assets/4514104/62edbd9b-950a-4146-ad05-610bb39946ba)

**Comment by sr320** [comment]
You set it in the header- 

See her qmd file: https://github.com/sarahtanja/quarto-blog/blob/main/index.qmd

**Comment by kubu4** [comment]
Ah! The main index.qmd! Thanks!
