### ISSUE TITLE
Graph / Evaluate organism size and weight over sampling events

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1712]
plot by temperature treatment.. 
determine if temperature influences growth..

data:
https://github.com/RobertsLab/project-cod-temperature/blob/main/data/temp-experiment.csv

can do analysis within repo.

**Comment by shedurkin** [comment]
I see there's already some existing code in the repo that seems to be doing this (titled Temp-Size-Graph-Box-Line.Rmd) -- do you just want me to generate my own code for this as practice? Do you want plotting with statistical tests (e.g. Tukey HSD)?

**Comment by sr320** [comment]
Yes - would like to see how you would do it and stats would be great..

**Comment by shedurkin** [comment]
Just push my finished code to project-code-temperature! It's saved in the code directory under "01_temp-size-analysis.Rmd"

**Comment by sr320** [comment]
Can you drop in a link to a url where we can view - eg knit to markdown, or even better,  a notebook post describing / showing code and graphs?
