### ISSUE TITLE
Confirm correct notebook links in handbook 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1715]
Please have a look at https://robertslab.github.io/resources/Lab-Notebooks

and confirm, add, review notebook links.

**Comment by shedurkin** [comment]
How can I add my lab notebook to the website? Do I need to find the code for it here on github and edit it directly? Not sure if I'm 100% confident in not messing up the site somehow...

**Comment by AHuffmyer** [comment]
Confirmed

**Comment by aspencoyle** [comment]
Confirmed

**Comment by grace-ac** [comment]
correct!

**Comment by zbengt** [comment]
Confirmed! If/when I migrate to quarto, I'll update it

**Comment by kubu4** [comment]
Mine is all good.

**Comment by ChrisMantegna** [comment]
Updated.

**Comment by valeste** [comment]
updated.

**Comment by mattgeorgephd** [comment]
Mine is good.

**Comment by graceleuchtenberger** [comment]
> How can I add my lab notebook to the website? Do I need to find the code for it here on github and edit it directly? Not sure if I'm 100% confident in not messing up the site somehow...

Same!

**Comment by kubu4** [comment]
On this page (https://robertslab.github.io/resources/Lab-Notebooks), click the pencil icon in the upper right (to the right of the "Lab notebooks" text).

![image](https://github.com/RobertsLab/resources/assets/4514104/29f46c6e-d846-483d-b3fe-fa6c0368aff4)

---

On the subsequent GitHub page, click the pencil icon.

![image](https://github.com/RobertsLab/resources/assets/4514104/b63f0326-7d08-4a6c-833f-c4a619826fde)

**Comment by sr320** [comment]
@meganewing pinging you on this...

**Comment by meganewing** [comment]
added my stuff! didn't render, but I think that's a you thing right?

**Comment by sr320** [comment]
Render and push on your end - then I will do last step

**Comment by meganewing** [comment]
done (I think)

**Comment by sr320** [comment]
my bad - no need to render on Handbook,

this comment only applies to website robertslab.info - I rendered your profile

**Comment by larkenr** [comment]
updated link
