### ISSUE TITLE
notebook page created but no "view page option"

### ISSUE THREAD

**Issue by meganewing** [RobertsLab/resources#1718]
okay so I got the notebook published from github desktop, but now I'm running into an issue getting the page to be viewable? In the [tutorial](https://sr320.github.io/course-fish521-2023/lectures/week_07/lec_06b_websites.html) there was a "view page" option that showed up, but I'm not seeing it. 

<img width="803" alt="Screen Shot 2023-10-03 at 11 21 02 AM" src="https://github.com/RobertsLab/resources/assets/66333757/5d5279f8-9409-438e-8c75-de9396e1047e">

also got this error email
<img width="548" alt="Screen Shot 2023-10-03 at 11 25 46 AM" src="https://github.com/RobertsLab/resources/assets/66333757/794ae853-464d-4b20-a331-34dc9a0b0e0f">

when i click "workflow run"
<img width="1406" alt="Screen Shot 2023-10-03 at 11 25 57 AM" src="https://github.com/RobertsLab/resources/assets/66333757/a38d5560-a388-472b-821d-20d4b846477e">

Is there something I'm doing wrong or should double check/am overlooking? I'm pretty sure I'm following the tutorial exactly and am running into more issues than I'd care to. 

Thanks!

**Comment by kubu4** [comment]
Looking at your notebook repo, you don't have any files in it (other than the README file):

![image](https://github.com/RobertsLab/resources/assets/4514104/b5947553-cd8f-448e-b7f6-f98fc432ad32)


Have you pushed your notebook to GitHub?

**Comment by kubu4** [comment]
Your repo on GitHub.com should look something like this (I have a couple of extra directories for file storage/organization), but you should still end up with a bunch of files and the `posts` and `docs` directories:

![image](https://github.com/RobertsLab/resources/assets/4514104/6118ebca-6757-4273-a69a-4744d5b82b12)

**Comment by sr320** [comment]
resolved - several issues identified, but did nuclear option and started from scratch.
