### ISSUE TITLE
Questions for RNA isolation 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#172]
1. How many samples should I try with? 
There are 254 "extra" samples. By "extra", I mean samples that I did not select to be included in the 14 pooled samples. 

2. Am I isolating "total RNA"?

3.  Is estimating the amount of RNAzol to use ok?
For context, I see that for liquid samples, you have to homogenize with 1 ml RNAzol per 0.4ml of sample. The hemolymph is in a sort of clump at the bottom of the tubes, and it is at different amounts across tubes. How important is it to be super accurate with the RNAzol:Sample ratio? 

4. Is it ok to use pestles and just regular snap cap tubes? Or are the specific pestle tubes required?

5. Do I make the 75% ethanol with 0.1% DEPC-treated H20?

**Comment by sr320** [comment]
How many samples should I try with?
There are 254 "extra" samples. By "extra", I mean samples that I did not select to be included in the 14 pooled samples.

> 2

Am I isolating "total RNA"?

> yes 

Is estimating the amount of RNAzol to use ok?
For context, I see that for liquid samples, you have to homogenize with 1 ml RNAzol per 0.4ml of sample. The hemolymph is in a sort of clump at the bottom of the tubes, and it is at different amounts across tubes. How important is it to be super accurate with the RNAzol:Sample ratio?

> estimate

Is it ok to use pestles and just regular snap cap tubes? Or are the specific pestle tubes required?

> yes

Do I make the 75% ethanol with 0.1% DEPC-treated H20?

> yes

**Comment by kubu4** [comment]
To add to @sr320 's comments:


> Is it ok to use pestles and just regular snap cap tubes? Or are the specific pestle tubes required?

Yes, but you won't need these. Follow the manufacturer's protocol for cells (or liquid; whatever it is). Cells will be disrupted via pipetting, not physical homogenization.

> Is estimating the amount of RNAzol to use ok?

Use 1mL of RNAzol RT per sample.

**Comment by grace-ac** [comment]
Okay great! Thank you. I'm going to try it out tomorrow, and root around today to make sure I know where everything is and such.

**Comment by sr320** [comment]
Root while you do :)

**Comment by grace-ac** [comment]
1. **What is meant by adding  "1 volume"?**
 
![screen shot 2018-02-13 at 3 26 22 pm](https://user-images.githubusercontent.com/14934314/36179754-7b5bedaa-10d2-11e8-81ff-8e8dba07d0f6.png)

2. **Is wet ice ok?** Or maybe not even necessary since I'm only trying out with 2 samples - I could just put directly into -80. 

3. **Link to notebook post detailing specifics of protocol for tomorrow - based on RNA isolation protocol in resources.** --> Link [HERE](https://github.com/grace-ac/grace-ac.github.io/blob/master/_posts/2018-02-13-RNA-isolation-protocol-for-tomorrow.md)

**Comment by kubu4** [comment]
1. It means add a volume of isopropanol equivalent to your sample volume.

2. Is wet ice OK for what? For short-term storage (i.e. a couple of hours), yes. Otherwise, -80<sup>o</sup>C.

3.
