### ISSUE TITLE
Hobo Software

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1720]
I am trying to download data from hobo temperature loggers. Do we have software, or do I have to purchase software to do this?

**Comment by sr320** [comment]
thanks!

**Comment by kubu4** [comment]
Also, for reference, we have software that we've paid for (including HOBOware) and licenses on Eagle:

`Backup/Software/<Mac/Windows>/`

**Comment by mattgeorgephd** [comment]
Hoboware Pro is required to use the docking station for the temp hobo loggers.
