### ISSUE TITLE
 transcribe this data into the Mussel Data Collection Sheet 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1721]
data sheet https://d.pr/f/CsdPwg

(note there might be some innovative ways in Excel to import) if I recall @DoroLar did something similar.)

**Comment by sr320** [comment]
@ChrisMantegna what GitHub should we be working in?

**Comment by sr320** [comment]
lets go with https://github.com/ChrisMantegna/WDFWmussels unless corrected.

**Comment by ChrisMantegna** [comment]
That’s correct. Thank you

**Comment by sr320** [comment]
@ChrisMantegna see issue to give us access. https://github.com/ChrisMantegna/WDFWmussels/issues/1
