### ISSUE TITLE
Add short RNA discovery methods

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1724]
for coral work at 
https://docs.google.com/document/d/1_6jNLAg32QQEMbhC3wtWHH4mXB5JsbKn1PiIpKWu90k/edit

also please be sure to add links to output in results.

**Comment by kubu4** [comment]
Mostly completed during today's meeting.

**Comment by shedurkin** [comment]
Added P.meandrina results with linked outputs for miRTrace, MirMachine, BLASTn(E-val=1000 and E-val=10), miRdeep2, and ShortStack
