### ISSUE TITLE
Downloading the cutadapt module on Raven / permission errors with running code on someone else's data?

### ISSUE THREAD

**Issue by graceleuchtenberger** [RobertsLab/resources#1726]
I ran some code from Matt to start the tag-seq alignment process (pretty sure we're aligning to a new transcriptome that members of the lab assembled). Here's all the QC and trimming code. For some reason when I try to run commands with Matt's data it says permission denied, so I've just been redoing the qc stuff in my own directory and it's worked well, but if you know how to deal with the permission issue let me know, because he's done all the QC already and has it stored in his Raven folder.

```{bash, engine.opts='-l'}
echo $PATH
```

# Download tag-seq data
I appear to have the raw data in .fastq files in my directory (in addition to the fastq.gz files), so I think this step worked and the next worked.

```{bash}
mkdir raw-data/
cd raw-data/
Â
wget -r \
--no-directories --no-parent \
-P . \
-A .fastq.gz https://gannet.fish.washington.edu/panopea/PSMFC-mytilus-byssus-pilot/20220405-tagseq/ \
--no-check-certificate

```

# unzip .fastq.gz files

```{bash}
cd raw-data/
gunzip *.fastq.gz

```

# Run fastqc on untrimmed files
```{bash}
mkdir fastqc/
mkdir fastqc/untrimmed/

/home/shared/FastQC/fastqc \
/home/shared/8TB_HDD_02/mattgeorgephd/PSMFC-mytilus-byssus-pilot/raw-data/*.fastq \
--outdir /home/shared/8TB_HDD_02/mattgeorgephd/PSMFC-mytilus-byssus-pilot/fastqc/untrimmed/ \
--quiet

```

# Run multiqc
```{bash}

eval "$(/opt/anaconda/anaconda3/bin/conda shell.bash hook)"
conda activate

cd fastqc/untrimmed/

multiqc .

```

# trim adapter sequences
**Here's where I'm getting stuck, I need to install cutadapt but I can't as I am not "the root." If I could run this code in Matt's folder then it wouldn't be an issue, because he has it installed (I also wouldn't even need to do this because he's done the QC already).**
```{bash}
mkdir trim-fastq/
cd raw-data

for F in *.fastq
do
#strip .fastq and directory structure from each file, then
# add suffix .trim to create output name for each file
results_file="$(basename -a $F)"

# run cutadapt on each file
/home/shared/8TB_HDD_02/mattgeorgephd/.local/bin/cutadapt $F -a A{8} -a G{8} -a AGATCGG -u 15 -m 20 -o \
/home/shared/8TB_HDD_02/mattgeorgephd/PSMFC-mytilus-byssus-pilot/trim-fastq/$results_file
done

```

```{bash}

# Before trimming
! wc -l /home/shared/8TB_HDD_02/mattgeorgephd/PSMFC-mytilus-byssus-pilot/merged-fastq/*.fastq

# After trimming
! wc -l /home/shared/8TB_HDD_02/mattgeorgephd/PSMFC-mytilus-byssus-pilot/trim-fastq/*.fastq

```

This is from when Matt put it all together.
```{r}
# Reads remaining after trimming and filtering (%)
1472899016/1582147952*100
```

# Run fastqc on trimmed files
**Haven't been able to do this yet b/c of the cutadapt/permissions issue.**

```{bash}
mkdir fastqc/
mkdir fastqc/trimmed/

/home/shared/FastQC/fastqc \
/home/shared/8TB_HDD_02/mattgeorgephd/PSMFC-mytilus-byssus-pilot/merged-fastq/*.fastq \
--outdir /home/shared/8TB_HDD_02/mattgeorgephd/PSMFC-mytilus-byssus-pilot/fastqc/trimmed/ \
--quiet

```

# Run multiqc on trimmed files
Haven't been able to do this yet b/c of the cutadapt/permissions issue.
```{bash}

eval "$(/opt/anaconda/anaconda3/bin/conda shell.bash hook)"
conda activate

cd fastqc/trimmed/

multiqc .

```

# Interleave sequences
Haven't been able to do this yet b/c of the cutadapt/permissions issue.
```{bash}

cd trim-fastq/

for filename in *_R1_*.fastq
do
# first, make the base by removing .extract.fastq.gz
  base=$(basename $filename .fastq)
  echo $base

# now, construct the R2 filename by replacing R1 with R2
baseR2=${base/_R1/_R2}
echo $baseR2

# construct the output filename
  output=${base/_R1/}.pe.fastq

  (interleave-reads.py ${base}.fastq ${baseR2}.fastq | \
  gzip > $output)
done

```

# concatenate fastq files by lane
Haven't been able to do this yet b/c of the cutadapt/permissions issue. 
```{bash}
mkdir merged-fastq
cd trim-fastq/

printf '%s\n' *.fastq | sed 's/^\([^_]*_[^_]*\).*/\1/' | uniq |
while read prefix; do
    cat "$prefix"*R1*.fastq >"${prefix}_R1.fastq"
    # cat "$prefix"*R2*.fastq >"${prefix}_R2.fastq" # include if more than one run
done

# I moved files to merged-fastq

**Comment by kubu4** [comment]
If this is code that he's run before, why do you need to run it? Aren't the files already available?

Also, I went ahead and installed `cutadapt` on Raven. You should be able to find it here:

`/home/shared/`

I'm away from my computer, so I can't remember the full path, but look in there for a folder called `cutadapt-venv` or something similar.

**Comment by mattgeorgephd** [comment]
Grace - I think we transferred the trimmed and concatenated files to your folder on raven for this reason; raven doesn't like when you try and use files that are in another users folder.

**Comment by graceleuchtenberger** [comment]
Oh right, I forgot, thank you! Hazards of having the meeting in the summer and then saying I'd do it two months later, my bad. I think I now know where all the trimmed and merged files are. I know Steven was saying in science hour that the hisat2 program wouldn't be the best choice for this though (and that's the next step in alignment), should I still run the alignment with it and the following code?

```{bash}
mkdir data
cd data/
curl -O https://owl.fish.washington.edu/halfshell/genomic-databank/Mtros-hq_transcripts.fasta
```

# create hisat2 index for trossulus transcriptome (took 25:13 min on Raven)
```{bash}

/home/shared/hisat2-2.2.1/hisat2-build \
-f /home/shared/8TB_HDD_02/graceleuchtenberger/PSMFC-mytilus-byssus-pilot/data/Mtros-hq_transcripts.fasta \
/home/shared/8TB_HDD_02/graceleuchtenberger/PSMFC-mytilus-byssus-pilot/data/hisat2_index_trossulus.fa 
# called the reference genome (scaffolds)

```



# Run hisat2 on trimmed reads (took 40 min on Raven)
```{bash}

mkdir hisat2_trossulus_sam/
mkdir hisat2_trossulus_bam/
cd /home/shared/8TB_HDD_02/graceleuchtenberger/PSMFC-mytilus-byssus-pilot/merged-fastq/

# This script exports alignments as bam files
# sorts the bam file because Stringtie takes a sorted file for input (--dta)
# removes the sam file because it is no longer needed
array=($(ls *.fastq)) # call the sequences - make an array to align
for i in ${array[@]}; do
       sample_name=`echo $i| awk -F [.] '{print $1}'`
	/home/shared/hisat2-2.2.1/hisat2 \
	  -p 48 \
	  --dta \
	  -x /home/shared/8TB_HDD_02/graceleuchtenberger/PSMFC-mytilus-byssus-pilot/data/hisat2_index_trossulus.fa \
	  -U ${i} \
	  -S /home/shared/8TB_HDD_02/graceleuchtenberger/PSMFC-mytilus-byssus-pilot/hisat2_trossulus_sam/${sample_name}.sam 
	  
	  /home/shared/samtools-1.12/samtools sort -@ 8 -o                /home/shared/8TB_HDD_02/graceleuchtenberger/PSMFC-mytilus-byssus-pilot/hisat2_trossulus_bam/${sample_name}.bam /home/shared/8TB_HDD_02/graceleuchtenberger/PSMFC-mytilus-byssus-pilot/hisat2_trossulus_sam/${sample_name}.sam
    		echo "${i} bam-ified!"
        # rm ${sample_name}.sam
done >> hisat2out_trossulus.txt 2>&1

```

# check % alignment from hisat2
```{bash}

grep "overall alignment rate" /home/shared/8TB_HDD_02/graceleuchtenberger/PSMFC-mytilus-byssus-pilot/merged-fastq/hisat2out_trossulus.txt
```

**Comment by sr320** [comment]
I suggest kallisto https://robertslab.github.io/resources/bio-Gene-expression/#alignment-kallisto-pseudo-alignment

using the new transcriptome.
