### ISSUE TITLE
Issues running bash code in RStudio

### ISSUE THREAD

**Issue by shedurkin** [RobertsLab/resources#1727]
I've been trying to through a lab tutorial that's written in an .Rmd file with bash code chunks, but haven't been able to run any of the bash code in it. After some digging it seems that my Terminal in RStudio, which works fine, is set to use Git Bash, while running bash code in the console is using WSL, which hasn't been running correctly on my machine. Does anyone have any idea how to change the "bash" path for RStudio console separately from the terminal? Google hasn't been very helpful...

For context I'm working on a PC (which requires separate software like Git Bash or WSL to run command line stuff) with the latest versions of Windows and RStudio. More details on trying to figure out the issue are in my recent lab notebook entries.

https://shedurkin.github.io/Roberts-LabNotebook/posts/Oct.%2011,%202023/

**Comment by sr320** [comment]
We can address - but in meantime use raven - (raven.fish.washington.edu:8787) 

Also can you be specific about "bash code does not work" (eg screen shots)

**Comment by shedurkin** [comment]
When trying to run a bash code chunk (e.g. ```{bash] pwd```) in the Rmd file, hitting the "play" button on the chunk to run it results in no output of any kind and the green progress bar on the left side of the code chunk never completes, which to me indicates it never ran in the first place. When I try to knit the entire document, I get an error (see screenshot below).
![Screenshot (210)](https://github.com/RobertsLab/resources/assets/89885240/911e80b0-1cef-4e44-b6bf-c3c835bfa2ae)

**Comment by shedurkin** [comment]
Ok I think I might've fixed it? I added the line 
```{r setup, include=T}
knitr::opts_chunk$set(engine.path=list(bash='C:/Program Files/Git/git-bash.exe'))
```
at the beginning of the doc and, while I still don't seem to be able to run some individual chunks, knitting the document works
