### ISSUE TITLE
help with sea star data entry

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1728]
Data entry from summer 2023 sea star wasting disease experiments! 

There are three projects from summer 2023, each with their own repository.

To start, please scan/take pictures of each data sheet and put into their respective directory in each project's repository:
1. Experiment FHW (Friday Harbor-raised stars vs. wild-caught stars): [project-pycno-FHW-2023/data/scanned_datasheets](https://github.com/grace-ac/project-pycno-FHW-2023/tree/main/data/scanned_datasheets)
2. Experiment MUSP (Multi-species): [project-pycno-multispecies-2023/data/scanned_datasheets](https://github.com/grace-ac/project-pycno-multispecies-2023/tree/main/data/scanned_datasheets)
3. Experiment REX (re-exposure): [project-pycno-REX-2023/data/scanned_datasheets](https://github.com/grace-ac/project-pycno-REX-2023/tree/main/data/scanned_datasheets)

From there, we can go over where the data entry will go once I figure that out :)

**Comment by Noahk22** [comment]
I'm sorry if I'm missing something but could you please point me in the direction to where I can access the data sheets.

**Comment by grace-ac** [comment]
Hi Noah! 

They're physical sheets that I have in FTR. I'll be on campus this afternoon and all day tomorrow. Will you be around? I can show you where they are/get them to you.

**Comment by Noahk22** [comment]
I will be in lab from 1-5 today and I can come in tomorrow from 9-11 or from 2-3!

**Comment by grace-ac** [comment]
Awesome! How about 1pm-ish today we can meet in FTR 132

**Comment by Noahk22** [comment]
Sounds great!

**Comment by Noahk22** [comment]
For me to upload the pictures to the repositories I think I need access. Do you mind giving me access to all the repositories. Thanks!

**Comment by kubu4** [comment]
If you want to learn a bit more about GitHub, you could take the complicated approach:

1. Fork each repo.
2. Add the files to each repo that you forked (the forked repos are yours now).
3. Initiate a Pull Request from the original repos.

With that said, it'll be much easier to wait until you have direct access to the repos. :)

**Comment by sr320** [comment]
Yes - please do wait for direct access- I would like that too.

**Comment by grace-ac** [comment]
yes of course! doing that for you all now

**Comment by grace-ac** [comment]
let me know if it worked!

**Comment by kubu4** [comment]
It worked.

**Comment by grace-ac** [comment]
Hi @Noahk22 -  I need to get the data sheets fixed to match our previous summer's, so if you could pause for now, I'll let you know once they're fixed/we can meet this week to go over!

**Comment by Noahk22** [comment]
Ok sounds good, what times would work for you to need early this week?

**Comment by grace-ac** [comment]
thanks @Noahk22 ! I have flexible time tomorrow between 2 and 5pm? Are you around then at all?

**Comment by grace-ac** [comment]
That works! does 2pm work ok for you?

**Comment by Noahk22** [comment]
Yes perfect!
