### ISSUE TITLE
Registering/Paying for SICB

### ISSUE THREAD

**Issue by shedurkin** [RobertsLab/resources#1729]
How does one go about registering and paying fees for a local conference? I looked through https://robertslab.github.io/resources/Purchasing-and-Reimbursement/ and saw an old github issue about how to submit for travel reimbursement, but it wasn't clear to me whether local conferences that don't require travel are handled the same way...

**Comment by sr320** [comment]
Great question. This could be done as a reimbursement using treq - https://treq.environment.uw.edu
as just registration it fall under non-travel reimbursement

**Comment by sr320** [comment]
And if you do not want to go that route -  see on the page you link to above on how to have UW pay directly for registration.

>Note that there are options to have UW directly pay for conference registration, if you can get an invoice from the conference When this is the case you would simply submit this invoice for payment with the "Pay an Invoice" option in Treq and not include in Travel Authorization / Reimbursement. Make sure you upload your invoice to the OneDrive folder associated with your request.

**Comment by shedurkin** [comment]
Ok apparently TREQ is currently undergoing "system modifications" and I can't get added to system for a bit. Instead I can register for SICB and then contact Jonas Louie to submit a reimbursement request on my behalf (invoicing apparently isn't an option). The information I'd need from you, @sr320 , to submit the request are below:


Budget Number, including the Workday Worktags associated with the budget
 
Attach backup documents granting you approval to use the budget.

**Comment by shedurkin** [comment]
bumping this info request
