### ISSUE TITLE
Questions for DNA isolation from paraffin 

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#173]
I'm prepping for lab work this week, following the [PAXgene Tissue DNA Kit](https://github.com/laurahspencer/O.lurida_Stress/blob/master/References/PAXgene-Tissue-DNA-Kit-Handbook.pdf) and have a few questions:

1.  Protocol calls for "disrupting and homogenizing tissue", instructions below. I don't see a homogenizer on our inventory list, but do we have one lying around?  Any other method you'd suggest? Although I see from @kubu4 's notebook that Sam used pestles to homogenize the Virginica tissue, however my tissue is fixed/embedded in paraffin, I'm presuming it requires more extreme measures. 

_Add one stainless steel bead (5 mm mean diameter) to each 2 ml processing tube, and place the tubes in the TissueLyser Adapter Set 2 x 24. Note: If no bead mill is available, alternatively, a **rotor–stator homogenizer** (e.g.k the TissueRuptor) can be used as an alternative. In this case, the **homogenization time has to be optimized, and the sample should not be homogenized completely since this can cause DNA fragmentation by shearing.**_

2. I can co-purify RNA with DNA using this protocol, if I wish to. I'm guessing no - however if I can without interfering with downstream steps/analyses, then it would make sense to do so in case I want to do tag-seq or something. Thoughts? 

3. Protocol requires [Xylene](https://www.carolina.com/specialty-chemicals-t-z/xylene-laboratory-grade-500-ml/898741.pr), which I will purchase unless I hear differently. (Note: we have Xylene Cyanol FF, but I believe that is for staining purposes, not a solvent).

4. Following @kubu and @yaaminiv 's notebooks, I'll need [Qubit™ dsDNA HS Assay Kit](https://www.thermofisher.com/order/catalog/product/Q32851) for quantification; I don't see this in inventory, but are there enough supplies left in the kit for 20 samples? 

5. Same question as 4, for [MethylMiner™ Methylated DNA Enrichment Kit](https://www.thermofisher.com/order/catalog/product/ME10025)

**Comment by kubu4** [comment]
1. Previously I've used an apparatus in the Friedman Lab. However, it's broken (it broke the last time I did this). We need an alternative.

3. We can borrow some xylene from Graham Young's Lab.

4. Yes, we have this. In 209 fridge. 

5. Short answer, probably need more. 

Long answer, depends on how many samples you're going to be processing and what starting amount of DNA you're going to be using for each sample.

**Comment by sr320** [comment]
Re: 1 - I suggest the Tissue Tearors (modified Dremel tools)

**Comment by kubu4** [comment]
Those are going to be too large for the volumes she'll be working with.

**Comment by sr320** [comment]
What about sonicator and pestle?

**Comment by kubu4** [comment]
Certainly a possibility, but haven't tried that before, so don't know how it will perform.

**Comment by sr320** [comment]
Lets try with extra sample

**Comment by laurahspencer** [comment]
FYI I found one to borrow from Jackie’s lab. Going to get trained on it
this afternoon.

**Comment by laurahspencer** [comment]
And by “one” I mean a homogenizer

**Comment by sr320** [comment]
Does it look like ours?

**Comment by laurahspencer** [comment]
TBD - I'm going over there at 3:30 today.

**Comment by laurahspencer** [comment]
![vwr-200-homogenizer](https://user-images.githubusercontent.com/17264765/36172119-bcef3c22-10b9-11e8-9041-dcdd4be834df.JPG)

**Comment by kubu4** [comment]
Looks like the Tissue Tearers we have, however, I do see that this can handle sample volumes as low as 30μL (assuming they have that tip attachment), which might be small enough.

**Comment by laurahspencer** [comment]
Jackie's homogenizer kit apparently is missing the smallest tip (5mm) - the next smallest (7mm) is too large to fit inside a 2mL tube safely.  Not sure when she'll get the small tip, but regardless she doesn't want it to touch any toxic substances (I use Xylene in a prior step). She said we could buy one, and share the it and the homogenizer motor.  Regardless, I can't use hers this week to test out my protocol, which I'd like to do, so ... 

I'll test the pestle/sonicator on a low/gentle setting. I'll test with some of my samples, unless @sr320  and Brent want me to use geoduck (?) tissue that's lying around?

**Comment by sr320** [comment]
Just use your samples - you can do small samples with our terrors.

**Comment by laurahspencer** [comment]
@kubu4, @grace-ac or @sr320 any idea where the tissue tearers are? I've poked around the labs (and inventory sheet) and don't see them.

Also, I need to incubate at varying temps while also shaking: 
![image](https://user-images.githubusercontent.com/17264765/36227020-8a8bb136-1184-11e8-8407-98fa250bc434.png)

Is it acceptable to put a heating block ontop of the Innova 2000 shaker?  Or is there another way/piece of equipment that ya'll use?

Thanks.

**Comment by grace-ac** [comment]
I am not sure that I know what a tissue tearer is...

**Comment by grace-ac** [comment]
Oh wait @laurahspencer check the metal table in 213 by the sink. I think those are the tearers

**Comment by laurahspencer** [comment]
FYI I found a shaker/incubator combo in Graham's lab which I hope to use, just waiting to hear back from him.

**Comment by kubu4** [comment]
If you can't use Graham's shaker (does it go to 400RPM?), you can use ours (assuming it goes to 400RPM...). It's in FTR 228.

**Comment by sr320** [comment]
Generally speaking we need to be using ours, and if we do not have
something we will likely purchase (within reason).

**Comment by laurahspencer** [comment]
Young lab's machine has max speed and temperature as 400rpm, 80C
Roberts lab's machine maxes at 500rpm, 60C
Kit says I need to go as high as 1400rpm, and 80C, simultaneously.

@kubu4 I checked out the PAXgene RNA isolation kit that you used on paraffin-embedded gonad tissue; it also requires high rpm (1400rpm, but only goes to 65C).  Your [notebook entry](http://onsnetwork.org/kubu4/2017/07/19/rna-isolation-olympia-oyster-gonad-tissue-in-paraffin-histology-blocks-2/) doesn't state any alteration to the kit protocol regarding the rpm. Did you use someone else's machine, or simply max out the rpm using ours?

**Comment by kubu4** [comment]
I used the Disruptor Genie (sans glass beads) that was used for tissue disruption. 

Thanks for catching that! I'll be updating my notebook to include that (important!) piece of info.

**Comment by laurahspencer** [comment]
I tested the protocol last night using the tissue tearor & Graham’s incubator/shaker, compromising the rpm for the appropriate temperature. Of course halfway through the process the shaker stopped shaking entirely- seemingly a component broke. I’m going to see if Emma can track down an appropriate machine in genome sciences. Or, if you need an excuse to purchase a neat machine, we could buy a thermomixer. Something like this: https://online-shop.eppendorf.us/US-en/Temperature-Control-and-Mixing-44518/Instruments-44519/Eppendorf-ThermoMixerC-PF-19703.html

I can’t confirm from the site what the temperature range is for this machine. I need as high as 80C. Looks like it goes up to 3000rpm, which is good.  

I ran out of time to run the assay to quantify- stored the elutant in the fridge and will quantify next Friday.

**Comment by sr320** [comment]
We have a vortexer inside an incubator that will work.

**Comment by kubu4** [comment]
Have you informed the Young Lab about their incubator/shaker? We probably should have a plan for repairing their machine in a timely fashion.

**Comment by laurahspencer** [comment]
Yes, I emailed Graham and Chris this AM. I’m hoping that it just needs a break/cool-down, but let them know that I can troubleshoot next Friday when I’m back in town.

**Comment by kubu4** [comment]
I'm inclined to think the drive belt broke (I went and listened to it - doesn't rotate, but can hear motor speed increase/decrease as speed dial is changed).

Technically, an easy fix, but probably a bit of a pain to get inside to put a new belt on.

**Comment by kubu4** [comment]
> We have a vortexer inside an incubator that will work.

NOTE: You will need to Parafilm the tops of your tubes to keep them closed during the shaking at such a high temperature.

**Comment by laurahspencer** [comment]
Thanks for diagnosing- that makes sense, also what I was thinking based on
the fact that the RPM dial shows the motor is running as speed increases,
but not transferring to the plate/tray.

Good tip!

**Comment by laurahspencer** [comment]
Quantified my test samples today, here are the results from 4 samples:

![image](https://user-images.githubusercontent.com/17264765/36712052-aed92f4e-1b3b-11e8-9000-d9ff8687e369.png)


I see that this is way lower than in [Sam's notebook with _virginica_ samples](http://onsnetwork.org/kubu4/2017/11/14/dna-isolation-quantification-c-virginica-gonad-gdna/), but according to [Aberg et al. 2017](https://www.ncbi.nlm.nih.gov/pubmed/28703682), MBD-seq performs equally well with 15ng DNA vs. >1ug. 

What do ya'll think?

**Comment by kubu4** [comment]
You should expect only 1% recovery post-MBD. It's likely you'll get more, but the kits are expensive, so it makes sense to only proceed as though you'll only recovery 1% from MBD. 

As such, there's currently only one sample from your test set that we'd expect to have sufficient DNA (going by the 15ng number used by those authors).

Additionally, despite what those authors used for MBD-seq library construction, we have to abide by minimum DNA requirements that are requested by the sequencing facility.

**Comment by kubu4** [comment]
There's also the issue of DNA integrity. DNA integrity still needs to be assessed, as it will determine sonicator settings for fragmentation to the desired size range.

**Comment by laurahspencer** [comment]
It sounds like I'll need to adjust my protocol regardless. There are some troubleshooting options in the kit handbook I'll use, as well as actually shaking at high RPM. I will do another test run with adjustments, and hopefully that's sufficient. Sounds like my goal should be at min. >10ng/ul. 

@sr320 tomorrow (Wednesday) can you show me that vortexer/shaker combo you referred to?  I want to make sure I use the right equipment, so I don't break anything again ... 

For DNA integrity: can anyone point me to the protocol you use to assess integrity?

**Comment by kubu4** [comment]
I can show you the Vortexer attachment and oven.

DANA integrity is assessed by running the samples on a 0.8% 1x TAE agarose gel.

**Comment by laurahspencer** [comment]
Re-ran protocol with 4 new samples (5-8) and a control. Adjustments did not improve DNA concentration: 
![image](https://user-images.githubusercontent.com/17264765/37185316-98d41a86-22f4-11e8-9133-8c79acfe0d02.png)

Adjustments to protocol included: 
  * Chopped tissue into smaller pieces  
  * Increased homogenization time to ~30 seconds  
  * Adding glass beads to sample during proteinase-K incubations  
  * Used our vortexer / oven. NOTE: the vortexer stopped working at 80C. I removed it from the oven, let it cool, and it started working again.   

Not sure what the next steps are for these gonad samples, open to suggestions.  I'll focus on the other tissue types for now.
