### ISSUE TITLE
obtain RNA-seq quote

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1731]
For Pacific cod samples. Providing core with tissue. 80 samples

**Comment by kubu4** [comment]
What type of tissue?

**Comment by sr320** [comment]
Liver
Gill

**Comment by kubu4** [comment]
> Providing core with tissue.

FYI, this is probably going to be difficult to find a place that will accept tissues as starting material.

**Comment by kubu4** [comment]
Yep, just submitted quote request!

**Comment by kubu4** [comment]
Azenta: $14,049 (turnaround time is estimated 30 days)

**Comment by sr320** [comment]
we are ready to send out samples, given calendar maybe we shoot to ship out on Dec 4.
