### ISSUE TITLE
obtain quote for iso-seq transcriptomes

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1733]
3 tissues.. 
Pacific Cod

https://pacbio.gs.washington.edu/

**Comment by kubu4** [comment]
> 3 tissues..

Does this equate to three samples? If not, how many samples? Also, they will only accept total RNA as starting material.

**Comment by sr320** [comment]
Yes, will likely make three samples (pooled within tissue) for transcriptomes.

**Comment by kubu4** [comment]
UW PacBio:

No quote yet. They have questions/recommendations that we should consider and get back to them.

> For the Iso-Seq project, it's always a tricker estimate for coverage. Are you looking to get a catalog of expressed genes/transcripts? Are there particular genes you're interested in that are known to be lower abundance or longer transcripts than average in your tissue of interest? If this project is on a timeline of the next month or two, I'd recommend running Iso-Seq on the Sequel II platform that should generate ~2.5-3.5M reads per SMRT Cell. For genome annotation purposes, 1-2 SMRT Cells of sequence, ideally split among a handful of tissue types, is typically used. For rare or long transcripts, you may choose to run a full SMRT Cell per tissue. If you're thinking about running this project in 2024, I'm expecting a new kit will be coming out from PacBio that will allow MAS concatenation of Iso-Seq cDNA that enables sequencing on Revio with much higher data yields (30-40M cDNA reads per Revio SMRT Cell) in which case I'd recommend generating cDNA from your three samples with cDNA sample barcodes, then pooling for MAS concatenation and one Revio SMRT Cell. I can give you a general idea of cost for the MAS but note that once the kit is released the price may change.

**Comment by kubu4** [comment]
UW PacBio:

Iso-Seq (3 samples on their own Sequel II SMRT Cells) = ~$9k
MAS-Seq (after Jan 2024) (3 samples pooled for concatenation) = ~$3k

**Comment by sr320** [comment]
Lets leave this open to remind us to follow up in January

**Comment by sr320** [comment]
@kubu4 can you follow up to see if the new technology is in place?

**Comment by kubu4** [comment]
Updated pricing:

> you're a UW customer, so the price is actually  $2,988.50,
