### ISSUE TITLE
obtain quote for methylation data 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1734]
60 oysters, 500MB genome size 
Ostrea chilienis 

open to options but want whole genome... 

could be BS, or alternative (New England Bio has enzyme method)
PacBio technology?
Nanopore technology?

**Comment by kubu4** [comment]
UW PacBio:

TL;DR: 60 oyster samples -> 8 SMRT Cells, 7 samples per SMRT Cell = ~$36k


Wall of text response from UW PacBio:

>Starting with your WGS projects (Cod and Oyster.) I want to make sure I clarify before we begin that the methylation signatures called onboard by Revio is currently limited to mCpG. At this time, cytosine methylation in other base contexts is not called. Typically this is a non-issue for human sequencing but depending on the organism of interest, this may be a limitation of the method. There may be post-acquisition analyses you could run (e.g. fibertools calls m6A modifications, and bacterial motifs can be called for 4mC and 6mA.) We can retain the raw kinetics information that could be used for post-acquisition analysis but this typically results in file sizes ~10X larger than files without the embedded kinetics.

> Typically we average 90 Gbp/Revio SMRT Cell, but based on past experience with marine invertebrates, I'd suggest revising that number down and I'll do my math with an 80 Gbp/SC expectation. In this case I'd plan to pool 6 cod samples or 7 oysters per Revio SMRT Cell (~23X coverage expected per sample). To save money and processing, I'd recommend pooling before size selection (3- or 4-plex per size selection pool) -- this way if topoff is necessary it limits the extraneous sequence that will be generated. We would need about 3-5 µg of high-quality extracted gDNA (peak size > 50kbp) per sample in order to begin. Unfortunately, we do not offer extraction services at this time. These are significant projects and we will have to work out a schedule for sample and data delivery. I'd generally say we should be able to process about 2 SMRT Cells worth of samples in about 3-4 weeks with proper scheduling and planning. 40 Cod samples -> 7 SMRT Cells, 6 samples per SMRT Cell = ~$29k; 60 oyster samples -> 8 SMRT Cells, 7 samples per SMRT Cell = ~$36k.

**Comment by sr320** [comment]
WGBS quote (Azenta, Macrogen, Zymo)

UW nanopore Center

**Comment by kubu4** [comment]
Azenta WGBS quote requested.

**Comment by kubu4** [comment]
UW nanopore quote requested.

**Comment by kubu4** [comment]
Zymo quote requestd.

**Comment by kubu4** [comment]
Macrogen quote requested.

**Comment by kubu4** [comment]
UW Nanopore quote: `$23,321.64` ($383/sample)

Could be significantly cheaper if we could reduce QC. QC for all 60 samples is ~`$7,600`...

[Estimate_NSC_0120.pdf](https://github.com/RobertsLab/resources/files/13170972/Estimate_NSC_0120.pdf)

**Comment by kubu4** [comment]
Zymo quote: `$21,120` ($353/sample)

[zymo-quote-4475-SamWhite.pdf](https://github.com/RobertsLab/resources/files/13177753/zymo-quote-4475-SamWhite.pdf)

**Comment by kubu4** [comment]
Updated (?) Zymo quote: `$29,988` ($500/sample)

[Zymo-Quote_QUO14529_1698254601734.pdf](https://github.com/RobertsLab/resources/files/13178002/Zymo-Quote_QUO14529_1698254601734.pdf)

This quote has twice as many reads per sample (120M/sample) compared to the previous quote. I think the quote in _this_ comment is the more accurate one, to get 20x coverage.
