### ISSUE TITLE
Access to Gannet

### ISSUE THREAD

**Issue by shedurkin** [RobertsLab/resources#1735]
Could someone help me get access to Gannet? :)

**Comment by meganewing** [comment]
also same pls!

**Comment by kubu4** [comment]
@meganewing - I've updated your PW and shared with you in Slack.

**Comment by kubu4** [comment]
@shedurkin - I've added you to Gannet. You should receive an email from the server providing you with a login link and instructions to change your password.

You can access your directory via any web browser (for viewing): https://gannet.fish.washington.edu/kdurkin1/

**Comment by kubu4** [comment]
@meganewing and @shedurkin - To access files via command line (via `ssh` or `rsync`), you'll need to use this path:

`/volume2/web/<your-directory>`

**Comment by kubu4** [comment]
Oh, one more thing. Give some thought on data organization on Gannet. Once folders/files are in place, you should not change them. Changing them will break any URLs that you (or other people) rely on for data access retrieval.

**Comment by shedurkin** [comment]
I unfortunately haven't been able to log in to Gannet -- the start-up email I recieved gave me a user and pwd, but the password was shown as a series of asterisks (*****) for some reason. I also tried requesting to change my password, but the instructions I was sent were for resetting the password for an admin account, and involved pressing a physical rest button on (I'm assuming) the physical computer...

**Comment by kubu4** [comment]
Check Slack for credentials.
