### ISSUE TITLE
Calculate Sample Size for cod RNA-seq 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1736]
https://bioconductor.org/packages/release/bioc/html/RNASeqPower.html

**Comment by shedurkin** [comment]
I've been looking at the documentation for the RNASeqPower package and there are several required parameters: sequencing depth, coefficient of variation, detectable expression/effect, alpha, power, and sample size. I'm assuming the standard alpha=0.05 and power=0.9, and I can run it for a range of detectable expression values. However, I'm not sure how to determine necessary sequencing depth or coefficient of variation. The package authors also published [an investigation of appropriate parameter values](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3842884/) for a few taxa, the closest to our cod data being zebrafish, so I could try some values recommended there. The other option would be to estimate appropriate values from our data but it isn't clear to me if we have the right kind of data for this -- the packages I've found that can estimate these values (DESeq2, edgeR) seem to require RNAseq data, which I don't think we have yet.

**Comment by sr320** [comment]
Go ahead an try with defaults, and 20x sequence coverage... 

Coefficient of Variation is probably the trickiest 🎃 - @laurahspencer do you have an estimated value for Coefficient of Variation for your cod RNAseq work?

**Comment by sr320** [comment]
@mattgeorgephd you done power analysis before? you have an example?

**Comment by mattgeorgephd** [comment]
Here is an example: https://mattgeorgephd.github.io/USDA-NRSP-8-gigas-rDNA-analysis-1/

The two parameters you will need to determine for your data are:

1. The standard deviation of your control group
2. The minimum difference that you would like to be able to detect between the control and treatment group

**Comment by shedurkin** [comment]
I just included a range of possible values fro both cv and depth, based on suggestions/estimations made by the RNASeqPower package authors
https://github.com/RobertsLab/project-cod-temperature/blob/main/code/04-RNASeq-sample-size.md
