### ISSUE TITLE
blast help

### ISSUE THREAD

**Issue by meganewing** [RobertsLab/resources#1737]
working through this on raven and running into two issues so far

1) been going through the workflow with the linked fasta file in [the tutorial](https://robertslab.github.io/tusk/modules/04-blast.html) (so as to reduce potentially variables causing errors) before using the actual link of interest. But when trying to switch over to the file/link of interest, I get this error.
<img width="725" alt="Screen Shot 2023-10-23 at 8 22 04 PM" src="https://github.com/RobertsLab/resources/assets/66333757/92bae5fd-65b0-4c4b-9ffb-dcbb6683db7c">

2) biostrings and the readDNAsequences function
<img width="628" alt="Screen Shot 2023-10-23 at 9 20 49 PM" src="https://github.com/RobertsLab/resources/assets/66333757/93ff294d-0706-482a-b3e8-3b3ebd521950">

was able to run up to the "running blastx" section from the tutorial locally last week with the tutorial file (the geoduck blast file was giving me the same error locally as it is now on raven), but now even locally the biostings/readDNAsequences stuff is giving me grief too. Any tips would be appreciated

**Comment by kubu4** [comment]
In Step 1,try replacing `http` in the URL to `https` and run the chunk again.

**Comment by sr320** [comment]
note - it would be best practice to comment on https://github.com/RobertsLab/resources/issues/1710

also good practice to provide url of code in question. (pushed to GitHub)


reason point 2
you can skip that chunk as it just plots chararactistics. 
but likely related to line 62, where you are loading a file from tutorial you do not have..

**Comment by meganewing** [comment]
the https worked, thank you! 

plot chunk still didn't work but I'll just skip since its not directly related to the blast task. thanks y'all :)
