### ISSUE TITLE
raven commit message

### ISSUE THREAD

**Issue by meganewing** [RobertsLab/resources#1739]
trying to commit from raven and the commit message box won't let me enter anything -- cursor doesn't even show up in it. not sure what's going on here ? 

<img width="376" alt="Screen Shot 2023-10-24 at 12 58 33 PM" src="https://github.com/RobertsLab/resources/assets/66333757/099cc58a-e220-4e77-8a46-7dea999b95c4">

**Comment by sr320** [comment]
Show screen shot of entire Rstudio and can you pull?

**Comment by sr320** [comment]
Also url for repo?

**Comment by meganewing** [comment]
https://github.com/meganewing/blast-tutorial

I can pull just fine (says "already up to date" which is expected)

<img width="1426" alt="Screen Shot 2023-10-24 at 1 11 47 PM" src="https://github.com/RobertsLab/resources/assets/66333757/602cf724-ff24-4ff9-965a-43f0cd42a0c2">

its also not showing all of the changes I've made since the last successful push so I'm not sure what happened with those.

**Comment by sr320** [comment]
Make sure you have files selected when you commit.

**Comment by meganewing** [comment]
I'm not sure what you mean. Is that different than staging them?

**Comment by kubu4** [comment]
Screenshot showing staged files (`.gitignore` and `01-blasttutorial.Rmd`) looks fine.

With those two files checked (like they are above), you are _not_ able to type a commit message?

Also, if it was me, I'd make sure I had everything saved, then end my R session (the orange power button in the upper right) and then start a new session.

**Comment by meganewing** [comment]
correct. 

saved and ended session, re opened, but still no dice :/

**Comment by kubu4** [comment]
In the Terminal tab, please enter the following and share screenshot:

```bash
git status
```

Thanks!

**Comment by meganewing** [comment]
<img width="442" alt="Screen Shot 2023-10-24 at 2 13 48 PM" src="https://github.com/RobertsLab/resources/assets/66333757/68ad0aac-dece-40f9-81f7-f90377154136">

**Comment by kubu4** [comment]
Huh. Okay. That matches what we're seeing in RStudio.

I say commit using the command line and maybe that'll fix things going forward?

So, in the Terminal, enter the following:

```bash
git commit -m "change to correct FastA"
```

After that, you should be able to push.

**Comment by meganewing** [comment]
<img width="570" alt="Screen Shot 2023-10-24 at 2 24 56 PM" src="https://github.com/RobertsLab/resources/assets/66333757/62238b83-3c30-49c3-9863-4001e225eb22">
<img width="1431" alt="Screen Shot 2023-10-24 at 2 26 50 PM" src="https://github.com/RobertsLab/resources/assets/66333757/88edf593-5c95-4593-a62d-48e24ca05545">

not super sure what the error messages mean, also I included the files in my git ignore file, so shouldn't it not be an issue when trying to push?

Also, if/when the push works, about how long does it usually take before its visible on github?

**Comment by kubu4** [comment]
>  I included the files in my git ignore file, so shouldn't it not be an issue

It depends on when you added them to the `.gitignore` file. If you committed them _before_ adding them to the file, then they will _not_ be ignored, because you've already told `git` to accept them.

>  how long does it usually take before its visible on github

It's "instantaneous." Once the push is finished, you can refresh the repo on GitHub and see all the files/changes.

**Comment by kubu4** [comment]
Dealing with trying to revert a repo back to the point _before_ committing large files is kind of a pain. Here's what I would do:

1. Copy the directories/files you want to keep to a different location on your computer. 
2. Delete the repository in its entirety from the computer.
3. Clone the repository from GitHub.
4. Copy directories/files into freshly cloned repo on computer.
5. Add any directories/files to the `.gitignore` file.
6. Go through the add/commit/push process for all files directories.

**Comment by meganewing** [comment]
Does that process change if I'm doing it from raven and not my local computer ?

**Comment by kubu4** [comment]
The instructions are for Raven, since that's the computer you've been working on.

**Comment by sr320** [comment]
take home - committed a file > 100mb - in this instance makes sense to delete local copy (raven) and restart.
