### ISSUE TITLE
Can we do a partial PO for sequencing using eScience budget numbers? 

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1740]
Hi Sam! I have a quote for RNAseq for some coral samples through Genewiz. $4875 of this cost will come from the eScience department from my postdoc award through their department and the remaining $3168 will come from the University of Rhode Island through my NSF OCE postdoc grant. 

My question is - can we generate a PO using the eScience budget numbers for the amount of $4875? I sent them the quote and they asked if someone from SAFS could generate the PO and use the eScience budget number. 

I will then obtain a separate PO for the remaining cost through URI. Here is the quote attached. 
[30-943303755.pdf](https://github.com/RobertsLab/resources/files/13136573/30-943303755.pdf)

**Comment by sr320** [comment]
I suggest they provide two quotes - one being for $4875

**Comment by AHuffmyer** [comment]
Thanks I'll work on that!

**Comment by AHuffmyer** [comment]
Ok I now have a PO with the split price reflected. What is the best way to get a PO using the worktag "GF136972"? Sidenote: our lab handbook doesn't have a purchasing section for POs, but that may just be because you can do it in Treq and I don't have access to that system.  

[30-943303755_R1.pdf](https://github.com/RobertsLab/resources/files/13170166/30-943303755_R1.pdf)
[price_split_azenta.pdf](https://github.com/RobertsLab/resources/files/13170176/price_split_azenta.pdf)

**Comment by sr320** [comment]
I will submit via treq

**Comment by sr320** [comment]
SR

**Comment by sr320** [comment]
in treq now.
