### ISSUE TITLE
Transcriptome annotation for PSFMC byssus pilot

### ISSUE THREAD

**Issue by graceleuchtenberger** [RobertsLab/resources#1741]
I know Matt said that you guys (Sam and Steven) were annotating the trossulus transcriptome for the PSFMC byssus pilot, do you have the file path name to the annotated transcriptome that I can use to create an index with Kallisto? 
Thanks!

**Comment by kubu4** [comment]
What type(s) of file do you need? The [Handbook seems to have an assembly FastA](https://robertslab.github.io/resources/Genomic-Resources/#mytilus-trossulus), but that's it.

**Comment by sr320** [comment]
See https://sr320.github.io/Myt-GO/ - I have annotated

**Comment by sr320** [comment]
This might be a file to work with: https://raw.githubusercontent.com/mattgeorgephd/PSMFC-mytilus-byssus-pilot/main/analyses/blast/Mtros_GO.txt

**Comment by sr320** [comment]
Note you do not need annotation for kallisto - just the file Sam pointed to: https://github.com/RobertsLab/resources/issues/1741#issuecomment-1779955056
