### ISSUE TITLE
Best way to download many large files from Google Drive

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1742]
Does anyone have a favorite way to download many large files from Google Drive? My PhD institution is limiting Google Drive storage so I need to remove about 600 GB of files from Google Drive (large microscopy files). Aside from zipping and downloading small batches at a time, does anyone have an efficient way to download large batches of files from Google Drive?

**Comment by sr320** [comment]
Here is one option: https://github.com/glotlabs/gdrive

I think @kubu4 uses a different CLI.

**Comment by AHuffmyer** [comment]
Amazing, thank you! I'll take a look.

**Comment by kubu4** [comment]
Rclone is the best. Even works between HPC clusters!

https://rclone.org/

**Comment by AHuffmyer** [comment]
Thanks Sam!! Rclone looks easy to use and has lots of functionality.
