### ISSUE TITLE
Improving pseudoalignment rate?

### ISSUE THREAD

**Issue by graceleuchtenberger** [RobertsLab/resources#1746]
PSMFC mussel byssus project: I pseudo-aligned the tag-seq reads to the transcriptome and got 29.8% of the reads to pseudo align. Matt and I were wondering what the best way forward might be to increase alignment rate, given that Matt trimmed 15 bases off the front end of all the reads. Should we just pseudo align with files that have the adapter sequences trimmed off but still have the first 15 bases? The reads are 100 bp originally.

**Comment by kubu4** [comment]
Please provide URL to code.

**Comment by graceleuchtenberger** [comment]
Okay, I am not totally sure how to do that. Are you looking for a GitHub link? Because right now I just have it stored on Raven.

**Comment by sr320** [comment]
You would need to push to github first.

**Comment by graceleuchtenberger** [comment]
Sam in his infinite kindness helped me figure out how to push to Github (I had dug myself into a Git/directory mixup hole, thank you Sam for pulling me out), here are the links to the code:
html: https://github.com/graceleuchtenberger/PSMFC-mytilus-byssus-project/blob/main/1_1_process-tagseq-data-mytilus.nb.html
Rmd: https://github.com/graceleuchtenberger/PSMFC-mytilus-byssus-project/blob/main/1_1_process-tagseq-data-mytilus.Rmd

Data should be on gannet or in my directory on Raven

**Comment by kubu4** [comment]
I glanced through your code and went to try to find the Kallisto data, but got this:

```bash
sam@raven:~$ cd /home/shared/8TB_HDD_02/graceleuchtenberger/PSMFC-mytilus-byssus-pilot/kall-output/

-bash: cd: /home/shared/8TB_HDD_02/graceleuchtenberger/PSMFC-mytilus-byssus-pilot/kall-output/: No such file or directory
```

Where might we find these files?

**Comment by kubu4** [comment]
Also, it would be helpful if files in your analyses were on a server somewhere (i.e. GitHub) to facilitate viewing. For example, FastQC/MultiQC HTMl files are not viewable via command line. 

WARNING: If you _do_ add files to your git/GitHub repo, be sure the files are <100MB in size!! That is the limit for GitHub and it's a pain to fix if you commit files that exceed that limit.

If you need/want help figuring this stuff out, just let us know.

**Comment by kubu4** [comment]
I'd also say that this issue requires much more background info to help troubleshoot:

- What's the source of the transcriptome (i.e. how was it assembled? What's the BUSCO score(s)?)?
- How were TaqSeq libraries constructed?
- What were trimming recommendations from sequencing facility?
- Knowing what you know about the transcriptome assembly and the TaqSeq libraries/sequencing, would you expect higher mapping rates?
- It looks like your data is single-ended, but you didn't specify single-ended options for Kallisto. See: https://pachterlab.github.io/kallisto/manual
- The Kallisto manual also indicates that only a single sample should be provided at a time, but it [looks like you provided multiple files](https://github.com/graceleuchtenberger/PSMFC-mytilus-byssus-project/blob/4fb4a35ce47fd664ea87eef1928f6577c0e3d9cd/1_1_process-tagseq-data-mytilus.Rmd#L180C1-L185C116):

```bash
/home/shared/kallisto/kallisto \
  quant -i /home/shared/8TB_HDD_02/graceleuchtenberger/PSMFC-mytilus-byssus-pilot/kall-index/kall-index-tross.index \
  -o /home/shared/8TB_HDD_02/graceleuchtenberger/PSMFC-mytilus-byssus-pilot/kall-output \
  -t 40 \
  /home/shared/8TB_HDD_02/graceleuchtenberger/PSMFC-mytilus-byssus-pilot/trim-fastq/*.fastq \
  2>&1 | tee /home/shared/8TB_HDD_02/graceleuchtenberger/PSMFC-mytilus-byssus-pilot/kall-output/kallisto-output.out
```

That's a lot to digest, so please feel free to ask any questions you might have!

**Comment by sr320** [comment]
alignment rates are good.
