### ISSUE TITLE
removing hashes in markdown rendered quarto code

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1747]
For below I add, and failed at render...
Can link to quarto file where you implented?

I've added an additional parameter to the setup chunk:

` comment = ""         # Prevents appending '##' to beginning of lines in code output`

_Originally posted by @kubu4 in https://github.com/RobertsLab/resources/discussions/1745#discussioncomment-7448415_

**Comment by kubu4** [comment]
https://github.com/urol-e5/deep-dive/blob/main/D-Apul/code/12-Apul-sRNAseq-MirMachine.Rmd

**Comment by sr320** [comment]
Thanks! I added the line in right place but forgot comma on line above 🤦‍♂️
