### ISSUE TITLE
Run RNA-seq analysis on clam gonad samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1748]
raw Manila clam reads on Gannet  /var/services/homes/charlie/Manila_clam_egg_reads/raw.     Note: the sample ID of "T" (treatment) and "C" (control) is mislabled for clam 193.  It is a control clam.  I left the original naming scheme, but feel free to change it or remember to change it down the road when doing differential expression 

And here is info about where to find the genome references we've been using.  We added the mitochondrial genome to the "genome" before we made the reference (lots of mitochondrial in eggs) Genome used for mapping
Nuclear genome:https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9803972/ (link to paper, “data availability” shows genome NCBI ref as well as annotation tables on FigShare)
Figshare link: https://figshare.com/articles/dataset/Multi-tissue_RNA-Seq_analysis_and_long-read-based_genome_assembly_reveal_complex_sex-specific_gene_regulation_and_molecular_evolution_in_the_Manila_clam/21069946/5
Mitochondrial genome: https://www.ncbi.nlm.nih.gov/nuccore/MZ675529.1

**Comment by meganewing** [comment]
How do I access the clam reads? All the times I've pulled something from Gannet before has been with a link rather than a file path.

**Comment by sr320** [comment]
I can move to your gannet folder, what is your directory name?

**Comment by meganewing** [comment]
cool thank you! 

mewing0

**Comment by sr320** [comment]
https://gannet.fish.washington.edu/mewing0/Man_clam_raw/

ftr

```
sr320@Gannet:/volume2/web/mewing0$ 
cp -r /var/services/homes/charlie/Manila_clam_egg_reads/raw .
```

```
sr320@Gannet:/volume2/web/mewing0$ 
mv raw Man_clam_raw
```

**Comment by meganewing** [comment]
thank you!

**Comment by meganewing** [comment]
kallisto results returning NAs and 0 values. I'm not sure where I'm going wrong. Followed [kallisto tutorial](https://pachterlab.github.io/kallisto/starting). It ran but did give me a warning that my reads didn't pseudo align. Why might this be happening / what can I do? 

<img width="596" alt="Screen Shot 2023-11-29 at 10 46 28 AM" src="https://github.com/RobertsLab/resources/assets/66333757/6fa4a513-4300-4ef0-acf1-fba5e66afec5">
example of what one of the output kallisto tsvs looks like when I load it into R

<img width="841" alt="Screen Shot 2023-11-29 at 10 47 10 AM" src="https://github.com/RobertsLab/resources/assets/66333757/1a8a1ad5-b2fe-42d1-a594-795af69d7fcd">
and what I got when trying to make a trinity matrix with the outputs (what made me realize something funky was goin on)

[kallisto code](https://github.com/meganewing/clamgonads-macsamples/blob/main/code/05-kallisto.Rmd)
[full code subdirectory of repo](https://github.com/meganewing/clamgonads-macsamples/tree/main/code)

**Comment by kubu4** [comment]
After looking through your code, I'm guessing this line is part of the issue:

`/home/shared/kallisto/kallisto index -i transcripts.idx ../data/GCF_026571515.1.zip`

This is attempting to index a ZIP file.

That ZIP file (downloaded from NCBI) needs to be unzipped in order to have access to the genome FastA.

You can unzip the file like this:

`unzip ../data/GCF_026571515.1.zip`

That will unzip a number of subdirectories, so you'll have to look through them to find the actual genome FastA file location.

Give that a rip and see if you can get it to run.

P.S. Did that indexing step generate any messages? I'm surprised it ran without issue at that step.

**Comment by meganewing** [comment]
okay I knitted the [code](https://github.com/meganewing/clamgonads-macsamples/blob/main/code/06-deseq2.Rmd) so you can see the outputs without running it [here](https://github.com/meganewing/clamgonads-macsamples/blob/main/code/06-deseq2.html). Very very bottom (literal last chunk) is where I'm running into issues. 

what I'm trying to get: 
- a data frame containing rows = genes, cols = samples, values = mean exp but ONLY for things where p <= 0.05
- a heatmap that then shows the genes that are significantly deferentially expressed

also want that DF with the sig. DEGs so I can use that for the next step of blast/annotation stuff. 

PS. if anyone has a workflow or documentation for using goseq to share, that'd be sick 😎

**Comment by meganewing** [comment]
how does this look? 

https://github.com/meganewing/clamgonads-macsamples/blob/main/output/DEG_annotations.tab

**Comment by sr320** [comment]
Looking good! - now just need Swiss-Prot annotations based on UniProt Accession... eg line one is `S8FGV1`


see
https://sr320.github.io/course-fish546-2023/assignments/01-blast.html
https://sr320.github.io/annotation/

**Comment by meganewing** [comment]
https://meganewing.github.io/mewing-notebook/posts/2024-01/RNAseq_clamgonads.html

**Comment by sr320** [comment]
> where is this data from?

https://docs.google.com/document/d/1eJtVsJ7tXpFlP8RmqeQecYmWLiCoKhNxPHc7zgKFlbM/edit?usp=sharing

>how to know if the results are good? what sort of failsafes and/or check points are there for me to ensure that my code is producing proper results and not just some results?

profound knowledge gained through courses, lab meetings, pub-a-thon, reading papers and content that shows up on slack

**Comment by meganewing** [comment]
looking for md5sum file: https://gannet.fish.washington.edu/mewing0/Man_clam_raw/

**Comment by kubu4** [comment]
Each FastQ file has a corresponding MD5 checksum file.

**Comment by meganewing** [comment]
How can I compare the server file md5s to the locally dowloaded files to ensure file integrity? Not sure how to generate a sum for a file that is still on the server, not local.

**Comment by kubu4** [comment]
Download the checksum files, too.

**Comment by meganewing** [comment]
ohhhhhh. the .md5 was getting cutoff on my screen so I thought they were just another version of the fastq files. thank you
