### ISSUE TITLE
Login credentials for raven

### ISSUE THREAD

**Issue by Eric-Ess** [RobertsLab/resources#1751]
Looking to use raven for my oyster project, will be using it some in the winter and a lot in the spring. Could I get login credentials?

**Comment by kubu4** [comment]
See slack DM for credentials.

To access RStudio Server on Raven, visit: http:raven.fish.washington.edu:8787

You can safely ignored the security warning that most browser will give you when using an `http` address; the connection is still secure.

Login in with the credentials provided.
