### ISSUE TITLE
Update Roberts COA with 2022-2023 co-authors

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1753]
Update Table 4 of https://d.pr/f/YncqY1

such that it includes co-author affiliations - will have to click through at 
https://faculty.washington.edu/sr320/publications.html. (will just be authors 2022-2023

Also include first names where not present

**Comment by Noahk22** [comment]
Just to confirm you want me to fill in all of the organizational affiliations and fill in first names on table 4?

**Comment by Noahk22** [comment]
The document should be all set now. Here is in the new excel file 
[COA_Roberts_14NOV2023.xlsx](https://github.com/RobertsLab/resources/files/13358232/COA_Roberts_14NOV2023.xlsx)
