### ISSUE TITLE
Get PO number for Azenta RNA-seq

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1754]
I would like to send out tissue samples on https://github.com/RobertsLab/resources/issues/1731
on Monday. 

@kubu4 I presume we need a PO # now.. can you get one?

**Comment by kubu4** [comment]
Yep. Need a budget number, please.

**Comment by sr320** [comment]
GR031727 COD THERMAL STRESS - 66-9283 - 2021

**Comment by kubu4** [comment]
Still waiting on Workday, so I've gone ahead and submitted via TREQ as well. Hopefully one of these will get through eventually!

**Comment by kubu4** [comment]
Received PO number via Workday yesterday. Sample sheet is being prepared in #1764 .
