### ISSUE TITLE
hisat2 on mox error: ERROR: Unable to locate a modulefile for 'bio'

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1758]
script: [https://raw.githubusercontent.com/grace-ac/project-pycno-sizeclass-2022/main/code/02-hisat2-summer2022.sh](https://raw.githubusercontent.com/grace-ac/project-pycno-sizeclass-2022/main/code/02-hisat2-summer2022.sh)

trying to run `hisat2` to align summer 2022 trimmed RNAseq reads with pycno genome 

error (slurm-5008043.out ):     
> ERROR: Unable to locate a modulefile for 'bio' 

Running all this in `/gscratch/scrubbed/graceac9/jobs`

email alert: Slurm Job_id=5008043 Name=gac_2022_hisat2 Failed, Run time 00:00:01, FAILED, ExitCode 1

**Comment by kubu4** [comment]
In general, we don't use modules, so if you're trying to load any modules on your script, you will likely encounter issues.
