### ISSUE TITLE
Histology Shipping Questions

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#176]
@kubu4 can you confirm that this is the correct histology company: [Histology Consulting Services, Inc](http://histocs.com/index.html) - I want to make sure I'm shipping to the right place. 

Also, Laurie asked for a budget number. She says they use their own Fedex account, then bill it to us. @sr320 I could use the Hall since we have it (also could use it for histology processing ~$750).

**Comment by kubu4** [comment]
Shipping address is on bottom of order form.

In regards to FedEx, I put the SAFS FedEx account number on the order form, so they shouldn't need to bill SAFS.

However, you do need a budget number to ship the package out: 65-2861

Also, please don't forget to add the histology services to the Purchasing Log.

**Comment by kubu4** [comment]
> @kubu4 can you confirm that this is the correct histology company: Histology Consulting Services, Inc

Yes, that's the right place, but you'll need the FedEx shipping address on the bottom of the shipping form. The P.O. Box they have listed in their contact section of the website will not work for FedEx!
