### ISSUE TITLE
Create Cod Sample Submission Sheet

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1764]
For RNA-seq

**Comment by shedurkin** [comment]
Spreadsheets for RNAseq (first page) and methylation (second page)
https://docs.google.com/spreadsheets/d/19CqqS3wOhmG7drw163v7evUylRWwOjBOdvuR-y0RqF0/edit#gid=0

**Comment by kubu4** [comment]
Please fill out attached Excel sample sheet for RNAseq. Let me know if you have any questions.

[30-943133806_NGS_Template_File.xls](https://github.com/RobertsLab/resources/files/13665406/30-943133806_NGS_Template_File.xls)

**Comment by shedurkin** [comment]
[Cod_RNAseq_NGS_Template_File.xlsx](https://github.com/RobertsLab/resources/files/13676560/Cod_RNAseq_NGS_Template_File.xlsx)
^ The template file you sent with tube label, tissue type, and species filled out

**Comment by kubu4** [comment]
@shedurkin - Sample 90 is listed twice. Could you please let me know what to change one of the duplicates to?

**Comment by kubu4** [comment]
@sr320 and @shedurkin - Blood samples cannot be processed in the same way as tissue. Per discussion with @sr320 last week, we need to select replacement issue samples and send them out. This will also allow us to replace the duplicate sample 90.

If we can do the same process as before (i.e. pull samples, divide, and place samples for sequencing in separate box in -80C), that'd be killer. I think I'm feeling better, so should be able to come in sometime next week to help with this.

Ideally, we should plan to ship these out on 1/10/2024.

**Comment by sr320** [comment]
@shedurkin can you provide a list of new samples to add?

**Comment by sr320** [comment]
Re sample 90 - are we sure this is just not a typo?

**Comment by kubu4** [comment]
Per a Slack convi with @shedurkin a couple of weeks ago:

> Oh dang, I must've messed up when I selected 4 more liver samples to meet the 80-sample mark. Looking at the pictures I have of the box of samples for sequencing, I do see two tubes with the "90" label, so there wasn't a mislabelling issue.

**Comment by sr320** [comment]
So no mislabelling of spreadsheet, but maybe tube..

**Comment by shedurkin** [comment]
I'm assuming that since both the spreadsheet and tubes contain two 90 samples that it isn't a mislabling issue. One of the 90s included is part of the additional four liver samples we pulled to meet the 80 sample quota, so I think I just somehow missed that we'd already sampled 90 when selecting the additional 4.

**Comment by shedurkin** [comment]
Ok here's an [updated listing sheet](https://docs.google.com/spreadsheets/d/19CqqS3wOhmG7drw163v7evUylRWwOjBOdvuR-y0RqF0/edit#gid=0) (that I checked for duplicates in sheets), with the five replacement samples at the bottom. @kubu4 do you need me to send an updated sequencing form and, if so, how should the it be formatted (remove the blood/duplicate samples, just append the replacemtns to the bottom,...)?

**Comment by kubu4** [comment]
I don't need an updated sequencing form, thanks.

However, could you please make that link public? Currently can't access.

Thanks!

**Comment by shedurkin** [comment]
Sorry about that, now publically viewable
