### ISSUE TITLE
Develop DNA Methylation Sample List (cod)

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1765]
40 Samples

Subset of RNAseq samples

4*8 32 - liver... 

4 blood
4 liver

**Comment by shedurkin** [comment]
rnaseq (first page) methylation (second page)

https://docs.google.com/spreadsheets/d/19CqqS3wOhmG7drw163v7evUylRWwOjBOdvuR-y0RqF0/edit#gid=0
