### ISSUE TITLE
kallisto: trouble getting quantification to run with paired end 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1769]
performing on Raven

code:  https://github.com/grace-ac/project-pycno-sizeclass-2022/blob/main/code/07-kallisto-summer2022-phelgenome.Rmd 

based on: https://github.com/mattgeorgephd/PSMFC-mytilus-byssus-pilot/blob/main/code/07-kallisto.md#4-kallisto-quantification

**Comment by zbengt** [comment]
I think this might be what you're trying to do?

https://github.com/zbengt/coral-lncRNA/blob/main/code/07-count-matrices.Rmd

**Comment by grace-ac** [comment]
this works! thanks @kubu4 https://github.com/grace-ac/project-pycno-sizeclass-2022/blob/main/code/07-kallisto-summer2022-phelgenome.Rmd
