### ISSUE TITLE
Working through MBD-seq analysis pipeline

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#177]
@sr320 you mentioned working through the MBD-seq analysis pipeline with the *C. virginica* oil spill samples. Is this what [Sean worked on](http://rpubs.com/seanb80/269763)? He has a series of lab notebooks taking BS-seq data through Bismark, Methylkit, relatedness matrices, and MACAU. Do I need to reproduce this?

**Comment by sr320** [comment]
Great place to start. Though I would not suggest running Bismark through R- would keep it simple in Jupyter or terminal so we can transfer to Hyak if we need to..
There is likely an improved genome now in NCBI..

**Comment by yaaminiv** [comment]
To clarify: I'm repeating what Sean did (with the same samples) but in Jupyter/terminal and with the improved genome?

**Comment by sr320** [comment]
You do not have to repeat, but if you want to take that approach that is
fine.
Those are the samples for analysis.
Can also be accessed via
https://docs.google.com/spreadsheets/d/1_XqIOPVHSBVGscnjzDSWUeRL7HUHXfaHxVzec-I-8Xk/edit#gid=0

**Comment by yaaminiv** [comment]
Not too keen on repeating work unless necessary, so I'm a bit confused as to what exactly I'm doing with these samples!

**Comment by sr320** [comment]
You need to make sure you can effectively analyze the data when it comes back. 
You should have a pipeline set-up to take your data when it returns. Set of Jupyter notebooks..
These data offer ability to validate pipeline.
This is also product that has potential and is more ecological relevant.
