### ISSUE TITLE
GANNET - Failure to Upload

### ISSUE THREAD

**Issue by ChrisMantegna** [RobertsLab/resources#1770]
Each time I attempt to drag and drop my files into Gannet it gives me **"Failed to upload "file name". The source file does not exist.** See screenshot below noting that the Anacapa file folder is empty of any data files. 

I was able to move 2 files and then every single other file failed. How do I fix that error? 
I downloaded the information as zip files to my computer and have attempted to upload to Gannet in the .zip format as well as individual files with no luck.
I need to move the data from this [Google Drive Folder ](https://drive.google.com/drive/folders/1PUJstidJrus4pVDZ4rdeRmQNiZc2f_1I?usp=sharing) to Gannet.
![gannet upload error](https://github.com/RobertsLab/resources/assets/81385272/d810fc03-b830-48d3-b201-d93548bb203c)

Please & thank you!

**Comment by sr320** [comment]
I added most if not all files. Generally speaking I am unsure of file integrity. This might not be an option but it is always best to try to go from server to server for sequencing files with hashes to check integrity.

**Comment by ChrisMantegna** [comment]
Thank you - the option isn't there for the ONT data, but the other files - the bulk of the fastqc's - I can zoom with Rachel to make sure to pull directly from the UCSC servers. The Tronko and /or Anacapa results will be the files I'm working with for the visualizations for my talk and their results are already in taxonomic tables.

**Comment by kubu4** [comment]
This is overkill, but has proven to be a valuable tools for me when dealing with data transfers between different servers/sources:

https://rclone.org/

Works between Google Drive, Dropbox, high performance computing clusters, Amazon AWS, personal servers, personal computers, etc. Pretty much any time of file service you can think of.

In regards to file integrity, you should ask whoever provided you with the files to generate checksums for all the files in each directory, save the checksums for each directory to a file within the same directory, and then upload all of those checksum files to the Google Drive folder.

That would be best practice and would allow you to confirm that the file transfers worked without corrupting any data. (you can use the checksum files to do this). The program linked above, R Clone, actually checks data integrity during transfer, so eliminates the need to do this whole checksum verification process.

**Comment by ChrisMantegna** [comment]
Thanks Sam! I did see the checksum files when the data was transferred from the sequencing server to the Meyer Lab, but they are definitely missing here. I'm assuming the checksum file generation is a bash command/ separate bash script run to generate?

**Comment by kubu4** [comment]
> I'm assuming the checksum file generation is a bash command/ separate bash script run to generate?

Correct.

To generate a checksum, you run  this command (Linux - Mac has a different command of course) - substitute in your actual filename:

`md5sum MyONT.fq >> checksums.md5`

That will generate a checksum value and write that value and the filename to the output file called `checksums.md5`.

Then, after transferring your file, and the checksums file, you can confirm that the checksum did not change (if it did change, then the file got corrupted during transfer):

`md5sum --check checksums.md5`

That command will read the `checksums.md5` file for the filename(s) you want to check, generate the checksum, and then compare it to the checksum for listed in `checksums.md5`. It will then tell you whether or not they match.

Hopefully it's not a big deal to ask the Meyer Lab to pass those along.

**Comment by ChrisMantegna** [comment]
I have crossed over to the dark side... I see you haven't been keeping up with my cryptic daily notebook posts! I am a macbook user now... 😈

**Comment by ChrisMantegna** [comment]
Related - thank you. I will be running through this soon.
