### ISSUE TITLE
annotation of pycno genes?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1771]
## Questions:
1. Is the interproscans.tsv annotation file what I should be using? 
2. If not, I'm thinking going through the BLAST --> GO process is what I'd do instead, BLAST-ing against the _P. helianthoides_ genome? 

## Background info: 

I looked on DRYAD for the _P. helianthoides_ genome annotation file. 

Link: https://datadryad.org/stash/dataset/doi:10.5061/dryad.51c59zwfd 

There's one called the interproscans.tsv

I downloaded it and it seems to be a list of proteins rather than gene IDs? 

Screenshots of the open interproscans.tsv file in R: 
<img width="1004" alt="interproscans_annot_1" src="https://github.com/RobertsLab/resources/assets/14934314/b4dc8bdf-d508-4e37-83c0-e57d4764eae3">
<img width="1007" alt="interproscans_annot_2" src="https://github.com/RobertsLab/resources/assets/14934314/c8380516-e298-4eaf-81e7-b44ff7236906">

**Comment by sr320** [comment]
Go ahead and initiate 2.

**Comment by grace-ac** [comment]
sounds good! thanks!
