### ISSUE TITLE
Quarto - PNG renders with clear background, but has white background when viewing image directly?

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1778]
I have some plots as PNG that I link to in [this Quarto post](https://robertslab.github.io/sams-notebook/posts/2024/2024-01-03-Data-Exploration---CEABIGR-Spurious-Transcription-Calculations-and-Plotting/) which render with transparent backgrounds. However, when viewing the images directly at their URLs, the backgrounds are white. Anyone have any idea how to remedy this?

Here's the direct link to one plot. If you open the plot in a new tab or a new window, the plot shows with a white background:

![https://raw.githubusercontent.com/sr320/ceabigr/8bc64a3a5dcca6932d14bcf13a3fb15f3e9d5d95/output/65-exon-coverage/figures/control-females.v.control-males-line_plot.png](https://raw.githubusercontent.com/sr320/ceabigr/8bc64a3a5dcca6932d14bcf13a3fb15f3e9d5d95/output/65-exon-coverage/figures/control-females.v.control-males-line_plot.png)

Here's a web capture of what I'm talking about:

[Screencast from 01-10-2024 04:07:55 PM.webm](https://github.com/RobertsLab/resources/assets/4514104/7addb673-0cb3-49da-801b-06e60c839a1d)

Anyone have any suggestions?

**Comment by kubu4** [comment]
Took @AHuffmyer's advice and set the PNG background to "white" in the code. Was a quick "find and replace" to add to the extra parameter to all instances of the file saves.

Thanks!

**Comment by AHuffmyer** [comment]
Awesome I'm glad that worked!
