### ISSUE TITLE
Add SICB talks to Lab website

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1779]
Add citation (and link to PDF if you would like) of your SICB talks here in "recent publications": https://github.com/RobertsLab/lab-website/blob/main/publications.qmd

**Comment by grace-ac** [comment]
done! also added my WSN talk from Nov 2023

**Comment by AHuffmyer** [comment]
done!

**Comment by ChrisMantegna** [comment]
done!

**Comment by sr320** [comment]
@zbengt ?

**Comment by zbengt** [comment]
Done!
