### ISSUE TITLE
Testing new UW Data Repo

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#178]
Friday I am going to the library to provide some feedback on the new repository system.

They want me to bring some data that we might deposit.

Any examples? Note, it would not be the raw sequence data we send to other repos.

**Comment by kubu4** [comment]
Do you have more info? What is this? A GitHub-type thing? More like OSF? Like FigShare? Just data storage?

**Comment by sr320** [comment]
That is what they want me to tell them....
Suggestions?

**Comment by sr320** [comment]
thoughts 
why not do figshare for institution
need big limits
easy
doi
CLI access...
