### ISSUE TITLE
Sign up to lead Ch. 4 discussion at lab meeting on 1/18/2024 ("Race After Technology")

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1780]
Please add yourself to the calendar:

https://docs.google.com/spreadsheets/d/1WB87aK0_CHu9mxb5P9nWRH0-LDF15ogf3Ibjoe_cGTQ/edit?usp=sharing

Please provide discussion points here and/or in Slack.

**Comment by meganewing** [comment]
I have a 10am meeting thursday so will be leaving lab meeting early, but if y'all are okay with that, I'm happy to lead this one. Let me know
