### ISSUE TITLE
paperpile

### ISSUE THREAD

**Issue by meganewing** [RobertsLab/resources#1782]
howdy. how can I get onto the paperpile account? I've just been using the free trial so far.

thanks!

**Comment by shedurkin** [comment]
i got a license code from Steven: JZIC-Pevz-Y1sd-IglM
not sure if it will still work though, so you may have to contact him/wait for him to get back from chile

**Comment by sr320** [comment]
code only works for one person, everyone needs a different code, will send you one

**Comment by sr320** [comment]
@meganewing - actually JZIC-Pevz-Y1sd-IglM should work now..
