### ISSUE TITLE
Transcriptomes for E5 deep dive species

### ISSUE THREAD

**Issue by shedurkin** [RobertsLab/resources#1783]
Ariana, could you look into whether we have transcriptomes for any of the three deep dive species (A.pulchra, P.evermanni, P.meandrina) for gene expression work?

**Comment by sr320** [comment]
maybe elaborate on exactly what you are looking for.. we have cds feature files where we could extract transcriptomes. we also have RNA-seq data where we could generate de novo. And third we have RNA-seq aligned to genome where known and know transcripts can be generated.

**Comment by AHuffmyer** [comment]
Yes we have RNA seq data [Deep Dive Wiki here](https://github.com/urol-e5/deep-dive/wiki/Expression-Data-Types) for the deep dive samples from A. pulchra, P. meandrina, and P. evermanii. These samples are from the 2020 Moorea time series project, taken at 1 site from the same time point. There are n=5 of each species. All the options Steven outlined above are possible depending on what you need!

**Comment by shedurkin** [comment]
I've heard/read about generating de novo transcriptomes from RNAseq data to then use as comparison for gene expression analysis but I'm still kind of confused on how that works. You would be assembling the transcriptome from rnaseq data and then mapping the same rnaseq data back to that transcriptome to get expression counts, right? How does comparing data to itsself work?

**Comment by AHuffmyer** [comment]
What are you wanting to obtain from the analysis? Are you looking for differential expression between certain groups or treatments? I.e., do you want to look for differences in a gene count matrix?

**Comment by AHuffmyer** [comment]
You would use a de novo transcriptome when a reference genome or reference transcriptome is not available, or you are not confident in the quality of a previously published reference. Essentially, a de novo transcriptome is made by assembling our shorter RNAseq reads into longer transcript reads. This creates a reference for transcripts that are possible in the data. Then you use this reference to map the sequences back to and generate a count matrix for how often each transcript shows up in a sample for differential gene expression analysis.

**Comment by zbengt** [comment]
Steven and I just talked and I know what we're looking for! We want transcript FASTAs to run kallisto for mRNA count matrices. I'll grab the links from NCBI and post here.

**Comment by zbengt** [comment]
Acropora: https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_013753865.1/
Choose the transcript FASTA
![Screen Shot 2024-01-18 at 3 06 27 PM](https://github.com/RobertsLab/resources/assets/91245841/f29b365b-a7a3-4ab2-81a9-5e15d4fcedf1)

The others are less clear. I don't see similar FASTAs available for [Porites evermanni](https://www.genoscope.cns.fr/corals/genomes.html) and [Pocillopora meandrina](http://cyanophora.rutgers.edu/Pocillopora_meandrina/). However, there is a CDS FASTA for Pocillipora meandrina. And for Porites evermanni there is a file noted in the e5 wiki located [here](https://gannet.fish.washington.edu/seashell/snaps/Porites_evermanni_v1.annot.gff) that is an annotation with CDS and mRNA.

Could we use the Pocillopora meandrina CDS FASTA? And then the Porites evermanni annotation GFF to generate a FASTA?

**Comment by sr320** [comment]
as Zach points out use the genes gff at https://www.genoscope.cns.fr/corals/genomes.html for evermanni, using bedtools `getfasta`.

and use yes, use CDS fasta for meandrina http://cyanophora.rutgers.edu/Pocillopora_meandrina/

**Comment by shedurkin** [comment]
All transcriptomes retrieved/generated and added to deep-dive repo here: https://github.com/urol-e5/deep-dive/wiki/Species-Characteristics-and-Genomic-Resources
