### ISSUE TITLE
Extract DNA for cod methylation analysis

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1786]

**Comment by kubu4** [comment]
Was just getting ready to submit Psomagen (Macrogen) order for this project (we got the PO number already!) and discovered they offer DNA/RNA extraction services, too! These services were not listed on their website when I first looked into things.

@sr320 - Do you want me to get a quote for DNA extraction and subsequent WGBS sequencing? Sorry about this!

**Comment by sr320** [comment]
Yep

**Comment by kubu4** [comment]
Quote _with_ DNA extractions for tissue and blood: $14,940. (Original quote for just WGBS was $12,400).

Go ahead with updated quote?

**Comment by sr320** [comment]
yes go ahead with updated quote

**Comment by kubu4** [comment]
Thanks. Which budget(s) should I use?

**Comment by sr320** [comment]
GR031727 COD THERMAL STRESS - 66-9283 - 2021


Steven B. Roberts, Professor School of Aquatic and Fishery Sciences
University of Washington Fisheries Teaching and Research (FTR) Building -
Office 232 1140 NE Boat Street - Seattle, WA 98105 robertslab.info
<https://faculty.washington.edu/sr320/> - ***@***.*** - @sr320
vm:206.866.5141 - cell:360.362.3626 schedule a zoom call:
https://d.pr/gsgxVJ

**Comment by kubu4** [comment]
PO request submitted via Workday.
