### ISSUE TITLE
Cod RNA-seq - Decision regarding samples with too low RNA yields

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1787]
Received the attached QC report from Azenta:

[Sample QC report of_30-943133806_240118025106.pdf](https://github.com/RobertsLab/resources/files/13995175/Sample.QC.report.of_30-943133806_240118025106.pdf)

There are six samples that did not yield RNA:

- 19
- 41
- 48
- 98
- 128
- 149

There are others that have a RIN score < 6.0. Traditionally, we've always proceeded with sequencing for samples with low RIN scores, but that's because we've primarily sequenced shellfish which don't have the "standard" eukaryotic rRNA bands.

We need to let Azenta know how to proceed:

1. Proceed with all samples (even those that have undetectable amounts of RNA).
2. Resubmit more tissue for the samples listed above.
3. Only sequence samples with sufficient RNA and RIN scores >6.0.

EDITED: Fixed attachment upload weirdness.

**Comment by sr320** [comment]
What treatments are those samples corresponding to?

**Comment by shedurkin** [comment]
19:  16 degree41, 48:  0 degree 98:  9 degree128, 149:  5 degreeOn Jan 19, 2024, at 2:45 PM, Steven Roberts ***@***.***> wrote:﻿
What treatments are those samples corresponding to?

**Comment by sr320** [comment]
lets go with 

> Proceed with all samples (even those that have undetectable amounts of RNA).
