### ISSUE TITLE
epigenetic inheritance paper hunt

### ISSUE THREAD

**Issue by meganewing** [RobertsLab/resources#1788]
Howdy all!
I’m looking for a paper on epigenetic inheritance. ideally with an experimental setup of something like F0 (control/ambient conditions) F1 (various treatments) F2( control/ambient conditions) to look at how well retained epigenetic changes are for offspring of parents who faced the altered environment, but the offspring themselves haven’t faced the altered environment. 

I’ve been searching but haven’t quite yet found what i’m looking for. I feel like I remember someone doing something similar with OA in oysters across generations but can’t remember who. 

Does anyone have any paper recommendations?

**Comment by sr320** [comment]
In oysters we have unpublished "CEABIGR" data... Also french have at least two publications looking at pesticide exposure...
https://pubmed.ncbi.nlm.nih.gov/38217500/ - and Rondon et al (which is certainly cited within...) 

More broadly, examples of epigenetic inheritance in invertebrates encompass various mechanisms and organisms. For instance, in C. elegans, dsRNA-mediated gene silencing (RNAi) can be inherited for more than five generations, demonstrating a striking example of epigenetic inheritance (Buckley et al., 2012). Additionally, in honey bees, there is evidence of the intergenerational transfer of DNA methylation marks, indicating transgenerational epigenetic inheritance in invertebrates (Yagound et al., 2020). Furthermore, the review by Lim & Brunet (2013) surveys recent examples of epigenetic inheritance induced by genetic and environmental perturbations in animals, shedding light on the broad scope of epigenetic inheritance in invertebrates.  Moreover, the study by Harris et al. (2019) suggests that transgenerational epigenetic inheritance of DNA methylation may be a common feature of invertebrates. 

Publications consulted.
Buckley, B., Burkhart, K., Gu, S., Spracklin, G., Kershner, A., Fritz, H., … & Kennedy, S. (2012). A nuclear argonaute promotes multigenerational epigenetic inheritance and germline immortality. Nature, 489(7416), 447-451. https://doi.org/10.1038/nature11352
Chille, E., Strand, E., Neder, M., Schmidt, V., Sherman, M., Mass, T., … & Putnam, H. (2021). Developmental series of gene expression clarifies maternal mrna provisioning and maternal-to-zygotic transition in a reef-building coral. BMC Genomics, 22(1). https://doi.org/10.1186/s12864-021-08114-y
Gerdol, M., Gomez‐Chiarri, M., Castillo, M., Figueras, A., Fiorito, G., Moreira, R., … & Vasta, G. (2018). Immunity in molluscs: recognition and effector mechanisms, with a focus on bivalvia., 225-341. https://doi.org/10.1007/978-3-319-76768-0_11
Harris, K., Lloyd, J., Domb, K., Zilberman, D., & Zemach, A. (2019). Dna methylation is maintained with high fidelity in the honey bee germline and exhibits global non-functional fluctuations during somatic development. Epigenetics & Chromatin, 12(1). https://doi.org/10.1186/s13072-019-0307-4
Head, J. (2014). Patterns of dna methylation in animals: an ecotoxicological perspective. Integrative and Comparative Biology, 54(1), 77-86. https://doi.org/10.1093/icb/icu025
Hinzmann, M., Lopes‐Lima, M., Boboş, I., Ferreira, J., Domingues, B., & Machado, J. (2014). Morphological and chemical characterization of mineral concretions in the freshwater bivalve anodonta cygnea (unionidae). Journal of Morphology, 276(1), 65-76. https://doi.org/10.1002/jmor.20320
Lim, J. and Brunet, A. (2013). Bridging the transgenerational gap with epigenetic memory. Trends in Genetics, 29(3), 176-186. https://doi.org/10.1016/j.tig.2012.12.008
Putnam, H., Trigg, S., White, S., Spencer, L., Vadopalas, B., Natarajan, A., … & Roberts, S. (2022). Dynamic dna methylation contributes to carryover effects and beneficial acclimatization in geoduck clams.. https://doi.org/10.1101/2022.06.24.497506
Yagound, B., Remnant, E., Buchmann, G., & Oldroyd, B. (2020). Intergenerational transfer of dna methylation marks in the honey bee. Proceedings of the National Academy of Sciences, 117(51), 32519-32527. https://doi.org/10.1073/pnas.2017094117

**Comment by sr320** [comment]
There is also https://www.sciencedirect.com/science/article/pii/S037811191930825X

**Comment by meganewing** [comment]
thank you!
