### ISSUE TITLE
Simple assays for assessing stress in bivalve spat / seed

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1789]
What might be some simple, relatively inexpensive assays for assess stress in bivalves..

along lines of @mattgeorgephd work

Citrate synthase, NAK Atpase...

Any and all suggestions welcome and estimates on per sample cost would be great. 

lipidomics? metabolomics?

**Comment by AHuffmyer** [comment]
[Northwest Metabolomics Research Center @ UW](https://northwestmetabolomicsorg.wpcomstaging.com/services/assays-fees/) - they have services for targeted and untargeted metabolomics and lipidomics as well as stable isotope metabolomics! I'll look more into their services and costs. They have options for submission of extracted metabolites and full tissue preparation.

**Comment by AHuffmyer** [comment]
Lipids, proteins, and carbs (to calculate total energetic content) can also be done in 96 well plate format

**Comment by mattgeorgephd** [comment]
![image](https://github.com/RobertsLab/resources/assets/70529576/8c88b945-e70d-4636-b016-fb7d4ba6d14b)

I would add:
1. [Succinate/Lactate Dehydrogenase](https://www.mdpi.com/1660-3397/8/8/2318): Succinate accumulation is considered an indicator of anaerobic metabolism in bivalves including oysters [[Greshaber et al 2005](https://link.springer.com/chapter/10.1007/BFb0030909),[Kurochkin et al 2009](https://journals.physiology.org/doi/full/10.1152/ajpregu.00324.2009)]
2. [Malate Dehydrogenase (MDH)](https://www.researchgate.net/profile/Adam-Marsh-3/publication/248924428_Interindividual_variation_of_malate_dehydrogenase_activity_in_the_oyster_Crassostrea_virginica/links/56f91efb08ae7c1fda311037/Interindividual-variation-of-malate-dehydrogenase-activity-in-the-oyster-Crassostrea-virginica.pdf): Catalyzes interconversion of oxaloacetate and malate, is an integral component of the carbon transport system that fuels metabolism under the regular hypoxic stress experienced by oysters during tidal emersion.Activity correlates significantly with total respiration in the mussel Mytilus californianus ([Dahlhoff et al. 2002](https://watermark.silverchair.com/i1540-7063-042-04-0862.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAA1wwggNYBgkqhkiG9w0BBwagggNJMIIDRQIBADCCAz4GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMGx6S2QbLOYMHCjx5AgEQgIIDD6uJk-Bwjvl0r_rJyOB4T1nFpOn7FAIbTyKTm7pXPLsK6nLddaX_P19jfeBjojaWcODACG7O_Nc9EditSePMmVbzAri9AGdFXCvu8aoDY70aYF2VsUspsiCyYL94OV0JXqL-6POsXeAI1-6Ij8ZPYDxZClACKjYDIDRlMyQDlGtjl_VdMXe0MaWJaX58eELj8f9FjKslKxTqDQ8jCB9DD3FtdoOm7QXBToOzexSN1DHT4I0lY-ISlvvS7AXqzPb5qIHBst7KxyuV2PrUuUyzmW41vFD6I0GYtUvbvHQ9hUZIQ9WwK3oz0_XXnaSb5dC1JODRewGpjqS1iEhU_bFDRBBh57xIH5ugqsFv7YGGMZdDqQegVay-kbHgi36rxv2r9jm4K7RqjnblI549-6cnTRnEdBv2eR_OgCpChmfTWRtpUioJgNA-swAv6OaevQZWgj5eNH7_CNaN4X-GWtQfFBd0OSdxw25KM784IJJs5hvA-InxCydWRcGES4nlbx9Wr2qctXno7kWx5Q8z2DcoUxqDEkQY19tMk24FIxqHs9CgBFavy23Ag6n-IqBmcF3WT0FII0ZelrcY38Ymh0n5Sdt0UGMmNMgtg3UsTode2qHU6GWvZaCdIhrRGY3T7IwCHX-UOnQmIcAWuZbNDwXYLcRIr3Ng3Wj6VjldzncdnaYf963v-G1VTSEwW6JVaQyrJP-2VkznpRW_EAS_0RPWJ6mY8pOYp0myOTfqH4o9CtEPpRUZE2Vze-wXe1_xkZrZRguLOxb2iRRA_3bBqe0UGzwTi14KLqUIgd5pG93W4cdgNfX4pfNc5hb_lpI8ZJ2zMBptIpHOUXQYO-q9algWKxOZ4ONdjt0CsNOwCI7GyPyznsSZuYq219k3RiJsz7PTzXhxss7Zie2-LoBSbiftZuF-kTF8rbrHGy0Kjd715A-J9Clt6E3pDkBYP5cAWEYj0WB7DAvuMIFCc_CjbIisuC0ZsSuhcowzi8b-B6uUrewnNdUCDM-pbyDBcSEte3QJDYaDWMAHZn3wzPZjuqkK5Q)) and fish ([Yang and Somero 1993](https://journals.biologists.com/jeb/article/181/1/213/6633/Effects-of-Feeding-and-Food-Deprivation-on-Oxygen)).

Additional Resources:
1. [Energy-Limited Tolerance to Stress as a Conceptual Framework to Integrate the Effects of Multiple Stressors](https://academic.oup.com/icb/article/53/4/597/632460)
7. [Evolution of cellular stress response mechanisms](https://onlinelibrary.wiley.com/doi/10.1002/jez.2347)

**Comment by AHuffmyer** [comment]
Took samples on 2/28 of spat and seed that we can use for some assays. We also transported spat and juveniles to UW and we can use these to try out assays. Goal is to try out respirometry and ATPase assays next.

**Comment by AHuffmyer** [comment]
I think incorporating TPC's via respirometry addresses a lot of our questions of interest. (e.g., https://www.sciencedirect.com/science/article/pii/S0025326X23011852). We can look into SDR and Oxy-10 systems to do this and I can write these as proposed expenses for the Sea Grant/NOAA proposal.
