### ISSUE TITLE
Planning for DNA Shearing

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#179]
I see from @yaaminiv notebook that she and @kubu4 sheared the DNA at NOAA in Mac's lab.  I expect I'll need to do the same, but before contacting Mac - are ya'll content with the resulting bp length? 

Also, why not use our sonicator in the lab?

**Comment by sr320** [comment]
Let’s see if you get DNA first :)
We have bought a new one for SAFS- not sure if arrived yet.

**Comment by kubu4** [comment]
>Also, why not use our sonicator in the lab?

It's not high enough frequency. It's designed for tissue disruption, not DNA shearing.
