### ISSUE TITLE
RStudio Server can't install packages, `/opt/R/4.2.3/lib/R/library` not writeable

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1790]
@graceleuchtenberger was experiencing this issue in https://github.com/RobertsLab/resources/issues/1774#issuecomment-1908848273.

As that differs than the topic of that issue, I've moved this particular problem to it's own issue.

Regarding updating/installing packages, you'll need to create a personal R library installation location. Currently, R is trying to install to the "global" location (`/opt/R/4.2.3/lib/R/library`). As noted in the error message, this path is not writeable. This is by design, so that people don't accidentally change/remove the "base" packages that everyone relies on.

To start the process, can you please run the following code (in R console)?

```r
.libPaths()
```

Please paste the output in your reply and then we'll discuss the next steps.

**Comment by graceleuchtenberger** [comment]
Hi Sam,
This is the output I got:
[1] "/home/shared/8TB_HDD_02/graceleuchtenberger/R/x86_64-pc-linux-gnu-library/4.2"
[2] "/opt/R/4.2.3/lib/R/library"    
Thanks for your help!

**Comment by kubu4** [comment]
Closing, as it seems like software install wasn't a problem with analysis, as analysis was successfully completed here:

https://github.com/RobertsLab/resources/issues/1799
