### ISSUE TITLE
CEABiGR coding sequence FASTA

### ISSUE THREAD

**Issue by zbengt** [RobertsLab/resources#1791]
This is more of a check to make sure I can use this. I've been using a CEABiGR CDS FASTA I found from previous work and want to make sure I understand how it was made. It was used in [14-kallisto](https://github.com/sr320/ceabigr/blob/main/code/14-RNA-kallisto.Rmd) and I retrieved it from `/home/shared/8TB_HDD_01/sr320/github/ceabigr/data/GCF_002022765.2_C_virginica-3.0_cds_from_genomic.fna` on Raven.

I'm assuming it's using the Crassostrea virginica mRNA GFF to filter the genomic FASTA. Thus far I have used it for DESeq2.

**Comment by kubu4** [comment]
The code shows it was downloaded from NCBI:

https://github.com/sr320/ceabigr/blob/dbd107b9bf97f3e8a1f3a4b7f9d81a7f43d027cf/code/14-RNA-kallisto.Rmd#L16-L19

You'll likely need to visit the NCBI site for details on creation.

**Comment by sr320** [comment]
Yep have a look at the transcripts fasta and cds from genomic fasta at NCBI (https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_002022765.2/) and see what is different... and post here.

**Comment by zbengt** [comment]
The transcripts fasta includes all RNAs, so in addition to mRNA it contains categories misc_RNA and ncRNA. The CDS fasta only includes those that code for a protein, along with protein name and isoform info. A quick search also shows that there are 60,288 mRNA entries in the transcripts fasta (out of 66,625 total) and 60,288 entries total in the CDS fasta. So seems like the CDS fasta is definitely the most appropriate for mRNAs. Thank you both!
