### ISSUE TITLE
Establish tentative oyster deployment scenario

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1792]
For commercial grow-out across farms for USDA and WSG effort

Spring/Summer 2024

**Comment by AHuffmyer** [comment]
Started work to prepare some adults for outplanting at Point Whitney this week: https://ahuffmyer.github.io/ASH_Putnam_Lab_Notebook/Oyster-Individual-Growth-and-New-Seed-Exposures/ 

We also started a new plan for treating seed. Where do we want to outplant these eventually?
