### ISSUE TITLE
Kallisto indexing [build] warning: replaced 10722052 non-ACGUT characters in the input sequence with pseudorandom nucleotides

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1795]
@shedurkin - To try to keep things a bit "cleaner", I've created a separate issue (originally taken from here: https://github.com/RobertsLab/resources/issues/1793#issuecomment-1920023835).

Code:

- [R Markdown file](https://github.com/urol-e5/deep-dive/blob/main/E-Peve/code/12-Peve-RNAseq-kallisto.Rmd)
- [Rendered markdown](https://github.com/urol-e5/deep-dive/blob/main/E-Peve/code/12-Peve-RNAseq-kallisto.md)

Problem section of code:

- [Building Kallisto index on extracted mRNA FastA](https://github.com/urol-e5/deep-dive/blob/main/E-Peve/code/12-Peve-RNAseq-kallisto.md#building-index)

**Comment by kubu4** [comment]
From https://github.com/RobertsLab/resources/issues/1793#issuecomment-1920023835:

> Oh interesting, that's super helpful! So, if that means the mRNA fasta has been extracted correctly, then the Ns shouldn't be a problem for pseudoalignment, right? My basic understanding of kallisto pseudoalignment is that it avoids directly aligning reads to a reference by instead breaking reads into k-mers and then mapping them to identify which reference sequence the read likely originated from. It seems like internal stretches of Ns (or the "pseudorandom nucleotides" they're replaced with) shouldn't interefere with that process

**Comment by sr320** [comment]
This is indicating genome has "NNNNNNs"
