### ISSUE TITLE
Next steps for mytilus byssus expression/ did I do this PCA correctly

### ISSUE THREAD

**Issue by graceleuchtenberger** [RobertsLab/resources#1799]
I finally got a PCA to work with some code from Sam's snow crab repository. Here's the plot:
![Screenshot 2024-02-05 at 2 09 59 PM](https://github.com/RobertsLab/resources/assets/122406581/fb5e4c8d-5d13-4b3f-a98c-71d3d836ca5a)

See the overall code [here](https://github.com/graceleuchtenberger/Byssus-expression-analysis/blob/d362947ae341a34c772ec5e96b2ede0a5b4b85aa/code/01-diff-exp-analysis.Rmd). 

Here's the code section I used to generate the plot:

## Visualize differences between treatment groups
```{r}
# Filter data
treatmentinfo.F <- treatmentinfo.2 %>% filter(tissue == "F" | day == "3") %>%
  filter(!(day == "0" | tissue == "G"))
treatmentinfo.F$sample.1 <- factor(treatmentinfo.F$sample.1)
treatmentinfo.F$tissue <- factor(treatmentinfo.F$tissue)
treatmentinfo.F$treatment <- factor(treatmentinfo.F$treatment)
treatmentinfo.F$day <- factor(treatmentinfo.F$day)
countmatrix_F <- subset(countmatrix_2, select=row.names(treatmentinfo.F))

# Calculate DESeq object
dds2 <- DESeqDataSetFromMatrix(countData = countmatrix_F,
                              colData = treatmentinfo.F,
                              design = ~ treatment)

dds2 <- DESeq(dds2)
resultsNames(dds2) # lists the coefficients
summary(dds2)

# Plot PCA

PCAdata <- plotPCA(vst(dds2), intgroup = c("treatment"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=treatment)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()

````

**Where do people want to go from here? Did I do the PCA correctly?**

**Comment by kubu4** [comment]
Regarding where to go from here, @sr320's [comment](https://github.com/RobertsLab/resources/issues/1774#issuecomment-1875916124) still applies:

- identify differentially expressed genes (DEGs) between various one-to-one comparisons.

**Comment by graceleuchtenberger** [comment]
Thanks Sam! I think Matt wanted to see a PCA across all four treatments first, so that's why I did what I did. Hoping to get a go ahead to see if a pairwise comparison is worth it given the graph above.

**Comment by sr320** [comment]
Yes - I say pairwise info is worth getting.

**Comment by mattgeorgephd** [comment]
Nice work Grace!

As far as the PCA goes, some improvement could be:
1. Add day zero foot samples as their own treatment (true control). The control listed is foot tissue from day 3, which is technically a "treatment" or "laboratory control".
2. Add circles (https://stackoverflow.com/questions/34869768/how-to-make-a-pca-plots-as-i-posted-here)

Agree that next steps are trt vs control comparisons of gene expression. The PC1 vs PC2 axis didn't pick up much of the variance, so there is likely a lot of overlap. A list of genes that are differentially expressed across each treatment relative to the true control. I would start with just significant and not filter by lfc to start.

**Comment by mattgeorgephd** [comment]
Wow, really interesting! Looks like bringing them into the lab really made a difference.

**Comment by graceleuchtenberger** [comment]
I did pairwise comparisons (true control to everything else), got PCA's and DEG lists. See the PCA's [here](https://graceleuchtenberger.github.io/DGE-analysis-1/)

**Comment by mattgeorgephd** [comment]
Amazing work @graceleuchtenberger!

**Comment by mattgeorgephd** [comment]
Agreed, a two step analysis would be helpful here. Here is the approach we came up with. Interested in everyone's input:

1. Generate DEG lists of treatment vs. control 0  (lab control) - gives you impact of lab exposure
2. Generate DEG lists of treatment vs. control 3 (treatment control) - gives you impact of treatment
3. Filter DEG lists for significance
4. Normalize lfc value obtained in step 2 using lfc value in step 1

I think this accomplishes the same thing as the approach that @AHuffmyer suggested, but has the potential to more accurately capture tank level effects as they relate to animals in each treatment. Treatments in this case were not pseudo-replicated by splitting animals into different chambers, so we really are looking at tank level effects.
