### ISSUE TITLE
Update members, outside collabs

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#18]
For RobertsLab organization

**Comment by kubu4** [comment]
By update, do you mean add _and_ remove?

Sent invites to Kaitlyn and Katie.

Anyone else that I'm missing?

**Comment by sr320** [comment]
Jay
Megan

**Comment by sr320** [comment]
Brent
Jose

**Comment by sr320** [comment]
promote Hollie to collaborator

**Comment by kubu4** [comment]
I don't think Megan or Brent have GitHub accounts?

Don't know about Jose (don't even know his last name) to look.

**Comment by kubu4** [comment]
> promote Hollie to collaborator

Will result in the following:

![selection_097](https://user-images.githubusercontent.com/4514104/29185003-d1dfdc4e-7dbc-11e7-8df6-023eba24a53c.png)

OK?
