### ISSUE TITLE
Determine expression clusters using WGCNA

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1801]
We have exon expression levels of 13k genes and I would like to group based on expression pattern (thinking of as time series).. 

Here is the data: https://github.com/sr320/ceabigr/blob/main/output/68-female-exon-fold/logfc.txt

Here is my attempt at WGCNA:
https://github.com/sr320/ceabigr/blob/main/code/69-wgcna.qmd

a bit lost though.

Is this the proper approach..

**Comment by zbengt** [comment]
If you haven't already, you might want to take a look at Ariana's WGCNA code I have been basing my work off of [here](https://github.com/AHuffmyer/EarlyLifeHistory_Energetics/blob/master/Mcap2020/Scripts/TagSeq/Genome_V3/1_WGCNA_Mcap_V3.Rmd). It does a good job of walking you through it, and I think you would just need to replace the thinking around "lifestage" with any grouping in these samples.

I'm running my mRNA WGCNAs, so once I have the code up and running with instructions, I can link it here. We can discuss tomorrow as well!

**Comment by sr320** [comment]
merged text file (exposed and controls) : https://raw.githubusercontent.com/sr320/ceabigr/main/output/68-female-exon-fold/female_merge.txt

**Comment by AHuffmyer** [comment]
Notebook post on attempt/script from 2/8 here: https://ahuffmyer.github.io/ASH_Putnam_Lab_Notebook/WGCNA-Attempt-1-for-ceabigr-project-exon-expression-data/

**Comment by AHuffmyer** [comment]
Resolved with ASCA analysis here: https://ahuffmyer.github.io/ASH_Putnam_Lab_Notebook/Analysis-of-Variance-Simultaneous-Component-Analyses-ASCA-for-CEABIGR-project/
