### ISSUE TITLE
ID mussel samples for methylation analysis

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1802]

**Comment by ChrisMantegna** [comment]
So this is less straightforward than I anticipated.
1. The assays ran were p450 and SOD. The p450 indicates response to aromatic chemicals like PAH's only. The SOD assay is a general stress response.
2. The results in hand are less similar than expected. There are about 85 samples across the 312 that I will rerun for SOD this weekend. The plate values fall outside the range of my standard curve. I didn't do a thorough check when I went in to rerun BCAs and now I have to back in. I don't believe that will change the outcome drastically, but that is a  high number of samples to rerun.
3. The values can be found [here](https://github.com/ChrisMantegna/WDFWmussels/blob/main/data/biomarkerprelim.csv).
4. Right now, the SOD results are more interesting than the p450. Leading me to project that choosing the lowest sites and the highest sites for each biomarker may be the best bet. Each site has 4 samples but 2 per site might be enough, or increasing site number versus sample number might be better? Thoughts?
5. What is your preferred deadline for a decision? Right now, Saturday will be tight but Monday EOD will work.

**Comment by ChrisMantegna** [comment]
Based on the hypothesis that DNA methylation in mussels will differ in response to contaminant exposure in Puget Sound, I want to pick  Penn Cove and Elliot Bay, Myrtle Edwards mussels for comparison. Each site has 3/4 close in value that could make this comparison work. If there needs to be a tighter comparison of pair at each site, that can happen as well.
Thoughts?

**Comment by sr320** [comment]
Provide a sample list for methylation analysis with respective data

**Comment by sr320** [comment]
This week? Funds have to be spent

**Comment by ChrisMantegna** [comment]
Knowing that there are distinct difference in SOD activity between Elliott Bay, Myrtle Edwards and Hood Canal, I'd like to see if I could petition to look at the those sites *and* the penn cove reference site. There are 4-6 samples for each site, but I think taking the two closest mussels per site might be a way to go?

**Comment by sr320** [comment]
Where is analyte data most different?

**Comment by ChrisMantegna** [comment]
I have attached the screenshot of the summed analytes (for viewing ease) found at each of the three sites, Elliott Bay Myrtle Edwards, Hood Canal and Penn Cove Reference. Analytes in black aren't different, analytes in red are definitely different, and analytes in orange show difference between only 2 of the 3 sites. 

<img width="1444" alt="Screenshot 2024-04-22 at 2 14 35 PM" src="https://github.com/RobertsLab/resources/assets/81385272/92eeb013-2d15-48df-aaf3-06e8fa1df81e">

The analyte data across the other sites don't show as many categories in agreement. For instance, Elliott Bay against anything is always the highest but Dick Gilmur boat launch at Commencement Bay shows higher values then Elliott Bay at 2 of the 5 PAH categories.  

There are no sites that are consistently lower in detected analytes than Hood Canal.

Penn Cove Reference site could be debated at the middle of the pack.

**Comment by ChrisMantegna** [comment]
Where are we standing on this? Do we want to go with the Hood Canal site and the Elliott Bay site? Is there something I need to do?
