### ISSUE TITLE
Add Ariana as editor to Nightingales spreadsheet

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1808]
After [creating an account for @AHuffmyer on Owl](https://github.com/RobertsLab/resources/issues/1807), please allow access to [`Nightingales`](https://b.link/nightingales) (Google Sheet) spreadsheet to document NGS data uploaded to Owl.

**Comment by kubu4** [comment]
Alrighty, I got you added as  user on Owl (https://github.com/RobertsLab/resources/issues/1807).

I've now added you as a user for our Nightingales spreadsheet. Please fill out all corresponding fields for any NGS data you add to Owl/nightingales.

Please let us know if you have any questions/problems. Thanks!

**Comment by AHuffmyer** [comment]
Thank you!
