### ISSUE TITLE
Quarto notebook missing menu items

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1809]
My notebook is missing the menu items (navbar?):

![image](https://github.com/RobertsLab/resources/assets/4514104/7e8a9cc9-7dc0-4a18-8485-bb99d59312f5)

---

This is an example of what should look like:

![image](https://github.com/RobertsLab/resources/assets/4514104/c3fb429b-3ccb-4397-9e5d-2f2de955fde5)

---

I'm not sure what's happened. Unfortunately, I'm not entirely sure when the navbar disappeared.

Anyone have any suggestions?

Link to notebook code:

https://github.com/RobertsLab/sams-notebook

**Comment by sr320** [comment]
I am going to call it if you remove line 13 and 14

https://github.com/RobertsLab/sams-notebook/blob/90565461b6bad0a984e329ee6e3882c3cedc8ec2/_quarto.yml#L13

(last commit yaml) it will work.. broke with the indention

**Comment by kubu4** [comment]
Thanks. Kinda figured it was related to that commit, but didn't have any thoughts. I'll give it a shot!

**Comment by kubu4** [comment]
Okay, managed to resolve this, by relocating the `execute:` block to a different section of the YAML.
