### ISSUE TITLE
DIA issue: Step 2c

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#181]
[Step 2C](https://github.com/RobertsLab/resources/blob/master/protocols/DIA-data-Analyses.md#step-2c-modify-tabular-digested-proteome) in DIA protocol
I had this issue last time I did this and we fixed in issue #107 .

I am on the computer in 209 - not sure which bird it is - but I can't seem to do the "awk" or "head" in the command line. Here is what I tried and what happened:
![capture6](https://user-images.githubusercontent.com/14934314/36335465-0d1d8ef6-1335-11e8-9e51-50ecb8a5599b.PNG)

What am I doing wrong? Are things not installed on this computer, too?

**Comment by kubu4** [comment]
That doesn't look like a Git Bash window to me. Might need to install Git Bash. If so, follow instructions for installing Git Bash that are linked in Issue #107.

**Comment by grace-ac** [comment]
Thanks Sam! Will do.

**Comment by kubu4** [comment]
You should check and see if Git Bash is already installed, first.
