### ISSUE TITLE
Subscription to Scite for Ariana 

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1810]
Could I use some of the annual software funds for a subscription to Scite? https://scite.ai/

**Comment by sr320** [comment]
So do you want to purchase via treq or get reimbursed via treq?

**Comment by AHuffmyer** [comment]
I can purchase via treq! I still do not have access to treq - waiting on UW to add me to the system.

**Comment by sr320** [comment]
with treq you should be ready to go on this...

**Comment by AHuffmyer** [comment]
Yes, I'll go ahead and purchase and request a reimbursement through Treq. What budget should I use?

**Comment by AHuffmyer** [comment]
@sr320 confirming it is ok to purchase subscription for one year - price is $144.
