### ISSUE TITLE
Size and expression distribution figures for CEABiGR lncRNA

### ISSUE THREAD

**Issue by zbengt** [RobertsLab/resources#1811]
I'm making simple descriptive figures for my CEABiGR lncRNA work. I've already done an initial stab here for size:
https://zbengt.github.io/2024-01-11-00-CEABiGR_sizedistributionmd/

Ariana and I discussed expanding the size range to focus more on the >1000 category since the majority of lncRNAs fall in this category. Should I be eliminating things less than <200 since that does not technically fit the definition of a lncRNA?

Also going to plot expression distribution with my count matrix. Should I separate these by sex (male/female) and/or treatment (control/exposed)? And average counts per lncRNA? Ariana and I also discussed plotting expression by length distribution to get a better idea of which lengths have the highest number of transcripts expressed.

Not a super straightforward questions, but looking for thoughts on how best to present this data!

**Comment by sr320** [comment]
> Should I be eliminating things less than <200 since that does not technically fit the definition of a lncRNA?

no - leave in

**Comment by sr320** [comment]
> And average counts per lncRNA?

I would do total
