### ISSUE TITLE
Order request for 5G of Resazurin salt and 0.1% DMSO from Sigma

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1812]
Resazurin salt: https://www.sigmaaldrich.com/US/en/product/sigma/r7017 

Please also order 0.1% DMSO from Sigma 

We would love to use this on Wednesday the 28th out at Point Whitney if possible to receive by then. 

Thank you!

**Comment by kubu4** [comment]
> 0.1% DMSO from Sigma

Volume?

Also, I please need a budget number.

**Comment by kubu4** [comment]
> Resazurin salt: https://www.sigmaaldrich.com/US/en/product/sigma/r7017

1g of 5g?

**Comment by sr320** [comment]
5g Resazurin

**Comment by sr320** [comment]
14-9189

**Comment by sr320** [comment]
100 ml  mol bio grade? of DMSO

**Comment by kubu4** [comment]
Heads up, these might not make it to Seattle by 2/28...

**Comment by kubu4** [comment]
@sr320 - That budget is not coming up in Workday (other budgets pull up without issue).

**Comment by AHuffmyer** [comment]
If they don't come in in time that's ok. We can do this test the following week!

**Comment by sr320** [comment]
> @sr320 - That budget is not coming up in Workday (other budgets pull up without issue).

try Worktags: | 19 | AQUATIC&FISHERY SCIENC | FIELD PROGRAM SUPPORT | 149189 | BU133 | CC100948 | RS100364 | FD134 | FN170 | PG107622

**Comment by kubu4** [comment]
Submitted.

**Comment by AHuffmyer** [comment]
Thank you Sam!
