### ISSUE TITLE
Gannet Access

### ISSUE THREAD

**Issue by zbengt** [RobertsLab/resources#1813]
I locked myself out of gannet a while ago, could I get a password reset?

**Comment by kubu4** [comment]
Did you forget your password or are you unable to login? Or, both?

If you forgot your password, the login process has an option for resetting your password: https://128.95.149.52:5001

If you know your password and are still unable to login, it's likely your IP address got blocked. I'll poke through the logs and see if I notice anything.

**Comment by zbengt** [comment]
Pretty sure it's the latter, but I'll try password reset first!

**Comment by zbengt** [comment]
I got this password reset email. Does this mean I need to go to gannet physically? Also, I vaguely remember getting the error message that I was blocked and the administrator would be notified.

"If you have forgotten your password, please follow these steps:

1. Use a paper clip to gently press and hold down the RESET button for 4 seconds until you hear a beep, and then release the button immediately.
2. Launch Web Assistant in a web browser and double-click on your RackStation.
3. On the login page, enter admin in the username field and leave the password field blank.
4. On the next page, please select an administrators account from the drop-down list and set a new password.
5. Sign in with your new password. For security reasons, the "admin" account will automatically be deactivated once you reset the password for any administrators account or create a new administrators account.

From Gannet"

**Comment by kubu4** [comment]
No need to physically go to Gannet.

I'll reset your password momentarily...

**Comment by zbengt** [comment]
Worked! Thank you
