### ISSUE TITLE
Liquid nitrogen for sampling on Wednesday 

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1814]
How do we go about getting some liquid nitrogen in a dewar? We would like to have some out at Point Whitney for sampling on Wednesday. Grace and Kathleen and Eric will be coming out for the sampling and could pick up the nitrogen on Tuesday to bring with them Wednesday.

**Comment by kubu4** [comment]
Liquid nitrogen is available at UW Chemistry Stores.

We have a "dry shipper" type of dewar which is safe for transporting in personal vehicles. Would the dry shipper work (you'd have to have samples in tubes, and then drop tubes in dry shipper to snap freeze)?

Alternatively, dry ice and ethanol (to create a dry ice/ethanol bath) are both safe for transporting in personal vehicles.

**Comment by AHuffmyer** [comment]
Either option would work - dry ice and ethanol or the dry shipper. What is the cost difference between the two? Maybe that will help us decide.

**Comment by kubu4** [comment]
I have no idea what the cost is for liquid nitrogen, nor the dry ice. We've never actually checked before...

**Comment by sr320** [comment]
> I have no idea what the cost is for liquid nitrogen, nor the dry ice. We've never actually checked before...

cost does not matter. will do what is easier

**Comment by AHuffmyer** [comment]
Dry shipper with nitrogen is preferred so that samples can be safely transported back to freezers.

**Comment by kubu4** [comment]
Using the dry shipper will require it to be filled at least 24hrs before transport. Here are the instructions:

https://github.com/RobertsLab/resources/blob/master/equipment_manuals/cryoscience_CXR100_LN2_dewar_dry_shipper_instructions.pdf

**Comment by AHuffmyer** [comment]
Great! Could we fill it on Tuesday morning? It would be transported Wednesday morning.

**Comment by kubu4** [comment]
You can fill it whenever.

Do you need/want me to fill it? That's not a problem.

If so, I'll need worktag(s) to provide to Chemistry Stores.

**Comment by AHuffmyer** [comment]
That would be great if you are planning to be on campus! If not we can see if Eric, Kathleen, or Grace could also fill it. @sr320 what worktag should we use for nitrogen?

**Comment by sr320** [comment]
> I'll come in.

It would be ideal to coordinate with Eric so you can either go over qPCR results or get something on the machine. I think he is coming in Monday?

**Comment by sr320** [comment]
> what worktag should we use for nitrogen?

Worktags: | 19 | AQUATIC&FISHERY SCIENC | FIELD PROGRAM SUPPORT | 149189 | BU133 | CC100948 | RS100364 | FD134 | FN170 | PG107622

**Comment by kubu4** [comment]
> I think he is coming in Monday?

Looks like he's in today, but I don't see anything listed for next week.

**Comment by kubu4** [comment]
> Could we fill it on Tuesday morning?

I'll be in on Monday, in order to coordinate qPCR stuff with Eric, and will fill it then. It's supposed to stay cold for 14 days, so should be fine.

**Comment by kubu4** [comment]
All set. In FTR 132, as mentioned here https://github.com/RobertsLab/resources/issues/1817#issuecomment-1965123643.
