### ISSUE TITLE
Sample Viz Code help

### ISSUE THREAD

**Issue by ChrisMantegna** [RobertsLab/resources#1815]
Hello!

I am trying to visualize my biomarker data found [here](https://github.com/ChrisMantegna/WDFWmussels/blob/main/data/biomarkerfull.csv). I would like to separate them by site for easy quick assessment. 

Thank you Ariana!

**Comment by AHuffmyer** [comment]
Here is an example you can try. You will have to edit paths to files and output directories as needed.   

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
biomarker<-read_csv("~/Desktop/biomarkerfull.csv")

str(biomarker)
```

```{r}
plot<-biomarker%>%
  
  ggplot(aes(x=site_name, y=SOD))+

  geom_boxplot()+
  geom_point(position=position_dodge(0.3), alpha=1, size=1)+

  xlab(expression(bold("Site"))) +
  ylab(expression(bold(paste("SOD (mg protein)"^-1)))) +
  theme_classic()+
  #ylim(-10, 150)+ #adjust this to remove values you are going to exclude 
  theme(legend.position="right")+
  theme(axis.text.x=element_text(angle=90, hjust=1)); plot

ggsave(plot=plot, filename="~/Desktop/biomarker.png", width=15, height=8)
```

In the ggplot script I added a ylim() function which will trim the y axis. Here is the plot with all values:  

![biomarker](https://github.com/RobertsLab/resources/assets/32178010/afdb8859-d090-48cc-ac49-cf4727caab27)

And here is the plot with the big negative value not shown:  

![biomarker_ylim](https://github.com/RobertsLab/resources/assets/32178010/7288b5d6-84d8-41a3-a165-fe35168fc6a7)

Happy plotting! :)

**Comment by ChrisMantegna** [comment]
You are amazing. Thank you!
