### ISSUE TITLE
Shellfish Field Experiment Ideas

### ISSUE THREAD

**Issue by ChrisMantegna** [RobertsLab/resources#1816]
- Goal is to generate experimental ideas that we have the budget to execute to build upon existing work in the lab. 
- Target species are triploid oysters and/ or mussels
- Application is aquaculture process improvement re: stock health and building anticipatory monitoring tools
- Existing data to support: WDFW water quality data proxied by the Mussel Watch program whole mussel and tissue targeted assays for legacy chemical and metal contaminants in Puget Sound

**Comment by shedurkin** [comment]
Current idea is experiment investigating stress priming in triploid and diploid C.gigas. Reciprocal stress exposure with spat, then outplant to field for a summer, moniter suite of environmental variables, and regularly sample oysters to evaluate physiological condition.

**Comment by ChrisMantegna** [comment]
I like the time series aspect. I was thinking about looking at gut microbiome of mussels at Penn Cove a few sites based on the biomarker work. This  [map](https://github.com/ChrisMantegna/WDFWmussels/blob/main/map/Screenshot%202024-03-04%20at%201.54.54%E2%80%AFPM.png) is a quick kepler map that shows my sites by biomarker expression. 
The p450 expression is the white to blue dots, the darker the dot the higher the expression. The SOD expression is in oranges where the larger the radius the higher the expression. There are several sites with overlap and it may be interesting to pick sites that are high in p450, high in SOD, and high in both with Penn Cove as a control to see if there are any differences in microbial community and/ or indication of a synergistic effect.
