### ISSUE TITLE
Prepare equipment for Feb 28th sampling for oyster lifestage carryover project

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1817]
Hi all! We need to prepare equipment to bring on our sampling day on Wednesday the 28th. @shedurkin, @graceleuchtenberger, and @Eric-Ess could you please help prepare this equipment and bring with you on Wednesday? 

See our planning document [here for more details on the day](https://github.com/RobertsLab/project-gigas-carryover/blob/main/lifestage_carryover/notebooks/Planning-20240228-sampling.md).   

- [ ] Liquid nitrogen/dewar/dry shipper 
	- Fill and pick up on Monday (Sam) 
	- Transport Wednesday with folks driving from Seattle/by ferry
	
- [ ] RNA/DNA shield or RNA later (~250 mL) and 70% ethanol (~150 mL). This can be pre-aliquotted into tubes or done during sampling (see tube list below). Please bring at least ~50-100 mL extra of RNA later and 70% ethanol in case we need to take more samples than what was planned. 

- [ ] Tubes pre-labeled
        - Tubes no. 1-100: Screw cap tubes left empty (100 tubes)
        - Tubes no. 101-160: Snap cap tubes with 750 µL of 70% ethanol for DNA (160 tubes)
        - Tubes no. 161-400: Snap cap tubes with 750 µL of RNA Later for RNA sampling (240 tubes)
	- 100-200 extra tubes of snap cap and screw cap in case we want to sample more on that day 
	- Please label with a number on the top and on the side of each tube with a running number and project code (top = "1"; side = "LCO-24; 1").  Store in tube boxes with labels on the box that state the tube numbers in each box (e.g., "Box 1: Tubes 1-81"). 
	- Please label as many tubes as you have time for - we can label more the day of as needed.

- [ ] Markers 

- [ ] Gloves (1 box of each size) 

- [ ] Ethanol 70% for sterilizing equipment (500 mL squirt bottle) 

- [ ] Bleach 10-20% for sterilizing equipment (500 mL squirt bottle) 

- [ ] DI water/water for cleaning (500 mL squirt bottle) 

- [ ] Pipettes (P1000, P200, and P10) and 1 box of tips for each size

- [ ] Bench paper or paper to keep surfaces clean when sampling (if possible)

- [ ] Shucking knifes x 3-4 

- [ ] Razer blades x 3-4 

- [ ] Tweezers x 3-4 

- [ ] Pencils and pens

Ariana will prep loggers, heaters, data sheets, and equipment at Point Whitney on Monday. Ariana can also drive to campus Tuesday afternoon if needed to help. 

Post status and any questions on this issue thread. Thanks all!

**Comment by kubu4** [comment]
> 480 tubes (maximum) for RNA/DNA
160 tubes for physiology/metabolomic samples

Heads up - I don't think the dry shipper has the capacity to store that many tubes. It can hold ~100 tubes, maximum.

**Comment by kubu4** [comment]
> Tubes pre-labeled

If going into liquid nitrogen (i.e. dry shipper), these should all be screw cap tubes.

Also, someone should confirm whether or not we have enough...

**Comment by AHuffmyer** [comment]
Thanks Sam! Those for RNA/DNA can be snap cap (just going in RNA/DNA shield) and the others should be screw cap. I'll update the list above.

**Comment by AHuffmyer** [comment]
Can anyone in the lab today confirm that we have enough of RNA/DNA shield/later and tubes?

**Comment by AHuffmyer** [comment]
Also Sam, we should be good on the dry shipper. The RNA/DNA samples don't need to be frozen.

**Comment by AHuffmyer** [comment]
I can just plan to sample only as many physiology samples as can fit in the dry shipper.

**Comment by graceleuchtenberger** [comment]
I'm not sure where the RNA later is, but I can start putting together a little box for all our tools (probably on Monday). Do you have a naming convention for the tubes that you'd like us to follow?

**Comment by AHuffmyer** [comment]
See above checklist for a list of tube numbers and what needs to go in each tube. Thank you!

**Comment by AHuffmyer** [comment]
@shedurkin @graceleuchtenberger @Eric-Ess could you provide an update here on the status of these checklist items today? Thank you!

**Comment by kubu4** [comment]
LN2 dry shipper has been filled.

Due to the elevator in FTR being broken, I could not carry the shipper nor the cart upstairs. They have been left in the corner of FTR 132.

**Comment by shedurkin** [comment]
Ok the rest of the materials are in two boxes on a table in the conference room (FTR 230):

- spray bottles of DI H2O, 10% bleach, and 70% ethanol
- 500mL of 70% ethanol
- RNA later (250mL recieved in 2023, additional that may be expired)
- waterproof markers, pens, pencils
- 4 tweezers
- 5 razors
- 4 oyster shucking knives (two with broken tips?)
- gloves (1box ea S,M,L)
- pipettors (P10, P200, P1000) with 1 box tips each
- tubes (snap cap and screw cap, currently unlabelled)

**Comment by graceleuchtenberger** [comment]
Got up to 150 labeling the tubes (100 screw cap, 50 snap cap), will try to do more tomorrow.

**Comment by mattgeorgephd** [comment]
FYI, there should be a large tote (black, yellow lid) in FTR 213 filled with equipment/supplies I used to take on sampling days to Pt. Whitney. I think it was underneath the steel bench as you walk in.

**Comment by AHuffmyer** [comment]
Thank you everyone!

**Comment by AHuffmyer** [comment]
@shedurkin @Eric-Ess @graceleuchtenberger thank you for gathering all supplies! Please remember to take the dry shipper as well!
