### ISSUE TITLE
Quarto notebook URL redirects to an individual NB entry?

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1818]
Well, this is probably related to #1809 (moving the `execute:` block in the YAML), but now when I visit my notebook (https://robertslab.github.io/sams-notebook/), it redirects me to here!

https://robertslab.github.io/sams-notebook/posts/2016/2016-11-04-computing-retrieve-data-from-amazon-ec2-instance/index.html

Possible this is a broken render or something??!!

Code is here: https://github.com/RobertsLab/sams-notebook

I'm probably going to revert back to a state before the most recent render and see if I can resolve this... Ugh. 😠

**Comment by sr320** [comment]
related-- why even have 

```
execute:
  freeze: true
```

?

**Comment by kubu4** [comment]
Well, I decided to get "fancy" and have code chunks in my notebook. However, some of the notebook posts code chunks with paths for programs on Raven and some notebook posts have code chunks with path for programs on my laptop. These paths differ between the two computers... 

Rendering notebook posts on one computer or the other breaks rendering because the two computers can't execute all of the code chunks that exist in my various notebook entries, due to the differences in paths/programs/etc.

So, in theory, when you have

```
execute:
  freeze: true
```
 
code chunks should _not_ be executed during a "global" render of a Quarto project.

Currently, that's not my experience - the rendering still attempts to execute the code chunks. I've also tried caching the notebook entries with the code chunks, and then sync-ing the cache folder that's created, but that hasn't prevented rendering from trying to execute the code chunks, either.

**Comment by sr320** [comment]
Might not work depending on your workflow, but once you render you could _ignore_ the html product (or before push, revert html).

**Comment by kubu4** [comment]
FIXED!

Basically, I edited one of my computational notebooks so that the various paths for programs was the same on my laptop and on Raven. Then, was able to successfully render on Raven.

Will try to avoid "global" notebook renders from now on, and stick to individual NB renders!

Thanks for weighing in!
