### ISSUE TITLE
Lab Meeting Slidedeck

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#182]
For Prospective Student Days, as part of our lab meeting Friday, I would like folks give a 5 min presentation of their work. Max 3 slides. Please lay off the methods and focus scientific question, results and implications...

Please post slides here and I will compile in one slidedeck.
thanks

**Comment by yaaminiv** [comment]
[My slides](https://github.com/yaaminiv/yaaminiv.github.io/blob/master/presentations/2018-02-23-Prospective-Student-Day-Slides.pptx). Can edit before Friday if needed.

**Comment by grace-ac** [comment]
Here are my slides, too! [link](https://docs.google.com/presentation/d/1cZqrtFvz3dSO1H8226YxwurHmT5DLICDSkv6Hfvbwt8/edit?usp=sharing)

I can edit before Friday if needed, as well.

**Comment by jldimond** [comment]
[jay_slides.pptx](https://github.com/RobertsLab/resources/files/1746433/jay_slides.pptx)

**Comment by kaitlynrm** [comment]
Here are [my slides](https://github.com/kaitlynrm/OysterSeedProject/blob/master/KRM-PSDslides.pptx)! I can edit them if needed.

**Comment by laurahspencer** [comment]
[PSD_Spencer.pptx](https://github.com/RobertsLab/resources/files/1750095/PSD_Spencer.pptx)
