### ISSUE TITLE
Develop means to assess oyster feeding regime

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1820]
Can we develop a automated means to capture feeding - filling of bucket.

float switch that pings web?

Less desirable would be button some hits when filling..

monitor chlorphyll in tanks?

**Comment by sr320** [comment]
possibly just mount temp logger 3/4 up on can and secondarily tell when trash can fills? 
https://www.onsetcomp.com/products/data-loggers/mx2201

**Comment by AHuffmyer** [comment]
A temp logger is a good idea. Apex also has water fill indicators: https://www.bulkreefsupply.com/lls-liquid-level-sensor-neptune-systems.html?ab_version=B&utm_term=&utm_campaign=EL+%7C+ACQ_Smart_Shopping+%7C+ROAS+%7C+All+Products&utm_source=adwords&utm_medium=ppc&hsa_acc=7373341438&hsa_cam=17740353356&hsa_grp=&hsa_ad=&hsa_src=x&hsa_tgt=&hsa_kw=&hsa_mt=&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=CjwKCAiAivGuBhBEEiwAWiFmYd7wmLk43DMLZDDB4ZkoljKtXCkuQxdoZHllh5W-CWCy23rQtQAmGBoCXeoQAvD_BwE

**Comment by sr320** [comment]
nice - probably makes sense to do both.

**Comment by AHuffmyer** [comment]
The square magnetic sensor we found is actually a water level sensor! https://www.bulkreefsupply.com/mos-magnetic-optical-sensor-neptune-systems.html?ab_version=A&utm_term=&utm_campaign=EL+%7C+ACQ_Smart_Shopping+%7C+ROAS+%7C+All+Products&utm_source=adwords&utm_medium=ppc&hsa_acc=7373341438&hsa_cam=17740353356&hsa_grp=&hsa_ad=&hsa_src=x&hsa_tgt=&hsa_kw=&hsa_mt=&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=Cj0KCQiA84CvBhCaARIsAMkAvkKITmJWmrMe-UP2R8I8NGBYO-50mPb3H4ErfaOEri4V9IiDEeYJDy4aAlNvEALw_wcB

**Comment by AHuffmyer** [comment]
We added the optical sensor (link above) last week. It lets us know when it is submerged or not submerged. We got it working on 3/5/2024. We will need a second one or a temperature probe paired with this to be able to tell the rate at which food is being used from the bucket.
