### ISSUE TITLE
Add Paper Drafts to Pubathon

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1821]
Add links using Google Doc as primary document (with setting anyone with link can edit)

at https://robertslab.github.io/resources/Pubathon/
(2024 Contenders)

can use current formatting of other entreis

- [x] Zach - oyster lncRNA
- [x] Chris - mussel enzyme
- [x] Chris - eDNA 
- [ ] Grace - mussel differential expression
- [x] Grace - seastar differential expression
- [x] Grace - another seastar paper
- [ ] Eric - oyster stress experiment
- [x] Kathleen - cod growth / RNA-seq
- [x] Kathleen - deep dive ncRNA expression paper
- [x] Megan - clam OA differential expression
- [x] Megan - Ostrea lurida sex-determination genes

Please feel free to add more but these readily come to mind.

**Comment by AHuffmyer** [comment]
My manuscripts are updated (n=3)!

**Comment by sr320** [comment]
@meganewing @shedurkin @Eric-Ess @ChrisMantegna remember to check off here when added

**Comment by shedurkin** [comment]
updated!
