### ISSUE TITLE
FastQC on Cod RNA-seq

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1822]
RNA-seq data is in from Azenta.

When you have a second, please run FastQC on the raw RNA-seq data and enter URLs for each FastQC HTML output file for its corresponding FastQ file in the [`nightingales`](https://docs.google.com/spreadsheets/d/1_XqIOPVHSBVGscnjzDSWUeRL7HUHXfaHxVzec-I-8Xk/edit?usp=sharing) Google Sheet (I shared access with you a bit ago). The columns for FastQC links are Column V & Y.

Don't hesitate to ask any questions!

And, here is link to my notebook with link to raw data:

https://robertslab.github.io/sams-notebook/posts/2024/2024-02-21-Data-Received---Pacific-cod-RNA-seq-Azenta-Project-30-943133806/

**Comment by shedurkin** [comment]
I'm downloading the reads now to run fastqc -- once I've fastqcd the raw reads do I need to do a trimming step? Some places in the lab handbook state that [trimming is necessary](https://eagle.fish.washington.edu/whale/pub/jsr37309_1r8rd0.pdf), while others say [it isn't](https://robertslab.github.io/resources/bio-Gene-expression/#trimming) for gene expression analysis...

**Comment by sr320** [comment]
first step is to run fastqc prior to trimming

**Comment by shedurkin** [comment]
yes, I'm doing that now. Once I've QCd do I need to trim, or should I move directly to kallisto?

**Comment by sr320** [comment]
will need to see output first.. can just drop notebook url here.

**Comment by shedurkin** [comment]
notebook post: https://shedurkin.github.io/Roberts-LabNotebook/posts/projects/pacific_cod/2024_03_04_RNAseq_QC_trimming.html

Didn't get the chance to add individual fastqc urls o the spreadsheet today, but I'll do that first thing tomorrow

**Comment by kubu4** [comment]
FYI - There's a formula setup in the Google Sheet to help populate the URLs, so you can just "drag and fill". Check an existing entry to see how the formula works and whether or not you need to tweak it for your samples.

This way, you don't have manually enter each of them!
