### ISSUE TITLE
Schedule site visit with Taylor Shellfish and Nisbet Oyster Co.

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1823]
Steven, could you please provide contact information for Taylor Shellfish and Nisbet Oyster Co. so that we can schedule a site visit? Or even better, introduce me over email? 

Let's look at potentially doing site visits the week of March 18th. I could do visits on the 19th, 20th, or 21st. @sr320 would those days work for you?

**Comment by sr320** [comment]
Ideally arrange at shellfish meeting - @mattgeorgephd is planning on introducing you to folks..

FTR on WSG and USDA? 
Collaborator: Benoit Eudeline, Ph.D., Taylor Shellfish Co.
Collaborator: Kathleen Nisbet Moncy, Nisbet Oyster Co.
Collaborator: Erik Anderson, Westcott Bay Shellfish Co.

@mattgeorgephd is this correct?

**Comment by sr320** [comment]
Ideally arrange at shellfish meeting - @mattgeorgephd is planning on introducing you to folks..

FTR on WSG and USDA? 
Collaborator: Benoit Eudeline, Ph.D., Taylor Shellfish Co.
Collaborator: Kathleen Nisbet Moncy, Nisbet Oyster Co.
Collaborator: Erik Anderson, Westcott Bay Shellfish Co.

@mattgeorgephd is this correct?

**Comment by mattgeorgephd** [comment]
This list looks correct. Happy to introduce over email. Kathleen will be at WSG shellfish conference on 3/11. Haven't met Erik before - best point of contact is Emily.

**Comment by AHuffmyer** [comment]
Perfect! Looking forward to meeting everyone at the shellfish meeting and I can schedule visits then.

**Comment by mattgeorgephd** [comment]
Also Laura Kraft, WSU Extension Agent in Long Beach.

**Comment by AHuffmyer** [comment]
Thank you for the email introductions, Matt!

**Comment by AHuffmyer** [comment]
Sent emails to Benoit, haven't heard back yet. Will call tomorrow if I haven't heard anything

**Comment by AHuffmyer** [comment]
AH has a call with Kathleen this week to talk about field gear
