### ISSUE TITLE
Add size data from 2/26 to growth data frame and analyze spat images for size 

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1826]
I took new growth measurements today and images of spat. We can add size measurements to dataframe and analyze spat images. Uploaded here: https://github.com/RobertsLab/project-gigas-carryover/tree/main/lifestage_carryover/data/size/notebook_images/20240226

**Comment by Eric-Ess** [comment]
Can measure on imageJ today. Where should I record the measurements?

**Comment by AHuffmyer** [comment]
You could record in the data frame on Git Hub here: https://github.com/RobertsLab/project-gigas-carryover/blob/main/lifestage_carryover/data/size/gigas-lengths.csv. You could also record in a Google Sheet and then copy over, whichever works best for you. Thank you!

**Comment by Eric-Ess** [comment]
Left is treatment and right is control?

**Comment by AHuffmyer** [comment]
Yes!

**Comment by Eric-Ess** [comment]
Added spat measurements to data frame. Can add other measurements from notebook later.

**Comment by AHuffmyer** [comment]
Thank you!

**Comment by Eric-Ess** [comment]
Added the rest of the growth data to the data frame.

**Comment by AHuffmyer** [comment]
Amazing, thank you!
