### ISSUE TITLE
Step3- PECAN- DIA 2015 Oyster

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#183]
I am re-doing the DIA analysis with all 16 raw files from the 2015 oysterseed experiment.

I am at [Step 3a](https://github.com/RobertsLab/resources/blob/master/protocols/DIA-data-Analyses.md#step-3a-create-two-text-files-that-indicate-path-for-1-the-reference-peptide-list-in-silico-protein-digestion-and-2-spectra-data-mzml-files). 

Does PECAN have to be re-done for all files? Or can it just be for the four files missing from the original run?

**Comment by emmats** [comment]
Was the pecan blib file you are using provided by me? If so, I will verify that I used the right files. If the correct files were not used to generate it, then it needs to be re-run.

**Comment by grace-ac** [comment]
It was provided by you!

**Comment by emmats** [comment]
What is the file name?

**Comment by grace-ac** [comment]
I think it's called 2015oysterseed ...?

**Comment by grace-ac** [comment]
or wait, I think it's oysterseed2.blib

**Comment by emmats** [comment]
That has the correct raw files in it so we don't have to re-run pecan.

**Comment by grace-ac** [comment]
oh awesome! ok, thank you
