### ISSUE TITLE
Design next round of seed exposures at Point Whitney 

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1832]

**Comment by sr320** [comment]
Idea 1 -
get a daily temperature ramp with a more extreme stress every week? The more extreme would involve presence, and could be combo

**Comment by AHuffmyer** [comment]
Started new work with seed and adult this week - see notebook post here: https://ahuffmyer.github.io/ASH_Putnam_Lab_Notebook/Oyster-Individual-Growth-and-New-Seed-Exposures/
