### ISSUE TITLE
Plot final growth measurements of lifestage carry over from Feb measurements

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1833]

**Comment by AHuffmyer** [comment]
![mean_lengths](https://github.com/RobertsLab/resources/assets/32178010/7fbf2f35-693b-46ea-8a8d-26c454488d13)
![mean_lengths_box](https://github.com/RobertsLab/resources/assets/32178010/a90a219d-917c-4db5-b9ab-a7933f620e4d)

Growth is significantly higher in spat from the treated condition in February. No other differences.

**Comment by sr320** [comment]
@Eric-Ess can we get a notebook post that explains the experiment / history of these data?

**Comment by AHuffmyer** [comment]
In particular, if we could add information on where the stocks came from and any family information available, that would be great!

**Comment by Eric-Ess** [comment]
[post](https://eric-ess.github.io/data-explanation/). happy to make changes if I missed important details, though I think this is everything I know.

**Comment by AHuffmyer** [comment]
Looks great! Could you just add that the adults were from Pacific Hybreed and that the diploids and triploids are siblings. Thank you!

**Comment by sr320** [comment]
@Eric-Ess can you make a time line of events?

**Comment by Eric-Ess** [comment]
Yes I have also been thinking this. Do you have any recommendations on what to use to illustrate this?

**Comment by sr320** [comment]
Paper and pencil might be a good start...
I often use powerpoint-google presentations for this..
Ariana uses Adobe Illustrator but that is beyond my expertise.
