### ISSUE TITLE
Protocol recommendation for RNA or cDNA clean up

### ISSUE THREAD

**Issue by valeste** [RobertsLab/resources#1834]
Experiencing issues getting expected relative standard curves and acceptable E values for all of my genes of interest. I suspect issue to be related to the quality of the cDNA (inhibitors in the qPCR reaction mix?).

Protocol leading to cDNA synth:

1.    RNA extracted using Qiagen RNeasy Mini Kit with 10% β-mercaptoethanol (β-ME) in RLT buffer and QiaShredder column step supplemented to protocol.

2.    Quantify RNA with NanoDrop.

3.    gDNA elimination with [Invitrogen TURBO DNA-*free* Kit (Cat. No. AM1907)](https://assets.thermofisher.com/TFS-Assets/LSG/manuals/1907M_turbodnafree_UG.pdf).

4. Requantification of gDNA eliminated RNA with NanoDrop:

|    Date    	|       Sample ID      	| RNA Concentration (ng/uL) 	| A260/A280 	| 260(10mm) 	|
|:----------:	|:--------------------:	|:-------------------------:	|:---------:	|:---------:	|
| 09/30/2023 	| 9302023 0-R1 pilot   	|                      19.2 	|      1.55 	|      0.48 	|
| 09/30/2023 	| 9302023 0-R2 pilot   	|                     113.2 	|      1.85 	|      2.83 	|
| 09/30/2023 	| 9302023 0-R3 pilot   	|                     152.4 	|      1.87 	|     3.809 	|
| 09/30/2023 	| 9302023 0-R4 pilot   	|                      67.1 	|      1.77 	|     1.676 	|
| 09/30/2023 	| 9302023 5-R1 pilot   	|                      22.4 	|      1.66 	|      0.56 	|
| 09/30/2023 	| 9302023 5-R2 pilot   	|                      30.6 	|      1.68 	|     0.764 	|
| 09/30/2023 	| 9302023 5-R3 pilot   	|                        29 	|      1.67 	|     0.726 	|
| 09/30/2023 	| 9302023 5-R4 pilot   	|                      45.1 	|      1.77 	|     0.128 	|
| 09/30/2023 	| 9302023 45-R2 pilot  	|                      87.6 	|      1.82 	|      2.14 	|
| 09/30/2023 	| 9302023 45-R3 pilot  	|                      13.8 	|      1.47 	|           	|
| 09/30/2023 	| 9302023 45-R4 pilot  	|                      84.8 	|      1.83 	|      2.12 	|
| 10/25/2023 	| 10252023 0-R1 E1     	|                      12.1 	|      1.55 	|     0.305 	|
| 10/25/2023 	| 10252023 0-R2 E1     	|                      45.9 	|      1.83 	|     1.148 	|
| 10/25/2023 	| 10252023 0-R3 E1     	|                      78.4 	|      1.85 	|     1.959 	|
| 10/25/2023 	| 10252023 0-R4 E1     	|                      38.5 	|       1.8 	|     0.962 	|
| 10/25/2023 	| 10252023 5-R1 E1     	|                      83.3 	|      1.82 	|     2.082 	|
| 10/25/2023 	| 10252023 5-R3 E1     	|                      27.1 	|      1.69 	|     0.676 	|
| 10/25/2023 	| 10252023 5-R4 E1     	|                      69.5 	|      1.84 	|     1.737 	|
| 10/25/2023 	| 10252023 45-R1 E1    	|                        50 	|      1.78 	|     1.249 	|
| 10/25/2023 	| 10252023 45-R2 E1    	|                      57.3 	|      1.84 	|     1.433 	|
| 10/25/2023 	| 10252023 45-R3 E1    	|                      43.5 	|      1.73 	|     1.087 	|
| 10/25/2023 	| 10252023 45-R4 E1    	|                      60.1 	|      1.83 	|     1.505 	|
| 11/15/2023 	| 11152023 0-R1 E2     	|                      86.5 	|      1.86 	|     2.163 	|
| 11/15/2023 	| 11152023 0-R2 E2     	|                      54.7 	|      1.66 	|     1.367 	|
| 11/15/2023 	| 11152023 0-R3 E2     	|                      37.4 	|      1.72 	|     0.935 	|
| 11/15/2023 	| 11152023 5-R1 E2     	|                      58.4 	|      1.66 	|     1.459 	|
| 11/15/2023 	| 11152023 5-R2 E2     	|                      69.7 	|      1.69 	|     1.743 	|
| 11/15/2023 	| 11152023 5-R3 E2     	|                      33.7 	|      1.51 	|     0.843 	|
| 11/15/2023 	| 11152023 45-R2 E2    	|                      34.5 	|      1.44 	|     0.863 	|
| 11/15/2023 	| 11152023 45-R3 E2    	|                      16.2 	|       1.5 	|     0.405 	|
| 11/29/2023 	| 11292023 0-R1 E3     	|                      72.4 	|      1.78 	|     1.809 	|
| 11/29/2023 	| 11292023 0-R2 E3     	|                      60.3 	|      1.78 	|     1.507 	|
| 11/29/2023 	| 11292023 0-R3 E3     	|                      21.4 	|      1.61 	|     0.534 	|
| 11/29/2023 	| 11292023 5-R1 E3     	|                      12.7 	|      1.43 	|     0.318 	|
| 11/29/2023 	| 11292023 5-R2 E3     	|                      15.5 	|      1.57 	|     0.387 	|
| 11/29/2023 	| 11292023 5-R3 E3     	|                      64.4 	|      1.76 	|     1.609 	|
| 11/29/2023 	| 11292023 45-R1 E3    	|                      80.6 	|      1.82 	|     2.016 	|
| 11/29/2023 	| 11292023 45-R2 E3    	|                      49.3 	|      1.77 	|     1.231 	|
| 11/29/2023 	| 11292023 45-R3 E3    	|                      64.3 	|      1.79 	|     1.607 	|  

**Drop in RNA 260/280 of about 0.2 across each sample**

 
Refer to [notebook post ](https://valeste.github.io/tough-tunicates/posts/qPCR-relative-standards/) for full details if needed.

Is it normal for the quality of the RNA to drop so much after using Turbo DNA free kit?

**Comment by kubu4** [comment]
Okay, I'll start this with a "warning" - there's a LOT to unpack here, because you're not really just asking about the RNA.

You're real concern is the qPCR results.

So, let's get into it! Be prepared for a lot of reading and a lot of questions!

In an attempt to make this a bit easier, I'll try to divide it into sections.

---

## RNA

> Is it normal for the quality of the RNA to drop so much after using Turbo DNA free kit?

Yes, this is not surprising. You're enzymatically fragmenting DNA. Enzymes are proteins. The 260/280 ratio measures absorbance of nucleotides (~260nm) relative to the absorbance of protein (~280nm). Thus, you've added more protein to your samples, so your sample "purity" is expected to decrease.

Questions:

1. Do you have access to a Qubit (the Roberts Lab has one, if you don't already)? The Qubit is far more sensitive and accurate than the NanoDrop, but will not provide you with A260/280 and A260/230 ratios.
2. Do you have the A260/230 ratios? This information will provide a clearer picture on whether or not there are any possible inhibitors that got carried over (things like phenol, alcohol, excessive salts result in a poor A260/230 ratio).

---

### DNase

1a. Which DNase protocol did you follow - standard or rigorous?
1b. What was the makeup of your DNase reactions (e.g. 1uL DNase, 5ug of RNA, 25uL water, etc)? 

---

### cDNA

1. How much RNA did you use for your reverse transcription reactions?
3. What was the makeup of your reverse transcription reactions (e.g. 5uL buffer, 5ug RNA, 10uL, 1uL dNTPs)?

---

### PCR and Primers

Your two gels mostly appear to consist of primer dimers (except ACTb).

Questions:

1. What are your expected amplicon sizes for each primer set? I did see a note in your notebook entry on primer design that said you were targeting 500bp, but it'd be helpful/useful to include that info in your table(s).
2. What was the makeup of your end-point PCR reactions (e.g. 10uL 2x polymerase, 0.5uL 10uM P<sub>f</sub>, 0.5uL P<sub>r</sub>, 9uL H<sub>2</sub>O, etc)?
3. What were your cycling parameters for end-point PCR?
4. Where is your 18s primer set on either of the two gels?
5. What were your cycling parameters for your qPCR reactions?
6. Were your NTCs clean? It be cool if you could color code your amplification plots to have the NTCs be a different color than the rest of the samples - that would make it easier to quickly evaluate this aspect of things.

---

Okay, I think that's it for now. If you're so inclined, it could be good to go over this stuff at lab meeting, as there are certainly others in the lab who may have to do qPCR and it would be a good excuse to discuss all the ins/outs. Plus, sometimes a topic with this much breadth can be a bit difficult to handle via back-and-forth on GitHub.

However, the decision is yours! I'll happily help out here or during lab meeting or even a one-on-one video chat if desired.

We'll get things figured out!

**Comment by sr320** [comment]
Agree with @kubu4 - Science hour would have loved this, but otherwise lets tackle at lab meeting. To offer crude / correct? framework to how I would consider qPCR output.

1. NTC amp - start over.
2. Melt curve single peak - next step. Not- try one more PCR with higher anneal - and/or then move to new primer.
3. Amplification looks good? Done.

(I could be corrected but no need for standard curves) - but related if I am interpreting correct - technical replicates concern me.

**Comment by valeste** [comment]
**RNA**

> 1. Do you have access to a Qubit (the Roberts Lab has one, if you don't already)? The Qubit is far more sensitive and accurate than the NanoDrop, but will not provide you with A260/280 and A260/230 ratios.

No, I don't currently have access to a Quibit out at UW Tacoma.

> 2.  Do you have the A260/230 ratios? This information will provide a clearer picture on whether or not there are any possible inhibitors that got carried over (things like phenol, alcohol, excessive salts result in a poor A260/230 ratio).

The NanoDrop available for use at UW Tacoma is a NanoDrop Lite and only reports 260/280 ratios. I agree it would be good to have info for the 260/230 ratios as well.

**DNase**

> 1a. Which DNase protocol did you follow - standard or rigorous?

Standard

> 1b. What was the makeup of your DNase reactions (e.g. 1uL DNase, 5ug of RNA, 25uL water, etc)?

| **gDNA Elimination Component** | **per 1 rxn (uL)** |
|--------------------------------|--------------------|
| 10x DNase Buffer               | 2                  |
| Turbo Enzyme                   | 1                  |
| RNA sample                     | 20                 |
| **Total**                      | **23**             |

**cDNA**

> 1.  How much RNA did you use for your reverse transcription reactions?

96.8 ng per sample rxn

> 2.  What was the makeup of your reverse transcription reactions (e.g. 5uL buffer, 5ug RNA, 10uL, 1uL dNTPs)?

| **cDNA synthesis Component**   | **per 1 rxn (uL)** |
|--------------------------------|--------------------|
| SuperScript IV VILO Master Mix | 2                  |
| Nuclease-free water            | variable           |
| RNA sample                     | variable           |
| **Total**                      | **8**              |


**qPCR**

>1.What are your expected amplicon sizes for each primer set? I did see a note in your notebook entry on primer design that said you were targeting 500bp, but it'd be helpful/useful to include that info in your table(s).

Below is the info for amplicon length per primer set. I couldn't find all the info for primers pulled from the literature but aside from ACTb all are below 200 bp as I described for my aims in designing.


| Number 	| Gene     	| Forward Primer (5'-3')      	| Reverse Primer (5'-3')     	| NCBI Accession Number (If complete CDS) 	| Botryllus Contig Sequence (if no complete CDS was found) 	| Amplicon Length 	| Source                          	|
|--------	|----------	|-----------------------------	|----------------------------	|-----------------------------------------	|----------------------------------------------------------	|-----------------	|---------------------------------	|
| 1      	| BAX      	| CATTGACCTTGCGTGTTATTGG      	| AAGATGTCCTTGGTGGGTTG       	| KU948200.1                              	| None                                                     	| 97              	| in house                        	|
| 2      	| POU3     	| CAGTAGGTCTTCGCATCCATC       	| CGTTTGCATCGTTGGTGTAAG      	| KU948203.1                              	| None                                                     	| 80              	| in house                        	|
| 3      	| PolB     	| GGCTTCACAATCAATGAGTATTCC    	| AGCAATCTTTCCGCATTCATTC     	| None                                    	| botctg092056                                             	| NA              	| in house                        	|
| 4      	| TNF      	| GTTTCAGTCAACACCTTGTGTC      	| AATCTCGACCGCTGACTTATAC     	| None                                    	| botctg065850                                             	| 131             	| in house                        	|
| 5      	| SOXB1    	| GGGAATGTGTTCATCCTCTGG       	| TGAATCCAGGAGTTACTCAAGTTC   	| KU948203.1                              	| None                                                     	| 116             	| in house                        	|
| 6      	| MYC      	| GAAGTCCTGGCTAAGATGCTAC      	| AGCGTCAAGAAGGAAGTACG       	| KU948203.1                              	| None                                                     	| 119             	| in house                        	|
| 7      	| AIF1     	| GGATTCTCTCACCGATGGAATAG     	| CCTGACTTGGAGCCTTTATGG      	| KU948202.1                              	| None                                                     	| 102             	| in house                        	|
| 8      	| SOD1     	| CAATCCATATAACAAGGTTCATGGC   	| TGATATCCACACAGGCACAAC      	| EE743567.1                              	| None                                                     	| 107             	| in house                        	|
| 9      	| PARP1    	| AATTTGGCACCGCTCATTTC        	| TGCAAGACCTTCAGCTTCTC       	| KU948201.1                              	| None                                                     	| 94              	| in house                        	|
| 10     	| SIRT6    	| ATTAGTACCGCGTCTGGAATAC      	| GGATGGAATCGCTTCTTCAAATC    	| None                                    	| botctg109566                                             	| 114             	| in house                        	|
| 11     	| IAP7     	| GGTCTCTTCACGGACATCTTC       	| GCTCAGTATGTTGTGCTTGTTC     	| KU948203.1                              	| None                                                     	| 111             	| in house                        	|
| 12     	| HSP70    	| CGAGAAGTTGAAGGACAAGATCTCCG  	| TCTCTGCAGTCTGGTTGTTGTCGAGC 	| NA                                      	| NA                                                       	| NA              	| doi:10.1016/j.ydbio.2017.10.023 	|
| 13     	| Mortalin 	| TTCATGATACCGAAACCAAGATGGACG 	| AATTTCCTCCTTGATGGCATCCACC  	| KY212120.1                              	| None                                                     	| 79              	| doi:10.1016/j.ydbio.2017.10.023 	|
| 14     	| ACTb     	| GTAGGTAGTCTCGTGAATTC        	| CACGCCATCTTGCGTCTGGA       	| NA                                      	| NA                                                       	| 321             	| doi:10.1016/j.dci.2006.12.009   	|
| 15     	| 18s      	| GGCAGCCTCCGGGAAACCAAAGTC    	| CTGGTGGTGCCCTTCCGTCAATTC   	| NA                                      	| NA                                                       	| NA              	| doi:10.1016/j.ydbio.2017.10.023 	|

> What was the makeup of your end-point PCR reactions (e.g. 10uL 2x polymerase, 0.5uL 10uM Pf, 0.5uL Pr, 9uL H2O, etc)?

| **EP-PCR Component**                                 | **per 1 rxn (uL)** |
|------------------------------------------------------|--------------------|
| PCR Master Mix (brand TBD)                           | 12.5               |
| Nuclease-free water                                  | 9.5                |
| Forward Primer (5 uM)                                | 1                  |
| Reverse Primer (5 uM)                                | 1                  |
| 1:3 dilution of pooled (per treatement) cDNA         | 1                  |
| **Total**                                            | **10**             |


> What were your cycling parameters for end-point PCR?

Need to double check but roughly these parameters.


| Stage      	| Step          	| Temperature (C) 	| Duration (sec) 	| Cycles 	|
|------------	|---------------	|-----------------	|----------------	|--------	|
| PCR        	| Denature      	| 95              	| 15             	| 40     	|
| PCR        	| Anneal/Extend 	| 60              	| 60             	| 40     	|
| Hold        | Hold            | 4                 | infinity        | 1       |

> Where is your 18s primer set on either of the two gels?

Gel annotation is mislabeled. Where it says 40s it should say 18s.

> What were your cycling parameters for your qPCR reactions?

| Stage      	| Step          	| Temperature (C) 	| Duration (sec) 	| Cycles 	|
|------------	|---------------	|-----------------	|----------------	|--------	|
| Hold       	| Hold          	| 50              	| 120            	| 1      	|
| Hold       	| Hold          	| 95              	| 600            	| 1      	|
| PCR        	| Denature      	| 95              	| 15             	| 40     	|
| PCR        	| Anneal/Extend 	| 60              	| 60             	| 40     	|
| Melt Curve 	| Denature      	| 95              	| 15             	| 1      	|
| Melt Curve 	| Anneal/Extend 	| 60              	| 60             	| 1      	|
| Melt Curve 	| Dissociation  	| 95              	| 1              	| 1      	|



> Were your NTCs clean? It be cool if you could color code your amplification plots to have the NTCs be a different color than the rest of the samples - that would make it easier to quickly evaluate this aspect of things.

The only NTCs that were "clean" were the ones for the primers I labeled as trash that failed to amplify in target reactions with cDNA. Beta actin also had a clean NTC.

Note that for some of the GOI's like AIF1 and SOD1, the NTC Ct value is nearly identical to the rest of the Ct values. (Meaning the Ct value remains the same across decreasing concentrations of cDNA and in the NTC, likely a primer dimer artifcat and no amplification potentially occuring?)

| Target Name 	| Task 	| CT           	|
|-------------	|------	|--------------	|
| BActin      	| NTC  	| Undetermined 	|
| BAX         	| NTC  	|       32.548 	|
| SOD1        	| NTC  	|       26.921 	|
| SIRT6       	| NTC  	| Undetermined 	|
| IAP7        	| NTC  	|       32.048 	|
| HSP70       	| NTC  	| Undetermined 	|
| Mortalin    	| NTC  	|       32.660 	|
| 18s         	| NTC  	|       32.623 	|
| POU3        	| NTC  	|       33.793 	|
| PolB        	| NTC  	| Undetermined 	|
| TNF         	| NTC  	| Undetermined 	|
| MYC         	| NTC  	|       32.153 	|
| AIF1        	| NTC  	|       27.873 	|
| PARP1       	| NTC  	| Undetermined 	|

**Comment by sr320** [comment]
> Note that for some of the GOI's like AIF1 and SOD1, the NTC Ct value is nearly identical to the rest of the Ct values. (Meaning the Ct value remains the same across decreasing concentrations of cDNA and in the NTC, likely a primer dimer artifcat and no amplification potentially occuring?)

this is liking simply contamination.

**Comment by sr320** [comment]
Also, have a look at https://robertslab.github.io/resources/Lab-Protocols/#qpcr-data-analysis

**Comment by kubu4** [comment]
Thanks for all this! Here's another lengthy response!


### DNase

- How much inactivation reagent did you add to each reaction?

---

### Reverse Transcription

- From what I can tell, the manual for SuperScript IV VILO Master Mix indicates to run reactions in 20uL total volume. Your reaction is only 8uL. Looking at the amount of master mix reagent you used (2uL), I'm guessing you were cutting reactions in half, but half of 20uL would be 10uL - not 8uL. Why did you end up with a total volume of 8uL?

---

### End-point PCR

- Why run this on a gel? Why not just run qPCR to check products?

---

### qPCRs

- NTCs
  - Like @sr320 mentioned, if you get any amplification in your NTCs, it's either contamination and/or primer dimers.

- Technical reps
  - Like @sr320 mentioned, your technical qPCR reps for most of your primer sets (beta actin and 18s are exceptions) aren't great.

---

So, where does that leave us?

Well, personally, I'd run each primer set again  (in triplicate, including NTCs), using just your undiluted pooled cDNA - don't bother with standard curves. Need to make sure qPCR reactions for each primer set are working (or not) before worrying about primer efficiencies. Try to improve technical reps and clean NTCs and then make further decisions.
