### ISSUE TITLE
Source of Pacific cod cds file?

### ISSUE THREAD

**Issue by shedurkin** [RobertsLab/resources#1835]
There's a cds file in the [pacific cod repo](https://github.com/RobertsLab/project-cod-temperature/blob/main/data/Gadus_macrocephalus.coding.gene.V1.cds) titled "Gadus_macrocephalus.coding.gene.V1.cds", but I can't see where it originally came from. I've checked both the repo and the last code that used this cds (Steven's [transcriptome annotation](https://github.com/RobertsLab/project-cod-temperature/blob/main/code/03-transcriptome-annotation.Rmd), but I can't find details. What is the source of this cds file?

**Comment by sr320** [comment]
might be github but those links do not take me anywhere..

**Comment by shedurkin** [comment]
oops, I had the paths linked instead of the urls -- fixed

**Comment by sr320** [comment]
also I would use what is on NCBI - also in Handbook

https://robertslab.github.io/resources/Genomic-Resources/#gadus-macrocephalus-pacific-cod
