### ISSUE TITLE
Prepare files to send to SAFS grant manager for Sea Grant application

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1838]
Check off and add documents here for the following list:  

Forms required to send to Lisa: 

- [x] SR: Budget form [draft sent to Lisa](https://docs.google.com/spreadsheets/d/10aZPD22BW_F53SaTCH3yITzD66tmn6o3/edit#gid=1324482939)
- [x] SR: confirm eRA commons ID with Lisa 
- [x] AH: Copy of letter of intent [available here](https://drive.google.com/drive/u/4/folders/1ixXap1vbp8v0hDBBdjVJbghY05VFDL7Q)
- [x] SR: Confirm cost share as salary with Lisa
- [x] SR: Email Jim about tribal agreement letter and letter of collaboration of partnership with Point Whitney [available here](https://docs.google.com/document/d/17xZy3lqx6S-JcVaFGqxQ4weuwqbItHle/edit?usp=drive_link&ouid=109182465336502227018&rtpof=true&sd=true)
- [x] SR: Letter of support from Neil USDA [available here](https://drive.google.com/file/d/1ripzMBH6sKfiN25lYiKCvkODNYfIbRoU/view?usp=drive_link)
- [x] NEPA Questionnaire [completed here](https://docs.google.com/document/d/1zltChU1hiuEN8MdlvQYdWazQM3pxjlWX/edit) 
- [x] AH: Letter of support from Ashleigh Epps [completed here](https://drive.google.com/file/d/1E-3i1cL4-RjGuQMATqdBTIZuvJDOV5Hi/view?usp=drive_link)
- [x] SR: Letter of support from NOAA and Mac [available here](https://drive.google.com/file/d/1rSip69EimRiKx_pbc94MisQqI9sOA8nv/view?usp=drive_link)
- [x] SR: Current and Pending Support 
[NOAA CPS Template.docx](https://github.com/RobertsLab/resources/files/14518950/NOAA.CPS.Template.docx)
- [x] SR: CV
- [x] AH: Current and Pending Support [draft needs WSG funds information here from SR](https://docs.google.com/document/u/4/d/1dYIN1FyZwuyHczS8KSatdjfAapLn1Yvx/edit?usp=drive_web&ouid=109182465336502227018&rtpof=true)
- [x] AH: CV [completed here](https://drive.google.com/drive/u/4/folders/1ixXap1vbp8v0hDBBdjVJbghY05VFDL7Q)
- [x] AH: [Budget justification draft sent to Lisa](https://docs.google.com/document/d/1gg1Pcqdc3fS2k8IVyURhzkPRWHtpNMHzYQo9HW-eSes/edit#heading=h.n9i60h9etw6k)
- [x] SR: [Demographics information](https://docs.google.com/forms/d/e/1FAIpQLSdIjYevtFZD2cFT5e_6nsd_YNNbgOuu-i7UdcPVIDN5VndaVg/viewform) and statement that it has been completed to sg.grants@noaa.gov
- [x] AH: [Demographics information](https://docs.google.com/forms/d/e/1FAIpQLSdIjYevtFZD2cFT5e_6nsd_YNNbgOuu-i7UdcPVIDN5VndaVg/viewform) and statement that it has been completed to sg.grants@noaa.gov
- [x] AH: Data sharing/management plan [2 page max; ready for SR check here](https://docs.google.com/document/d/10sLWaui_9gDwy7Jr7k2Q5a-ZGttRWAPnS729iFgha0s/edit)
- [x] AH: Project narrative [draft here](https://docs.google.com/document/d/1rGW13Lw493e7VyEBy4bFifH6rfpUpjMVVQBvdJIt7Hw/edit)
- [x] AH: Epps CV [available here](https://docs.google.com/document/d/1WFV0XiUXOmmttJqNJiO2Jh05QkSFvOWS/edit?usp=drive_link&ouid=109182465336502227018&rtpof=true&sd=true)

**Comment by AHuffmyer** [comment]
[Roberts_Huffmyer_UW_LOI.pdf](https://github.com/RobertsLab/resources/files/14519033/Roberts_Huffmyer_UW_LOI.pdf)

[Huffmyer_CV_March2024.pdf](https://github.com/RobertsLab/resources/files/14519034/Huffmyer_CV_March2024.pdf)

**Comment by AHuffmyer** [comment]
AH completed and sent email to Sea Grant for demographics form on 3/6/2024

**Comment by AHuffmyer** [comment]
[Project title and abstract](https://docs.google.com/document/d/1rGW13Lw493e7VyEBy4bFifH6rfpUpjMVVQBvdJIt7Hw/edit) available to send to collaborators for letters of support. Edits on this abstract are welcome!

**Comment by AHuffmyer** [comment]
@sr320 here is my current/pending support. The highlighted section needs details from the WSG before it is ready. 
[NOAA.CPS.Huffmyer.docx](https://github.com/RobertsLab/resources/files/14529164/NOAA.CPS.Huffmyer.docx)

**Comment by AHuffmyer** [comment]
Data management plan ready for @sr320 check here: https://docs.google.com/document/d/10sLWaui_9gDwy7Jr7k2Q5a-ZGttRWAPnS729iFgha0s/edit

**Comment by AHuffmyer** [comment]
@sr320 do you have a previous NEPA questionnaire draft that I could adapt for this proposal?

**Comment by sr320** [comment]
https://www.dropbox.com/scl/fi/2szs04vd7kdsz0unw6obb/NEPA.docx?rlkey=sqm8r6t04f8jzxpcrj55i39qv&dl=0


Steven B. Roberts, Professor School of Aquatic and Fishery Sciences
University of Washington Fisheries Teaching and Research (FTR) Building -
Office 232 1140 NE Boat Street - Seattle, WA 98105 robertslab.info
<https://faculty.washington.edu/sr320/> - ***@***.*** - @sr320
vm:206.866.5141 - cell:360.362.3626 schedule a zoom call:
https://d.pr/gsgxVJ

**Comment by AHuffmyer** [comment]
NEPA ready for @sr320 check here: https://docs.google.com/document/d/1zltChU1hiuEN8MdlvQYdWazQM3pxjlWX/edit

**Comment by sr320** [comment]
Made NEPA edits, should be good to go.

**Comment by AHuffmyer** [comment]
Epps letter of support received and uploaded to Drive (https://drive.google.com/file/d/1E-3i1cL4-RjGuQMATqdBTIZuvJDOV5Hi/view?usp=drive_link)

**Comment by AHuffmyer** [comment]
Final budget ready for @sr320 final check [here](https://docs.google.com/spreadsheets/d/10aZPD22BW_F53SaTCH3yITzD66tmn6o3/edit#gid=1324482939) and final budget justification ready for @sr320 check [here](https://docs.google.com/document/d/1gg1Pcqdc3fS2k8IVyURhzkPRWHtpNMHzYQo9HW-eSes/edit#heading=h.n9i60h9etw6k)

**Comment by AHuffmyer** [comment]
Waiting on Epps CV and comments on proposal. Emailed reminder for feedback and CV to her on 3/20.

**Comment by AHuffmyer** [comment]
Epps CV available in folder here: https://docs.google.com/document/d/1WFV0XiUXOmmttJqNJiO2Jh05QkSFvOWS/edit?usp=drive_link&ouid=109182465336502227018&rtpof=true&sd=true

**Comment by AHuffmyer** [comment]
Proposal narrative at correct length and in full draft form, ready for SR edits and approval. AH will generate a clean copy without PaperPile links when it is finalized.

**Comment by AHuffmyer** [comment]
All documents on Drive here: https://drive.google.com/drive/u/4/folders/1c-YzZ_otu03x96vP5xOIpvC6Y7i4GRyH
