### ISSUE TITLE
Conduct another round of resazurin trials to look for differences under stress

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1842]
It would be great to measure change in resazurin in a set of the same animals at ambient and then at high. We could run an ambient plate and then refresh the liquid, then run that same plate of animals again at high temperature. This would let us say that we can detect changes under stress!

**Comment by sr320** [comment]
Lets get a variety of small seed in 12 well plate, a few larger ones in mini dishes.. a few controls.. (the later could use second 12 well plate)

measure, wait 30 minutes, measure, wait 30 minutes, measure,

replace resazurin, place at 35C, 30min measure, wait 30 minutes measure, place at room temp. wait 30 minute measure

record size of all oysters

**Comment by kubu4** [comment]
Are all oysters in that cold room? Are there any that should _not_ be used?

**Comment by sr320** [comment]
Yes- in cold room

Anything is fine to use

Steven B. Roberts, Professor School of Aquatic and Fishery Sciences
University of Washington Fisheries Teaching and Research (FTR) Building -
Office 232 1140 NE Boat Street - Seattle, WA 98105 robertslab.info
<https://faculty.washington.edu/sr320/> - ***@***.*** - @sr320
vm:206.866.5141 - cell:360.362.3626 schedule a zoom call:
https://d.pr/gsgxVJ

**Comment by kubu4** [comment]
Completed. Files are here:

https://github.com/RobertsLab/project-gigas-carryover/tree/main/lifestage_carryover/data/resazurin_trial_02

Haven't had a chance to write up notebook or README yet, but here's the _very_ quick rundown on plate layout/experimental design:

- 12-well plate had oysters in wells A01-C01.
- Wells C02-C03 were negative controls.
- Well C04 was empty (i.e. no liquid of any kind).
- Time 0 (t0) measurements were taken _before_ the addition of oysters.
- For heat stress, resazurin assay media was distributed to wells/dishes and pre-heated to 35<sup>o</sup>C for 45mins prior to the t0 measurement (and transfer of oysters).

Size/weight measurements are currently here (Google Sheet). I'll add fluorescence data when I have the chance (probably first thing tomorrow morning):

- [20240312-cgig-resazurin-trial-02](https://docs.google.com/spreadsheets/d/1WeA-PG_pkg-f9SmyNFP30Jn5rhkWhEKJaMReuF-oK8M/edit?usp=sharing)

**Comment by AHuffmyer** [comment]
Thank you so much Sam! I'll work on analyzing the data!

**Comment by kubu4** [comment]
Here's a link (GitHub) to the weight/size/fluorescence all compiled into a single CSV:

https://github.com/RobertsLab/project-gigas-carryover/blob/main/lifestage_carryover/data/resazurin_trial_02/20240312-cgig-resazurin-trial-02.csv
