### ISSUE TITLE
Rationale on February oyster sampling

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1843]
![](http://gannet.fish.washington.edu/seashell/snaps/Monosnap_20240228_sampling_metadata_2024-03-11_08-12-51.png)

Trying to ID sample for processing but just want to confirm design here.. we are not able to look at hardening but rather only acute stress response as prior treatment is the same?

**Comment by AHuffmyer** [comment]
The left-spat have a treated history and the right-spat have the control history. You could compare left-spat to right-spat, both will have ambient and acute high treatments from February. On Mar 11, 2024, at 08:18, Steven Roberts ***@***.***> wrote:﻿
as a follow up I am trying to ID samples for qPCR that would correlate with hardening and growth phenotype we saw
