### ISSUE TITLE
Extract RNA from oyster spat

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1844]
from 0228 sampling

![](http://gannet.fish.washington.edu/seashell/snaps/Monosnap_20240228_sampling_metadata_2024-03-11_14-32-00.png)

samples
| ----- |
|  223 |  
|  254 |  
|  234 |  
|  243 |  
|  264 |  
|  244 |  
|  257 |  
|  211 |  
|  285 |  
|  256 |  
|  266 |  
|  200 |

**Comment by AHuffmyer** [comment]
These were sampled by putting entire spat into the RNAlater. We tried to crush the shell once it was in the tube. Hopefully the quality of RNA is ok! If not, let’s talk about how to optimize sampling. I could resemble from these same groups using a different method if needed. On Mar 11, 2024, at 14:35, Steven Roberts ***@***.***> wrote:﻿
from 0228 sampling




samples




223


254


234


243


264


244


257


211


285


256


266


200

**Comment by AHuffmyer** [comment]
It may not be realistic, but it would be really cool to see if we can get any qPCR data for heat shock genes in the treated vs control history spat for the National Sea Grant proposal. Grant application is due early April, so we would need this data within the next two weeks if we want to add it to the proposal. What do you think? It's totally ok if that is not possible in that amount of time.

**Comment by kubu4** [comment]
Yep, this is doable. I'm planning on being in lab at least once a week to get this stuff done.

**Comment by sr320** [comment]
@AHuffmyer Are these the ideal samples or are others preferred?

**Comment by AHuffmyer** [comment]
If we are sampling only one group I think we would process the "spat" samples instead because they showed differential growth. But if we are able, we could do both seed and spat to give a lifestage comparison.

**Comment by sr320** [comment]
@AHuffmyer Can you list the specific samples by ids that are priority?

**Comment by AHuffmyer** [comment]
I have added a metadata sheet called `20240314_rna_extractions` to the repo located [here](https://github.com/RobertsLab/project-gigas-carryover/blob/main/lifestage_carryover/data/sampling_metadata/20240314_rna_extractions.csv). I have also included this table below. There is a column for the priority level. Spat samples ( n=12) are most important (priority = 1) and seed samples (n=12) are next (priority 2). If possible, we should process both seed and spat. If we are limited on time/capacity, we should focus on spat first. 

| tag_tank    | lifestage | tube_ID | conditioning_treatment | acute_treatment | preservation_method | 20240314.priority |
|-------------|-----------|---------|------------------------|-----------------|---------------------|-------------------|
| right-seed  | seed      | 223     | control                | high            | RNA later 750 uL    | 2                 |
| right-seed  | seed      | 234     | control                | high            | RNA later 750 uL    | 2                 |
| right-seed  | seed      | 243     | control                | high            | RNA later 750 uL    | 2                 |
| right-seed  | seed      | 244     | control                | high            | RNA later 750 uL    | 2                 |
| right-seed  | seed      | 254     | control                | high            | RNA later 750 uL    | 2                 |
| right-seed  | seed      | 264     | control                | high            | RNA later 750 uL    | 2                 |
| left-seed   | seed      | 200     | treated                | high            | RNA later 750 uL    | 2                 |
| left-seed   | seed      | 211     | treated                | high            | RNA later 750 uL    | 2                 |
| left-seed   | seed      | 256     | treated                | high            | RNA later 750 uL    | 2                 |
| left-seed   | seed      | 257     | treated                | high            | RNA later 750 uL    | 2                 |
| left-seed   | seed      | 266     | treated                | high            | RNA later 750 uL    | 2                 |
| left-seed   | seed      | 285     | treated                | high            | RNA later 750 uL    | 2                 |
| right-spat  | spat      | 206     | control                | high            | RNA later 750 uL    | 1                 |
| right-spat  | spat      | 262     | control                | high            | RNA later 750 uL    | 1                 |
| right-spat  | spat      | 274     | control                | high            | RNA later 750 uL    | 1                 |
| right-spat  | spat      | 282     | control                | high            | RNA later 750 uL    | 1                 |
| right-spat  | spat      | 284     | control                | high            | RNA later 750 uL    | 1                 |
| right-spat  | spat      | 289     | control                | high            | RNA later 750 uL    | 1                 |
| left-spat   | spat      | 220     | treated                | high            | RNA later 750 uL    | 1                 |
| left-spat   | spat      | 226     | treated                | high            | RNA later 750 uL    | 1                 |
| left-spat   | spat      | 242     | treated                | high            | RNA later 750 uL    | 1                 |
| left-spat   | spat      | 253     | treated                | high            | RNA later 750 uL    | 1                 |
| left-spat   | spat      | 296     | treated                | high            | RNA later 750 uL    | 1                 |
| left-spat   | spat      | 298     | treated                | high            | RNA later 750 uL    | 1                 |

**Comment by sr320** [comment]
@kubu4 
Just want to confirm - is this complete?

**Comment by kubu4** [comment]
Yep. 

https://robertslab.github.io/sams-notebook/posts/2024/2024-03-19-RNA-Isolation---C.gigas-Lifestage-Carryover-Seed-and-Spat/
