### ISSUE TITLE
Analyze resazurin trials #1 and 2 results

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1846]
Analyze data from first resazurin trial and heat stress trial

**Comment by AHuffmyer** [comment]
Ran preliminary analysis on resazurin trial with control and stress oysters (trial #2). The [script can be found here](https://github.com/RobertsLab/project-gigas-carryover/blob/main/lifestage_carryover/scripts/resazurin_AH.Rmd) and the output is [here](https://github.com/RobertsLab/project-gigas-carryover/tree/main/lifestage_carryover/output/resazurin). 

@sr320 @kubu4 I plotted the corrected fluorescence values as the change in values from T0 to T1 minus the change observed in negative controls. I then plotted this scaled by oyster weight. I removed the largest oysters since they were not submerged in the solution. The results are really cool! It shows that response scales with oyster size and the slope of that relationship changes under stress. 

![treatment_scale_weights](https://github.com/RobertsLab/resources/assets/32178010/752d3097-18c1-4bf9-9a6d-4b110b22e974)

**Comment by kubu4** [comment]
Neat!
