### ISSUE TITLE
Custom Respirometry Chambers

### ISSUE THREAD

**Issue by sarahtanja** [RobertsLab/resources#1847]
Seeking advice and feedback for a custom respirometry chamber setup (for my anemone-leachate-heat project).

My goals are to make a chamber that you can load from the bottom up with:
- stir bar
- petri dish mount
- 60mm petri dish (with adhered anemone!)
- watertight lid
- watertight  temp probe port
- watertight oxygen optode port
- backfill & purge valve (to fill chamber with seawater treatment)

My current design uses:
- a 0.5 pint (~200mL) mason jar
- a [wide-mouth mason jar lid from Amazon](https://www.amazon.com/Pack-Wide-Mouth-Mason-Lids/dp/B0CFST67NG/ref=sr_1_1_sspa?dib=eyJ2IjoiMSJ9.2HN8HVSOLKu5NuUeSkR0b97__fyi0Bpjn3rpzFY2a3i4Cor1onGVRDKP4rGDaCnIGQaf55mdUmOpUHfnAXoZjn5Sam8TCQaSlq8YAHyuKF5QaZqYhaCgG9Vuv1i1pg1rAHnAjBLf2VFZl5u6gnfxyVSLn54rE9je96-jdZsjEaVfPHHKpJVTy7OvC1vRo0KaIgEvFiYRrtTFS5bJZGm3LCvMTfmHzl0CnkQPH7z7Ugre-tYJ8iijtcZb8qqlgam479w2yNu4YKq0ZGaJ5a04egnFSblgYgBq6egclXiSxGc.P96KEYwMYkFZBVShjnf_wWF34HYhi1HFkGX9T9a-Wbo&dib_tag=se&hvadid=486290794208&hvdev=c&hvlocphy=9033316&hvnetw=g&hvqmt=b&hvrand=3014786341708260655&hvtargid=kwd-1071809506931&hydadcr=4699_10064490&keywords=mason+wide+mouth+jars+lids&qid=1710434188&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1)
- a 3D printed petri dish stand (courtesy of husband Michael)
- [Blue Robotics WetLink Penetrators](https://bluerobotics.com/product-category/cables-connectors/penetrators/)
- Blue Robotics Vent Plug, Vacuum plug, Backfill adaptor

I will make a post with photos to share in this issue. 
Any guidance on what other groups have had success with is much appreciated!

**Comment by AHuffmyer** [comment]
Here are some images of respirometry chambers we made for recent work in Moorea. They are made from acrylic and are custom made and glued together. The lid can be pressed down as far as needed to reduce the water volume and the acrylic chamber could be cut higher if more volume is needed. There are racks built in to hold the animal off the bottom of the chamber with a stir bar. Chambers are set in plastic bins as water baths with heaters and recirculating pumps with a magnetic stir plate underneath. Lights were hung in racks above the array. The chambers were sealed using tubing that was cut long ways and wrapped around the edge of the lid. This sealing system on the lid wasn't ideal, but it worked!

![IMG_1311](https://github.com/RobertsLab/resources/assets/32178010/a1018492-7e70-4b52-823d-2c49adaa68fd)
![IMG_1319](https://github.com/RobertsLab/resources/assets/32178010/0eb02926-57d2-4132-9813-df85fb34d70a)
![IMG_1586](https://github.com/RobertsLab/resources/assets/32178010/026f7b48-4bb6-4d24-b253-2f98adba7a65)

**Comment by AHuffmyer** [comment]
For exchanging water, we have been using a syringe. This takes some time but does work.

**Comment by AHuffmyer** [comment]
Hollie Putnam has a parts list for these chambers. If you are interested let me know and I can send to you.

**Comment by sarahtanja** [comment]
This is an awesome setup, and great to see visually. The stands my husband 3D printed are similar:
 
![PXL_20240314_212818142](https://github.com/RobertsLab/resources/assets/86446350/b4dab7c5-0668-4a74-aa84-a5898cebb5c5)
![PXL_20240314_212907517](https://github.com/RobertsLab/resources/assets/86446350/0f4c3f17-46b1-4566-8701-857b2fbaf9b3)
![PXL_20240314_212922196](https://github.com/RobertsLab/resources/assets/86446350/9f49f09b-c1f5-4c5f-a30f-d7a3191b8acc)

The stands in your setup look commercially bought, could you share/find out from Hollie what that part in particular is?

One of my lingering design questions is probe penetration length... where is the best location for the probes? My guess is they have to be as close to the specimen as possible? With a smaller chamber, It's more of a challenge to fit the probe.... 


My WetLink Penetrators are coming in the mail Tuesday, once I have them installed I will share more photos.

**Comment by AHuffmyer** [comment]
The stands in ours are actually just egg crate (see an example [here](https://www.homedepot.com/p/PLASKOLITE-4-ft-x-2-ft-Suspended-Egg-Crate-Light-Ceiling-Panel-1199233A/202025149)), but 3D printing works great! To make ours out of egg crate we just cut out pieces and glued little legs on them. 

If you have a stir bar and stir plate, the probe just needs to be submerged. You can actually introduce a lot of variability in the readings by having the probe too close to the animal (think oxygen boundary layers). Therefore, having the probe submerged but not touching the animal is just fine. The water stirring will make sure the oxygen concentration is homogenous in the chamber. 

Here is an example - you can see the probes submerged but not touching the coral. To keep the probe from sliding too far into the chamber, we just wrapped a bit of parafilm around the probe at the desired height. 

![IMG_1318](https://github.com/RobertsLab/resources/assets/32178010/e6614021-0540-42d7-8a7d-19b8f39fd020)

**Comment by sarahtanja** [comment]
THANK YOU !
