### ISSUE TITLE
Purchase new digital caliper and try to fix malfunctioning caliper at Point Whitney

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1850]
Today while taking growth measurements the digital caliper went haywire and started displaying highly variable and incorrect values. I temporarily fixed it by taking the battery out, cleaning it, and putting it back in. But after about 5 minutes it started malfunctioning again and I could not fix it by replacing the battery. Could we order another one and I'll try again next time to fix the current one?

**Comment by sr320** [comment]
certainly worth ordering new ones... there are standard ones at hatchery. Original were cheap on amazon - probably worth finding something more robust.

**Comment by AHuffmyer** [comment]
Ok I'll do some searching. It is nice to have the digital caliper to get +-0.1 mm resolution. We can use the standard ones in the meantime.

**Comment by AHuffmyer** [comment]
Something like this would be good. IP67 (submersion) waterproof, 150 mm, digital. $89

[Amazon link here](https://www.amazon.com/Kynup-Waterproof-Calipers-Measuring-Stainless/dp/B0BS96R2FQ/ref=sr_1_1_sspa?crid=2BUKA7IIXV7UZ&dib=eyJ2IjoiMSJ9.NpDX9vnTdrkJ4c6FJSzuBa-0Pqemz5xecsvly9H_e9JblMDgYx7bPY0sJI9FqEBItXX6QsucKcMX3DnHCo6zo3rYwM62Y2a167Yxe10stJiYStsvZ2yJxttwZNsZkYnIX1q1l2Fy9WCY_gEwj7yTmJYKCycQHvHvB9LnDyq-TdnZp5VmqUZDFTKL12vJ_EuQ79MpgPXbLIrONyOSfz6PFdTfy1oCGe8qbnY8TtAhahg.SHyIjleE04HFfdTAjuySr09_zELucKBI35p_AsXCZVY&dib_tag=se&keywords=waterproof+digital+caliper+ip67&qid=1711032365&sprefix=waterproof+digital+caliper+ip67%2Caps%2C206&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1)

**Comment by sr320** [comment]
You can go ahead and have treq order

Something like this would be good. IP67 (submersion) waterproof, 150 mm,

**Comment by AHuffmyer** [comment]
New caliper ordered via TREQ
