### ISSUE TITLE
Generating appropriate count matrix for DESeq2

### ISSUE THREAD

**Issue by shedurkin** [RobertsLab/resources#1852]
I'm working with RNAseq data from the cod project and have gotten through using kallisto and the trinity abundance_estimates_to_matrix.pl script to generate a count matrix.

The DESeq2 documentation specifies it [requires "un-normalized count data](https://www.bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#why-un-normalized-counts)" as input, which would mean the input count matrix should contain only integers. My count matrix has decimals. Looking into this mismatch has left me a little confused. I saw a couple past github issues about this (e.g. #943, #1056) where the recommendation was to just round all the counts to nearest whole number. However, the DESeq2 documentation [recommends using the package tximport](https://www.bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#transcript-abundance-files-and-tximport-tximeta) to import transcripts abundance data like that generated by kallisto. **Is using trinity to generate a gene-level count matrix effectively taking the place of using tximport?** How exactly do gene-level counts differ from transcript abundances?

**Comment by sr320** [comment]
I would do the recommended method and compare with alternative (Trinity)
