### ISSUE TITLE
Missing Pacific cod RNAseq reads -- sample 92

### ISSUE THREAD

**Issue by shedurkin** [RobertsLab/resources#1853]
I just noticed that there seems to be a missing Pacific cod RNAseq set of reads? I have a **sample 92** in my spreadsheets and in the [RNA QC report from Azenta](https://github.com/RobertsLab/project-cod-temperature/blob/main/data/Sample.QC.report.of_30-943133806_240118025106.pdf), but I don't see data for sample 92 [where the raw reads are stored](https://owl.fish.washington.edu/nightingales/G_macrocephalus/30-943133806/). Did one just get missed or did that sample not get sequenced?

**Comment by kubu4** [comment]
This is odd. Thanks for noticing! Will hit up Azenta to get some deets! I'll report back...

**Comment by shedurkin** [comment]
just wanted to check in to see if you have any updates on this @kubu4 ?

**Comment by kubu4** [comment]
Alrighty! Missing data is currently being uploaded to their servers! 

@shedurkin I'll forward you email with download credentials and you can grab it if you want. Otherwise, I'm happy to do so on the 18th.

**Comment by kubu4** [comment]
The missing cod reads for sample 92 have been added to Owl.

**Comment by shedurkin** [comment]
Neither Laura or I downloaded the sample 92 data from Owl before it died -- do you have the reads stored/backed up in an easy-to-access place @kubu4 ? It's not urgent, so if retrieving the data would be a pain we can just wait until Owl's successor is up and running.

**Comment by kubu4** [comment]
Check the Google Drive link in #1882. It should be in there (`nightingales` folder).

NOTE: It takes a little bit for the directories to load, so don't panic if you don't see the stuff you need right away.
