### ISSUE TITLE
Web Interface for NCBI

### ISSUE THREAD

**Issue by meganewing** [RobertsLab/resources#1854]
Was playing around with the NCBI web interface and noticed that some organisms don't have full list of genes even with a genome provided. Was wondering why this is? Has it not been annotated fully yet ? How can you tell if something has been annotated? If they have been annotated, what's the step between the annotated file and the web interface of gene names? Guess I'm just curious as to why things are the way they are and if anyone has any experience with the NCBI web interface. 

two examples (one with [many](https://www.ncbi.nlm.nih.gov/search/all/?term=cassostrea+gigas) genes listed and one with [few](https://www.ncbi.nlm.nih.gov/search/all/?term=ostrea+lurida))

**Comment by kubu4** [comment]
Let's try a different approach which doesn't rely on the web interface. With that being said, let's start with these quick questions:

1. What are you trying to accomplish?

2. What data are you working with?

**Comment by sr320** [comment]
Generally speaking content is there when people upload it there. 

Aligning with Sam's comment, we likely have direct knowledge or genome sequence efforts in this space and can advise on which version of public resource to use and how non-published resources might be accessible.
