### ISSUE TITLE
Dispose of glass bottles in FTR 228

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1855]
Arlighty, we've acquired more broken lab glass boxes. They're next to the cart in FTR 228.

Please box up all of the remaining empty glass bottles and dispose in the garbage dumpster outside.

Plastic bags should be tied closed (or taped tightly) before putting the lid on each box - this may require you to transfer some bottles to different boxes in order to have enough room in the plastic bag to actually be able to tie it closed.

Box lids should be taped closed and then the lids taped tightly to the box so that it cannot open when being tossed into the dumpster.

I've left a roll of packing tape on the cart handle.

Thanks so much for your help with this!

**Comment by Noahk22** [comment]
Ok that sounds good. What plastic bags are you referring to though? Also is it ok for me to leave the bottles in their current boxes or would you want be to transfer them all to broken glass boxes. Or can I just write broken glass on the side? Also, where is the dumpster specifically? Thanks!

**Comment by kubu4** [comment]
> What plastic bags are you referring to though?

Inside each of the broken lab glass boxes are plastic bags. When you assemble the new boxes, you'll need to put the provided bags inside the box before adding bottles.

> Also is it ok for me to leave the bottles in their current boxes or would you want be to transfer them all to broken glass boxes

Most of the bottles are already in broken lab glass boxes. If there's room to seal the plastic bag, then do that, add the lid for the box (I think the lids are under the qPCR machines), and tape it securely. If there's _NOT_ room to tie/seal the plastic bag, then you'll have to transfer bottles to a different broken lab glass box until you've removed enough that you _can_ seal the plastic bag.

> lso, where is the dumpster specifically? 

In the loading zone, between FTR and MAR.

**Comment by Noahk22** [comment]
I was able to complete all glass disposal yesterday!

**Comment by kubu4** [comment]
Awesome! Thanks so much!!
