### ISSUE TITLE
Suspiciously perfect PCA from cod RNAseq data...

### ISSUE THREAD

**Issue by shedurkin** [RobertsLab/resources#1856]
As part of my preliminary look at the cod RNAseq data I made a PCA (as recommended in #1774) of the liver sample data (untrimmed) and the plot I got perfectly separates samples by temperature treatment, even maintaining the temperature _gradient_! Honestly it's freaking me out, surely such a perfect PCA must be the result of an error somewhere -- does anyone have any thoughts?

[repo for all project code](https://github.com/RobertsLab/project-cod-temperature/tree/main/code)
[code to generate PCA](https://github.com/RobertsLab/project-cod-temperature/blob/main/code/07-cod-RNAseq-DESeq2.md)

![image](https://github.com/RobertsLab/resources/assets/89885240/aca453fd-49a4-4735-a637-36232bea2d25)

**Comment by laurahspencer** [comment]
Your code looks good, and I'm not surprised that liver expression is strongly influenced by temperature. Very, very cool! The only suggestion is to re-run your PCA using more genes; that _might_ reduce the clustering slightly. By default, the [DESeq2 function `plotPCA`](https://www.rdocumentation.org/packages/DESeq2/versions/1.12.3/topics/plotPCA) uses only the top 500 most variable genes. This code should run PCA using all genes in your dataset (but you can play around with the number used for `ntop=`). 

`pca_L <- plotPCA(vst(dds_L), intgroup = c("temp_treatment"), returnData=TRUE, ntop=nrow(assay(vst(dds_L))))`

**Comment by shedurkin** [comment]
Oh that's super helpful information about the plotPCA function, thank you! I reran with some different numbers of genes and got some much less perfect (but still interesting) plots!

![image](https://github.com/RobertsLab/resources/assets/89885240/e5eaa74a-e814-43b4-aaf5-c341460c7c6f)
![image](https://github.com/RobertsLab/resources/assets/89885240/5f04dbe8-23f5-46ba-829b-5ea93c171044)
![image](https://github.com/RobertsLab/resources/assets/89885240/e1258616-9b48-45c0-b4f8-9007802356f1)
