### ISSUE TITLE
finding pathways

### ISSUE THREAD

**Issue by meganewing** [RobertsLab/resources#1858]
I'm looking for find all the genes / proteins in a given pathway (eg. oocyte maturation/development). What are some ways I could do this aside from (or rather in tandem with) manually looking in literature? I've heard of strings and kegg pathways, but am not too familiar with these, and curious about any tips/tricks/recommendations.

**Comment by sr320** [comment]
great Q!

First think that target will be a multi-sequence fasta file... 

Go to String, Panther, Reactome, Kegg and simply search based on interest on function. You will likely have to id a taxa. Pick the one that is close to target, and download fastas. Might not be possible for all sites, but I spot check first couple and found. I have doubts on what can be downloaded in terms of Kegg put others might have experience

**Comment by sr320** [comment]
Another approach is using fully annotated model genome, possibly C. gigas, Lymnaea stagnalis 

ID genes in these published annotations (GO, Kegg) etc and use this as query for search lesser studied taxa
