### ISSUE TITLE
Resazurin Purchasing and Protocol

### ISSUE THREAD

**Issue by zbengt** [RobertsLab/resources#1859]
We're planning to test using Resazurin for Jose's class with Hemigrapsus (hairy shore crabs). Where have you all been ordering it from and what protocol have you been using?

**Comment by AHuffmyer** [comment]
Check out Sam's notebooks [here](https://robertslab.github.io/sams-notebook/posts/2024/2024-03-08-Resazurin---Preliminary-Respiration-Test-Using-C.gigas/) and [here](https://robertslab.github.io/sams-notebook/posts/2024/2024-03-12-Resazurin---C.gigas-Second-Trial/). 

Resazurin salt order information is on Issue #1812

**Comment by kubu4** [comment]
Roberts Lab Purchasing log also has info:

https://docs.google.com/spreadsheets/d/1DHXiiEzWhh0XHnEMvKz4TX10e69ErOWHv5Jo-ouk6x8/edit?usp=sharing

**Comment by zbengt** [comment]
Thanks!
