### ISSUE TITLE
Peak-checking importance

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#186]
@emmats  when I showed you my error rate for Skyline peak checking in issue #136  you said "~35% error rate seems OK, I guess. There's not much we can do about it."

Based on your comment about "not much we can do about it", I'm wondering:
- How important checking and adjusting 100 peptide peaks is? 
- How important calculating an error rate is?

**Comment by emmats** [comment]
I don't think you need to adjust the 100 peptide peaks. You only need to adjust DIA peaks if you are going to use them for downstream analyses. Once you do your analyses and you decide which peptides to focus on, I would go back to the data and make sure that the peaks picked are correct. 

I think it is important to understand the error rate in the data that we are analyzing and interpreting. The Skyline developers tend to think it is infallible, but we know that it misses peaks and chooses the wrong ones.

**Comment by grace-ac** [comment]
Okay, cool, so I will skip over [Step 5}(https://github.com/RobertsLab/resources/blob/master/protocols/DIA-data-Analyses.md#step-5-within-skyline-analyses) until after the analyses and peptides are chosen.
