### ISSUE TITLE
Using the plate reader

### ISSUE THREAD

**Issue by zbengt** [RobertsLab/resources#1860]
I'll be using the plate reader for Jose's class. Sam I know you'll be gone for a few weeks soon, Steven mentioned that I should ask you for a walkthrough either in person or over zoom. Would you have time next week?

**Comment by kubu4** [comment]
I'd be happy to come in on Tuesday. Does that work for you?

Also, take good notes and then you can add the process to the Roberts Lab Handbook for us all!

**Comment by zbengt** [comment]
That would be great! I'm free 11:15-1:30 on Tuesday. Let me know if that works for you. I'll be sure to take lots of notes.

**Comment by kubu4** [comment]
Sounds good. 

11:15 in FTR 228 is perfect.

**Comment by zbengt** [comment]
Great, see you then!
