### ISSUE TITLE
Fill dewar and dry shipper this week for shipment on Monday April 8th

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1861]
Hi Sam! Could we please charge a dry shipper (which I am bringing from URI and will have at UW tomorrow) and partially fill a dewar this week? If we fill a dewar with some extra liquid, I can top off the dry shipper and make sure it is fully charge on the morning of Monday April 8th when I leave for Australia. This way, you could fill the dewar and charge the dry shipper on a day that is convenient for you this week. 

The dry shipper will hold a charge for about a week, but I need to make sure it is fully charged and freshly charged before my travel. If we fill some extra liquid in a separate dewar I can charge the dry shipper myself the morning before I leave. What do you think?

**Comment by kubu4** [comment]
Sounds good. I'll be in on Tuesday and do this.

**Comment by AHuffmyer** [comment]
Thank you! Where should I leave the dry shipper for you?

**Comment by kubu4** [comment]
In 209. Thanks.

**Comment by kubu4** [comment]
All set! Both are on the cart in FTR 209.

**Comment by AHuffmyer** [comment]
Thank you! I'll ask someone to peak at the dry shipper on Friday to make sure its still cold and that we have liquid in the dewar still. Was it cold when you filled it?

**Comment by kubu4** [comment]
Yep, it was still cold.
