### ISSUE TITLE
Thoughts on Analysis Next Steps?

### ISSUE THREAD

**Issue by ChrisMantegna** [RobertsLab/resources#1863]
Hey! Check out my last workflow and let me know what you think is missing from an analysis or qc point of view. [full workflow](https://rpubs.com/cmantegna/mb06avgsite). 

The point is to correlate the biomarker activity from the digestive tissue to the who tissue response in the analyte assessment done by WDFW. p45o biomarker activity directly relates to the PAH analytes and the SOD biomarker is a general stress response.

Thanks!
Chris

**Comment by kubu4** [comment]
I'd just like to add that the spatial-based plotting is cool! And, the code looks _very_ clean/easy! Nice work!

**Comment by AHuffmyer** [comment]
Great work! The spatial plotting is super cool!

**Comment by ChrisMantegna** [comment]
Thanks y'all! Was super fun to play around with.
