### ISSUE TITLE
Getting GOSlim terms from GO ID's 

### ISSUE THREAD

**Issue by graceleuchtenberger** [RobertsLab/resources#1864]
Hi all,
For the PSMFC mussel byssus project, we now have our DEG lists with GO ID's but we need to get GOslims for these. I've been poking around on some old Roberts lab issues to see if there's code we could use, but I'm not sure I totally understand the process. Could someone please walk me through how to do this/post a link to some helpful code?
Thanks and best,
Grace

**Comment by sr320** [comment]
Post a link to the DEG list with GO info?

**Comment by graceleuchtenberger** [comment]
If you look in [here](https://github.com/graceleuchtenberger/Byssus-expression-analysis/tree/main/output/DEG_lists/with_GO_terms) the csv files with the suffix "sigs_ID" will have the DEG's that could be matched up with GO ID's.

**Comment by kubu4** [comment]
We have a great guide in the handbook. Check it out and then feel free to follow up with any questions:

https://robertslab.github.io/resources/bio-Annotation/#gene-ontology-go

**Comment by kubu4** [comment]
Oh boy. You can ignore my comment above... Didn't fully read your post. You already have GO terms. Sorry!

**Comment by kubu4** [comment]
After that embarrassment, here's a link to some code which is actually useful!

https://github.com/sr320/ceabigr/blob/main/code/17.1-GO-and-GOslim-CDS-Annotation.Rmd

This is R code which will take you through GO term acquisiition (which you've already done, so you don't need that) and GOslim mapping.

The GOslim mapping starts on line 172:

https://github.com/sr320/ceabigr/blob/1eea728f943b6fef8b42ea6033985d26bd0ebc47/code/17.1-GO-and-GOslim-CDS-Annotation.Rmd#L172

Check it out and feel free to ask any questions!

**Comment by graceleuchtenberger** [comment]
No worries Sam, been there haha. Thanks for the tip, I'll check these out.

**Comment by graceleuchtenberger** [comment]
On line 222 in the code, what kind of array are you indexing? It says GOBPoffspring, what kind of information does that contain? I'm just trying to figure out how to apply it to my code. Like is it your list of all identified DEG's in the offspring group?

**Comment by kubu4** [comment]
Here's the code and I'll try to explain it:

```r
# Create custom collection with our GO IDs
myCollection <- GOCollection(go_ids)


# Pull out GOslims from GOslim obo file
slim <- getOBOCollection(fl)


# Get Biological Process (BP) GOslims for our GO IDs
slimdf <- goSlim(myCollection, slim, "BP", verbose)


# Convert to list
gomap <- as.list(GOBPOFFSPRING[rownames(slimdf)])
```

1. Create a "collection" of the GO IDs that you're starting with (this is likely the GO IDs associated with your differentially expressed genes).
2. Retrieve all of the GOslims from the GOslim OBO file. The OBO file comes directly from the Gene Ontology Consortium. I think it's mentioned earlier in the code.
3. Use the `goSlim` function of `GSEABase` to get all of the Biological Process (BP) GO slims associated with your GO IDs, into a data frame.
4. Create a list of of all GO BP Offspring, using the rownames from the data frame of GOslims created in Step 3. The `GOBPOFFSPRING` is part of the `GSEABase` library.

**Comment by graceleuchtenberger** [comment]
OH okay thank you that makes a lot more sense.

**Comment by graceleuchtenberger** [comment]
What kind of data does column V2 contain in your cleaned up data file?

**Comment by kubu4** [comment]
Sorry, can you provide more specific info?

Also, if you clone that repo, you can run all that code yourself.

Also, it might help to view the input/output files in the repo, in order to get a sense if what everything looks like.

**Comment by sr320** [comment]
I offered Simple join solution
