### ISSUE TITLE
Order hobos

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1866]
20 loggers

**Comment by AHuffmyer** [comment]
We have two options. The main differences are price and accuracy. Option #1 = higher accuracy, higher price; Option #2 = lower accuracy, lower price. If we have the budget, Option 1 is the better logger. 

1) [Tidbit MX2203 loggers](https://www.onsetcomp.com/products/data-loggers/mx2203): 0.25°C accuracy; waterproof; Bluetooth

$155.00 each x 20 = $3,100 total 

2) [Pendant MX2201 loggers](https://www.onsetcomp.com/products/data-loggers/mx2201): 0.5°C accuracy; waterproof; Bluetooth

$75.00 each x 20 = $1,500 total

@sr320 what would you prefer given the budget?

**Comment by sr320** [comment]
lets go with Tidbit? - more robust.

**Comment by AHuffmyer** [comment]
I could also order 10 of each - the Tidbits would be more robust for in lab measurements and the Pendants resolution would likely be just fine for field measurements.

**Comment by sr320** [comment]
I was think robustness in terms of handling harsh conditions is field.. to me the accuracy is not critical - will add work tags in slack

**Comment by AHuffmyer** [comment]
Submitted via TREQ TREQ003845
