### ISSUE TITLE
Order pH and conductivity multimeter 

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1867]

**Comment by AHuffmyer** [comment]
[Orion Star A329 Cat STARA3290](https://www.thermofisher.com/order/catalog/product/STARA3290?SID=srch-srp-STARA3290) 
- Temperature
- Salinity/conductivity 
- Dissolved Oxygen 
- pH/mV 

$2,220

[Orion Star A221 Cat STARA2218](https://www.thermofisher.com/order/catalog/product/STARA2218?SID=srch-srp-STARA2218)
- Temperature
- pH/mV
- Doesn't say that it does conductivity, but in the Putnam Lab we have added a conductivity probe onto this model. I'm checking to confirm that this is possible. 

$1,700

**Comment by AHuffmyer** [comment]
@sr320 What do you think of these options given the budget?

**Comment by AHuffmyer** [comment]
I recommend the A325 if there is room in the budget - especially if we expand to do fresh water exposures in the future.

**Comment by sr320** [comment]
A325 is fine - added worktags in slack
