### ISSUE TITLE
Decide on outplant site for WSG oysters in May

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1869]
At our WSG meeting today, we talked about outplanting in May. Emily suggested Westcott as the outplant site because they could easily access and monitor and Grace L. could be more involved. As AH and SR talked about earlier this week, Willapa is also a good potential site because an intern will be at the site. 

We agreed that outplanting at one site for this first summer is a good idea. 

@sr320 what are your thoughts on outplant site?

**Comment by sr320** [comment]
We need to be outplanting at multiple sites this summer particularly considering USDA effort. Will want something at Willapa for intern- lets get bags to both places minimally.

**Comment by sr320** [comment]
For each site we need to know how to bag, and if permits are needed.

**Comment by AHuffmyer** [comment]
Ok, I'll work on finding out bag info and permitting information for transport between counties.

**Comment by AHuffmyer** [comment]
Will meet with Kathleen next week to talk about Goose Point outplant options

**Comment by AHuffmyer** [comment]
Will go for Goose Point and Westcott this summer.
