### ISSUE TITLE
Prepare WDFW shellfish transfer permits for WSG/USDA 

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1870]
Permit application: https://wdfw.wa.gov/sites/default/files/2023-11/wdfwshellfishtransferpermitapplication-2023.pdf

Supplemental information: https://wdfw.wa.gov/sites/default/files/2019-08/WDFW_TransferPermit_guidelines_2019.pdf

Will need to file a permit once site selection and number of animals is finalized.

**Comment by mattgeorgephd** [comment]
Hey Ariana, if you need help with permitting, Nam Siu (WDFW Permit Coordinator) is a good resource. His email is nam.siu@dfw.wa.gov, happy to introduce you. Having a consult with him describing your project and letting him know the volume of transfers may help you expedite.

**Comment by AHuffmyer** [comment]
Thank you, Matt! I would love an introduction and it would be great to chat with him before submitting applications.

**Comment by mattgeorgephd** [comment]
Email sent!

**Comment by AHuffmyer** [comment]
Meeting scheduled with Nam for May 6th (invite sent to SR)

**Comment by AHuffmyer** [comment]
Spoke with Nam today. No standalone permit needed, we can conduct transfers under Point Whitney's permit, which allows for transfers to commercial facilities within state waters. Matt H. will just need to report the transfer as "research" on quarterly reporting. No additional health testing required as long as Pt. Whitney is in compliance with green crab control protocols.
