### ISSUE TITLE
Decide on number of adult animals for transport from Neil

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1872]
From Neil in email: 

"Apologies on the tardy response here.

We're seeing a slow buildup of mortality in the spat right now. Hence the silence on what's going to be available because at this point I'm not sure what is available.  Until mortality stabilizes I won't be able to give you any sort of satisfactory answer on spat.

As for broodstock; we have adults from MBP cohort 27 that can be transferred to you. How many animals do you want? Do you want a genetically diverse mix or from a small number of full-sib families? Will, lets put a sticky note to grab these animals from the rafts and stash them in an NAL trough until shipping.

We can ship as soon as we get an approved import permit.

For the import permit I need the following info from you:
Geographic destination of import (specific tideland, hatchery, aquarium, laboratory, educational facility, government facility, live holding facility, quarantine, etc.):
If receiving body is a facility (e.g. hatchery, nursery, research lab, educational institution, aquarium, etc.), has this facility previously been inspected and approved by WDFW?"

**Number of animals:** 
- Option 1: Genetically diverse mix: 80-100 animals (?)
- Option 2: Small number of full-sib families: 20-30 animals from 4-5 families (?) 

Given our interests from USDA project and need for larval experiments, we would likely be most interested in adults from full sib families. Would give us the opportunity to characterize variability across families. @sr320 what do you think? 

**Permit information:** 
- Geographic destination: Point Whitney Shellfish Laboratory and Jamestown S'Klallam Point Whitney Hatchery, 1000 Point Whitney Rd, Brinnon, WA 98320 
- @sr320 this facility has likely been inspected and approved by WDFW, correct? 

AH will email Neil back with this information

**Comment by sr320** [comment]
>likely be most interested in adults from full sib families.

Yes


Steven B. Roberts, Professor School of Aquatic and Fishery Sciences
University of Washington Fisheries Teaching and Research (FTR) Building -
Office 232 1140 NE Boat Street - Seattle, WA 98105 robertslab.info
<https://faculty.washington.edu/sr320/> - ***@***.*** - @sr320
vm:206.866.5141 - cell:360.362.3626 schedule a zoom call:
https://d.pr/gsgxVJ

**Comment by sr320** [comment]
>been inspected and approved by WDFW, correct?


Yes

**Comment by AHuffmyer** [comment]
Sent email asking for ~30 animals from 4-6 families - waiting for Neil's response on whether that is possible

**Comment by AHuffmyer** [comment]
Neil working on permit to send 20 animals from each of 5 families
