### ISSUE TITLE
Training to use Bioanalyzer?

### ISSUE THREAD

**Issue by valeste** [RobertsLab/resources#1873]
I've decided to move forward with RNAseq for a handful (12) of Botryllus samples from my Autumn 2023 nickel exposure work. I will be sending off samples to our collaborator at the UW Superfund Functional Genomics and Bioinformatics Core facility, but wanted to know if I could use and be trained on the Bioanalyzer in the Roberts Lab prior to sending them off sometime this week or the week of the 29th.

Thanks!

**Comment by sr320** [comment]
You would want to wait until the week of the 29th, Sam is out this week.

**Comment by kubu4** [comment]
This is certainly a possibility, and I'd be happy to do so.

However, you'd likely need to purchase your own reagents (ours are _very_ old and expired). The kit will be expensive (usually contains 25 chips and necessary reagents to run samples on all 25 - which is ~250 samples).

So, with that in mind, it would be significantly cheaper to find/use a core facility which specifically runs samples on a Bionalyzer (although, probably a TapeStation, as the Bioanalyzer is "outdated" at this point).

We've previously used Fred Hutchinson to run samples for us. Here's their current page. You'd want to contact them for pricing/sample requirements/payment/etc.:

https://www.fredhutch.org/en/research/shared-resources/core-facilities/genomics-bioinformatics/genomics-services.html#other

With all that said, I'm still more than happy to go through the Bioanalyzer with you! I'm probably going to be in lab on the 23rd (keep an eye on the Roberts Lab calendar).

Just post here if you have any questions.

**Comment by valeste** [comment]
We also do have the option to use a core facility for this, was just wondering if it would be cheaper if I did it in-house instead. Since that's not the case, I will move forward with having them run my samples on their Bioanalyzer. Thank you both again!
