### ISSUE TITLE
Table printing column numbers

### ISSUE THREAD

**Issue by ChrisMantegna** [RobertsLab/resources#1874]
Hey All!

i created this table but can't seem to get rid of the column numbers. Any suggestions? Thanks!
The file is here [file](https://github.com/ChrisMantegna/WDFWmussels/blob/main/data/morphtable.csv)

The code is 

`library(knitr)
#install.packages("kableExtra")
library("kableExtra")

# Create a simple table using kable and make headers span across columns
kable_styled <- kable(morph, "html", escape = FALSE, row.names = FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F) %>%
  add_header_above(c(" " = 1, "Condition Factor" = 3, "Shell Thickness (mm)" = 3, "p450 (activity mg-1 protein)"=3, "SOD (activity mg-1 protein)" =3))   

# Print the styled table 
kable_styled`

The output is ![this table](https://github.com/ChrisMantegna/WDFWmussels/blob/main/output/Screenshot%202024-04-15%20at%203.08.29%E2%80%AFPM.png?raw=true)

**Comment by sr320** [comment]
> created this table but can't seem to get rid of the column numbers 

I see no column numbers.-- 

Assuming this is for a manuscript -use excel

Also use scientific notation on numbers

**Comment by ChrisMantegna** [comment]
will use excel. the column numbers a the ...1 and then ...2 and ...3 next to the median, 2.5-97.5% and range for each grouping.

**Comment by ChrisMantegna** [comment]
Question - scientific notation for all or for just the p450 values?

**Comment by sr320** [comment]
I would do all so easy to compare.
