### ISSUE TITLE
using a loop for hisat

### ISSUE THREAD

**Issue by meganewing** [RobertsLab/resources#1876]
trying to run a loop in hisat using this code: 

```bash
cd ../code/

input_directory="../data/raw"

# Path to the HISAT executable
hisat_executable="/home/shared/hisat2-2.2.1/hisat2"

# Path to the reference genome index (replace GCF_026571515.1_index with the appropriate index prefix)
reference_genome_index="../output/hisat/GCF_026571515.1_index"

# Number of threads to use
threads="48"

# Output directory
output_directory="../output/hisat"

# Verify if input directory exists
if [ ! -d "$input_directory" ]; then
    echo "Error: Input directory does not exist: $input_directory"
    exit 1
fi

# Verify if output directory exists
if [ ! -d "$output_directory" ]; then
    echo "Error: Output directory does not exist: $output_directory"
    exit 1
fi

cd "$input_directory" || exit 

# Iterate over each pair of files in the input directory
for read1 in *R1_001.fastq.gz; do
    if [ -f "$read1" ]; then
        read2="${read1/_R1_001.fastq.gz/_R2_001.fastq.gz}"  # Generate read2 filename based on read1
        base_name="${read1%_R1_001.fastq.gz}"  # Extract base name without suffix

        # Generate output file names based on input file names
        output_sam="$output_directory/${base_name}.sam"
        stats_file="$output_directory/${base_name}_hisat2_stats.txt"

        # Run HISAT alignment for the current pair of reads
        "$hisat_executable" \
        -x "$reference_genome_index" \
        -p "$threads" \
        -1 "$input_directory/$read1" \
        -2 "$input_directory/$read2" \
        -S "$output_sam" \
        2>&1 | tee "$stats_file"
    else
        echo "Warning: Read file '$read1' does not exist"
    fi
done
```

and getting the following error (multiple errors like this actually but I'm not going to post the full list):

```
tee: ../output/hisat/M-C-193_hisat2_stats.txt: No such file or directory
Warning: [Errno 2] No such file or directory: '../data/raw/M-C-193_R1_001.fastq.gz'
(ERR): Read file '../data/raw/M-C-193_R1_001.fastq.gz' doesn't exist
Exiting now ...
```

here's the link (last chunk): https://github.com/meganewing/clamgonads-macsamples/blob/main/code/hisat_alignment-20240416.Rmd

EDITED: Created code block for easier reading.

**Comment by sr320** [comment]
I am pretty sure it's because by the time that code is run your location is ../data/raw

can you run the code without any use of variables and without any use of the CD command?

**Comment by meganewing** [comment]
like this? :

`# Iterate over each pair of files in the input directory
for read1 in *R1_001.fastq.gz; do
    if [ -f "$read1" ]; then
        read2="${read1/_R1_001.fastq.gz/_R2_001.fastq.gz}"  # Generate read2 filename based on read1
        base_name="${read1%_R1_001.fastq.gz}"  # Extract base name without suffix

        # Generate output file names based on input file names
        output_sam= ..output/hisat/${base_name}.sam
        stats_file= ..output/hisat/${base_name}_hisat2_stats.txt

        # Run HISAT alignment for the current pair of reads
        /home/shared/hisat2-2.2.1/hisat2 \
        -x ../output/hisat/GCF_026571515.1_index \
        -p 48 \
        -1 ..data/raw/"$read1" \
        -2 ..data/raw/"$read2" \
        -S "$output_sam" \
        2>&1 | tee "$stats_file"
    else
        echo "Warning: Read file '$read1' does not exist"
    fi
done`

if so, this is the error I'm getting: Warning: Read file '*R1_001.fastq.gz' does not exist

**Comment by kubu4** [comment]
Which section of code is this? In your [hisat_alignment-20240416.Rmd](https://github.com/meganewing/clamgonads-macsamples/blob/main/code/hisat_alignment-20240416.Rmd) file, it looks like this section of code is repeated a couple of times.

But, basically, don't change directories if you don't need to.

Stay in the working directory and use relative paths to refer to file locations. For example, you'd modify that section of code above to start like this:

```bash
# Iterate over each pair of files in the input directory
for read1 in "${input_directory}/*R1_001.fastq.gz"; do
```
"$input_directory/

**Comment by meganewing** [comment]
okay if i change it to 
```
input_directory="../data/raw"

# Iterate over each pair of files in the input directory
for read1 in "${input_directory}/*R1_001.fastq.gz"; do
    if [ -f "$read1" ]; then
        read2="${read1/_R1_001.fastq.gz/_R2_001.fastq.gz}"  # Generate read2 filename based on read1
        base_name="${read1%_R1_001.fastq.gz}"  # Extract base name without suffix

        # Generate output file names based on input file names
        output_sam= ..output/hisat/${base_name}.sam
        stats_file= ..output/hisat/${base_name}_hisat2_stats.txt

        # Run HISAT alignment for the current pair of reads
        /home/shared/hisat2-2.2.1/hisat2 \
        -x ../output/hisat/GCF_026571515.1_index \
        -p 48 \
        -1 "$input_directory/$read1" \
        -2 "$input_directory/$read1" \
        -S "$output_sam" \
        2>&1 | tee "$stats_file"
    else
        echo "Warning: Read file '$read1' does not exist"
    fi
done
```

I still get `Warning: Read file '../data/raw/*R1_001.fastq.gz' does not exist`

**Comment by sr320** [comment]
can you push `../data/genomic.gtf` or is it too big?

**Comment by kubu4** [comment]
Gah! Sorry! My B!

Change opening of loop to:

```bash
for read1 in "${input_directory}"/R1_001.fastq.gz; do
```

Wildcard expansion won't happen inside the quotes. Sorry about the typo above!

**Comment by meganewing** [comment]
@sr320 it's too big, but here's the link to the ncbi page wehre I got it: https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_026571515.1/

also, pushed updates and cleared out redundant chunks

**Comment by meganewing** [comment]
@kubu4 funky lookin error codes (one of many) after adjustment of that line: 

<img width="817" alt="Screen Shot 2024-04-19 at 3 31 22 PM" src="https://github.com/RobertsLab/resources/assets/66333757/8fae7515-8482-404c-817d-f3b22f27aa65">

**Comment by sr320** [comment]
remember in class when I went over xargs?

I had to run full paths but you would just do relative 

```
find /home/shared/8TB_HDD_02/mewing0/clamgonads-macsamples/data/raw/*gz \
| xargs basename -s _R1_001.fastq.gz | xargs -I{} \
/home/shared/hisat2-2.2.1/hisat2 \
-x /home/shared/8TB_HDD_02/mewing0/clamgonads-macsamples/output/hisat/GCF_026571515.1_index \
-p 20 \
-1 /home/shared/8TB_HDD_02/mewing0/clamgonads-macsamples/data/raw/{}_R1_001.fastq.gz \
-2 /home/shared/8TB_HDD_02/mewing0/clamgonads-macsamples/data/raw/{}_R2_001.fastq.gz \
-S ../output/{}.sam
```

**Comment by meganewing** [comment]
That's what it was... I remembered mentioning wildcards and for loops but not xargs. Thank you

**Comment by kubu4** [comment]
As a related aside, after alignment, you're going to want a step to create sorted BAMs and a step to remove the SAMs you created during alignment.

BAMs are compressed SAMs and are _substantially_ smaller in size!

Also, most downstream programs will expect the BAM files to be sorted.

Here's a quick example you can use to guide yourself on how to do that.

For context, this is taken from the middle of a loop, where `${sample}` is a variable using the input filename.

Also, I've included the BAM indexing step, as a BAM index file is needed in Integrated Genomics Viewer (IGV), if you want to visually inspect the alignments.

```bash
  # Sort SAM files, convert to BAM, and index
  echo "Sorting ${sample}.sam and converting to ${sample}.sorted.bam..."
  ${programs_array[samtools_view]} \
  -@ "${threads}" \
  -Su "${sample}".sam \
  | ${programs_array[samtools_sort]} - \
  -@ "${threads}" \
  -o "${sample}".sorted.bam
  echo "Sorting and conversion completed."
  echo ""

  # Index BAM
  echo "Creating index of ${sample}.sorted.bam..."
  ${programs_array[samtools_index]} "${sample}".sorted.bam
  echo "Indexing completed."
  echo ""
```

**Comment by sr320** [comment]
Also


Samtools to convert the SAM files output from the previous HISAT2 command into sorted BAM files...

```{bash samtools}
for file in /home/shared/8TB_HDD_01/apul/sam/*.sam; do
    base=$(basename "$file" .sam)
    /home/shared/samtools-1.12/samtools view -bS "$file" | \
    /home/shared/samtools-1.12/samtools sort \
    -o /home/shared/8TB_HDD_01/apul/bam/"$base".bam
done
```

**Comment by AHuffmyer** [comment]
Here is a post with scripts that I am running right now that has a loop by reading in a file array in hisat2. [See the align.sh script in the post here.]( https://ahuffmyer.github.io/ASH_Putnam_Lab_Notebook/RNAseq-Alignment-and-Assembly-for-Mcapitata-Larval-Thermal-Tolerance-Project/)

**Comment by meganewing** [comment]
So the xargs was working very well for the first dozen or so of my samples, then around 8:30 last night, it stopped working and the rest of the sam files after that have 0B. Here's the red text. Any ideas as to what is going on here? 

<img width="680" alt="Screen Shot 2024-04-20 at 3 13 00 PM" src="https://github.com/RobertsLab/resources/assets/66333757/39610307-d164-4735-ab2e-b298a1b69398">

**Comment by kubu4** [comment]
One problem is that the hard drive is full:

![image](https://github.com/RobertsLab/resources/assets/4514104/35f6b137-d001-43e1-9a74-87068f69a15a)

Sometimes that leads to weird problems like this.

Even if it's not the cause of the problems, we'll need to take care of that issue before you'll be able to proceed.

**Comment by sr320** [comment]
I think we have

Fixed the loop issue

**Comment by meganewing** [comment]
@kubu4 you mentioned in the drive issue: "Another option for you would be to modify your code so that you're deleting each SAM file immediately after you convert each to BAM. That way, the SAM files don't accumulate (they eat up LOTS of disk space)." 

Do you have an example of code to do this that I could add into my xargs loop?

**Comment by kubu4** [comment]
Can you please post code you're currently using to convert SAM to BAM?

But, basically, immediately after the command to convert the SAM to BAM, you'd add a command to delete the SAM which was just used as the input for the SAM to BAM command.
