### ISSUE TITLE
Two different geographical paths to discuss biomarker results

### ISSUE THREAD

**Issue by ChrisMantegna** [RobertsLab/resources#1877]
Hello!

I have spent some time looking at the sites separated by manual geographic cutoffs (latitude) and through the spatial analysis technique of K-means clustering. Both yield some interesting results.
1. Geography, groups the sites and looks at them overall - see the [correlations page](https://rpubs.com/cmantegna/mb02correlations). There are several statistically significant differences in the North and one significant relationship each in the Central and South region.
2. K-means uses a more complicated method that groups the individual samples by their deviation from the mean of the 4 metrics (p450, SOD, condition_factor and avg_thickness). See the [spatial work](https://rpubs.com/cmantegna/mb04spatial). There is no real geographic pattern but it is an interesting layer of result that could support a better discussion. 

All tables and outputs are written out into the repo. Take a look please and let me know what you think. I am moving forward working on the rewrite of the results and discussion using the manual geographic cutoffs for now.

Thanks!

**Comment by sr320** [comment]
What hypothesis are you testing?

**Comment by ChrisMantegna** [comment]
Now that analytes are 95% off the table, the hypothesis changes from correlation of activity to analyte value. I am asking whether or not there is an activity difference across regions in Puget Sound. I manually grouped regions by latitude to avoid averaging values, and found that:
* North region had statistically significant correlations between SOD and site, p450 activity, and average thickness. p450 has a statistically significant correlation with average thickness (and SOD). And finally, both average thickness and condition factor had a statistically significant correlation with site.
* Central and South regions had a statistically significant correlation between SOD and p450. 
* Overall region to region comparison, across the 4 metrics (SOD, p450, condition_factor and avg_thickness) show no statistically significant difference.
* Overall data, no region grouping, showed no significance except that the SOD activity at Elliot Bay Myrtle Edwards and Hood Canal sites were significantly different.

These differences are blind to waterway influences like percent cover of impervious surfaces, stormwater or wastewater effluences, or dock/ marina presence. Looking at the data this way shows comparable condition and biomarker activity across all of Puget Sound.

If I use the k-means clustering algorithm, it shows sample grouping outside of geography that will warrant extra time to untangle but may be worth the work after the results writing for the geographical groupings is done. I say extra time, because I will have to go back and really look at the waterway features that may have influenced the clustering - if that exists.
