### ISSUE TITLE
Raven R installation is "missing"

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1879]
![image](https://github.com/RobertsLab/resources/assets/4514104/cde2f6d6-889b-4d2e-9a97-b0e36ad5634a)

Will investigate. Likely need to restart.

**Comment by kubu4** [comment]
Well, restarting didn't help...

**Comment by sr320** [comment]
You likely know this already - but it was working Tuesday

Could it be related to moving files off?

**Comment by kubu4** [comment]
> Could it be related to moving files off?

It shouldn't be. I just rsync'd the contents of each user's directory to Gannet and then deleted those directories; nothing at a system level.

The thing is, R still works when using RStudio. RStudio still has the location of the R install.

It's the rest of the system (i.e. Bash) which no longer has the R install in its system `$PATH`.

It's a relatively easy fix (just need to append R install location to system `$PATH` in `/etc/environment`), but I'd love to know what happened...

**Comment by kubu4** [comment]
Still not sure what happened, but I've added the R install location to the system `$PATH` which resolves the issue.

![image](https://github.com/RobertsLab/resources/assets/4514104/006b379e-afdf-43af-88d6-2de655404ae5)
