### ISSUE TITLE
deseq 2

### ISSUE THREAD

**Issue by meganewing** [RobertsLab/resources#1880]
Updated heatmap still not grouping. Any advice or feedback on how this looks/the code looks? 
<img width="666" alt="Screen Shot 2024-04-25 at 1 52 07 PM" src="https://github.com/RobertsLab/resources/assets/66333757/6f053def-c90c-49e6-b264-746481508e76">

[Kallisto Isoform Counts Matrix used in DESeq2](https://github.com/meganewing/clamgonads-macsamples/blob/main/output/kallisto.isoform.counts.matrix)
[DESeq2 code](https://github.com/meganewing/clamgonads-macsamples/blob/main/code/06-deseq2.Rmd)

**Comment by sr320** [comment]
Note heat maps are not great figures for this - so don’t waste significant
energy on this.  But can you post link to tab delimited data you are
plotting?

**Comment by meganewing** [comment]
this? https://github.com/meganewing/clamgonads-macsamples/blob/main/output/1213-DEG.tab

**Comment by sr320** [comment]
No - the data behind the heatmap

**Comment by meganewing** [comment]
the data gets read in from the kallisto matrix

**Comment by sr320** [comment]
Yes - I know


Can you provide tab delimited format

**Comment by meganewing** [comment]
@sr320 ahh I see [kallisto.matrix.tab](https://github.com/meganewing/clamgonads-macsamples/blob/main/output/kallisto.matrix.tab)

**Comment by sr320** [comment]
I do not think these are degs -


See this gene highlighted?  and others?

Golden rule?

**Comment by meganewing** [comment]
Is my count matrix wrong?

**Comment by sr320** [comment]
I would not say your matrix is wrong - it’s just doubtful it is a matrix of
DEGs

**Comment by kubu4** [comment]
Working through your code, the very first step (reading in your data), looks like this:

![image](https://github.com/RobertsLab/resources/assets/4514104/03f65150-5dda-4658-a6e0-c3cbe2cb00ca)

I'd start there to try to resolve that and then work your way through, checking each file/object as you go.

**Comment by meganewing** [comment]
<img width="962" alt="Screen Shot 2024-04-25 at 3 58 36 PM" src="https://github.com/RobertsLab/resources/assets/66333757/ff63ae37-4bd8-411e-90d8-86e102fe6817">
for me it looks normal, might be something with trying to push it because it is kinda a bigger file?

**Comment by laurahspencer** [comment]
Have you tried `cluster_rows = FALSE`?

**Comment by meganewing** [comment]
@laurahspencer 
<img width="729" alt="Screen Shot 2024-04-25 at 4 03 18 PM" src="https://github.com/RobertsLab/resources/assets/66333757/6e718380-14e5-4c2c-8fe1-55a534174cff">

**Comment by kubu4** [comment]
> for me it looks normal, might be something with trying to push it because it is kinda a bigger file?

Found the file on Raven and it's only 8.8MB, so shouldn't be an issue to add/push to GitHub.

Anyway, I'm now using the copy in your Raven directory, instead of what I cloned from GitHub.

**Comment by meganewing** [comment]
<img width="768" alt="Screen Shot 2024-04-25 at 4 12 41 PM" src="https://github.com/RobertsLab/resources/assets/66333757/fa80ade4-a0b2-4b52-a81e-a7c9024e8afb">


zach seems to have saves the day. how does this look?

**Comment by laurahspencer** [comment]
That heatmap looks more sorted, since the rows (genes) aren't reshuffled by pheatmap. You define the gene order here: `top_25_genes_matrix <- count_matrix[top_25_genes_ids, ]`. But, it looks like the genes are sorted by absolute value of Log2FC, which means that they aren't ordered most negative L2FC <--> most positive L2FC.  

```
# Sort results by absolute log2 fold change
significant_results <- significant_results[order(abs(significant_results$log2FoldChange), decreasing = TRUE), ]
```

**Comment by laurahspencer** [comment]
Never mind, looks like you've got it!
