### ISSUE TITLE
Send seed number estimates to Neil as USDA

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1881]
Niel now has a better idea of seed stock that he can send us! He wants to know number of seed and number of families. 

@sr320 I don't know what a reasonable number of seed is to ask for... We asked for 20 adults from 5 families. If we did 5 families of seed, would it be reasonable to ask for 5,000 seed per family from 5 families? This is within my original estimates from [this sheet](https://docs.google.com/spreadsheets/d/1gasSHWZV_AJKqMfixigTO-WQbHoIFwtHidUycu7t5L0/edit#gid=0).

**Comment by sr320** [comment]
Yes, minimally. If we could get more than that (eg double) that would also be good.

**Comment by AHuffmyer** [comment]
Great, I'll ask if we can do 10,000 seed from each of 5 families and see what he says.

**Comment by AHuffmyer** [comment]
Neil said they have 5,000 available from 6 families - I replied that we will take what he has
