### ISSUE TITLE
Owl has died.

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#1882]
It seems like Owl has died.

It's exhibiting the "blue blinking light of death." It powers on, but does not boot (with or without drives in unit).

Owl and its expansion unit comprise a total of 13 drives. Due to the age of both Owl and it's expansion unit, it would be challenging to acquire a Synology unit which is compatible with the expansion unit. As such, I think we need to purchase a 16 bay unit as a potential replacement, or some other unit and compatible expansion unit to accommodate all 13 drives.

From what I can tell, the data on the disks should be fine and will be accessible once installed in a new Synology unit.

For immediate access to data on Owl, you can access the data at this Google Drive link:

https://drive.google.com/drive/u/1/folders/0BzKkDWZ6tIK4eXV4VFB3VHN2ZUk?resourcekey=0-QMtII7dU932nrNOyJl5kxg

Dealing with multiple and/or large files via Google Drive is frustratingly slow (or, just doesn't work). A good alternative is using [Rclone](https://rclone.org/), which allows command line interface and, fast and "easy" transfers between Google Drive and other computers.

IMPORTANT: This data on Google Drive will only be accessible until June! UW's new agreement with Google Drive storage limits goes into effect then, which means we will be losing this backup source.

---

@sr320 - This seems to be the only 16 bay Synology unit that I can find:

$3300 : https://www.amazon.com/Synology-16-Bay-RackStation-RS2821RP-Diskless/dp/B0936QBJ2S

B&H Photo has this unit in stock (the Amazon link availability is mid-May to mid-June).

I've looked into 12 bay units, plus expansions, and the prices would be ~$4700.

**Comment by sr320** [comment]
via esits:

The idea of SAFS providing some type of centralized data storage for their faculty came and went years ago. The college does not provide centralized data or computational services.

That being said, UWIT has been working on Kopah, a high-speed data system for researchers.  The system is about to go live this month and I should have some solid information on pricing and availability by July.  You are on a list of other college researchers that want/need this type of system so as soon as I get some definitive information, I will pass it along.

**Comment by kubu4** [comment]
> The idea of SAFS providing some type of centralized data storage for their faculty came and went years ago. 

Haha! These types of responses kill me. Always comes off as so negative.

**Comment by kubu4** [comment]
That cost is an Amazon Glacier backup of `nightingales`.

_However_, the backup is likely incomplete, due to repeated failures of the Synology/Glacier syncing process over the last year or so.

**Comment by sr320** [comment]
Separate issue.... but maybe we reconsider Amazon

**Comment by kubu4** [comment]
Ordered RS2821RP unit.
