### ISSUE TITLE
ethanol type that's best for buffer prep for RNA extractions?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1883]
I don't have any molecular grade ethanol and was hoping to get my extractions going this weekend (aiming to extract RNA from 21 samples to send off for seq asap). 

**Would it be ill-advised to reconstitute the DNA/RNA Wash Buffer concentrate with the 200proof ethanol in FTR 209 (I'd buy replacement bottle from sea star budget)?** Or should I order some molecular grade ethanol... I'd hopefully still get it in time before I leave for Marrowstone June 8th. 

The [protocol](https://files.zymoresearch.com/protocols/_d7005t_d7005_quick-dna-rna_microprep_plus_kit.pdf) does not specify that the ethanol should be molecular grade or not:     

![Screenshot 2024-05-03 at 3 06 14 PM](https://github.com/RobertsLab/resources/assets/14934314/86d1d549-b6b7-4f3d-96b5-c5977f5b6a90)

**Comment by kubu4** [comment]
200 proof ethanol we have in lab is what we use for all of our molecular biology, so it's fine.

**Comment by grace-ac** [comment]
ok yay! thanks. I'll order a replacement bottle if it's ok if i use one of the unopened ones under the hood?

**Comment by kubu4** [comment]
Yep, it's definitely fine to use the ethanol.

**Comment by grace-ac** [comment]
thanks @kubu4 !
