### ISSUE TITLE
Bring supplies from UW to Point Whitney on next visit 

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1886]
We need the following items out at Point Whitney:  

- 50 mL falcon tubes (n=10) 
- Kim wipes (2-3 boxes)
- Pencils (a box or two)
- Scissors (n=1)

I won't be on campus this week. @sr320 would you be able to grab these items to bring to Point Whitney next time? I can also pick them up the week of May 13th if you aren't on campus this week.

**Comment by sr320** [comment]
note I have those supplies at my house, but will not be able to make out Thursday as teaching.

**Comment by AHuffmyer** [comment]
No problem, no items are urgent. I normally wouldn't go out on a Thursday, but works well with the shipment.
