### ISSUE TITLE
Develop Plan for mussel DNA extractions

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1887]
Lay out protocol for DNA extractions. Target extraction timeline is next week.

**Comment by ChrisMantegna** [comment]
extractions complete. samples prepped for shipping on 6/7/24.

**Comment by kubu4** [comment]
Heads up - we can't ship until we have PO number. 

We'll also need a sample manifest filled out. I'll get this tomorrow.

**Comment by ChrisMantegna** [comment]
yup - just in the middle of updating Issue 1884 with this exact comment/ workflow needs.
