### ISSUE TITLE
DNA Extraction Protocol?

### ISSUE THREAD

**Issue by ChrisMantegna** [RobertsLab/resources#1888]
Any suggestions on DNA extraction protocols or kits for mussels? Looking to extract DNA from gill tissue. 

Thanks!

**Comment by kubu4** [comment]
There are many.

One preferred option is the Mollusc DNA Kit (OMEGA). Usually get good yields and good DNA quality, but it requires the use of chloroform. As such, it's more hazardous, and a bit more tedious, to use than other kits.

Other options are, essentially, any other DNA extraction kit: DNeasy (Qiagen), Quick-DNA kits (ZymoResearch). They'll get good yields and high quality DNA.

Tried and true is to use DNAzol, but this is a trickier protocol and requires a bit more lab skill//savvy than the other methods. Biggest benefit is that it's the cheapest option.

I don't know the current inventory status of any of these options in the lab currently - you'd have to check. Kits are stored on the shelf in 213 (immediately to your left as you enter). DNAzol would be in chemical cabinet in 209.

**Comment by ChrisMantegna** [comment]
Thanks, Sam! I'll take a look at the inventory and come back to this issue with any follow-up questions.

**Comment by ChrisMantegna** [comment]
Hey @kubu4 I'm not on campus today. :( 
Could you please check to see if there is a mollusk DNA kit available to use? I haven't done that yet.

**Comment by kubu4** [comment]
There is a Mollusc Kit available, but I don't know how many samples you need to isolate DNA from. Looks like there might be enough for 10 samples?

However, it looks like we're also low on chlorform:IAA (24:1).

We did just get a Zymo Quick-DNA MiniPrep Kit. I'll be using ~8 preps from it, meaning there would be ~40 preps remaining.

**Comment by ChrisMantegna** [comment]
I will have 24 tissue samples, so it would be better to use the Zymo kit. Thank you for checking.
