### ISSUE TITLE
Mistake made in first batch of RNA isolation

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#189]
There are [56 samples](http://owl.fish.washington.edu/scaphapoda/grace/Crab-project/Samples-for-RNA-isolation.png) total that I will isolate RNA from, so **I'm separating them into 7 groups of 8 samples**. 

**Today I did the first batch of 8**. HOWEVER, at the final centrifuge step, I realized I was off by a zero. Meaning that instead of centrifuging at 12,000 g, I may have done it at 1,200 g. 

@kubu4  said that this could be bad because RNA comes out of solution at a certain speed, and by being a decimal off, I may have not isolated RNA. 

I picked two of the eight tubes and [ran the Qubit](http://owl.fish.washington.edu/scaphapoda/grace/Crab-project/QubitData_2018-02-28_18-01-13.csv) to see if any RNA was found.

I used 10µL of sample to run the Qubit:
Tube 56 --> 0.896 ng/µL
Tube 176 --> out of range

### Should I pick new sample tubes and re-do this batch tomorrow?

**Comment by sr320** [comment]
Just wait - and lets discuss the 56 samples at meeting tomorow.
