### ISSUE TITLE
Revise temp logger order due to production delay

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1890]
Our Onset temperature logger order is going to be delayed for shipment because of production delays. The MX2203 loggers that we ordered will be delivered "on or before August 14th". I inquired about other options and they said that we could change our order to the MX2204 loggers with a 10% discount. 

The only difference in the original loggers and the MX2204 loggers is that the new model goes to 5000 ft depth instead of 400 ft. If we switch models, we will actually be cheaper than our original order. The original loggers were $155 and the new ones would be $148.50 each. 

I think it makes sense to change our order to the MX2204 given that it would be faster and cheaper with the same temperature logging capabilities. @sr320 how would I need to go about changing this order? Could I change our order with Onset and then the updated order will be sent back to UW? Or do I need to change the PO first?

**Comment by sr320** [comment]
There is no PO... Just change with onset and will see what happens.

**Comment by AHuffmyer** [comment]
Requested order change with Onset
