### ISSUE TITLE
Generate FedEx shipping label for USDA oyster shipment

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1892]
Could we please generate a FedEx label for the following oyster shipment? I will provide the label to Neil Thompson for shipment.

Speed: FedEx overnight
Ship date: Wednesday May 15th; delivery Thursday May 16th
Weight: Approx. 95 pounds

Origin: Hatfield Marine Science Center, 2030 SE Marine Science Drive, Newport Oregon 97365
Destination: Point Whitney Shellfish Hatchery ℅ Steven Roberts 1000 Point Whitney Rd, Brinnon, WA 98320

@sr320 does this PW address look correct? 

I'll go to PW on Thursday May 16th to receive them. I'll email Matt to ask about space to hold them.

**Comment by kubu4** [comment]
You'll have to contact the SAFS desk to do this:

safsdesk@uw.edu

**Comment by AHuffmyer** [comment]
Thanks! @sr320 do I need to provide them with worktags to generate a label?

**Comment by sr320** [comment]
yes - | PG107267 | GR014587 | FD200 | RS100077 | FN111 |

**Comment by AHuffmyer** [comment]
Done, sent to Neil

Tracking 776296348134
