### ISSUE TITLE
Getting to differential isoform/transcript expression using featurecount

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1893]
How do you eventually get to differential isoform/transcript expression in the Hisat -> FeatureCount workflow?

**Comment by sr320** [comment]
quick chatGPT indicates

> Quantification of Features: FeatureCounts is primarily used for gene-level quantification. For transcript/isoform quantification, a tool like StringTie or HTSeq might be more suitable. However, if gene-level quantification is acceptable, you can use FeatureCounts.

**Comment by laurahspencer** [comment]
I have not used featureCounts to get isoform counts. I'm tackling the alternative splicing question at the exon level, based on this study - [Mehmood et al. 2020](https://doi.org/10.1093/bib/bbz126). I'm currently doing differential exon usage using STAR -> featureCounts -> [DEXSeq](https://bioconductor.org/packages/release/bioc/vignettes/DEXSeq/inst/doc/DEXSeq.html) and can report back once I have results.

**Comment by sr320** [comment]
thanks
