### ISSUE TITLE
Schedule EOY meeting 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1895]
Some time in next month please schedule an end of year / outlook meeting - reviewing https://robertslab.github.io/resources/Environment-and-Expectations/#graduate-students and GSR linked there in..

**Comment by ChrisMantegna** [comment]
scheduled 5/30.

**Comment by grace-ac** [comment]
schedule 5/20 at 12:30pm

**Comment by shedurkin** [comment]
scheduled 6/6

**Comment by grace-ac** [comment]
> Some time in next month please schedule an end of year / outlook meeting - reviewing https://robertslab.github.io/resources/Environment-and-Expectations/#graduate-students and GSR linked there in..

I'm pretty sure this is right, but by GSR,  you mean this form: https://fish.uw.edu/wp-content/uploads/sites/29/2020/06/GSAR.pdf ?

**Comment by sr320** [comment]
Yes

Steven B. Roberts, Professor School of Aquatic and Fishery Sciences
University of Washington Fisheries Teaching and Research (FTR) Building -
Office 232 1140 NE Boat Street - Seattle, WA 98105 robertslab.info
<https://faculty.washington.edu/sr320/> - ***@***.*** - @sr320
vm:206.866.5141 - cell:360.362.3626 schedule a zoom call:
https://d.pr/PfBNav

**Comment by zbengt** [comment]
Scheduled 06/07 @ 2pm

**Comment by ChrisMantegna** [comment]
The most recent version of the GSAR form can be found here: https://docs.google.com/document/d/1fXcmxg7BMmzUNfQJquiqwAzOWRm-BFDG/edit?usp=sharing&ouid=112805088439958222746&rtpof=true&sd=true

**Comment by meganewing** [comment]
6/7 @12

**Comment by valeste** [comment]
rescheduled 6/4 @11am
