### ISSUE TITLE
from featurecounts to blast

### ISSUE THREAD

**Issue by meganewing** [RobertsLab/resources#1897]
With my feature counts output I was able to do deseq2 no issues, but then when I went to join my blast output with my deg file, I noticed that there's not really anything in common for me to merge them with. I back tracked things a little bit and even before deseq2, theres nothing in my feature counts output for me to merge with the blast results. How should I proceed? 

I could do it by the NW_#####.#, but I don't think that is proper as there are redundant NW_####.# in the blast output. With the kallisto output / trinity matrix version, there was a column in the output that was the XP_####.# that I used to join since those were unique and present in both the deseq2 output and the blast ouput. 

Here are the **column names from the featureCounts** output (and a preview): 
<img width="979" alt="Screen Shot 2024-05-13 at 3 14 42 PM" src="https://github.com/RobertsLab/resources/assets/66333757/9c9df02b-1923-4da5-a20a-4a8cbbeafff5">

**Column names from the DEG list** from DESeq 2: 
<img width="891" alt="Screen Shot 2024-05-13 at 3 14 16 PM" src="https://github.com/RobertsLab/resources/assets/66333757/31702524-c139-4588-9bc7-83efdce32256">

**Column names from blast:** 
<img width="901" alt="Screen Shot 2024-05-13 at 3 15 05 PM" src="https://github.com/RobertsLab/resources/assets/66333757/a0765204-1bf6-4ef8-99a7-60976969e577">

Does anyone have a (simple) example of going from feature counts to GO terms for DEGs I could look at as an example?

**Comment by sr320** [comment]
To clarify, you used feature counts as input to DESeq2 to get DEGs and now you want to annotate the DEGs correct?

What file did you use for blast.. in essence you are in need of a blast output with LOC IDS....

**Comment by meganewing** [comment]
@sr320 

cds_from_genomic.fna 

https://github.com/meganewing/clamgonads-macsamples/blob/main/code/10-blast_with_cds.Rmd

**Comment by kubu4** [comment]
The matching gene names are actually in that FastA file, but because of the formatting of the FastA definition lines, that info didn't get incorporated into the BLAST output (truncates after first space in definition line):

```bash
grep "^>" cds_from_genomic.fna | head

>lcl|NW_026851514.1_cds_XP_060579799.1_1 [gene=LOC132712676] [db_xref=GeneID:132712676] [protein=uncharacterized protein LOC132712676] [protein_id=XP_060579799.1] [location=complement(join(8570..8679,9698..9800,9934..10108,10375..10520,10828..10970,11352..11870,12239..12377,12599..12643))] [gbkey=CDS]
>lcl|NW_026851514.1_cds_XP_060597846.1_2 [gene=LOC132748637] [db_xref=GeneID:132748637] [protein=uncharacterized protein LOC132748637] [protein_id=XP_060597846.1] [location=join(8759..8831,9021..9136,9394..9594)] [gbkey=CDS]
>lcl|NW_026851515.1_cds_XP_060584853.1_3 [gene=LOC132740568] [db_xref=GeneID:132740568] [protein=clumping factor B-like] [protein_id=XP_060584853.1] [location=join(77287..77300,77644..78204,78526..78583)] [gbkey=CDS]
>lcl|NW_026851515.1_cds_XP_060561973.1_4 [gene=LOC132718660] [db_xref=GeneID:132718660] [protein=uncharacterized protein K02A2.6-like] [protein_id=XP_060561973.1] [location=167380..168189] [gbkey=CDS]
>lcl|NW_026851515.1_cds_XP_060572685.1_5 [gene=LOC132727619] [db_xref=GeneID:132727619] [protein=uncharacterized protein LOC132727619] [protein_id=XP_060572685.1] [location=complement(join(177509..177538,203129..203573,203882..203988))] [gbkey=CDS]
>lcl|NW_026851515.1_cds_XP_060581950.1_6 [gene=LOC132738154] [db_xref=GeneID:132738154] [protein=somatostatin receptor type 2-like] [protein_id=XP_060581950.1] [location=217993..219111] [gbkey=CDS]
>lcl|NW_026851515.1_cds_XP_060582695.1_7 [gene=LOC132738154] [db_xref=GeneID:132738154] [protein=somatostatin receptor type 2-like] [protein_id=XP_060582695.1] [location=217993..219111] [gbkey=CDS]
>lcl|NW_026851515.1_cds_XP_060583779.1_8 [gene=LOC132739666] [db_xref=GeneID:132739666] [protein=somatostatin receptor type 3-like] [protein_id=XP_060583779.1] [location=225974..227020] [gbkey=CDS]
>lcl|NW_026851515.1_cds_XP_060579431.1_9 [gene=LOC132736035] [db_xref=GeneID:132736035] [protein=piggyBac transposable element-derived protein 4-like] [protein_id=XP_060579431.1] [location=complement(join(234839..236314,236619..236786))] [gbkey=CDS]
>lcl|NW_026851516.1_cds_XP_060593541.1_10 [gene=LOC132747699] [db_xref=GeneID:132747699] [protein=uncharacterized protein LOC132747699] [protein_id=XP_060593541.1] [location=complement(14337..16805)] [gbkey=CDS]
```

**Comment by meganewing** [comment]
@kubu4 okay cool I think I can work with this!! I have to go to work right now but will revisit this later tonight/tomorrow morning. 

thank you!

**Comment by laurahspencer** [comment]
I just dealt with this, too! Here's what I did: 

In bash, grab headers from .cds file and save to new file:
```
 cat cds_from_genomic.fna | grep ">" > cds_from_genomic_headers.txt
```

In R, read in header information and create columns with gene info: 
```
pcod.blast.cds.headers <- read_delim(file = "../../references/cds_from_genomic_headers.txt", delim = "nothing", col_names = "all") %>% 
  mutate(cds=gsub(">| \\[", "", str_extract(all, ">lcl\\|(.*?) \\[")),
         gene=gsub("gene=|\\]", "", str_extract(all, "gene=(.*?)\\]")),
         ncbi_id=gsub("db_xref=GeneID:|\\]", "", str_extract(all, "db_xref=GeneID:(.*?)\\]")),
         protein=gsub("protein=|\\]", "", str_extract(all, "protein=(.*?)\\]")),
         protein_id=gsub("protein_id=|\\]", "", str_extract(all, "protein_id=(.*?)\\]")),
         location=gsub("location=|\\]", "", str_extract(all, "location=(.*?)\\]")),
         gbkey=gsub("gbkey=|\\]", "", str_extract(all, "gbkey=(.*?)\\]"))) %>% 
  dplyr::select(-all)
```
In R, join the blast results with the gene information that I pulled from .cds headers. I also reduce blast results to gene-level, so where there are multiple blast hits for same gene, I select one with minimum e-value. You can omit that step if you need annotation information at the transcript level.  NOTE: since your file was downloaded from NCBI, it looks like you also have NCBI gene IDs for each gene ("db_xref=GeneID:#########"). These are unique gene identifiers that won't be duplicated across species, so they are quite helpful. 

```
pcod.blast.cds <- right_join(pcod.blast.cds.headers,
                            read_delim(file = "../../references/cds_from_genomic_blastx.tab",
                                       delim = "\t", col_names = c("cds", "saccver", "pident", "length", "mismatch", 
                                                                   "gapopen", "qstart", "qend", "sstart", "send", "evalue", "bitscore")),
                            by="cds") %>%
  # I have to reduce from cds to gene-level, so where multiple blast hits for same gene, select one with minimum e-value
  group_by(ncbi_id) %>% dplyr::slice(which.min(evalue)) %>%  #could instead use `group_by(cds)` to make sure one blast result per transcript
 separate(saccver, sep="\\|", into=c("na", "SPID", "gene.Uni"), remove = F) %>%
 dplyr::select(-na) %>% separate(gene.Uni, sep="_", into=c("gene.Uni", "species"), remove=T) %>%
  clean_names()
```

**Comment by sr320** [comment]
and here is how I did something similar - focusing on LOC where it was not predominant in files..
https://robertslab.github.io/tusk/modules/04-blast.html#case-study---oyster

**Comment by meganewing** [comment]
@laurahspencer 

Super helpful !!! Thank you!
