### ISSUE TITLE
Missing filter wheel B for plate reader

### ISSUE THREAD

**Issue by zbengt** [RobertsLab/resources#1899]
The plate reader in 228 is missing the second filter wheel with 1 inch filter lens openings (below on the right). Sam, am I crazy or do I remember the filter wheel being on top of the plate reader when you showed it to me earlier this quarter? I've looked all over and can't seem to find it.
![IMG_6737](https://github.com/RobertsLab/resources/assets/91245841/6b36ee0b-c12f-4338-a68b-44d1d55fe3b6)

**Comment by kubu4** [comment]
Are you saying the filter wheel is no longer installed in the machine?

**Comment by kubu4** [comment]
To my knowledge, there's never been a second excitation wheel for this machine (we inherited it from another lab).
