### ISSUE TITLE
Develop HTML code for People page

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#19]
Page in question: https://github.com/sr320/LabDocs/blob/master/web/People.md

Markdown or HTML will work.

Based on suggestion to add links at robertlab.info.

Lets decide possible accounts that would be linked and generate HTML snippet that could be added for each person and customized. 

I imagine it would be webtable with icons...

**Comment by sr320** [comment]
Optional links
Cv
Notebook
Twitter
Instagram 
Github
Figshare
?????

**Comment by sr320** [comment]
Also include other improvements suggested by @yaaminiv

**Comment by sr320** [comment]
Looks like our major revamp is not launching but I would like some minor updates here.
https://github.com/sr320/LabDocs/blob/master/web/People.md

Mainlym @grace-ac can you include blurb and photo (and way for persons to contact you)

@yaaminiv @laurahspencer @jldimond @MeganHintz 
Can you provide minimally a way anyone can contact you...
and anything else you would like ie https://github.com/RobertsLab/resources/issues/19#issuecomment-321815817

Thanks

**Comment by sr320** [comment]
Thanks @grace-ac &  @jldimond 🏆 

@laurahspencer @yaaminiv ?

**Comment by laurahspencer** [comment]
I suggested an edit, since I don't have permission to edit directly. 

![image](https://user-images.githubusercontent.com/17264765/35878411-106bc722-0b2d-11e8-858c-9c1a82c9af6b.png)

**Comment by sr320** [comment]
@laurahspencer you need to go ahead and click "Create pull request"
