### ISSUE TITLE
Transferring frozen samples from Manchester

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#190]
I'm at manchester today, planning to transfer all my samples from Rick's -80 to UW. I picked up a bunch of block dry ice and will sandwich sample boxes in between dry ice blocks in a cooler.  Time between -80's will be ~2 hours.  I've never transferred samples on dry ice before - from webs searches it seems this will effectively keep samples frozen, but let me know if otherwise.

@yaaminiv do you want me to try to bring any of your samples back?  If so, which ones? I'm not sure how many boxes I'll be able to fit in the cooler with the dry ice blocks.

**Comment by sr320** [comment]
A few hours at with dry ice is fine.

**Comment by yaaminiv** [comment]
If you could bring back samples from my larval experiment, that would be great. At least the first larval collection, and the larger Falcon tubes from my midway collection. I think I should have 3-4 boxes total. Thanks!

**Comment by laurahspencer** [comment]
Brought all the samples I could find from "our" shelf in Rick's -80. They are in Roberts' lab middle -80, middle shelf. @yaaminiv your boxes and falcon tubes are all on the right side of the shelf.  There is some dry ice left in the blue cooler in the freezer room. I'm planning on inventorying my samples tomorrow using the dry ice.
