### ISSUE TITLE
Alt Splicing - walk through data set

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1903]
For lab meeting next week going over alternative splicing and DEGs... 
I thought it would be good to use the same datasets.

@laurahspencer lets use whatever you are dealing with 

I presume these are reads:
https://sr320.github.io/tumbling-oysters/posts/sr320-13-cod/#1-reads

can you pick two treatments to compare and post specifically which fastq files correspond to the two treatments?

I will do Stringtie to DESeq2....

@kubu4 maybe you can do Stringtie to Ballgown?  

and we can go over next labmeeting?

**Comment by sr320** [comment]
and @shedurkin you can present on what kallisto looks like..

**Comment by laurahspencer** [comment]
I'm rsyncing trimmed RNASeq data for the 9C (control) and 16C (warm) treatments to Mox: /gscratch/srlab/lhs3/data/pcod-juveniles. Should be done transferring tonight.

**Comment by sr320** [comment]
@laurahspencer thanks, but how we know which are 9C and which are 16C?

**Comment by laurahspencer** [comment]
Couple options: 
- [DESeq2_Sample_Information.csv](https://github.com/RobertsLab/project-cod-temperature/blob/main/data/DESeq2_Sample_Information.csv)
- [Pcod Temp Growth experiment 2022-23 DATA.xlsx](https://github.com/RobertsLab/project-cod-temperature/blob/main/data/Pcod%20Temp%20Growth%20experiment%202022-23%20DATA.xlsx)

**Comment by laurahspencer** [comment]
If anyone else has a list of genes with alternative splicing send them my way, I can try to produce a venn diagram for tomorrow

**Comment by sr320** [comment]
What I have is a list of differentially expressed genes
https://sr320.github.io/tumbling-oysters/posts/sr320-15-coddeg/

and list of differentially expressed transcripts
https://sr320.github.io/tumbling-oysters/posts/sr320-14-coddet/

**Comment by kubu4** [comment]
Ballgown doesn't find any DETs or DEGs.

This is based on selecting those with p-values _and_ q-values <= 0.05.

If I only use p-values, then we'd have some results.

**Comment by kubu4** [comment]
Otherwise, if filtering only p-values <=0.05:

DETs: 933

DEGs: 786

**Comment by sr320** [comment]
> Ballgown doesn't find any DETs or DEGs.

This is very interesting as when I go from Stringtie -- DESeq2 I get 5000+ for both

**Comment by sr320** [comment]
> If I only use p-values, then we'd have some results.

I presume these are these adjusted p-values (for multiple comparisons)

**Comment by sr320** [comment]
> If you post lists of genes containing DETs I can compare methods.

Oddly enough I cannot easily determine the which DETs relate to which genes.

**Comment by kubu4** [comment]
Here of DETs (no q-value filter; p-value <=0.05 only):

[DET_temp_pvalOnly_filtered_stat_results_p-0.05.csv](https://github.com/RobertsLab/resources/files/15421236/DET_temp_pvalOnly_filtered_stat_results_p-0.05.csv)

Looks like this:

```
geneNames     geneIDs            feature     id   fc                 pval                qval
abhd14a       gene-abhd14a       transcript  60   0.674753221422441  0.0372103635999635  0.739815228191825
LOC132465650  gene-LOC132465650  transcript  467  1.75619374313028   0.0252552275250153  0.739815228191825
n6amt1        gene-n6amt1        transcript  553  1.15446815703663   0.0247603538263612  0.739815228191825
LOC132466378  gene-LOC132466378  transcript  599  0.824387962409548  0.0170201322768343  0.739815228191825
LOC132466774  gene-LOC132466774  transcript  639  1.25085946423748   0.010103925995758   0.739815228191825
sarnp         gene-sarnp         transcript  714  0.77902476599345   0.0472607034427815  0.739815228191825
kansl2        gene-kansl2        transcript  721  1.32477404769406   0.0101801715702434  0.739815228191825
pip4k2ca      gene-pip4k2ca      transcript  738  0.617674799125262  0.0226212586614239  0.739815228191825
hsd17b10      gene-hsd17b10      transcript  753  1.47761581126461   0.0385542844473806  0.739815228191825
```

You'll want to use the `geneIDs` column.

Side note: Is it weird that the q-value appears to be identical in the subset shown???

**Comment by laurahspencer** [comment]
@sr320 can I get this file?  ../output/10.1-hisat-deseq2/DETlist.tab

**Comment by laurahspencer** [comment]
@kubu4 and @sr320 I can also compare against DEGs, if you have those handy

**Comment by kubu4** [comment]
DEGs (no q-value filter; p-value <=0.05 only):

[DEG_temp_pvalOnly_filtered_stat_results_p-0.05.csv](https://github.com/RobertsLab/resources/files/15421710/DEG_temp_pvalOnly_filtered_stat_results_p-0.05.csv)


Looks like:

```
feature  id            fc                 pval                qval
gene     gene-aamp     1.64398217454079   0.0473189901402451  0.731520235542954
gene     gene-abhd10b  1.23901395973453   0.0319619862399934  0.731520235542954
gene     gene-abhd14a  0.658247010907664  0.044596241554251   0.731520235542954
gene     gene-acad9    0.451690397202728  0.0127731511530629  0.731520235542954
gene     gene-acap1    0.886265590813975  0.0367384682538837  0.731520235542954
gene     gene-acd      1.13827380245454   0.0301733000196754  0.731520235542954
gene     gene-acmsd    1.36209008551637   0.0125604589908431  0.731520235542954
gene     gene-acsbg2   0.717028711437008  0.0180650186160483  0.731520235542954
gene     gene-acsf2    1.8989755149531    0.0302459384927044  0.731520235542954
```

**Comment by laurahspencer** [comment]
R object relating transcript IDs to gene IDs

[pcod.gtf.transcript2gene.zip](https://github.com/RobertsLab/resources/files/15422621/pcod.gtf.transcript2gene.zip)

**Comment by sr320** [comment]
My lists
https://github.com/RobertsLab/project-cod-temperature/blob/main/output/10-hisat-deseq2/DEGlist.tab
https://github.com/RobertsLab/project-cod-temperature/blob/main/output/10.1-hisat-deseq2/DETlist.tab

**Comment by laurahspencer** [comment]
Pretty good overlap among differentially expressed **GENES** in our three analyses 

<img src="https://github.com/RobertsLab/resources/assets/17264765/326b518b-39d4-4fc5-8f00-8e778b4d6d0c " width="600">

But quite poor overlap among genes that contain differentially expressed **EXONS/TRANSCRIPTS** that were not also identified as DEGs in their respective analyses. 

<img src="https://github.com/RobertsLab/resources/assets/17264765/89ee5340-e169-4bea-bf83-1173c28bae91" width="550">

**Comment by kubu4** [comment]
Interesting response from Ballgown developer in this [old thread](https://support.bioconductor.org/p/107011/#110750), regarding the use of Ballgown for gene expression:

> Ballgown was not really designed for *gene*-level differential expression
analysis -- it was written specifically to do *isoform*-level DE. Using
DESeq2 with FeatureCounts is a much better-supported operation if your main
interests are in gene-level DE. Count-based models like those in DESeq2 are
totally appropriate for gene-level DE (whereas Stringtie and Ballgown are
tools for when the count-based models *don't* work). So Hisat2 ->
FeatureCounts -> DESeq2 would be a great workflow if you don't need
isoform-level results.

**Comment by laurahspencer** [comment]
Slide deck with details of featureCounts --> DEXSeq approach (Laura's) and overlapping genes containing DEUs / DETs, etc. 
 [Alternative Splicing Approach_ Exon Usage.pdf](https://github.com/RobertsLab/resources/files/15438242/Alternative.Splicing.Approach_.Exon.Usage.pdf)

**Comment by kubu4** [comment]
Ran `edgeR`.

It identifies ~`4,700` genes as being significantly differentially expressed.

Code is here: https://github.com/RobertsLab/project-cod-temperature/blob/main/code/13.0.0-RNAseq-edgeR.md
