### ISSUE TITLE
Hackathon Schedule & Prep

### ISSUE THREAD

**Issue by ChrisMantegna** [RobertsLab/resources#1905]
Hey Y'all!
A few questions about this upcoming Hackathon (6/3 - 6/7).
1. Do we have a schedule for Hackathon? For example, cod DESeq on Monday, some other project on Tuesday, etc...
2. How much prep should we do in advance? I'm assuming all files we're working with, proposed workflow, and research question? Anything else?
3. Can I request we work on eDNA on Tuesday or Thursday or Friday? 

Thanks!

**Comment by sr320** [comment]
Great Questions! 🥳 

1. Schedule is open to suggestion.. the idea is folks will work on what they need to work on and simply ask questions of the group when necessary. Will not necessarily be project based but rather address challenges individuals are having with given workflow (likely this will be common)

2. Prep- have everything in place with a general plan. - files in place, goals, initial workflows (how to get started). Submit issues ahead of time if at at loss of how to get started. 

3. Yes if you want/need to tackle something specific add to the calendar.
