### ISSUE TITLE
do loci not always have a gene id?

### ISSUE THREAD

**Issue by meganewing** [RobertsLab/resources#1909]
I'm looking at some of the dataframes from my rna seq analysis and I notice that when combining my df that has loci and log count data with the blast info, so i can associate gene id with log count data. I notice that not all of my loci have a match. Is this just because not all loci have a match in the database? Or is something funky going on?

**Comment by sr320** [comment]
Can you provide a url so we can see an example. For instance I am not quite clear what loci means here. If you are asking if a gene might not have a blast hit.. yes this can occur.

**Comment by sr320** [comment]
More on this, if I am imagining question correctly. 

You can see how many relative annotations you have with `grep -c ">"` on query to see how many sequences there are and `wc -l` on blast table (assuming parameters limit hits to 1 per query). Note this will not confirm if blast job prematurely ended. For this I see what the query is at end of blast table and hope/check that this is one of last sequences in query fasta.
