### ISSUE TITLE
Consider a new Mox Node

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#191]
Possibly lower memory node....
if this is the case I imagine we can direct to node?

![cost](http://eagle.fish.washington.edu/cnidarian/skitch/Shared_Scalable_Compute_Cluster_for_Research__Hyak____IT_Connect_20517EE7.png)

**Comment by kubu4** [comment]
I think that's the case. Having trouble finding a concrete answer to this on official Mox/Hyak wikis. I'll shoot them an email.

**Comment by kubu4** [comment]
Ordered on 3/16.

**Comment by kubu4** [comment]
Node has arrived to UW IT. Installation taking place. ETA on availability for use is ~1 week.

**Comment by kubu4** [comment]
New node is now available for use!

Will update Mox wiki.
