### ISSUE TITLE
Getting unmapped reads from alignment

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1910]
I am trying got get unmapped reads from hisat... seems simple but this could gives me an empty fastq file... any suggestions on how to get unmapped reads?

```
find /home/shared/8TB_HDD_02/graceac9/data/pycno2021/*_R1_001.fastq.gz.fastp-trim.20220810.fq.gz \
| xargs -I{} basename -s _R1_001.fastq.gz.fastp-trim.20220810.fq.gz {} \
| xargs -I{} sh -c '/home/shared/hisat2-2.2.1/hisat2 \
-x ../analyses/10-hisat-deseq2/GCA_032158295.index \
-p 36 \
-1 /home/shared/8TB_HDD_02/graceac9/data/pycno2021/{}_R1_001.fastq.gz.fastp-trim.20220810.fq.gz \
-2 /home/shared/8TB_HDD_02/graceac9/data/pycno2021/{}_R2_001.fastq.gz.fastp-trim.20220810.fq.gz \
-S ../analyses/10-hisat-deseq2/{}_03.sam \
--un ../analyses/10-hisat-deseq2/{}_unmapped_reads.fastq \
> ../analyses/10-hisat-deseq2/{}_hisat03.stdout 2> ../analyses/10-hisat-deseq2/{}_hisat03.stderr'
```

all other outputs are valid... 

![](http://gannet.fish.washington.edu/seashell/snaps/Monosnap_paper-pycno-sswd-2021-2022__RStudio_Server_2024-05-29_14-41-52.png)

**Comment by kubu4** [comment]
I think you need this flag (instead of `--un`):

`--un-conc`

**Comment by kubu4** [comment]
To elaborate, the difference is that the `--un` is for unpaired reads, while `--un-conc` is for paired reads.

**Comment by sr320** [comment]
thanks! that was it..
