### ISSUE TITLE
Location of eDNA reads

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1913]
In excited preparation for hack-week... what is the location of eDNA sequence reads?

**Comment by ChrisMantegna** [comment]
Will talk about this with you at lab meeting - we're working from the Anacapa files in the Yellow Island 2023 repo [repo link](https://github.com/ChrisMantegna/YellowIsland2023/tree/main/data/Anacapa_Results).   
These reads have already been trimmed and qc'd and had the taxonomies assigned by the CALeDNA crew.

**Comment by ChrisMantegna** [comment]
@sr320 I'm going to close this issue sine you were able to pull those files yesterday.
