### ISSUE TITLE
Assemble reads and annotate

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1915]
Can you assemble 
https://gannet.fish.washington.edu/seashell/bu-github/paper-pycno-sswd-2021-2022/analyses/10-hisat-deseq2/PSC-34_unmapped_reads.1.fastq
and 
https://gannet.fish.washington.edu/seashell/bu-github/paper-pycno-sswd-2021-2022/analyses/10-hisat-deseq2/PSC-34_unmapped_reads.2.fastq

then blast to nucleotide db to see what sequences are / resemble

**Comment by kubu4** [comment]
To clarify, do you want me to actually run `blastn` or do you want me to run `blastx` against the NCBI `nr` database?

**Comment by sr320** [comment]
Blastn

**Comment by kubu4** [comment]
Relevant output link:

https://github.com/grace-ac/project-pycno-sswd-2021/blob/main/code/12.0.0-blastn-unmapped-assembly.md#32-count-species

```
  17617 Mus musculus
  12185 Homo sapiens
   7251 Marthasterias glacialis
   6956 Asterias rubens
   2496 Asterias amurensis
    853 Vibrio pectenicida
    479 eukaryotic synthetic construct
    396 Mus caroli
    369 Pan troglodytes
    330 synthetic construct
```

**Comment by kubu4** [comment]
Marthasterias glacialis
Asterias rubens
Asterias amurensis

These are all species of sea star. The total counts for all three combined are 16,703.
