### ISSUE TITLE
Is it appropriate to conduct functional enrichment of up vs down regulated genes separately? 

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1916]
We touched on this at lab meeting today and I would like to discuss in more detail! 

*Is it appropriate to conduct functional enrichment of up vs down regulated genes separately?*

**Here is a test scenario**:  

Let's say I have samples from two temperature treatments: high and control. I have the hypothesis that there will be increased expression of heat stress response genes in the high temperature treatments. I could conduct a DESeq analysis to identify differentially expressed genes and could then subset significant DEGs that are increased at high temperature (log2 fold change >0) and those that are decreased at high temperature (log2 fold change <0). Then, I could conduct functional enrichment of the increased (up regulated) genes to look for enrichment of heat stress response genes. 

Alternatively, from our discussion it seems that the other option would be to take all significant DEGs and conduct functional enrichment on all DEGs (regardless of direction of fold change). In order to test the hypothesis that heat response genes are up-regulated at high temperature, I would then need to identify heat response GO terms and then go back and subset genes that contain those enriched GO terms, and plot expression to see if it is up or down regulated. 

Interestingly, there are some papers that argue for conducting functional enrichment separately for up and down regulated genes to increase detection capacity for this type of hypothesis. [Here is an example](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3899863/). 

Of course, there are nuances in how we describe up vs down regulation based on transcript abundance. Increased abundance of a transcript does not capture all of the other steps in the process that would fully characterize up vs down regulation. This is true for any of the responses we measure that are a snapshot in time. 

**In this example, why would or wouldn't it be appropriate to conduct functional enrichment for up and down regulated genes separately to test this hypothesis?**

**Comment by sr320** [comment]
This would be great to discuss (was planning for during enrichment discussion). Lets discuss at hack-a-thon but here is my opinion in brief.

There would be some hypothesis that would necessitate doing enrichment separately and totally valid. I would suggest the example hypothesis would not necessarily fit. And more importantly I think in most cases our hypotheses should be more focused in organismal physiological response. This is where factors such as transcript storage, transcript half-life, translation rate, transcription rate, and the very very complex nature of pathway regulatory functionality come into the mix. One example is when transcript abundance is low, this could be a signal of increased translation.

**Comment by AHuffmyer** [comment]
Agreed on further discussion! Very interesting points. Perhaps in our analyses we should be more detailed in how we term genes to be "up" vs "down". Perhaps phrasing it as higher vs lower "transcript abundance" would be a more accurate description of the data we are actually getting. 

I think it would be fun to talk through the statistics behind functional enrichment of all DEGs vs those that are "up" and "down" regulated. I was thinking about this more and it makes sense that you could potentially have greater capacity to detect enrichment of certain GO terms if you analyze up and down regulated genes separately. Since functional enrichment compares GO term presence to the background of all genes expressed, the enrichment of terms in up regulated genes could be washed out or masked by including all DEGs (up and down regulated) in the test set.
