### ISSUE TITLE
Problem gff/gtf with Seastar

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1917]
Am I correct in identifying problem with gtf provided with seastar is that even if converted to gff the first column needs to be chromosome as defined by fasta (eg CM063243.1) and not pycn_heli.0392?
```
(base) sr320@raven:/home/shared/8TB_HDD_03/sr320/github/paper-pycno-sswd-2021-2022/data/ncbi_dataset/data/GCA_032158295.1$ head *fna
>CM063243.1 Pycnopodia helianthoides isolate M0D057908R chromosome 1, whole genome shotgun sequence
gttaaaataatttgaatattgGATTAGTTTCAAACCCTCCCAGATCCTTCTAGATCCTCTTTGTTGAAATacaggattca
gaaggactgagggctgtaggcccaaatgacagttgcttatcactgggtcaggcatacagTAGGGCAGatgggtgatggga
ttgtgcctttgatgatacaagcatggtaaggggcacacagtcagagtatagcATGACAAATTAATTTGTCTAAAAGGCCA

(base) sr320@raven:/home/shared/8TB_HDD_03/sr320/github/paper-pycno-sswd-2021-2022/data/ncbi_dataset/data/GCA_032158295.1$ head /home/shared/8TB_HDD_03/sr320/github/paper-pycno-sswd-2021-2022/data/*gtf
pycn_heli.0392  AUGUSTUS        gene    1       4781    0.95    +       .       g1
pycn_heli.0392  AUGUSTUS        transcript      1       4781    0.95    +       .       g1.t1
pycn_heli.0392  AUGUSTUS        intron  1       4506    0.95    +       .       transcript_id "g1.t1"; gene_id "g1";
pycn_heli.0392  AUGUSTUS        CDS     4507    4781    0.95    +       2       transcript_id "g1.t1"; gene_id "g1";
pycn_heli.0392  AUGUSTUS        exon    4507    4781    .       +       .       transcript_id "g1.t1"; gene_id "g1";
 
```

**Comment by sr320** [comment]
for reference - here are all annotation files- https://datadryad.org/stash/dataset/doi:10.5061/dryad.51c59zwfd

**Comment by kubu4** [comment]
I think the larger issue is that the GFF and the GTF are the same...

![image](https://github.com/RobertsLab/resources/assets/4514104/9406d0f2-8007-49cb-8ca2-369abcb61198)


However, the chromosome line in the GFF/GTF does _not_ have to match the FastA. It would certainly be nice, as well as logical.

Of course, it raises the questions of how the naming convention was applied and why isn't it consistent between FastA and GFF/GTFs...

**Comment by sr320** [comment]
> However, the chromosome line in the GFF/GTF does not have to match the FastA.

how would any software program know which line of the gff corresponds to the chormosome?

**Comment by sr320** [comment]
> I think the larger issue is that the GFF and the GTF are the same...
those are not the files we are using, just me copying file :)

**Comment by kubu4** [comment]
> > However, the chromosome line in the GFF/GTF does not have to match the FastA.
> 
> how would any software program know which line of the gff corresponds to the chormosome?

Good point! Duh!

So, this suggests some discrepancy in the published data - which I think was part of the hangup with this data set at last year's Hack Week.

I've been trying to get help from Dryad on and off for the past year with this and the help department never responds...

Might need to contact the author's of the paper?

**Comment by sr320** [comment]
> Might need to contact the author's of the paper?

Done!

**Comment by kubu4** [comment]
Can you please provide line to that paper/data again?

**Comment by kubu4** [comment]
> Can you please provide line to that paper/data again?

OMG! Ha! It's posted [above](https://github.com/RobertsLab/resources/issues/1917#issuecomment-2142940633). Sorry!

**Comment by kubu4** [comment]
Where is the genome available? I don't see it linked/discussed in that Dryad link. They talk about it, but they don't provide info on where one can download it.

**Comment by kubu4** [comment]
Found it. Guess I should've searched first, _before_ posting. Sorry!

Is there a reason all other marine researchers refuse to put their data on NCBI???

> Pycnopodia helianthoides genome is available for browsing on the UCSC genome browser

**Comment by sr320** [comment]
Note genome is on NCBI - https://www.ncbi.nlm.nih.gov/datasets/taxonomy/7614/

@kubu4 the genome at UCSC genome browser would solve the problem. I just could not figure out a way to download UCSC version.

**Comment by kubu4** [comment]
> Note genome is on NCBI - https://www.ncbi.nlm.nih.gov/datasets/taxonomy/7614/

Oh! Is that a different one than what was published in that paper (UCSC)?

That would certainly explain the differences in chromosome naming conventions!

**Comment by sr320** [comment]
Just got email - probably just renamed.

> Thanks for the enquiry. This was not something of which we were aware. It appears the scaffolds/chromosomes get renamed by NCBI … how the numbers (e.g. CM063243.1) associate with the chromosomes is decipherable from this page:
[https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_032158295.1/](https://urldefense.com/v3/__https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_032158295.1/__;!!K-Hz7m0Vt54!jl_bDt2ZafDaLXOFfxIfj9geuoJfX0sWB84Qm_NZ5c-XxtJxu1WzL6W2DZAALTfoUGM3mFZhti3eBmVGrxo$)
So chr 1 (CM063243.1 on NCBI) would be pycn_heli.0001 in the gtf file and so forth. 
 
>  Does this solve the issue?

I don't think this resolves it

**Comment by kubu4** [comment]
Hey, that was fast! Nice!

**Comment by sr320** [comment]
Ok I think we can hack it together.. knowing pycn_heli.0001 is Chromosome 1.

![](http://gannet.fish.washington.edu/seashell/snaps/2024-05-31_15-14-42.png)

**Comment by sr320** [comment]
resolved https://sr320.github.io/tumbling-oysters/posts/sr320-20-seastar/
