### ISSUE TITLE
Yellow eDNA - Illumina & MinION Sequences

### ISSUE THREAD

**Issue by ChrisMantegna** [RobertsLab/resources#1918]
I sent a direct Google folder invite to @sr320, but just in case, here is the link to the MinION reads from the same final sample sent to Illumina for the HiSeq sequencing. https://drive.google.com/drive/folders/1HZDlwB3_CZFiSLoxqeOVysJkdyVyFCEb?usp=sharing 

The output format is the same as an Illumina output per the UCSC lab that did the sequencing, basecalling and generation of consensus reads. I cannot explain that any further, I hope that makes sense to y'all.

**Comment by ChrisMantegna** [comment]
Question - where can I upload the sequences directly from my Google Drive to another web-based place? When I download and attempt to re-upload to an open access folder, there is some level of data loss. See the picture.
<img width="1363" alt="Screenshot 2024-06-02 at 6 11 34 PM" src="https://github.com/RobertsLab/resources/assets/81385272/b406e71e-0f1e-4b67-8c77-eff1722f21ed">

**Comment by kubu4** [comment]
You'll probably need to use something like [rclone](https://rclone.org/) to go directly from Google Drive to another location. 

If you can get them on Raven, we can get them onto a server for hosting.

**Comment by ChrisMantegna** [comment]
I'll give that a shot and see what happens. Worse case, I'll get help during hackathon tomorrow.

**Comment by ChrisMantegna** [comment]
Steven has the files. Closing the issue.

**Comment by sr320** [comment]
I have none of these files.

**Comment by ChrisMantegna** [comment]
I thought you said you were able to pull them off of the Google Drive folder on Wednesday. Did something go wrong?

**Comment by sr320** [comment]
I downloaded everything she shared with me, but the only thing she shared
with me were ASV files

**Comment by ChrisMantegna** [comment]
Ok. I'll get that sorted.

**Comment by sr320** [comment]
I now have files linked earlier in this issue on raven - presume this is all illumina and minion data.. will write up notebook post soom
