### ISSUE TITLE
Consider Metabolomics for larval samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#192]
Seems like this is worth exploring for several larval projects....
or broodstock under environmental regimes.

http://metabolomics.ucdavis.edu/

We should determine costs and sample prep..

**Comment by kubu4** [comment]
I'll call them to get more info, but here's some basic requirements/turnaround times:
http://metabolomics.ucdavis.edu/contact/how-to-submit

Summary:
- Min number of samples is 50
- Turnaround time is 16 - 18 weeks

**Comment by kubu4** [comment]
Called today. Here's rundown:

Cost: $69/sample (i.e. $3500 to process the minimum 50 samples)
Tissue: Min 10mg (for oyster larvae, we'd have to send more to try to account for shell weight contribution)
Tissue processing: They'd handle this; just need to send them frozen sample.

They've never worked with oyster larvae, so they indicated they might be able to do a test run on a sample or two. However, I neglected to ask if we'd be charged for this...

**Comment by sr320** [comment]
I suggest we ID 50 samples for analysis... I will start new issue

**Comment by laurahspencer** [comment]
I have lots of samples from last year, and some from this year that could be sent. I'll start thinking about which would be best. When is the deadline?

**Comment by sr320** [comment]
I think we have considered it, and now have details of how to proceed.
