### ISSUE TITLE
Questions about graduate committees 

### ISSUE THREAD

**Issue by meganewing** [RobertsLab/resources#1921]
Non coding question regarding general "about being a grad student" stuff. Specifically committees. 
One of my goals for this week is to get my committee formed (finally), but has left me with questions: 

Someone says yes.... now what? Do I just send them the docusign form and that's it? 

Should you meet with them 1 on 1 to go over expectations and things? What would some example expectations be if so?

What does your committee do? 

How often do most folks meet with them? 

How often do you send them stuff? What do you send them? 

How involved are they typically?

**Comment by meganewing** [comment]
@ChrisMantegna Super helpful, thank you! (Perhaps the most helpful bit of it all is knowing that it's okay that I don't have all of these answers right now 😅)

**Comment by ChrisMantegna** [comment]
Big facts @meganewing! The only thing standard in each committee is the name... These are the folks that will ultimately support you in completing your degree, so choose wisely.
