### ISSUE TITLE
sorting for certain biological processes within blast results

### ISSUE THREAD

**Issue by meganewing** [RobertsLab/resources#1924]
I have a blast output from using the o. lurida as my query file. I want to search / sort for hits that are associated with reproduction. Is there an efficient way to do this? Or is it going to be just a lot of ctrl-F-ing for genes that literature says _should_ be there

**Comment by kubu4** [comment]
Please share link to output file. 

To find genes associated with reproduction, you'll need/want to annotate BLAST results with gene ontology terms.

**Comment by kubu4** [comment]
They're mostly the same (in our use cases), but BLAST only provides one type of annotation, which doesn't contain the info you're looking for. 

You need additional annotation information (e.g. GO/GOslim terms).

**Comment by meganewing** [comment]
Okay word -- what does that entail?

**Comment by kubu4** [comment]
Using SwissProt IDs (found in your BLAST results) to retrieve gene ontology terms (IDs) from UniProt (we have code to do this in the Annotation section of the Handbook).

Then, map GO to GOslim...
