### ISSUE TITLE
clam histology drop-off request for Health Sciences Building?

### ISSUE THREAD

**Issue by mgavery** [RobertsLab/resources#1925]
I have Littleneck clam histology cassettes that need to be dropped off in the Health Sciences Building for processing.  I am wondering if someone (with a functioning Husky card) would be willing/able to do this if I bring the cassettes to the lab?  I'm trying to find out if we need to coordinate a day to drop off or if anytime works.  I will update with the response if this will work.

Room info: C411 lab of the Health Sciences building

**Comment by mgavery** [comment]
follow up: any drop off time works.  I will just need to let them know when they've been dropped off.  There is a door code I can provide if this works for someone to drop off.

**Comment by kubu4** [comment]
I'll be in lab a fair amount over the next couple of weeks. 

Feel free to drop the cassettes off whenever, and I'll take them to the histology facility sometime when I'm in.

**Comment by mgavery** [comment]
Awesome! Thanks so much. I put the samples in the flammables cabinet in 209 along with the sample submission sheet.  I'll send the door code via Slack.
![Histo_-_mackenzie_gavery_noaa_gov_-_National_Oceanic_and_Atmospheric_Administration_Mail](https://github.com/RobertsLab/resources/assets/4512578/3e9b8982-2c80-4f07-a375-dc86164c8301)

**Comment by kubu4** [comment]
Made the drop.

![PXL_20240618_170348291](https://github.com/RobertsLab/resources/assets/4514104/6457fcce-cea8-4227-bf23-7f1d1349b7f6)
