### ISSUE TITLE
need to install python to run a python chunk on raven?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1928]
hello!

trying to make count matrices using python and stringtie on raven.

i am running this code chunk (based on [Steven's notebook post](https://sr320.github.io/tumbling-oysters/posts/sr320-14-coddet/)) :    
```{python}
python /home/shared/stringtie-2.2.1.Linux_x86_64/prepDE.py \
-i ../analyses/03-hisat2/list01.txt \
-g ../analyses/03-hisat2/gene_count_matrix.csv \
-t ../analyses/03-hisat2/transcript_count_matrix.csv
```

and get the below message:    
```
> reticulate::repl_python()
Would you like to create a default Python environment for the reticulate package? (Yes/no/cancel)
```

here's a link to my Rmd: [paper-pycno-sswd-2021-2022/code/03-hisat2-summer_2021_2022.Rmd](https://github.com/grace-ac/paper-pycno-sswd-2021-2022/blob/main/code/03-hisat2-summer_2021_2022.Rmd)

**Comment by sr320** [comment]
use bash chunk 

not python chunk

https://github.com/grace-ac/paper-pycno-sswd-2021-2022/blob/2dde4e3531b086c29b10adc951ed359899c2ee60/code/10-hisat-deseq2.Rmd#L283

**Comment by grace-ac** [comment]
thanks! worked
