### ISSUE TITLE
Extract DNA from Lake Trout Samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1929]
Samples are in -20 behind @kubu4 bench...
Only bag with tube boxes.
Samples are in RNAlater.

Specific samples to extract
| ----- |
|  FA 066 |  
|  FA 067 |  
|  FA 068 |  
|  FA 069 |  
|  FA 070 |  
|  FA 077 |  
|  FA 078 |  
|  FA 079 |  
|  FA 080 |  
|  FA 081 |

(_Long term we hope to generate PCR products for sequencing_)

**Comment by kubu4** [comment]
Done. Yields were good.

https://robertslab.github.io/sams-notebook/posts/2024/2024-07-12-DNA-Isolation-and-Quantification---Lake-Trout-Liver/
