### ISSUE TITLE
Looking to see if anything from a set of genes is differentially expressed between treatments

### ISSUE THREAD

**Issue by graceleuchtenberger** [RobertsLab/resources#1930]
I'm doing gene expression analysis of mussel feet kept under different conditions (ocean acidification, warming, and hypoxia) relative to a control and I'm trying to see if the transcripts that code for foot proteins (which make its byssal threads) are differentially expressed. 
I previously did DGE analysis for this project by aligning my transcripts to a transcriptome, but now there's an annotated genome out, so we switched to that. I now have gone through the DESeq process for all treatments using the genome, but I need to run some shrinkage estimates and then get GO ID's for all the DEG's. Previously, Steven had made a list of all expressed transcripts with their GO ID's that I then left joined to my lists (based on transcript #), but now I have actual gene locations that I would like to have GO ID's for. So, my questions are:
1. How do I put my entire list of expressed genes through UniProt to get GO ID's? Do I use the HiSat index file that I have from aligning transcripts to the genome? 
2. How do I then narrow down whether the foot proteins I'm interested in are differentially expressed? Once I've joined my GO ID array to my gene array, do I just search through the array to find genes labeled as encoding for foot proteins?

Repository is here: https://github.com/graceleuchtenberger/Byssus-expression-analysis

**Comment by sr320** [comment]
Lets start with the primary hypothesis. Foot proteins will be differentially expressed.

You need to annotate your genes (this is also the case for GO information.

1) Confirm what the IDs are for your count matrix.

2) Find the corresponding fasta file, or fasta file that can connect to these IDs.

3) Blast this to UniProt-SwissProt.

---

Next step - provide below the first few lines of your count matrix and if you know what correct fasta file might be .... post the header of that (if not just post the count matrix with IDs and first few sequence titles  for RNA and CDSfromGenomic fasta provided from NCBI)

**Comment by graceleuchtenberger** [comment]
Alright, looks like you used the cds file to build the index, so I can just blast that to UniProt?

Here's the count matrix header:
![Screenshot 2024-06-27 at 5 34 05 PM](https://github.com/RobertsLab/resources/assets/122406581/38c168fc-4971-4828-aae5-ffeff8874805)

Here's the cds header:
![Screenshot 2024-06-27 at 5 33 14 PM](https://github.com/RobertsLab/resources/assets/122406581/5f73fbaa-b6f9-44a5-aaa2-f8d5ea00a50e)

Here's the RNA header: 
![Screenshot 2024-06-27 at 5 35 11 PM](https://github.com/RobertsLab/resources/assets/122406581/0814c766-7ad4-4dba-950a-bd287ad676ae)

**Comment by sr320** [comment]
Correct- the next step would be to blast the cds_from_genomic fasta to Uniprot Swiss-Prot database

**Comment by graceleuchtenberger** [comment]
Alright, I blasted the fasta against UniProt using [modified code from your bioinformatics course](https://github.com/graceleuchtenberger/Byssus-expression-analysis/blob/29d9b8eaae6b614fe5790f12ce419789c13dff3b/code/Mtros-genome-blast.Rmd) and I got warnings like this for basically every query:

[Output truncated]Warning: [blastx] Examining 5 or more matches is recommended
Warning: [Query 1-4] Examining 5 or more matches is recommended
Warning: [Query 5-11] Examining 5 or more matches is recommended
Warning: [Query 12-19] Examining 5 or more matches is recommended
Warning: [Query 20-27] Examining 5 or more matches is recommended
Warning: [Query 28-30] Examining 5 or more matches is recommended

Should I be worried about this? Modify the code to look more generally and expand the number of matches?

**Comment by sr320** [comment]
No - not to worry

**Comment by graceleuchtenberger** [comment]
Alright, I am working on doing the annotation, and it looks like my Uniprot only has information for 2 of the 10+ mytilus foot proteins. I followed this protocol [here](https://sr320.github.io/course-fish546-2023/assignments/01-blast.html) and used only the reviewed (Swissprot) entries on Uniprot. Do you think it's worth using the unreviewed ones on TrEMBL too?

**Comment by sr320** [comment]
Use the foot protein sequences as the database

**Comment by sr320** [comment]
That’s expected
