### ISSUE TITLE
Get RNA sequence modification quote 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1931]
from UW Nanopore core

Looking to get info on RNA modification on 116 samples.. 

basis:
> In the case of ONT, translocation speed is controlled by a helicase protein that is loaded onto the nucleic acids during the library preparation and ratchets the template through the nanopore stepwise. Different nucleotides confer different resistances within the pore: the sequence of bases being translocated through the nanopore can be inferred from current intensity  patterns  via  machine-learning  algorithms  in  a  process  commonly  called  ‘base-calling.’  Notably, modified  DNA  or  RNA  bases  cause  characteristic  current  changes  compared  to  unmodified  bases,  thus making  it  possible  to  identify  DNA  and  RNA  modifications  in  individual  molecules  without  any  chemical pretreatments

**Comment by kubu4** [comment]
I have a consultation scheduled for Monday at 10:30, if you want to come with.

**Comment by kubu4** [comment]
Consultation info:

- ~$1600/sample
- Project total: ~$300,000
