### ISSUE TITLE
Littleneck clam histology - pick up slides in HSB?

### ISSUE THREAD

**Issue by mgavery** [RobertsLab/resources#1932]
Hi, would someone be able to pick up the histology slides from the Health Sciences Building? Lab C411.  

I received word that they were available.

Thanks!

**Comment by kubu4** [comment]
I can grab them next time I'm in (hopefully next week).

**Comment by mgavery** [comment]
Sweet! Thanks

**Comment by kubu4** [comment]
Slides have been left on bench in 213, near scale.

![PXL_20240709_183110813](https://github.com/RobertsLab/resources/assets/4514104/d36f81d4-d941-4da2-a1cd-41dcc5a8983e)
