### ISSUE TITLE
sea star samples to send for rnaseq? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1933]
Goal:    
Send off n=18 samples from Day 12 of the multispecies sea star experiment for RNA seq, with the added goal of having even distribution of the three star species --> n=6 dermasterias (leather star), n=6 pisaster (ochre star), and n=6 pycnopodia (sunflower star). 

Stars were co-housed in bins, one of each species. Bin # 7 is not going to be used in this dataset, so the bins are numbered 1-6, and 8. The stars within each bin had the exact same disease exposure so I was hoping to send RNA off for n=6 bins, and not mix and match. 

### **I'm thinking that even though the amount of RNA for one of the leather stars is low (bin 2, sample 523), we could still send and have them do their best effort? So send off RNA for bins 1, 2, 3, 4, 6, and 8?** 

Google sheet of Day 12 Extraction results: [here](https://docs.google.com/spreadsheets/d/177fIEsPEIzlbc0TijFX-AMCnRJhjuucN_WjA-XJ9txU/edit?gid=785175753#gid=785175753) <-- tab labeled "day12_samples" 

And here's a simplified table of the samples:   
| sample_ID_PSC | species                  | treatment | experiment_day | bin_number | total_RNA_in_remaining_sample_ng |
|---------------|--------------------------|-----------|----------------|------------|-------------------------------|
|           517 | dermasterias_imbricata   | exposed   |             12 |          1 |                         358.4 |
|           518 | pisaster_ochraceus       | exposed   |             12 |          1 |                          2632 |
|           519 | pycnopodia_helianthoides | exposed   |             12 |          1 |                         716.8 |
|           523 | dermasterias_imbricata   | exposed   |             12 |          2 |                          74.2 |
|           524 | pisaster_ochraceus       | exposed   |             12 |          2 |                        1089.2 |
|           525 | pycnopodia_helianthoides | exposed   |             12 |          2 |                          1484 |
|           529 | dermasterias_imbricata   | exposed   |             12 |          3 |                         173.6 |
|           530 | pisaster_ochraceus       | exposed   |             12 |          3 |                          1568 |
|           531 | pycnopodia_helianthoides | exposed   |             12 |          3 |                          1764 |
|           535 | dermasterias_imbricata   | exposed   |             12 |          4 |                         529.2 |
|           536 | pisaster_ochraceus       | exposed   |             12 |          4 |                          1652 |
|           537 | pycnopodia_helianthoides | exposed   |             12 |          4 |                          2576 |
|           541 | dermasterias_imbricata   | exposed   |             12 |          5 |                             0 |
|           542 | pisaster_ochraceus       | exposed   |             12 |          5 |                          1134 |
|           543 | pycnopodia_helianthoides | exposed   |             12 |          5 |                          1568 |
|           547 | dermasterias_imbricata   | exposed   |             12 |          6 |                         646.8 |
|           548 | pisaster_ochraceus       | exposed   |             12 |          6 |                         481.6 |
|           549 | pycnopodia_helianthoides | exposed   |             12 |          6 |                         831.6 |
|           559 | dermasterias_imbricata   | exposed   |             12 |          8 |                          1652 |
|           560 | pisaster_ochraceus       | exposed   |             12 |          8 |                           231 |
|           561 | pycnopodia_helianthoides | exposed   |             12 |          8 |                          2016 |

There isn't enough RNA in two of the leather stars... one read as "TOO LOW" (sample ID: 541), and the other read as a total of ~74ng of RNA in the remaining sample (sample ID: 523). 

Samples are eluted in 14ul of water.

**Comment by grace-ac** [comment]
also i have a quote from Azenta already for the 18 libraries!

**Comment by sr320** [comment]
What is the question? Also there are 21 samples on that sheet.

**Comment by grace-ac** [comment]
Yes there are 21, but I’m only going to send 18. So question is if sending
the samples for bins 1, 2, 3, 4, 6, and 8 is a good idea!

Just looking for confirmation or suggestions if I’m missing something.

*Grace Crandall *
she/her

**Comment by sr320** [comment]
Sure - single day is important - not sure of basis of day 12, but maybe we already decided this

**Comment by grace-ac** [comment]
we decided it because it was right before stars dropped arms but after a ton of exposure to disease.

ok great! i'll work on finding a time and way to get these samples shipped off soon.
