### ISSUE TITLE
WGBS planning for Pacific cod (and shark)

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#1935]
This is regarding the quote obtained for WGBS sequencing (#1732) . 

For this sequencing run we plan to include DNA from a few different Pacific cod tissue types (blood, fin, jawbone). The blood and fin DNA is coming from our lab. The jawbone DNA probably needs to be sent from a different lab that specializes in bone DNA extraction. @kubu4 Can I have our collaborators ship jawbone DNA separately from their lab for sequencing? 

We also plan to send a few samples from the Pacific sleeper shark, which probably has a very large genome (perhaps as large as 12Gb). Since this quote is for 12 GB/sample, this could result in low coverage. @kubu4 can the facility accommodate two species during library prep, and increase data for a few sleeper shark samples? 

Just to _triple_ check- we're sending DNA and they are doing the bisulfite treatment etc.?

**Comment by kubu4** [comment]
> Can I have our collaborators ship jawbone DNA separately from their lab for sequencing?

Certainly.

> can the facility accommodate two species during library prep, and increase data for a few sleeper shark samples?

They can accommodate different species (it's just DNA), however, we'd likely need to get a separate quote for the sleeper shark samples.

> we're sending DNA and they are doing the bisulfite treatment etc.?

Yes.

---

NOTE: I'm going to need to get a new quote. The [old quote](https://github.com/RobertsLab/resources/issues/1732#issuecomment-1906587391) expired in April...

**Comment by kubu4** [comment]
@laurahspencer - Please create a new issue with desired sequencing info for sleeper shark samples.

**Comment by laurahspencer** [comment]
Great, thanks!
