### ISSUE TITLE
Determine what additives are for Resazurin assay

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1936]
For the following 

https://github.com/RobertsLab/project-gigas-carryover/blob/main/protocols/Resazurin-assay.md

ant-bacterial and anti-fungi are added 

	◦	100X Penn/Strep – 1 mL
	◦	100X Fungizone – 1 mL

What are these (concentration - how to make) - possible look in literature

**Comment by kubu4** [comment]
We have 100X stock.

Final concentration should be 1x.

**Comment by sr320** [comment]
great - Colby was not using so maybe he forgot or did no know..  (Where is it?)

**Comment by AHuffmyer** [comment]
I'm curious how much it matters to do antibacterial/fungicide before hand - could we do a test of some with and some without and compare? The protocol we were originally sent didn't have any citations for the sample preparation. I can reach out to Katie McFarland to ask for more details on this step if needed. 

I couldn't find records in the literature for this step. The original paper looking at this assay in Zebrafish didn't use it: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5936655/.
