### ISSUE TITLE
Send out 20 clam miRNA samples for sequencing

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1937]

**Comment by kubu4** [comment]
@mgavery - Please fill out the attached Excel sample sheet and upload completed sheet here.

I'm planning on sending samples on Monday.

[30-1035633055_NGS_Template_File.xls](https://github.com/user-attachments/files/16314587/30-1035633055_NGS_Template_File.xls)

**Comment by sr320** [comment]
have these been sent out?

**Comment by kubu4** [comment]
Yep. Sorry.

https://robertslab.github.io/sams-notebook/posts/2024/2024-07-22-Samples-Submitted---Macs-Manilla-Clam-Egg-Samples-for-sRNA-seq-at-Azenta/

**Comment by kubu4** [comment]
These have entered the sequencing queue at Azenta.
