### ISSUE TITLE
Obtain Macrogen per-sample estimate for Sleeper shark WGBS

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#1938]
@kubu4 can you ask Macrogen for the cost is per sample for WGBS data for the Pacific sleeper shark, target coverage of 20x for a large genome (could be as large as 12Gb).  This could theoretically be part of our Pacific cod run, see issue https://github.com/RobertsLab/resources/issues/1732.  Cost would probably dictate how many samples we do.

**Comment by sr320** [comment]
Generally we tell them the number of samples... (cost will vary depending on samples)
I suggest asking for a quote for 8 samples, providing DNA as starting material. 
and quote for 8 samples providing them with BS treated DNA.

**Comment by kubu4** [comment]
Quote request submitted.

**Comment by kubu4** [comment]
Quote is `$1392/sample`.

**Comment by laurahspencer** [comment]
Wow, that's much pricier than I expected.

**Comment by kubu4** [comment]
Admittedly, it's actually _less_ than expected. Considering that the sleeper shark genome is nearly 20X the size of _C.gigas_, and _C.gigas_ always seems to be ~$350/sample. If that scaled linearly, you'd be looking at ~$7000/sample!

**Comment by laurahspencer** [comment]
Yeah, it does make sense. Thanks for getting this!
