### ISSUE TITLE
Raven Access Question

### ISSUE THREAD

**Issue by ChrisMantegna** [RobertsLab/resources#1939]
Question -

I have an REU student who is running models that forecast the range shift of Olympia oysters based on 35 different metrics related to climate change. His computer is not powerful enough to get the runtimes down into something manageable. Is this something that Raven can mitigate, and if so, can I request he gets a temporary access point into Raven? He is not a UW student and doesn't have access to a more powerful remote computing situation at his home institution in the timeframe he needs it to complete his project (as soon as feasible  - August 10th)

Thanks!

**Comment by sr320** [comment]
Sure - just send @kubu4 his email via slack
