### ISSUE TITLE
Tips for frozen larvae/tissue DNA extraction 

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#194]
I am now going to extract DNA from frozen larvae and adult tissue samples. For larvae, I've seen some studies that individually crush larval shells under a scope as their hard shells can result in low quantities of DNA (e.g. [Taris, 2005](http://archimer.ifremer.fr/doc/2005/publication-1814.pdf)). Elsewhere, this step is not used (e.g. [Launey & Hedgecock, 2001](http://www.genetics.org/content/159/1/255), not sure what was done in [Olson & Roberts methylation papter](https://www.biorxiv.org/content/early/2015/03/13/012831)). Any insight? 

As for the extraction, I plan to follow @kubu4 lab notebook entry on his virginica tissue DNA extraction, I will use the E.Z.N.A.® [Mollusc DNA Kit](http://omegabiotek.com/store/wp-content/uploads/2013/05/D3373-Mollusc-DNA-Kit-Online.pdf), of which we have plenty (although the kits are from 2015...). For the homogenization step, the kit says to homogenize in liquid nitrogen. It appears that Sam did not use liquid nitrogen, but instead homogenized with a pestle in buffer. I'd prefer to _not_ use liquid nitrogen. Sam - am I reading your notebook correctly?: 

![image](https://user-images.githubusercontent.com/17264765/37180358-92c0ee88-22dd-11e8-9cb5-5f11f3c7662d.png)

![image](https://user-images.githubusercontent.com/17264765/37180318-67d43b8a-22dd-11e8-9fe0-d9452db211ce.png)

Also, I'd like to incubate overnight at 37C (which the kit says is a viable option). Curious - in ya'll's experience was an overnight 37C incubation OK? Also, @kubu4 did you add glass beads in any of the extraction steps? (Kit does not say to). 

![image](https://user-images.githubusercontent.com/17264765/37180447-e0ff3adc-22dd-11e8-9fde-7a862093b80f.png)

**Comment by sr320** [comment]
LN is not required, you can use plastic mortal and pestle tubes (sterile)
and 37 overnight is fine.

**Comment by kubu4** [comment]
You should use LN2 if possible. If using the plastic pestles & tubes, you'll need to get some pestles ready. Soak in 10% bleach for 15mins (min), rinse in DI water, then autoclave. 

Additionally, it's very possible we're all out if the mortar tubes for use with the plastic pestles. Although not required, they make an enormous difference in the ability to efficiently homogenize samples.

**Comment by kubu4** [comment]
There are more mortar and pestles under the sink in FTR 213.

Autoclave (& instructions; on the wall) are in the room across from the -80C room.

If you have more samples than mortar/pestle combos, then you have to process samples across multiple days in order to clean (use bleach & DI rinse) them.

**Comment by laurahspencer** [comment]
Budget Number for liquid nitrogen?  I'm going to grab some this afternoon, enough to do 3 test samples

**Comment by sr320** [comment]
use the Hall number

**Comment by laurahspencer** [comment]
Finished isolating larvae & mantle tissue; better results this time! Do my numbers meet the sequence facility's min. DNA requirements?: 

DNA VIAL # | SAMPLE # | Treatment | TISSUE TYPE | tissue mass (ug) | DNA Concentration (ng/uL) | Total ng DNA after assay | 1% of DNA (ng)
-- | -- | -- | -- | -- | -- | -- | --
test10-B | 27-A | HL-10-Low | Frozen larvae | 35 | 10 | 1,900 | 19
test11-B | 60-A | HL-10-Low | Frozen larvae | 36.9 | 12.1 | 2,299 | 23
test12 | 73-A | HL-10-Low | Frozen larvae | 12.6 | 5.5 | 1,045 | 10
test13 | 59-A | HL-6-Ambient | Frozen larvae | 29.5 | 12.75 | 2,423 | 24
test14 | HL-10-12 | HL-10-Low | Frozen mantle | 28.1 | 11.4 | 2,166 | 22
test15 | HL-10-10 | HL-10-Low | Frozen mantle | 14.1 | 6.18 | 1,174 | 12
test16 | HL-6-18 | HL-6-Ambient | Frozen mantle | 34.9 | 10.475 | 1,990 | 20
test17 | HL-6-20 | HL-6-Ambient | Frozen mantle | 34.5 | 4.68 | 889 | 9

I will plan on processing my "actual" samples on Monday. 

Issues I encountered tonight: 
  * **Getting larvae out of sample tube.**  they are at the bottom of the tube, and semi-liquid once thawed.  I inverted the tube and tapped vigorously into the mortar, but I leave a bunch of larvae behind in the tube.  I tested adding liquid nitrogen directly into the microcentrifuge tube, which works OK. Could try using disposable pipette, with tip cut off.  If anyone has found the best method, let me know!  
  * **Transferring powdered/frozen sample into clean tube.**  Metal spatulas we have are too big. I ordered small metal spatulas / scoops, arriving Sunday.  
  * **Sterilizing metal spatulas used to scrape/transfer frozen tissue.** Is it adequate to soak metal spatulas in 10% bleach, then rinse twice with DI water, between samples?  (FYI I ordered 9 of the above spatulas, so will be OK for Monday, but am generally curious what your metal sterilization protocol is).  

Thanks!

**Comment by kubu4** [comment]
> Do my numbers meet the sequence facility's min. DNA requirements?

To date, the smallest amount of DNA we've successfully submitted for MBD-BSseq is 19ng. Off-hand, I can't find/remember what the actual limits are. I'll contact them to get an absolute cut-off amount.

> I will plan on processing my "actual" samples on Monday.

Before doing so, please be sure to read through the MBD protocl (MethylMiner Kit)! This will inform you on what the input volume should be (and, in turn, inform you what your elution volume should be when using the PAXGene DNA kit).

>  Getting larvae out of sample tube.

I don't have any specific suggestions, as I haven't done this before, but a narrow spatula seems like the best approach (hopefully that's what  you ordered, as we don't have any).

> Is it adequate to soak metal spatulas in 10% bleach, then rinse twice with DI water, between samples? 

Definitely, but soak time should be ~10 minutes, if not including an ethanol/flame step in the sterilization process.

**Comment by kubu4** [comment]
> (FYI I ordered 9 of the above spatulas

I don't see a record of this order on the Roberts Lab Purchasing Log.

Please be sure to follow the instructions on the [Purchasing Wiki](https://github.com/RobertsLab/resources/wiki/Purchasing) for all purchases.

**Comment by jldimond** [comment]
I am tuning in late here, but for my recent mortar and pestle LN2 grinding, I cleaned and sterilized mortars and pestles in between samples by first scrubbing under hot water, then pouring in about 1mL of ethanol and lighting on fire. I read this technique somewhere and it seems acceptable to me in lieu of autoclaving.
