### ISSUE TITLE
Psomagen Sample Prep

### ISSUE THREAD

**Issue by ChrisMantegna** [RobertsLab/resources#1940]
Hello!

I need some help in getting the order form completed and samples prepared for shipment to Psomagen. 
1. This is the [order form](https://github.com/ChrisMantegna/WDFWmussels_epigenetics/blob/main/(Form)%20Psomagen_NGS_Order_Sheet_2024.xlsx). 
2. Can you help me with the library, run and deliverable columns? I'm unclear which of the information from the quote goes on the sheet and what is considered redundant/ common knowledge to them.
3.  Which of these sample buffers should I be sending the samples in? What do we have in the lab?
<img width="401" alt="Screenshot 2024-07-23 at 7 10 45 AM" src="https://github.com/user-attachments/assets/a4251af5-8580-4337-9b32-400a441ff710">
4. Should I ask them to print a FedEx label (they offered), or do we prefer to use our account to ship? If our account, what is the number?

Thank you!

**Comment by kubu4** [comment]
Please post the quote so we can see what you ordered.

Also, feel free to ask the Psomagen people  - they're fairly responsive and very helpful.

> Which of these sample buffers should I be sending the samples in?

Just enter in whatever buffer they're currently in. It's not possible to change the buffer (since they're already in buffer).

**Comment by ChrisMantegna** [comment]
Sam, you placed the quote. It was emailed to you. 

Also, the buffer it's in is whatever the C6 solution is from the Qiagen extraction kit. 

What about FedEx? Should I just let them print it?

**Comment by kubu4** [comment]
> Also, the buffer it's in is whatever the C6 solution is from the Qiagen extraction kit.

Then select "EB" from the drop down menu. The "EB" stands for Elution Buffer.

> What about FedEx? Should I just let them print it?

Sure! Will save you the hassle of having to write out the FedEx slip and get a budget number at the SAFS desk.

---

For posterity, here's a link to the quote (GitHub Issue comment):

https://github.com/RobertsLab/resources/issues/1884#issuecomment-2096964264

From the quote:

```
Application: WGBS
Species: Animal
Starting Material: gDNA ( > 200 ng DIN > 7)
Sample Size - 24
Library Prep Kit- Accel DNA Methylation
Platform - Novoseq X plus 150 PE
Output - 26 GB (~20X coverage)
 Deliverable - raw FastQ (including PhiX - sequence for downstream analysis)
Data delivery method - FTP
Timeline - 4-6 weeks
```

So, for the sample sheet, choose the following options from the dropdown menus (or, enter manually if no dropdown menu is present):

Library: `Swift Accel-NGS® Methyl-Seq DNA Library`
Sequencing Coverage Unit*: `X/unit`
Sequencing Coverage*: `20`
Read length: `Illumina 150bpPE`
Analysis: `Raw data`
Data delivery: `FTP Link (Download)`

**Comment by ChrisMantegna** [comment]
Thank you!
