### ISSUE TITLE
Get Quote for coral WGBS 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1942]
Analogous to recent RNA seq quote.

Want WGBS for 116 samples, sending DNA

**Comment by kubu4** [comment]
Quotes have been requested from Azenta, Zymo, and GenoHub.

**Comment by kubu4** [comment]
Zymo quote: `$42,873.60`

[Quote_QUO18419_1722383150835.pdf](https://github.com/user-attachments/files/16435672/Quote_QUO18419_1722383150835.pdf)

**Comment by kubu4** [comment]
Psomagen quote: `$25,636`

($221/sample)

**Comment by kubu4** [comment]
Azenta quote: `$27,890`

($240/sample)


[30-1067895835_R2.pdf](https://github.com/user-attachments/files/16474053/30-1067895835_R2.pdf)

**Comment by kubu4** [comment]
Genohub quotes are in.

`23,664.00`

[Genohub_Quote_55027585_Confirmed.pdf](https://github.com/user-attachments/files/16532028/Genohub_Quote_55027585_Confirmed.pdf)

---

`$27,003.47`

[Genohub_Quote_55011817_Confirmed.pdf](https://github.com/user-attachments/files/16532030/Genohub_Quote_55011817_Confirmed.pdf)

**Comment by kubu4** [comment]
Apparently Zymo saw our quote request come across Genohub and they realized [their initial quote](https://github.com/RobertsLab/resources/issues/1942#issuecomment-2259547188) was "wrong." Here's the updated quote.

`$31,911.60`

[Quote_QUO18419_1722971332835.pdf](https://github.com/user-attachments/files/16532050/Quote_QUO18419_1722971332835.pdf)

**Comment by hputnam** [comment]
@sr320 @kubu4 Confirming Steven's preference for Azenta. I will have Jill and Zoe move forward with DNA aliquots for Azenta [30-1067895835_R2.pdf](https://github.com/user-attachments/files/16474053/30-1067895835_R2.pdf)

**Comment by kubu4** [comment]
Sample sheet needs to be filled out:

[30-1067895835_NGS_Template_File.xls](https://github.com/user-attachments/files/16591351/30-1067895835_NGS_Template_File.xls)


I'll get PO requested.

**Comment by kubu4** [comment]
Have requested updated quote for 120 samples. Will post sample sheet submission form when I received revised quote.

**Comment by kubu4** [comment]
Updated quote:

`$28830.00`

[30-1067895835_R4.pdf](https://github.com/user-attachments/files/16605370/30-1067895835_R4.pdf)


Sample sheet needs to be filled out:

[30-1067895835_NGS_Template_File.xls](https://github.com/user-attachments/files/16605374/30-1067895835_NGS_Template_File.xls)


Will request PO number.

**Comment by JillAshey** [comment]
Azenta requires 500ng of DNA for WGBS. Looking over the [DNA concentrations](https://docs.google.com/spreadsheets/d/1iFsVfp1vix9IfNcqSajQfLgXXDg0CCPT/edit?gid=1140341238#gid=1140341238), we have ~34 samples that have less than that. I'm not sure if we should send samples with <500ng. We should decide if we need to re-extract these. Either way, we likely have to push back sending the DNA samples out. 

Today, Zoe and I can either re-extract the 34 DNA samples or prep the RNA plates.

**Comment by hputnam** [comment]
Can you call Azenta today and ask their minimum amount?

**Comment by JillAshey** [comment]
From Azenta: Thanks for your interest in Genewiz Multiomics Solutions! Our methylation sequencing workflow kit says it will work well with inputs as low as 10 ng of DNA. However, our lab prefers to have at least ~300ng of input DNA given our internal workflow optimizations.

**Comment by kubu4** [comment]
I received a PO number yesterday, so we're all set on that front.

**Comment by hputnam** [comment]
@sr320 based on Jill's chat with Azenta and thinking about potential batch effects, Jill and I discussed and propose the following for your approval.

The samples are in RNA/DNA shield, which has lysed the cells and made the liquid a homogenized nucleic acid pool so the RNA and DNA have the potential to be directly related. Due to this I can't think of super strong effects from doing another extraction of DNA and adding the DNA to the previously extracted DNA to bring all of the total ng to the same amount to submit to Azenta.  This way all of the library preps and sequencing would occur at the same time.  We can then also after the  sequencing examine statically for any extraction batch effects.  @sr320, do you agree with this approach? If so, Jill will move ahead for the necessary re-extractions, aliquoting, and shipment to Azenta based on the PO number from Sam above.

**Comment by sr320** [comment]
Sounds like a good plan to me.... 

(as a side note can we get metabolomic test samples out prior to re-extraction if not already sent out?)

**Comment by hputnam** [comment]
Thanks @sr320 ! @JillAshey can you switch the priority order to metabolomic test samples then DNA re-extraction? Thanks @JillAshey !

**Comment by JillAshey** [comment]
Sounds good, will prioritize the metabolomic test samples.

**Comment by JillAshey** [comment]
Tracking number for DNA to Azenta: 779092801013. 120 samples sent with sample [manifest](https://docs.google.com/spreadsheets/d/1iFsVfp1vix9IfNcqSajQfLgXXDg0CCPT/edit?gid=1765842332#gid=1765842332) and quote. Should arrive by tomorrow (10/9) morning.
