### ISSUE TITLE
Do we have access to UV to sterilize tubes? 

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1945]
In the next couple of weeks I'll be preparing tubes for a research cruise in the Caribbean. Do we have UV light in one of the hoods to sterilize some tubes?

**Comment by kubu4** [comment]
I think the PCR Workstation in 213 has a UV light that is _known_ to still have many hours of use.

There _is_ a UV light in the biosafety cabinet (BSC) in 213, but the UV light has never been changed in the 17yrs I've been here _and_ that BSC was in this lab _prior_ to Steven and I moving in here. So, I wouldn't trust that UV light to still be effective for sterilization.

**Comment by AHuffmyer** [comment]
Thank you! I'll use the UV light on the PCR workstation. I'll probably work on this a bit next week.
