### ISSUE TITLE
Epigenetic Primer Design

### ISSUE THREAD

**Issue by anita-wray** [RobertsLab/resources#1947]
What program do you use for multiplex primer design to amplify bisulfate-treated sequences? Any advice or manuals/how-tos would be greatly appreciated!

For reference: I am trying to replicate the methods (as closely as possible) in [this study](https://onlinelibrary.wiley.com/doi/10.1111/1755-0998.13440).

**Comment by kubu4** [comment]
If you're looking to replicate that study, you should give PRIMERSUITE a shot (that's what they used). It's a web-based primer design program. It appears to be pretty straightforward.

I have a recent notebook entry which designed bisulfite primers in a reproducible manner using Primer3, followed by EMBOSS PrimerSearch to confirm primer specificity:

https://robertslab.github.io/sams-notebook/posts/2024/2024-07-29-Primer-Design---Lake-Trout-C1q-Gene-Bisulfite-Sequencing-Primers-Using-Primer3/

Unfortunately, I don't really have any specific advice on multiplexing. I think that will just take some manual evaluation of primer specificity, as well as comparing primers to each other for potential to anneal to each other.
