### ISSUE TITLE
Low DIN Score on Mussel Samples

### ISSUE THREAD

**Issue by ChrisMantegna** [RobertsLab/resources#1948]
Hello!

I don't know how to proceed. Psomagen has run QC on the mussel samples and DIN values range from 1.3 to 5.8 across all 24 samples. No sample is above 7 which is the cutoff written on the original quote request. I've attached the table for you to view beyond the screenshot here. 
<img width="1556" alt="Screenshot 2024-08-07 at 1 15 23 PM" src="https://github.com/user-attachments/assets/4007954a-e539-44b1-bb00-795f01de49ff">

 How should I proceed?
[Original_Sample_QC_AN00020747_ANW240807S003Q002.xlsx](https://github.com/user-attachments/files/16533788/Original_Sample_QC_AN00020747_ANW240807S003Q002.xlsx)

**Comment by sr320** [comment]
What QC was done prior to sending?

**Comment by ChrisMantegna** [comment]
No. I ran them through the Qubit for DNA quantification only. There's still half of each sample's volume remaining in the lab, should I check them as well even though I'd suspect I'd get similar results?

**Comment by ChrisMantegna** [comment]
I ran the gel on 6 samples that I extracted yesterday, it is below. All of this information is in [my repo](https://github.com/ChrisMantegna/WDFWmussels_epigenetics/blob/main/20240829_test_extractions_concentration_gel.xlsx) as well as below. What do you think? 
All samples with 'A' are gill tissue, those with 'B' are mantle tissue. The gel ran for 2 hours at 100v.
Concentrations (ng/ uL):
* 79A - 79.1
* 79B - 1080
* 80A - 46.8
* 80B - 746
* 92A - 210
* 92B - 204
![gel](https://github.com/user-attachments/assets/8cd0b0b6-bf75-4eed-bf7b-e2fc88065e33)

**Comment by sr320** [comment]
Mantle DNA looks less degraded

**Comment by ChrisMantegna** [comment]
Yup. The chloroform came in, so I'm going to do the extractions on the rest of the mantle samples and run a gel to see what the others look like.

**Comment by ChrisMantegna** [comment]
Here is the gel for the remaining 22 mantle samples; I added the ladder to both sides because I thought it would be less confusing to view as a whole. All concentrations are more than enough, with the lowest concentrations coming in around 89 - 90 ng/uL.\
What do you think? Does it add complication if we keep some gill and some mantle?
![9-2gel](https://github.com/user-attachments/assets/0643516d-0949-4946-b28d-22fd6c8657f4)

**Comment by sr320** [comment]
You have DNA,,
Yes

Let’s discuss

**Comment by ChrisMantegna** [comment]
Ok. Do you have any open appointment times on Wednesday or Thursday before 10am? If we decide to ship samples out, they have to go out on Thursday if possible - I'm out of the area all of next week, so if we're sending samples out I will have to ask Sam to do it if he's in.

**Comment by ChrisMantegna** [comment]
We have results! The DIN scores are better for all but 3 samples and I've included a [quick table](https://github.com/ChrisMantegna/WDFWmussels_epigenetics/blob/main/samplePAHclassification.csv) of which samples belong to which PAH category. 
This time, 8 of 24 samples passed DIN, 12 of 24 samples failed, and 4 of 24 are on hold. The failed samples all have a higher DIN than the failed gill tissue samples. The hold samples are less clear, but based on the graphs for each it's possibly because of the distribution of the sample across base pair ranges. 
The newest QC report is in the [GH repo](https://github.com/ChrisMantegna/WDFWmussels_epigenetics/blob/main/Mantle_Sample_QC_AN00021156_September11.pdf).
