### ISSUE TITLE
Order disposable mortar and pestles

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#195]

**Comment by laurahspencer** [comment]
Not sure what constitutes a mortar tube. We currently have plenty of these 1.7mL sterile microcentrifuge tubes, which _look_ like they may work as mortar tubes. Also, lots of small PCR tubes. 

![img_3867](https://user-images.githubusercontent.com/17264765/37187289-83fda596-22fe-11e8-96e3-dd47cf05636f.JPG)

**Comment by kubu4** [comment]
I don't think we have any. If we do, they're blue 1.7mL tubes on the shelf at the RNA station in 209.

**Comment by kubu4** [comment]
Technically, they will accommodate the pestles. However, the pestles don't achieve a very snug fit and those tubes are also very flexible (compared to the proper tubes); both of these things make homogenization inefficient (i.e difficult).

**Comment by kubu4** [comment]
Ordered.
