### ISSUE TITLE
Aquire Klone node

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1952]

**Comment by kubu4** [comment]
Next-gen HPC slices (AMD):
256GB: $3,174.33
512GB: $7,706.17

**Comment by sr320** [comment]
think we need 512?

**Comment by kubu4** [comment]
Probably be best, but Raven is 256 and does pretty well with the stuff we throw at it.

**Comment by sr320** [comment]
lets go with a 512 - GR006094

**Comment by kubu4** [comment]
I've submitted the requested info to UW IT. Will update here with progress.

**Comment by kubu4** [comment]
Although, check out the `coenv` `cpu-g2` node!

![image](https://github.com/user-attachments/assets/8a288f21-3f59-4da1-8c22-5bb4d91538db)

**Comment by sr320** [comment]
But we lose this when our nodes expire?

**Comment by kubu4** [comment]
Oh yeah, that's probably correct! Thanks.

**Comment by kubu4** [comment]
Have submitted signed/dated paperwork to UW IT.

**Comment by kubu4** [comment]
DocuSigned final version. I think it's complete.

Will report back when deployment date is determined.

**Comment by kubu4** [comment]
Wow! It's up and running! That was faaaaaast!

> Hi Sam,
>
> We've completed the installation of the 1x 512GB Slice for the "srlab" allocation.
>
> Please visit https://hyak.uw.edu/docs/ for the cluster documentation. If you have any questions please email help@uw.edu and mention "Hyak" to get further follow-up from our team.

![image](https://github.com/user-attachments/assets/3b6bd062-7f80-4710-a43d-de42397c8303)
