### ISSUE TITLE
Set up sponsored account/access to Klone for Emma Strand

### ISSUE THREAD

**Issue by shellywanamaker** [RobertsLab/resources#1957]
emma.strand@gmgi.org

**Comment by sr320** [comment]
the first step is getting a UW net id - @kubu4 can you help with that?

**Comment by kubu4** [comment]
Alrighty, Emma should be receiving an email from UW IT with a Sponsored NetID.

I'll update here when that's been issued.

**Comment by sr320** [comment]
Husky OnNet for Affiliates is pending acceptance from Emma via gmgi email

**Comment by sr320** [comment]
@kubu4 can you also give elstrand access to klone/mox via srlab group?

**Comment by kubu4** [comment]
> @kubu4 can you also give elstrand access to klone/mox via srlab group?

Done.
