### ISSUE TITLE
Purchase user license for Adobe products through UW? 

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1959]
Is there potential for purchasing a user license for Adobe products through UW? My license with URI expired and I would still like to be able to use Illustrator, etc. for generating figures. 

Cost is $175/year with more information [available here](https://itconnect.uw.edu/uware/adobe-creative-cloud-suite/). 

Acquiring a license requires budget worktags and submission of [this form](https://uw.service-now.com/sp?id=sc_cat_item&sys_id=165a8977dbdc5810de61105f689619ed).

**Comment by sr320** [comment]
Sure

**Comment by AHuffmyer** [comment]
Request submitted REF0970852
