### ISSUE TITLE
Do we have any mercaptethanol?

### ISSUE THREAD

**Issue by jldimond** [RobertsLab/resources#196]
Need to add some to reagent in Qiagen RNeasy kit (calls for 14.3 M β-mercaptoethanol). If someone could check for me then I can figure out if I need to order some. Thanks.

**Comment by kubu4** [comment]
Yes, in fridge in 209. Small brown bottle, stored 8n cardboard box with a bunch of other miscellaneous reagents. Should be listed on MyChem.

**Comment by jldimond** [comment]
Great thank you - was not aware of MyChem. I may be in next Monday to do some RNA extractions, or at the very least use some reagent.
