### ISSUE TITLE
Run methylation analysis (bismark) on ceasmallr samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1961]
sample info : https://github.com/sr320/ceabigr/issues/111#issuecomment-2078062169

**Comment by sr320** [comment]
repo: https://github.com/sr320/ceasmallr

**Comment by kubu4** [comment]
Just an update.

This is running, but there's a strong possibility that this will need to run for a week or two (hope I set it up correctly...)!

**Comment by kubu4** [comment]
Bismark alignment has finally completed!

Now, on to deduplication.

**Comment by sr320** [comment]
can we try next steps on klone?

**Comment by kubu4** [comment]
Sure.

I can tap into 100CPUs and 1000GB of RAM on the coenv node...  :smile:

**Comment by kubu4** [comment]
Alrighty, I think this is complete.

Outputs are here: https://gannet.fish.washington.edu/Atumefaciens/gitrepos/ceasmallr/output/

All code is in ceasmallr repo.

**Comment by kubu4** [comment]
Hold up on this. It seems like something wonky happened with deduplication that I'm trying to figure out.

**Comment by kubu4** [comment]
Per #2030, I resolved the weird deduplication issue. However, it means I have to re-run that process, followed by methylation extraction. Will likely be finished tomorrow afternoon.

**Comment by kubu4** [comment]
This has completed and has been rsync'd to:

https://gannet.fish.washington.edu/Atumefaciens/gitrepos/ceasmallr/output/

**Comment by sr320** [comment]
yes please

**Comment by kubu4** [comment]
Gah!!! Alrighty, on it.
