### ISSUE TITLE
Oyster counts and size measurements of 10K seed images

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#1963]
From our images of 10K seed project, we need to do the following: 

- Count the number of oysters in each photograph 
- Measure size of oysters in each photograph 

The images for analysis can be downloaded here: https://github.com/RobertsLab/10K-seed-Cgigas/tree/main/data/images_0915 

Here is a general protocol. Contact @AHuffmyer with questions or if you'd like to meet over Zoom to go over a detailed protocol. 

- Download the images 
- Start a Google sheet (and share link with ashuff@uw.edu) with a tab for "counts" and a tab for "size" 
- Open the image in ImageJ or other image analysis software
- Count the number of oysters present in each photo and record this on the data sheet. On the data sheet, include the name of the image. The image name includes the bag number (e.g., bag 30). 
- Measure the size (length and width) for at least n=50 oysters in each photograph. First be sure to set the length standard using the ruler in the image. Choose a random selection of oysters (not just the large or the small ones). In the data sheet, record the length and width of each oyster and the image name for each measurement. 
- Plot the mean size for oysters in each bag.

**Comment by Noahk22** [comment]
Looks good! I will get started with this tomorrow or possibly a bit tonight!

**Comment by AHuffmyer** [comment]
Great - let me know if you have any questions! Thanks!

**Comment by AHuffmyer** [comment]
I'll add more photos to this folder tomorrow when I am out at the hatchery.

**Comment by Noahk22** [comment]
Just to confirm, Bag 30a and Bag 30b are pictures taken of the same group of oysters and I would only have to count and measure the picture Bag 30a for instance, and not 30b and 30c, right?

**Comment by sr320** [comment]
yes all the same.

**Comment by Noahk22** [comment]
Sounds good!

**Comment by AHuffmyer** [comment]
The data look great, Noah! Thanks for your help. Keep up the great work and let me know if you have any questions.

**Comment by AHuffmyer** [comment]
Adding link to Google Sheet here: https://docs.google.com/spreadsheets/d/1AyjsakZbCdKnpOD1UXf36C95OrngP5d03biPYL_bwIA/edit?gid=0#gid=0

**Comment by sr320** [comment]
@Noahk22 be sure to notebook post at https://genefish.wordpress.com/

**Comment by Noahk22** [comment]
Yep, I'm on it!

**Comment by AHuffmyer** [comment]
Completed
