### ISSUE TITLE
raven: R studio code chunks not running... 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1964]
I thought I successfully cancelled my running code chunks in R studio on Raven, and I even deleted the script and made a new one, but when I try to run a basic chunk like:   
```{bash}
pwd
``` 

I get the timer symbol, and the window that says: "The code in this chunk is scheduled to run later, when other chunks have finished executing."

How do I figure out which code chunks are running... and how do I then cancel them to start over?

**Comment by sr320** [comment]
try restarting R - https://d.pr/i/GAL9xq

**Comment by grace-ac** [comment]
gah of course. it worked! t hanks!
