### ISSUE TITLE
access to Gannet for Emma Strand

### ISSUE THREAD

**Issue by shellywanamaker** [RobertsLab/resources#1966]
@kubu4 can you please set up access to Gannet for Emma so she can back up analysis she does on Klone? We budgeted $3.3K in the grant for 6 x 16 TB UPC storage drives and an expansion unit so I can purchase that and have it shipped to you any time.

**Comment by kubu4** [comment]
Will do.

> 6 x 16 TB UPC storage drives and an expansion unit

Sorry, can you clarify what you're talking about here (i.e. specifics)? I don't know what "UPC storage drives" are.

**Comment by kubu4** [comment]
Access granted!

**Comment by shellywanamaker** [comment]
I don't what UPC meant. I copied that from the grant but I'm not sure where I got that from in the first place. What I meant is 6 x 16TB HDDs and an expansion unit to expand Gannet. 

I saw on the purchasing log that you got 3 x 16TB HDDs - Seagate ST16000NEZ00 for Gannet expansion (cat: B07SLPTK17) last November. Are these the drives I should order?

**Comment by sr320** [comment]
Don’t order anything until we chat
