### ISSUE TITLE
expanding Gannet 

### ISSUE THREAD

**Issue by shellywanamaker** [RobertsLab/resources#1967]
Opening this issue to discuss expanding Gannet to be able to support storage needs for the [USDA shellfish omics meta-analysis project](https://resilience-biomarkers-for-aquaculture.github.io/).

We budgeted for 6 x 16TB HDDs and an expansion unit to expand Gannet.

I saw on the purchasing log @kubu4 ordered 3 x 16TB HDDs - Seagate ST16000NEZ00 for Gannet expansion (cat: B07SLPTK17) last November and a Synology RX1217 12 Bay expansion for Gannet (cat: 4292258) last July.

Are these the drives and expansion unit I should order?

**Comment by kubu4** [comment]
We cannot expand Gannet beyond the single expansion unit that's already installed.

However, we might be able to upgrade all of the HDDs to 20TB (28 drives x (20TB - 16TB) = 112TB of additional space), which would be similar to the 6 x 16TB HDDs budgeted for... Also, I'd have to check to see if the Synology can accept 20TB HDDs.

**Comment by shellywanamaker** [comment]
gotcha. That would be great if you can check on the 20TB HDDs. Is there open space for more 16TB HDDs or is the expansion unit completely filled?

**Comment by kubu4** [comment]
Completely filled.

**Comment by kubu4** [comment]
20GB HDDs are compatible.

Price range is ~$500 - $900/ea, depending on brand.

**Comment by shellywanamaker** [comment]
ok. Do all 28 drives need to be the same size?

**Comment by sr320** [comment]
Remind us the dollar amount budgeted?

**Comment by shellywanamaker** [comment]
"A total of $3,300 in year 1 is requested to cover the cost for 6 x 16TB ultra high performance storage drives at $300 each and the cost for an expansion unit for data volume expansion at $1500."

**Comment by sr320** [comment]
So $4800 ?

**Comment by kubu4** [comment]
> ok. Do all 28 drives need to be the same size?

Don't think so, as long as they're >= to existing drives.

**Comment by shellywanamaker** [comment]
$3,300 total. 
3300 = (6 *$300) + $1500

**Comment by sr320** [comment]
@kubu4 - maybe give her a recommendation for $3300 that makes sense for our
system set-up

**Comment by kubu4** [comment]
Have confirmed that Raven should be able to handle that external drive:

```bash
(base) sam@raven:~$ cat /sys/bus/thunderbolt/devices/0-0/device_name 
Dell Precision Thunderbolt 3 Add-in Card
```

**Comment by shellywanamaker** [comment]
That's great. This is significantly less space than initially proposed (16TB vs. 96TB), and I realize I underbudgeted. But it's possible to divert some funding from support staff salary to supplies if that makes more sense. I'm wondering if it makes sense to get a 32 TB ($6100) or if get the 16TB one for now and see how that goes. And if needed, but another one down the line? @kubu4 would it be possible to connect multiple drives like these to Raven?

**Comment by kubu4** [comment]
Yep.

**Comment by shellywanamaker** [comment]
I'm thinking ahead for sharing data with collaborators, @kubu4 does Raven have the same interface as Gannet for viewing/sharing files like  [https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/](https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/)?

**Comment by sr320** [comment]
Sharing will be done on gannet.

**Comment by shellywanamaker** [comment]
ok so save data on Raven and link it through Gannet?

**Comment by sr320** [comment]
If working on raven - yes rsync output to gannet... same when you are using klone.

**Comment by shellywanamaker** [comment]
OH!! got it. So we will still be syncing everything to Gannet. I will go ahead and purchase the drive

**Comment by shellywanamaker** [comment]
Is this correct (sorry it's been a while):

Sam White
University of Washington School of Aquatic and Fisheries Sciences
1122 NE Boat Street
FTR 232
Seattle, WA 98105

**Comment by kubu4** [comment]
Received the HDD today. 

No packing slip included.

I'll report back later today with how to access on Raven.

**Comment by kubu4** [comment]
HDD came in this bad boy, LOL!

![image](https://github.com/user-attachments/assets/5c8bcdb5-1529-4126-90a5-d97b5008a658)

**Comment by kubu4** [comment]
Also, I probably won't be able to get this setup on Raven today. Looks like I'm going to need to fuss around with partitions/mounting/formatting junk...

**Comment by kubu4** [comment]
New external HDD has been configured and is ready to roll.

Can be accessed at: `/home/shared/16TB_HDD_01`
