### ISSUE TITLE
issue with pulling from GitHub on raven

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#1968]
before i commit, i tried pulling while in Raven and got this error:

>>> /usr/bin/git pull
fatal: update_ref failed for ref 'ORIG_HEAD': could not write to '.git/ORIG_HEAD'

anyone know what this means? how do i fix?

**Comment by sr320** [comment]
what repo? 
can you provide a screenshot?

**Comment by grace-ac** [comment]
repo: [https://github.com/grace-ac/paper-pycno-sswd-2021-2022](https://github.com/grace-ac/paper-pycno-sswd-2021-2022)

i just tried to pull again and got a different message: 

![Screenshot 2024-10-01 at 1 59 02 PM](https://github.com/user-attachments/assets/ea6ef044-0b29-40af-b4f9-b2c976c098db)

**Comment by kubu4** [comment]
You may want to see if you have the file `.git/ORIG_HEAD.lock`

If you have that, delete that lock file (`rm .git/ORIG_HEAD.lock`) , then try to pull. If pulling fails again with that same error message, _then_ delete `.git/ORIG_HEAD`

`rm .git/ORIG_HEAD`

**Comment by kubu4** [comment]
My comment above is in response to your original post. Not sure what to do regarding [your subsequent post](https://github.com/RobertsLab/resources/issues/1968#issuecomment-2387066588).

**Comment by kubu4** [comment]
The new error message suggests that the `main` branch was removed from the remote site (i.e. removed from GitHub.com).

Try running this in a Terminal (in that git repo) and let us know what it says:

`git ls-remote origin`

**Comment by grace-ac** [comment]
```
Graces-MacBook-Air-10:paper-pycno-sswd-2021-2022 graciecrandall$ git ls-remote origin
6f9a2e3a19851c7269c933603f6149b651a292da	HEAD
6f9a2e3a19851c7269c933603f6149b651a292da	refs/heads/main
```

**Comment by kubu4** [comment]
But, honestly, with stuff like this, it's probably easier to copy the documents you've made changes to, to another location on the computer, then nuke your local copy of the problematic repo, and then re-clone the repo.

Then, copy your the docs back over to the freshly-cloned repo....

**Comment by grace-ac** [comment]
ok! 

 i don't get how this happened in the first place? I usually am pretty good about pulling before committing and pushing.

**Comment by kubu4** [comment]
Also, any possibility that the HDD is full???? That's a common cause of weird problems with various programs...

Which HDD are you using?

**Comment by grace-ac** [comment]
Wouldn't have thought to check that!

I'm using 8TB_HDD_02

**Comment by sr320** [comment]
```
/dev/sdd1       7.3T  6.9T  898M 100% /home/shared/8TB_HDD_02
/dev/sdb1       7.3T  4.4T  2.6T  64% /home/shared/8TB_HDD_03
```

full?

**Comment by kubu4** [comment]
Yep, that's the issue!

**Comment by grace-ac** [comment]
ok yay! i'm sure i have tons of stuff i  can remove... i'll look through that this evening after my meetings and tomorrow morning

**Comment by kubu4** [comment]
The sooner you can tackle this, the better. Everyone uses that drive and, as long as it's full, no one else will be able to run any analysis.

**Comment by grace-ac** [comment]
got it!! i'll get it going after my meetings. hopefully they'll wrap up quick

**Comment by kubu4** [comment]
Thanks!

**Comment by grace-ac** [comment]
is it a bad idea to delete files that were used to create count matrices?

as an example: 

```
graceac9@raven:~/GitHub/paper-pycno-sswd-2021-2022/analyses/03-kallisto$ ls
kallisto_20240118.isoform.counts.matrix                PSC-36  PSC-52  PSC-67
kallisto_20240118.isoform.TMM.EXPR.matrix              PSC-37  PSC-54  PSC-69
kallisto_20240118.isoform.TPM.not_cross_norm           PSC-38  PSC-56  PSC-71
kallisto_20240118.isoform.TPM.not_cross_norm.runTMM.R  PSC-39  PSC-57  PSC-73
PSC-19                                                 PSC-40  PSC-58  PSC-75
PSC-23                                                 PSC-42  PSC-59  PSC-76
PSC-24                                                 PSC-43  PSC-61  PSC-78
PSC-34                                                 PSC-48  PSC-63  PSC-81
PSC-35                                                 PSC-49  PSC-64  PSC-83
```

each of those PSC-## is a folder that contains files abundance.h5  abundance.tsv  run_info.json

**Comment by kubu4** [comment]
Don't know, but you want to delete LARGE files (like SAMs, BAMs, FastQs).

**Comment by grace-ac** [comment]
the space was the issue! all working now and i'll keep deleting stuff that's not needed
