### ISSUE TITLE
Extract DNA from metagenomic samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#197]
that correspond to what Emma processed for proteomics

**Comment by grace-ac** [comment]
Emma brought samples over and I put them in a cardboard box on the top shelf of the -20 in RM 209.

**Comment by kubu4** [comment]
@emmats 

OK, tried isolating DNA from two samples using Qiagen Stool Kit - no dice.

@sr320 mentioned you might have actual filters left/available. If this is the case, this would be a better source for DNA extraction. I've extracted DNA from filter paper before and know that definitely works.

Any info/thoughts you might have would be helpful. Thanks!

**Comment by emmats** [comment]
I believe there are many other filters associated with this project that haven't been touched yet.

I still have the filters left that I washed cells off of, but I have already rinsed them off and I accidentally left them on the lab bench overnight.

**Comment by sr320** [comment]
Will we need to pool filters for a library of can 1 filter be enough for a library?

**Comment by sr320** [comment]
We only have 5 filters at 0.22 micron left...

3 from tank 10 (5/15,5/22,5/26) . ph 7.1
2 from tank 7 (5/15,5/17) . ph 8.2


---
this is what metaproteomics was done on..
```
5/15/17
5/19/17
5/22/17
5/26/17
Conical #4 and #8 at pH 8.2 
Conical #6 and #9 at pH 7.1
```

@emmats we have 24 libraries - what else should we do? are the 0.7 um filters worthwhile?

**Comment by emmats** [comment]
I don't think there will be a ton of bacterial biomass on the 0.7. What is there will probably be attached to larger biological material and most of the sequencing reads would be of that larger material. I would just sequence the 0.2 um filters that we have.
