### ISSUE TITLE
Github, Gannet, and Raven access for PSRF post-doc

### ISSUE THREAD

**Issue by zbengt** [RobertsLab/resources#1971]
Mac and I are working with post-doc at PSRF. Could we get them added to the github org? Once that's done I can tag them in this issue and we can get the ball rolling on their Raven and Gannett access. Here's their info:
Evelyn Abbott
evelyn@restorationfund.org

Thank you!

**Comment by kubu4** [comment]
Currently awaiting responses from Evelen to:

- GitHub invite
- UW NetID provisioning

I'll wait until either of those two are finished, I'll use one of those user IDs as user ID for Raven and Gannet.

**Comment by kubu4** [comment]
Alrighty, I have @evelynabbott UW NetID. I'm in the process of setting up UW NetID provisioning to be able to use the UW VPN.

Will get Gannet and Raven access set up today, as well.

**Comment by kubu4** [comment]
Husky OnNet provisioning has been requested.

Account on Raven has been created. Credentials have been sent to @everlynabbott via Slack.

**Comment by kubu4** [comment]
Gannet account has been set up.

That should take care of everything. @evelynabbott, if anything comes up, please create an issue in this repo and we'll get you taken care of!

**Comment by zbengt** [comment]
Thank you Sam!
