### ISSUE TITLE
Planning remaining tasks for larval DNA methylation lab work

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#198]
Isolated DNA from 8 frozen larval samples yesterday; I did 3 reps from each larval sample to try to produce sufficient DNA for the sequencing facility (will combine reps before sending to facility - not sure at which step, though...)  My results are in the table below. My understanding of next steps in this workflow: 
  1. Run DNA on gel to determine integrity     
  2. Shear DNA into ~100–200 bp lengths & verify (at NOAA with Mac)  
  3. Run samples through MethylMiner kit   
  4. Quantify methyl-enriched DNA concentration   
  5. Prepare samples for shipping  

I'm working under the Hall Grant funding deadline clock (~end of month-ish), and since I'll be fully occupied by NSA next week, then my Olys start spawning at Manchester (!), so I need to get as much done this week as possible.  @kubu4 would you have capacity on Wed (tomorrow) AM to do some hand holding with me while I run the my first ever gel?  If integrity is sufficient, hoping to shear on Thursday AM. @sr320 could you put me in contact with Mac so I can arrange the NOAA visit?  

How long will it take the sequencing facility to bill us?  Worried about this Hall deadline ... 

DNA VIAL # | DNA Concentration (ng/uL) | Total ng DNA after assay | 1% of DNA (ng) per rep | 1% of DNA (ng) for each sample
-- | -- | -- | -- | --
1-A | 17.600 | 2,200 | 22 | 70.50
1-B | 18.800 | 2,350 | 24 |  
1-C | 20.000 | 2,500 | 25 |  
2-A | 25.500 | 3,188 | 32 | 79.13
2-B | 17.000 | 2,125 | 21 |  
2-C | 20.800 | 2,600 | 26 |  
3-A | 29.000 | 3,625 | 36 | 103.13
3-B | 28.000 | 3,500 | 35 |  
3-C | 25.500 | 3,188 | 32 |  
4-A | 29.500 | 3,688 | 37 | 111.25
4-B | 29.500 | 3,688 | 37 |  
4-C | 30.000 | 3,750 | 38 |  
5-A | 23.500 | 2,938 | 29 | 92.50
5-B | 23.500 | 2,938 | 29 |  
5-C | 27.000 | 3,375 | 34 |  
6-A | 26.500 | 3,313 | 33 | 99.31
6-B | 28.200 | 3,525 | 35 |  
6-C | 24.750 | 3,094 | 31 |  
7-A | 25.500 | 3,188 | 32 | 89.06
7-B | 22.000 | 2,750 | 28 |  
7-C | 23.750 | 2,969 | 30 |  
8-A | 29.500 | 3,688 | 37 | 104.94
8-B | 28.050 | 3,506 | 35 |  
8-C | 26.400 | 3,300 | 33 |

**Comment by kubu4** [comment]
I'll be around all day tomorrow to help.

Shearing will be done in Seeb Lab. We will need to coordinate with their lab manager (Carita) for using their machine.

Sequencing won't be complete for 8 - 12 weeks after sample submission. Billing is submitted to university upon completion of project.

**Comment by laurahspencer** [comment]
Thanks, Sam.  
I presume the Seeb Lab is at NOAA?  I found Carita's email online - I'll contact her to see if I can come use the shearer on Thursday.  I'll also contact Mac to see if she'd be willing to help me, as she did before, unless @kubu4 you're interested in another field trip to NOAA?  

Regarding timeline - yikes. @sr320 can you advise on how to negotiate an extension on the Hall funds with CoEnv?  Perhaps we can chat tomorrow AM during our meeting...

**Comment by sr320** [comment]
Not NOAA not Mac- let’s discuss at lab meeting

**Comment by laurahspencer** [comment]
Ok, I'll hang tight.

**Comment by laurahspencer** [comment]
Results from Bioanalyzer are in my [lab notebook entry from today](https://github.com/laurahspencer/LabNotebook/blob/master/_posts/2018-03-14-Larval-DNA-Integrity.md)

Let me know what ya'll think.

**Comment by kubu4** [comment]
Results look good to me. 

Most of the DNA should be (and is) pushed up against the far right side of the electropherograms - that's why you can't see the 17,000bp marker in most of the samples. This is the major limitation to using the BioAnalyzer for size assessment of gDNA in molluscs - it doesn't go high enough. However, we don't need to know the actual size; we just need to be confident that the DNA isn't degarded.

So, you're good to go for shearing!

**Comment by laurahspencer** [comment]
Great news!  
@sr320 - do we need to chat before I move forward with the shearing / methyl enrichment?  There was some debate yesterday as to the type of sequencing I can do... 

If I get the go-ahead, I'm around all day, Sam, if you are available to help me figure out the shearing settings.
