### ISSUE TITLE
Extract DNA from lean trout liver samples in freezer

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1981]
|  Sample # |  Pit tag # |  cross |  
|-----|---|---|
|  FA 046 |  6C00013401 |  LxL |  
|  FA 047 |  6C00012139 |  LxL |  
|  FA 048 |  6C00012156 |  LxL |  
|  FA 049 |  6C00012207 |  LxL |  
|  FA 050 |  6C00013455 |  LxL |  
|  FA 051 |  6C00013428 |  LxL |  
|  FA 055 |  6C00012135 |  LxL |  
|  FA 056 |  6C00012203 |  LxL |

looking to get at least 5ug.

**Comment by kubu4** [comment]
Yields are good for all samples.

| sample_ID | Original sample conc. (ng/uL) | yield(ng) |
|-----------|-------------------------------|-----------|
| FA046     | 224                           | 8960      |
| FA047     | 984                           | 39360     |
| FA048     | 1180                          | 47200     |
| FA049     | 584                           | 23360     |
| FA050     | 185                           | 7400      |
| FA051     | 990                           | 39600     |
| FA055     | 770                           | 30800     |
| FA056     | 792                           | 31680     |

Ran DNA on gel and it looks excellent, as well.
