### ISSUE TITLE
HISAT2 & samtools | header formatting & genome naming convention errors

### ISSUE THREAD

**Issue by sarahtanja** [RobertsLab/resources#1988]
I'm following the code in @kubu4 [notebook post on HISAT2 Alignment](https://robertslab.github.io/sams-notebook/posts/2024/2024-10-08-RNA-seq-Alignment---A.pulchra-RNA-seq-Alignments-Using-HISAT2-and-StringTie-for-Azenta-Project-30-1047560508/index.html)

The way I've modified it to my project can be found [here](https://github.com/sarahtanja/coral-embryo-leachate/blob/main/code/04_align_genome.qmd)

When aligning using HISAT2 and samtools I get the following error for each sample:

```
Failed to read header for "-"
samtools sort: failed to read header from "-"
samtools index: "-" is in a format that cannot be usefully indexed
WARNING: no reference transcripts were found for the genomic sequences where reads were mapped!
Please make sure the -G annotation file uses the same naming convention for the genome sequences.
```

I'm using the gff_fixed format generated by @AHuffmyer for the Montipora_capitata_HIv3 and when I open it and compare it to the fasta file the naming convention seems to match... Anybody else run into similar samtools errors?

**Comment by sr320** [comment]
What is the exact code chunk that generated that error?

**Comment by kubu4** [comment]
Without looking to deeply into this, my guess is that the filename parsing is incorrect and is passing a literal `-` as a "file".

If you don't mind, add an example of your FastQ filenames in your code. That will allow us to more easily see what expected filenames look like and compare that to the filename parsing which is taking place.

**Comment by sr320** [comment]
is this line correct? maybe extra period?

`echo 'export genome_index_name="Montipora_capitata_HIv3."'`


also I am a fan of simple chunk by chunk when first starting out as opposed to the expansive variable set ups
facilitates easier troubleshooting.

https://sr320.github.io/tumbling-oysters/#category=hisat

**Comment by kubu4** [comment]
Also, where are you running this. I looked on Raven in 

`/home/shared/8TB_HDD_02/sarahtanja/coral-embryo-leachate/output/04_align`

but there's nothing there.

Would be great if we could poke around in directories/files.

And, @sr320 is correct. Even though I have that massive loop, it was built step-by-step using a set of FastQs for testing. Trying to dive in to that massive code chunk with your own files can make it very difficult to troubleshoot.

**Comment by kubu4** [comment]
I think it's related to the FastQ filename parsing. You have the following in your code:

https://github.com/sarahtanja/coral-embryo-leachate/blob/dd55a3c89cad381f0e2b596fb10c30a713dd637c/code/04_align_genome.qmd#L320C1-L333C68

```bash
############## BEGIN HISAT2 ALIGNMENTS ##############
for sample in "${!sample_info_map[@]}"
do




  # Create and switch to dedicated sample directory
  mkdir --parents "${sample}" && cd "$_"


  # Create HISAT2 list of fastq R1 files
  # and generated MD5 checksums file.
  for fastq in "${fastq_array_R1[@]}"
  do
    # Parse sample name from FastQ filename
    fastq_sample=$(echo "${fastq##*/}" | awk -F"[_-]" '{print $3}')
```

That last line is intended to extract the sample name from the FastQ filename. However, this is what the output of that command actually is:

![image](https://github.com/user-attachments/assets/179e98a7-a5c0-4295-9a97-207238dab88b)

Also confirming that this is the likely culprit are the following step(s):

https://github.com/sarahtanja/coral-embryo-leachate/blob/dd55a3c89cad381f0e2b596fb10c30a713dd637c/code/04_align_genome.qmd#L335C1-L345C7

```bash
    # Process matching FastQ file, based on sample name
    if [ "${fastq_sample}" == "${sample}" ]; then

      # Generate checksum/list of input files used
      md5sum "${fastq}" >> input_fastqs_checksums.md5

      # Create comma-separated lists of FastQs for HISAT2
      printf -v joined_R1 '%s,' "${fastq}"
      fastq_list_R1=$(echo "${joined_R1%,}")
    fi
  done
```

_If_ the `${fastq_sample}` was correct, you'd expect to find the file `input_fastqs_checksums.md5` in each of your output directories, but you do not:

![image](https://github.com/user-attachments/assets/b0b5b79b-d05c-492b-bb39-018d634c37b3)


So, fixing the sample name parsing, you'd want to use `fastq_sample=$(echo "${fastq##*/}" | awk -F"[_]" '{print $1}')`

Additionally, those `if/then` statements are only really necessary if you're using a subset of your FastQ files, so you could get rid of them if you'd like.

Also, don't forget to fix the FastQ filename parsing for the R2 reads, too.

**Comment by sarahtanja** [comment]
> If you don't mind, add an example of your FastQ filenames in your code. That will allow us to more easily see what expected filenames look like and compare that to the filename parsing which is taking place.

I included this in the markdown annotation of my code... for reference here my sample names look like `123C4` and fastq files are `123C4_R1_001.fastq.gz` (& R2 is the same pattern).
The sample names indicate:
- Pooled sample crosses
     - a variable length string of numbers indicating the pooled sample crosses
     - ex. 123 is pooled samples from crosses 1, 2 & 3
- PVC leachate level
     - ex. C = control, L = low, M = mid, H = high
- Developmental phase
     - ex. 4 = 4hpf (initial cleavage), 9 = 9hpf (prawn chip), 14 = 14hpf (early gastrula)

> also I am a fan of simple chunk by chunk when first starting out as opposed to the expansive variable set ups facilitates easier troubleshooting.

@sr320 Thanks for the other Hisat code examples... I'm working now to break Sam's loop into chunks with more annotation for my benefit and for troubleshooting 

> So, fixing the sample name parsing, you'd want to use fastq_sample=$(echo "${fastq##*/}" | awk -F"[_]" '{print $1}')

@kubu4 I replaced the string manipulation for R1 and R2 using your suggested pattern, and while this did result in getting `input_fastqs_checksums.md5` for each sample, it still gave the same error code as before and the following files were written with no content (0B):
- {sample}.gtf
- {sample}.cov_refs.gtf
- {sample}.sorted.bam
- {sample}-hisat2_output.flagstat

> Additionally, those if/then statements are only really necessary if you're using a subset of your FastQ files, so you could get rid of them if you'd like.

I also removed the if/then statements

**Comment by kubu4** [comment]
Can you please push any changes to GitHub so we can view updated code?

Looking at the `input_fastqs_checksums.md5`, it appears the code is looping through all of the FastQ files, instead of just the paired FastQs for a given sample:

![image](https://github.com/user-attachments/assets/f0a17475-4ed8-4176-a501-9cafe0e98be8)

The image above should have just two entires, 

```
b7f575269ec4a6154dca8dd9f10afb4f  /home/shared/8TB_HDD_02/stanja/sarahtanja/coral-embryo-leachate/output/03_qaqc/trim_reads_fastp/101112C14_R1_001.fastp-trim.fq.gz
0438778c85cf2728fc6593f1052aeedd  /home/shared/8TB_HDD_02/stanja/sarahtanja/coral-embryo-leachate/output/03_qaqc/trim_reads_fastp/101112C14_R2_001.fastp-trim.fq.gz
```

**Comment by sarahtanja** [comment]
I see what you mean about the `input_fastqs_checksums.md5`...
I just pushed the most recent changes

**Comment by kubu4** [comment]
Also, it looks like your array is parsing the "value" portion of the "key=value" pair, so that's a place to look at.

![image](https://github.com/user-attachments/assets/57ef4eb3-7814-4466-ab82-8831157d3d7c)

---

> I see what you mean about the input_fastqs_checksums.md5...

It looks like this is the only sample with that issue. The other samples look correct (i.e. just have the two appropriate corresponding FastQs).

**Comment by kubu4** [comment]
Here's HISAT2 stderr for one of your samples:

```
$ cat 89C9_hisat2.stats

Warning: Output file 'chip,control,9,0' was specified without -S.  This will not work in future HISAT 2 versions.  Please use -S instead.
Could not locate a HISAT2 index corresponding to basename "Montipora_capitata_HIv3."
Error: Encountered internal HISAT2 exception (#1)
Command: /home/shared/hisat2-2.2.1/hisat2-align-s --wrapper basic-0 -x Montipora_capitata_HIv3. --threads 40 --rg-id 89C9 --rg SM:07-Jul-2024,prawn --read-lengths 150,141,142,138,143,145,149,146,140,144,132,116,130,139,133,148,137,147,131,125,121,136,135,129,128,124,120,122,118,127,126,134,123,112,114,119,115,110,108,117,113,111,106,107,103,100,109,105,102,93,97,92,104,98,90,89,88,95,86,96,99,94,87,83,70,101,75,47,91,85,74,68,35,31,82,79,77,73,61,59,55,34,32,84,81,80,78,76,72,69,67,63,62,57,53,52,48,44,38,37,33 -1 /tmp/34721.inpipe1 -2 /tmp/34721.inpipe2 chip,control,9,0 
(ERR): hisat2-align exited with value 1

gzip: 
gzip: stdout: Broken pipe
stdout: Broken pipe
```

Looks like it's using the "value" part of the array as input, so that's definitely the source of the problem.

Also, as @sr320 mentioned, looks like you need to check the name of the index you're specifying.

**Comment by sarahtanja** [comment]
Here are the unpacked index files I'm working with:
```
Montipora_capitata_HIv3.1.ht2
Montipora_capitata_HIv3.2.ht2
Montipora_capitata_HIv3.3.ht2
Montipora_capitata_HIv3.4.ht2
Montipora_capitata_HIv3.5.ht2
Montipora_capitata_HIv3.6.ht2
Montipora_capitata_HIv3.7.ht2
Montipora_capitata_HIv3.8.ht2
```

They're located in `data/mcapgenome/hisat-index`

**Comment by kubu4** [comment]
This is from @sr320, previously:

> is this line correct? maybe extra period?
> 
> `echo 'export genome_index_name="Montipora_capitata_HIv3."'`
>

**Comment by sarahtanja** [comment]
I previously had it without the `.` like:
`echo 'export genome_index_name="Montipora_capitata_HIv3"'`
and I got the same error but am trying it again now

**Comment by kubu4** [comment]
>  could that be messing up the valu

That's likely! Spaces are almost always a problem (unless you explicitly account for them).
