### ISSUE TITLE
Seastar AB metadata with Sample ID, year study, stage (A/J), Alignment rate from HiSat

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1990]
and if exposed or control

url to tab delim file in repo....

**Comment by sr320** [comment]
@grace-ac ping

**Comment by grace-ac** [comment]
thanks for the ping! 

https://github.com/grace-ac/paper-pycno-sswd-2021-2022/blob/main/data/Sample_Metadata_with_alignment.tsv
