### ISSUE TITLE
Develop Lab poster with pictures

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#1992]
Telling broad story of field work, implications, study organism, aquaculture etc - for very general audience, outreach

PosterL
https://docs.google.com/presentation/d/1JMj2K1Q8sdat8fmdBmshpUv_gfPxYbQi2G7VHfTAxOc/edit?usp=sharing

**Comment by AHuffmyer** [comment]
I added a field map and organized a draft of the poster. @sr320 do you already have a QR code you like to use for the lab? I could create a Linktree as well if we want a QR code that could take folks to a page with links to all our lab sites.

**Comment by sr320** [comment]
I have nothing particular in terms of codes

**Comment by AHuffmyer** [comment]
Submitted to CC for printing. Requested printing by 11/7/2024. I'll hang up in the hallway on Friday!
