### ISSUE TITLE
raven R server slow to start, anyone else having trouble with raven freezing up?

### ISSUE THREAD

**Issue by sarahtanja** [RobertsLab/resources#1993]
Running into hangups using Big-IP Edge Client to work from home and access raven RStudio remote server... 
![big-ip](https://github.com/user-attachments/assets/562da53b-adaf-4488-b11c-c3cd3b9ddd47)

On startup I often get a warning that R is taking longer than usual to load
![r-long-to-start](https://github.com/user-attachments/assets/b1e675f4-68ff-4602-bf6e-03f835f292e8)

Then I terminate and restart the R session
![r-termination](https://github.com/user-attachments/assets/6910bc4d-8a5c-4dd9-9b7c-9ea7acf0a146)

Only for R to freeze up and stop responding to both terminal and console commands.

Could this be my internet stability, or some other issue? Is anyone else experiences freezes on raven?

**Comment by kubu4** [comment]
Checking `htop` on Raven (via Terminal), I can see that you're running `md5sum`. 

With R taking a long to load and/or crashing like that, I suspect that your `md5sum` command is printing a _lot_ of lines to the screen. Usually if R is taking a long time to load, it's because the Rmd document has a _lot_ lines being output to the screen, which uses a ton of memory, causing it to crash.

So, if you're unable to get RStudio to run without it crashing, you'll likely need to login to Raven via `ssh` and kill the process(es) that are running your RStudio session.

However, with that said, `htop` just switched to running your HISAT2 command! So, that's going...

**Comment by sarahtanja** [comment]
intermediate update:

We used `htop` to look at the rsession process ID (PID) that was using up 99% of the CPU, and attempted to kill it using `kill -P <PID>` and `kill 9 <PID>`
only Sam/Steven were successful in killing the process (using sudo and admin permissions)

When re-opening the rsession, you can't attempt to open the code that was causing the crash, or else the process will start again and lock up the rsession.

We renamed the code file that was causing the crash from an ssh terminal using `mv <filename>_backup.qmd` and opened it in terminal using `cat` to view the file and `nano` to edit it.

We discussed the possibility of rebooting raven... and it seems like that's happening now,  because when I try to ssh I get the following: 
![image](https://github.com/user-attachments/assets/4b0e2338-f672-49c6-b5de-f67b52927ac2)

**Comment by kubu4** [comment]
@sarahtanja - Raven has been "fixed" (mostly) and can be reached again.

So, give it another shot and we'll see what happens!

**Comment by sarahtanja** [comment]
I went in and edited my `04_genome_alignment_backup.qmd` file through ssh nano text editor ( I removed the entire code block that was running the loop ) and I also removed some yaml front matter related to render/knit. 

> When re-opening the rsession, you can't attempt to open the code that was causing the crash, or else the process will start again and lock up the rsession.

I tried to open the code file in raven this morning and sadly the same lock-up rsession issue we experienced before is persisting
![image](https://github.com/user-attachments/assets/b0396935-8e5a-4b46-9b98-2986387a775f)

**Comment by sarahtanja** [comment]
In conclusion... my yaml file looked like this
```
---
title: "Step 4: Align sequences to annotated *M. capitata* genome"
subtitle: "Using `HISAT2`"
author: "Sarah Tanja"
date: 10/21/2024
format:
  gfm: default  # or html if you want to render in HTML
toc: true
toc-depth: 3
link-external-icon: true
link-external-newwindow: true
reference-location: margin
citation-location: margin
**execute:
  cache: true**
  eval: true
  echo: true
  warning: false
  message: false
---
```
And the `execute:  cache: true` line created a folder of cached output from all the code chunks that somehow locked up all the CPU upon re-opening the code file. 

I fixed this by deleting the yaml execute parameters and the cache directory using ssh and command line
