### ISSUE TITLE
10.28.24 DEI Lab Meeting Deliverables

### ISSUE THREAD

**Issue by ChrisMantegna** [RobertsLab/resources#1995]
Monday’s DEI meeting will be focused on how we can co-create and sustain the lab culture we need in order to support our continued success. So what do we want to create?

### We’re going to answer the following questions
* Where are we starting from?
* How do we define success in the lab?
* How are our goals for ourselves and for the lab space aligned?
* What do we want to create?
* What strengths or skills do we bring to help support that vision? 
* Where can we use support to shore up our weaknesses in our science, task/ project management or motivation?

### To start brainstorming together, please add the following resources to this issue for discussion
* 2 lab websites that embody what we want to see in our lab
* 1-2 ways to hold ourselves and each other accountable

**Comment by sarahtanja** [comment]
CLEAR Lab How to Run a Lab Meeting:
https://civiclaboratory.nl/2017/03/31/how-to-run-a-feminist-science-lab-meeting

Babraham Bioinformatics Trainings:
https://www.bioinformatics.babraham.ac.uk/training.html 

- co-working sessions (body doubling)
- teaching each other (I learn things better myself when I have to teach/explain them to someone else)

**Comment by AHuffmyer** [comment]
Guide to decolozing syllabi: https://resources.lmu.edu/media/lmuinclusiveexcellence/documents/Decolonizing%20the%20Syllabus%20(J%20Williams).pdf

Inclusive lab agreements: https://www.theequitylab.org/blog/why-start-with-agreements

Inclusive Lab Leaders program (perhaps we could participate!): https://21centurysci.beckman.illinois.edu/inclusive-lab-leaders/

- Asking for help when needed and providing help/feedback when requested 
- In person working sessions and/or social time

**Comment by ChrisMantegna** [comment]
Two labs
Critical Ecology Lab: https://www.criticalecologylab.org/
Wels Group: https://www.cuwelsgroup.com/

Accountability
1. I’d like to hold us all accountable to going for it by having a physical lab Victory Jar & Epic Fails Jar. Celebrating our wins and the places where we fell short normalizes the ebb and flow of the work and what it means to get this work done. It also chips away at the isolation of ‘failure’ and the illusion of ‘singular successes’.

2. I’d like to hold myself accountable to asking for help and following up with the ask, not just dropping an ominous “I’m going to need help”, but an explicit ask for support.

**Comment by grace-ac** [comment]
I also am not sure where to look for lab website examples, but I'll do some searching!

In the mean time some thoughts on accountability: 
- I really like accountabilibuddy systems! Yaamini and I would do that in our office where we'd check in with each other at the start of a work block and tell each other what we intended to do. Then we'd work for however long we decided together, then check in at the end about what we accomplished. This falls into the co-working time! 

 The above also fits into creating a closer lab culture, which I think would help with productivity too! It's harder for me to get things done when I feel trapped in my own head and my own screens. Getting face time with people is a big mood booster for me and then helps me feel better about returning to screen time. 

- I also like the pubathon board idea that was talked about before! Some sort of physical visual representation of what we'd like to accomplish

**Comment by meganewing** [comment]
Two labs:
- [Bernardi Lab, UCSC](https://bernardi.eeb.ucsc.edu/pictures/vips/). I like there pictures sections that show the lab's personality (which is furthered by the contact us page). 
- [Mills Research Team](https://suzannemills.org/). Have a cool selection of graphics from their research that I feel quickly gives you an idea about their research besides/in addition to the typical "our research" page. 

Accountability:
- I like the co working idea. I think that's part of the point of science hour, but could be helpful to have an infrastructure for this that is more flexible (maybe even just saying on slack 'hey is anybody interested in coworking on tuesday') 
- Physical goal board (I have one at my house) since electronic methods for goal setting arent as prevalent a reminder (once you submit the google form, do you really look at it again?)

**Comment by zbengt** [comment]
This website provides good models for participatory science: https://participatorysciences.org/about/
Love this as a framework for a lab, including integration on lab website: https://www.marineevoeco.com/

Accountability:

1. Love co-working in a way shape or form
2. Would be nice to have less formal science discussions combined with social time to keep up with literature

**Comment by shedurkin** [comment]
Accountability:
- prioritize in-person engagement, when possible (lab meetings, science hour, pubathon)
- Seek regular feedback, e.g. by scheduling a weekly meeting with Steven

Lab Website:
Also have never really interacted with other lab sites, but two things I think could be useful are:
- more images
- restructure to make website and handbook more concise, clearly structured
