### ISSUE TITLE
Trouble installing R packages on Raven

### ISSUE THREAD

**Issue by shedurkin** [RobertsLab/resources#2000]
I've been trying to install some R packages on Raven that are available via Cran (e.g., the `energy` package), but they keep failing with the message 

> "Warning in install.packages : installation of package ‘energy’ had non-zero exit status"

along with some warnings about installation of dependencies also failing. Chatgpt suggests it may be a problem with RTools, but I'm not sure if/where RTools is installed on Raven, so I'm not sure how to troubleshoot. Any tips?

**Comment by kubu4** [comment]
After a video chat with @shedurkin , it was determined that the GSL version installed was too low (packages she was trying to install required GSL version >=2.5, but Raven has v2.4 installed).

GSL is a system level set of libraries (i.e. _not_ an R package). After various attempts at installing, I've come to the conclusion that Raven's operating system (OS) version (18.04LTS) is likely too old. Meaning, updated versions of GSL (and, primarily, _its_ dependencies) haven't been produced for 18.04LTS. 

FYI, Ubuntu is currently up to version 24.10, I think, so Raven is many years (and version) behind at this point.

So, how to get around this?

1. Run on your own computer, if feasible.
2. Begin using [Klone](https://robertslab.github.io/resources/klone_quick-start/). If you opt for this route, let me know and please provide a list of R packages you'll be using. I'll get them installed for you.
3. Upgrade Raven's OS.

**Comment by shedurkin** [comment]
RIP -- thank you for looking into this thugh! I should just be able to run this locally
