### ISSUE TITLE
find pisaster ochraceus transcriptome 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#2001]

**Comment by grace-ac** [comment]
this paper: https://pmc.ncbi.nlm.nih.gov/articles/PMC5562136/#sec5 

mentions: [Table S1](https://pmc.ncbi.nlm.nih.gov/articles/PMC5562136/#supp-1) provides information for each library used in transcriptome assemblies; all sequence data are available from NCBI (BioProject [PRJNA357374](http://www.ncbi.nlm.nih.gov/bioproject/?term=PRJNA357374)). Of the two de novo assemblies, the reduced-input transcriptome had greater length and quality of contigs (N50 of 1,799 bp, median contig length 513, total assembled bases 179,034,265) and is the focus of subsequent analyses.

**Comment by grace-ac** [comment]
this paper: https://pmc.ncbi.nlm.nih.gov/articles/PMC10320347/#s6 

mentions this: The data from this study are available from the Dryad Digital Repository [[80](https://pmc.ncbi.nlm.nih.gov/articles/PMC10320347/#RSPB20230347C80)]. Sequence data reported in this article have been deposited in the National Center for Biotechnology Information (NCBI) (BioProject no. PRJNA934423).
Additional information is provided in the electronic supplementary material [[81](https://pmc.ncbi.nlm.nih.gov/articles/PMC10320347/#RSPB20230347C81)].

**Comment by sr320** [comment]
is it just me or is nobody publishing the transcriptomes?? @kubu4 could you have a look and see if you can find one ?

**Comment by grace-ac** [comment]
ok i thought that was right!! i thought maybe i just was missing something because i was looking at the bio project pages so quick. but i have really had a hard time finding anything promising

**Comment by grace-ac** [comment]
i'll ask my sea star people slack group if anyone knows anything too

**Comment by kubu4** [comment]
Interestingly, they assembled their transcritpome from only 2 of their 24 individuals. 

I'll keep poking around, though.

**Comment by kubu4** [comment]
I've created an issue on the GitHub repo associated with the paper asking about the transcriptome availability. Guess we'll see if they respond.

However, at this point it might be faster to just assemble it ourselves...

**Comment by sr320** [comment]
@kubu4 note we are not tied to this paper - looking for anything out there available for this species

**Comment by kubu4** [comment]
I can't find anything.

**Comment by grace-ac** [comment]
dang. thanks for looking sam!
