### ISSUE TITLE
unmapped reads for seastar RNAseq

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#2007]

**Comment by sr320** [comment]
mainly appears to be common sea star? echinoderm

**Comment by sr320** [comment]
https://robertslab.github.io/sams-notebook/posts/2024/2024-11-05-Sequencing-Read-Taxonomic-Classification---Unmapped-P.helanthoides-RNA-seq-Using-DIAMOND-BLASTx-and-MEGAN6-on-Mox/
