### ISSUE TITLE
Podcast subscription trouble

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#201]
I have the Podcast App from apple, and also podcasts in iTunes.

I tried using the url listed on the website:
https://bittercrab.wordpress.com/category/podcast/feed

I also tried searching for the podcast in the app and in iTunes and couldn't find it.

When I selected the feed, I got an alert saying that no RSS reader is installed.... Is this necessary for subscribing to a Podcast?? 

I feel like this should be easier. I also could be doing it wrong. I haven't subscribed to a new podcast in a long time.

**Comment by kubu4** [comment]
Hmmm, I don't have any issues subscribing. I tested with "gPodder" on Ubuntu. It pulled both episodes using the feed URL posted above.

**Comment by sr320** [comment]
Actually the Apple app is the oddest. It oddly does seem to require the
Apple News app as a RSS translator...

**Comment by grace-ac** [comment]
One of my friends started a Podcast and used this: https://anchor.fm

might be an easy way to get the podcasts into a more accessible form? I'll look into it more
