### ISSUE TITLE
4TB_JPG_ext |  clean out, data backup, project migration

### ISSUE THREAD

**Issue by sarahtanja** [RobertsLab/resources#2011]
Follow up from issue #1998 

@kubu4 I'm going to start cloning my git repo to 4TB_JPG_ext, but will wait to migrate big files from gannet until I either see that you've cleared space or heard from you here.

**Comment by kubu4** [comment]
Sounds good. You can migrate all you want, no need to wait for me. Just be aware that the drive is 81% full ATM. 

Aaaand, since my Internet is down, I can't do much to clear it out until that's resolved.

**Comment by kubu4** [comment]
Hopefully I don't screw anything up. I started re-tarballing the `montipora` directory this morning, not realizing a transfer was still running.

**Comment by sarahtanja** [comment]
I ran `rsync` to grab all the large files from the gannet backup yesterday evening and it looks like I filled up the 4TB_JPG_ext .... 
![image](https://github.com/user-attachments/assets/b5ab22e6-3ef4-4011-b836-ab263d8eb565)
Currently can't open my project directory, I think until the backup & clean-out finish

**Comment by kubu4** [comment]
Alrighty, I've removed one subdirectory and now 50% of the drive space is available.

So, you should probably be fine moving big stuff over.

I'm currently backing up my other subdirectory. I'll report once it's gone, too.

**Comment by sarahtanja** [comment]
Thank you!!
