### ISSUE TITLE
Get seastar GO slim term counts

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#2012]
Get BP GOslim list with gene counts 
Ala https://github.com/RobertsLab/resources/issues/1989#issuecomment-2450384416

on 
https://gannet.fish.washington.edu/seashell/bu-github/project-pycno-multispecies-2023/output/06-Go-3-species/der_go.tsv

And

https://gannet.fish.washington.edu/seashell/bu-github/project-pycno-multispecies-2023/output/06-Go-3-species/pyc_go.tsv

**Comment by sr320** [comment]
sorry - X1 columns..

**Comment by kubu4** [comment]
_Dermasterias imbricata_:

- https://github.com/RobertsLab/code/blob/master/r_projects/sam/20241106-dimb-GO-to-GOslim/output/01-GO-to-GOslim/counts.GOID-per-GOslim_term.tab

_Pycnopodia helianthoides_:

https://github.com/RobertsLab/code/blob/master/r_projects/sam/20241106-phel-GO-to-GOslim/output/01-GO-to-GOslim/counts.GOID-per-GOslim_term.tab
