### ISSUE TITLE
Prep letter of intent for NOAA Sea Grant Aquaculture Business RFP

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#2014]
https://grants.gov/search-results-detail/356751

LOI due Dec 4th

**Comment by AHuffmyer** [comment]
LOI from 2024 that can be the base of new application: https://docs.google.com/document/d/1DakWMT7js7UPq5TDUD9ka_Fdzv4_cQffJyyaviYEB6Q/edit?tab=t.0

**Comment by AHuffmyer** [comment]
[NOAA-OAR-SG-2025-28975.pdf](https://github.com/user-attachments/files/17653574/NOAA-OAR-SG-2025-28975.pdf)

**Comment by AHuffmyer** [comment]
An additional specific stressor could be biomarkers of pollution/toxins. Could include glutathionine reductatase, glutathione peroxidase,  MDA, and SOD. 

My thoughts on time frame of work: 

- This should include "baseline" sampling across seasons to quantify deviations from baseline as indications of stress for each assay. 
- Increase frequency of sampling during stress events that are expected (i.e., heat stress based on summer forecasts) and other irregular/unexpected stress events that we are alerted to by the growers. 

One comment from previous NOAA RFP reviewers was "what happens if there are no natural mortality events?" Characterizing baselines of biomarks and monitoring stress from a variety of angles would address this same type of reviewer comment.

**Comment by sr320** [comment]
the model would be picking several farms (network) with regular sampling (diverse environments across and within farms) - archiving and going back post environmental data assessment.  we likely have similar proposals, will look

**Comment by AHuffmyer** [comment]
Logistics: 
- Start Sept 1 2025, end Aug 31 2028 (3 year project)
- Can request between $100,000 and $1,000,000

Study aims: 
1. Supporting businesses by establishing baseline understanding of oyster physiology and stress response in diverse farm environments in the Puget Sound over a 2-3 year period. 
2. Supporting businesses by detecting and diagnosing oyster mortality as deviations in responses from baseline to provide growers with the ability to make proactive decisions to reduce losses, especially during summer mortality events.

Potential farm network:
- Baywater
- Point Whitney
- Goose Point
- Seattle Shellfish (waiting on reply from them)
- Westcott 

Regular sampling: 
- assays listed above in n=15 oysters per environment per farm taken every 4-6 weeks  

Farm environments: 
- each type of bag/rack at the farm 
- low/medium/high locations in tidal height
- if farm has multiple locations then samples from each location

Environmental measurements: 
- salinity loggers (if possible)
- temperature loggers 
- oxygen loggers (Baywater is already doing this)
- either our own loggers or collaborating to view data from farm data collection
- Constant deployment and regular read outs 

Funding needs: 
- Travel to farm sites for 2 people at each sampling 
- Lab/assay costs
- Costs of loggers/environmental data 
- Salaries 

Nonfederal match (50%): 
- SR salary 

SeaGrant collaboration: 
- Ashleigh Epps, WSG to assist with grower outreach, education, and communication of findings 

**Letter of Intent Requirements**
Letters of Intent (LOI) are required and will allow the National Sea Grant Office to gauge interest and topics that may be submitted. Please note that LOIs will not be used to decide whether or not a full proposal should be encouraged. All applicants submitting a LOI will be eligible to submit a full proposal.

The LOI (please limit to two pages) must include the following:
• Tentative Project Title
• Lead submitting entity and project point of contact name and email address
• Potential Co-PIs and other existing or potential project partners
• Tentative Objectives
• Estimate of federal funds requested by year

To be eligible to submit a full proposal, a letter of intent must be received via email by the Program Managers (oar.hq.sg.aquaculture@noaa.gov) by 5:00 pm (local time of lead submitting entity) on December 4, 2024. Please only use this email address to submit an LOI.

@sr320 what are your thoughts on this outline?

**Comment by sr320** [comment]
lets break out objective such that **one** is focused on value of environmental data..
and **second** one is focused on oyster physiology work that uses environmental data to produce valuable info

then lets come up with a few sentences on objective two that delineates valuable outcome .. with this info the industry can xxxx

**Comment by AHuffmyer** [comment]
@sr320 draft of physiology paragraph here: https://docs.google.com/document/d/1CSILo7gVLOcZVQac6JMPdKNy7ihFsgZmYBwsWDSAz2s/edit?tab=t.0
