### ISSUE TITLE
Plate layout info needed for Azenta 30-1067895835 - coral WGBS

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#2017]
@JillAshey

Azenta please needs info on how the submitted sample sheet corresponds to the plates submitted for sequencing (i.e. which samples are in which locations in which plate), since that info isn't included on the sample sheet provided by/to Azenta.

**Comment by JillAshey** [comment]
[azenta_dna_JAZD.csv](https://github.com/user-attachments/files/17671427/azenta_dna_JAZD.csv) - this is the sample sheet with the sample names

[azenta_dna.csv](https://github.com/user-attachments/files/17671428/azenta_dna.csv) - this is the same sheet that I submitted to Azenta

[dna plate1.csv](https://github.com/user-attachments/files/17671454/dna.plate1.csv) - this is the plate map for plate 1

[dna plate2.csv](https://github.com/user-attachments/files/17671453/dna.plate2.csv) - this is the plate map for plate 2

Was there other info they needed?

**Comment by kubu4** [comment]
How were the plates physically labeled? I.e. How would they distinguish one plate from the other? 

Thanks!

**Comment by kubu4** [comment]
I just looked at the plate files and there aren't any sample names. 

Do you have plate files which indicate sample name and positions in the plates you set t to Azsnta?

**Comment by JillAshey** [comment]
In the azenta_dna_JAZD.csv, there is the sample name, plate number, well number, azenta sample name, colony ID and time point. Each physical plate was covered with foil and the project ID (30-1067895835) and plate number (plate 1 or 2) was written on it. 

I printed out the azenta_dna.csv sheet and included it in the box with the samples
