### ISSUE TITLE
Requesting Klone Access

### ISSUE THREAD

**Issue by ChrisMantegna** [RobertsLab/resources#2020]
Hello! 

Can you add me to the lab's Klone group?

Thank you!

**Comment by ChrisMantegna** [comment]
Yes, mantegna is my current NetID. cnmntgna was my old one.

**Comment by sr320** [comment]
So you already have access to- did you have issue logging in?

**Comment by ChrisMantegna** [comment]
No, I tried to check and see if I was in the Roberts group early Wednesday and didn't see myself so I figured I'd just follow the GH instructions and go from there.
