### ISSUE TITLE
Annotate assembled unmapped reads 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#2022]
to determine what non-target species code be in the data 

https://gannet.fish.washington.edu/seashell/bu-github/project-pycno-multispecies-2023/output/08-trinity-unmapped/Trinity.fasta

**Comment by kubu4** [comment]
To clarify, are we talking functional annotation (i.e. SwissProt IDs) or are we talking taxonomic annotation?

**Comment by sr320** [comment]
taxonomic - might not be worth it given findings with megan

**Comment by kubu4** [comment]
Thanks.

I'll just throw it in and see what happens.

**Comment by sr320** [comment]
... interesting mainly common sea star (echinoderm)
