### ISSUE TITLE
Ambiguous RepeatMasker error

### ISSUE THREAD

**Issue by shedurkin** [RobertsLab/resources#2023]
[code](https://github.com/urol-e5/deep-dive-expression/blob/main/D-Apul/code/14-Apul-RepeatMasker.Rmd)
I'm trying to run RepeatMasker to id TEs in our E5 coral genomes, and have been using [Sam's script ](https://robertslab.github.io/sams-notebook/posts/2023/2023-05-26-Repeats-Identification---P.meandrina-Using-RepeatMasker-on-Mox/index.html)to run the tool. RepeatMasker will run at first, but quickly errors out with the message 

> Building species libraries in: /home/shared/8TB_HDD_02/shedurkin/.RepeatMaskerCache/CONS-Dfam_3.8/cnidaria
RepeatMasker::createLib(): Error invoking /home/shared/rmblast-2.14.1/bin/makeblastdb on file /home/shared/8TB_HDD_02/shedurkin/.RepeatMaskerCache/CONS-Dfam_3.8/cnidaria.working/specieslib.

I did some googling, and [this Biostars post](https://www.biostars.org/p/9174/) suggests it's related to rmblastn originally being built with an older UNIX system, and that adding a link to the current libpcr.so file (whatever that is), like so:

`sudo ln -s /lib/x86_64-linux-gnu/libpcre.so.3 /lib/x86_64-linux-gnu/libpcre.so.0`

However, I don't have permissions to make that change so I'm not sure if it'll actually fix the problem

**Comment by kubu4** [comment]
Log file shows this error:

```bash
$ cat /home/shared/8TB_HDD_02/shedurkin/.RepeatMaskerCache/CONS-Dfam_3.8/cnidaria.working/rmblastdb.log


/home/shared/rmblast-2.14.1/bin/makeblastdb: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/shared/rmblast-2.14.1/bin/makeblastdb)
/home/shared/rmblast-2.14.1/bin/makeblastdb: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/shared/rmblast-2.14.1/bin/makeblastdb)
/home/shared/rmblast-2.14.1/bin/makeblastdb: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/shared/rmblast-2.14.1/bin/makeblastdb)
/home/shared/rmblast-2.14.1/bin/makeblastdb: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/shared/rmblast-2.14.1/bin/makeblastdb)
/home/shared/rmblast-2.14.1/bin/makeblastdb: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/shared/rmblast-2.14.1/bin/makeblastdb)
```

Currently investigating solution.

**Comment by kubu4** [comment]
SOLUTIONS: 

- Upgrade operating system. GLIBC is a core part of the OS. However, it seems as though Ubuntu 18.04LTS most up to date version of GLIBC is v2.27.

- I can install in our bioinformatics container and you can run it that way. I've created an issue (#2027) to do this.
