### ISSUE TITLE
monitoring 'srlab' partition usage on klone

### ISSUE THREAD

**Issue by shellywanamaker** [RobertsLab/resources#2024]
sr320
  Monday at 4:55 PM
ok - trying to understand how to best share and do not seem to be able to see `srlab` in `squeue` like before. In other words I do not want to be hogging up resources.... related have you tried using `ckpt` ( the unused nodes) 

sr320
  [Monday at 4:55 PM](https://genefish.slack.com/archives/CDCGTGKU2/p1730757317445049)
I am trying but getting
[sr320@klone-login03 sr320]$ 

```
squeue | grep sr320
          21865065      ckpt rstudio-    sr320 PD       0:00      1 (AssocGrpJobsLimit)
          21839279 cpu-g2-me rstudio-    sr320  R   17:06:10      1 n3439
```
(edited)

Shelly Wanamaker
  Monday at 5:00 PM
srlab isn't showing up in `squeue` because I'm running nfcore pipelines and for them to be more interactive I'm running it through screen as suggested by Carson Miller at UW Peds who does a lot with nfcore [https://resilience-biomarkers-for-aquaculture.github.io/a-fetchNGSKlone/](https://resilience-biomarkers-for-aquaculture.github.io/a-fetchNGSKlone/).
if you `squeue | grep strigg`  you'll see my jobs

sr320
  Monday at 5:01 PM
cool - but can you use
 `ckpt` with that or only our node?

Shelly Wanamaker
  Monday at 5:02 PM
oh i haven't tried, let me see
when I `squeue | grep strigg` I see

![image_720](https://github.com/user-attachments/assets/3890a1b8-31bc-4576-b70d-e952e65ebfc6)
does that mean I'm using `ckpt`?

sr320
  [Monday at 5:05 PM]
wow - that's a lot - I think everything with "Limit" means not running....
[5:06]
we should zoom sometime - I am still learning how this all works, (note currently I am using 30 of 32 cores on our node)
[5:07]
I am curious why your ckpt jobs are not running though.. (edited) 

Shelly Wanamaker
  Monday at 5:08 PM
I am running two jobs, 1 is just downloading data from SRA so I can cancel that one and resume it later because both of my jobs look stalled out or just running slowly

sr320
  [Monday at 5:09 PM]
I do not need any resources myself - just trying to undersand how this all works

kubu4
  Monday at 5:21 PM
squeue doesn't show groups any more, just individual users.

sr320
  [Monday at 10:45 PM]
 but note to see who is using our srlab node this works:
`squeue -A srlab`

**Comment by shellywanamaker** [comment]
even more details if you use:
```
squeue -A srlab -o "%.18i %.9P %.8j %.8u %.2t %.10M %.6D %R %c %m"
```
This checks jobs and shows CPUs and memory used by each job

**Comment by sr320** [comment]
thanks!
