### ISSUE TITLE
using `ckpt` partition on klone with nextflow nf-core pipelines

### ISSUE THREAD

**Issue by shellywanamaker** [RobertsLab/resources#2025]
Shelly Wanamaker
  Yesterday at 1:31 PM
@kubu4  do we have access to `ckpt`? i think my scripts are trying to use those available resources before using srlab resources, but I don't think it is actually using them. when I run `hyakalloc` i see only the `srlab` partition, not the `ckpt` partition

![image_480](https://github.com/user-attachments/assets/44fea6be-3d1e-48a4-bde4-bb24cfd89297)

kubu4
  [Yesterday at 1:33 PM]
We'll, it seems you don't have access to the `ckpt` partition
I have no idea why, though. Could be because you're not a UW employee/student?

Shelly Wanamaker
ah ok, does everyone in srlab have access?

kubu4
  [Yesterday at 1:34 PM]
No idea. @sr320 an myself are the only ones who have used Hyak.

Shelly Wanamaker
  Yesterday at 1:35 PM
ok. I wonder if I can ask IT to give Emma nad me access?

kubu4
  [Yesterday at 1:40 PM] You can always ask. I'm guessing access is related to how you're "sponsored" to have access to Hyak.

sr320
  [Yesterday at 1:43 PM] @Shelly Wanamaker
 I am almost positive I saw you using `ckpt`?

Shelly Wanamaker
  Yesterday at 1:48 PM
i tried but i think my jobs were just PD and maybe never ran on it. i have a job that seems hung up right now and I see available `ckpt` resources and i don't know why it's not using those

sr320
  [Yesterday at 1:59 PM]
Other option is you can set up and we could submit to `ckpt`

Shelly Wanamaker
  26 minutes ago
i was able to output the partition in my nextflow trace file and it **IS** using `ckpt`: [https://gannet.fish.washington.edu/metacarcinus/USDA_MetaOmics/Cgigas_denovotranscript/20241108/pipeline_trace.txt](https://gannet.fish.washington.edu/metacarcinus/USDA_MetaOmics/Cgigas_denovotranscript/20241108/pipeline_trace.txt). the hang ups seem to be something specific with nextflow

**Comment by shellywanamaker** [comment]
I pasted below what my nextflow config file looks like. The 'trace' section shows how I specified the fields to output in the trace file and that is how i saw the ckpt partition was being used.

```

params {
    config_profile_description = 'UW Hyak Roberts labs cluster profile provided by nf-core/configs.'
    config_profile_contact = 'Shelly A. Wanamaker @shellywanamaker'
    config_profile_url = 'https://faculty.washington.edu/sr320/'
    max_memory = 742.GB
    max_cpus = 40
    max_time = 72.h
}

process {
    executor = 'slurm'
    queue = { task.attempt == 1 ? 'ckpt' : 'cpu-g2-mem2x' }
    maxRetries = 1
    clusterOptions = { "-A srlab" }
    scratch = '/gscratch/scrubbed/srlab/'
}

executor {
    queuesize = 50
    submitRateLimit = '1 sec'
}

singularity {
    enabled = true
    autoMounts = true
    cacheDir = '/gscratch/scrubbed/srlab/.apptainer'
}

trace {
    enabled = true
    file = 'pipeline_trace.txt'
    fields = 'task_id,hash,name,status,exit,submit,duration,realtime,%cpu,rss,vmem,rchar,wchar,disk,queue,hostname,cpu_model'
}

debug {
    cleanup = false
}


```

**Comment by sr320** [comment]
maybe try revising  
`queue = { task.attempt == 1 ? 'ckpt' : 'cpu-g2-mem2x' }`
to
`queue = { task.attempt == 1 ? 'ckpt'}`

**Comment by sr320** [comment]
see #2045
