### ISSUE TITLE
Embarrassing Request

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#203]
>I have read your paper entitled 'Evidence of Ostrea lurida Carpenter, 1864, population structure in Puget Sound, WA, USA', and I would like to include your data in my analysis. To do so, however, I need to know what the sample sizes used to measure growth were (i.e. those represented in figures 5, 7 and 9). I was wondering if you could send me this information?

What are the sample sizes?

**Comment by kubu4** [comment]
Don't have time to calculate atm, but here's the link to figure it out (I think): https://github.com/RobertsLab/OluridaSurvey2014/blob/master/data/Size-outplant-end-all-2013-14.csv

**Comment by kubu4** [comment]
I get those same numbers.

I used bash ```grep``` instead of Excel.

E.g.: ```grep Fidalgo Size-outplant-end-all-2013-14.csv | wc -l```

Would be curious to see what solution with R looks like.

**Comment by kubu4** [comment]
Whoop! I got the same "Grand Total" numbers located in the last column. I'll see if I can confirm the numbers for the Sep and Oct columns...

**Comment by sr320** [comment]
Yes I do not think all data in that table was used.   Just last date. But
would have to dig into R code to confirm

**Comment by kubu4** [comment]
Haven't had time to look into this in R, but I think there's a section in the Data Carpentry R Ecology course that uses the ```dplyr``` library with the ```filter``` and ```select``` functions that might make this pretty straightforward.

**Comment by sr320** [comment]
I was referring to looking at Jakes code to make the figures

**Comment by kubu4** [comment]
Yes, I saw that.

I was just proposing a solution to pull the data using R, like you did using Excel.

**Comment by sr320** [comment]
Gotcha

**Comment by sr320** [comment]
@kubu4 could you check the figure code and see what you think?

**Comment by kubu4** [comment]
Figure code confirms your numbers.

**Comment by sr320** [comment]
so October for two graphs and September for the other?

**Comment by kubu4** [comment]
Yep!

**Comment by sr320** [comment]
Thanks!
