### ISSUE TITLE
Install MiRanda on Raven

### ISSUE THREAD

**Issue by shedurkin** [RobertsLab/resources#2033]
@kubu4 would you be able to assist me in installing the miRNA target prediction software, miRanda, on Raven? The tool's website is down, but Jill says she was able to install using the [github repo](https://github.com/hacktrackgnulinux/miranda), then access using a conda environment.

**Comment by kubu4** [comment]
Done.

It's here:

`/home/shared/miRanda-3.3a/src/miranda`

I installed it by pulling the download via the Internet Archive:

https://web.archive.org/web/20170830035321/http://www.microrna.org/microrna/getDownloads.do
