### ISSUE TITLE
NGS quote and questions

### ISSUE THREAD

**Issue by jldimond** [RobertsLab/resources#204]
I got a [quote](https://drive.google.com/open?id=0B3SxFvUO3NtcUGQxTGZUclBoelNMQVFDakszc1FGWXdfVG5r) for RNAseq library prep and sequencing from Genewiz. It comes to $318.50 per sample after a 30% off discount applied. They quoted me for only 10 samples but I would probably do double that. 

A couple of questions:

1. Is this a good quote? Seems pretty good to me for both library prep and sequencing.

2. Would I be smarter to do the library prep myself (with, say, an NEB directional kit), or would I be saving myself a lot of potential issues and headaches? Never done RNAseq before.

3. I want to couple the RNAseq with MBD-bisulphite, with the ultimate goal of looking at methylation and potential alternative splicing. Based on their pricing, should I get a quote for library prep and sequencing of the MBD libraries and consider having them do everything, or should I do some of this myself? I have about $10k to work with and just want to optimize time, effort, and money. I would also be new at MBD-bisulphite.

4. Prior to RNA sample submission (if I have them do the library prep), is it essential that I run RNA on a bioanalyzer if my Qubit results look good? Nanodrop?

Thanks

**Comment by sr320** [comment]
A couple of questions:

> 1. Is this a good quote? Seems pretty good to me for both library prep and sequencing.

Yes

> 2. Would I be smarter to do the library prep myself (with, say, an NEB directional kit), or would I be saving myself a lot of potential issues and headaches? Never done RNAseq before.

No

> 3. I want to couple the RNAseq with MBD-bisulphite, with the ultimate goal of looking at methylation and potential alternative splicing. Based on their pricing, should I get a quote for library prep and sequencing of the MBD libraries and consider having them do everything, or should I do some of this myself? I have about $10k to work with and just want to optimize time, effort, and money. I would also be new at MBD-bisulphite.

Yes on getting a quote


> 4. Prior to RNA sample submission (if I have them do the library prep), is it essential that I run RNA on a bioanalyzer if my Qubit results look good? Nanodrop?

No

**Comment by sr320** [comment]
A couple of questions:

> 1. Is this a good quote? Seems pretty good to me for both library prep and sequencing.

Yes

> 2. Would I be smarter to do the library prep myself (with, say, an NEB directional kit), or would I be saving myself a lot of potential issues and headaches? Never done RNAseq before.

No

> 3. I want to couple the RNAseq with MBD-bisulphite, with the ultimate goal of looking at methylation and potential alternative splicing. Based on their pricing, should I get a quote for library prep and sequencing of the MBD libraries and consider having them do everything, or should I do some of this myself? I have about $10k to work with and just want to optimize time, effort, and money. I would also be new at MBD-bisulphite.

Yes on getting a quote


> 4. Prior to RNA sample submission (if I have them do the library prep), is it essential that I run RNA on a bioanalyzer if my Qubit results look good? Nanodrop?

No

**Comment by jldimond** [comment]
Perfect, thank you.

Hoping to get a quote from Genewiz and Diagenode for MBDseq and/or RRBS.
