### ISSUE TITLE
Disk quota on scrubbed klone

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#2042]
Did not think this was possible but err files

```
Failed to close filehandle Disk quota exceeded
Warning: unable to close filehandle properly: Disk quota exceeded, <IN> line 474689064 during global destruction.
```

**Comment by sr320** [comment]
? according to https://robertslab.github.io/resources/klone_Data-Storage-and-System-Organization/

I have 200 TB....

**Comment by sr320** [comment]
trying

```
[sr320@klone-login03 code]$ ulimit -n
1024
[sr320@klone-login03 code]$ ulimit -n 4096
[sr320@klone-login03 code]$ ulimit -n
4096
```

**Comment by kubu4** [comment]
There's also a limit on the total number of files in scrubbed.

There should be a way to view the disk quotas for scrubbed. I'll report back if I can find it.

**Comment by sr320** [comment]
Thanks
Would also be interested to know if we can pay to increase

**Comment by kubu4** [comment]
Well, looks like Scrubbed is:

- [10TB/individual](https://uw-rcc.slack.com/archives/C04SCAARLHZ/p1731085855050439?thread_ts=1731026084.152009&cid=C04SCAARLHZ)

- [90TB shared](https://uw-rcc.slack.com/archives/C04SCAARLHZ/p1731097501442889?thread_ts=1731026084.152009&cid=C04SCAARLHZ)

Guessing this is another change they implemented in Klone, compared to Mox...

**Comment by kubu4** [comment]
I'll certainly ask, but it seems complicated since Scrubbed is a shared resource across all users.

**Comment by sr320** [comment]
Related- the costs for increasing srlab space

**Comment by sr320** [comment]
exceed my storage of 10TB

**Comment by kubu4** [comment]
From UW IT, regarding increasing storage:

> Hi Sam, 
>
>
>You can increase you groups gscratch quota in 1 TB increments on request. Storage in excess of the 1TB included with a slice purchase is $10/TB/month. I see that you have an additional storage subscription for 1TB/month using the worktags: GR006094 AS105876, we could increase the billed quota if you wish. Are you aware of any other storage subscriptions with us?
>
>
>It looks like you have a 1TB quota on klone from your slice purchase. However, your quota on mox is 8TB of which it appears you are using 5TB. 
>
>
>We do not have plans to increase the total scrubbed quota and so we don't plan to increase the individual quotas. FYI We have seen that at times individuals can't use their entire 10TB quota. The TOTAL scrubbed quota is 90TB and so if few users use larger amounts, there is little left for other users, hence the 21 day automatic erase for unmodified files. Scrubbed is a courtesy for the community, but it is not intended to support large quotas long term. 
>
>
>We do have our new Kopah S3 storage option. It is in preview launch and so free to use on a trial basis. The prices will be between $5-6 per TB per month. Would you be interested in starting a group account? 
>
>
>Let me know how you would like to proceed. 
>
>
>Kristen


Looks like the Kopah S3 storage is just that - additional storage in S3 "buckets". It doesn't appear to be able to be used for directly computing on Klone, but I've requested clarification on that.

**Comment by kubu4** [comment]
> exceed my storage of 10TB

Just to expand on this. Although each user has a limit of 10TB, if the total capacity on scrubbed is used by others, then you may _not_ have 10TB of space available to use. 

E.g. Nine users are each using their full allotment of 10TB on scrubbed. That's a total of 90TB, which is the entire capacity on scrubbed. This would mean that no other users will have _any_ space to use on scrubbed. So, it's possible you didn't actually hit your 10TB quota, since it's possible that scrubbed may have already been full.
