### ISSUE TITLE
Assess status / mortality / WC of oyster tanks in FTR

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#2043]

**Comment by AHuffmyer** [comment]
Can work on this today

**Comment by AHuffmyer** [comment]
Oysters look good - we want to re do storage system. I think I'll go look at the store this weekend and see what I can find! The seed are too small for the baskets/bags we currently have in the freezer room. 

I'm thinking plastic storage baskets with smaller mesh/hole sizes (and bonus for dividers).
