### ISSUE TITLE
Ceasmallr sample metadata -- clarifying questions

### ISSUE THREAD

**Issue by shedurkin** [RobertsLab/resources#2046]
I'm trying to get a handle on the experimental design and metadata for the Ceasmallr samples. I've read through the methods in [Yaamini's paper](https://doi.org/10.1093/eep/dvae018) (the ceabigr data) and the associated [pCO2-exposed larval physiology paper](https://doi.org/10.1002/lno.12162).

My understanding is that:
1) Adult male and female C.virginica oysters were exposed to elevated pCO2 for 30 days (controls at ambient)
2) Oyster gonads were sampled for their gametes (sperm or eggs). These samples were used to generate the ceabigr WGBS and RNAseq data.
3) Oysters were then used for fertilization crosses. A given female was only crossed with males from the same OA treatment, resulting in ControlxControl and ExposedxExposed zygotes. 
4) Offspring were then exposed to the same elevated pCO2 for ~3 days (again, with controls at ambient). Larvae from both parent treatments were used for both larval treatments, yielding 4 functional treatment groups (ParentControl+LarvalControl, ParentControl+LarvalExposed, ParentExposed+LarvalControl, ParentExposed+LarvalExposed. See below)
![image](https://github.com/user-attachments/assets/f9b1bfe4-59ef-48fb-b172-4708b4083b9c)
(Fig. 2 [McNally et al. 2022](https://doi.org/10.1002/lno.12162))
5) 2 hours into this treatment, zygotes were sampled for WGBS. At conclusion of treatment, larvae were sampled for WGBS. These comprise the ceasmallr data. 

Looking at the [ceasmallr metadata](https://github.com/sr320/ceasmallr/blob/main/data/L18_larvae_meta.csv) I see the notations `CF##`, `CM##`, `EF##`, `EM##`, under `Sample.ID`, which I'm assuming denote the sex and treatment of both parents, where C=control, E=exposed, F=female parent, and M=male parent. The `Treatment` column denotes the treatment and developmental stage of each offspring sample (e.g. `C_Zygote` denotes a zygote exposed to control pCO2 conditions). I also note that the only offspring represented in this metadata are those which experienced the same treatment as their parents (ParentControl+LarvalControl or ParentExposed+LarvalExposed). 

Questions:
1) Is this interpretation of the experimental setup and metadata correct?
2) Were no control larvae with exposed parents sequenced?
3) If there's no WGBS data for ParentExposed+LarvalControl samples, which could be used to investigate inheritance of methylation markers, what was the motivation for selecting these samples for WGBS?

**Comment by sr320** [comment]
Have you linked offspring data directly back to parent data using offspring
IDs?

**Comment by sr320** [comment]
How about we want to determine if methylation marks induced in parents are present in offspring?

**Comment by sr320** [comment]
> The Treatment column denotes the treatment and developmental stage of each offspring sample (e.g. C_Zygote denotes a zygote exposed to control pCO2 conditions)

I do not think this is necessarily true, that could just be a label so could group all zygotes from control parents... @yaaminiv, @kubu4 do you know if offspring themselves had a treatment - I was considering they were all in control conditions?

**Comment by shedurkin** [comment]
There were definitely offspring cohorts that underwent an elevated pCO2 treatment, as detailed in [McNally et al. 2022](https://doi.org/10.1002/lno.12162), which is cited by [Venkataraman et al. 2024](https://doi.org/10.1093/eep/dvae018) as the experimental source of ceabigr data. The figure I included in my original post shows the reciprocal exposure design.

I could just be misinterpreting the metadata labels though?

**Comment by sr320** [comment]
@shedurkin you are correct in terms of the experiment ... but we did not sequence everything.

yes the question is treatment really exposure - or just a group label...

**Comment by sr320** [comment]
more hints: https://d.pr/i/CRBLZp

https://d.pr/i/PkpAeh
