### ISSUE TITLE
in search of go slim tutorial 

### ISSUE THREAD

**Issue by meganewing** [RobertsLab/resources#2048]
As someone who has never used it before, I am seeking some info on go slim: how to use (correctly and effectively), when to use, how to interpret.

**Comment by sr320** [comment]
GO parental terms offer annotation information, would always obtain / use.
Interpret as form of annotation.

**Comment by meganewing** [comment]
Is there a use tutorial somewhere?

**Comment by sr320** [comment]
Not sure if you are asking for how-to… but there is
https://robertslab.github.io/resources/bio-Annotation/#map-go-ids-to-goslims

**Comment by meganewing** [comment]
yes! thank you!
