### ISSUE TITLE
Purchase srlab group storage on klone

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#2049]
80TB

**Comment by sr320** [comment]
sorry my math was wrong...

How about 8 more TBs - that would but us at 18TB in group storage?

**Comment by kubu4** [comment]
`srlab` only has 1TB of storage currently.

To get to a total of 18TB would cost $170/month.

**Comment by sr320** [comment]
Let’s start with 8 additional at $80/month

**Comment by kubu4** [comment]
Request has been submitted to UW IT.

**Comment by kubu4** [comment]
We should be good to go!
