### ISSUE TITLE
RNA isolation questions

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#205]
I'm going to extract both larvae (using the [protocol in lab resources](https://github.com/RobertsLab/resources/blob/master/protocols/rna_isolation_rnazol_rt.md)), and gonad fixed in paraffin using the PAXgene Tissue RNA kit, and following [Sam's notebook](http://onsnetwork.org/kubu4/2017/07/19/rna-isolation-olympia-oyster-gonad-tissue-in-paraffin-histology-blocks-2/).  

Is there a specific hood that is recommended for RNA isolation?  E.g., the "BioGARD" hood in 209? 

For disruption & homogenization:  
  * Larvae: I'll plan to use the recently ordered tube mortar/pestles to homogenize, following the protocol (so, I won't use liquid nitrogen... feedback?).  
  * Fixed gonad:  
    - I'll plan on using the Tissue Tearor, since I presume the Friedman Disrupter Genie is still broken?  
    - @kubu4 you added glass beads to the samples when you used the Disruptor Genie, and suggested I do the same, but I'm not clear on when in the protocol I should do this - while homogenizing with the Tissue Tearor (wouldn't this shatter the beads?) , or while incubating/shaking?  
    - Regarding cleaning between samples, I'll plan to use bleach, then water, ethanol. I can also wipe with the ELIMINase - suggestions?   

Thanks!

**Comment by laurahspencer** [comment]
Update: I found 2-mercaptoethanol in the 209 fridge, which [Wikipedia])https://en.wikipedia.org/wiki/2-Mercaptoethanol) tells me is the same as beta-mercaptoethanol.

**Comment by kubu4** [comment]
> Is there a specific hood that is recommended for RNA isolation? E.g., the "BioGARD" hood in 209?

Use a fume hood. The "BioGARD" is a biosafety cabinet and should not be used with any volatile chemicals, as it is not a fume hood. It is a recirculating cabinet to prevent outside air from contaminating the contents contained within the hood. 

> I'll plan on using the Tissue Tearor, since I presume the Friedman Disrupter Genie is still broken?

Yes, it is still broken and will likely never be replaced/repaired.

> added glass beads to the samples when you used the Disruptor Genie

This is the homogenization step. 

> while homogenizing with the Tissue Tearor (wouldn't this shatter the beads?)

I wouldn't use the Tissue Tearer. I would use the vortexer and glass beads.

> Regarding cleaning between samples

What will you be cleaning?

**Comment by laurahspencer** [comment]
Thanks Sam!  Roger that on the hood.

My cleaning question was regarding the Tissue Tearor, i.e. how to clean it between samples.  However, if I use glass beads + vortexer, then I won't need to clean.  I will plan on vortexing at max speed. How long do you suggest?

**Comment by kubu4** [comment]
Don't know. I'd do it for at least the amount of time that the protocol indicates for homogenization. However, this might be something you'd need to test out a bit. Do you have more "junk" samples that you can test?

Regardless, I'd probably extend the time a bit (increase 5 - 10 mins?).

**Comment by laurahspencer** [comment]
My conclusion: to vortex until I visually see no (or little) solid tissue mass.  

@kubu4 - is there any reason I should not keep the glass beads in my sample during a 15-minute incubation with Proteinase K (@45C, with very high rpm shaking)?  I'd prefer to not transfer the lysate into new tubes to avoid losing some of my sample, just to get rid of the beads.

**Comment by kubu4** [comment]
You can keep the beads in the sample. The protocol doesn't indicate removal of the beads prior to that step. The supernatant is transferred to a new tube at Step 6.

However, transferring the supe to a new tube after disruption/homegenization (before pro K incubation) will provide easier visualization of the pellet at the end of Step 6.
