### ISSUE TITLE
add 2024 slidedecks to lab website

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#2050]

**Comment by AHuffmyer** [comment]
https://github.com/AHuffmyer/presentations

**Comment by sr320** [comment]
@AHuffmyer and all you can add directly at https://faculty.washington.edu/sr320/publications.html#recent-presentations (top icons have edit this site option)

I will have to render so edits will not show up immediately on site.

**Comment by AHuffmyer** [comment]
Done!
