### ISSUE TITLE
Check notebook links on lab website

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#2051]

**Comment by kubu4** [comment]
FYI - We have a GitHub action running that checks links each time the website is updated:

![image](https://github.com/user-attachments/assets/1940daa7-f4d2-4bfe-b122-36ad1c32cf7a)


It looks like everything is passing.

**Comment by sr320** [comment]
should be up to date now...
https://faculty.washington.edu/sr320/notebooks.html

Folks should triple check - seems impossible? some have not been updated since October? @zbengt @valeste
