### ISSUE TITLE
error rsync to gannet

### ISSUE THREAD

**Issue by shellywanamaker** [RobertsLab/resources#2052]
Getting an error trying to rsync to gannet from klone. Am I missing something?

![image](https://github.com/user-attachments/assets/b3e93ed6-e4f9-4040-88de-31353d5b0d5b)

**Comment by shellywanamaker** [comment]
i will say that i had tried to login to gannet earlier this morning to create a new directory but i entered my username and password incorrectly 3 times and i got the message 
![image](https://github.com/user-attachments/assets/cae1198c-fcd9-42ab-a9a7-74995a0203f5)

**Comment by kubu4** [comment]
I've unblocked two IP addresses originating from the United States, which were blocked this morning. I'm guessing one of them was yours.

Feel free to give it another go.

**Comment by shellywanamaker** [comment]
still getting the same error and it's immediate as soon as i hit enter

**Comment by shellywanamaker** [comment]
I just checked with @emmastrand and she's getting the same error

**Comment by kubu4** [comment]
Which error are you referring to? IP address or the initial error?

Have you tried to SSH to gannet?

Have you tried to login to gannet via the web interface (https://gannet.fish.washington.edu)?

**Comment by shellywanamaker** [comment]
the rsync error, not the initial IP address error

**Comment by sr320** [comment]
I tried and get..

```
[sr320@klone-login03 analyses]$ rsync -avz 20241127_methylseq_test sr320@gannet.fish.washington.edu:/volume2/web/seashell/bu-orange/
kex_exchange_identification: read: Connection reset by peer
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.3]
```

note never getting to point where asking for password

**Comment by shellywanamaker** [comment]
no problem logging in now

**Comment by shellywanamaker** [comment]
but still getting rsync error

**Comment by kubu4** [comment]
Seems to be related to Klone, as I can ssh into gannet from my computer, but am _unable_ to from Klone...

**Comment by sr320** [comment]
Agree its a klone issue.....

```
sr320@Stevens-MacBook-Air-8 ~ % rsync -avz wekafiles sr320@gannet.fish.washington.edu:/volume2/web/seashell/bu-orange/
sr320@gannet.fish.washington.edu's password: 
building file list ... done
wekafiles/
wekafiles/weka.log
wekafiles/native/
wekafiles/packages/
wekafiles/props/
wekafiles/repCache/
wekafiles/wekaMetaStore/
```
