### ISSUE TITLE
FastQ checksums failing after download from Owl

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#2056]
I'm experiencing some weird behavior when trying to download FastQs from Owl to Raven.

After downloading (via `wget`), all the MD5 checksums fail. I've deleted and re-downloaded the files a couple of times:

https://github.com/RobertsLab/project-clam-oa/blob/3554e68245c0a12dad596d176e8561d094437b35/code/00.00-fastqc-concatenation-raw_reads.Rmd#L145C1-L164C5

```
./196_R1_001.fastq.gz: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
./196_R2_001.fastq.gz: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
./199_R1_001.fastq.gz: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
./199_R2_001.fastq.gz: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
./211_R1_001.fastq.gz: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
./211_R2_001.fastq.gz: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
```

I've confirmed (repeatedly) that the MD5 checksums _on_ Owl are fine:

![Screenshot showing MD5 checksums passing checks.](https://github.com/user-attachments/assets/47683a52-97df-4124-8ba7-91b26e1aa7d4)

Anyone have any idea what might be happening? I've never experienced this before, and it's weird that it's happening after repeated downloads...

**Comment by kubu4** [comment]
No. Figured the computer was better at checking it! Will do. BRB...

**Comment by kubu4** [comment]
They don't match.

![image](https://github.com/user-attachments/assets/00c2d574-d0a9-419c-b2d1-024c5cf08133)

**Comment by sr320** [comment]
what about rsync? still an issue?

**Comment by kubu4** [comment]
Rsync results in successful transfer/checksum verification. I'll utilize this to go forward with analysis, obviously, but it's very odd behavior...

**Comment by kubu4** [comment]
Closing, as it's not worthy spending time figuring out what's going wrong with `wget` transfers....
