### ISSUE TITLE
Low on 96 well plates

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#2058]
We are low/out of 96 well plates in the lab. I looked on the shelf in 209 and didn't see any additional plates. Is there somewhere else I should look? If we are out, could we place an order for more?

**Comment by kubu4** [comment]
Which kind of plates? PCR? qPCR? Cell culture?

PCR/qPCR plates are in drawers beneath the thermacylcer(s) in 209.

Cell cultures plates are have generally been stashed on top of the chemical cabinet and/or on top of the shelves between the lab benches in 209.

**Comment by AHuffmyer** [comment]
Culture plates!

Thanks I did find some on top of the chemical cabinet, but only 6 of them. Could we do an order to restock? I'll need 10-15 total for some lab work in January. I'm happy to place an order if you send me the link to what you normally purchase.

**Comment by sr320** [comment]
we probably have never ordered....... 
would this work? https://www.amazon.com/Tissue-Culture-Plate-Well-Individual/dp/B08MVV8MYC

**Comment by AHuffmyer** [comment]
Yes, these would be just fine - I can place a Treq order.
