### ISSUE TITLE
Add qPCR and RNA extraction methods to lifestage carry over manuscript

### ISSUE THREAD

**Issue by AHuffmyer** [RobertsLab/resources#2059]
Hi Sam! Could you add RNA extraction and qPCR methods to the manuscript at the link below? This can be bullet point format with all the relevant information and I can turn into sentence format if needed. 

https://docs.google.com/document/d/1rev275fb10r0Abl21HabtCelCR74FOHPZRhm3fbTsZ8/edit?tab=t.0

**Comment by kubu4** [comment]
Think I have most of it entered in there. Whenever you get around to it, check it out and let me know.

**Comment by AHuffmyer** [comment]
Wow this looks great! Thank you!
