### ISSUE TITLE
2-propanol: for RNA isolation

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#208]
I used pretty much the last of it today. 

I looked in myChem and saw that 3 bottles of 2-propanol were purchased in 2008. I couldn't find any other bottles in the flammable cabinet in 209 other than the current one that is almost out.

**Comment by kubu4** [comment]
It's not a problem to order more, but there is plenty (I'd guess ~250mL) of isopropanol (which is the same as 2-propanol) in the flammables cabinet.
