### ISSUE TITLE
HMW DNA extraction 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#209]
Question :

>> I was wondering if I could ask what protocol you have used for HMW DNA extraction for geoduck and oysters. My first attempt with the Qiagen HMW DNA kit did not give me very long DNA so I am looking into multiple options and I know protocols often need a bit of tweaking for bivalve samples to deal with the mucopolysaccharides, so I was hoping to see what you have done.

**Comment by kubu4** [comment]
We use the E.Z.N.A. Mollusc Kit (Omega). Combined with tissue pulverization under liquid nitrogen, we have yielded HMW DNA that was suitable for 10x Genomics sequencing platform.
