### ISSUE TITLE
Consider a podcast

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#21]
See also https://github.com/RobertsLab/2017-hackweek/issues/16

**Comment by laurahspencer** [comment]
Will interview Megan as a pilot/test run, planning on doing so within the next 3 weeks.
Will nail down which gear to purchase within the next couple days.

**Comment by laurahspencer** [comment]
Ian put together a list of equipment for transportable podcast recording kit, attached.  He also suggests having a dedicated laptop, either Windows or Mac.  Do we have any laptops kicking around that could be used for this?  

Let me know your thoughts on the equipment, costs, etc. 

[UW Fisheries Podcast Spec.pdf](https://github.com/RobertsLab/resources/files/1275794/UW.Fisheries.Podcast.Spec.pdf)

**Comment by laurahspencer** [comment]
Consideration:  
Natalie used this mic, rented (for free) from UW tech resources.  We could look into using some of their stuff in the beginning until we get a feel for what we need/want. 
![file_000 12](https://user-images.githubusercontent.com/17264765/30708664-85a1ff56-9eb4-11e7-87d1-ea1bc08fae86.jpeg)

**Comment by grace-ac** [comment]
The proposal suggests this equipment:
Total: $2500
- Podcasting microphone (Shure PG42-USB Vocal Microphone) ($220) 
- broadcast boom (Heil Sound PL-2T Overhead Broadcast Boom) ($120)
- shock mount ($50)
- webcam ($50) 
- two lavaliere microphones (Rode smartLav+Lavalier Microphone) ($160)
- GoPro Camera ($300) 
- two studio headphones ($100)
- computer for recording, audio and video processing, publishing (21.5 inch iMac) ($1500)

**Comment by grace-ac** [comment]
The above prices may be different now (cheaper) because the proposal is from 3 years ago

**Comment by sr320** [comment]
@grace-ac - note @laurahspencer created an updated shopping list
https://github.com/RobertsLab/resources/issues/21#issuecomment-327050206

But before we purchase everything - see what UW tech resources might have that we can borrow.

**Comment by sr320** [comment]
Also determine how we might "publish" a podcast..

**Comment by grace-ac** [comment]
maybe a silly question, but we do not need cameras for a podcast, right?

the NPRB proposal includes cameras, but the shopping list Laura created does not.

**Comment by sr320** [comment]
we could do audio-only (we could also use our webcams for video podcast)

**Comment by grace-ac** [comment]
I stopped by the [UW Student Technology Loan Program](https://stlp.uw.edu/#/equipment) (Basement of Kane Hall) this morning. 

I have set up a 7-day rental for three mic options in order to test them out and see what we might like to purchase. 
[Sony UWP - V1](https://www.cte.uw.edu/w/images/6/69/Sony_WMS_Manual.pdf)
[Olympus WS-510M](http://www.olympusamerica.com/files/oima_cckb/ws-520M_ws-510M_ws-500M_ws-400S_Detailed_Instructions_en.pdf)
[Samson Meteor Mic](http://www.samsontech.com/site_media/legacy_docs/Meteor%20Mic_OM_v1.pdf)
