### ISSUE TITLE
Efficient Literature Discovery [Pub-a-thon]

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#210]
As we get closer to the official launch of Pub-a-thon 2018, pre season point accumulation has begun. 

The first task is to provide an automated way to discover literature that is relevant to your research.

This will likely be a url (or several). Please provide below.

**Comment by grace-ac** [comment]
https://scholar.google.com/scholar_alerts?view_op=list_alerts&hl=en
I tried out the google scholar alerts.... nothing has happened yet

![screen shot 2018-04-02 at 11 33 43 am](https://user-images.githubusercontent.com/14934314/38209641-dd2c5454-3669-11e8-837b-8a576f5cb8d1.png)

**Comment by grace-ac** [comment]
Got some alert emails from google scholar... and none of them were helpful. Might be interesting reads, but nothing particularly relevant to the crab project 

"Historical dictionary of New England" (dutch elm **disease**) ; "Considering the importance of metaphors in marine conservation"; deep sea fish assemblages.... etc.

**Comment by yaaminiv** [comment]
I made some Google Scholar alerts as well! Not sure what queries I actually need so I added whatever I could think of
![screen shot 2018-04-05 at 12 28 01 am](https://user-images.githubusercontent.com/22335838/38352521-5640aef8-3868-11e8-99cf-1c6c6b52f228.png)

I created some topic alerts on Science Direct, and some journal alerts (those haven't loaded yet so I don't have a fancy screenshot)
<img width="979" alt="screen shot 2018-04-05 at 12 49 31 am" src="https://user-images.githubusercontent.com/22335838/38353463-55bbf8a4-386b-11e8-8d41-69d2b4e188f7.png">

**Comment by yaaminiv** [comment]
Update: my ScienceDirect and Google Scholar alerts sent me some cool papers this weekend! Shared a few in the lab's Google+
