### ISSUE TITLE
Establish histology database, physical inventory, and management plan

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#213]
We received the slide cases from Pam today. Cassette drawers will probably come at the end of the month.

We should start considering how to organize things and how to document all of this stuff. It'd be killer to have links to corresponding images in the database, as well as info on post-embedding sampling info (i.e. RNA/DNA isolations).

**Comment by sr320** [comment]
Hackweek?

**Comment by sr320** [comment]
moved to hackweek
