### ISSUE TITLE
Qubit RNA HS Assay Kit

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#214]
Ran out of RNA reagent today... 

https://www.thermofisher.com/order/catalog/product/Q32852

**Comment by sr320** [comment]
Pam needs to order

**Comment by kubu4** [comment]
I believe there's an unopened kit in the fridge. A kit that was received in Nov. 2017.

**Comment by grace-ac** [comment]
yup! there was some in the fridge in a box that i used today
