### ISSUE TITLE
DNA minimum for MBD-BS

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#215]
For the virginica project we are trying to ID the lower limit of starting material for larvae library prep. What does this value look like under our current workflow?

**Comment by kubu4** [comment]
Assuming 1% recovery, 1700ng of starting input DNA is the current minimum.

This is based off of @yaaminiv's most recent MBD/BSseq with Zymo. They were able to make a library out of 17ng of MBD-enriched DNA.

**Comment by sr320** [comment]
Thanks
