### ISSUE TITLE
Details of zymo BS library prep

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#216]
For data analysis we need to know library prep details C virginica libraries, enough details so one could reproduce. A major point is whether they are directional.

**Comment by kubu4** [comment]
FYI, I have an email out to Zymo. Will post deets once received.

**Comment by kubu4** [comment]
Current info (awaiting additional clarification on library construction):

- non-directional
- HiSeq1500
- bisulfite conversion using EZ DNA Methylation - LightningTM kit (ZymoResearch, Cat#: D5030).

**Comment by kubu4** [comment]
Library prep:

- Pico Methyl-Seq Library Prep Kit (cat. #D5455)

Protocol summary:

>Section 1: Bisulfite Conversion of Genomic DNA 
Section 2: Amplification with PrepAmp Primer  
Section 3: Purification with the DNA Clean & Concentrator
Section 4: Amplification with LibraryAmp Primers 
Section 5: Amplification with Index Primer 
Section 6: Validation and Quantification of Library
