### ISSUE TITLE
Trim Cvirginica MBD-BS samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#217]
Based on a cursory fastqc check I believe 5' end (14bp) and maybe last bp should trimmed.
Please double check and trim accordingly.
thanks!

**Comment by kubu4** [comment]
Overall, I think they look OK. I don't think trimming is necessary, but happy to do so. Do you want to try trimmed vs. untrimmed? Based on the rest of the FastQC data, I think this data has already been through a round of trimming (e.g. no adaptor contamination present).

**Comment by sr320** [comment]
You have a link to fastqc and I can indicate what concerns me?

**Comment by sr320** [comment]
I would like to compare trimmed vs untrimmed. I mapped untrimmed and it is
pretty poor compared to Qiagen (though still need to know if directional
for direct comparison)

**Comment by kubu4** [comment]
MultiQC output: http://owl.fish.washington.edu/Athaliana/20180409_fastqc_Cvirginica_MBD/multiqc_report.html

I'm guessing the Sequence Length Distribution (that's the only one that throws consistent warnings for all samples).

**Comment by sr320** [comment]
Interesting- it does not seem multiQC catches it...
See
http://owl.fish.washington.edu/halfshell/bu-serine-wd/18-04-07/fqc/zr2096_4_s1_R1_fastqc.html

Per base sequence content

**Comment by sr320** [comment]
At least on mobile- I cannot discern

**Comment by kubu4** [comment]
Although I'm still awaiting a response about how library construction was performed, I glanced through Zymo's [Pico Methyl-Seq Library Prep Kit protocol](https://dwo0hlbtc3ypb.cloudfront.net/amasty/amfile/attach/d5455i.pdf) and found this "tip" on page 8:

> Treat Pico Methyl-Seq™ libraries as 50 bp single-end reads when mapping back to the reference genome. Sequentially trimming of the first four bases may increase mapping efficiency. 

The part about treating libraries as single-end reads is what really caught my eye.

However, I have no idea if this is the kit they used to construct the libraries - just a guess.

Hopefully we'll have a definitive answer soon, but in the meantime, it could be interesting trying to map the reads as single-end.

**Comment by sr320** [comment]
Minimally they should be able to provide rationale for 

![pic](https://d.pr/i/RDPgcJ+)

those lines should be straight across in my opinion

**Comment by kubu4** [comment]
Well, this is why MultiQC didn't catch it (my FastQC results are different than yours):

http://owl.fish.washington.edu/Athaliana/20180409_fastqc_Cvirginica_MBD/zr2096_4_s1_R1_fastqc.html

![selection_030](https://user-images.githubusercontent.com/4514104/38526652-01f2dec8-3c0c-11e8-922f-a3539fe25c8e.png)

**Comment by kubu4** [comment]
My "Per base sequence content" is identical to yours (which I would've expected for all of it).

Yeah, it's definitely a bit lumpy at the beginning. TrimGalore is running and has identified a very small amount of adapter contamination. After that runs and we see how it looks, maybe I'll just have it trim n bases off the beginning of each read.

**Comment by sr320** [comment]
Yes I am thinking a hard trim is needed...

**Comment by kubu4** [comment]
Trimming per Bismarck's recommendations (10bp 5'/3') is done, looks good, and can be found here: 

http://owl.fish.washington.edu/Athaliana/20180411_trimgalore_10bp_Cvirginica_MBD/
