### ISSUE TITLE
Fix "Salinity (PSU)" data in Manchester Water Chemistry Data sheet

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#222]
Hi @yaaminiv,

There are still some issues with some of the data in that column. When you have the chance, could you please fix them (see screenshot for example)?

[Manchester Water Chemistry Data sheet](https://docs.google.com/spreadsheets/d/1NimY1gQFM8eR_wdkM5__nEw3JwEhihmIBHiOqXnBYJ4/edit?usp=sharing)

![selection_035](https://user-images.githubusercontent.com/4514104/39208421-cf240730-47b7-11e8-92c1-737722cac122.png)

**Comment by yaaminiv** [comment]
done!
