### ISSUE TITLE
Data Management: Moving data from spreadsheets into a MasterSheet

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#223]
Apparently copy and pasting is frowned upon! So, I am reaching out to see if anyone has any helpful resources that I can use to help with re-organizing and consolidating my data. 

I currently have things in lots of separate files for various reasons, but want to learn a non-copy and paste method for pulling data from one spreadsheet and getting it into a different one.

**Comment by kubu4** [comment]
An example would be helpful in guiding suggestions.

**Comment by grace-ac** [comment]
One example:
So I have lots of files with Qubit data that look like this:
![screen shot 2018-04-24 at 4 07 49 pm](https://user-images.githubusercontent.com/14934314/39218456-b608d632-47d9-11e8-85bc-51bbeab7c72b.png)

I have a separate spreadsheet containing data on the crab that the Qubit data samples are from that looks like this:
![screen shot 2018-04-24 at 4 09 22 pm](https://user-images.githubusercontent.com/14934314/39218539-193ffe38-47da-11e8-9cfd-722c8fad1b5a.png)
The Qubit Tube Conc. data is in column 5 of the Qubit Data spreadsheet.

**Comment by kubu4** [comment]
I'd argue that this would count as data entry, so copying/pasting would be just fine.

However, you could use this as an exercise in learning about table joins. You'd be performing a "left join". You can join tables in virtually any programming language you'd like (including the shell).

Finally, although the above Qubit data file isn't the best example for what I'm about to say, please remember that the oldest sample measured in a set (i.e. the first sample you measure) is listed <em>last</em> in the Qubit data file.

**Comment by grace-ac** [comment]
Okay cool! Thanks - I'll try it out. 

And in regards to the Qubit order in the files, I am aware and have been extra careful to keep track with every file.
