### ISSUE TITLE
Assess Oly Methylation datasets 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#225]
Using Bismark / or related nextflow pipeline...

**Comment by kubu4** [comment]
What do you mean by "assess"?

**Comment by sr320** [comment]
Analyze.. determine differences in methylation across samples...

**Comment by kubu4** [comment]
Summary (notebook entry is forthcoming):

Ran TrimGalore on all seqs prior to Bismark.

Bismark default settings, plus:
- ```-u 1000000```
- ```--non-directional```

Genome (JPG): [pbjelly assembly](https://camo.githubusercontent.com/7784a3da24c28a81f416a4e68455c25bb6c33d9c/687474703a2f2f6f776c2e666973682e77617368696e67746f6e2e6564752f417468616c69616e612f32303138303131365f71756173745f6f6c795f617373656d626c6965732e706e67)

Might be worth re-running using assembly with fewer Ns.

---

#### [Whole genome BS-seq (2015)](https://github.com/RobertsLab/project-olympia.oyster-genomic/wiki/Whole-genome-BSseq-December-2015)

##### Prep overview

- Library prep: Roberts Lab
- Sequencing: Genewiz

|Bismark Report|Mapping Percentage|
|--------------|------------------|
| 1_ATCACG_L001_R1_001_trimmed_bismark_bt2_SE_report.txt |40.3% |
| 2_CGATGT_L001_R1_001_trimmed_bismark_bt2_SE_report.txt |39.9% |
| 3_TTAGGC_L001_R1_001_trimmed_bismark_bt2_SE_report.txt |40.2% |
| 4_TGACCA_L001_R1_001_trimmed_bismark_bt2_SE_report.txt |40.4% |
| 5_ACAGTG_L001_R1_001_trimmed_bismark_bt2_SE_report.txt |39.9% |
| 6_GCCAAT_L001_R1_001_trimmed_bismark_bt2_SE_report.txt |39.6% |
| 7_CAGATC_L001_R1_001_trimmed_bismark_bt2_SE_report.txt |39.9% |
| 8_ACTTGA_L001_R1_001_trimmed_bismark_bt2_SE_report.txt |39.7% |

---

#### [MBD BS-seq (2015) ](https://github.com/RobertsLab/project-olympia.oyster-genomic/wiki/MBD-BSseq-December-2015)

##### Prep overview

- MBD: Roberts Lab
- Library prep: ZymoResearch
- Sequencing: ZymoResearch

|Bismark Report|Mapping Percentage|
|--------------|------------------|
| zr1394_1_s456_trimmed_bismark_bt2_SE_report.txt |33.0% |
| zr1394_2_s456_trimmed_bismark_bt2_SE_report.txt |34.1% |
| zr1394_3_s456_trimmed_bismark_bt2_SE_report.txt |32.5% |
| zr1394_4_s456_trimmed_bismark_bt2_SE_report.txt |32.8% |
| zr1394_5_s456_trimmed_bismark_bt2_SE_report.txt |35.2% |
| zr1394_6_s456_trimmed_bismark_bt2_SE_report.txt |35.5% |
| zr1394_7_s456_trimmed_bismark_bt2_SE_report.txt |32.8% |
| zr1394_8_s456_trimmed_bismark_bt2_SE_report.txt |33.0% |
| zr1394_9_s456_trimmed_bismark_bt2_SE_report.txt |34.7% |
| zr1394_10_s456_trimmed_bismark_bt2_SE_report.txt |34.9% |
| zr1394_11_s456_trimmed_bismark_bt2_SE_report.txt |30.5% |
| zr1394_12_s456_trimmed_bismark_bt2_SE_report.txt |35.8% |
| zr1394_13_s456_trimmed_bismark_bt2_SE_report.txt |32.5% |
| zr1394_14_s456_trimmed_bismark_bt2_SE_report.txt |30.8% |
| zr1394_15_s456_trimmed_bismark_bt2_SE_report.txt |31.3% |
| zr1394_16_s456_trimmed_bismark_bt2_SE_report.txt |30.7% |
| zr1394_17_s456_trimmed_bismark_bt2_SE_report.txt |32.4% |
| zr1394_18_s456_trimmed_bismark_bt2_SE_report.txt |34.9% |

**Comment by sr320** [comment]
this would go to Methylkit to check for differences ...

**Comment by kubu4** [comment]
Full Bismark pipeline run on full data sets:

http://onsnetwork.org/kubu4/2018/08/16/dna-methylation-analysis-bismark-pipeline-on-all-olympia-oyster-bsseq-datasets/

Will start looking at data based on the two different experiments in MethylKit.

**Comment by kubu4** [comment]
Discussed with Steven last week. Will re-trim (just 10bp 5' end of reads), and change Bismark cutoff score. Jobs are queued on Mox (which is down for maintenance through 9/11/2018).

Then, will process with MethylKit and test out various coverage cutoff values.

**Comment by kubu4** [comment]
Bismark pipelines - two analyses:

- default settings

- "relaxed" bowtie2 settings

- http://onsnetwork.org/kubu4/2018/09/13/dna-methylation-analysis-olympia-oyster-whole-genome-bsseq-bismark-pipeline-comparison/

MethylKit analysis of both Bismark pipelines with various coverage cutoffs:

- http://onsnetwork.org/kubu4/2018/09/18/dna-methylation-analysis-olympia-oyster-whole-genome-bsseq-bismark-pipeline-methylkit-comparison/
