### ISSUE TITLE
Install Bismark on mox

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#226]
https://www.bioinformatics.babraham.ac.uk/projects/bismark/

**Comment by kubu4** [comment]
This is done. 

Note, currently you will have to specify the location of bowtie2 when you run bismark:

```--path_to_bowtie </../../bowtie(1/2)>```

OR, you can add bowtie2 to your system $PATH by adding the following to your ~/.bash_profile file:

```PATH=/gscratch/srlab/programs/bowtie2-2.1.0:$PATH```

After updating your ~/.bash_profile, you'll need to re-source the file OR log out of Mox and then log back in.

To source:

```source ~/.bash_profile```

Also, I just saw the issue regarding installing new version of bowtie2, so you'll want the $PATH to that version instead.
