### ISSUE TITLE
Data org. help

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#228]
I want to get the info from this [Qubit results spreadsheet](https://github.com/RobertsLab/project-crab/blob/master/data/Qubit-consolidated.csv) 
![screen shot 2018-04-26 at 11 42 54 am](https://user-images.githubusercontent.com/14934314/39325430-02bb4370-4947-11e8-9b7f-6dcbd9fd9c3c.png)

into this [subset of samples for RNA iso](https://github.com/RobertsLab/project-crab/blob/master/data/samples-for-RNA-isolation.csv) matching the tube numbers. 
![screen shot 2018-04-26 at 11 43 34 am](https://user-images.githubusercontent.com/14934314/39325465-1aaf7d16-4947-11e8-89d6-7889cb42c583.png)

**Comment by kubu4** [comment]
The first thing that needs to be done to enable programmatic joining of two tables is to have at least one column of date that is the same in both columns (e.g. Uniq_ID).

Currently, your Qubit dataset doesn't appear to have any columns that match any columns in your "subset of samples for RNA" dataset.

Update your Qubit dataset.

Post a response once you've made that change and we'll see what we can do.

**Comment by sr320** [comment]
Qubit direct link
`https://raw.githubusercontent.com/RobertsLab/project-crab/master/data/Qubit-consolidated.csv`

RNA table direct link
`https://raw.githubusercontent.com/RobertsLab/project-crab/master/data/samples-for-RNA-isolation.csv`

**Comment by grace-ac** [comment]
In both sheets, there is a column called "tube_number".

**Comment by sr320** [comment]
This R project should do it..
https://d.pr/f/VHcqS4

download and open R project - run code

**Comment by sr320** [comment]
Screencast of running through project 
https://d.pr/i/97iv7k

**Comment by sr320** [comment]
Though imagining you want to keep all of RNA table and just add qubit data where available you could just add the following code to the script

`crab_master <- left_join(RNA, qubit, by = "tube_number")`

**Comment by kubu4** [comment]
> In both sheets, there is a column called "tube_number".

Doh! You're right! Sorry!

**Comment by grace-ac** [comment]
Wow! So cool and easy! Thank you!
