### ISSUE TITLE
Things to pick up at Taylor tomorrow?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#23]
I'm going to Taylor Hatchery tomorrow to pick up the micro biome filters.... anything else there that's ours that I should grab?

**Comment by sr320** [comment]
Dewer
Filter housings
Oyster larval samples
Hobos

**Comment by grace-ac** [comment]
got everything except hobos. Didn't ask Rhonda where they were beforehand, and Benoit (spelling?) and I searched everywhere. Rhonda is on a trip right now, but we'll ask once she returns!

**Comment by grace-ac** [comment]
I put the micro biome filter samples (plastic bag) and the larval samples (2 boxes) on the bottom shelf of the left -80 freezer in FTR. 
![img_4256](https://user-images.githubusercontent.com/14934314/29691191-062b7f3a-88df-11e7-8484-2225a218c629.JPG)
![img_4255](https://user-images.githubusercontent.com/14934314/29691192-06327b64-88df-11e7-9f6f-f59cd978b683.JPG)

**Comment by sr320** [comment]
And added to spreadsheet? :)

**Comment by kubu4** [comment]
I'd also propose that all boxes should be in racks.

**Comment by grace-ac** [comment]
Yup! It all will be done tomorrow morning. i wasn't parked in a law-abiding way, so when i go in tomorrow i'll re-label the boxes and put them in their rack!

**Comment by sr320** [comment]
to confirm, these are not in racks and marked in inventory yet?

**Comment by grace-ac** [comment]
They are in racks and in the spreadsheet. The bag of filters is on the
bottom shelf in the left -80. Wasnt sure where to keep those.

**Comment by sr320** [comment]
The reason I ask is I am in the spreadsheet and the last edit appears to be in May

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/-80_Inventory_Map_-_Google_Sheets_1F58C29B.png" alt="-80_Inventory_Map_-_Google_Sheets_1F58C29B.png"/>

**Comment by grace-ac** [comment]
Okay - maybe i updated the wrong link. But this is the one I updated: https://docs.google.com/spreadsheets/d/13PIQP2g1DpGOLd_HNGru_IGkrKb3JfUdIBaih4XxMB8/edit#gid=0 

rack 13.

**Comment by sr320** [comment]
moved to https://github.com/RobertsLab/resources/issues/38
