### ISSUE TITLE
do we have a vga to lightning adaptor?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#230]
Wanted to check before purchasing if anyone knows of one?  

I need a vga to lightning adaptor to use monitor in grad student office. 

I found a vga to HDMi adaptor in conference room, but my laptop only has lightning. 

I found a vga to lightning adaptor on [amazon](https://www.amazon.com/gp/product/B019D0LS4E/ref=ox_sc_act_title_1?smid=ATVPDKIKX0DER&psc=1) for ~$12.

**Comment by sr320** [comment]
I doubt you mean lightning as this is for idevices..
But just order. We might have one in box of adapters in conference room.
