### ISSUE TITLE
anaconda not working on roadrunner

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#232]
Unable to load jupyter notebook, other programs on roadrunner. @kubu4 unable to run them as well

**Comment by sr320** [comment]
If this is MBD work - should run on laptop first with -u

or use mac mini in conf room..

**Comment by kubu4** [comment]
@yaaminiv - 

I've rebooted Roadrunner.

When you have the chance, please login, open Terminal and type the following:

```which jupyter```

Please post the output.

**Comment by kubu4** [comment]
@sr320 - The thought process was that it'd be faster to get started, since she wouldn't have to install any software; all the necessary software is (not?) ready to go on Roadrunner.

**Comment by yaaminiv** [comment]
@sr320 last time you said to start the pipeline on a subset of data using a linux machine!
@kubu4 I'm sitting at Roadrunner now but the screen just says "No Signal"...did I miss a step somewhere?

**Comment by kubu4** [comment]
Did switch to Roadrunner inputs (keyboard & monitor)?

**Comment by yaaminiv** [comment]
@kubu4 Yup.

**Comment by kubu4** [comment]
Hmmm, I was able to ssh in a few minutes ago. Not sure what to tell you atm.

**Comment by sr320** [comment]
>@sr320 last time you said to start the pipeline on a subset of data using a linux machine!

url or it did not happen 😄 


> @sr320 - The thought process was that it'd be faster to get started, since she wouldn't have to install any software

seems like that has been disproven at this point....

**Comment by yaaminiv** [comment]
@sr320 I'll move over to the mac mini in the conference room then
