### ISSUE TITLE
Unable to change working directory in Jupyter nbs

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#233]
I'm working from the Mac mini in the conference room and I'm unable to change my working directory in my [juypter nb](https://github.com/RobertsLab/project-virginica-oa)

![untitled](https://user-images.githubusercontent.com/22335838/39337694-307cb100-4973-11e8-9ca0-56b209769211.png)

It says the directory does not exist...but it definitely does!

![untitled](https://user-images.githubusercontent.com/22335838/39337732-63213e0a-4973-11e8-81a9-f223c40ded81.png)

How do I change my working directory?

**Comment by kubu4** [comment]
Pro tip: Use tab completion in notebook to help ensure things are being entered correctly.

To your issue, you may need an exclamation point before your cd command.

**Comment by yaaminiv** [comment]
@kubu4 I did use tab completion!

I was able to work around it, even without an exclamation point...

![untitled](https://user-images.githubusercontent.com/22335838/39337856-2049b156-4974-11e8-83d5-3fc1bdcaf5a8.png)
