### ISSUE TITLE
Trouble installing bismark/updating bowtie2

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#234]
I'm working on the Mac mini, which I see has `bowtie2` installed:

![untitled](https://user-images.githubusercontent.com/22335838/39388336-15e0da62-4a34-11e8-8d54-89920993ace9.png)

Based off of the [bioconda documentation](http://bioconda.github.io/recipes/bowtie2/README.html), I tried updating the package. I got this error:

![untitled](https://user-images.githubusercontent.com/22335838/39388364-4e970e08-4a34-11e8-82d1-db4cb6e99437.png)

I tried changing my directory to the one where `bowtie2` is installed, but that didn't help either:

![untitled](https://user-images.githubusercontent.com/22335838/39388444-df1825fc-4a34-11e8-99b9-29a3bb8e1e1d.png)

I'm having a similar problem trying to install `bismark`:

![untitled](https://user-images.githubusercontent.com/22335838/39388389-870c5388-4a34-11e8-8bec-8f8433e0007a.png)

How do I fix this?

**Comment by sr320** [comment]
Install Bismark via
https://www.bioinformatics.babraham.ac.uk/projects/bismark/

**Comment by kubu4** [comment]
Bowtie was probably installed independently, not with Anaconda. As such, Anaconda won't be able to update it.

**Comment by yaaminiv** [comment]
How can I go about updating it?

**Comment by kubu4** [comment]
Either install using Anaconda, (which should download and install most recent version) or download and install from Bowtie website

**Comment by sr320** [comment]
I would just install the latest version via conda
http://bioconda.github.io/recipes/bowtie2/README.html

or download source
https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.3.4.1/bowtie2-2.3.4.1-macos-x86_64.zip/download

**Comment by yaaminiv** [comment]
I tried downloading/updating using conda earlier in the issue! That didn't work, so I can download the source code. However, would it be better to figure out how to get the conda download to work?

**Comment by kubu4** [comment]
It looks like you only tried to update Bowtie via Anaconda, not install it.

**Comment by yaaminiv** [comment]
I did try installing it (see third image in first comment) but was unsuccessful.

**Comment by kubu4** [comment]
You have to specify the conda channel called bioconda.

The command would be:

conda install -c bioconda bowtie2

**Comment by sr320** [comment]
I prefer not to use conda
You have complete control by simple downloading and extracting....
and using full path to confirm version
