### ISSUE TITLE
gunzip error from bismark alignment

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#236]
I ran my Bismark alignment on a subset of the *C. virginica* OA samples yesterday

[Jupyter notebook](https://github.com/RobertsLab/project-virginica-oa/blob/master/notebooks/2018-04-27-Gonad-Methylation-Bismark.ipynb)
[Lab notebook post](https://yaaminiv.github.io/Gonad-Methylation-Analysis-Part5/)

`bismark` ran completely for each file, but I did get the following `gunzip` error each time:

![untitled](https://user-images.githubusercontent.com/22335838/39400283-7bd7621a-4ae2-11e8-9a72-f87846e757da.png)

What does this mean, and how do I fix it? My alignment outputs are in [this folder](https://github.com/RobertsLab/project-virginica-oa/tree/master/analyses/2018-04-27-Bismark).

**Comment by sr320** [comment]
You produced outputs- so no need to be concerned with message
