### ISSUE TITLE
Next steps in C.virg analysis

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#239]
I successfully completed all steps of `bismark` with a subset of my data.

[Jupyter notebook](https://github.com/RobertsLab/project-virginica-oa/blob/master/notebooks/2018-04-27-Gonad-Methylation-Bismark.ipynb)
Lab notebook: [Genome preparation](https://yaaminiv.github.io/Gonad-Methylation-Analysis-Part4/), [Alignment](https://yaaminiv.github.io/Gonad-Methylation-Analysis-Part5/), [Methylation Extractor and Report Generation](https://yaaminiv.github.io/Gonad-Methylation-Analysis-Part6/)

What are the next steps? Should I start to run the pipeline with the full extent of my sequencing data? How do I visualize all of the outputs?

**Comment by sr320** [comment]
Install methylkit and Macau (review manuals)

From Bismark - data such as aligned reads (in reports) should be described
- several graphs are generated

**Comment by yaaminiv** [comment]
For `bismark`: Should just look at .txt file/HTML reports, or should I also open .bam files?

**Comment by sr320** [comment]
You should be familiar with what all output files are and what they are
used for (see manual). Visualizing bedgraphs and bams has value.
