### ISSUE TITLE
Provide Illumina HQ Geoduck DNA 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#24]

**Comment by kubu4** [comment]
Ha! Just got done with a meeting with Stacy about this. Want to discuss isolation methodology with you (i.e. spend money on a kit or try "homebrew" salting out method).

I also need to find out from them how much DNA they will need.

**Comment by sr320** [comment]
Go money route if recommended

**Comment by kubu4** [comment]
Ugh, if we follow the suggested MagAttract protocol, we need a mixer from Eppendorf: $4000!

Waiting to hear back from Illumina to see how strict they're going to be about using that protocol for extraction.

**Comment by kubu4** [comment]
Well, it turns out that we'd still need that mixer from Eppendorf for ANY of the recommended 10x protocols!

If we follow the recommended protocol for DNA extractions from frozen tissue, the total cost for all the supplies is: $4342.30

:face_with_head_bandage:

**Comment by sr320** [comment]
See if Stacy can link us with a local core so you can use their 4k mixer,
we buy reagents.

**Comment by sr320** [comment]
Also Leche lab might have one - check with Jay

**Comment by kubu4** [comment]
@jldimond - Do you (or someone else's lab) happen to have access to an Eppendorf Thermomixer C (with 24 sample Thermoblock)?

**Comment by jldimond** [comment]
No, sorry. Could you just put a heating block on a shaker table? Sounds
like that's all it does?

**Comment by kubu4** [comment]
Ha! Essentially, yes, but needs 1400rpm. Plus, this is a protocol that we should follow rather strictly, so deviating from the protocol is not really an option. Thanks for checking & responding!

**Comment by kubu4** [comment]
Update - they will perform DNA isolation for us. Will send frozen geoduck tissue to them.
