### ISSUE TITLE
In situ pH from seacarb output

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#240]
@hputnam I was able to use your code in [my R script](https://github.com/RobertsLab/project-oyster-oa/blob/master/data/Manchester/Water-Chemistry-Data/2018-04-30-In-Situ-Variable-Calculations/2018-04-30-In-Situ-pH-Calculations.R) and generate table of carbonate chemistry parameters (see output [here](https://github.com/RobertsLab/project-oyster-oa/blob/master/data/Manchester/Water-Chemistry-Data/2018-04-30-In-Situ-Variable-Calculations/2018-04-30-In-Situ-Carbonate-Chemistry-Parameters.csv)). Since pH was an input to `seacarb`, it doesn't spit out an in situ pH! Is this something I would have to calculate using the HCO3 values? I'm a bit confused.

**Comment by hputnam** [comment]
@yaaminiv check to see if there are any small differences in pH between the tris calculation output and the seacarb output. The effect of salinity is likely to be very small if any.

**Comment by yaaminiv** [comment]
@hputnam Oh okay! And just to confirm: when I used Nyssa's script, I shouldn't change the salinity value there, and just compensate for salinity with your script?

**Comment by hputnam** [comment]
@yaaminiv the salinity value in that script is for the salinity of the Tris.

**Comment by yaaminiv** [comment]
@hputnam I went through the script again and realized that, but forgot to update my question in this issue. The value I used reflects the salinity of the Tris we used.
