### ISSUE TITLE
R script for creating subset file 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#244]
https://github.com/RobertsLab/project-crab/blob/master/data/20180502_seq_subset.csv

This file contains a column called "FRP" (unique crab ID number). The FRP number repeats depending on how many samples from that one crab had quantifiable RNA in the sample tube. 

I would like only the data from crabs that have three sample data points (three FRP number repeats).

**Comment by kubu4** [comment]
This'll do it:

```
# Read in file
crab_data <- read.csv("~/Downloads/20180502_seq_subset.csv", stringsAsFactors=FALSE)

# Pull out data where instances of a given FRP value are greater than or equal to three
crab_data[crab_data$FRP %in% names(which(table(crab_data$FRP) > 3)), ]

**Comment by sr320** [comment]
@kubu4 
When you get a chance, can you go into more detail about what 
`crab_data[crab_data$FRP %in% names(which(table(crab_data$FRP) > 3)), ]` 
is doing?

**Comment by kubu4** [comment]
See my edited comment! Fixed evaluation (which is VERY important)! Sorry!

I don't fully understand it, but here's some of it (working inside to outside):

```table()``` - A function designed to do the main task we want - count instances of values in a column. So, we specify the data frame and the column in the data frame (```table(crab_data$FRP)```) that we want to be counted.

```which()``` - An evaluation function. Takes output from the ```table()``` function and selects all those that have counts greater than or equal to 3.

```names()``` - Not entirely sure why this is needed, but pulls out the "names" of the individuals (in this case ```FRP```) resulting from our ```which()``` function. I think the names command must work with the ```%in%%``` (see below).

```%in%``` - This is similar to a ```select``` or ```join``` command. Takes values from the left side of the operand (in this case, the FRP column in our data frame) and matches any values on the right side of the operand (in this case, the list generated by ```names()```) - retains all rows from the data frame that have matches.

Then, the whole thing functions as a basic data frame subsetting (e.g. ```crab_data[rows,columns]```).

**Comment by grace-ac** [comment]
I'm not sure why, but I had to add "data.frame" in order for it to work for me. Maybe it doesn't matter, but this is what I had to change it to: (yaamini showed me this yesterday when we were doing subset stuff)   

crab_data <- data.frame(crab_data[crab_data$FRP %in% names(which(table(crab_data$FRP) >= 3)), ])

![r-script-right](https://user-images.githubusercontent.com/14934314/39606913-c4f4a1e8-4eec-11e8-9ba2-4b068e8c3d92.png)


![r-right](https://user-images.githubusercontent.com/14934314/39606915-c9f5f570-4eec-11e8-9723-b3189a6466f1.png)

**Comment by sr320** [comment]
I was thinking group by and summarize....

**Comment by kubu4** [comment]
I wanted to go that route initially, but couldn't quickly figure out how to
get counts of of individuals. Google yielded the answer I posted before I
could come up with a group by solution.

Curious to see if we can figure it out!

**Comment by grace-ac** [comment]
@kubu4 Here is a screenshot of what the file looked like when I ran the script that you gave without the "data.frame" thing:

![r-ex](https://user-images.githubusercontent.com/14934314/39607924-d0b992a8-4ef2-11e8-8aeb-f8ad26ef5a32.png)


Script:
![r-script](https://user-images.githubusercontent.com/14934314/39607933-d7d4d28c-4ef2-11e8-832c-6c80ee206723.png)

**Comment by kubu4** [comment]
That doesn't show the output from the code. Your ```View()``` function is looking at the original file that you read in, not the output of the code.

What I'm getting at is that I don't think you need the ```data.frame()``` because the output from the code is a data frame already. You can verify this by by wrapping the entire code in the ```str()``` function.

However, I think what you are wanting is to save the output of the code. So, as you implemented in your fix, you would need to assign the output of the code to a variable. But, I don't think the ```data.frame()``` dies anything in this instance.

**Comment by grace-ac** [comment]
ah, yes! that worked! no need for data.frame.

**Comment by sr320** [comment]
Better ?

```
library(dplyr)

#read in data
crabdata <- read.csv("https://github.com/RobertsLab/project-crab/raw/master/data/20180502_seq_subset.csv")


#create object that groups by FRP, summarizes by count, and filter for those with count > 2 
fullset <- group_by(crabdata, FRP) %>%
  summarize(count = n()) %>%
  filter(count > 2)

#create new table where join fullset with crabdata
goodstuff <- left_join(fullset, crabdata, by = "FRP")
```

**Comment by sr320** [comment]
well actually I can get in one line...

```
Mygoodsamples <- group_by(crabdata, FRP) %>%
  summarize(count = n()) %>%
  filter(count > 2) %>%
  left_join(crabdata, by = "FRP")
```

**Comment by kubu4** [comment]
Shortened up your dplyr code a bit: :smile: 

```
crabdata %>% 
  count(FRP) %>% 
  filter(n > 2) %>% 
  left_join(crabdata, by = "FRP")
```

Turns out, using ```count()``` implements ```group by``` and ```summarise``` automatically!

**Comment by sr320** [comment]
Nice! To me you can’t get more intuitive than this.
