### ISSUE TITLE
Full disk space on Mac mini

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#247]
I tried to run `bismark` on my full *C. virginica* data but I ran out of disk space before it finished aligning the last 3 files

![untitled](https://user-images.githubusercontent.com/22335838/39712444-ee17636a-51d7-11e8-92a2-f4149283890f.png)

Should I be saving these files directly to Owl?

**Comment by sr320** [comment]
There are likely plenty of files that can be deleted.

**Comment by kubu4** [comment]
I freed up ~170GB of space from defunct users, as well as my user account.

I did not dive into @sr320's account, nor the srlab account, as I'm not sure what's needed.
