### ISSUE TITLE
No index files for bismark output

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#248]
I'm trying to use IGV to look at the .bam files generated by `bismark` on a subset of my data. My data can be found [here](https://github.com/RobertsLab/project-virginica-oa/tree/master/analyses/2018-04-27-Bismark), and my IGV file can be found [here](https://github.com/RobertsLab/project-virginica-oa/blob/master/analyses/2018-04-27-Bismark/2018-05-07-Subset-Alignment.xml).

I loaded the *C. virginica* genome, but was unable to load any of my .bam data files. I got the following prompt, asking me for index files. However, `bismark` didn't generate any index files! How do I get them?

![untitled3](https://user-images.githubusercontent.com/22335838/39731644-a956194c-521d-11e8-8be8-fc6f3d78a447.png)

**Comment by sr320** [comment]
IGV
https://software.broadinstitute.org/software/igv/igvtools

**Comment by yaaminiv** [comment]
I'm getting an error ("Illegal State Exception") trying to run `igvtools` in both the GUI and the command line:

![untitled](https://user-images.githubusercontent.com/22335838/39767961-d6b085e2-529c-11e8-82ff-073a62e0e44c.png)

![untitled2](https://user-images.githubusercontent.com/22335838/39767962-d6c9f900-529c-11e8-9433-6fb10b84086a.png)

My input files are .bam files generated by `bismark`. Am I supposed to run the `sort` function before I use `index`?

**Comment by yaaminiv** [comment]
Update: read [this](https://software.broadinstitute.org/software/igv/igvtools_commandline) more closely, I do need to run `sort` first.

**Comment by kubu4** [comment]
Yep: http://software.broadinstitute.org/software/igv/bam

**Comment by sr320** [comment]
Yep

**Comment by yaaminiv** [comment]
I successfully ran the `sort` + `index` combo on one of my .bam files ([see Jupyter notebook](https://github.com/RobertsLab/project-virginica-oa/blob/master/notebooks/2018-04-27-Gonad-Methylation-Bismark.ipynb)). I want to write a line of code that will apply the `sort` command to all of the .bam files in my directory. I tried the code below, but that didn't work. Any tips?

> ! /Users/Shared/Apps/IGVTools/igvtools sort \
zr2096_*_bt2.bam \
zr2096_*_sort.bam

**Comment by kubu4** [comment]
If you're not too particular about naming, this is the quickest (i.e. least amount of brainpower for me to attempt):

```
%%bash
for bam in *.bam
do
/Users/Shared/Apps/IGVTools/igvtools \
sort \
"$bam" "$bam".sorted
done
```

**Comment by yaaminiv** [comment]
Hm...that didn't seem to produce any new sorted files.

**Comment by sr320** [comment]
It might be as simple as running deduplication in bismark as I am pretty
sure this sorts. (not possitive)

**Comment by kubu4** [comment]
> Hm...that didn't seem to produce any new sorted files.

What did it produce? Any errors? Can you update your Jupyter Notebook so I can see execution and output?

**Comment by yaaminiv** [comment]
@kubu4 My Jupyter notebook is updated! See the last 2 cells. I ran the command and there were no errors, or any output. I used the `ls` command in the cell below to see if it produced anything in my working directory and it did not.

**Comment by yaaminiv** [comment]
Based off of [this issue](https://github.com/RobertsLab/resources/issues/253), it seems `samtools` should be used for sorting and indexing instead of `igvtools`. I was able to use `samtools` to sort and index multiple files in [this Jupyter notebook](https://github.com/RobertsLab/project-virginica-oa/blob/master/notebooks/2018-04-27-Gonad-Methylation-Bismark.ipynb) using a combination of `find` and `xargs`.
