### ISSUE TITLE
Shellfish Tags 

### ISSUE THREAD

**Issue by MeganHintz** [RobertsLab/resources#25]
Purchase cattle tags for shellfish farm
Budget # 164900

Select "Large Panel Set Tag"
Quantity of sequential tags: **50**
beginning with: **1**
I want to include the letter: **U before** the above numbers
I want to include the second letter: **W before** the above numbers
*Check* Add zero's to the front of the tag numbers so that all tags have the same number of characters (the second option)
Tag Color: **yellow**
Custom Tag front:
2 text: **PROP OF UW**
4 text: **OYSTERS@UW.EDU**

I filed out the purchasing form the best I could
[Purchasing_Form_TAGS2.pdf](https://github.com/RobertsLab/resources/files/1252710/Purchasing_Form_TAGS2.pdf)

**Comment by MeganHintz** [comment]
@kubu4 how to I add the purchasing label?

**Comment by kubu4** [comment]
Look on the right side of the page. Click "labels". Note, that option is not visible on mobile.

**Comment by MeganHintz** [comment]
Labels (and other things) are visible but not clickable...

**Comment by sr320** [comment]
@MeganHintz 
Signed form
https://www.dropbox.com/s/hzbezzpa0agm110/Purchasing_Form_TAGS2%20%28signed%29.pdf?dl=0


[next step](https://github.com/RobertsLab/resources/wiki/Purchasing#SubmitRequest)

And remember to fill out Purchasing Log..

**Comment by MeganHintz** [comment]
@kubu4 added what I could, I'm not sure what type it is & will you add the reference number?

**Comment by sr320** [comment]
@MeganHintz  just add SAFS as type and price, and that will do it..
Thanks
