### ISSUE TITLE
Clarification on IGV use for bismark outputs

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#251]
Some clarification before I jump too far down this IGV rabbit hole...

I want to use IGV to understand the output from the `bismark` alignment step. I uploaded the one sorted and indexed file into IGV:

![untitled](https://user-images.githubusercontent.com/22335838/39771929-a7d67d7e-52a8-11e8-98ca-2c6a12f37c5b.png)

I don't really see anything...? I'm also not sure what I'm looking for.

Do I need to add my bedGraphs as well? Again, mainly confused because I haven't used IGV in years.

**Comment by sr320** [comment]
Read the screen
