### ISSUE TITLE
Deduplication error

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#252]
Using the same code from [Steven's lab notebook](https://github.com/sr320/nb-2018/blob/master/C_virginica/13-OAKL-fullpipe.ipynb) for `deduplicate_bismark`. Got the following error:

![untitled2](https://user-images.githubusercontent.com/22335838/39773435-f74a87ac-52ac-11e8-8763-c2962c8fcff6.png)

There is nothing in the help menu that says I need to specify a number for -p!

![untitled3](https://user-images.githubusercontent.com/22335838/39773495-2b836c5a-52ad-11e8-937a-0805a5b0dfeb.png)

Did I misinterpret something?

**Comment by yaaminiv** [comment]
Used wrong command. Clearly not thinking this morning.

**Comment by sr320** [comment]
Yep

**Comment by yaaminiv** [comment]
I have a REAL error this time

[Jupyter notebook](https://github.com/RobertsLab/project-virginica-oa/blob/master/notebooks/2018-05-04-Gonad-Methylation-Full-Samples-Bismark.ipynb)

![untitled4](https://user-images.githubusercontent.com/22335838/39774054-a54658f8-52ae-11e8-857a-85152955f4d1.png)

The files from the `bismark` alignment step are apparently not compatible with correct methylation extraction, and I need to use unsorted files instead...Is the --barcode argument something that can remedy this, or do I need to redo the alignment?

**Comment by sr320** [comment]
Likely because when you ran alignment you did not indicate paired-end reads

**Comment by sr320** [comment]
Also you should get in habit of writing standard error out to file so notebook can be viewed more readily.

**Comment by yaaminiv** [comment]
I assume this means I need to re-run my alignment?
