### ISSUE TITLE
sort: open failed error

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#253]
[Jupyter notebook](https://github.com/RobertsLab/project-virginica-oa/blob/master/notebooks/2018-04-27-Gonad-Methylation-Bismark.ipynb)

I want to sort my deduplicated.bam files using `sort` from `igvtools`. I'm using code similar to what's in [Steven's lab notebook](https://sr320.github.io/MethylKittens/).

I'm running into an error where `sort` is unable to open my files because there is no such file or directory. 

![untitled](https://user-images.githubusercontent.com/22335838/39788633-2f09f8e8-52e0-11e8-8e99-04b21d99006d.png)

The files are there! I can run the first half of the command (`find` + `xargs`) successfully. Also, my working directory is set to the directory with all of my deduplicated.bam files. How else can I specify the location of my file?

**Comment by sr320** [comment]
aka backslash

**Comment by yaaminiv** [comment]
I added the backslash! Not sure if `sort` actually worked though. I don't see any of my output files (deduplicated.sorted.bam) in my working directory.

![untitled](https://user-images.githubusercontent.com/22335838/39788962-dd4c36a4-52e1-11e8-84dc-60534731aaa1.png)

**Comment by sr320** [comment]
Big picture - I would use samtools sort (as I did :)
not sure igv sort can handle PE.

**Comment by yaaminiv** [comment]
I successfully used `samtools` to sort and index my .bam files! Thanks for the help
