### ISSUE TITLE
Error from unite in methylKit

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#254]
[R script](https://github.com/RobertsLab/project-virginica-oa/blob/master/analyses/2018-05-01-MethylKit/2018-05-01-MethylKit-Analysis.R)

I'm following [Steven's code](https://sr320.github.io/MethylKittens/) for `methylKit`. I was able to process my files with processBismarkAln, but using unite gives me this error:

> Warning message:
In max(i) : no non-missing arguments to max; returning -Inf

What am I missing?

**Comment by kubu4** [comment]
Do you need this part from Steven's notebook entry?

```
install_github("al2na/methylKit", build_vignettes=FALSE, 
               repos=BiocInstaller::biocinstallRepos(),
               dependencies=TRUE)
```

**Comment by yaaminiv** [comment]
> Do you need this part from Steven's notebook entry?

I just added that part in, and now the `processBismarkAln` function does not work!

**Comment by yaaminiv** [comment]
Update: realized the order of the commands was different from Steven's notebook. I changed it and am rerunning the code. Will see what happens

**Comment by sr320** [comment]
So You should understand every command... If not ask

**Comment by yaaminiv** [comment]
I still get the same error when I use `unite`:

![untitled](https://user-images.githubusercontent.com/22335838/39826201-c28231a2-5368-11e8-82cc-bd7aa934faf0.png)
![untitled 2](https://user-images.githubusercontent.com/22335838/39826202-c29a58a4-5368-11e8-9f93-98854fcb0297.png)

`processBismarkAln` worked fine and proceeded a methylRawList. I don't know why `unite` is unable to process it

**Comment by sr320** [comment]
Again - see if you can replicate my analysis with my files.

**Comment by sr320** [comment]
with my files?

**Comment by yaaminiv** [comment]
@sr320 What do you mean with your files? Your R script or your .bam files?

**Comment by sr320** [comment]
with my bam files / data

**Comment by yaaminiv** [comment]
Where can I find those files? Looking at your Jupyter nbs it looks like it's on your desktop...?

**Comment by sr320** [comment]
There is a set of sorted bams @
http://owl.fish.washington.edu/halfshell/bu-serine-wd/18-04-27/

**Comment by yaaminiv** [comment]
I used dedup.sorted.bam files 1 and 10 to test if `unite` worked in [this R script](https://github.com/RobertsLab/project-virginica-oa/blob/master/analyses/2018-05-01-MethylKit/2018-05-09-Steven-Test-Files/2018-05-09-MethylKit-Analysis-Steven-Test-Files.R). The script is identical to [the one I was using previously](https://github.com/RobertsLab/project-virginica-oa/blob/master/analyses/2018-05-01-MethylKit/2018-05-01-MethylKit-Analysis.R). The `unite` function worked! I was able to run through the entire script with no problems.

So now the question: what's different between my files and Steven's files? Here is the [Jupyter notebook](https://github.com/RobertsLab/project-virginica-oa/blob/master/notebooks/2018-04-27-Gonad-Methylation-Bismark.ipynb). I modeled my code after his. The one difference I can think of right off the bat is that I did not send my files through TrimGalore, while he did (I was told to ignore the TrimGalore step in an offline conversation...whoops). Would skipping this step be enough to prevent me from using the `unite` function?

**Comment by yaaminiv** [comment]
Another difference between my data and Steven's: I used a subset of first 10,000 reads, he used 1,000,000

**Comment by sr320** [comment]
likely that .. go ahead and move forward with full set.

**Comment by yaaminiv** [comment]
For the full set, should I run the data through TrimGalore?

**Comment by kubu4** [comment]
Trimmed data is here: http://owl.fish.washington.edu/Athaliana/20180411_trimgalore_10bp_Cvirginica_MBD/

**Comment by sr320** [comment]
use that
