### ISSUE TITLE
Categorizing/sorting in R

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#255]
I have this file: https://github.com/RobertsLab/project-crab/blob/master/data/goodsamples.csv

It contains all the good samples (20 ng/µL or more RNA). I am wondering if there is a way to sort the rows based on treatment (warm/cold/ambient) and infection status (0/ 1) so that I can more easily visualize what I have within each category. 

I hope that makes sense... I realize I could just write it down, but since I'm learning R, I thought I'd ask here.

**Comment by sr320** [comment]
raw link: https://raw.githubusercontent.com/RobertsLab/project-crab/master/data/goodsamples.csv

**Comment by grace-ac** [comment]
oh sorry, i always forget to use the raw

**Comment by sr320** [comment]
Here are some ways to get started

https://github.com/sr320/nb-2018/tree/master/misc/02-crab

**Comment by kubu4** [comment]
@sr320 - Just some fun learning with R; you don't need ```summarize()``` if you're using ```count()``` - summarize is built-in.

Example below produces same output as your command:

```
group_by(crab_big3, temperature_treatment) %>%
  count()
```

**Comment by sr320** [comment]
it would be good to plot in one graph.
This might take me a little longer.

**Comment by sr320** [comment]
some code for graphs

https://github.com/sr320/nb-2018/tree/master/misc/02-crab

**Comment by grace-ac** [comment]
1. Way to have y-axis include all numbers (i.e., not just 5 and 10) to make it easier to count?
------
2. So the crab in the warm treatment that has RNA for all three sample days is an UNINFECTED crab.

I also have two infected warm-treatment crabs (FRP 6210 and 6219 - in [seq_subset](https://raw.githubusercontent.com/RobertsLab/project-crab/master/data/20180502_seq_subset.csv)), not all three sample days for these crabs had RNA. 

Not sure if it's worth trying to figure out how to include in a visual, but just thought I'd share that.

**Comment by sr320** [comment]
1 is already in code... see bottom

**Comment by sr320** [comment]
I am not clear what else you are specifically asking

**Comment by grace-ac** [comment]
1. sorry - yes! 

2. Maybe too crazy to add to plot. -->

**only 3 warm treatment crabs survived whole experiment.**

In plot with R script, warm treatment crab is UNINFECTED.

I have two infected warm treatment crabs, but not every sample day had RNA. Picture is a table of what I have of those two infected warm treatment crabs :  
![img_1640](https://user-images.githubusercontent.com/14934314/39885120-ae6fb558-5440-11e8-84e6-4071299158c5.JPG)

**Comment by grace-ac** [comment]
Yes, I know. :) I guess I was mostly asking if it was worth the trouble to try to figure out how to include those from the other spreadsheet. 

I'll go back to other issue/make new and close this one.
