### ISSUE TITLE
Trim Geoduck RRBS libraries

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#260]
per Bismark recommendations

---

Technique | 5' Trimming | 3' Trimming | Mapping | Deduplication | Extraction
-- | -- | -- | -- | -- | --
RRBS | --rrbs (R2 only) | --rrbs (R1 only) | ⬜️ | ❌ | (--ignore_r2 2)

SPECIFIC LIBRARY/KIT NOTES

RRBS

RRBS is a specialised technique to only look at CpG rich regions of the genome by using the restriction enzyme MspI (please see this RRBS Guide for some more specifics regarding data processing). For reasons explained in the RRBS-guide, the second last position of all reads before reading into the Illumina adapter exhibits an artificially (not methylated) methylation state as a result of the end-repair reaction. The option --rrbs within Trim Galore removes 2 extra bases whenever adapter contamination has been detected. This 3' end trimming that needs to be carried out for single-end runs or Read 1 of paired-end libraries. Read 2 of paired-end libraries is however not affected by this 3' bias, but instead the first couple of positions on the 5' end of Read 2 suffer from the read-through problem as Read 1 (Read 2 is a mere copy of Read 1), so Read 2 needs to have the first 2 bp removed instead. As of the current development version of Trim Galore (v0.4.2_dev; 12/16/2016) the option --rrbs removes: - 2 bp from the 3' end of single-end and Read 1 of paired-end reads in addition to adapter contamination, and - 2 bp from the 5' end of Read 2 of paired-end reads

**Comment by kubu4** [comment]
Trimmed files are here (*.fq.gz):

- [20180514_geoduck_trimgalore_rrbs/](http://owl.fish.washington.edu/Athaliana/20180514_geoduck_trimgalore_rrbs/)

- [MultiQC Report](http://owl.fish.washington.edu/Athaliana/20180514_geoduck_trimgalore_rrbs/20180514_geoduck_trimmed_fastqc/multiqc_data/multiqc_report.html)

Notebook:

- [http://onsnetwork.org/kubu4/2018/05/16/trimgalorefastqcmultiqc-trimgalore-rrbs-geoduck-bs-seq-fastq-data/](http://onsnetwork.org/kubu4/2018/05/16/trimgalorefastqcmultiqc-trimgalore-rrbs-geoduck-bs-seq-fastq-data/)

Will run FastQC/MultiQC on pre-trimmed files for comparison. Will add to this issue when complete.

**Comment by sr320** [comment]
First 10bp and last bp still bother me.....

https://d.pr/i/7rfXiZ

**Comment by kubu4** [comment]
Yeah, I noticed that. But, if we (meaning any researcher performing NGS) always have to trim the first/last 10 -15bp, then why bother with the TrimGalore settings for specific sequencing types?

Would we expect some sort of bias that's related to the restriction digestions that could explain this?

**Comment by kubu4** [comment]
OMG! 

I ran this with the ```--non-directional``` setting (despite having caught and "fixed").

This is the incorrect setting, as the libraries _are directional_!

Going to restart.

:angry:

**Comment by kubu4** [comment]
Properly trimmed (_w/o_```--non-directional``` setting!) files are here (*.fq.gz):

http://owl.fish.washington.edu/Athaliana/20180516_geoduck_trimgalore_rrbs

MultiQC report:

http://owl.fish.washington.edu/Athaliana/20180516_geoduck_trimgalore_rrbs/20180516_geoduck_trimmed_fastqc/multiqc_data/multiqc_report.html
