### ISSUE TITLE
Error in methylation extractor

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#262]
[Notebook](https://github.com/RobertsLab/project-virginica-oa/blob/master/notebooks/2018-05-04-Gonad-Methylation-Full-Samples-Bismark.ipynb)
[error file](https://github.com/RobertsLab/project-virginica-oa/blob/master/analyses/2018-05-04-Bismark-Full-Samples/bme.err)

I'm following [Steven's code](https://github.com/sr320/nb-2018/blob/master/C_virginica/17-OAKL-fullpipe-mk.ipynb) but am unable to replicate the use of the methylation extractor. It's asking me to use an unsorted file, or a file sorted from `samtools`. However, Steven never got that error message! I can't figure out why I am.

**Comment by sr320** [comment]
Comparing your notebook and Steven's code.. there is big difference in step 1?
Bismark alignment...

![screen shot on 2018-05-12 at 03_30_25](https://user-images.githubusercontent.com/4442039/39956445-4fb53384-5595-11e8-8993-ff1aebe063c9.png)

**Comment by yaaminiv** [comment]
<img width="1013" alt="screen shot 2018-05-12 at 12 14 40 pm" src="https://user-images.githubusercontent.com/22335838/39960812-13e4ccb8-55de-11e8-90e4-0dc60fe5a135.png">

^That's the screenshot from the notebook I'm using.

I didn't include a score_min option, because we discussed using the default setting when I was running the alignment.

**Comment by sr320** [comment]
Switch over to DNR paper

**Comment by yaaminiv** [comment]
indexing was just so I can look at it in IGV later (if I wanted to)
sorting was something you did after deduplication. deduplication is not covered in the manual at all.

**Comment by sr320** [comment]
but I did not sort before methylation extractor - 
run methylation extractor on files that are not sorted

**Comment by yaaminiv** [comment]
but you did run `sort` before methylation extractor!

I used methylation extractor on unsorted files, which lead to the error I posted the issue for.

**Comment by sr320** [comment]
I tried to recreate here:
https://github.com/RobertsLab/project-virginica-oa/blob/master/notebooks/sr2_2018-05-04-Gonad-Methylation-Full-Samples-Bismark.ipynb

I did not get any errors.

**Comment by yaaminiv** [comment]
Well......I'm stumped. I can rerun the methylation extraction step in my notebook and see what happens.

**Comment by yaaminiv** [comment]
I still get an error and no bedGraphs:

![error](https://user-images.githubusercontent.com/22335838/40192079-2e4d2de2-59b8-11e8-91c8-dfcd1bd0ab99.png)

**Comment by yaaminiv** [comment]
Same notebook!

https://github.com/RobertsLab/project-virginica-oa/blob/master/notebooks/2018-05-04-Gonad-Methylation-Full-Samples-Bismark.ipynb

**Comment by sr320** [comment]
try running methyl extractor on deduplicated bams here:
https://github.com/RobertsLab/project-virginica-oa/tree/master/data/dignore

**Comment by yaaminiv** [comment]
It worked! What was the difference between the files?

**Comment by sr320** [comment]
Not sure.
I suggest running a new notebook from the beginning.

It is hard to trouble shoot if you use same notebook and indicate it still
does not work.
That is- differences cannot be identified.
