### ISSUE TITLE
Error installing package in R  

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#263]
I am trying to install rgdal
see below. 

Any tricks or suggestions  (I also tried from pull-down menu)

Do other get same error?

```
> install.packages("rgdal")

  There is a binary version available but the source
  version is later:
      binary source needs_compilation
rgdal 1.2-18 1.2-20              TRUE

Do you want to install from sources the package which needs compilation?
y/n: y
installing the source package ‘rgdal’

trying URL 'https://cran.rstudio.com/src/contrib/rgdal_1.2-20.tar.gz'
Content type 'application/x-gzip' length 1650449 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

* installing *source* package ‘rgdal’ ...
** package ‘rgdal’ successfully unpacked and MD5 sums checked
configure: CC: clang
configure: CXX: clang++
configure: rgdal: 1.2-20
checking for /usr/bin/svnversion... yes
configure: svn revision: 725
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘rgdal’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rgdal’
Warning in install.packages :
  installation of package ‘rgdal’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/z0/b4gwvpvx0zz2ml59qg9bbs7c0000gn/T/RtmpYqqUVv/downloaded_packages’
```

**Comment by kubu4** [comment]
Yep, I get this error on Ubuntu, too.

Here's a potential solution for Macs:

https://stackoverflow.com/a/37829420/3470742

**Comment by sr320** [comment]
this

```
install.packages('rgdal', type = "source", configure.args=c(
     '--with-gdal-config=/Library/Frameworks/GDAL.framework/Programs/gdal-config',
     '--with-proj-include=/Library/Frameworks/PROJ.framework/Headers',
     '--with-proj-lib=/Library/Frameworks/PROJ.framework/unix/lib'))
```

did not work

```
configure: gdal-config set to /Library/Frameworks/GDAL.framework/Programs/gdal-config
checking gdal-config exists... no
configure: error: gdal-config not found - configure argument error.
ERROR: configuration failed for package ‘rgdal’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rgdal’
Warning in install.packages :
  installation of package ‘rgdal’ had non-zero exit status
```

I am hesitant to try `brew` and `conda` solutions given students will have same issues.

**Comment by kubu4** [comment]
This answer might work (specifically, Steps 1 -3): https://stackoverflow.com/a/34336842/3470742

**Comment by kubu4** [comment]
Or, download and install the OSX binary?

https://cran.r-project.org/web/packages/rgdal/index.html

Link to actual file: 

- https://cran.r-project.org/bin/macosx/el-capitan/contrib/3.5/rgdal_1.2-20.tgz

**Comment by sr320** [comment]
Can you check to see if this installs on Windows?

**Comment by kubu4** [comment]
Never mind. There isn't a Windows executable - just a binary and I'm not going to try to figure out how to compile it.

**Comment by sr320** [comment]
This is surprising - I do not see any reference to issues on data carp site

**Comment by laurahspencer** [comment]
I have seen that question a couple times before when installing programs:

`Do you want to install from sources the package which needs compilation?
y/n:`

And when I said "yes" it didn't work for me, but when I said "no" the package installed and worked fine.

**Comment by sr320** [comment]
Will try - thanks

**Comment by sr320** [comment]
@laurahspencer Thanks! 
I think it worked on my Mac. 

@kubu4 I presume you indicated `y` in Windows attempts?

**Comment by kubu4** [comment]
Error message on Windows is different: 

```Warning in install.packages: package 'rdgal' is not available (for R version 3.5.0).```

**Comment by sr320** [comment]
I get similar error
`Warning message:
package ‘rgdal’ was built under R version 3.4.4 `

but it still seems to work

**Comment by kubu4** [comment]
The error message I posted above indicates that there's nothing to download and install; and, that is indeed the case. Nothing is downloaded/installed.
