### ISSUE TITLE
ID and order reagents / standards for Titrator

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#27]

**Comment by kubu4** [comment]
Have info from Hollie, but still need some clarification. She would like to chat sometime next week to go over this in more detail (she's currently busy in Canada).

**Comment by kubu4** [comment]
Will be on a call with her on the 14th (after your call with her). Will get full details then.

**Comment by sr320** [comment]
I have a called scheduled for the 11th

**Comment by kubu4** [comment]
Yep!

>... (after your call with her) ...

**Comment by sr320** [comment]
my point was I do not have a call on the 14th - just wanted to make sure
you had date correct.

**Comment by kubu4** [comment]
Haha! Thanks! Have it correctly on my calendar! Sorry!
