### ISSUE TITLE
Crab csv file will all crabs in experiment.

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#270]
Where is such a csv?

**Comment by grace-ac** [comment]
RAW csv link: [here](https://raw.githubusercontent.com/RobertsLab/project-crab/master/data/20180522-master-all-crabs-hemo.csv)

Contains FRP numbers from all crabs used in the experiment, including the ones that died along the way.

This is what we were working with yesterday and is copy and pasted from [Pam's excel](https://github.com/RobertsLab/project-crab/blob/master/data/20180125-NPRB-crab-sample-data.xlsx) file that she sent me tab "all crabs".

**Comment by sr320** [comment]
@grace-ac 

please confirm this file is accurate 
https://d.pr/f/fUpgJM

**Comment by sr320** [comment]
But everything else is correct?

**Comment by grace-ac** [comment]
Yes!

**Comment by sr320** [comment]
How about this one?
https://d.pr/f/fqFjpt

**Comment by sr320** [comment]
ftr this is what I did 

```
df <- prim_master %>% 
  group_by(FRP) %>% 
  mutate(grouped_id = row_number())

dfhack <- df %>% 
  spread(grouped_id, tube_no)
```
stuff in excel .....

and

stuff in excel .....

```
prim_master_00 <- filter(dfhack2, tube12 != ".")
```

**Comment by grace-ac** [comment]
yes that looks awesome!
