### ISSUE TITLE
consider gigas MBD bisulfite sequencing

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#275]

**Comment by sr320** [comment]
Awaiting DNA extractions - @yaaminiv can you get @kaitlynrm started on something related to this?

**Comment by yaaminiv** [comment]
@kaitlynrm Let's start extracting DNA Thursday morning! I can help when I'm not in class. I'll write up a protocol and post it here.

**Comment by sr320** [comment]
please put protocol here:
https://github.com/RobertsLab/resources/tree/master/protocols

and provide url here

**Comment by kaitlynrm** [comment]
Do you want me to pre-scrape any blocks @yaaminiv ?

**Comment by yaaminiv** [comment]
@kaitlynrm Not that I know of. If you and @kubu4 have time, could you take some of our old samples and run them on the Bioanalyzer? I'd like to know fragment lengths. The samples are in a box in the fridge and they have my name on them.

**Comment by yaaminiv** [comment]
Protocol can be found [here](https://github.com/RobertsLab/resources/blob/master/protocols/DNA-Extraction-from-Histology-Blocks.md)

Lysis method may be modified when I look at Qubit results later today.

@kaitlynrm, you can find the plan for tomorrow in [this lab notebook post](https://yaaminiv.github.io/Gigas-Broodstock-DNA-Extraction-Part7/).

**Comment by kubu4** [comment]
Heads up, Step 11 (cleaning Tissue Tearer) is not sufficient. 

If using ethanol, then it must be followed by flaming.

Alternatively, it should be placed in a 10% bleach solution for a few minutes, then rinsed in two sequential beakers of water. We have multiple Tissue Tearers, so the bleaching can be performed without slowing down the workflow too much - just use clean Tissue Tearer while one is bleaching.

**Comment by kaitlynrm** [comment]
It might be worthwhile to note that no more than 0.02 should be used as well.

**Comment by yaaminiv** [comment]
@kubu4 does the rinse have to be done with nanopure water, or just DI water?

**Comment by kubu4** [comment]
DI's fine.

**Comment by yaaminiv** [comment]
Final DNA yield (will update with Bioanalyzer results later today):

https://yaaminiv.github.io/Gigas-Broodstock-DNA-Extraction-Part9/

**Comment by yaaminiv** [comment]
This protocol seems promising for using MethylMiner with low amounts of starting DNA: https://www.tandfonline.com/doi/pdf/10.1080/15592294.2017.1335849

Thoughts? @kubu4 I know you also mentioned a Qiagen kit that could be good for low starting volumes?

**Comment by kubu4** [comment]
Yes, there should be a Qiagen bisulfite conversion kit (and library prep?) that accepts low quantities of input DNA. Don't know what it's called; you'll have to investigate.

**Comment by yaaminiv** [comment]
Is it their EpiTect kit? 

https://www.qiagen.com/us/shop/epigenetics/epitect-fast-bisulfite-conversion-kits/#productdetails

**Comment by kubu4** [comment]
That's the one!

**Comment by yaaminiv** [comment]
Would it be better to use the Qiagen kit or try and adapt the low-input protocol in the paper I linked above? I couldn't find any information in the Qiagen protocol about being able to use the low input DNA methods for downstream sequencing applications.

**Comment by yaaminiv** [comment]
Recap from yesterday's lab meeting (correct me if I'm wrong): it's probably best to use the Qiagen kit. @kubu4 will ask Zymo how much input DNA they need for bisulfite library preparation and sequencing/how much input DNA they take in general. Based on what we hear from Zymo I can order the necessary kits/process my extracted DNA

**Comment by kubu4** [comment]
Heard from Zymo tonight:

Preferred minimum: 50ng

Absolute minimum: 1ng - no QC and can't guarantee libraries and sequencing results

They do _not_ accept bisulfite-converted DNA

**Comment by yaaminiv** [comment]
The consensus is that I could do MBD with my samples and get more than the absolute minimum of 1ng for each of my samples.

I could also look into enzyme-based methods. Any suggestions on where to start there?

**Comment by yaaminiv** [comment]
From my understanding, I would need to first use the MethylMiner kit to enrich methylated sequences, then the EpiTect kit for bisulfite conversion. The MethylMiner kit usually as a 1% yield.

The smallest DNA extraction yield I had was 282 ng, and 1% of that would be 2.82 ng. That is still more than the input volume for the EpiTect kit, and above Zymo's absolute minimum. Is there anything else I'm forgetting to consider with this workflow?

Sam's last comment says that Zymo does not accept bisulfite-converted DNA...does this mean we can't use Zymo for sequencing?

**Comment by kubu4** [comment]
You'll also be constructing the libraries, so you'll need to look into
library kits, too. Then, we can send libraries anywhere for sequencing.

**Comment by yaaminiv** [comment]
@kubu4 Something like [this](https://www.zymoresearch.com/pico-methyl-seq-library-prep-kit-2)? Looks like it will accept the low volumes I have

**Comment by kubu4** [comment]
Either one will get the job done.

**Comment by sr320** [comment]
What have we used in the past?. How were your gonad libraries made?

**Comment by yaaminiv** [comment]
@sr320 Gonad libraries were made with the Pico Methyl-Seq Library Prep Kit (first link). Leaning towards using that again.
