### ISSUE TITLE
Trouble pushing Github commits?

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#276]
I've tried pushing a Github commit I made three days ago to the project-virginica-oa repository both using the command line and Github desktop on genefish. Each time I try, I have to wait hours before the remote connection is dropped and I am unable to sync anything. Is there something I'm missing here? I've never had a problem with Github before!

**Comment by kubu4** [comment]
Screenshot of failed command(s)/error message(s), please.

What happens when you try to pull? Same thing?

Can you connect to the internet using a web browser?

**Comment by yaaminiv** [comment]
I thought I had a screenshot of the failed command but I don't...I'm trying once more to sync on Github Desktop so if/when that fails I'll post a screenshot.

I haven't tried to pull. I'm assuming I cannot do that while I'm trying to push something?

I can connect to the internet!

**Comment by grace-ac** [comment]
"Fetch origin" on Github Desktop pulls from GitHub! You can do this while you have a commit you're trying to push

**Comment by yaaminiv** [comment]
@grace-ac I think that's the newer version of Github Desktop! The one I'm using doesn't have that option.

**Comment by kubu4** [comment]
> I can connect to the internet!

OK, guess we can rule that out as the source of the problem.

> I'm trying once more to sync on Github Desktop so if/when that fails I'll post a screenshot.

Also run on command line, please.

> while I'm trying to push something

> while you have a commit you're trying to push

I'm not entirely sure I follow what you two are saying here. 

If you're saying that you're literally waiting for a push command to finish executing, then no, you cannot pull at that time.

However, outside of that (normally) very short window of time, you can pull any time you want.

With that said, I've found that the best time to pull is when you first sit down at the computer that you're going to be working on. This will minimize any weird merging stuff that will happen if you pull after you've made some local commits on your computer.

**Comment by kubu4** [comment]
Also, can you please post screenshot of local repo contents and their file sizes?

Via the command line:

```ls -lh```

**Comment by yaaminiv** [comment]
@kubu4 I will also try the command line when the Desktop finishes (it's been 2 hours at this point so I'm not sure how much longer I need to wait). I don't (and cannot) pull when I'm waiting for a push command to execute, and I too pull before I do any work to ensure there aren't any merge conflicts.

![untitled2](https://user-images.githubusercontent.com/22335838/40688487-2413db06-6353-11e8-88b0-a678bfa0ce68.png)

**Comment by kubu4** [comment]
> (and cannot) pull when I'm waiting for a push command to execute

Correct.

> it's been 2 hours at this point so I'm not sure how much longer I need to wait)

Kill it. It should sync in seconds. If it takes more than a minute, then something is wrong and there's no need to wait.

Can you please post link to GitHub repo?

**Comment by yaaminiv** [comment]
Just killed Github Desktop.

Repo: https://github.com/RobertsLab/project-virginica-oa

**Comment by yaaminiv** [comment]
du: illegal option -- -
usage: du [-H | -L | -P] [-a | -s | -d depth] [-c] [-h | -k | -m | -g] [-x] [-I mask] [file ...]

**Comment by kubu4** [comment]
Change to:

 ```du -ah```

Or, maybe better, redirect the output of that command to a temporary file and then put the temporary file on Owl or something where you can post a link? The output might be kinda long for copying/pasting/screenshotting.

Example:

```du -ah > ~/Downloads/tmp.txt```

**Comment by yaaminiv** [comment]
https://github.com/yaaminiv/yaaminiv.github.io/blob/master/presentations/tmp.txt

**Comment by kubu4** [comment]
The problem is that you are trying to push files that are too large. 

GitHub has a file size limit of 100MB. You have many, many files that exceed this limit. My inclination would be that these files are causing your issues.

See the RobertsLab code wiki for info on ignoring file sizes >100MB. There should be something in there on how to add these files to your ```.gitignore``` file.

However, since you've already committed, your ```.gitignore``` file won't actually honor your request. You'll have to perform an additional step to have your git repo "forget" about your files. @laurahspencer just had to recently do this. Maybe she'll remember off the top of her head? I'll try to find the explanation and post here when I do.

**Comment by kubu4** [comment]
OK, here's the process:

1. Update ```.gitignore``` file to skip files >100MB

2. ```git rm -r --cached .```

3. ```git add .```

4. ```git commit -am "Remove ignored files"```

**Comment by yaaminiv** [comment]
@kubu4 Darn I thought I already caught all of the files that were larger than 100MB and added them to the `.gitignore`! So I would go through the process above, then try pushing my commits?

**Comment by yaaminiv** [comment]
Alternatively, could I just undo my commit...?

**Comment by sr320** [comment]
Yes- you should also be able to undo commit in Desktop- ignore, then commit

**Comment by yaaminiv** [comment]
Undid my commit in Github Desktop, added files to my `.gitignore`, and then successfully committed and pushed files.

@kubu4, when would I have to use the process you outlined? Would that be if I were working solely in the command line?

**Comment by sr320** [comment]
Yes that was command-line solution
