### ISSUE TITLE
Claire's notebook for bedtools?

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#278]
@sr320 I found Claire's [bioRxiv preprint](https://www.biorxiv.org/content/biorxiv/early/2015/03/13/012831.full.pdf) that broadly describes the `bedtools` methods I need to use for the *C. virginica* data. However, I can't find the Jupyter notebook associated with this analysis! Where can I find it?

**Comment by sr320** [comment]
In references: Olson C, Roberts S. https://github.com/che625/olson-ms-nb.
GitHub. (2015).

also see:
https://github.com/sr320/nb-2018/blob/master/C_virginica/21-Bedtools.ipynb
