### ISSUE TITLE
Computer for titrator?

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#28]
We'll want a computer for the titrator. Presumably, the laptop that's currently at Manchester will be the primary/dedicated computer for this. Do we want to bring the laptop back over to SAFS for getting the titrator set up and tested or do we want to acquire a new computer (this same computer could be used for the Opticon/NanoDrop)?

**Comment by sr320** [comment]
New computer

**Comment by kubu4** [comment]
Found computer (~$550). Which budget(s)?

**Comment by sr320** [comment]
61-0221
