### ISSUE TITLE
Understanding bash commands

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#281]
I'm going through [Steven's `bedtools` Jupyter notebook](https://github.com/sr320/nb-2018/blob/master/C_virginica/21-Bedtools.ipynb) and I'm a bit confused about the following command:

> !/Applications/bioinfo/bedtools2/bin/intersectBed \
-wb \
-a R/0510/analyses/dml05251200.bed \
-b data/ref_C_virginica-3.0_Gnomon_mRNA.gff3 \
| cut -f $14 | cut -f8 -d$";" | cut -f2 -d$"=" | head

I understand everything but the last row. The [code document](https://github.com/RobertsLab/code/blob/master/bash.md#count-the-number-of-instancesoccurrences-of-items-in-a-column-in-a-file) explains what `cut -f` is, but what is `d$";"` or `d$"="`? Is that specifying some kind of delimiter?

**Comment by sr320** [comment]
see
https://explainshell.com/explain?cmd=cut+-f+%2414+%7C+cut+-f8+-d%24%22%3B%22+%7C+cut+-f2+-d%24%22%3D%22+%7C+head

**Comment by kubu4** [comment]
> Is that specifying some kind of delimiter?

Yes. However, I don't understand the use of ```$``` in any of that command.

What happens if you run it w/o the various ```$```?

The link @sr320 posted doesn't really clear that aspect of things up.

**Comment by kubu4** [comment]
Interestingly, the explainshell.com seems to be confused by the use of the ```$```.

However, I did find out what the usage is (but, don't understand the explanation, nor the usage in your example): https://unix.stackexchange.com/questions/48106/what-does-it-mean-to-have-a-dollarsign-prefixed-string-in-a-script/48122#48122

The link I posted above does _not_address the usage of the ```$``` in this part of the command: ```cut -f $14```.
