### ISSUE TITLE
Port Whitney OA System specs 

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#282]
@sr320, Brent & Sam (GitHub usernames?); can you provide any of the following system specs from Point Whitney?   

- Flow rate to tanks   
- Frequency of pH reading that controls solenoid (e.g. reading every 90 seconds, if above set point injection occurs)  
- Length of time solenoid was open for each injection   
- Seawater filtration method/size (e.g. sock filtered to 5um, UV filtered)  
- APEX system specs, or separate pH, T and salinity probe make/model if applicable  
- Approximate volume of conical tanks   
- Any other pertinent specs regarding the CO2 system?  E.g. back on line pressure?  
- To confirm - pH probes were calibrated via standards that came with the APEX system?

**Comment by sr320** [comment]
@SamGurr do you have this information?

**Comment by kubu4** [comment]
@laurahspencer - See 3/9/2018 Drs. Foster & Smith on purchasing log for APEX system info (catalog numbers you can use to look on Drs. Foster & Smith website for product info).

**Comment by laurahspencer** [comment]
Here's info that Sam G. emailed me: 

Flow rate = 0.8 L per min (this likely changed for Sam's project)
SW Filtered to 0.5um and UV 
Conical tank volume = 300L
All APEX sensors calibrated with with the standards by APEX

Remaining info needed: pH control settings - if there are any pertinent details, such as frequency/duration of CO2 injections

**Comment by SamGurr** [comment]
I am sending the raw data from 20180601 now to your email.

**Comment by kaitlynrm** [comment]
I'm going to close this now. I'll be up at Port Whitney this week if there is anything else you need @laurahspencer.
