### ISSUE TITLE
Budget # for few more histology cassettes

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#283]
@sr320 I have a few more gonad samples in cassettes to get processed, estimated cost $250.  Budget #? 

@kubu4 - just to confirm, I left the box nearly ready to be shipped in the 213 fridge. It's not yet sealed, since the order form (which is inside the box) needs the budget # and return shipping account info.  Thank you!

**Comment by sr320** [comment]
65-2861

**Comment by kubu4** [comment]
Sent.
