### ISSUE TITLE
Location of C. virginica bed files

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#287]
Where on Owl can I find the following files? I want to identify the location of DMLs in the genome.

ref_C_virginica-3.0_Gnomon_exon.bed
ref_C_virginica-3.0_intron-mrna.merged.bed
ref_C_virginica-3.0_Gnomon_mRNA.gff3
Cvirg_v3_CG-motif.bed

@sr320

**Comment by sr320** [comment]
See
https://github.com/RobertsLab/resources/wiki/Genomic-Resources

**Comment by sr320** [comment]
Will get CG file posted later tonight
