### ISSUE TITLE
Confusion about DML-exon and DML-mRNA overlaps

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#288]
In this [Jupyter notebook](https://github.com/RobertsLab/project-virginica-oa/blob/master/notebooks/2018-06-11-DML-Analysis.ipynb) I identified overlaps between DMLs and exon and mRNA feature tracks using `intersectBed`. I noticed that there are more exon overlaps than mRNA overlaps, which doesn't make sense to me. Did I miss a step before using `intersectBed`? I also don't understand the difference between the exon and mRNA tracks. Wouldn't they feature the same chromosomes/start and stop positions?

**Comment by sr320** [comment]
Look at them in iGV

**Comment by yaaminiv** [comment]
![untitled](https://user-images.githubusercontent.com/22335838/41305790-df10c4fc-6e28-11e8-887a-16b85be4a7e1.jpg)

The mRNA track includes introns and exon, while the exon track is just exons! That distinction makes sense.
