### ISSUE TITLE
DML analysis: Step after locating DMLs

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#289]
[Jupyter notebook](https://github.com/RobertsLab/project-virginica-oa/blob/master/notebooks/2018-06-11-DML-Analysis.ipynb)

I identified overlaps between DMLs and exons, introns, mRNA, and CG motifs, and wrote out the overlaps at .txt files. I assume the next step has to do with finding GO terms associated with the mRNA and exon overlaps?

**Comment by sr320** [comment]
You should see how many (proportion) of CG motifs intersect with exons, introns, mRNA.

Determine the DMLs and CGs motifs that are within 1000 bp mRNAs

Perform enrichment analysis to determine if functional gene categories are predominant. 

Be sure to read the Olson biorxiv paper

**Comment by yaaminiv** [comment]
> You should see how many (proportion) of CG motifs intersect with exons, introns, mRNA.
I have the number of intersections, so I'm assuming it's just a simple proportion: # intersections/# CG-motifs

> Determine the DMLs and CGs motifs that are within 1000 bp mRNAs
Would I use the -iobuf argument with `intersectBed` to do this?

> Perform enrichment analysis to determine if functional gene categories are predominant.
I have a .txt file with mRNA and DML overlaps. Would I enrich the gene categories in this document? Would I use DAVID?

>Be sure to read the Olson biorxiv paper
Read the paper! Just needed some more clarification on the methods not present in [her notebook](https://github.com/che625/olson-ms-nb/blob/master/BiGo_dev.ipynb).

**Comment by sr320** [comment]
Yes - you should compare proportions of CG intersect with DML overlap.

not sure. Try and see.

I would explore several enrichment options including R packages specific for this

Let me know what specific clarification you might need
