### ISSUE TITLE
Purchasing help

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#29]
It appears the labels can only be purchased using a credit card or PayPal.
How do I go about ordering these if I'm supposed to use a budget number? 

![screen shot 2017-08-28 at 10 13 20 am](https://user-images.githubusercontent.com/14934314/29784750-148b9328-8bda-11e7-97a3-129174bc45a5.png)

**Comment by kubu4** [comment]
Fill out the SAFS Purchasing form and submit to Lisa Smith in the main SAFS office (FSH 116).

It's likely you'll have to email her a copy of the design that you want printed for this order.

**Comment by grace-ac** [comment]
Oh, ok. I didn't understand that Lisa is the one that does the actual purchasing.

**Comment by kubu4** [comment]
Yep, that's Step 3 in the SAFS Purchasing on the [Purchasing wiki](https://github.com/RobertsLab/resources/wiki/Purchasing).

Thanks for the feedback. Will clarify this on Purchasing wiki!

**Comment by kubu4** [comment]
@grace-ac - If this issue is resolved, please close it when you have a sec. Thanks!
