### ISSUE TITLE
Skyline Q for Yaamini

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#290]
@yaaminiv 
**Should all four files be listed for every protein?**     

I have four oyster seed samples (tabs). Each sample has four RAW files associated with it. 

For some proteins, only a few of the four files are listed: 
![2files](https://user-images.githubusercontent.com/14934314/41321747-2b3dfada-6e5a-11e8-9086-ccfd1e967f32.jpg)

For other proteins, all four files are listed:
![allfiles](https://user-images.githubusercontent.com/14934314/41321754-345e001a-6e5a-11e8-9304-11f2931ea40a.jpg)

**Comment by yaaminiv** [comment]
If some of the files aren't listed for protein, I'd assume that protein was not detected in that sample. That could be confusing to keep track of with the replicate view you're using. I generally look at all files at once.

**Comment by grace-ac** [comment]
How would I do that?

**Comment by grace-ac** [comment]
Wait, never mind. Let me see if I'm on the verge of figuring this out

**Comment by grace-ac** [comment]
close for now- may re-open or create new issue.
