### ISSUE TITLE
Methods for gene flanking in bedtools

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#291]
Based on [this issue](https://github.com/RobertsLab/resources/issues/289), I need to identify DMLs and CG motifs within 1000 bp of mRNA. Here's how I see that working:

1. Use [`flank`](http://bedtools.readthedocs.io/en/latest/content/tools/flank.html) in `bedtools` to add 1000 bp to each chromosome in the mRNA gff in each direction
2. Use `intersect` to find overlaps between DMLs and CG motifs and write the output as a .txt file
3. Compare the above .txt files with .txt files previously generated to find differences (not actually sure how effective this step would be)

Is there another workflow I should use instead?

**Comment by sr320** [comment]
Yes! flank will create new track - use intersect to see which / what proportion of DMLs and CG intersect.

Once you have intersects of DMLs and CGs with all the tracks lets chat about how to compare.
(I will be on campus Friday)

Reminder any enrichment analysis of DMLs that intersect each track would be useful

**Comment by yaaminiv** [comment]
Enrichment analysis of DMLs that intersect with mRNA, correct?

**Comment by sr320** [comment]
And exon and intron separately.

And for those DMLs that fall into flanking area, determine the flanking
gene and respective enrichment (at least description of those).

**Comment by yaaminiv** [comment]
How would I know what genes the exons or introns correspond to? Do I need to merge my overlap document with the mRNA gff?

**Comment by sr320** [comment]
Yes
