### ISSUE TITLE
GOterms for C. Virginia genome?

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#292]
Is there a list of GOterms and associated genes for the *C. virginica* genome I can use for gene enrichment analyses? I'm using `topGO` in [this script](https://github.com/RobertsLab/project-virginica-oa/blob/master/analyses/2018-06-11-DML-Analysis/2018-06-14-Gene-Enrichment-Analysis.Rmd), and the input needs to have GOterms according to [this manual](https://bioconductor.riken.jp/packages/3.3/bioc/vignettes/topGO/inst/doc/topGO.pdf) and [this blog post](http://avrilomics.blogspot.com/2015/07/using-topgo-to-test-for-go-term.html).

**Comment by sr320** [comment]
I do not think so, It might involve blasting against uniprot and getting those associated GO terms

**Comment by yaaminiv** [comment]
I was looking into R packages, and [`org.Hs.egGO2ALLEGS`](http://bioconductor.org/packages/release/data/annotation/manuals/org.Hs.eg.db/man/org.Hs.eg.db.pdf) from the package seems promising, assuming I have entrez gene IDs? Is blast the better option?

**Comment by sr320** [comment]
also look at the genome feature tracks in NCBI - they might have GO info....

I think entrez gene ID information is in some of the genome feature tracks on NCBI

**Comment by yaaminiv** [comment]
Is the Entrez Gene ID the same as the Gene ID provided by NCBI in the mRNA track? If so, then I have it. It might be easier just to use `blast2go` because (I think) I understand that manual better than the R package's manual.

Also where can I find the genome feature tracks on this website? https://www.ncbi.nlm.nih.gov/genome/398

**Comment by sr320** [comment]
Not sure on IDs, 

GFF link at top left 
also @ 
ftp://ftp.ncbi.nlm.nih.gov/genomes/Crassostrea_virginica/GFF/

see also https://github.com/sr320/nb-2018/blob/master/C_virginica/18-OAKL-DML-genelist.ipynb
for break out

**Comment by yaaminiv** [comment]
According to [this link](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3013746/) Entrez is NCBI's gene ID, so that solves that issue.

How do I figure out if there are GOterms within that GFF? I'm very confused...

**Comment by sr320** [comment]
open the GFF and look?

ie 
`grep "GO"`

**Comment by sr320** [comment]
I do not really see any GO info
https://d.pr/i/0zVLn9

**Comment by yaaminiv** [comment]
There are no GOterms in the GFF, so I'll need to use a different method. 
![untitled](https://user-images.githubusercontent.com/22335838/41442189-d1d4867a-6fea-11e8-9db3-f9188bf17e7d.png)

Is `blast2go` my best bet?

**Comment by sr320** [comment]
I would try whatever you can

**Comment by yaaminiv** [comment]
Turns out the IDs in the genome aren't Entrez IDs. The IDs aren't official IDs, so they aren't Entrez IDs. There doesn't seem to be a way to get GOterms without Entrez IDs using an R package. Haven't dug around into `blast2go` too much yet, but it seems like the command line interface can only be accessed with a Pro subscription.

**Comment by yaaminiv** [comment]
Should I just use DAVID for gene enrichment at this point?

**Comment by sr320** [comment]
Sure - this would require blastp that would get GO terms and Gene IDs so
you could also use these R packages once blast is done.

**Comment by yaaminiv** [comment]
To clarify:

1. Use blasts to get Gene IDs and GOterms
2. Perform enrichment (either with R packages or DAVID)

**Comment by sr320** [comment]
Note there are several identifiers that could be used for DAVID.
could be worth seeing if any in GFF are useable

![image](https://user-images.githubusercontent.com/4442039/41452115-1783d862-7025-11e8-8bc5-fd7046dc0fff.png)

**Comment by yaaminiv** [comment]
I used some of the IDs in the GFF (LOC111124802, 111124802), said I was "Not Sure" about what type of ID it was and got this:

![untitled](https://user-images.githubusercontent.com/22335838/41479698-de1571a6-7080-11e8-8cd0-3a814d2a621c.png)

![untitled2](https://user-images.githubusercontent.com/22335838/41479699-de29b940-7080-11e8-8ee5-9610b347213c.png)

I got the same result when I used XM_022468004 as a Genbank Accession. There are no other ID types in the GFF.

I guess I do need to use `blasts` first.

**Comment by yaaminiv** [comment]
Wait...I would use `blastx` because my input query is DNA, right?

**Comment by sr320** [comment]
You could, but if there is a common ID (which I would presume there is)
blastp could also work.

**Comment by yaaminiv** [comment]
Opening this again because I have the same question I did a year ago...

I was able to annotate my DML list with associated genes, gene IDs, Genbank IDs, and Uniprot Accession codes (lab notebook [here](https://yaaminiv.github.io/DML-Analysis-Part37/), master annotation table [here](https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2018-12-02-Gene-Enrichment-Analysis/2019-06-20-Master-DML-Annotation.csv). I would like to describe gene functions DML are in by grouping together GOterms. How do I go from Uniprot Accession to GOterms? I know DAVID is an option, but are there any other methods? @shellytrigg and @kaitlynrm  you did this recently, right?

**Comment by kubu4** [comment]
You can also "manually" get them by using the web-based Uniprot accession mapping tool:

https://www.uniprot.org/uploadlists/

After the initial ID mapping, you can then use checkboxes on the subsequent page to include GO terms. Then, you resubmit it and it will update. Then, you can download a text file representing the updated data.

**Comment by yaaminiv** [comment]
@kubu4 Thanks! Reviewing the comments above, is there a way to use `blastp` to match Uniprot Accession codes with GOterms?

**Comment by shellytrigg** [comment]
Here's how I did BLASTp with protein sequences to a Uniprot database that contains Uniprot accession codes and GO terms. https://shellytrigg.github.io/40th-post/

**Comment by kubu4** [comment]
You'd run `blastp` against a SwissProt BLAST db. These are available from NCBI and/or SwissProt. This would give you the SwissProt IDs for doing the Uniprot mapping thing.

**Comment by yaaminiv** [comment]
@shellytrigg Looking code how, I see you combined your `blastp` output with Uniprot codes with a different file. 

```
#combine Uniprot annotations with BLAST'd proteins
!awk -F"\t" 'NR==FNR{a[$1]=$0;next}{print $0"\t"a[$2]}' \
/Users/strigg/Desktop/gigas_blastP_uniprot/uniprot-reviewed%3Ayes.tab \
/Users/strigg/Desktop/gigas_blastP_uniprot/all_giga-uniprot-blastP-out.nopipe.placeholder.tab \
> /Users/strigg/Desktop/gigas_blastP_uniprot/all_giga-uniprot-blastP-out.nopipe.annotations.tab
```
What is `/Users/strigg/Desktop/gigas_blastP_uniprot/uniprot-reviewed%3Ayes.tab`? I assume that one has GOterms?

**Comment by yaaminiv** [comment]
@kubu4 @shellytrigg I think I'm still confused...

I already have genes annotated with Uniprot Accession codes. I'm trying to match these genes and codes with GOterms. I want some sort of master database with Uniprot Accession codes and GOterms. 

If I run `blastp` against SwissProt, I will get Uniprot codes, but not GOterms. Shelly's code has her combining `blastp` output with Uniprot annotations. I assume the annotations include GOterms, based on perusing her Jupyter notebook. How do I get those annotations with GOterms? I know on the Uniprot website you can add GOterm columns, but when I tried downloading the file those additional columns were not included in my download.

**Comment by shellytrigg** [comment]
@yaaminiv the uniprot DB contains GO terms and GO IDs as well as Uniprot accession codes so when you Blast your sequences to it, you can get the GO terms.

**Comment by kubu4** [comment]
If you already have Uniprot accession numbers, then just pop those into that website I linked above. Then follow my very rough instructions on how to get GO terms for them. This is assuming you want to bother with pointing and clicking (blah!).

**Comment by kubu4** [comment]
> I know on the Uniprot website you can add GOterm columns, but when I tried downloading the file those additional columns were not included in my download.

Sorry, didn't read that part. Screenshots would be helpful. Also, you have to "save" or something like that after you pick your options. Then, it will be updated and your downloaded text file will have the additional info you chose with the check boxes.

**Comment by yaaminiv** [comment]
> the uniprot DB contains GO terms and GO IDs as well as Uniprot accession codes so when you Blast your sequences to it, you can get the GO terms.

@shellytrigg this is what I saw when I downloaded the Uniprot Sprot database

<img width="1059" alt="Screen Shot 2019-06-25 at 2 53 48 PM" src="https://user-images.githubusercontent.com/22335838/60136455-0e575a00-9759-11e9-9522-9a89c750182a.png">

> Also, you have to "save" or something like that after you pick your options. Then, it will be updated and your downloaded text file will have the additional info you chose with the check boxes.

@kubu4 The columns I "saved":

<img width="1079" alt="Screen Shot 2019-06-25 at 2 55 55 PM" src="https://user-images.githubusercontent.com/22335838/60136551-57a7a980-9759-11e9-823a-e7e2b0678d60.png">

Previewed my download:

<img width="422" alt="Screen Shot 2019-06-25 at 2 56 22 PM" src="https://user-images.githubusercontent.com/22335838/60136580-68581f80-9759-11e9-80f4-4280e6932521.png">

No GOterm columns!

<img width="1080" alt="Screen Shot 2019-06-25 at 2 56 45 PM" src="https://user-images.githubusercontent.com/22335838/60136607-7c038600-9759-11e9-93db-8c4f2fc7a3f4.png">

**Comment by kubu4** [comment]
You'd need to download as a text file to get that table. That info won't be added to a FastA file.

**Comment by shellytrigg** [comment]
whoops wait a sec, I'm mistaken. @yaaminiv you're right, I downloaded this other table from Uniprot uniprot-reviewed%3Ayes.tab, probably the same way @kubu4 is suggesting. You can go [here]( https://www.uniprot.org/uniprot/?query=reviewed:yes), click columns to select which columns you want (GO BP, GO term, click download, select tab delim, then you can parse your tab file with your list of uniprot accessions

**Comment by yaaminiv** [comment]
@kubu4 @shellytrigg THANK YOU. I knew I was missing something.

My next question...do I actually have to `blastp`? I already did a `blastx` against *C. virginica* transcripts (how I got the Uniprot codes matched to genes in the first place). Could I just revise my Uniprot database with `makeblastdb` and redo a `blastx`?

**Comment by kubu4** [comment]
Sounds like you already have everything you need, right? What would be reason to redo stuff?

**Comment by shellytrigg** [comment]
I don't think you need to Blast at all anymore. I think you just need to join/merge your tables. One table that has your C. virg. uniprot accessions and the other uniprot tab file you just downloaded

**Comment by yaaminiv** [comment]
> Sounds like you already have everything you need, right? What would be reason to redo stuff?

@kubu4 I want to match my genes annotated with Uniprot codes with GOterms without using the point-and-click method. The GOterms are for downstream gene enrichment/general gene group descriptions so I can have a better idea of what kinds of genes I found DML in

**Comment by yaaminiv** [comment]
> I don't think you need to Blast at all anymore. I think you just need to join/merge your tables.

As long as merging is scientifically sound, that sounds super easy.

**Comment by shellytrigg** [comment]
@yaaminiv why would merging not be scientifically sound? You are just joining two tables based on common terms (uniprot accessions).

**Comment by yaaminiv** [comment]
> why would merging not be scientifically sound? You are just joining two tables based on common terms (uniprot accessions).

For some reason I got in my head that I needed e-values, but I definitely don't because I'm joining. I was confusing myself. I'm good now!

**Comment by shellytrigg** [comment]
Gotcha. It's probably a good idea to use an e-value cut off before you have your final list of C.virg genes with Uniprot accessions that you want to merge with your master Uniprot/GO term file
