### ISSUE TITLE
flankBed error: Genome file w/o required fields

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#294]
[Jupyter notebook](https://github.com/RobertsLab/project-virginica-oa/blob/master/notebooks/2018-06-11-DML-Analysis.ipynb)

I tried using [`flankBed`](http://bedtools.readthedocs.io/en/latest/content/tools/flank.html) to add 1000 bp flanks to my mRNA regions and got the following error:

> Less than the req'd two fields were encountered in the genome file (../2018-04-27-Bismark/2018-04-27-Bismark-Inputs/C_virginica-3.0_genomic.fa) at line 1.  Exiting.

I think this may be the issue:

> In order to prevent creating intervals that violate chromosome boundaries, bedtools flank requires a genome file defining the length of each chromosome or contig.

How do I fix this?

**Comment by sr320** [comment]
What is the format of said file?

**Comment by yaaminiv** [comment]
The input file is a gff, and the genome is a fasta file

**Comment by sr320** [comment]
I don’t think so....


1.3.10 What is a “genome” file?

Some of the BEDTools (e.g., genomeCoverageBed, complementBed, slopBed) need
to know the size of the chromosomes for the organism for which your BED
files are based. When using the UCSC Genome Browser, Ensemble, or Galaxy,
you typically indicate which species / genome build you are working. The
way you do this for BEDTools is to create a “genome” file, which simply
lists the names of the chromosomes (or scaffolds, etc.) and their size (in
base pairs).

Genome files must be tab-delimited and are structured as follows (this is
an example for C. elegans):

chrI 15072421

chrII 15279323

…

chrX 17718854

chrM 13794

**Comment by yaaminiv** [comment]
Okay. How do I create this tab-delimited genome file?

**Comment by sr320** [comment]
Type :) in TextWrangler?

You know chrom name, and length in bp

https://www.ncbi.nlm.nih.gov/genome/?term=Crassostrea%20virginica

**Comment by yaaminiv** [comment]
Dang it I was hoping there was an easy, automated way!

**Comment by yaaminiv** [comment]
creating a new genome file worked!
