### ISSUE TITLE
Mapping program for R? 

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#295]
@yaaminiv a few weeks ago you showed the lab a neat way to make maps in R.  Can you remind us what the package is? Did you need a shape file?  Thanks!

**Comment by sr320** [comment]
Here is script with all the packages,
https://github.com/RobertsLab/project-oyster-oa/blob/master/images/DNR/2018-05-23-Site-Map/2018-05-23-Outplant-Site-Map-Code.R

I do not think shape files are involved (but not sure).

**Comment by yaaminiv** [comment]
No shape file needed! Just know your coordinates

**Comment by laurahspencer** [comment]
Fantastic, thanks!
