### ISSUE TITLE
Unable to save flankBed output

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#296]
[Jupyter notebook](https://github.com/RobertsLab/project-virginica-oa/blob/master/notebooks/2018-06-11-DML-Analysis.ipynb)

I used the following code to successfully run `flankBed`:

> ! /Users/Shared/bioinformatics/bedtools2/bin/flankBed \
-i C_virginica-3.0_Gnomon_mRNA.gff3 \
-g 2018-06-15-bedtools-Chromosome-Lengths.txt \
-b 1000 \

When I add ` > 2018-06-15-mRNA-1000bp-Flanks.txt` at the very end of the code, it runs without producing any output. I first tried this on Friday, but did not see any file produced on Monday. I started it again Monday, and still don't have any saved output.

I can't find anything in the [documentation](http://bedtools.readthedocs.io/en/latest/content/tools/flank.html) about saving output from `flankBed`. Ideally, I want to save this new track and use `intersectBed` to find overlaps between DMLs and CG motifs. Any thoughts on how I can do this?

**Comment by sr320** [comment]
I do not see that code in that notebook

**Comment by yaaminiv** [comment]
It should be there now (forgot to push the commit)

**Comment by sr320** [comment]
can you provide url to files used?

**Comment by yaaminiv** [comment]
Nevermind: just restarted Jupyter nb and got the file I wanted!

**Comment by yaaminiv** [comment]
[mRNA gff](http://eagle.fish.washington.edu/Cvirg_tracks/C_virginica-3.0_Gnomon_mRNA.gff3)
[chrom lengths](https://github.com/RobertsLab/project-virginica-oa/blob/master/analyses/2018-06-11-DML-Analysis/2018-06-15-bedtools-Chromosome-Lengths.txt)

[BEDfile output](https://github.com/RobertsLab/project-virginica-oa/blob/master/analyses/2018-06-11-DML-Analysis/2018-06-15-mRNA-1000bp-Flanks.bed)
