### ISSUE TITLE
Supplies for Nanopore seq

### ISSUE THREAD

**Issue by jldimond** [RobertsLab/resources#297]
Starting to gear up for using the MinION. I am prepared to purchase everything I need but wanted to check first on a few things that might be available. 

1. I have decided to aim for multiplexing of samples following MBD enrichment. I see a recent purchase of MethylMiner kits. Are any of these reagents left and can I use them?

2. The protocols call for AMPure beads. I don't see anything like this in the inventory or purchasing logs, so I assume I will need to buy these -?

3. I'm planning on doing the bulk of the library prep at SPMC. Does anyone mind if I borrow the magnetic rack for a week or two?

[Here is my list of supplies](https://docs.google.com/spreadsheets/d/1rMPxNMZePUgAH9cn7RbKoDX6uNHaAIrB7DneSysEvXw/edit?usp=sharing) if you are interested.

Thanks

**Comment by jldimond** [comment]
UPDATE

I am now considering getting the $1000 startup kit that includes a MinION, two flow cells, and a sequencing kit. This seems like a really good deal and a good way to get started (a flow cell alone costs $900 if you buy it separately). So for now please disregard what I wrote in the initial post, in part because the new effort would not involve the multiplex kit that I first spec'd out.

**Comment by sr320** [comment]
Makes sense
