### ISSUE TITLE
How to render pics from GitHub in a post

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#298]
This worked during Hackweek when I put the image in an issue, but it isn't working anymore, so I think I must have done something different then. 

Today's image I want to put in my notebook post: https://github.com/grace-ac/grace-ac.github.io/blob/master/notebook-images/20180619-notes.png

I did this:
`![img](https://github.com/grace-ac/grace-ac.github.io/tree/master/notebook-images)`

this is what shows up:
![img](https://github.com/grace-ac/grace-ac.github.io/tree/master/notebook-images)

**Comment by sr320** [comment]
This will work

`![img](https://github.com/grace-ac/grace-ac.github.io/blob/master/notebook-images/20180619-notes.png?raw=true)`

![img](https://github.com/grace-ac/grace-ac.github.io/blob/master/notebook-images/20180619-notes.png?raw=true)


HOWEVER, it is best to use relative paths.  What is the url for the page you are trying to embed image on?

Guessing... 
try this

`![img](../notebook-images/20180619-notes.png?raw=true)`

**Comment by sr320** [comment]
or better?

`![img](../notebook-images/20180619-notes.png)`

**Comment by grace-ac** [comment]
I just did this and it worked:

`![](https://github.com/grace-ac/grace-ac.github.io/blob/master/notebook-images/20180619-notes.png)` 

But it doesn't work in the issue:
![](https://github.com/grace-ac/grace-ac.github.io/blob/master/notebook-images/20180619-notes.png)

which seems weird.

but yes!!! the relative path one works great. Yet again, I forgot about relative paths. 

link to post: https://github.com/grace-ac/grace-ac.github.io/blob/master/_posts/2018-06-19-Updates-and-plan-for-week.md
