### ISSUE TITLE
Skyline Q for Yaamini

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#299]
@yaaminiv       
Based on your .pynb post from when you did this, I should only be looking at proteins that have more than one peptide? 

https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/DNR/2017-07-07-SRM-Target-Identification-in-Skyline.ipynb 

Also, my Skyline has 6,806 proteins listed.... that is wayyyy more than what you have... I put all my settings just as they are in the DIA protocol.

**Comment by yaaminiv** [comment]
The notebook you are looking at is for SRM target selection, not for error rates! From my understanding, it doesn't matter if the protein has 1 or more peptides when checking error rates (thought I don't know why)

Also I had 9,047 proteins listed in my Skyline document (check the bottom right of the screenshot in the notebook)

**Comment by grace-ac** [comment]
Ah, ok yay!!! I keep second guessing literally EVERYTHING I do in Skyline... glad I'm still doing all right. Thanks!
