### ISSUE TITLE
Get TA samples analyzed

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#3]
_From @sr320 on July 21, 2017 17:24_

_Copied from original issue: sr320/LabDocs#663_

**Comment by kubu4** [comment]
Have phone call in to Mettler-Toledo to get the rundown on titrators and means of automation. Will report back with info once received.

**Comment by kubu4** [comment]
Rep is out of office. Will get back to me Aug 7th.

**Comment by kubu4** [comment]
Have confirmed with Hollie:
- Purchased and has used 9 sample Rondolino ($20,000)
- Purchased and has used LabX software ($2500)
- Purchased and has used pH probe ($500)
- Time per 100mL sample is ~12 minutes; time frame (and acid use) can be cut by using 50mL samples.

Now waiting to figure out payment.

**Comment by sr320** [comment]
Lets go ahead and get 
12k on 65-2861
Rest 62-9868

**Comment by kubu4** [comment]
We going for 9 sample or 18 sample unit?

**Comment by sr320** [comment]
9 sample
