### ISSUE TITLE
hummingbird update and permissions

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#30]
_From @jldimond on August 30, 2017 6:8_

I realize this is not hackweek anymore, but thought this would be an appropriate place to post a few issues. 

3 things:

1. Should we update hummingbird's OS - it is still running OS X - ?

2. I've tried installing some things (e.g. coreutils) via brew and do not have permission (user: srlab). 

3. Finally, sort of unrelated, but why would this command work at the terminal but not in a jupyter notebook (using NCBI Entrez Direct, and yes I did use ! in jupyter):

esearch -db nuccore -query "Symbiodinium [ORGN] AND Symbiodinium sp. clade D [ORGN]" | efetch -format fasta > /Volumes/toaster/jdimond/Porites-astreoides-RAD/data/SymCladeD.fasta

_Copied from original issue: RobertsLab/2017-hackweek#18_

**Comment by kubu4** [comment]
1. I don't think there's a need. We have the most current OS on Roadrunner if you need it. Plus, it's not a bad idea to keep a "legacy" OS around.

2. srlab does not have Administrator privileges, so won't be able to install some software. We can:
  - Change srlab to Adminstrator
  - Have an Adminstrator install the software you need
  - Create your own user account with Administrator priveleges

Since the first option is the easiest for all parties involved, I'll just change srlab to have Administrator privileges. However, we should consider if we want to keep it that way or if we should create some sort of guest account for non-Roberts Lab members to use (which won't have Administrator priveleges).

3. Can you post a screen shot with the error message? Hard to troubleshoot without seeing the computer's explanation for failure. My initial guess would be that ```esearch``` isn't installed on Hummingbird.

**Comment by kubu4** [comment]
Also, for Number 2, why do you need to install ```coreutils```? As far as I can tell, virtually all of the programs contained in ```coreutils``` are already available on Macs. Just curious what you need.

**Comment by kubu4** [comment]
I've thought about this some more and have changed my mind on changing srlab to Administrator until @sr320 chimes in. The reason I hesitate is that the srlab account is a multi-user account. The fact that it is a multi-user account is the primary reason that it's set up as a Standard account; so that individual users don't/can't (drastically) alter the working environment and impact other users use of the srlab account who are expecting the "default" working environment. 

Of course, I've probably overthought this, but I'd prefer to wait until we get feedback from @sr320.

**Comment by jldimond** [comment]
Thanks @kubu4 

1. Makes sense re: OS

2. I was looking for a command to sort a file randomly, and either `shuf` or `sort -R` can do this but are not standard Mac commands, and are not on Hummingbird. `coreutils` has both of these commands and seems to be how most people install them.

3. I installed NCBI Entrez Direct on Hummingbird, which includes the esearch tool, and was able to execute the command successfully in the terminal, but not in a jupyter notebook, using either conda root or python root. Here is a screenshot of the error:

![screen shot 2017-08-30 at 7 47 37 am](https://user-images.githubusercontent.com/9869457/29878524-9fc070ac-8d57-11e7-9935-fdc2f99294af.png)

**Comment by sr320** [comment]
Re 3- try full path for esearch.

**Comment by kubu4** [comment]
Interesting about ```shuf``` and ```sort```!

I echo the same thing that @sr320 suggests.

Also, what is displayed when when you run ```which esearch``` from the Jupyter notebook (that's a ```bash``` command, so you'll need the exclamation point or ```%%bash``` as the first line of the cell in order for it to run)? Running that command in Terminal works (i.e. spits out the install location for ```esearch```), but it's in a non-standard location. Did you happen to install ```esearch``` while your Jupyter notebook was already running? 

If yes, then it's likely that your Jupyter notebook doesn't have an updated version of your system ```$PATH```. The system ```$PATH``` is where the computer looks for installed programs. However, the computer only looks at the system ```$PATH``` when you start a new Terminal. Thus, if you started Jupyter notebook and then installed ```esearch```, the Terminal that's running Jupyter notebook can't see the updated system ```$PATH```.

**Comment by jldimond** [comment]
OK, that was it! Just had to restart Terminal and Jupyter.

**Comment by kubu4** [comment]
I just looked and srlab account is already an Admin account. Can you post screenshot(s) of error message when trying to install ```coreutils```?

**Comment by jldimond** [comment]
![screen shot 2017-08-30 at 2 38 31 pm](https://user-images.githubusercontent.com/9869457/29896232-03d3db18-8d91-11e7-8551-d889dd3cb1a0.png)

**Comment by kubu4** [comment]
Try this:

```sudo chown -R $USER /Library/Caches/Homebrew/```

Then, try your install command.

**Comment by jldimond** [comment]
That helped me with the install, but then I still got some errors:

![screen shot 2017-08-30 at 3 55 26 pm](https://user-images.githubusercontent.com/9869457/29898675-f96b0c18-8d9b-11e7-9f8e-000411b09e6c.png)

**Comment by kubu4** [comment]
Try this:

```sudo chown -R $USER /usr/local```

Then, try your install command again.

**Comment by jldimond** [comment]
I had to do `sudo chown` to several directories, and symlink finally worked. Thanks!
