### ISSUE TITLE
How to confirm files are the same?

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#300]
I want to confirm [oyster.v9.glean.final.rename.gff.pep.gz](ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100030/gene_v9/oyster.v9.glean.final.rename.gff.pep.gz) is the same as the [proteome file I worked with for the DNR paper](http://owl.fish.washington.edu/halfshell/bu-git-repos/nb-2017/C_gigas/data/Cg_Gigaton_proteins.fa). How do I do this? I remember learning about checksums but I don't quite know how to use it...

**Comment by sr320** [comment]
Both are fasta.  

first you could  run `head` to see if first 10 lines are same...

could also 

`grep -c ">" filename` to count number of seqs is the same.

**Comment by yaaminiv** [comment]
![untitled](https://user-images.githubusercontent.com/22335838/41682992-3fa7f158-748e-11e8-863c-b645b93da882.png)

there seem to be some differences

**Comment by sr320** [comment]
you are correct

**Comment by yaaminiv** [comment]
So...where did my proteome file come from?

**Comment by sr320** [comment]
Good Q - create a new issue with details.
