### ISSUE TITLE
Where did the oyster proteome come from?

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#301]
Here's a link to the oyster proteome file I used for the DNR paper: http://owl.fish.washington.edu/halfshell/bu-git-repos/nb-2017/C_gigas/data/Cg_Gigaton_proteins.fa

Where did it come from? I determined that it did not come from Fang et al. (see [this issue](https://github.com/RobertsLab/resources/issues/300)).

**Comment by sr320** [comment]
What did you use it for?

Provide more info ie output from head, sequence name format, # of sequences.

**Comment by yaaminiv** [comment]
The file was used in the protein digest simulator (see [this nb](https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/DNR/2017-02-28-DIA-Analysis-PECAN.ipynb)).

Output from head:

![head](https://user-images.githubusercontent.com/22335838/41688465-1191391a-74a1-11e8-933c-f5557d089649.png)

Not entirely sure about the sequence name format, but they all start with CHOYP

Number of sequences: 

![sequences](https://user-images.githubusercontent.com/22335838/41688469-15945808-74a1-11e8-9d35-ed48e88d8c4c.png)

**Comment by sr320** [comment]
@emmats Why would she have used this proteome (likely derived from the translation of a transcriptome assembled with Trinity), as opposed to the canonical proteome published with the genome?

**Comment by emmats** [comment]
I have no idea! I think I asked her to ask you which one to use, although I don't remember exactly. I'm pretty sure I wasn't part of that particular decision-making process. If I was, I didn't make note of it and don't remember.

**Comment by sr320** [comment]
@yaaminiv do you recall why this is relevant?

**Comment by yaaminiv** [comment]
@sr320 We wanted to cite the proteome source in the DNR paper
