### ISSUE TITLE
Warranty conditions for Titrator

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#303]
We are considering moving the titrator out to Pt Whitney. Are there any conditions about moving it and voiding warranty (assuming there is a warranty)?

**Comment by kubu4** [comment]
Just saw titrator was taken.

A couple of observations/thoughts:

- Replacement acid is still here (will probably be needed soon - depends on how many samples are going to be processed)

- CRM is still here.

- Both scales were taken, which means we no longer have a scale in the lab.

- SOP for operating titrator and for processing files is not finished, so it may be difficult to operate (however, I think Sam took good notes, so I think he'll be OK).
