### ISSUE TITLE
Trinity practice with geoduck data

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#304]
1. Where can I find the geoduck ~proteomics~ data?

2. Where can I find a guide to using Trinity? 

I was looking at the wiki from Trinity the other day: https://github.com/trinityrnaseq/trinityrnaseq/wiki

**Comment by sr320** [comment]
That is is the proper guide.

See if you can come up with initial steps from that guide then we can
discuss how to get started.

**Comment by sr320** [comment]
@grace-ac 

based on what you read today, does this code make sense?
that is, could you explain what every line does...

```
/gscratch/srlab/programs/trinity/Trinity \
--seqType fq \
--max_memory 100G \
--left /gscratch/srlab/sr320/data/geoduck-RNA-seq/NR012_S1_L001_R1_001.fastq,\
/gscratch/srlab/sr320/data/geoduck-RNA-seq/NR012_S1_L002_R1_001.fastq \
--right /gscratch/srlab/sr320/data/geoduck-RNA-seq/NR012_S1_L001_R2_001.fastq,\
/gscratch/srlab/sr320/data/geoduck-RNA-seq/NR012_S1_L002_R2_001.fastq \
--trimmomatic \
--CPU 28
```

**Comment by sr320** [comment]
Also give this a read - https://d.pr/f/7oPLDR

**Comment by grace-ac** [comment]
--seqType fq \ 
the sequence reads are of fastq type (there is a quality value given to each read)

--max_memory 100G \
the amount of memory (temporary data storage space) to be allocated to running Trinity

--left /gscratch/srlab/sr320/data/geoduck-RNA-seq/NR012_S1_L001_R1_001.fastq,\
/gscratch/srlab/sr320/data/geoduck-RNA-seq/NR012_S1_L002_R1_001.fastq \
look at the left reads of the paired data 

--right /gscratch/srlab/sr320/data/geoduck-RNA-seq/NR012_S1_L001_R2_001.fastq,\
/gscratch/srlab/sr320/data/geoduck-RNA-seq/NR012_S1_L002_R2_001.fastq \
look at the right reads of the paired data

--trimmomatic \
trim the reads for quality

--CPU 28
number of computer processing units to allocate to running Trinity

**Comment by grace-ac** [comment]
currently reading the Roberts and Gavery paper and will then do the practice with Command line.
