### ISSUE TITLE
Downloading specific files from web directory

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#307]
I often want to download a subset of files in a directory on the web

For instance, this is what I did to get some of Katherine's files to mox

`wget -r --no-parent -A 'CP*.gz' http://owl.fish.washington.edu/nightingales/O_lurida/`

The snag is that it keeps directory stucture

`/gscratch/srlab/sr320/data/ks_CP-2/owl.fish.washington.edu/nightingales/O_lurida`

I just wanted the files to end up in `ks_CP-2`

How might I do this?

**Comment by kubu4** [comment]
Try this is option:  ```--no-directories```

**Comment by sr320** [comment]
thanks
