### ISSUE TITLE
Student needs project

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#308]
I just spoke with a very well qualified high school student (has done ecotox, qPCR work at NOAA) who wants to do a experiment with animals and molecular work..  So this would likely mean bringing animals to SAFS, doing a stressor experiments followed by gene expression...

Any suggestions?

**Comment by yaaminiv** [comment]
If he's interested in ecotox, we could try and expose oysters to pollutants (stormwater runoff, Cu, microplastics)? We can do different intensities and/or exposure times.
