### ISSUE TITLE
Develop Principal Datasheet for Crab Samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#310]

**Comment by sr320** [comment]
@grace-ac sounds like we are close to one form of a master sheet based on our conversation today- can you post putative sheet here  (or url)

**Comment by sr320** [comment]
404: Not Found

**Comment by grace-ac** [comment]
https://raw.githubusercontent.com/RobertsLab/project-crab/master/data/20180813-all-hemo-with-Qubit.csv

**Comment by kubu4** [comment]
@sr320 Reopening. Goal is to develop principal spreadsheet for submission to NPRB project portal. Should just be critical data utilized for the project. Doesn't need "extraneous" data like carapace size, tank locations, etc.

**Comment by kubu4** [comment]
There are a number of spreadsheets in here:

https://github.com/RobertsLab/project-crab/tree/master/data

Also, want to add mean qPCR data for all crabs.

**Comment by grace-ac** [comment]
Sampling table: [analyses/sample_table.csv](https://github.com/RobertsLab/project-crab/blob/master/analyses/sample_table.csv)   

"master" sample spreadsheet with qubit data: [analyses/master-qubit-sample.csv](https://github.com/RobertsLab/project-crab/blob/master/analyses/master-qubit-sample.csv)

Excel spreadsheet from Pam with sampling, claw measurements, etc: [data/Excel-data-from-Pam/20180125-NPRB-crab-sample-data.xlsx](https://github.com/RobertsLab/project-crab/blob/master/data/Excel-data-from-Pam/20180125-NPRB-crab-sample-data.xlsx)      

Excel spreadsheet from Pam for qPCR: [data/Excel-data-from-Pam/20180518-Hemato_qPCR_results.xlsx](https://github.com/RobertsLab/project-crab/blob/master/data/Excel-data-from-Pam/20180518-Hemato_qPCR_results.xlsx)    

Copy of the tab with qPCR from all runs from the above excel spreadsheet" [analyses/qpcr_hemat-new.csv](https://github.com/RobertsLab/project-crab/blob/master/analyses/qpcr_hemat-new.csv)

**Comment by sr320** [comment]
I would like to propose the following as the principal datasheet - it is sample centric.
@kubu4 @grace-ac Do you see any fatal flaws?


screenshot:

![Screen Shot on 2020-06-17 at 13:28:41](https://user-images.githubusercontent.com/4442039/84947072-7ad01500-b09e-11ea-9993-19dd8bec181d.png)


[sample_table.xlsx](https://github.com/RobertsLab/resources/files/4794952/sample_table.xlsx)

**Comment by grace-ac** [comment]
Did some spot-checks and it looks good!

**Comment by kubu4** [comment]
No fatal flaws. Would add mean copy number from qPCR data. I'd probably change all of the treatment-temp for sample-day 9 to "ambient"; mostly a personal preference, though.

**Comment by kubu4** [comment]
What do numbers in "infection-status" column indicate? I see values of: 0, 1, 3. I was only expecting 0 or 1 (i.e. uninfected or infected).

**Comment by grace-ac** [comment]
According to pam’s notes it means undetermined
