### ISSUE TITLE
Prepare Crab RNA for sequencing

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#311]
Please work with Sam to prep RNA to go out for sequencing

**Comment by grace-ac** [comment]
Will do speed vac when @kubu4 and I are both in lab together again on Tuesday and then they'll be ready! 

not enough time today for speed vac before sam leaves today, so I'll just make the pooled samples.

**Comment by sr320** [comment]
Do double check labels

**Comment by grace-ac** [comment]
@kubu4 speed vac sometime today? I'm around til 5.

**Comment by kubu4** [comment]
Yes. Sooner rather than later (i.e. start now). Don't know how long it will take.

**Comment by kubu4** [comment]
Update: Post-speedvac Qubit is no good (way too low; doesn't match expected quantities). Ran on NanoDrop and absorbance profile is sub par. I'll re-quantify the original samples on the Qubit and NanoDrop tomorrow.

It's possible samples will require some sort of cleanup - either kit-based or EtOH precip.

**Comment by kubu4** [comment]
Ran cleanup on pooled RNA: http://onsnetwork.org/kubu4/2018/07/19/rna-cleanup-tanner-crab-rna-pools/

Results weren't great. Suggests that recovery from cleanup kit was very, very poor (<10% recovery) or initial quantifications were incorrect.

After working with the samples, I'm inclined to think it's the latter. The three pools all had undissolved/insoluble material in them. Additionally, NanoDrop curves of the three pools showed high levels of absorbance around 230nm - usually indicative of contaminant carryover (excess salt/phenol/EtOH). I suspect that this could have possibly interfered with the initial Qubit assays for quantification.

Not entirely sure how to proceed from here, but I think it would be a very good idea to run all original RNA samples through a cleanup kit and re-quantify them.

**Comment by sr320** [comment]
Lets discuss this morning- 10am

**Comment by kubu4** [comment]
Discussion summary:

- @grace-ac will isolate additional RNA from four samples using large(r) volume of RNAzol, quantify, and check absorbance spectrum on NanoDrop.

- @grace-ac will run samples and some of my initial test samples on Bioanalzyer to check integrity and get another quantification metric.

**Comment by sr320** [comment]
For report - all we need to say is RNA has been isolated from XX samples

**Comment by sr320** [comment]
Please send me any report text to review and also check to see if we have
sufficient TRI-reagent to run 4 samples

**Comment by grace-ac** [comment]
Yep! I just emailed Pam to give her an update

I just sent you the link to the google doc that we have been filling out.

**Comment by sr320** [comment]
I am splitting this out to new issues..
