### ISSUE TITLE
PAXgene Tissue DNA Kit for C. gigas broodstock

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#313]
Product: https://www.preanalytix.com/products/tissue/DNA/paxgene-tissue-dna-kit?suggest=1

Need to purchase 1 additional kit for July 30 *C. gigas* broodstock gonad DNA extractions and eventual MBD sequencing, pending budget number + approval from @sr320

**Comment by sr320** [comment]
61-1553
