### ISSUE TITLE
Next steps for flanking analysis

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#315]
[Jupyter notebook](https://github.com/RobertsLab/project-virginica-oa/blob/master/notebooks/2018-06-11-DML-Analysis.ipynb)

I have a [file](https://github.com/RobertsLab/project-virginica-oa/blob/master/analyses/2018-06-11-DML-Analysis/2018-06-19-mRNA-100bp-Flanks-DML.txt) that shows intersections between DMLs and mRNA coding regions with 100 bp flanks on either end. I also have a [file](
https://github.com/RobertsLab/project-virginica-oa/blob/master/analyses/2018-06-11-DML-Analysis/2018-06-15-mRNA-1000bp-Flanks.bed) with only the mRNA coding regions and 100 bp flanks.

What do I do next? I assume I have to to a gene enrichment down the line too.

**Comment by sr320** [comment]
Start drafting paper

**Comment by yaaminiv** [comment]
Great, already in progress

https://docs.google.com/document/d/1gOMJrnhs4D-jCKWlJK2tm0Z27IrSqMkmc7K1pDBmqi0/edit
