### ISSUE TITLE
Location of histology photos

### ISSUE THREAD

**Issue by kaitlynrm** [RobertsLab/resources#316]
I was wondering where the histology photos that need to be organized are and if there is a specific way they should be organized.

**Comment by sr320** [comment]
I hack week we came up with a schema and maybe createded a spreadsheet?

**Comment by sr320** [comment]
see some code from @kubu4
https://github.com/RobertsLab/hackweek-2018/issues/13

**Comment by kaitlynrm** [comment]
I read through the Histology Data Management Plan and I see some info in the [Histology-database](https://docs.google.com/spreadsheets/d/1Dsfkam_h5hXvPAWWHiaI4ph-hUC4idL7ZZou41He9wU/edit#gid=2035956184). I don't see any images in the [specified Owl directory](http://owl.fish.washington.edu/hesperornis/). I'm also not sure where/how I would add the timestamp, but I looked at the code and understand Sam is referencing an image from owl then labeling it a specific way.

Are these [the images](https://github.com/RobertsLab/paper-gigas-early-gametogenic-exposure/tree/master/images) that haven't been filed yet?
