### ISSUE TITLE
Measure larvae from images using ImageJ

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#317]
I have larvae images that need to be processed for size using [ImageJ](https://imagej.nih.gov/ij/download.html).  The images are saved here:  https://github.com/laurahspencer/O.lurida_Temperature/tree/master/images/New-Larvae 

Larvae were imaged on a hemocytometer, so use grid the grid lines to set your scale in ImageJ. Re-do your scale for each image. (hemocytometer grid measurements: https://www.hemocytometer.org/hemocytometer-square-size/)

There are ~48 larval groups, and the images are labeled with group #-rep (e.g. 10-1 and 10-2 are two images from the same group, likewise 27-1 & 27-2). I'd like 30 larvae measured per group. I took 2-3 images per group, so you may need to split the 30 larvae between images. Just make sure to re-do your scale if you switch images. 

Measurements should include length and width (see image), which should be perpendicular to each other. Only measure larvae that are lying flat against the plate, and those that were live when I froze them (aka don't image empty shells). You'll notice some junk in some of the images - this is b/c I left some larvae samples sitting overnight in ethanol prior to imaging. This shouldn't affect the size measurements. 

Do a few images, then tell me which ones and I'll do them too - I'd like to make sure we're getting similar measurements. 

![104-1_example-measurements](https://user-images.githubusercontent.com/17264765/42985435-bec8fd3e-8c34-11e8-8091-a3e04459ea5f.JPG)

**Comment by kaitlynrm** [comment]
I measured 6 larvae in three images for you to check. The order I measured the larvae in goes red, orange, yellow, green, blue, and purple. The first measurement is always length, followed by width (eg. measurement 1 is the red length line and measurement 2 is the red width line).

[10-2 image](https://github.com/kaitlynrm/O.lurida_Temperature/blob/master/images/New-Larvae/10-2_draw.jpg) and [10-2 measurements](https://github.com/kaitlynrm/O.lurida_Temperature/blob/master/images/New-Larvae/10-2_m.csv)

[7-1 image](https://github.com/kaitlynrm/O.lurida_Temperature/blob/master/images/New-Larvae/7-1_draw.jpg) and [7-1 measurements](https://github.com/kaitlynrm/O.lurida_Temperature/blob/master/images/New-Larvae/7-1_m.csv)

[16-1 image](https://github.com/kaitlynrm/O.lurida_Temperature/blob/master/images/New-Larvae/16-1_draw.jpg) and [16-1 measurements](https://github.com/kaitlynrm/O.lurida_Temperature/blob/master/images/New-Larvae/16-1_m.csv)

**Comment by laurahspencer** [comment]
When measuring, first step is to identify the hinge, which is the flattest/straightest part of the shell. In my image below I've drawn red lines next to the hinge.  

The shell length is a line running perpendicular to the hinge side, measured from the middle of the hinge. In the photo the yellow lines = shell length. 

The shell width is a line running parallel to the hinge side, at the fattest part of the oyster. In the photo the orange lines = shell width. 

Also- check out [this video](https://www.youtube.com/watch?v=i3pnG-37b8I) for easy tracking of multiple measurements.  

![7-1_draw-lhs](https://user-images.githubusercontent.com/17264765/43124057-5aa625ce-8f69-11e8-8dd4-b1847fb20199.jpg)

My measurements from the above image: 

oyster | measurement | size    (mm)
-- | -- | --
red | length | 0.170
red | width | 0.180
orange | length | 0.166
orange | width | 0.189
yellow | length | 0.158
yellow | width | 0.172
green | length | 0.155
green | width | 0.174
blue | length | 0.162
blue | width | 0.185
purple | length | 0.164
purple | width | 0.177

**Comment by kaitlynrm** [comment]
Thanks for the video! It helped out a lot. After tracing your lines and practicing a bit more, I did 6 more oysters on the above image.

![new](https://user-images.githubusercontent.com/26392677/43221090-a465132c-9000-11e8-86fe-6c73dfafcc96.JPG)

oyster| measurement | size (mm)
--|--|--|
2|length|0.157
2|width|0.171
4|length|0.162
4|width|0.168
6|length|0.139
6|width|0.169
8|length|0.156
8|width|0.187
10|length|0.150
10|width|0.179
12|length|0.152
12|width|0.188

**Comment by laurahspencer** [comment]
Your measurements look good- when setting your scale I think it's best to use a larger length. For example, I used 4 of the squares (0.25mm each) and set the scale at 1mm.  Also- please measure/record your scale length for each image so I can get an error rate. 

Feel free to move forward with the measurements- thank you!
