### ISSUE TITLE
Does anyone have any slides that need imaging?

### ISSUE THREAD

**Issue by kaitlynrm** [RobertsLab/resources#318]
@laurahspencer @yaaminiv

**Comment by yaaminiv** [comment]
@kaitlynrm I'm all done with imaging, thanks for asking!

**Comment by laurahspencer** [comment]
@kaitlynrm yes, I do!  Steven put a box of histology slides on my desk area, which arrived in the mail.  They need to be imaged, but it's a bit complicated ... 

Each slide has several separate gonad tissues on them (from different oysters), which need to be imaged and labeled with sample #.  Here's how I did it: 

Step 1:  lay out the slides on a piece of paper, and label each tissue on the slide A, B, C, ... etc. in a logical, consistent order and take a photo of the layout, like this but use letters and start over your lettering on each slide (I was dumb and numbered the tissues, which confused things):
![slides_01-14](https://user-images.githubusercontent.com/17264765/43174610-5e55ad58-8ffe-11e8-9dd1-8b36fbe506d1.jpg)

Step 2: image each slide - first image the slide number, then take photos at both **4x and 10x** of an area of the gonad tissue, which is representative of the whole section. Eggs are pink, and sperm are blue/purple. Check out [my previous gonad tissue images for reference](https://github.com/laurahspencer/O.lurida_Temperature/tree/master/images/Histology). Take the photos in order of your letters. The image file numbers should be chronological, so you know which image is A, which is B, etc .... from each slide #. 

Step 3: Upload the images to a computer, and rename image files with sample #, and magnification, using naming convention:  "Oly-XXX-4x" and "Oly-XXX-10x". This is tricky. To identify which sample number the tissues belong to, refer to my [histology cassette images](https://github.com/laurahspencer/O.lurida_Temperature/tree/master/images/Histology/Cassettes) & my histology [cassette keys]().  I put blue ink on one tissue in each cassette, which may help with orientation.  The tissues are hopefully in the same configuration as in the images, but they may be mirror imaged.  As you're identifying the sample #, annotate the photo with a bunch of slides with the sample # for future reference, like this: 
![slides_71-81](https://user-images.githubusercontent.com/17264765/43174667-aaecc0f2-8ffe-11e8-8936-09e2dc7535f9.jpg)

**Comment by kubu4** [comment]
Check histology database for slide locations.

**Comment by kaitlynrm** [comment]
Also, the histology cassette key link isn't linking to anything @laurahspencer.

**Comment by kubu4** [comment]
I believe you want the slides dated 6.6.18.

**Comment by kaitlynrm** [comment]
How can I tell which slides those are? Sorry I'm not in lab right now and dont remember seeing dates on the slides in the slide boxes. None in the database are labelled that date that I see.

**Comment by kubu4** [comment]
Histology database rows 521 - 546.

**Comment by kaitlynrm** [comment]
Am I looking at the wrong spreadsheet? Where can I access the one with that info?

**Comment by kubu4** [comment]
https://docs.google.com/spreadsheets/d/1BIbDleJPEiKrmx7JwNIPwg2pM-thuZ39upmenldx4pA/edit?usp=drivesdk

**Comment by kaitlynrm** [comment]
Thank you so much Sam!

**Comment by laurahspencer** [comment]
Cassette keys uploaded - labeled, for example, "Cassette-key_100-107.JPG"

**Comment by sr320** [comment]
@kaitlynrm - as you take these images please follow instructions at 

https://github.com/RobertsLab/resources/wiki/Data-Management#histology-data-management-plan

we can modify if need be.
