### ISSUE TITLE
Hyak user request

### ISSUE THREAD

**Issue by jldimond** [RobertsLab/resources#321]
I am interested in becoming a Hyak user. I have some Nanopore data (yay!) that I'd like to assemble using Canu, and it seems like a rather large job. Can someone add me? Thanks

**Comment by kubu4** [comment]
You've been added.

Follow instructions for "user" at this page: https://github.com/RobertsLab/hyak_mox/wiki/Adding-a-User

**Comment by kubu4** [comment]
Oh, and here's our wiki page to help you get started using Mox (Hyak): https://github.com/RobertsLab/hyak_mox/wiki

**Comment by jldimond** [comment]
Thanks Sam! 

I saw that page and will proceed from there - thanks!
