### ISSUE TITLE
Store geoduck samples in -80

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#322]

**Comment by sr320** [comment]
follow steps re -80 at https://github.com/RobertsLab/resources/wiki/Lab-Inventory

**Comment by kaitlynrm** [comment]
I added Sam's samples but don't have access to edit the map for some reason. I sent a request to edit. Sam's geoduck samples are in Rack 3, column 3, row 2.

**Comment by grace-ac** [comment]
@kaitlynrm i just changed the share settings to "can edit"- does it work now?

**Comment by kaitlynrm** [comment]
Yes, thank you!
