### ISSUE TITLE
Jekyll Page Build Failure...? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#323]
Just got this email alert from Github: 

![pagebuild-fail](https://user-images.githubusercontent.com/14934314/43294731-c75ed98a-90f5-11e8-9a59-5bd53e28cc51.png)

**Comment by kubu4** [comment]
Can you please paste troubleshooting URL?

**Comment by grace-ac** [comment]
https://help.github.com/articles/troubleshooting-jekyll-builds

**Comment by sr320** [comment]
as long as your notebook looks like correct-not a problem
https://grace-ac.github.io/monthview/
is something missing?

**Comment by grace-ac** [comment]
nope! okay thanks!
