### ISSUE TITLE
Mox is over storage quota

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#324]
We've exceeded our Mox storage quota (5.5TB). As such, the two jobs that are currently running (mine and @jldimond) are currently locked up. Mine is throwing an error in the slurm output about being over quota, however, @jldimond's is not throwing an error. His slurm output file hasn't been updated since 7/28 - a gap of this amount of time is unusual, likely indicating his job is not actually running.

**Comment by kubu4** [comment]
![](http://owl.fish.washington.edu/Athaliana/20180730_mox_maker_quota_01.png)

**Comment by sr320** [comment]
I will delete files now...

**Comment by sr320** [comment]
now 
```
                         Block Limits                                    |     File Limits
Filesystem type             GB      quota      limit   in_doubt    grace |    files   quota    limit in_doubt    grace  Remarks
gscratch   FILESET        3153       5500       6050        347     none |  7915551 8250000  9075000      875     none 
```

**Comment by jldimond** [comment]
Looks like my job is not running - does anyone have experience running Canu on mox? It started out OK then just stopped I guess.

**Comment by sr320** [comment]
Slurm might be best way to start to diagnose

**Comment by kubu4** [comment]
@jldimond - It probably stopped due to Mox going over quota. I think you'll need to kill and restart your job.

**Comment by jldimond** [comment]
Got it - thanks.

**Comment by kubu4** [comment]
Looks like the timestamp on your slurm output file has been updated. Likely
don't need to restart job.

**Comment by kubu4** [comment]
My recent Trinity run put us way over quota. I'm in the process of gzipping folder. After gzipping, will transfer data to Owl. This should put us back under quota. Will report back here when that happens.

**Comment by kubu4** [comment]
I've deleted my stuff, but we're still well over our data quota.

**Comment by sr320** [comment]
Can you determine what/who is the culprit?

**Comment by kubu4** [comment]
Well, looks like I spoke too soon after deleting my stuff; the usage log hadn't fully updated. The usage log now shows us at 4TB used (out of 5.5TB), so we're OK.

But, here's the current breakdown, for the curious:

- @jldimond : Using 3.7TB (67% of srlab storage)

- @sr320 : Using 300GB

- @kubu4: Using 27GB

- sean: Using 29GB

**Comment by sr320** [comment]
@jldimond - do you have all you files backuped?
Let me know if you need help.

Once somewhere else could you remove most of the files on Mox?

**Comment by kubu4** [comment]
@jldimond - it ran, but did not complete. It was killed on on 8/2/2017 due to hitting the time limit you set for your job.

**Comment by jldimond** [comment]
I see. I gave it 7 days and that was apparently not enough. I deleted most of the 3.7TB that was generated by Canu. My utilization is back down to 9GB.

I'd like to retry a Canu assembly with double the amount of FASTQs one of these days (maybe in a few weeks). Does anyone have any recommendations for a time limit and how to deal with the huge amount of files (which I assume are mostly temporary)?

**Comment by sr320** [comment]
30 days would be fine. Really no need to limit.

Also note we have 200TB of temp storage (30 days)
https://github.com/RobertsLab/hyak_mox/wiki/Data-Storage-&-System-Organization#3-temporary-storage

and it might make sense for you to write out Canu output to it.

**Comment by kubu4** [comment]
1. - Set time limit to something ridiculous (like 100 days) - it really has no bearing on anything. However, in essence, 30 days is the max time limit, as Mox goes down for monthly maintenance.

2. Use /gscratch/scrubbed directory (you can make your own subdirectory). I think there's a 200TB limit on this directory. However, all files get removed automatically after 30 days.

**Comment by jldimond** [comment]
Okay, thanks, will do. Sorry to fill up the permanent storage. But I think it was a useful test run to see how time and storage intensive it is.
