### ISSUE TITLE
Manchester OA system header tank specs

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#326]
Does anyone (@laurahspencer ?) have the following information about the Manchester OA system/header tanks? If not, I'll email Ryan.

- Volume of header tanks
- How the water from Oyster Bay is treated before reaching header tanks

**Comment by laurahspencer** [comment]
I do not have these details, but will also need it.  Can you copy me in your email to Ryan? Thanks!

**Comment by sr320** [comment]
Please add answer to this issue for future reference

**Comment by yaaminiv** [comment]
- The experimental system consisted of a 425 gallon storage tank that fed two 200 gallon header tanks. 
- Water from Oyster Bay, WA was pumped through a sand filter, then UV-treated. The UV-treated water passed through a set of three sock filters — 100 µm, 50 µm, and 25 µm — and a degassing column. Once degassed, water passed through three more sock filters — 25 µm, then 10 µm, and 5 µm — before entering the 425 gallon storage tank. The storage tank was outfitted with an off-gas vent and pump to recirculate water such that CO2 in the water could be equilibrated with atmospheric CO2.
