### ISSUE TITLE
Run crab samples through RNA-easy kit

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#327]
Please take 4 samples from D26 where we currently have triplicates and run through RNA-easy kit.

**Comment by kubu4** [comment]
@grace-ac - When you have a chance, please grab samples for me to process.

**Comment by kubu4** [comment]
RNA looks good (purity) and has OK yields.

http://onsnetwork.org/kubu4/2018/07/31/rna-isolation-tanner-crab-hemolymph-using-rneasy-plus-mini-kit/

**Comment by kubu4** [comment]
@grace-ac - I can't find sample 432 that I isolated yesterday. The two crab RNA boxes that I found are full, but 432 isn't in either one. Is there another box that I should look in?

**Comment by kubu4** [comment]
Found it; thanks!
