### ISSUE TITLE
Bioanalyze crab RNA samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#328]
Please run a chip with that includes Sam's samples and a random sampling of other RNA.

**Comment by grace-ac** [comment]
Electropherogram:   
![electropherogram](https://user-images.githubusercontent.com/14934314/43489813-12ba168e-94d3-11e8-80c9-9794bbd67ff1.PNG)

Gel:    
![gel](https://user-images.githubusercontent.com/14934314/43489819-18a703f4-94d3-11e8-8157-078204b839ad.PNG)


Previous notebook post from when I tried the Bioanalyzer out before: https://grace-ac.github.io/Bioanalyzer-Pubathon/

**Comment by kubu4** [comment]
Things look pretty crazy.

A couple of things:

1. No marker is showing up in any of the wells. Expect a tall, narrow, defined peak at ~20 - 23 seconds.

2. These have not been DNased, so it may not be surprising that these look crazy?
