### ISSUE TITLE
Bioanalyze crab RNA samples done with RNeasy kit

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#331]

**Comment by kubu4** [comment]
Done on RNA isolated with RNeasy Kit. RNA looks good to me!

Notebook: http://onsnetwork.org/kubu4/2018/08/01/bioanalyzer-tanner-crab-rna-isolated-with-rneasy-plus-mini-kit/

This has not been done with RNA that has been cleaned up with the RNeasy Kit.

**Comment by sr320** [comment]
Nice!
