### ISSUE TITLE
Xylene for Gigas Broodstock DNA Extractions

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#333]
Young lab is out of xylene, so I need to order some (pending approval!).

Product: https://www.sigmaaldrich.com/catalog/product/aldrich/214736?lang=en&region=US&gclid=EAIaIQobChMI-NSXyODM3AIVkP5kCh3x7AYmEAAYASAAEgK4ivD_BwE

**Comment by yaaminiv** [comment]
Biochem stores also has a 4L bottle for $50

**Comment by sr320** [comment]
Biochem stores is fine - charge to 66-4313

**Comment by kubu4** [comment]
I would get from Chemistry Stores instead, as they sell 500mL bottles. It's unlikely we'd ever use the entire 4L of xylene, so smaller quantity would be better.

**Comment by yaaminiv** [comment]
@kubu4 How do I order from the Chemistry Stores?

**Comment by kubu4** [comment]
Just like Biochem Stores - walk over there and buy the item you need. I think Chemistry Stores has a self-checkout system, so you'll need to ask the personnel there to add the budget number to your UW NetID account before you can walk out with the item.

Anyway, go there and just tell them it's your first time there and they'll get you all set up and show you how to find stuff. They're super friendly.
