### ISSUE TITLE
tube_numbers are wrong 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#337]
I want to combine these two files by "tube_number":    
- [20180801-Qubit-consolidated.csv](https://raw.githubusercontent.com/RobertsLab/project-crab/master/data/20180801-Qubit-consolidated.csv)   
- [20180522-all-crabs-hemo.csv](https://raw.githubusercontent.com/RobertsLab/project-crab/master/data/20180522-all-crabs-hemo.csv)

I changed the tube_number column to be read as numeric, and the files were able to be left_joined.

However, after looking through the file more closely, the tube numbers are wrong.

In [20180522-all-crabs-hemo.csv](https://raw.githubusercontent.com/RobertsLab/project-crab/master/data/20180522-all-crabs-hemo.csv), I made a column called "Uniq_ID". The unique ID's are made using the FRP, tube number, and sample day number. Formatted like this:     
FRP_tube#_d#      
Example: 6125_503_26

When I looked through the file [20180801-all-hemo-with-Qubit.csv](https://raw.githubusercontent.com/RobertsLab/project-crab/master/data/20180801-all-hemo-with-Qubit.csv), I noticed that the tube numbers in the column "tube_number" were wrong: different from the tube number listed in the "Uniq_ID" column:     
![20180802-wrong-tube-nums](https://user-images.githubusercontent.com/14934314/43609740-ad14a1d6-9659-11e8-8616-cb161014ff96.png)

[Rproject](https://github.com/grace-ac/crab-sample-selection/blob/master/crab-sample-selection.Rproj)

[Script](https://github.com/grace-ac/crab-sample-selection/blob/master/scripts/sample-selection.R)

**Comment by grace-ac** [comment]
wait- never mind. i think i figured it out.

**Comment by kubu4** [comment]
Please post solution.

**Comment by kubu4** [comment]
Did you reopen this because you still need help?

**Comment by grace-ac** [comment]
I did not figure it out. But I did figure out when the problem occurs:    

This file: [20180522-all-crabs-hemo.csv](https://raw.githubusercontent.com/RobertsLab/project-crab/master/data/20180522-all-crabs-hemo.csv) needs to have the tube_number column changed to be read as numeric.

## Before I change "tube_number" column to be read as numeric:    
![20180802-before-as-numeric](https://user-images.githubusercontent.com/14934314/43610731-d3146176-965b-11e8-823a-43ea795424fe.png)

## After I change "tube_number"  column to be read as numeric:    
![20180802-after-as-numeric](https://user-images.githubusercontent.com/14934314/43610748-de2a523c-965b-11e8-81b7-a769128a3f00.png)


Changing it to be read as.numeric is only necessary for the [20180522-all-crabs-hemo.csv](https://raw.githubusercontent.com/RobertsLab/project-crab/master/data/20180522-all-crabs-hemo.csv), and thus this is the file of the two that gets all weird, and causes the joining to be wrong.

**Comment by grace-ac** [comment]
I think I just need to find a different format for the as.numeric thing...

**Comment by grace-ac** [comment]
this is how yaamini showed me how to do it yesterday:    
![20180802-as-numeric-code](https://user-images.githubusercontent.com/14934314/43611447-f963dba2-965d-11e8-97ce-ab4a0a98a154.png)

**Comment by kubu4** [comment]
Oh, I see what's happening! This is an issue with converting a factor to numeric. As it turns out, factors are actually number representations. So, when you convert a factor to numeric, you're seeing the numeric representation of the value that was in a given field. It sounds convoluted (and, sorta is), but makes some sense if you read up on it.

Solution coming forthwith; hang on...

**Comment by kubu4** [comment]
I believe this factors junk is covered in the Software Carpentry R Lesson. I highly recommend going through that, if/when you have the chance (the whole lesson, not just the factors stuff).

**Comment by kubu4** [comment]
Use the following:

```as.numeric(levels(f))[f]```

I think you replace ```f``` with your column name?

**Comment by grace-ac** [comment]
how does it know which file I want this to happen in, though? 
It says:
```[1] NA```

I'll look for the software carpentry thing on this.

I cleared my R environment and re- read.csv the all-crab-hemo file. 

The column "tube_number" is still listed as being Factor:     
![20180802-new-as-num-still-fact](https://user-images.githubusercontent.com/14934314/43611922-9391c2d8-965f-11e8-8af7-ae7fd6d94ce5.png)

**Comment by kubu4** [comment]
I'm guessing you need to specify the data frame and corresponding column. 

E.g. ```as.numeric(levels(df1$column10))[df1$column10]```

**Comment by kubu4** [comment]
Also, it might be worthwhile to import your CSV file with this option specified:

```stringsAsFactors=FALSE```

If this works, then your column will be imported as numbers.

If it doesn't work, then your column will be imported as characters. If this is the case, then your previous solution of using the ```as.numeric()``` function will work to convert the column to numbers.

**Comment by kubu4** [comment]
On the import CSV options front, I'd add this option as well:

```header = TRUE```

Since your data has a header, you want this enabled (the default is ```header = FALSE```).

This might resolve your issue as well.

**Comment by kubu4** [comment]
Oops! Ignore my last comment!!! Seemed odd that ```header = FALSE``` would be default - I was accidentally reading the ```read.table()``` documentation!

**Comment by kubu4** [comment]
You can also try specifying the ```colClasses``` option in your ```read.csv()``` command:

```read.csv(file, colClasses=c("tube_number"="numeric"))```

**Comment by grace-ac** [comment]
```hemo_samples <- read.csv("../project-crab/data/20180522-all-crabs-hemo.csv", colClasses=c("tube_number"="numeric"))```

resulted in this error:      
```> read.csv("../project-crab/data/20180522-all-crabs-hemo.csv", colClasses=c("tube_number"="numeric"))
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  scan() expected 'a real', got '"60'```

**Comment by kubu4** [comment]
What about the two other possible solutions posted above that one?

**Comment by grace-ac** [comment]
## I think this one worked!! I didn't try this one til just now
1. 
```hemo_samples <- read.csv("../project-crab/data/20180522-all-crabs-hemo.csv", stringsAsFactors = FALSE)```

it changed the column tube_number to characters

---

2.
```hemo_samples <- read.csv("../project-crab/data/20180522-all-crabs-hemo.csv")
as.numeric(levels(hemo_samples$tube_number))[hemo_samples$tube_number]```

resulted in:     
```as.numeric(levels(hemo_samples$tube_number))[hemo_samples$tube_number]
  [1]  84 206 415  18 236 439  46 215 409  41 259 458  43 234 438   5 241 450 115 350 471   6 255 455  31 351
 [27] 480 135 331 488  90 356 468  28 317 499  78 214 419 142 326 484  33 307 514  76 212 417  42 225 440  87
 [53] 240 430 153 258 461 165 248 459  15 352 472 133 325 489  82 345 473  75 347 464 144 303 503  79 201 418
 [79]  37 335 497 112 231 441  86 299 403  47 339 498  38 314 507  88 205 406  36 223 434  77 353 465   4 327
[105] 492  91 321 491  81 301 500  80 247 453 104 332 493   8 237 429 123 249 451  65 346 474  10 343 479  14
[131] 348 477  59 305 505  12 309 502  30 204 421  56 213 405  64 226 437 119 312 511  19 243 454  32 344 467
[157]  11 209 404  68 232 436  66 358 476  24 242 446 169 224 423 101 324 483  26 313 508   7 238 426  53 302
[183] 512  61 220 407 130 228 424  71 257 460  55 360 469  21 349 496  45 207 414  27 357 466  57 328 486  70
[209] 320 516  73 221 427  NA 316 517  63 210 420  20 233 433  67 246 447  48 329 490  54 250 456 124 218 410
[235]  34 315 515 149 370 402 175 355 470 137 354 462 141 322 494 148 318 513 145 336 487 171 306 510 158 239
[261] 431 172 245 443 176 216 422 101 256 452  95 227 442 178 359 463 174 333 482  98 235 432 150 304 501 170
[287] 203 408 161 244 449 154 230 428 151 254 445  94 208 416 163 341 478 109 337 495 113 222 425 114 252 448
[313] 121 342 475 103 319 509 128 202 412 106 229 435 125 251 444 120 274 401 118 349 481 132 334 485 108 310
[339] 506 107 311 504  23 253 457  40 267 129 285  93 373 116 276 162 293  16 380   1 266  44 270  74 277  92
[365] 298  85 260  83 366  29 290  89 379  22 292 102 278  52 286 117 371   2 263  35 297 157 361  17 271   9
[391] 375 166 291 134 362  62 323  39 377 173 272  58 284 126 365   3 265 152 287  49 378  96 279  72 294 167
[417] 376  99 330  25 275  69 296 143 262 146 283 138 363 140 261 139 281 136 374 164 273 168 289 179 368 180
[443] 268 155 282 156 264 159 288  97 369 160 364 131 269 105 295 111 338 127 280 122 367 110 372  50 177 147
[469]  NA 413  13 219 411  NA  NA  NA
Warning message:
NAs introduced by coercion ```

And, the column tube_number is still listed as being: Factor

**Comment by grace-ac** [comment]
thank you @kubu4

**Comment by kubu4** [comment]
This is what your script would look like:


```
# Read in data.
hemo_samples <- read.csv("../project-crab/data/20180522-all-crabs-hemo.csv", stringsAsFactors = FALSE)

# Convert column to numeric
hemo$tube_number <- as.numeric(hemo$tube_number)

# Test that as.numeric conversion worked
is.numeric(hemo$tube_number)
```

**Comment by kubu4** [comment]
I just tested the example script above in R and it works (meaning, that column gets converted to numeric).

**Comment by grace-ac** [comment]
THANK YOU @kubu4 !!! it worked!!
