### ISSUE TITLE
Geoduck Tissue needed 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#34]
@emmats needs some tissue...
here is what we have.

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/-80_Inventory_Map_-_Google_Sheets_1F58BC77.png" alt="-80_Inventory_Map_-_Google_Sheets_1F58BC77.png"/>

I have going to look in rack 8 first...

**Comment by sr320** [comment]
@emmats 
I checked 8-1-3 and 8-1-4, both look like have tubes that would work for you..

**Comment by emmats** [comment]
I took sample 46 from box 8-1-4. Thanks!
