### ISSUE TITLE
Generate new Geoduck transcriptome

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#345]
August 13, 2018 at 04:45PM<br>

**Comment by kubu4** [comment]
Trinity run is throwing errors. 

Known issue: https://groups.google.com/forum/#!topic/trinityrnaseq-users/35SODUJX7bg

Have to install new version and re-run...

**Comment by kubu4** [comment]
Transcriptome is here: http://owl.fish.washington.edu/Athaliana/20180827_trinity_geoduck_RNAseq/Trinity.fasta

Notebook post coming soon. Will add link here when ready.

**Comment by kubu4** [comment]
Adding notebook entry:

https://robertslab.github.io/sams-notebook/2018/09/04/transcriptome-assembly-geoduck-rnaseq-data.html
