### ISSUE TITLE
Develop plan for first crab RNA-seq library

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#346]

**Comment by grace-ac** [comment]
what we have of the 40 Sam processed that have quantifiable RNA:

uninfected, cold: 5/10
infected, cold: 5/10
uninfected, ambient: 2/10
infected, ambient: 3/10

will update this comment more in a bit with the yields (ng) of those samples.

**Comment by grace-ac** [comment]
Some preliminary thoughts of mine so far: 

From these 15, we could:
- combine all 15 samples (1560.8 ng RNA)    
 
or       
- combine the cold treatment together (1200.8 ng RNA)

Combining the infected cold and infected ambient is very close to 1000ng (954 ng RNA).

Or we can try isolating RNA using the Qiagen Kit from the second tubes taken in triplicate and then hopefully have more than enough for these potential 4 libraries.

**Comment by grace-ac** [comment]
Update:

Combined all 15 samples into one pool. Volume is now at 150 ul.
Need to get the volume down to 50 ul 

Speed vac on medium started at 10:50 am 08/22/18

**Comment by sr320** [comment]
Be sure to get budget # if you have not already

**Comment by kubu4** [comment]
Also, you'll probably have to adjust the sample volume after SpeedVac-ing.

**Comment by grace-ac** [comment]
Thank you @kubu4 !

**Comment by grace-ac** [comment]
@kubu4 do you have the budget number? Or should I email Christie/Pam about it?

**Comment by kubu4** [comment]
33-4032

Review Pam's email for information regarding the use of this budget and the documentation required:

>Pam Jensen - NOAA Federal <pam.jensen>
>	
>May 22, 2018, 2:01 PM
>	
>to Steven, Sam, Grace
>
>Eek! Can't believe I forgot to mention this when we talked about UW sequencing. When AFSC uses the 33-4032 budget, we get BARs & BSRs from them, but everything is lumped together such that our admin people can't tell what I spent from what someone else at AFSC spent. So, it's critical to get an invoice/receipt/estimate/whatever from the sequencing facility when samples are turned in, services scheduled, etc., that I can turn in here at AFSC. It doesn't have to be an 'official' invoice, but should have a date & amount as close to the actual cost as possible. (An order confirmation with handwritten info added would work). Otherwise, AFSC admin will assume that other charges that no one is claiming (there are always some), belong to whoever is convenient & has 'other' missing receipts, & we could end up paying for someone else's charges.

**Comment by grace-ac** [comment]
UPDATE!!! WE HAVE ENOUGH RNA IN THE POOL!!

Sample is 53 ul and has 1,020ng of RNA!!

I am going to call/email the NWGC to get clearer instructions of what is required in order for us to walk over the sample for library prep and sequencing.

**Comment by grace-ac** [comment]
2:45 pm
Handed sample (on dry ice) over to Chris at the Nickerson Lab in Foege. I gave him a bunch of information on the sample, as well as contact info. 

He's going to email me (I'll forward to you two and keep you all in the loop) regarding a quote and what type of sequencing we want.

**Comment by grace-ac** [comment]
From Chris:  

```The library will be stranded and we'll do a poly-A selection as well.  Sequencing will be PE100 on either the NovaSeq or the HiSeq4000.  Its your choice which platform you would like to use.  The turn around on the NovaSeq is usually faster and the price is almost half the cost of a run on the 4000.  Let me know what you think. ```

**Comment by kubu4** [comment]
$632.20 for sequencing. Give the go-ahead?

![selection_064](https://user-images.githubusercontent.com/4514104/44689226-9d95c300-aa0b-11e8-987e-d0cfc5919539.png)

**Comment by kubu4** [comment]
This includes a minimum of 50M reads, btw.
