### ISSUE TITLE
Can I borrow the DynaMag rack?

### ISSUE THREAD

**Issue by jldimond** [RobertsLab/resources#348]
I'm going to be doing some library prep at Shannon Point next week. Does anyone have plans to use the rack in the next week or so, and would it be possible for me to borrow it?

**Comment by sr320** [comment]
You can borrow

**Comment by jldimond** [comment]
Thanks - I actually ended up getting a cheapo on ebay. Probably a good idea
for us to have one here anyway. If it doesn't work well I will go for the
DynaMag.
