### ISSUE TITLE
Merge columns in R?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#349]
I added the Qubit RNA HS results from the 40 samples Sam processed. I did this by "left_join" by the tube_number with the [20180813-all-hemo-with-Qubit.csv](https://raw.githubusercontent.com/RobertsLab/project-crab/master/data/20180813-all-hemo-with-Qubit.csv).

However, it added repeat columns (I deleted the ones that aren't important):     
![screen shot 2018-08-16 at 11 55 58 am](https://user-images.githubusercontent.com/14934314/44229016-9fc66a80-a14b-11e8-8c95-a378b2c00082.png)

Is there a way in R to merge information in "Test_Date.x" with "Test_Date.y" and "Original_sample_conc_ng.ul.x" with "Original_sample_conc_ng.ul.y" so that there aren't repeats. I'll have to keep adding more Qubit information as isolations continue. 

Materials:    
Sam's Qubit results copied into a csv: [here](http://owl.fish.washington.edu/scaphapoda/grace/Crab-project/results_from-Sam.csv)
RAW Hemo and Qubit file (currently has Sam's results added): [here](https://raw.githubusercontent.com/RobertsLab/project-crab/master/data/20180813-all-hemo-with-Qubit.csv)
Rproject: [here](https://github.com/grace-ac/crab-sample-selection/blob/master/crab-sample-selection.Rproj)

**Comment by grace-ac** [comment]
I think I found a merge thing... reading about it now. If I figure it out, I'll post here and close issue

**Comment by sr320** [comment]
use select to select columns you want 

newfile <- left_join(RNA, qpcr, by = "FRP") %>%  select(columnsyouwant)


Note it is helpful if you can point to a script we could run on our machines (repo-based)

**Comment by kubu4** [comment]
Also, when linking to an R Project, please link to the repo (i.e. the project), not the ```.Rproj``` file.

**Comment by sr320** [comment]
or possibly select before you join- might be more logical ....

http://r4ds.had.co.nz/transform.html#select

**Comment by grace-ac** [comment]
Raw script (last four lines): [here](https://raw.githubusercontent.com/grace-ac/crab-sample-selection/master/scripts/sample-selection.R)

R Project repo: [crab-sample-selection](https://github.com/grace-ac/crab-sample-selection)

**Comment by sr320** [comment]
so we can't run this.

hint
`qSam <- read.csv("../../../Desktop/results-from-Sam.csv")`

**Comment by grace-ac** [comment]
yeah, that's where the link to OWL comes in: http://owl.fish.washington.edu/scaphapoda/grace/Crab-project/results_from-Sam.csv

Sorry, I meant to change that before posting all this!

**Comment by grace-ac** [comment]
Wait, does the file have to be in my R Project GitHub repo?

**Comment by grace-ac** [comment]
If yes, I added it to the R Project repo anyway

**Comment by kubu4** [comment]
Try a "mutating" join (I have note tried):

(requires ```dplyr``` library to be loaded)

```updated <- hemoqub %>% left_join(qSam, by = "tube_number")```

**Comment by grace-ac** [comment]
Thank you for the heads up, @kubu4 ! So true. I'll start working on making this more user-friendly! :) 

"Mutating" join note: 
The above still gave me duplicate columns "Test_Date.x", "Test_Date.y" and "Original_sample_conc_ng.ul.x", "Original_sample_conc_ng.ul.y". 

![screen shot 2018-08-16 at 1 22 52 pm 2](https://user-images.githubusercontent.com/14934314/44233069-b4106480-a157-11e8-9059-37b3804629fd.png)

**Comment by kubu4** [comment]
Your script references this file, but I can't find it: 

```hemoqub <- read.csv("../project-crab/data/20180802-all-hemo-with-Qubit.csv")```

**Comment by grace-ac** [comment]
Oh yikes... I've made a mess. Yeah, that file doesn't exist in the repo anymore :( 

So I reverted "20180813-all-hemo-with-Qubit.csv" back to the version before I left_join"ed" your Qubit results... , so that should now be     
```hemoqub <- read.csv("../project-crab/data/20180813-all-hemo-with-Qubit.csv")```

Maybe I'll clean things up first and then we can work on this more! Sorry!

**Comment by kubu4** [comment]
These two dataframes are difficult to work with for joining/merging because the column names for the same content differ:

e.g. 

 ```qSam``` : Test.Date

```hemoqub``` Test_Date

I believe the ```merge()``` function allows you to specify multiple columns, but is dependent upon the columns having the same names in each dataframe. Maybe try renaming columns in each dataframe so that they're the same in both and then try something like:

```merge(x = hemoqub, y = qSam, by = "c(tube_number, Test_Date, Original.sample.conc.)", all.x = TRUE)```

**Comment by kubu4** [comment]
Unrelated to this specific topic, but encountered when trying to investigate, I was unable to read in the following file:

```crab-sample-selection/20180813-results_from-Sam.csv```

It threw a weird "invalid multibyte string error". To resolve, I had to run the following and then read in the file:

```Sys.setlocale("LC_ALL", "C")```

I believe this is related to the "Rights Reserved" character and the mu (micro) characters present in the file. It might be a good idea to remove those characters to ensure compatibility.

**Comment by grace-ac** [comment]
Yes, I updated the column names and replaced µ with u, but likely after you starting working with the data sets. I'll try out the merge thing!

**Comment by sr320** [comment]
I would still like to see select and join as opposed to merge.

**Comment by kubu4** [comment]
Merge command is formatted incorrectly, sorry. Fix is below:

```merge(x = hemoqub, y = qSam, by = c("tube_number", "Test_Date", "Original.sample.conc."), all.x = TRUE)```

**Comment by kubu4** [comment]
Now that we've typed all of this out, I don't think you can accomplish what you'd like to accomplish using join/merge. I believe the main goal is to have a single column for a given set of data (e.g. a single column with ```Test_Date``` data for all tubes).

I don't believe you'll be able to achieve this via a join/merge because the computer doesn't know which value to keep. 

For example, should it keep the empty/NA value from the ```qSam``` dataframe or the date value from the ```hemoqub``` dataframe when joining? The computer won't make a decision like this, so it creates two versions of the "same" column.

**Comment by grace-ac** [comment]
The fixed merge worked! I'll work on fixing my repos and scripts so it's easier for collaboration and help next time I get stuck.

**Comment by sr320** [comment]
where is `/project-crab/data/20180813-all-hemo-with-Qubit.csv`

**Comment by grace-ac** [comment]
it's there!     
If you mean the new one that has been merged, it's [20180816-all-hemo-with-Qubit.csv](https://raw.githubusercontent.com/RobertsLab/project-crab/master/data/20180816-all-hemo-with-Qubit.csv) and will replace the one from 20180813.

**Comment by sr320** [comment]
We should talk about file naming also- let’s go over this tomorrow

**Comment by kubu4** [comment]
> where is /project-crab/data/20180813-all-hemo-with-Qubit.csv

> it's there!

I'm guessing @sr320 is having the same problem that I pointed out [here](https://github.com/RobertsLab/resources/issues/349#issuecomment-413673851).

**Comment by sr320** [comment]
one of the two files you are referring to here

`20180813-all-hemo-with-Qubit.csv`

is not in the repo

https://github.com/grace-ac/crab-sample-selection

**Comment by grace-ac** [comment]
oh, I see. 

Yeah, that'll be fixed once I re-organize where I keep the R Project. Or if I clean up the script and ad the ```download.file()``` thing Sam was referring to. 

I didn't realize how confusing this would be for other people to work with! Learning a lot

**Comment by grace-ac** [comment]
I take it back, merge messed things up a bit. 

It messed up the tube_number column     
![mess-up-tube-numbers](https://user-images.githubusercontent.com/14934314/44288512-6f52ff00-a225-11e8-802d-19141ecb4880.png)

The tube numbers got moved into a new column called "X". 

---
### Sidenote
---
I think I've figured out a cleaner and easier way of doing this all, though. Detailed in my notebook post today, but essentially I made a new [R Project](https://github.com/RobertsLab/project-crab/blob/master/project-crab.Rproj) and [R Script](https://github.com/RobertsLab/project-crab/blob/master/project-crab_join_files.R) in the [project-crab](https://github.com/RobertsLab/project-crab) repo. 

All the files needed to do the joins already exist in that repo. 

New script:     
```
library(dplyr)
library(tidyverse)

# Script for creating joined and merged data files from project-crab. Ultimate goal is to create a true master file of all crab-related data files in this repo. 

# Join all hemolymph sampling data with Qubit RNA HS results data into one file. 

# read in all-crabs-hemo.csv
hemo <- read.csv("data/20180522-all-crabs-hemo.csv")
# read in Qubit-results.csv
qub <- read.csv("data/20180817-Qubit-results.csv")

# Convert "tube_number" in hemo.csv numeric (not factor)
hemo$tube_number <- as.numeric(hemo$tube_number)

# test that as.numeric conversion worked
is.numeric(hemo$tube_number)

# Join files based on column "tube_number"
master <- left_join(hemo, qub, by = "tube_number")

# Look at columns in master file
colnames(master)

# Select columns that are useful and relevant
master2 <- master %>%
  select(year.FRP, FRP, infection_status, Uniq_ID, sample_day, infection_status, maturity, Holding_Tank, Low_Tag, High_Tag, sample, treatment_tank, where, tube_number, Comments, death, comments, CW, SC, CH, Test_Date, Original_sample_conc_ng.ul, total_sample_vol_ul, total_yield_ng) %>%
  arrange(FRP)

# Write updated csv to project-crab data repo. 
write.csv(master2, "20180817-hemo-Qubit.csv")

# Move new csv to data directory in repo project-crab and update readme.md
```
