### ISSUE TITLE
Removing samples from middle -80

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#35]
There should not be anything in the middle -80, there looks like some of our stuff is there.
This should be moved to left -80, following protocol.

**Comment by sr320** [comment]
@laurahspencer - if I recall you had samples that needed moving?

**Comment by laurahspencer** [comment]
Yes correct, @yaaminiv and my samples from the last mass spec run are in the middle freezer.  I'll move mine tomorrow to the left freezer.

**Comment by sr320** [comment]
And please make sure to add to inventory sheet...

**Comment by laurahspencer** [comment]
@grace-ac are there any more cardboard boxes that fit into the -80 "cabinets" hiding somewhere?  I checked the usual spots, with no luck.

**Comment by grace-ac** [comment]
There may be some in the -80 room on the shelves across from the
freezers...

If there aren't any on that shelf in 209, then I don't know of any others!

**Comment by yaaminiv** [comment]
Sorry about the delay but I FINALLY moved my samples out of the middle -80. I'l update the inventory map as soon as I get edit access!

**Comment by kubu4** [comment]
>I'l update the inventory map as soon as I get edit access!

Done. Invite sent to UW email addy. Please let me know if you have a different address you'd prefer to use.

**Comment by yaaminiv** [comment]
Thanks! Just updated the inventory sheet.
