### ISSUE TITLE
Improved hemo data sheet. Any more changes needed?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#350]
R script: https://github.com/RobertsLab/project-crab/blob/master/scripts/all-hemo-fixing.R

Changed treatment_tank numbers to words. Removed columns that don't mean much.

Anything else need changing to make this better? 

```
# Script for making a clean and valuable data sheet to join new data with as project continues

library(dplyr)
library(tidyverse)

hemo <- read.csv("data/20180522-all-crabs-hemo.csv")
colnames(hemo)

# select relevant columns
newhemo <- hemo %>%
  select(year.FRP, FRP, Uniq_ID, sample_day, infection_status, maturity, treatment_tank, tube_number, Comments, death, comments, CW, SC, CH) %>%
  arrange(FRP)

# Need to change treatment_tank numbers to words. Numbers 1, 2, 3 are COLD; Numbers 4, 5, 6 are WARM; Numbers 7, 8, 9 are AMBIENT. 

newhemo2 <- mutate(newhemo, trtmnt_tank = ifelse(treatment_tank == 1 | treatment_tank == 2 | treatment_tank == 3, "cold", ifelse(treatment_tank == 4 | treatment_tank == 5 | treatment_tank == 6, "warm", "ambient")))

newhemo3 <- newhemo2 %>%
  select(year.FRP, FRP, Uniq_ID, sample_day, infection_status, maturity, tube_number, Comments, death, comments, CW, SC, CH, trtmnt_tank) %>%
  arrange(FRP)
```

**Comment by kubu4** [comment]
Dang! Looks pretty solid! Killer use of```ifelse()```!

I think the ```death``` column should be something more accurate like ```death_date```. Additionally, it seems like there are "Comments" in the ```death``` column; I don't think they should be there. Speaking of this ```death``` column, where is the original data that was copied/pasted to create ```20180522-all-crabs-hemo.csv```? I want to see what's in the ```death``` column in that sheet.


But, on that note, I think you can probably ditch the following columns:

- ```sample```: There's nothing in this column.

- ```comments```: This one, with the lowercase "c" has nothing in it.

- ```Comments```: This one, with the uppercase "C" doesn't really have any useful info.

- ```maturity``` or ```Im.mat```: These are duplicates; only need one (if we even need one).

- ```death```: Not sure this is actually needed.

- ```where```: Not needed.

- ```Low_Tag``` & ```High_Tag```: Don't think we need either of these.

- ```treatment_tank```: With the fancy conversion to ```trtmnt_tank```, this is no longer needed.

**Comment by grace-ac** [comment]
The hemolymph sampling data is from Pam's excel sheet: https://github.com/RobertsLab/project-crab/blob/master/data/20180125-NPRB-crab-sample-data.xlsx 

Specifically, the tab labeled "all crabs". 

@sr320 showed me the ifelse thing a while back! Had it saved in an old script

**Comment by grace-ac** [comment]
oh! and as far as the "death" column goes, I added that name to the column that has all the dates that the crabs died. I am seeing that there are also some comments in that same column...

**Comment by sr320** [comment]
I edited the script a bit. But agree might be able to move some columns

**Comment by sr320** [comment]
Note you will need to pull to get my edits
