### ISSUE TITLE
Download Geoduck Assembly and related files

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#351]
There are a lot of files on Gdrive. 

Can you get these are on our NAS (if not already) and try to make sense of what they all are?

I want to be able to document files soon in case we have questions.

**Comment by kubu4** [comment]
Everything is downloaded.

Most recent assembly: 

- [geoduck_manual_scaffolds.fasta](http://owl.fish.washington.edu/Athaliana/20180822_phase_genomics_geoduck_Results/geoduck_manual/geoduck_manual_scaffolds.fasta)

Notebook: http://onsnetwork.org/kubu4/2018/08/23/assembly-stats-geoduck-hi-c-final-assembly-comparison/

FastQ files from sequencing effort are already in nightingales (Geoduck_HiC*.fastq.gz)

**Comment by kubu4** [comment]
> try to make sense of what they all are?

I think this part will require some info from Phase Genomics, as no README files have been provided. Other than the FastA and FastQ files, it seems like most other files are various assembly stats. However, I'm not sure what to do with that info.
