### ISSUE TITLE
ID Transposable Elements in C virginica genome

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#352]
Genome @ https://github.com/RobertsLab/resources/wiki/Genomic-Resources#genome-1

**Comment by kubu4** [comment]
Should've clarified first, as I've already started this using the v300 genome.

Do you want me to use the NCBI version instead (or, run on both)?

**Comment by kubu4** [comment]
Done with v300 genome:

http://onsnetwork.org/kubu4/2018/08/28/transposable-element-mapping-crassostrea-virginica-genome-cvirginica_v300-using-repeatmasker-4-07/

Of note, I ran this with four different species settings:

1. all
2. Crassotrea gigas
3. Crassostrea virginica
4. default (i.e. human genome)
