### ISSUE TITLE
Perform qPCR assay to test shellfish primers

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#353]
In an effort to become familiar with qPCR

lets run a few assay

see https://docs.google.com/document/d/1MlSBLkd302oXpfuoNpPR1ZQ31mTg3R9Z1je-VNsjCWk/edit?usp=sharing

Starting with Cgigas primer/probes

**Comment by laurahspencer** [comment]
FYI: this will likely be helpful/pertinent to Alanna's capstone project
