### ISSUE TITLE
Roberto bisulfite sequencing considerations

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#354]
Quotes have been requested from ZymoResearch.

Based on past sequencing from Zymo (50bp PE, 20M reads minimum), here are some things to consider:

- C.gigas genome is 558Mbp.

- 50bp PE

- 20M reads = ~1.75x coverage

- 25M reads = ~2.25x coverage

- 30M reads = ~2.65x coverage

It might be worth considering paying more upfront for a higher minimum reads guarantee, instead of waiting around for sequencing results, running analysis, and then deciding we need more sequencing to achieve the desired coverage threshold.

**Comment by kubu4** [comment]
ZymoReseach quote for ~60M reads (~5x coverage) per library (12 libraries) is $13,338.

This is bisulfite conversion, library prep, QC, and sequencing.

**Comment by kubu4** [comment]
Want to evaluate Oly coverage from past whole genome BSseq before deciding.

**Comment by sr320** [comment]
WGBS Oly is about 10M reads / library (raw) (SE)

**Comment by sr320** [comment]
I am thinking about maybe going enzyme route

**Comment by sr320** [comment]
What are the DNA quantities?

**Comment by sr320** [comment]
Thinking this enzyme based method might be good
https://d.pr/f/WabBpN

**Comment by kubu4** [comment]
Initial costs:

KAPA HiFi Kit - 50 rxns: $265
T4 DNA Ligase: $256
DNA polymerase: $68
Csp61: $39
Ampure XP beads: $416
QIAquick PCR Purification Kit: $105
EZ DNA Methylation Lightning Kit: $193
5-mC dNTPs: $62
Methylated primers (from IDT): ~$610 ea (x 4 = $2400)
Illumina primers: ~$10 each (x 2 = $20)

Total upfront costs: ~$4100

**Comment by sr320** [comment]
Just talked to Zymo - they indicate since August for same price we can get 20-50x coverage with WGBS- they are resending the quote.

**Comment by kubu4** [comment]
Well that's something! Dang!

**Comment by kubu4** [comment]
Genewiz quote:

$6728 for 12 samples with 30x coverage. That pricing includes a $1600 "promotional" discount. Still would be cheaper than Zymo at "full" price.

**Comment by sr320** [comment]
Do you know what quantity of DNA Genewiz needs?

**Comment by kubu4** [comment]
Min 500ng, 20ng/uL

**Comment by kubu4** [comment]
I'm in the process of getting clarification on this, but after reviewing the Genewiz quote more carefully, I'm dubious they've quoted this project correctly.

I'll explain why I have my doubts:

- C.gigas genome = 560Mbp

- 30x coverage: 560Mbp x 20 = 16.8Gbp

- Quote indicates 350M, 150bp reads (paired-end) per lane: 350M reads per lane x 150bp per read = 52.5Gbp per lane.

- Quote is unclear, but suggests two lanes: 52.5Gbp per lane x 2 = 105Gbp of sequence

- Based on quote: 105Gbp/12 libraries = 8.75Gbp per library

So, if I've done the math correctly, that looks like ~15x coverage, which is not what was requested (30x coverage is indicated on top of the quote).

So, what I'm getting at is I think a revised quote will likely be more expensive and probably on par with Zymo's. Hoping to have an answer soon...

**Comment by sr320** [comment]
Submitted to Genewiz

**Comment by kubu4** [comment]
Estimated data availability is 3/25/2019.

**Comment by kubu4** [comment]
Sample QC report from Genewiz (i.e. should we have them treat with RNase  $20/sample or proceed directly with library prep/sequencing?):

>ngs@genewiz.com
>	
>Attachments7:48 AM (1 hour ago)
>	
>to samwhite, Kari.nelson, ngs

>Hi Samuel,

>The sample QC for project # 30-183897003 has been completed. 

>Please review the attached DNA Qubit concentrations and gel images below.  A spot check for RNA contamination was also performed (please see RNA Qubit columns H,I,J,K in the attached excel).

>    All 16 samples meet our quantity requirements for WGBS library preparation.  
>    Samples spot checked for RNA contain >10% of RNA. For methylation sequencing, we recommend RNase treatment for all 16 samples. This service incurs a cost of $20/sample and a 3-5 business day increase in the turn around time. 
>    Please indicate how you would like to proceed. 
>        Option 1: Proceed with RNase treatment prior to library preparation.
>        Option 2: resubmit samples.
>        Option 3: proceed to library preparation directly.

**Comment by sr320** [comment]
Option 1: Proceed with RNase treatment prior to library preparation.

**Comment by kubu4** [comment]
Genewiz update: April 5th is new date. Sequencer had a technical issue and needed servicing.

**Comment by kubu4** [comment]
Data received. Transferring, verifying MD5s, and adding to nightingales.

**Comment by kubu4** [comment]
@yaaminiv - Your data is here:

http://owl.fish.washington.edu/nightingales/C_gigas/YRVA_R1_001.fastq.gz
http://owl.fish.washington.edu/nightingales/C_gigas/YRVA_R2_001.fastq.gz
http://owl.fish.washington.edu/nightingales/C_gigas/YRVL_R1_001.fastq.gz
http://owl.fish.washington.edu/nightingales/C_gigas/YRVL_R2_001.fastq.gz


@shellytrigg - Your data is here:

http://owl.fish.washington.edu/nightingales/C_gigas/Tank2-025-026_R1_001.fastq.gz
http://owl.fish.washington.edu/nightingales/C_gigas/Tank2-025-026_R2_001.fastq.gz
http://owl.fish.washington.edu/nightingales/C_gigas/Tank3-15-16_R1_001.fastq.gz
http://owl.fish.washington.edu/nightingales/C_gigas/Tank3-15-16_R2_001.fastq.gz

**Comment by kubu4** [comment]
Also, @shellytrigg and @yaaminiv: 

Also, of importance, are trimming guidelines for these sequences. [Hollie contacted Genewiz about their library prep](https://genefish.slack.com/archives/CD9M5LSFK/p1552084666004400) and learned they use the [Accel-NGS Methyl-Seq DNA Library Kit (Swift)](https://swiftbiosci.com/products/accel-ngs-methyl-seq-dna-library-kit/accel-ngs-methyl-seq-dna-library-kit/). Swift provides a [technical bulletin on trimming](https://swiftbiosci.com/wp-content/uploads/2016/09/16-0853-Tail-Trim-TN.pdf) and indicates the following:

> Trimming 10 bases from the beginning of both R1 and R2 _following_ adapter trimming eliminates the majority of Adaptase tails.

**Comment by kubu4** [comment]
All of Roberto's samples fail the "Per Tile Sequence Quality" FastQC module. I've contacted Genewiz about this.

![](https://github.com/RobertsLab/sams-notebook/blob/master/images/screencaps/20190415_fastqc_tile_fail-01.png?raw=true)

**Comment by kubu4** [comment]
Genewiz produced an 25% additional reads as compensation for potential read loss due when quality trimming. The data has been appended to the previous sequencing files. I've uploaded the new files to `owl/nightingales/C_gigas`. I'm generating updated FastQC/MultiQC reports as I type this.
