### ISSUE TITLE
Improve Oly genome annotation with ab initio gene predictors

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#355]
Update Oly genome annotation by "training" the SNAP gene predictor. This should improve delineation of gene features.

**Comment by sr320** [comment]
fyi - current separated tracks at https://github.com/RobertsLab/resources/wiki/Genomic-Resources%23genome-feature-tracks-2

also igv session file available to load all tracks in one step.

**Comment by kubu4** [comment]
@sr320 - Don't spend too much time on dealing with the current Maker assembly. I think I've found a more detailed Maker workflow that will tidy things up (this is in addition to the _ab initio_ gene prediction stuff.

**Comment by kubu4** [comment]
Well, looks like this _ab initio_ gene prediction isn't going to happen.

Based on a response in this thread (http://gmod.827538.n3.nabble.com/Maker-td4046873.html), it looks like we might just be out of luck with this current draft of the genome.

Here's the response to someone else who gets the same results (i.e. empty files when converting GFF to ZFF in Maker):

>The lack of fasta files means that you have no final gene models.  Either your contigs are too short to produce a model, or your evidence alignments are insufficient in end-to-end coverage, splice site recovery on polishing, or %identity, so maker cannot elucidate a usable model from alignment alone.

So, back to final annotation/curation "by hand."

**Comment by kubu4** [comment]
I figured out some changes to make and think this might work. Will report back next week...

**Comment by sr320** [comment]
Seems like we are letting this go for now.
