### ISSUE TITLE
R Project management on GitHub?

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#359]
Need some insight.

How would you go about retrieving and running the R Project I've saved on GitHub?:

https://github.com/RobertsLab/code/tree/master/r_projects/sam/20180827_oly_methylkit

**Comment by sr320** [comment]
Ah - you saved it inside a larger repo... always wondered how this might work

**Comment by kubu4** [comment]
Yep. I also was wondering how it would work (or, not!). Not sure I want to end up with a billion individual repos for each analysis using an R Project...

**Comment by sr320** [comment]
delayed in trying - https://github.com/RobertsLab/resources/issues/360

**Comment by sr320** [comment]
Easiest way to retrieve and run is using whole repo
https://github.com/RobertsLab/code.git
as version control project.
then navigating to folder of interest

**Comment by kubu4** [comment]
Yeah, that's what I was afraid off. Kind of cumbersome...

Thanks for testing!

Anyone else want to chime in/discuss before I close this issue?

**Comment by sr320** [comment]
I would say it is the least cumbersome... once you navigate to directory;
feels like single repo.

**Comment by sr320** [comment]
offtopic but code does not appear to work 

```
> # Download deduplicated, sorted, BAM files
> download.file("http://owl.fish.washington.edu/Athaliana/20180709_oly_methylseq/1_ATCACG_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam", destfile = "./data/1_ATCACG_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam")

downloaded 0 bytes

Error in download.file("http://owl.fish.washington.edu/Athaliana/20180709_oly_methylseq/1_ATCACG_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam",  : 
  cannot download all files
In addition: Warning messages:
1: In download.file("http://owl.fish.washington.edu/Athaliana/20180709_oly_methylseq/1_ATCACG_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam",  :
  URL http://owl.fish.washington.edu/Athaliana/20180709_oly_methylseq/1_ATCACG_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam: cannot open destfile './data/1_ATCACG_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam', reason 'No such file or directory'
2: In download.file("http://owl.fish.washington.edu/Athaliana/20180709_oly_methylseq/1_ATCACG_L001_R1_001_trimmed_bismark_bt2.deduplicated.sorted.bam",  :
  downloaded length 0 != reported length 218171085
```

**Comment by kubu4** [comment]
Strange. I downloaded the files using that script...

**Comment by kubu4** [comment]
> I would say it is the least cumbersome... once you navigate to directory; feels like single repo.

It's OK. I just feel like it requires a bit more effort and configuring than I would like. For example, the if someone follows the link I posted above, it might not be obvious to them how to get that folder downloaded. Particularly since the GitHub clone button is only presented at the root directory of the entire repo. 

But, maybe I'm overthinking it. I mean, who's really going to be accessing these, right? Mainly our lab, and most of us already have these various repos cloned already...

**Comment by kubu4** [comment]
I just downloaded the first of the files while sitting at eScience Institute. No issues. Not sure why it's failing on your end.

![screenshot from 2018-08-30 11-36-27](https://user-images.githubusercontent.com/4514104/44871914-07e77700-ac49-11e8-856d-6d11ae4f9e8a.png)

**Comment by kubu4** [comment]
Thanks for feedback.
