### ISSUE TITLE
System for backing up GoogleDoc Sheets

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#36]
There are large inventory lists etc that live on google docs. 
I suggest we list them here and decide if routine backup is necessary.

**Comment by kubu4** [comment]
This can be done using Eagle/Owl "Cloud Sync". However, I'm not sure if you can target individual files; it might just be an entire directory. Will have to double check.

**Comment by sr320** [comment]
@grace-ac can you compile the list of sheets...

**Comment by grace-ac** [comment]
Here is a list of all the ones that I personally am aware of:

-80 inventory: https://docs.google.com/spreadsheets/d/1Qsvz3QTURlPF_hX05BQxjom3484WuMfqQ1ILl9LEljU/edit#gid=2006985773 

Lab Inventory: https://docs.google.com/spreadsheets/d/11RA_mlLB-3m_GySnTTuDazDdOi0bCxJu2VERuX9Qfx8/edit#gid=0 

Roberts Lab Purchasing Log:
https://docs.google.com/a/uw.edu/spreadsheets/d/1DHXiiEzWhh0XHnEMvKz4TX10e69ErOWHv5Jo-ouk6x8/edit?usp=drive_web

Primer Stocks:
https://docs.google.com/spreadsheets/d/1Tu1c9mzJFjL2vN5xwQctRLGQhLRNB0heha5ZQMrNsOA/edit#gid=8

Primer Database:
https://docs.google.com/spreadsheets/d/14m2kkFhxcoKWWIGoAD_7VOVsAg9wilME2UcSLqfnqLI/edit#gid=0
