### ISSUE TITLE
Git not working with Rstudio

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#360]
I cannot get git to work with Rstudio..

Says git is not in path (but it is) and indicates I can set in Preferences (which I did) 
but still nothing.

https://d.pr/i/ttMR46

any ideas?

**Comment by kubu4** [comment]
GIF resolution is a bit too low; can't read text. Or, can you repeat and zoom in Terminal and R Studio?

**Comment by kubu4** [comment]
Is it possible that R Studio was started before an update to you PATH was made? I.e. R Studio may be using a previous version of your PATH, if your PATH was updated while R Studio was already open. Restart R Studio and see if that helps (if you haven't done this already).

**Comment by sr320** [comment]
fixed...
I think it was related to an OS update...
see https://github.com/jennybc/happy-git-with-r/issues/8

I switched to git terminal was using in Rstudio. 
..
nothing..
re-installed xcode

Rstudio was using different git vs terminal, but could not revert so reset Rstudio prefs with

`mv ~/.rstudio-desktop ~/backup-rstudio-desktop`

restarted - worked..


I think the key was needing to reinstall xcode clt after OS upgrade.

**Comment by kubu4** [comment]
Had an issue with git and needing to install xcode clt yesterday in Software Carpentry for someone on a Mac. Almost suggested this!
