### ISSUE TITLE
Github notebook posts not showing up on bittercrab.science

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#363]
Since Aug 1, no new posts have shown up on:

https://bittercrab.wordpress.com 

Github.io notebook: https://grace-ac.github.io

The way that I tag posts that have to do with the crab project is as follows:

```
layout: post
title: TITLE
date: '2018-09-05'
category: bairdi
tags: RNAisolation
```

OR

If i have a post that has both crab and Oysterseed DIA info in it, I do the category as follows:     
```
categories: [bairdi, 2015Oysterseed]
```

**Comment by sr320** [comment]
currently this is not automatic, I post manually to weed out non crab samples....

**Comment by sr320** [comment]
You also have ability to do this at Wordpress site. Just to to blog posts -> drafts -> and publish the ones you would like.

**Comment by grace-ac** [comment]
oooooh ok. thought you had the IFTTT still set up. 

thank you!

**Comment by sr320** [comment]
correct ifttt pushes them as drafts to bittercrab
