### ISSUE TITLE
blastx: Saving results, reducing run time

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#365]
In my infinite wisdom, I never properly saved my `blastx` results when I blasted the *C. virginica* genome against the Swiss-prot database (see [lab notebook](https://yaaminiv.github.io/DML-Analysis-Part5/)). My [previous notebooks](https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/notebooks/2016-10-28-oly-gonad-OA-part-2-BLAST.ipynb) never included code on how to save those results. I'm wondering if I could just do the following:

`````
/Users/Shared/Apps/ncbi-blast-2.2.29+/bin/blastx -query analyses/2018-04-27-Bismark/2018-04-27-Bismark-Inputs/C_virginica-3.0_genomic.fa -db analyses/2018-06-11-DML-Analysis/uniprot-filtered-reviewed.fasta -outfmt 6 > 2018-09-06-Virginica-Genome-blastx
`````

Also, is there a way to specify how many CPUs to use so the `blastx` completes sooner?

**Comment by sr320** [comment]
Lot going on here, but first, why blast genome to Swiss-Prot?

**Comment by yaaminiv** [comment]
I wanted to get Uniprot accession codes for gene enrichment. The output should be used as the background for the tool Mike Riffle built for our project, or even as the background list in DAVID.

**Comment by yaaminiv** [comment]
The R Markdown file I'm working in can be found [here](https://github.com/RobertsLab/project-virginica-oa/blob/master/analyses/2018-06-11-DML-Analysis/2018-06-14-Gene-Enrichment-Analysis.Rmd)

**Comment by kubu4** [comment]
```blastx -help``` is your friend.

You'll need:

- ```-out <filename>```: Specify output filename and location

Recommended:

- ```-num_threads <Integer, >=1>```
   Number of threads (CPUs) to use in the BLAST search
   Default = `1'

- ```-max_target_seqs 1```
   Maximum number of aligned sequences to keep 
   Not applicable for outfmt <= 4
   Default = `500'
