### ISSUE TITLE
Combine LSU oil MBD-BS libraries and run fastqc on untrimmed reads

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#366]
http://onsnetwork.org/kubu4/2015/02/09/sequencing-data-lsu-c-virginica-mbd-bs-seq/

**Comment by kubu4** [comment]
Done.

Notebook: 

- http://onsnetwork.org/kubu4/2018/09/10/sequencing-data-analysis-c-virginica-oil-spill-mbdseq-concatenation-fastqc/

---

MultiQC: 

- http://owl.fish.washington.edu/Athaliana/20180910_Cvirginica_oil_fastqc/multiqc_report.html

---

Folder with concatenated files: 

- http://owl.fish.washington.edu/Athaliana/20180910_Cvirginica_oil_fastqc/
