### ISSUE TITLE
Compile reagents for oyster qPCR

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#368]
In anticipation of Ronit coming in Wednesday - can you find some some C. gigas cDNA, primers and necessary reagents

**Comment by kubu4** [comment]
Rack in FTR 209 -20<sup>o</sup>C freezer. _C.gigas_ cDNA made by Emma comparing juvenile response to CO<sub>2</sub>; four samples from each treatment. I'll show you when we're ready.

Primers are:

- HSP90
- Cytochrome p450
- Elongation factor
