### ISSUE TITLE
Develop QC trim plan for Oil samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#369]
Given fastQC 
http://owl.fish.washington.edu/Athaliana/20180910_Cvirginica_oil_fastqc/multiqc_report.html

what is best approach to clean libraries up - should probably drop a couple of libraries

**Comment by kubu4** [comment]
I say process them with TrimGalore!, using default settings and see how they turn out (should get rid of a LOT of adapter sequence; I think that's why we see that small peak in the Sequence Duplication Levels plot). I suspect that'll help a bit, but we'll have to try to figure out if/why FastQC doesn't like them.

I'll go ahead and get them trimmed.

**Comment by kubu4** [comment]
Here's what things look like after default trimming parameters with TrimGalore!:

http://owl.fish.washington.edu/Athaliana/20180911_virginica_oil_trimgalore_01/multiqc_report.html

They're better, but I think we might need to implement more aggressive trimming. Specifically:

- trim 26bp from 3' end

- trim 8-10bp from 5' end (this would be Bismark recommendation, regardless)

**Comment by sr320** [comment]
Why 26 from 3'?

Sequence content seems informative.
http://owl.fish.washington.edu/Athaliana/20180911_virginica_oil_trimgalore_01/multiqc_report.html#fastqc_per_base_sequence_content
(the graphs not the heat maps).

TGACCA should likely be dropped.
![screen shot 2018-09-13 at 08 55 25](https://user-images.githubusercontent.com/4442039/45500147-d84d6a00-b732-11e8-816d-ff8bde235aba.png)

and the flatlining from 60-80 on other samples seems odd. then there is the blip at 70 bp in cutadapt graph

**Comment by kubu4** [comment]
Agreed with that assessment.

And, now that I've looked at things further, don't want to trim last 26bp. 

Actually, want to filter out sequences that are shorter than75bp. That should resolve this issue:

![selection_067](https://user-images.githubusercontent.com/4514104/45501383-db962500-b735-11e8-895a-2caf8bd8cff9.png)


![selection_068](https://user-images.githubusercontent.com/4514104/45501387-dd5fe880-b735-11e8-86a7-9b0efc162a73.png)
