### ISSUE TITLE
Gene enrichment for Virgininca DMLs

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#370]
[R Markdown file](
https://github.com/RobertsLab/project-virginica-oa/blob/master/analyses/2018-06-14-Gene-Enrichment-Analysis/2018-06-14-Gene-Enrichment-Analysis.Rmd)

I am in the process of doing a gene enrichment for genes that overlap between my DMLs and mRNA sequences. I'm going to do this gene enrichment in both DAVID and the tool that Mike Riffle built.

Do I also need to do a gene enrichment for DML-exon or DML-intron overlaps? Or for flanking regions?

**Comment by sr320** [comment]
Enrichment w exons, introns, and flanking, and combining - basically all
ways you can come up with to do the enrichment analysis as it is
exploratory
