### ISSUE TITLE
DML-Exon overlap gene enrichment

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#371]
[R Markdown file](https://github.com/RobertsLab/project-virginica-oa/blob/master/analyses/2018-06-14-Gene-Enrichment-Analysis/2018-06-14-Gene-Enrichment-Analysis.Rmd)

[This issue](https://github.com/RobertsLab/resources/issues/370#issuecomment-420414589) leads me into my next question...

I want to obtain Uniprot codes for each of my overlaps so I can use them for gene enrichment I cannot merge the [DML-exon overlaps](https://github.com/RobertsLab/project-virginica-oa/blob/master/analyses/2018-06-11-DML-Analysis/2018-06-11-DML-Exon.txt) with the [transcript-blast results](
https://github.com/RobertsLab/project-virginica-oa/blob/master/analyses/2018-06-14-Gene-Enrichment-Analysis/2018-09-06-Transcript-Uniprot-blastx.txt) as is, because there are no identifiers that are common between the two files. I was able to merge the [DML-mRNA overlaps](
https://github.com/RobertsLab/project-virginica-oa/blob/master/analyses/2018-06-14-Gene-Enrichment-Analysis/2018-09-11-DML-mRNA-unfolded.txt) with the blast results. Does it make sense to merge the original mRNA gff with the DML-exon overlaps?

**Comment by sr320** [comment]
I believe we resolved this yesterday - one simple solution is to include ID in exon tracks.

Also you get overlaps with exons, then intersect with gene track to get IDs.

Same for introns.
