### ISSUE TITLE
Check DNA quality on sea lice samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#373]
We should have a couple of sea lice DNA samples in the -80 - please check quality and quantity.

**Comment by kubu4** [comment]
Not finding anything listed in -80C inventory with "sea" or "lice" or "chile" or "caligus". 

Any ideas how they might be labelled?

**Comment by sr320** [comment]
maybe loose on bottom shelf? or middle -80?

**Comment by sr320** [comment]
actually -20
http://onsnetwork.org/kubu4/2018/05/23/dna-received-sea-lice-dna-from-cris-gallardo-escarate-at-universidad-de-concepcion/

**Comment by kubu4** [comment]
Ha! Look at that! Thanks!

**Comment by kubu4** [comment]
Notebook: http://onsnetwork.org/kubu4/2018/09/12/dna-quantification-sea-lice-dna-from-20180523/
