### ISSUE TITLE
-80C Freezer Full

### ISSUE THREAD

**Issue by kaitlynrm** [RobertsLab/resources#374]
There is 1 spot left in the freezer and the bottom, loose shelf, is very full. There are 7 loose boxes on the second shelf- Ronit's C. gigas samples and Laura's O. lurida samples. I can add another rack there that fits 16 boxes as opposed to 20 boxes- it would be another small rack like rack 14. I can also go through the -80 and throw out any samples we don't need anymore. 

I highlighted a few boxes on the inventory that are unlabeled or don't have a description.

**Comment by sr320** [comment]
@kaitlynrm 
can you add shelf in the hole and update the inventory appropriately.

**Comment by sr320** [comment]
@kaitlynrm can put link to inventory?

**Comment by kaitlynrm** [comment]
[-80C Inventory](https://docs.google.com/spreadsheets/d/1Qsvz3QTURlPF_hX05BQxjom3484WuMfqQ1ILl9LEljU/edit#gid=2006985773)

**Comment by sr320** [comment]
solution to problem 
https://github.com/RobertsLab/resources/issues/391

**Comment by kaitlynrm** [comment]
Added the new shelf and updated the -80C spreadsheet!
