### ISSUE TITLE
Emu not rebooting after freezing

### ISSUE THREAD

**Issue by kaitlynrm** [RobertsLab/resources#376]
I was working with the 2016 protein data set (which is very large) in LibreOffice on Emu. It was running pretty slow then eventually froze entirely. I tried to reboot it, but it failed. The boot screen would pop up but then it would go black and not fully reboot. I tried twice more and the same thing happened the second time. The final time, the boot screen wouldnt load. I left it shut down.

**Comment by kubu4** [comment]
The issue is related to @kaitlynrm upgrading the operating system to 18.04. Due to hardware limitations, the easiest and fastest fix for this is to perform a clean install of Ubuntu 16.04. I'll post a new issue related to this activity.
