### ISSUE TITLE
Unable to view bedGraphs in IGV

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#377]
I want to look at my DMLs in IGV. For one of my samples, I added my sorted and indexed .bam file, coverage information, and a bedGraph. Even when I zoomed in to the nucleotide level, I couldn't see the bedGraphs.

![screen shot 2018-09-16 at 2 36 35 pm](https://user-images.githubusercontent.com/22335838/45601196-0397b980-b9be-11e8-83b5-85889a3607eb.png)

I'm clearly missing something...what is it?

**Comment by sr320** [comment]
Can you post a bed graph?

**Comment by yaaminiv** [comment]
Ah, whoops. They can be found in [this folder](https://github.com/RobertsLab/project-virginica-oa/tree/master/analyses/2018-05-22-Bismark-Full-Samples).

bedGraph I was using: 
https://github.com/RobertsLab/project-virginica-oa/blob/master/analyses/2018-05-22-Bismark-Full-Samples/zr2096_10_s1_R1_val_1_bismark_bt2_pe.deduplicated.bedGraph

**Comment by sr320** [comment]
you see there is nothing in that file?
https://github.com/RobertsLab/project-virginica-oa/blob/master/analyses/2018-05-22-Bismark-Full-Samples/zr2096_10_s1_R1_val_1_bismark_bt2_pe.deduplicated.bedGraph

**Comment by sr320** [comment]
you can grab some bedgraphs here
http://gannet.fish.washington.edu/seashell/bu-serine-wd/18-04-29/

example: http://gannet.fish.washington.edu/seashell/bu-serine-wd/18-04-29/zr2096_9_s1_R1_val_1_bismark_bt2_pe.deduplicated.bedGraph

**Comment by yaaminiv** [comment]
How did I end up with empty bedGraphs...? I used the same code you did.

I will grab bedGraphs from the link.
