### ISSUE TITLE
Run Oyster samples through Bismark

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#379]
Install Bismark and run the following MBD-BS data

10 libraries at
http://gannet.fish.washington.edu/seashell/bu-serine-wd/18-04-07/

against 
this genome

http://owl.fish.washington.edu/halfshell/genomic-databank/Cvirginica_v300.fa

I would suggest using the `-u` parameter to just align a subset of reads

**Comment by shellytrigg** [comment]
is there a way I can mount the seashell server and access the data via command line rather than download it?

**Comment by kubu4** [comment]
Yes. I'll set you up with server credentials. BRB...

**Comment by sr320** [comment]
@kubu maybe set up a directory "metacarcinus" in web..

**Comment by kubu4** [comment]
Alrighty, if things all worked correctly, you should now have access to both servers where those two sets of data reside.

You should have received an email from each of the two servers (Gannet and Owl). You will be required to login to each and change your password before you can actually start connecting to them.

After changing your password, you should be able to mount both servers on your Mac.

Finally, I've created a publicly viewable folder for all of your stuff on Gannet:

http://gannet.fish.washington.edu/metacarcinus/

This will allow you to link to any images/files that you store here. Best practice is to not change/delete things once you put them on Gannet, as it any changes potentially break URLs. There's plenty of space, so you can put anything/everything on Gannet (i.e. no need to "groom" data prior to putting on Gannet).

**Comment by shellytrigg** [comment]
Thanks! I received the emails and was able to login to both, change my passwords, and mount the servers on my mac.

**Comment by shellytrigg** [comment]
@sr320 Here is the link to a repo containing my jupyter notebook and Bismark summary report of this analysis:   https://github.com/shellytrigg/C_virginica
Maybe we can discuss Monday morning

**Comment by sr320** [comment]
@shellytrigg can you get analysis to a point where you could say what loci are differentially methylated between samples 1-5 and 6-10?
