### ISSUE TITLE
Update Oly WGBS methods

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#385]
Update to include Bismarck with "relaxed" and methylkit with 3x coverage.

https://github.com/sr320/paper-oly-wgbs/blob/master/submission/Narrative.Rmd

**Comment by kubu4** [comment]
Done.

Ooof, just realized why my commits weren't showing up in the repo; I'm working on a fork of the repo.

I'm going to submit a pull request, but I don't think it's going to be pretty, as I've been working on a copy that doesn't have the most recent updates.

Guess we'll see how it goes...
