### ISSUE TITLE
Get Shelly an account on Mox

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#388]

**Comment by kubu4** [comment]
Hey, @shellytrigg , what's your UW NetID? (it's public info, so it's OK to post it here)

**Comment by kubu4** [comment]
Also, @shellytrigg , please follow these instructions (the "For the user" part) to enable access to Mox:

https://github.com/RobertsLab/hyak_mox/wiki/Adding-a-User

**Comment by shellytrigg** [comment]
@kubu4 I don't see hyak and lolo servers listed under the computing services tab. Is this where I should see them?
![screen shot 2018-09-24 at 6 24 04 pm](https://user-images.githubusercontent.com/4720221/45987664-ac31c300-c027-11e8-81da-c4a2f61993d7.png)

**Comment by kubu4** [comment]
@shellytrigg - I hadn't added you to the Hyak group yet.

My guess is it should be listed in the Inactive Services section, now.

Sorry about that!
