### ISSUE TITLE
Publish PCSGA slidedecks and update web

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#389]
Here is a link to update web content:
https://github.com/sr320/LabDocs/blob/master/web/Products.md

**Comment by yaaminiv** [comment]
[Uploaded slides](https://github.com/RobertsLab/project-virginica-oa/blob/master/presentations/Venkataraman_WED_1030.pptx) and added link to Products page

**Comment by sr320** [comment]
somewhere more permanent with DOI

**Comment by laurahspencer** [comment]
Weird, I swore I posted here last week.  In any case, my slides are on Fig Share and on the products page [here](https://figshare.com/articles/Carry-over_effects_of_parental_pH_exposure_in_the_Olympia_oyster/7130837/1)
