### ISSUE TITLE
Add basic descriptive stats for BS reads and genome assembly

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#392]
in the results section 
of 
https://github.com/sr320/paper-oly-wgbs/blob/master/submission/Narrative.Rmd

**Comment by kubu4** [comment]
Pull request submitted: https://github.com/sr320/paper-oly-wgbs/pull/4

What other types of stats were you looking for for the BSseq reads? Seems a bit barren with just an average read number...
