### ISSUE TITLE
Make Crab Podcast discoverable on ITunes etc

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#394]

**Comment by grace-ac** [comment]
working on creating an RSS feed specifically for the podcast. there is currently only an RSS feed for comments and for posts on bittercrab.science

i have a soundcloud account for it: https://soundcloud.com/grace-crandall-838579799/tracks
but they are currently individual tracks as opposed to a podcast station

it seems that once i have an RSS feed specifically for the podcast, i can continue on to iTunes to make it subscribable

**Comment by grace-ac** [comment]
Found RSS. Submitted into a [new podcast feed](https://podcastsconnect.apple.com/my-podcasts/new-feed) from podcastconnect.apple.com

Error:      

**I'm sure I can figure out the image size issue, but not sure about the HTTP part...**

![screen shot 2018-09-27 at 3 52 44 pm](https://user-images.githubusercontent.com/14934314/46178897-99a8cb00-c26d-11e8-87fd-8cf734870f10.png)

**Comment by grace-ac** [comment]
Fixed image issue, and podcast has been submitted to apple for review. will get email notification on review results
