### ISSUE TITLE
Can't access gscratch/srlab on mox

### ISSUE THREAD

**Issue by jldimond** [RobertsLab/resources#395]
Anyone know why this would happen? 

[jldimond@mox1 ~]$ cd gscratch/srlab
-bash: cd: gscratch/srlab: No such file or directory

**Comment by sr320** [comment]
Someone needs to retake a class :)

**Comment by kubu4** [comment]
````./data``` refers to a folder in ```/gscratch/srlab```. If you want to move _up_ to a folder, you need two dots: ```../data```

**Comment by sr320** [comment]
We will cover this on 3pm next Tuesday if you need a refresher :)

**Comment by jldimond** [comment]
Fair enough, I do know that about the dots - that actually wasn't the syntax I used. 

But still, see below - why no slashes when I am going to `data` from `/gscratch/srlab/` -?

[jldimond@mox1 srlab]$ cd /data
-bash: cd: /data: No such file or directory
[jldimond@mox1 srlab]$ cd /data/
-bash: cd: /data/: No such file or directory
[jldimond@mox1 srlab]$ cd data
[jldimond@mox1 data]$

**Comment by kubu4** [comment]
Those are different directories. The leading slash tells the computer to start looking for a folder called data in the system's root directory. Without the slash, the computer looks for a folder called data within the current directory.

**Comment by jldimond** [comment]
Oh, ok. Maybe I do need to retake a class =P

**Comment by sr320** [comment]
IOW you are telling the system you want to use the absolute path....
see
https://github.com/sr320/course-fish546-2018/blob/master/01-Notes/Tutorials/Navigating-commandline.md

**Comment by jldimond** [comment]
Thanks - I do remember that tutorial!
