### ISSUE TITLE
Prep oyster heat stress samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#396]
Ronit should be coming in today-
It would be good to confirm sample organization, documentation and in the freezer.

Ronit should maybe "prep" 2 samples from each treatment such that @kubu4 can easily extract RNA. 

This might be subsampling, measuring and storing is central place.

Gill tissue. 

If time allows he could always test more primers

**Comment by kubu4** [comment]
Beefed up spreadsheet, confirmed sample documentation and freezer locations.

Pulled samples for RNA isolation next week.

Checked/reviewed supplies/reagents.
