### ISSUE TITLE
Data format for ASCA analysis?

### ISSUE THREAD

**Issue by kaitlynrm** [RobertsLab/resources#397]
I'm trying to organize my data to run an [ASCA](https://www.ncbi.nlm.nih.gov/pubmed/15890747) with [Silo 3 (23C)](https://github.com/kaitlynrm/OysterSeedProject/blob/master/analysis/kmeans/silo3/silo3.csv) and [Silo 9(29)](https://github.com/kaitlynrm/OysterSeedProject/blob/master/analysis/kmeans/silo9/silo9.csv). (Alternatively, the table [Silo3and9](https://github.com/kaitlynrm/OysterSeedProject/blob/master/analysis/kmeans/Silo3_and_9/silo3and9.csv) might be easier to manipulate depending on the organization of the data.) [An ASCA is essentially an ANOVA that separates factors and calculates variances for each factor such that the PCA considers time.](https://academic.oup.com/bioinformatics/article/21/13/3043/197836)

The function `ASCA.calculate` in [MetStaT](https://cran.r-project.org/web/packages/MetStaT/MetStaT.pdf) requires two matricies: `'data'` and `'levels'`.` 'Data'` is specified as a "numeric data matrix that is to be analyzed with ASCA. Variables are represented by columns, observations by rows". Therefore, my proteins should be put in columns and my abundances should be in rows.

`'Levels'` is specified as a "numeric matrix describing the experimental design.  Each factor is represented by  a  column. The  elements  of  the  columns  give  the  treatment  level  the  row
belongs to". I believe time and temperature are my factors, although I read that factors are categorical data that is either nominal or ordinal- time would be considered ratio... However, the ASCA should consider time and factors are the only way I can specify that. I think the time factor would just be single column as "3, 5, 7, 9, 11, 13, 15" for each respective element, but I'm not sure how to organize temperature. Would temperature, for example 23, have to run as the column as well as  row for as many rows as there are detected proteins in silo 3 and the restart with the value 29 for silo 9?

Then I specify `equation.elements=".."`(a  string  value  indicating  which  factors  and  interactions  are  to  be  part  of  the ASCA analysis. A factor is defined by writing its column number in the ’levels’
matrix (eg. "1") and an interaction by combining the interacting factors’ column
numbers from the ’levels’ matrix (eg.  "123").  Multiple factors/interactions are separated with comma’s (eg. "1,2,12")). I believe factor 1 would be my column containing time and factor2 would be temperature, but specifying the factor for temperature would depend on how it is organized in `'levels'` which I'm not sure of. Furthermore, would time and temperature be considered interacting factors or multiple factors (that is, if time can be a factor)?

**Comment by kaitlynrm** [comment]
Thanks @shellytrigg ! Also, I wasn't sure if day 0 should be included since it is the same for both silos and occurred before treatment (thus we wouldn't see a temperature/time effect based on day 0). Do you think including day 0 affects the analysis?

**Comment by shellytrigg** [comment]
I don't think it would effect the analysis, but you could try the analysis with and without it to see if your results change.
