### ISSUE TITLE
Bioanalyzer results from gigas broodstock DNA test extractions

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#398]
Here are the bioanalyzer results from the gigas broodstock DNA test extractions: 

![unnamed-1](https://user-images.githubusercontent.com/22335838/46119829-d0290c00-c1c1-11e8-93f1-d4ce76f78d5c.png)
![unnamed-2](https://user-images.githubusercontent.com/22335838/46119830-d0290c00-c1c1-11e8-953a-68e826c9521a.png)
![unnamed-3](https://user-images.githubusercontent.com/22335838/46119831-d0c1a280-c1c1-11e8-8e42-a02b7667d1b7.png)
![unnamed-4](https://user-images.githubusercontent.com/22335838/46119832-d0c1a280-c1c1-11e8-800e-19ab94f504de.png)

From what I can tell, most of my DNA is 35 bp. This is really short for a downstream MBD bisulfite seq. I would need to modify my lysis step so the DNA isn't sheared. Is this a correct interpretation?

**Comment by yaaminiv** [comment]
To clarify: each sample name is coded with a different lysis methodology.

TT: TissueTearor used at lowest setting for 20 seconds (top image) or 10 seconds (bottom image). This method gave me the highest yield in two separate extraction trials, so I would like to use this method when doing extractions tomorrow.
V[number]: Vortexing with glass beads for either 2, 5, or 10 minutes. Most likely not using this method.

When I look at the results in gel mode, I see that the darkest band hovers around 35 bp. In the electropherogram, I also see a peak at 10,380 bp. **Does this mean that I have some DNA sheared to 35 bp, but I have usable DNA at 10,380 bp?** 

The PAXgene kit also has some suggestions for DNA shearing, but I don't think the first suggestion is feasible at this point:

<img width="1027" alt="screen shot 2018-09-26 at 8 46 33 pm" src="https://user-images.githubusercontent.com/22335838/46122403-5860de80-c1cd-11e8-8d33-3bde891251fc.png">

**Do I need to reduce the amount of time I use the TissueTearor to reduce shearing?**

**Comment by kubu4** [comment]
The majority of your samples have high molecular weight DNA in them. This is evidenced by the increase in fluorescence seen near the large marker. One caveat is that the DNA chip maxes out 10,380bp, so DNA larger than this just bunches up here. Intact gDNA should be much larger than this and you cannot assess this via the Bioanalyzer. So, it's still possible to have degraded DNA, but not be able to visualize it via this methodology.

The prominent banding seen at low molecular weight (~50bp) is likely RNA. Was there an RNase treatment in the protocol?

Banding around ~35bp is likely degraded RNA.

Prominent smearing throughout the entire lane (and no high molecular weight band/peak) is indicative of sheared DNA.

**Comment by yaaminiv** [comment]
There was an RNase treatment for samples in the first two images, but not the second two. That could explain the banding in the second gel image.

Since the BioAnalyzer cannot visualize gDNA, is it safe to assume I might have large enough fragments that would be viable for downstream bisulfite seq?

**Comment by sr320** [comment]
safe to assume
