### ISSUE TITLE
Out of dsDNA BR dye for Qubit (and 1000ul pipette tips)

### ISSUE THREAD

**Issue by kaitlynrm** [RobertsLab/resources#400]
Unless they're are some stashed away somewhere!

**Comment by yaaminiv** [comment]
@kubu4 Is there a way to purchase just the dye, or would we have to get the [whole kit](https://www.thermofisher.com/order/catalog/product/Q32850)?

**Comment by sr320** [comment]
If I am reading the purchasing log correctly would it not be
https://www.thermofisher.com/order/catalog/product/Q33231?SID=srch-hj-Q33231

Steven B. Roberts
Kenneth K. Chew Endowed Professor
School of Aquatic and Fishery Sciences
University of Washington, Seattle WA
sr320@uw.edu - 206.866.5141
robertslab.info - @sr320

**Comment by kaitlynrm** [comment]
It would be [the broad range kit](https://www.thermofisher.com/order/catalog/product/Q32853?SID=srch-srp-Q32853). We only need the dye, not the standards or buffer, but I'm guessing there isn't an option for just the dye... We already have a lot of standards so we were trying to figure out if we could but only the dye or the dye and buffer.

**Comment by sr320** [comment]
Gotcha! just order the kit...

**Comment by kaitlynrm** [comment]
Okay- 500 or 100 assays?

**Comment by sr320** [comment]
500

**Comment by kaitlynrm** [comment]
How many boxes of 1000ul tips should I order?

**Comment by kaitlynrm** [comment]
Whoops- guessing the (8 box one)[https://geneseesci.com/shop-online/product-details/?product=24-430]

**Comment by sr320** [comment]
whatever we did last time
