### ISSUE TITLE
Is it true I shouldn't update Skyline Daily?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#402]
I may not be remembering quite right, but I  think @laurahspencer and @yaaminiv said that updating Skyline Daily is ill-advised because it would make working from protocols difficult...?

I ask because I can't open skyline doc that Emma sent me because our version is too old. 

![oldversionsskyline](https://user-images.githubusercontent.com/14934314/46319521-2d8cd680-c58f-11e8-99e2-e6faba3737bc.PNG)

**Comment by yaaminiv** [comment]
@grace-ac Skyline Daily usually updates itself! You should always keep it updated.

**Comment by grace-ac** [comment]
thanks!
