### ISSUE TITLE
Issue with setting up RT prediction in Skyline

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#404]
Following along @emmats 's notebook: [here](https://www.evernote.com/shard/s242/nl/32843380/167d2c46-b499-4674-9f52-e7b13c84f6ee/)

On part where you set up retention time prediction.

I am using the PierceRT.irtdb in the zip file @emmats  sent in GitHubIssue [#341]( https://github.com/RobertsLab/resources/issues/341)

## **Problem:**       
![no-irt-std-peptides](https://user-images.githubusercontent.com/14934314/46375270-cda63680-c647-11e8-9d6c-8da1e46e6eb3.PNG)

### **Here is what it looks like when I add the Pierce retention time predictor:**       
![addingpierceirt](https://user-images.githubusercontent.com/14934314/46375287-deef4300-c647-11e8-8a7b-c2fe36eeda85.PNG)

### **After I click "OK" on the Edit iRT Calculator window, I get the above issue of it not containing peptides.**

**Comment by grace-ac** [comment]
Wait, I missed a step.  I didn't Add the results to the iRT calculator... let me see how it looks. 

However, side question: should I just use your document to continue on with?

**Comment by grace-ac** [comment]
zipped contents:     
![zippedcontents](https://user-images.githubusercontent.com/14934314/46378244-d7339c80-c64f-11e8-8907-bbc3fbf5dfc2.PNG)

**I used the PierceRT.irtdb**

**Comment by emmats** [comment]
I made a document that should have everything you need in it. It seems silly to remake it! But it is always worth checking to make sure you understand what I did and that I did not make any mistakes.

**Comment by sr320** [comment]
@grace-ac is this resolved?

**Comment by grace-ac** [comment]
I'll revisit today!

Question @sr320 : at this point, after I go through what emma did, can I use her skyline file to move forward with the analysis?

**Comment by sr320** [comment]
Yes

**Comment by grace-ac** [comment]
okay - then i'll close issue and look through what emma did. then move forward.
