### ISSUE TITLE
Mounting OWL on macMini

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#405]
How do I mount OWL on the macMini? I used to be able to access OWL on that machine and access/save files directly to an OWL directory. I no longer see OWL as a remote device.

![screen shot 2018-10-03 at 12 27 14 pm](https://user-images.githubusercontent.com/22335838/46434187-c5153500-c707-11e8-8fcf-b643e3262d32.png)

**Comment by kubu4** [comment]
Try this:

http://osxdaily.com/2010/09/20/map-a-network-drive-on-a-mac/

**Comment by yaaminiv** [comment]
It worked! Thanks
