### ISSUE TITLE
R crashing with library(methylKit)

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#406]
I've run the following code to install methylKit:

this first two lines per [Bioconductor installation troubleshooting guide](https://bioconductor.org/install/#install-bioconductor-packages)

remove.packages("BiocInstaller", lib=.libPaths())
source("http://bioconductor.org/biocLite.R")
biocLite("methylKit")
browseVignettes("methylKit")
-this command opens the html page which seems to suggest the installation worked

library(methylKit, lib.loc = "/Users/Shelly/Library/R/3.4/library/")
-this command aborts the R session

when I run these commands from R in the command line, I get the error below.

Anyone have any tips for getting the methylKit successfully loaded in R 3.4?

> library(methylKit)
Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, cbind, colMeans, colnames,
    colSums, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, lengths, Map, mapply, match,
    mget, order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rowMeans, rownames, rowSums, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which, which.max, which.min

Loading required package: S4Vectors

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges
Loading required package: GenomeInfoDb

 *** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: FUN(X[[i]], ...)
 2: lapply(name, function(id) {    v <- .Internal(getSymbolInfo(as.character(id), PACKAGE, as.logical(withRegistrationInfo)))    if (is.null(v)) {        msg <- paste("no such symbol", id)        if (length(pkgName) && nzchar(pkgName))             msg <- paste(msg, "in package", pkgName)        stop(msg, domain = NA)    }    names(v) <- c("name", "address", "package", "numParameters")[seq_along(v)]    v})
 3: getNativeSymbolInfo(symNames, dll, unlist = FALSE, withRegistrationInfo = TRUE)
 4: assignNativeRoutines(dlls[[lib]], lib, env, nsInfo$nativeRoutines[[lib]])
 5: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
 6: namespaceImport(ns, loadNamespace(i, c(lib.loc, .libPaths()),     versionCheck = vI[[i]]), from = package)
 7: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
 8: asNamespace(ns)
 9: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
10: loadNamespace(package, lib.loc)
11: doTryCatch(return(expr), name, parentenv, handler)
12: tryCatchOne(expr, names, parentenv, handlers[[1L]])
13: tryCatchList(expr, classes, parentenv, handlers)
14: tryCatch({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps)}, error = function(e) {    P <- if (!is.null(cc <- conditionCall(e)))         paste(" in", deparse(cc)[1L])    else ""    msg <- gettextf("package or namespace load failed for %s%s:\n %s",         sQuote(package), P, conditionMessage(e))    if (logical.return)         message(paste("Error:", msg), domain = NA)    else stop(msg, call. = FALSE, domain = NA)})
15: library(methylKit)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

**Comment by kubu4** [comment]
Can you please post output from this command:

```installed.packages()[, c("Package", "LibPath")]```

**Comment by kubu4** [comment]
Alternatively, instead of bothering with this, you could use one of our installations of R Studio Server. This would allow you to run R/R Studio on much faster computers. It also allows you to shutdown your computer without having to wait for a job to finish, since all the action is happening on a different computer.

Finally, we know methylkit is installed and working on both computers that are running R Studio Server.

**Comment by sr320** [comment]
Its still good to have it installed locally to tweak and test..
see 
https://sr320.github.io/MethylKittens/
near end for installations tips

**Comment by shellytrigg** [comment]
This (code below) finally worked! It was one or some packages that methylKit had tried to update or install in my /Library/Frameworks/ directory as Sam suggested. Thanks @kubu4 and @sr320 for helping with this!

#from command line, change the permissions on R library folders to make them writable
sudo chmod -R 777 /Users/Shelly/Library/R/
sudo chmod -R 777 /Library/Frameworks/

remove.packages("BiocInstaller", lib=.libPaths())
source("http://bioconductor.org/biocLite.R")

biocLite("methylKit")
library(methylKit)
