### ISSUE TITLE
Quality Trim EPI geoduck data

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#408]
Maybe you already did this too 😄 
but what is your recommendation for trimming?

Maybe 10bp 5'
Phred
remove adaptors
??

**Comment by kubu4** [comment]
Indeed, I did!

http://onsnetwork.org/kubu4/2018/05/16/trimgalorefastqcmultiqc-trimgalore-rrbs-geoduck-bs-seq-fastq-data-directional/

**Comment by kubu4** [comment]
Here's the original discussion: Issue #260 .

**Comment by sr320** [comment]
There are adaptor issues with ~10bp 5' and ~5bp 3' 

eg.
https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/0807/EPI-167_S10_L002_R1_001_val_1_bismark_bt2_PE_report.html

can you give it another trim (with hard clips) from raw to see if we can resolve.

**Comment by kubu4** [comment]
I don't see any adaptor contamination in the FastQC/MultiQC reports:

http://owl.fish.washington.edu/Athaliana/20180516_geoduck_trimgalore_rrbs/20180516_geoduck_trimmed_fastqc/multiqc_data/multiqc_report.html

But, I can easily perform additional hard trimming. Is the concern this wonky stuff at the 5' end?

![20190923_001](https://user-images.githubusercontent.com/4514104/65445112-5e8c9980-dde6-11e9-887b-a6fc94902787.png)

**Comment by sr320** [comment]
See M-Bias plots in the link I provided.

**Comment by kubu4** [comment]
I think it might be better to process the data in Bismark using:

 `bismark_methylation_extractor --ignore <int> --ignore_r2 <int>`

That way, we're not "permanently" truncating the sequencing files.

Also, here's the Bismark explanation:

https://github.com/FelixKrueger/Bismark/tree/master/Docs#usage-bismark_methylation_extractor-options-filenames

And, here's one additional note about tweaking M-Bias (linked via the Bismark documentation on M-Bias):

https://sequencing.qcfail.com/articles/library-end-repair-reaction-introduces-methylation-biases-in-paired-end-pe-bisulfite-seq-applications/

Anyway, per our conversation, I'll just get these hard trimmed.

**Comment by kubu4** [comment]
I trimmed 20bp from the 5' end of each read. Data is here:

https://gannet.fish.washington.edu/Atumefaciens/20190923_pgen_fastp_EPI_trimming/

MultiQC report is here:

https://gannet.fish.washington.edu/Atumefaciens/20190923_pgen_fastp_EPI_trimming/multiqc_report.html

Interestingly, MulitQC can interpret the output data from the trimming program I used (fastp). 

AND, fastp actually generates _its own_ HTML report (including before/after info!):

https://gannet.fish.washington.edu/Atumefaciens/20190923_pgen_fastp_EPI_trimming/fastp.html

Anyway, here's an example of how the data looks (before/after):

![20190924_003](https://user-images.githubusercontent.com/4514104/65541993-3161e900-dec3-11e9-9356-842421b126ff.png)

---

![20190924_004](https://user-images.githubusercontent.com/4514104/65542039-4b033080-dec3-11e9-9642-0cde1e9ba114.png)
