### ISSUE TITLE
Bismark: -score_min testing

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#409]
I tested different `-score_min` options on a subset of the *C. virginica* data in [this Jupyter notebook](https://github.com/RobertsLab/project-virginica-oa/blob/master/notebooks/2018-10-03-Bismark-Parameter-Testing.ipynb).

@sr320 Should I produce the summary report now, or should I dedpulicate/sort/index/extract methylation calls before producing the summary? I'm not sure which option would be better for understanding how well the alignment went.

**Comment by sr320** [comment]
can you provide a simple table showing mapping efficiency with different `-score_min` s ?

**Comment by yaaminiv** [comment]
The table can also be found in [this lab notebook post](https://yaaminiv.github.io/DML-Analysis-Part10/).

| **Sample** | **L,0,-0.6** | **L,0,-0.9** | **L,0,-1.2** |
|:----------:|:------------:|:------------:|:------------:|
|      1     |     15.5     |     20.2     |     28.8     |
|      2     |     32.4     |     40.2     |     49.8     |
|      3     |     37.2     |     45.3     |     53.6     |
|      4     |     36.0     |     44.7     |     52.9     |
|      5     |     34.6     |     42.9     |     51.7     |
|      6     |     36.7     |     45.0     |     53.8     |
|      7     |     34.6     |     42.9     |     51.4     |
|      8     |     31.7     |     39.0     |     47.6     |
|      9     |     33.0     |     41.2     |     49.9     |
|     10     |     36.6     |     44.9     |     53.0     |

**Comment by sr320** [comment]
Were files satisfactorily quality trimmed prior to aligning?

**Comment by yaaminiv** [comment]
Yes, I used files that @kubu4 quality trimmed.

**Comment by sr320** [comment]
url for QC pre and post trim?

**Comment by yaaminiv** [comment]
From [Sam's notebook](http://onsnetwork.org/kubu4/2018/04/11/trimgalorefastqcmultiqc-trim-10bp-53-ends-c-virginica-mbd-bs-seq-fastq-data/)

**Comment by sr320** [comment]
we need to keep an eye on sample 1.. 
but go ahead and run full Bismark align w `L,0,-1.2`  into (and out of) methylkit for DML and DMR
