### ISSUE TITLE
help! bizarre sum() issue with matrix in R

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#41]
Can anyone help me figure out what's happening in this script?

I'm creating bar plots with data in R and running into a bizarre issue with part of my data set.   Here's an example script (which is working), that creates the below set of plots: 

###### HSP 90
`par(mfrow=c(3,1))`  
`barplot(SRM.data4plots.ordered[sum(1:3),], main=SRM.proteins[1,c(1:2)], col=SRM.data4plots.ordered[117,], density=SRM.data4plots.ordered[118,])`
`barplot(SRM.data4plots.ordered[sum(4:6),], main=SRM.proteins[4,c(1:2)], col=SRM.data4plots.ordered[117,], density=SRM.data4plots.ordered[118,])`
`barplot(SRM.data4plots.ordered[sum(7:9),], main=SRM.proteins[7,c(1:2)], col=SRM.data4plots.ordered[117,], density=SRM.data4plots.ordered[118,])`

![image](https://user-images.githubusercontent.com/17264765/29945222-30c720a2-8e55-11e7-8ccf-52ab3d4f25ea.png)

Each plot represents a peptide, and within the plots each bar represents a sample (column of the dataset) and the sum of data in three consecutive rows. This script works great for the first 36 rows of my data, then stops working and gives the error: ` subscript out of bounds` 

While troubleshooting I found that I cannot take the sum() of any three consecutive rows _past_ the 39th row. I've included some troubleshooting commands in my R script, and a couple notes. Any help is appreciated! 

R Script, which reads in data via urls from spreadsheets saved on GitHub:   
[2017-08-31_SRM-bar-plot-script.R](https://github.com/laurahspencer/Geoduck-DNR/blob/master/Analyses/2017-August_SRM-Analysis/2017-08-31_SRM-bar-plot-script.R)

**Comment by sr320** [comment]
I would start by looking at data the script is working on and look for any abnormalities around lines 36-39.

**Comment by sr320** [comment]
I do not see anything apparent in raw data...

For others here is some of @laurahspencer troubleshooting in the R script she provided above.

```
# trying to troubleshoot / figure out where the problem lies
SRM.data4plots.ordered[sum(36:38),] #sum of rows 36-38 works
SRM.data4plots.ordered[sum(39:41),] #sum of rows 39-41 does NOT work
SRM.data4plots.ordered[mean(39:41),] #but the MEAN of rows 39-41 does work
SRM.data4plots.ordered[sum(39:40),] #this works
SRM.data4plots.ordered[sum(40:41),] #this works
SRM.data4plots.ordered[sum(39,41),] #this works
is.numeric(SRM.data4plots.ordered[39:41,]) #all data in all three rows are numeric
any(is.na(SRM.data4plots.ordered[39:41,])) #no NA data in these three rows

#and this weirdness happens: 
SRM.data4plots.ordered[c(38:40),] #these are rows 38-40
SRM.data4plots.ordered[sum(38:40),] #sum of rows 38-40 is NOT CORRECT 
```

**Comment by laurahspencer** [comment]
I figured it out.  my script is not plotting correctly.  It uses this form: `barplot(mymatrix[sum(rowA:rowC),],...)`

Which results in plotting the value in the row number that equals rowA + rowB.
For example: 
`barplot(mymatrix[sum(row1:row3),]...) is in fact plotting barplot(mymatrix[row4,]...)`

The plots stop working at row 40 since 39+40+40 > the number of rows in my matrix.
