### ISSUE TITLE
Owl and Gannet mounted on Hyak?

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#412]
Can you submit a job on Hyak that needs to access data on Gannet and/or Owl? Or do you need to copy all your data over onto Hyak gscratch?

**Comment by sr320** [comment]
Copy data...

**Comment by kubu4** [comment]
The reason for this is that compute nodes don't have internet access, thus, they cannot mount drives.

**Comment by shellytrigg** [comment]
Got it, thanks!
