### ISSUE TITLE
Explore Geoduck mapping 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#415]
Run Bismark on 
files in 
http://owl.fish.washington.edu/Athaliana/20180516_geoduck_trimgalore_rrbs/

to look at mapping efficiency, genome coverage

genome: http://owl.fish.washington.edu/halfshell/genomic-databank/Pgenerosa_v070.fa

Details of trimming @ 
http://onsnetwork.org/kubu4/2018/05/16/trimgalorefastqcmultiqc-trimgalore-rrbs-geoduck-bs-seq-fastq-data-directional/

**Comment by shellytrigg** [comment]
I'm building the Bismark genome from Pgenerosa_v070.fa and am getting this warning message "Warning: Encountered reference sequence with only gaps", which seems to be from lots of NNNs in the sequence. [See my notebook for reference](https://github.com/shellytrigg/Shelly_Pgenerosa/blob/master/methylation_analysis/Geoduck_OA_mapping_quality.ipynb). Will this affect the alignment?

**Comment by sr320** [comment]
We expect NNNNs but the error would suggest there is a contig with only NNNNs which would be odd. 
Re: mapping it just means nothing will map there.

**Comment by shellytrigg** [comment]
Got it, thanks!

**Comment by shellytrigg** [comment]
@sr320 @kubu4 where could I find a working GFF or GTF for the Pgenerosa_v070.fa genome?

**Comment by kubu4** [comment]
If we had one, it'd be here: [Genomic Resources wiki](https://github.com/RobertsLab/resources/wiki/Genomic-Resources)

However, the genome is not annotated, so we don't have a GFF at this time.

**Comment by sr320** [comment]
So no MAKER for this genome yet?

**Comment by kubu4** [comment]
Nope. It's been low on priority list. Can try to get something run next
week. However, have almost used up entirely of computing resources on
Xsede/CyVerse/Atmosphere or whatever it's called. Have used 65% of
allotment and am currently re-running O.lurida with new custom repeat
library.

**Comment by kubu4** [comment]
Do we have any proteomic data (in FastA format) I can use for annotation?

**Comment by sr320** [comment]
Let’s hold off on Maker for now.

**Comment by sr320** [comment]
@shellytrigg where might the bismark output live?

**Comment by shellytrigg** [comment]
@sr320 the bismark analysis is [here](http://gannet.fish.washington.edu/metacarcinus/Pgenerosa/20181011/)

I also copied deduplicated sorted bams to emu to try methylkit on R server and those are [here](/home/srlab/GitHub/Shelly_Pgenerosa/analyses/methylkit_JuviPgenr_allData)

I have most recently been trying to compare the preconditioned "super low" and "ambient" treatments after which animals were returned to low pH (samples 205,206,214,215,220,221,226, and 227). And that analysis is [here](https://github.com/shellytrigg/Shelly_Pgenerosa/tree/master/analyses/methylkit_JuviPgenr_allData)

I am still working to update [this repo](https://github.com/shellytrigg/Shelly_Pgenerosa/) and notebook posts about analyses I've done
