### ISSUE TITLE
Go after Winter Incubator?

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#416]
Does this make sense to apply for?
https://escience.washington.edu/get-involved/incubator-programs/overview/

I think there might be some interesting machine learning aspects with methylation

**Comment by kubu4** [comment]
Certainly couldn't hurt. Informational meeting is on Oct. 25th - applications due Nov. 9th.

Maybe we can have a "methylation meeting" where we all sit down and come up with some tentative research questions that could be tackled by the Winter Incuabtor?
