### ISSUE TITLE
Assess global DNA methylation via ELISA

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#417]
on 
* Sea lice samples
* Oysters @ different Ploidy level (should have samples from Oregon)
* Oysters from recent ploidy heat-stress experiment

**Comment by kubu4** [comment]
@shellytrigg - Sea lice DNA can be found in my [gDNA Box #2](https://docs.google.com/spreadsheets/d/1SWzKMKh7LBOgTfvEhJamE6pZFsTpRXY7otzXUC5fZSM/edit?usp=sharing) in Slots H4 & H5. My gDNA Box # 2 is in the small -20<sup>o</sup>C in the back of FTR 213.

**Comment by shellytrigg** [comment]
@kubu4 Steven mentioned you've done this before. Maybe tomorrow we could do a lab rundown of where the lab supplies are etc.? Also, is there an entry in your lab notebook with a protocol for this? I found this [one](http://onsnetwork.org/kubu4/2016/07/07/dna-methylation-quantification-coral-dna-from-jose-m-eirin-lopez-florida-international-university/) but wasn't sure if there is a more recent one.

**Comment by kubu4** [comment]
That's the most recent time; we haven't done this very many times, not have we used this exact kit before.

The hardest part will be coordinating a time to use the Seeb Lab plate reader.

I'm available any time tomorrow to go over stuff.

**Comment by shellytrigg** [comment]
great, thanks @kubu4 !

**Comment by shellytrigg** [comment]
Need to locate: 
- Oysters @ different Ploidy level (should have samples from Oregon)
- Oysters from recent ploidy heat-stress experiment
*these are tissue samples in the -80C but not sure what they are labelled. [Ronit's samples?](https://docs.google.com/spreadsheets/d/1Qsvz3QTURlPF_hX05BQxjom3484WuMfqQ1ILl9LEljU/edit#gid=2006985773)

Need to extract DNA from frozen samples:
-What is the preferred protocol for this? [Qiagen DNeasy?](https://github.com/RobertsLab/resources/blob/master/protocols/Commercial_Protocols/Qiagen_DNeasy_Blood_and_Tissue.pdf) [Omega Mollusk DNA kit?](http://onsnetwork.org/kubu4/2017/12/11/dna-isolation-quantification-crassotrea-virginica-mantle-gdna/)[Omega manual here](https://github.com/RobertsLab/resources/blob/master/protocols/Commercial_Protocols/Omega_Mollusc-DNA-Kit-Combo-May-2013-D3373.pdf)

Also @kubu4, could we discuss [this notebook entry](http://onsnetwork.org/kubu4/2017/05/11/dna-methylation-quantification-acropora-cervicornis-staghorn-coral-dna-from-javier-casariego-fiu/) tomorrow?

**Comment by kubu4** [comment]
> *these are tissue samples in the -80C but not sure what they are labelled. Ronit's samples?

Correct.

> What is the preferred protocol

E.Z.N.A. Mollusc DNA Kit (Omega)

> Also @kubu4, could we discuss this notebook entry tomorrow?

Of course. Come by any time!

**Comment by sr320** [comment]
I believe @yaaminiv would have sampled tetraploids from Oregon as part of Haws project.

**Comment by yaaminiv** [comment]
From what I remember she never sent any of the tetraploid samples, so I didn't do anything with them

**Comment by sr320** [comment]
There was a box in the windowed 4C - someone extracted tissue - maybe @kubu4 ?

**Comment by sr320** [comment]
Actually they were all triploid and came in late February

**Comment by sr320** [comment]
Found! http://onsnetwork.org/kubu4/2018/02/28/samples-received-triploid-crassostrea-gigas-from-nisbet-oyster-company/

**Comment by kubu4** [comment]
Heads up - it appears these have been moved from the original -80<sup>o</sup>C location indicated in my notebook. They now reside in: Rack 2, Column 1, Row 4 of the -80<sup>o</sup>C.

I've also added the "triploid" tag to the -80<sup>o</sup>C inventory for these.

**Comment by shellytrigg** [comment]
@sr320 here is [my post for the ELISA](https://shellytrigg.github.io/11th-post/) and here is [the post .md file](https://github.com/shellytrigg/shellytrigg.github.io/blob/master/_posts/2018-10-18-11th-post.md) because for some reason I can't get pictures to show on my .io site, but they show up in the .md file.

**Comment by kubu4** [comment]
@shellytrigg - You need this URL:

https://raw.githubusercontent.com/shellytrigg/C_gigas/master/Polyploids/imgs/IMG_20181018_134824.jpg

That's direct link to file. You can get this URL by right-clicking on the "Download" button at the URL you used, and then "Copy Link Location". 

The link you used was a link to the GitHub page that shows the image.

**Comment by shellytrigg** [comment]
yes! thanks @kubu4 !
