### ISSUE TITLE
Color coding stacked barplots by groups in R

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#42]
An issue I've been struggling with the past few days in R: 

My goal is to create a barplot like this, but stacked so that each bar represents the sum of data in three rows of each column:

![image](https://user-images.githubusercontent.com/17264765/29955156-593119c0-8e92-11e7-8ad7-e76a2700bb30.png)

I can get a stacked barplot, but the color & pattern coding falls apart:
![image](https://user-images.githubusercontent.com/17264765/29955176-91adfb6a-8e92-11e7-8eb7-08e2f34cacd1.png)

Here's dummy data and resulting bar plots to describe what's happening: 
```
m = matrix(1:9, ncol = 3, byrow = TRUE)
v = matrix(c("red", "blue", "green"), ncol=3, nrow=3, byrow=TRUE)
m #matrix of values
v #matrix of colors for each point
```
![image](https://user-images.githubusercontent.com/17264765/29955059-5454f044-8e91-11e7-8c60-ea7e128a2627.png)

plot row 1, designating colors correctly
`barplot(m[1,], col=v[1,]) `
![image](https://user-images.githubusercontent.com/17264765/29955070-886f58a6-8e91-11e7-8ca1-5bdf16bfb1c3.png)

plot rows 1-3 stacked correctly
`barplot(m[c(1:3),]) `
![image](https://user-images.githubusercontent.com/17264765/29955073-a0fcb99a-8e91-11e7-9744-d7054c18cd0f.png)

plot rows 1-3 with BESIDE=TRUE, color codes correctly
`barplot(m[c(1:3),], col=v[c(1:3),], beside = TRUE) `
![image](https://user-images.githubusercontent.com/17264765/29955080-b5fa393a-8e91-11e7-86a5-f5043b2c9054.png)

plot rows 1-3, which stacks correctly, but color coding goes away. 
`barplot(m[c(1:3),], col=v[c(1:3),])`
![image](https://user-images.githubusercontent.com/17264765/29955089-cd8255ec-8e91-11e7-93fd-c619f22b7dc0.png)

Any suggestions?

**Comment by kubu4** [comment]
My suggestion would be to use ```ggplot2``` instead. Sorry I can't help more than that. :(

**Comment by sr320** [comment]
Is this resolved?

**Comment by laurahspencer** [comment]
Never figured out how to do it, instead moved to ggplot. Oh well...
