### ISSUE TITLE
Improve -80 inventory descriptions

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#420]
Specifically "Ronit's" should - have other searchable keywords

**Comment by kubu4** [comment]
Any examples? Tissue type (I just made tissue a bit more specific, but it previously had "gill and gut") and species are listed.

**Comment by sr320** [comment]
like triploid, heat stress, temperature. 
thinking about words one might search on...

**Comment by kubu4** [comment]
Interesting. Currently, the spreadsheet is just set up to reflect the box label, sample type (this was intended more for tissue/RNA/DNA/protein, but has expanded to more specific descriptors), and species.

Should we add a "tags" column or something of that nature?

**Comment by sr320** [comment]
Seems like a good idea. If you think about end user - trying to find something in the spreadsheet.

**Comment by kubu4** [comment]
Added tags column and some info for Ronit's stuff.
