### ISSUE TITLE
Split out VCF files into sample specific VCF files

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#421]
This is the large VCF (14G)
http://gannet.fish.washington.edu/seashell/eog/files/VCF_files/SNP.TRSdp5g95FnDNAmaf05.vcf.gz

It contains information on 96 samples. 
I need to get this into 96 separate files

_Big picture is I am trying to get sample specific genome sequence information so I can calculate CpG O/E on oysters throughout the range._

**Comment by sr320** [comment]
Have spent days and days on that to no avail. 
If you could give it a shot and see if you can get it to work, that would be great.

**Comment by kubu4** [comment]
You getting this error using bcftools?

```
Contig 'NC_035780.1' is not defined in the header. (Quick workaround: index the file with tabix.)
Undefined tags in the header, cannot proceed in the sample subset mode.
```

**Comment by sr320** [comment]
This is one error I have come across.

**Comment by kubu4** [comment]
I think I'm getting this taken care of, but this VCF is friggin' huge and it's taking a very long time to process... Will obviously report back once my job(s) finish running.

**Comment by kubu4** [comment]
Quick update. Made some tweaks and have code that is splitting into individual files that actually have data! However, it looks like it's taking ~30mins per sample, so if there are really 96 individuals... 30min x 96 = 2880mins/60mins  per hour = 48hrs

Should be done Wednesday. I'll update here when files are ready.

**Comment by kubu4** [comment]
Whew! All finished.

Results are here:

http://gannet.fish.washington.edu/Atumefaciens/20181015_vcf_split/

Notebook is here:

http://onsnetwork.org/kubu4/2018/10/15/vcf-splitting-with-bcftools/

The TL;DR is:

- Used bcftools ```fill-AC-AN``` plugin on sorted/indexed master VCF file, then code from Biostars produced individual VCFs that actually contain data.

Admittedly, I'm not terribly familiar with what the plug-in actually does/did, so it's definitely worth comparing the master VCF with some of the individual VCF.

Hopefully this worked!!!
