### ISSUE TITLE
Can't cd to Mox /gscratch/srlab directory??!!

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#423]
Anyone else having this issue??

![selection_074](https://user-images.githubusercontent.com/4514104/46754051-53dd0100-cc76-11e8-9676-954b1c4cb094.png)

**Comment by sr320** [comment]
works for me
```
[sr320@mox1 ~]$ cd /gscratch/srlab/
[sr320@mox1 srlab]$ ls
data  programs	sam  scripts  sr320  strigg  tmp  usage_report.txt
```

**Comment by kubu4** [comment]
Thanks for checking. Emailing UW IT now...

**Comment by kubu4** [comment]
I can login and ```cd``` again! No info from UW IT (yet) on what the fix was.
