### ISSUE TITLE
Mox job failed

### ISSUE THREAD

**Issue by jldimond** [RobertsLab/resources#426]
I can't figure out why my Canu job failed after 17 hours. There's nothing in any of the logs that shows the error, and all I get is this:

[jldimond@mox1 ~]$ sjobexitmod -l 353216
       JobID    Account   NNodes        NodeList      State ExitCode DerivedExitCode        Comment 
------------ ---------- -------- --------------- ---------- -------- --------------- -------------- 
353216            srlab        1           n2354     FAILED      1:0             0:0

**Comment by kubu4** [comment]
I wouldn't be surprised it it's related to these two issues:

- #425

- #423 

It looks like both have been resolved, but it wouldn't surprise me if they had to restart nodes or something to fix the problems.

Additionally, did anyone ever receive a confirmation email saying system was back online (as they mentioned in their maintenance email)?

**Comment by jldimond** [comment]
I see. Didn't get any email.

**Comment by sr320** [comment]
I did not get an email. I think something is still weird..

**Comment by sr320** [comment]
back onlne
