### ISSUE TITLE
Why do I get index.html files when using wget?

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#427]
I used `wget` to download a directory off of gannet:

`````
! wget --no-parent -r http://gannet.fish.washington.edu/spartina/2018-10-10-project-virginica-oa-Large-Files/2018-10-03-Bismark-Parameter-Testing/2018-10-03-L012-Output/
`````

I downloaded this list of files:

![untitled](https://user-images.githubusercontent.com/22335838/46834775-3173e200-cd61-11e8-8dbb-44825659d1a8.png)

Where do the index.html files come from?

**Comment by sr320** [comment]
When you go to 
http://gannet.fish.washington.edu/spartina/2018-10-10-project-virginica-oa-Large-Files/2018-10-03-Bismark-Parameter-Testing/2018-10-03-L012-Output/

you are looking at the index.html file. (has title, hyperlinks etc.)

You can view source on the page to see the actual content of said page.

you can ignore this (or just delete after the fact)

**Comment by kubu4** [comment]
Update command to the following:

```wget --no-parent -r -R 'index.html*' http://gannet.fish.washington.edu/spartina/2018-10-10-project-virginica-oa-Large-Files/2018-10-03-Bismark-Parameter-Testing/2018-10-03-L012-Output/```

```-R```: This is for "reject" and specifies files and/or file pattern to match. Files that match are deleted _after_ the ```wget``` command concludes. So, if you interrupt the ```wget``` command, you'll still end up with the annoying ```index.html``` files.
