### ISSUE TITLE
Subscribing to Mox

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#429]
Following the [Adding a User](https://github.com/RobertsLab/hyak_mox/wiki/Adding-a-User) instructions:

I don't "Hyak Services" or "Lolo Server" options:

<img width="724" alt="screen shot 2018-10-12 at 11 24 50 am" src="https://user-images.githubusercontent.com/22335838/46887103-9be45b00-ce11-11e8-9391-b6b73a89dbc3.png">

**Comment by kubu4** [comment]
My b. I think  I have to add you to the Mox group first. One sec...

**Comment by kubu4** [comment]
Ok, give it another go!

**Comment by yaaminiv** [comment]
It worked! I'm not subscribed.
