### ISSUE TITLE
Run Bismark on Oly WGBS  (genome v081)

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#430]
In downstream analyses I realized bismark was done on different genome.

https://github.com/sr320/paper-oly-wgbs/blob/master/notebooks/07-Bismark-Mox.Rmd

Could you run with v081?
https://github.com/RobertsLab/resources/wiki/Genomic-Resources%23genome-2

**Comment by kubu4** [comment]
Also, what's the rational on using the size-filtered genome? Why not use everything we have?

**Comment by kubu4** [comment]
Done:

http://gannet.fish.washington.edu/Atumefaciens/20181015_oly_WGBSseq_v081/

Notebook entry coming later.

**Comment by sr320** [comment]
Having trouble finding code for this - any hints?

**Comment by kubu4** [comment]
http://gannet.fish.washington.edu/Atumefaciens/20181015_oly_WGBSseq_v081/20181015_oly_WGBSseq_v081.sh

**Comment by kubu4** [comment]
My SBATCH scripts are always named the same as the directory, if that helps for future script-finding. :)
