### ISSUE TITLE
score_min L,0,-1.2 data to test parameters with

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#432]
I tried using subset sequences from a previous `bismark` run (see [Jupyter notebook](https://github.com/RobertsLab/project-virginica-oa/blob/master/notebooks/2018-10-03-Bismark-Parameter-Testing.ipynb) and [lab notebook](https://yaaminiv.github.io/DML-Analysis-Part10/)) to test differences in 1x, 3x, and 5x coverage in `methylkit` (see [lab notebook](https://yaaminiv.github.io/DML-Analysis-Part11/)). These subset sequences did not have enough data.

I have three options:

1. Find other deduplicated, sorted, and indexed *C. virginica* full sample data that used -score_min L,0,-1.2 (maybe from @sr320's runs...?) to test coverage with
2. Finish [this `bismark` run](http://gannet.fish.washington.edu/spartina/2018-10-10-project-virginica-oa-Large-Files/2018-10-04-Bismark-Full-Samples-Revised-Parameters/) on hummingbird and use that output. The [files are currently on gannet](http://gannet.fish.washington.edu/spartina/2018-10-10-project-virginica-oa-Large-Files/2018-10-04-Bismark-Full-Samples-Revised-Parameters/)
3. Wait for my data to eventually come from Mox

I'm leaning towards option 2. Any objections/things I'm not considering?

**Comment by sr320** [comment]
Subsettting will not provide enough data to get loci for methylkit -

I would pursue 1-3 as comparison of outcome will be nice comparison.

thanks
Steven


Steven B. Roberts
Kenneth K. Chew Endowed Professor
School of Aquatic and Fishery Sciences
University of Washington, Seattle WA
sr320@uw.edu - 206.866.5141
robertslab.info - @sr320

**Comment by yaaminiv** [comment]
@sr320 Where can I find data from [this notebook](https://github.com/sr320/nb-2018/blob/master/C_virginica/17-OAKL-fullpipe-mk.ipynb)?

**Comment by sr320** [comment]
Can be found @ http://gannet.fish.washington.edu/seashell/bu-serine-wd/18-04-29/
