### ISSUE TITLE
Complete Ronit qPCR for SK proposal

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#433]
We have a proposal due this week and it would be great to get the qPCR data into it. 
Can you have something done this week?
Maybe prep cDNA so PCRs can be run Wednesday?

**Comment by kubu4** [comment]
Sure thing!

**Comment by kubu4** [comment]
Notebook is here: http://onsnetwork.org/kubu4/2018/10/18/qpcrs-ronits-c-gigas-ploidydessicationheat-stress-cdna-15-dilution/

I emailed you data (ugh, sorry) yesterday afternoon.
