### ISSUE TITLE
Remove duplicate proteins if in same cluster

### ISSUE THREAD

**Issue by kaitlynrm** [RobertsLab/resources#434]
I have a [spreadsheet](https://github.com/kaitlynrm/OysterSeedProject/blob/master/analysis/clustering/Silo3_and_9/silo3_9-anno_clus.csv) with duplicate proteins (a protein for silo 3 and a protein for silo 9) with a cluster assignment (created by [this code](https://github.com/kaitlynrm/OysterSeedProject/blob/master/analysis/clustering/Silo3_and_9/clustering-dendrogram_s3_9.R). I am trying to parse out what proteins have different cluster assignments by subsetting (or removing) rows that have proteins in the same cluster for each silo. Retaining the rows beyond the Protein.Id isn't necessary because I can merge that information at a later date if needed in the future. 

Some possible approaches include using the unique function in either Bash or R, creating two datasheets - one for each silo- and comparing them, or multicolumn sorting. 

In this image, **highlighted proteins have the same cluster denomination and thus would need to be removed**, or ideally subsetted. Note that I sorted the columns by descending cluster number in excel to take this screenshot; the vast majority of proteins are in cluster 1 which is evident when you first open the spreadsheet. 

![alt text](https://raw.githubusercontent.com/kaitlynrm/OysterSeedProject/master/analysis/clustering/Silo3_and_9/screenshot-silo3_9-anno-clus.png)

**Comment by kaitlynrm** [comment]
I'm going to try separating the silos and using `anti_join` from `dplyr`.

**Comment by kaitlynrm** [comment]
I did
```
libary(dplyr)

s3.test <-  filter(merge3, Silo == 3)
s9.test <- filter(merge3, Silo == 9)

s9.prot <- anti_join(s9.test, s3.test, by="Cluster")
s3.prot <- anti_join(s3.test, s9.test, by="Cluster")
```
which gives me two dataframes. Each dataframe is comprised of only either silo3 or silo9 proteins. I believe these dataframes are the proteins that did not have any clusters that matched in the opposing silo's dataframe, but I'm not sure how to test that.

**Comment by kaitlynrm** [comment]
I'm going to see if I can use `unique` in R next.

**Comment by kaitlynrm** [comment]
```
#determine if duplicates were removed
anyDuplicated(merge3[,c("Protein.ID","Cluster")]) #returns first duplicated rows, in this case columns 1 and 2 are duplicated so 2 is returned
anyDuplicated(test[,c("Protein.ID","Cluster")]) #returns 0 because there are no duplicates
```

`anyduplicated` returns "an integer or real vector of length one with value the 1-based index of the first duplicate if any, otherwise 0."

**Comment by kaitlynrm** [comment]
@kubu4 could you double check this? It seems like a lot of unique proteins so I just want to be sure I interpreted the final `anyDuplicated` function correctly and the previous code did work as expected.

**Comment by kaitlynrm** [comment]
Oh! There are more than 258 unique proteins because there are proteins that are unique to each silo as well. For example,  CHOYP_2AAA.1.1|m.13307 is only found in Silo 3 and is therefore printed into the new spreadsheet.

**Comment by kubu4** [comment]
Here's bash "one-liner" to do this:

```
awk 'NR >1' silo3_9-anno_clus.csv | sed 's/ /=/g' | sort -t"," -k2,2 -k4,4 | sed 's/\"//g' | sed 's/,/ /g' | uniq -f3 -u | sed 's/ /,/g' | sed 's/=/ /g' > silo3_9-anno_clus_unique.csv
```

And, here's how it works:

```awk 'NR >1' silo3_9-anno_clus.csv```: Skips first record (i.e. line) of your input file, which is your header.

```sed 's/ /=/g'```: Substitutes an equals sign for spaces in your file. Needed to handle formatting for uniq command later. Will be removed at the end. Equals sign was chosen, as it does not appear in your dataset, so makes sure not to mess up existing formatting.

```sort -t"," -k2,2 -k4,4 silo3_9-anno_clus.csv```: Sets delimiter as comma, then sorts on field 2 (Cluster), followed by sorting on field 4 (Protein.ID) of your file.

```sed 's/\"//g'```: Substitutes nothing (i.e. deletes) for the double quotations throughout the file. Not sure why these are present, so I removed them.

```sed 's/,/ /g'```: Substitutes a space for a comma. This is a formatting requirement for the next command.

```uniq -f3 -u```: Retains only unique lines, skipping the first three fields (i.e. works on Protein.ID).

```sed 's/ /,/g'```: Substitutes a comma for spaces. This re-formats the file to CSV.

```sed 's/=/ /g'```: Substitutes a space for equals signs. Restores original file formatting.

```> silo3_9-anno_clus_unique.csv```: Writes the results to a new file. A total of 1532 records.

REMEMBER! This does _not_ have the header any more! I haven't taken the time to figure out how to insert if back (but, I've done this before in some old code; just need to track it down).

**Comment by kubu4** [comment]
Steps to remove and then re-add header.

Run this before running the "one-liner" above:

```header=$(awk 'NR==1' silo3_9-anno_clus.csv | sed 's/\"//g')```: Copies header (first line of file) and removes double quotations from all fields.

After running the "one-liner" above, use these commands to restore the header:

```sed -i.old "1s/^.*$/$header/" silo3_9-anno_clus_unique.csv```: Uses sed to create a backup of the input file (filename.old) and then edit the input file "in place". Inserts header above the existing first line of the input file.

```rm *.old```: Deletes the backup file created by sed.

**Comment by kaitlynrm** [comment]
I checked both files (created by R and Bash) against each other using `anti_join` and they match- thanks!

**Comment by kaitlynrm** [comment]
I forgot to mention, the file created by bash is ~15x larger though (16,406 KB vs. 1,590 KB)

**Comment by kubu4** [comment]
Hmm, when I run that bash command, the output file is 1.5M (1,500KB).

**Comment by kaitlynrm** [comment]
I reran it and got the same file size, but the two tables appear identical... I'm using a Windows and therefore created it in Git Bash- could it write it differently such that the file is larger?

**Comment by kubu4** [comment]
Don't use Git Bash. If on Windows 10, install and run Ubuntu application.

Command does not work with Git Bash. You can see this by counting lines (```wc -l```) of the output file; it's no different than input. That's why you see such a large file size.

I don't have the time to figure out why it doesn't work as expected on Git Bash; sorry!

**Comment by kaitlynrm** [comment]
Ah, I see now I accidentally loaded in the same table twice when I tested it in R. I'll do it on Roadrunner and then test it again correctly. I see that the length did not change last time.

**Comment by kaitlynrm** [comment]
So I ran

`header=$(awk 'NR==1' silo3_9-anno_clus.csv | sed 's/\"//g')`

`awk 'NR >1' silo3_9-anno_clus.csv | sed 's/ /=/g' | sort -t"," -k2,2 -k4,4 | sed 's/\"//g' | sed 's/,/ /g' | uniq -f3 -u | sed 's/ /,/g' | sed 's/=/ /g' > silo3_9-anno_clus_unique.csv`

`sed -i.old "1s/^.*$/$header/" silo3_9-anno_clus_unique.csv`

`rm *.old`

and it created the same file as before on Git Bash (~16000 KB with all lines). I ran just the second code (which would produce the file without the header) and it printed out the same file as when I entered it in the previously stated order, except the file was missing the header- as predicted. I ran these in the terminal on Linux (Roadrunner) this time, and I ran it in the Silo3_9/ directory where silo3_9-anno_clus.csv is located.

**Comment by kubu4** [comment]
Was just looking at this in Git Bash and the original file is _not_ the same as the one that I downloaded the other day. The file I downloaded (and have been working with) the other day had a header that looked like this:

```"","Cluster","Silo","Protein.ID"```

The one I downloaded today to test out Git Bash when it didn't work for you has a header that looks like this:

```"Cluster","Silo","Protein.ID"```

Now. looking at the history for that file, it looks like you removed the numeric row names.

That's why it the "one-liner" above no longer works correctly in Git Bash or in Ubuntu bash...

**Comment by kubu4** [comment]
If you wanted to use that bash one-liner with your updated file, here's an updated one-liner:

```
awk 'NR >1' silo3_9-anno_clus.csv | sed 's/ /=/g' | sort -t"," -k1,1 -k3,3 | sed 's/\"//g' | sed 's/,/ /g' | uniq -f3 -u | sed 's/ /,/g' | sed 's/=/ /g' > silo3_9-anno_clus_unique.csv
```

**Comment by kaitlynrm** [comment]
Ah I see. Yes I changed the first column of those files since it was just a numeric row from R. Another reason besides paths that doing this in R might be easier in the future. Thank you for getting back to me on this!
