### ISSUE TITLE
Brief methods section for SK grant

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#436]
Could you write a brief methods section for constructing both MBDbs and msp-bs library from DNA to sequencer (ie kit names)? 
And estimate cost per/sample

**Comment by kubu4** [comment]
Methylation Enrichment (MBD-BSseq)

High molecular weight genomic DNA will be sheared via sonication to an average fragment size of 350bp using a Bioruptor 300 (Diagenode). Fragmentation will be confirmed on a Bioanlyzer 2100 (Agilent) using the DNA 12000 assay (Agilent). Fragmented DNA will be enriched for methylated fractions using the MethylMiner Methylated DNA Enrichment Kit (Invitrogen). The manufacturer's protocol will be followed, according to the quantities of input DNA, and will be subjected to a single, high-salt elution.

Reduced Representation (RRBSseq)

Genomic DNA will be digested with the methylation insensitive enzyme, MspI (New England Biolabs), which recognizes the following site: C^CGG ("^" represents the cut site). Post-digestion DNA will be evaluated using the DNA 12000 assay (Agilent) on a Bioanalzyer 2100 (Agilent) and then sheared via sonication to an average fragment size of 350bp using a Bioruptor 300 (Diagenode). Fragmentation will be confirmed on a Bioanlyzer 2100 (Agilent) using the DNA 12000 assay (Agilent). End repair and A-tailing will be performed using the KAPA LTP Library Preparation Kit for Illumina platforms (KAPA Biosystems).

Bisulfite Conversion and Sequencing Library Construction

DNA from both methylation enrichment and reduced representation procedures will be prepared for sequencing on an Illumina HiSeq2500. Bisulfite conversion will be performed using the EZ DNA Methylation Gold Kit (ZymoResearch). Library construction and barcoding will be performed using the TruSeq DNA Methylation Kit (Illumina).

---

Cost per sample (does not include sequencing):

MBDBSseq - ~$160

RRBSseq - ~$170

MBD costs are based on getting 10 reactions out of MethylMiner Kit.

RRBSseq costs could be reduced by doing end repair and A-tailing in a "homebrew" method, as opposed to using KAPA LTP Library Prep Kit.

**Comment by sr320** [comment]
Thanks!
