### ISSUE TITLE
Compression issue with split VCFs

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#437]
While the file name appear to suggest the files are zipped. The head command suggest not.
And the lack of specific compression breaks downstream actions.

Can these (or one) be compressed with bgzip so I can test consensus?

![screen shot on 2018-10-17 at 08-43-17](https://user-images.githubusercontent.com/4442039/47098896-f2beab80-d1e8-11e8-9b61-b4f3ab368355.png)

**Comment by kubu4** [comment]
When I  run ```head``` on that file (locally and stored here: http://gannet.fish.washington.edu/Atumefaciens/20181015_vcf_split/SNP.TRSdp5g95FnDNAmaf05.sorted.ANACfill.CS_2.vcf.gz), it's definitely compressed; a bunch of crazy stuff gets spit out.

Also, the ```file``` command when run on that file also says it's compressed (as well as with the others).

Link to your file so I can test?

**Comment by sr320** [comment]
Some unknown problem transferring files from gannet. VCF files on gannet are good.
