### ISSUE TITLE
Did my Mox job fail...?

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#438]
I queued my `bismark` run on Mox and got the following emails:

<img width="931" alt="screen shot 2018-10-17 at 1 25 42 pm" src="https://user-images.githubusercontent.com/22335838/47114287-3c6ebc80-d210-11e8-9348-4c4accd258b5.png">

Does this mean my job failed or did is it still running?

**Comment by kubu4** [comment]
Yes, it failed.

When ExitCode is > 0 (and the word "Failed" is in the email subject, the job did not complete.

Check the slurm-jobID-.out file for hints (```tail slurm-381386.out```).

**Comment by yaaminiv** [comment]
@kubu4 I tried that! I got the following error:

tail: cannot open ‘slurm-381386.out’ for reading: No such file or directory

How can I figure out 1) what happened to my Mox run and 2) where the output file went

**Comment by kubu4** [comment]
The output file is in your working directory (designated in the header of your SBATCH script).

**Comment by kubu4** [comment]
```
#!/bin/bash
## Job Name
#SBATCH --job-name=20181015_bismark
## Allocation Definition
#SBATCH --account=srlab
#SBATCH --partition=srlab
## Resources
## Nodes
#SBATCH --nodes=1
## Walltime (days-hours:minutes:seconds format)
#SBATCH --time=10-00:00:00
## Memory per node
#SBATCH --mem=120G
##turn on e-mail notification
#SBATCH --mail-type=ALL
#SBATCH --mail-user=samwhite@uw.edu
## Specify the working directory for this job
#SBATCH --workdir=/gscratch/scrubbed/samwhite/20181015_oly_WGBSseq_v081
```

The last line of the SBATCH header specifies working directory (i.e. location of all output files).

**Comment by yaaminiv** [comment]
Turns out my job failed because my working directory path had a typo. I fixed that and now the job is running!

One last tangential question: do I have to keep the terminal window where I run my commands on Mox open during the job?

**Comment by sr320** [comment]
you are running now...

```
[sr320@mox1 ~]$ squeue | grep srlab
            359332     srlab  Ae_canu jldimond  R 5-03:42:20      1 n2211
            381403     srlab 20181012 yaaminiv  R       2:01      1 n2357
```

**Comment by sr320** [comment]
>One last tangential question: do I have to keep the terminal window where I run my commands on Mox open during the job?
no

**Comment by kubu4** [comment]
No need to leave terminal window open.
