### ISSUE TITLE
Create an amazing syllabus

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#439]
My R class needs a proper syllabus for formal review. 
https://sr320.github.io/course-fish497-2018/

See what you can scrape from the website- modeling after some good one below and the following advice:
>It helps to pay a lot of attention to content (SAFS interest), Learning goals  and how learning goals are achieved (SAFS and College pay attention), reading lists (College cares) and policy statements (College and UW CC pay a lot of attention to these). You can also find resources here:
https://environment.uw.edu/intranet/academics/curriculum/proposing-a-new-course/
https://environment.uw.edu/intranet/academics/teaching/sample-syllabus-disability-statement/
http://www.washington.edu/teaching/teaching-resources/preparing-to-teach/designing-your-course-and-syllabus/

[370_2016_Marine_Evolutionary_Biology_syllabus.pdf](https://github.com/RobertsLab/resources/files/2491896/370_2016_Marine_Evolutionary_Biology_syllabus.pdf)
[Fish 427 Tropical Marine Biology course application.pdf](https://github.com/RobertsLab/resources/files/2491897/Fish.427.Tropical.Marine.Biology.course.application.pdf)
[Fish_270_newCourse.pdf](https://github.com/RobertsLab/resources/files/2491898/Fish_270_newCourse.pdf)
[Fish_406_Parasite_Ecology _Syllabus_04.12.17.pdf](https://github.com/RobertsLab/resources/files/2491900/Fish_406_Parasite_Ecology._Syllabus_04.12.17.pdf)

**Comment by kaitlynrm** [comment]
Hopefully that's amazing enough for administration!
