### ISSUE TITLE
Pump location

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#44]
Kicking tires on new github 

I used 
https://docs.google.com/spreadsheets/d/11RA_mlLB-3m_GySnTTuDazDdOi0bCxJu2VERuX9Qfx8/edit#gid=0

to try to find out where the peristaltic pump is?

No success with "Find" in google sheets..

**Comment by kubu4** [comment]
Any chance you have more info on this? I can't even find a peristaltic pump listed on purchasing log...

**Comment by sr320** [comment]
Aaahh good point - I should have checked that first!


Masterflex L/S Precision Variable-Speed Console Drive 6-600 rpm (Cat: GH-07528-10); Easy-Load II pump heads of high performance precision pump tubing. stainless steel rotor. x 2 (Cat: GH-77200-62); Norprene Food L/S 35 (50ft/pack; Cat: GH-06402-35)

**Comment by kubu4** [comment]
Ah! See storage location on purchasing log. It was never unboxed since I thought it was going to be taken to the hatchery. Thus, it's in "inventory limbo" and was never entered on inventory sheet.

**Comment by sr320** [comment]
Gotcha Thanks!
