### ISSUE TITLE
C. bairdi seq data

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#440]
I saw @kubu4 's [post](http://onsnetwork.org/kubu4/2018/10/15/data-received-chionoecetes-bairdi-rnaseq-fastqc-analysis/) about where the new sequence data is! yay

I know I need to keep isolating RNA (current plan: Tri-reagent without lyophilizing, even though bioanalyzer results didn't look great - yields are pretty low). Will pick that back up tomorrow since I have class in a bit today. 

Can I start doing stuff with the sequence data - can I use it for FISH 546?

**Comment by sr320** [comment]
Yes I would replicate what @kubu4 has done with regard to running fastqc, trimming reads
