### ISSUE TITLE
Multipanel plot from methylKit output

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#441]
This is not super critical, but I was wondering if there was any way to create a multipanel plot to visualize some `methylKit` output.

I'm working in [this R Markdown file](
https://github.com/RobertsLab/project-virginica-oa/blob/master/analyses/2018-10-11-MethylKit-Parameter-Testing/2018-10-11-MethylKit-Parameter-Testing.Rmd). When I use the `getMethylationStats` or `getCoverageStats` functions, I can produce plots like the ones below for each sample:

![percent CpG methylation](https://raw.githubusercontent.com/RobertsLab/project-virginica-oa/master/analyses/2018-10-11-MethylKit-Parameter-Testing/2018-10-14-Steven-Samples/2018-10-11-Percent-CpG-Methylation-1xCoverage-Sample1.jpeg)

![percent CpG coverage](https://raw.githubusercontent.com/RobertsLab/project-virginica-oa/master/analyses/2018-10-11-MethylKit-Parameter-Testing/2018-10-14-Steven-Samples/2018-10-11-Percent-CpG-Coverage-1xCoverage-Sample1.jpeg)

These are useful plots, but it's a pain to click through all %methylation or %coverage for each of my 10 samples. I would like to create a 5 row x 2 column multipanel plot for all my samples so I can look at 1 figure to compare %methylation or %coverage across samples. Here's what I've tried so far:

1. I tried creating a for loop with the following structure to create a multipanel plot:

`````
par(mfrow = c(5, 2)) #Places all my plots in a 5 row x 2 column grid, filling it in my rows
for (i in nFiles) { #For each sample file
  getCoverageStats(processedFilesCov1[[i]], plot = TRUE, both.strands = FALSE) #Plot the coverage stats
}
`````

This produced an error saying that my plot window was too small for the object being created. I tried messing with `oma` to contract any outer margins and give the plot more space, but it still didn't work.

2. Then, I tried saving the `getCoverageStats` output in an object, then plotting that object. However, the function's output cannot be saved in an object (I just end up creating an empty object).

I don't see anything about create a multipanel plot in the [user guide](https://bioconductor.org/packages/devel/bioc/vignettes/methylKit/inst/doc/methylKit.html#6_frequently_asked_questions). Am I just trying to do something that cannot be done?

**Comment by kubu4** [comment]
Try faceting with ggplots. Scroll down to Faceting section on this page:

https://datacarpentry.org/R-ecology-lesson/04-visualization-ggplot2.html

**Comment by yaaminiv** [comment]
@kubu4 Faceting "split[s] one plot into multiple plots based on a factor included in the dataset." I'm trying to take 10 individual plots and merge them into one! I skimmed through the Faceting section and it doesn't seem like I can apply it to this situation.

**Comment by sr320** [comment]
I have not figured that out

> 
<sub>[View in Slack](https://genefish.slack.com/archives/CDBLV05PY/p1539889992000100)</sub>

**Comment by kubu4** [comment]
This doesn't seem _too_ terrible...

https://cran.r-project.org/web/packages/egg/vignettes/Ecosystem.html

**Comment by yaaminiv** [comment]
I realize I should have emphasized this in my initial post, but the plotting option is something that comes out of `methylKit` itself:

`````
getCoverageStats(objectOfInterest, plot = TRUE, both.strands = FALSE)
`````

And again, I was unable to save the output from that as a separate object. The vignette above uses saved plot objects to create a multipanel plot.

Darn! So many cool options, but none of them applicable.

**Comment by kubu4** [comment]
Possible solution(s) [read through all of the answers - many options]:

https://stackoverflow.com/questions/29583849/save-a-plot-in-an-object
