### ISSUE TITLE
Decision on mincov in methylKit

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#442]
[Lab notebook entry](https://yaaminiv.github.io/DML-Analysis-Part13/)

In `methylKit`, I altered the `mincov` metric to see how it affected sample clustering and DMLs. I used  `mincov` = 1, 3, or 5. I tested these metrics on [deduplicated and sorted samples Steven created](http://gannet.fish.washington.edu/seashell/bu-serine-wd/18-04-29/) and [deduplicated and sorted sample files I made on genefish](http://gannet.fish.washington.edu/spartina/2018-10-10-project-virginica-oa-Large-Files/2018-10-04-Bismark-Full-Samples-Revised-Parameters/). Both sets of sample files produced the same results. Output from pipeline tests can be found [here](https://github.com/RobertsLab/project-virginica-oa/tree/master/analyses/2018-10-11-MethylKit-Parameter-Testing).

**Table 1**. The `mincov` metric, total number of loci produced, and the number of DMLs that were at least 50% different between treatment andc control samples. More restrictive `mincov` metrics produced less significantly different DMLs.

| **`mincov`** | **Total Loci** | **Number of Significantly Different DMLs** |
|:------------:|:--------------:|:------------------------------------------:|
|       1      |     1112085    |                    4904                    |
|       3      |     670301     |                    1398                    |
|       5      |     503780     |                     816                    |

@sr320: I haven't dug into the .csv files with DMLs for each `mincov` yet, but just based on the dendrogram and PCA, I think `mincov = 3` maximizes similarity between samples in their respective treatment groups and gives us enough coverage to identify DMLs. I feel comfortable proceeding with `mincov = 3` for future analyses. Thoughts?

**Comment by sr320** [comment]
Sure - you can move ahead with `3` but this table is beneficial and useful in our discussion Tuesday.
