### ISSUE TITLE
How do I know if FASTQC results are good?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#443]
I ran the four .fastq files in [/nightingales/C_bairdi/](http://owl.fish.washington.edu/nightingales/C_bairdi/) through FASTQC.

I think they look fine, based on the "Basic Statistics" category that lists zero sequences being flagged for poor quality for all four files. 

**Is there anything else that I should consider?**
![screen shot 2018-10-19 at 3 30 17 pm](https://user-images.githubusercontent.com/14934314/47246677-171ab380-d3b4-11e8-9242-60f82e11c198.png)

**Comment by sr320** [comment]
Can you put output on owl or github - and provide corresponding url so we can see?

thanks
Steven


Steven B. Roberts
Kenneth K. Chew Endowed Professor
School of Aquatic and Fishery Sciences
University of Washington, Seattle WA
sr320@uw.edu - 206.866.5141
robertslab.info - @sr320

**Comment by grace-ac** [comment]
[reports](https://github.com/fish546-2018/grace-Cbairdi-transcriptome/tree/master/analyses)

In the .zip files

**Comment by sr320** [comment]
This is the url I was looking for.... :)
http://htmlpreview.github.io/?https://github.com/fish546-2018/grace-Cbairdi-transcriptome/blob/master/analyses/304428_S1_L001_R1_001_fastqc.html

thanks
Steven


Steven B. Roberts
Kenneth K. Chew Endowed Professor
School of Aquatic and Fishery Sciences
University of Washington, Seattle WA
sr320@uw.edu - 206.866.5141
robertslab.info - @sr320
