### ISSUE TITLE
Write privileges for Gannet

### ISSUE THREAD

**Issue by jldimond** [RobertsLab/resources#444]
Apparently I don't have the ability to upload files to Gannet. Can someone grant me access? Thanks

![screen shot 2018-10-19 at 3 28 02 pm](https://user-images.githubusercontent.com/9869457/47246863-ff8ffa80-d3b4-11e8-8700-788196f33882.png)

**Comment by kubu4** [comment]
You should be good now. Sorry for the hiccup!

**Comment by jldimond** [comment]
Awesome, thanks!
