### ISSUE TITLE
"Hyak server" and "Lolo server" not showing up

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#446]
[Step 3](https://github.com/RobertsLab/hyak_mox/wiki/Adding-a-User) of "Adding a User", "Hyak Server" and "Lolo server" are not listed in my Inactive Services. 

![screen shot 2018-10-22 at 2 08 56 pm](https://user-images.githubusercontent.com/14934314/47319824-8d155980-d604-11e8-8842-4acb15b480cf.png)
![screen shot 2018-10-22 at 2 10 49 pm 2](https://user-images.githubusercontent.com/14934314/47319832-930b3a80-d604-11e8-9e3b-6506cc31a99e.png)

**Comment by kubu4** [comment]
Sorry, just saw this. They should be available options now. Either refresh the page, or logout/login.

**Comment by grace-ac** [comment]
Got them! Thanks!
