### ISSUE TITLE
can't read.csv from OWL into R

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#447]
Trying to ```read.csv``` my Qubit data from Owl into R. getting errors.

Owl link to csv --> http://owl.fish.washington.edu/scaphapoda/grace/Crab-project/Qubit/QubitData_2018-10-19_13-22-52.csv

Here's my script where this is happening: https://github.com/RobertsLab/project-crab/blob/master/scripts/all-hemo-fixing.R

Errors:    
![screen shot 2018-10-22 at 3 29 27 pm](https://user-images.githubusercontent.com/14934314/47323135-6ad50900-d60f-11e8-8abf-e7d2ea13169d.png)

**Comment by grace-ac** [comment]
yaamini showed me a way to connect to owl on my laptop, so I think I'll just use that.

**Comment by kubu4** [comment]
Or, should this file exist in your repo?

**Comment by kubu4** [comment]
Also, I think the code you wanted was:

```qubitnew <- read.csv(url("http://owl.fish.washington.edu/scaphapoda/grace/Crab-project/Qubit/QubitData_2018-10-19_13-22-52.csv"), header = TRUE, fileEncoding = "latin1")```

**Comment by kubu4** [comment]
Never mind, that doesn't seem to work.

**Comment by grace-ac** [comment]
Yes, it could live in the [data](https://github.com/RobertsLab/project-crab/tree/master/data) directory, but it'll just get really messy in there as I keep adding Qubit data. That's why I was using Owl for all those small Qubit data files.

**Comment by kubu4** [comment]
If you don't want to keep the files in your repo, then it would be best to write your script to download the files first, then work on them, as opposed to working on them from a directory of Owl mounted on your local computer. The latter method breaks the ability for other people to re-run your script.

**Comment by grace-ac** [comment]
Yeah, I thought that might be the case! I'm still trying to figure out how to read the csv in... reopen issue!

**Comment by kubu4** [comment]
It's the encoding issue that we keep encountering with these Qubit CSVs...

Need to figure out a way to get rid of the junk (the "rights reserved" symbol and the "mu" symbol). This can likely be done with a bash program, but will need to do some hunting.

**Comment by kubu4** [comment]
This command will do it:

```
iconv -f utf-8 -t utf-8 -c QubitData_2018-10-19_13-22-52.csv | head -n 1

Run ID,Assay Name,Test Name,Test Date,Qubit tube conc.,Units,Original sample conc.,Units,Sample Volume (L),Dilution Factor,Std 1 RFU,Std 2 RFU,Std 3 RFU,Excitation,Emission,Green RFU,Far Red RFU,tube_number
```

But, notice that the "mu" is stripped from the "Sample Volume" column; it will need to be added back in.

**Comment by grace-ac** [comment]
should that happen in terminal? I'm unsure how to use that command. 

I can ask about this in person tomorrow am if it's difficult to explain in issue.

**Comment by kubu4** [comment]
To flesh this out, here's the whole bash "one-liner":

```
iconv -f utf-8 -t utf-8 -c QubitData_2018-10-19_13-22-52.csv | \
sed 's/(L)/(uL)/g' | \
sed 's/ng\/L/ng\/uL/g' \
> QubitData_2018-10-19_13-22-52_UTF8.csv
```

```iconv -f utf-8 -t utf-8 -c QubitData_2018-10-19_13-22-52.csv```: Uses ```iconv``` to convert file encoding to UTF8, which strips out weird characters.

```sed 's/(L)/(uL)/g'```: Uses ```sed``` to find ```(L)``` and replace with ```(uL)```.

```sed 's/ng\/L/ng\/uL/g'```: Uses ```sed``` to find ```ng/L``` and replace with ```ng/uL```. Backslashes are needed in the ```sed``` command to escape" the forward slashes to prevent ```sed``` from interpreting them as part of the substitute command.

```> QubitData_2018-10-19_13-22-52_UTF8.csv```: Writes output to new file.

**Comment by kubu4** [comment]
Yes, this happens using bash. You can use bash in R by using the ```sys.arg()``` function. Something like this (haven't tested):

```
system("iconv -f utf-8 -t utf-8 -c QubitData_2018-10-19_13-22-52.csv | sed 's/(L)/(uL)/g' | sed 's/ng\/L/ng\/uL/g' > QubitData_2018-10-19_13-22-52_UTF8.csv")

**Comment by kubu4** [comment]
First attempt didnt work, needs additional backslashes:

system("iconv -f utf-8 -t utf-8 -c QubitData_2018-10-19_13-22-52.csv | sed 's/(L)/(uL)/g' | sed 's/ng\\/L/ng\\/uL/g' > QubitData_2018-10-19_13-22-52_UTF8.csv") ```

**Comment by grace-ac** [comment]
it worked! it made the "rights reserved" symbol into <a8> and the "µ" into <b5>, but that doesn't matter because I change the "Original.sample.conc." column into "Original_sample_conc_ng.ul" to include the units. 

Thanks @kubu4 !

**Comment by grace-ac** [comment]
Reopening because something interesting happened - all the column names are in Row 1, when they should be where the "V1"...etc. are:     
![screen shot 2018-10-22 at 7 37 05 pm](https://user-images.githubusercontent.com/14934314/47331773-08d9cb00-d632-11e8-9048-674a81901bb6.png)

**Comment by kubu4** [comment]
> I change the "Original.sample.conc." column into "Original_sample_conc_ng.ul" to include the units.

How did you do this? And, out of curiosity, why? To remove spaces in column names?

**Comment by grace-ac** [comment]
No, to add the units to the column name so that the "Units" column in the Qubit is not needed.

I add the "_" because my [hemosample_qubit_table.csv](https://github.com/RobertsLab/project-crab/blob/master/analyses/hemosample_qubit_table.csv) that I ```left_join``` the new Qubit data with has that name.

**Comment by grace-ac** [comment]
And I can't find where I said:    
> I change the "Original.sample.conc." column into "Original_sample_conc_ng.ul" to include the units.

But, regardless of where I said it, I can't change it anymore. I think because the column names for the Qubit data are now in Row 1.

**Comment by kubu4** [comment]
The issue is that it's not reading the first line as the header. I recommend putting the Qubit data file in your repo or using the ```download.file()``` function to work on the file locally (i.e. on your computer), as the ```read.csv()``` function works without issue.

**Comment by grace-ac** [comment]
oh man. okay. I'll take a look at this! Thanks, @kubu4

**Comment by sr320** [comment]
Do keep all Qubit data in your repo - simply make a subdirectory where all files reside.
