### ISSUE TITLE
Check Extra Disk status for Owl

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#45]

**Comment by kubu4** [comment]
This is <not> disk inventory.

Just adding this for reference to make inventory identification (and purchasing decisions) easier:

Owl (Synology DS1812+) uses 4TB HDDs (n = 8)
Extension unit (Synology DX513-2) uses 8TB HDDs (n =5).

**Comment by kubu4** [comment]
Also, we should probably add available HDDs to inventory.

**Comment by kubu4** [comment]
Extra disk status:

Owl - 0
DX513 - 2
Eagle - 1

I'll order two HDDs for Owl.
