### ISSUE TITLE
How do I upload .fastq files to Mox?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#451]
I have a log-in for Mox and have logged in successfully. 

I found data storage and system organization on wiki: https://github.com/RobertsLab/hyak_mox/wiki/Data-Storage-&-System-Organization 

How do I upload [ the files](http://owl.fish.washington.edu/nightingales/C_bairdi/) to Mox through command line?

**Comment by grace-ac** [comment]
never mind - found info in the wiki https://github.com/RobertsLab/hyak_mox/wiki/Data-Storage-&-System-Organization

**Comment by kubu4** [comment]
Look at the file transfers section of the wiki.

**Comment by sr320** [comment]
We should probably update the wiki to have a recommended directory structure.
I suggest in srlab/grace create a logical directory structure,
Like class, data, analyses, scripts, etc

thanks
Steven


Steven B. Roberts
Kenneth K. Chew Endowed Professor
School of Aquatic and Fishery Sciences
University of Washington, Seattle WA
sr320@uw.edu - 206.866.5141
robertslab.info - @sr320

**Comment by grace-ac** [comment]
```[graceac9@mox1 ~]$ cd /gscratch/srlab/graceac9/data/
[graceac9@mox1 data]$ pwd
/gscratch/srlab/graceac9/data
[graceac9@mox1 data]$ ls
[graceac9@mox1 data]$ rsync --archive --progress --verbose graciecrandall@205.175.107.122:/Users/graciecrandall/Downloads/304428_S1_L001_R1_001.fastq .
^Crsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(557) [Receiver=3.0.9]
[graceac9@mox1 data]$ rsync --archive --progress --verbose graciecrandall@205.175.107.122:/Users/graciecrandall/Downloads/304428_S1_L001_R1_001.fastq . 
```

Error I'm getting:

```ssh: connect to host 205.175.107.122 port 22: Connection timed out
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(605) [Receiver=3.0.9]
```

I have my firewalls disabled.

**Comment by grace-ac** [comment]
```
D-10-19-119-59:~ graciecrandall$ pwd
/Users/graciecrandall
D-10-19-119-59:~ graciecrandall$ rsync --archive --progress --verbose graciecrandall@205.175.107.122:/Users/graciecrandall/Downloads/304428_S1_L001_R1_001.fastq /gscratch/srlab/graceac9/data/
ssh: connect to host 205.175.107.122 port 22: Operation timed out
rsync: connection unexpectedly closed (0 bytes received so far) [receiver]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/io.c(453) [receiver=2.6.9]
D-10-19-119-59:~ graciecrandall$

**Comment by sr320** [comment]
Going from computer- all you need is the path to files

**Comment by sr320** [comment]
graciecrandall$ rsync --archive --progress --verbose /Users/graciecrandall/Downloads/304428_S1_L001_R1_001.fastq gra@mox.hyak.uw.edu:/gscratch/srlab/graceac9/data/


With correct user name

**Comment by grace-ac** [comment]
thank you!!
