### ISSUE TITLE
Trinity: Error; cannot find path to bowtie2 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#452]
Here's what I have, basing off of what @kubu4  has done in [his notebook](http://onsnetwork.org/kubu4/2018/09/19/transcriptome-assembly-olympia-oyster-rnaseq-data-with-trinity/)    

**Questions**
1. Does everything look ok?
2. What do I do about bowtie2 error? 

```
[graceac9@mox1 srlab]$ pwd
/gscratch/srlab
[graceac9@mox1 srlab]$ #!/bin/bash
[graceac9@mox1 srlab]$ ## Job Name
[graceac9@mox1 srlab]$ #SBATCH --job-name=20181024_Cbairdi_trinity_01
[graceac9@mox1 srlab]$ ## Allocation Definition 
[graceac9@mox1 srlab]$ #SBATCH --account=srlab
[graceac9@mox1 srlab]$ #SBATCH --partition=srlab
[graceac9@mox1 srlab]$ ## Resources
[graceac9@mox1 srlab]$ ## Nodes 
[graceac9@mox1 srlab]$ #SBATCH --nodes=1   
[graceac9@mox1 srlab]$ ## Walltime (days-hours:minutes:seconds format)
[graceac9@mox1 srlab]$ #SBATCH --time=90:30:00
[graceac9@mox1 srlab]$ ## Memory per node
[graceac9@mox1 srlab]$ #SBATCH --mem=500G
[graceac9@mox1 srlab]$ ## Specify the working directory for this job
[graceac9@mox1 srlab]$ #SBATCH --workdir=/gscratch/srlab/graceac9/analyses/1024
[graceac9@mox1 srlab]$ 
[graceac9@mox1 srlab]$ /gscratch/srlab/programs/trinity/Trinity \
> --seqType fq \
> --max_memory 100G \
> --left /gscratch/srlab/graceac9/data/304428_S1_L001_R1_001.fastq,\
> /gscratch/srlab/graceac9/data/304428_S1_L002_R1_001.fastq \
> --right /gscratch/srlab/graceac9/data/304428_S1_L001_R2_001.fastq,\
> /gscratch/srlab/graceac9/data/304428_S1_L002_R2_001.fastq \
> --trimmomatic \
> --CPU 28
Left read files: $VAR1 = [
          '/gscratch/srlab/graceac9/data/304428_S1_L001_R1_001.fastq',
          '/gscratch/srlab/graceac9/data/304428_S1_L002_R1_001.fastq'
        ];
Right read files: $VAR1 = [
          '/gscratch/srlab/graceac9/data/304428_S1_L001_R2_001.fastq',
          '/gscratch/srlab/graceac9/data/304428_S1_L002_R2_001.fastq'
        ];
Trinity version: Trinity-v2.4.0
** NOTE: Latest version of Trinity is Trinity-v2.8.4, and can be obtained at:
	https://github.com/trinityrnaseq/trinityrnaseq/releases

which: no bowtie2 in (/gscratch/srlab/programs/trinity/trinity-plugins/BIN:/sw/local/bin:/usr/lib64/qt-3.3/bin:/sw/modules-1.775/bin:/usr/lpp/mmfs/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/lusers/graceac9/bin)
which: no bowtie2-build in (/gscratch/srlab/programs/trinity/trinity-plugins/BIN:/sw/local/bin:/usr/lib64/qt-3.3/bin:/sw/modules-1.775/bin:/usr/lpp/mmfs/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/lusers/graceac9/bin)
Error, cannot find path to bowtie2 () or bowtie2-build (), which is now needed as part of Chrysalis' read scaffolding step.  If you should choose to not run bowtie, include the --no_bowtie in your Trinity command.

**Comment by kubu4** [comment]
I'm not exactly sure what you've pasted here.

You shouldn't have all of these:

```[graceac9@mox1 srlab]$```

Or, all of these:

```>```

**Comment by kubu4** [comment]
Where is your script located? I can't find it.

Also, I needed this line when I last ran Trinity (doesn't resolve bowtie error, but will prevent a problem with Trinity later on)

```
# Load Python Mox module for Python module availability

module load intel-python3_2017
```

**Comment by kubu4** [comment]
bowtie2 error is because bowtie2 isn't currently in your ```$PATH```. That means you'll probably also have to add ```jellyfish``` and ```salmon``` to your ```$PATH```.

To do so, add the following text to your ```~/.bashrc``` file:

```
# Custom PATH

export PATH="$PATH:\
/gscratch/srlab/programs/bowtie2-2.3.4.1-linux-x86_64:\
/gscratch/srlab/programs/anaconda3/bin/cutadapt:\
/gscratch/srlab/programs/FastQC:\
/gscratch/srlab/programs/jellyfish-2.2.10/bin:\
/gscratch/srlab/programs/salmon-0.11.2-linux_x86_64/bin:\
/gscratch/srlab/programs/samtools-1.9"
```

**Comment by grace-ac** [comment]
Yeah, I'm not entirely sure what I'm doing! 

I literally just copy and pasted the script from TextWrangler into my terminal while logged in to Mox. 

...Which I now understand is not the way to go. Now I'm thinking that I send the job via the script file rather than copy and pasting it ...

Here's where my script lives: https://github.com/fish546-2018/grace-Cbairdi-transcriptome/blob/master/scripts/20181024_Cbairdi_trinity_01.sh

**Comment by kubu4** [comment]
Correct, you cannot copy and paste script to run it. Script has to be on Mox and then needs a special command to run it; see the Mox wiki.

**Comment by kubu4** [comment]
I looked at script. You need to put the Custom PATH stuff in your ```~/.bashrc``` file.

**Comment by kubu4** [comment]
Also, after adding that to your ```~./bashrc``` file, you'll need to source the file so the computer finds the new info:

```source ~/.bashrc```

**Comment by sr320** [comment]
Or she could use absolute paths- that is what I teach them in class

**Comment by grace-ac** [comment]
Is ```~/.bashrc``` file the same thing as the script file?

**Comment by sr320** [comment]
Let’s not mess with bashrc yet

**Comment by sr320** [comment]
Pg 396 in textbook... for info on scripts

**Comment by kubu4** [comment]
Those programs need to be available in the system $PATH for Trinity to run. Absolute or relative paths have no bearing, as long as the programs are available in the system $PATH.

**Comment by kubu4** [comment]
Or, maybe that export PATH command _will_ work in your SBATCH script the way you already have it... Hmmm...

**Comment by grace-ac** [comment]
well I guess we'll find out! just started running job on Mox

**Comment by kubu4** [comment]
Exciting!

However, I noticed you'll be using this version of Trinity:

```/gscratch/srlab/programs/trinity/Trinity```

That's a pretty old version (2.40) and is nearly two years old at this point. I'd recommend using the newer version:

```/gscratch/srlab/programs/Trinity-v2.8.3/Trinity```

However, since you'll be using the old version, I don't think you'll actually need those programs in your PATH; I think they came bundled with Trinity back then.

**Comment by grace-ac** [comment]
Yep, got an error:    
```
[graceac9@mox2 1024]$ head slurm-401714.out 
Left read files: $VAR1 = [
          '/gscratch/srlab/graceac9/data/304428_S1_L001_R1_001.fastq',
          '/gscratch/srlab/graceac9/data/304428_S1_L002_R1_001.fastq'
        ];
Right read files: $VAR1 = [
          '/gscratch/srlab/graceac9/data/304428_S1_L001_R2_001.fastq',
          '/gscratch/srlab/graceac9/data/304428_S1_L002_R2_001.fastq'
        ];
Trinity version: Trinity-v2.4.0
-ERROR: couldn't run the network check to confirm latest Trinity software version.
```

Will fix Trinity version in script and re do. 

**Any other things I should fix before I send the job again?**

**Comment by sr320** [comment]
Trinity completed

**Comment by sr320** [comment]
Screenshot of your fasta
https://d.pr/i/VzHPAC

**Comment by grace-ac** [comment]
Oh, I didn't fully read the error correctly... thought it said it couldn't run trinity because it wasn't the updated version. 

I'll check the fq files and compare to source!

**Comment by grace-ac** [comment]
These are the files I had in the script:     
```
304428_S1_L001_R1_001.fastq
304428_S1_L002_R1_001.fastq
304428_S1_L001_R2_001.fastq
304428_S1_L002_R2_001.fastq
```

These are the files that are in the ```trinity_out_dir```:     
```
304428_S1_L001_R1_001.fastq.PwU.qtrim.fq 
304428_S1_L001_R2_001.fastq.PwU.qtrim.fq
304428_S1_L002_R1_001.fastq.PwU.qtrim.fq
304428_S1_L002_R2_001.fastq.PwU.qtrim.fq
```

The numbers are correct in the .fastq file names, but I'm not sure if the added extensions of ".PwU.qtrim.fq" means that there was a problem?

**Comment by sr320** [comment]
I was referring to fq files you assembled (4 in script)- are these the same as files on nightingales?
Think md5...

**Comment by kubu4** [comment]
> but there is likely problem with your fq files

Why do you think this? I'm not following.

**Comment by grace-ac** [comment]
the files are from [/nightingales/C_bairdi/](http://owl.fish.washington.edu/nightingales/C_bairdi/). I downloaded them, and then uploaded them to my data directory on mox. 

I didn't do md5, but [Sam did](http://onsnetwork.org/kubu4/2018/10/15/data-received-chionoecetes-bairdi-rnaseq-fastqc-analysis/)

**Comment by kubu4** [comment]
MD5 is a program that generates a unique code (checksum) for a file. Transferring data from one place to another can corrupt a file (larger files are more prone to corruption during transfer). You can use the MD5 checksum originally generated for the file to compare the MD5 checksum generated after a file is transferred. If the checksums match it means the transferred file is exactly the same as the original. If the checksums do not match, something got corrupted during transfer.

So, any time you copy/move any FastQ files, you should compare the checksums. 

Pro tip: Using rsync to copy files actually has this functionality built in and will do it automatically.

**Comment by grace-ac** [comment]
Right! We learned about that in class a few weeks ago. 

Cool! Since I used rsync, the files are fine then?

**Comment by sr320** [comment]
Nice!
Never hurts to check though...

Golden rule of bioinformatics?

**Comment by grace-ac** [comment]
Never trust your data or your tools!

**Comment by kubu4** [comment]
> I downloaded them, and then uploaded them to my data 

You used ```rsync``` for both steps?

Also, as @sr320 mentioned, it never hurts to check! The process is quick.

**Comment by grace-ac** [comment]
Nope, I downloaded them without ```rsync```. I uploaded using ```rsync```.

Yes! I will do md5! I'll look back at the textbook and the class notes.

**Comment by kubu4** [comment]
Heads up. Macs use a program called ```md5```, while Linux (i.e. Mox) uses a program called ```md5sum```. They will generate the same checksum for a given file, but the output will be formatted differently. This can make it a pain to compare checksums computationally. 

However, you can use the ```-r``` flag on Macs to get the output to match that of Linux ```md5sum```. E.g.

```md5 -r fastq.fq.gz```

You can also have ```md5/md5sum``` work with wildcards to generate checksums for a set of files:

```md5 -r *.fq.gz```

**Comment by grace-ac** [comment]
@kubu4 helped me and we figured out that I was using ```.fastq``` files, not the ```.fast.gz```.

For some reason my laptop, automatically unzips the files...? And they are only 64K, so they aren't the true unzipped files. 

![screen shot 2018-10-30 at 10 51 48 am](https://user-images.githubusercontent.com/14934314/47742161-409bd080-dc39-11e8-9a3f-798b2a705d94.png)

Anyway, @kubu4 showed me how to ```rsync``` the files from [/nightingales/C_bairdi/](http://owl.fish.washington.edu/nightingales/C_bairdi/) into my Mox data folder. 

![screen shot 2018-10-30 at 10 58 08 am](https://user-images.githubusercontent.com/14934314/47742193-56a99100-dc39-11e8-96d9-f526f6aae543.png)

I ran md5 and compared results to the [md5 in nightingales](http://owl.fish.washington.edu/nightingales/C_bairdi/checksums.md5), and the files look good.
![screen shot 2018-10-30 at 11 28 57 am](https://user-images.githubusercontent.com/14934314/47742301-9a03ff80-dc39-11e8-8022-62da78741384.png)


### **I have now changed the file names in my [.sh](https://github.com/fish546-2018/grace-Cbairdi-transcriptome/blob/master/scripts/20181030_Cbairdi_trinity_01.sh) and will re-run Trinity**
