### ISSUE TITLE
Recent Titrator notes and script?

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#453]
@ksil91 we are going to be using the titrator up at Pt. Whitney for the next round of geoduck experiments and I was hoping to read through your notes from using it this past September. Are these up on Github, your lab notebook, or somewhere else?

**Comment by sr320** [comment]
Related:
https://github.com/hputnam/Geoduck_Conditioning
https://github.com/RobertsLab/titrator

**Comment by shellytrigg** [comment]
thanks @sr320. I saw the titrator repo and found the 3 standards and HCl to order. I'll make a new issue for purchasing
