### ISSUE TITLE
Ordering reagents for titrator

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#454]
- [pH Buffer 4.0 (Fisher SB101-4) Fisher pH4.0 buffer 4L (cat: SB101-4)  $99.23](https://www.fishersci.com/shop/products/buffer-solution-ph-4-00-color-coded-red-certified-fisher-chemical-4/sb1014?searchHijack=true&searchTerm=SB1014&searchType=RAPID&matchedCatNo=SB1014)
- [pH Buffer 7.0 (Fisher SB107-4) Fisher ph7.0 buffer 4L (cat: SB107-4) $100.15](https://www.fishersci.com/shop/products/buffer-solution-ph-7-00-color-coded-yellow-certified-fisher-chemical-5/sb1074?searchHijack=true&searchTerm=SB1074&searchType=RAPID&matchedCatNo=SB1074)
- [pH buffer 10.0 (Fisher SB115-4) Fisher ph10.0 buffer 4L (cat: SB115-4) $99.49](https://www.fishersci.com/shop/products/buffer-solution-ph-10-00-color-coded-blue-certified-fisher-chemical-4/sb1154?searchHijack=true&searchTerm=SB1154&searchType=RAPID&matchedCatNo=SB1154)
- 0.1M Hydrochloric acid from Dickson Lab Andrew Dickson 1 x 1000mL alkalinity titrant
@kubu4  how did you order the HCl titrant from the Dickson lab?

**Comment by sr320** [comment]
66-4313

**Comment by kubu4** [comment]
Here's the [completed SAFS Purchasing form](https://drive.google.com/file/d/1tJCVDHdhql03joRRhS8FeVCFEpAWOWG3/view) for the last order of titrant for reference.

Here's titrant order form: https://drive.google.com/file/d/0B2S_90rPaQMzbVlFRktJc1dFQTd2VnRhUHcyQWxfUVlqZkhF/view?usp=sharing

**Comment by shellytrigg** [comment]
- 3 M KCl Mettler Toledo pH Electrode filling solution with special cap, Fisher Scientific, [cat no.:01-911-512 ](https://www.fishersci.com/shop/products/kcl-3m-electrode-filling-solution/01911512) $16.98
- 5 x 500mL TA CRMs, Andrew Dickson Lab $265.00 
*it turns out there is only 1 full, unopened bottle of CRMs remaining. The other bottles in the CRMs boxes were near empty. I can bring these back to the lab and can look into sending them back to the Dickson lab (and potentially saving some money on the bottles and shipping for future orders).
