### ISSUE TITLE
QUICK! Qubit calibration error, 2nd standard 

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#456]
Breaking news .... 
Ronit keeps getting an error on the Qubit with the 2nd calibration standard. He remade it once, and is using the same standards as last week. Anyone have an idea how he should proceed right now?  We tried switching the standards around (1 <-> 2), in case they got mixed up.

Thanks

**Comment by kubu4** [comment]
Unplug it for 30s and plug back in.

**Comment by laurahspencer** [comment]
Didn't work, any instructions for him as to what to do with the prepared Qubit samples?

**Comment by laurahspencer** [comment]
He is taking off, scrapping them (possibly master mix was made incorrectly).  
Ronit says he will re-do the Qubit step on Wednesday unless, Sam, you have time to and would like to try it tomorrow.

**Comment by kubu4** [comment]
Tested standards today and had no issues.
