### ISSUE TITLE
left_join: how to get rid of .x and .y additional columns

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#457]
[R Script: all-hemo-fixing.R](https://github.com/RobertsLab/project-crab/blob/master/scripts/all-hemo-fixing.R)

After fixing the new qubit data so that it matches the column names in [hemo-sample_qubit_table.csv](https://github.com/RobertsLab/project-crab/blob/master/analyses/hemosample_qubit_table.csv) for when I ```left_join``` based on "tube_number", some duplicate columns with the extensions ".x" and ".y" are made. 

An example is highlighted with the pink boxes:      
![screen shot 2018-10-29 at 7 03 26 pm](https://user-images.githubusercontent.com/14934314/47690987-9b87e600-dbad-11e8-9885-35a1fc9ecf1f.png)

A similar problem has happened in the past, and Yaamini helped me showing how to change all columns to have the same variable types (factor, integer, character, etc). For example, at the end of the script above, I did this to make sure that the columns had the same variable types as their corresponding columns in the  [hemo-sample_qubit_table.csv](https://github.com/RobertsLab/project-crab/blob/master/analyses/hemosample_qubit_table.csv):         
```
#Try changing column variables so that they match in the .x and .y columns...
qubitnew2$Original_sample_conc_ng.ul <- as.factor(qubitnew2$Original_sample_conc_ng.ul)
qubitnew2$total_sample_vol_ul <- as.integer(qubitnew2$total_sample_vol_ul)
qubitnew2$total_yield_ng <- as.factor(qubitnew2$total_yield_ng)
qubitnew2$lyophilized_y_n <- as.factor(qubitnew2$lyophilized_y_n)
```

I ```left_join```-ed the updated "qubitnew2" with the "hemo_qubit" table, and the new file still has the same ".x" and ".y" issue:

**Comment by kubu4** [comment]
You get the ```.x``` and ```.y``` notation because those column names are the same, pre-join. When the join is performed, R doesn't know how to handle duplicate column names, so it appends them with that notation so no data is overwritten.

**Comment by kubu4** [comment]
@grace-ac and I discussed this today.

Proposed solution:

1. Have master CSV with all sample/tube names/other columns, but no columns corresponding to Qubit data columns.

2. Have a list of Qubit data CSVs. Ideally, use a loop to pull new Qubit data in to list from directory, so script can be executed repeatedly without having to be modified each time a new Qubit CSV is added to directory.

3. Concatenate all Qubit CSV data in to a single data frame.

4. Perform left join with the master CSV and the concatenated Qubit data frame.

5. Run script any time a new Qubit data CSV is added to the directory to produce updated master CSV.

**Comment by grace-ac** [comment]
working on the above solution now
