### ISSUE TITLE
New mox software request

### ISSUE THREAD

**Issue by jldimond** [RobertsLab/resources#459]
I'm interested in trying wtdbg2 for genome assembly on mox: https://github.com/ruanjue/wtdbg2

Any chance you could install this @kubu4?

**Comment by kubu4** [comment]
Done. Can be found on Mox at:

```/gscratch/srlab/programs/wtdbg-2.1_x64-linux/wtdbg2```

**Comment by jldimond** [comment]
Sweet, thanks!
