### ISSUE TITLE
blast in jupyter: invalid syntax? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#461]
I modeled this off of other BLAST jupyter notebooks I have in my [Practicing-with-Blast](https://github.com/grace-ac/Practicing-with-Blast/tree/master/notebooks) notebooks.

[This script](https://github.com/fish546-2018/grace-Cbairdi-transcriptome/blob/master/notebooks/20181025-blast-Cbairdi_swiss-prot.ipynb) is using the really short fasta that was assembled with the short .fastq files over the weekend just to practice.

![screen shot 2018-10-31 at 2 04 43 pm](https://user-images.githubusercontent.com/14934314/47818970-61862380-dd16-11e8-95df-7bc98f70cb4b.png)

**Comment by sr320** [comment]
db should not be `.fasta`
try leaving that off. 

and check for extra spaces in line with `max_target_seqs`

**Comment by kubu4** [comment]
The error message looks like a Python error message, not BLAST. With that in mind, I'd try using 

```%%bash```

at the top of the cell instead of using a ```!``` to call ```blastx```

**Comment by grace-ac** [comment]
![screen shot 2018-10-31 at 2 51 53 pm](https://user-images.githubusercontent.com/14934314/47821086-be84d800-dd1c-11e8-91ed-7f676ccdf159.png)
![screen shot 2018-10-31 at 2 52 01 pm](https://user-images.githubusercontent.com/14934314/47821087-be84d800-dd1c-11e8-971c-c689734b9446.png)

**Comment by kubu4** [comment]
There's a space after your end-of-line slash on the ```-db``` line. That's causing the problem. +1 for @sr320 !

**Comment by grace-ac** [comment]
Yes! here is the output, and I'll close the issue. thanks!

![screen shot 2018-10-31 at 3 04 47 pm](https://user-images.githubusercontent.com/14934314/47821580-65b63f00-dd1e-11e8-9b4c-3a79ecde4508.png)

**Comment by sr320** [comment]
9/10 it will be a space...
