### ISSUE TITLE
RNeasy Plus Micro Kit protocol questions

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#462]
1: In [sam's notebook post](http://onsnetwork.org/kubu4/2018/08/09/rna-isolation-quantificaiton-tanner-crab-hemolymph/), it says that @kubu4 used QIAshredder columns. I only see the gDNA eliminator columns. I'm assuming the RNeasy MiniElute columns are somewhere in the fridge(?). Should I worry about using the QIAshredder columns, too? 

2: In steps 4-7, there are liquids being added to the RNeasy MiniElute columns, and at the end of the steps, it says "discard flow-through". Does this mean that I'd just dump out the contents of the collection tubes and re-use until it says to get a new collection tube in step 8?

**Comment by kubu4** [comment]
1. According to Purchasing Log and Lab Inventory, QIAshredder and MiniElute columns are on Shelf 5 in 213 and/or on Shelf 1 of fridge in FTR 209.

2. Yes.
