### ISSUE TITLE
G Calendar and Slack

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#463]
![screen shot 2018-11-01 at 11 38 02 am](https://user-images.githubusercontent.com/4720221/47874242-8b9c1c00-ddd0-11e8-915f-fa70a6ae94a7.png)
Why are there two google calendars ('robertslab' and 'Gene Fisher')? When I post an event on 'robertslab' it doesn't sync with the Slack #calendar channel, but when I post an event on 'Gene Fisher' it does. Anyone else seeing this?

**Comment by sr320** [comment]
very odd. I only experience one calendar: "robertslab"

**Comment by grace-ac** [comment]
@kaitlynrm this might explain why I see you on the calendar after you remove yourself from the schedule...?

**Comment by kaitlynrm** [comment]
I only have one calendar, robertslab. What about you @grace-ac?

**Comment by grace-ac** [comment]
I only have gene fish calendar...

**Comment by shellytrigg** [comment]
solution: kept 'Gene Fisher' calendar and removed 'robertslab' calendar. Then renamed 'Gene Fisher' calendar 'robertslab'. Here is [the URL to the calendar](https://calendar.google.com/calendar/embed?src=mrc305%40gmail.com&ctz=America%2FLos_Angeles)
