### ISSUE TITLE
Is my deduplication running?

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#464]
From my slurm.out file on Mox:

<img width="1253" alt="screen shot 2018-11-01 at 12 08 57 pm" src="https://user-images.githubusercontent.com/22335838/47873735-39a6c680-ddcf-11e8-8003-000c1e8827b3.png">

Does that last line mean that `deduplicate_bismark` cannot run on my SAMfiles?

**Comment by yaaminiv** [comment]
Ah fork. 

I'll kill my Mox job (and the other one that I queued up) since they both would have this error.

**Comment by kubu4** [comment]
I wouldn't kill _both_ jobs before testing whether or not that's actually causing the issue...

**Comment by yaaminiv** [comment]
...dang it. too late.
