### ISSUE TITLE
Difference between C. virginica transposable element feature files

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#466]
I noticed there are 2 different transposable element files listed under [*C. virginica* Genome Feature Tracks](https://github.com/RobertsLab/resources/wiki/Genomic-Resources#genome-feature-tracks-1). @kubu4 What is the difference between these 2 files? The notebook entry you've linked tells me how it was made, but not what the differences are!

@sr320: Should I also identify overlaps between DML/DMR and TEs?

**Comment by sr320** [comment]
> @sr320: Should I also identify overlaps between DML/DMR and TEs?

yes

**Comment by sr320** [comment]
Yes
