### ISSUE TITLE
Problem installing methylkit on Rstudio Server - roadrunner

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#467]
As methykit always seems to be a challenge - not sure if this is related to new version of Rstudio...

https://d.pr/i/tcVCKR
![screen shot on 2018-11-02 at 13-50-13](https://user-images.githubusercontent.com/4442039/47940459-de94d280-dea7-11e8-94e4-4540be3aaebe.png)

**Comment by kubu4** [comment]
It (BiocManager) requires R >3.5.

I can uninstall Microsoft R (which is currently only at v3.4.3) on one of the birds and install regualar R, if you'd like.

**Comment by sr320** [comment]
But I should not need BiocManager for methykit though should I?

**Comment by sr320** [comment]
no luck- can you put regular R on one of the birds?

**Comment by kubu4** [comment]
Alrighty, roadrunner is ready. And, it's using Microsoft Open R (3.5.1), which is multithreaded!!

Previously, I installed this: 

- [Microsoft R Client](https://docs.microsoft.com/en-us/machine-learning-server/r-client/what-is-microsoft-r-client)

This time, installed this (which is what I wanted initially, but somehow missed):

- [Microsoft Open R](https://mran.microsoft.com/open)

Will install on Emu as well.

**Comment by kubu4** [comment]
Available on Emu now, too.
