### ISSUE TITLE
how to cd to GitHub repo in jupyter on hummingbird

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#469]
I'm in a jupyter notebook on Hummingbird srlab login and want to change directory to the [grace-Cbairdi-transcriptome](https://github.com/fish546-2018/grace-Cbairdi-transcriptome/tree/master/notebooks) repo.

I want to BLAST the newly assembled transcriptome (in /gscratch/srlab/graceac9/analyses/trinity_out_dir/Trinity.fasta on Mox)

**Comment by grace-ac** [comment]
or wait... I think working directory needs to be http://owl.fish.washington.edu/scaphapoda/grace/Crab-project/fasta_files/11012018_query_library01/ because that is where the fasta "query.fa" is.

**Comment by grace-ac** [comment]
I was just asking if it was possible to set your working directory within a jupyter notebook to be a GitHub repo. Sort of like what you can do with ```ssh``` in bash. 

Didn't know I had to clone github repo to hummingbird. will figure out how/where to put it. 

and i just remembered that I will ```!curl``` the query.fa from owl .

**Comment by kubu4** [comment]
Yes, you can set a working directory.

> Sort of like what you can do with ssh in bash.

I'm not sure what you man here. ```ssh``` is a program for connecting to a remote computer. You don't (can't?) set a working directory with ```ssh```.

> Didn't know I had to clone github repo

If you want access to a repo on the computer you're using, you need to clone it (i.e. download it), if it hasn't already been cloned to the computer you're using.

**Comment by grace-ac** [comment]
switching to mox - closing this issue for now!

will make a database using a jupyter notebook. then, i'll create the .sh script to run blast on mox. will get the script looked over before sending job to mox.
