### ISSUE TITLE
Move images to owl and consider key

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#47]
How to find them
https://github.com/RobertsLab/resources/blob/master/Project-images.md

**Comment by kubu4** [comment]
I'll also add that readme files should provide URLs to notebooks and/or GitHub project pages and/or project description.

**Comment by sr320** [comment]
Discussed with @grace-ac -

**Comment by sr320** [comment]
@grace-ac is this complete?
if so you can delete 
https://github.com/RobertsLab/resources/blob/master/Project-images.md

**Comment by grace-ac** [comment]
yes! deleted.
