### ISSUE TITLE
Request input: BLAST script for Mox

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#470]
[Script](https://github.com/fish546-2018/grace-Cbairdi-transcriptome/blob/master/scripts/20181106_Cbairdi-sprot_BLAST.sh)

```
#!/bin/bash
## Job Name
#SBATCH --job-name=20181106_Cbairdi_blast_01
## Allocation Definition 
#SBATCH --account=srlab
#SBATCH --partition=srlab
## Resources
## Nodes 
#SBATCH --nodes=1   
## Walltime (days-hours:minutes:seconds format)
#SBATCH --time=90:30:00
## Memory per node
#SBATCH --mem=500G
##turn on e-mail notification
#SBATCH --mail-type=ALL
#SBATCH --mail-user=graceac9@uw.edu
## Specify the working directory for this job
#SBATCH --workdir=/gscratch/srlab/graceac9/analyses

# Load Python Mox module for Python module availability

module load intel-python3_2017


/gscratch/srlab/programs/ \ #need to find where blast lives on mox
--blastn \
--query Trinity.fasta \ #OR do I have to rsync query.fa from owl/scaphapoda/grace/Crab-project/fasta_files/11012018_query_library01/query.fa
--db http://owl.fish.washington.edu/scaphapoda/grace/Crab-project/blastdb/uniprot_sprot \
--max_target_seqs 1 \
--outfmt 6 \
--num_threads 8 \
--out 1106-cbairdiblast-sprot.tab
--CPU 28
```

**Comment by sr320** [comment]
https://d.pr/v/IEuCjx

**Comment by grace-ac** [comment]
changes made:      
![screen shot 2018-11-06 at 2 07 37 pm](https://user-images.githubusercontent.com/14934314/48097153-e61cea00-e1cd-11e8-9b72-27c92780111c.png)

**Comment by kubu4** [comment]
Double-check your path to the blastn program.

Also, check the blastn documentation (call ```blastn -h``` from the proper directory to get a quick help guide) for how to format your arguments (i.e. db, and query are arguments).

**Comment by grace-ac** [comment]
ah! correct path is : ```/gscratch/srlab/programs/ncbi-blast-2.6.0+/bin/blastn```

**Comment by grace-ac** [comment]
the job is no longer in queue and nothing is in my ```/gscratch/srlab/graceac9/analyses```... assuming this means that it didn't work? 

Also, when in ```/gscratch/srlab/programs/ncbi-blast-2.6.0+/bin```,  ```blastn -h``` ; ```./blastn -h```; and ```blastn -h``` don't work...
