### ISSUE TITLE
Create Draft SAFS IT survey

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#471]
Can you take these questions
https://d.pr/f/z5Wh3u

and create a Google Survey / Form in manner that makes it super easy for survey taker?
ie menus, checkboxes, scales etc..

**Comment by kaitlynrm** [comment]
[I made a google survey!](https://docs.google.com/forms/d/1T09-ufi6O43b4Mr-VXfoX_uge4RN0g8708t6M20uNCs/edit)

**Comment by sr320** [comment]
Very nice!
Is there a way to logically break it up in different tables, and maybe provide subheadings?

**Comment by kaitlynrm** [comment]
I broke it up into sections now!
Note that the person taking the survey will only go to the SAFS IT Assistance section if they respond that they have requested assistance before (otherwise the person will be moved on to the last section).
