### ISSUE TITLE
Add summary results to temperature proteomics paper

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#472]
In the [google-doc](https://docs.google.com/document/d/1oVgqsODHQFkRwsxuzcv_k-px6AaQ8Dg1w2x5XMOMmMI/edit#heading=h.zbna7v119uk4) results section- add a paragraph and summary table that describes number of proteins detected, in each silo, how many proteins that are unique to a silo. Related there should be a table (supplemental) where these proteins could be identified by name (and with some work one could get fastas)

**Comment by shellytrigg** [comment]
@kaitlynrm do you have time this week to meet about this/paper progress?

**Comment by kaitlynrm** [comment]
Yes! I'm in tomorrow all day, or I can be here Thursday or Friday if that works better and/or if there is some work for me @shellytrigg .

**Comment by shellytrigg** [comment]
@kaitlynrm perfect, let's meet at 9:30

**Comment by shellytrigg** [comment]
@kaitlynrm here is [the table of ACSA selected proteins](https://github.com/shellytrigg/OysterSeedProject/blob/master/analysis/ASCA/ASCA_shellytest/uniprot_PC1_0.04.csv) that I made based on [this analysis](https://github.com/shellytrigg/OysterSeedProject/blob/master/analysis/ASCA/ASCA_shellytest/ASCA_OysterSeedTemp.md) that we looked at today.

**Comment by shellytrigg** [comment]
@sr320 @kaitlynrm here is [a post](https://shellytrigg.github.io/22th-post/) about what Kaitlyn and I discussed for next steps in manuscript prep.
