### ISSUE TITLE
Over CPU quota when creating checksums on Mox

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#473]
I'm in the directory `/gscratch/scrubbed/yaammini/analyses/Virginica-MBD/2018-10-31-Virginica-Bismark-Revised-Parameters-Samtools`

I want `rsync` that directory to one on gannet. Before I do that, I would like to generate checksums for all of my files. I tried running the following command in my directory:

`md5sum * > 2018-11-07-checksums.md5`

I get the following message:

![screen shot 2018-11-07 at 9 22 08 am](https://user-images.githubusercontent.com/22335838/48148481-afe37700-e26e-11e8-865e-c9e75093b8ec.png)

Would creating a new script for checksum creation solve this problem...?

**Comment by kubu4** [comment]
To answer your question directly, you need to use an interactive node for these types of processes. Your login node (i.e. the default node that you are on when you login to Mox) is really only for transferring files between systems and initiating jobs to run on other node types. See our Mox wiki for info on how to launch an interactive node.

To indirectly answer your question, you don't really need to generate/compare checksums when using ```rsync```, as ```rsync``` does this automatically. However, it'd definitely a good practice to implement (and, good practice to learn about using ```md5sum```) checksum generation/verification.
