### ISSUE TITLE
Can't ssh into owl w/ my username 

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#474]
I'm trying to rsync a directory from mox to owl, and can't successfully log into owl using ssh. I've tried both using owl's IP and the owl.fish... address. I can successfully log into Owl online using the same username and pw that I'm trying to use via ssh.  Any suggestions? 

`D-10-19-24-215:~ laura$ ssh lhs3@128.95.149.83 . 
lhs3@128.95.149.83's password:   
Permission denied, please try again.  
Connection to 128.95.149.83 closed.` . 

`D-10-19-24-215:~ laura$ ssh lhs3@owl.fish.washington.edu . 
The authenticity of host 'owl.fish.washington.edu (128.95.149.83)' can't be established.  
ECDSA key fingerprint is SHA256:wKDZt2FbOtqu5CCTGuWCbDWSDx6mATkgsjMwxVKh55M.  
Are you sure you want to continue connecting (yes/no)? yes . 
Warning: Permanently added 'owl.fish.washington.edu' (ECDSA) to the list of known hosts.  
lhs3@owl.fish.washington.edu's password:   
Permission denied, please try again.  
Connection to owl.fish.washington.edu closed.`

**Comment by kubu4** [comment]
This is because you're not an adminstrator on owl, which is required for ```ssh```.

I'll change this. BRB...

**Comment by laurahspencer** [comment]
I see. thanks!

**Comment by kubu4** [comment]
Done. You should be good to go now.
