### ISSUE TITLE
rsync mox to owl, some files not transferring

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#475]
I rsynced the results of a trinity assembly to owl (whole output directory), and a couple files are missing. Some background ...

I want to use the trimmed/normalized read files to evaluate the assembly using [`transrate`](http://hibberdlab.com/transrate/getting_started.html). According to the [slurm output](http://owl.fish.washington.edu/generosa/2018-Oly-gonad-assembly/20181029_Trinity/slurm-415800.out) the trimmed/normalized reads were combined into two files for my left and right reads into "left.norm.fq" and "right.norm.fq". 

These files are on mox: 

![48239257-178ae680-e383-11e8-9ef7-e32b523db263](https://user-images.githubusercontent.com/17264765/48239722-d7c4fe80-e384-11e8-9997-255213cc1ce6.png)

But despite repeated attempts to rsync the entire directory from mox to owl, these files are not on [owl](http://owl.fish.washington.edu/generosa/2018-Oly-gonad-assembly/20181029_Trinity/insilico_read_normalization/). Any ideas why? 

![48239480-e8c14000-e383-11e8-9ba9-3af56e1db212](https://user-images.githubusercontent.com/17264765/48240042-1ad3a180-e386-11e8-9f90-9b646f5884b4.png)

**Comment by kubu4** [comment]
What were the rsync command used and it's output (assuming you used the --verbose or -v flag)?

**Comment by laurahspencer** [comment]
`rsync -av /gscratch/srlab/lhs3/outputs/trinity20181029/ lhs3@128.95.149.83:/volume1/web/generosa/2018-Oly-gonad-assembly/20181029_Trinity/`

I tried rsyncing one of the .fq files only, too; it seems like it's being ignored somehow: 
![image](https://user-images.githubusercontent.com/17264765/48240098-58d0c580-e386-11e8-8105-10dd74131e57.png)

**Comment by kubu4** [comment]
Can't test at the moment, but try leaving last slash off of your
destination path. Can test after bath time...

**Comment by laurahspencer** [comment]
Weird, check this out
![image](https://user-images.githubusercontent.com/17264765/48240349-591d9080-e387-11e8-8451-413f72b5981e.png)

**Comment by kubu4** [comment]
What's that output from, ```ls -l```?

**Comment by laurahspencer** [comment]
It's the verbose standard output from rsync, while it was in process (total output is many many lines, so I won't paste it all here).

**Comment by laurahspencer** [comment]
Here's a taste: 

[lhs3@mox2 lhs3]$ rsync -av /gscratch/srlab/lhs3/outputs/trinity20181029/ lhs3@128.95.149.83:/volume1/web/generosa/2018-Oly-gonad-assembly/20181029_Trinity/
lhs3@128.95.149.83's password: 
sending incremental file list
./
.iworm.ok
.iworm_renamed.ok
.jellyfish_count.ok
.jellyfish_dump.ok
.jellyfish_histo.ok
CP-4Spl_S11_L004_R1_0343.fastq.gz.P.qtrim.gz
CP-4Spl_S11_L004_R1_0343.fastq.gz.PwU.qtrim.fq
CP-4Spl_S11_L004_R1_0343.fastq.gz.U.qtrim.gz
CP-4Spl_S11_L004_R1_0348.fastq.gz.P.qtrim.gz
CP-4Spl_S11_L004_R1_0348.fastq.gz.PwU.qtrim.fq
CP-4Spl_S11_L004_R1_0348.fastq.gz.U.qtrim.gz
CP-4Spl_S11_L004_R2_0343.fastq.gz.P.qtrim.gz
CP-4Spl_S11_L004_R2_0343.fastq.gz.PwU.qtrim.fq
CP-4Spl_S11_L004_R2_0343.fastq.gz.U.qtrim.gz
CP-4Spl_S11_L004_R2_0348.fastq.gz.P.qtrim.gz
CP-4Spl_S11_L004_R2_0348.fastq.gz.PwU.qtrim.fq
CP-4Spl_S11_L004_R2_0348.fastq.gz.U.qtrim.gz
Trinity.fasta
Trinity.fasta.gene_trans_map
Trinity.fasta.shasum.txt
Trinity.timing
both.fa
both.fa.ok
both.fa.read_count
inchworm.K25.L25.DS.fa
inchworm.K25.L25.DS.fa.finished
inchworm.kmer_count
jellyfish.kmers.fa
jellyfish.kmers.fa.histo
left.fa.ok
partitioned_reads.files.list
partitioned_reads.files.list.ok
pipeliner.21298.cmds
recursive_trinity.cmds
recursive_trinity.cmds.completed
recursive_trinity.cmds.ok
right.fa.ok
scaffolding_entries.sam
slurm-415800.out
trimmomatic.ok
chrysalis/
chrysalis/GraphFromIwormFasta.out
chrysalis/GraphFromIwormFasta.out.ok
chrysalis/bundled_iworm_contigs.fasta
chrysalis/bundled_iworm_contigs.fasta.ok
chrysalis/inchworm.K25.L25.DS.fa.min100
chrysalis/inchworm.K25.L25.DS.fa.min100.1.bt2
chrysalis/inchworm.K25.L25.DS.fa.min100.2.bt2
chrysalis/inchworm.K25.L25.DS.fa.min100.3.bt2
chrysalis/inchworm.K25.L25.DS.fa.min100.4.bt2
chrysalis/inchworm.K25.L25.DS.fa.min100.bowtie2-build.ok
chrysalis/inchworm.K25.L25.DS.fa.min100.ok
chrysalis/inchworm.K25.L25.DS.fa.min100.rev.1.bt2
chrysalis/inchworm.K25.L25.DS.fa.min100.rev.2.bt2
chrysalis/iworm.bowtie.nameSorted.bam
chrysalis/iworm.bowtie.nameSorted.bam.ok
chrysalis/iworm_cluster_welds_graph.txt
chrysalis/iworm_cluster_welds_graph.txt.ok
chrysalis/iworm_cluster_welds_graph.txt.sorted
chrysalis/iworm_cluster_welds_graph.txt.sorted.ok
chrysalis/iworm_cluster_welds_graph.txt.sorted.wIwormNames
chrysalis/iworm_cluster_welds_graph.txt.sorted.wIwormNames.ok
chrysalis/iworm_scaffolds.txt
chrysalis/iworm_scaffolds.txt.ok
chrysalis/readsToComponents.out
chrysalis/readsToComponents.out.ok
chrysalis/readsToComponents.out.rcts.out
chrysalis/readsToComponents.out.sort
chrysalis/readsToComponents.out.sort.ok
insilico_read_normalization/
insilico_read_normalization/CP-4Spl_S11_L004_R1_0343.fastq.gz.PwU.qtrim.fq_ext_all_reads.normalized_K25_maxC200_minC1_pctSD10000.fq
insilico_read_normalization/CP-4Spl_S11_L004_R1_0343.fastq.gz.PwU.qtrim.fq_ext_all_reads.normalized_K25_maxC200_minC1_pctSD10000.fq.ok
insilico_read_normalization/CP-4Spl_S11_L004_R2_0343.fastq.gz.PwU.qtrim.fq_ext_all_reads.normalized_K25_maxC200_minC1_pctSD10000.fq
insilico_read_normalization/CP-4Spl_S11_L004_R2_0343.fastq.gz.PwU.qtrim.fq_ext_all_reads.normalized_K25_maxC200_minC1_pctSD10000.fq.ok
insilico_read_normalization/left.norm.fq -> /gscratch/srlab/lhs3/outputs/trinity20181029/insilico_read_normalization/CP-4Spl_S11_L004_R1_0343.fastq.gz.PwU.qtrim.fq_ext_all_reads.normalized_K25_maxC200_minC1_pctSD10000.fq
insilico_read_normalization/normalization.ok
insilico_read_normalization/right.norm.fq -> /gscratch/srlab/lhs3/outputs/trinity20181029/insilico_read_normalization/CP-4Spl_S11_L004_R2_0343.fastq.gz.PwU.qtrim.fq_ext_all_reads.normalized_K25_maxC200_minC1_pctSD10000.fq
read_partitions/
read_partitions/Fb_0/
read_partitions/Fb_0/CBin_0/
read_partitions/Fb_0/CBin_0/c0.trinity.reads.fa
read_partitions/Fb_0/CBin_0/c0.trinity.reads.fa.out.Trinity.fasta
read_partitions/Fb_0/CBin_0/c1.trinity.reads.fa
read_partitions/Fb_0/CBin_0/c1.trinity.reads.fa.out.Trinity.fasta
read_partitions/Fb_0/CBin_0/c10.trinity.reads.fa
read_partitions/Fb_0/CBin_0/c10.trinity.reads.fa.out.Trinity.fasta
read_partitions/Fb_0/CBin_0/c11.trinity.reads.fa
read_partitions/Fb_0/CBin_0/c11.trinity.reads.fa.out.Trinity.fasta
read_partitions/Fb_0/CBin_0/c12.trinity.reads.fa
read_partitions/Fb_0/CBin_0/c12.trinity.reads.fa.out.Trinity.fasta
read_partitions/Fb_0/CBin_0/c13.trinity.reads.fa
read_partitions/Fb_0/CBin_0/c13.trinity.reads.fa.out.Trinity.fasta
read_partitions/Fb_0/CBin_0/c14.trinity.reads.fa
read_partitions/Fb_0/CBin_0/c14.trinity.reads.fa.out.Trinity.fasta
read_partitions/Fb_0/CBin_0/c15.trinity.reads.fa
read_partitions/Fb_0/CBin_0/c15.trinity.reads.fa.out.Trinity.fasta
read_partitions/Fb_0/CBin_0/c16.trinity.reads.fa
read_partitions/Fb_0/CBin_0/c16.trinity.reads.fa.out.Trinity.fasta
read_partitions/Fb_0/CBin_0/c17.trinity.reads.fa
read_partitions/Fb_0/CBin_0/c17.trinity.reads.fa.out.Trinity.fasta
read_partitions/Fb_0/CBin_0/c18.trinity.reads.fa
read_partitions/Fb_0/CBin_0/c18.trinity.reads.fa.out.Trinity.fasta
read_partitions/Fb_0/CBin_0/c19.trinity.reads.fa
read_partitions/Fb_0/CBin_0/c19.trinity.reads.fa.out.Trinity.fasta
read_partitions/Fb_0/CBin_0/c2.trinity.reads.fa
read_partitions/Fb_0/CBin_0/c2.trinity.reads.fa.out.Trinity.fasta
read_partitions/Fb_0/CBin_0/c20.trinity.reads.fa
read_partitions/Fb_0/CBin_0/c20.trinity.reads.fa.out.Trinity.fasta
read_partitions/Fb_0/CBin_0/c21.trinity.reads.fa
read_partitions/Fb_0/CBin_0/c21.trinity.reads.fa.out.Trinity.fasta
read_partitions/Fb_0/CBin_0/c22.trinity.reads.fa

**Comment by kubu4** [comment]
That output looks good so far!

**Comment by laurahspencer** [comment]
It's finished- from what I can tell, `->` is a symbolic link, which is telling me that the contents of **left.norm.fq** has been redirected to **/gscratch/srlab/lhs3/outputs/trinity20181029/insilico_read_normalization/CP-4Spl_S11_L004_R1_0343.fastq.gz.PwU.qtrim.fq_ext_all_reads.normalized_K25_maxC200_minC1_pctSD10000.fq**.  I still find it weird that only the latter file is transferred to owl, but both appear on mox. Additionally, the naming convention on the latter file indicates it's only reads from one of my 2 left read files. (I'll inspect the two aforementioned files to see if they differ). Thanks.
