### ISSUE TITLE
Purchase mini freezer for Pt. Whitney

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#478]
[some mini freezer reviews](https://www.bestrefrigeratorcentral.com/mini-freezer-best-selling-compact-freezers/). I think Home Depot sells the [Danby](https://www.homedepot.com/p/Danby-3-2-cu-ft-Manual-Defrost-Upright-Freezer-in-White-DUFM032A1WDB-3/303713913) but I dont know if they carry it in house. Either way, we can order one and just bring it up when it arrives. We don't need it urgently. If you don't find one at the store, I can submit a purchase order through Slack.

**Comment by sr320** [comment]
purchased - will bring to Pt Whitney tomorrow.
