### ISSUE TITLE
Jupyter: join _blast_GO_unfolded.sorted with GO-GOslim.sorted not working

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#479]
Based on [Steven's notebook](https://github.com/sr320/nb-2018/blob/master/C_virginica/83-blast-2-slim.ipynb)    

```!join``` based on column 1 for both files. The columns both contain the "```GO:000...```" data. 

The output should show the ```head``` of the ```!join```, but it doesn't. Also, it should show a value for the "joining files to get GOslim for each query (with duplicate GOslim / query removed)".

![screen shot 2018-11-13 at 10 19 03 am](https://user-images.githubusercontent.com/14934314/48433993-5f1bc480-e72d-11e8-8e99-7078c15a98b8.png)
![screen shot 2018-11-13 at 10 19 12 am](https://user-images.githubusercontent.com/14934314/48433999-6347e200-e72d-11e8-9449-06a1571f36a6.png)

**Comment by sr320** [comment]
It is because there is a space after the GO IDs in one of the tables.
This happened to me and I just used textwrangler to search for spaces and replace with nothing….

`tr` or `sed` should work to.

**Comment by grace-ac** [comment]
```!sed 's/ //g' _blast-GO-unfolded.sorted | head``` 

worked! thanks @sr320.

**Comment by kubu4** [comment]
Interesting! To check files for hidden spaces (i.e. at the end of lines), you can use the following command:

```tr " " "*" < input_file.txt | head```

This will substitute an asterisk for all spaces present in the file.
