### ISSUE TITLE
How best to make a pie chart 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#480]
**Currently using R to make pie chart. Should I instead use my jupyter notebook?**

My [.ipynb](https://github.com/fish546-2018/grace-Cbairdi-transcriptome/blob/master/notebooks/11052018-C_bairdi-blastn.ipynb).

I moved the [Blastquery-GOslim.sorted](https://github.com/fish546-2018/grace-Cbairdi-transcriptome/blob/master/analyses/Blastquery-GOslim.sorted) from the final step in the above .ipynb to my [analyses directory](https://github.com/fish546-2018/grace-Cbairdi-transcriptome/tree/master/analyses). 

I uploaded the file into an [R script](https://github.com/fish546-2018/grace-Cbairdi-transcriptome/blob/master/scripts/plots.R) and made a [weird pie chart](https://github.com/fish546-2018/grace-Cbairdi-transcriptome/blob/master/analyses/odd_pie.png). 

I was googling a ton of different things and am having a hard time finding how to change the pie chart values to percentages.

![odd_pie](https://user-images.githubusercontent.com/14934314/48445705-0e679400-e74c-11e8-9337-aa57aa751578.png)

**Comment by kubu4** [comment]
There are a couple of questions here. Is your issue "how to fix pie chart labels in R"? Or, is your issue "how to make pie chart in Jupyter Notebook"? 

If you had to prioritize, which one would you want help with the most? That will help us focus our efforts on figuring this out.

**Comment by sr320** [comment]
Given timeframe - use excel...,
