### ISSUE TITLE
poster printing

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#482]
Perhaps we should add info [resources/wiki](https://github.com/RobertsLab/resources/wiki)

Assigning @yaaminiv because I know you've done this fairly recently...

**Comment by kubu4** [comment]
Have also used [UW Creative Commons](https://finance.uw.edu/c2/posters) many times in the past.

I also recall an issue related to this, but I can't find anything...

**Comment by yaaminiv** [comment]
The UW Creative Communications portal seems more familiar to me...

**Comment by grace-ac** [comment]
put instructions [here](https://github.com/RobertsLab/resources/blob/master/protocols/poster-printing.md)
