### ISSUE TITLE
Add blast taxonomy database to mox

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#486]
To complement to nt/nr databast can the blast taxonomy database be added to mox?

https://www.ncbi.nlm.nih.gov/books/NBK279680/

(in an effort to try to see all the taxa in the crab libraries)

**Comment by kubu4** [comment]
Already in there! :)

![20181114_001](https://user-images.githubusercontent.com/4514104/48512053-57cbe800-e80d-11e8-8abf-6f944776162e.png)

**Comment by sr320** [comment]
odd as I am not capturing that in blast..

```
TRINITY_DN26145_c0_g2_i1	gi|291259137|gb|GU924239.1|	4.72e-118	435	77133	N/A	N/A	N/A
TRINITY_DN26145_c0_g1_i1	gi|470475999|ref|NR_076313.1|	1.06e-93	353	28068	N/A	N/A	N/A
TRINITY_DN43393_c0_g1_i1	gi|1133426534|ref|XM_020013529.1|	1.09e-46	198	116153	N/A	N/A	N/A
TRINITY_DN43364_c0_g1_i1	gi|1331453224|ref|XM_003470096.4|	1.38e-84	326	10141	N/A	N/A	N/A
TRINITY_DN43327_c0_g1_i1	gi|909581633|ref|XM_013291358.1|	9.29e-21	111	76194	N/A	N/A	N/A
```

**Comment by kubu4** [comment]
Did you provide the output formatting option for that in your blast command?

**Comment by sr320** [comment]
yes (sorry my other computer is locked so I cannot capture the code)

**Comment by sr320** [comment]
`-outfmt "6 qseqid sseqid evalue bitscore staxids sscinames scomnames sskingdoms"`

**Comment by kubu4** [comment]
Do you have this set?

> BLASTDB environment variable contains the path to the installation directory of the BLAST databases

If not, you can set it like this:

```export BLASTDB=/gscratch/srlab/blastdbs/ncbi-nr-nt-20181114```

**Comment by kubu4** [comment]
I'm also not sure why setting that would have any impact, since you're providing BLAST with the path to the database(s) when running the command...

**Comment by sr320** [comment]
nevermind - 
including `export BLASTDB=/gscratch/srlab/blastdbs/` 

worked !

```
#!/bin/bash
## Job Name
#SBATCH --job-name=cg-blastn-tax
## Allocation Definition 
#SBATCH --account=coenv
#SBATCH --partition=coenv
## Resources
## Nodes (We only get 1, so this is fixed)
#SBATCH --nodes=1   
## Walltime (days-hours:minutes:seconds format)
#SBATCH --time=4-00:00:00
## Memory per node
#SBATCH --mem=100
##turn on e-mail notification
#SBATCH --mail-type=ALL
#SBATCH --mail-user=sr320@uw.edu
## Specify the working directory for this job
#SBATCH --workdir=/gscratch/srlab/sr320/analyses/1114b

export BLASTDB=/gscratch/srlab/blastdbs/

/gscratch/srlab/programs/ncbi-blast-2.6.0+/bin/blastn \
-query /gscratch/srlab/sr320/query/Cbairi_trinity_1113.fa \
-db /gscratch/srlab/blastdbs/ncbi-nr-nt-20181114/nt \
-out /gscratch/srlab/sr320/analyses/1114b/cg-trinity-nt.tab \
-max_target_seqs 1 \
-evalue 1e-20 \
-outfmt "6 qseqid sseqid evalue bitscore staxids sscinames scomnames sskingdoms" \
-num_threads 28
```

**Comment by kubu4** [comment]
Glad the ```export``` command worked!

> I wonder if its related to the fact the taxdb in not in same directory as nt?

It is in the same directory.
