### ISSUE TITLE
Perform MBD immunoprecip on Lotterhos samples (24)

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#487]
Presuming there is sufficient DNA... 
We will be sending these samples out for MBD-BS-seq.

**Comment by kubu4** [comment]
Probably need to order a kit (or two). Which budget(s) should I use? Kits are ~$600 each.

**Comment by sr320** [comment]
61-1553

**Comment by kubu4** [comment]
Uh-oh...

![20181121_001](https://user-images.githubusercontent.com/4514104/48872490-2075b200-ed9e-11e8-9799-86e8b18d47c9.png)

**Comment by kubu4** [comment]
I've submitted order for this. Still out of stock and currently no estimated availability...

**Comment by sr320** [comment]
Can you try to determine if there are other similar kits provided by other companies - MeDIP would also work.

**Comment by sr320** [comment]
Maybe these will work…
https://www.epigentek.com/catalog/advanced_search_result.php?keywords=medip

**Comment by kubu4** [comment]
FYI, I got a quote from Genewiz for 48 samples WGBS, 30x coverage: $28,816 ($434/sample). Cost/time-wise, it might be worth just sending the DNA to them?

Waiting on 12 sample quote for Roberto's stuff...

**Comment by sr320** [comment]
Decided to go with WGBS

**Comment by kubu4** [comment]
Well, got quote from Genewiz (no more discount - apparently it was a one-time discount for first online order) for 24 samples, 30x coverage:

$17,960 ($750/sample)

I'm awaiting a Zymo quote.

However, I _may_ have a workaround for the Genewiz "problem". I'm going to have them modify an existing quote which already has the discount applied. I'll report back with results...

**Comment by kubu4** [comment]
Alrighty, the Genewiz modified quote is now: $13256.00 ($552/sample).

Still waiting to hear from Zymo.

**Comment by kubu4** [comment]
Zymo quote:

$23,760 ($990/sample). 

This includes a standard 10% academic discount that gets applied to all Zymo orders.

**Comment by sr320** [comment]
Are they using same math to calculate coverage?

Thanks
steven

**Comment by kubu4** [comment]
Quote doesn't specify expected output. Have asked for this info.

**Comment by sr320** [comment]
If I recall there 30x was actually 100x

Thanks
steven

**Comment by kubu4** [comment]
Here's response from Zymo on why they seem to insist on sequencing at such high coverage. What are your thoughts?

>Hi Sam,

>I apologize that I wasn’t able to reply to you earlier today.

>You are correct that 62.5 Gb per sample is ~111x coverage. I made an error yesterday in my calculations of the output.>

>To estimate data output needed to achieve  ~30X CpG coverage for bisulfite-converted libraries, it is necessary to double this number to ~60X coverage. This is done because bisulfite-converted libraries have much lower alignment efficiency and a good portion of sequencing data is not usable. For 560 Mb genome and ~60X coverage (~30X CpG coverage), data output has to be about 34 Gb. Please keep in mind that this is an estimate.

>When pricing projects, we take into consideration acceptable multiplexing options. For  your project, we will be able to multiplex 12 samples together and have 2 pools or we will be able to multiplex 24 samples together into one pool.  For 2 pools of 12, you will get twice as much data as for one pool of 24. I’m not sure that you will get enough data for one pool of 24, and for two pools of 12 it may be more data than you need. For a pool of 24 samples, the estimated coverage of CpG sites is ~20X with about 20-25 Gb per sample.

>The quote I sent you yesterday is for two pools of 12 samples. If you would like, we can multiplex 24 samples into one pool, sequence them and see if it’s enough data for you. If it’s not enough, we will sequence again for an additional cost.

>Please share your thoughts.

>Kind regards,

>Daria

**Comment by sr320** [comment]
I think I get what they are saying. We should know if they are correct once we see Roberto's data?
That is, his coverage could be inadequate? 
12k is a tough gamble for these samples.
I recommend we do MBD on these 24 now that we have the kits. 
But could be convinced otherwise...

**Comment by kubu4** [comment]
> We should know if they are correct once we see Roberto's data?
That is, his coverage could be inadequate?

Yes. I guess it has that potential.

What do our previous methylseq data to confirm/disconfirm number of reads received vs. number of aligned reads?

**Comment by sr320** [comment]
Ok now its clicking, we are happy with 50% mapping - thus coverage is more like half of what math plays out. Simple math is presuming 100% mapping.

**Comment by sr320** [comment]
Go ahead and MBD these samples...
