### ISSUE TITLE
Wireless card for Windows PC running TA machine

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#490]
What would be the best way to add wireless capability for the PC out at Pt Whitney (presuming it does not already have it)?

**Comment by kubu4** [comment]
A WiFi card. Should be cheap and easy to install.

**Comment by sr320** [comment]
I will order this then
https://www.amazon.com/TP-Link-Archer-T9E-Beamforming-Technology/dp/B00TQEX7AQ/ref=sr_1_6?s=pc&ie=UTF8&qid=1542395938&sr=1-6&keywords=wifi+card
