### ISSUE TITLE
Develop and Validate Geoduck VTG qPCR assay

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#491]

**Comment by sr320** [comment]
I think step one might be identifying the canonical transcriptome and finding the vitellogenin gene(s)

**Comment by kubu4** [comment]
I put together this transcriptome a while ago:

http://owl.fish.washington.edu/Athaliana/20180827_trinity_geoduck_RNAseq/Trinity.fasta

But, it never got put up on the Genomic Resources wiki as the canonical version. :sob: 

Notebook of assembly is here:

https://robertslab.github.io//sams-notebook/2018/09/04/transcriptome-assembly-geoduck-rnaseq-data.html

Regardless, I'll just use this to find some vitellogenin genes.

**Comment by kubu4** [comment]
Update: Transdecoder finished late last week, so I'll be designing and ordering some VTG primers today.

**Comment by kubu4** [comment]
Never updated this. All finished and primers work.

Primer design process:

https://robertslab.github.io/sams-notebook/2018/11/29/Primer-Design-Geoduck-Vitellogenin-using-Primer3.html

Successful primer tests:

https://robertslab.github.io/sams-notebook/2018/12/06/qPCR-Geoduck-gonad-cDNA-with-vitellogenin-primers.html
