### ISSUE TITLE
Quantseq pipeline: "no isogroup designation" error when generating counts

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#494]
Encountering an error generating read counts using a [perl script called samcount.pl](https://raw.githubusercontent.com/z0on/tag-based_RNAseq/master/samcount.pl) in the quantseq processing pipeline (aka tagseq). 

I'm following the [tagSeq_processing_README.txt](https://raw.githubusercontent.com/z0on/tag-based_RNAseq/master/tagSeq_processing_README.txt) instructions. In the final step under "# generating read-counts-per gene" I generate empty .count files. I suspect it's related to a [tab file](https://raw.githubusercontent.com/fish546-2018/laura-quantseq/master/results/trinity/20181029-olurida-gonad-assembly_seq2iso.tab) that I generate from my [Trinity-assembled transcriptome](http://owl.fish.washington.edu/generosa/2018-Oly-gonad-assembly/20181029_Trinity/Trinity.fasta) using the following: 

```
grep ">" ../../results/trinity/20181029-olurida-gonad-assembly.fasta | \
perl -pe 's/^>(\S+)\|(\S+)(_i\d+)\s.+/$1\|$2$3\t$1_$2/' \
> ../../results/trinity/20181029-olurida-gonad-assembly_seq2iso.tab
```

Executing script and part of the output, which is full of the "no isogroup" error: 

![image](https://user-images.githubusercontent.com/17264765/48654573-dc139c00-e9c2-11e8-9683-dc657648f7e0.png)

[My Quantseq Processing notebook](https://github.com/fish546-2018/laura-quantseq/blob/master/notebooks/Quantseq-processing.ipynb) - issue is located towards the end of the notebook.

**Comment by kubu4** [comment]
The instructions following that step say this:

```
# if you have no assembler-derived isogroups, use cd-hit-est to cluster contigs.
# to look for 99% or better matches between contigs taking 30% of length of either longer or shorter sequence:
cd-hit-est -i transcriptome.fasta -o transcriptome_clust.fasta -c 0.99 -G 0 -aL 0.3 -aS 0.3
```

Have you done this?

**Comment by laurahspencer** [comment]
Successfully used `cd-hit-est` from the [cdhit package](https://github.com/weizhongli/cdhit/releases) to assign "isoclusters", but I've hit a new snag.  The next step is to use the [isogroup_namer.pl](https://github.com/z0on/tag-based_RNAseq/raw/master/isogroup_namer.pl) script to take the cd-hit results (.clstr file), and produce 1. a transcriptome with gene=isogroupNNNN identifiers added to headers, and 2. a tab-delimited table of sequences - cluster designations.  I run the script without any errors, but the isogroup numbers are empty. It's a simple perl script, but with limited perl experience I'd appreciate any advice. Here's a screenshot from my [Jupyter notebook](https://github.com/fish546-2018/laura-quantseq/blob/master/notebooks/Quantseq-processing.ipynb) entry. 

### .clstr file, from `cd-hit-est` output: 
![image](https://user-images.githubusercontent.com/17264765/48668371-7695dd00-eaa0-11e8-8fd4-5f0266e3f665.png)

### output from the isogroup_namer.pl script: 
![image](https://user-images.githubusercontent.com/17264765/48668321-397d1b00-ea9f-11e8-8e12-0586dc69f2bf.png)

**Comment by kubu4** [comment]
It looks like you had the output go to this file: ```trinity/20181029-olurida-gonad-assembly_seq2iso.tab```, but the cells you highlight aren't looking at that file.

**Comment by laurahspencer** [comment]
The isogroup_namer.pl script creates 3 files, actually -  below is an updated screenshot of the 3 files.  `trinity/20181029-olurida-gonad-assembly_seq2iso.tab` is empty 

![image](https://user-images.githubusercontent.com/17264765/48668650-b2807080-eaa7-11e8-9d13-1201787bdb11.png)

**Comment by kubu4** [comment]
Maybe you used the wrong transcriptome fasta file?

I interpret this:

> \# adding cluster designations to fasta headers:
> isogroup_namer.pl transcriptome.fasta transcriptome_clust.fasta.clstr >transcriptome_seq2iso.tab

as meaning to use the original transcriptome file, not the post-cd-hit fasta file.

E.g.:

```isogroup_namer.pl 20181029-olurida-gonad-assembly.fasta 20181029-olurida-gonad-assembly_clust.fasta.clstr >20181029-olurida-gonad-assembly_seq2iso.tab```

**Comment by laurahspencer** [comment]
I tried that too previously, with no success (same resulting file/contents, missing isogroup numbers)

**Comment by kubu4** [comment]
Jupyter Notebook link or it didn't happen. :wink:

**Comment by kubu4** [comment]
Where are these files located, so we can poke around a bit? 

P.S. I'm out of ideas, but thought looking at the files might trigger something inside the old noggin.

**Comment by sr320** [comment]
I agree - for these types of troubleshooting activities there needs to be a jupyter notebook where all work can be reproduced.

**Comment by laurahspencer** [comment]
Added the alternate .fasta step to the [Jupyter notebook](https://github.com/fish546-2018/laura-quantseq/blob/master/notebooks/Quantseq-processing.ipynb). This notebook should have everything needed.
![image](https://user-images.githubusercontent.com/17264765/48677074-763f2580-eb24-11e8-912f-ac5a65fade5c.png)

**Comment by kubu4** [comment]
Also, where are these files so we can play around?

**Comment by sr320** [comment]
Everything should be in the repository so anyone could clone the repository and could reproduce the work locally.
If too big- code should be present to download.

**Comment by laurahspencer** [comment]
If you start from the beginning of the Jupyter Notebook you should have everything needed to replicate. To skip directly to the step that's causing me issues, here are the required files: 

.clstr file created by the `cd-hit-est` function: 
[20181029-olurida-gonad-assembly_clust.fasta.clstr](https://github.com/fish546-2018/laura-quantseq/raw/master/results/trinity/20181029-olurida-gonad-assembly_clust.fasta.clstr)

To download the transcriptome: 
`curl http://owl.fish.washington.edu/generosa/2018-Oly-gonad-assembly/20181029_Trinity/Trinity.fasta > ../results/trinity/20181029-olurida-gonad-assembly.fasta`

To download the tagseq scripts & create path variable to directory 
`git clone https://github.com/z0on/tag-based_RNAseq.git /Applications/bioinformatics/tag-based_RNAseq/`
`tagseq = "/Applications/bioinformatics/tag-based_RNAseq/"`

The step that's giving me issues: 

`{tagseq}isogroup_namer.pl trinity/20181029-olurida-gonad-assembly.fasta trinity/20181029-olurida-gonad-assembly_clust.fasta.clstr > trinity/20181029-olurida-gonad-assembly_seq2iso.tab`
