### ISSUE TITLE
Looping over dates in R

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#495]
[R Markdown file](
https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_SRM_20170902/2017-11-15-Environmental-Data-and-Biomarker-Analyses/2017-12-13-Environmental-Data-Quality-Control/2018-11-18-Environmental-Data-NMDS.Rmd)

I have a data frame with pH values for each unique site-habitat combination for the DNR out plant experiment:

![screen shot 2018-11-19 at 8 54 37 am](https://user-images.githubusercontent.com/22335838/48722422-db545300-ebd8-11e8-94d0-21e8d9786f7b.png)

For each day, I want to calculate the minimum pH at each unique site-habitat combination (i.e. each column).

I isolated the unique dates in the `outplantDates` vector:

![screen shot 2018-11-19 at 8 57 17 am](https://user-images.githubusercontent.com/22335838/48722562-279f9300-ebd9-11e8-9346-333d630f3f03.png)

I created an empty dataframe, `pHMinimum` to hold the results of my calculations:

![screen shot 2018-11-19 at 8 54 52 am](https://user-images.githubusercontent.com/22335838/48722471-f3c46d80-ebd8-11e8-8764-b90a1724b297.png)

I want to fill this dataframe using the following for loop, but I keep getting an error:

![screen shot 2018-11-19 at 8 55 10 am](https://user-images.githubusercontent.com/22335838/48722511-09d22e00-ebd9-11e8-953f-89c901c26503.png)

I tried running the loop without filling in the dataframe, and it seems to work:

![screen shot 2018-11-19 at 9 00 22 am](https://user-images.githubusercontent.com/22335838/48722748-a3014480-ebd9-11e8-9184-c57c0d59408b.png)

How can I resolve the error? The minimum pH value is calculated, but there's a problem saving that value in the empty data frame.

*edited: R Markdown link now works*

**Comment by kubu4** [comment]
Your link to your markdown file just links to this issue...

**Comment by yaaminiv** [comment]
I keep forgetting to add the link when I'm typing out my issue! Should be fixed now.

**Comment by kubu4** [comment]
The behavior is certainly confusing. With that said, do you need to parse the dates as actual dates or can you just parse it as a string?

The reason I ask is that I think you won't encounter this error if you just leave the date column alone. 

What you're experiencing is that you've asked R to interpret the date column as an actual date. This is then attempting to coerce the data into a date format (i.e. integer) that R can subsequently perform time-based calculations on for any downstream manipulations. When that's the case, you need to specify the start date (i.e. "origin") that R should use (e.g. ```as.Date(unique(temperatureData$Date, "origin="1970-01-01")```) for setting date values (that previous code might not work; I haven't fully digested how the ```as.Date()``` function actually works).

So, if you don't need R to actually manipulate your data based on time/dates, then I wouldn't actually use the ```as.Date()``` function for that data at all. Just let R interpret is as a string (or character?) and you should be able to avoid this headache.

**Comment by yaaminiv** [comment]
<img width="747" alt="screen shot 2018-11-19 at 9 29 46 am" src="https://user-images.githubusercontent.com/22335838/48724291-b1e9f600-ebdd-11e8-8bca-e9325213fe88.png">

Iterating over a character string gives me a new error

**Comment by yaaminiv** [comment]
Let me clarify...I converted the dates to characters, and got the following error. I reread your comment and I think you're saying that I convert the dates to numbers using the "origin" argument of `as.Date`...?

**Comment by kubu4** [comment]
I believe you might need to add that origin argument to your ```as.Date()``` function - if you need/want to use those dates as integers (i.e. a way to perform calculations using your date values).

How can I see your updated code where you changed the data format to a character?

**Comment by yaaminiv** [comment]
> I believe you might need to add that origin argument to your as.Date() function - if you need/want to use those dates as integers (i.e. a way to perform calculations using your date values).

I'll try this and see what happens

> How can I see your updated code where you changed the data format to a character?

It's in the same R Markdown file!

**Comment by kubu4** [comment]
I'm not seeing it. When I refresh that link, it still shows a commit that was last updated an hour ago. Line number?

**Comment by yaaminiv** [comment]
Line 376. Do you see it now...?

**Comment by kubu4** [comment]
Yes, thanks! I was looking for line(s) 328 & 329 where you're parsing the dates in to date and/or character format. 

What is this section trying to do?

```{r}
nDates <- length(outplantDates) #Number of dates in the outplant experiment
for (j in 4:12) { #For each column with pH data
  for(i in 1:nDates) { #For each date
    pHMinimum[i, j-3] <- min(pHTideData[pHTideData$Date == outplantDates[i], j], na.rm = TRUE) #Find the minimum value of the designated column at each date. The minimum value will be entered in the specified column of the dataframe pHMinimum.
  }
} #The loop will cycle through each date first in one column, then move to the next column.
```

**Comment by yaaminiv** [comment]
> What is this section trying to do?

This is the main for loop where I'm iterating over columns for each date to calculate minimum pH!

`nDates <- length(outplantDates)`: Calculate the length of `outplantDates` to tell me how many dates I have to loop over
`for (j in 4:12)`: For each column in `pHTideData` with actual pH data (some columns have dates, times, or tidal data
`for (i in 1:nDates)`: For each date
`pHMinimum[i, j-3] <- min(pHTideData[pHTideData$Date == outplantDates[i], j], na.rm = TRUE)`: For each row entry in `pHTideData$Date` that matches `i` in `outplantDates`, find the minimum value in column `j` ignoring all N/As. Once the minimum value is calculated, save it in `pHMinimum` row `i` and column `j-3`. The `j-3` helps me add something to the right column.

In going through this, I realized that it should be `j-2` instead of `j-3`. I changed my for loop where I'm iterating over character strings and NOW IT WORKS. I also changed it for my for loop where I'm iterating over dates and it works. So I guess my issue involved me trying to overwrite dates...?

**Comment by kubu4** [comment]
This was the part that I was most curious about:

```min(pHTideData[pHTideData$Date == outplantDates[i], j], na.rm = TRUE)```

Was wondering what type of data the ```min()``` was acting upon. You probably (?) can't use ```min``` on characters (although, I think they do have an underlying numerical value?), so was thinking that might be triggering your second error messages, after you had converted the dates to characters.

Hey, if it works now, then I wouldn't sweat it too much! Nice work!

**Comment by yaaminiv** [comment]
Reopening this issue because I'm encountering the same error with a different data frame using my revised code.

> This was the part that I was most curious about: 
>
> min(pHTideData[pHTideData$Date == outplantDates[i], j], na.rm = TRUE)
>
> Was wondering what type of data the min() was acting upon.

`min()` is acting upon numeric data

**Comment by yaaminiv** [comment]
Now using a dataframe with temperature data, I'm encountering the same error as I did previously with my loop:

<img width="746" alt="screen shot 2018-11-19 at 12 30 26 pm" src="https://user-images.githubusercontent.com/22335838/48733254-ecac5800-ebf6-11e8-8f99-f560f719c44b.png">

Again, it's saying the origin isn't found for `as.Date`. I will try converting to character strings and see if I encounter the same error/a different error

**Comment by yaaminiv** [comment]
It worked using character strings instead of dates! The only weird thing is the resultant dataframe gives you no dates and the last column turns into characters instead of being numeric values, but it's easy to do that conversion after the dataframe is filled.

<img width="755" alt="screen shot 2018-11-19 at 12 46 48 pm" src="https://user-images.githubusercontent.com/22335838/48734102-4f065800-ebf9-11e8-9efc-3210ca40ccc8.png">
![screen shot 2018-11-19 at 12 46 56 pm](https://user-images.githubusercontent.com/22335838/48734103-4f065800-ebf9-11e8-8869-fb5d4f7505b7.png)
