### ISSUE TITLE
Add Oly RNA-seq / quant seq to Nightingales

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#496]
see https://github.com/RobertsLab/resources/wiki/Data-Management#ngs-data-management-plan

**Comment by sr320** [comment]
Is this complete?- important first step

**Comment by ksil91** [comment]
Does this require something of me? All my raw RNASeq data is up there, and Laura's is as well as well but no Wiki page for it..

**Comment by laurahspencer** [comment]
Katherine uploaded to Nightengales here: http://owl.fish.washington.edu/nightingales/O_lurida/20181109_QS_Laura/    
I updated the spreadsheet with my QuantSeq info - not sure what to put in these columns: 
  - Library_ID   
  - Library_name   
  - SeqSubmissionDate    
  - Length  ... I think it's "SE50" (sequences are 50bp) but what does "SE" stand or?  
  - SRA_ID

**Comment by kubu4** [comment]
Looks good. Nothing else needs to be added.

However, here're answers to explain the other stuff:

- Library_ID: A unique number for each library. This has not been implemented as of yet.

- Library_name: A name for a given library, in case multiple libraries were prepared/sequenced at one time.

- SeqSubmissionDate: Date that stuff was submitted to sequencing facility.

- Length: "SE" stands for "single end". The other option is "PE" for "paired end". 

- SRA_ID: This is the ID when sequencing data is submitted to the NCBI short read archive (SRA).

**Comment by kubu4** [comment]
FYI, to keep with our data management plan for ```owl/nightingales```, I moved all the raw data that Katherine uploaded and Laura's data to ```owl/nightingales/O_lurida``` and have removed the two subdirectories. I've also updated the Nightingales sheet to reflect this. I've also appended MD5 checksums to the ```owl/nightingales/O_lurida/checksums.md5``` file.
