### ISSUE TITLE
difficulty with technical replicate clustering

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#50]
In the first step of my analysis, I made an NMDS plot using euclidean distances to see if my technical replicates (two separate injections on the mass spectrometer) clustered well. Unfortunately it's a bit of a...shit show. I've gone through my [R code](https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_SRM_20170902/2017-09-06-NMDS-for-Technical-Replication.R) a few times to see if I made any mistakes reading in data, but I don't think I can find any. This is the best technical replicate clustering I have (I use the term "best" loosely):

![nmds](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-09-08-NMDS-TechnicalReplication-Normalized.jpeg)

The distances between ordinations for each technical replicate is visualized below:

![distances](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-09-08-NMDS-TechnicalReplication-Ordination-Distances.jpeg)

I'd appreciate if anyone could 1) give my code a look and see if they catch any mistakes I made or 2) give me advice on how to best explain this mishap in my PCSGA presentation!

**Comment by sr320** [comment]
Can you provide url to raw data and associated meta-data (i.e. Samples IDs etc)

**Comment by sr320** [comment]
Also - go ahead make protein specific graphs with averages of technical replicates.

**Comment by yaaminiv** [comment]
[Raw data](https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_SRM_20170902/2017-09-06-Gigas-SRM-ReplicatesOnly-PostDilutionCurve-NoPivot-Report.csv)
[Sample IDs](https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_SRM_20170902/2017-07-28-SRM-Samples-Sequence-File.csv)
[Biological Replicate Information](https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_SRM_20170902/2017-09-06-Biological-Replicate-Information.csv)

**Comment by sr320** [comment]
As a matter of proper documentation - how was `.raw` file transformed to this csv. 

---

First guess is going to be discrepancy between what sample was going through the MS and what was entered in as what the sample was.

**Comment by yaaminiv** [comment]
Raw files are imported into the Skyline document, and from Skyline you can export as a .csv. The sequence file was created as we were running samples, so there shouldn't be any discrepancies there!

**Comment by kubu4** [comment]
I assume controls/standards were run with each technical replicate. How does those look?

If you haven't looked at that, my inclination would be to review those technical replicates before getting too crazy with your actual sample data, as the controls/standards should be a much small data set that will be easier to work with.

If your controls/standards technical replicates are jacked, then you can reasonably assume the rest of your data follows suit.

**Comment by yaaminiv** [comment]
@kubu4  The NMDS plot I posted was my way of seeing how my technical replicates are clustering (ex. O90-1 and O90-2). They aren't clustering well at all, and our internal control is wonky across my samples and Laura's samples.

**Comment by kubu4** [comment]
@yaaminiv - Yep, I followed that. 

I'm saying that you don't (didn't) have to do the NMDS on all of your technical reps for your samples if the technical reps for your control/standards were janky.

**Comment by sr320** [comment]
Minor - but when you indicate
>Raw files are imported into the Skyline document, and from Skyline you can export as a .csv.

this is enough data for me to generate that csv?

**Comment by yaaminiv** [comment]
@kubu4 My controls (OBLNK2-1 and OBLNK2-2) are clustering well, but there rest of my samples are not. The internal standard we used (Pierce Retention Time Calculator) was not consistent between all of my samples. The general protocol is to use PRTC concentrations to normalize samples, but I couldn't do that for my data. What should be my next step?

**Comment by yaaminiv** [comment]
@sr320 You'd also need the [blib](http://owl.fish.washington.edu/spartina/DNR_Skyline_20170524/2017-05-23-oyster-desearleinated.blib), [background proteome](http://owl.fish.washington.edu/spartina/DNR_PECAN_Run_1_20170303/Combined-gigas-QC.txt), [transition list](http://owl.fish.washington.edu/spartina/DNR_Skyline_SRM_20170707/2017-07-10-FINAL-SRM-Transitions-with-PRTC/2017-07-10-SRM-Transitions-With-PRTC.csv,

**Comment by sr320** [comment]
Here are some observations...

http://d.pr/v/MsCGgT

I note 101 does not seem to have a replicate.

**Comment by yaaminiv** [comment]
101 has a replicate. Last night I noticed that some replicates were not included in my raw data, meaning they were not added to the Skyline document. I added them and re-exported the data:

https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_SRM_20170902/2017-09-11-Gigas-SRM-ReplicatesOnly-PostDilutionCurve-NoPivot-Report.csv

**Comment by kubu4** [comment]
Out of curiosity, what do you mean by "it wasn't included in my raw data..."? Doesn't the raw data contain everything? There isn't data more raw than raw data.

**Comment by yaaminiv** [comment]
I forgot to upload the corresponding .raw file to Skyline before I exported the .csv that I marked as "Raw data" earlier in the thread. misnomer on my part.

**Comment by sr320** [comment]
In summary - once there is a PCSGA talk in hand, the most efficient means to address this is to focus on methods section of corresponding manuscript that is written in a reproducible mannner.

**Comment by yaaminiv** [comment]
Using Skyline settings suggested by @emmats , I remade my NMDS plots. The clustering is better, but still not great. (Emma: Julian said I should be using euclidean distances and not bray-curtis. His rationale was that peak area is a continuous variable so bray-curtis is not appropriate. I've been using only euclidean distances)

Without normalizing by TIC:

![nonnorm](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-09-08-NMDS-TechnicalReplication-NotNormalized.jpeg)

With normalizing by TIC:

![normalizing](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-09-08-NMDS-TechnicalReplication-Normalized.jpeg)

distances between replicates after normalizing:

![dist](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-09-08-NMDS-TechnicalReplication-Ordination-Distances.jpeg)

**Comment by emmats** [comment]
Could you actually draw lines between replicates on the NMDS plot so we can see where replicates are in relation to each other?

**Comment by yaaminiv** [comment]
@emmats Not sure how but I'll get to it in a few days

**Comment by sr320** [comment]
Please develop a methods protocol from taking samples through skyline and we will re evaluate reps once this can be reproduced (and validated).
