### ISSUE TITLE
Come up with platform for Geoduck genome paper

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#501]

**Comment by sr320** [comment]
@kubu4 can you go ahead and start Gdoc and get Genome Seq methods in place?
and link @ https://github.com/RobertsLab/resources/wiki/Pubathon (number 6).

**Comment by kubu4** [comment]
Done. I'm also updating the [GitHub project wiki](https://github.com/RobertsLab/project-geoduck-genome/wiki)
