### ISSUE TITLE
Titrator rondolino power supply port loose

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#502]
The power supply port of the Mettler Toledo Rondolino is loose which leads to inconsistent power supply to the device and can cause errors during titrator runs. The power supply cord is currently taped in place so the port can transmit power, but can we contact the company to figure out a longer term solution, like a port replacement? @kubu4, @sr320 mentioned you've dealt with this before?

**Comment by kubu4** [comment]
The initial poor connection issue was related to the fact that they sent the incorrect adapter with the initial product shipment. Can you post pics of adapter:

- attached to Rondolino

- end of adapter (to see type of adapter).

**Comment by shellytrigg** [comment]
Our current solution:  
![img_20181128_162541](https://user-images.githubusercontent.com/4720221/49199639-d9fbf680-f34d-11e8-9c12-a90193515f62.jpg)
With no tape, the cord pulls the port away from the machine (notice the gap between the top of the port and the metal).  
![img_20181128_162559](https://user-images.githubusercontent.com/4720221/49199640-da948d00-f34d-11e8-8008-ef40761e401d.jpg)
![img_20181128_162639](https://user-images.githubusercontent.com/4720221/49199644-da948d00-f34d-11e8-9b50-47c7c8d41004.jpg)
Power supply port with no power supply plugged in:  
![img_20181128_162610](https://user-images.githubusercontent.com/4720221/49199641-da948d00-f34d-11e8-8818-e5d027ee159a.jpg)
Power supply port with no power supply plugged in (front view):   
![img_20181128_162614](https://user-images.githubusercontent.com/4720221/49199642-da948d00-f34d-11e8-82c2-b26d8115daa1.jpg)
Adapter:  
![img_20181128_162626](https://user-images.githubusercontent.com/4720221/49199643-da948d00-f34d-11e8-89f3-82df5f33d28f.jpg)

**Comment by kubu4** [comment]
Thanks for these. I've submitted a service request. I'll post updates as they come.

**Comment by kubu4** [comment]
January 8th is proposed repair date. Will unit be back at SAFS by then?

**Comment by sr320** [comment]
It will be at hatchery

Steven B. Roberts
Kenneth K. Chew Endowed Professor
School of Aquatic and Fishery Sciences
University of Washington, Seattle WA
sr320@uw.edu - 206.866.5141
robertslab.info - @sr320

**Comment by sr320** [comment]
We could bring it to campus (presuming they will not go to Brinnon).
This could be almost anytime, but it will live out there for the foreseeable future.
I imagine we would not need to bring everything back?

**Comment by kubu4** [comment]
Correct, we'll need to have the unit here.

We should only need the Rondolino and the power supply for the Rondolino.

**Comment by kubu4** [comment]
> This could be almost anytime, ...

Would Jan. 8th work for scheduling service date?

**Comment by sr320** [comment]
Yes this should be fine…

**Comment by shellytrigg** [comment]
@kubu4 can you confirm we only need to bring the rondolino back?

**Comment by kubu4** [comment]
Rondolino and power supply.

**Comment by kubu4** [comment]
Rondolino "repair" is complete. Solution was new power supply; connection is much more snug. Flexing of port has no effect. However, it is recommended to try to support that power supply connection. Rondolino is on bench in 213 where @shellytrigg placed it yesterday.
