### ISSUE TITLE
Embed pdfs in lab notebook?

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#504]
Has anyone tried embedding pdfs in their Jekyll lab notebook? I exported figures in the pdf format and would like to put them in my lab notebook entry. My guess is that I might need some HTML code...?

I tried the following HTML code in my lab notebook entry and something popped up, but it didn't have my figure:

```
<embed src="https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-11-05-Integrated-Dataset/2018-11-28-Protein-Abundance-NMDS-Ellipse.pdf" width="500" height="375" type='application/pdf'>
```

Lab notebook entry: https://yaaminiv.github.io/MEPS-Revisions-Part3/

**Comment by kubu4** [comment]
You can try using an iframe:

```[iframe src="http://nbviewer.ipython.org/github/sr320/paper-Temp-stress/blob/authorea/ipynb/Array-feature-overlap-03.ipynb" width="100%" same_height_as="window" scrolling="yes"]```

Replace the URL with a URL (or, maybe even a relative path?) to your PDF.

Taken from here: 

https://github.com/RobertsLab/code/blob/7eaac54f4ca13693db38ce5ebb6fd1d7c688cf28/jupyter.md#embed-ipython-notebook-hosted-on-nbviewer-in-onsnetworkorg-wordpress

**Comment by sr320** [comment]
I believe the simplest means would be converting PDFs to images…

**Comment by yaaminiv** [comment]
@kubu4 The iframe didn't work when I replaced the URL

@sr320 Yes...but I'm trying to see if I can avoid that! I exported my figures as pdfs because that's apparently the best way to retain quality. I can always convert to an image but just wanted to know if another solution existed

**Comment by kubu4** [comment]
Export figs as TIFFS. I believe these are an SVG (scalable vector graphic - like a PDF) and will not lose any quality when shrinking/expanding.

**Comment by kubu4** [comment]
Also, for the iframe, you might need to replace those square brackets with ```<``` and ```>``` on the left and right ends, respectively.

**Comment by sr320** [comment]
Quite likely iframes will not be allowed…

**Comment by kubu4** [comment]
I misspoke. TIFFS are _not_ SVGs. TIFFs are actually image files using lossless compression (i.e. they don't degrade each time they are accessed, unlike JPEGS).

You should be able to export directly to an SVG and I believe most modern browsers will display them.
