### ISSUE TITLE
Development of Titrator SOP

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#505]
I believe we have one, but where does it live - and is it complete?

**Comment by shellytrigg** [comment]
[Here are the protocols that Sam made](https://github.com/hputnam/Geoduck_Conditioning/tree/master/Protocols) that I've been following. @kaitlynrm took some video of it too. maybe we can add them to the repo?

**Comment by sr320** [comment]
Lets have this be the canonical protocol -
https://github.com/RobertsLab/project-geoduck-oa/blob/master/protocols/Mettler_T5_Titrator_vPW

@kaitlynrm can you please work on updating this?

**Comment by kaitlynrm** [comment]
I modified @kubu4 's early procedure and added in the new methods we are doing. Nothing is linked- once the repo we have been working in is pushed to github, I can link that info as well.
