### ISSUE TITLE
How/where to set thresholds for DIA analysis

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#507]
Do I set the "stringent thresholds" we talked about yesterday in the EncyclopeDIA GUI? 

![encyclopedia-quant](https://user-images.githubusercontent.com/14934314/49669303-d6cfcd00-fa15-11e8-89bc-be64328af244.PNG)

**Comment by emmats** [comment]
I would hope so, but I don't really know. I don't have an elib that I can import and play around with at the moment. Are there options in the peptide/raw/feature browsers that seem promising?

**Comment by grace-ac** [comment]
Unfortunately nothing that is obvious in the raw browser. Under "File", the only option is to "Open RAW file". 

And the only options in the ELIB/DIA browser under "File" are: "Open BLIB" or "Open RAW file".

**Comment by emmats** [comment]
Those are the options I saw, but I wasn't sure if there were more once you actually had files in there.

Asking Lindsay...

**Comment by emmats** [comment]
You'll need to do the work outside of Bri-line. From Lindsay:
There's built in "filters" when running encyclopedia, the parameters include "min quantitative ions" etc. Other filtering is all DIY. I use R or Python to parse the *.elib.peptides.txt and run statistical tests. Then I set up skyline doc to view results of statistical testing

**Comment by grace-ac** [comment]
OWL folder with output files:  [2015-Cgseed-DIA/EncyclopeDIA-Walnut-outputs](http://owl.fish.washington.edu/scaphapoda/grace/2015-Cgseed-DIA/EncyclopeDIA-Walnut-outputs/) 

[20181210-Cg-quant-reps.elib.peptides.txt](http://owl.fish.washington.edu/scaphapoda/grace/2015-Cgseed-DIA/EncyclopeDIA-Walnut-outputs/20181210-Cg-quant-reps.elib.peptides.txt)

I'm going to start trying some things suggested above.

**Comment by grace-ac** [comment]
@emmats I followed the Skyline part of [data_analysis](https://docs.google.com/document/d/1Vr3wE7Z8eJVenUWgbxJ3CmXxCoNiba_HYQXh7sNce_k/edit), 

here is the Skyline daily zip: http://owl.fish.washington.edu/scaphapoda/grace/2015-Cgseed-DIA/20181210-Cgseed-DIA.sky.zip

I'm not sure if those settings are appropriate for the type of files I have, because that protocol might be for "wide window". Will keep working on it, but figured I'd post update in the meantime.

**Comment by emmats** [comment]
I think that as long as you have the correct isolation scheme you will be fine.
Remember that the instrument settings will be specific to the instrument that was used for your data.

**Comment by grace-ac** [comment]
## I'm thinking I'm close to the point where I can export report and try MSStats? 

New .zip:  [20181210-2015Cgseed-DIA.sky.zip](http://owl.fish.washington.edu/scaphapoda/grace/2015-
Cgseed-DIA/post-EncyclopeDIA-Skyline/20181210-2015Cgseed-DIA.sky.zip)

What I did: [02-SkylineDaily-protocol.md](https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/DIA_2015/protocol/02-SkylineDaily-protocol.md)

All peaks look really good, except some have dotted-line peaks... I'm not sure what that means, but I'm looking into it. 
### Most look really good, similar to this
![26-peaks](https://user-images.githubusercontent.com/14934314/49767157-576d2280-fccf-11e8-889a-867b6489a1d1.PNG)

### Some look like this: 
![27-spotted-peaks](https://user-images.githubusercontent.com/14934314/49767182-6b188900-fccf-11e8-9481-ee71f2828b83.PNG)

**Comment by emmats** [comment]
I've never seen the dotted lines before. If you can't figure it out easily, just send a quick message to Nick*. He'll know.

*Most of the Skyline team is at a meeting in NC this week, but worth a try to save you some time.

**Comment by grace-ac** [comment]
It looks like those are non-quantitative transitions. 

Someone responded to [my question](https://skyline.ms/announcements/home/support/thread.view?rowId=38430) and sent me a link to [this](https://skyline.ms/announcements/home/support/thread.view?rowId=33426):    
![screen shot 2018-12-11 at 11 40 26 am](https://user-images.githubusercontent.com/14934314/49825617-b9627200-fd39-11e8-8bf6-9e5588363d65.png)

**Comment by grace-ac** [comment]
closing this issue. opening a new one with a different, but related topic
