### ISSUE TITLE
Assemble Metagenomic dataset

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#508]
using 
Megahit 
https://github.com/voutcn/megahit
and/or
SPAdes
http://cab.spbu.ru/software/spades

**Comment by kubu4** [comment]
Sorry, here's updates (from a little while ago):

Megahit assembly:

https://robertslab.github.io/sams-notebook/2019/01/02/Metagenome-Assembly-P.generosa-Water-Sample-HiSeqX-Data-Using-Megahit.html

MetaGeneMark gene prediction:

https://robertslab.github.io/sams-notebook/2019/01/03/Gene-Prediction-HiSeqX-Metagenomics-from-Geoduck-Water-Using-MetaGeneMark-on-Mox.html

Want to BLAST the predicted genes for annotation/taxonomy.

Will also run SPAdes and see how that compares.
