### ISSUE TITLE
Annotate Herring transcriptomes

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#511]
Oddly I continue to get inquiries on [this oldy](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0030908)

Can you blastx each to uniprot SP - max_target_seqs 1; 

https://doi.org/10.6084/m9.figshare.89765.v2
https://doi.org/10.6084/m9.figshare.89764.v1

**Comment by kubu4** [comment]
BLASTX outputs (fmt 6) are here:

liver: http://gannet.fish.washington.edu/Atumefaciens/20181212_blastx_herring_transcriptomes/20181212.herring.liver.blastx.outfmt6

testes: http://gannet.fish.washington.edu/Atumefaciens/20181212_blastx_herring_transcriptomes/20181212.herring.testes.blastx.outfmt6
