### ISSUE TITLE
Add order, infraOrder, family to taxonomy blast output

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#513]
Currently, we get the genus and species, common name, and kingdom or domain names

```-outfmt "6 qseqid sseqid evalue bitscore staxids sscinames scomnames sskingdoms" \```

Would like to get some or all of these:
order
infraorder 
family

**Comment by kubu4** [comment]
Does ```staxids``` provide more than one value? If yes, I believe each of those values (should be integers) indicate taxonomic lineage. You might be able to cross-reference those values with [the NCBI taxonomy "dump"](ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump_readme.txt)?

**Comment by sr320** [comment]
Go for it!




(See blastn -help)

Steven B. Roberts
Kenneth K. Chew Endowed Professor
School of Aquatic and Fishery Sciences
University of Washington, Seattle WA
sr320@uw.edu - 206.866.5141
robertslab.info - @sr320
