### ISSUE TITLE
Order replacement pH probe for titrator

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#515]

**Comment by shellytrigg** [comment]
@kubu4 do you happen to know the product number for the Metler-Toledo probe for the Titrator? I found on our purchasing log where you ordered one on 8/21/2017, but I couldn't find the catalog number.

**Comment by kubu4** [comment]
Mettler catalog number is: 89806 (pH Sensor DG115-SC).

**Comment by shellytrigg** [comment]
submitted SAFS purchasing form to Lisa
