### ISSUE TITLE
Error in MS Stats 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#516]
### [R script](https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/DIA_2015/R/Skyline-to-MSstats-format.R)

I'm at the point of doing ```dataProcess``` and I'm getting an error:    
```
#** There are 4379 intensities which are zero or less than 1. These intensities are replaced with 1.
#Error in dataProcess(PeakAreas) : 
  #** MSstats suspects that there are fractionations and potentially technical replicates too. Please add Fraction column in the input.
```

The [DIA processing](http://msstats.org/wp-content/uploads/2017/01/MSstats_v3.7.3_manual.pdf) (page 44), doesn't include a step for removing peptides that have intensities of "0". 

### 2. **What does "fractionations" mean, and should I add a "Fraction" column like the message suggests?

**I'm looking into this as well, but am posting an issue for it in case you have some ideas before I spend too much time on it.**

**Comment by emmats** [comment]
1. I would make sure that your data is what MSStats is expecting. Why wouldn't it like intensities that are <1?
2. No idea what "fractionations" are in this context.  See this post (although maybe not very helpful): https://groups.google.com/forum/#!searchin/msstats/fractionations%7Csort:date/msstats/dVh6IEE0xTE/jiokWrNSCgAJ

I suggest joining the google group. The developer is usually quick to respond and helpful if you can't find the answer in the archives. I'll try to help as I can, but I haven't used MSstats in a long time so 1) I don't remember a lot and 2) they have probably changed a lot.

**Comment by grace-ac** [comment]
@emmats 
### **Should I change what  I set for "BioReplicate"?**      
It seems to be a required column for MS Stats. 

There are four separate samples, so I was a little unsure of how to think about what to do for the "BioReplicate" column.. I ended up doing this:     
![37-results-grid](https://user-images.githubusercontent.com/14934314/49970208-7215e600-fedf-11e8-9979-e60d24d8bc52.PNG)

**Comment by emmats** [comment]
They should all be separate bio replicates

**Comment by emmats** [comment]
I think

**Comment by emmats** [comment]
Just actually checked what I did before. Bio replicate is used for when you have the same bio rep in a condition multiple times. So I think it would be 1,2 and then 1,2.

**Comment by grace-ac** [comment]
so like this instead:    
![39-new-biorep](https://user-images.githubusercontent.com/14934314/50021901-648d5880-ffd2-11e8-96f4-f9576fddaf52.PNG)

**Comment by emmats** [comment]
From what I can tell in my notes, yes.

**Comment by grace-ac** [comment]
Okay, thanks! I'm getting some assistance from Meena from MS Stats regarding the error, so i'll post an update.

**Comment by grace-ac** [comment]
Meena's response:


>To clarify your experiment, there is only one biological replicate per condition. Correct?
>Then, I found the reason for the warning message. The warning message '** MSstats suspects that there are fractionations and potentially technical replicates too. Please add Fraction column in the input.' means that there are multiple MS runs for certain Biological replicate and certain Condition. In this case, MSstats need to know that multiple MS runs came from fractions or technical replicates. Two different cases will be handled differently. I attach the annotation information that I found from your Skyline output. You need to fill in 'Fraction' column and to used in Skyline converter function. If you don't have fractionation and do have technical replicates, just put one unique information, like '1'. If you do have fractionation, please put fractionation information in this column.

### I added "Fraction" Column with "1" as input:     
[R script](https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/DIA_2015/R/Skyline-to-MSstats-format.R)

Followed some of [Yaamini's code](https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_Skyline_20170524/2017-06-22-MSstats/2017-06-22-MSstats.R) for creating some visuals:

[Volcano Plot pdf](https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/VolcanoPlot-1.pdf)

[Comparison Plot pdf](https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/ComparisonPlot-1.pdf)
