### ISSUE TITLE
Locating oyster seed proteomics data files needed for manuscript

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#517]
We are trying to locate all the proteomics data files we'll need for the C.gigas seed temperature x time series manuscript. As a reminder, this data is from [Rhonda's 2016 oyster seed experiment](https://github.com/RobertsLab/project-pacific.oyster-larvae/wiki/2016-Oyster-Seed-experiment-23C-vs.-29C). 

@kaitlynrm what is the original data file you started with? Then maybe @sr320 can trace back from there?

@emmats could you advise on which proteomics data files should be uploaded to which repositories? And if you might know where those data files might live?

**Comment by kaitlynrm** [comment]
I started with [the proteins and their abundance values] (https://github.com/kaitlynrm/OysterSeedProject/blob/master/data/ABACUSdata_only.csv), which I believe is an output from Abacus after proteins were assembled via the TransProteomic Pipeline. @sr320 was able to annotate the table I was given with SwissProt/UniProt on MySql which i think means there is an associated .fasta file? Do you have that date from MySql?

**Comment by emmats** [comment]
Pretty sure Rhonda kept all her files on the local Roberts server. If you can't find them, let me know.

As with all DDA files, they should be uploaded to PRIDE: raw files, pep.xml from Comet search, and fasta search database.

**Comment by sr320** [comment]
This should be the raw data:
http://owl.fish.washington.edu/phainopepla/C_gigas/2016-12-05/

This is also a good test to see how well
https://github.com/RobertsLab/resources/wiki/Data-Management#proteomics-data-management-plan
works / is folllowed.

**Comment by sr320** [comment]
Is this what you need?

**Comment by shellytrigg** [comment]
@sr320 yes, but also looking for where @kaitlynrm's [data file](https://github.com/kaitlynrm/OysterSeedProject/blob/master/data/ABACUSdata_only.csv) came from. It seems like her data file contains the averages of the technical replicate peptide ADJNSAF values from [this data file you generated](https://github.com/sr320/nb-2017/blob/master/C_gigas/data/ABACUS_output021417.tsv), which was also linked in [this issue](https://github.com/sr320/LabDocs/issues/530). 

I found your posts from [2/13/2017](https://github.com/sr320/sr320.github.io/blob/master/_posts/2017-02-13-Going-through-DDA.md) and [2/15/2017](https://github.com/sr320/sr320.github.io/blob/master/_posts/2017-02-15-Abacus-Failure.md) but I'm unclear how [ABACUS_output021417.tsv](https://github.com/sr320/nb-2017/blob/master/C_gigas/data/ABACUS_output021417.tsv) was made, or why the ADJNSAF values in that file would be different than those in [the data generated by Sean(and/or Rhonda)](http://owl.fish.washington.edu/scaphapoda/Sean/Rhonda-2016-Oyster-Intermediates/ABACUS_output.tsv) despite [their ABACUS parameters](http://owl.fish.washington.edu/scaphapoda/Sean/Rhonda-2016-Oyster-Intermediates/Abacus-01.param) appearing the same as [yours](http://owl.fish.washington.edu/halfshell/working-directory/17-02-14b/Abacus-01.param). [Your source .mzXML files](http://owl.fish.washington.edu/halfshell/working-directory/17-02-14/) and [their source files](http://owl.fish.washington.edu/scaphapoda/Sean/Rhonda-2016-Oyster-Intermediates/) also appear the same based on file name and size.

@sr320 @emmats @kaitlynrm if this rings any bells or if there is a closed issue somewhere about this, please share here.

**Comment by kaitlynrm** [comment]
Those files that are posted and we discussed are the only ones I know of.

**Comment by emmats** [comment]
I remember that we couldn't figure out how she made the file. If you are up for it, it could be worth it to remake the file so that you know what you are working with.

**Comment by sr320** [comment]
I can help with that- the focus now for Kaitlyn and Shelly should be to complete a methods section that describes the experiment and also presumably how data was generated. We can then follow the methods section to determine accuracy / reproduce.

**Comment by shellytrigg** [comment]
@sr320 [here is the draft paper](https://docs.google.com/document/d/1OusRSi9W5qLRcc3nuJm-kyQYrTQb7yPFiCBtqZIKNpQ/edit?usp=sharing) where Kaitlyn and I are actively working on the methods section. And here is [a more detailed description of the analysis part](https://github.com/shellytrigg/OysterSeedProject/blob/master/analysis/2016OysterSeedProteomicsAnalysisMethods.md).

I also [figured out what the discrepancies between the files were](https://github.com/shellytrigg/shellytrigg.github.io/blob/master/_posts/2019-1-11-31th-post.md). Your ABACUS_output021417.tsv and Sean's ABACUS_output.tsv files were the same, but your ABACUS_output021417NSAF.tsv file actually contains NUMSPECADJ values, not NSAF values. And the data file that Kaitlyn and I have been working with contains average NUMSPECADJ values. 

I'm going to start a new issue to clarify what Abacus output values we should be using for different analyses.
