### ISSUE TITLE
Imaging gigas histo

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#52]
@yaaminiv  -  Do I just label the oyster samples sequentially, or do you have a histology key denoting which tissue belongs to which individual?

**Comment by yaaminiv** [comment]
Here's the key!

https://github.com/RobertsLab/project-oyster-oa/blob/master/data/2017-02-04-Adult-Gigas-Tissue-Sampling/20170408-GigasTissueSamplingInformation.xlsx

**Comment by grace-ac** [comment]
quick q: there is blue dye on samples - was that placed on the top-left tissue sample? @yaaminiv

**Comment by yaaminiv** [comment]
@grace-ac yup

**Comment by grace-ac** [comment]
Things got re-ordered during the histology process, it seems. This happened with Laura's samples as well. 

I think I may have labeled Gigas 1 and Gigas 2 correctly, but Gigas 3-5 seem to have been rearranged quite a bit. Images below: Any thoughts, @yaaminiv 

![gigas_1-04082017](https://user-images.githubusercontent.com/14934314/30295965-6279bb1e-96f7-11e7-9d00-efc5c7baa18d.JPG)
![gigas_2_04082017](https://user-images.githubusercontent.com/14934314/30295966-6279f44e-96f7-11e7-98f2-44886b69f053.JPG)
![gigas_3](https://user-images.githubusercontent.com/14934314/30295964-6276b086-96f7-11e7-93c8-a1604481df0c.JPG)
![gigas_4](https://user-images.githubusercontent.com/14934314/30295967-627ca5b8-96f7-11e7-9648-2cbc27e096d1.JPG)
![gigas_5](https://user-images.githubusercontent.com/14934314/30295968-62865608-96f7-11e7-8f39-b6fcacf1c82f.JPG)

**Comment by sr320** [comment]
Status?

**Comment by grace-ac** [comment]
all slides were imaged.
