### ISSUE TITLE
tax blast: why is there no taxonomy info? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#521]
My BLAST on Mox with ```nt``` taxonomy database finished. 

### **Why is the taxonomy information missing?**    
**All cells have "N/A"**     

File: [1129-Cb-tax-blast.tab](http://owl.fish.washington.edu/scaphapoda/grace/Crab-project/1129-Cb-tax-blast.tab)
![screen shot 2018-12-17 at 12 59 59 pm](https://user-images.githubusercontent.com/14934314/50115426-37bc8980-01fc-11e9-8399-45fcd30dca33.png)

```head``` on Mox:    
![screen shot 2018-12-17 at 1 03 30 pm](https://user-images.githubusercontent.com/14934314/50115458-4efb7700-01fc-11e9-95a7-225f867bc654.png)

#### Script used:    

```
#!/bin/bash
## Job Name
#SBATCH --job-name=1129-cg-blastn-tax
## Allocation Definition
#SBATCH --account=coenv
#SBATCH --partition=coenv
## Resources
## Nodes (We only get 1, so this is fixed)
#SBATCH --nodes=1
## Walltime (days-hours:minutes:seconds format)
#SBATCH --time=4-00:00:00
## Memory per node
#SBATCH --mem=100
##turn on e-mail notification
#SBATCH --mail-type=ALL
#SBATCH --mail-user=graceac9@uw.edu
## Specify the working directory for this job
#SBATCH --workdir=/gscratch/srlab/graceac9/analyses/1129-Cb-tax-blstn

export BLASTDB=/gscratch/srlab/blastdbs/

/gscratch/srlab/programs/ncbi-blast-2.6.0+/bin/blastn \
-query /gscratch/srlab/graceac9/query/library01/query.fa \
-db /gscratch/srlab/blastdbs/ncbi-nr-nt-20181114/nt \
-out /gscratch/srlab/graceac9/analyses/1129-Cb-tax-blstn/1129-Cb-tax-blast.tab \
-max_target_seqs 1 \
-evalue 1e-20 \
-outfmt "6 qseqid sseqid evalue bitscore staxids sscinames scomnames sskingdoms" \
-num_threads 28 \
-task blastn
```

**Comment by sr320** [comment]
Bit of a mystery... here is my code that provided taxonomy...

```
#!/bin/bash
## Job Name
#SBATCH --job-name=cg-blastn-tax
## Allocation Definition 
#SBATCH --account=coenv
#SBATCH --partition=coenv
## Resources
## Nodes (We only get 1, so this is fixed)
#SBATCH --nodes=1   
## Walltime (days-hours:minutes:seconds format)
#SBATCH --time=4-00:00:00
## Memory per node
#SBATCH --mem=100
##turn on e-mail notification
#SBATCH --mail-type=ALL
#SBATCH --mail-user=sr320@uw.edu
## Specify the working directory for this job
#SBATCH --workdir=/gscratch/srlab/sr320/analyses/1114b

export BLASTDB=/gscratch/srlab/blastdbs/

/gscratch/srlab/programs/ncbi-blast-2.6.0+/bin/blastn \
-query /gscratch/srlab/sr320/query/Cbairi_trinity_1113.fa \
-db /gscratch/srlab/blastdbs/ncbi-nr-nt-20181114/nt \
-out /gscratch/srlab/sr320/analyses/1114b/cg-trinity-nt.tab \
-max_target_seqs 1 \
-evalue 1e-20 \
-outfmt "6 qseqid sseqid evalue bitscore staxids sscinames scomnames sskingdoms" \
-num_threads 28
```

**Comment by kubu4** [comment]
I can't say why @sr320's would work and yours wouldn't.

However, I'd change this:

```export BLASTDB=/gscratch/srlab/blastdbs/```

to this:

```/gscratch/srlab/blastdbs/ncbi-nr-nt-20181114/```

The reasoning behind doing this is that this is the actual directory where the databases exist, as well as where the taxonomy database files exist.

**Comment by grace-ac** [comment]
- I put my script in text wrangler and there weren't any extra spaces or anything.

- I compared mine to @sr320 's and couldn't find any differences besides obvious file names and directories

- re-running now with @kubu4 suggested edit to ```export BLASTDB=/gscratch/srlab/blastdbs/ncbi-nr-nt-20181114/```

**Comment by sr320** [comment]
I am going to suggest the tax files moved....

**Comment by sr320** [comment]
somewhat unrelated - this job never really hits 28 threads, on average about 5... 
Not a big deal I suppose and I am guessing related to the size of the database.

**Comment by sr320** [comment]
and can confirm `export BLASTDB=/gscratch/srlab/blastdbs/ncbi-nr-nt-20181114/` works ..

**Comment by kubu4** [comment]
> I am going to suggest the tax files moved....

Based on [this issue](https://github.com/RobertsLab/resources/issues/486), I don't think they've been moved.

**Comment by sr320** [comment]
Well actually... 😏 [that issue](https://github.com/RobertsLab/resources/issues/486#issuecomment-438823950) indicates it was moved 

(at the time it was not in the same directory as nt and now it is... )

**Comment by kubu4** [comment]
> Well actually... smirk that issue indicates it was moved
>
> (at the time it was not in the same directory as nt and now it is... )

Hmmm, I'm not sure I follow. It's always been in ```/gscratch/srlab/blastdbs/ncbi-nr-nt-20181114/```. I even indicate that in that issue. 

Eh, it's fixed, that's the important part!
