### ISSUE TITLE
Connecting snap gene models with annotations

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#523]
The last Maker run looks great in providing gene models!

Here is an example of output (gff)

```
Contig0    maker    gene    12485    93036    .    +    .    ID=maker-Contig0-snap-gene-0.6;Name=maker-Contig0-snap-gene-0.6
```

What is the best way to join annotations (eg Swiss-Prot) to this?
We could `getfasta` and blast but curious if there is a "built-in" solution.

**Comment by kubu4** [comment]
No built in solution. We'll need to do some blasting using the merged FastA produced by MAKER.

**Comment by sr320** [comment]
Do you have a url for that?

**Comment by kubu4** [comment]
These would be the files that need blasting:

Transcripts: http://gannet.fish.washington.edu/Atumefaciens/20181127_oly_maker_genome_annotation/Olurida_v081.all.maker.transcripts.fasta

Proteins: http://gannet.fish.washington.edu/Atumefaciens/20181127_oly_maker_genome_annotation/Olurida_v081.all.maker.proteins.fasta

**Comment by kubu4** [comment]
I'm also working on getting BUSCO/Augustus set up to get a "final" refined gene model, as that seems to be the standard way to do this. However, reading suggests that two rounds of SNAP prediction are pretty good.

**Comment by kubu4** [comment]
There's also built in MAKER functions to make the FastA descriptions more human-readable and are standardized towards NCBI FastA descriptors, instead of these MAKER-specific descriptors. I figured I'd run those, but have been trying to get the metagenome stuff going and getting the geoduck MAKER run set up.

**Comment by kubu4** [comment]
MAKER actually will handle the post-blast annotation of the existing GFF(s) and FastA files. Running blast now and will get these incorporated in to GFF files.

**Comment by kubu4** [comment]
Done!

Fully annotated GFF here: http://owl.fish.washington.edu/halfshell/genomic-databank/Olurida_v081.all.gff

Individual tracks are listed on [Genomic Resources wiki](https://github.com/RobertsLab/resources/wiki/Genomic-Resources#genome-feature-tracks-2)

Functional annotation notebook entry: https://robertslab.github.io/sams-notebook/2019/01/09/Annotation-Olurida_v081-MAKER-Functional-Annotations-on-Mox.html
