### ISSUE TITLE
Discrepencies between online and github desktop repo 

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#525]
Anyone know how to resolve changes not recognized between an online repo and a local repo? I did some local directory organization and my local changes are not recognized by github desktop or by git from the command line. If I try to pull or fetch it says 'already up to date' even though there are discrepancies.
 
Here's a screenshot of some of the discrepancies:  
![screen shot 2018-12-20 at 6 05 43 pm](https://user-images.githubusercontent.com/4720221/50320628-140a7500-0482-11e9-8ac3-70a744911302.png)
This is a shot of the github desktop not recognizing differences:  
![screen shot 2018-12-20 at 6 03 22 pm](https://user-images.githubusercontent.com/4720221/50320742-a3b02380-0482-11e9-8e01-99e120136428.png)
This is a shot of git commit results from command line:  
![screen shot 2018-12-20 at 6 09 17 pm](https://user-images.githubusercontent.com/4720221/50320860-1ae5b780-0483-11e9-8a43-d6cdcc527252.png)
this is my git log:   
![screen shot 2018-12-20 at 6 10 29 pm](https://user-images.githubusercontent.com/4720221/50320871-276a1000-0483-11e9-9591-8dc2022d7f79.png)
this is the git fetch and git pull output:  
![screen shot 2018-12-20 at 6 13 52 pm](https://user-images.githubusercontent.com/4720221/50320891-36e95900-0483-11e9-8c7f-373bab7a20d8.png)

**Comment by shellytrigg** [comment]
git status shows no new changes  
![screen shot 2018-12-20 at 6 59 06 pm](https://user-images.githubusercontent.com/4720221/50322318-68fdb980-0489-11e9-9b05-4dfb8b3add7f.png)

I typically make a new directory and add new files through the finder window, and the GitHub Desktop GUI normally recognizes those changes. But you're right, it seems like the problem is moving things around within the directory from the finder window. I just tested this with some random files and those
moves aren't recognized by the GUI.

**Comment by kubu4** [comment]
Also, did you try pushing to GitHub?

Also, any remote possibility that this is somehow included in your ```.gitignore``` file?

**Comment by shellytrigg** [comment]
git push from command line says everything up to date:  

![screen shot 2018-12-20 at 7 56 26 pm](https://user-images.githubusercontent.com/4720221/50323982-64d59a00-0491-11e9-865b-dc66e53d9b53.png)

This is my .gitignore file:  
Shellys-MacBook-Pro:P_generosa Shelly$ cat .gitignore 
.DS_Store
*.DS_Store
*.Rhistory
*.RData
*video/
*pics/
.Rproj.user
*.html
Apex_Setup_37399

I tried removing the .gitignore file and seeing if the local changes would show up, but they didn't.

**Comment by kubu4** [comment]
One last thing to try (substitute your relative path to that folder you show in your screencap above)

```git check-ignore -v path/to/20181219```
