### ISSUE TITLE
Upload oyster JSR accepted manuscript to UW Research Works

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#527]
similar to what Jay has done.
https://digital.lib.washington.edu/researchworks/handle/1773/34298

**Comment by yaaminiv** [comment]
@jldimond How did you submit to ResearchWorks? I'm unable to submit my manuscript because I'm not part of the faculty group.

**Comment by jldimond** [comment]
I can't remember the process exactly but I know you don't need to be faculty. Check out this page and I'd suggest just emailing them if you're stuck: http://researchworks.lib.washington.edu/rw-archive.html

**Comment by yaaminiv** [comment]
Thanks! Didn't realize there was a Google Form you could fill out to upload your work. I just filed out the form and will post the URL here once the submission has been uploaded.

**Comment by yaaminiv** [comment]
http://hdl.handle.net/1773/43182
