### ISSUE TITLE
Split up Easter oyster VCF

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#528]
Using prior approach 
http://onsnetwork.org/kubu4/2018/10/15/vcf-splitting-with-bcftools/

Please split up 
http://gannet.fish.washington.edu/seashell/eog_v2/VCF_files/Combined.SNP.TRSdp5g95FnDNAmaf05.vcf.gz

**Comment by kubu4** [comment]
Update:

Files are currently splitting. 

20 have been completed and it's taking ~1hr to split out each individual VCF. 

I don't know how many total samples are present, but this should give you a rough idea of when this will finish.

**Comment by kubu4** [comment]
Alrighty, this finally completed last night. Link to files:

http://gannet.fish.washington.edu/Atumefaciens/20190103_Cvirginica_vcf_splitting/

Link to lab notebook:



Link to Jupyter notebook:

https://github.com/RobertsLab/code/blob/master/notebooks/sam/20190103_swoose_C.virginica_vcf_splitting.ipynb
