### ISSUE TITLE
Lab Sticker - for water bottles, laptops, etc

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#53]
https://www.stickermule.com/products/circle-stickers 

Thinking circle stickers with the lab label? 

@sr320 was thinking it'd be fun to have it just be the lab logo, so that people have to ask you, "Excuse me, what does that sticker mean?" and other such variations. 

Here's a draft of what it could look like, along with a version with some text. Any ideas??? Colors;
other text; just logo... etc. 

![srlab_sticker_words](https://user-images.githubusercontent.com/14934314/30299632-662b48a0-9705-11e7-97fd-c16e1d5e968a.png)
![srlab_sticker_logo](https://user-images.githubusercontent.com/14934314/30299631-6624b062-9705-11e7-895f-881eeee7f0cf.png)

**Comment by yaaminiv** [comment]
I personally would display the one without text on my water bottle, but I think the one with text would be useful for conferences/networking. I think logo could be bigger on both versions.

**Comment by MeganHintz** [comment]
YAY stickers! 
I think just the lab logo for stickers would be cool, or for it to have small text under just saying "UW Roberts Lab" similar to the location stickers (such as the Seattle one below).
![image](https://user-images.githubusercontent.com/14929070/30342291-3d5c0df2-97ae-11e7-86ab-d3986b1a013e.png)

I agree, it would be nice to have an image with the logo and Roberts Lab to easily add to posters and presentations. 

How big do we want the stickers? If its just the logo I'd think a 2x2 would be good.

**Comment by sr320** [comment]
clear is an option too
https://www.stickermule.com/products/clear-stickers
