### ISSUE TITLE
Submit Raw Proteomic Data to PRIDE

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#535]
Submit raw proteomic data associated with MEPS manuscript EBI Pride

**Comment by yaaminiv** [comment]
Uploaded data to PRIDE, will post accession number when I get it

**Comment by yaaminiv** [comment]
Accession number: PXD012527

**Comment by sr320** [comment]
Should this not be provided in the manuscript?

Steven

**Comment by yaaminiv** [comment]
Yes, but unfortunately I didn't get the accession number until now. I sent you the proofs so they could be sent off by their Monday morning Central European Time requirement. I could add it to the proof and resend it...?

**Comment by sr320** [comment]
Yes, please do..

Steven

**Comment by yaaminiv** [comment]
Done.
