### ISSUE TITLE
Git Push fail: 'fatal: the remote end hung up unexpectedly'

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#538]
I'm trying to push my local changes to the [RobertsLab/project-pacific.oytser-larvae](https://github.com/RobertsLab/project-pacific.oyster-larvae) and am getting a fail message: 

```fatal: The remote end hung up unexpectedly```

I have tried doing this from my R, from my GitHub Desktop, and from command line.

My most recent attempt, I did:       
```git config http.postBuffer 524288000``` to increase the buffer to 500MB, but still got the same fatal message. 

I think it's because I was trying to push too much all at once... and should have broken it down into a few commits at a time...

**Comment by sr320** [comment]
You should be able to reverse commits and commit and push in smaller increments. I can only assist w GUI - but feel free to stop by office.

**Comment by grace-ac** [comment]
oh wow. yup! forgot about that. thanks!
