### ISSUE TITLE
Characterizing DMR for C. virgnicia analysis

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#544]
So far I've characterized the [location of DML/DMR in the genome](https://yaaminiv.github.io/DML-Analysis-Part17/), characterized the [location of the gene background](https://yaaminiv.github.io/DML-Analysis-Part19/) in the genome, and [conducted a proportion test](https://yaaminiv.github.io/DML-Analysis-Part20/) to compare locations of the DML/DMR and the gene background. I also conducted a [flanking analysis for DML/DMR](https://yaaminiv.github.io/DML-Analysis-Part18/). 

Now, I want to describe the genes DMR are in. I could conduct a gene enrichment using the gene background and DMR file. I would also need to account for how the gene background was constructed. I'm pretty confident I know how to do the gene enrichment, but I don't really know how to account for the gene background. I think I can compare the gene background with the *C. virginica* genome...? @sr320 you mentioned looking at how many hits a DMR had with the gene background (or did I misinterpret what you said)...?

**Comment by sr320** [comment]
I believed we have discussed this...
