### ISSUE TITLE
Compile Co-author list

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#550]
Please add co-authors in past two years from
http://faculty.washington.edu/sr320/?page_id=13537
up to and not including 
The Aquaculture Genomics, Genetics and Breeding Workshop (2017) 
to https://docs.google.com/spreadsheets/d/16qzqfVIhzi6thEck8mCDp4C09q5K4DWXEqU_MtFKmLs/edit#gid=0

**Comment by kaitlynrm** [comment]
Finished!
