### ISSUE TITLE
Balance and microfuge

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#551]
The balance in FTR209 seems to be on the fritz (won't stabilize; throws an error when taring). A new Mettler Toledo comparable balance is ~$1000 (list).

We only have one functional microfuge in the labs. A second one would be helpful for keeping in the refrigerator (or, getting a refrigerated unit - pricey).

**Comment by sr320** [comment]
You can go ahead and order a balance. 66-4313

Preference on microfuge?

**Comment by kubu4** [comment]
OK, thanks.

I'd lean towards the tried-and-true Eppendorfs, but I'll get some quotes from various manufacturers and post here.

**Comment by kubu4** [comment]
After looking around, it looks like most microfuges (non-refrigerated) are in the $2500 - $2800 range. Eppendorf is towards the high end, but they're including an electronic repeater pipette as part of a current promotion...

**Comment by kubu4** [comment]
Which budget(s) should I use for microfuge?

**Comment by sr320** [comment]
66-4313

Steven
