### ISSUE TITLE
Bairdi RNA isolations - next steps?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#552]
Post outlining the protocol I followed with Trizol LS: [Jan 14, 2019](https://grace-ac.github.io/Centrifuge-error-3-fail-extraction/)

Post with comments of what happened when I [actually extracted with the Trizol LS](https://grace-ac.github.io/Trizol-ls-extraction-fail/)

#### What should I do now?
1. Use Trizol LS again on different samples and hopefully there'll be RNA to bioanalyze?
2. Go back to the Qiagen RNeasy Micro Plus Kit and extract some more samples and bioanalyze?
3. Other...?

**Comment by kubu4** [comment]
This may sound a little ridiculous, but I believe the manual is missing a step. Specifically, after adding chloroform, you should vortex the tube for ~15s to create an emulsion (i.e. sample should be uniformly cloudy). I've never seen a phenol-based RNA extraction where a vortexing step isn't needed after the addition of chloroform.

So, maybe give it another shot, but vortex after you add the chloroform.
