### ISSUE TITLE
anyone have extra tissue/hemolymph samples I can use?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#554]
### Do any of you have any extra **hemolymph** or **tissue** samples from any organisms that I can use?

I want to try out a couple of RNA extraction protocols on other organisms (I have been having issues with my crab hemolymph samples) to see if the protocols work with other samples.

**Comment by sr320** [comment]
Check the -80 database, I am sure there are plenty of forgotten samples.

Steven

**Comment by yaaminiv** [comment]
@grace-ac There are lots of leftover tissue samples from the DNR project that could be used!

**Comment by shellytrigg** [comment]
@grace-ac I have some hemolymph samples from the test geoducks we had here at UW that you could try.

**Comment by shellytrigg** [comment]
@grace-ac yes. You could try the samples in the first row labeled '1H', '2H', '1H 11-08', and/or '2H 11-08'. 
![img_20190104_173617 2](https://user-images.githubusercontent.com/4720221/51768835-49fcd380-2096-11e9-8a27-53a4394c1eab.jpg)
