### ISSUE TITLE
How to use Trizol LS Reagent with Tissue sample

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#555]
### Isn't there usually some sort of crushing of tissue samples that has to happen before extraction? 

This is all the Trizol LS Reagent Manual says:     
![trizol-lyse-samples](https://user-images.githubusercontent.com/14934314/51769688-89c4ba80-2098-11e9-8efc-afd88c3786f9.png)

**Comment by kubu4** [comment]
Sorry, I know this is closed, but I'm not sure I understand. You wouldn't use Trizol LS with a tissue sample - that's what regular Trizol is for. Trizol LS is specifically designed for use with liquid samples (LS).

**Comment by grace-ac** [comment]
Makes sense. I closed it on saturday when i went in and did lab work. i just used two extra oyster tissue samples with the reagent.

I just went back to [my post](https://grace-ac.github.io/trizol-with-geo-and-oyster/) and added a note to disregard the oyster tissue results- as that's not what the reagent is meant for. Thanks!

**Comment by kubu4** [comment]
No reason to disregard results - it'll still isolate RNA.
