### ISSUE TITLE
check sensaphone on freezer

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#56]

**Comment by grace-ac** [comment]
What about this am I checking?

**Comment by kubu4** [comment]
Please verify that it can call out. The manual is here: https://github.com/RobertsLab/resources/blob/master/equipment_manuals/sensaphone_1104_manual_20170807.pdf

See if the manual has a way to trigger an alarm state without actually opening the freezers.

**Comment by grace-ac** [comment]
![screen shot 2017-09-21 at 3 42 08 pm](https://user-images.githubusercontent.com/14934314/30722000-901ee816-9ee3-11e7-9113-de88dfcccaa7.png)

**Comment by kubu4** [comment]
I called the Sensaphone successfully. This suggests that phone line is functional and has not been deactivated since FTR phone were converted to VoIP.
