### ISSUE TITLE
Yaamini's Code of Conduct page feedback

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#560]
Again, can post into separate issues if that's better!

-Is there any place for people to sign in agreement/state they read this?
-"...or religion (or lack thereof)" --> add "etc." to the end of this sentence (think the "etc." important in case we left out any category of identify)
-Less Quick Version: Guess this plays into to the fact that SAFS is working on said protocol, but I think it would be good to include other options/resources outside of @sr320  and the ombud (ex. Title IX office, Tim and/or Amy, disability resource, etc.)

**Comment by sr320** [comment]
All improvements made - (there is not a place for people to sign)
