### ISSUE TITLE
Details on hatchery microbiome sequencing

### ISSUE THREAD

**Issue by emmats** [RobertsLab/resources#562]
Does anyone have information on what each library/file name corresponds to for the hatchery microbiome metagenomic sequencing? @kubu4? @sr320?

**Comment by kubu4** [comment]
Look for "original_sample" column here:

https://docs.google.com/spreadsheets/d/131Z45uaUycJhyZJRxbEVlOviyoGqV44GehUxaaOWcGo/edit#gid=1917516568

**Comment by emmats** [comment]
I'm not done!
I seem to be missing the MG4 sequences. Do you have them?

**Comment by sr320** [comment]
As a “data check” is this info also in nightingales spreadsheet?

**Comment by kubu4** [comment]
Yes, nightingales is accurate (i.e. has the sequence files).

MG4 was not sequenced. See the email I sent you previously:

Hi >Emma,

>Steven asked me to pass along info about the metagenome libraries and have you submit the libraries to genome sciences for sequencing (single lane of sequencing on a HiSeq 2500).>

>Here are the details:

>Pooled library location: Sam's gDNA Box #2, Position I4. This box is in the small -20C in FTR 213.>

>Libraries were constructed with the Illumina Nextera Flex DNA kit. They are dual-indexed.>

>Library names and corresponding indexes:

>Library Geoduck MG #1	H503	H705
>Library Geoduck MG #2	H505	H706
>Library Geoduck MG #3	H506	H707

>	
>	
>Library Geoduck MG #5	H503	H711
>Library Geoduck MG #6	H505	H714
>Library Geoduck MG #7	H505	H705

>My notebook entry on library prep is here: http://onsnetwork.org/kubu4/2018/06/06/library-construction-geoduck-water-filter-metagenome-with-nextera-dna-flex-kit-illumina/>

>Thanks!

  |   |  
Library Geoduck MG #5 | H503 | H711
Library Geoduck MG #6 | H505 | H714
Library Geoduck MG #7 | H505 | H705
