### ISSUE TITLE
Dead links - Colton Shellfish Collection site

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#563]
Greg Jensen came by today to ask about some links and noted they were dead.

Colton website: 

http://owl.fish.washington.edu/halfshell/bu-wikispaces/genefish/mainSpace/Colton.html

Dead links are those that link to the PDFs of index card subsets (e.g. 0001-0020):

http://aquacul4.fish.washington.edu/mercenaria/0001-0020.pdf

- Where is backup for aquacul4?

Additionally, the full index card PDF doesn't download as a PDF. It downloads as  very small file and I'm unable to open it.

http://faculty.washington.edu/sr320/Colton/Colton%20Collection_ocr.pdf

**Comment by sr320** [comment]
suggesting he was using this info?
Or was there something specific he was looking for?

**Comment by kubu4** [comment]
Yes, he was trying to find some info. He didn't really specify - he doesn't really say too much. :)

It sounds like they've found space in FSH to put some of the collection on display and he was trying to find info on specimens.

**Comment by sr320** [comment]
will not fix
