### ISSUE TITLE
Explanation of this aov() function?

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#564]
I've had Ronit recycle some old R code for computing some statistics on his qPCR data. However, I didn't write the code, nor do I have enough grasp of R to understand what the code is doing. Here's the code:

```aov(formula = HSC70 ~ Ploidy + Desiccation + Ploidy:Desiccation, data = dCt)```

Quick description of the data:

- HSC70 is column name in dataframe ```dCt``

- Data are Cq values

Here's link to his R project if anyone needs/want to run the script themselves (there are two scripts in the Scripts directory - either one will do the same thing):

https://github.com/ronitjain31/gigas_ploidy

**Comment by sr320** [comment]
I suppose you want more than

https://www.rdocumentation.org/packages/stats/versions/3.5.2/topics/aov

😉

**Comment by kubu4** [comment]
Ha! Yep! What are the tilde and plus symbols and colon doing in that formula above?

**Comment by kubu4** [comment]
Thanks for that! What are the plus symbols doing? Why isn't everything
connected by colons?

**Comment by yaaminiv** [comment]
You can add multiple factors to examine with the ANOVA. This formula is saying conduct an ANOVA looking at HSC70 Cq values based on the following factors: Ploidy, Desiccation, and the interaction between Ploidy and Desiccation (Ploidy:Dessication)

**Comment by kubu4** [comment]
Sweet! Thanks!

**Comment by ronitjain31** [comment]
Hey Yaamini, do you mind explaining what exactly you mean by the "interactions between Ploidy and Desiccation variables?" Also to clarify--the Ploidy variable looks at differences between triploid and diploid samples irrespective of treatment, and the Desiccation variable looks at differences between control and desiccated samples irrespective of ploidy, right?

**Comment by yaaminiv** [comment]
@ronitjain31 

> Also to clarify--the Ploidy variable looks at differences between triploid and diploid samples irrespective of treatment, and the Desiccation variable looks at differences between control and desiccated samples irrespective of ploidy, right?

Yes!

>  do you mind explaining what exactly you mean by the "interactions between Ploidy and Desiccation variables?"

As you noted above, the ploidy variable looks at differences between different ploidy statuses without desiccation treatment, and desiccation doesn't incorporate ploidy. The interaction variable, `Ploidy:Dessication`, looks at both ploidy and desiccation treatment at the same time to see if there's a combined effect.

**Comment by ronitjain31** [comment]
Makes sense, thanks so much!
