### ISSUE TITLE
Place for NGS assemblies

### ISSUE THREAD

**Issue by emmats** [RobertsLab/resources#567]
I have assembled NGS data from the hatchery microbiome project that I would like to make accessible to the Roberts Lab. Where should I put it?

Do you have the raw data from the sequencing effort already, or should I move that over too?

**Comment by kubu4** [comment]
We have raw data, thanks. Upload to your directory on Eagle, just like the good old days!

**Comment by emmats** [comment]
I don't remember my login details for eagle. Can someone send me some login credentials?

**Comment by kubu4** [comment]
Check email for info.
