### ISSUE TITLE
Does Plass recognize paired NGS files?

### ISSUE THREAD

**Issue by emmats** [RobertsLab/resources#568]
I'm trying to figure out if the NGS assembly software Plass (https://github.com/soedinglab/plass
) will recognize pairs of sequencing files. I asked the developer and this was his response (I'm not sure exactly what he means):
Only if they have the same order in both files. We do not try to detect similar identifier. 

Plass calls FLASH (paired end read merger) as a first step to combines the reads. 

Any insight on if I can safely proceed? Here is the website for Flash: https://ccb.jhu.edu/software/FLASH/

If not, I will try to get clarity from the developer.

**Comment by kubu4** [comment]
Yes. The info is right on the page you linked:

> Plass can assemble both paired-end reads (FASTQ) and single reads (FASTA or FASTQ):

>  # assemble paired-end reads 
>  plass assemble examples/reads_1.fastq.gz examples/reads_2.fastq.gz assembly.fas tmp

**Comment by kubu4** [comment]
Unless you're having a problem, don't worry about it.

However, generally sequencing reads from paired-end sequencing should be in the same order in the two files (e.g. the first read of read one and the first read of its pair should both exist in the same positions in the two corresponding FastQ files).

**Comment by emmats** [comment]
I probably wouldn't have worried about it if he hadn't specifically mentioned it!
