### ISSUE TITLE
Try GenSas for Geoduck genome annotation

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#570]
https://www.gensas.org/

**Comment by kubu4** [comment]
Hmmm, not sure we can use this. Our geoduck assembly has 313,649 sequences, but GenSas has a limit of 25,000 sequences:

![image](https://user-images.githubusercontent.com/4514104/52574125-6ad06300-2dd0-11e9-86d6-ccd244286f8a.png)

**Comment by kubu4** [comment]
Maybe I can just split the FastA so each one is <25,000 sequences? I'll give it a shot and see what happens.

**Comment by kubu4** [comment]
Nope, can't split. That limit is the total number of seqs across all files.

**Comment by sr320** [comment]
How about giving v071 a try 


https://github.com/RobertsLab/resources/issues/572

**Comment by kubu4** [comment]
Quick update, as I've finally revisited.

Stuff is "running", but only preliminary stuff (RepeatModeler and RepeatMasker).

**Comment by kubu4** [comment]
I've performed BLASTn and BLASTx.

_Ab initio_ gene prediction is now running with SNAP and Augustus.

**Comment by kubu4** [comment]
Just updating to say that Augustus gene prediction is still running...

**Comment by kubu4** [comment]
Augustus gene prediction completed late last week. It wasn't actually running this long - Augustus wasn't working properly and the GenSas people had to do some behind-the-scenes troubleshooting to get it straightened out.

Will report back when next step is complete.
