### ISSUE TITLE
Create modified version of Geoduck genome (v070)

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#572]
as per https://github.com/RobertsLab/resources/issues/259

create >10k and >30k version of geoduck genome.

**Comment by kubu4** [comment]
Done. Will add to Genomic Resources wiki tomorrow.

10k: http://owl.fish.washington.edu/halfshell/genomic-databank/Pgenerosa_v070_10k_plus.fasta

30k: http://owl.fish.washington.edu/halfshell/genomic-databank/Pgenerosa_v070_30k_plus.fasta

**Comment by sr320** [comment]
Lets rename 10k to v071
and 30k to v073

ftr
```
sr320$ fgrep -c ">" Pgenerosa_v070_30k_plus.fasta 
1350
sr320$ fgrep -c ">" Pgenerosa_v070_10k_plus.fasta 
14014
```

**Comment by kubu4** [comment]
Renamed:

http://owl.fish.washington.edu/halfshell/genomic-databank/Pgenerosa_v071.fasta

http://owl.fish.washington.edu/halfshell/genomic-databank/Pgenerosa_v0713.fasta

Will update wiki soon.

**Comment by sr320** [comment]
v073 not v0713

**Comment by sr320** [comment]
And maybe check the 30k plus....
seems like it is light on sequences

```
[sr320@mox2 geoduck]$ fgrep -c ">" Pgenerosa_v0713.fasta 
22
```

**Comment by kubu4** [comment]
Sorry, that's a copy/paste error. It's named properly. Here's the correct link:

http://owl.fish.washington.edu/halfshell/genomic-databank/Pgenerosa_v073.fasta

```
[samwhite@mox2 generosa_genomes]$ grep -c ">" Pgenerosa_v073.fasta
1350
```

**Comment by kubu4** [comment]
Wiki's been updated.
