### ISSUE TITLE
Jupyter: Trouble joining uniprot-SP-GO with skyline output 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#575]
Jupyter notebook link: https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/DIA_2015/Jupyter/GOterms-2015DIA0oysterseed.ipynb 

#### Trouble spot: the joining of the uniprot-SP-GO.sorted and sorted skyline output (_skyout-sort.tab). 

I have a skyline output file that contains data for 4 oysterseed samples (Oysterseed_01, Oysterseed_02, Oysterseed_13, and Oysterseed_14) including protein name, peptide sequence, mod. peptide sequence, and peak area (this tells abundance of protein in sample) 

I am trying to join with uniprot-SP-GO.sorted, and then GO-GOslim.sorted to get GO terms for the proteins expressed.

the _skyout-sort.tab file looks like this:     
![screen shot 2019-02-13 at 11 32 50 am](https://user-images.githubusercontent.com/14934314/52738353-52ed1080-2f83-11e9-96d0-b651d7199458.png)
 

**Sidenote: not sure why the file heads aren't showing up in the jupyter notebook link above, but they do show in my notebook in jupyter.**

**Comment by kubu4** [comment]
I don't see any ```join``` commands in your notebook. What have you tried and what is not working?

**Comment by grace-ac** [comment]
The ```join``` command is at the bottom of the notebook
I have tried what is shown above in the screenshot:
```
!join -t $'\t' \
_skyout-sort.tab \
uniprot-SP-GO.sorted \
| cut -f1,2,14 \
> _skyout-annot.tab
```
As well as: 

```
%%bash 
join -t $'\t' \
_skyout-sort.tab \
uniprot-SP-GO.sorted \
| cut -f1,2,14 \
> _skyout-annot.tab
```

---
And in terminal:   
``` join -t $'\t' _skyout-sort.tab uniprot-SP-GO.sorted | cut -f1,2,14 > _skyout-annot.tab```

#### All resulted in empty '_skyout-annot.tab' files

**Comment by kubu4** [comment]
Thanks! Sorry, missed it (obviously)!

**Comment by kubu4** [comment]
Quick update, I get two errors (see screencap):

1. Original join command throws an error about multiple separators.

2. The modified join command indicates that one of the files is not sorted. Files must be sorted before joining.


![image](https://user-images.githubusercontent.com/4514104/52749842-48d90b00-2f9f-11e9-91b3-6e6851455fa8.png)

**Comment by grace-ac** [comment]
does the following code sort? this is what i did to get '_skyout-sort.tab'
```
!awk -v OFS='\t' '{print $3, $1, $14, $17}' < _skyout2-sep.tab | sort \
> _skyout-sort.tab
```

**Comment by kubu4** [comment]
When you run it, is the file sorted?

**Comment by kubu4** [comment]
Oh, I see what you're asking. I didn't realize that was in the notebook already. Yes, that's sorts the file, but the sorting might have to be on the field(s) you're using to join.

**Comment by kubu4** [comment]
Wait, which field are you trying to join on?

Also, those two files don't appear to have matching content on which to perform a join. A join looks for matching data in a given field within two different files. Those two files don't appear to have matching data of any kind.

![image](https://user-images.githubusercontent.com/4514104/52750919-76738380-2fa2-11e9-9cf8-5dee60657afc.png)

**Comment by grace-ac** [comment]
Trying to join 'uniprot-SP-GO.sorted' with '_skyout-sort.tab' so that I can find the GO terms for the proteins expressed in the 2015 DIA oysterseed samples

I think that the first column in '_skyout-sort.tab' matches the first column in 'uniprot-SP-GO.sorted'. (?)

I know that the length of the modified peptide sequences in '_skyout-sort.tab' at the head of the file are much longer than those in the head of the first column of 'uniprot-SP-GO.sorted', but I figured that since both files were large, that maybe there is a range of lengths...?

I could be totally wrong about all of this!

**Comment by kubu4** [comment]
I think the first column in the ```_skyout-sort.tab``` file are peptide sequences.

**Comment by grace-ac** [comment]
they are! :)

**Comment by sr320** [comment]
Can your provide urls for the 3 files in question?

Thanks
steven

**Comment by kubu4** [comment]
```uniprot-SP-GO.sorted``` does not have peptides in the first column (note the numbers present - no numbers in peptide sequences).

**Comment by grace-ac** [comment]
@sr320 these? 
skyline output report: http://owl.fish.washington.edu/scaphapoda/grace/2015-Cgseed-DIA/post-EncyclopeDIA-Skyline/20181218-SkytoMSstats-report.csv

_skyout-sort.tab: https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/DIA_2015/data/_skyout-sort.tab 

uniprot GO annotation file: http://owl.fish.washington.edu/halfshell/bu-alanine-wd/17-07-20/uniprot-SP-GO.sorted

**Comment by grace-ac** [comment]
Main issue: I was trying to `join` two things that aren't the same (I thought the Uniprot-ID column was peptide sequences. didn't notice the numbers...)

The skyline output file and the Uniprot GO annotation file currently do not have any column that is possible to join on

closing issue and will make new one with new question
