### ISSUE TITLE
Crab Project Next Steps

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#577]
Based on discussion during last meeting, here's what I plan to have finished before next lab mtg:   

- Grab 4 crab hemolymph "pellets" and their corresponding supernatant (8 samples total)
- extract RNA using RNeasy Kit (working on protocols now, and will post issues with questions)
- run 1ul of each sample on Qubit with RNA High Sensitivity reagents

Will process supernatant samples (~1ml each) in 15ml falcon tubes     
Will use RNA carrier for both pellet and supernatant

Purpose of this is to see if there's RNA in the supernatant and that if by combing the pellet with the supernatant, we might get higher RNA yields for each crab sample.

-----
Other thoughts brought up in lab mtg based on [my figure of attempts](https://docs.google.com/drawings/d/1BduMHnANqwlB6ovVXZ-wbUyFahb95W5spx1yKjXn65s/edit?usp=drive_web&ouid=109180173241522173082):    
- Try Trizol LS Reagent protocol on supernatant
- Desalting

**Comment by grace-ac** [comment]
New plan:

Supernatant and pellet of 4 crabs

Today: Trizol LS on supernatant (separating out 250ul of super into 4 tubes)  

Later: RNeasy with QIA shredder and RNA carrier on the pellets that correspond to super

**Comment by grace-ac** [comment]
Post with today's TrizolLS on supernatant process and results: [here](https://grace-ac.github.io/TrizolLS-supernatant/)   

Qubit results --> all samples were "Out of Range: TOO LOW"

**Comment by shellytrigg** [comment]
@grace-ac here is the protocol for eluting DNA from the gDNA eliminator column. This is a protocol to be used in combination with the RNeasy protocol for checking presence of DNA in your samples (and trying to confirm whether there are cells or just seawater). This protocol is adapted from here: https://www.researchgate.net/post/Is_it_possible_to_get_DNA_from_gDNA_eliminator_spin_columns_Qiagen.

![screen shot 2019-02-15 at 11 51 00 am](https://user-images.githubusercontent.com/4720221/52881030-5f56a200-3118-11e9-9c3e-d7d0adf70009.png)

**Comment by grace-ac** [comment]
New plan based on results from today ([post](https://grace-ac.github.io/RNeasyKit-with-QIAshredder/)):    
Extract RNA from tube 516-2 in four volumes: 10ul, 50ul, 100ul, 150ul. If not enough for all four, I could just do 10,50,100. 

There should be RNA in this tube because there was detectable RNA on the Qubit from today extracted from 50ul.

**Comment by grace-ac** [comment]
Update: 
Extracted RNA from tube 516-2 at two volumes of the slurry. The ratio of all reagents was the same for both samples, except for the 70% ethanol, which was adjusted to match the actual flow-through volumes (more details will be in my post for today)

Qubit results
10ul     --> eluted at 14ul --> used 1ul on Qubit --> 4.6 ng/ul        
50ul     --> eluted at 14ul --> used 1ul on Qubit --> 14 ng/ul

**Comment by sr320** [comment]
Develop an RNA extraction plan and lets discuss.
