### ISSUE TITLE
RNeasy kit protocol questions

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#578]
Link to my protocol post: [here](https://grace-ac.github.io/Supe-RNeasy-protocol/)

- Q1: What amount of RNA carrier solution should I add to the ~1ml of supernatant samples? The handbook says for samples with <500 cells, you should add 5ul of a solution that is 4ng/ul. 

- Q2: What volumes of reagents and buffers should be added to the ~1ml of supernatant and for ~250ul of hemolymph pellet? The current volumes are those listed in the handbook. I'm not sure what sample volume those are based on. 

- Q3: Are the current volumes in the protocol sufficient for the crab hemolymph pellets? They are each approx. 250ul of slushy substance.

**Comment by sr320** [comment]
Are you doing this today around 12:30? If we can go through then

Thanks
steven

**Comment by grace-ac** [comment]
@sr320 yep! I’ll be up in the lab around 12:45
