### ISSUE TITLE
Selecting a geoduck genome for publication

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#579]
Write now I would say our draft genome is too big for analysis and publication.

v070 is 300k contigs and the size distribution is as follows 

```
1000:1999 	146882
2000:2999 	62246
3000:3999 	35461
4000:4999 	19983
5000:5999 	13055
6000:6999 	8557
7000:7999 	6081
8000:8999 	4299
9000:9999 	3071
10000:10999 	2388
11000:11999 	1813
12000:12999 	1429
13000:13999 	1219
14000:14999 	1036
15000:15999 	745
16000:16999 	632
17000:17999 	580
18000:18999 	447
19000:19999 	445
20000:20999 	348
21000:21999 	282
22000:22999 	225
23000:23999 	210
24000:24999 	187
25000:25999 	183
26000:26999 	169
27000:27999 	116
28000:28999 	114
29000:29999 	96
30000:30999 	136
31000:31999 	90
32000:32999 	90
33000:33999 	85
34000:34999 	73
35000:35999 	53
36000:36999 	65
37000:37999 	37
38000:38999 	49
39000:39999 	64
40000:40999 	53
41000:41999 	46
42000:42999 	38
43000:43999 	38
44000:44999 	31
45000:45999 	38
46000:46999 	35
47000:47999 	25
48000:48999 	27
49000:49999 	26
50000:50999 	16
51000:51999 	18
52000:52999 	14
53000:53999 	9
54000:54999 	22
55000:55999 	5
56000:56999 	15
57000:57999 	11
58000:58999 	9
59000:59999 	7
60000:60999 	2
61000:61999 	2
62000:62999 	6
63000:63999 	6
64000:64999 	4
65000:65999 	3
66000:66999 	1
67000:67999 	3
68000:68999 	3
69000:69999 	2
70000:70999 	4
71000:71999 	3
72000:72999 	1
73000:73999 	4
74000:74999 	2
75000:75999 	5
76000:76999 	2
77000:77999 	1
78000:78999 	6
79000:79999 	2
80000:80999 	0
81000:81999 	0
82000:82999 	0
83000:83999 	2
84000:84999 	2
85000:85999 	0
86000:86999 	1
87000:87999 	0
88000:88999 	1
89000:89999 	1
90000:90999 	1
91000:91999 	0
92000:92999 	1
93000:93999 	0
94000:94999 	0
95000:95999 	0
96000:96999 	1
97000:97999 	1
98000:98999 	0
99000:99999 	0
100000:100999 	0
101000:101999 	0
102000:102999 	0
103000:103999 	0
104000:104999 	1
105000:105999 	1
```

Sam has made a few reduced version by selecting a threshold 
and here are there contig numbers

```
sr320$ fgrep -c ">" Pgenerosa_v070_30k_plus.fasta 
1350
sr320$ fgrep -c ">" Pgenerosa_v070_10k_plus.fasta 
14014
```
I think we might want to make various versions and do a comparison on mapping BS and WG data back to it to pick an ideal one?

@hputnam ?

**Comment by shellytrigg** [comment]
I can go ahead and get a mox job submitted for aligning a few of those Geoduck-juvenile-OA-exposure libraries to Pgenerosa_v070_30k_plus.fasta and Pgenerosa_v070_10k_plus.fasta. Then compare to the alignments I did previously.

**Comment by shellytrigg** [comment]
I submitted jobs on mox for building bismark genomes with Pgenerosa_v070_30k_plus.fasta and Pgenerosa_v070_10k_plus.fasta, and for bismark alignment of samples EPI-111, 113, 119, and 120. I will compare the results to my previous analysis https://github.com/shellytrigg/Shelly_Pgenerosa/blob/master/analyses/BismarkAlignments/20181101/bismark_summary_report.html

**Comment by shellytrigg** [comment]
here are the alignment comparisons between the different genome versions (https://github.com/shellytrigg/Shelly_Pgenerosa/blob/master/analyses/CompareGenomeVersions/CompareGenomeVersions.md). Still need to calculate coverage

**Comment by sr320** [comment]
will also examine blast output see https://github.com/RobertsLab/resources/issues/650

**Comment by sr320** [comment]
lets go with 74
