### ISSUE TITLE
Onboarding Page Feedback: Resume Instructions for Prospective Students

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#584]
(creating new issues for feedback on the main onboarding page as asked. original issue [here](https://github.com/RobertsLab/resources/issues/561))

* What should people include in a resume (thinking about those that may not have as much guidance in this process)?

**Comment by sr320** [comment]
Where would be a good place to indicate this?

**Comment by yaaminiv** [comment]
Maybe in this document under "Resume"? https://docs.google.com/forms/d/e/1FAIpQLSckh7GPpXTHS3AQNLS2cE2WqrCsHRRKmLSdx217G25h69-4bg/viewform
