### ISSUE TITLE
Onboarding Page Feedback: Student Expectations

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#585]
(creating new issues for feedback on the main onboarding page as asked. original issue [here](https://github.com/RobertsLab/resources/issues/561))

* Split the second half "Expectations of Students" into another section (...Reseach Methods maybe)? Thematically it seems different (talks about day-to-day operations in the lab as opposed to things you expect from us)

**Comment by sr320** [comment]
done
