### ISSUE TITLE
Methods for DNA Extraction for Lotterhos Sperm Samples

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#587]
I want to extract DNA from [Lotterhos sperm samples](https://docs.google.com/spreadsheets/d/1_ejhH2xx81WN8EvMkEpqmc3zAGlrGOrAl5RWgL7ShJ8/edit#gid=0) for eventual WGBS. The sperm is diluted in seawater and flash frozen, but I should be able to centrifuge the samples, remove the seawater, and retain the sperm pellet.

Since my sperm sample isn't a whole tissue piece (ex. gonad, mantle), can I still use the [E.Z.N.A. Mollusc Kit](https://github.com/RobertsLab/resources/blob/master/protocols/Commercial_Protocols/Omega_Mollusc-DNA-Kit-Combo-May-2013-D3373.pdf)? Reading through Claire's work, I saw she used [DNAzol](https://github.com/RobertsLab/resources/blob/master/protocols/Commercial_Protocols/MRC_DNAzol_GENOMIC_DNA_ISOLATION_REAGENT.pdf) for sperm samples. I don't see DNAzol in the Roberts Lab Inventory, but I do see the [DNeasy Kit](https://github.com/RobertsLab/resources/blob/master/protocols/Commercial_Protocols/Qiagen_DNeasy_Blood_and_Tissue.pdf). Which of these options would be best for sperm samples?

**Comment by kubu4** [comment]
Personally, I'd give the E.Z.N.A. Mollusc kit a shot. Remember, you'll need dry ice and liquid nitrogen. Use the dry ice to keep the sperm sample frozen and then dig the frozen sperm sample out of the tube and pulverize in liquid nitrogen with ceramic mortar/pestle. Then, proceed with the Mollusc kit. I'd also follow their overnight incubation at 37<sup>o</sup>C during the initial lysis. 

---

>  I don't see DNAzol in the Roberts Lab Inventory

This is a chemical, so is listed in the UW MyChem system, in the FTR 209 inventory (i.e. look in the chemicals cabinet in FTR 209).

**Comment by yaaminiv** [comment]
To clarify:

- Centrifuge samples and remove seawater
- Freeze sample in dry ice
- Pulverize in liquid nitrogen
- Follow Mollusc kit + overnight incubation for initial lysis

Where can I get dry ice and liquid nitrogen?

**Comment by yaaminiv** [comment]
For the overnight incubation: Can I incubate samples on a heat block at 37ºC?

**Comment by kubu4** [comment]
- Do not thaw (i.e. do not centrifuge and remove seawater).
- Keep sample frozen by keeping on dry ice until ready for liquid nitrogen (LN2)
- Pulverize "in" liquid nitrogen (generally, cool the mortar by filling with LN2; allow LN2 to boil off; transfer sample to mortar (you may have to briefly warm the sample in your hand to facilitate getting the sample out of the tube) and pulverize with LN2-cooled pestle; transfer powder to tube using LN2-cooled spatula)

Dry ice is definitely available at Biochemistry Stores. LN2 is available in Chemistry Stores. They likely have dry ice as well. For LN2, you'll need to bring the dewar, _not_ the dry shipper. The dewar is large and likely by my bench ATM. Dewar capacity is 10 liters, but you won't need that much - I'd say five liters at the most.

You'll also need a budget number when purchasing both items.

**Comment by kubu4** [comment]
> For the overnight incubation: Can I incubate samples on a heat block at 37ºC?

Yes, that's exactly what you'd want to do.

**Comment by yaaminiv** [comment]
@kubu4: 
- We have a mortar/pestle then? I don't need to use the blue disposable pestles?
- In-between samples, can I clean the mortar/pestle/spatula with ethanol and rinse with DI water? Or should I use a bleach solution?

@sr320:
- What budget number can I use to purchase LN2 and dry ice?

**Comment by kubu4** [comment]
Yes, we have ceramic mortar/pestles (n = 8 each). They're likely in the drying rack. You cannot use the plastic pestles with liquid nitrogen.

Mortar/pestles should be cleaned with a 10% bleach solution after use. If you need more than eight, then after bleaching/rinsing, then you can dry them quickly by using 95% ethanol. As long as the spatula remains very cold, you can just wipe any residual powder off with a Kim wipe or paper towel. If powder starts to thaw on spatula, wipe thoroughly with a Kim wipe or paper towel that's been wetted with a 10% bleach solution and then dry the spatula with a Kim wipe or paper towel.

**Comment by sr320** [comment]
61-1553

@yaaminiv Note it might be best to do this when someone else is around that has done it before. @laurahspencer will be in tomorrow...

**Comment by yaaminiv** [comment]
@kubu4 Can I get LN2 a few days before I need it (if I get it Friday can I still use it on Monday)?

**Comment by kubu4** [comment]
Yep. The dewar will keep LN2 for a little while. If going to let sit over weekend, I'd go ahead and fill it with 10 liters (dewar capacity) just to be sure you'll have enough for Monday (you will definitely still have more than enough).

**Comment by sr320** [comment]
Just a heads up Alanna / @laurahspencer will be using LN2 Friday for DNA extractions

**Comment by laurahspencer** [comment]
We are now using LN2 on Thursday

**Comment by yaaminiv** [comment]
[Lab notebook entry](https://yaaminiv.github.io/Sperm-DNA-Extractions-Part2/)

I extracted DNA from sperm samples today with the E.Z.N.A kit. My hope is that I can use these DNA samples for WGBS. I just want to confirm the following yields are adequate and I can extract the rest of my 9 samples using this kit:

| **Sample** | **Concentration (ng/µL)** | **DNA Yield (ng in 45 µL total)** |
|:-----------:|:--------------------------:|:---------------------------------:|
|  L18A0012s |                    125                   |                          5625                       |
|  L18A0031s |                  9.84                   |                         442.8                       |

**Comment by kubu4** [comment]
Consult the methylation decision tree. :)

**Comment by kubu4** [comment]
Anyway, proceed with extracting the rest.

**Comment by yaaminiv** [comment]
Totally forgot I made that! Looks like I need 50-100 ng input minimum for Illumina, so I should be set.
