### ISSUE TITLE
Create Genome Stat Table

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#588]
Using 
![img_0821 1](https://user-images.githubusercontent.com/4442039/53041446-dfdb1280-3438-11e9-9159-0d5238248f1e.jpg)

as a model.

Create a comparable table with both Crassostrea species and Geoduck and Oly

**Comment by kubu4** [comment]
To clarify, what do you want as the output? A spreadsheet and/or a image file?

Do you want me to apply version numbers to the Oly and Pgen genomes?

**Comment by sr320** [comment]
Spreadsheet is fine - yes please apply version numbers
Thanks

**Comment by kubu4** [comment]
Google Sheet:

https://docs.google.com/spreadsheets/d/1Wvf62vwHd2HuJm2fQAYxjRwn8oKzUkmI75GkjC7lWiY/edit?usp=sharing

I'll add this info to the Genomic Resources wiki, too.

Recommendations on estimating genome sizes? I was going to run a program or two (e.g. Jellyfish) to perform kmer estimation on genome sizes, but, technically, we have genome size estimations (via kmer calculations) from BGI, so I could just use those.

**Comment by sr320** [comment]
Just use BGI..

thanks
Steven

**Comment by sr320** [comment]
Can you double check n50?
Seems like ours should be lower than Cv?

thanks
Steven

**Comment by kubu4** [comment]
Good catch, sorry! Fixed!

Added genome sizes from BGI reports.
