### ISSUE TITLE
Develop taxa comparison of methylation via Bismark

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#589]
Concatenate all BS reads for each species (Cv, Cg, Pg, Ol) then randomly sample set number of reads. 
Align to the respective genome using Bismark.

for talk next week. Thinking some number of reads that could "easily" map leveraging coenv node etc. Maybe start conservatively.

**Comment by kubu4** [comment]
Here's mapping efficiencies of all except geoduck (this will complete late tonight, I think - will post here when finished).

Notebook posts are in the works, but the results below are untrimmed, R1 reads only, for each species (paired-end Bismark analysis didn't yield any results for mapping efficincies - like that part of the report is just empty).

---

#### C.gigas

| Reads Subset | Mapping Efficiency (%) |
|--------------|------------------------|
| 100000       | 55.0                   |
| 500000       | 55.1                   |
| 1000000      | 55.1                   |
| 2000000      | 55.0                   |
| 5000000      | 54.9                   |
| 10000000     | 54.2                   |

---

#### C.virginica

| Reads Subset | Mapping Efficiency (%) |
|--------------|------------------------|
| 100000       | 18.5                   |
| 500000       | 18.6                   |
| 1000000      | 19.2                   |
| 2000000      | 19.5                   |
| 5000000      | 18.6                   |
| 10000000     | 16.1                   |

---

#### O.lurida

| Reads Subset | Mapping Efficiency (%) |
|--------------|------------------------|
| 100000       | 54.2                   |
| 500000       | 54.4                   |
| 1000000      | 54.5                   |
| 2000000      | 54,4                   |
| 5000000      | 54.3                   |
| 10000000     | 53.8                   |

**Comment by kubu4** [comment]
#### P.generosa

| Genome | Reads Subset | Mapping Efficiency (%) |
|--------|--------------|------------------------|
| v070   | 100000       | 56.3                   |
| v070   | 500000       | 56.1                   |
| v070   | 1000000      | 56.1                   |
| v070   | 2000000      | 56.2                   |
| v070   | 5000000      | 56.2                   |
| v070   | 10000000     | 56.2                   |
| v071   | 100000       | 54.1                   |
| v071   | 500000       | 53.8                   |
| v071   | 1000000      | 53.9                   |
| v071   | 2000000      | 53.9                   |
| v071   | 5000000      | 54.0                   |
| v071   | 10000000     | 53.9                   |
| v073   | 100000       | 49.8                   |
| v073   | 500000       | 49.7                   |
| v073   | 1000000      | 49.7                   |
| v073   | 2000000      | 49.7                   |

**Comment by sr320** [comment]
Can you produce a single DNA methylation gff for each species?

thanks
Steven

**Comment by kubu4** [comment]
Would a bedgraph suffice?

**Comment by sr320** [comment]
Yes

thanks
Steven

**Comment by kubu4** [comment]
Bedgraph files (gzipped).
---

#### C.gigas

http://gannet.fish.washington.edu/Atumefaciens/20190222_cgigas_se_bismark/subset_10000000/cgig_bsseq_all_R1_bismark_bt2.deduplicated.bedGraph.gz

---

#### C.virginica

http://gannet.fish.washington.edu/Atumefaciens/20190222_cvirginica_se_bismark/subset_10000000/cvir_bsseq_all_R1_bismark_bt2.deduplicated.bedGraph.gz

---

#### O.lurida

http://gannet.fish.washington.edu/Atumefaciens/20190224_olurida_se_bismark/subset_10000000/olur_bsseq_all_R1_bismark_bt2.deduplicated.bedGraph.gz

---

#### P.generosa

- v070: http://gannet.fish.washington.edu/Atumefaciens/20190224_pgenerosa_rrbs_se_bismark/subset_Pgenerosa_v070_10000000/pgen_bsseq_all_R1_bismark_bt2.deduplicated.bedGraph.gz

- v071: http://gannet.fish.washington.edu/Atumefaciens/20190224_pgenerosa_rrbs_se_bismark/subset_Pgenerosa_v071_10000000/pgen_bsseq_all_R1_bismark_bt2.deduplicated.bedGraph.gz

- v073: http://gannet.fish.washington.edu/Atumefaciens/20190224_pgenerosa_rrbs_se_bismark/subset_Pgenerosa_v073_10000000/pgen_bsseq_all_R1_bismark_bt2.deduplicated.bedGraph.gz
