### ISSUE TITLE
Oysterseed DIA: How can I get GO terms from my Skyline output?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#590]
Skyline output file: http://owl.fish.washington.edu/scaphapoda/grace/2015-Cgseed-DIA/post-EncyclopeDIA-Skyline/20181218-SkytoMSstats-report.csv     

This file currently does not have any column that matches any column in the [uniprot-SP-GO.sorted](http://owl.fish.washington.edu/halfshell/bu-alanine-wd/17-07-20/uniprot-SP-GO.sorted) file

Column names of skyline output (useful columns in **bold**):       
**Protein Name**      
**Peptide Sequence**       
**Peptide Modified Sequence**           
Precursor Charge         
Precursor Mz           
Fragment Ion        
Product Charge          
Product Mz          
Isotope Label Type          
Condition           
BioReplicate          
File Name            
**Area** (peak area in Skyline: tells rel. abundance of peptide)         
Standard Type         
Truncated           
Detection Q Value       
**Replicate Name** (tells which sample the data comes from. Oysterseed_01, Oysterseed_02, Osyterseed_13, or Oysterseed_14)

**Comment by sr320** [comment]
Why do you want GO terms?
Big Picture?

If that is where you want to go step 1 is you need a blastp output that takes Chopy proteins and compares to UniProt SP - Do you have that? I am sure we have one somewhere.

**Comment by grace-ac** [comment]
ah, yes. I understand how I'd do that now. 

Basically, *I'm trying to figure out what all is interesting and what steps I should take to get the project finished.* 

I was thinking it might be nice to know what the GO terms are. And maybe make some plots comparing the abundance of each GO term between 23C and 29C... 

Maybe it's a waste of time since I already have some results from MS stats. According to the volcano plot comparing the 23C and 29C, there's just the one protein that's down regulated, while all others are denoted as having "no regulation".  I just don't know the GO term for the one protein that's down regulated. 

So far for this project, my results from MS stats are:    
[volcano plot](https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/DIA_2015/analyses/VolcanoPlot.pdf)     
[Profile plots](https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/DIA_2015/analyses/ProfilePlot.pdf)     
[profile plots with summarization](https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/DIA_2015/analyses/ProfilePlot_wSummarization.pdf)         
[comparison plots](https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/DIA_2015/analyses/ComparisonPlot.pdf)      

[R script using MS stats](https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/DIA_2015/R/Skyline-to-MSstats-format-and-plots.R) to get results listed above
