### ISSUE TITLE
Determine common track(s) for 4 species

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#592]
to compare methylation can a gene track etc be identified for all four species? What are those tracks?

**Comment by kubu4** [comment]
mRNA tracks for each:

#### C.gigas:

- http://owl.fish.washington.edu/halfshell/genomic-databank/Crassostrea_gigas.oyster_v9.40_mRNA.gff3

---

#### C.virginica:

- http://eagle.fish.washington.edu/Cvirg_tracks/C_virginica-3.0_Gnomon_mRNA.gff3

---


#### O.lurida:

- http://owl.fish.washington.edu/halfshell/genomic-databank/Olurida_v081.mRNA.gff

---


#### P.generosa:

- http://owl.fish.washington.edu/halfshell/genomic-databank/Pgenerosa_v071_snap02.renamed.mRNA.gff
