### ISSUE TITLE
Determine cpG o/e for 91 fasta files

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#593]
Using http://htmlpreview.github.io/?https://github.com/hputnam/EastOyEpi/blob/master/02-Cpg-test.html

as a basis..

Need ratios for all files at http://gannet.fish.washington.edu/seashell/bu-serine-wd/19-01-08/ {GENE}.

(all files in the directory that have `GENE` in name

**Comment by kubu4** [comment]
This is successfully running. Will post URL to data and Jupyter notebook when I get home.

**Comment by kubu4** [comment]
Sorry, this didn't work. Received an error about a limit on the number of fields that ```awk``` can process. The solution is to use (need to install, too) ```gawk```. I've done that and have re-started the loop using ```gawk```. Hopefully it'll be finished soon.

**Comment by kubu4** [comment]
OK, finished!

http://gannet.fish.washington.edu/Atumefaciens/20190225_cpg_oe/

There's a subdirectory that corresponds to each original FastA file and the subdirectory contains the output files that are shown in your example above, so you'll want the ```ID_CpG``` file in each subdirectory (e.g.):

http://gannet.fish.washington.edu/Atumefaciens/20190225_cpg_oe/Combined.SNP.TRSdp5g95FnDNAmaf05.sorted.ANACfill.CLP_1_GENE_analysis/ID_CpG

**Comment by kubu4** [comment]
And link to Jupyter Notebook (scroll down to the bottom to review the functional code):

https://github.com/RobertsLab/code/blob/master/notebooks/sam/20190225_swoose_CpG_OE.ipynb
