### ISSUE TITLE
Merge CpG O/E datasets

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#596]
Yesterday @kubu4 created 91 files with CpG o/e values for 91 samples.
Please merge these into a single file / spreadsheet. The data is in `ID_CpG` file and the label would need to include directory. For example below, the data label could be `CLP_1` 

>http://gannet.fish.washington.edu/Atumefaciens/20190225_cpg_oe/

>There's a subdirectory that corresponds to each original FastA file and the subdirectory contains the output files that are shown in your example above, so you'll want the `ID_CpG` file in each subdirectory (e.g.):

>http://gannet.fish.washington.edu/Atumefaciens/20190225_cpg_oe/Combined.SNP.TRSdp5g95FnDNAmaf05.sorted.ANACfill.CLP_1_GENE_analysis/ID_CpG

**Comment by kaitlynrm** [comment]
[Here is the merged file!](https://github.com/kaitlynrm/Miscellaneous-Tasks/raw/master/CpG/CpG-oe-merged-analysis.txt) I did it in R using [this script](https://raw.githubusercontent.com/kaitlynrm/Miscellaneous-Tasks/master/CpG/CpG-oe-merge.R).
