### ISSUE TITLE
File doesn't appear to be tab delimited after pasting

### ISSUE THREAD

**Issue by kaitlynrm** [RobertsLab/resources#598]
I'm trying to merge the tables in #596 . I did the following:

Add headers: 'filename' as $2 and 'rows' as $1
`for d in ./*/; do cd "$d"; sed "1irows\t${d}" ID_CpG > colnames; head colnames; cd ../; done`

Paste second column of all files into master sheet containing column 1
`awk '{printf$1}' Combined.SNP.TRSdp5g95FnDNAmaf05.sorted.ANACfill.CLP_1_GENE_analysis/colnames > master
for d in ./*/; do cd "$d"; awk '{printf$2}' colnames > coltwo; paste ../master coltwo > ../master; cd ../; done`

When I look at `colnames` and `coltwo`, the columns I want are there, however after trying to paste them to the master file it seems like the file becomes disorganized (I checked with `head -n 1 master`). How do I make sure they stay tab delimited when I paste the columns into `master`?

**Comment by kubu4** [comment]
Can you please post a screenshot and/or the output file (the latter would be ideal)?

**Comment by kaitlynrm** [comment]
[master.txt](https://github.com/RobertsLab/resources/files/2912013/master.txt)
 
Sure! It didn't originally have an extension- I renamed it with .txt in the gui file explorer so I could quickly upload it here. Hope that is alright...

**Comment by kaitlynrm** [comment]
There should be 92 columns, with the first column titled rows and the other 91 titled with the long file folder name. This is what the `head` command shows
![head](https://user-images.githubusercontent.com/26392677/53518423-daf40f80-3a85-11e9-94a1-ef96ee77adb3.JPG)

**Comment by kubu4** [comment]
You should be using ```{print}``` instead of ```{printf}```. Doing this will resolve the layout issues. 

However, the ```paste``` command still doesn't work properly - investigating this now.

**Comment by kaitlynrm** [comment]
Is it because something is happening when trying to overwrite `master` when doing `paste`?

**Comment by kubu4** [comment]
Yes, that is the issue.

**Comment by kaitlynrm** [comment]
I read that the file you append something to is created before the function is run. If that is the case, then `master` would only end up with one `$2` from the last subdirectory in the directory list. I couldn't tell in the file how many columns were in `master` because of the layout, but I can see that the IDs (e.g. column 1) are not there.

**Comment by kubu4** [comment]
For each round of the loop, you essentially have to write the output of ```paste``` to a temporary file. Then, rename the temporary file to ```master```. 

As it happens, ```bash``` has a command specifically for creating temporary files: ```mktemp```

To use this, add this line to the beginning of your script:

```tmp=$(mktemp)```

This saves the output of the ```mktemp``` command to the variable called ```tmp```.

To use in your loop:

```
for d in ./*/; do cd "$d"; awk '{print$2}' colnames > coltwo; paste ../master coltwo > ../${tmp} && mv ../${tmp} ../master; cd ../; done
```

**Comment by kaitlynrm** [comment]
[master.txt](https://github.com/RobertsLab/resources/files/2912397/master.txt)

This is the new file made with the above code. I looked at the first column and it seems to only contain the IDs, but I'm having trouble being able to tell if everything is correctly aligned still using the `head` command.

**Comment by kaitlynrm** [comment]
Actually, it looks like the columns are still not being pasted together correctly.

**Comment by kaitlynrm** [comment]
Sorry, I forgot to change the first line to `print` from `printf`. However, the code still didn't work- the format is correct but nothing was appending to `master`, e.g. `master` only contains the `rows` column after running the last `for` loop.

**Comment by kubu4** [comment]
Yeah, that for loop doesn't work. You should get a bunch of the following errors:

```bash: ..//tmp/tmp.FcUMfeDLh4: No such file or directory```

To fix that error, the loop actually needs to be this (sorry):

```for d in ./*/; do cd "$d"; awk '{print$2}' colnames > coltwo; paste ../master coltwo > ${tmp} && mv ${tmp} ../master; cd ../; done```

However, this doesn't produce the correct results, either.

**Comment by kaitlynrm** [comment]
I got `-bash: ../: Is a directory` but no explicit error saying the above- sorry I should have reported that.

**Comment by kaitlynrm** [comment]
Still not sure what to do in Bash, but this works in R!

```
path <- "Documents/robertslab/gannet.fish.washington.edu/Atumefaciens/20190225_cpg_oe" #defining master directory
folder.list <- dir(path) #making list of subdirectories w/in master directory

d <- read.table(paste(path,folder.list[1], "ID_CpG",sep="/"), sep="\t", stringsAsFactors=FALSE) #reading in ID_CpG file in first subdirectory
colnames(d) <- c("ID", "CL_1") #renaming columns of file just loaded in 
for(i in 2:length(folder.list)){
  dtemp <- read.table(paste(path,folder.list[i], "ID_CpG",sep="/"), sep="\t", stringsAsFactors=FALSE) #starting loop for ID_CpG files in all subdirectories
  colnames(dtemp)[1] <- "ID" #rename col 1 
  colnames(dtemp)[2] <- sub(".*ANACfill.","",folder.list[i]) #sub all characters before (and including) ANACfill. with NOTHING ("") in folder (i)
  colnames(dtemp)[2] <- sub("_GENE_analysis","",colnames(dtemp)[2]) #sub GENE... with nothing in folder (i)
  d <- merge(d,dtemp, by = "ID") #merge file in subdirectory with previously created file
}
```

**Comment by kubu4** [comment]
Nice work!

Here's a bash solution, if you're curious:

```
#!/bin/bash

## Script to append sample-specific headers to each ID_CpG
## file and join all ID_CpG files.

## Run file from within this directory.

# Temp file placeholder
tmp=$(mktemp)

# Create array of subdirectories.
array=(*/)

# Create column headers for ID_CpG files using sample name from directory name.
for file in ${array[@]}
do
  gene=$(echo ${file} | awk -F\[._] '{print $6"_"$7}')
  sed "1iID\t${gene}" ${file}ID_CpG > ${file}ID_CpG_labelled
done

# Create initial file for joining
cp ${array[0]}ID_CpG_labelled ID_CpG_labelled_all

# Loop through array and performs joins.
for file in ${array[@]:1}
do
  join \
  --nocheck-order \
  ID_CpG_labelled_all ${file}ID_CpG_labelled \
  | column -t \
  > ${tmp} \
  && mv ${tmp} ID_CpG_labelled_all
done

```

**Comment by kaitlynrm** [comment]
Awesome, thank you!!
