### ISSUE TITLE
Reset OWL password because I forgot mine

### ISSUE THREAD

**Issue by kaitlynrm** [RobertsLab/resources#599]
I seem to have forgotten my OWL password and am trying to upload some histology images. The email for OWL should be kaitrm@uw.edu (but may be mitchellrkaitlyn@gmail.com). So sorry! I haven't used OWL much lately...

**Comment by kubu4** [comment]
Can you please post your IP address (enter "What's my IP?" in to Google)?

If you've failed to log in too many times, your IP address will be blocked.

**Comment by kubu4** [comment]
Your email is listed as ```krmitch7@uw.edu```.

**Comment by kaitlynrm** [comment]
This is my current IP address: 205.175.106.221 

I run a VPN with multiple connectors, and I was also on UW wifi when I attempted though so it shouldn't be a problem. That's my IP without the VPN though and I think that one got blocked (I switched it a lot with my VPN).

**Comment by kaitlynrm** [comment]
Okay, that makes more sense why I couldn't get on. That is my old student email that I don't have access too anymore. Will I be able to log in with that or should we set it up to a new email I have access to?

**Comment by kubu4** [comment]
You can use that email address, as it's just used for login; doesn't need
to be active. However, we can change it if you'd like.

**Comment by kubu4** [comment]
Sorry for delay! Check slack for updated login info.
