### ISSUE TITLE
Getting into Nanopore

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#6]
_From @sr320 on May 19, 2017 14:7_

What would it take? Might be good avenue for k-12 outreach

_Copied from original issue: sr320/LabDocs#622_

**Comment by kubu4** [comment]
_From @seanb80 on May 19, 2017 15:16_

Looks like the $1000.00 starter kit gets you:

- The device
- Two Flow cells, good for 48 hours of sequencing time or ~7Gb data.
- One Sequencing kit, good for 6 libraries 
- One Wash kit, for reusing the flow cells.

Consumable wise, each replacement flow cell is $900.00, Sequencing kits are between $500.00-$600.00 for 6 or 12 samples, depending on kit. You can also buy bundles of all consumables but they start at $4400.00

Compute wise, it looks like you need a fairly hefty laptop for RT data acquisition and base calling, they call for a quad core i7, 16gb RAM, and a 1Tb SSD to be able to keep up with data rate. 

They've got accuracy up to ~90%, and can produce some pretty long reads (40kb), so it looks like it would be a neat thing to play with!

**Comment by sr320** [comment]
Rick bought one, will use that and decide
