### ISSUE TITLE
Trouble joining files

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#60]
I'm learning about BLAST, etc. 

This issue arose today with Steven: last step wasn't able to complete. 

![screen shot 2017-09-18 at 3 01 15 pm](https://user-images.githubusercontent.com/14934314/30566898-c3151802-9c82-11e7-9771-a0a420689dcd.png)

**Comment by kubu4** [comment]
Link to your Jupyter notebook?

Oddly enough, I was just talking to @sr320 about problems/difficulties with joins at lunch today...

**Comment by grace-ac** [comment]
Notebook: https://github.com/grace-ac/Practicing-with-Blast/blob/master/notebooks/blast-to-slim.ipynb

**Comment by kubu4** [comment]
Did you try any troubleshooting steps?

If yes, what were they (I don't want to provide redundant, unsuccessful solutions)?

**Comment by grace-ac** [comment]
Only step 27 to show that that part was working...

I honestly don't fully understand what I'm talking about, so I don't know
how to do any troubleshooting!

**Comment by kubu4** [comment]
So, you did or did not do any troubleshooting? Your initial post suggested that @sr320 was with you when encountered the problem. Did he have you try anything to figure out the issue?

Can you please post links to both of the files you tried joining in Input 27?

I tested your command on small test files (using slightly modified data from your sorted files) on Ubuntu and OS X and things work fine. Try it out and see if it works for you. Here are the two files:

GOslim.sorted
```
GO:0000001	mitochondrion inheritance	cell organization and biogenesisP
GO:0000002	mitochondrial genome maintenance	cell organization and biogenesis	P
GO:0000003	reproduction	other biological processes	P
GO:0000006	high affinity zinc uptake transmembrane transporter activity	transporter activity	F
GO:0000007	low-affinity zinc ion transmembrane transporter activity	transporter activity	F
GO:0000009	"alpha-1,6-mannosyltransferase activity"	other molecular function	F
GO:0000010	trans-hexaprenyltranstransferase activity	other molecular function	F
GO:0000011	vacuole inheritance	cell organization and biogenesis	P
GO:0000012	single strand break repair	DNA metabolism	P
GO:0000012	single strand break repair	stress response	P
```

GOunfolded.sorted
```
Q9TTS3	CHOYP_ACACA.3.7	GO:0000009
Q9TTS3	CHOYP_ACACA.6.7	GO:0000010
Q9TTS3	CHOYP_ACACA.7.7	GO:0000011
P09917	CHOYP_LOC584481.1.10	GO:0000012
P15428	CHOYP_PGDH.5.5	GO:0000012
C8VQ62	CHOYP_THIKA.1.1	GO:2001307
C8VQ62	CHOYP_contig_020217	GO:2001307
Q4WRY5	CHOYP_contig_040462	GO:2001310
Q8BP40	CHOYP_LOC756773.1.1	GO:2001311
Q9NPH0	CHOYP_contig_031590	GO:2001312
```

I ran the following command to join them:

```
join -1 3 -2 1 -t $'\t' GOunfolded.sorted GOslim.sorted
```

**Comment by grace-ac** [comment]
The only troubleshooting was when @sr320 did Input 27, in order to show something... I don't really know what it means. He did this right before he left for the day, so that's the extent of the troubleshooting. 

I don't really understand any of this. I tried doing your command, but I doubt I did it right. https://github.com/grace-ac/Practicing-with-Blast/blob/master/notebooks/blast-to-slim.ipynb

This is the notebook that was used as the template: https://github.com/sr320/nb-2017/blob/master/misc/10-blast-2-slim.ipynb

**Comment by kubu4** [comment]
Can you please post links to both of the files you tried joining in Input 27?

Also, the command I provided above needs the two samples files that I posted above. 

As far as the error that showed up in the notebook when you tried to run the example command I posted, you need an "!" before the word ```join```. That will resolve the syntax error you received.

**Comment by grace-ac** [comment]
Yes, I'm still trying to figure out where those files are/how to get them.

**Comment by kubu4** [comment]
Doh! Never mind! Inputs 4 & 5 have the links to the files. I'll grab 'em and give the command and whirl on my end and see what happens. Sorry!

**Comment by kubu4** [comment]
One thing that hasn't been tried/considered is that there is nothing to join - meaning there are no shared GO terms. However, I would think this would be impossible, due to the fact that you're joining from a file that contains a subset of GO terms to a "master" file, which should have ALL possible GO terms.

The fact that ```join``` doesn't generate an output or an error message of any kind suggests that nothing is joining.

Now that I've typed this, there are actually two things that should be tried:

1. Use the following two commands (in the order I've listed them) on your two files:

```
awk '{ print $1 }' GO-GOslim.sorted > GO_only_GOslim.sorted
```

```
grep -f --only-matching GO_only_GOslim.sorted _blast-GO-unfolded.sorted
```

These commands use ```awk``` to print just the GO terms (which are present in column 1 -  ```print $1```) and saves them to a new file. Then, we use ```grep``` to search for matching patterns in the two files (that's the ```-f``` flag) and output only matching terms.

This will tell us if the ```_blast-GO-unfolded.sorted``` subset has any GO terms that are present in the master file (there should be!).

2. Try different iterations of the ```join``` columns. Maybe we're viewing the columns differently than how ```join``` sees them? Seems weird, but worth a shot. Modify your ```join``` command like this:

```
join -1 1 -2 1 -t $'\t' \
_blast-GO-unfolded.sorted \
GO-GOslim.sorted | head
```

AND

```
join -1 2 -2 1 -t $'\t' \
_blast-GO-unfolded.sorted \
GO-GOslim.sorted | head
```

AND

```
join -1 4 -2 1 -t $'\t' \
_blast-GO-unfolded.sorted \
GO-GOslim.sorted | head
```

**Comment by grace-ac** [comment]
I didn't do any of the things you just commented about, but re-ran some of the Inputs after you changed the script yesterday. 

It looks like the change in script was the answer...? 
![screen shot 2017-09-21 at 12 22 07 pm](https://user-images.githubusercontent.com/14934314/30714456-b1851140-9ec7-11e7-9d36-f0e63e2dc649.png)

**Comment by kubu4** [comment]
Hey, great! After playing around with some small test files, I didn't think that change to the script was going to work.

I'll update the script with the fix.
