### ISSUE TITLE
Lotterhos C. virginica sperm samples for WGBS

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#600]
I finished extracting DNA from Lotterhos sperm samples (results found [here](https://yaaminiv.github.io/Sperm-DNA-Extractions-Part2/) and [here](https://yaaminiv.github.io/Sperm-DNA-Extractions-Part4/)). @sr320 mentioned that we should send these out for WGBS. What do I need to do to make that happen?

**Comment by sr320** [comment]
How many samples? looks like 9 - what are treatment conditions?

Presuming sequencing of 8 samples, (using your tree) determine the cost of MBD-BS and cost of WGBS.

**Comment by yaaminiv** [comment]
11 samples: 4 high pCO<sub>2</sub>, 7 ambient pCO<sub>2</sub>. Revised concentrations can be found [here](https://yaaminiv.github.io/Sperm-Extractions-Part5/).

Assuming 8 samples are sequenced (4 of each treatment), WGBS would be $32000. 

We already have MBD kits right? Illumina library construction would be $1360/25 preparations (we would need to purchase this if we do not have the kit). I actually couldn't find a number for Illumina sequencing online, so I don't know how much this costs and it's not in my flowchart.

**Comment by sr320** [comment]
Lets go with MBD on 8 samples
