### ISSUE TITLE
Best columns for RNA isolation from frozen Olys, RNEasy kit (Alanna captsone)

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#601]
In isolating RNA from frozen Oly tissue last week using the RNeasy kit, a few columns were partially clogged and required additional spinning, and one was completely clogged. We used the MinElute columns (max capacity 45 ug), because that's what is available in the lab for this kit (and it's what Grace was using), but Shelly suggested that we might want to use a different column, for example the Mini columns (max capacity is 100 ug RNA), Midi (1mg) or Maxi columns (6mg). 

Do we have any of the above higher capacity spin columns in the lab (FYI, I don't see any on the lab inventory)? Should we order some for Alanna's project?

**Comment by kubu4** [comment]
Can you post link to notebook entry so I can review the procedure you used? I'll provide suggestions after I check it out.

**Comment by kubu4** [comment]
Alternatively, using RNazo RT is cheaper and is great for samples with an abundance of tissue. However, a subsequent DNase treatment is usually required after isolation to remove residual genomic DNA (gDNA), whereas the Qiagen RNeasy kit uses the the QIAshredder columns to eliminate gDNA (which is much faster and easier).

**Comment by laurahspencer** [comment]
Alanna is writing up the lab day in which we/she actually isolated the RNA.  Here's my entry from the homogenization step: https://laurahspencer.github.io/LabNotebook/Alanna-captsone-homogenization/

Alanna has used the RNeasy protocol twice now, once on real samples, and has become pretty comfortable with the protocol, so I think it's best to use that if possible.  We just quantified her samples, and the yield was pretty good (100 ng/uL or more for all samples), even for the sample which clogged the column.  We estimate that we have at least 1.1 ug RNA for samples extracted thus far - so perhaps we should just move forward with the miniElute columns, unless those should be reserved for someone who actually needs them? 

@sr320 do you have a preference for the kit used by Alanna?

**Comment by kubu4** [comment]
Presumably this is the RNeasy Plus Micro Kit?

Things look fine - based on your notebook entry and the yields you're getting. 

Clogging isn't an issue to be concerned about if you're following the Qiagen handbook (which you are) - it just slows you down, that's all. You may just have to perform longer spins.

**Comment by laurahspencer** [comment]
Okay sounds good, we'll carry on with the current protocol/columns. We did end up increasing the speed of the centrifuge (it says to use at least 8g, and so we increased it from 8 rcf to 13 rcf which worked pretty well).  With the one sample that clogged the column entirely, we just transferred the fluid over to a new column, and yield was good!

**Comment by kubu4** [comment]
Personally, I'd just set the microfuge at max speed for any speeds where it only specifies a minimum speed.
