### ISSUE TITLE
Visualize Cv DMLs and DMRs

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#602]
In IGV visualize DMLs and DMRs with corresponding filtered methylation data to verify DMLs / DMRs

**Comment by yaaminiv** [comment]
To clarify: all DMLs and DMRs?

**Comment by sr320** [comment]
Yes from your gonad analysis with methylation of all samples

thanks
Steven

**Comment by yaaminiv** [comment]
What criteria should I use to verify DML/DMR? I'll get this done once I'm able to access my bedGraphs from gannet.

**Comment by sr320** [comment]
We should look at and see how / if it makes sense- not sure bedgraphs will work- pretty sure they are 1x - will need to run some simple code on .cov files.

Also have track that highlights common loci would be useful

thanks
Steven

**Comment by sr320** [comment]
Reminder all files are available as backup on google drive

thanks
Steven

**Comment by yaaminiv** [comment]
Here's my [IGV session](
https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2019-03-07-IGV-Verification/2019-03-07-DML-and-DMR-Visualization.xml). Coverage files (3x and 10x) can be found in [this folder](http://gannet.fish.washington.edu/spartina/2018-10-10-project-virginica-oa-Large-Files/2019-03-07-Yaamini-Virginica-Repository/analyses/2019-03-07-IGV-Verification/). BEDfiles for DML, DMR (100 bp and 1000 bp windows), and the gene background/unite output are in [this folder](http://gannet.fish.washington.edu/spartina/2018-10-10-project-virginica-oa-Large-Files/2019-03-07-Yaamini-Virginica-Repository/analyses/2018-10-25-MethylKit/).

**Comment by yaaminiv** [comment]
Changed paths from local to URL paths. IGV session can be found [here](
https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2019-03-07-IGV-Verification/2019-03-07-DML-and-DMR-Visualization.xml). Just looking at heatmaps for DMRs, it seems like they're often artifacts of areas with no data.

**Comment by sr320** [comment]
genome location is still local - see first few lines of xml file.

**Comment by yaaminiv** [comment]
genome location is now a URL from gannet.

**Comment by sr320** [comment]
The "gene background / unite output" is not what you need. 
https://d.pr/i/4BrAi6

What you want is a track that indicates what CpG are being considered for DML / DMR analysis. This would be all CpGs with 3x coverage in all samples?

**Comment by sr320** [comment]
I am going to suggest there are some errors in the DMR code (or track development)
Is not the basis that all CpG need 3x coverage for consideration? 

![dmr](http://gannet.fish.washington.edu/seashell/snaps/IGV_-_Session_httpsraw.githubusercontent.comfish546-2018yaamini-virginicamasteranalyses2019-03-07-IGV-Verification201_2019-03-12_06-50-59.png)

**Comment by sr320** [comment]
More likely a visualization issue rather than data but CpG methylation is offset (bar at left).

![off](http://gannet.fish.washington.edu/seashell/snaps/IGV_-_Session_httpsraw.githubusercontent.comfish546-2018yaamini-virginicamasteranalyses2019-03-07-IGV-Verification201_2019-03-12_06-57-24.png)

**Comment by yaaminiv** [comment]
From what I understand, the unite output *is* all CpGs with 3x coverage in all samples (from [Bioconductor](https://bioconductor.org/packages/release/bioc/vignettes/methylKit/inst/doc/methylKit.html):

> The `unite()` function will return a `methylBase` object which will be our main object for all comparative analysis. The `methylBase` object contains methylation information for regions/bases that are covered in all samples.

I specified 3x coverage using `mincov` with `processBismarkAln` (step before `unite`)

**Comment by yaaminiv** [comment]
> I am going to suggest there are some errors in the DMR code (or track development)
Is not the basis that all CpG need 3x coverage for consideration?

Tiles were created using all CpGs with 3x coverage (R Markdown file [here](https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2018-10-25-MethylKit/2018-10-25-MethylKit.Rmd)):

`````
tiles100 <- tileMethylCounts(processedFilesCov3, win.size = 100, step.size = 100) #Add up C and T counts from each covered cytosine and return total C and T count for each tile. Perform this analysis with 100 bp sized windows, and slide 100 bp for each new window
`````

Not entirely sure what went wrong there...

**Comment by yaaminiv** [comment]
Maybe there's an issue in how the BEDfiles are generated? My code is at the bottom of the [same R Markdown file](https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2018-10-25-MethylKit/2018-10-25-MethylKit.Rmd).

example:

`````
write_delim(methylationInformationCov3, "2018-11-29-Methylation-Information-Cov3.bed", delim = "\t", col_names = FALSE) #Write out all methylation information as a background to be used for gene enrichment analyses.
`````

**Comment by kubu4** [comment]
In regards to this:

> More likely a visualization issue rather than data but CpG methylation is offset (bar at left).

The bars should be shifted to the right by one base, right?

It looks like an off-by-one error. Likely due to 0-based vs. 1-based differences in programs (Bismark vs. Methylkit). Offhand, I can't remember which system each program uses, but have vague recollections of this plaguing Claire's analysis at some point many, many years ago.

**Comment by sr320** [comment]
@kubu4 agreed but not clear how this is captured in one file, derived from bismark methylation coverage file..

**Comment by sr320** [comment]
@yaaminiv How did you create the bed files - https://github.com/RobertsLab/resources/issues/602#issuecomment-472067201 
code is not clear.

Maybe run awk on coverage file?https://genefish.slack.com/archives/D3ZDQLRC3/p1551906527001600?thread_ts=1551902681.001400&cid=D3ZDQLRC3

**Comment by sr320** [comment]
Re unite
> I specified 3x coverage using mincov with processBismarkAln (step before unite)

But how did you create the track?

**Comment by yaaminiv** [comment]
> code is not clear

Here's some of my code sequentially (maybe that will be more helpful?), including how I created the unite track.

1. Gene background

`````
processedFilesCov3 <- processBismarkAln(location = analysisFiles, sample.id = sample.IDs, assembly = "v3", read.context = "CpG", mincov = 3, treatment = treatmentSpecification) #Process files for CpG methylation using 3x coverage.

methylationInformationCov3 <- unite(processedFilesCov3) #Combine all processed files into a single table

write_delim(methylationInformationCov3, "2018-11-29-Methylation-Information-Cov3.bed", delim = "\t", col_names = FALSE) #Write out all methylation information as a background to be used for gene enrichment analyses.

`````

2. 100 bp DMR

`````
tiles100 <- tileMethylCounts(processedFilesCov3, win.size = 100, step.size = 100) #Add up C and T counts from each covered cytosine and return total C and T count for each tile. Perform this analysis with 100 bp sized windows, and slide 100 bp for each new window

methylationInformationTiles100 <- unite(tiles100) #Combine all processed files into a single table

differentialMethylationStatsTiles100 <- calculateDiffMeth(methylationInformationTiles100) #Calculate differential methylation statistics based on treatment indication from processBismarkAln

diffMethStats50Tiles100 <- getMethylDiff(differentialMethylationStatsTiles100, difference = 50, qvalue = 0.01) #Identify regions that are at least 50% different

DMR10222018 <- select(diffMethStats50Tiles100, chr, start, end, meth.diff) %>% mutate(start = start -1) %>% mutate_if(is.numeric, as.integer)  %>% mutate(TYPE ="DMR")  %>% select(chr, start, end, TYPE, meth.diff) #Reformat object so it can be saved as a BEDfile.

write_delim(DMR10222018, "2018-11-07-DMR-Locations.bed",  delim = '\t', col_names = FALSE) #Save data as a BED file
`````

**Comment by sr320** [comment]
Go ahead and create 3x coverage files from coverage files Bismark produces and see how they compare

**Comment by yaaminiv** [comment]
I have 3x coverage bed graphs for each sample. Could I simply merge all 10 of those bedgraphs for each locus that has data across all samples?

**Comment by sr320** [comment]
I suppose I am not convinced your 3x coverage bed graphs are accurate. 
https://github.com/RobertsLab/resources/issues/602#issuecomment-472017632

**Comment by yaaminiv** [comment]
> I am not convinced your 3x coverage bed graphs are accurate

I could generate a merged bedgraph, then add 1 to each start/stop position...?

**Comment by sr320** [comment]
The key thing is to understand why the data looks that way in IGV.

**Comment by yaaminiv** [comment]
Potentially relates to programmatic differences right (based on [Sam's comment](https://github.com/RobertsLab/resources/issues/602#issuecomment-472084251))?

Just trying to understand if I should generate this merged background file first, then investigate the off-by-one issue.

**Comment by sr320** [comment]
I would say the first step is that you should look at methylation in one file (library) and make sure it can be explained.

**Comment by yaaminiv** [comment]
> look at methylation in one file (library) and make sure it can be explained

Do you mean:

- Look at one sample in IGV?
- Take one sample through `methylKit` to troubleshoot?

**Comment by sr320** [comment]
Look at one sample in IGV.

**Comment by sr320** [comment]
For example... 
https://d.pr/v/QXFOJv

Main thing with this is how is the reverse strand being handled?

**Comment by sr320** [comment]
Will break out to new issues..
