### ISSUE TITLE
Isolate DNA for Sea Lice MBD-BS libraries 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#603]

**Comment by shellytrigg** [comment]
@sr320 are the samples in the -80C? I didn't see them on the inventory list

**Comment by sr320** [comment]
Same ones you used with ELISA - @kubu4 might have details in his lab notebook on what we have in from Chile.

**Comment by kubu4** [comment]
They only sent us DNA - no tissue.

**Comment by shellytrigg** [comment]
And I believe only 2 samples:
H4 | Female 1 . | Caligus tape | sea lice | 5/23/2018 | http://onsnetwork.org/kubu4/2018/09/12/dna-quantification-sea-lice-dna-from-20180523/ | sent from Chile by Cris Gallardo-Escarate
-- | -- | -- | -- | -- | -- | --
H5 | Female 2 . | Caligus tape | sea lice | 5/23/2018 | http://onsnetwork.org/kubu4/2018/09/12/dna-quantification-sea-lice-dna-from-20180523/ | sent from Chile by Cris Gallardo-Escarate

**Comment by kubu4** [comment]
Correct.

**Comment by sr320** [comment]
Can you determine if there is enough material for MBD-BS prep?

**Comment by shellytrigg** [comment]
There's about 70ng of Female1 and about 240ng of Female2. What is the minimum for MBD-BS prep?

**Comment by kubu4** [comment]
Technically, you can start with 5ng.

Don't know much about the sea lice methylome, but oyster yields are very low (expect 1 - 5% of input DNA to be captured via MBD).

Off-hand, can't remember what library prep kits will accept as minimum DNA input (50pg?). @yaaminiv - Can you link your decision tree for us to glance at to help us figure this out?

**Comment by yaaminiv** [comment]
https://docs.google.com/presentation/d/1oE2c7QZGSeQ73HLsZw0hJBmLwODXwiVWfhYlJbzetMg/edit

FYI it's in the Roberts Lab Team Drive!

**Comment by shellytrigg** [comment]
@sr320 should I plan to run these samples through MethylMiner and PicoMethylSeq library prep? @yaaminiv do we know what kind of coverage we get from low input DNA samples prepared like this? I read this recommendation on page 11 of the MethylMiner manual: 
![screen shot 2019-03-06 at 5 27 53 pm](https://user-images.githubusercontent.com/4720221/53926199-7150a400-4037-11e9-8d88-896d4e236450.png)

**Comment by shellytrigg** [comment]
Also, Qubit HS DNA assay low end is 200pg/uL [https://www.thermofisher.com/order/catalog/product/Q32854](https://www.thermofisher.com/order/catalog/product/Q32854). I think the nanodrop ND1000 low end is 2ng/ul (excerpt from page 15 of ND1000 v3.8 user manual)
![page 15 of ND1000 v3.8 user manual](https://user-images.githubusercontent.com/4720221/53926716-65fe7800-4039-11e9-92cf-b702fe0f35a1.png). @yaaminiv what was your total DNA yield after MethylMiner and PicoMethylSeq library prep?

**Comment by yaaminiv** [comment]
@shellytrigg 

> do we know what kind of coverage we get from low input DNA samples prepared like this?

What do you mean by coverage? I used 1.28 µg to 4 µg of DNA for my gonad sample MBD and ended up with a lot of sequencing data! I used 3x coverage for my `methylKit` analyses, so I know I at least have that.

> what was your total DNA yield after MethylMiner and PicoMethylSeq library prep?

@kubu4 actually finished that step for me! Here's a spreadsheet from his lab notebook that has yield information: https://docs.google.com/spreadsheets/d/1p13VsqTMrynvWIfokPVAwqaL78_GA6QtTZ0NAgLVfSI/edit#gid=236614896

**Comment by shellytrigg** [comment]
With the two samples we currently have, even if we pooled it'd only be ~300ng total which seems too little to try MBD-seq on. Mac shared that she used Diagenode's RRBS kit (manual below) on 100ng O.mykiss samples, but hasn't determined the coverage of methylated regions yet. For reference, [Caligus rogercresseyi's genome](https://www.ncbi.nlm.nih.gov/genome/38161) is ~400M and [Lepeophtheirus salmonis's](http://metazoa.ensembl.org/Lepeophtheirus_salmonis/Info/Annotation/#assembly) genome is ~700M.
[Premium_RRBS_kit_manual.pdf](https://github.com/RobertsLab/resources/files/2944130/Premium_RRBS_kit_manual.pdf)

**Comment by shellytrigg** [comment]
There's also this Swift library prep method for low input BS [here's the site showing the performance compared to traditional methods](https://swiftbiosci.com/applications/bisulfite-sequencing/#exp-performance-data). Here's [a webinar about it](https://www.youtube.com/watch?v=ugKcneJlW2U).

**Comment by kubu4** [comment]
WGBS quote from Genewiz for the two samples is:

$2320

- $880/sample, plus a lane of sequencing ($1440).

I'll report back with a Zymo quote.

**Comment by kubu4** [comment]
Zymo would be $2300/sample (i.e. $4600 for the project).

**Comment by shellytrigg** [comment]
Ok so plan is to pool the remaining sea lice dna and send it to genewiz for WGBS. @sr320 can you confirm this?

**Comment by sr320** [comment]
No - since we will be buying library kits for salmon etc. Will prep the libraries in house, and plan on doing WGBS, sequencing at UW

**Comment by shellytrigg** [comment]
Ok so how about this for the sea lice:

Don't pool sample, make two WGBS libraries in-house with zymo pico methylseq kit, and give 1/3 of Novaseq sequencing to these samples (240M reads/sea lice library; leaving 1120M reads for the 20 salmon samples-56M reads/salmon library, higher coverage than the 34M reads/sample in the Sci Reports paper)

**Comment by sr320** [comment]
Sounds good
