### ISSUE TITLE
Samples moved back to Roberts Lab -80

### ISSUE THREAD

**Issue by emmats** [RobertsLab/resources#606]
I just dropped off 4 sample boxes to the top row of the -80, rack 1. I've attached a picture of the boxes so you can decide if you want to keep them or not. If you think I have other samples that I did not bring over today, let me know so I can find them.

![IMG_4154](https://user-images.githubusercontent.com/4564812/54145180-b5062d80-43ea-11e9-9dcc-189800829a4b.JPG)

**Comment by sr320** [comment]
@kaitlynrm - can you confirm / update the -80 inventory accordingly?

**Comment by kaitlynrm** [comment]
Yes! What types of tissue/samples are the middle boxes (Rhonda autosampler Vials and C. gigas samples for SRM)?

**Comment by emmats** [comment]
C. gigas samples for SRM are probably pooled larvae
Autosampler vials will be peptides from pooled larvae (C. gigas)
I didn't actually open any of these boxes to see what was inside

**Comment by kaitlynrm** [comment]
Okay, and is the last box, Oyster Larvae for D119, also C. gigas?

**Comment by emmats** [comment]
yes

**Comment by kaitlynrm** [comment]
Inventory is updated!
