### ISSUE TITLE
Input on Crab Supply list for Christie, please

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#608]
@sr320 @kubu4 

Making a list to send to Pam for Christie to order. 

### Here's what I am thinking:   
3 orders of Qiagen RNeasy Plus Micro Kit (50rxns) (cat. 74034)
https://www.qiagen.com/us/shop/sample-technologies/rna/total-rna/rneasy-plus-micro-kit/#orderinginformation 

3 orders of Qiagen QIA Shredder Columns (50) (cat. 79654)
https://www.qiagen.com/us/shop/lab-basics/plastics/qiashredder/#orderinginformation 

1 order of UltraPure 4x1.25mL DEPC-treated water (cat.10813012 ) (for eluting the RNA)
https://www.thermofisher.com/order/catalog/product/10813012 

1 order of UltraPure 1 L DEPC-treated water (cat. 750023) (for making the 70% and 80% ethanol mixes)
https://www.thermofisher.com/order/catalog/product/750023 

### Questions: 
1. Is this overkill? It's enough for 150 extractions, plus we currently have supplies for about 60 extractions. 
2. Should I also order things like gloves, pipet tips, RNAse-free snap cap tubes, ethanol, etc. to replace what I'll end up using from our current inventory?

**Comment by kubu4** [comment]
How many samples will you need to process?

It doesn't really seem like overkill if you need this stuff for extractions.

The kits come with water for elution - why order DEPC-treated water for elution? Is RNA degradation a concern (I mean, I know it's _always_ a concern)?

Yes, order "consumables" (i.e. gloves, pipette tips, tubes, ethanol).

**Comment by sr320** [comment]
I would order 4 sets of kits - and add in some RNA’ase free tubes

Thanks
steven

**Comment by grace-ac** [comment]
@kubu4 
>How many samples will you need to process?

Not entirely sure how many extractions are needed because we don't really know what to expect, but @sr320 suggestion of 4 kits is a good idea! Will do. 

>The kits come with water for elution - why order DEPC-treated water for elution? Is RNA degradation a concern (I mean, I know it's always a concern)? 

@sr320 recommended I use aliquots of DEPC-treated water 

>Yes, order "consumables" (i.e. gloves, pipette tips, tubes, ethanol).
Will do! :)

**Comment by grace-ac** [comment]
sent to Pam for Christie and added 4 kits, gloves, pipet tips, ethanol, and RNAse free tubes

**Comment by sr320** [comment]
Water too please

Thanks
steven

**Comment by grace-ac** [comment]
@sr320 DEPC treated water? 

I put down an order for 1L of it, in addition to the aliquots.

**Comment by sr320** [comment]
That’s it - just misunderstood one of the comments

Thanks
steven
