### ISSUE TITLE
Characterize MBD-BS performance

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#609]
Using C virginca gonad data, concatenate all libraries and examine coverage on 4 levels of read quantity.
1) Average read count for a single library
2) 50% of average read count for a single library
3) All data
4) 50% of all data

Questions to addressed 
Mean CpG Coverage 
% CpG Coverage at 5x
% CpG Coverage at 10x
Any "Report" information automatically calculated by Bismark.

**Comment by kubu4** [comment]
Should I use the Cvirginica_v300 genome that's on the [Genomic Resources](https://github.com/RobertsLab/resources/wiki/Genomic-Resources#genome-1) wiki?

**Comment by sr320** [comment]
@yaaminiv does that concur with what you used?

**Comment by kubu4** [comment]
Looks like she used the NCBI version:

https://github.com/RobertsLab/project-virginica-oa/blob/master/notebooks/2018-04-27-Gonad-Methylation-Bismark.ipynb

I'll use that one as well.

**Comment by yaaminiv** [comment]
@kubu4 Yup, used the NCBI version

**Comment by sr320** [comment]
Should be the same - but would be great to verify.

thanks
Steven

**Comment by kubu4** [comment]
Well, this is _mostly_ complete. All the requested subsets ran correctly. The full set did not run correctly (ran as subset of half total reads); am running just that again and will update notebook once complete. I haven't had time to do coverage comparisons, but will get to that soon (I hope) and will update notebook.

Here's my notebook entry:

https://robertslab.github.io/sams-notebook/2019/03/13/Methylation-Analysis-C.virginica-Gonad-MBD-with-Varying-Read-Subsets-with-Bismark-on-Mox.html

**Comment by kubu4** [comment]
Alrighty, I _think_ I'm finished with the sequencing coverage analysis. Here's my notebook (please review to make sure things make sense):

- http://b.link/20190418-cvir-mbd-notebook

Jupyter Notebook of analysis (can be downloaded and easily run locally - just need to change the two work_dir values and output_file value at top of notebook):

- http://b.link/20190418-cvir-mbd-coverage-comparison-ipynb-github

Here's a plot of "Percent CpG Coverages" of the various Bismark read subsets:

![](https://github.com/RobertsLab/sams-notebook/blob/master/images/screencaps/20190418_cvir_mbd_cov_comparison.png?raw=true)

And, here's a summary table of the data (lines/bars are redundant; added lines to help visualize trends):



| Bismark Subset                | No. of Read pairs | Trimmed read length (bp) | No. of Bases (Gbp) | Genome size (Gbp) | Genome coverage (x fold) | Mean CpG Coverage | Percent CpG Coverage | Percent 5x CpG Coverage | Percent 10x CpG Coverage |
|-------------------------------|-------------------|--------------------------|--------------------|-------------------|--------------------------|-------------------|----------------------|-------------------------|--------------------------|
| total_reads_CpG_coverage      | 275914272         | 80                       | 22.07              | 0.684741          | 32.24                    | 7.3               | 45.3                 | 14.7                    | 9.1                      |
| half_total_reads_CpG_coverage | 137957136         | 80                       | 11.04              | 0.684741          | 16.12                    | 3.5               | 33.5                 | 9.2                     | 5.7                      |
| avg_reads_CpG_coverage        | 27591427          | 80                       | 2.21               | 0.684741          | 3.22                     | 0.7               | 15.3                 | 3.2                     | 1.8                      |
| half_avg_reads_CpG_coverage   | 13795713          | 80                       | 1.10               | 0.684741          | 1.61                     | 0.5               | 11.2                 | 2.3                     | 1.2                      |
