### ISSUE TITLE
Bismark Code and Output for Cv MBD-BS analysis

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#610]
Where does this live?

**Comment by yaaminiv** [comment]
Bismark Code: 
https://github.com/fish546-2018/yaamini-virginica/blob/master/scripts/2018-11-08-Bismark-Revised-Parameters-Samtools.sh
Output: http://gannet.fish.washington.edu/spartina/2018-10-10-project-virginica-oa-Large-Files/2018-11-07-Bismark-Mox/

**Comment by sr320** [comment]
Thanks! R code for methylkit?

**Comment by yaaminiv** [comment]
`methyKit` R Markdown: https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2018-10-25-MethylKit/2018-10-25-MethylKit.Rmd
