### ISSUE TITLE
Crab supply questions from Pam

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#612]
@sr320 and @kubu4 

1. Will we need more kits for determining gene expression levels in all crab samples? If yes she'd like to ask Qiagen for a quote on RNA kits. (*I think we will need more for that.*)

2. (@kubu4) After the sequencing is done, we have qPCRs to do, so you'll need gloves & tips then. Perhaps you can talk to Sam & guesstimate what to order to also at least partially cover qPCRs? (*Below is what I included in my original order request*). 

> 1 order of Genesee Scietific P1000 tips (cat 24-430)
https://geneseesci.com/shop-online/product-details/24-430
1 order of Medium X-GEN Nitrile Gloves 
https://geneseesci.com/shop-online/product-details/44-100M 

3. Is there a 250 column kit? It's probably cheaper than 4 50-column kits. Ditto on the shredder columns. (*I have been looking and can only find 50 column kits 50 shredder columns....*)

4. Can you make aliquots from the liter size? Since the 5 ml cost almost as much as the liter.

**Comment by kubu4** [comment]
1. I don't know what the plan is for the project, so difficult to say.

2. No need to order this stuff at this time. As Pam noted, I just ordered both of these items recently (I think I neglected to add to Purchasing Log - sorry!). We'll wait to order qPCR supplies (that aspect of things is still a ways off).

3. No RNeasy Plus Micro Kit (250) - 50 only. QIAshredder is available in a 250 pack: Cat: 79656.

4. We can make DEPC-treated H<sub>2</sub>O here in the lab - no need to purchase any water. With that being said, yes, we can make aliquots from the liter size.

**Comment by sr320** [comment]
Main thing is we need extraction kits ASAP. and I am fine with purchasing water.

**Comment by grace-ac** [comment]
@sr320, do you think i should have her get the liter and the aliquots? Or just the liter water

**Comment by sr320** [comment]
liter is fine

**Comment by grace-ac** [comment]
thanks. asking christie to order RNeasy kits (4), QIA shredder columns (250 set), and 1 L DEPC-treated H20
