### ISSUE TITLE
Create new DML tracks for Cv gonad data

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#613]
with 5x minimum coverage and 10x minimum coverage.

**Comment by yaaminiv** [comment]
- [Lab notebook](https://yaaminiv.github.io/DML-Analysis-Part27/)
- [5x sample tracks](http://gannet.fish.washington.edu/spartina/2018-10-10-project-virginica-oa-Large-Files/2019-03-07-Yaamini-Virginica-Repository/analyses/2019-03-07-IGV-Verification/) 
- [DML bedfiles](http://gannet.fish.washington.edu/spartina/2018-10-10-project-virginica-oa-Large-Files/2019-03-07-Yaamini-Virginica-Repository/analyses/2018-10-25-MethylKit/). 
- [IGV session]()

**Comment by sr320** [comment]
So it would appear our 5x DML bedfiles do not match and you are still getting both strands?
Here is my nb https://github.com/sr320/nb-2019/blob/master/C_virginica/52-OAKL-mk.Rmd

my bedfile http://gannet.fish.washington.edu/seashell/snaps/dml52.bed

**Comment by yaaminiv** [comment]
Looks like your 5x DML bedfile and my 5x DML destranded bedfile match. I think the "strandedness" of my destrand track is an artifact of how I exported the file. I used your code to re-export my 5x and 10x destranded tracks, but now I have something different and I'm not sure what happened:

http://gannet.fish.washington.edu/spartina/2018-10-10-project-virginica-oa-Large-Files/2019-03-07-Yaamini-Virginica-Repository/analyses/2018-10-25-MethylKit/2019-03-13-DML-Destrand-5x-Locations.bed

**Comment by yaaminiv** [comment]
Solved the issue with my tracks! Turns out I was using `mutate` on the wrong dataframe.

![Untitled 2](https://user-images.githubusercontent.com/22335838/54398600-f8c19700-4677-11e9-9542-4ae670242154.png)

I am going to go ahead and characterize the locations of the 5x destranded DML track.
