### ISSUE TITLE
Determine Protocol and Validate running R in Jupyter

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#614]

**Comment by kaitlynrm** [comment]
I run Ubuntu 18.04 through WSL on my laptop. If I follow [these instructions (for Ubuntu & Debian in my case)](https://irkernel.github.io/installation/#source-panel), I can create R scripts in jupyter notebook.

**Comment by kaitlynrm** [comment]
Additionally, [these are other kernels](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) you can install and create notebooks of.

**Comment by sr320** [comment]
Can you demonstrate on Mac, maybe genefish?

thanks
Steven


Steven B. Roberts
Kenneth K. Chew Endowed Professor
School of Aquatic and Fishery Sciences
University of Washington, Seattle WA
sr320@uw.edu - 206.866.5141
robertslab.info - @sr320

**Comment by kubu4** [comment]
Also, when/if you get this installed, please update the software list for Ostrich:

https://github.com/RobertsLab/resources/wiki/Lab-Software#computer-ostrich

**Comment by sr320** [comment]
Would also love some proof you have it working in Linux :)

Steven

**Comment by kubu4** [comment]
![20190314_001](https://user-images.githubusercontent.com/4514104/54376848-27704b00-4641-11e9-8eae-f9f7ec3699b4.png)

Installed using Anaconda R kernel package.

As easy as:

```conda install -c r r-irkernel```

**Comment by sr320** [comment]
@kubu4 is that Linux or Mac?

Steven

**Comment by kaitlynrm** [comment]
It's in Linux @sr320

**Comment by kaitlynrm** [comment]
I couldn't shell into genefish so I worked on ostrich. Sam added an account for me to gain admin permissions. First, I ran `chmod +x anaconda3.sh` to run executable commands (anaconda was already downloaded). Then I ran 
`conda update conda`
`conda install jupyter`
`conda install -c r r-irkernel`.

I was then able to launch jupyter notebook and open an R notebook.

![Screen Shot 2019-03-19 at 8 22 43 AM](https://user-images.githubusercontent.com/26392677/54621323-d091b980-4a24-11e9-801f-a60f5313507a.png)

**Comment by sr320** [comment]
What about running R with other stuff (can you run R commands in a regular notebook?)

**Comment by sr320** [comment]
I can confirm `conda install -c r r-irkernel` gets u the ability to have an R notebook.

**Comment by kaitlynrm** [comment]
No, this is an R notebook only. You can run R in magic cells using `rpy2`.

`conda install -c r r-irkernel`

In jupyter notebook:

`import rpy2.interface`
`%load_ext rpy2.ipython`

Note that here I got an error that `matplotlib` had no artist attribute. So I `conda uninstall matplotlib` then `conda install matplotlib`. Ran the above two lines again, received an error that `tazlocal` module was not present- ran `conda install tazlocal`. Reran the above two lines in jupyter notebook and was successful. I believe you will have to run `%load_ext` each time you open a notebook to run R. Here's [some info about moving data between the languages ](https://www.linkedin.com/pulse/interfacing-r-from-python-3-jupyter-notebook-jared-stufft/). 

The second cell is an example of an attribute error.
![Screen Shot 2019-03-19 at 10 53 16 AM](https://user-images.githubusercontent.com/26392677/54629753-6fbead00-4a35-11e9-8ddf-902e14cdf65d.png)

**Comment by sr320** [comment]
![mygry](http://gannet.fish.washington.edu/seashell/snaps/Untitled2_2019-03-19_11-00-35.png)

**Comment by kaitlynrm** [comment]
I edited the above comment but it may have been to late- I put install irkernel instead of rpy2 in the first line. Did you run `conda install -c r rpy2` or the previous `conda install -c r r-irkernel`?

**Comment by sr320** [comment]
Still no luck

https://d.pr/i/ogjSM6

**Comment by kaitlynrm** [comment]
Sorry, the above should be `import rpy2.rinterface`

**Comment by kaitlynrm** [comment]
The rest is correct and will work! I also installed this on genefish to troubleshoot.

**Comment by kubu4** [comment]
Pro tip:

If you don't want to always have to load the ```rpy2``` module, check out this post on how to create a startup file to always load the extensions when you launch a Jupyter Notebook:

https://towardsdatascience.com/how-to-automatically-import-your-favorite-libraries-into-ipython-or-a-jupyter-notebook-9c69d89aa343

(I think lines 11-15 of the code are what you'd want - but replace ```autoreload``` with ```rpy2```)
