### ISSUE TITLE
Identifying methylated CpGs in Cv gonad data

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#615]
I want to describe general methylation trends, irrespective of pCO<sub>2</sub> treatment in my *C. virginica* gonad data. Claire and Mac both had sections in their papers where determined if a CpG locus was methylated or not. From Mac's 2013 PeerJ paper:

> A CpG locus was considered methylated if at least half of the reads remained unconverted after bisulfite treatment.

I believe this was done `methratio` in BSMAP ([Claire's notebook](https://github.com/che625/olson-ms-nb/blob/master/.ipynb_checkpoints/BiGo_dev-checkpoint.ipynb)). Is there a way to do this with `bismark` or `methylKit`?

**Comment by yaaminiv** [comment]
I'd assume this would be the goal of `unite` in `methylKit`, but I haven't figured out why it's not giving us the output we want (yet).

**Comment by sr320** [comment]
.cov files have methylation for each loci, as well as coverage.

Limit to 5x then you can call each loci.

**Comment by yaaminiv** [comment]
To clarify: I plan on just looking at the 5 samples from the control to not induce treatment effects. Is this the correct approach?

**Comment by sr320** [comment]
That is fine…

**Comment by yaaminiv** [comment]
Comparing [Bismark Processing Reports](http://gannet.fish.washington.edu/spartina/2018-10-10-project-virginica-oa-Large-Files/2018-11-07-Bismark-Mox/zr2096_2_s1_R1_val_1_bismark_bt2_PE_report.html) to the "Total Sequences" from FastQC reports, it looks like they are the same counts...? @kubu4 am I looking at the wrong thing to obtain pre-trimming read counts? Or was there minimal trimming?

**Comment by yaaminiv** [comment]
I filtered 5x loci from all 5 control samples, then concatenated all loci with 5x coverage across the 5 samples in [this Jupyter notebook]().  I noticed
