### ISSUE TITLE
Counting reads in Cv gonad data

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#616]
I want to use a loop to count reads in my raw *C. virginica* gonad sequence data. I tried a loop in [this Jupyter notebook](
https://github.com/fish546-2018/yaamini-virginica/blob/master/notebooks/2019-03-17-Counting-Reads.ipynb) but got a `gunzip` error:

![Screen Shot 2019-03-18 at 8 53 10 AM](https://user-images.githubusercontent.com/22335838/54543649-44678f80-495b-11e9-93f4-5b8d5e13a5be.png)

I've tried the `echo $(( $(gunzip -c FILENAME | wc -l) / 4 ))` code on a single file so I know it works...just not sure how the loop changes things.

**Comment by sr320** [comment]
Why do you want to count reads? This is provided in Bismarck

thanks
Steven


Steven B. Roberts
Kenneth K. Chew Endowed Professor
School of Aquatic and Fishery Sciences
University of Washington, Seattle WA
sr320@uw.edu - 206.866.5141
robertslab.info - @sr320

**Comment by yaaminiv** [comment]
Bismark has trimmed reads, not raw reads. I thought it would be good to include read counts from both untrimmed and trimmed files.

**Comment by kubu4** [comment]
You're missing the ```*``` needed as a wildcard to identify which files you want your for loop to operate on.

**Comment by sr320** [comment]
True - FastQC should have those numbers

**Comment by yaaminiv** [comment]
@kubu4 RIP me. Thanks!

@sr320 Got it. Total sequences = total reads

**Comment by yaaminiv** [comment]
Another loop question...

I was able to successfully count reads, but I want to save the `grep` output in a new file. When I try redirecting the output to a new file, I only get the last entry saved. In R, I know I can create a blank dataframe with 10 lines, then save each read count in a designated row/column. How do I do something similar with a bash loop?

![Screen Shot 2019-03-18 at 10 01 01 AM](https://user-images.githubusercontent.com/22335838/54548154-8517d680-4964-11e9-84ca-04b21c92d5ad.png)

**Comment by kubu4** [comment]
Without adding any "fancy" stuff like the corresponding filename, you need to change your redirect symbol from ```>``` to ```>>```.

The ```>>``` will concatenate the results from each run of the loop to the end of the file. Using ```>``` will overwrite the file each time, thus, you only end up with the results from the last FastQ file from the loop.

**Comment by yaaminiv** [comment]
(Posted this in the wrong issue initially...posting here)

Comparing [Bismark Processing Reports](http://gannet.fish.washington.edu/spartina/2018-10-10-project-virginica-oa-Large-Files/2018-11-07-Bismark-Mox/zr2096_2_s1_R1_val_1_bismark_bt2_PE_report.html) to the "Total Sequences" from FastQC reports, it looks like they are the same counts...? @kubu4 am I looking at the wrong thing to obtain pre-trimming read counts? Or was there minimal trimming?

**Comment by kubu4** [comment]
Link to FastQC?

**Comment by yaaminiv** [comment]
http://owl.fish.washington.edu/Athaliana/20180411_trimgalore_10bp_Cvirginica_MBD/20180411_fastqc_trim_10bp_Cvirginica_MBD/zr2096_1_s1_R1_val_1_fastqc.html

**Comment by kubu4** [comment]
That's not the FastQC report for the files in the Bismark report linked above.

**Comment by yaaminiv** [comment]
Whoops! Here you go: http://owl.fish.washington.edu/Athaliana/20180411_trimgalore_10bp_Cvirginica_MBD/20180411_fastqc_trim_10bp_Cvirginica_MBD/zr2096_1_s2_R1_val_1_fastqc.html

http://owl.fish.washington.edu/Athaliana/20180411_trimgalore_10bp_Cvirginica_MBD/20180411_fastqc_trim_10bp_Cvirginica_MBD/zr2096_1_s2_R2_val_2_fastqc.html

**Comment by yaaminiv** [comment]
Whoops! Here you go:

http://owl.fish.washington.edu/Athaliana/20180411_trimgalore_10bp_Cvirginica_MBD/20180411_fastqc_trim_10bp_Cvirginica_MBD/zr2096_2_s1_R1_val_1_fastqc.html

http://owl.fish.washington.edu/Athaliana/20180411_trimgalore_10bp_Cvirginica_MBD/20180411_fastqc_trim_10bp_Cvirginica_MBD/zr2096_2_s1_R2_val_2_fastqc.html

**Comment by kubu4** [comment]
Those aren't correct, either.

**Comment by kubu4** [comment]
Yes, you are looking at the wrong FastQC report. You're looking at the FastQC report for the trimmed files.

Check nightingales spreadsheet for link to raw FastQ files and/or FastQC for raw files (scroll all the way to right on that spreadsheet to see if there's already a link to a FastQC report for a given FastQ file).

**Comment by yaaminiv** [comment]
Gotcha. I keep forgetting about the nightingales spreadsheet.

To clarify: `Read1URL` is the original file, and `Read1FastQC` is the trimmed file? (can't find that information in the Data Management wiki...is that metadata somewhere else that I don't know of?)

**Comment by kubu4** [comment]
```Read1URL```: URL to the read 1 FastQ files

```Read1FastQC```: Corresponding FastQC report for read 1 FastQ files

There are no links to trimmed files on nightingales.
