### ISSUE TITLE
morphology data from microbiome experiment

### ISSUE THREAD

**Issue by emmats** [RobertsLab/resources#617]
In her notebook, Rhonda mentions that she collected morphology data on the geoduck larvae that accompanied the microbiome experiment. Do we have these data?

https://ellior2.github.io/Geoduck-Trials-2017/

**Comment by shellytrigg** [comment]
It seems like when she says 'morphology' she really just means mortality based on her notebook description. I can't find any morphology data anywhere. Just size and mortality data.

**Comment by emmats** [comment]
Any idea where the raw data for her growth curve might be? I only see raw data for counts in her notebook.

**Comment by shellytrigg** [comment]
This? https://github.com/RobertsLab/project-pacific.oyster-larvae/blob/master/DDA_2016/OysterSeedMorphology_%20C.%20gigas_pivottable.xlsx

Also looks like there is a picture file name listed on '10mL Tubes' tab so it seems like pictures must exist somewhere (e.g. "T9_69to135_7-1"). @sr320 do you remember any particular place on the server or lab drive where Rhonda may have saved images?

**Comment by emmats** [comment]
These were geoduck larvae so that is probably not the right file. Thanks for digging it up, though!

**Comment by shellytrigg** [comment]
Rhonda's notebook link you sent from 5/9/2017-6/1/2017 she seems to refer to the oysters as larvae throughout, and sometimes as 'setters'. You are looking for 2017 data and i realize that xlsx file is 2016 data. It's gotta be around somewhere

**Comment by emmats** [comment]
I think she slipped up once or twice and typed "oysters" but the experiment was with geoduck, May 2017

**Comment by shellytrigg** [comment]
right! yeah, i'm not sure what repo any of that stuff is in

**Comment by sr320** [comment]
I checked the owl folder and it just has proteomic data - @kubu4 do you have any ideas where data might live?

**Comment by sr320** [comment]
@emmats reach out to Rhonda and see if she has a recollection of where the data you are looking lives.

**Comment by kubu4** [comment]
I don't have any guesses. Poked around a bit, but didn't find anything.

**Comment by emmats** [comment]
I got a spreadsheet! I figured you might want to store it somewhere.
[2017X15GeoduckLowpH_prot.xlsx](https://github.com/RobertsLab/resources/files/3004371/2017X15GeoduckLowpH_prot.xlsx)
