### ISSUE TITLE
Oysterseed DIA: Get GO terms, make Venn Diagram

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#618]
Skyline output file: http://owl.fish.washington.edu/scaphapoda/grace/2015-Cgseed-DIA/post-EncyclopeDIA-Skyline/20181218-SkytoMSstats-report.csv 

File includes four oyster seed samples from the two control silos (last column in file):    
Sample name    -  Temp  -     Sample Date
Oysterseed_01   -  23C    -      9/11/2015           
Oysterseed_02   - 29C    -      9/11/2015       
Oysterseed_13   - 23C     -     9/14/2015
Oysterseed_14   - 29C     -     9/14/2015

Compare GO terms of 23C with 29C in a Venn Diagram

**Comment by grace-ac** [comment]
@sr320 where does uniprot/swissprot fasta live?

**Comment by sr320** [comment]
See urls near top of this page
https://github.com/RobertsLab/code/blob/master/10-blast-2-slim.ipynb

**Comment by shellytrigg** [comment]
JAN 2019 version here: http://gannet.fish.washington.edu/metacarcinus/Cgigas/uniprot_swprot2019_01.fasta

**Comment by grace-ac** [comment]
closing issue and making new with specific R questions
