### ISSUE TITLE
Should I include late shift to high pH in manuscript?

### ISSUE THREAD

**Issue by emmats** [RobertsLab/resources#619]
The big question looming over the geoduck OA manuscript is whether we should include the proteomics data for the larvae that were moved to pH 8.2 on day 11. The growth profiles are intriguing since the larvae at low pH make up their size differential when moved to 8.2, and the larvae are ready to set sooner if moved to 8.2. Something to discuss Wednesday?

**Comment by sr320** [comment]
Given time frame - I would say no. But we can discuss Wednesday and determine a plan for capturing all of the data.
