### ISSUE TITLE
Print Ronit's Triploid Poster

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#624]
link to poster https://d.pr/f/Gmof2j

**Comment by kaitlynrm** [comment]
What is the project name and budget number I should put this under?

**Comment by sr320** [comment]
65-2861 ROBERTS CHEW PROFESSOR

thanks
Steven

**Comment by kaitlynrm** [comment]
Submitted an order to receive next Tuesday! I cc'ed you in the UW Creative Commons submission form @sr320 as well.
