### ISSUE TITLE
create link to data on Gannet?

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#625]
is it possible to create a link to data that's on Gannet?

**Comment by kubu4** [comment]
Add the name of your Gannet folder to the end of this URL:

```https://gannet.fish.washington.edu/```

Then browse to the file you want to link to and copy the link.

**Comment by kubu4** [comment]
Example:

http://gannet.fish.washington.edu/Atumefaciens/20190225_cpg_oe/ID_CpG_labelled_all

**Comment by shellytrigg** [comment]
awesome! thank you so much!
