### ISSUE TITLE
Fixing a broken curl

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#626]
presumably in efforts to get R in jupyter I broke curl

```
Stevens-MacBook-Pro:fun-gen sr320$ curl
dyld: Library not loaded: @rpath/libssl.1.0.0.dylib
  Referenced from: /anaconda3/lib/libssh2.1.dylib
  Reason: image not found
Abort trap: 6

```

Any advice on resolving? - I like curl better than having R inside jupyter :)

**Comment by sr320** [comment]
random pastes into terminal eventually resolved

what worked...
`conda install libssh2`

**Comment by kubu4** [comment]
Also going to add that this is a common "issue" when installing/using Anaconda (and it drives me crazy). The error shows that your computer is looking in the anaconda directories, finding something it thinks should work, but then can't actually find it - and doesn't go through the rest of the system $PATH to try to find the functioning ```curl```. My recommendation is to move anaconda to the end of your system path (Anaconda sets it to be at the beginning of your system path).

When you do this, your computer will load all of your "normal" programs first and then use Anaconda for any programs it doesn't find in your regular computer set up (e.g. Jupyter). That way, you won't go crazy trying to install a billion Anaconda packages/libraries just to use a program that you used to be able to use without issue.
