### ISSUE TITLE
Inventory/label supplies from Manchester

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#63]
Brought all supplies back from Manchester's dry lab so we can inventory, label and either store @ the UW lab or take back to Manchester.  Thought we could tackle this Monday or Tuesday with help from @grace-ac , pending everyone's availability.  Things are on the metal bench in the lab in 213.

**Comment by grace-ac** [comment]
I can start this now. Or, would you rather I wait for you or someone else to hep determine what should stay and what should go back? @laurahspencer 

I can come in every day this week.

**Comment by sr320** [comment]
Go ahead and start

**Comment by laurahspencer** [comment]
Great, thanks Grace!
Can you also put items away in the lab with location on the inventory
sheet?

**Comment by grace-ac** [comment]
All items that have a place in 213 are listed in the [Roberts Lab Inventory](https://docs.google.com/spreadsheets/d/11RA_mlLB-3m_GySnTTuDazDdOi0bCxJu2VERuX9Qfx8/edit#gid=0) 

Lab labels have been placed on equipment items. 

The tool box and tool bag are on the metal table, along with the two boxes of chemicals.
