### ISSUE TITLE
Upload Geoduck RNA-seq Raw data to SRA

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#630]
Particularly need accession numbers for
```
NR021_S8_L001_R1_001.fastq,NR021_S8_L002_R1_001.fastq \
NR021_S8_L001_R2_001.fastq,NR021_S8_L002_R2_001.fastq \
```
for Emmas paper.

**Comment by kubu4** [comment]
What are these? Nightingales has these listed, but has no other information for them (other than species).

I found this notebook entry of yours: https://sr320.github.io/Illumina-Summary/

Seeing that, it seems fair to say these are "Larvae Day 5". However, I need more info for the SRA submission. What does day 5 represent - day 5 post-fertilization? Day 5 of some treatment? Day 5 of the larval stage?

Also, were there any treatments that I should be aware of?

Sorry for all the questions - don't have access to that Google Doc with the manuscript yet.

**Comment by sr320** [comment]
> What are these? Nightingales has these listed, but has no other information for them (other than species).

Should probably submit issue that Nightingales needs updating :)

Larvae are 5 days post fertilization, no treatment.

**Comment by kubu4** [comment]
Adding Hollie's sample sheet for prosperity:

https://github.com/hputnam/project_larval_geoduck_OA/blob/master/Larval_Sample_Info.csv

And, sample submission to Illumina:

https://robertslab.github.io/sams-notebook/2016/12/21/sample-submission-geoduck-tissue-gdna-for-illumina-pilot-sequencing-project.html

**Comment by kubu4** [comment]
[PRJNA529226](https://www.ncbi.nlm.nih.gov/bioproject/529226):

https://www.ncbi.nlm.nih.gov/bioproject/529226

SRA recommends using BioProject accession  for publications (which is what's linked above), instead of the SRR/SRP accession
