### ISSUE TITLE
Run higher volume of Crab RNA on Qubit

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#636]
Go ahead and run 10ul from 24 samples you processed with vacuum manifold

**Comment by grace-ac** [comment]
Ran 10ul from each of the 24 samples from [March 19th](https://grace-ac.github.io/24sample-RNeasy-extraction/) on Qubit

4/24 had RNA (rest were Out of Range: TOO LOW)(google sheet [here](https://docs.google.com/spreadsheets/d/1me8cRniPYfM4AUiFo5oO2cS_7km00uroTeMCktiMTFk/edit?usp=sharing))

The four that had RNA:     
![Screen Shot 2019-04-01 at 4 22 10 PM](https://user-images.githubusercontent.com/14934314/55365725-74a24880-549a-11e9-853d-25b1e6d967ce.png)
