### ISSUE TITLE
Table of proteins: Pg larvae paper

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#638]
Can you provide table with 

1) 7673 proteins detected
2) those expressed in each pH
3) cluster ID they group into

**Comment by emmats** [comment]
https://drive.google.com/file/d/1Bi1wOZVmyoVJo20zzjKczHf4yRoy9WMv/view?usp=sharing

**Comment by sr320** [comment]
How do I translate `GX_X` column headers?

**Comment by emmats** [comment]
This file will tell you which is which. I can also rename the column headers if you prefer.

<img width="203" alt="Screen Shot 2019-03-27 at 9 19 56 AM" src="https://user-images.githubusercontent.com/4564812/55093340-81c1d080-5071-11e9-9b64-23d7007c8373.png">

You found an error in my code! I will fix the file.

**Comment by emmats** [comment]
I have to re-run abacus and redo a bunch of other things to fix this problem.

**Comment by emmats** [comment]
New table
https://drive.google.com/file/d/1KHMjdl10sg16MXh-8Jnng5_NDO8BIpC9/view?usp=sharing
