### ISSUE TITLE
Develop generic descriptors for protein expression clusters 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#639]
such that they can be binned. 

Pg larvae paper

**Comment by sr320** [comment]
Here is a first pass

![pic](http://gannet.fish.washington.edu/seashell/snaps/cluster-bin_2019-03-28_10-49-12.png)

**Comment by emmats** [comment]
What about this? I used Loess smoothing on the groups of proteins.
[clusters with loess smoothing v1 pH 7.5.pdf](https://github.com/RobertsLab/resources/files/3023990/clusters.with.loess.smoothing.v1.pH.7.5.pdf)

**Comment by emmats** [comment]
I've developed 5 categories based on patterns: 
1) stable throughout
2) multiple peaks
3) 1 peak
4) general decrease over time
5) general increase over time

**Comment by sr320** [comment]
Awesome
