### ISSUE TITLE
Publish PCSGA slidedecks

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#64]
for example on Figshare

**Comment by yaaminiv** [comment]
https://figshare.com/articles/PCSGA_2017_Exploring_Proteomic_Variation_in_Pacific_Oysters/5445616

**Comment by MeganHintz** [comment]
https://figshare.com/articles/Hintz_PCSGA_FINAL_pptx/5445622

**Comment by laurahspencer** [comment]
https://figshare.com/articles/Geoduck_as_indicators_of_environmental_change/5447302
