### ISSUE TITLE
Upload MS/MS proteomics data to PRIDE

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#640]
I found [.mzXML files](http://owl.fish.washington.edu/halfshell/working-directory/17-02-14/) and also [.raw files](http://owl.fish.washington.edu/phainopepla/C_gigas/2016-12-05/). Should be mzIdentML, mzTab, or PRIDE XML format, @yaaminiv @laurahspencer @emmats how what format did you submit, and if you converted your data, how did you do it? 
![Screen Shot 2019-03-26 at 9 55 53 AM](https://user-images.githubusercontent.com/4720221/55017147-5d9cbb80-4fad-11e9-8833-faf3d6d90c8c.png)

**Comment by laurahspencer** [comment]
I did the partial submission option, and uploaded the raw data (did not convert)

**Comment by emmats** [comment]
You can only do a partial submission for the pipeline we use. You will upload the .raw files and the pep.xml files from the Comet search (not from TPP). I always include the search database as well. You could also include a list of file names and descriptions, if you'd like.

**Comment by shellytrigg** [comment]
@emmats to clarify, is the pep.xml file [20161205_Sample_3.pep.xml](http://owl.fish.washington.edu/scaphapoda/Sean/Rhonda-2016-Oyster-Intermediates/20161205_Sample_3.pep.xml) or [interact-20161205_Sample_3.pep.xml](http://owl.fish.washington.edu/scaphapoda/Sean/Rhonda-2016-Oyster-Intermediates/interact-20161205_Sample_3.pep.xml)?

**Comment by emmats** [comment]
The ones without "interact". "Interact" are the results from TPP.

**Comment by grace-ac** [comment]
So, for the DIA 2015 project, would I just upload the [.raw](http://owl.fish.washington.edu/phainopepla/C_gigas/2015-12-30/) files? @emmats

**Comment by emmats** [comment]
You can look at the DIA dataset that I uploaded to pride before. You'll notice that I uploaded the .raw files and the percolator result files that you should have from running pecan.
<img width="1196" alt="Screen Shot 2019-03-26 at 3 33 18 PM" src="https://user-images.githubusercontent.com/4564812/55037996-b5065000-4fdc-11e9-8836-ba4878c596c5.png">
<img width="1282" alt="Screen Shot 2019-03-26 at 3 34 08 PM" src="https://user-images.githubusercontent.com/4564812/55037998-b6d01380-4fdc-11e9-95a8-a256ad3e50c7.png">

**Comment by shellytrigg** [comment]
Uploaded .raw, pep.xml, and .mzXML files to pride successfully as a partial submission
[PRIDE Submission Complete.pdf](https://github.com/RobertsLab/resources/files/3035694/PRIDE.Submission.Complete.pdf)

Accession number is :  PXD013262 , but is not public yet. @laurahspencer @emmats did you just contact the PRIDE people to make it public before the paper is submitted?

**Comment by emmats** [comment]
I think you can log on yourself and just press a button that will make it public.

**Comment by grace-ac** [comment]
@emmats I do not have the perolator files because I used Walnut instead of Pecan.

**Comment by emmats** [comment]
This sounds like something I ran into before....I'll try to figure it out this afternoon! If I can't, I'll have to talk to people in the lab next week.

**Comment by emmats** [comment]
I think to do this you have to run encyclopedia using command line and that should get you percolator outputs. I did do this for Yaamini, but I had to do a clean-up of files since then to make more space and so I don't have all my files anymore. I do have notes! I need to contact people in the lab to see if there is a way to run the current version of encyclopedia using command line.

Here are my annoyingly long notes on the process: https://www.evernote.com/l/APJJ42UsnXRDgLb3fTcPwJkv6Mj3rZebdEw
