### ISSUE TITLE
LC-MS/MS methods for larvae 2015 Lumos experiment

### ISSUE THREAD

**Issue by emmats** [RobertsLab/resources#641]
For @shellytrigg and @kaitlynrm 
I checked the .raw file and confirmed that the data were collected on the Lumos, in case there was still confusion.
Check out the methods in my WSG pub-a-thon paper to get an idea for what information you should include for the LC-MS/MS methods.
These screenshots should help you and contain all you need.
For MS1 - 
<img width="398" alt="Screen Shot 2019-03-26 at 3 48 14 PM" src="https://user-images.githubusercontent.com/4564812/55038856-673f1700-4fdf-11e9-985d-19ca04993ddb.png">

For MS2 - 
<img width="417" alt="Screen Shot 2019-03-26 at 3 49 02 PM" src="https://user-images.githubusercontent.com/4564812/55038876-77ef8d00-4fdf-11e9-9331-19d6694a7724.png">

Gradient - 
<img width="435" alt="Screen Shot 2019-03-26 at 3 49 30 PM" src="https://user-images.githubusercontent.com/4564812/55038889-7d4cd780-4fdf-11e9-98c3-d6fb74c4de08.png">
<img width="283" alt="Screen Shot 2019-03-26 at 3 49 42 PM" src="https://user-images.githubusercontent.com/4564812/55038896-80e05e80-4fdf-11e9-92c4-4ecf2333caf3.png">
<img width="264" alt="Screen Shot 2019-03-26 at 3 49 51 PM" src="https://user-images.githubusercontent.com/4564812/55038898-82aa2200-4fdf-11e9-99a5-b52185636de9.png">
<img width="267" alt="Screen Shot 2019-03-26 at 3 49 59 PM" src="https://user-images.githubusercontent.com/4564812/55038900-8473e580-4fdf-11e9-95c3-456ed85adaa4.png">
<img width="295" alt="Screen Shot 2019-03-26 at 3 50 08 PM" src="https://user-images.githubusercontent.com/4564812/55038907-8c338a00-4fdf-11e9-829c-04379488a7f1.png">
<img width="253" alt="Screen Shot 2019-03-26 at 3 50 16 PM" src="https://user-images.githubusercontent.com/4564812/55038909-905fa780-4fdf-11e9-8260-ce97d192e698.png">
<img width="314" alt="Screen Shot 2019-03-26 at 3 50 25 PM" src="https://user-images.githubusercontent.com/4564812/55038913-92296b00-4fdf-11e9-8e52-97d04ce5273d.png">

**Comment by kaitlynrm** [comment]
Awesome Emma, thank you!

**Comment by kaitlynrm** [comment]
@grace-ac I just realized this is probably for you since it's labelled for the 2015 experiment!
