### ISSUE TITLE
Comparing Cv and Cg transposable elements

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#643]
Presuming the same code were / are used to ID TEs in C virginica and C gigas.
Please generate a simple table where results can be easily compared..

**Comment by kubu4** [comment]
Running RepeatMasker on _C.gigas_ to get comparable stats.

**Comment by kubu4** [comment]
Google sheet:

https://docs.google.com/spreadsheets/d/1Or-zrbFAq2xl4iDNIJPJX0I9DWLtpa3m7gqDrFw-NT8/edit?usp=sharing
