### ISSUE TITLE
Submit geoduck 10x raw data to NCBI

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#644]

**Comment by kubu4** [comment]
Quick update. This is happening, but data transfer is _crawling_ from Owl to NCBI. These 10x FastQ files are very large and data transfer rates are ~1.6MB/s. 

I'd estimate that transfer, and subsequent SRA release, will be completed in ~3 days.

Will post accession number here, and in Nightingales, when available.

**Comment by kubu4** [comment]
Just providing update. Still transferring. My ETA was _way_ off. We'll be lucky if it's complete by the end of _this_ week....

**Comment by kubu4** [comment]
Another update. Still transferring. On the final group of files, though...

**Comment by kubu4** [comment]
Finally have an accession number.

[SRX5581791](https://www.ncbi.nlm.nih.gov/sra/SRX5581791) (under [BioProject PRJNA316601](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA316601))

This corresponds to the following files:

Geoduck-[1256]* in [nightingales](http://b.link/nightingales)

However, I just noticed these files in nightingales:

10x-Genomics-Libraries-Geo10x*

I'm uploading those now, too. Whoops! Sorry!

**Comment by kubu4** [comment]
Done. Adding SRA accessions to [nightingales](http://b.link/nightingales)

**Comment by sr320** [comment]
Ok I need some help deciphering this....

Here is what is in NCBI
https://d.pr/i/o1LhcG


I have a recollection (and code) that there were 4 files

```
/gscratch/srlab/programs/supernova-2.0.0/supernova run --id=Geoduck \
--fastqs=/gscratch/scrubbed/sr320/Chrom \
--sample=Geoduck-1,Geoduck-2,Geoduck-5,Geoduck-6
```

which I can see _maybe_ corresponding to https://www.ncbi.nlm.nih.gov/sra/SRX5581791[accn]

but not sure how the more recent 8 files play in

**Comment by kubu4** [comment]
Admittedly, I'm not sure either. Per my post above:

> Finally have an accession number.
> SRX5581791 (under BioProject PRJNA316601)
> This corresponds to the following files:
> Geoduck-[1256]* in nightingales
> However, I just noticed these files in nightingales:
> 10x-Genomics-Libraries-Geo10x*
> I'm uploading those now, too. Whoops! Sorry!

Basically, I just added additional "10x sequencing" that we had listed in Nightingales. 

Here's my notebook on data receipt:

https://robertslab.github.io/sams-notebook/2018/05/16/data-management-illumina-novaseq-geoduck-genome-sequencing.html

**Comment by kubu4** [comment]
Sorry, and yes, SRA accession SRX5581791 corresponds to those four samples: Geoduck-[1256]*

**Comment by sr320** [comment]
The notebook entry seems odd.

The genome is based on me providing the 10x assembly (Supernova) to Phase Genomics and they used that and their Hi-C data - though I suppose they sequencing of the Hi-C data could have been done by Illumina.

**Comment by sr320** [comment]
I think this might help
![pic](https://d.pr/i/y54l2b+)

link: https://d.pr/i/y54l2b

It would seem like most of the data is not Geoduck? and not sure 🤔 and concerned about the numbering of the four files used..

**Comment by sr320** [comment]
This is also likely relevant... https://d.pr/i/LwPTGG
The fact that a one laner was done. Not sure if we even used this?

**Comment by kubu4** [comment]
In [this post](https://github.com/RobertsLab/resources/issues/644#issuecomment-505454631), I'm fairly certain that table is referencing loading samples on a gel to evaluate molecular weight of the DNA. So, sample names from that table are not applicable to anything else.

**Comment by sr320** [comment]
>In this post, I'm fairly certain that table is referencing loading samples on a gel to evaluate molecular weight of the DNA. So, sample names from that table are not applicable to anything else.

Agree

**Comment by kubu4** [comment]
I'll look into this. 

I know that loading table would represent the goal of the project (from Illumina's perspective), which was to sequence an entire genome in a single NovaSeq run.

However, I'm not sure if that was actually done or not...

**Comment by sr320** [comment]
Origin of 
`--sample=Geoduck-1,Geoduck-2,Geoduck-5,Geoduck-6`

http://htmlpreview.github.io/?https://github.com/sr320/nb-2018/blob/master/P_generosa/01-10x-Chromium-explore.html

**Comment by kubu4** [comment]
OK, now I'm lost. 

What are we trying to figure out again?

**Comment by sr320** [comment]
Trying to confirm 10x raw data used for genome assembly is in NCBI.

and if there is more data in NCBI... be able to describe.

**Comment by sr320** [comment]
The 48 files `ls` at http://htmlpreview.github.io/?https://github.com/sr320/nb-2018/blob/master/P_generosa/01-10x-Chromium-explore.html

are what I consider the raw files - (what I used in supernova). Are these files in NCBI?

**Comment by kubu4** [comment]
> Are these files in NCBI?

Yes.

> SRA accession SRX5581791 corresponds to those four samples: Geoduck-[1256]*

**Comment by sr320** [comment]
Gotcha - so the 12 files per library are somehow compressed into a single file?

and  the `10x-Genomics-Libraries-Geo10x*` files are still a mystery as to their origin?

**Comment by kubu4** [comment]
> Gotcha - so the 12 files per library are somehow compressed into a single file?

Yep. When uploading to NCBI, you indicate a single "sample" and then upload all corresponding sequencing files for that sample. Then, they magically combine all sequencing files for a given sample.

>  10x-Genomics-Libraries-Geo10x* files are still a mystery as to their origin?

Sort of? My understanding is that they are 10x libraries sequenced on the NovaSeq.

**Comment by kubu4** [comment]
More info on those 10x-Genomics_Libraries-Geo10x* in this spreadsheet:

https://github.com/RobertsLab/project-geoduck-genome/blob/master/docs/20180403GeoDuckSamples.csv

**Comment by sr320** [comment]
>Sort of? My understanding is that they are 10x libraries sequenced on the NovaSeq.

I would agree. But would be good to find provenance. It would appear we have never used for anything.  
Will close as the issue is complete but will add Hackweek issue for us to try to decipher.
