### ISSUE TITLE
Can we remove .DS_Store files from GitHub repos?

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#645]
and if so how...

**Comment by kubu4** [comment]
Without testing, here's what I think needs to happen:

- Delete those files
- Add `.DS_Store` to ignore list
- Commit changes to ignore list

If the ignore list already has `.DS_Store` in it, remove it, save and commit changes to ignore list, add `.DS_Store` to ignore list, save and commit changes to ignore list.

**Comment by kubu4** [comment]
Looks like this is the way to do it:

From the root of the repo (e.g. `RobertsLab/resources`):

`git rm --cached /\*.DS_Store`

That would remove all `.DS_Store` files from the `resources` repo, but will _not_ delete them from your computer.

This will get all of those files within the repo. Then, make sure `.DS_Store` is in your ignore list.
