### ISSUE TITLE
Having trouble installing packages devtools and lfmm

### ISSUE THREAD

**Issue by kaitlynrm** [RobertsLab/resources#648]
I'm trying to work through the tutorial for `lfmm` (#633), but I'm having a lot of trouble installing the package.  `lfmm` must be installed via Github so the package `devtools` needs to be installed. Windows, Linux and Mac all have different requirements for installing `devtools`. Windows requires `Rtools`, which I have installed (Mac requires `Xcode`). `devtools` successfully loads for me and is in my packages tab in R, but I still cannot install `lfmm`. This is what I have tried so far:

```
#https://www.r-project.org/nosvn/pandoc/devtools.html
        #third command did not work, 
        #found stackoverflow saying this was outdated (https://community.rstudio.com/t/cant-install-devtools-on-windows-10/11730),
        #proceeded to this website
#https://cran.r-project.org/web/packages/devtools/readme/README.html

install.packages("processx")
install.packages("rlang")
install.packages("Rcpp")
install.packages("glue")
install.packages("devtools")

#install Rtools (b/c Windows) 
#https://cran.r-project.org/bin/windows/Rtools/
#Rtools 3.5 in C:/Rtools (did not install 32 bit files)

library(devtools)
devtools::install_github("r-lib/devtools") #some warnings saying "" package wasn't found and thus listed as topic

#devtools:load_all("R/win-library/3.5/") #highly suggested, didn't work- maybe wrong path?

devtools::install_github("hadley/devtools")
#Skipping install of 'devtools' from a github remote, the SHA1 (8b1b3fb7) has not changed since last install.
  #Use `force = TRUE` to force installation

devtools::install_github("hadley/devtools", force=TRUE)

devtools::install_github("r-lib/devtools", force=TRUE) #same warnings as before

devtools::install_github("bcm-uga/lfmm") 
#Downloading GitHub repo bcm-uga/lfmm@master
#Prompts to ask permission to find new tools, say yes,
#Error: Could not find tools necessary to compile a package
```
---
_If you try to just run_ `install.packages("lfmm")`, _the error:_
`Installing package into ‘C:/Users/Katty/R/win-library/3.5’`
`(as ‘lib’ is unspecified)`
`Warning in install.packages :`
  `package ‘lfmm’ is not available (for R version 3.5.3)` _will come up._

**Comment by kubu4** [comment]
> package ‘lfmm’ is not available (for R version 3.5.3)

Isn't this the answer? You're running R version 3.5.3 and the package isn't available for that version of R.

**Comment by kaitlynrm** [comment]
That seems likely! Previously I was running 3.5.2 and updated because of that error. I can't find anything about which R version will work with this package. Maybe I'm missing it in the [Github repo](https://github.com/bcm-uga/lfmm/blob/master/R/lfmm.R)? Or I need to use [`LEA`](http://membres-timc.imag.fr/Olivier.Francois/lfmm/software.htm)?

**Comment by kubu4** [comment]
Based on the last time this program was updated (Feb 2018 is last commit), I'd guess you'd need to be running  a 3.4.n version of R:

https://cran.r-project.org/bin/windows/base/old/

**Comment by kaitlynrm** [comment]
Should I do a release prior to February 2017 (last commit)? That would mean a 3.3.2 or less version.

**Comment by kubu4** [comment]
Latest commit is Feb 2018: https://github.com/bcm-uga/lfmm/commit/5411c350280500d3ed561b021c51dddd55951fa6

**Comment by kaitlynrm** [comment]
Update to this problem: running R version 3.4.4 (`devtools` requires at least 3.4.4) however there is now a new issue:
![R_error](https://user-images.githubusercontent.com/26392677/55183758-c458db00-514d-11e9-9c56-e2f7f394621d.JPG)

and `rrcp` and thus `devtools` won't load.
