### ISSUE TITLE
Install Macau on a R Studio Server

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#649]
http://www.xzlab.org/software/macau/MACAU-R-Manual.pdf

**Comment by kubu4** [comment]
I've spent a fair amount of time looking into this and it's not feasible on a "system-wide" level for users using R Studio Server. However, this type of control _is_ available on R Studio Server Pro (paid).

So, each person will need to install for themselves. :(

**Comment by sr320** [comment]
Let’s pay

thanks
Steven


Steven B. Roberts
Kenneth K. Chew Endowed Professor
School of Aquatic and Fishery Sciences
University of Washington, Seattle WA
sr320@uw.edu - 206.866.5141
robertslab.info - @sr320

**Comment by kubu4** [comment]
OK... It might be expensive. I'll get a quote.

**Comment by kubu4** [comment]
There's definitely an academic discount of sorts, but pricing for Pro for non-academic users is listed $10,000/yr/server.

**Comment by sr320** [comment]
Wow- not expecting that
