### ISSUE TITLE
Troubleshoot audio issue in FTR 230

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#65]

**Comment by sr320** [comment]
@grace-ac or anyone 
can you try joining video call now at

https://washington.zoom.us/j/770782548

**Comment by sr320** [comment]
Ok we could not reproduce issues, - but if anyone else wants to call in I will leave it open for a bit

**Comment by kubu4** [comment]
I know this is already close, but do you want to retry on Friday? I'll be working at home. Maybe audio fails only when there are off-campus connections?

**Comment by sr320** [comment]
That would be great.
