### ISSUE TITLE
Organization tips/tricks

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#655]
Need some tips and tricks for keeping organized, particularly since I'm now trying to keep track of Issues that exist across multiple repos.

Do people use To Do lists? If yes, which ones? Have you/can you integrate them in Slack?

I've started a To Do private channel in Slack, but I find it to be a bit lacking/clunky.

Basically, I need/want something that I can integrate with Slack so that I don't have to look hard to find my To Do lists. I'd also like something that somehow integrates with GitHub Issues, so that I can quickly and easily add GitHub Issues to a To Do list.

**Comment by sr320** [comment]
I use Todoist- and anything assigned to me shows up there-
Could probably do same with slack via IFTTT.

It would seem there might me somewhere on GitHub where one should be able to find all assigned / opened issues?

**Comment by kubu4** [comment]
Have you added Todoist to Slack? If yes, how do you like the integration?

**Comment by sr320** [comment]
https://github.com/issues/assigned

**Comment by sr320** [comment]
I have not

**Comment by kubu4** [comment]
Thanks for feedback here and in lab meeting today.

Well, here's what I've decided to do:

- Todoist
  - Combine with IFTTT to automatically send GitHub issues assigned to me to designated "project" in Todoist
  - Use browser extension/add-on to send emails to Todoist
  - Slack Todoist app to quickly send Slack stuff to Todoist
    - Includes being able to send unassigned GitHub Issues to Todoist
