### ISSUE TITLE
Illumina authorship/acknowledgement

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#657]
Email out to Cindy Lawley.

Earlier emails from Cindy, and confirmed by @sr320, indicate we need to add Illumina R&D people as co-authors:

Cindy's email from Dec 20, 2016:
>... I would request that Jon be included as a coauthor as he will be driving this internally.
Steven I look forward to seeing you at PAG. 
If you gain additional information on the timing of the FAANG meeting, I would be very interested in trying to attend.  
In addition if you have a document that you can share that provides more detail on the "why geoduck are so important" aspects, that would save me some time in digging up references and be helpful for me to help others understand this priority..
Many many thanks for your time.
Stacy please jump in if I have missed anything!

Steven's response:

> Hi Cindy,
Thanks for reaching out to us and considering the shellfish. Sam will send down the samples and of course Jon and any others will be co-authors.
I will let you know about the salmon meeting.
Here is some info regarding the geoduck..

Current list of Illumina co-authors:

- Jon Hetzel

- Aparna Natarajan

- Erich Jaeger

**Comment by kubu4** [comment]
Cindy has indicated she would like to be involved in the manuscript. I will add her to any email exchanges going forward.

She's also going to send a list of Illumina people that she thinks should be potential co-authors.

**Comment by kubu4** [comment]
Additional info:

- Jonathan Soohoo

- Mike Deras (acknowledgement)

- Stacy Musone (acknowledgement)

**Comment by sr320** [comment]
@kubu4 can you add this into the manuscript? https://docs.google.com/document/d/10Wmr_ceODWreZfS8WPekvoBwD2xEqlq28iSitapHTHA/edit

**Comment by kubu4** [comment]
added.
