### ISSUE TITLE
Why 4 files per sample? DIA 2015 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#659]
http://owl.fish.washington.edu/phainopepla/C_gigas/2015-12-30/ 

Why are there four files per sample again? I forget... sorry

**Comment by emmats** [comment]
They cover different parts of the mass range. It's the same as the 2017 geoduck paper DIA protocol. 400-525 m/z, 535-650 m/z, 650-775 m/z, 775-900 m/z. If this still doesn't make sense, let me know.

**Comment by sr320** [comment]
@emmats so how do we handle the data - right now we have "area" for each range - do we simply sum these "areas" and consider these abundance? Or average?

**Comment by emmats** [comment]
They should be imported into skyline such that skyline combines them into single samples. There is a format of nested directories for storing the data for import into skyline so that the program realizes all 4 file are fractionations of a single sample. Keeping them separate is not how you should analyze them.

This should hopefully sound familiar.

**Comment by grace-ac** [comment]
![Screen Shot 2019-04-02 at 3 48 41 PM](https://user-images.githubusercontent.com/14934314/55441209-ddeb8f80-555e-11e9-979a-88c9cc597775.png)


yes, in skyline i combined the four files for each sample. 

but the skyline report looks like this (files are separate rows):   https://github.com/grace-ac/paper-pacific.oyster-larvae/blob/master/data/20181218-SkytoMSstats-report.csv

**Comment by emmats** [comment]
you should not have to combine them. you should import them from a directory such that skyline automatically combines them, recognizing that they are all one sample.

**Comment by emmats** [comment]
Maybe there is a problem with your export settings?

**Comment by grace-ac** [comment]
Ah, ok. I followed the export settings required for MS stats. 

I'll go figure this out in skyline

**Comment by grace-ac** [comment]
I figured it out pretty easily (just have to select "Replicate Name" and not select "File Name")

I'm wondering what all is important to compare. 

I know I need:    
Protein Name
Replicate Name 
Condition (tells me 23C or 29C)

For MSstats I used Transition Results Summary Area

### Are the area data I need "Transition Results Summary " Area? 
### Any other important information to compare the two temperature treatments? 
Peptide sequence... etc.

**Comment by emmats** [comment]
This sounds like a question for the MS stats discussion board. I haven't used it in years. Sorry!

**Comment by sr320** [comment]
Let’s not be concern about MSStats - just get sound, accurate protein abundance for the 4 libraries

thanks
Steven

**Comment by sr320** [comment]
But it is important to state 
>400-525 m/z, 535-650 m/z, 650-775 m/z, 775-900 m/z 
info in regards to methods

**Comment by grace-ac** [comment]
yeah, i shouldn't have mentioned MS stats in this issue... i was trying to use it for context to figure out what I should export for comparing 23C and 29C. 

Anyway, I made a new report: http://owl.fish.washington.edu/scaphapoda/grace/2015-Cgseed-DIA/20190403-Cgseed-report.csv 

It has Replicate Name, Condition (temp), Protein Name, and Area

**Comment by grace-ac** [comment]
new reports are in [repo](https://github.com/grace-ac/paper-pacific.oyster-larvae/tree/master/data)

[new MSstats report](https://github.com/grace-ac/paper-pacific.oyster-larvae/blob/master/data/20190403-MSstats-report.csv.zip) (will re-do MS stats with this report)

[new report for comparing 23C and 29C](https://github.com/grace-ac/paper-pacific.oyster-larvae/blob/master/data/0403-DIA-Cgseed.csv)
