### ISSUE TITLE
SRM Analysis wiki

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#66]
Planning on updating [this page](https://github.com/sr320/LabDocs/wiki/SRM-data-Analyses) in the old LabDocs repo.

@kubu4 / @sr320 is there anywhere else I should write this instead, or should I just update this page and worry about moving it over to the new resources repo later?

**Comment by sr320** [comment]
That has been moved to
https://github.com/RobertsLab/resources/blob/master/protocols/SRM-data-Analyses.md
