### ISSUE TITLE
Re-do GO analysis/Cytoscape including proteins from updated clustering analysis

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#660]
@kaitlynrm can you add a link to the updated list of proteins from clustering analysis that excludes day 0?

**Comment by shellytrigg** [comment]
@kaitlynrm can you update supplementary figure 2?

**Comment by kaitlynrm** [comment]
[Updated list of proteins without day 0](https://github.com/kaitlynrm/OysterSeedProject/blob/master/analysis/clustering/silo3_9-NSAF/euclidean/150unique-prot.csv)
