### ISSUE TITLE
Compare 23C and 29C: 2015 C.g. seed DIA

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#661]
[R script](https://github.com/grace-ac/paper-pacific.oyster-larvae/blob/master/scripts/23Cv29C_skyoutput.R) so far...

There are 4 samples (Oytserseed_01, Oysterseed_02, Oysterseed_13, and Oysterseed_14)     
Each sample has 4 files associated with it ([post](https://grace-ac.github.io/2015-DIA-Oysterseed-new-info/)):      
![Screen Shot 2019-04-02 at 3 27 48 PM](https://user-images.githubusercontent.com/14934314/55440301-09b94600-555c-11e9-8d2d-2a17ef082265.png)

Reason for four files per sample: #659 
>They cover different parts of the mass range. It's the same as the 2017 geoduck paper DIA protocol. 400-525 m/z, 535-650 m/z, 650-775 m/z, 775-900 m/z. If this still doesn't make sense, let me know.

R script linked above takes the [skyline output](https://github.com/grace-ac/paper-pacific.oyster-larvae/blob/master/data/20181218-SkytoMSstats-report.csv), pulls out columns of interest, and then makes that 5-column version an object in R. 

### Goal is to compare the 23C and 29C treatments (Condition column)

want to reformat file so that each row is a protein, with the different "File.Name"s as columns and cell contents being the "Area"

**Comment by grace-ac** [comment]
new report: http://owl.fish.washington.edu/scaphapoda/grace/2015-Cgseed-DIA/20190403-Cgseed-report.csv

**Comment by kubu4** [comment]
Can you please add new report to repo/R Project?

**Comment by grace-ac** [comment]
going a different route. will post new issue
