### ISSUE TITLE
Find best Transcriptome Amplification Kit for library prep

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#662]

**Comment by kubu4** [comment]
Here's what I've come up with so far:

- https://www.sigmaaldrich.com/life-science/molecular-biology/whole-genome-amplification/seqr-rna-amplification.html

- https://www.qiagen.com/us/shop/sequencing/qiaseq-fx-single-cell-rna-library-kit/?akamai-feo=off&clear=true#productdetails

- This one is the one Illumina uses as part of their pipeline: https://www.takarabio.com/products/next-generation-sequencing/single-cell-rna-and-dna-seq/smart-seq-v4-for-mrna-seq?catalog=634888
