### ISSUE TITLE
ID low input RNA extraction kits 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#663]

**Comment by sr320** [comment]
@grace-ac - work with @kubu4 to get some kits ordered today please 61-1553

**Comment by grace-ac** [comment]
There's a free sample from [zymo](https://www.zymoresearch.com/collections/quick-dna-rna-kits/products/quick-dna-rna-microprep-plus-kit?utm_campaign=dnarna_4.3.19&utm_medium=email&utm_source=newsletter&_ke=eyJrbF9lbWFpbCI6ICJwYW0uamVuc2VuQG5vYWEuZ292IiwgImtsX2NvbXBhbnlfaWQiOiAiSmFQTXVjIn0%3D) coming soon that @kubu4 requested last week. 

I will look into other kits and talk with @kubu4

**Comment by grace-ac** [comment]
[PicoPure RNA Isolation Kit](https://www.thermofisher.com/order/catalog/product/KIT0204)

**Comment by sr320** [comment]
@kubu4 could you run a few samples with zymo kit? - @grace-ac give him a few from the last 12 - including any that had RNA.

**Comment by kubu4** [comment]
This might be another good option (particularly for dealing with "difficult" samples):

[Zymo RNA Fecal and Soil Microbe Microprep Kit](https://www.zymoresearch.com/products/quick-rna-fecal-soil-microbe-microprep-kit)

**Comment by sr320** [comment]
Think we can get sample?

thanks
Steven

**Comment by kubu4** [comment]
Maybe... However, Zymo usually lists free sample kits when they're available. No sample kit option is listed for this one.

**Comment by kubu4** [comment]
> @kubu4 could you run a few samples with zymo kit? - @grace-ac give him a few from the last 12 - including any that had RNA.

Heads up. Sample kit only contains 10 preps.

**Comment by sr320** [comment]
Go ahead and order the smaller soil kit- number in issue-


thanks
Steven

**Comment by grace-ac** [comment]
@kubu4 
-80 Rack 7, col 2, row 2 
10 tubes set aside for you!    
![IMG_6047](https://user-images.githubusercontent.com/14934314/55986989-6ea82680-5c55-11e9-9213-99236c256c78.JPG)

**Comment by kubu4** [comment]
Thanks. Need a bit more info.

What do I need to do to repeat what you did (but with this new kit)?

**Comment by sr320** [comment]
The hope is you could get RNA from these 10 samples

thanks
Steven

**Comment by grace-ac** [comment]
here's how I prepped the samples before using with RNeasy:   
let the tubes thaw on ice      
vortex to mix the slurry       
sample out 15ul of the slurry and use that for extraction

**Comment by kubu4** [comment]
Well, everything turned out great!

| SampleID | Concentration (ng/uL) |
|----------|-----------------------|
| 31       | 6.24                  |
| 142      | 9.2                   |
| 285      | 9.92                  |
| 291      | 3.49                  |
| 317      | 10.1                  |
| 326      | 11.6                  |
| 419      | 8.28                  |
| 455      | 7.2                   |
| 503      | 7.64                  |
| 506      | 15.6                  |

Here's my notebook:

- 

I've ordered two of those kits (i.e. 100 preps).

**Comment by kubu4** [comment]
Also, I'd consider using a larger input volume to increase yields...
