### ISSUE TITLE
Exporting Protein level data from Skyline

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#666]
Is there a way to export protein level data from Skyline - that is already integrating transition and peptide data?

**Comment by sr320** [comment]
Or in otherwords, how do we get protein level abundance for each protein?

**Comment by sr320** [comment]
from @laurahspencer paper

>Transition peak area, which is assumed to correlate to peptide transition abundance, was exported from Skyline for analysis in R version 2.4-3 (R Core Team, 2016). Abundance was normalized by the total ion current (TIC) for each injection.

**Comment by emmats** [comment]
grace - do not normalize by TIC. I don't think that is necessary for your project.

From Nick:
We don't have any such value at the protein level. Mike and Brendan keep telling me to add it.

It is possible to get Skyline to sum the precursor areas to get a protein level area, using the Pivot Editor, which is the button next to the Views drop-down on the Document Grid.

Let me know if you need a Pivot Editor demo.

**Comment by grace-ac** [comment]
@yaaminiv  and I were talking yesterday and she said this (correct me if i'm wrong):  

exclude proteins with less than 3 peptides     
for proteins that have more than 3 peptides, use the three most abundant 

---
So i think we can do this with the report that was exported yesterday... [0403-DIA-Cgseed.csv](https://github.com/grace-ac/paper-pacific.oyster-larvae/blob/master/data/0403-DIA-Cgseed.csv)

**Comment by yaaminiv** [comment]
Thinking about what I said yesterday...that's the criteria I used for SRM target selection. Not sure if the same specificity applies to you!

**Comment by emmats** [comment]
If you wanted to do that, you could argue that you don't have confidence that you actually detected a protein if only 1-2 peptides were found in the DIA experiment. And we did discuss that using the 3 most abundant peptides for abundance is a possibility, and I think preferred by some people. Low abundance peptides may not be detected reliably and could just result in extra noise. Does it say anything in the DIA pipeline document from the MacCoss lab about this?

**Comment by yaaminiv** [comment]
^

You also may want to exclude any peptides/proteins with significant interference from your analyses for similar reasons.

**Comment by sr320** [comment]
I think we are just going to go with MSstats output - it provides logfoldchange values for all proteins excluding all peptides that provide multiple hits...
