### ISSUE TITLE
Should we be concerned about non-target species proteomic data

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#667]
For instance 
![ec](http://gannet.fish.washington.edu/seashell/snaps/0403-DIA-Cgseed_2019-04-03_17-39-47.png)

Why are we adding these to database?

**Comment by emmats** [comment]
Those are common lab contaminants and should just be removed from the analysis.

**Comment by sr320** [comment]
Why include them in the database - to remove them if they hit multiple proteins (which would make sense)

**Comment by emmats** [comment]
We include them so that contaminating peptides don't erroneously get assigned to an oyster protein. It's makes for a more robust and accurate search space. I rarely find that peptides overlap between contaminant and target proteins, but it does happen. For DDA, abacus takes care of that confusion.
