### ISSUE TITLE
Peptide data corresponding to multiple proteins?

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#668]
Does it make sense for the same peptide data to be associated with numerous proteins?

![d](http://gannet.fish.washington.edu/seashell/snaps/0403-DIA-Cgseed_2019-04-03_17-55-30.png)

**Comment by emmats** [comment]
Sometimes peptides are found in more than one protein. You can tell Skyline that you only want to keep peptides that are uniquely found in a single protein.

**Comment by sr320** [comment]
I think sometimes is an understatement :) - We have data on +7000 proteins but when removing multiple hits - 2000
