### ISSUE TITLE
Oly Session talks at NSA?

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#67]
Deadline for titles for Oly session is tomorrow?
What are folks thinking about presenting?

**Comment by laurahspencer** [comment]
I'm planning on submitting my Manchester Oly experiment, currently thinking about titles:
  * Family matters: effect of dual climate stressors varies between Puget Sound populations
  * From fecundity to survival: effects of dual climate stressors on Puget Sound Olympia oysters

**Comment by sr320** [comment]
Family matters: effect of temperature and pH varies between Puget Sound Olympia oyster

???

**Comment by laurahspencer** [comment]
Are you asking what this title refers to?

The larval production & survival patterns by treatments differ between populations. Need more analysis but figured this was OK for session planning purposes.

**Comment by sr320** [comment]
I was suggesting that revisions and asking what you thought.

**Comment by laurahspencer** [comment]
Oh I see- I submitted to Kay already, but will likely revise prior to submitting to NSA. Thanks!
