### ISSUE TITLE
where do i publish skyline .zip file? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#670]

**Comment by yaaminiv** [comment]
Skyline files go on [Panorama Public](https://panoramaweb.org/project/Panorama%20Public/begin.view?). @laurahspencer is the admin for the Roberts Lab section on Panorama, so she can give you permission to upload your file there.

**Comment by laurahspencer** [comment]
I just created an account for you, Grace, under graceac9@uw.edu - you should have received an email, and have full access to the section.

**Comment by grace-ac** [comment]
got it! thank you @laurahspencer
