### ISSUE TITLE
Difference between DML lists

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#672]
There is a discrepancy between the number of DML @sr320 and I obtained. I think it's because there are differences in our R code.

My list: http://gannet.fish.washington.edu/spartina/2018-10-10-project-virginica-oa-Large-Files/2019-03-07-Yaamini-Virginica-Repository/analyses/2018-10-25-MethylKit/2019-03-13-DML-Destrand-5x-Locations.bed
code: https://github.com/epigeneticstoocean/paper-gonad-meth/blob/master/code/04-methylkit.Rmd

Steven's list: https://github.com/sr320/nb-2019/blob/master/C_virginica/analyses/dml52.bed
code: https://github.com/epigeneticstoocean/paper-gonad-meth/blob/master/code/methylkit_sr.Rmd

The first thing I see is a difference in `processBismarkAln`. I used `mincov = 5`, while Steven used `mincov = 2`. Additionally, I used `assembly = v3`, and Steven used `assembly = v001`.

- Mine: `processBismarkAln(location = analysisFiles, sample.id = sample.IDs, assembly = "v3", read.context = "CpG", mincov = 5, treatment = treatmentSpecification)`
- Steven's: `processBismarkAln(location = file.list_10, sample.id = list("1","2","3","4","5","6","7","8","9","10"), assembly = "v001", read.context="CpG", mincov=2, treatment = c(0,0,0,0,0,1,1,1,1,1))`

Steven also uses this extra filtering step while I do not:

`filtered.myobj=filterByCoverage(myobj_10,lo.count=5,lo.perc=NULL, hi.count=100,hi.perc=NULL)`

Both of these discrepancies could affect the number of DML and which DML are identified. Which method is "correct"?

**Comment by sr320** [comment]
Go ahead and set `mincov = 2`, and use `filterbyCoverage` - note `hi.count` is something recent I was playing with and did not necessarily contribute to bed.

**Comment by yaaminiv** [comment]
Why would I set `mincov = 2` if our goal is `mincov = 5`?

**Comment by sr320** [comment]
You set coverage in filterByCoverage
As this also provides ability to make hi end threshold.
Code wise you only have to make object once - this is what takes the longest; then you can easily further tweak with  filterByCoverage.
Thus provides more flexibility.

**Comment by yaaminiv** [comment]
Would `assembly` differences also affect DML?

**Comment by sr320** [comment]
no - that is just naming

**Comment by yaaminiv** [comment]
I now get 598 DML: https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2018-10-25-MethylKit/2018-10-25-Loci-Analysis/2019-04-05-Differentially-Methylated-Loci-Filtered-Destrand-50-Cov5.csv
