### ISSUE TITLE
how to make tables in GitHub.io look good? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#673]
### My tables look great [here](https://github.com/grace-ac/grace-ac.github.io/blob/master/_posts/2019-04-03-bairdi-RNA-RNeasy.md):      
   
![Screen Shot 2019-04-05 at 11 05 37 AM](https://user-images.githubusercontent.com/14934314/55647716-3dca7c00-5793-11e9-86f3-7f1f3cb593b4.png)

### But on [grace-ac.github.io](https://grace-ac.github.io/bairdi-RNA-RNeasy/)... they are a big mess.           

![Screen Shot 2019-04-05 at 11 06 05 AM](https://user-images.githubusercontent.com/14934314/55647779-65b9df80-5793-11e9-9785-b34a2bafdacd.png)

**Comment by kubu4** [comment]
That's the way a table looks in the Markdown (i.e. text) format. You could use a Markdown table generator (available online) to make a better looking Markdown layout with equal spacing for columns and whatnot. However, that might not help viewing if your table width is wider than your screen; the text will be wrapped and won't line up any more.

With all that said, the Markdown text will get rendered into a nice looking table no matter what, once you view it in your published notebook.

**Comment by sr320** [comment]
Problem is - it is not rendering in published notebook - something to do with markdown flavors

**Comment by kubu4** [comment]
Oh, whoops! Didn't click on links. MB.

**Comment by sr320** [comment]
I just did a pr https://github.com/grace-ac/grace-ac.github.io/pull/8

accept that and let me see

**Comment by sr320** [comment]
just did another PR

should be good.

All you need was space after header. 

this works

```
### Prepping samples

| Tube number | Sample Day | Infection status | Temp trtmnt |
|-------------|------------|------------------|-------------|
| 135         | 9          | 0                | NA          |
| 90          | 9          | 1                | NA          |
| 317         | 12         | 0                | Amb         |
| 352         | 12         | 1                | Amb         |
| 242         | 12         | 0                | Cold        |
| 234         | 12         | 1                | Cold        |
| 285         | 12         | 0                | Warm        |
| 271         | 12         | 1                | Warm        |
| 499         | 26         | 0                | Amb         |
| 468         | 26         | 1                | Amb         |
| 458         | 26         | 0                | Cold        |
| 438         | 26         | 1                | Cold        |
```

Not as pretty but readable!

**Comment by grace-ac** [comment]
Thanks!
