### ISSUE TITLE
SAFS Open House Activity

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#676]
I signed us up for the SAFS open house again. We need an activity title/information by 4/19. 

I thought we could have a similar set-up to last year with a ppt introducing the lab and larvae of some sort for people to look at. Instead of doing something oyster-based, what if we had an activity about geoduck?

Open to other ideas for activities as well!

**Comment by shellytrigg** [comment]
I asked @SamGurr about broodstock and juvenile geoduck availability for this. 

In lab meeting today @kubu4 mentioned displaying APEX data to show how we can manipulate/monitor seawater chemistry. 

We also have gonad tissue microscope slides that look pretty cool. We could hook up a phone to microscope so it's easier for people to look at

**Comment by kubu4** [comment]
- A slide show of images with descriptions of geoduck farming techniques (I bet most people have no idea how it's conducted). 

    - Include video from @shellytrigg and @kaitlynrm sampling hemolymph.

**Comment by sr320** [comment]
maybe this could inspire us to get that new tv monitor

thanks
Steven

**Comment by kaitlynrm** [comment]
These ideas sound really cool and I think it would be nice to show the connection between them through our display:

- We could do a picture of a geoduck with a shell or two for people to touch, 
- then next to it a large picture of the apex data to show how we manipulate and monitor environmental conditions
- and a scope with histo slides below/in front of the apex data to show the impact of environmental manipulation on reproduction

If we could get juvenile geoduck we could either have it/them under a dissecting scope or broadcast it to a monitor as well to round out the whole thing, or if not we could post images of juveniles/larvae (we have some on the FFAR drive).

**Comment by SamGurr** [comment]
Hi everyone,

There are juvenile geoduck about 10mm shell length available for this at
the hatchery from last summer. I also do not see any issues with you taking
a couple live broodstock - especially since the hatchery is now focused on
setting and done with larvae.

Best
Sam

Best,
Sam

**Comment by shellytrigg** [comment]
To clarify, this open house event is taking place May 4.

**Comment by grace-ac** [comment]
@shellytrigg  
please add some info about yourself and some images to your slide, modeling after the other people slides 
[2019 Open House slidedeck](https://docs.google.com/presentation/d/15eKvP94WdD0lp11TcwwKn7O19s1QDsF5czL2jzSQHjI/edit?usp=sharing)

**Comment by shellytrigg** [comment]
@grace-ac done!

**Comment by grace-ac** [comment]
@shellytrigg @kaitlynrm 
what do you two think about bringing back larvae for the open house when you go to Pt Whitney tomorrow? 
---
I think the activity for the open house will hopefully involve:    
- histo slides - **microscope 1**
- live larvae - **microscope 2**
- shells 
- slideshow (includes hemolymph sampling video and out planting video; farming techniques; basic geoduck facts; people in lab slides) - **monitor**

**Comment by shellytrigg** [comment]
@grace-ac the plan is to bring back a couple juveniles and a couple broodstock tomorrow.

**Comment by grace-ac** [comment]
@shellytrigg thanks!!! sorry if i missed that...

**Comment by shellytrigg** [comment]
@grace-ac you didn't, it wasn't solidly confirmed. When we get back tomorrow, I'll set them up in the recirc table in the basement

**Comment by shellytrigg** [comment]
@laurahspencer  helped me figure out the aquarium set up for the broodstock and commercial setters for Saturday. I'll hold the broodstock in the aquarium room and setters in the teaching lab from Tomorrow evening until then. I have a monitor that we can use for a display. Here is [a link to a video of a Dhinge sorting](https://drive.google.com/drive/u/1/folders/1UxPo0TeS6otU9GWeX-uKCeNZoIIEQUJn) and [a drive folder with some other pics and video showing broadcast spawning](https://drive.google.com/drive/u/1/folders/1UxPo0TeS6otU9GWeX-uKCeNZoIIEQUJn).

**Comment by shellytrigg** [comment]
animals (2 broodstock, 2 1yr-juveniles, and 2 90dpf-juveniles) are all in the aquarium table in the FSH basement and are doing OK as of this AM. 
![IMG_20190502_182742](https://user-images.githubusercontent.com/4720221/57152302-f0d4c800-6d87-11e9-931a-1a2347ae56da.jpg). @grace-ac [here is some more cool juvenile footage from yesterday](https://drive.google.com/open?id=1N1P5KMauEEPYrQLlSek6LCLM9C5-k4id) and [folder with other footage and images from yesterday](https://drive.google.com/drive/u/1/folders/18TtfFRd9Y4MXX7dKQENXiSkm64ZqlrPe)

**Comment by grace-ac** [comment]
@yaaminiv @laurahspencer @shellytrigg 
Please take a look at the slides so far and make any edits/additions as you see fit! 

**still a slight work in progress**

https://docs.google.com/presentation/d/15eKvP94WdD0lp11TcwwKn7O19s1QDsF5czL2jzSQHjI/edit#slide=id.g51430f587b_0_20

**Comment by laurahspencer** [comment]
Here are a few more geoduck-related things if you need one. The first link is a nice video of geoduck larvae feeding: 

https://drive.google.com/file/d/13DG6_13i2EyqK_TrNBx3m_zeaPmdgGt6/view?usp=sharing
https://drive.google.com/open?id=1srlOVvqIe0U7HbULcZV7TA8ogKf4jAxL
https://drive.google.com/file/d/1-m3_FqIlyVKo-S6fqlWZpRjwpyZbHdJg/view?usp=sharing

**Comment by yaaminiv** [comment]
@grace-ac Just made some of the text bigger, but it looks great!!!
