### ISSUE TITLE
how to remove "" from object in jupyter notebook

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#677]
[raw data](https://raw.githubusercontent.com/grace-ac/paper-pacific.oyster-larvae/master/data/20190403-2015Cgseed-protcomp.csv) has "" around column names, all protein names (contents of column 1) and all cells in the column "Label"

![raw](https://user-images.githubusercontent.com/14934314/55842676-6cc15480-5ae9-11e9-83e5-c30060c73deb.png)

[Jupyter notebook](https://github.com/grace-ac/paper-pacific.oyster-larvae/blob/master/notebooks/02-detected-prots-annotate-GOslim.ipynb)
![Screen Shot 2019-04-09 at 4 59 52 PM](https://user-images.githubusercontent.com/14934314/55842683-734fcc00-5ae9-11e9-9da1-0b9f8935843e.png)

Trying to annotate protein list from MS Stats (the .raw data link above) with GOslim terms. I won't be able to if ProteinName column has "" around each one.

**Comment by sr320** [comment]
`sed 's/"//g'`

see https://github.com/sr320/nb-2019/blob/master/C_gigas/02-larvae-annotation.ipynb for example where I changed comma to tabs
removed "
removed first line (titles)
and sorted



```
!cat data/20190403-2015Cgseed-protcomp.csv | tr ',' "\t" \
| sed 's/"//g' \
| tail -n +2 \
| sort \
> analyses/20190403-2015Cgseed-protcomp.tab
```

**Comment by sr320** [comment]
and FTR I did not just know this but went to 
https://github.com/RobertsLab/code/blob/master/bash.md
to remind myself how to do all of these things.

**Comment by grace-ac** [comment]
thank you! forgot we had the code repo.
