### ISSUE TITLE
large amounts of data for supplemental file

### ISSUE THREAD

**Issue by emmats** [RobertsLab/resources#679]
I did a bunch of enrichment analyses (>30?) for the geoduck larvae paper. I have .txt tables and graphics as results for each analysis. Any suggestions on how to present these as supplemental files? I could create a large excel workbook for the tables and a power point for the graphics. It just all seems really bulky. Do I even need to provide them if I provide the input files and the url for generating the results?

**Comment by sr320** [comment]
.txt and images in github repo-
Always best to avoid proprietary formats

thanks
Steven

**Comment by emmats** [comment]
I guess I'll have to figure out how to make a repo. Yay!

**Comment by sr320** [comment]
I already made the repo
And populated

thanks
Steven

**Comment by emmats** [comment]
But I was just in the process of making it and uploading my hundreds of files....
Where is your repo?

**Comment by sr320** [comment]
https://github.com/sr320/paper-Pg-larvae-2019

(What do you think I been doing with all to code and data I have been asking for :)

**Comment by emmats** [comment]
Well, I guess you weren't just gazing at it in admiration.
