### ISSUE TITLE
Low battery alarm on -80

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#68]
I suppose this means we need to purchase a batter?

**Comment by kubu4** [comment]
Maybe, maybe not. The battery is just used for the alarm on the freezer itself; it serves no other purpose.

**Comment by sr320** [comment]
@grace-ac 
Can you please purchase a battery.

**Comment by grace-ac** [comment]
Got it! It's now $151.17

Budget number @sr320 ?

**Comment by sr320** [comment]
61-0221

**Comment by grace-ac** [comment]
are you here today still, @sr320 ? I need an authorization signature.

**Comment by sr320** [comment]
No -you can email it to me or I will be in tomorrow

**Comment by grace-ac** [comment]
Ok! I will be in tomorrow morning, so we can finish this then.

**Comment by kubu4** [comment]
@grace-ac - Actually, current price is $119.16. 

Sorry I couldn't grab it earlier, was swamped.

**Comment by grace-ac** [comment]
@kubu4 Oh! Is it cheaper because it's purchased through UW, like the Genesee boxes?

**Comment by grace-ac** [comment]
@kubu4 Saw your new issue - got it!
