### ISSUE TITLE
Removing text using sed

### ISSUE THREAD

**Issue by emmats** [RobertsLab/resources#681]
I'm trying to remove a string of characters from every line of a fasta using sed. Each string starts with ">k141_" but is then followed but multiple characters.  The closest I can get is to remove ">k141_" with the following:
sed -e ’s/<k141_*//' 20190103-mgm-proteins.fa > 20190103-mgm-proteins-v2.fa

Any ideas on how to be more effective? Below is a full line of text with an example of what needs to be removed.
>gene_1|GeneMark.hmm|105_aa|-|2|316	>k141_4 flag=1 multi=11.0000 len=316

**Comment by kubu4** [comment]
This should do it:

```sed 's/>k141.*//' 20190103-mgm-proteins.fa > 20190103-mgm-proteins-v2.fa```

This is using regular expressions (which are different than bash "globbing"; e.g. expanding the asterisk to match zero or more characters), with the period followed by the asterisk.

**Comment by emmats** [comment]
That worked! Thanks.
