### ISSUE TITLE
Species database for RepeatMasker

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#683]
I have the following text in the [*C. virginica* methylation draft paper](https://docs.google.com/document/d/1gOMJrnhs4D-jCKWlJK2tm0Z27IrSqMkmc7K1pDBmqi0/edit#) (based on [this notebook entry](https://robertslab.github.io/sams-notebook/2018/08/28/transposable-element-mapping-crassostrea-virginica-genome-cvirginica_v300-using-repeatmasker-4-07.html)):

> Putative transposable elements were identified using RepeatMasker (v4.07) with RepBase-20170127 and RMBlast 2.6.0 (Smit et al. 2013-2015). All species available in the database were used to identify transposable elements. 

@kubu4 is there an actual name/version number for this species database? Or is it built into RepeatMasker?

**Comment by kubu4** [comment]
RepBase-20170127
