### ISSUE TITLE
Diluting RNA 

### ISSUE THREAD

**Issue by alannag** [RobertsLab/resources#684]
I need to dilute some of my RNA samples to quantify them, because the last reading said "too high." Would anyone know how many uL of RNAse-free water I should add to dilute them? I think I have 14 uL of my sample currently...

**Comment by kubu4** [comment]
Qubit measurement is also dependent upon what sample volume you used in your assay. What sample volume did you use in the Qubit assay? If you use >1uL, you could re-measure using a smaller volume and you might fall within the assay range without the need to dilute your sample(s).

**Comment by alannag** [comment]
I used 1uL exactly...

**Comment by kubu4** [comment]
I'd dilute your samples 1:1. To do so, add a volume of water equal to the current volume of your sample, vortex and then quantify on Qubit.

**Comment by alannag** [comment]
You mean add water to the original sample tube, right?

**Comment by kubu4** [comment]
Yep.
