### ISSUE TITLE
Please review and update recent presentations

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#686]
Please make sure recent presentations are up to date @ https://github.com/sr320/LabDocs/blob/master/web/Products.md

This includes posters and slidedecks...

**Comment by yaaminiv** [comment]
@sr320 I think all of my presentations are up-to-date unless you want me to include my outreach talk at Town Hall Seattle

**Comment by laurahspencer** [comment]
I proposed a couple file changes, but not sure if they were "saved" since I forgot to hit the "pull request" button. Let me know if I need to re-do the edits.

**Comment by sr320** [comment]
@laurahspencer I see no edits 

@yaaminiv minimally your SAFS100 and It would be great to have your outreach talk also.
Your SAFS100 talk should even have a youtube link.
