### ISSUE TITLE
Autoclave and Incubator Needs

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#687]
This summer, folks from Auburn will be in the lab and need access to 

- Incubator(s) - 35C
- Autoclaves

They are concerned about capacity.

What is the sum we have access to?

**Comment by kubu4** [comment]
Incubators (assuming they just need temperature control): 3

Autoclaves: 2

**Comment by sr320** [comment]
Yes - just 35C for incubators

The 2 are in FTR?  - they both function?

Are there larger ones in FSH we could use? The want to do "a lot" of samples.

**Comment by kubu4** [comment]
No, there's only one in FTR.

There's another one in FSH. It's a large autoclave.

**Comment by sr320** [comment]
for reference
![UNADJUSTEDNONRAW_thumb_183c](https://user-images.githubusercontent.com/4442039/57394170-ac776c80-7179-11e9-9d4c-ff8c9e6a6632.jpg)
![UNADJUSTEDNONRAW_thumb_183d](https://user-images.githubusercontent.com/4442039/57394171-ac776c80-7179-11e9-83ef-367c1ff60310.jpg)
![UNADJUSTEDNONRAW_thumb_183e](https://user-images.githubusercontent.com/4442039/57394172-ac776c80-7179-11e9-834c-928d3d270696.jpg)
![UNADJUSTEDNONRAW_thumb_183f](https://user-images.githubusercontent.com/4442039/57394173-ac776c80-7179-11e9-92c4-5e2c4a2293c4.jpg)
![UNADJUSTEDNONRAW_thumb_1841](https://user-images.githubusercontent.com/4442039/57394174-ac776c80-7179-11e9-9646-75e0d0b541d9.jpg)

**Comment by kubu4** [comment]
FYI, this oven is not functional:

https://user-images.githubusercontent.com/4442039/57394172-ac776c80-7179-11e9-834c-928d3d270696.jpg

**Comment by sr320** [comment]
thanks! good to know.
