### ISSUE TITLE
Macrospin column details 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#688]
>from an email.

I am very interested in trying the described protocol in shrimp and annelid species. I have done some proteomics work previously, but following the traditional 2D gel approach, so I am now aiming for in-solution approaches and high resolution methods.

**I wish to ask you what type of macrospin column was used to purify the samples?**

Species that belong to the mollusk and annelid groups can be very tricky due to mucous, etc. As the polychaete species that I am currently working on is very small (1-2mm), I am not able to separate tissues, which makes it even more complex and prone to the existence of interferents, so I need to make sure that the sample is cleaned before analysis.

Kind regards,

Diana Madeira, Ph.D.
1 Marine Biotechnology & Aquaculture Group
CESAM, University of Aveiro
Portugal

**Comment by yaaminiv** [comment]
> I wish to ask you what type of macrospin column was used to purify the samples?

According to the gigs proteomics paper, Macrospin C18 columns (The Nest Group).

**Comment by sr320** [comment]
Thanks!
