### ISSUE TITLE
Update Roberts COI

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#69]
please 
update 

[COI.xlsx](https://github.com/RobertsLab/resources/files/1344943/COI.xlsx)

such that it conforms to

![image](https://user-images.githubusercontent.com/4442039/31024364-a82ab852-a4f3-11e7-9a2d-1e1708747aa4.png)

using 
http://faculty.washington.edu/sr320/?page_id=13537

**Comment by grace-ac** [comment]
Updated COI: 
[COI_updated.xlsx](https://github.com/RobertsLab/resources/files/1345352/COI_updated.xlsx)

May have mislabeled some people as "Co-Authors" when they should be Collaborators... Not sure how to tell the difference between the two.

**Comment by sr320** [comment]
Thanks!
