### ISSUE TITLE
Order more HSP70 

### ISSUE THREAD

**Issue by alannag** [RobertsLab/resources#690]

**Comment by kubu4** [comment]
This needs a bit more detail, like species, SR ID, etc. Something to guide
me on what exactly needs to be ordered.

**Comment by alannag** [comment]
Spp: O. lurida, 
FWD and Reverse primers: 
TTGTCGCCATTTTCCTCGCT | GTTCCGATTTGTTCCGTGCC
Not sure SR ID, couldn't find it in the database

**Comment by kubu4** [comment]
Thanks. What's the source on primer seqs?

**Comment by sr320** [comment]
Should be right out of the Heart paper…

**Comment by kubu4** [comment]
I'll go ahead and order those, but I'm concerned that we don't appear to have this primer set already...

**Comment by kubu4** [comment]
ordered
