### ISSUE TITLE
Need photos of geoduck larvae

### ISSUE THREAD

**Issue by emmats** [RobertsLab/resources#691]
I just found out that I need to make a graphical abstract. Does anyone have good quality of photos of geoduck larvae? Multiple stages of development would be a plus.
Thanks!

**Comment by shellytrigg** [comment]
not sure about the quality but maybe one of these?
![dhinge](https://user-images.githubusercontent.com/4720221/57548500-f09f7400-7315-11e9-842f-790eca6aab64.png)
![53dpf](https://user-images.githubusercontent.com/4720221/57548501-f09f7400-7315-11e9-9bd5-e84c225ddb34.jpg)
![62dpf_v2](https://user-images.githubusercontent.com/4720221/57548502-f09f7400-7315-11e9-9bc3-a3bb181c7d9a.png)
![62dpf](https://user-images.githubusercontent.com/4720221/57548503-f1380a80-7315-11e9-94b1-3693c9fe6318.png)
![46dpf](https://user-images.githubusercontent.com/4720221/57548504-f1380a80-7315-11e9-8dfe-ad548d8d7b50.jpeg)

**Comment by emmats** [comment]
The first one is great! Thank you!
If anyone has a picture of an earlier larva, please send it along.

**Comment by laurahspencer** [comment]
I found geoduck larvae images from Hollie's OA project, winter 2016: https://drive.google.com/open?id=1i392fvu2E36_xXQyZ7V5CXcT04gqu226

**Comment by emmats** [comment]
Thanks!
