### ISSUE TITLE
Creating a C.v intron track with subtractBed

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#692]
[Jupyter notebook](https://github.com/fish546-2018/yaamini-virginica/blob/master/notebooks/2019-05-13-Generating-Genome-Feature-Tracks.ipynb)
[IGV session](https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2019-05-13-Generating-Genome-Feature-Tracks/2019-05-13-Genome-Track-Verification.xml)

I tried using `subtractBed` to identify introns:

<img width="296" alt="Screen Shot 2019-05-13 at 11 42 03 PM" src="https://user-images.githubusercontent.com/22335838/57676146-b7e2f180-75d8-11e9-869c-fb41a7365a69.png">

The file I generated had 688167 introns, which is way more than the 319,262 in the pre-made intron track. I looked at the tracks in IGV:

<img width="1164" alt="Screen Shot 2019-05-13 at 11 24 01 PM" src="https://user-images.githubusercontent.com/22335838/57675367-a567b880-75d6-11e9-80ce-21e56303270f.png">

By comparing the intron track I generated to the pre-made intron track, it looks like there are some regions that are being properly subtracted, and others that were not. I already used `-s` to enforce strandedness, but reading the [`subtractBed` help file](https://bedtools.readthedocs.io/en/latest/content/tools/subtract.html), I don't see any other obvious solution to my problem. How do I properly generate this track?

**Comment by yaaminiv** [comment]
Okay, found an potential solution. I used the gene track I generated instead of the mRNA track and counted 307088 possible introns:

![Screen Shot 2019-05-13 at 11 50 22 PM](https://user-images.githubusercontent.com/22335838/57676683-ee6d3c00-75d9-11e9-8d6b-25fcdfcec7d5.png)

However, looking at this file in IGV, there are still some discrepancies between the intron track generated using the gene track and the pre-made track:

<img width="1161" alt="Screen Shot 2019-05-14 at 12 01 13 AM" src="https://user-images.githubusercontent.com/22335838/57677395-97686680-75db-11e9-8037-f6a0296727a1.png">

Follow-up question: What is the difference between the mRNA and gene tracks? For example, this screenshot shows some extra genic regions that are not included as mRNA, but are included as exons.

<img width="1163" alt="Screen Shot 2019-05-13 at 11 59 40 PM" src="https://user-images.githubusercontent.com/22335838/57677379-90415880-75db-11e9-9480-16e652d1348e.png">

My assumption is that there are CDS, but I would not expect to have to incorporate CDS into intron generation...

**Comment by yaaminiv** [comment]
@sr320 An actual question:

I looked at the intron track I generated [in IGV]() and for the most part, I think `subtractBed` worked when I subtracted the exon track from the gene track. However, there are region,s like those pictured below, where I see a gene sequence and exons, but no introns. **Why are there no introns?**

![Screen Shot 2019-05-15 at 3 11 47 PM](https://user-images.githubusercontent.com/22335838/57813082-d570a200-7723-11e9-9833-fad12418d87e.png)

![Screen Shot 2019-05-15 at 3 11 27 PM](https://user-images.githubusercontent.com/22335838/57813083-d570a200-7723-11e9-814c-cde1bfdf0d2b.png)

**Comment by yaaminiv** [comment]
Based on lab meeting discussion, I looked at the intron track I generated by using `subtractBed` with genes and exons:

<img width="734" alt="Screen Shot 2019-05-15 at 3 31 19 PM" src="https://user-images.githubusercontent.com/22335838/57813858-7fe9c480-7726-11e9-9036-48086fa70ea6.png">

For the most part, it looks pretty good:

![Screen Shot 2019-05-15 at 3 22 40 PM](https://user-images.githubusercontent.com/22335838/57813877-93952b00-7726-11e9-8f51-9c405cee40db.png)

But there are also areas where the introns and exons overlap (even though they shouldn't). The tracks in green are the gene track, exon track, and the intron track I derived:

![Screen Shot 2019-05-15 at 3 28 58 PM](https://user-images.githubusercontent.com/22335838/57814012-1ae29e80-7727-11e9-822d-d14f34cce0e4.png)

@sr320 My questions:

1. Could this be an artifact of [using `-s` as an argument to enforce same strandedness](https://bedtools.readthedocs.io/en/latest/content/tools/subtract.html#s-enforcing-same-strandedness)?

2. Does it make sense to run `subtractBed` again to subtract the exon track from the intron track (and hopefully get rid of these overlaps)?

**Comment by yaaminiv** [comment]
Determined that `-s` should be used to enforce same strandedness since exon and introns should be on the same strand. 

@kubu4 Could you look at my code (notebook [here](https://github.com/fish546-2018/yaamini-virginica/blob/master/notebooks/2019-05-13-Generating-Genome-Feature-Tracks.ipynb)) to help me figure out why certain exons are not being subtracted from the genome?

**Comment by kubu4** [comment]
I think you want be using [bedtools complement](https://bedtools.readthedocs.io/en/latest/content/tools/complement.html) instead of `bedtools subtractBed`. The bedtools link has a good diagram of how it works:

![20190521_001](https://user-images.githubusercontent.com/4514104/58125029-78ae3500-7bc4-11e9-9e83-0b86e035be32.png)


This [Biostars post](https://www.biostars.org/p/112251/#314840) will be good guidance, but here's the summary of the approach:

- introns = `bedtools complement` of *intra*genic regions and exons

**Comment by yaaminiv** [comment]
That worked! My intron track is now workable:

![Screen Shot 2019-05-28 at 6 42 36 PM](https://user-images.githubusercontent.com/22335838/58579559-5bf3ac00-8219-11e9-8cbc-39cf63a38080.png)
