### ISSUE TITLE
Where to find deduced proteome?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#693]
deduced proteome will be used as background with the Oysterseed DIA data to find all the bugs, ciliates, etc.

**Comment by sr320** [comment]
I think what @kubu4 has is a good start. 
@kubu4 you have predicted genes? Do you have complementary **deduced amino acid sequences** from this?

or presumably, @emmats created one for her metaproteomics analysis?

**Comment by emmats** [comment]
I'm a little lost. What, exactly, is Grace looking for?

**Comment by sr320** [comment]
Deduced amino acid fasta (proteome) to run her oyster larvae data against using walnut… to see what non oyster sequences are there.

The file you used to analyze your metaproteomic data.

**Comment by emmats** [comment]
She should put all the additional sequences she is interested in into a fasta with the oyster sequences. Walnut does run into problems when fasta databases get too big, though.

**Comment by kubu4** [comment]
@sr320 recommended I share this:

http://gannet.fish.washington.edu/Atumefaciens/20190103_metagenomics_geo_metagenemark/20190103-mgm-proteins.fa

Protein FastA file of all samples combined into a single metagenome.
