### ISSUE TITLE
Weird qPCR Results

### ISSUE THREAD

**Issue by alannag** [RobertsLab/resources#695]
I ran a qPCR using HSP70 as a primer, and good portion of my samples didnt amplify, as seen in the second screenshot. Not entirely sure what this could be a result of or what this means. Any thoughts on next steps? Re run maybe? (screenshots below)

<img width="992" alt="Screen Shot 2019-05-23 at 11 04 53 PM" src="https://user-images.githubusercontent.com/49991259/58306171-84aa1a80-7daf-11e9-9954-b233197ce788.png">
<img width="980" alt="Screen Shot 2019-05-23 at 11 04 31 PM" src="https://user-images.githubusercontent.com/49991259/58306176-870c7480-7daf-11e9-8527-debf04690472.png">
<img width="697" alt="Screen Shot 2019-05-23 at 11 05 09 PM" src="https://user-images.githubusercontent.com/49991259/58306183-896ece80-7daf-11e9-8c54-e2f5d34596db.png">

**Comment by sr320** [comment]
Just means no expression was detected. 
@shellytrigg or @kubu4 might have suggesting of how to deal with. One method is to use expression value of zero.
