### ISSUE TITLE
Summer field work

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#696]
Any ideas on who might be interested in this? (via email from Bill Walton)

>I’m working with James on our plan for sampling this summer up in Samish Bay. He’s going to be tied up in the lab with processing so I wanted to see if you could point us in any direction of being able to hire some hourly (student?) help and, ideally, use of a UW boat. Bill Dewey mentioned a rowboat, but I would feel better if those sampling had power. Trying to figure out if there would be help so we could work up a budget.

>Because of the travel time, I think we need two people to pull and transport samples, and another to drive the boat. That might be overkill but trying to err on the safe side. These would probably be ~12 hour days with maybe three of these across that week in July (the good low tides). Don’t know if there’s anyone around your lab or school that might be good fits for this, but figured best to start with you!

**Comment by laurahspencer** [comment]
We can send this out to SAFS undergrads

**Comment by laurahspencer** [comment]
@sr320 does Bill still need help?  I'm sending an email out to my Shellfish Bio. class, and could mention this if so.

**Comment by sr320** [comment]
He probably does- he should be here next week.
Go ahead and mention as possibility and just have them contact me if they might be interested.
