### ISSUE TITLE
Covering Thursday Class

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#697]
Between the three of you could you cover class for me on Thursday?
Class got this email from me:

---
We will not meet today but will be meeting on Thursday.
Before Thursday please complete the Reading 
https://sr320.github.io/course-fish497-2019/readings/R-git/
and Lecture Notes
https://sr320.github.io/course-fish497-2019/materials/knitr/
 
Remember to post any questions in the discussion board.

---

it is really just showing them R Markdown. You could go over lecture notes or reading. But really just answer questions. There are only 4 students (Grace is one- so she could provide details).

**Comment by yaaminiv** [comment]
I can definitely be there Thursday.

**Comment by kubu4** [comment]
Same. @yaaminiv, if you are able to run the show, I'll show up for support.

**Comment by grace-ac** [comment]
here's the class GitHub where everyone has their own repos: https://github.com/fish497-2019

**Comment by laurahspencer** [comment]
I'm attending the WOAC OA symposium on Thursday, but can zip over for class if needed. @yaaminiv & @kubu4 up to you if you want backup!

**Comment by yaaminiv** [comment]
@laurahspencer seems like we should be okay without you!

**Comment by kubu4** [comment]
@yaaminiv did a great job. Biggest class concerns involved Git and GitHub!

**Comment by yaaminiv** [comment]
Thanks! I even taught @kubu4 stuff.
