### ISSUE TITLE
R: get unique species counts from blast output

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#698]
### R markdown script in progress: [here](https://github.com/fish497-2019/GraceCrandall/blob/master/scripts/060419-mydata.Rmd)

I want to make a table that has all the unique taxa listed, with their counts (# of times present) from these blast outputs:      

https://gannet.fish.washington.edu/Atumefaciens/20190516_metagenomics_pgen_blastx/MG3_pH71.blastx.outfmt6     
https://gannet.fish.washington.edu/Atumefaciens/20190516_metagenomics_pgen_blastx/MG1_pH82.blastx.outfmt6        

### End goal something like this:       

| Unique taxa ID        | Count |
|-----------------------|-------|
| Papio anubis          | 23    |
| Oryctolagus cuniculus | 48    |
| Etc                   | Etc   | 

Taxa can be columns with counts as rows... doesn't matter.

**Comment by sr320** [comment]
Bonus points for most elegant and use of `tidyverse`

**Comment by kubu4** [comment]
Do you specifically need/want an `R` solution?

`bash` can do this quickly:

`awk -F'\t' '{print $14}' MG3_pH71.blastx.outfmt6 | sort | uniq --count`

Explanation:

1. Use `awk`, setting field delimiter as tab (`-F'\t'`), print the 14th column (which has the taxa).

2. Pipe to `sort` (required for `uniq --count` to work properly).

3. Use `uniq --count` to count the number of instances of each taxa.

**Comment by kubu4** [comment]
I've returned for the bonus points:

```R
library(tidyverse)
df <-read.csv("MG3_pH71.blastx.outfmt6", , header = FALSE,sep ="\t")

taxa_counts <- df %>% 
  group_by(df$V14) %>% 
  summarise(count = n())
```

Screencap of output data frame:

![20190605_001](https://user-images.githubusercontent.com/4514104/58984836-de86e900-878e-11e9-8f44-fc740517e6c0.png)

**Comment by kubu4** [comment]
Plus, _syntax_ highlighting in the code block above. Fancy, eh???!!

**Comment by sr320** [comment]
@kubu4 that is pretty good 👍

**Comment by grace-ac** [comment]
awesome! thanks!
