### ISSUE TITLE
Compile Current and Pending for FFAR

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#70]
[PRTMPL69570.XLSX](https://github.com/RobertsLab/resources/files/1345097/PRTMPL69570.XLSX)

is the form and need to get

these into said format..

- [2017-Roberts-USDA.docx](https://github.com/RobertsLab/resources/files/1345103/2017-Roberts-USDA.docx)
- http://d.pr/f/tS6ZHT
- Brent's C&P

**Comment by grace-ac** [comment]
Should they be in three separate forms - one for each person?

**Comment by grace-ac** [comment]
Here it is: 
[PRTMPL69570_all.xlsx](https://github.com/RobertsLab/resources/files/1345555/PRTMPL69570_all.xlsx)


Missing:
Steven- Role on Project; Location of Project; Persons-Months per Year Committed to the project

Brent - Persons-months per year committed to the project

Holly - I highlighted two things that were missing: $ amount on first title; whether it conflicts with FFAR on last title

**Comment by sr320** [comment]
thanks!
