### ISSUE TITLE
Examples of Reproducible / Executable Science

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#700]
Next week I am going to giving a short presentation on how we try to do reproducible research at the 2 day workshop at eScience..
 [https://www.eventbrite.com/e/writing-reproducible-and-executable-scientific-papers-with-r-python-registration-61060854660](https://www.eventbrite.com/e/writing-reproducible-and-executable-scientific-papers-with-r-python-registration-61060854660) 

What are some examples of this being done well or even just ok?

**Comment by kubu4** [comment]
Genomic Resources wiki is a decent example. We identify/produce/use "canonical" versions of frequently used data sets so that all lab members are using the same data to base their analyses on.

**Comment by kubu4** [comment]
We've recently started to write/modify code to be more platform agnostic (i.e. run on Mac/Linux without using options available only on a single platform). Shelly's recent changes to the CpG OE bash script is a great example of this problem and solution!

**Comment by yaaminiv** [comment]
Maybe some of my C.v notebooks would work?

Characterizing general methylation trends: https://github.com/fish546-2018/yaamini-virginica/blob/master/notebooks/2019-03-18-Characterizing-CpG-Methylation.ipynb
DML and DMR analysis: https://github.com/fish546-2018/yaamini-virginica/blob/master/notebooks/2018-11-01-DML-and-DMR-Analysis.ipynb

We also include all of our raw data and code in paper repos: 

https://github.com/RobertsLab/paper-gigas-DNR-proteomics

**Comment by laurahspencer** [comment]
Fairly obvious, but how about showing that links to GitHub repos are published in papers, which include all needed data + code/notebooks? I.e. someone should only need our repo DOI to redo our analyses.

**Comment by sr320** [comment]
@laurahspencer can you provide some specific examples of ones we should be proud of

**Comment by sr320** [comment]
lab notebooks

**Comment by shellytrigg** [comment]
How about coupling lab members journal entry +  jupyter notebook with our lab's anaylsis pipelines:

e.g. when I was trying to figure out how the proteomics data was analyzed I looked at the lab's protocol:

https://github.com/RobertsLab/resources/blob/master/protocols/DDA-data-Analyses.md

Then looked through lab members lab notebook entries + jupyter notebooks to trace back exactly what was done:

https://github.com/shellytrigg/OysterSeedProject/blob/master/analysis/2016OysterSeedProteomicsAnalysisMethods.md

**Comment by jldimond** [comment]
Here are some of mine:

2016 paper:
https://onlinelibrary.wiley.com/doi/abs/10.1111/mec.13414
Dryad repo:
https://datadryad.org/resource/doi:10.5061/dryad.pq827
GitHub repo:
https://github.com/jldimond/Coral-CpG

2017 paper:
https://onlinelibrary.wiley.com/doi/abs/10.1111/mec.14252
Zenodo repo:
https://zenodo.org/record/801550#.XP1l3dNKhTY
GitHub repo:
https://github.com/jldimond/Branching-Porites
Markdown file showing analyses in R:
https://github.com/jldimond/Branching-Porites/blob/master/analyses/ipyrad_analysis/data3_outfiles/PoritesRAD_analysis.md
