### ISSUE TITLE
Long-term animal storage @ Manchester 

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#702]
Checked on some animals yesterday @ the Manchester dock and beach.  

The cages hanging off the dock were extremely fouled. Mussels were particularly problematic, as they were everywhere and some damaged the mesh bags that contain separate oyster groups. Some oysters seemed alive (I didn't open bags), but those in finer mesh pouches hadn't grown much probably b/c they were fairly silted in.  

Cages on the beach were surprisingly clean- nothing but a few barnacle set.  This could be a great place to store animals long-term once hey get to a certain size.  We should ask PSRF a) can we have space for long term storage on the beach, and 2) have they kept oysters there year-round with success?  I checked on my exp. Olys yesterday, they were set on silos held in a shellfish bag on the beach for 1 year (June 2018 - June 2019) - extremely low survival. 

Once we determine a plan, let's schedule a day for 2 people to go out, transfer animals to new bags with new labels, and place in long-term storage. 

Side-note:  Hanging a cage off the dock at Manchester in the spring is a great way to collect an amazing diversity of animals - cucumbers, scallops, nudibranchs, mussels, clams, tunicates, crab, some finfish - could be leveraged for a class.

**Comment by laurahspencer** [comment]
For context: 

Beach setup; bags flipped over with silos have been there since June 2018: 
![IMG_8475](https://user-images.githubusercontent.com/17264765/59632081-3235f280-90fe-11e9-9139-7f6a54b9b9aa.JPG)
![IMG_8476](https://user-images.githubusercontent.com/17264765/59632082-32ce8900-90fe-11e9-8408-0f029ba296c6.JPG)

Cages off dock: 

![IMG_8477](https://user-images.githubusercontent.com/17264765/59632084-32ce8900-90fe-11e9-9ce4-3e928fd90664.JPG)
![IMG_8478](https://user-images.githubusercontent.com/17264765/59632085-32ce8900-90fe-11e9-87ac-c0b737f620fb.JPG)

**Comment by sr320** [comment]
@laurahspencer any plans for this? I should be available next Monday (8/5) or Wednesday (8/7)

**Comment by laurahspencer** [comment]
I haven't scheduled this yet - it's dependent on the tides, though, which needs to reach -1 to work on the beach.  I'll take a look at the tide charts will put this on the calendar in the next month, then coordinate with Stuart.

**Comment by laurahspencer** [comment]
Scheduled for Thursday, Aug. 29.  If we end up needing access to the beach again, there's another good low tide on Aug. 30th @ 11:30am.

**Comment by laurahspencer** [comment]
Going out on Friday Aug. 30th instead, since Ana Wilson (undergrad) can help that day.

**Comment by laurahspencer** [comment]
Update: Only Olys we had remaining at dock were from my OA/T 2017 study - remaining adults and offspring not sampled or tested in the field. All were transferred to new bags, labels re-touched for readability, placed in tumble bags, and zip-tied to racks on the beach. 

If we had other Olys hanging off the dock, they are no more. Stuart will send me the dock database; I'll add the transferred Olys to that database and will see what we lost (if anything).
