### ISSUE TITLE
Getting IVG web portal to use url data

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#703]
Anyone get 
https://igv.org/app/

to work with our data?

I get error 
https://d.pr/i/kkKvla

**Comment by kubu4** [comment]
Error when loading which file(s)?

**Comment by sr320** [comment]
sorry pasted wrong url
this files
http://owl.fish.washington.edu/halfshell/genomic-databank/Olurida_v081.fa.fai

error: https://d.pr/i/kkKvla

**Comment by kubu4** [comment]
Owl might still be in the process of rebooting.

**Comment by kubu4** [comment]
Ignore that! Sorry.

**Comment by kubu4** [comment]
Ugh, probably related to this issue (tl;dr - requires special server configuration??!!):

https://github.com/igvteam/igv.js/issues/406

**Comment by kubu4** [comment]
Tried GoogleDrive option and got "Access Forbidden" message:

![20190619_005](https://user-images.githubusercontent.com/4514104/59789608-190a7e80-9283-11e9-90cd-cafab0465fcc.png)

**Comment by sr320** [comment]
Nothing seems work- I tried loading a session file locally and url
