### ISSUE TITLE
Is emu offline?

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#704]
Can't login to Rstudio web server or ssh into emu. Is it offline?

**Comment by kubu4** [comment]
I'd say so. You can use roadrunner if you don't want to go restart Emu.

**Comment by shellytrigg** [comment]
I checked 213 and saw the emu node does not have the little green light or white light next to the power button lit up on the left side of the node like the others do. Seems like the power is off. Can I turn it back on?
![IMG_20190624_131218](https://user-images.githubusercontent.com/4720221/60048826-df21e980-9681-11e9-8ad1-87c0401a16a7.jpg)

**Comment by shellytrigg** [comment]
was trying to access an html file I made on the emu github directory that I didn't sync.

**Comment by kubu4** [comment]
If it's not on, please turn it on. Thanks.

**Comment by shellytrigg** [comment]
Ok, my first time playing with a node. Power's back on and back online!
