### ISSUE TITLE
Create 18 scaffold Geoduck assembly

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#705]
Phase refers to the following...
>Juicebox correction resulted in a final set of 18 scaffolds spanning 942 Mbp, with these scaffolds having a scaffold N50 of 57,743,597 Mbp and a scaffold N90 of 34,923,512 Mbp.

Can you try to find these 18 scaffolds (presumably biggest?) and create respective fasta.

**Comment by sr320** [comment]
or maybe this is a different assembly we have yet to uncover?

**Comment by kubu4** [comment]
I think what they've described is what has been used for the assembly (however, it's not clear how the final assembly designated as `Pgenerosa_v070.fa` was created - no info on Genomic Resources page). With that being said, I think the confusion comes down to "lingo". Here's a screenshot of the data for the 18 "scaffolds" they're referencing:

![20190625_002](https://user-images.githubusercontent.com/4514104/60115612-2912da00-972b-11e9-9b27-2c8bf4ae31db.png)

(Taken from Google Drive: [20180419_geoduck_hi-c/Results/geoduck_roberts_zk results 2018-08-09 11:38:04.868217](https://drive.google.com/file/d/1vVWUjMWxn4rA8d2lxoCHeSJ0yc2I7rW2/view?usp=sharing)

The "scaffolds" are, essentially, clusters of related contigs. So, all contigs are clustered in to scaffolds (i.e. "chromosomes"). Thus, there aren't 18 individual scaffolds/contigs as we usually refer to them. 

Here's the head of the manually curated assembly they produced:

```shell
head geoduck_manual_scaffolds.fasta 
>PGA_scaffold1__77_contigs__length_89643857
ATGCGCAGAAGTTGTTCCGGAAAATGGTACTGTAGTGACATGTGAATATGACCCGTATTTAGAGAAAGTAGCGAGAATGT
ACTTTGATTCAACTCCGCATGGCAGGAAGATTCACATTCGTATAGGTATTGTTTTTAAATTAATTATAATAATGTGTATT
GTTGAAACTAAAAAAACAAGCAAGCAGGGTGTCGGATAAAACGTAGGACGCTCGACATTGCGATACCAGAATTTGCTCGA
TGTTATTGAGCTAATTATCAAAAATAAATACCATCCACTGTGTTGTTCCTGGGTGCCACATGGATGAAGGCAAGAATGTA
GCCACTGTAGTTCATACAATTCCCAGAAGTAGTGTCTTGTGTGTTTAAACATGAATATCTGAATTAGTTGAAAACGGGTA
TATATATAAATTTGGTTGAGCTGTAAAACTAATGAATGTGTGTGGTTTATTTAAGAATTAATTATTACTTTTTTATCAGA
AGTAGTTTTTGAAAAAAATACTGTTTTTGAAAGTTACACTTATTCAAATAAGTAGCAACAGAAATTCAATATTGAATTTT
ATGTCGGTGTGTGCCTCGTGATCGTTGCACAATGCAGTAATTCACCTGCACATAGATCGTGCAAGCCTGTGCAGAGCAGA
ATCCCGGCTCAATTTTCGCACAGGTATTAAGCAACGATCACGGGGAACAGTTCCTCTCAATAACTTGGTAGCTAGCTGCG
```

Then, there's this (the FastA below is what they provided - also found in that Google Drive folder linked above):

```shell
grep PGA_scaffold1 geoduck_manual_scaffolds.fasta | head -n 25
>PGA_scaffold1__77_contigs__length_89643857
>PGA_scaffold10__49_contigs__length_53961475
>PGA_scaffold11__79_contigs__length_51449921
>PGA_scaffold12__71_contigs__length_50438331
>PGA_scaffold13__52_contigs__length_44396874
>PGA_scaffold14__91_contigs__length_45393038
>PGA_scaffold15__101_contigs__length_47938513
>PGA_scaffold16__33_contigs__length_31980953
>PGA_scaffold17__51_contigs__length_34923512
>PGA_scaffold18__69_contigs__length_27737463
>PGA_scaffold19__1_contigs__length_6170
>PGA_scaffold100__1_contigs__length_37850
>PGA_scaffold101__1_contigs__length_30584
>PGA_scaffold102__1_contigs__length_45787
>PGA_scaffold103__1_contigs__length_12750
>PGA_scaffold104__1_contigs__length_44353
>PGA_scaffold105__1_contigs__length_50812
>PGA_scaffold106__1_contigs__length_25211
>PGA_scaffold107__1_contigs__length_13357
>PGA_scaffold108__1_contigs__length_37373
>PGA_scaffold109__1_contigs__length_31266
>PGA_scaffold110__1_contigs__length_17768
>PGA_scaffold111__1_contigs__length_5435
>PGA_scaffold112__1_contigs__length_13685
>PGA_scaffold113__1_contigs__length_6181
```

This adds to the lingo confusion because it appears that the FastA sequences are labelled as "scaffolds" and indicate how many contigs comprise a "scaffold". Clearly, there are more than 18 scaffolds in the FastA file.

**Comment by kubu4** [comment]
With that being said, based on that quick `head` command, it does appear that the first 18 scaffolds may hold the majority of the sequence data. However, those other scaffolds (especially when taken together) still have a large amount of sequence info.

**Comment by sr320** [comment]
>I think what they've described is what has been used for the assembly (however, it's not clear how the final assembly designated as Pgenerosa_v070.fa was created - no info on Genomic Resources page). 

same

```
MD5 (/Users/sr320/Desktop/geo/geoduck_manual_scaffolds.fasta) = de0958fec4b9f8845babf3717ce7168c
MD5 (/Users/sr320/Documents/GitHub/nb-2019/P_generosa/data/Pgenerosa_v070.fa) = de0958fec4b9f8845babf3717ce7168c
```

**Comment by kubu4** [comment]
Will add info to Genomic Resources page.

**Comment by sr320** [comment]
Can you create assembly that just includes contigs from 18 scaffolds?

**Comment by kubu4** [comment]
Top 18 scaffolds.

FastA is here:

https://gannet.fish.washington.edu/Atumefaciens/20190625_pgen_v070_scaffold_subsetting/Pgenerosa_v070.18.fa

FastA index is here:

https://gannet.fish.washington.edu/Atumefaciens/20190625_pgen_v070_scaffold_subsetting/Pgenerosa_v070.18.fa.fai

**Comment by sr320** [comment]
I am probably missing something - but why discrepancy in sequences and report - specifically the length.

![pidc](http://gannet.fish.washington.edu/seashell/snaps/13-18scaffold-assembly_2019-06-25_14-49-11.png)

**Comment by kubu4** [comment]
You're definitely not missing anything. 

We just made the assumption that the "scaffolds" they listed in the report matched the provided FastA. However, that doesn't seem to be the case. Basically, we don't know how the FastA was produced.

**Comment by kubu4** [comment]
However, the stats you generated from those 18 FastAs appear to match this statement:

> Juicebox correction resulted in a final set of 18 scaffolds spanning 942 Mbp,

**Comment by sr320** [comment]
I am tempted to say we are using the wrong fasta....

`PGA_assembly` better aligns with report, and thus scaffolds are longer.

![pic](http://gannet.fish.washington.edu/seashell/snaps/13-18scaffold-assembly_2019-06-25_16-52-27.png)

TBS- this is not from the `manual` folder, the folder I was directed too...

**Comment by kubu4** [comment]
Correct. The manually-curated FastA doesn't have a report file (because it was manually curated). But, the manually-curated file is the most recent FastA and should represent the most accurate assembly.

**Comment by sr320** [comment]
Makes sense based on their text 
this must be PGA
>This process resulted in a set of 18 chromosome-scale scaffolds containing 1.42 Gbp of sequence (64.53% of the corrected assembly).

then manual...
>Finally, Juicebox[8,9] was used to correct scaffolding errors (primarily due to a combination of very short contigs and haplotigs present in the assembly) as well as introduce one new break into contig 349, which appeared to be an assembly misjoin. Juicebox correction resulted in a final set of 18 scaffolds spanning 942 Mbp, with these scaffolds having a scaffold N50 of 57,743,597 Mbp and a scaffold N90 of 34,923,512 Mbp.

**Comment by sr320** [comment]
new assembly version name v074.
see https://github.com/RobertsLab/resources/wiki/Genomic-Resources#genome-2
