### ISSUE TITLE
Run Maker on Geoduck Genome (v074)

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#707]
re transcriptomes- use individual tissue assemblies?
re TE - the "all" or not reliant on other specific species is preferred (if relevant)

**Comment by kubu4** [comment]
Job has been submitted to `coenv`. 

Will report back when complete.

**Comment by kubu4** [comment]
Alrighty, this is complete, but doesn't seem very good.

[Notebook entry](https://robertslab.github.io/sams-notebook/2019/07/01/Genome-Annotation-Pgenerosa_v074-MAKER-on-Mox.html)

- Full GFF:

  - [Pgenerosa_v074_genome_snap02.all.renamed.putative_function.domain_added.gff](https://gannet.fish.washington.edu/Atumefaciens/20190701_pgen_maker_v074_annotation/Pgenerosa_v074_genome_snap02.all.renamed.putative_function.domain_added.gff)

- CDS GFF:

  - [Pgenerosa_v074.CDS.gff](http://owl.fish.washington.edu/halfshell/genomic-databank/Pgenerosa_v074.CDS.gff)

- exon GFF:

  - [Pgenerosa_v074.exon.gff](http://owl.fish.washington.edu/halfshell/genomic-databank/Pgenerosa_v074.exon.gff)

- gene GFF:

  - [Pgenerosa_v074.gene.gff](http://owl.fish.washington.edu/halfshell/genomic-databank/Pgenerosa_v074.gene.gff)

- mRNA GFF:

  - [Pgenerosa_v074.mRNA.gff](http://owl.fish.washington.edu/halfshell/genomic-databank/Pgenerosa_v074.mRNA.gff)


Summary:

- 1,712 transcripts/proteins
  - v070 has 53,035 transcripts/proteins
  - v071 has 20,813 transcripts/proteins
- Gene annotations present in only 2 of the 18 scaffolds
- Gene annotations differ across assembly versions
- No gene annotations in the largest scaffold in _any_ assembly version
- Within a given scaffold, gene annotations differ across assembly versions

Here are some IGV comparisons of a few scaffolds to show how assembly versions differ in annotation:

#### PGA_scaffold_1

No annotations found by any of the three different annotations. Surprising, as this is the longest scaffold in each of the three assemblies (89 Mbp)

![IGV comparison of PGA_scaffold_1](https://github.com/RobertsLab/sams-notebook/blob/master/images/screencaps/20190701_igv_compare_scaffold1.png?raw=true)

---

#### PGA_scaffold_3

Annotations only appear in the Pgenerosa_v070 assembly.

![IGV comparison of PGA_scaffold_3](https://github.com/RobertsLab/sams-notebook/blob/master/images/screencaps/20190701_igv_compare_scaffold3.png?raw=true)

---

#### PGA_scaffold_18

Annotations are found in each of the three assemblies, but differ among the three.

![IGV comparison of PGA_scaffold_18](https://github.com/RobertsLab/sams-notebook/blob/master/images/screencaps/20190701_igv_compare_scaffold18.png?raw=true)

**Comment by kubu4** [comment]
I am also running GenSAS on v071 and v074. Will be interesting to see how things shake out.
