### ISSUE TITLE
zoom on macs

### ISSUE THREAD

**Issue by emmats** [RobertsLab/resources#709]
Not sure if this has been discussed in the lab, but thought people should know about the security concern with zoom on Macs. There's an option to download zoom's new, more secure app, but it looks like Apple has fixed the problem on its own.

https://techcrunch.com/2019/07/10/apple-silent-update-zoom-app/

**Comment by kubu4** [comment]
I think Slack is the more appropriate venue for this type of "issue."

**Comment by emmats** [comment]
At least I didn't try to use the defunct Google+
