### ISSUE TITLE
Compile SubAward Budget

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#71]
Get 
http://d.pr/f/5e6xhj

into 

the SubAwards tab on this file
Year 1 - 3 
[PRTMPL69565.XLSX](https://github.com/RobertsLab/resources/files/1345661/PRTMPL69565.XLSX)

**Comment by grace-ac** [comment]
I thiiiink this is right: 
[PRTMPL69565_updated.xlsx](https://github.com/RobertsLab/resources/files/1345763/PRTMPL69565_updated.xlsx)

**Comment by grace-ac** [comment]
I can stay ~40 more minutes if there's anything else i can help with!

**Comment by sr320** [comment]
Focusing on Year 1
see if you can figure out how to get totals to match. (or why they do not...)

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/d_1F829033.png" alt="d_1F829033.png"/>

**Comment by grace-ac** [comment]
I think what's happing is that the requested column on your sheet includes the fringe benefits into Holly's total, whereas in Holly's it remains in the match column, and isn't included in the total requested. 
![screen shot 2017-10-02 at 10 55 58 am](https://user-images.githubusercontent.com/14934314/31091653-94625752-a760-11e7-9890-9c6197aafcd3.png)

Also, There is an indirect cost rate rate being applied to Holly's spreadsheet which isn't on yours.
![screen shot 2017-10-02 at 10 58 29 am](https://user-images.githubusercontent.com/14934314/31091743-d3b1cca8-a760-11e7-87a9-f227ab847c11.png)

**Comment by sr320** [comment]
Thanks
I will have a look at how to proceed
