### ISSUE TITLE
Generating Circos Plots

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#710]
via Cristian..

As I mentioned I have some troubles with my server to run Sibelia and get the duplication info/input files from the Caligus genome. I need these files to plot them using Circos. Here the link for Sibelia and the command

https://sourceforge.net/projects/sibelia-bio/files/

./Sibelia -s loose <Path-to-assembly>

Alternatively, there is another one "SEDEF: Segmental Duplication Evaluation Framework"
https://github.com/vpc-ccg/sedef

Here the assembly for Caligus with the 21 scaffolds:

https://drive.google.com/file/d/1qm1FuImuEgIbNBRq_PRuAj5GEPQYVKM4/view?usp=sharing

Can you run this at the UW server?

**Comment by kubu4** [comment]
Update: I think whatever took Gannet offline this weekend also killed Emu - which is where this was running. I've restarted the job.

**Comment by kubu4** [comment]
Update. I had/have this running on Mox. Timed out after 16 days. Ugh. Have restarted with 20 day time limit to get in under the scheduled Mox maintenance. Sibelia doesn't seem to produce any intermeidate files (just uses a ton of memory - can't run on 120GB node) or stder/stdout info while it's running, so it's difficult to monitor progress.

**Comment by kubu4** [comment]
Ran out of time with the 20 day limit. Suspect Sibelia isn't going to work, due to time limitations associated with Mox maintenance windows.

Will explore the other option linked above: SEDEF.
