### ISSUE TITLE
Coral specific Nucleic Acid extraction protocols

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#711]
I am working on developing some RNA/DNA extraction protocols... Is there any special considerations, (or yield data) in work with corals?

**Comment by jldimond** [comment]
Qiagen DNeasy and RNeasy are most widely used and I have had success with them, however, I have seen reports thats phenol chloroform extractions provide better yield and quality. I think the Matz Lab only uses phenol chloroform extraction. For example:

"DNA was isolated from adult holobiont tissue using dispersion buffer (4 M guanadine thiocyanate, 30 mM sodium citrate, 30 mM β-mercaptoethanol) followed by phenol chloroform purification and a final cleanup with Zymo Genomic DNA Clean and Concentrator-10 kit (Catalog No D4011). "

from: https://www.biorxiv.org/content/10.1101/184457v4.full

**Comment by kubu4** [comment]
Used DNeasy kit in the Friedman Lab and it seemed to work fine - good yields, clean DNA.
