### ISSUE TITLE
FASTQC on mox

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#712]
@kubu4 I'm trying to run FASTQC/TrimGalore/MultiQC on mox and my jobs keep failing. I made a script (/gscratch/srlab/strigg/jobs/20190719_FASTQC_ADPTRIM_Caligus.sh) based on yours from [this post](http://onsnetwork.org/kubu4/2018/08/30/fastqcmultiqctrimgaloremultiqcfastqcmultiqc-o-lurida-wgbsseq-for-methylation-analysis/)

slurm file is here /gscratch/srlab/strigg/analyses/20190719/Caligus/FASTQC/slurm-1057521.out

I realize I need to change the permissions on my directories so they can be written to, but any ideas how I can fix these errors? 

/var/spool/slurm/d/job1057521/slurm_script: line 37: --threads: command not found

/var/spool/slurm/d/job1057521/slurm_script: line 50: /gscratch/srlab/programs/bin/multiqc: No such file or directory

**Comment by sr320** [comment]
looks like you are missing backslash before `--threads 28` line

```
#Run FASTQC
/gscratch/srlab/programs/FastQC-0.11.5/fastqc \
--outdir /gscratch/srlab/strigg/analyses/20190719/Caligus/FASTQC
--threads 28 \
/gscratch/srlab/strigg/data/Caligus/FASTQS/Sealice_F1_S20_L001_R1_001.fastq.gz  
/gscratch/srlab/strigg/data/Caligus/FASTQS/Sealice_F2_S22_L001_R1_001.fastq.gz
/gscratch/srlab/strigg/data/Caligus/FASTQS/Sealice_F1_S20_L001_R2_001.fastq.gz
/gscratch/srlab/strigg/data/Caligus/FASTQS/Sealice_F2_S22_L001_R2_001.fastq.gz
/gscratch/srlab/strigg/data/Caligus/FASTQS/Sealice_F1_S20_L002_R1_001.fastq.gz
/gscratch/srlab/strigg/data/Caligus/FASTQS/Sealice_F2_S22_L002_R1_001.fastq.gz
/gscratch/srlab/strigg/data/Caligus/FASTQS/Sealice_F1_S20_L002_R2_001.fastq.gz 
/gscratch/srlab/strigg/data/Caligus/FASTQS/Sealice_F2_S22_L002_R2_001.fastq.gz

```

**Comment by kubu4** [comment]
What @sr320 said.

You'll also need continuation slashes after each input FastQ file (FastQC takes a space-separated list of input files).

Finally, MultiQC is here: `/gscratch/srlab/programs/bin/multiqc`

Don't ask why, I don't remember why it got moved there...

**Comment by shellytrigg** [comment]
Awesome, thanks for the catches @sr320 and @kubu4 . I'll give it another go with the corrections and hopefully it runs!

**Comment by shellytrigg** [comment]
@kubu still getting this error:

var/spool/slurm/d/job1057619/slurm_script: line 50: /gscratch/srlab/programs/bin/multiqc: No such file or directory

i think multiqc is a symlink:

strigg@mox1 Caligus]$ readlink /gscratch/srlab/programs/bin/multiqc 

/gscratch/srlab/programs/anaconda3/bin/multiqc

but I don't see anaconda3 in the /gscratch/srlab/programs directory. Is this what's going on?

**Comment by shellytrigg** [comment]
also I think /gscratch/srlab/programs/cutadapt-1.16  is a symlink too:

[strigg@mox1 programs]$ readlink /gscratch/srlab/programs/cutadapt-1.16 

/gscratch/srlab/programs/anaconda3/bin/cutadapt

**Comment by kubu4** [comment]
Ah yes! Now I know what's going on. Unfortunately, installing python packages (multiqc and cutadapt are both python packages) is difficult to do for a multi-user "environment" on Mox. The easiest way to do this is via Anaconda. Using a build node, load the Anaconda module:

`module load anaconda3_5.3`

Then, follow Anaconda install instructions for MultiQC and cutadapt. Test to see that they are installed by running `which multiqc` and `which cutadapt`. If things worked like I think they should, then those two commands should spit out the absolute path to each of those programs.

After that, put the `module load anaconda3_5.3` at the beginning of your SBATCH script. And then, you should be able to run those commands (you won't need the absolute path to either of those programs any more).

**Comment by kubu4** [comment]
To clarify, each person needs to install their own instances of each of those two programs. There's not an easy way for newbs like us to figure out how to easily do a single installation for everyone to use.

**Comment by kubu4** [comment]
One more thing. It might be easier to just do this on Emu/Roadrunner - that's what I usually do these days. Those programs are available on both computers and work for all users.

**Comment by kubu4** [comment]
Another alternative is this: cutadapt is available as a module on Mox. Load it with (at the beginning of your SBATCH script):

`contrib/cutadapt/1.15`

Then, you should be able to run your trimming. However, this doesn't address MultiQC. You'd have to run this locally on your own computer or Emu/Roadrunner. MultiQC runs very quickly on a regular computer, so it wouldn't be so bad to run it on your own computer.

One last note (I think), is that cutadapt is only single-threaded, so you don't actually gain any advantage by running it on Mox. It's the biggest shortcoming of that program. So, with that being said, there's not a terribly large time difference between running this particular pipeline on Mox vs a local computer.

This will

**Comment by shellytrigg** [comment]
Got it! Thanks @kubu4

**Comment by kubu4** [comment]
Which option did you choose?

**Comment by shellytrigg** [comment]
running it on different computer
