### ISSUE TITLE
Fill LN Dry Shipper and UPS out to Pt Whitney

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#714]
July 30 -- Tuesday..

**Comment by kaitlynrm** [comment]
I can pick this up and bring this out to Sam if we end up doing the outplant on Friday!

**Comment by kaitlynrm** [comment]
Actually I can fill it Thursday and just take it with me for when I leave Friday morning for the outplant.

**Comment by sr320** [comment]
Post this option to slack and see what Hollie and Sam Gurr say… Might be too late?


thanks
Steven


Steven B. Roberts, Associate Professor
Associate Director - Graduate Program Coordinator
School of Aquatic and Fishery Sciences
University of Washington, Seattle WA
Fisheries Teaching and Research (FTR) Building - Office 232
robertslab.info - sr320@uw.edu - @sr320
vm:206.866.5141 - cell:360.362.3626

**Comment by kubu4** [comment]
@kaitlynrm What's the status on this? I definitely appreciate the offer, but I also need enough notice so I can fill it and ship it today, if needed.

**Comment by sr320** [comment]
Hollie gave green light for Kaitlyn to bring it

thanks
Steven


Steven B. Roberts, Associate Professor
Associate Director - Graduate Program Coordinator
School of Aquatic and Fishery Sciences
University of Washington, Seattle WA
Fisheries Teaching and Research (FTR) Building - Office 232
robertslab.info - sr320@uw.edu - @sr320
vm:206.866.5141 - cell:360.362.3626
