### ISSUE TITLE
Map RNA reads on Geoduck Genomes (v070, 074)

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#716]

**Comment by kubu4** [comment]
v070 sorted BAM files are in here: https://gannet.fish.washington.edu/Atumefaciens/20190723_stringtie_pgen_v070/

Haven't had time to write notebook (or look at in IGV) yet.

Will post v074 when finished (I think it should finish tomorrow morning).

**Comment by kubu4** [comment]
Just finished transferring v074 alignments (haven't looked at them or written notebook post yet):

https://gannet.fish.washington.edu/Atumefaciens/20190723_stringtie_pgen_v074/
