### ISSUE TITLE
Splitting a large fasta into several smaller fasta files (multifasta)

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#717]
In theory this should be straight forward as we commonly use 
https://github.com/RobertsLab/code/blob/master/script-box/fasta-splitter.pl

but this will not work for me, nor several other google finds....

Here is the fasta https://d.pr/f/UlzHLR (~86MB)

(it is the big geoduck scaffold with no annotations)

I am not picky - just want it split up so can blast to try to figure out what it is...

**Comment by kubu4** [comment]
FastA has been split into 2000bp chunks:

https://gannet.fish.washington.edu/Atumefaciens/20190731_faSplit_PGA-scaffold1_splits_2000bp/

Did this with the `faSplit` tool: 

http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/

```shell
faSplit \
size \
20190731_faSplit_PGA-scaffold1_splits_2000bp/ \
2000
```

**Comment by sr320** [comment]
Thanks!
