### ISSUE TITLE
Analyze Oly data in MACAU

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#718]

**Comment by sr320** [comment]
see https://github.com/RobertsLab/resources/issues/722#issuecomment-518752977

**Comment by laurahspencer** [comment]
First run with MACAU: https://laurahspencer.github.io/LabNotebook/macau-run1-results/

Results file has p-values for all methylated loci, indicating which are DML and are significantly influenced by our predictor variable- i.e. shell length.  How shall I move forward?  I'm guessing something related to describing location of loci?
