### ISSUE TITLE
Confirm Oly genome annotation are correct and revised 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#719]
@ https://docs.google.com/document/d/1HKIAAIzJ2-t86US8GY5PD12z7aNsKZSnt25u8QJOiaY/edit

**Comment by kubu4** [comment]
Looks good. Nothing's changed.

**Comment by sr320** [comment]
Includes the new isoform run- and using all of Katherine's different transcriptomes?

**Comment by sr320** [comment]
https://robertslab.github.io/sams-notebook/2019/06/25/Genome-Annotation-O.lurida-(v081)-Transcript-Isoform-ID-with-Stringtie-on-Mox.html

**Comment by sr320** [comment]
Also go ahead and add "results" of assembly and annotation.

**Comment by kubu4** [comment]
No, it doesn't include all of that. Will get the isoform stuff in there. I don't know deets on @ksil91's assemblies. Maybe she can fill that in.

**Comment by sr320** [comment]
No rush - just the genome stuff you did.
Did you redo Maker with her transcriptomes?

**Comment by kubu4** [comment]
Yep. Is that the annotation you want to use?
