### ISSUE TITLE
Explain Geoduck Scaffold #1 lack of annotation

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#721]
Scaffold 1 does not have any annotation via Maker. 

Using blastx on Uniprot - the scaffold split into about 40k, 2kbp sequences, go about 1300 hits.

https://d.pr/n/QUe96k

Will also try some genomic blastn alignments.

**Comment by sr320** [comment]
see also https://github.com/sr320/nb-2019/blob/master/P_generosa/15-Big-Mystery-Scaffold.ipynb

**Comment by kubu4** [comment]
To add to the confusion, RNAseq reads definitely align throughout Scaffold 1 and Stringtie makes transcript/isoform calls based on these alignments. Very odd that the gene prediction software (MAKER, SNAP) found nothing, despite the fact that we have the RNAseq alignment data to support the existence of expressed genes.

![20190801_001](https://user-images.githubusercontent.com/4514104/62318517-dbd40780-b450-11e9-9196-eea5cb207d09.png)

**Comment by kubu4** [comment]
Just adding to this thread for posterity.

Stringtie calls ~5000 transcripts.

NOTE: That number includes all isoforms. I have not looked at just the number "genes". That number will be much smaller.

**Comment by sr320** [comment]
@kubu4 can you compare mapping of RNA-seq versus other scaffolds, and see if there are ways to look at synteny (comparing genome to other genomes like C. virg).

**Comment by sr320** [comment]
@kubu and maybe get a blastn in going on v074 against C virg.. to get an idea of scaffold alignment hit differences..
