### ISSUE TITLE
Get MACAU up and running

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#722]
http://www.xzlab.org/software/macau/MACAUmanual.pdf

**Comment by kubu4** [comment]
A couple of things:

1. The link to the "executable" version of the software links to an outdated version (1.00alpha, from 2015), not the current version (1.30, compiled in May 2019).

2. The link to the source code for v1.30 goes to an advertising site and doesn't link to the gzipped tarball indicated on the site.

3. Which computer(s) do you want this on. I was just going to put it on Mox.

**Comment by kubu4** [comment]
Oh, and I do have an email out to them to see if they can get me links that work.

**Comment by sr320** [comment]
Thanks! not picky on computer - just want to get it running. Mox is fine, but I imagine there might be a bit of learning curve for running R on mox?

**Comment by kubu4** [comment]
The manual you linked above doesn't seem to have any indications of using R. It shows use of a MACAU binary.

I'll look into R-related MACAU stuff.

**Comment by sr320** [comment]
Sorry - confused on manuals 

https://www.xzlab.org/software/macau/MACAU-R-Manual.pdf

**Comment by kubu4** [comment]
Ah! No problem!

**Comment by sr320** [comment]
and either is fine, does matter I had just assumed the R version would be easier, but commandline on mox (or anything) is better than what we have now 😄

**Comment by kubu4** [comment]
The developer has clarified that the MACAU binary on the site is current and that they neglected to update the version listed in the software. So, MACAU binaries (not R package) have been installed. 

- Mox: /gscratch/srlab/programs/macau/macau

- Emu: /home/shared/macau/macau

- Roadrunner: /home/shared/macau/macau

R package may be difficult, as the very first dependency listed in the installation instructions doesn't work (link used in that dependency is dead).

**Comment by sr320** [comment]
Awesome! thanks
