### ISSUE TITLE
geoduck bs alignment settings

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#723]
non-directional or directional?

according to issue [#260 ](https://github.com/RobertsLab/resources/issues/260) the libraries are directional. But if they are really in fact WGBS, than they may be non-directional.

however, in the past when I ran bismark with non-directional specified on a subset of these reads for all samples ([data here](https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20181011/reports/)), the bismark PE reports show CT/GA/CT:GA/CT/CT:GA/CT/GA:CT/GA/GA to be in about a 10:1:1:10 ratio where if the libraries were really non-directional, we'd expect 1:1:1:1 ratio ([see SeqAnswers post here](http://seqanswers.com/forums/showthread.php?t=18908)). 

![Screen Shot 2019-08-06 at 11 01 01 AM](https://user-images.githubusercontent.com/4720221/62564745-45ca2380-b83a-11e9-9a2e-a4a145456d41.png)

@sr320 @kubu4 @hputnam what do you think?

**Comment by shellytrigg** [comment]
@sr320 same is the case for your partial --non-directional Bismark job on Mox where the output was saved in /gscratch/srlab/strigg/data/Pgenr/FASTQS

![Screen Shot 2019-08-06 at 11 12 01 AM](https://user-images.githubusercontent.com/4720221/62565289-5a5aeb80-b83b-11e9-9e47-2d02f735a84a.png)

**Comment by kubu4** [comment]
> according to issue #260 the libraries are directional

---

Isn't that exactly what your alignment shows?

> about a 10:1:1:10 ratio where if the libraries were really non-directional, we'd expect 1:1:1:1 ratio

**Comment by shellytrigg** [comment]
@kubu4 yes, the results from --non-directional Bismark jobs appear to show libraries are in fact directional. @sr320 was thinking the settings should be non-directional because [these libraries are not really RRBS](https://genefish.slack.com/archives/GG4HW5SC9/p1565112897007800?thread_ts=1561507685.005900&cid=GG4HW5SC9). But it seems like the directional and non-directional part is dependent on the adapters used to prepare the library, and independent of whether libraries were WGBS or RRBS

**Comment by sr320** [comment]
@shellytrigg is right, @sr320 wrong... I just asked her to post for clarity
