### ISSUE TITLE
Determining GO-MWU methods for Cv enrichment

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#724]
I performed a gene enrichment with [GO-MWU](https://github.com/z0on/GO_MWU) to see if there were any enriched GO terms in genes with DML (lab notebook [here](https://yaaminiv.github.io/DML-Analysis-Part39/)). I did not have any significantly enriched GO categories, so I'm working on describing genes with DML. GO-MWU provides [this output file](https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2018-12-02-Gene-Enrichment-Analysis/BP_2019-07-30-allTested-Table-of-Significance-Measures.csv), which groups genes ("Genbank" column) by GOslim terms. My goal is to count the frequency of these GOslim terms for genes with DML.

Two questions:

1. I ran GO-MWU 2 different ways based on a suggestion from @sr320 (see [this R Markdown file](https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2018-12-02-Gene-Enrichment-Analysis/2019-07-30-Gene-Enrichment-with-GO-MWU.Rmd): using signed log p-values, and log p-values. I don't get any difference in my enrichment results (no sig enriched terms), but the output files are different (signed log p-values linked above, log p-values [here](https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2018-12-02-Gene-Enrichment-Analysis/BP_2019-07-30-allTested-Table-of-Significance-Measures-Uncorrected.csv)). The genes are grouped into different GOslim categories. **Which method should I use when counting how many genes with DML are in various GOslim categories?** I'm leaning towards using signed log p-values, since that's the example GO-MWU provides.

2. In the R Markdown file linked above, I tried counting the number of genes with DML in each GO grouping. I did this by merging the GO-MWU output file with my [master DML-gene overlap annotation](https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2018-12-02-Gene-Enrichment-Analysis/2019-06-20-DML-Gene-Annotation.csv), then counting how many DML were in each category. When I merged the files, I was able to account for the fact that I could have multiple DML in a gene. However, I end up with 59 DML assigned to various GO groupings even though I have 598 DML. **Why am I getting such low counts?**

**Comment by sr320** [comment]
1. signed log p-values is fine

2. can't you just count lines for each go term in https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2018-12-02-Gene-Enrichment-Analysis/BP_2019-07-30-allTested-Table-of-Significance-Measures.csv? Each line appears to be a gene.

**Comment by yaaminiv** [comment]
1. 👍 
2. No. GO-MWU has you put in genes for all loci tested, even if those CpG loci are not significantly differentially methylated. I did count lines for each GOterm in the file you linked (table [here](https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2018-12-02-Gene-Enrichment-Analysis/2019-07-30-allTested-Parent-GOSlim-Frequency-BP.csv)), but this includes nonsig CpG and DML. I'm interested in filtering the genes with sig DML, and including every DML in a gene (some genes have multiple DML, but I only used the locus with the lowest p-value for GO-MWU).

**Comment by yaaminiv** [comment]
I think I figured out my issue...there are several genes that do not have parent GO-MWU terms, which is why I'm getting such low counts:

<img width="642" alt="Screen Shot 2019-08-08 at 4 40 44 PM" src="https://user-images.githubusercontent.com/22335838/62744403-4bbb3280-b9fb-11e9-80d0-da8aebc059c1.png">

I'll sum these up, put them in a table, and then figure out a better method later (if needed).
