### ISSUE TITLE
Calibrating multichannel pipettes

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#726]
I need to use a couple multi-channel pipettes in the QuantSeq library prep.  It looks like ours haven't been calibrated in a while - anyone know how I would go about doing this?  Related, I think some of our other single channel pipettes could use calibrating.

**Comment by kubu4** [comment]
Correct, our pipettes have not been calibrated in at least 12yrs.

No specific procuedure. Roughly, it goes like this:

1. contact a pipette servicer (e.g. Rainin or Fisher or Eppendorf)

2. send them out for calibration

3. get them back a few days later

**Comment by sr320** [comment]
Probably worth calibrating everything at this point.

thanks
Steven


Steven B. Roberts, Associate Professor
Associate Director - Graduate Program Coordinator
School of Aquatic and Fishery Sciences
University of Washington, Seattle WA
Fisheries Teaching and Research (FTR) Building - Office 232
robertslab.info - sr320@uw.edu - @sr320
vm:206.866.5141 - cell:360.362.3626

**Comment by kubu4** [comment]
I'll get some quotes. Calibration will likely need to wait until after Shanelle and Javier have come and gone.

**Comment by kubu4** [comment]
Quote to calibrate _all_ of our pipettes is ~$2300.

~$36 per single channel
~$60 per 8-channel
~$72 per 12-channel

**Comment by sr320** [comment]
split 50/50 61-1553 / 66-2429

**Comment by kubu4** [comment]
These have been sent out.
