### ISSUE TITLE
Annotating Cv coverage files

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#727]
I'm replicating a differentially methylated gene analysis from [this paper](https://www.biorxiv.org/content/early/2018/02/21/269076). The first step is to annotate coverage files from `bismark` with gene information. I am using [this python script](https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2019-08-14-Differentially-Methylated-Genes/2019-08-14-annotate_bismark_cov.py), which I got from [this repository](https://github.com/lyijin/working_with_dna_meth).

I started running the script but encountered this error:

![Screen Shot 2019-08-14 at 2 38 21 PM](https://user-images.githubusercontent.com/22335838/63058281-2a49c300-bea1-11e9-94ed-916ded2fecb8.png)

I think the issue is coming from the [.gff3 I downloaded from NCBI](https://gannet.fish.washington.edu/spartina/2018-10-10-project-virginica-oa-Large-Files/2019-05-13-Yaamini-Virginica-Repository/analyses/2019-05-13-Generating-Genome-Feature-Tracks/ref_C_virginica-3.0_top_level.gff3)? 

![Screen Shot 2019-08-14 at 2 42 10 PM](https://user-images.githubusercontent.com/22335838/63058498-b65bea80-bea1-11e9-8abd-ac13df203bc1.png)

There are some eons associated with "rna0", but I don't know why that's an issue. Thoughts?

**Comment by kubu4** [comment]
Without diving too deep into this, I'd guess it's related to how the script was written. I'm guessing it was written for their specific use case and it is not a "generic" GFF parser. From that script you linked above, they provide an example of the GFF file the script is designed to work on:

```
# sample line:
#   RNA-1;1.gff:1000131     maker   five_prime_UTR  1968    1999    .   
#   +       .       ID=maker-1000131-exonerate...
```

Regardless, to address the specific error, it's telling you that `rna0` is not present in the dictionary being referenced at line 206 in the script. That tells me that the parser didn't parse out `rna0` from `ID=rna0` and/or `Parent=rna0` - I haven't looked much beyond that to try to figure out why.

**Comment by yaaminiv** [comment]
@kubu4 Hmm okay...I guess I need to dive more into that GFF parser script.

@hputnam Shelly mentioned you were working on this kind of analysis? Do you know of any general GFF parser, or od you have anything that's a bit easier to interpret?

**Comment by kubu4** [comment]
What do you want/need to parse out? I've used [`gffutils`](https://github.com/daler/gffutils) in the past for various GFF manipulations.

**Comment by yaaminiv** [comment]
I want to take the gene information from the GFF and use it to annotate the coverage file (ie add another column with gene information to the coverage file). My overall goal is to calculate median % methylation for each gene, hence the need to annotate the coverage file.

**Comment by kubu4** [comment]
What do you want the output file to look from this GFF?

**Comment by yaaminiv** [comment]
I want gene names and start and stop positions of all genes so I can match that to start and stop positions in the coverage files. I guess it doesn't need to be that complicated of a python script then since I don't need any of the extra stuff in the script (which # exon the locus is in, intergenic vs. genic, etc.). I could just pull out information from the GFF then use `bedtools` to find intersections........this gives me ideas.

**Comment by kubu4** [comment]
You can pull out anything labeled as "gene" with the following awk command:

`awk 'BEGIN { print "##gff-version 3" ; } $3 == "gene" {print}' ref_C_virginica-3.0_top_level.gff3`

Will that get you what you need?

**Comment by hputnam** [comment]
Here is what i have been doing: https://github.com/hputnam/Geoduck_Meth/blob/master/RAnalysis/Scripts/Juv_Geoduck_Meth_notebook.md

https://github.com/hputnam/Geoduck_Meth/blob/master/RAnalysis/Scripts/methylation_analysis.R

**Comment by hputnam** [comment]
This approach is based on https://advances.sciencemag.org/content/4/6/eaar8028

**Comment by hputnam** [comment]
I think if you merge earlier than I did, you can get the percent meth by gene and calculate median % meth

**Comment by yaaminiv** [comment]
@hputnam To confirm, this is where you're annotating the coverage file with gene information (ex. line 73)?

```
epi.41 <- full_join(epi.41, Genes, by="scaffold") %>% filter(position >= start & position <= stop)
```

**Comment by yaaminiv** [comment]
@kubu4 I already did something similar to that so I have a gene track! Used `grep` instead. Figured I could use that file with Hollie's script.

**Comment by kubu4** [comment]
@yaaminiv - One thing to be watchful for when using `grep` in a case like this is if your search term (e.g. `exon`) is present in an undesired field. `grep` would pull the entire line with the `exon` match, but the feature could actually be CDS or something (e.g. the word `exon` is found in the description field for some reason).

**Comment by yaaminiv** [comment]
@kubu4 Definitely. I used "Gnomon gene" or "Gnomon exon" to generate those tracks.

**Comment by yaaminiv** [comment]
I ended up [using `bedtools` to annotate coverage files](https://yaaminiv.github.io/DMG-Analysis/). After a bunch of file-formatting, I used `aggregate` to calculate percent methylation by gene for each treatment. Thanks for your help @kubu4 and @hputnam!
