### ISSUE TITLE
Determine options for assessing geoduck hemolymph samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#728]
From broodstock OA treatment, with an eye toward reproductive development

![image](https://user-images.githubusercontent.com/4442039/63166005-1ade8d00-bffb-11e9-9f15-f89fa61fd462.png)

**Comment by sr320** [comment]
Suggestions: qPCR, metabolomics, Tag-seq

**Comment by shellytrigg** [comment]
Other options:
- Triglyceride content (https://www.caymanchem.com/product/10010303)
- Free fatty acid content (https://www.abcam.com/free-fatty-acid-assay-kit-quantification-ab65341-protocols.html#top-414)
- Targeted protein content (e.g. ELISA or SRM for Vitellogenin/female-specific Lipoproteins)
- Targeted lipidomics (following up on this with WCMC @ UC Davis)
- qPCR: @kubu4 designed and ground-truthed primers for vitellogenin transcript (https://genefish.wordpress.com/2018/12/10/sams-notebook-qpcr-geoduck-gonad-cdna-with-vitellogenin-primers/). I will post another issue for testing this primers on hemolymph samples

**Comment by shellytrigg** [comment]
Confirmed with the West coast metabolomics core at UC Davis that the cost is $69 per sample for . That includes sample prep and preliminary (spectral) data analysis. Minimum of 12 samples/platform (e.g. CSH QTOF M/S lipidomics). And turn around time is 4 months

**Comment by sr320** [comment]
options determined - moving ahead with PCR next week
