### ISSUE TITLE
Re-Run Maker on Geoduck Genome (v074)

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#729]
As per https://robertslab.github.io/sams-notebook/2019/07/22/Genome-Annotation-Pgenerosa_v070-and-v074-Top-18-Scaffolds-Feature-Count-Comparisons.html

and our conversation of on parameters that differed in the two runs above, re-run Maker presumably getting a higher gene count.

**Comment by kubu4** [comment]
Running.
