### ISSUE TITLE
Add "Products" link to top of http://faculty.washington.edu/sr320/

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#73]
![selection_003](https://user-images.githubusercontent.com/4514104/31132746-72ef809c-a812-11e7-9db4-80f669bb8897.png)

**Comment by sr320** [comment]
Will do, but I thought you were the one that did not like that term and
pushed for Publications :)

Curious is it Notebooks specifically you are interested in? I could do a
drop-down on the front page.

**Comment by kubu4** [comment]
Ha! I don't like "Products", but was trying to keep consistency with section below (because it's missing at the top).

Publications seems misleading when searching for notebooks (which is, as you correctly surmised, what I was trying to find).

**Comment by sr320** [comment]
But if you want easy access to notebooks (as do I) I will create a notebook
heading at top with direct drop-down menu for all notebooks so you can go
from front page to notebook. Less thinking, less clicks.

**Comment by kubu4** [comment]
Sounds killer to me!

**Comment by sr320** [comment]
Better?

http://faculty.washington.edu/sr320/

**Comment by kubu4** [comment]
Fancy! Thanks!
