### ISSUE TITLE
Handling both strands in methylation data

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#730]
Bismark provides methylation data for two bp at each CG (given second strand this makes sense).

![image](https://user-images.githubusercontent.com/4442039/63215801-d71e7d00-c0f9-11e9-9567-01de697c00b3.png)

@yaaminiv  how did we handle this in your general characterization of Cv methylation? If I recall we collapsed the data?

**Comment by yaaminiv** [comment]
I believe we augmented base pairs in the coverage files/bedgraphs such that there was only a 1 bp difference:

https://github.com/fish546-2018/yaamini-virginica/blob/master/notebooks/2019-03-18-Characterizing-CpG-Methylation.ipynb

**Comment by yaaminiv** [comment]
We also used destrand = TRUE in `methylKit`: https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2018-10-25-MethylKit/2018-10-25-MethylKit.Rmd
