### ISSUE TITLE
Obtaining longest mRNA for each gene

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#731]
In order to [annotate coverage files with gene information](https://github.com/RobertsLab/resources/issues/727), I'm reformatting some data in [this R Markdown script](https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2019-08-14-Differentially-Methylated-Genes/2019-08-14-Differentially-Methylated-Gene-Analysis.Rmd). Similar to [this paper](https://www.biorxiv.org/content/early/2018/02/21/269076), I only want to include product/Uniprot/GOterm information for the longest mRNA for each gene. I tried using the following code to retain the longest mRNA for each gene (modified from some code @kubu4 wrote [here](https://github.com/RobertsLab/resources/issues/708)):

```
#Sort the file by the gene start position (--key = 2,2) and only retain unique lines (--unique). Save output to a new file
sort --unique --key=2,2 2019-08-14-All-Annotated-Gene-and-mRNA.csv \
> 2019-08-14-All-Annotated-Gene-and-mRNA-Unique.csv
```

[Input file](https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2019-08-14-Differentially-Methylated-Genes/2019-08-14-All-Annotated-Gene-and-mRNA.csv)

[Output file](https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2019-08-14-Differentially-Methylated-Genes/2019-08-14-All-Annotated-Gene-and-mRNA-Unique.csv)

Looking at the output, there are some genes with multiple mRNA:

![Screen Shot 2019-08-19 at 3 21 57 PM](https://user-images.githubusercontent.com/22335838/63303560-0cab9d80-c295-11e9-8abc-054ce8281c83.png)

Is there something I'm missing from my code?

**Comment by sr320** [comment]
Code is working in sense that all lines are unique... 

You need more code to select longest.

**Comment by kubu4** [comment]
What data is in each column (specifically, the columns containing only numbers)?

**Comment by yaaminiv** [comment]
![Screen Shot 2019-08-19 at 3 28 04 PM](https://user-images.githubusercontent.com/22335838/63303843-e6d2c880-c295-11e9-8aeb-713a85aad88c.png)

@kubu4:
1 - chromosome
2 - gene start pos
3 - gene end pos
4 - mRNA start pos
5 - mRNA end pos
6 - geneID
7 - Genbank iD
8 - Product
9 - mRNA Length

**Comment by kubu4** [comment]
What "defines" an mRNA in your data : 

`Genbank`? 

`gene.ID`?

**Comment by yaaminiv** [comment]
> What "defines" an mRNA in your data

`Genbank` is unique to each mRNA. `gene.ID` is what I used to match entries in the gene GFF with the mRNA GFF.

**Comment by kubu4** [comment]
Now, I think I'm confused. In your initial post, you have all unique mRNAs (i.e. `Genbank`), don't you? Isn't that what you want, unique mRNAs (i.e. the longest of each `Genbank` entry)?

**Comment by yaaminiv** [comment]
> Isn't that what you want, unique mRNAs (i.e. the longest of each Genbank entry)?

Ah no! I don't want the longest of each `Genbank` entry. I want the longest for each `geneID` entry, since I only want the longest corresponding mRNA for each gene.

**Comment by yaaminiv** [comment]
I tried sorting and retaining unique `geneID`, but I'm missing a lot of data.

Output when sorting and retaining unique `geneID`:

![Screen Shot 2019-08-19 at 3 51 00 PM](https://user-images.githubusercontent.com/22335838/63304792-2b139800-c299-11e9-8c24-173f8e2ffdb9.png)

Examples of entries that should be there but aren't are in the white boxes

![Screen Shot 2019-08-19 at 3 50 52 PM](https://user-images.githubusercontent.com/22335838/63304857-78900500-c299-11e9-8e65-fabd00061976.png)
:

**Comment by kubu4** [comment]
I think this will do it, but admittedly, I'm not really sure what's going on and I didn't do extensive testing. I'll try to figure out how it works. Also, I'm assuming your data is already sorted.

`awk -F"," '!x[$6]++' 2019-08-14-All-Annotated-Gene-and-mRNA.txt`

**Comment by yaaminiv** [comment]
@kubu4 My file is already sorted, and it works! Output [here](). I'm interested to know why it works as well (explainshell wasn't very helpful).

**Comment by yaaminiv** [comment]
According to [this link](https://linuxaria.com/article/6-trucchi-con-awk):

```
Using awk, find duplicates in a file without sorting, which reorders the contents. awk will not reorder them, and still find and remove duplicates which you can then redirect into another file.

awk '!x[$0]++'
```

So it's looking at the 6th field (gene ID) and removing duplicates...?

**Comment by kubu4** [comment]
This is the best explanation I've found so far:

https://unix.stackexchange.com/questions/159695/how-does-awk-a0-work

It seems that most people will actually write it as:

`awk !seen[$0]++` (this example actually compares each full line - we only wanted to compare the values in field 6 of your file: `$6`)

I still don't fully grasp it, but here's what I think I've figured out so far:

This is creating an associative array named `seen` (or, in the solution I posted above, the array was named `x`). It reads each specified value in to the array, line by line, and compares it with the previous entry. If the value has _not_ been encountered (i.e. seen) before (the _not_ is indicated by the `!`), then the array will print the line from which that value was encountered and increment the array index (that's the `++` part). The print command is not explicitly stated because the default behavior of any `awk` command is: `{ print $0 }` which prints the entire line. The command becomes a bit easier to follow if the print command is added: `awk !seen[$0]++ { print $0 }`

The main thing I don't understand has to do with the incrementing the index and how it works with populating the array.

**Comment by kubu4** [comment]
Just adding for posterity.

So, the associative array works like this; it has an index and and associated value. The "catch" here (and this is what was throwing me off in understanding how the incrementing worked in the above awk command) is that the index is a _string_. 

Usually, an array has an index (or, position) and a corresponding element. E.g. a bash array could is created like this:

`array=(pizza hotdog popcorn)`

- pizza is at index 0
- hotdog is at index 1
- popcorn is at index 2

The awk associative array is created like this:

`arrayname[string]=value`

So, the incrementing in the awk command is incrementing the _value_ associated with a given _string_ in the array! 

When we run this:

`awk -F"," '!x[$6]++' 2019-08-14-All-Annotated-Gene-and-mRNA.txt`

Here's how it all works (remember, awk reads the input file line by line):

1. `-F",": Set field delimiter as comma, so awk knows how each field (column) is separated.
2. `!x[$6]`: If the contents in field 6 (`$6`), which is your `gene.ID` column, is _not_ found in the index of the array named `x`, do the following:
  - enter the contents of field 6 as a new index in the array
  - print the current line
3. `++`: If the contents in field 6 match an existing index in the array, the increment the value associated with the index by 1. The line is _not_ printed.

So, essentially, this just prints the first occurrence of each value in field 6.

Hope this helps clear this up for you and for future me! :timer_clock: :space_invader: :man_astronaut:
