### ISSUE TITLE
Uploading RAW DIA data to PRIDE

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#734]
Looking at the command line doc that Austin sent me ([link](https://docs.google.com/document/d/1J-cVPac-JsKqZQcq5P6v6b9yw4vUyc5MMTghqLUNGz8/edit)), I see that the output files are:     

![EncyclopeDIA-output-files](https://user-images.githubusercontent.com/14934314/63716639-4d5a6800-c7fb-11e9-924d-02584057f3af.PNG)

### **Are those the percolator files you are talking about @emmats ?**
> In the past, we have included percolator files as the "search" files in a DIA submission when I used Pecan

If yes, using the GUI for Encyclopedia DID in fact create and save 4 of those files in my directory (allong with a bunch of others)! **The one file it doesn't seem to create is the .mzML.pecan.txt.log**

![percolator-files](https://user-images.githubusercontent.com/14934314/63716773-a5916a00-c7fb-11e9-81fd-c8dbbadc31aa.PNG)

**Comment by emmats** [comment]
Sorry this took so long. Here is Brian Searle's response:
Pride isn’t really set up for DIA search results, so I would recommend that they just upload a “partial” submission with raw files only (no search results). They can still get a Pride accession number with that type of submission.

**Comment by grace-ac** [comment]
I emailed the PRIDE support people, but maybe you know, @emmats :     

What am I missing? It won't let me continue to the next section of the partial submission until I fulfill this:     

![Screen Shot 2019-09-04 at 12 40 07 PM](https://user-images.githubusercontent.com/14934314/64287599-f9473600-cf14-11e9-839b-c799d302ef7e.png)

**Comment by emmats** [comment]
They want search result files. I thought that was required, even for a partial submission. I'll follow up with Brian.

**Comment by emmats** [comment]
Update from Brian: I typically upload to Massive, which can do a partial submission with only raw files. Looking at the Pride docs, the partial submission needs search results, but they can be in any format so you can upload the *.elib files for each individual search. See this for more info: https://www.ebi.ac.uk/pride/help/archive/submission

**Comment by grace-ac** [comment]
@emmats , any ideas on what modifications were done for this? It's a long list, and is a required response... 

![Screen Shot 2019-09-11 at 10 43 44 AM](https://user-images.githubusercontent.com/14934314/64721395-44b39400-d481-11e9-97e8-860af4993fbc.png)

**Comment by emmats** [comment]
I think "none" should be an option.

**Comment by grace-ac** [comment]
I selected "No PTMS", which means "no post-translational modifications".
