### ISSUE TITLE
Troubleshoot Apex and/or order new controller

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#736]
The [apex controller base unit](https://www.bulkreefsupply.com/apex-controller-base-unit-neptune-systems.html) (serial number AC5:29413) currently does not turn on. We are missing [the power supply it came with](https://www.bulkreefsupply.com/12v-power-supply-neptune-systems.html?gclid=EAIaIQobChMI1N2X8a-n5AIVieNkCh0ifQC0EAQYASABEgIpevD_BwE). Attached is communication about what troubleshooting I attempted and suggestions Sam G. received but did not get through. If anyone has time to troubleshoot, all the equipment is in room 213 near the CO2 canister. 
[TroubleshootingApexFeb2019.pdf](https://github.com/RobertsLab/resources/files/3554026/TroubleshootingApexFeb2019.pdf)

**Comment by sr320** [comment]
just order new one
