### ISSUE TITLE
Troubleshoot traceable high precision thermometer

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#737]
Determine whether the module or the USB temperature probe is bad. Call tech support to find out best way to troubleshoot (281-482-1714; [product #:6412CC](https://www.traceable.com/6412-traceable-platinum-ultra-accurate-digital-thermometer.html)). Alternatively, find another USB temperature probe to plug into the module or plug traceable high precision USB temperature probe into a different module. ![IMG_20190724_112225](https://user-images.githubusercontent.com/4720221/63914148-2bbdd400-c9e7-11e9-9425-923e7180f253.jpg).

**Comment by sr320** [comment]
@shellytrigg status?

**Comment by sr320** [comment]
Needs to be purchased
