### ISSUE TITLE
opening .jar with java: not working

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#739]
Need this .jar to submit RAW data to PRIDE. I updated java. 

Pride GUI is not opening. I get this error:        
![Capture-issue](https://user-images.githubusercontent.com/14934314/64213977-8762e400-ce63-11e9-902c-3c93f5d59a80.PNG)

**Comment by kubu4** [comment]
Does the README have any tips?

**Comment by grace-ac** [comment]
another option was to use command line, but `java` command didn't work:      
![Capture-command](https://user-images.githubusercontent.com/14934314/64214270-aca42200-ce64-11e9-97f8-6af2e7027c83.PNG)

**Comment by kubu4** [comment]
You'd have to run that using Git Bash or Ubuntu for Windows. With that said, maybe try running on a Mac?

**Comment by grace-ac** [comment]
got it to work on mac! thanks
