### ISSUE TITLE
Tentative project plans for Manchester this year

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#74]
At tomorrow's hatchery meeting I'll need to provide any tentative plans for research through summer 2018.  So far I'm aware of: 
  * short-term OA experiment with my juvenile Olys, likely this winter
  * geoduck OA exp (Hollie's) - spring 2018?

**Comment by sr320** [comment]
Please indicate you are aware Steven has several funded and pending projects that involve the hatchery but they will need to contact me for details. I am currently swamped in proposal writing.
