### ISSUE TITLE
Error running bismark on Mox

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#740]
I'm trying to run `bismark` on Mox with [this script](https://github.com/fish546-2018/yaamini-virginica/blob/master/scripts/2018-11-08-Bismark-Revised-Parameters-Samtools.sh). I encountered this error:

<img width="583" alt="Screen Shot 2019-09-04 at 10 36 31 AM" src="https://user-images.githubusercontent.com/22335838/64277707-de1dfb80-ceff-11e9-970e-b0d217ae4a1c.png">

Is there a different format for this option I should use instead? I looked at `sbatch --help` and couldn't find anything.

**Comment by kubu4** [comment]
`--workdir` is no longer in user. Use `--chdir`.

Also, for brevity, you can just initiate your job run by typing: `sbatch script_name.sh`

**Comment by kubu4** [comment]
Also, Shelly mentioned this the other day: https://genefish.slack.com/archives/CDCGTGKU2/p1565368552001800

**Comment by yaaminiv** [comment]
Gotcha. Haven't paid that much attention to the Mox channel lately. Thanks!
