### ISSUE TITLE
tax BLAST: general help requested

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#748]
### Need general help with understanding these resources and how to get a blast going that will give me desired results. 

found this link in a notebook post of mine from [Nov 2018](https://grace-ac.github.io/tax-nt-BLAST-no-data/): 
### ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump_readme.txt

Sam gave it to me to help with taxonomy BLAST.  It is supposed to help me get deeper taxonomy data back from the BLAST

Unsure how to use this information in the readme. 

Does it seem like a useful thing?

**Comment by grace-ac** [comment]
Does this seem close to something that might work?        

It still doesn't have columns that will tell me phylum, class, order, but I put in the exclusion for mammalia, and the taxIDs for dinoflagellates and crustacea.... 

```
#!/bin/bash
## Job Name
#SBATCH --job-name=0912-crab-blastn-tax
## Allocation Definition
#SBATCH --account=coenv
#SBATCH --partition=coenv
## Resources
## Nodes 
#SBATCH --nodes=1
## Walltime (days-hours:minutes:seconds format)
#SBATCH --time=4-00:00:00
## Memory per node
#SBATCH --mem=100
##turn on e-mail notification
#SBATCH --mail-type=ALL
#SBATCH --mail-user=graceac9@uw.edu
## Specify the working directory for this job
#SBATCH --workdir=/gscratch/srlab/graceac9/analyses/091319-Cb-tax-blastn

export BLASTDB=/gscratch/srlab/blastdbs/ncbi-nr-nt-20181114/

/gscratch/srlab/programs/ncbi-blast-2.8.1+/bin/blastn \
-query /gscratch/srlab/graceac9/query/library01/query.fa \
-db /gscratch/srlab/blastdbs/ncbi-nr-nt-20181114/nt\
-out /gscratch/srlab/graceac9/analyses/091219-Cb-tax-blastn/091319-Cb-tax-blast.tab \
-max_target_seqs 1 \
-evalue 1e-20 \
-negative_taxidlist 40674 \
-taxidlist 2864 \
-taxidlist 6657 \
-outfmt "6 qseqid sseqid evalue bitscore staxids sscinames scomnames sskingdoms" \
-num_threads 28 \
-task blastn
```

**Comment by sr320** [comment]
worth a shot

looks like missing space at `1114/nt\`

**Comment by grace-ac** [comment]
Error message:    

>USAGE
  blastn [-h] [-help] [-import_search_strategy filename]
    [-export_search_strategy filename] [-task task_name] [-db database_name]
    [-dbsize num_letters] [-gilist filename] [-seqidlist filename]
    [-negative_gilist filename] [-negative_seqidlist filename]
    [-taxids taxids] [-negative_taxids taxids] [-taxidlist filename]
    [-negative_taxidlist filename] [-entrez_query entrez_query]
    [-db_soft_mask filtering_algorithm] [-db_hard_mask filtering_algorithm]
    [-subject subject_input_file] [-subject_loc range] [-query input_file]
    [-out output_file] [-evalue evalue] [-word_size int_value]
    [-gapopen open_penalty] [-gapextend extend_penalty]
    [-perc_identity float_value] [-qcov_hsp_perc float_value]
    [-max_hsps int_value] [-xdrop_ungap float_value] [-xdrop_gap float_value]
    [-xdrop_gap_final float_value] [-searchsp int_value] [-penalty penalty]
    [-reward reward] [-no_greedy] [-min_raw_gapped_score int_value]
    [-template_type type] [-template_length int_value] [-dust DUST_options]
    [-filtering_db filtering_database]
    [-window_masker_taxid window_masker_taxid]
    [-window_masker_db window_masker_db] [-soft_masking soft_masking]
    [-ungapped] [-culling_limit int_value] [-best_hit_overhang float_value]
    [-best_hit_score_edge float_value] [-subject_besthit]
    [-window_size int_value] [-off_diagonal_range int_value]
    [-use_index boolean] [-index_name string] [-lcase_masking]
    [-query_loc range] [-strand strand] [-parse_deflines] [-outfmt format]
    [-show_gis] [-num_descriptions int_value] [-num_alignments int_value]
    [-line_length line_length] [-html] [-max_target_seqs num_sequences]
    [-num_threads int_value] [-remote] [-version]

> DESCRIPTION
   Nucleotide-Nucleotide BLAST 2.8.1+

> Use '-help' to print detailed descriptions of command line arguments
========================================================================

> Error:  (CArgException::eSynopsis) Argument with this name is defined already: taxidlist

**Comment by sr320** [comment]
probably does not like to see taxidlist twice.

**Comment by grace-ac** [comment]
1. Removed one taxidlist. (had negative_taxidlist for mammalia, and taxidlist for dinoflagellate): 
>Error:  (CArgException::eConstraint) Argument "taxidlist". Incompatible with argument:  `negative_taxidlist' 



2. Removed 'negative_taxidlist' and kept taxidlist for dinoflagellates: 
> BLAST query/options error: File is not acessible: 2864
Please refer to the BLAST+ user manual.


Will look back at the manual now...

**Comment by sr320** [comment]
I think 2864 needs to refer to a file...

**Comment by grace-ac** [comment]
1. made 2864 into a file called `2864.taxids` like this:    

```
$ get_species_taxids.sh -n Enterobacterales
Taxid: 91347
 rank: order
 division: enterobacteria
 scientific name: Enterobacterales
 common name:
1 matches found
$ get_species_taxids.sh -t 91347 > 91347.txids
```

2. changed in script to `-taxidlist /gscratch/srlab/graceac9/files/2864.taxids \` 

`slurm` message: 
> Warning: [blastn] Examining 5 or more matches is recommended
BLAST Database error: Taxonomy filtering is not supported in v4 BLAST dbs
