### ISSUE TITLE
BLASTx to GOslim: gsort command not found

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#750]
Notebook: [here](https://github.com/RobertsLab/project-crab/blob/master/notebooks/091419-hemat-BLAST-to-slim.ipynb) 

how can I get `gsort` to work?  
![Screen Shot 2019-09-14 at 12 34 52 PM 1](https://user-images.githubusercontent.com/14934314/64912976-59e02b00-d6ec-11e9-9c10-37e843eab3d4.png)

**Comment by sr320** [comment]
Likely not installed on your machine

I can run later this afternoon...

See https://superuser.com/questions/334450/equivalent-of-gnu-sort-r-on-osx

For installing gsort on your machine

**Comment by grace-ac** [comment]
installation worked - completed notebook: [091419-hemat-BLAST-to-slim.ipynb](https://github.com/RobertsLab/project-crab/blob/master/notebooks/091419-hemat-BLAST-to-slim.ipynb)

hematodinium GOslim list: [hemat-Blastquery-GOslim.sorted](https://github.com/RobertsLab/project-crab/blob/master/analyses/hemat-Blastquery-GOslim.sorted)     
Only 27 GOslim terms...

**Comment by grace-ac** [comment]
All GOslim terms in [hemat-Blastquery-GOslim.sorted](https://github.com/RobertsLab/project-crab/blob/master/analyses/hemat-Blastquery-GOslim.sorted) are "other molecular function" and there are only 27 blast hits... seems like a low number and it's also a very non-descriptive GOslim term. 

Could I have done something wrong?

**Comment by sr320** [comment]
how many blastx hits on with uniprot for the entire transcriptome?

**Comment by grace-ac** [comment]
384,072 ([Blastquery-GOslim.sorted)](https://raw.githubusercontent.com/fish546-2018/grace-Cbairdi-transcriptome/master/analyses/Blastquery-GOslim.sorted))

**Comment by grace-ac** [comment]
used wrong file- let me do over and i'll let you know if i get something different @sr320

**Comment by grace-ac** [comment]
blastx hits from uniprot with entire transcriptome: 154,858 

http://owl.fish.washington.edu/scaphapoda/grace/PCSGA-2019/1108-cbairdiblast-sprot.tab

**Comment by sr320** [comment]
And how many of the 150k hits are dinoflagellates based on the file I provided?

**Comment by grace-ac** [comment]
would that be the # hits in your transcriptome-dinoflagellate blastx? 34,256 

I did an `anti_join` between the uniprot-transcriptome blastx hits and the blastx that you sent on slack and got 114,379 for crabs. 

markdown script for the `anti_join`: [sep_crab-hemat-genes.Rmd](https://github.com/RobertsLab/project-crab/blob/master/scripts/sep_crab-hemat-genes.Rmd)

**Comment by sr320** [comment]
(the anti_join is what I was referring to)

Ok so looks like you are on the right path…

You have a uniprot blast from crabs @ 114k sequences

and a unitprot blast for hematodinium @ 40k sequences

So it is just a matter of summarizing those two data sets

**Comment by grace-ac** [comment]
Does it seem right that of those 40k sequences for hematodinium, that there would be 27 GOslim terms that are all "other molecular function"?

**Comment by sr320** [comment]
Nice R code !

in addition to anti join , you also just needed an inner...

see https://github.com/sr320/nb-2019/blob/master/C_bairdi/10-crab_v_hemat.Rmd

with two resulting table that can now be summarized.. 
https://github.com/sr320/nb-2019/blob/master/C_bairdi/analyses/crab-blastx-sp.tab
https://github.com/sr320/nb-2019/blob/master/C_bairdi/analyses/hemat-blastx-sp.tab

**Comment by grace-ac** [comment]
That makes sense now!! Thank you!

**Comment by grace-ac** [comment]
New results:     
[crab-Blastquery-GOslim.sorted ](https://raw.githubusercontent.com/RobertsLab/project-crab/master/analyses/crab-Blastquery-GOslim.sorted)       
690633 terms      
          Notebook: [091419-crab-BLAST-to-slim.ipynb](https://github.com/RobertsLab/project-crab/blob/master/notebooks/091419-crab-BLAST-to-slim.ipynb)
         
[hemat-Blastquery-GOslim.sorted](https://raw.githubusercontent.com/RobertsLab/project-crab/master/analyses/hemat-Blastquery-GOslim.sorted)     
237971 terms       
Notebook: [091419-hemat-BLAST-to-slim.ipynb](https://github.com/RobertsLab/project-crab/blob/master/notebooks/091419-hemat-BLAST-to-slim.ipynb)
