### ISSUE TITLE
C. gigas blast output?

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#751]
@sr320 Is there `blastx` output for *C. gigas* anywhere? Or an annotated *C. gigas* transcriptome? I want to look at the functions of genes with DML, but [the gene GFF](https://eagle.fish.washington.edu/trilobite/Crassostrea_gigas_v9_tracks/Cgigas_v9_gene.gff) I'm using doesn't include that information.

**Comment by sr320** [comment]
I have this based on Gigaton https://raw.githubusercontent.com/sr320/nb-2019/master/C_gigas/analyses/Cgigaton_sprot_name.sorted


but imagine you need CGI IDs… will keep looking

**Comment by yaaminiv** [comment]
Yeah, I found some of my own stuff too but the IDs don't match the CGI IDs in the gff. Thank you!

**Comment by sr320** [comment]
Here is fasta with CGI ids.. including gene names.
https://gannet.fish.washington.edu/seashell/snaps/Crassostrea_gigas.oyster_v9.cdna.all.fa
I will start a sp blast now on it.

**Comment by yaaminiv** [comment]
Thank you! I got revised files off Mox so I'm taking them through the analysis pipeline right now. Hoping I can present some gene names, if not an enrichment, for tomorrow.

**Comment by sr320** [comment]
related I have updated wiki re gigas https://github.com/RobertsLab/resources/wiki/Genomic-Resources#crassostrea-gigas

**Comment by sr320** [comment]
Here is a blast output..
https://gannet.fish.washington.edu/seashell/bu-mox/analyses/0913/Cg_v9_blastx_uniprot.05.tab


but it does not look quite right… not a lot of CGIs…

**Comment by yaaminiv** [comment]
I tried annotating my DML-Gene overlaps at the bottom of [this notebook](https://github.com/RobertsLab/project-gigas-oa-meth/blob/master/notebooks/2019-09-15-DML-Analysis.ipynb) and I didn't get any annotations. Either I messed up the code or the genes with DML are not annotated...

**Comment by yaaminiv** [comment]
Looks like there are only 9 lines with CGI codes in the `blast` output out of 16,456 lines total:

![Screen Shot 2019-09-16 at 10 30 48 AM](https://user-images.githubusercontent.com/22335838/64979667-01846700-d86d-11e9-9ad2-74c7dcc5a411.png)

**Comment by yaaminiv** [comment]
@sr320 What fasta file is annotated with gene names? I don't see any in the genome fasta or gene GFF linked on the genomic resources page.

**Comment by yaaminiv** [comment]
![Screen Shot 2019-09-16 at 10 42 47 AM](https://user-images.githubusercontent.com/22335838/64980432-ad7a8200-d86e-11e9-8ac1-71419a1dbe8a.png)

**Comment by sr320** [comment]
>What fasta file is annotated with gene names? 
https://github.com/RobertsLab/resources/issues/751#issuecomment-531609598

**Comment by yaaminiv** [comment]
`blast` output used for prelim analysis: https://eagle.fish.washington.edu/cnidarian/oyster_v9_Gene_node2_blastout
