### ISSUE TITLE
Add Taxa Characterization to Metaproteomics paper

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#752]
I believe one at all library scale, at Class Level

and 2? others that complement what Emma has for metaproteome. (also Class level)

https://docs.google.com/document/d/1amaNX86VUDcXi0UGzgmHYt8QVe6fSuVcT1oYohlFCDM/edit?ts=5b918dab

**Comment by kubu4** [comment]
Updating. Running DIAMOND BLASTx on Mox, which should create files to load into MEGAN for taxonomic assessment/comparisons...

**Comment by sr320** [comment]
update?

**Comment by kubu4** [comment]
Ready for us to look at output/data. I can try to summarize some of the results and put in paper.
