### ISSUE TITLE
Question regarding oyster silos

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#754]
Q from interwebs...

>I have been looking through various resources etc. to find a setup that would work well for our facility and I think that the mini-silos (https://faculty.washington.edu/sr320/?p=13846) that have been used in your lab will be perfect. I did have a couple of questions about them that I was hoping you might be able to help me answer.

>When performing the water changes, do you remove the larvae (pass through a filter) and clean the silo, and then add the larvae back in, and then put the silo back into the tripour?

>In terms of any cleaning of the tripours/mini-silos/general apparatus, do you have any special procedures? We were thinking a quick wash with 15% HCl followed by liquinox (a phosphate free soap), then freshwater.

>When the adding the microcultch for setting, is there much settlement on the interior edges of the silo? If so, do you do anything to minimize this?

>What is the longest that you have taken the oysters in the silos? Have you transferred the oysters from silos into upwellers?

**Comment by laurahspencer** [comment]
I think I answered everything- feel free to send them my email address. 

_When performing the water changes, do you remove the larvae (pass through a filter) and clean the silo, and then add the larvae back in, and then put the silo back into the tripour?_

**Larvae remained in the silos during water changes, I simply moved the silos+larvae into new tripours with fresh water + algae. I had extra tripours so the larvae did not spend any time out of the water. The downside to this method is that any dead larvae/shells remained in the silos with live larvae. However, my stocking density was low (~1 larvae / mL), and the frequent water changes maintained relatively clean water (daily during larval phase, less frequently after settlement)**

_In terms of any cleaning of the tripours/mini-silos/general apparatus, do you have any special procedures? We were thinking a quick wash with 15% HCl followed by liquinox (a phosphate free soap), then freshwater._

No special cleaning methods, and no chemicals. During daily water changes I sprayed the empty tripours thoroughly with fresh water. If I didn't need to  use them immediately, I let them dry thoroughly upside down overnight. I occasionally sprayed the silos with freshwater gently- this effectively rinsed away residue/detritus, and cleaned the larvae (larvae were always shelled, so could withstand freshwater rinses).**

_When the adding the microcultch for setting, is there much settlement on the interior edges of the silo? If so, do you do anything to minimize this?_

**Yes, many larvae settled onto the silo. This didn't matter for my purposes, as I simply was counting survival, but  would be an issue if  you wanted to grow all settled oysters as singles. One way to minimize this would be to put the mini-silos into a downwelling system, where water flowed into the silos from the top.** 

_What is the longest that you have taken the oysters in the silos? Have you transferred the oysters from silos into upwellers?_

**I raised my oysters for 50 days in the mini-silos, then counted survival. I reduced water change frequency to every other day beginning at day 21. Yes, in a previous experiment I moved the oysters that held on a 450um screen to an upwelling system with 450um silos, and they grew large enough to put into bags made from window screen for long-term storage. Here are a few notebook posts with photos that might be helpful for that phase: https://laurahspencer.github.io/LabNotebook/oysters-are-growing-up/ https://laurahspencer.github.io/LabNotebook/Moved-Oly-seed/ https://laurahspencer.github.io/LabNotebook/Olys-and-Cleaning/**
