### ISSUE TITLE
Add PCSGA talks to Products page 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#755]
Publish and add slidedecks to Products at 
https://github.com/RobertsLab/website/blob/master/Products.md

(@laurahspencer and @shellytrigg) I incorporated your PR on old page into the new repo we created during hack week - thanks for the PRs!)

**Comment by yaaminiv** [comment]
done: https://doi.org/10.6084/m9.figshare.9897719.v1

**Comment by grace-ac** [comment]
add to Products

https://figshare.com/articles/Effects_of_Bitter_Crab_Disease_on_the_gene_expression_of_Alaskan_Tanner_Crabs/9898916
