### ISSUE TITLE
Install dDocent on mox

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#758]
See also details regarding installation on hummingbird: https://github.com/RobertsLab/resources/issues/143

**Comment by kubu4** [comment]
All done.

Add the following to your SBATCH script (at the top, after the header):

`module load ddocent.module`

That will load all the dependencies into your `$PATH`, which is required for dDocent.

The dDocent program is here:

`/gscratch/srlab/programs/dDocent-2.7.6/dDocent`

**Comment by kubu4** [comment]
I've also added a note on the Mox wiki about adding MODULEPATH to ~/.bashrc (in the Software section).
