### ISSUE TITLE
R error with lme

### ISSUE THREAD

**Issue by emmats** [RobertsLab/resources#759]
A reviewer has requested that I do a nested ANOVA. I am trying to do this in R, but keep on getting an error and I am not finding helpful information in resolving it online. I would appreciate any ideas! I haven't done this in a while, so it could just be a stupid mistake.

Here is my input file: https://drive.google.com/open?id=1AQVIxnGQIfsPv-wqXo-4Hr-olXibpqQn

Here is the code I am running (first, changing variables to factors):
size.lowpH$Age.Days=as.factor(size.lowpH$Age.Days)
size.lowpH$Treatment=as.factor(size.lowpH$Treatment)
size.lowpH$Conical=as.factor(size.lowpH$Conical)
library(nlme)
model = lme(Average.Size~Treatment+Age.Days, data=size.lowpH, method='REML')

And here is the error I keep getting: 
Error in getGroups.data.frame(dataMix, groups) : 
  invalid formula for groups

Ideally, I would also like to add Conical as a random factor, but I want to get this first part figured out first.

Thank you!

**Comment by kubu4** [comment]
Can you provide full script? The code you shared fails on the very first line:

```R
> size.lowpH$Age.Days=as.factor(size.lowpH$Age.Days)
Error in is.factor(x) : object 'size.lowpH' not found
```

**Comment by emmats** [comment]
size.lowpH is the name of the data file - sorry.
You should use something like this:
size.lowpH<-read.csv('larval sizes.csv', header=T)

**Comment by kubu4** [comment]
Check out the example found in:

```R
?lme()
```

It uses the `Orthodont` data set. When you run `str()` on that data set, this is the output:

```R
> str(Orthodont)
Classes ‘nfnGroupedData’, ‘nfGroupedData’, ‘groupedData’ and 'data.frame':	108 obs. of  4 variables:
 $ distance: num  26 25 29 31 21.5 22.5 23 26.5 23 22.5 ...
 $ age     : num  8 10 12 14 8 10 12 14 8 10 ...
 $ Subject : Ord.factor w/ 27 levels "M16"<"M05"<"M02"<..: 15 15 15 15 3 3 3 3 7 7 ...
 $ Sex     : Factor w/ 2 levels "Male","Female": 1 1 1 1 1 1 1 1 1 1 ...
 - attr(*, "outer")=Class 'formula'  language ~Sex
  .. ..- attr(*, ".Environment")=<environment: R_GlobalEnv> 
 - attr(*, "formula")=Class 'formula'  language distance ~ age | Subject
  .. ..- attr(*, ".Environment")=<environment: R_GlobalEnv> 
 - attr(*, "labels")=List of 2
  ..$ x: chr "Age"
  ..$ y: chr "Distance from pituitary to pterygomaxillary fissure"
 - attr(*, "units")=List of 2
  ..$ x: chr "(yr)"
  ..$ y: chr "(mm)"
 - attr(*, "FUN")=function (x)  
  ..- attr(*, "source")= chr "function (x) max(x, na.rm = TRUE)"
 - attr(*, "order.groups")= logi TRUE
```

When you run `str()` on your data, this is what you get:

```R
> str(size.lowpH)
'data.frame':	36 obs. of  4 variables:
 $ Conical     : Factor w/ 6 levels "1","3","5","6",..: 1 2 3 4 5 6 1 2 3 4 ...
 $ Treatment   : Factor w/ 2 levels "7.1","7.5": 1 2 1 1 2 2 1 2 1 1 ...
 $ Age.Days    : Factor w/ 6 levels "6","8","10","12",..: 1 1 1 1 1 1 2 2 2 2 ...
 $ Average.Size: num  5 6 3 1 4 2 10 8 9 7 ...
```

I don't know what this all means, but you're input is just a data frame, whereas the example has other classes associated with it. I don't have any idea what those data classes are or how to apply them to your data, but I figured I'd throw this observation out there in hopes that someone understands it...

**Comment by emmats** [comment]
If you actually look at the Orthodont data, it looks a lot like mine. And from the lme variable descriptions:

data | an optional data frame containing the variables named in fixed, random, correlation, weights, and subset. By default the variables are taken from the environment from which lme is called.

So I'm not convinced there is anything wrong with my data structure.

**Comment by emmats** [comment]
I got it to work! I'm not sure why because I didn't change the code really. I even got the random variable in there.

size.lowpH$Age.Days=as.factor(size.lowpH$Age.Days)
size.lowpH$Treatment=as.factor(size.lowpH$Treatment)
size.lowpH$Conical=as.factor(size.lowpH$Conical)
library(nlme)
model = lme(Average.Size~Treatment+Age.Days, data=size.lowpH, random=~1|Conical, method='REML')

anova.lme(model, type='sequential', adjustSigma = F)
