### ISSUE TITLE
Offline Notebook Access

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#76]
If onsnetwork goes down, how do we access Sam's Notebook?

My instinct is that routine archives would live at
https://github.com/RobertsLab/resources/wiki

**Comment by kubu4** [comment]
You would use the weekly backed up version of the notebook located on Eagle:

/Archive/notebooks/sam/onsnetwork.org/kubu4/index.html

**Comment by kubu4** [comment]
Or, wait, are you asking how we find the information about where people's notebooks are backed up (i.e. we should have links on GitHub wiki for everyone's backed up notebooks)?

**Comment by sr320** [comment]
My idea is that we should have a wiki page
Lab Notebook Archives
with urls to active notebook backups as well as alumni notebooks

**Comment by kubu4** [comment]
https://github.com/RobertsLab/resources/wiki/Lab-Notebooks
