### ISSUE TITLE
Advice on colors in a figure

### ISSUE THREAD

**Issue by emmats** [RobertsLab/resources#760]
Here is my original figure 
[nmds averaged reps.pdf](https://github.com/RobertsLab/resources/files/3682526/nmds.averaged.reps.pdf)

I need to remake the same figure, but with "higher contrast" colors so that the days can be more easily differentiated. There are 6 separate days/colors in the figure.
I've made the same figure with two different color schemes. Please let me know if either of them works better or if I need to keep working on this. Thanks!
[NMDS blue green.pdf](https://github.com/RobertsLab/resources/files/3682534/NMDS.blue.green.pdf)
[NMDS yellow orange brown.pdf](https://github.com/RobertsLab/resources/files/3682535/NMDS.yellow.orange.brown.pdf)

**Comment by sr320** [comment]
I like blue green - seems like making symbols larger would also help
