### ISSUE TITLE
Questions about MethylKit parameters for C. gigas

### ISSUE THREAD

**Issue by RoeArEs** [RobertsLab/resources#762]
Hello everybudy. I have a couple questions about MethylKit. Here I go...

In context of samples ID's I have:
Thermal-susceptible families (3 replicates per family): 
Family 05 = 0501, 0502 and 0503
Family 35 = 3501, 3502 and 3503
Thermal-resistant families:
Family 52 = 5201, 5202 and 5203
Family 59 = 5901, 5902 and 5903

1: The output results from group of samples analysis is different than phenotypes analysis.
In group of samples I have the considerations like:
## Samples IDS
sample_ids_list <- list("0501", "0502", "0503", 
                                   "3501", "3502", "3503",
                                   "5201", "5202", "5203", 
                                   "5901", "5902", "5903")
Afet, I used this assignation:
Set number of families 05, 35, 52 or 59 treatments.
0, 1, 2  3 is assigned to each sample ID corresponding to a particular treatment.
treatmentSpecification <- c(rep(0, times = 3), rep(1, times = 3), rep(2, times=3), rep(3, times=3))

This is the specification for families but NOT for phenotypes.
In this it looks that all will be compared taking the 0 as a reference. At the end I couldn't know where the differential methylation calls belongs. I mean, the difference will be assigned to which family?

Then I wanted to fix it considering phenotypes (Thermal-susceptible vs thermal-resistant) like:

Samples IDS
sample_ids_list <- list("0501", "0502", "0503", "3501", "3502", "3503",
                                   "5201", "5202", "5203",  "5901", "5902", "5903")
Set number of phenotypes TS or TR treatments.
0 or 1 assigned to each phenotype ID corresponding to a particular treatment.
treatmentSpecification <- c(rep(0, times = 6), rep(1, times = 6))

Here will be the same, taking 0 as a reference to compare against 1 (where 0 is thermal-susceptible).

2: In the methylation analysis, the percentage considerer could be 25 or 50. I understand how the result will be but in my case, Is it OK if I preferred 25? It is because I would like to see more data and infer if some DML or DMR are related with my differentially expressed genes between phenotypes in promoters.

**Comment by yaaminiv** [comment]
@RoeArEs what's your first question? I don't quite understand it

> In the methylation analysis, the percentage considerer could be 25 or 50. I understand how the result will be but in my case, Is it OK if I preferred 25? It is because I would like to see more data and infer if some DML or DMR are related with my differentially expressed genes between phenotypes in promoters.

That's up to you anyways! It could be interesting to test both 25 and 50 to see how much data you lost

**Comment by RoeArEs** [comment]
Yes, I am on it now. Testing the 25 %. I will let you know the difference. Thanks

**Comment by RoeArEs** [comment]
Well just the recommendations about what is the best score to use. I mean
50 or 25% but now I am on the process of 25.
I will have more data or at least I hope.
Thanks a lot!
Roberto
