### ISSUE TITLE
Test VTG primers on hemolymph samples

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#763]
@kubu4 could you make cDNA from [these samples](https://docs.google.com/spreadsheets/d/1BD0vHIYuGtAiwSTp922mS0Yw68bWshvRuNS41DyGHcs/edit?usp=sharing) and run qPCR using the vitellogenin primers you designed [here](https://genefish.wordpress.com/2018/12/10/sams-notebook-qpcr-geoduck-gonad-cdna-with-vitellogenin-primers/)?

**Comment by kubu4** [comment]
Are RNA concentrations listed on the tubes? If not, please post sample concentrations.

**Comment by shellytrigg** [comment]
Sorry for not clarifying:  Samples are hemolymph or hemocytes. RNA has not been extracted yet.

**Comment by kubu4** [comment]
Storage method (i.e. snap frozen, RNA later) and sample volume or are they pellets?

**Comment by shellytrigg** [comment]
snap frozen. hemocytes are pelleted before snap freezing. hemolymph samples have ~1mL.

**Comment by kubu4** [comment]
So, is supe still in tubes on top of pellets?

**Comment by shellytrigg** [comment]
The hemocyte samples are just pellets. The hemolymph samples I believe are not pelleted, I don't see a pellet when I look at the tubes. The hemolymph samples are from @grace-ac 's capstone and she briefly described the hemolymph samples back in [this issue](https://github.com/RobertsLab/resources/issues/476)

**Comment by shellytrigg** [comment]
@kaitlynrm mentioned she can help with this but hasn't done qPCR before, so maybe @kubu4 you can set her up to do it? Or she can shadow you?

**Comment by kubu4** [comment]
I'll coordinate with her.

**Comment by kubu4** [comment]
@shellytrigg 

There weren't any samples with these labels:

```
11/01/2018_1H
11/01/2018_2H
11/15/2018_1H
11/15/2018_2H
```

I've isolated RNA from the others in the list.

**Comment by shellytrigg** [comment]
@kubu4 sounds good. I think the 11/15 samples may have actually been called '11/15/2018_CH' and '11/15/2018_SH' instead of 1H and 2H. Sorry about that. Great that you got RNA from the other samples. That should be enough to test for VTG presence for now

**Comment by kubu4** [comment]
Cool.

**Comment by kubu4** [comment]
Quick rundown of results:

- No amplification in 39H

Otherwise, things looked fine (after adjusting annealing temp to 60<sup>o</sup>C). 

Notebook entry is here:

https://robertslab.github.io/sams-notebook/2019/11/27/qPCR-Geoduck-hemolymph-and-hemocyte-cDNA-with-vitellogenin-primers.html

**Comment by shellytrigg** [comment]
@kubu4 exciting that VTG amplified from pelleted hemocytes and mixed hemolymph+hemocyte!!! From what I've read, people have thought it to be synthesized in invert. gonad and hepatopancreas [see ref here](https://drive.google.com/open?id=1TkOKf_EjW1ZnxUD_lXtk34pm9Dc7GAFS). 

It turns out that G39 may have had something weird in it to begin with (see notes from [past calcium assay experiment](https://docs.google.com/spreadsheets/d/10PyIMrQopm2fmHF9SQpbmliy37cE41-oJ-s-NlxrFUQ/edit#gid=0)).

Here's @kubu4 's data next to the sample info:

| Sample    | Sex     | Stage   | Cq Mean     |
|-----------|---------|---------|-------------|
| 31H       | Female  | 4       | 35.50751498 |
| 57H       | Female  | 7       | 39.43161922 |
| 61H       | Female  | 7       | 33.18352799 |
| 11-08 1H  | unknown | unknown | 35.7555603  |
| 11-08  2H | unknown | unknown | 37.78256398 |
| Pos Ctrl  | pool    | pool    | 32.88824956 |

Since the idea behind this qPCR is to see if we can use these primers to determine sex and/or developmental stage, and now that we know we can amplify VTG from hemocytes, we next need to check the following:

1. some male samples. Hopefully they will show a difference from the female samples. If the males aren't distinguishable from the females, we may need to redesign the primers to be more specific to the vitellogenin isoform that's shown in the bottom of the fig. 6 heatmap in [Emma's paper](https://pubs.acs.org/doi/10.1021/acs.jproteome.7b00288) (shown below).
![Screen Shot 2019-12-04 at 3 51 14 PM](https://user-images.githubusercontent.com/4720221/70191630-3d7dda00-16ae-11ea-9790-7e32d8e5688b.png)

2. some additional female samples at different stages.

3. the additional samples from 11/1/18 and 11/15/18 that had inconsistent names with the sample list.

I've updated the [sample list](https://docs.google.com/spreadsheets/d/1BD0vHIYuGtAiwSTp922mS0Yw68bWshvRuNS41DyGHcs/edit#gid=0) with the additional samples listed in 1, 2, and 3 above. @kaitlynrm do you want to work with @kubu4 to prep these (make RNA and cDNA) and run qPCR? I will order a quick DNA/RNA zymo kit to replace what's been borrowed from Grace's kit.

**Comment by kaitlynrm** [comment]
Yes that'd be great! When do you have time @kubu4?

**Comment by kubu4** [comment]
I'm available any time (except for the times I'm not - check the lab calendar).

If you're going to tackle all of the samples for RNA isolation at one time, you should probably plan for 5 - 6hrs (that includes prep time and stuff). 

For the hemolymph samples, you'll only need/want to use 150uL of each sample; this will save you a TON of work/time and should yield ample quantities of RNA.

Be familiar with the [Zymo Quick DNA/RNA Microprep protocol before beginning](https://github.com/RobertsLab/resources/blob/master/protocols/Commercial_Protocols/ZymoResearch_quick-dna-rna_microprep_plus_kit_20190411.pdf).

**Comment by kaitlynrm** [comment]
Does extraction and cDNA production need to wait until new kits come in?

**Comment by kubu4** [comment]
Nope.

**Comment by shellytrigg** [comment]
New kit will be in today

**Comment by kaitlynrm** [comment]
Great! I'll be in Tuesday. Grad school apps are all due Sunday so I'm excited to start working on the geoduck samples and data analysis more once those are finished.

**Comment by shellytrigg** [comment]
@kaitlynrm in [your post](https://wp.me/p1QK1L-1fY) the RNA standards read different concentrations than what they should. Standard #1 is 0ng/uL and standard #2 is 10 ng/uL (see attached manual). Did you account for the dilution volume when you read the samples? See step 2.5 on page 4 of the manual.
[Qubit_RNA_HS_Assay_UG.pdf](https://github.com/RobertsLab/resources/files/3980027/Qubit_RNA_HS_Assay_UG.pdf)

**Comment by kubu4** [comment]
@shellytrigg - The standard values she lists in that table are actually the RFU values for the two standards, not their concentrations. 

@kaitlynrm Did you actually measure their concentrations? Also, it would be best if you exported the data from the Qubit and put the raw data (or, a link to data) in your notebook. The raw data sheet also contains important/useful info like sample volume that was set.

**Comment by kaitlynrm** [comment]
@kubu4 When measuring the samples, the units were listed as ng/ul. However I am not sure about the standards. Sample volume was set at 1ul. I did 199ul of working solution to 1ul of sample. I will be sure to export the file next time!

**Comment by kubu4** [comment]
> I will be sure to export the file next time!

All the data is still on the Qubit. Next time you're in, you can export the data files and update your notebook.

**Comment by kaitlynrm** [comment]
Great! Then I can move between units to understand if there was an error during the prep or an error when recording the units?

**Comment by kaitlynrm** [comment]
@shellytrigg I will export the data on Friday and then see if I should redo the Qubit analysis. Does that sound good?

**Comment by kubu4** [comment]
> Then I can move between units to understand if there was an error during the prep or an error when recording the units?

I'm not sure what you mean by this. There aren't any obvious problems with your data. 

If you're referring to the values you listed for the standards, you simply listed the RFU values; the Qubit doesn't calculate a concentration for the standards (since they're "known").

**Comment by kubu4** [comment]
> see if I should redo the Qubit analysis

In regards to this, the only thing you might want to consider re-running is the samples that were too low to measure. You could try to re-run them using a larger sample volume. However, this decision should be guided by how much sample you have remaining and how much you might need for reverse transcription.

**Comment by kaitlynrm** [comment]
14ul should be remaining in the tubes. After I measured all values, I did re-check all the low values just in case.
