### ISSUE TITLE
Run blastx on Geoduck gene list to get putative gene names

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#764]

**Comment by sr320** [comment]
take current blast - check # hits, evlaue and get GOs

**Comment by sr320** [comment]
@kubu4 can you take your newest annotation at 
https://gannet.fish.washington.edu/Atumefaciens/20190928_Pgenerosa_v074.a4_gensas_annotation/Panopea-generosa-vv0.74.a4.5d951a9b74287-blast_functional.tab

and filter by only taking a single, top hit for each contig and limiting the evalue to 1e-10.

**Comment by kubu4** [comment]
Other than the e-value cutoff (it was run with a cutoff of 1e-8), the file only has a top result for each mRNA (i.e. each line is a unique mRNA annotation).

**Comment by kubu4** [comment]
Do you want me to just get rid of entries with higher e-values than the 1e-10 cutoff proposed above?

**Comment by sr320** [comment]
No need. Sorry - I thought some of the bit scores were evalues. .. this is good. Can you pull down GO IDs based on Unitprot Accessions?

**Comment by kubu4** [comment]
Will do.

**Comment by kubu4** [comment]
I should have asked earlier, but what do you want in the output file? I may have wasted a decent chunk of time working on joining the GO IDs to that tab-delimited file linked above...

**Comment by kubu4** [comment]
It looks like you've already done this, but here're links to how I did it (basically the same approach as you):

output file: https://gannet.fish.washington.edu/Atumefaciens/20191022_pgen_Pgen_v074.a4_BLAST-GO-mapping/20191022_Panopea-generosa-vv0.74.a4.5d951a9b74287-blast_functional_sp_id-join-go_id.tab

Jupyter notebook: https://github.com/RobertsLab/code/blob/master/notebooks/sam/20191022_swoose_pgen_v074.a4_BLAST-GO-mapping.ipynb

**Comment by shellytrigg** [comment]
@kubu4 @sr320 is this output file the final GO ID mappings that we should be using for funcitonal analysis? If so, is it on OSF?

https://gannet.fish.washington.edu/Atumefaciens/20191022_pgen_Pgen_v074.a4_BLAST-GO-mapping/20191022_Panopea-generosa-vv0.74.a4.5d951a9b74287-blast_functional_sp_id-join-go_id.tab

**Comment by hputnam** [comment]
@sr320 @shellytrigg @kubu4 I was previously using Panopea-generosa-vv0.74.a4.5d951a9b74287-blast_functional.tab2019-10-25 04:37 PM from OSF https://osf.io/yem8n/ in the GenSas_out folder, but it would be ideal and reduce manual curation of the GO analysis if there was a Uniprot to GO mapping that already existed on OSF. Thanks!

**Comment by kubu4** [comment]
@shellytrigg @hputnam Offhand, I'm not sure of the history, but looking throught the OSF repo, I think you want this file:

https://osf.io/4etsu/

I'll do some sleuthing to see if I can figure out where this one came from. To me, the naming is clear (i.e. it's annotations of _P.generosa_ genes), but not sure how it was produced.

**Comment by hputnam** [comment]
Yes, this has the necessary content of uniprot and GO. I will test with this one as you check for its origin. Thanks!
