### ISSUE TITLE
measure juvenile geoduck shell length with imageJ

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#767]
@H-Ra, could you help me collect shell length data from a geoduck experiment that just ended? Photos of animals are [here](https://drive.google.com/open?id=1Fo1ivUR7BfpKmSORCCNycfcqYoCKQ_LC). I've created [this google sheet](https://docs.google.com/spreadsheets/d/1Y75kqmWWuAink48U4vHjgaEWLgbKEyJRrspbAxzW3jc/edit?usp=sharing) to enter the data into. Have you used imageJ before? When's a good time to meet to discuss this in more detail?

**Comment by H-Ra** [comment]
@shellytrigg Sure, I'd love to help! I haven't used imageJ before, but I have seen other people use it, so I'm familiar with the program. I am meeting Sam White this Thursday at 10:30 am to discuss lab safety information, so I could meet you either before or after the meeting (anytime before 12:30pm), if you would be able to meet then?

**Comment by shellytrigg** [comment]
@H-Ra Thursday after you meet with Sam would work perfect. My office is FTR 234 (next to Steven's). ImageJ can seem complicated because it can do so much, but these measurements are fairly straightforward and we'll go over how to do it together. Thanks Hana and see ya Thursday!

**Comment by H-Ra** [comment]
@shellytrigg Sounds good! Look forward to seeing you on Thursday!

**Comment by shellytrigg** [comment]
@H-Ra here's the link to the protocol we came up with: https://github.com/shellytrigg/P_generosa/blob/master/amb_v_varlowpH_juvis/ImageJ_shelllength_protocol.md

**Comment by H-Ra** [comment]
@shellytrigg Hi Shelly! I've been doing the measurements from the juvenile geoduck images, and I have been having some trouble distinguishing if some of the geoducks are dead or alive. I've attached some examples of geoducks I've been struggling with, and I was wondering if you could tell me if they are alive (aka should measure) or not alive (aka should not measure)? 

I know in eg.1, both of the geoduck are considered not alive since there siphons are not plump and they don't look very "round" overall, but for eg.2, eg.3, and eg.4, I am not sure how to identify them (they seem to be something in-between alive and not alive). Thank you very much!

![eg 1](https://user-images.githubusercontent.com/56777085/68094613-2782bc80-fe57-11e9-8074-0bd0763c7e73.png)
![eg 2](https://user-images.githubusercontent.com/56777085/68094614-281b5300-fe57-11e9-9841-b1e046ffbb63.png)
![eg 3](https://user-images.githubusercontent.com/56777085/68094616-281b5300-fe57-11e9-9c1b-a4d812f50e1e.png)
![eg 4](https://user-images.githubusercontent.com/56777085/68094615-281b5300-fe57-11e9-83c8-9d0925c31c7e.png)

**Comment by H-Ra** [comment]
@shellytrigg Hi Shelly! Just to clarify on my last message, eg.1 refers to the first image, eg.2 refers to the second image, and so on and so forth. Thank you!

**Comment by H-Ra** [comment]
@shellytrigg Hi Shelly! I have one final question about the measurements. There are sometimes objects in the image that look like bare shells (there doesn't seem to be a siphon). I was wondering if these shells should be measured? I have attached a few examples below. 

Also, I was wondering if you were available to meet sometime this week to talk about the measurements? I am planning on coming to lab on Thursday morning, so I would be able to meet you then, if that works for you?

![eg 5](https://user-images.githubusercontent.com/56777085/68100784-cbcc2980-fe7e-11e9-8c9e-8462d93ca583.png)
![eg 6](https://user-images.githubusercontent.com/56777085/68100785-cbcc2980-fe7e-11e9-90cb-128790afad2e.png)
![eg 7](https://user-images.githubusercontent.com/56777085/68100786-cbcc2980-fe7e-11e9-885a-d1650022b7f6.png)

**Comment by shellytrigg** [comment]
@H-Ra I would measure all of the above. In reference to your first comment, I think all of those animals are alive but probably not super healthy. The ones that are more obviously dead have siphons that look really shriveled up and translucent. In reference to your third comment, those are animals that have retreated their siphons. You can tell because their mantle is visible outside their shell. If the shells were open  and there was little to no tissue inside, I would not measure them. I am available Thursday am so let's meet then. Your example measurements look great! Thanks Hannah and let me know if you have any other questions before Thursday.

**Comment by H-Ra** [comment]
@shellytrigg Thank you very much for the clarification! That means that I should measure the two geoducks in the first image in the first comment I made as well? 

I will definitely let you know if I have any other questions before our meeting. I look forward to meeting you on Thursday!

**Comment by shellytrigg** [comment]
@H-Ra correct

**Comment by shellytrigg** [comment]
Hana's analysis [here](https://github.com/shellytrigg/P_generosa/tree/master/amb_v_varlowpH_juvis/analyses/20191018_ShellLength)

**Comment by shellytrigg** [comment]
![](https://raw.githubusercontent.com/shellytrigg/P_generosa/master/amb_v_varlowpH_juvis/analyses/20191018_ShellLength/Density%20Plot%20of%20Experimental%20Groups.jpeg)

**Comment by shellytrigg** [comment]
There is a significant parental history effect by two-way ANOVA where the var.low offspring in var.low conditions show a larger size distribution than 1) ambient offspring in ambient conditions (adj. p = 0.0000052 Tukey HSD), 2) ambient offspring in var.low pH conditions (adj. p = 0.0000075 Tukey HSD), and 3) var.low pH offspring in ambient conditions (adj. p = 0.0000324 Tukey HSD)
