### ISSUE TITLE
Generate karyotypeR figure for Geoduck Genome

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#771]
The following code should get chromosomes..
https://github.com/sr320/nb-2019/blob/master/P_generosa/55-karotypeR.Rmd

**Comment by sr320** [comment]
An example with Cv data. https://htmlpreview.github.io/?https://github.com/epigeneticstoocean/2017OAExp_Oysters/blob/master/markdown_files/compareGonadMantle/CompareGonadMantle.html

**Comment by shellytrigg** [comment]
here's as far as I got in the KaryotypePlotR stuff. Added lines 209 to 234 for trying to plot Yaamini's data. It plots %methylation as points for each loci across all chromosomes but something is off with the scaling so the points from different chromosomes bleed into others [https://github.com/shellytrigg/Shelly_Pgenerosa/tree/master/analyses/karyotype](https://github.com/shellytrigg/Shelly_Pgenerosa/tree/master/analyses/karyotype)

**Comment by sr320** [comment]
@kubu4 can you get me a simple table with two columns with column 2 being the start and stop position of every gene in scaffold 1 of geoduck genome. and column 1, just '1'?

trying to mimic

```
GRanges object with 4 ranges and 0 metadata columns:
      seqnames           ranges strand
         <Rle>        <IRanges>  <Rle>
  [1]        1        1-5000000      *
  [2]        1 7000000-90000000      *
  [3]        5     1000-3200000      *
  [4]       17 4000000-80000000      *
```

**Comment by kubu4** [comment]
Uploaded file (tab-delimited, no header) to Slack:

https://genefish.slack.com/archives/GG4HW5SC9/p1572445991000800

**Comment by sr320** [comment]
I can plot  the genes 

![Screen Shot on 2019-10-30 at 08-11-29](https://user-images.githubusercontent.com/4442039/67871095-0fc0d680-faed-11e9-9842-38a4dad07d6c.png)

now just need to figure out how to bin to a density plot... as no value at scaffold resolution

**Comment by sr320** [comment]
closer https://d.pr/i/gfDVXj

**Comment by shellytrigg** [comment]
DMRs:
- [All ambient DMRs](https://github.com/shellytrigg/Shelly_Pgenerosa/blob/master/analyses/DMRs_heatmap/amb_AllTimes_DMR250bp_MCmax30_cov5x_rms_results_collapsed_AOV0.1.DMR.bed)
- [Day 10 DMRs](https://github.com/shellytrigg/Shelly_Pgenerosa/blob/master/analyses/DMRs_heatmap/day10_AllpH_DMR250bp_MCmax30_cov5x_rms_results_collapsed_AOV0.1.DMR.bed)
- [Day 135 DMRs](https://github.com/shellytrigg/Shelly_Pgenerosa/blob/master/analyses/DMRs_heatmap/day135_AllpH_DMR250bp_MCmax30_cov5x_rms_results_collapsed_AOV0.1.DMR.bed)
- [Day 145 DMRs](https://github.com/shellytrigg/Shelly_Pgenerosa/blob/master/analyses/DMRs_heatmap/day145_AllpH_DMR250bp_MCmax30_cov5x_rms_results_collapsed_AOV0.1.DMR.bed)
