### ISSUE TITLE
Generate Circos figure for Geoduck Genome

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#772]

**Comment by kubu4** [comment]
Baby steps...

![20191107_001](https://user-images.githubusercontent.com/4514104/68413477-2f867900-0143-11ea-8bb2-bc9fd447561a.png)

**Comment by kubu4** [comment]
It's getting more interesting...

![20191107_002](https://user-images.githubusercontent.com/4514104/68419197-9eb59a80-014e-11ea-85c6-1eee363734a7.png)

**Comment by kubu4** [comment]
Starting to get the hand of this.

#### Scaffold 1

- Blue = Individual genes
- Grey = gene density (genes per 1Mbp)
- Green = methylation density (75% methylation per 1Mbp)

--- 
![image](https://user-images.githubusercontent.com/4514104/68807586-ef306a80-061c-11ea-8d37-c5a8063dcbe9.png)
