### ISSUE TITLE
Data Science Incubator Program

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#773]
Should we apply?
https://escience.washington.edu/get-involved/incubator-programs/overview/

**Comment by shellytrigg** [comment]
Propose meta analysis to see if genome regions are commonly affected across different species in response to environmental change?

**Comment by shellytrigg** [comment]
Expected challenges: normalizing across different datasets, reference genomes with varying quality, etc

**Comment by sr320** [comment]
Similar - Aggregate all methylation/epiegenetic data across all marine invertebrates to gain insight into function..

**Comment by shellytrigg** [comment]
@sr320 application is due today. I'm wondering how many and which datasets we should propose integrating? Maybe this should be a more focused meta-analysis for this time around e.g. propose only looking at adult samples (maybe still include different tissues). What do you think?

**Comment by sr320** [comment]
Is there a google doc or something we can work on ?

thanks
Steven


Steven B. Roberts, Associate Professor
Associate Director - Graduate Program Coordinator
School of Aquatic and Fishery Sciences
University of Washington
Fisheries Teaching and Research (FTR) Building - Office 232
1140 NE Boat Street - Seattle, WA 98105
robertslab.info - sr320@uw.edu - @sr320
vm:206.866.5141 - cell:360.362.3626

**Comment by shellytrigg** [comment]
I just started one [here](https://docs.google.com/document/d/1wv7xjnztmDK6EZWjY1PcFsbwNNNcjCCiKDRSPGcWxoo/edit?usp=sharing) that's copied from the NRSP proposal

**Comment by shellytrigg** [comment]
For the data description: We have [DNA bisulfite sequencing data from four different bivalve species in fastq file format totaling 320GB](https://docs.google.com/spreadsheets/d/1jU2Bwp4YfKdvhOuljEU22jRnA8g7_ifTYoskGeNrrvE/edit?usp=sharing). The data currently reside on lab servers and there are no privacy or access restrictions.

And move the part about the 200 genome feature tracks to the 1 page proposal, talking about how we can use those to compare to and/or verify the new findings

**Comment by shellytrigg** [comment]
[submitted](https://docs.google.com/document/d/1wv7xjnztmDK6EZWjY1PcFsbwNNNcjCCiKDRSPGcWxoo/edit)

**Comment by shellytrigg** [comment]
Our project didn't get picked for the 2020 Winter Incubator :( . BUT we can still get help on this project from the data scientists in eScience during their office hours

[eScience Winter Incubator.pdf](https://github.com/RobertsLab/resources/files/3942266/eScience.Winter.Incubator.pdf)
