### ISSUE TITLE
Adding SAFS calendar to Google Calendar

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#774]
How do you take 
https://fish.uw.edu/news-events/events/  (see subscribe link)

and bring into Gcal?

**Comment by grace-ac** [comment]
Go to google calendar     
1. in other calendar section, select the "+"
2. A menu should pop up, select the "From URL" option
3. Paste the iCalendar subscribe link from https://fish.uw.edu/news-events/events/
4. Click "create calendar"
