### ISSUE TITLE
Crab RNA extractions- should I move on to other trtmnt groups? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#775]
Here's a summary of what I have (Day 9 (Pre-temperature treatment)):      

| Infection status | Total ng RNA in all | Number of sample tubes with RNA |
|------------------|---------------------|---------------------------------|
| Infected         | 5532.67             | 21 out of 24                    |
| Uninfected       | 4678.96             | 22 out of 24                    |

Sam's resent submission says that NWGC likes to have 60 ng/ul... it mentions 1000ng, but apparently NWGC can work with less ng, but don't specify a minimum. ([Sam's post](https://robertslab.github.io/sams-notebook/2019/05/21/Sample-Submission-Tanner-Crab-Infected-vs-Uninfected-RNAseq.html))

---
### Questions: 
1. Should I extract more from Day 9? (I have about 15 uninfected and 25 infected hemolymph samples left. Also most of the samples I have extracted recently have some hemolymph left over since I only used 35ul)
2. If no to 1, should I move on to other treatment groups? Temperature?

**Comment by sr320** [comment]
Yes move on.. to other days
