### ISSUE TITLE
Remove lines with specific text if a CGI ID is represented

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#778]
I have [this file](https://github.com/RobertsLab/project-gigas-oa-meth/blob/master/analyses/2019-09-15-DML-Analysis/Blastquery-GOslim-BP.sorted.unique) with GOSlim terms assigned to *C. gigas* CGI IDs (individual genes). Some genes are associated with multiple biological process GOslim terms. Of these genes, there are some that are associated with a defined process and "other biological processes"

![Screen Shot 2019-10-29 at 1 12 58 PM](https://user-images.githubusercontent.com/22335838/67805264-e56c0c00-fa4d-11e9-97ce-0cd9e6aa302f.png)

For these genes, I want to remove the "other biological processes" entry. Is there an efficient way to do this? Here are the potential steps I can think of:

1. Scan the file to see if there are duplicate CGI IDs
2. For each duplicated ID, look at the text in the second column (GOslim term)
3. If the second column text matches "other biological processes," remove the line

**Comment by kubu4** [comment]
To clarify, you want to remove lines with "other biological processes" _only when it is part of a duplicated CGI ID_?

Or, do you just want to get rid of all lines containing "other biological processes"?

**Comment by yaaminiv** [comment]
> To clarify, you want to remove lines with "other biological processes" only when it is part of a duplicated CGI ID?

Yes, I want to remove lines with "other biological processes" only when it is part of a duplicated CGI ID

**Comment by sr320** [comment]
you should just remove all "other biological  processes"

**Comment by kubu4** [comment]
If you're following @sr320's suggestion:

`grep --invert-match "other biological processes" Blastquery-GOslim-BP.sorted.unique`
