### ISSUE TITLE
Order qPCR primers to ID crassostrea species

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#786]
Kumamoto = sikamea..

Based on https://www.researchgate.net/profile/Ximing_Guo/publication/259643859_Identification_of_Crassostrea_ariakensis_and_related_oysters_by_multiplex_species-specific_PCR/links/55c79eb708aeb9756746e35e/Identification-of-Crassostrea-ariakensis-and-related-oysters-by-multiplex-species-specific-PCR.pdf

It would appear the COI primers would work ...

**Comment by kubu4** [comment]
Done.

**Comment by kubu4** [comment]
I previously ordered the wrong primers. This explains the results I was getting.

I've ordered the replacement primers.

:disappointed:
