### ISSUE TITLE
approach to look @ differential expression - crab transcriptomes 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#790]
Want to have some new results to share for GSS talk (next Thursday) 

Want to compare just infected and uninfected transcriptomes (combine sample days)

**Comment by sr320** [comment]
Try using kallisto ... see https://github.com/sr320/course-fish546-2018/blob/master/jupyter-nbs/005-RNA-seq.ipynb

https://pachterlab.github.io/kallisto/about

**Comment by grace-ac** [comment]
what's a good computer for me to run kallisto on?           
should I try to create a .sh to run it on Mox instead?

**Comment by sr320** [comment]
any local bird or genefish is probably easier as I do not think pseudo alignment is very intensive.

**Comment by grace-ac** [comment]
jupyter notebook: [2019-11-06-bairdi-kallisto.ipynb](https://github.com/RobertsLab/project-crab/blob/master/notebooks/2019-11-06-bairdi-kallisto.ipynb)

results from `quant` in [analyses](https://github.com/RobertsLab/project-crab/tree/master/analyses)

Each sample has 2 directories because the lanes were separate files. 

working to figure out what comes next ([kallisto-sleuth-workshop-2016/](https://pachterlab.github.io/kallisto-sleuth-workshop-2016/))

**Comment by grace-ac** [comment]
So... since I have abundance.tsv files for all 4 samples (8 total because 2 lanes per sample), I don't need to run the [trinity .pl script](https://github.com/sr320/course-fish546-2018/blob/master/jupyter-nbs/006-Trinity.ipynb)... ?

I just have to figure out how to get a table of counts for all samples, and use that in RStudio with [DESeq2](https://github.com/sr320/course-fish546-2018/blob/master/jupyter-nbs/008-DESeq2.ipynb)?

**Comment by sr320** [comment]
I am pretty close...
following https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html


http://htmlpreview.github.io/?https://github.com/sr320/nb-2019/blob/master/C_bairdi/11-Deseq2.html

I got all the way to graphs and DEGs... 
Problem is I loss column 1 early on which  is the gene names, thus at the end I cant determine which genes that are DE!

**Comment by grace-ac** [comment]
Cool!! 

To get a table of merged abundances, I can just do that in R? 
And ideally, the gene names would be part of that table? 

I see yours in your Rmd, and it looks like it's the 8 samples (4 libraries), what are the rows?

**Comment by sr320** [comment]
You could but I already did  that and it is @
https://github.com/sr320/nb-2019/blob/master/C_bairdi/analyses/Abundance-merge.txt

**Comment by sr320** [comment]
Or if you are more comfortable with edgeR that same table will likely work.

**Comment by sr320** [comment]
Got it.... here is the list of DEGs
https://raw.githubusercontent.com/sr320/nb-2019/master/C_bairdi/analyses/Crab_DEGlist.txt

and corrected code...
http://htmlpreview.github.io/?https://github.com/sr320/nb-2019/blob/master/C_bairdi/11-Deseq2.html

**Comment by grace-ac** [comment]
Cool! I'll try out both. thanks

**Comment by sr320** [comment]
Here is a join of DEGS, with count data and blastout....
http://htmlpreview.github.io/?https://github.com/sr320/nb-2019/blob/master/C_bairdi/13-DEG-join.html

table 
https://raw.githubusercontent.com/sr320/nb-2019/master/C_bairdi/analyses/bigtable.txt

might be best to start with this to work up, and if there is time you could always go back and recreate....

would want to describe what genes are differentially expressed.

**Comment by grace-ac** [comment]
Ok. Here's what I'm thinking to describe genes that are DE:   
- sort out the DEGs for both infected and uninfected from the bigtable.txt you made
- get the GO terms for those two lists in jupyter
- get enriched GO terms in DAVID

visualizations for enriched GO terms for each list (infected and uninfected) 

I'll also look back through EIMD scripts with EdgeR to see if I can make heatmaps. 

Don't want to waste time - am I on a good track with this?

**Comment by sr320** [comment]
Good plan!

**Comment by grace-ac** [comment]
list of DEGs ONLY in infected samples (2383): 
- [analyses/1111-infected-d12-d26.csv](https://github.com/RobertsLab/project-crab/blob/master/analyses/1111-infected-d12-d26.csv)

list of DEGs ONLY in uninfected samples (27):   
- [analyses/1111-uninfected-d12-d26.csv](https://github.com/RobertsLab/project-crab/blob/master/analyses/1111-uninfected-d12-d26.csv)

enriched GO terms (using a Uniprot Accession IDs from a blast with first transcriptome and uniprot sp) only in infected group (74 enriched) :     
- [analyses/enriched-GO-infected-d12-d26.txt](https://github.com/RobertsLab/project-crab/blob/master/analyses/enriched-GO-infected-d12-d26.txt)
