### ISSUE TITLE
bioanalyzer results - better than first round? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#792]
## @kubu4 do these seem better than the first round? 
**Should I continue with the rest of my samples?**

I think they look a little better.... ?

#### gel

![bairdi-firstround-gel](https://user-images.githubusercontent.com/14934314/68348495-d967f600-00ae-11ea-9dad-be76bb25e3df.PNG)

#### electropherogram

![bairdi-firstround-electro](https://user-images.githubusercontent.com/14934314/68348508-e4228b00-00ae-11ea-836a-36fa41a51a59.PNG)

#### gel

![bairdi-gel](https://user-images.githubusercontent.com/14934314/68348430-b2112900-00ae-11ea-8d13-fce9e73d764e.PNG)

#### electropherogram 

![bairdi-electropherogram](https://user-images.githubusercontent.com/14934314/68348451-b8070a00-00ae-11ea-8fe4-82aa1401dbd6.PNG)

**Comment by kubu4** [comment]
Samples don't look good and seem to be interfering with the marker. Check samples on NanoDrop.

**Comment by grace-ac** [comment]
| Sample ID | User ID | Date      | Time    | ng/ul | A260  | A280  | 260/280 | 260/230 | Constant | Cursor Pos. | Cursor abs. | 340 raw |
|-----------|---------|-----------|---------|-------|-------|-------|---------|---------|----------|-------------|-------------|---------|
| 10        | Default | 11/6/2019 | 4:47 PM | 40.03 | 1.001 | 0.486 | 2.06    | 0.32    | 40.00    | 230         | 3.117       | 0.038   |
| 169       | Default | 11/6/2019 | 4:48 PM | 51.50 | 1.288 | 0.599 | 2.15    | 1.92    | 40.00    | 230         | 0.671       | 0.020   |
| 29        | Default | 11/6/2019 | 4:49 PM | 49.92 | 1.248 | 0.630 | 1.98    | 1.33    | 40.00    | 230         | 0.937       | 0.128   |
| 119       | Default | 11/6/2019 | 4:50 PM | 33.50 | 0.838 | 0.486 | 1.72    | 0.22    | 40.00    | 230         | 3.826       | 5.695   |
| 119       | Default | 11/6/2019 | 4:52 PM | 7.22  | 0.180 | 0.076 | 2.38    | 0.06    | 40.00    | 230         | 3.049       | -1.480  |
| 177       | Default | 11/6/2019 | 4:53 PM | 24.73 | 0.618 | 0.293 | 2.11    | 1.08    | 40.00    | 230         | 0.575       | 0.196   |
| 24        | Default | 11/6/2019 | 4:54 PM | 26.51 | 0.663 | 0.319 | 2.08    | 1.13    | 40.00    | 230         | 0.588       | 0.025   |
| 111       | Default | 11/6/2019 | 4:55 PM | 23.54 | 0.589 | 0.296 | 1.99    | 0.22    | 40.00    | 230         | 2.637       | 0.138   |
| 124       | Default | 11/6/2019 | 4:57 PM | 15.28 | 0.382 | 0.170 | 2.24    | 0.57    | 40.00    | 230         | 0.675       | 0.016   |
| 53        | Default | 11/6/2019 | 4:59 PM | 20.58 | 0.514 | 0.272 | 1.89    | 0.10    | 40.00    | 230         | 5.414       | 0.015   |
| 91        | Default | 11/6/2019 | 5:00 PM | 15.70 | 0.392 | 0.201 | 1.96    | 0.19    | 40.00    | 230         | 2.022       | 0.621   |
| 81        | Default | 11/6/2019 | 5:01 PM | 24.68 | 0.617 | 0.305 | 2.02    | 0.22    | 40.00    | 230         | 2.814       | 0.021   |

**Comment by grace-ac** [comment]
I ran 119 twice because it gave this error (also gave same error after I tried again):    
![nano-119](https://user-images.githubusercontent.com/14934314/68351259-bf7ee100-00b7-11ea-9b7d-5a6b1e1ec131.PNG)

**Comment by grace-ac** [comment]
I took screenshots of all graphs

**Comment by kubu4** [comment]
NanoDrop results look perfect (260/280 at ~2.0 for all samples; 260/230 < 2.0 for all samples).

Two suggestions:

1. Run a chip and use the kit's elution buffer as your "sample". This will see if elution buffer is causing issues with Bioanalyzer (i.e. causing marker to fail).

2. Run some of the RNA samples I used for most recent round of RNAseq and see how they compare. Choose some from successful libraries and some from unsuccessful libraries.

**Comment by grace-ac** [comment]
New plan:   
1. Run four samples from the above group on Qubit using DNA HS
2. Use Turbo DNA-free Kit on those samples
3. Run those samples on Bioanalyzer
4. Re-run those samples on Qubit using DNA HS

**Comment by grace-ac** [comment]
1. Done --> [results](https://docs.google.com/spreadsheets/d/1s24I4mCZ-cc3doEP8mFzSorhmhTRUeOeNhJORagqbpM/edit#gid=0)
2. Done (Did the [routine DNase treatment](https://assets.thermofisher.com/TFS-Assets/LSG/manuals/1907M_turbodnafree_UG.pdf)) 
3. Done (screenshots below) ran each of the 4 samples twice (##-a and ##-b)
4. Done - samples were eluted in ~40-45ul         
(ran dsDNA HS [results](https://docs.google.com/spreadsheets/d/1vo88dZhff06Afgz6ejCYwsYLlOaEO8Z22ui-sg3P58k/edit?usp=sharing); ran RNA HS [results](https://docs.google.com/spreadsheets/d/1jf5JNffUMiI5d7fDz39C7j0v5QXkXBYbwhg7SWC71sY/edit?usp=sharing))

![bioanalyzer-4samples](https://user-images.githubusercontent.com/14934314/68517695-735da900-023d-11ea-9713-48919ae3360f.PNG)

![bioanalyzer-gel-4samples](https://user-images.githubusercontent.com/14934314/68517711-82445b80-023d-11ea-99e9-0dc4d9df13ce.PNG)

**Comment by sr320** [comment]
will go fwd with seq
