### ISSUE TITLE
missing 1st column after joining two files based on 1st column? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#793]
Jupyter notebook: [1111-blastx-uniprot-file-merging-for-EdgeR.ipynb](https://github.com/RobertsLab/project-crab/blob/master/notebooks/1111-blastx-uniprot-file-merging-for-EdgeR.ipynb)

Problem occurs in Step 3a, when I try to `join` :       
```
!join -1 1 -2 1 -t $'\t' \
infected-blast-sort.tab \
uniprot-SP-GO-sorted.tab \
> infected-blast-annot.tab
```

Output looks like this:    
```
	E3 ubiquitin-protein ligase rnf213-alpha (EC 2.3.2.27) (EC 3.6.4.-) (Mysterin-A) (Mysterin-alpha) (RING finger protein 213-A) (RING finger protein 213-alpha) (RING-type E3 ubiquitin transferase rnf213-alpha)	blood circulation [GO:0008015]; sprouting angiogenesis [GO:0002040]; ubiquitin-dependent protein catabolic process [GO:0006511]	cytosol [GO:0005829]	ATPase activity [GO:0016887]; metal ion binding [GO:0046872]; ubiquitin-protein transferase activity [GO:0004842]	GO:0002040; GO:0004842; GO:0005829; GO:0006511; GO:0008015; GO:0016887; GO:0046872	reviewed	Danio rerio (Zebrafish) (Brachydanio rerio)
	Cilia- and flagella-associated protein 20 (Bug22p)	cilium assembly [GO:0060271]; positive regulation of cell 
```

**MIssing the Uniprot Acession IDs, which are in Column 1 of both files and what I joined the two files with...**

**Comment by sr320** [comment]
can you post urls for both tables?

**Comment by grace-ac** [comment]
tables are too big to be on GitHub, so here's some short version of the tables:    

http://owl.fish.washington.edu/scaphapoda/grace/infected-blast-sort-short.tab      

http://owl.fish.washington.edu/scaphapoda/grace/uniprot-SP-GO-sorted-short.tab

**Comment by sr320** [comment]
Big picture - what are you trying to do?

**Comment by grace-ac** [comment]
trying to join these two tables based on the first column (uniprot accession IDs). when I do that, the column I'm joining (Uniprot Accession IDs) disappears. 

Needed for downstream work in that notebook - final product will be files that I can use in `edgeR`

**Comment by sr320** [comment]
was thinking bigger....
But why do you need edgeR, Deseq was already run?

so you want GO info for DEGs... 
how about https://raw.githubusercontent.com/sr320/nb-2019/master/C_bairdi/analyses/deg.annot.txt

derived via https://github.com/sr320/nb-2019/blob/master/C_bairdi/14-DEG-annotation.Rmd
