### ISSUE TITLE
Getting URL from OSF to pull directly into IGV

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#797]
Is there a way to do this?

**Comment by kubu4** [comment]
Yes, but it's tedious. Following instructions are when using the Chrome browser.

1. Go to file on OSF.

2. Download the file using OSF "Download" button.

3. In Chrome, enter the following URL: `chrome://downloads/`
  - This shows your download history

4. Then, copy the full URL that's listed in the panel for the file you just downloaded.

NOTE: Looks like URLs to files on OSF are named by their checksum value. This results in a file with the checksum as the file name; it's not pretty.

**Comment by sr320** [comment]
thanks

This is cool, but does not seem to work as url does not end in IGV compatible extensions (eg .fa, .gff)

**Comment by kubu4** [comment]
Ugh.

**Comment by kubu4** [comment]
An email exchange with OSF didn't really yield anything. Doesn't seem like it's feasible, since the files stored on OSF are referenced via a unique ID - not their actual filename.
