### ISSUE TITLE
Add Hauser lab folks to mox

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#799]
Dear Steven,

I followed the directions on your Hyak wiki regarding adding a user, and I could not find the Hyak Server and Lolo Server under the "Computing Services" link  on https://uwnetid.washington.edu/manage/

I then navigated to the UW-IT Groups Service, found the u_hyak_srlab membership page, but did not have access to an "Add members" text field.

I suspect that perhaps you or your Hyak administrator have to first add us to the UW-IT Groups Service before we can subscribe to the service using  https://uwnetid.washington.edu/manage/

Our UW Net IDs are:

elpetrou
nclowell
ctarpey

Thank you for adding us to your group!

**Comment by kubu4** [comment]
They've now been added. They can try subscribing again.

**Comment by EleniLPetrou** [comment]
Thank you, it worked now!
