### ISSUE TITLE
I need help extracting DNA/RNA for the first time w/ oly larvae. -Lindsay Alma

### ISSUE THREAD

**Issue by lalma** [RobertsLab/resources#802]
Hi Roberts Lab,
My advisor would like me to do a small molecular project with some of my olympia oyster larvae and adults. I am new to the molecular world, and I would love some guidance with extracting DNA for the first time. Laura, you mentioned I could use some of your old oly larvae to practice. My schedule is pretty open within the next few weeks.  If anyone has some time to help with this, I would be very grateful. 
-Lindsay Alma

**Comment by kubu4** [comment]
@lalma Here's the approach that we use:

1. Grind samples under liquid nitrogen (LN2).

2. Extract DNA using [E.Z.N.A. Mollusc DNA Kit ](https://www.omegabiotek.com/product/e-z-n-a-mollusc-dna-kit/), according to manufacturer's protocol.

There really isn't much more to it than that. If want help learning how to use LN2 for grinding samples, just let us know. I'm generally available most days (other than Mondays) and would be happy to show you.

P.S. Do you have access to an LN2 dewar?

**Comment by lalma** [comment]
Hi Sam,
Thanks for the protocol! I would love to arrange some time to get some help grinding samples. Are you available sometime next week Wed, Thu, or Fri?
We have a dewar. Is there a place on campus where I can fill it with liquid nigrogen?

**Comment by kubu4** [comment]
> Wed, Thu, or Fri

Yes, any of those days would be fine. You can pick the time (Note: I have to split at ~3:45PM each day).

> Is there a place on campus where I can fill it with liquid nigrogen?

Chemistry stores (Bagley Hall; can't remember actual lab number off-hand).

**Comment by lalma** [comment]
Can we plan for Friday 12/13 at 11:00? 
I will get some LN2 before then. 
Is there anything else I should bring or prep for? I will ask Laura where her practice samples are.

**Comment by kubu4** [comment]
> Can we plan for Friday 12/13 at 11:00?

Sounds good. I've added you to our lab calendar.

No need to bring anything else (besides the LN2); we have mortar, pestles, spatulas. We'll just run through a couple of samples.

**Comment by laurahspencer** [comment]
@lalma based on the amount of larvae you have, you might find it difficult to grind with mortar/pestle without losing a lot of your sample. Maybe it's possible to use a tissue disrupter and/or mini plastic pestle that fits inside a tube?  I do have plenty of larvae for you to experiment with, so perhaps you could try both methods with the appr. amount of larvae you have.

**Comment by lalma** [comment]
@laurahspencer Thanks for the tip! Are those something I need to buy? If so, can you send me a link where I can buy them or can I buy them from the chem store? Can you let me know where to find the practice larvae?
@kubu4 how much liquid nitrogen should I buy? I believe our dewar can hold up to 5 gallons, but I'm sure we dont need that much.

**Comment by kubu4** [comment]
I figure we'll just process a couple of samples so you can see the process, so I'd say 3 liters at the most; should be more than enough.
