### ISSUE TITLE
Number of lanes used for C. virginica gonad MBD Seq

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#803]
I'm being asked to include how *C. virginica* gonad samples were divided into sequencing lanes for MBD-Seq, but I can't find that information anywhere. @kubu4 Do you know how many lanes were used/which samples were run on each lane, or where I can find this information? I already checked the `nightingales` folder readme.

**Comment by kubu4** [comment]
I'll need an example file from your set of FastQ files. Which set are you referring to:

- 1_25_S25_L001_R1_001.fastq.gz

OR

- zr2096_1_s1_R1.fastq.gz

If the first one, then the "L001" section of the filename indicates which lane that sample was run on. If all the samples in the set have the same "L001" notation, then they were all run on the same lane.

If it's the second one, then I'll have to track down paper work for that sequencing and see if they provided that info.

**Comment by yaaminiv** [comment]
It's the second one (zr2096_1_s1_R1.fastq.gz). Thanks!

**Comment by kubu4** [comment]
Email's been sent to Zymo to see if they have this info.

**Comment by kubu4** [comment]
However, I should add that the 10 samples were pooled together and sequenced together (i.e. on the same lane(s)). Is this the info you need?

I don't know the answer to "number of lanes used" and have emailed Zymo.

**Comment by yaaminiv** [comment]
> However, I should add that the 10 samples were pooled together and sequenced together (i.e. on the same lane(s)). Is this the info you need?

Yeah that should work! It's for the metadata submission for the overall *C. virginica* project, so I'll check with Katie. Either way this is probably information I should have in the paper...

**Comment by kubu4** [comment]
I heard back from Zymo and it seems I misinterpreted their wording in the paper work they sent at the end of the project.

Samples were sequenced on two different lanes. I'm awaiting word on which samples were sequenced together in each of the two lanes that were used.

Sorry about that!

**Comment by yaaminiv** [comment]
> Samples were sequenced on two different lanes. I'm awaiting word on which samples were sequenced together in each of the two lanes that were used.

Got it. Thanks for the update!

**Comment by kubu4** [comment]
Response from Zymo:

> Samples MBD Cv106 (zr2096_9) and MBD Cv108 (zr2096_10) were sequenced together, and the rest of the samples were sequenced in a separate lane.
