### ISSUE TITLE
SAFS Fellowship 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#804]
So far I have found this: https://fish.uw.edu/wp-content/uploads/sites/4/2017/09/2019-20_SAFSGraduateStudentFundingInfo.pdf 

Trying to find info on how to apply

**Comment by sr320** [comment]
details should be in student guide https://github.com/sr320/uSAFS-guide/blob/master/graduate-students/Student-Guide-2015%E2%80%932016.pdf

**Comment by grace-ac** [comment]
Found it under "Scholarship Applications for Current Students" at https://fish.uw.edu/intranet/overview/student-resources/ 

---

### @sr320 : 
#### One copy of a confidential (sealed) letter of recommendation from your major professor (or the professor may email safs@u.washington.edu or give the letter directly to Student Services Office)
