### ISSUE TITLE
Nanopore to assess quality of cDNA libraries? 

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#805]
The QuantSeq library prep kit suggests using the RIN number to assess quality of libraries. From what I've learned from Sam, and from some test samples that I ran through the Bioanalyzer, oyster tissue doesn't typically allow for this since there is no 28S peak (just an 18S peak). So, the QuantSeq people advise sequencing a few preliminary samples to assess quality, before moving forward with the full prep/sending for sequencing. Is this something we could do in-house with the nanopore?

**Comment by kubu4** [comment]
It might be possible, but we don't have any experience with it yet, so can't say for sure.

Regardless, it's not a financially viable option, as each flow cell is ~$1000.

You can still determine if your RNA is good or not by looking at the Bioanalyer results. You're just looking for degradation (i.e. a smear below the rRNA band that should be present). If you have no rRNA band and/or a significant amount of smearing, then you're RNA is likely degraded. If you have a nice, solid rRNA band and little-to-no smearing, then you should be good to go.

**Comment by sr320** [comment]
what does @ksil91 suggest, or what did she do?

(note using one flow cell to confirm all libraries are good would be fine)

**Comment by ksil91** [comment]
Agree with Sam, you can easily see degraded vs. good quality RNA on the Bioanalyzer RNA trace and I found the RIN to match up with what the trace looked like. To confirm, you use the RNA Bioanalyzer chips on extracted RNA and High Sensitivity DNA chips to check the quality of the finished QuantSeq library. Page 28-29 of your QuantSeq manual discussions how to use HS chips to evaluate libraries.

**Comment by kubu4** [comment]
> (note using one flow cell to confirm all libraries are good would be fine)

If this is on the table, I'd think it would be better to spend the money by actually sequencing a few "test" libraries with, as suggested by the QuantSeq people, to get a definitive answer on whether or not the libraries are viable.

**Comment by kubu4** [comment]
> using the RIN number to assess quality of libraries

Now that I've re-read your issue, I'm not sure exactly what you're referring to here. A RIN number evaluates RNA quality, but you're talking about libraries (completed)? As @ksil91 mentioned, the manual has instructions on how to use the Bionalzyer to evaluate libraries (you will not get a RIN for these, as you're not running libraries on an RNA chip).

**Comment by laurahspencer** [comment]
Okay, this clears things up. I ran a few RNA samples on the bioanalyzer, the results looked pretty good. I'm now interested in checking quality of my libraries prior to sequencing - I had misunderstood the QuantSeq rep, and I see now the library QC instructions in the manual. Thanks all!
