### ISSUE TITLE
Create robust archive of lab notebooks

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#806]
Getting doi's and have all accessible in a single location.

**Comment by sr320** [comment]
For Github notebooks it should be as easy 
https://d.pr/i/krdl6o
though I also need to capture jupyter notebooks

**Comment by sr320** [comment]
Please capture snapshots @ 
https://github.com/RobertsLab/resources/wiki/Lab-Notebooks#archive

**Comment by yaaminiv** [comment]
done: https://github.com/yaaminiv/yaaminiv.github.io/archive/v2019.zip

**Comment by kubu4** [comment]
I also have all current lab members' GitHub notebooks cloned on `gannet/web/github_notebooks`. Gannet runs `gut pull` on each of them everyday, so the backups are always current.

**Comment by kubu4** [comment]
How frequently should we create GitHub releases of our notebooks?

**Comment by kubu4** [comment]
Have added:

- Sam GitHub archive link

- Sam Jupyter notebook, R project archive link (really, it's the Roberts Lab `code` repo)

- Jake Blogspot `.zip` link

- Steven ONS `.zip` link

**Comment by laurahspencer** [comment]
Added my 2019 snapshot as well - [https://github.com/laurahspencer/LabNotebook/releases/tag/v2019](https://github.com/laurahspencer/LabNotebook/releases/tag/v2019)
