### ISSUE TITLE
Generate new crab transcriptome - combine all 5 libraries

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#808]
(@sr320 told me to do this) 

@kubu4 : please generate new crab transcriptome combining all 5 libraries to have going through the holidays

gannet link to 4 new libraries data:          https://gannet.fish.washington.edu/Atumefaciens/20191024_cbai_fastqc_multiqc/ 

gannet link to original library data:              
https://gannet.fish.washington.edu/Atumefaciens/20181015_Cbairdi_fastqc/

**Comment by kubu4** [comment]
@grace-ac - Can you please send me the metadata associated with each of the sequencing files (e.g. Day9-cold fastq01_R1.gz)?

**Comment by grace-ac** [comment]
Is this what you are asking for?

The [first library](https://gannet.fish.washington.edu/Atumefaciens/20181015_Cbairdi_fastqc/) is a pool of Day 26, cold and ambient, infected and uninfected. 

Breakdown  of the [4 new libraries](https://gannet.fish.washington.edu/Atumefaciens/20191024_cbai_fastqc_multiqc/):       
329774 --> D12_infected         
329775 --> D12_uninfected          
329776 --> D26_infected          
329777 --> D26_uninfected

**Comment by kubu4** [comment]
Thanks!

**Comment by kubu4** [comment]
Notebook entry will be up later today with more details, but, for now, here're the files.

Transcriptome FastA:

https://gannet.fish.washington.edu/Atumefaciens/20191218_cbai_trinity_RNAseq/trinity_out_dir/20191218.C_bairdi.Trinity.fasta

FastA index:

https://gannet.fish.washington.edu/Atumefaciens/20191218_cbai_trinity_RNAseq/trinity_out_dir/20191218.C_bairdi.Trinity.fasta.fai
