### ISSUE TITLE
Setup older Windows Box - Skyline

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#81]

**Comment by kubu4** [comment]
I've added Skyline to the computer in 238.

However, wasn't there some sort of custom patch that had to be applied to Skyline in order to get proper handling of certain file types or something? If yes, does someone know where this patch file is? @yaaminiv @laurahspencer

**Comment by sr320** [comment]
@grace-ac 
Can you kick tire on the new computer to see if it is functional with regard to skyline?

**Comment by laurahspencer** [comment]
@kubu4 I'm unaware of a custom patch, _however_ I highly advise that we all use [Skyline-daily](https://skyline.ms/project/home/software/Skyline/daily/register-form/begin.view?), which is a regularly updated albeit in-development version of Skyline.  I've noticed that all Skyline project files I've encountered can be opened with Skyline-daily, but not in the more static Skyline.

**Comment by grace-ac** [comment]
This computer has Skyline, which will not work with the SRM protocols that Laura and Yaamini are developing. 

Skyline Daily requires a sign in in order to download. I can create one for myself, or if someone already has one, we can use that.

**Comment by kubu4** [comment]
OK, maybe the custom patch was for MS convert and not Skyline. Couldn't remember.

In regards to Skyline Daily, I think this is a major problem in regards to reproducibility (assuming Skyline Daily is updated automatically)...

But, this is weird, the current stable release of Skyline is listed as version  3.7.0.11317; is this a higher version than the daily build that we currently have installed?

**Comment by kubu4** [comment]
Current daily build available is 3.7.1.11357. What version do we have on the Windows computer in FTR 209?

**Comment by laurahspencer** [comment]
current daily version:
![image](https://user-images.githubusercontent.com/17264765/31408187-907280c4-adbc-11e7-866f-24379ebb2467.png)

current skyline version:
![image](https://user-images.githubusercontent.com/17264765/31408220-9c038028-adbc-11e7-8d98-be2e1a91b74d.png)

**Comment by kubu4** [comment]
What version of the daily build do we have on the computer in FTR 209?

**Comment by grace-ac** [comment]
Skyline Daily is now on the computer as well

**Comment by sr320** [comment]
@kubu4 I believe @laurahspencer indicated that https://github.com/RobertsLab/resources/issues/81#issuecomment-335593300
`3.7.1.11357`
My understanding is that it updates when you restart...

**Comment by yaaminiv** [comment]
@kubu4 @sr320 When you open Skyline daily and there's an update available, it will prompt you to install the update and restart the program.

**Comment by sr320** [comment]
@kubu4 I agree with reproducibility issue in developer version, however I was told it is impossible to run @laurahspencer and @yaaminiv analysis in regular skyline, only skyline-daily.

My presumption is skyline will be update eventually, and then it could be used...

**Comment by sr320** [comment]
Closing as we resolved the issue of getting Skyline-daily on an additional Windows box. 
We can certainly open new issues
