### ISSUE TITLE
Identify useful / highly used equipment in MAR

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#810]
What equipment in the Seeb lab is / could be used by our group?

**Comment by kubu4** [comment]
Discussed in person, but I'll formally enter stuff in this issue. Here are the three primary items we'd have interest in:

- sonicator (for DNA shearing)

- Bioanalyzer

- plate reader

Wouldn't mind having:

- pipettes

- -80C

- -20C

- microfuge(s)

- centrifuge(s)

- water purification system (NanoPure)
