### ISSUE TITLE
Approach for "stranded" intron BED files?

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#811]
I created an intron BED file for the `Olurida_v081` genome. Upon inspection, I discovered that the genome has overlapping genes on opposite strands. Since creating the intron BED file is solely based on gene/exon coordinates, it loses strandedness and ends up with an intron track that, essentially, represents a "summary" of a region where two genes overlap (see the right side of the screencap below):

![20191217_002](https://user-images.githubusercontent.com/4514104/71019860-f9c4a080-20af-11ea-98fc-873ac3523c11.png)

---

Since strand info is present in the gene and exon GFFs, I'm guessing it would have to go something like this:

1. Split gene GFF into `gene_strand1.gff` and `gene_strand2.gff`

2. Split exon GFF into `exon_strand1.gff` and `exon_strand2.gff`

3. Run the various BEDTOOLS `complementBed` and `intersectBed` programs on those files separately and end up with two intron bed files: `intron_strand1.bed` and `intron_strand2.bed`

What approach(es) would you take to make sure I end up with gene-specific intron tracks?

**Comment by sr320** [comment]
I would say we do not need a stranded intron feature track.

**Comment by kubu4** [comment]
Sure, it may not be _needed_ per se, but is there a point in having an intron track at all, if introns can't be specifically associated with a given gene?

**Comment by sr320** [comment]
Yes, it makes some of the analysis simpler.
