### ISSUE TITLE
Confirm duck trimmed BS files

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#812]
Are we able to confirm that the files in 
`/gscratch/srlab/strigg/data/Pgenr/FASTQS`

are in fact the direct result of what is described in the manuscript?

> Quality filter thresholds were set for trimming of sequences in Trim Galore (Krueger 2015), (a minimum quality of 20, with the paired end option)

maybe an md5 comparison of one file re-filtered?

**Comment by kubu4** [comment]
The last trimming I did was here: https://github.com/RobertsLab/resources/issues/408#issuecomment-534180697

This was in September. The dates on the files in `/gscratch/srlab/strigg/data/Pgenr/FASTQS` is Oct. 2018. 

That's about all I know. What made you point to that directory as a source for files?

**Comment by sr320** [comment]
Because that is what I used for everything in the paper.

Does the methods in the paper accurately reflect what you did?

**Comment by kubu4** [comment]
Trimming was done using TrimGalore! (v0.4.5) using the default settings, along with the following options: `--paired` and `--rrbs`.

**Comment by shellytrigg** [comment]
Files in /gscratch/srlab/strigg/data/Pgenr/FASTQS are from here: [http://owl.fish.washington.edu/Athaliana/20180516_geoduck_trimgalore_rrbs/](http://owl.fish.washington.edu/Athaliana/20180516_geoduck_trimgalore_rrbs/)

confirmed by this readme: [https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20181010/readme.txt](https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20181010/readme.txt)

and github issue here:  [https://github.com/RobertsLab/resources/issues/415](https://github.com/RobertsLab/resources/issues/415)

trim parameters are described is Sam's post here: [https://robertslab.github.io/sams-notebook/2018/05/16/trimgalorefastqcmultiqc-trimgalore-rrbs-geoduck-bs-seq-fastq-data-directional.html](https://robertslab.github.io/sams-notebook/2018/05/16/trimgalorefastqcmultiqc-trimgalore-rrbs-geoduck-bs-seq-fastq-data-directional.html)

**Comment by sr320** [comment]
just confirming...

```
[sr320@mox1 FASTQS]$ md5sum EPI-44_S41_L005_R1_001_val_1.fq.gz 
67ce2af15035316ba66b86965d6987e8  EPI-44_S41_L005_R1_001_val_1.fq.gz

sr320s-iMac:20180516_geoduck_trimgalore_rrbs sr320$ md5 EPI-44_S41_L005_R1_001_val_1.fq.gz 
MD5 (EPI-44_S41_L005_R1_001_val_1.fq.gz) = 67ce2af15035316ba66b86965d6987e8
```
