### ISSUE TITLE
Verify intron track generation is acceptable

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#814]
I want to verify I generated my *C. virginica* intron track in a way that it does **not** include UTRs.

*[Previous discussion on intron track generation](https://github.com/RobertsLab/resources/issues/692)*

I have the following sentence in my paper:

> The complement of non-coding sequences were then intersected to identify introns.

Which spurred discussion

Katie: just to clarify - when you applied this complement, would it have identified UTRs as an intron?
@kubu4 : For a given mRNA, you'd need to compare coding sequence (CDS) regions with gene regions. Any regions of the mRNA that don't overlap with a region of the CDSs (should only be on 5'/3' ends of mRNAs, in theory) would be the untranslated regions (UTRs).

So it looks like I took the complement of CDS (nonCDS), found the intersection with genes, and called those my introns: https://github.com/fish546-2018/yaamini-virginica/blob/master/notebooks/2019-05-13-Generating-Genome-Feature-Tracks.ipynb

I modeled this after Jon Puritz's code discussed during FROGER:

https://github.com/hputnam/FROGER/wiki/Genome-Sequence-Files-and-Feature-Tracks

I don't think the intron track contains UTRs, but can someone confirm by looking at my code that I generated the track correctly?

**Comment by sr320** [comment]
Ultimately you would want to check it in IGV.

Provide a igv session file with files on web servers (using urls).

**Comment by yaaminiv** [comment]
https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2019-05-13-Generating-Genome-Feature-Tracks/2019-05-13-Genome-Track-Verification.xml

**Comment by sr320** [comment]
Would probably want to delve into to figure out which are NCBI tracks - but based on names I would guess none?

Anyway - see https://d.pr/i/ehjRVd
This would be a case whereby Sam’s explanation does not hold true? you have a UTR marked as exon.

Why not use NCBI tracks? I am pretty sure there is at least an mRNA and exon track. Does not fix issue I realize.

**Comment by sr320** [comment]
see also what @kubu4 just did ... https://robertslab.github.io/sams-notebook/2019/12/14/Data-Wrangling-Olurida_v081-UTR-GFFs-and-Intergenic,-Intron-BED-files.html

**Comment by yaaminiv** [comment]
> Would probably want to delve into to figure out which are NCBI tracks - but based on names I would guess none?

I pulled the gene, mRNA, and exon information directly from the NCBI genome:

`!grep "Gnomon	exon" ref_C_virginica-3.0_top_level.gff3 > C_virginica-3.0_Gnomon_exon_yrv.gff3`

> Anyway - see https://d.pr/i/BJx9j6
This would be a case whereby Sam’s explanation does not hold true? you have a UTR marked as exon.

So I guess the UTRs are being assigned to exons by NCBI instead of introns...

There's this code on the FROGER wiki I might have to use to remove UTRs from the exon track:

`````
bedtools subtract -a sorted.ref3.0.exon.bed -b sorted.ref3.0.CDS.bed -g genome.file -sorted > sorted.ref3.0.UTR.bed
bedtools merge -i <(bedtools sort -i sorted.ref3.0.UTR.bed -faidx <(cut -f1 genome.file))> sorted.ref3.0.UTR.sc.b
bedtools sort -i sorted.ref3.0.UTR.sc.b -faidx <(cut -f1 genome.file) > sorted.ref3.0.UTR.sc.bed
`````

Should I go ahead and do the same thing?

**Comment by kubu4** [comment]
Everything looks good to me.

> So I guess the UTRs are being assigned to exons by NCBI instead of introns...

This is what you'd expect, and is what you see in that IGV screenshot. I tried to explain this in the manuscript; apologies if it wasn't very clear. The IGV screenshot is the best way to explain it, but I'll try it again.

UTRs will exist in exons.

UTRs will _not_ exist in introns.

UTRs are only found at the 5' and/or 3' ends of mRNAs.

**Comment by kubu4** [comment]
UTRs will only be found in the most 5' exons and the most 3' exons.

**Comment by kubu4** [comment]
Let me try that again:

UTRs will only be found in the most 5' exons and the most 3' exons for a given gene.

UTRs will _not_ be found on any "interior" exons between the furthers 5' and furthest 3' exons for a given gene.

**Comment by yaaminiv** [comment]
Got it! So my intron and exon tracks should be good to go.

**Comment by sr320** [comment]
But this statement is not true? or likely just out of context.
>The complement of non-coding sequences were then intersected to identify introns.
