### ISSUE TITLE
Merging or Annotating Large CpG datasets

### ISSUE THREAD

**Issue by hputnam** [RobertsLab/resources#815]
For BS data, I am trying to get each CpG assigned to a gene. The input data are strand merged  bed files (e.g., EPI-103_S27_L005_R1_001_val_1_bismark_bt2_pe.deduplicated.bismark.cov.gz (Version: 1) in https://osf.io/yem8n/).

I am then running this script and crashing on line 281.
https://github.com/hputnam/Geoduck_Meth/blob/master/RAnalysis/Scripts/GM.Rmd

MD.D10<- full_join(meth.data.D10, Genes, by="scaffold") %>% filter(position >= start & position <= stop)

The error is "Error in full_join_impl(x, y, by_x, by_y, aux_x, aux_y, na_matches, environment()) : 
  negative length vectors are not allowed" 

The interweb indicates "You are getting this error because the data.frame / data.table created by the join has more than 2^31 - 1 rows (2,147,483,647)."

I am looking for a way to get each CpG assigned to a gene so I can use a GLM to test for significance on a gene by gene basis. If anyone has an suggestions for doing this in bash, I would love to hear them. (e.g., successfully run https://github.com/lyijin/working_with_dna_meth/blob/master/annotate_bismark_cov.py)

Thanks!

**Comment by kubu4** [comment]
Issue #732 solved this by using `bedtools` instead of trying to use R.

**Comment by kubu4** [comment]
> CpG assigned to a gene

Can you clarify this statement? I'm not sure what you mean. Since you have positions of each CpG on each scaffold, and you have gene GFFs, you essentially already have this information.

Can you provide a snippet of what you want the output file to look like? That might help.

**Comment by hputnam** [comment]
> Issue #732 solved this by using `bedtools` instead of trying to use R.

@yaaminiv @kubu4 can you link to an example for the bedtools approach?

**Comment by kubu4** [comment]
@hputnam It will help if we have a better understanding of what you're trying to accomplish. Please see my [post above](https://github.com/RobertsLab/resources/issues/815#issuecomment-567979132).

**Comment by hputnam** [comment]
![Screen Shot 2019-12-20 at 11 42 39 AM](https://user-images.githubusercontent.com/5198996/71269663-e0289080-231d-11ea-900f-f8601d8f1227.png)

I am trying to go from all CpG data, which is not yet assigned to to a gene, but has been filtered by bed tools to know the position is within a gene, to listing the gene name next to each position so that I can test for Differentially Methylated genes including those with multiple CpGs in a single gene




![Screen Shot 2019-12-20 at 11 42 47 AM](https://user-images.githubusercontent.com/5198996/71269673-e454ae00-231d-11ea-8b32-f9c7bae693d3.png)

**Comment by hputnam** [comment]
I was trying to do this with a filtering by both scaffold and greater than start position and less than stop position 

MD.D10<- full_join(meth.data.D10, Genes, by="scaffold") %>% filter(position >= start & position <= stop)

But this is too computationally intensive for R

**Comment by yaaminiv** [comment]
@hputnam I also ran into that negative vector length error so I used a `bedtools` workaround. Here's my script:

https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2019-08-14-Differentially-Methylated-Genes/2019-08-14-Differentially-Methylated-Gene-Analysis.Rmd

Line 242 is where I used `intersectBed`

**Comment by hputnam** [comment]
Thanks!! I will try that loop with the -wb: Print all lines in the second file

**Comment by kubu4** [comment]
Did it work??

**Comment by hputnam** [comment]
> Did it work??

This script will generate 4 csv files of the annotated DMGs from using the GLM approach.
https://github.com/hputnam/Geoduck_Meth/blob/master/RAnalysis/Scripts/GM.Rmd

Thanks!
