### ISSUE TITLE
Next steps for hemolymph samples

### ISSUE THREAD

**Issue by kaitlynrm** [RobertsLab/resources#816]
I isolated RNA from [geoduck hemolymph](https://docs.google.com/spreadsheets/d/1BD0vHIYuGtAiwSTp922mS0Yw68bWshvRuNS41DyGHcs/edit#gid=0) samples of known males and females. 1/3 of the samples contained enough RNA to quantify in 1ul samples on Qubit: 2 females and 3 males. The two females have lower yields (about 4.5 ng/ul) and I have 14ul left of their samples (~65ng/ul).

I could redo RNA isolation using a larger sample volume. This time around I used 150ul of hemolymph  based on @kubu4 suggestion from his previous RNA isolations. However, there is ample sample and I could use more (500-1000ul) to try and get more RNA. (Note @kubu4 used 1000ul of hemolymph for his extractions.)

I could also rerun Qubit analysis on low samples. I only used 1ul of sample for prep, and I could try running it with 2ul. However, I'm not sure this would be useful because I know I have less than 4.5ng/ul. Less than that amount would put me lower than a 50ng/ul yield in my 14ul which is probably too little to get good cDNA rields for qPCR (want 50-100ul yield).

Finally, I could go ahead and make cDNA with the 3 males and 2 females that I have yields from to see how the primer amplifies in each known sex.

**Comment by shellytrigg** [comment]
@kaitlynrm seems like you have enough RNA to make cDNA for the 5 known female and male samples. @kubu4 could you confirm that's enough?

**Comment by kubu4** [comment]
Yes, she has enough.

**Comment by kaitlynrm** [comment]
Great! I'm [working on the calculations now](https://docs.google.com/spreadsheets/d/14GpBXCQZ1uL6NdVoEY7kvbsFv9_SfMY7Ozbd6cqj684/edit#gid=0) and will get started making the cDNA once I'm finished.

**Comment by shellytrigg** [comment]
@kaitlynrm it would be great to try to isolate RNA from the 2/3 known male and female hemolymph samples that you got yield too low to detect by qubit. Maybe by starting with more than 150uL, like starting with something like 500uL instead. But I know you mentioned some samples looked discolored. Do you think more starting vol. could improve your yield enough to make cDNA?

**Comment by shellytrigg** [comment]
@kaitlynrm you could go ahead and make the cDNA today for the samples you have RNA for and then go back and try to get RNA from the 'too low to detect' samples.

**Comment by kubu4** [comment]
Personally, I'd opt for completing all RNA isolations and then performing reverse transcription all at one time. This allows all of the samples to be reversed transcribed with a single master mix, which is nice to ensure uniform treatment/processing of all the samples (since they'll be compared to each other downstream via qPCR).

**Comment by kaitlynrm** [comment]
I can take 600ul of sample from those with lower yields today to ensure uniform processing for reverse transcription.

Should I try to extract more RNA from the two female samples that had lower yield?

**Comment by kubu4** [comment]
Go ahead and extract RNA, using 600uL of hemolymph, from the following samples:

```
G-32 H
G-47 H
G-53 H
G-59 H
G-62 H
G-63 H
G-29 H
G-30 H
G-19 H
G-22 H
G-64 H
G-66 H
G-40 H
G-58 H
G-50 H
```

**Comment by kaitlynrm** [comment]
I will do all of those except G-30 H because only G-30 exists and it looks like gonad.
