### ISSUE TITLE
Location of Stickers?

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#82]
I looked 
https://docs.google.com/spreadsheets/d/11RA_mlLB-3m_GySnTTuDazDdOi0bCxJu2VERuX9Qfx8/edit#gid=486596965

for "stickers" and did not seem to find

**Comment by grace-ac** [comment]
I put them in as "lab inventory labels"

however, i don't think i returned them to the drawer... so they're on the middle raised bar in room 213 above the lab bench

**Comment by sr320** [comment]
And the "water bottle stickers"?

**Comment by sr320** [comment]
Also when I search the sheet I cannot get "labels"

**Comment by sr320** [comment]
Got it! was searching "webpage" instead of sheet
