### ISSUE TITLE
Get read counts for Caligus fq files

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#820]
The files
```
Sealice_F1_S20_L001_R1_001.fastq.gz
Sealice_F1_S20_L001_R2_001.fastq.gz
Sealice_F1_S20_L002_R1_001.fastq.gz
Sealice_F1_S20_L002_R2_001.fastq.gz
Sealice_F2_S22_L001_R1_001.fastq.gz
Sealice_F2_S22_L001_R2_001.fastq.gz
Sealice_F2_S22_L002_R1_001.fastq.gz
Sealice_F2_S22_L002_R2_001.fastq.gz
```

and are at.. 

`/Volumes/web/nightingales/C_rogercresseyi/`

issue is related to consistent error seen with raw and trimmed files...

```
Created C -> T converted version of the FastQ file Sealice_F1_S20_L001_R1_001.fastq.gz (20565855 sequences in total)

Writing a G -> A converted version of the input file Sealice_F1_S20_L001_R2_001.fastq.gz to Sealice_F1_S20_L001_R2_001.fastq.gz_G_to_A.fastq

Created G -> A converted version of the FastQ file Sealice_F1_S20_L001_R2_001.fastq.gz (113474961 sequences in total)

[FATAL ERROR]:	Number of bisulfite transformed reads are not equal between Read 1 (#20565855) and Read 2 (#113474961).
Possible causes: file truncation, or as a result of specifying read pairs that do not belong to each other?! Please re-specify file names! Exiting...
```

**Comment by kubu4** [comment]
I'm determining counts now, but based on file sizes(the file sizes are noticeably different between each of the R1/R2 FastQ files), it's not terribly surprising that they don't have the same number of R1/R2 reads.

**Comment by sr320** [comment]
Thanks! makes sense. Probably should confirm files match what was provided by core.

**Comment by kubu4** [comment]
Hmmm, well, I was wrong regarding file size being an indicator for equal/unequal read counts!

The R1/R2 files have equal numbers of reads:

```
Sealice_F1_S20_L002_R1_001.fastq.gz
112706276
Sealice_F1_S20_L002_R2_001.fastq.gz
112706276
Sealice_F1_S20_L001_R1_001.fastq.gz
113474961
Sealice_F1_S20_L001_R2_001.fastq.gz
113474961
Sealice_F2_S22_L001_R1_001.fastq.gz
82177525
Sealice_F2_S22_L001_R2_001.fastq.gz
82177525
Sealice_F2_S22_L002_R1_001.fastq.gz
81699034
Sealice_F2_S22_L002_R2_001.fastq.gz
81699034

```


![20200102_001](https://user-images.githubusercontent.com/4514104/71693706-ff81dd80-2d61-11ea-9e1a-820dee65dc82.png)

**Comment by kubu4** [comment]
Looking at the error message you shared and the count outputs from Bismark and my calculations, it looks like there's a problem with `Sealice_F1_S20_L001_R1_001.fastq.gz` that you used for input. Maybe it didn't get fully transferred when you pulled it off of Owl?

**Comment by sr320** [comment]
You are correct! just ran md5...

Should have checked that first!
