### ISSUE TITLE
Improved primers for reproductive stage detection in geoduck hemolymph samples

### ISSUE THREAD

**Issue by kaitlynrm** [RobertsLab/resources#822]
[I got variable amplification results on qPCR](https://wordpress.com/post/genefish.wordpress.com/4891) (~~will update once posted~~), so the next steps to improve the amplification results would be:

1. Take proteome Emma used (FASTA file) and identify which full length proteins match fragments in [Fig 6](https://pubs.acs.org/doi/10.1021/acs.jproteome.7b00288)

2. Blast to most current geoduck genome (last primers were created from older version of the geoduck genome)

3. Order primers based on above alignment

4. Test primers via qPCR to see if there is better amplification in females that shows differences across reproductive stages

**Comment by kaitlynrm** [comment]
From paper:

[De novo transcriptome](https://www.ncbi.nlm.nih.gov/bioproject/?term=PRJNA316216)

[ProteomeXchange raw files](http://proteomecentral.proteomexchange.org/cgi/GetDataset?ID=PXD004921)

[PRIDE raw files](https://www.ebi.ac.uk/pride/archive/projects/PXD004921)

[PeptideAtlas raw files](https://db.systemsbiology.net/sbeams/cgi/PeptideAtlas/PASS_View?identifier=PASS00943)

**Comment by sr320** [comment]
This should be the protein Fasta Emma used https://osf.io/2h5ma/

you should be able to identify the proteins referenced, and create a new fasta with just those specific proteins

**Comment by kaitlynrm** [comment]
How do I identify the proteins referenced? Would I need the sequences of the referenced proteins to find them within the linked fasta file?

**Comment by sr320** [comment]
Can you  post that excel spreadsheet with the 40 hemolymph proteins?

**Comment by kaitlynrm** [comment]
[pr7b00288_si_004 (2).xlsx](https://github.com/RobertsLab/resources/files/4037217/pr7b00288_si_004.2.xlsx)
 under hemolymph ROC tab

**Comment by sr320** [comment]
Here is a Fasta protein file with the 8 proteins corresponding to the heat map..

https://d.pr/f/FJE9lL


Take that and blast against the transcriptome https://osf.io/tb5kz/

**Comment by kaitlynrm** [comment]
How do I blast proteins against nucleotides?

**Comment by sr320** [comment]
run tblastn …

I can get started if you have not run blast before

**Comment by kaitlynrm** [comment]
Sure- I am downloading blast now...

**Comment by sr320** [comment]
Lets design new qPCR primers for
genes denoted by the `PGEN_.00g` prefix.

full seq available @ https://osf.io/ct623/

```
cds.comp133422_c0_seq1|m.21507	PGEN_.00g194630-vv0.74.a	90.00	50	5	0	9	58	2059	2208	3e-21	98.6
cds.comp141647_c0_seq1|m.38959	PGEN_.00g280110-vv0.74.a	99.61	254	1	0	352	605	17554	18315	3e-145	  513
cds.comp140343_c0_seq1|m.34678	PGEN_.00g114060-vv0.74.a	98.73	79	1	0	301	379	23463	23699	8e-43	  166
cds.comp144315_c1_seq1|m.50925	PGEN_.00g070040-vv0.74.a	27.04	196	119	6	630	815	5104	5649	1e-09	67.4
cds.comp130260_c0_seq1|m.17968	PGEN_.00g188130-vv0.74.a	95.92	49	2	0	152	200	6356	6502	1e-21	  100
cds.comp138018_c0_seq1|m.29201	PGEN_.00g088260-vv0.74.a	100.00	64	0	0	43	106	3317	3508	3e-24	  105
cds.comp144180_c0_seq1|m.50177	PGEN_.00g338640-vv0.74.a	81.93	83	15	0	522	604	16652	16900	5e-34	  144
cds.comp140645_c0_seq2|m.35570	PGEN_.00g224740-vv0.74.a	93.06	72	5	0	1	72	42924	43139	5e-24	  103
```

**Comment by shellytrigg** [comment]
@kaitlynrm do we know it's the primers and not the samples? Can you describe the variable amplification more? Did your qPCR results for the cDNA samples that @kubu4 prepared from the known females look similar to his [https://robertslab.github.io/sams-notebook/2019/11/27/qPCR-Geoduck-hemolymph-and-hemocyte-cDNA-with-vitellogenin-primers.html](https://robertslab.github.io/sams-notebook/2019/11/27/qPCR-Geoduck-hemolymph-and-hemocyte-cDNA-with-vitellogenin-primers.html)?

**Comment by kaitlynrm** [comment]
@shellytrigg [Here are the results!](https://wordpress.com/post/genefish.wordpress.com/4891) I got the same results as Sam from the cDNA samples he previously tested. It seems like it is the primers because of the number of samples failing to amplify. It could potentially be a technical error, but my technical reps were very similar, and I did get the same results as Sam. Potentially a technical error during RT, but there were still 2 samples that did not amplify in mine or Sam's qPCR. However, there are newer versions of the genome since the original primer design, and primers are cheap so it seems like it would be worth exploring other potential targets in Fig. 6 consequently.

**Comment by shellytrigg** [comment]
@kaitlynrm got it. It would be good to use a positive control primer set to amplify a transcript that we expect to see in all samples (like GAPDH or something) to convince ourselves the cDNA preps are good. Your results are still promising with males showing the least amplification and highest Cq value of 39. Then your stage 4 female shows Cq value 33.6 and stage 7 female shows 31.5 hopefully suggesting increased abundance with stage. But you're right that these primers are likely not ideal, especially with Sam's cDNA prep 57 which previously amplified isn't amplifying in this case.

**Comment by kaitlynrm** [comment]
Okay! I would have used the cDNA positive control Sam used previously but sample volume was too low. More will have to be made for the next qPCR. I thought this time around it would be fine because I was reused samples from the last qPCR so I knew what the Cf should (or in the case of sample 39 should not) be.

**Comment by kubu4** [comment]
@kaitlynrm Here's a [notebook entry](https://github.com/RobertsLab/code/blob/master/notebooks/sam/20181128_swoose_geoduck_vitellogenin_analysis.ipynb) describing a reproducible way to design primers and test them _in-silico_ to evaluate their specificity.

Here's the [Jupyter notebook](https://nbviewer.jupyter.org/github/RobertsLab/code/blob/master/notebooks/sam/20181128_swoose_geoduck_vitellogenin_analysis.ipynb) used to actually do the processing. You can start looking at the Jupyter notebook at `In [10]` for the relevant stuff. You'll need the following programs to design primers in a reproducible fashion:

- `pyfaidx` (splits multi-FastA into individual FastA files)
- `Primer3` (performs primer design)
- `EMBOSS software suite` (checks primer specificity against entire transcriptome)

As always, feel free to ask any questions.

**Comment by kaitlynrm** [comment]
Do I need to split this [file (containing the 8 proteins in Fig 6)](https://osf.io/ct623/) into multiple fastas? Otherwise, `pyfaidx` is not used beyond `ln [10]`, and I think I start by reformating the file for use in `Primer3`.

**Comment by kubu4** [comment]
Yep, sorry about the confusion. Start at `In [6]` to split multi-FastA into individual FastA files.

**Comment by kaitlynrm** [comment]
I'm having trouble locating `pyfaidx` on my computer.... I'm trying to find where it is installed to run `# Split FastA
time \
/home/sam/software/bin/pyfaidx-0.5.5.2 \
--split-files \
../20180827_trinity_geoduck.fasta.transdecoder.cds`

`/home/sam/software/bin/pyfaidx-0.5.5.2 \` is the directory I need to find on my local computer. I'm not sure if the installation did not run appropriately or if I'm looking in the wrong places.

Installation: 
Code ran: `pip install pyfaidx --user` I'm not sure what directory I ran this code from. Would the directory I ran this from be the installation location?...

Output: `Collecting pyfaidx
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from pyfaidx) (1.11.0)
Requirement already satisfied: setuptools>=0.7 in /usr/lib/python3/dist-packages (from pyfaidx) (39.0.1)
Installing collected packages: pyfaidx
  The script faidx is installed in '/mnt/c/Users/Katty/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pyfaidx-0.5.7
You are using pip version 19.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip'

**Comment by kubu4** [comment]
> `/home/sam/software/`

Well, I wouldn't expect you to have this directory structure on your computer (but you might).

That output message tells you where it's installed:

`The script faidx is installed in '/mnt/c/Users/Katty/.local/bin`

**Comment by kaitlynrm** [comment]
Ha! I'm trying to find my local path that would replace the line `/home/sam/software/`!

I tried to run `# Split FastA
time \
/mnt/c/Users/Katty/.local/bin/faidx
--split-files \
../Panopea-generosa-vv0.74.a4.5d9637f372b5d-publish.genes.fna`.

Output: Lots of argument options and 
`real	0m0.638s
user	0m0.063s
sys	0m0.031s
bash: line 6: --split-files: command not found`

**Comment by kubu4** [comment]
Please paste full error messages.

Also, you won't be able to run it, based on the code you've pasted above (there are comments and extra spaces in there that will definitely screw up your command). You should run it like so:

`time /mnt/c/Users/Katty/.local/bin/faidx --split-files ../Panopea-generosa-vv0.74.a4.5d9637f372b5d-publish.genes.fna`

**Comment by kaitlynrm** [comment]
Updated with entire output! 

It looks like the code I pasted (old), and the code above (new) are different only based on the removal of forward slashes.

Old:
> time \ /mnt/c/Users/Katty/.local/bin/faidx --split-files \ ../Panopea-generosa-vv0.74.a4.5d9637f372b5d-publish.genes.fna

New:
> time /mnt/c/Users/Katty/.local/bin/faidx --split-files ../Panopea-generosa-vv0.74.a4.5d9637f372b5d-publish.genes.fna

What do forward slashes do in Bash?

**Comment by kubu4** [comment]
The code you pasted above:

`# Split FastA time \ /mnt/c/Users/Katty/.local/bin/faidx --split-files \ ../Panopea-generosa-vv0.74.a4.5d9637f372b5d-publish.genes.fna`

differs significantly compared to what I pasted:

`time /mnt/c/Users/Katty/.local/bin/faidx --split-files ../Panopea-generosa-vv0.74.a4.5d9637f372b5d-publish.genes.fna`

Although difficult to see by just looking, your code has the following issues:

- line starts with `#`. This indicates a "comment" and the shell will ignore the line. Your code becomes complicated due to extra spaces and line continuation characters (see below).

- `\` are line continuation characters and are used to improve code readability when a command becomes very lengthy. Here's an example of when how it's used (to split a long command across lines in a script) and how it looks:

No line continuation:

`time /mnt/c/Users/Katty/.local/bin/faidx --split-files ../Panopea-generosa-vv0.74.a4.5d9637f372b5d-publish.genes.fna`

With line continuation:

```shell
time \
/mnt/c/Users/Katty/.local/bin/faidx \
--split-files \
../Panopea-generosa-vv0.74.a4.5d9637f372b5d-publish.genes.fna
```

The latter is easier to read because it doesn't wrap and/or doesn't require scrolling to see what the commands are.

Finally, you have extra spaces in your command:

- `time \ /mnt`: There shouldn't be a space between your `\` and `/mnt`. 

- `--split-files \ ../Panopea-`: There shouldn't be a space between `\` and `../Panopea-`

You already have the required space before the `\` in each of those instances.

**Comment by kaitlynrm** [comment]
In [`ln[13]`](https://nbviewer.jupyter.org/github/RobertsLab/code/blob/master/notebooks/sam/20181128_swoose_geoduck_vitellogenin_analysis.ipynb), for `sequence` and `seq_id`, do you only use one of the FastA files in `/home/sam/data/geoduck/transcriptomes/transdecoder_fasta_splits/`? I guess I'm not quite sure what the `TRINITY_DN51983_c0_g1_i8.p1.cds` file is.

**Comment by kubu4** [comment]
Yep, it's one of the split FastAs.

**Comment by kaitlynrm** [comment]
Gotcha, I have 17 FastA files, so I think I would have to loop `[ln] 13`. Do you know the best way to do this? Also, would I need the file the primer thermo dynamic parameters? It is in `[ln} 13` as:
```shell
PRIMER_THERMODYNAMIC_PARAMETERS_PATH=/home/sam/software/primer3-2.4.0/src/primer3_config/
=
EOF
```

**Comment by kubu4** [comment]
> Also, would I need the file the primer thermo dynamic parameters?

Yes.

I'll work on a formatting a loop for the 17 FastAs you have.

**Comment by kubu4** [comment]
Can you please list the filenames of your FastAs in this issue?

**Comment by shellytrigg** [comment]
PGEN_.00g000750-vv0.74.a.fna
PGEN_.00g025890-vv0.74.a.fna
PGEN_.00g079690-vv0.74.a.fna
PGEN_.00g082590-vv0.74.a.fna
PGEN_.00g132030-vv0.74.a.fna
PGEN_.00g132040-vv0.74.a.fna
PGEN_.00g245080-vv0.74.a.fna
PGEN_.00g288180-vv0.74.a.fna
PGEN_.00g287540-vv0.74.a.fna
PGEN_.00g194630-vv0.74.a.fna
PGEN_.00g280110-vv0.74.a.fna
PGEN_.00g114060-vv0.74.a.fna
PGEN_.00g070040-vv0.74.a.fna
PGEN_.00g188130-vv0.74.a.fna
PGEN_.00g088260-vv0.74.a.fna
PGEN_.00g338640-vv0.74.a.fna
PGEN_.00g224740-vv0.74.a.fna

**Comment by kaitlynrm** [comment]
Can you send me that file @kubu4?

**Comment by kubu4** [comment]
Which file?

**Comment by kaitlynrm** [comment]
The one for the primer thermodynamic parameters. 

When I installed Primer3 using `pip install primer3-py --user`, the output was:

`Collecting primer3-py Downloading https://files.pythonhosted.org/packages/7b/f4/c47952f5db5a0289e2dc056130e4304bb16bf0de9fb2d0c091f385094bfc/primer3-py-0.6.0.tar.gz (400kB) 100% |████████████████████████████████| 409kB 1.5MB/s Building wheels for collected packages: primer3-py Building wheel for primer3-py (setup.py) ... done Stored in directory: /mnt/c/Users/Katty/.cache/pip/wheels/d0/a5/2f/e3e39b4d52e55e9a9d4565a3d5a5c175afec23e6ddcec905bd Successfully built primer3-py Installing collected packages: primer3-py Successfully installed primer3-py-0.6.0 You are using pip version 19.0.3, however version 19.3.1 is available. You should consider upgrading via the 'pip install --upgrade pip' command.`

I do not see `primer3-2.4.0/src/primer3_config/` within the specified installation location. I only see `primer3_py-0.6.0-cp36-cp36m-linux_x86_64` so I'm  not sure what to specify for the primer thermodynamic parameters file.

**Comment by kubu4** [comment]
It's not a single file, it's a collection of files. That's why you just specify the path to that folder.

On that note, download and install from here:

https://sourceforge.net/projects/primer3/files/latest/download
 
That will allow you a bit more control. I'm not a fan of installations via the Python installer package thingy (pip); probably because I don't fully understand how it works and where it puts stuff.

Anyway, here's a script you could run from your directory with your _split_ FastAs. Remove the source FastA from that directory. You'll need to change the `primer3` path and the `thermo_params_path` to match your install locations.

```shell
#!/bin/bash

# Path to primer3_core program
primer3="/path/to/primer3_core"
thermo_params_path="/path/to/primer3-2.4.0/src/primer3_config/"

for fasta in *.fna
do
  # Store sequence only from desired FastA.
  # Print all lines after the first line and then delete newlines
  sequence=$(tail -n +2 /"${fasta}" | tr -d '\n')

  # Capture sequence ID from FastA filename
  seq_id=$(echo "${fasta}" | awk -F "-" '{print $1}')

# Use heredoc to create Primer3 parameters file
cat << EOF > "${seq_id}"_primer3_params.txt
SEQUENCE_ID=${seq_id}
SEQUENCE_TEMPLATE=${sequence}
PRIMER_TASK=generic
PRIMER_PICK_LEFT_PRIMER=3
PRIMER_PICK_RIGHT_PRIMER=3
PRIMER_OPT_SIZE=18
PRIMER_MIN_SIZE=15
PRIMER_MAX_SIZE=21
PRIMER_MAX_NS_ACCEPTED=1
PRIMER_PRODUCT_SIZE_RANGE=75-150
P3_FILE_FLAG=1
PRIMER_EXPLAIN_FLAG=1
PRIMER_THERMODYNAMIC_PARAMETERS_PATH=/home/sam/software/primer3-2.4.0/src/primer3_config/
=
EOF

  # Run Primer3
  ${primer3} \
  --format_output \
  --output="${seq_id}"_primer3_primers.txt \
  "${seq_id}"_primer3_params.txt
done
```
To run the script, save the above code to a file: primer3_split_FastA.sh

Save it to your directory with split FastAs.

Then, make it executable:

`chmod +x primer3_split_FastA.sh`

Then, run it:

`bash primer3_split_FastA.sh`

Then, cross your fingers that it all works!

**Comment by kubu4** [comment]
Update! I just edited the script above! Make sure you have the updated version. Update has the following line:

`PRIMER_THERMODYNAMIC_PARAMETERS_PATH="${thermo_params_path}"`

**Comment by kaitlynrm** [comment]
Great, thank you! Do you just find a website to download packages from then unzip them to a location of your choosing (rather than using pip)?

**Comment by kubu4** [comment]
Yes.

**Comment by kaitlynrm** [comment]
I don't have `primer3_core`:
![Capture](https://user-images.githubusercontent.com/26392677/72571236-e013a600-3873-11ea-8a56-eb2a2d5d6b53.JPG)

**Comment by kubu4** [comment]
It doesn't look like you installed the program. Did you run `make`?

**Comment by kubu4** [comment]
Here's what the README file says in my install:

```
Design PCR primers from DNA sequence. Widely used (190k Google hits for "primer3").
From mispriming libraries to sequence quality data to the generation of internal
oligos, primer3 does it. C&perl.

Installing
----------

`sudo apt-get install -y build-essential g++ cmake git-all`

`git clone https://github.com/primer3-org/primer3.git primer3`

`cd primer3/src`

`make`

`make test`
```

**Comment by kubu4** [comment]
Sorry, didn't remember where I had installed it from previously. Just assumed it was from that Sourceforge link above, as that's one of the first things that came up when searching the internet.

**Comment by kubu4** [comment]
Oooh, looks like the newest release does away with the whacky thermo paramaters!

```
release 2.5.0 - 2019-08-17

This release adds new features to primer3_core and related C code.

The primer3_config files for thermodynamic calculations are embedded in the
code and the primer3_config/ folder is not required any more for default
settings.
```

**Comment by kaitlynrm** [comment]
I only installed and unzipped it. I wasn't aware I had to run make- whoops! Should I download the newest version (and find installation instructions in the readme?) and remove the thermodynamic lines in the loop you wrote?

**Comment by shellytrigg** [comment]
@kaitlynrm you can add the primer sequences, GC%, Tm (melting temp), full sequence (full sequence from your .fna files), product size, etc. to this doc:  [https://docs.google.com/spreadsheets/d/1vkUQvqNUN-9ntv0NoVDAtD8zA-p9e3xosGwsWSFV0qk/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1vkUQvqNUN-9ntv0NoVDAtD8zA-p9e3xosGwsWSFV0qk/edit?usp=sharing). Then we can copy it over to the [Primer Database](https://docs.google.com/spreadsheets/d/14m2kkFhxcoKWWIGoAD_7VOVsAg9wilME2UcSLqfnqLI/edit?usp=sharing)

**Comment by kaitlynrm** [comment]
Ran following code in jupyter notebook:

```
%%bash

# Path to primer3_core program
primer3="/mnt/c/Users/Katty/Documents/linux_programs/primer3/src/primer3_core"
thermo_params_path="/mnt/c/Users/Katty/Documents/linux_programs/primer3/src/primer3_config/"

for fasta in ../../data/indv/*.fna
do
  # Store sequence only from desired FastA.
  # Print all lines after the first line and then delete newlines
  sequence=$(tail -n +2 /"${fasta}" | tr -d '\n')

  # Capture sequence ID from FastA filename
  seq_id=$(echo "${fasta}" | awk -F "-" '{print $1}')

# Use heredoc to create Primer3 parameters file
cat << EOF > "${seq_id}"_primer3_params.txt
SEQUENCE_ID=${seq_id}
SEQUENCE_TEMPLATE=${sequence}
PRIMER_TASK=generic
PRIMER_PICK_LEFT_PRIMER=3
PRIMER_PICK_RIGHT_PRIMER=3
PRIMER_OPT_SIZE=18
PRIMER_MIN_SIZE=15
PRIMER_MAX_SIZE=21
PRIMER_MAX_NS_ACCEPTED=1
PRIMER_PRODUCT_SIZE_RANGE=75-150
P3_FILE_FLAG=1
PRIMER_EXPLAIN_FLAG=1
PRIMER_THERMODYNAMIC_PARAMETERS_PATH="${thermo_params_path}"
=
EOF

  # Run Primer3
  ${primer3} \
  --format_output \
  --output="${seq_id}"_primer3_primers.txt \
  "${seq_id}"_primer3_params.txt
done
```

Output for each FastA file:
```
tail: cannot open '/../../data/indv/PGEN_.00g000750-vv0.74.a.fna' for reading: No such file or directory
bash: line 6: 10350 Segmentation fault      (core dumped) ${primer3} --format_output --output="${seq_id}"_primer3_primers.txt "${seq_id}"_primer3_params.txt
```
When I `head` the file that produced the error: ![Capture](https://user-images.githubusercontent.com/26392677/72657437-1d059880-3959-11ea-9256-e2609445a065.JPG)

**Comment by kubu4** [comment]
Your head command points to a different location than what you specified in your primer3 command. Compare the two paths and see if you can figure out the problem.

**Comment by kaitlynrm** [comment]
Does it have to do with where I put the asterisk?

**Comment by kaitlynrm** [comment]
I see the error put `/../../data/indv/` rather than `../../data/indv/`. Do I need to put the full path instead?

**Comment by kubu4** [comment]
Found it! Nice job. Use the path you used for your head command in your primer3 command.

**Comment by kubu4** [comment]
Ah! Actually, it's a bit trickier to find than that. Look for an errant `/` for your FastAs.

**Comment by kaitlynrm** [comment]
Dang, good find followed by an error. After fixing and re-running the code (including removing the line `PRIMER_THERMODYNAMIC_PARAMETERS_PATH="${thermo_params_path}` which I previously forgot to remove) I got the following error for each cycle in the loop:

```
/mnt/c/Users/Katty/Documents/linux_programs/primer3/src/primer3_core: Illegal PRIMER_EXPLAIN_FLAG value: 1"
```

**Comment by kubu4** [comment]
We'll, you'll have to read the manual for that one. Likely related to the updated version you're using, vs. the older version I was using when I originally put that notebook together.

**Comment by kaitlynrm** [comment]
@shellytrigg I filled out the spreadsheet! One sequence was very long and could not be put into the spreadsheet because of the character limit on cells- Accession ID 00g280110. 

I will upload all the sequences to OWL and link the file for the long sequence in the spreadsheet once my IP address is unblocked. Quickly, here is the sheet containing the full sequence so those can be ordered though:
[PGEN_.00g280110_primer3_primers.txt](https://github.com/RobertsLab/resources/files/4104610/PGEN_.00g280110_primer3_primers.txt)

**Comment by kaitlynrm** [comment]
@shellytrigg primers with sr_ID **1759 and 1757** as well as **1758 and 1756** in the PrimerDatabase have the same Primer name. Both pairs are for TIF3s8 (Translation initiation factor 3 subunit 8). We have to have unique names for each primer. How should we change the names for ordering?

**Comment by kaitlynrm** [comment]
I just added '-1' and '-2' for the two names!
