### ISSUE TITLE
Installing EMBOSS on Ubuntu

### ISSUE THREAD

**Issue by kaitlynrm** [RobertsLab/resources#824]
Having an issue trying to configure and compile after EMBOSS download. I run a Windows Subsystem for Linux (previously Git Bash, but ran into some problems with command limitations and decided to make the switch).

1. Downloaded `emboss-latest.tar.gz` at ftp://emboss.open-bio.org/pub/EMBOSS/)
2. Unzipped
3. Navigated to `..EMBOSS-6.6.0/` and ran `./configure`:

`checking for gawk... gawk
checking for icc... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for icpc... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C preprocessor... gcc -E
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking whether make sets $(MAKE)... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking whether build environment is sane... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking dependency style of g++... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for X... no
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for ANSI C header files... (cached) yes
checking for unistd.h... (cached) yes
checking TargetConfig.h usability... no
checking TargetConfig.h presence... no
checking for TargetConfig.h... no
checking whether byte ordering is bigendian... no
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for pid_t... yes
checking for size_t... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking whether getpgrp requires zero arguments... yes
checking for strftime... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for vprintf... yes
checking for _doprnt... no
checking for memmove... yes
checking X11/Xlib.h usability... no
checking X11/Xlib.h presence... no
checking for X11/Xlib.h... no

X11 graphics have been selected but no X11 header files
have been found.

**This error usually happens on Linux/MacOSX distributions
where the optional X11 development files have not been installed.
On Linux RPM systems this package is usually called something
like xorg-x11-proto-devel whereas on Debian/Ubuntu it may
be called x-dev.** On MacOSX installation DVDs the X11 files
can usually be found as an explicitly named optional
installation.

After installing the X11 development files you should do a
'make clean' and perform the configure stage again.

Alternatively, to install EMBOSS without X11 support, you can add
the --without-x switch to the configure command.`

I'm not sure how to get the X11 headers. I found this [biostars issue](https://www.biostars.org/p/6771/) where it appears the user solved the problem, but I'm not sure how to interpret the solution.

I know I need to `make clean` then redo `./configure` and then try `make` again after I solve the X11 header issue.

**Comment by kubu4** [comment]
Try this:

`sudo apt install xorg`

Then, run your `./configure` command.

You don't need to run `make clean`, since you haven't run `make` yet.

**Comment by kubu4** [comment]
I've also installed the EMBOSS suite on Emu and Roadrunner. It's here on both machines:

`/home/shared/EMBOSS-6.6.0`

**Comment by kaitlynrm** [comment]
Should that be ran from `..EMBOSS-6.6.0/`?

**Comment by kubu4** [comment]
Which?

`./configure` should be run in the `EMBOSS-6.6.0/` directory.

`sudo apt install xorg` can be run from anywhere.

**Comment by kaitlynrm** [comment]
Okay, I ran `sudo apt install xorg`. Additional packages for install, suggested packages and new packages for install were listed, and packages to be updated were listed. Then it prompted:

`2 upgraded, 186 newly installed, 0 to remove and 151 not upgraded.
Need to get 26.4 MB/52.6 MB of archives.
After this operation, 199 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y`

And then I started getting errors:

`Err:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 parted amd64 3.2-20ubuntu0.1
  404  Not Found [IP: 2001:67c:1360:8001::21 80]`

At the end, it suggested:

`Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

`

**Comment by kubu4** [comment]
Try the first suggestion in that error message.

After that, run `sudo apt upgrade`.

After that, run the xorg command from above.

Then, the configure command.

**Comment by kaitlynrm** [comment]
Ran the following:

- `sudo apt-get update`
- `sudo apt upgrade` (took 15 minutes!)
- `sudo apt install xorg` (also took a long time)
- `./configure` from the `EMBOSS-6.6.0/` directory

`./configure` produced the same error as above. No errors happened with the other 3 codes.

**Comment by kubu4** [comment]
Try this to get X11 working:

`sudo apt-get install x11-apps`

**Comment by kaitlynrm** [comment]
Ran the above code and got:

`Reading package lists... Done
Building dependency tree
Reading state information... Done
x11-apps is already the newest version (7.7+6ubuntu1).
x11-apps set to manually installed.
The following package was automatically installed and is no longer required:
  libllvm7
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

Then I ran `./configure` and got the same error as before.

**Comment by kaitlynrm** [comment]
Do I need X11 support, or should I try to install EMBOSS without it? (`Alternatively, to install EMBOSS without X11 support, you can add the --without-x switch to the configure command.`)

**Comment by kubu4** [comment]
If you haven't shutdown and restarted Ubuntu, I would do that first. 

Then, run the `./configure` command.

If error still persists, then yes, run the `--without-x` option when running the configure command.

**Comment by kaitlynrm** [comment]
Closed and reopened window then reran `./configure` and got the same error.

Ran `./configure --without-x` and didnt get any errors. Do you know how not having X11 support will affect things?

**Comment by kubu4** [comment]
Shouldn't be a problem for your usage. X11 is a graphics thing. You're only performing text-based stuff, so should be fine.

**Comment by kaitlynrm** [comment]
Thanks @kubu4! Another quick question per installing EMBOSS, I'm trying to set my path via `set path=/emboss` from the `/EMBOSS-6.4.0/` directory, but I don't recognize the location when I try and tab complete the path.

I.E. I type `set path=` then push tab to complete the path and these are my options `allexport             ignoreeof             nounset
braceexpand           interactive-comments  onecmd
emacs                 keyword               physical
errexit               monitor               pipefail
errtrace              noclobber             posix
functrace             noexec                privileged
hashall               noglob                verbose
histexpand            nolog                 vi
history               notify                xtrace` which are NOT in the `EMBOSS-6.4.0` directory I am in.

Is this in the Linux partition of my PC, and if so, do you know how to specify the path into the Windows section? I tried typing `/mnt/` to see if my C drive would pop up, but it didn't. Alternatively, should/could I set the path via the Windows GUI?

**Comment by kubu4** [comment]
A few things here:

1. > /emboss

This tells the computer to look in the root directory. When you lead a path with a slash, that means start at the root. You'd want `./emboss` if you're in your `EMBOSS-6.4.0/` directory.

2. `set` is a an actual bash program. That's why you see all those options when doing the tab completion. It's prompting you with options to use with `set`.

3. If you want `EMBOSS-6.4.0/emboss` in your system $PATH, you can do a few things, but here's the most common way to add something like the following to your `~/.bashrc` file (add your emboss installation location instead of what I used below).

```shell
# Custom PATH
export PATH="/home/shared/EMBOSS-6.6.0:\
$PATH"
```
This will prepend `emboss` to the beginning your system `$PATH`.

After adding that to your `~/.bashrc` file, you'll want to restart the terminal you're using to get the changes to take effect.

**Comment by kaitlynrm** [comment]
Ah okay, I tried `set path` because I thought I was using a `csh` style shell versus a `sh` style shell so I followed [those instructions (under 2.7.4)](http://emboss.open-bio.org/html/use/ch02s07.html).

I entered `export PATH="`, double tabbed to see options and saw `Documents/` as an option, but when I type `export PATH="Docu` it will not auto complete. 

Path is `/mnt/c/Users/Katty/Documents/linux_programs/EMBOSS-6.4.0`

I entered the path manually, `export Path="`/mnt/c/Users/Katty/Documents/linux_programs/EMBOSS-6.4.0:\ $PATH"` and nothing happened. I also tried without `/mnt/c/Users/Katty/`.

**Comment by kubu4** [comment]
Sorry, I'm not following what you're doing.

Did you add the info I mentioned above to your `~/.bashrc` file?

**Comment by kubu4** [comment]
Also, after looking at the page you linked, it's also important to explain the installation steps you performed, as this will allow us to figure out where the program was installed (it differs based on the installation commands you issued).

Please list the commands you used to configure and install.

**Comment by kaitlynrm** [comment]
I'm trying to add the info to the `~/.bashrc` file by entering `export PATH="/home/shared/EMBOSS-6.4.0:\
$PATH"`.

However, I can't navigate to the `EMBOSS-6.4.0/` directory while inputting the command. 
If I list the path options after typing `export PATH="`, I see `Documents/` as a directory option, but I can't reach the subdirectory `linux_programs/` after adding it where `EMBOSS-6.4.0/` is (note that it autocomplete also does not work for the `Documents/` directory).

I believe this means I am unable to properly insert the path, issue the command, and add the info to my `~/.bashrc` file.

--

Per the commands I used to configure and install, they are all listed above in the thread:

1. Downloaded emboss-latest.tar.gz at ftp://emboss.open-bio.org/pub/EMBOSS/)
2. Unzipped
3. Navigated to ..EMBOSS-6.6.0/ and ran ./configure:

At step 3, I ran into issues with the `./configure` command because of the X11 headers and posted this issue. Ultimately, I installed it without X11 support. 

4. Installed without X11 Support
5. Ran `make` from `EMBOSS-6.4.0/` directory.

The final step is adding EMBOSS to my path, but I'm having trouble with that now.

**Comment by kubu4** [comment]
You need to edit the `~/.bashrc` file with a text editor (_not_ Microsoft Word). Then, paste this in the file (at the bottom is probably best/easiest):

```shell
# Custom PATH
export PATH="/home/shared/EMBOSS-6.6.0:\
$PATH"
```

Replace `/home/shared/EMBOSS-6.6.0` with the path to your EMBOSS folder.

Save your edits.

Restart Ubuntu.

**Comment by kaitlynrm** [comment]
Oh I see! Sorry about that! 

I'm having a little trouble picking my path... I tried these three:

- Windows path: `C:\Users\Katty\Documents\linux_programs\EMBOSS-6.6.0`
- Path shown on terminal: `/mnt/c/Users/Katty/Documents/linux_programs/EMBOSS-6.6.0`
- Path given if in `EMBOSS` directory and type `echo $PATH`: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Rtools/mingw_64/bin:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files (x86)/ZipGenius 6/:/mnt/c/Program Files/Git/cmd:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/PuTTY/:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/NCBI/blast-2.6.0+/bin:/mnt/c/Users/Katty/AppData/Local/Microsoft/WindowsApps:/snap/bin`

However, when I restarted Ubuntu and tried `embossversion` I got the error the command was not found indicating I likely am picking the wrong path.

The `~/.bashrc` file is in the linux partition of my computer: `C:\Users\Katty\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\home\katty`.

**Comment by kubu4** [comment]
> I'm having a little trouble picking my path

I'm not sure what you mean by this. There's no path to "pick". The computer sets the system $PATH automatically.

Also, I just realized I made a mistake.SORRY!! Change your `~/.bashrc` to read this instead:

```shell
# Custom PATH
export PATH="/home/shared/EMBOSS-6.6.0/emboss:\
$PATH"
```

Sorry about that!!

Finally, you don't need to have emboss in your system $PATH. That's just a thing for convenience. Allows you to type:

`embossversion` from any directory

as opposed to having to type the full path to the program:

`/home/shared/EMBOSS-6.6.0/emboss/embossversion`

**Comment by kaitlynrm** [comment]
Oh that's great to know! Still wrapping my head around paths after all this time. 

> add your emboss installation location instead of what I used below

I thought I would have to insert one of the paths I mentioned in my most recent comment to reflect my emboss installation location instead in the above code (vs. `/home/shared/EMBOSS-6.6.0/emboss`). What replaces `home/shared/` in the path?

**Comment by kubu4** [comment]
Replace `/home/shared` with the full path to your installation of EMBOSS.

Easiest way to find this is to navigate to your `EMBOSS-6.6.0/emboss` and then type `pwd` (for print working directory). That will print the full path of that directory. Use that to substitute.

**Comment by kubu4** [comment]
The path vs. `$PATH` thing is definitely confusing! It's a poor choice of terminology.

path: A term to describe the location of a file/folder on a computer.

`$PATH`: A _variable_ that stores the locations (paths) of various files/folders on a computer. The values (i.e. paths) stored in the is variable are used by the computer to figure out where the default programs it should use for operations are located on the computer.

**Comment by kaitlynrm** [comment]
So if I type `echo $PATH`, the output contains all the locations (paths) within the variable `$PATH`?

**Comment by kubu4** [comment]
Exactly. Just like any variable.

You can test it by making a simple variable/value. E.g.

Set a variable to a value:

`pizza=cheeseandsauce`

`echo $pizza`

The `echo` command should print: `chesseandsauce`

That's why the system `$PATH` always has a dollar sign in front of it - that's how the shell refers to variables.
