### ISSUE TITLE
Submit Geoduck Assembly to ENA

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#826]
https://ena-docs.readthedocs.io/en/latest/submit/assembly.html

**Comment by kubu4** [comment]
Quick update on this. Submissions are "disrupted" until March 27th, due to EMBL-EBI data migration.

**Comment by kubu4** [comment]
Uploads still failing. Here's response from ENA tech support:

> Hi Sam,
>
>The migration was expected to be complete as of 27th of March, but appears to
still be ongoing.
>
>We apologise for the inconvenience, however this is beyond the control of ENA.
>
>Best wishes,
Alisha

**Comment by kubu4** [comment]
Alrighty, it's been submitted!

Accession: GCA_902825435

Their still in the midst of migrating stuff, so the link below doesn't currently work, but it should end up here eventually:

https://www.ebi.ac.uk/ena/data/view/GCA_902825435
