### ISSUE TITLE
ATAC-seq for mollusc?

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#830]
Some tips from Jason Buenrostro, the person who developed ATAC-seq:

[https://drive.google.com/drive/u/0/folders/1rL9ug9ixCk-dbE6qLFImvZ_vDmxqSPrr](https://drive.google.com/drive/u/0/folders/1rL9ug9ixCk-dbE6qLFImvZ_vDmxqSPrr)

**Comment by shellytrigg** [comment]
**Info from Genomics Core at University of Minnesota about their ATAC-seq services:**

Hi Ben,

Thanks so much for all the helpful info! I'm not sure how easy it will be to isolate single oyster cells from our samples. We have frozen tissue we'd like to look at, but if that doesn't work, we are could look at single cell embryos. We will work on investigating the single cell isolation and chromatin extraction part. And will be in touch with Elyse after we can figure that out. Great to know about the RNAseq deal too!

Thanks again!

-Shelly

On Mon, Jan 27, 2020 at 3:55 PM Benjamin Auch <auchx002@umn.edu> wrote:

    Hi Shelly and Yaamini,

    Great to hear from you! I'm going to put you in touch with Elyse on our NGS team (next-gen@umn.edu) who can verify the details of the ATAC-seq process I'm explaining here and provide pricing information. She'll be able to answer all your questions and coordinate if you decide to move forward. And she's awesome to work with! 

    Briefly, we use the attached protocol almost exactly as written. We would ship you reagents (TD, TDE1), and you would prepare cells and perform the transposase reactions yourself. You would then clean-up the reactions (standard column cleanup, e.g. Zymo DCC/Qiagen MinElute) and send the treated DNA back to us for further library prep and sequencing. Protocol is optimized for ~50k cells. Sequencing depth is a question, but I'll bet 20M clusters is a good place to start.

    One thing to be mindful of is that this protocol is designed for easy-peasy mammalian cells. Not sure how well the lysis buffer will work on molluscs. And I've had some trouble myself working with mollusc tissue and isolating cells or subcellular components. All those mucopolysaccharides cause cells/organelles to stick together, and downstream can cause issues with DNA purification as well. For example, my AMPure recovery efficiency on Dreissenid DNA was only ~30%. What's more, I don't know how this will affect the ability of the transposase to interact with the nuclei. Have you worked with isolated oyster cells before? Your own experience will be the most informative, and maybe you're doing this on hemocytes or something which would be much easier. But it's something I would recommend thinking about, and maybe experimenting with if there's time/energy. Happy to chat further with you about this if you get to that point.

    p.s. let Elyse know if you want to do RNA-seq as well. Our Charter-Seq service runs monthly for a flat rate of $205/sample @ 20M reads, and she can coordinate that, too. 

    Thanks for getting in-touch, and best of luck! 

    --
    Ben Auch 
    Research Scientist, Innovation Lab 
    University of Minnesota Genomics Center 
    Office: 612-624-6269 
    Mobile: 763-439-4468 


    On Mon, Jan 27, 2020 at 5:08 PM Shelly Trigg <strigg@uw.edu> wrote:

        Hi Ben,

        I'm inquiring about UMN GC services for doing ATAC-seq on let's say 30 samples of oyster tissue. What exact steps can the Core help with and about how much would it cost? Yaamini (CC'd on this email) is a graduate student in our lab who would be spearheading this project. Let me know if we can provide any other info.

        Thanks!

        -Shelly

**Comment by shellytrigg** [comment]
ATAC-seq protocol:

[atac_seq_cpmb_2015.pdf](https://github.com/RobertsLab/resources/files/4125419/atac_seq_cpmb_2015.pdf)

**Comment by shellytrigg** [comment]
ATAC-seq advice from Line Lieblein Rosaeg (Norwegian University of Life Sciences) who did ATAC-seq in atlantic salmon frozen and fresh tissue:

[https://drive.google.com/drive/u/0/folders/1rL9ug9ixCk-dbE6qLFImvZ_vDmxqSPrr](https://drive.google.com/drive/u/0/folders/1rL9ug9ixCk-dbE6qLFImvZ_vDmxqSPrr)

Protocols she used:
- [Omni-ATAC_article.pdf](https://github.com/RobertsLab/resources/files/4125495/Omni-ATAC_article.pdf)
- [Omni_ATAC_Supplementary_Protocol_1.pdf](https://github.com/RobertsLab/resources/files/4125497/Omni_ATAC_Supplementary_Protocol_1.pdf)
- [Omni_ATAC_Supplementary_Protocol_2.pdf](https://github.com/RobertsLab/resources/files/4125500/Omni_ATAC_Supplementary_Protocol_2.pdf)

**Comment by shellytrigg** [comment]
Alternative approach to look at capped small RNAs recommended by Sashca Duttke at UCSD:
- [Genome Res.-2019-Duttke-gr.253492.119.pdf](https://github.com/RobertsLab/resources/files/4125530/Genome.Res.-2019-Duttke-gr.253492.119.pdf)

Here's some info on ATACseq vs. csRNAseq from Sascha:  [https://docs.google.com/document/d/1fjvnLn0LsICt7WP9J3HSeXlBJaCz8QSp3fspADxb4pE](https://docs.google.com/document/d/1fjvnLn0LsICt7WP9J3HSeXlBJaCz8QSp3fspADxb4pE)

**Comment by sr320** [comment]
@yaaminiv probably worth noting
