### ISSUE TITLE
Installing executable program on Emu 

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#833]
I'm encountering errors on MACAU, and I see that there is a new version available, which could fix my issue (hopefully).  Any special instructions for installing executable files on Emu?  I tried downloading the executable format and altering permission settings to match the old version. When I try using it I get no errors, but no output either.  Is there something I need to do to make the file actually executable?  

¯\\\_(ツ)\_/¯

**Comment by kubu4** [comment]
Link to program to download?

**Comment by laurahspencer** [comment]
[http://xzlab.org/software.html](http://xzlab.org/software.html) - the software is in the section entitled "Mixed model Association for Count data via data AUgmentation (MACAU)"

**Comment by sr320** [comment]
see also https://github.com/RobertsLab/resources/issues/722

**Comment by laurahspencer** [comment]
Interesting to see that you installed version 1.30 - when I pull up the program's help file it says that it's version 1.00alpha, released on 06/05/2015.

**Comment by kubu4** [comment]
Ugh, thanks @sr320 for reminding me that I already dealt with the horrors of this program!

From the previous issue:

> The link to the "executable" version of the software links to an outdated version (1.00alpha, from 2015), not the current version (1.30, compiled in May 2019).


And... 

> The developer has clarified that the MACAU binary on the site is current and that they neglected to update the version listed in the software
