### ISSUE TITLE
Figuring out methylation island parameters

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#834]
Based on [this paper](https://academic.oup.com/gbe/article/10/10/2766/5098531) and using [this perl script](https://github.com/soojinyilab/Methylation-Islands/blob/master/methyl_island_sliding_window.pl), I generated various methylation islands for my *C. virginica* data in this [Jupyter notebook](https://github.com/fish546-2018/yaamini-virginica/blob/master/notebooks/2019-03-18-Characterizing-CpG-Methylation.ipynb). These tracks have different input parameters, number of total MI, and # of mCpG in MI:

| **Initial Window Size (bp)** | **mCpG Fraction** | **Number of MI** | **Max mCpG in MI** | **Min mCpG in MI** |
|:----------------------------:|:-----------------:|:----------------:|:------------------:|:------------------:|
|              200             |        0.02       |      119705      |        24777       |          4         |
|              200             |        0.03       |      129006      |        8305        |          6         |
|              200             |        0.04       |      113806      |        1682        |          8         |
|              200             |        0.05       |       93229      |        1452        |         10         |
|              200             |        0.10       |       18719      |        1167        |         20         |
|              200             |        0.15       |       2453       |         177        |         30         |
|              200             |        0.20       |        320       |         94         |         40         |
|              200             |        0.25       |        37        |         63         |         50         |
|              200             |        0.27       |         8        |         57         |         54         |
|              200             |        0.30       |         0        |          0         |          0         |
|              300             |        0.02       |       91756      |        24777       |          6         |
|              300             |        0.03       |       91833      |        8305        |          9         |
|              300             |        0.04       |       74497      |        1682        |         12         |
|              300             |        0.05       |       53510      |        1452        |         15         |
|              300             |        0.10       |       6629       |        1167        |         30         |
|              300             |        0.15       |        546       |         177        |         45         |
|              300             |        0.20       |        20        |         94         |         60         |
|              300             |        0.25       |         0        |          0         |          0         |       |

After looking at the stats, I created [this IGV session](https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2019-03-07-IGV-Verification/2020-02-06-Methylation-Island-Verification.xml) to visualize them and decide which MI track I should use for downstream analyses.

![Screen Shot 2020-02-06 at 7 36 05 PM](https://user-images.githubusercontent.com/22335838/73999055-632a9800-4918-11ea-826c-f056aaa88e4f.png)

![Screen Shot 2020-02-06 at 7 36 44 PM](https://user-images.githubusercontent.com/22335838/73999059-658cf200-4918-11ea-82bf-f3a21a7db07b.png)

## **Any thoughts on which MI track to use?** 

Just based on the stats and IGV session, I think the 0.02 mCpG fraction and 50 bp window the original authors used captures most of the islands, but I don't know how to choose between the 200 or 300 bp initial window size. There may also be a better way to choose the MI track.

**Comment by sr320** [comment]
I would go with 300 initial window...
But I  also think 50 bp window is too small for oysters. I would sett at 500. 
https://d.pr/i/XijNqE

**Comment by yaaminiv** [comment]
@sr320 so 300 initial window with a 500 step size?

> and also wonder why windows "extend" on top two...

What do you mean by extend? Do you mean windows that don't overlap with mRNA?

**Comment by sr320** [comment]
Not clear on lingo - but I recommend that an island has to have a minimum size of 500 bp. 

regarding extend - see this annotation https://d.pr/i/8Z5Zc8

**Comment by yaaminiv** [comment]
@sr320 Okay. I'll try increasing the initial window size to 500 bp (ie a MI will be no smaller than 500 bp), and maybe play around with 50 vs 100 bp for the step size (how much the window is extended by). 

> regarding extend - see this annotation https://d.pr/i/8Z5Zc8

My guess is it's based on the way the windows are extended:

> A 200-bp window satisfying the mCG fraction threshold is extended by 50 bp and re-evaluated for its mCG fraction. **This extension continues until the mCG fraction of the extended window falls below the threshold**, after which the last mCG in the previously evaluated window is chosen as the ending position of the methylation island (supplementary fig. S2B, Supplementary Material online). Therefore, the starting and ending positions of methylation islands are always mCGs.

The extension is probably where the window fell below the mCpG threshold.

**Comment by sr320** [comment]
extend 50 at max

**Comment by yaaminiv** [comment]
@sr320 I tried 500 bp windows with either 25 or 50 bp sizes:

| **Initial Window Size (bp)** | **mCpG Fraction** | **Step Size (bp) ** | **Number of MI** | **Max mCpG in MI** | **Min mCpG in MI** |
|:----------------------------:|:-----------------:|:-------------------:|:----------------:|:------------------:|:------------------:|
|              500             |        0.02       |          25         |       64795      |        24777       |         10         |
|              500             |        0.02       |          50         |       63483      |        24777       |         10         |

Unsure if 25 vs 50 bp step sizes are better, but either way I still see those extensions:

<img width="1155" alt="Screen Shot 2020-02-08 at 3 20 08 PM" src="https://user-images.githubusercontent.com/22335838/74093521-ca1a8f00-4a87-11ea-8533-99bc37caf88d.png">

<img width="1150" alt="Screen Shot 2020-02-08 at 3 20 54 PM" src="https://user-images.githubusercontent.com/22335838/74093520-c981f880-4a87-11ea-93a2-eee9e707da2f.png">

<img width="1151" alt="Screen Shot 2020-02-08 at 3 24 32 PM" src="https://user-images.githubusercontent.com/22335838/74093519-c850cb80-4a87-11ea-9bef-0ece0d1ca306.png">

**Comment by sr320** [comment]
These circled windows are >500bp?

**Comment by yaaminiv** [comment]
> These circled windows are >500bp?

@sr320 Which circled windows? All windows are at least 500 bp.

**Comment by sr320** [comment]
Sorry see https://d.pr/i/WAaNMP
Seems like these are just 1 cpg

**Comment by yaaminiv** [comment]
> Seems like these are just 1 cpg

I think that's just because I took the screenshots while zoomed out:

<img width="1156" alt="Screen Shot 2020-02-08 at 4 16 08 PM" src="https://user-images.githubusercontent.com/22335838/74093960-6b0c4880-4a8e-11ea-8d16-af3c5d3bedc3.png">

<img width="1158" alt="Screen Shot 2020-02-08 at 4 15 38 PM" src="https://user-images.githubusercontent.com/22335838/74093961-6fd0fc80-4a8e-11ea-9a2b-d19f18b2471e.png">

However, I am noticing that some MI are less than 500 bp and I don't know why since I used a 500 bp input...I will probably filter the MI list from the script by length so that no MI is less than 500 bp.

**Comment by yaaminiv** [comment]
I filtered the MI from the script (inputs: 500 bp window, 0.02 mCpG fraction, 25 or 50 bp step size) so now MI are definitely at least 500 bp using this code.

```
!awk '{if ($3-$2 >= 500) { print $1"\t"$2"\t"$3"\t"$4}}' 2020-02-06-Methylation-Islands-500_0.02_50.tab \
> 2020-02-06-Methylation-Islands-500_0.02_50-filtered.tab
```

About ~25000-30000 MI did not meet this criteria. 

| **Initial Window Size (bp)** | **mCpG Fraction** | **Step Size (bp)** | **Number of MI** | **Number of MI after Filtering** | **Max mCpG in MI** | **Min mCpG in MI** |
|:----------------------------:|:-----------------:|:------------------:|:----------------:|:--------------------------------:|:------------------:|:------------------:|
|              500             |        0.02       |         25         |       64795      |               36060              |        24777       |         11         |
|              500             |        0.02       |         50         |       63483      |               37063              |        24777       |         11         |

Looked at resulting MI in IGV:

<img width="1154" alt="Screen Shot 2020-02-08 at 5 11 06 PM" src="https://user-images.githubusercontent.com/22335838/74094446-40be8900-4a96-11ea-8e34-bcceaac1fc54.png">

The [IGV session](https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2019-03-07-IGV-Verification/2020-02-06-Methylation-Island-Verification.xml) is updated with gannet links if you wanted to take a look at it some more @sr320 . Any thoughts on 25 vs 50 bp step sizes?

**Comment by sr320** [comment]
either seem fine - maybe just go with 50
