### ISSUE TITLE
Find overlapping genes with DML for C. gigas and C. virginica

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#838]
In [this notebook](https://github.com/RobertsLab/project-gigas-oa-meth/blob/master/notebooks/2019-09-15-DML-Analysis.ipynb), I'm trying to identify genes with DML that are present in *C. gigas* and *C. virginica* DML lists:

- [Annotated *C. gigas* DML](https://github.com/RobertsLab/project-gigas-oa-meth/blob/master/analyses/2019-09-15-DML-Analysis/DML-Gene-annot.tab)
- [Annotated *C. virginica* DML](https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2018-12-02-Gene-Enrichment-Analysis/2019-06-20-DML-Gene-Annotation.tab)

I isolated the columns with gene products and tried partially matching columns with eachother. However, I don't think the partial match code I used is robust, since switching the order of the files gives me different outputs:

![Screen Shot 2020-02-12 at 10 13 41 AM](https://user-images.githubusercontent.com/22335838/74363891-5971bc00-4d80-11ea-8378-3e8e2d07a8e0.png)

![Screen Shot 2020-02-12 at 10 14 11 AM](https://user-images.githubusercontent.com/22335838/74363920-6b535f00-4d80-11ea-91e7-396caeb4aeed.png)

## **Is there a better way to try and find commonalities between these two files? I am trying to eventually match to GOSlim terms and characterize these overlaps.**

**Comment by kubu4** [comment]
Personally, I'd work off of the SwissProt IDs, since it's much simpler string to use for matching.

Also, can you please describe what the `awk` command is supposed to be doing? I don't understand how it allows for partial matches.

Finally, I'd probably do something like:

```shell
cut -f1 <input> | sort | uniq --count
```

Do that for each file and get a count of each unique SwissProt ID and then compare? Not sure how many rows you'd be dealing with.

for each file and the

**Comment by yaaminiv** [comment]
@kubu4 I got the `awk` command from [this link](https://stackoverflow.com/questions/32105362/compare-2-files-and-show-only-lines-with-partial-matches) but I don't really understand the code myself...

> I'd work off of the SwissProt IDs, since it's a much simpler string to use for matching.

That makes more sense.

> Do that for each file and get a count of each unique SwissProt ID and then compare? Not sure how many rows you'd be dealing with.

There's a fair amount of rows, but I could theoretically perform a `join` to only get rows (SwissProt IDs) that are common between both *C. gigas* and *C. virginica*, right?

**Comment by kubu4** [comment]
You could use the `diff` command, like so:

```shell
diff <(cut -f1 <input_1> | sort | uniq) <(cut -f1 <input_2> | sort | uniq)
```

This will show you the difference between the two files.

**Comment by kubu4** [comment]
Or, yes, you could join the files!

**Comment by yaaminiv** [comment]
> This will show you the difference between the two files.

Could you explain a little more how `diff` works? Would the output be all SwissProt IDs that are _different_ between the two files, or those that are the _same_ between the files?

**Comment by yaaminiv** [comment]
> You could use the diff command

@kubu4 To clarify: would I use diff after getting counts for each SwissProt ID, or would I just use `diff` to find common IDs between both files?

**Comment by yaaminiv** [comment]
Decided to just `join` using SwissProt IDs!

![Screen Shot 2020-02-12 at 1 27 52 PM](https://user-images.githubusercontent.com/22335838/74378804-79fb3f80-4d9b-11ea-856e-14a824928b12.png)
