### ISSUE TITLE
Determine primers to proceed with for the Repro. Dev. qPCR assay

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#839]
@kaitlynrm tested primers for detecting reproductive development stage in geoduck samples and got amplification for almost all (great job!)! See her post [here](https://wp.me/p1QK1L-1hT).

Since RPL5 and TIF3s6B primer pairs give the most robust amplification for the housekeeping genes, I think we should go with those two.

For the reproductive development genes, it seems like APLP, NFIP, GSK3B, and SPTN1 primer pairs give the most robust amplification so go with those 4 on the known samples. 

That would potentially be a total of 6 qPCR reactions per sample and if 2uL sample per reaction is enough to reproduce @kaitlynrm's qPCR results, we'd need a total 12uL cDNA per sample.

@kaitlynrm is this possible? 

Does anyone have any other thoughts or input on this?

**Comment by kaitlynrm** [comment]
Yes! I made enough cDNA for several known samples (in calculations table) and believe I have enough to do a qPCR with all those primers!

**Comment by shellytrigg** [comment]
@kaitlynrm great!

**Comment by shellytrigg** [comment]
@kubu4 can we meet to revisit kaitlyn's results and confirm which primers are the best ones to proceed with or if we should design different primers?

**Comment by shellytrigg** [comment]
I also think that is the case. I can create a new issue for qPCR on NTCs with the 6 primer pairs listed above and probably makes sense to have one positive control (like the pooled cDNA) too? Also, should we order more qPCR reagents for this?

**Comment by sr320** [comment]
Should have plenty of qpcr reagents

**Comment by shellytrigg** [comment]
going with APLP for repro dev. target and TIF3s8-1 for expression control.

Primers are specific to targets: https://github.com/RobertsLab/resources/issues/974

Primers performed well with NTC and positive control: 
- https://github.com/RobertsLab/resources/issues/864
- https://github.com/RobertsLab/resources/issues/970
