### ISSUE TITLE
R GSEABase - Way to view GO terms mapped to GOslims?

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#842]
Using the GSEABase package in R is an easy way to map a list of GO terms to GOslims. However, I don't see a way to view which of the provided GO terms gets mapped to each of the GOslims.

What I _really_ want to do is to identify the _genes_ mapped to the GOslims. Maybe this functionality exists in the GSEABase package if I provided it with a more comprehensive gene set which has the gene IDs and their corresponding GO terms?

I've posted some example code below.

The most relevant part of the code is this part:

```R
 ## Map GO terms to GOslims and select Biological Processes group
  slims <- goSlim(myCollection, slim, "BP", verbose = TRUE)
```

This performs the mapping, but doesn't seem to have an "intermediate" file/object/dataframe that one can inspect. Instead, it just spits out the output (truncated to use as an example):

| Goslim     | Count | Percent           | Term                                   |
|------------|-------|-------------------|----------------------------------------|
| GO:0000003 | 1     | 0.515463917525773 | reproduction                           |
| GO:0000278 | 2     | 1.03092783505155  | mitotic cell cycle                     |
| GO:0000902 | 0     | 0                 | cell morphogenesis                     |
| GO:0002376 | 0     | 0                 | immune system process                  |
| GO:0003013 | 0     | 0                 | circulatory system process             |
| GO:0005975 | 0     | 0                 | carbohydrate metabolic process         |
| GO:0006091 | 0     | 0                 | generation of precursor metabolites... |
| GO:0006259 | 1     | 0.515463917525773 | DNA metabolic process                  |
| GO:0006397 | 0     | 0                 | mRNA processing                        |
| GO:0006399 | 0     | 0                 | tRNA metabolic process                 |
| GO:0006412 | 0     | 0                 | translation                            |
| GO:0006457 | 0     | 0                 | protein folding                        |
| GO:0006464 | 3     | 1.54639175257732  | cellular protein modification proce... |
| GO:0006520 | 0     | 0                 | cellular amino acid metabolic proce... |
| GO:0006605 | 0     | 0                 | protein targeting                      |
| GO:0006629 | 0     | 0                 | lipid metabolic process                |
| GO:0006790 | 0     | 0                 | sulfur compound metabolic process      |
| GO:0006810 | 0     | 0                 | transport                              |
| GO:0006913 | 0     | 0                 | nucleocytoplasmic transport            |
| GO:0006914 | 0     | 0                 | autophagy                              |
| GO:0006950 | 2     | 1.03092783505155  | response to stress                     |
| GO:0007005 | 0     | 0                 | mitochondrion organization             |
| GO:0007009 | 0     | 0                 | plasma membrane organization           |
| GO:0007010 | 0     | 0                 | cytoskeleton organization              |
| GO:0007034 | 0     | 0                 | vacuolar transport                     |
| GO:0007049 | 6     | 3.09278350515464  | cell cycle                             |
| GO:0007059 | 0     | 0                 | chromosome segregation                 |
| GO:0007155 | 2     | 1.03092783505155  | cell adhesion                          |
| GO:0007165 | 7     | 3.60824742268041  | signal transduction                    |
| GO:0007267 | 0     | 0                 | cell-cell signaling                    |
| GO:0007568 | 0     | 0                 | aging                                  |
| GO:0008150 | 118   | 60.8247422680412  | biological_process                     |

Does anyone have any experience with this package and/or ideas on how to see which GO terms get mapped to each of the GOslims? I know we have our "tried and true" method of using that tab-delimited GO_goslim file that uses joins and whatnot, but this package just seems so much easier and provides a nice summary table, to boot.

---

Code below is from this R project:

- [20200207_cbai_DEG_GO-GOslims
](https://github.com/RobertsLab/code/tree/master/r_projects/sam/20200207_cbai_DEG_GO-GOslims)

```R
library(GSEABase)
library(tidyverse)

### Download files
download.file(url = "https://gannet.fish.washington.edu/Atumefaciens/20200207_cbai_DEG/infected-vs-uninfected/edgeR.2317.dir/salmon.gene.counts.matrix.infected_vs_uninfected.edgeR.DE_results.P0.05_C1.infected-UP.subset.GOseq.enriched",
              destfile = "./data/salmon.gene.counts.matrix.infected_vs_uninfected.edgeR.DE_results.P0.05_C1.infected-UP.subset.GOseq.enriched")
download.file(url = "https://gannet.fish.washington.edu/Atumefaciens/20200207_cbai_DEG/infected-vs-uninfected/edgeR.2317.dir/salmon.gene.counts.matrix.infected_vs_uninfected.edgeR.DE_results.P0.05_C1.infected-UP.subset.GOseq.depleted",
              destfile = "./data/salmon.gene.counts.matrix.infected_vs_uninfected.edgeR.DE_results.P0.05_C1.infected-UP.subset.GOseq.depleted")
download.file(url = "https://gannet.fish.washington.edu/Atumefaciens/20200207_cbai_DEG/infected-vs-uninfected/edgeR.2317.dir/salmon.gene.counts.matrix.infected_vs_uninfected.edgeR.DE_results.P0.05_C1.uninfected-UP.subset.GOseq.enriched",
              destfile = "./data/salmon.gene.counts.matrix.infected_vs_uninfected.edgeR.DE_results.P0.05_C1.uninfected-UP.subset.GOseq.enriched")
download.file(url = "https://gannet.fish.washington.edu/Atumefaciens/20200207_cbai_DEG/infected-vs-uninfected/edgeR.2317.dir/salmon.gene.counts.matrix.infected_vs_uninfected.edgeR.DE_results.P0.05_C1.uninfected-UP.subset.GOseq.depleted",
              destfile = "./data/salmon.gene.counts.matrix.infected_vs_uninfected.edgeR.DE_results.P0.05_C1.uninfected-UP.subset.GOseq.depleted")

### Create list of files
goseq_files <- list.files(path = "./data",
                         pattern = "\\.GOseq.[de]",
                         full.names = TRUE)

### Set output filename suffix
output_suffix=("GOslims.csv")

### Strip path from goseq files
goseq_filename <- basename(goseq_files)



for (item in goseq_files) {
  
  ## Get max number of fields
  # Needed to handle reading in file with different number of columns in each row
  max_fields <- max(count.fields(item, sep = "\t"))
  
  ## Read in tab-delimited GOseq file
  # Use "max_fields" to populate all columns with a sequentially numbered header
  go_seqs <- read.table(item,
                        sep = "\t",
                        header = TRUE,
                        col.names = paste0("V",seq_len(max_fields)),
                        fill = TRUE)
  
  ## Grab just the individual GO terms from the "category" column)
  goterms <- as.character(go_seqs$V1)
  
  ### Use GSEA to map GO terms to GOslims
  
  ## Store goterms as GSEA object
  myCollection <- GOCollection(goterms)
  
  ## Use generic GOslim file to create a GOslim collection
  
  # I downloaded goslim_generic.obo from http://geneontology.org/docs/go-subset-guide/
  # then i moved it to the R library for GSEABase in the extdata folder
  # in addition to using the command here - I think they're both required.
  slim <- getOBOCollection("./data/goslim_generic.obo")
  
  ## Map GO terms to GOslims and select Biological Processes group
  slims <- goSlim(myCollection, slim, "BP", verbose = TRUE)
  
  
  ### Prep output file naming structure
  
  ## Split filenames on periods
  ## Creates a list
  split_filename <- strsplit(item, ".", fixed = TRUE)

  ## Slice split_filename list from position 9 to the last position of the list
  ## Paste these together using a period
  goseq_filename_split <-paste(split_filename[[1]][9:lengths(split_filename)], collapse = ".")
  
  ## Paste elements together to form output filename
  outfilename <- paste(goseq_filename_split, output_suffix, collapse = ".", sep = ".")
  
  # Set output file destination and name
  outfile_dest <- file.path("./analyses/", outfilename)
  
  ## Write output file
  # write.csv(slims, file = outfile_dest, quote = FALSE)
  
  
}
```

EDITED: Added link to R project

**Comment by kubu4** [comment]
Poking around in the GSEABase code, I've found this file:

- [https://github.com/Bioconductor/GSEABase/blob/master/R/methods-OBOCollection.R](https://github.com/Bioconductor/GSEABase/blob/master/R/methods-OBOCollection.R)

Lines 233 - 278 seem to have the commands for mapping GO terms to GOslims.

Anyone know how to view any of the intermediate stuff generated here when running the package?

**Comment by shellytrigg** [comment]
@kubu4 what if you make a two column data frame with gene and GO term. If a gene has multiple GO terms it will be listed multiple times for each different GO term. Then run GSEAbase on each line of the data frame? That should give you the GO Slims for each GO term

**Comment by kubu4** [comment]
@shellytrigg I was hoping you'd chime in! I think we discussed exactly this before, but I couldn't remember what you had proposed. 

This would definitely work, but isn't much different than the lab's current approach to using that GO_goslim tab-delimited file (if I'm remembering correctly).

The commands for the R package are just so nice and tidy, and generate just a single output.

Regardless, I'll play around with that idea and see what I can come up with. I guess it'd go something like this:

1. Make an input file with a row for each GO term for each gene.

2. Run GSEABase on each row of input file. (Would anyone happen to have some example code for this? Quick internet search doesn't spit out any obvious answers).

3. Insert column with gene ID into each GSEABase output file.

4. Concatenate all GSEABase output files into single file for easier viewing.

**Comment by shellytrigg** [comment]
The difference is there are more GO slims in the goslim_generic.obo file (71 slim terms) than in the GO_goslim tab-delimited file (38 slim terms). So I find the GO slims from the generic GO slim.obo file to be a little more descriptive. Below is some example code for running GSEAbase on a list of genes (protein IDs in this case) with a row for each GO term for each gene (called "prot_GO"). Rather than performing the GO slim on each GO term, this code performs it on all terms for each protein, but the code could be altered to perform on each GO term.

#make an empty data frame that will get propagated by for loop
prot_slims <- data.frame()
#for each line in input file
for (i in 1:length(unique(prot_GO$protein_ID))){
   #create an object to store GO terms for each protein
   GO_IDs <- prot_GO[which(prot_GO$protein_ID == unique(prot_GO$protein_ID)[i]), "GO"]
  #convert GO_IDs object into GSEAbase GOCollection
   collection_clade <- GOCollection(GO_IDs)
  #read in goslim_generic.obo file
   fl <- system.file("extdata", "goslim_generic.obo", package="GSEABase")
  #create GSEAbase GO collection object from the goslim_generic.obo object
   slim <- getOBOCollection(fl)
  #save GSEA goSlim output as a data frame (for biological processes; can change this to molec. function or cell component)
   slims_map <- data.frame(goSlim(collection_clade, slim, "BP"))
   #remove lines where GO slim count is 0; in other words remove slim terms that no GO term mapped to
   slims_map <- slims_map[which(slims_map$Count !=0),]
   #add protein ID to the goSlim data frame
   slims_map$protein_ID <- unique(prot_GO$protein_ID)[i]
   #bind each GSEAbase goSlim data frame to the master data frame
   prot_slims <- rbind(prot_slims, slims_map)
}

**Comment by kubu4** [comment]
I posted this issue on the Bioconductor forums and actually got a response! And, the response is written up in steps, with explanations! Heck, the poster even wrote a function to use to simplify things even further!

Check it out:

https://support.bioconductor.org/p/128407/#128409

**Comment by kubu4** [comment]
Thanks to @shellytrigg for her amazing assistance with improving the above code to make the output writeable to csv!!

Here's an abridged version to what that guy posted in the Bioconductor response with the necessary modifications to make the output writeable to csv:

```R
library(GSEABase)
library(tidyverse)


myIds <- c("GO:0016564", "GO:0003677", "GO:0004345", "GO:0008265")
myCollection <- GOCollection(myIds)
fl <- system.file("extdata", "goslim_plant.obo", package="GSEABase")
slim <- getOBOCollection(fl)

# Sets ontology category to "Molecular Function". Use "BP" for "Biological Process"
slimdf <- goSlim(myCollection, slim, ontology = "MF")

# This should match the ontology used above.
# E.g. GOBPOFFSPRING or GOCCOFFSPRING
GO.db::GOMFOFFSPRING


mappedIds <-
  function(df, collection, OFFSPRING)
  {
    map <- as.list(OFFSPRING[rownames(df)])
    mapped <- lapply(map, intersect, ids(collection))
    df[["go_terms"]] <- vapply(unname(mapped), paste, collapse = ";", character(1L))
    df
  }

slimdf <- mappedIds(slimdf, myCollection, GOMFOFFSPRING)

write.csv(slimdf, file = "gsea.csv", quote = FALSE)
```

**Comment by kubu4** [comment]
BTW, the code above should produce a table like so:

| Goslim     | Count | Percent          | Term                                   | go_terms                         |
|------------|-------|------------------|----------------------------------------|----------------------------------|
| GO:0000166 | 0     | 0                | nucleotide binding                     |                                  |
| GO:0003674 | 3     | 33.3333333333333 | molecular_function                     | GO:0003677;GO:0004345;GO:0008265 |
| GO:0003676 | 1     | 11.1111111111111 | nucleic acid binding                   | GO:0003677                       |
| GO:0003677 | 1     | 11.1111111111111 | DNA binding                            |                                  |
| GO:0003682 | 0     | 0                | chromatin binding                      |                                  |
| GO:0003700 | 0     | 0                | DNA binding transcription factor ac... |                                  |
| GO:0003723 | 0     | 0                | RNA binding                            |                                  |
| GO:0003774 | 0     | 0                | motor activity                         |                                  |
| GO:0003824 | 2     | 22.2222222222222 | catalytic activity                     | GO:0004345;GO:0008265            |
| GO:0004518 | 0     | 0                | nuclease activity                      |                                  |
| GO:0004871 | 0     | 0                | signal transducer activity             |                                  |
| GO:0004872 | 0     | 0                | receptor activity                      |                                  |
| GO:0005102 | 0     | 0                | receptor binding                       |                                  |
| GO:0005198 | 0     | 0                | structural molecule activity           |                                  |
| GO:0005215 | 0     | 0                | transporter activity                   |                                  |
| GO:0005488 | 1     | 11.1111111111111 | binding                                | GO:0003677                       |
| GO:0005515 | 0     | 0                | protein binding                        |                                  |
| GO:0008135 | 0     | 0                | translation factor activity            | RNA bi...                        |
| GO:0008289 | 0     | 0                | lipid binding                          |                                  |
| GO:0016301 | 0     | 0                | kinase activity                        |                                  |
| GO:0016740 | 1     | 11.1111111111111 | transferase activity                   | GO:0008265                       |
| GO:0016787 | 0     | 0                | hydrolase activity                     |                                  |
| GO:0019825 | 0     | 0                | oxygen binding                         |                                  |
| GO:0030234 | 0     | 0                | enzyme regulator activity              |                                  |
| GO:0030246 | 0     | 0                | carbohydrate binding                   |                                  |
| GO:0045182 | 0     | 0                | translation regulator activity         |                                  |
