### ISSUE TITLE
installing python package

### ISSUE THREAD

**Issue by nclowell** [RobertsLab/resources#845]
I would like to run a model on mox that requires some python packages. All but one package are available in the python 3.6.3 module available to all users, and to the best of my knowledge one package needs to be installed (simuPOP). 

I'd like to know what the most kosher way of doing this is. My plan was to install simuPOP in a conda environment, and then load the python 3.6.3 module and activate the simuPOP conda environment before running the model. From talking to @kubu4 I gathered that I can install with conda except that programs will install to the user home directory, which has limited storage space. I just tried doing this from a build node and got a permission error (see below). Not sure what I did wrong! Thoughts? @kubu4 @sr320 

Thank you!!

```
[nclowell@n2232 bin]$ ./conda create -n simupop_env
Collecting package metadata (current_repodata.json): done
Solving environment: done

NotWritableError: The current user does not have write permissions to a required path.
  path: /gscratch/srlab/programs/miniconda3/pkgs/cache/9e0f62c3.json
  uid: 577308
  gid: 415510

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 577308:415510 /gscratch/srlab/programs/miniconda3/pkgs/cache/9e0f62c3.json

In general, it's not advisable to use 'sudo conda'.
```

**Comment by kubu4** [comment]
> My plan was to install simuPOP in a conda environment, and then load the python 3.6.3 module and activate the simuPOP conda environment

I'm not sure you can do this. When you activate a conda environment or the Mox Python module, you're telling the computer which Python it should use _and_ any corresponding packages that are installed. So, I think it's one or the other; you can't mix and match them.

Regardless, I just ran your command above and now I think you can use it? Please try and let me know.

```shell
[samwhite@n2232 bin]$ ./conda create -n simupop_env
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.12
  latest version: 4.8.2

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /gscratch/srlab/programs/miniconda3/envs/simupop_env



Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate simupop_env
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

**Comment by nclowell** [comment]
Thanks for the feedback about not being able to both load a module and activate the conda environment. Not sure what the smartest way forward is. Assuming I get conda to work, I can try installing all the packages into this environment. I've never used the setup.py install command with the --user option (e.g. python setup.py install --user) -- do you think that's more straightforward?

I tried activating the conda environment and got this error:

```
[nclowell@n2232 bin]$ ./conda activate simupop_env

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```

I checked to make sure the conda env is there and it is!

```

[nclowell@n2232 bin]$ ./conda env list
# conda environments:
#
base                  *  /gscratch/srlab/programs/miniconda3
simupop_env              /gscratch/srlab/programs/miniconda3/envs/simupop_env
```

Does it have anything to do with trying to use conda from the build node?

**Comment by nclowell** [comment]
And second question - does it make sense to install simuPOP not in a new environment but just to the base environment? Would I then only have to load the python 3.6.3 module?

Thank you!!

**Comment by kubu4** [comment]
> I've never used the setup.py install command with the --user option (e.g. python setup.py install --user) -- do you think that's more straightforward?

Yes. This is how I would proceed - it usually is the easiest method.

Don't forget to load the Mox Python module first.

In regards to

> I tried activating the conda environment and got this error:

Did you try the instructions that the error message provided? If not, give that a go:

```conda init bash```

Restart your shell (i.e. log out of Mox entirely and then log back in) and then try:

```./conda activate simupop_env```

**Comment by nclowell** [comment]
I tried installing with ``python setup.py install --user`` and got an error. The entire output is attached here, but I put some of the warnings below. Any idea what's happening?

[install_simupop_error_output.txt](https://github.com/RobertsLab/resources/files/4258687/install_simupop_error_output.txt)

```
[nclowell@n2232 simuPOP-1.1.10.9]$ python setup.py install --user
Downloading boost C++ library 1.70.0 ....................................................................................................
Extracting 16039 files
Testing tr1 support: no
Testing c++ library: libstdc++
Building static libraries
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
```
...
```
running install
running bdist_egg
running egg_info
writing simuPOP.egg-info/PKG-INFO
writing dependency_links to simuPOP.egg-info/dependency_links.txt
writing requirements to simuPOP.egg-info/requires.txt
writing top-level names to simuPOP.egg-info/top_level.txt
reading manifest file 'simuPOP.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README'
warning: no files found matching 'TODO'
warning: no files found matching 'src/plotter.py'
warning: no files found matching 'test/test_18_plotter.py'
warning: no files found matching 'development/win32/stdint.h'
warning: no files found matching '*.h' under directory 'development/win32/zlib-1.2.3'
warning: no files found matching '*.c' under directory 'development/win32/zlib-1.2.3'
writing manifest file 'simuPOP.egg-info/SOURCES.txt'
```
...
```
src/customizedTypes.c:1488:1: warning: missing initializer for member ‘_typeobject::tp_version_tag’ [-Wmissing-field-initializers]
src/customizedTypes.c:1488:1: warning: missing initializer for member ‘_typeobject::tp_finalize’ [-Wmissing-field-initializers]
srun: Force Terminated job 1970009
srun: Job step aborted: Waiting up to 12 seconds for job step to finish.
srun: error: n2232: task 0: Killed
```

Re: the conda issue, I tried running ``conda init bash``, which appeared to work, then closed out of the session entirely, relogged into mox, and tried to run ``conda activate simupop_env``, but I got the same error.

```
(base) [nclowell@mox2 bin]$ ./conda activate simupop_env

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```

Might give up on conda, at least while I pursue the setup.py install? 

Thanks!

**Comment by nclowell** [comment]
I don't know if this is helpful, but when I just reran ``conda init bash`` this is the output:

```
(base) [nclowell@mox2 bin]$ ./conda init bash
no change     /gscratch/srlab/programs/miniconda3/condabin/conda
no change     /gscratch/srlab/programs/miniconda3/bin/conda
no change     /gscratch/srlab/programs/miniconda3/bin/conda-env
no change     /gscratch/srlab/programs/miniconda3/bin/activate
no change     /gscratch/srlab/programs/miniconda3/bin/deactivate
no change     /gscratch/srlab/programs/miniconda3/etc/profile.d/conda.sh
no change     /gscratch/srlab/programs/miniconda3/etc/fish/conf.d/conda.fish
no change     /gscratch/srlab/programs/miniconda3/shell/condabin/Conda.psm1
no change     /gscratch/srlab/programs/miniconda3/shell/condabin/conda-hook.ps1
no change     /gscratch/srlab/programs/miniconda3/lib/python3.7/site-packages/xontrib/conda.xsh
no change     /gscratch/srlab/programs/miniconda3/etc/profile.d/conda.csh
no change     /usr/lusers/nclowell/.bashrc
No action taken.
```

**Comment by kubu4** [comment]
I've installed simuPOP via Anaconda.

Please see if you can start using it. Try the following (you can run these commands from anywhere):

1. Activate Anaconda:

```shell
/gscratch/srlab/programs/miniconda3/bin/conda activate
```

- This activates the "base" Anaconda environment (whatever that actually means...)
- This should switch your terminal prompt to look like this: `(base) [nclowell@mox2 bin]$`

2. Check that you're now using the Anaconda Python:

```shell
which python
```

- Output should be: `/gscratch/srlab/programs/miniconda3/bin/python`

3. Launch Python

```shell
python
```

- Output should be:

  - `Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux`

- Shell prompt should change to: `>>>`

4. Try to import simuPOP:

```python
import simuPOP as sp
```

- Output should be: 

```
simuPOP Version 1.1.10.9 : Copyright (c) 2004-2016 Bo Peng
Revision 4603 (Nov  7 2019) for Python 3.7.3 (64bit, 0thread)
Random Number Generator is set to mt19937 with random seed 0x59f89cbea7cd18c9.
This is the standard short allele version with 256 maximum allelic states.
For more information, please visit http://simupop.sourceforge.net,
or email simupop-list@lists.sourceforge.net (subscription required).
```

**Comment by nclowell** [comment]
Thank you so much - it's all working fine on my end.

You are a GODSEND.

**Comment by nclowell** [comment]
I closed the issue too soon! (No worries, you are still a godsend)

Yes simuPOP is installed and accessible from the base conda environment on my end. However, the base conda environment doesn't have all the packages I need for my model, and as you suggested would happen, loading the python 3.6.3 module and hoping to also access simuPOP from the base conda environment didn't work. The remaining packages are: numpy, matplotlib, os, subprocess, and scipy. Is the best path forward for me to install these to the base environment with conda?

**Comment by nclowell** [comment]
I lied - os and subprocess are on there. It looks like numpy, maptlotlib, and scipy are the only ones that aren't.

**Comment by nclowell** [comment]
Also - how did you get around the permission error that I see when I try to conda install things?

**Comment by kubu4** [comment]
Edit your `~.bashrc` file to look like mine (this part should be at the end of the file):

```shell
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/gscratch/srlab/programs/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/gscratch/srlab/programs/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/gscratch/srlab/programs/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/gscratch/srlab/programs/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```

After you've done that, exit Mox completely, and then login back in. Verify that you're using `anaconda3` by typing:

```which conda```

The output should be:

`/gscratch/srlab/programs/anaconda3/condabin/conda`

This resolves the error you were getting earlier (`CommandNotFoundError: Your shell has not been properly configured ...`). I believe the error was triggered by trying to use two different installations of Anaconda: miniconda and Anaconda. I'm guessing your `~.bashrc` was configured for miniconda, but you were trying to run Anaconda (they're the same, it's just that miniconda comes with almost no default packages installed, so it uses less space on the hard drive).

Now, you should be able to run `simuPOP` following the instructions before, as Anaconda comes with `numpy`, `scipy`, and `matplotlib` installed by default (plus, I verified that they were indeed installed).

Sorry for all of this!

**Comment by kubu4** [comment]
> Also - how did you get around the permission error that I see when I try to conda install things?

I'm listed the owner for all the miniconda files/folders, so that's how I was able proceed. :smiley:

**Comment by nclowell** [comment]
That all worked! Thanks so much 🙏

> Sorry for all of this!

Lol do not be sorry for helping me SO MUCH
