### ISSUE TITLE
SMEA postdoc - found Hemat. eDNA - asking about assay recommendations

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#846]
SMEA postdoc reached out to me. Asking for rec.s of more specific assay design for _Hematodinium_. Message snippet below: 

> We recently did a large eDNA metabarcoding study and found a single sequence from the genus Hematodinium in >10% of our 63 samples from the Hood Canal. 
The locus we used for metabarcoding doesn't help us get resolution below the level of genus (or verify that we are really seeing Hematodinium in the first place), and I was wondering if you had a more specific assay design (sanger sequencing primers and/or qPCR primers/probe) that I could order and use to try to verify and further classify Hematodinium in these samples.

**Comment by sr320** [comment]
Would have to know all Hemat taxa in sample - we really do not have that info
