### ISSUE TITLE
Collaborating on Code

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#849]
Is there a way multiple people can code on an online document? Like a Google doc version of Jupyter?

**Comment by kubu4** [comment]
In real-time?

Git/GitHub is designed for collaborative coding. Generally required the use of branches to minimize conflicts. However, it's not real-time and you can't see what people are typing.

Here's a list of real-time collaborative tools (looks like Atom has a plugin that will allow that feature):

https://webdesign.tutsplus.com/articles/real-time-code-collaboration-tools-for-developers--cms-30494

**Comment by sr320** [comment]
Sorry - yes real-time

**Comment by sr320** [comment]
How about this
https://colab.research.google.com/drive/1VAYTPN40O-1grkDYBz8rel0zTrsAM6Kb

**Comment by sr320** [comment]
And HackMD might have some use cases
