### ISSUE TITLE
Geoduck genome paper: reconcile DMGs and DMRs

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#852]
@hputnam and I need to compare our DMGs and DMRs to find if we've identified any that are overlapping. We also need to compare our GO analyses. Determine what gene(s) are driving enrichment.

**Comment by sr320** [comment]
Has this been done?

**Comment by hputnam** [comment]
Shelly and I chatted on Friday. We think this is apples and oranges. The working plan now is A) genome results, B) DMR result heatmaps and categorical test of locations of DMRs in genome, and C) DMG results with functional enrichment test. Thoughts?

**Comment by sr320** [comment]
Sounds good!
