### ISSUE TITLE
Run bioinformatics on Trim Galore samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#854]

**Comment by shellytrigg** [comment]
currently pending (job # 2044625). Script is here: [https://gannet.fish.washington.edu/metacarcinus/mox_jobs/20200309_TrimGfroger.sh](https://gannet.fish.washington.edu/metacarcinus/mox_jobs/20200309_TrimGfroger.sh). Also added it to [Meth_Compare_Pipeline.md](https://github.com/hputnam/Meth_Compare/blob/master/analyses/Meth_Compare_Pipeline.md).

**Comment by sr320** [comment]
meant to put this in MethCompare Repo
