### ISSUE TITLE
Identify a Mounted Camera that would work with Scope

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#856]
photo of mount 

![IMG_2845](https://user-images.githubusercontent.com/4442039/76428991-a2129a00-636b-11ea-91fd-be7fd47cf817.jpg)

**Comment by kubu4** [comment]
Is this from the Friedman Lab? If yes, they have a camera that will fit. We could borrow the camera. Alternatively, we can go look at the camera model they have that fits that mount. However, that mount is designed for a camera that's well over 10yrs old. Looking at the website listed on the mount, they don't even list this mount as an available option any more. Meaning, it's unlikely we'll be able to obtain a camera (unless we borrow from the Friedman Lab) that will fit that mount.

**Comment by sr320** [comment]
It is indeed, can you confirm we can borrow it and get it hooked up for Mac to use?

**Comment by kubu4** [comment]
A few things:

1. Carolyn loaned it out and it hasn't been returned (and, likely never will).

2. Camera that fits mount is a Nikon Cool Pix. Carolyn indicated that SAFS used to have one that can be checked out.

3. She also asked why not just use a phone adapter? Take reference pic of micrometer and then good to go.

**Comment by sr320** [comment]
@mgavery Would an iphone adapter work?
