### ISSUE TITLE
Align newly trimmed geoduck reads

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#860]
@sr320 newly trimmed reads are on mox here:
/gscratch/scrubbed/strigg/analyses/20200319

reads with specified adapters trimmed:
- /gscratch/scrubbed/strigg/analyses/20200319/specify_a/EPI-167_S10_L002_R1_001_val_1.fq.gz 
- /gscratch/scrubbed/strigg/analyses/20200319/specify_a/EPI-167_S10_L002_R2_001_val_2.fq.gz 

reads with TrimGalore! defaults adapter trimmed:
- /gscratch/scrubbed/strigg/analyses/20200319/EPI-167_S10_L002_R1_001_val_1.fq.gz 
- /gscratch/scrubbed/strigg/analyses/20200319/EPI-167_S10_L002_R2_001_val_2.fq.gz 

Can you:
1. align these reads with Bismark to the OFS genome 'Panopea-generosa-v1.0.fa' (I have a bismark genome for this here: /gscratch/srlab/strigg/data/Pgenr/OFS )

2. Deduplicate aligned reads

3. Run bismark methylation extractor on deduplicated alignments and non-deduplicated alignments

4. Sort and index resulting bams for viewing in IGV

**Comment by shellytrigg** [comment]
here is info about the newly trimmed reads:

- 8 bp were clipped off the beginning and end of each read using the following TG parameters:
```
--clip_R1 8 
--clip_R2 8 
--three_prime_clip_R1 8 
--three_prime_clip_R2 8 
```
- adapters were either specified using the illumina sequences provided on page 45 of the Illumina adapter sequences document or were identified using the default settings
```
#specifying adapters
--adapter AGATCGGAAGAGCACACGTCTGAAC 
--adapter2 AGATCGGAAGAGCGTCGTGTAGGGA 

#default settings did not include the --adapter and --adapter2 options
```

- [slurm-2358892.out](https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20200319/slurm-2358892.out)
- mox script [20200319_TG_EPI-Test.sh](https://gannet.fish.washington.edu/metacarcinus/mox_jobs/20200319_TG_EPI-Test.sh)

**Comment by sr320** [comment]
@shellytrigg can you get us before and after fastqc?

**Comment by shellytrigg** [comment]
@sr320 here are the links to the fastqc files:

BEFORE (raw data):
- [EPI-167 R1](http://owl.fish.washington.edu/Athaliana/20180516_geoduck_EPI_fastqc/EPI-167_S10_L002_R1_001_fastqc.html)
- [EPI-167 R2](http://owl.fish.washington.edu/Athaliana/20180516_geoduck_EPI_fastqc/EPI-167_S10_L002_R2_001_fastqc.html)

AFTER trimming with adapter specified):
- [EPI-167 R1](https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20200319/specify_a/EPI-167_S10_L002_R1_001_val_1_fastqc.html)
- [EPI-167 R2](https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20200319/specify_a/EPI-167_S10_L002_R2_001_val_2_fastqc.html)

AFTER trimming with default adapters:
- [EPI-167 R1](https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20200319/EPI-167_S10_L002_R1_001_val_1_fastqc.html)
- [EPI-167 R2](https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20200319/EPI-167_S10_L002_R2_001_val_2_fastqc.html)

**Comment by sr320** [comment]
Aligned -  Here is IGV session `https://raw.githubusercontent.com/sr320/nb-2020/master/P_generosa/igv/032020-igv_session.xml`

**Comment by sr320** [comment]
And here is a nb post  https://sr320.github.io/fds/

**Comment by shellytrigg** [comment]
Trimmed reads are on mox here: /gscratch/scrubbed/strigg/analyses/20200320/TG_FASTQS

- mox script: [https://gannet.fish.washington.edu/metacarcinus/mox_jobs/20200320_TrimGpgnrMeth1.sh](https://gannet.fish.washington.edu/metacarcinus/mox_jobs/20200320_TrimGpgnrMeth1.sh)
- slurm file: [https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20200320/slurm-2386816.out](https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20200320/slurm-2386816.out)
- multiqc for trimming of all samples: [https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20200320/multiqc_report.html](https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20200320/multiqc_report.html)

**Comment by sr320** [comment]
Bismark now running on newly trimmed reads.
job https://github.com/hputnam/Geoduck_Meth/blob/master/code/03-bismark.sh

**Comment by sr320** [comment]
update status: all samples aligned, 10 samples deduplicated..

**Comment by sr320** [comment]
update status: 28 samples have made through to `merged_CpG_evidence.cov` stage

**Comment by sr320** [comment]
Completed. Data uploading to https://gannet.fish.washington.edu/seashell/bu-mox/scrubbed/032120-fds/
