### ISSUE TITLE
Metagenomics Venn diagrams - what did we have in mind?

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#862]
I know we discussed making Venn diagrams of bacterial classes, but I'm not sure what we wanted here.

An individual Venn diagram for each class of bacteria, comparing pH7.1 and pH8.2?

For the record, reads were assigned to 20 different classes of bacteria, across all samples.

**Comment by emmats** [comment]
I think I was curious if there were taxonomic groups that occurred in some samples and not in others.

You do a between-pH comparison of all time points

It might also be interesting to see if there are big shifts between time points

**Comment by kubu4** [comment]
I definitely follow this, but what does a Venn diagram look like with 20 classes trying to intersect between pH treatments?

**Comment by emmats** [comment]
<img width="1001" alt="Screen Shot 2020-03-24 at 3 03 43 PM" src="https://user-images.githubusercontent.com/4564812/77481345-b1b8c680-6de0-11ea-80a1-6cf26db1e9e4.png">
List 1 is all the classes ID'd at pH 7.1
List 2 is all the classes from pH 8.2
If you click on the different parts of the venn diagram you will get a list of the components in that part in the Results box

**Comment by kubu4** [comment]
#### Venn Diagram of Shared Bacterial Classes

![image](https://user-images.githubusercontent.com/4514104/77653942-9a3b2400-6f2d-11ea-80b0-7af761c47274.png)

pH8.2 has one unique class:

- [Verrucomicrobiae](https://en.wikipedia.org/wiki/Verrucomicrobia). Doesn't seem like too much is known about them. These were present in 2/3 of pH8.2 libraries.

pH7.1 has five unique classes:

- [Bacteroidia](https://en.wikipedia.org/wiki/Bacteroidia): Sample MG3 only

- [Saprospiria](http://www.irmng.org/aphia.php?p=taxdetails&id=11908151): Sample MG3 only

- [Sphingobacteriia](https://en.wikipedia.org/wiki/Sphingobacteriia): Sample MG3 only

- [Nitrospinia](https://www.uniprot.org/taxonomy/1293498): Sample MG7 only

- [Bacilli](https://en.wikipedia.org/wiki/Bacilli): Sample MG3 only

Obviously, Sample MG3 skews these results.

---

PCAs of bacterial classes

![image](https://user-images.githubusercontent.com/4514104/77665366-cd38e400-6f3c-11ea-8b5b-e7ff174cdea8.png)





![image](https://user-images.githubusercontent.com/4514104/77665339-c14d2200-6f3c-11ea-8b36-f82b129eb5bb.png)


![image](https://user-images.githubusercontent.com/4514104/77665442-e80b5880-6f3c-11ea-8438-56e8941d23a7.png)

---

@emmats You mentioned comparisons by time points. Possibly interesting (but we don't have any replicates) is that Sample MG3 (the "outlier" in this analysis) is the only Day 6 sample...

Anyway, here's Venn diagram(s) of time point comparisons,

![image](https://user-images.githubusercontent.com/4514104/77666847-b3000580-6f3e-11ea-96f0-18bc726139fc.png)


Day 13 has one unique class:

- [Planctomycetia](https://www.researchgate.net/publication/235943916_Identification_of_Proteins_Likely_To_Be_Involved_in_Morphogenesis_Cell_Division_and_Signal_Transduction_in_Planctomycetes_by_Comparative_Genomics): Only present in 1/2 samples (pH8.2)

Day 17 has one unique class:

- [Nitrospinia](https://www.frontiersin.org/articles/10.3389/fmicb.2013.00027/full): Only present in 1/2 samples. (pH7.1)

**Comment by emmats** [comment]
I agree that lack of replication makes it hard to make any meaningful conclusion, but this is still good to keep in mind. Thanks, Sam!
