### ISSUE TITLE
C. gigas - annotations: linking CGI_# to a gene ID

### ISSUE THREAD

**Issue by mgavery** [RobertsLab/resources#863]
The oyster genome has a gff annotation file with CGI_# as the identifier.  The gtf file has a different set of LOC# and GeneID:#.  Is there a file exists that links a CGI_# with one of the numbers in the gtf?

**Comment by kubu4** [comment]
Can you post links to the files you're looking at?

**Comment by kubu4** [comment]
Basically, I'm trying to find out where the files came from. My guess is that this info might be available in the corresponding GenBank/EMBL "flatfile".

**Comment by mgavery** [comment]
https://ftp.ncbi.nlm.nih.gov/genomes/refseq/invertebrate/Crassostrea_gigas/latest_assembly_versions/GCF_000297895.1_oyster_v9/

**Comment by mgavery** [comment]
The gtf is on the above link (NCBI page)

The gff CGI numbers are here: https://eagle.fish.washington.edu/trilobite/Crassostrea_gigas_v9_tracks/Cgigas_v9_gene.gff

And also, usefully, these CGI_#s are used in the genome paper (Zhang et al. 2012) 
where they have RNA-Seq over developmental time (supp table 14) - https://www.nature.com/articles/nature11413#Sec9

**Comment by sr320** [comment]
Note there are in theory improved annotations at http://gigaton.sigenae.org/ngspipelines/#!/NGSpipelines/Crassostrea%20gigas%20-%20GIGATON

**Comment by mgavery** [comment]
For background: The single-cell software requires a GTF file for annotating genes.  We used the GTF file (which has annotations) from the NCBI site.  However, this GTF file doesn't have a single gene annotating to vasa, while there are 4 CGI_#s that I can find in the supp file 14 that annotate to vasa.  I can't find the bridge between the files to see which gene is which. I question the GTF, but not sure what to do about that.

**Comment by kubu4** [comment]
I don't think I'm seeing what you're seeing. If I use the GTF and GFF files that are in your NCBI link above, I find the following:

1. No CGI numbers in GFF and GTF.

2. No text matching "vasa" in GFF and GTF.

3. Accession numbers are consistent in GFF and GTF.

I'm inclined to think that @sr320's suggestion that the annotations have been improved hold true to the NCBI entries (last updated in Nov. 2019, based on file timestamps). Thus, there are now consistent accession numbers across the GFF/GTFs. Are you beholden to the C_gigas_v9_gene.gff?

---

![image](https://user-images.githubusercontent.com/4514104/77499265-e2175980-6e0e-11ea-8366-a618d019daff.png)

**Comment by kubu4** [comment]
Yeah, looks like the genome annotations have definitely been updated since that paper was published. I'm also not seeing a way to access the previous accessions.

![image](https://user-images.githubusercontent.com/4514104/77501141-4ee12280-6e14-11ea-9cdf-2c9263ffa7f0.png)

**Comment by mgavery** [comment]
Well dang, thanks for looking at this.  I gotta say though that I find it concerning that there are no genes that annotate to vasa as there lots of papers describing vasa in gigas.  Also a quick search for hsp70 finds a few 'associated proteins', but no hsp70.  Ugh.

**Comment by mgavery** [comment]
For what it's worth: https://metazoa.ensembl.org/Crassostrea_gigas/Info/Annotation/  has an associated FTP site, which still has CGI number.  I don't see these having official annotations within this ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100030/

Which one should I use for the single cell stuff? What do we know about these new annotations?

**Comment by kubu4** [comment]
Running BLASTx using a _D.melanogaster_ vasa transcript against _C.gigas_ in NCBI produces a ton of results:

https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=7PTHPTJH016

The results just aren't annotated with "vasa". They're mostly variations on RNA helicase and/or DEAD-box. That might help.

**Comment by sr320** [comment]
Seems like we should identify the canonical gene set for the species to use in the analysis and we could always annotate ourselves.

**Comment by mgavery** [comment]
https://www.ncbi.nlm.nih.gov/gene/105335166

Thanks for blasting.  I was text searching and not coming up with much.  That was really helpful, thanks.
