### ISSUE TITLE
Compile EMBOSS using git bash 

### ISSUE THREAD

**Issue by SamGurr** [RobertsLab/resources#865]
./configure  led to the same error discussed in the closed issue "Installing EMBOSS on Ubuntu"  and was resolved using ./configure --without-x
However, after configuring the installation, compiling with "make" is unsuccessful with the error message below.
![image](https://user-images.githubusercontent.com/38264911/77580222-fc564380-6eb1-11ea-99f6-a0973bc0edf7.png)

Any ideas? 
Glad to provide any additional information needed. Thank you!

**Comment by kubu4** [comment]
You won't be able to do this with Got Bash. You'll need a proper Linux system. Are you using Windows 10? If yes, you should install the Linux Subsystem for Windows. That will provide you with a full blown Linux OS (Ubuntu) on your computer.

**Comment by SamGurr** [comment]
Downloading and will attempt again, thanks Sam!

**Comment by kubu4** [comment]
Just a heads up. It will help to think of the Linux/Windows thingy as an entirely new computer. It will have its own home directory. You'll want to download/install programs on this "new" computer. You'll have to do so via the command line.

**Comment by SamGurr** [comment]
thanks for your help Sam! An hour of downloads later and I am now able primersearch with Ubuntu
