### ISSUE TITLE
Check 2015 DIA oyster paper methods for clarity

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#867]
@kaitlynrm please read over methods section

provide any edits or suggestions by commenting or suggesting. 

[DIA oyster paper](https://docs.google.com/document/d/1OaYNzlOJr5QibCYt8--GMNGvXlzHPR9_daCkNUVkj-U/edit?usp=sharing)

thanks!

**Comment by kaitlynrm** [comment]
It looks great @grace-ac ! I made a couple minor comments that may or may not matter, but I can definitely see the work you put into!

**Comment by grace-ac** [comment]
thanks so much Kaitlyn! I'll check out your comments :)
