### ISSUE TITLE
Add links to Roberts Lab capstones to new site

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#87]
Please add hyperlinks on titles at https://safscapstone.wordpress.com/past-capstones/
For Roberts lab capstones, to go to papers (found on robertslab.info peoples page).

**Comment by grace-ac** [comment]
Should I edit the way the projects are listed on the wordpress for your students?

For example, Berman's project is currently listed as, "Shrimp polyculture", while his paper is entitled, "A study in hydroponics and aquaculture integration".

**Comment by sr320** [comment]
Yes please, change to "A study in hydroponics and aquaculture integration"

**Comment by grace-ac** [comment]
1. Some names that are listed on the SAFS page are NOT included in your "People" page. I do not have papers for these names to add links to.
    - Seamans 2016
    - Jackson 2014
    - Williamson 2008
    - Lorenz 2008

2. Some names are listed in your "People" page, but NOT on SAFS page. I can add them, but need to know YEAR: 
    - Lexie Miller: hard clam - QPX Virulence factors
    - Amanda Davis:  Effect of 5-azacytidine on Global DNA Methylation.

3. Two papers are not accessible/deleted:
   - Tayag - need permission to access
![tayang](https://user-images.githubusercontent.com/14934314/31401116-b132fa16-ada6-11e7-9437-64fa2c8d8b44.png)

   - Albin - paper has been deleted 
![albin](https://user-images.githubusercontent.com/14934314/31401118-b6018706-ada6-11e7-96b4-271ed78d75ef.png)

4. Three papers that are on gene fish tumblr don't load. 
   - McLemore 
   - Spurr
   - Fulkerson
   - Taplin
This is what the page is stuck on. I left it for 10 minutes or more and it never loaded. 
![tumblr](https://user-images.githubusercontent.com/14934314/31401276-47311606-ada7-11e7-8ddf-574fe86e29de.png)

**Comment by grace-ac** [comment]
Issue with Tayag's paper is fixed.

**Comment by sr320** [comment]
thanks
I am calling it done enough ⛅️
