### ISSUE TITLE
Create CG dinucleotide motif bed files for coral genomes

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#872]
3 genomes (fasta)

https://gannet.fish.washington.edu/seashell/bu-mox/data/froger/Mcap_Genome/Mcap.genome_assembly.fa

https://gannet.fish.washington.edu/seashell/bu-mox/data/froger/C1_Genome/SymbC1.Genome.Scaffolds.fasta

https://gannet.fish.washington.edu/seashell/bu-mox/data/froger/Pact_Genome/Pocillopora_acuta_genome_v1.fasta

--
In the past I think EMBOSS Fuzznuc has worked and is available in Galaxy.
Nice to verify by loading into IGV.

**Comment by kubu4** [comment]
We have the EMBOSS suite installed on Emu/Roadrunner. You could run on there with Jupyter Notebook to keep track of everything.

**Comment by kubu4** [comment]
Here's a notebook entry on what I've done previously:

https://robertslab.github.io/sams-notebook/2019/08/21/Data-Wrangling-Create-a-CpG-GFF-from-Pgenerosa_v074-using-EMBOSS-fuzznuc-on-Swoose.html

**Comment by sr320** [comment]
Thanks - and GFF format is just fine. (and likely what I meant to request)

**Comment by sr320** [comment]
Was able to get it done via Galaxy 

*CpG.gff at https://gannet.fish.washington.edu/seashell/bu-github/Meth_Compare/genome-feature-files/
