### ISSUE TITLE
Screen cast of DAVID use

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#875]
Looking to refresh my memory as to how exactly DAVID enrichment tool should be used. Are there any existing resources, e.g. screen casts or images, to review?

**Comment by sr320** [comment]
There is this classic https://m.youtube.com/watch?v=lTNU6ppBiQs

**Comment by kubu4** [comment]
Is DAVID still up??

**Comment by sr320** [comment]
Or https://youtu.be/Ogb5H11wnNc

**Comment by sr320** [comment]
Yes - and updated in the past year.

**Comment by laurahspencer** [comment]
Awesome, thanks!

**Comment by kubu4** [comment]
What's the web address? The address I'm trying isn't loading. Is this the wrong address? https://david.ncifcrf.gov/

**Comment by sr320** [comment]
https://david.ncifcrf.gov/ Is working for me

**Comment by kubu4** [comment]
Hmmm, won't load on mobile and can't figure out how to share screenshot... 😭🤣

**Comment by sr320** [comment]
https://d.pr/v/FRnveC

**Comment by kubu4** [comment]
https://drive.google.com/file/d/1bBGZtbJJ_aLcgGytZ4kFSTUUJPbE_Z9a/view?usp=drivesdk

**Comment by yaaminiv** [comment]
I also wrote some tutorials for myself in my notebook if you need em!

https://yaaminiv.github.io/tagview/#david

**Comment by laurahspencer** [comment]
Thanks everyone, great to have links to these resources in one place!
