### ISSUE TITLE
Get Screen Sharing Access from home

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#876]
>When I'm on campus I can use the screen sharing application to connect to ostrich for GUI access but I can't get it to connect from home.

You need to install... 
https://itconnect.uw.edu/connect/uw-networks/about-husky-onnet/use-husky-onnet/

Background
https://itconnect.uw.edu/connect/uw-networks/about-husky-onnet/

**Comment by shellytrigg** [comment]
got screen sharing to work after installing Husky OnNet! Thanks @sr320 !
