### ISSUE TITLE
Assess higher end computing needs for near future

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#877]
We can discuss at lab meeting but folks should think about computing needs for next several months.... upgrades, campus network access, hardware, hard drives etc.

**Comment by laurahspencer** [comment]
@sr320 I could use an external hard drive to use for at-home data processing. Does the lab have an extra that I could "check out"? If not, any interest in purchasing one for me to use for the next year?

**Comment by sr320** [comment]
sure no problem- you can order and get reimbursed

**Comment by kubu4** [comment]
@laurahspencer 

So you're not out-of-pocket for anything, try these options (in order):

1. Ask Lisa Smith to order item(s) for you and ship to your house.

_or_

2. Ask me to order items for you and ship to your house.

**Comment by laurahspencer** [comment]
Thanks @sr320 and @kubu4, I went ahead and purchased one since I ran out of space yesterday evening, and wanted it expeditiously.

**Comment by kubu4** [comment]
Gannet has <20% capacity remaining (i.e. ~ 14TB). 

We should consider upgrading HDD capacity. Currently, there are 12 x 8TB drives.

Upgrade options:

12 x 12TB = ~$3600

12 x 16TB = ~$5000

**Comment by kubu4** [comment]
@sr320 - Per today's lab meeting about replacing HDDs in Gannet, which budget should I use (pricing is listed in post above this one)?

**Comment by sr320** [comment]
61-0552
