### ISSUE TITLE
Create list / histogram of scaffold sizes (bp) for coral genomes

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#883]
3 genomes (fasta)
https://gannet.fish.washington.edu/seashell/bu-mox/data/froger/Mcap_Genome/Mcap.genome_assembly.fa
https://gannet.fish.washington.edu/seashell/bu-mox/data/froger/C1_Genome/SymbC1.Genome.Scaffolds.fasta
https://gannet.fish.washington.edu/seashell/bu-mox/data/froger/Pact_Genome/Pocillopora_acuta_genome_v1.fasta

Big picture is we might want to create version with size limit thresholds.

**Comment by kubu4** [comment]
![M cap_50](https://user-images.githubusercontent.com/4514104/78268005-7b540900-74bc-11ea-9672-d2129c0d8da1.png)

---

![P acut_50](https://user-images.githubusercontent.com/4514104/78268021-8018bd00-74bc-11ea-8cdc-a911711be9a1.png)

![P acut_100_100](https://user-images.githubusercontent.com/4514104/78268031-8444da80-74bc-11ea-8560-8c9e2a8a4933.png)

---

![SymbC1_75](https://user-images.githubusercontent.com/4514104/78268044-8870f800-74bc-11ea-88d8-7d2457e70dcb.png)


![SymbC1_75_5](https://user-images.githubusercontent.com/4514104/78268054-8c047f00-74bc-11ea-8871-30f6daa21223.png)

**Comment by kubu4** [comment]
Probably should've clarified about plots above.

I've "zoomed" in on the P.acut and SymbC1 distributions to be able to see those scaffolds with smaller counts.

Data plotted is column two (sequence length) of the FastA index files.

**Comment by sr320** [comment]
thanks!
