### ISSUE TITLE
Using gannet as git repo server

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#884]
I am interested in pushing git repos (with many files over 100mb) to gannet such that collaborators can .... collaborate on. 

Is this possible and how might I go about doing this? Or is there a better solution to this?

**Comment by kubu4** [comment]
It is possible.

The best instructions are here:

https://www.synology.com/en-global/knowledgebase/DSM/help/Git/git

Here's the quick gist:

1. Create a repo somewhere on Gannet.

2. SSH into that folder and run `git init`.

3. Follow info in that link above to allow collaborators to clone the repo and start contributing.

Note: Each person you want to be able to collaborate on the repo will need a user account on Gannet. Additionally, they'll need to be individually authorized, by giving them permissions in the Synology Git Server app (found in the Package Center).

**Comment by kubu4** [comment]
Also, I should've added, you can run that `git init` command in any existing folder to. Then, you'll need to add/commit any files already present. Then, it's ready to go!
