### ISSUE TITLE
Accessing Desktop Computers in Lab Remotely

### ISSUE THREAD

**Issue by H-Ra** [RobertsLab/resources#885]
Does anyone know how to access the computers in lab remotely? Any advice/tips would be appreciated!

**Comment by sr320** [comment]
Specifically accessing the Windows (woodpecker) machine from a Mac remotely

**Comment by kubu4** [comment]
It's likely that woodpecker has TeamViewer software installed on it. This is screen sharing software. I'd guess it's available for Macintosh.

**Comment by sr320** [comment]
Shelly also mentioned this in lab meeting https://www.techrepublic.com/article/pro-tip-remote-desktop-on-mac-what-you-need-to-know/

**Comment by kubu4** [comment]
@laurahspencer Do you know the login credentials for TeamViewer? I think you were the one who originally installed/used it?

**Comment by laurahspencer** [comment]
I sent Sam the most recent PW that i had, from 2017. Didn’t want to post here. @kubu4 did that work?

**Comment by kubu4** [comment]
I haven't tried anything.

**Comment by kubu4** [comment]
@H-Ra Have do you still need help with this? Do you specifically need to use Woodpecker? I think you had been using a Python program for some of your analysis. Macintosh computers come with Python installed, so you could switch to using your personal computer, if that's easier.

**Comment by H-Ra** [comment]
I think there is a Python Script that I have in the Woodpecker computer that I would like to have access to, but it definitely isn't something that I need immediately... Is gaining access to the Woodpecker still a possibility? I do have Python on my personal computer, so I'm good to go in terms of continuing to work on the project.

**Comment by kubu4** [comment]
Yes it's a possibility. Did you try the instructions in the link that Steven posted above?

**Comment by kubu4** [comment]
> I think there is a Python Script that I have in the Woodpecker computer that I would like to have access to...

This is something we should help you address with your workflow. All your work should be backed up/synced to a central location that's accessible remotely (e.g. GitHub, lab server, etc). Do you know how to do this?

**Comment by H-Ra** [comment]
> Yes it's a possibility. Did you try the instructions in the link that Steven posted above?

I think the instructions for the link require information such as the computer IP address, and I am not exactly sure what it is.

**Comment by H-Ra** [comment]
> This is something we should help you address with your workflow. All your work should be backed up/synced to a central location that's accessible remotely (e.g. GitHub, lab server, etc). Do you know how to do this?

I don't think I know how to make all of my work synced to a central location, but I would be more than willing to learn!

**Comment by kubu4** [comment]
Sent spreadsheet of computer IP addresses to you in Slack.

**Comment by H-Ra** [comment]
Ok, so I tried to access the computer remotely using the application, but it seems like there is a domain name that it needs in order to access a certain user account. Would any of you happen to know what the domain name is and/or if there is a domain associated to the computer?

**Comment by kubu4** [comment]
Which application did you use? Also, Windows computers usually have a default domain of `WORKGROUP`.

Remote connections to these computers is also complicated by the possible need to use [Husky OnNet](https://itconnect.uw.edu/connect/uw-networks/about-husky-onnet/). It's likely that you need this, but I'm not exactly sure.

**Comment by sr320** [comment]
Microsoft Remote Desktop on a Mac works great.. 
see @shellytrigg link above.

**Comment by H-Ra** [comment]
> Which application did you use? Also, Windows computers usually have a default domain of `WORKGROUP`.
> 
> Remote connections to these computers is also complicated by the possible need to use [Husky OnNet](https://itconnect.uw.edu/connect/uw-networks/about-husky-onnet/). It's likely that you need this, but I'm not exactly sure.

I am using the Microsoft Remote Desktop app that @sr320 linked above. There might also be a Husky OnNet issue that I had not taken into consideration. Is there a server name that I could possibly connect to?

**Comment by sr320** [comment]
Just sent you info in Slack - you will need Husky OnNet running..

**Comment by H-Ra** [comment]
After I had Husky OnNet running, it worked! Thank you very much for all of your help!

**Comment by laurahspencer** [comment]
FYI when I was in FTR today I updated TeamViewer app on Woodpecker, and wrote down the current ID and password. It should now work for folks to log in remotely.  Where can I put that info to be accessible yet secure?  @kubu4 @H-Ra @sr320

**Comment by sr320** [comment]
It’s probably best to use Remote Desktop as opposed to Team Viewer.
