### ISSUE TITLE
C virginica gene set GO Annotations

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#886]
Do we have a canonical functional annotations of all C virginica genes? 

(Inquires have been made)

**Comment by yaaminiv** [comment]
What kind of annotations? I've annotated the mRNA track with Uniprot Accession and GOterms before, but that might be a reduced set for genes with DML. I'll do some digging and see if I have just the annotated mRNA track.

**Comment by yaaminiv** [comment]
Files I generated from [this R Markdown file](https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2019-08-14-Differentially-Methylated-Genes/2019-08-14-Differentially-Methylated-Gene-Analysis.Rmd):

- Canonical annotations for genes and their respective mRNA based on information from the GFF on NCBI ([.csv](https://raw.githubusercontent.com/fish546-2018/yaamini-virginica/master/analyses/2019-08-14-Differentially-Methylated-Genes/2019-08-14-All-Annotated-Gene-and-mRNA.csv) or [.txt](https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2019-08-14-Differentially-Methylated-Genes/2019-08-14-All-Annotated-Gene-and-mRNA.txt))
- [Uniprot Accession and GOterms for the longest mRNA within a gene](https://github.com/fish546-2018/yaamini-virginica/blob/master/analyses/2019-08-14-Differentially-Methylated-Genes/2019-08-14-Annotated-Gene-Longest-mRNA-Uniprot-GOterms.txt). May not be safe assume that each mRNA from a gene would have the same associated Uniprot and GOterms
