### ISSUE TITLE
MEGAN distance matrix

### ISSUE THREAD

**Issue by emmats** [RobertsLab/resources#887]
I have dug through the MEGAN manual a little to try to figure out if the PCA (PCoA) Sam made is based on a presence/absence matrix or on the number of reads for each taxon.
Short answer: I believe it is based on number of reads

Longer answer: In the Cluster Analysis Viewer section, it reads that the PCoA is made from a distance matrix of taxonomic profile or functional classification (have you made the latter yet?).
I believe that the taxonomic profile is derived from the comparison document (see "Comparison of Samples" and "Compare Dialog"). In the Compare Dialog section, the manual states that number of reads are used to compare samples.

**Comment by kubu4** [comment]
> functional classification (have you made the latter yet?).

Yep.
