### ISSUE TITLE
Trouble loading Pact files in IGV

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#890]
@sr320 Did you encounter any trouble visualizing the Pdam genome feature tracks ([found here](https://github.com/hputnam/Meth_Compare/tree/master/genome-feature-files)) in IGV? I downloaded the genome from the Google Drive and tried visualizing the intron track I generated in [this notebook](https://github.com/hputnam/Meth_Compare/blob/master/scripts/Generating-Genome-Feature-Tracks.ipynb). In IGV, this track looks blank (even though I know from my files that there are introns on this scaffold):

<img width="781" alt="Screen Shot 2020-04-06 at 9 58 09 PM" src="https://user-images.githubusercontent.com/22335838/78631621-b7d38c00-7851-11ea-81a9-8082441229d1.png">

<img width="1007" alt="Screen Shot 2020-04-06 at 9 58 27 PM" src="https://user-images.githubusercontent.com/22335838/78631632-c02bc700-7851-11ea-998f-704a13330dbd.png">

Is there a step I'm missing before I can visualize these tracks?

(also...am I supposed to post these issues here or in the Meth_Compare repo I am very confused)

**Comment by sr320** [comment]
Pretty sure we decided to use Pact and not Pdam...  so no need to visualize

**Comment by yaaminiv** [comment]
@sr320 Sorry wrote Pdam when I was working with Pact

**Comment by sr320** [comment]
Scaffold names do not match... one has an `_` : https://d.pr/i/Z279d8

**Comment by yaaminiv** [comment]
> Scaffold names do not match... one has an `_`

Yikes. I'll add `_` in between the scaffold number and cov in each feature track. Any suggestions for how to code this? Here's how I see it in my head:

1. Use `tr` to convert `cov` to `\t`
2. Add a column of just "_cov"
3. Paste the `scaffold`, `_cov`, and number columns together to match the scaffold names in the original genome.

**Comment by kubu4** [comment]
`sed 's/scaffold/scaffold_/' > newfilename`

**Comment by yaaminiv** [comment]
@kubu4 Doh...forgot about `sed` *facepalm* Thanks!!

<img width="905" alt="Screen Shot 2020-04-08 at 1 26 05 PM" src="https://user-images.githubusercontent.com/22335838/78830268-81eeee80-799c-11ea-9222-a30c9cc4236d.png">

**Comment by yaaminiv** [comment]
Matching the scaffold names to the genome did the trick!

![Screen Shot 2020-04-08 at 1 27 53 PM](https://user-images.githubusercontent.com/22335838/78830416-c24e6c80-799c-11ea-830f-b5960cce9940.png)
