### ISSUE TITLE
DIA oyster paper feedback please! 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#891]
only if you have time and want to!!!

feedback on the [2015 DIA oyster paper](https://docs.google.com/document/d/1OaYNzlOJr5QibCYt8--GMNGvXlzHPR9_daCkNUVkj-U/edit?usp=sharing) please! 

note: discussion still VERY rough - feel free to provide feedback on flow if you like. 

Thank you! 

(will also post on slack)

**Comment by yaaminiv** [comment]
Done! Focused more on methods and results.

**Comment by grace-ac** [comment]
thanks for the feedback thus far! I'll close the issue for now and once I have a cleaner version, i can send out for feedback again. Thanks!
