### ISSUE TITLE
CG motifs for Pact and Mcap?

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#893]
@sr320 Do we have CG motif tracks for both species? I see an [index file for Mcap CG motifs](https://github.com/hputnam/Meth_Compare/blob/master/genome-feature-files/Mcap_CpG.gff.idx) in the repo. Where is the actual track located? I'd like to quantify overlaps between the CG motifs and genome feature tracks so we can understand where methylation can occur.

**Comment by sr320** [comment]
CG tracks are at https://osf.io/x5waz/files/

**Comment by sr320** [comment]
Also be sure to assign things to me - it is easier me to find. https://d.pr/i/VxifgJ

**Comment by yaaminiv** [comment]
Got it. Thanks!
