### ISSUE TITLE
Processing clam gonads for histology

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#895]
If cockles are collected next week for histology... what would have to occur in the lab for preserving tissue for sending out for histo. 

Using the simplest, most straight forward approach..

**Comment by kubu4** [comment]
Simplest:

- put tissue in histo cassettes

- put cassettes in Davidson's fixative overnight

- transfer cassettes to 70% EtOH for storage

- ship cassettes only off for histology (however, this requires shipping of ethanol in "excepted quantities" which requires a trained person to do/sign off)

**Comment by grace-ac** [comment]
maybe to add:
- dissecting tools (lots of random stuff in drawers in 213 - spatulas, shuckers, tweezers, maybe some scissors --> i don't think i know what a cockle looks like, so i'm not sure what's needed)

**Comment by sr320** [comment]
do we have Davidson's fixative in the lab? 

One option is I sample, place in Davidson / EtOh, then we simply wait to ship when things are back to normal.

**Comment by kubu4** [comment]
Possibly. @mgavery has used in the past, so we might have a bottle in the dume good in FTR 213. Or, I may have moved it to the area beneath the whiteboard in FTR 209. Or, we don't have any. It's cheap/easy to make, but don't know the recipe offhand. Some combination of formaldehyde, sea water, acetic acid, and glycerol, I think. I have no idea on what we have of those components.

So, easiest (but pricey) would be to order PAXgene kit stuff...

**Comment by mgavery** [comment]
Ryan has been using Davidson's for his cockle sampling.   I sampled with him, but only did a bit of histo sampling. The anatomy is weird (gonad in base of foot) and would suggest having someone there who knows anatomy for first samples.

**Comment by laurahspencer** [comment]
I’ll be on campus tomorrow and will check to see if we have any more
paxgene fixative left.

**Comment by sr320** [comment]
thanks @laurahspencer - do you mind checking to see if we have Davidson's also?

@mgavery per @kubu4 comment, do you recall if we have any more Davidson's in the lab and where it might be?

**Comment by kubu4** [comment]
See my previous comment.

**Comment by mgavery** [comment]
I don't remember.  Sam's suggestions would be places to look.  I feel like I prepped it in Friedman Lab a million years ago.

**Comment by sr320** [comment]
@mgavery - Sorry I thought when he said you used it, he meant last week, not last decade..

**Comment by laurahspencer** [comment]
Will go check lab supplies in a couple hrs.

**Comment by laurahspencer** [comment]
Found Davidson’s solution dated from 2013. Also have one bottle of PAXgene fixative, which can preserve 4 histo cassettes. All is on a bench in 213.

**Comment by laurahspencer** [comment]
![09E625A0-FBCC-4E94-9536-D9265B0B0F9E](https://user-images.githubusercontent.com/17264765/78940682-1f185880-7a6b-11ea-9216-cf0e71a677ad.jpeg)
![A0B29A53-9151-4CE7-8D5D-0691633CB025](https://user-images.githubusercontent.com/17264765/78940690-217ab280-7a6b-11ea-909b-bfab91682cef.jpeg)
![5EA05EAC-03D2-4AA9-956A-A06585229ADB](https://user-images.githubusercontent.com/17264765/78940693-22134900-7a6b-11ea-9f8a-2d6708305b93.jpeg)

**Comment by laurahspencer** [comment]
![61FF382C-9AFD-4517-83F1-CD83B31EA077](https://user-images.githubusercontent.com/17264765/78940783-466f2580-7a6b-11ea-90c9-0959d7932cdf.jpeg)

**Comment by laurahspencer** [comment]
I also preserved gonad tissue using paraformaldehyde, with good success. Here is my notebook entry with recipes and details: 
https://laurahspencer.github.io/LabNotebook/Histology-processing/

**Comment by sr320** [comment]
Any items I should grab today in the lab for sampling you think I will forget ...  please add to https://docs.google.com/document/d/1mQZTLW6H3m9Y611BS6DykdWuWorYno6E6GYW-RkGS2w/edit?usp=sharing
