### ISSUE TITLE
IGV merging features in Pact genome

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#896]
I visualized various *P. acuta* feature tracks in [this IGV session](https://github.com/hputnam/Meth_Compare/blob/master/genome-feature-files/Pact-Genome-Feature-Tracks.xml) (all features link to `gannet` so it should be viewable by others). Looking at the tracks, I noticed that introns were overlapping with CDS, which doesn't make any sense. I think this might be because IGV is taking introns from different transcripts that overlap with eachother and smashing them together.

![Screen Shot 2020-04-08 at 2 00 34 PM](https://user-images.githubusercontent.com/22335838/78833771-435c3280-79a2-11ea-91a3-905550457871.png)

If the introns, CDS, exons etc. for each transcript aren't mashed together, it would be easier to figure out if these tracks are valid. Is there something I need to do when generating tracks to ensure they're processed properly in IGV?

**Comment by kubu4** [comment]
Intron tracks should be generated from gene/CDS info. Is that how this was constructed?

**Comment by yaaminiv** [comment]
@kubu4 No, I pulled the intron information straight from the genome annotation file we have in [this notebook](https://github.com/hputnam/Meth_Compare/blob/master/scripts/Generating-Genome-Feature-Tracks.ipynb):

<img width="974" alt="Screen Shot 2020-04-08 at 2 44 48 PM" src="https://user-images.githubusercontent.com/22335838/78836713-8240b700-79a7-11ea-8569-a909d8cbf233.png">
I did the same thing for *M. capitata* and I didn't see any overlapping introns for that annotation.

**Comment by kubu4** [comment]
Were those annotations created by the same people with the same software?

I'd start by visualizing the original GFF. However, I'm guessing IGV uses coordinates based on gene ID. So, it will merge stuff that have overlapping coordinates with same feature and gene ID.

**Comment by yaaminiv** [comment]
> Were those annotations created by the same people with the same software?

The genomes were constructed and annotated by separate groups but with the AUGUSTUS software. 

The original GFF is a bit convoluted, but I'll see if I can pull out what I need, make sure the scaffold names match, and load it in IGV.

**Comment by yaaminiv** [comment]
>  However, I'm guessing IGV uses coordinates based on gene ID. So, it will merge stuff that have overlapping coordinates with same feature and gene ID.

I think you're right. Just looking at the CpG track, it merged two CG motifs on separate lines into one object. I'll hold off on going to the original GFF for now. I pulled the information from there, so my guess is that it will also look smushed. This is not ideal!

![Screen Shot 2020-04-08 at 3 05 58 PM](https://user-images.githubusercontent.com/22335838/78838212-920dca80-79aa-11ea-9150-206dc5bec449.png)
