### ISSUE TITLE
Testing out the titrator: chemicals

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#90]
The titrator is mostly set-up and @sr320 thinks it would be smart to start getting things ready to perform a test-run.

The manual has a section detailing the steps to Run a general titration.

Do we have:
- Approx. 5 ml of a HCl solution (0.1 mol/L)
- Titrant bottle containing a carbonate free NaOH solution (0.1 mol/L)
- 3 buffer solutions: pH 4.01, 7.00, and 9.21 (recommended from Mettler Toledo - can order)
- Approx. 50 mg potassium hydrogen phthalate

I can look around lab tomorrow, but wanted to make an issue detailing the chemicals.

**Comment by kubu4** [comment]
Check MyChem. We definitely don't have potassium hydrogen phthalate.

**Comment by grace-ac** [comment]
I tried to look into the MyChem this evening, but I have to be given permission to do so. 
![screen shot 2017-10-11 at 8 13 22 pm](https://user-images.githubusercontent.com/14934314/31477480-135e3988-aec1-11e7-8a14-6e46f160e6a4.png)



I clicked the link, and it's just a form to submit with specific information regarding the following:
![screen shot 2017-10-11 at 8 15 38 pm](https://user-images.githubusercontent.com/14934314/31477488-1868ba52-aec1-11e7-82e7-09b95b0eb974.png)




It would take 72 hours to get me into the system, so it might be faster for someone who already has access to check for the chemicals

**Comment by kubu4** [comment]
You should have access now. Sorry about that!

Another reason we should all go through the Onboarding procedure - to see if we've overlooked stuff like this.

**Comment by grace-ac** [comment]
Got it, thank you!

**Comment by grace-ac** [comment]
We do NOT have: 
- 50 mg Potassium hydrogen phthalate
- Not sure about the buffer solutions 

We DO have:
- 500 g Sodium Hydroxide. It needs to be made into a titrant bottle-full of carbonate free NaOH solution

I have no clue if this is what we need, but it's the only HCl chemical in MyChem:
![hcl](https://user-images.githubusercontent.com/14934314/31508554-4d258208-af33-11e7-9b5a-8094fbbcdeff.png)

**Comment by grace-ac** [comment]
Lisa has been having a hard time ordering the pH 9.21 buffer solution. An error popped up when she attempted and she has been in contact with Mettler-Toledo via phone. 

The other two buffers (4.01 and 7.00) are easily order-able, but she's waiting until she can get the pH 9.21 ordered. Awaiting further information on the ordering of the buffers. 

She was able to order the potassium hydrogen phthalate.

**Comment by grace-ac** [comment]
Estimated delivery date for potassium hydrogen phthalate - 10/30/2017

Estimated delivery date for the buffers - 11/10/2017 

So, Steven said we'll try out with the potassium hydrogen phthalate when it arrives with buffers in 209.

**Comment by sr320** [comment]
@kubu4 do we have some protocols from Hollie on how to run samples?

**Comment by kubu4** [comment]
Yes. I'll get them added to protocols and post links here once I upload them.

**Comment by kubu4** [comment]
Here's the Word doc she sent me. I will convert to markdown and add to protocols.

The protocol references some Excel spreadsheets and an R script, which we do not have. I believe the Excel sheets are simply for keeping a log of calibration values and CRM batches, but I haven't looked at it too thoroughly yet.

[Titrator SOP.docx](https://github.com/RobertsLab/resources/files/1411925/Titrator.SOP.docx)


Additionally, she sent a method report file (PDF), which I think outlines the method used in the titrator's software. Here's that, too:

[MethodReport.pdf](https://github.com/RobertsLab/resources/files/1411944/MethodReport.pdf)

**Comment by sr320** [comment]
@grace-ac can you please convert the docx to markdown

**Comment by grace-ac** [comment]
converted to markdown, added to protocols, and updated readme 
https://github.com/RobertsLab/resources/blob/master/protocols/Titrator.SOP.md

**Comment by grace-ac** [comment]
the hydrogen potassium phthalate is here! I will start looking at the protocols in more detail and will post issues of what I'm figuring out. I will NOT do anything without other people weighing in!

**Comment by sr320** [comment]
Run the protocol from the User Manual first...
