### ISSUE TITLE
Accessing genefish (mini) remotely

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#900]
Is there some trick to this, cannot seem to mount with IP or name.

**Comment by yaaminiv** [comment]
I usually access using the Screen Sharing app for macOS with IP 172.25.149.226. I've also been able to `ssh`

![Screen Shot 2020-04-13 at 10 22 11 AM](https://user-images.githubusercontent.com/22335838/79142630-a4a04f00-7d70-11ea-845d-6009460be40c.png)

**Comment by sr320** [comment]
thanks
