### ISSUE TITLE
Run differential gene expression analysis on 2019 crab samples

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#901]
Comparing infected to uninfected. https://d.pr/i/ewUSP0

**Comment by kubu4** [comment]
This was done here:

https://robertslab.github.io/sams-notebook/2020/04/22/Gene-Expression-C.bairdi-Pairwise-DEG-Comparisons-with-2019-RNAseq-using-Trinity-Salmon-EdgeR-on-Mox.html

Followed by some GO-to-GOslim stuff here:

https://robertslab.github.io/sams-notebook/2020/04/27/GO-to-GOslim-C.bairdi-Enriched-GO-Terms-from-20200422-DEGs.html
