### ISSUE TITLE
crab: transcript abundance of 2019 samples using kallisto

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#902]
gene counts are needed in order to use edgeR 

link to Trinity manual: alignment-free abundance estimation methods     
https://github.com/trinityrnaseq/trinityrnaseq/wiki/Trinity-Transcript-Quantification#kallisto-output 

2019 fasta files here: https://owl.fish.washington.edu/nightingales/C_bairdi/ 
(files from 2019-10-25)

**Comment by kubu4** [comment]
@grace-ac I'm not sure what you want here. You have the FastQ files and now it looks like you need/want to perform an alignment-free abundance estimation via Kallisto.

**Comment by sr320** [comment]
We need kallisto run to get a count table.

**Comment by kubu4** [comment]
I've mostly used salmon, so would be less time consuming for me to figure out. Would that be OK?

**Comment by sr320** [comment]
Certainly- that would fine

**Comment by kubu4** [comment]
@grace-ac Here ya go! There's a plethora of stuff here, but you probably want [quant.sf.genes](https://gannet.fish.washington.edu/Atumefaciens/20200415_cbai_salmon_abundance/quant.sf.genes)

Here's notebook entry on how this was run:

https://robertslab.github.io/sams-notebook/2020/04/15/Transcript-Abundance-C.bairid-Alignment-free-with-Salmon-on-Mox-for-Grace.html

---

Transcript abundances (text):

- [20200415_cbai_salmon_abundance/quant.sf](https://gannet.fish.washington.edu/Atumefaciens/20200415_cbai_salmon_abundance/quant.sf)

Transcript counts matrix (text):

- [20200415_cbai_salmon_abundance/salmon.isoform.counts.matrix](https://gannet.fish.washington.edu/Atumefaciens/20200415_cbai_salmon_abundance/salmon.isoform.counts.matrix)

Gene abundances (text):

- [20200415_cbai_salmon_abundance/quant.sf.genes](https://gannet.fish.washington.edu/Atumefaciens/20200415_cbai_salmon_abundance/quant.sf.genes)

Gene counts matrix (text):

- [20200415_cbai_salmon_abundance/salmon.gene.counts.matrix](https://gannet.fish.washington.edu/Atumefaciens/20200415_cbai_salmon_abundance/salmon.gene.counts.matrix)

Annotated (Trinotate) gene counts matrix (text):

- [20200415_cbai_salmon_abundance/salmon.gene.counts.annotated.matrix](https://gannet.fish.washington.edu/Atumefaciens/20200415_cbai_salmon_abundance/salmon.gene.counts.annotated.matrix)

**Comment by sr320** [comment]
Thanks but we are in need of a matrix that has count data for each sample... You might have it but could not find. For example, with 4 samples there would be 4 columns of count data.

**Comment by kubu4** [comment]
Gotcha. Sorry, that wasn't clear. Will re-run...

**Comment by kubu4** [comment]
Alrighty I've updated [my post above](https://github.com/RobertsLab/resources/issues/902#issuecomment-614222589) to link to the desired files and have fixed the broken link to my notebook entry.
