### ISSUE TITLE
Add jupyter notebook to path without sourcing bash profile?

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#906]
When I'm running Terminal (macOS Catalina 10.15.4), `jupyter` is not recognized as a command unless I source my bash profile in that Terminal session.

<img width="764" alt="Screen Shot 2020-04-17 at 2 22 26 PM" src="https://user-images.githubusercontent.com/22335838/79615131-df7aed80-80b6-11ea-8e28-e73d072534cd.png">

Is there a way to add `jupyter` to my path or bashRC so I wouldn't have to keep doing this?

**Comment by yaaminiv** [comment]
`/opt/anaconda3/share/jupyter/lab`

**Comment by kubu4** [comment]
Add this to your ~/.zshrc:

export PATH="/opt/anaconda3/share/jupyter/lab:$PATH"

**Comment by kubu4** [comment]
Solution:

`export PATH="/opt/anaconda3/bin/:$PATH"`
