### ISSUE TITLE
do files specified in this issue exist already? needed for GO-MWU (enrichment tool)

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#908]
### Do either of the files listed below in bold exist somewhere already? 

I tried GO-MWU earlier, and I used the list of DEGs from the 2019 crab data to perform analyses. Results = no enrichment. 

GO-MWU is meant to be used with the full list of inputs, meaning that I should have used all 2019 crab dataset. ([GO-MWU README.md](https://github.com/z0on/GO_MWU) if you want more info)         
Now that I've figured out how to use GO-MWU, I'd like to try again with the correct data.

I need to make 2 files for GO-MWU, but in order to make them, I need:
1. **blast output of JUST the 2019 crab data**, _which I will `join` with the 2019 gene count table. Then I'll create the first file needed: two columns --> geneID, and GO terms_
2. **full list of 2019 crab genes (not just DEGs) from `DESeq` or `edgeR`**. _Then I'll make the second file: 2 column file: gene ID and a column of measures of significance associated with GO enrichment (examples: kME value, p-value, dN/dS value, etc) - i'd like to use p-value._

Let me know if anything above is unclear.

**Comment by sr320** [comment]
I would say you need to use transcriptome ref assembly annotation for this but lets discuss.

 Also I think DAVID is certainly worth a whirl.

**Comment by kubu4** [comment]
The short answer to both questions: no.
