### ISSUE TITLE
Ellie Bors addition as Hyak user?

### ISSUE THREAD

**Issue by ekbors** [RobertsLab/resources#909]
Hi Steven,

Following up here in addition to an earlier e-mail regarding gaining access to Hyak Mox. Based on the Wiki, it seemed like this is the appropriate channel for that request. Apologies for cross-posting the request. 

I am a new JISAO postdoc in Lorenz Hauser's lab. I'll be analyzing WGS data from pollock (if we ever get back to the lab!) and maybe working on some cod RAD seq. My UW e-mail is ekbors@uw.edu. My GitHub is linked to my gmail. Will that cause issues? 

Thanks!
-Ellie

**Comment by sr320** [comment]
We can get you set up this week- will be in touch soon with more details.

**Comment by kubu4** [comment]
Hey @ekbors! You've now been added as a user in the srlab Hyak (Mox) user group.

If you haven't already, please read through our lab's guide to using Mox:

https://github.com/RobertsLab/hyak_mox/wiki

Some quick notes that aren't in that link above.

- We have two available nodes: one with 128GB RAM and 512GB RAM

- When possible, please don't request the entire set of resources from a node; other users can tap into any unused resources on any given node. For example, if you are running a program that will only use 4 CPU threads and doesn't need a boatload of memory, please only request 4 CPU and 28GB RAM. By doing so, the node that runs that job will still have 24 CPUs (each node has 28) and 100GB/484GB RAM that other users can tap into. 

However, if you had requested 28CPUs and 28GB RAM, an entire node will be reserved for you job, even though the program you're running is capped at 4 CPUs.

Alrighty, I think that's it for now. Please feel free to drop any other questions about Mox in a new issue when/if they crop up!
