### ISSUE TITLE
Lab Safety Issues

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#91]
I got the following from Andre 
![9195dab1-92bd-4277-838e-5064a7f28e3c](https://user-images.githubusercontent.com/4442039/31439717-0cbfe7f4-ae42-11e7-8a43-61d375b654a8.jpeg)

Are these issues outstanding or resolved?
Thanks

**Comment by kubu4** [comment]
To me, it looks like we resolved these.

![20171011_safety](https://user-images.githubusercontent.com/4514104/31443572-a46c5888-ae4e-11e7-9e64-2196b6cdb0c7.png)

**Comment by sr320** [comment]
Gotcha! thanks

I suppose that is something I can log into? :)

**Comment by kubu4** [comment]
Yes. https://depts.washington.edu/ehas/pubcookie/prod/labsurvey/index.php

However, the survey is "closed", so it can no longer be edited to mark items as completed.
