### ISSUE TITLE
Feedback on Olympia oyster food / temperature paper 

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#910]
@sr320 looking for your feedback on my Oly temp/food paper. Target journal is Aquaculture.  

If anyone else feels like reading this MS, I'd gladly accept more comments! 

https://docs.google.com/document/d/1Z9RlHad5NFY4yJozZLaY_nmpBOuQMTijcu8BQDDleAI/edit?usp=sharing

**Comment by sr320** [comment]
Reminder to "Assign" me to issues like these so they hit my list of to-dos.
