### ISSUE TITLE
Elegant code to get from blast output to GOslim figure?

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#911]
10 bonus points for best code... judging at Science Hours with the pets

**Comment by yaaminiv** [comment]
I did something similar for *C. virginica* gonad methylation in two steps:

1. [Assign GOSlim terms to `blastx` output](https://github.com/epigeneticstoocean/paper-gonad-meth/blob/master/code/12-blastx-to-GOslim.ipynb)
2. [Create back-to-back figure](https://github.com/epigeneticstoocean/paper-gonad-meth/blob/master/code/14-Gene-Enrichment-with-GO-MWU.Rmd#L387)

**Comment by sr320** [comment]
remove duplicate GO slims for a single gene
