### ISSUE TITLE
Need file with all CpG loci in Ostrea lurida genome

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#912]
For the Oly methylation paper I will need to describe where we identified methylation, compared to all CpG loci in genome. @sr320 and @kubu4 does this exist?

**Comment by sr320** [comment]
I would say no.
I can create one.

**Comment by sr320** [comment]
Available @ https://github.com/RobertsLab/resources/wiki/Genomic-Resources#genome-feature-tracks-2

direct url: https://owl.fish.washington.edu/halfshell/genomic-databank/Olurida_v081_CG-motif.gff

**Comment by laurahspencer** [comment]
Great, thanks! For posterity / me in the future, can you provide the link the script you used to create this?

**Comment by kubu4** [comment]
@laurahspencer Probably something like this: https://robertslab.github.io/sams-notebook/2019/08/21/Data-Wrangling-Create-a-CpG-GFF-from-Pgenerosa_v074-using-EMBOSS-fuzznuc-on-Swoose.html

**Comment by sr320** [comment]
Correct… though I just ran on Galaxy...
