### ISSUE TITLE
Setting up a Globus endpoint on a Roberts Lab server for data transfer 

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#914]
Has anyone set up a Globus endpoint on a Roberts lab server to transfer data from the UW Sequencing Center (NWGC)? 

https://docs.globus.org/how-to/get-started/  

I presume it should be set up on Owl to transfer to nightingales, as per the NGS Data Management plan

**Comment by shellytrigg** [comment]
@laurahspencer this is what I did last time:

[https://shellytrigg.github.io/130th-post/](https://shellytrigg.github.io/130th-post/)

And @kubu4 helped me transfer the files to Nightengales on Owl here: [https://github.com/RobertsLab/resources/issues/713](https://github.com/RobertsLab/resources/issues/713])

**Comment by kubu4** [comment]
Do what @shellytrigg said. Since the Globus thing is a graphical user interface, it can't be installed/run on the servers (or, if it can, I'm not sure how).
