### ISSUE TITLE
Best program for demultiplexing?

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#918]
Received my QuantSeq sequencing data in the form of two large files, each containing data from many indexed libraries (69 and 77 samples, respectively). I found Sam's notebook entry indicating that when he tested `grep` and `fastx_barcode_splitter`, neither identified many reads successfully (max 25% of all reads). Anyone have a favorite demultiplexing program? I'm working with Ostrea lurida expression data, and each library has a 6nt barcode. 

FYI, when I asked the sequencing facility to demultiplex for me, they said the following: 

"For external projects, we only supply the Fastq data. Our pipeline does not allow for your species to be demultiplexed. Would raw data help you? If so, we do charge for this. I have attached the reads per sample csv files (saved [here](https://github.com/fish546-2018/laura-quantseq/blob/master/data/2020-QuantSeq/Batch1_69plex_lane1.stats.csv) and [here](https://github.com/fish546-2018/laura-quantseq/blob/master/data/2020-QuantSeq/Batch2_77plex_lane2.stats.csv)) and I can share the run data as follows:"

Date | Lane | Lane | Concentration (pM) | SAV Clusters/mm^2 | % Clusters PF | Overall Q30 | Read 1 Q30
-- | -- | -- | -- | -- | -- | -- | --
200420 | 1 | Batch1_69plex | 270 | 506.12 | 79.29 | 89.73 | 88.93
  | 2 | Batch2_77plex |   | 519.46 | 81.38 |   | 90.3

**Comment by kubu4** [comment]
Is this from NWGSC? If yes, who are you communicating with? Also, please provide me with the project ID. I'll contact some "higher ups" and see if I can get this resolved. Pipeline has absolutely _nothing_ to do with species.

Also, please send me the sequencing summary info they sent you (with # reads/library)

**Comment by kubu4** [comment]
Ooops, I see summary file links now! Sorry!

**Comment by kubu4** [comment]
Also, please send me a copy of the project quote.

**Comment by laurahspencer** [comment]
Yes, it's the Northwest Genomics Sequencing Center, and I'm communicating with Erica. Here is the signed quote [Est_202003_013_from_Northwest_Genomics_Center_18784_final.pdf](https://github.com/fish546-2018/laura-quantseq/blob/master/references/Est_202003_013_from_Northwest_Genomics_Center_18784_final.pdf). The project name is Spencer_O-lurida-QuantSeq-2020, and quote number is 2020-03_013. Also, here is a screen shot of the data on Globus: 

![image](https://user-images.githubusercontent.com/17264765/80292889-1bddc780-870f-11ea-8d5c-390dc7b4566f.png)

I am a little confused, because when I asked again about demultiplexing, she emphasized that they only provide fastq files - aren't demultiplexed files also fastq? Am I using the right terminology when I ask her to demultiplex, or is there another term that folks use for separating reads by sample/index?  

Thanks @kubu4 for the help escalating! Let me know how if there's anything else I can do / provide.

**Comment by kubu4** [comment]
Can you please send me Erica's email address (via Slack or email)?

**Comment by kubu4** [comment]
Email sent. Will report back with updates (this should be fun!).

**Comment by kubu4** [comment]
She wrote back, was confused, and indicated all the data was there.

And, she's correct. You need to untar/gunzip the `.tar.gz` files.

I'm in the process of doing that now. I'll get MD5s generated and put on `/owl/nightingales/O_lurida`.


```shell
/mnt/owl/nightingales/O_lurida/2020-04-21_QuantSeq-data$ tar -xzvf Batch1_69plex_lane1.tar.gz -C ~/Downloads/
Batch1_69plex_lane1_done/
Batch1_69plex_lane1_done/185_S60_L001_R1_001.fastq.gz
Batch1_69plex_lane1_done/302_S15_L001_R1_001.fastq.gz
Batch1_69plex_lane1_done/313_S36_L001_R1_001.fastq.gz
Batch1_69plex_lane1_done/161_S57_L001_R1_001.fastq.gz
Batch1_69plex_lane1_done/140_S64_L001_R1_001.fastq.gz
Batch1_69plex_lane1_done/304_S24_L001_R1_001.fastq.gz
Batch1_69plex_lane1_done/328_S12_L001_R1_001.fastq.gz
Batch1_69plex_lane1_done/Stats/
Batch1_69plex_lane1_done/Stats/Lane1/
Batch1_69plex_lane1_done/Stats/Lane1/Stats.json
Batch1_69plex_lane1_done/Stats/Lane1/DemuxSummaryF1L1.txt
Batch1_69plex_lane1_done/Stats/Lane1/DemultiplexingStats.xml
Batch1_69plex_lane1_done/Stats/Lane1/FastqSummaryF1L1.txt
Batch1_69plex_lane1_done/Stats/Lane1/AdapterTrimming.txt
Batch1_69plex_lane1_done/Stats/Lane1/ConversionStats.xml
Batch1_69plex_lane1_done/316_S9_L001_R1_001.fastq.gz
Batch1_69plex_lane1_done/337_S35_L001_R1_001.fastq.gz
```

I'll also let you close this issue. :)

**Comment by laurahspencer** [comment]
Awesome- next time I'll dig into the files before I start asking questions :) 
Thanks @kubu4 for solving that problem, and for extracting the files and generating MD5s!
