### ISSUE TITLE
Discuss collaborative repo approach(es)

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#919]
We've recently hit a bunch of snags on the [Meth_Compare repo](https://github.com/hputnam/Meth_Compare), in regards to merge conflicts. As this is really the first repo where multiple people have been working simultaneously in near-real-time for collaboration, it'd be cool to discuss how we should approach things to avoid/minimize conflicts. Some ideas:

1. Learn how to use branches. Allows everyone to work separately until they decide to merge their work (branch) back in, but work is still accessible to everyone.

2. Fork Meth_Compare repo and work on the forked version. Use Pull Requests to merge work back into original Meth_Compare repo.

**Comment by yaaminiv** [comment]
Related question/topic for discussion: how come some of the files that only I work on are changed after someone else pushes their commits to the repo? I've lost code in scripts even after I've pushed my commits to Github once there are large-scale changes that someone makes to other parts of the repo

**Comment by kubu4** [comment]
I've added the Science Hour label to this. 

I'd like to set up a "fake" repo where we can all practice collaborative repo destruction this Friday! Practice will include updating a `.gitignore` file after the files have been committed!

**Comment by sr320** [comment]
Great idea!

**Comment by kubu4** [comment]
Repo for breaking is here: https://github.com/RobertsLab/you_wreck_me

Everyone already has folders and a readme in each folder.

**Comment by kubu4** [comment]
Stay the course. Forking/branching are the same. Neither will help reduce conflicts.
