### ISSUE TITLE
Add Presentations to website

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#92]
Please 

add presentations posted 
https://github.com/RobertsLab/resources/issues/64

to 

https://github.com/sr320/LabDocs/blob/master/web/Products.md

Creating 2017 for Recent Presentations

**Comment by grace-ac** [comment]
I think I did it....? Not quite sure if I'm supposed to submit a pull request... 
![screen shot 2017-10-11 at 2 44 10 pm](https://user-images.githubusercontent.com/14934314/31468494-cdde329c-ae92-11e7-9553-3bdf1c66409c.png)

**Comment by sr320** [comment]
Don’t be scared, submit a pull request!
