### ISSUE TITLE
how can i undo a git commit that was 11 commits ago

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#920]
I made a commit 11 commits ago that included a file that is way too big for GitHub.

I kept making commits and didn't realize that it wouldn't push everything to the project-crab repo due to the one file being too large... so now my local project-crab repo is 11 commits ahead!

How can I undo the commit? 

(I'm googling and looking things up currently - posting issue in case someone can get me solution faster)

**Comment by grace-ac** [comment]
found this : https://www.git-tower.com/learn/git/faq/undo-revert-old-commit

**Comment by sr320** [comment]
Desktop or commandline?


thanks
Steven


Steven B. Roberts, Associate Professor
Associate Director - Graduate Program Coordinator
School of Aquatic and Fishery Sciences
University of Washington
Fisheries Teaching and Research (FTR) Building - Office 232
1140 NE Boat Street - Seattle, WA 98105
robertslab.info - sr320@uw.edu - @sr320
vm:206.866.5141 - cell:360.362.3626

**Comment by grace-ac** [comment]
i was using R to make all the commits, but I'm currently trying command line .... a bit scary, though. 

Going to open GitHub desktop now to see what that's like.

**Comment by grace-ac** [comment]
on desktop, it seems like i just have to undo all commits one by one. which isn't horrible.

**Comment by sr320** [comment]
Yes that will work..


remember commit, push, commit, push, commit, push, commit, push…. :)

**Comment by kubu4** [comment]
What you really want to do is remove the single large file from the guy index. No need to revert/reset to an earlier commit. Don't have time ATM to type out how to do this. Can report back after Audrey's in bed.

**Comment by grace-ac** [comment]
i removed the file and committed to removal of it, but it didn't help. maybe that's not what you are saying...

undo-ing commits and redoing without the big file is working fine though!

**Comment by kubu4** [comment]
Removing the file is not the same as removing it from the git index. The procedure is something like `git rm --cache`, then add large file to .gitignore, then commit, or something.

**Comment by grace-ac** [comment]
that makes sense.... if i ever do this again... I'll try that out instead :)
