### ISSUE TITLE
Develop "Crab" transcriptome that is not taxa filtered

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#923]
This might already exist, but looking for an assembly where all trimmed reads are used.

**Comment by kubu4** [comment]
Does not exist. Will make.

**Comment by kubu4** [comment]
Running.

**Comment by kubu4** [comment]
Transcriptome is here:

https://owl.fish.washington.edu/halfshell/genomic-databank/cbai_transcriptome_v2.0.fasta

Have added to Genomic Resources wiki (along with BUSCO and FastA index).

Notebook entry is here:

https://robertslab.github.io/sams-notebook/2020/05/02/Transcriptome-Assembly-C.bairdi-All-RNAseq-Data-Without-Taxonomic-Filters-with-Trinity-on-Mox.html

**Comment by kubu4** [comment]
I've also just added BLASTx annotation file to Genomic Resources wiki.
