### ISSUE TITLE
Average columns in union bedgraph in Jupyter notebook

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#924]
I want to average columns of the union bedgraphs so I can use that information downstream in [this Jupyter notebook](https://github.com/hputnam/Meth_Compare/blob/master/scripts/Characterizing-CpG-Methylation-5x-Union.ipynb). Here's what I'm working with:

![Screen Shot 2020-05-06 at 12 12 58 PM](https://user-images.githubusercontent.com/22335838/81218360-eea4db00-8f92-11ea-8e04-005227b3251c.png)

I need to average columns 3-5 but find a way to exclude entries with NAs from the denominator (similar to `na.rm = TRUE` in R). How can I do this? I found some awk code to get row averages but they do not include an option to ignore NAs.

**Comment by kubu4** [comment]
Try using Pandas. It's a dataframe thingy that's equivalent to R. Should be able easily ignore N/As.

**Comment by yaaminiv** [comment]
@kubu4 Could I use Pandas wrapped within other bash commands? Or would that be a different chunk in my notebook?

**Comment by kubu4** [comment]
Pandas is a Python package. You'd need to have it in its own cell.

**Comment by yaaminiv** [comment]
I'm trying to use Pandas now, but I also found this `awk` code to do something similar (column averages ignoring NAs) from [this link](https://stackoverflow.com/questions/33921031/calculate-mean-of-each-column-ignoring-missing-data-with-awk)

`awk '{for(i=1; i<=NF; i++){sum[i] += $i; if($i != "na"){count[i]+=1}}} END {for(i=1; i<=NF; i++){if(count[i]!=0){v = sum[i]/count[i]}else{v = 0}; if(i<NF){printf "%f\t",v}else{print v}}}' input.txt`

Is there an easy way to modify this to work on rows? Just trying to learn about all the options

**Comment by yaaminiv** [comment]
Ignore the above comment. I understand Pandas and it is magical. Thanks!

![Screen Shot 2020-05-06 at 2 00 39 PM](https://user-images.githubusercontent.com/22335838/81227875-f91aa100-8fa1-11ea-8ce0-32a403c3aa77.png)
