### ISSUE TITLE
O. lurida GTF annotation file for STAR aligner

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#926]
**Short version:** Does an Oly genome vs.081 annotation file in GTF format exist somewhere?

**Long version:** I'm using the [STAR aligner](https://github.com/alexdobin/STAR) to align my QuantSeq reads to the O. lurida genome. The STAR aligner is recommended by the QuantSeq developers. When building a STAR genome index, I need to include an annotated transcript file alongside the genome to _"extract splice junctions ... to greatly improve accuracy of mapping"_. 

The needed annotation file format is GTF, "where each of the exon lines contains both "transcript id" and "gene id", as GTF (but not GFF) format requires." (quoted from this [STAR repo issue](https://github.com/alexdobin/STAR/issues/387)).  The _O. lurida_ feature files available in our [Genomic Resources](https://github.com/RobertsLab/resources/wiki/Genomic-Resources) are all in .gff format. When I tried to convert the exon GFF to GTF using the `cufflinks` package (`gffread my.gff -T -o my.gtf`) the resulting file doesn't contain the necessary "gene_id" info. 

First few lines of the converted exon.gtf file: 
![image](https://user-images.githubusercontent.com/17264765/81368185-fd2ee780-90a3-11ea-9126-fd4b94797eb2.png)

When creating all the O. lurida vs.081 genome feature files, was a complete annotation file generated in GTF format, or that includes the info necessary to convert to GTF?

**Comment by kubu4** [comment]
Will this work?

https://gannet.fish.washington.edu/Atumefaciens/20190716_stringtie_20190709-olur-v081/20190709-Olurida_v081.stringtie.gtf

**Comment by kubu4** [comment]
![image](https://user-images.githubusercontent.com/4514104/81369005-1df83c80-90a6-11ea-9291-5be41807aaa2.png)

**Comment by kubu4** [comment]
Corresponding notebook entry: https://robertslab.github.io/sams-notebook/2019/07/16/Genome-Annotation-O.lurida-20190709-v081-Transcript-Isoform-ID-with-Stringtie-on-Mox.html

**Comment by laurahspencer** [comment]
Do you know if the 20190709-Olurida_v081.stringtie.gtf file contain all Oly exons? If so, then yes that should work! 

I know it was generated to indicate alternative splice variants, so was concerned that it could contain just a subset of exons (those that have >1 splice variants).

**Comment by kubu4** [comment]
My assumption is yes, but I honestly can't recall ATM. But, based on screencap above, the first line seems to support my assumption (e.g. gene_id MSTRG.1 only has a single corresponding transcript_id).

**Comment by laurahspencer** [comment]
Yes, that makes sense. I'll play with that file and the exon.gff to see if they differ much in # exons.

**Comment by kubu4** [comment]
Easiest/fastest thing to do is to toss it into IGV. You should be able to quickly see if any exons are "missing" a corresponding transcript.

**Comment by laurahspencer** [comment]
@kubu4 I checked out the below three O. lurida feature tracks in IGV: 
- Exon GFF track: [Olurida_v081-20190709.gene.gff](https://owl.fish.washington.edu/halfshell/genomic-databank/Olurida_v081-20190709.gene.gff)  
- Exon+isoform GTF track (stringtie-derived): [20190709-Olurida_v081.stringtie.gtf](https://gannet.fish.washington.edu/Atumefaciens/20190716_stringtie_20190709-olur-v081/20190709-Olurida_v081.stringtie.gtf)    
- Gene GFF track: [Olurida_v081-20190709.gene.gff](https://owl.fish.washington.edu/halfshell/genomic-databank/Olurida_v081-20190709.gene.gff)   
 
It looks like the Stringtie-derived track (GTF file) contains many exons that lie outside of gene regions according to the gene.gff.  Here's a SS from IGV, showing the 3 different tracks, and examples where the stringtie.GTF exons lie outside the gene.GFF genes: 

![Snip20200512_30](https://user-images.githubusercontent.com/17264765/81742241-a3883d80-9454-11ea-8768-ce299e6c5cc7.png)

Do  you know why this might be? I'm using the GTF file in my QuantSeq analysis, so I want to make sure it's based off of the Oly genome v.081, since I've used that in my alignment.

**Comment by kubu4** [comment]
@laurahspencer Unfortunately, I don't see what you're seeing. Using the files from the Genomic Resources wiki and the Stringtie GTF file, everything looks good on my end:

![image](https://user-images.githubusercontent.com/4514104/81758549-0094eb00-9477-11ea-90f8-8d58c0e29ed3.png)

**Comment by kubu4** [comment]
Sorry, responded too soon. Just looked at the same contig you posted above. Yes, I see that.

One thing to remember is that the genome annotations (i.e. decisions about gene/exon/intron/mRNA boundaries) has _not_ been manually curated. Same goes for Stringtie annotations. 

What you're seeing in Contig 79 is clearly a disagreement between what MAKER (which is the software that was used to annotate the genome) calls a gene/exon/mRNA and what Stringtie thinks is a transcript.

Unfortunately, without manually curating the genome annotations, you're going to encounter disagreements of this sort periodically.

**Comment by laurahspencer** [comment]
Good to know- but I can be confident that the Stringtie annotations are derived from the same Oly genome version (v.081)?

**Comment by kubu4** [comment]
Yes. Stringtie notebook entry:

https://robertslab.github.io/sams-notebook/2019/06/25/Genome-Annotation-O.lurida-(v081)-Transcript-Isoform-ID-with-Stringtie-on-Mox.html
