### ISSUE TITLE
Share Roberts Lab Experiment Database

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#927]
Cannot tell exactly who set this up but can someone share publically so anyone can view?
https://docs.google.com/spreadsheets/d/1nRSR_tgyslrJLXvKzhdtKx2iZLg1E7eKY0_-qzyS7OE/edit#gid=0

for reference 
https://github.com/RobertsLab/resources/wiki/Experiment-Database

**Comment by shellytrigg** [comment]
@sr320 i think it should be viewable to the public now

**Comment by sr320** [comment]
Yep thanks!
