### ISSUE TITLE
ship 2019 geoduck histo slide to URI

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#928]
@kaitlynrm can you confirm both slide sets (gonad slices from 20190123 and 20190221) are in 213? I see the 20190123 slides listed in the [histology database](https://docs.google.com/spreadsheets/d/1BIbDleJPEiKrmx7JwNIPwg2pM-thuZ39upmenldx4pA/edit#gid=0) but not the 20190221 slides.

**Comment by shellytrigg** [comment]
@sr320 is it OK for me to go into lab to get these slides? Or do we need to fill out paperwork for that?

**Comment by sr320** [comment]
For this, just email Andre and ask him if you can come in to pick up the slides to send out… cc me.
