### ISSUE TITLE
Obtaining UW pricing before submitting SAFS Purchase Form

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#93]
Currently, the only people able to view UW pricing from UW authorized vendors are @sr320 and myself. We can do this by logging into the UW purchasing system (eProcurement/Ariba) and viewing items.

Everyone else can only view pricing by visiting the vendor's website directly. The pricing listed there is "list price" and is highly inflated compared to the pricing discounts received by UW affiliates.

Filling out the SAFS Purchasing Form with the incorrect pricing may result in us paying significantly higher prices than we should be paying. I'd like to assume that when we submit a SAFS Purchasing Form that the purchasing person just uses eProcurement and we receive the proper pricing. However, I don't want to assume this. I will contact Lisa Smith (SAFS Purchasing person) and see what happens in this instance.

**Comment by sr320** [comment]
How can others see UW pricing?
Have Jessica set them up?

**Comment by kubu4** [comment]
Everyone would have to have eProcurement purchasing authorization. I don't know if you've asked Jessica to give anyone else authorization or not.

**Comment by kubu4** [comment]
Oh! I thought you were asking if Jessica has set them up already or not. Duh!

Yes, have Jessica set them up.

**Comment by kubu4** [comment]
Have confirmation with Lisa Smith that they look for vendor in eProcurement before submitting order to vendor. Thus, if the vendor is in the eProcurement system, we'd receive the appropriate pricing for UW affiliates.

However, using list pricing when submitting orders screws up accounting/budgeting on our end, as we would be recording prices in the Purchasing Log that are significantly higher than what we're actually paying.

So, it's still ideal to obtain UW pricing before submitting the SAFS Purchasing Form.
