### ISSUE TITLE
Separate upstream and downstream flanks

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#930]
In [this notebook](), I'm trying to separate upstream and downstream flanks. I created flanks with `flankBed`, and tried separating up and downstream flanks for forward and reverse strands using this code:

```
#Select forward strands
#Separate upstream and downstream flanks
!grep "+" Mcap.GFFannotation.flanks.gff \
| awk '{ if (NR%2) print > "Mcap.GFFannotation.flanks.forwardUpstream.gff"; \
else print > "Mcap.GFFannotation.flanks.forwardDownstream.gff" }'
```

I repeated this with reverse strands, then used `cat` to create an upstream track for all upstream flanks and a downstream track for all downstream flanks. Looking at IGV, I can tell this code does not work for all genes.

My guess is that some genes only have a single associated flank (up or downstream), so trying to separate every other flank entry as an upstream or downstream flank is causing these inconsistencies.

## How can I correctly separate upstream and downstream flanks for forward and reverse strands? 

Looking at [`flankBed` documentation](https://bedtools.readthedocs.io/en/latest/content/tools/flank.html) I tried using `-l` on its own, but that did not work.

![Screen Shot 2020-05-11 at 3 04 59 PM](https://user-images.githubusercontent.com/22335838/81616685-cbb26680-9398-11ea-979b-b30f46b0a49b.png)

**Comment by yaaminiv** [comment]
IGV file [here](https://github.com/hputnam/Meth_Compare/blob/master/genome-feature-files/Mcap-Genome-Feature-Tracks.xml), screenshots for reference:

good:
![Screen Shot 2020-05-11 at 3 09 40 PM](https://user-images.githubusercontent.com/22335838/81617035-7fb3f180-9399-11ea-9c37-c5a5b33710bb.png)

![Screen Shot 2020-05-11 at 1 35 03 PM](https://user-images.githubusercontent.com/22335838/81616851-264bc280-9399-11ea-897f-91dffec478b4.png)

bad:
![Screen Shot 2020-05-11 at 1 35 54 PM](https://user-images.githubusercontent.com/22335838/81616854-26e45900-9399-11ea-946d-abf89c4650c4.png)

**Comment by shellytrigg** [comment]
@yaaminiv I would not use your previous output to generate these. I would run flankbed again with the options 

for upstream flanks:
```
-l 1000
-r 0
-s
```

and for downstream flanks:
```
-l 0
-r 1000
-s
```

**Comment by yaaminiv** [comment]
@shellytrigg Thanks!!! Wish they had more pictures for how `-s` works in the documentation
