### ISSUE TITLE
Issues installing Salmon on MacOS

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#931]
Anyone else encounter issues installing Salmon on a Mac? I've tried to install from the source following the manual's instructions (build errors), and via Bioconda (out of date) & Homebrew (not available), and haven't been successful. The most recent Salmon version is 1.2.1, but they haven't released an OSX binary since 0.99.0 (which doesn't contain important selective-alignment math).

I'll keep trouble-shooting, but if anyone else has successfully installed Salmon recently on a Mac, please let me know which method you used!

**Comment by kubu4** [comment]
Can you please post error message(s)?

**Comment by kubu4** [comment]
Also, salmon is installed on Mox.

**Comment by sr320** [comment]
Kallisto is super easy on a Mac (and likely why I use it compared to Salmon)

**Comment by kubu4** [comment]
I've also installed the latest version of salmon on Emu and Roadrunner (the previous version installed on those computers was very old).

**Comment by laurahspencer** [comment]
Successfully installed Salmon today on my Mac. In short, yesterday I followed [install directions listed in their **manual**](https://salmon.readthedocs.io/en/latest/building.html#installation) and ran into issues. Today I followed [install instructions via Bioconda listed on their **website**](https://combine-lab.github.io/salmon/getting_started/#obtaining-salmon), and it worked like a charm (I also updated my OS to Catalina last night, but not sure if that was a factor). Moral of the story - follow instructions on the Salmon website for install on Mac via Bioconda, which is the following: 

```
conda config --add channels conda-forge
conda config --add channels bioconda
conda create -n salmon salmon
conda activate salmon 
```
Yesterday, I spent too much time trying to install Salmon following instructions on their user manual. Here is what I encountered: 
- The most recent OSX binary version is also out of date (v0.99.0, current version is v1.2.1), and the Linux releases don't work on OSX.  
- I tried to download the most recent release and install from the source, but ran into a couple configuration errors. For instance, here is text from the salmon/external/staden-io_lib/config.log file.  
- I also tried to install via Bioconda using `conda install --channel bioconda salmon`, but the version was was super out of date (v0.14.1).   

```
conftest.c:11:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
configure:3656: $? = 1
configure:3663: ./conftest
./configure: line 3665: ./conftest: No such file or directory
configure:3667: $? = 127
configure:3674: error: in `/Applications/bioinformatics/salmon-1.2.1/external/staden-io_lib':
configure:3676: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```
