### ISSUE TITLE
examples of how to make PCA and/or NMDS? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#932]
Assigning everyone, because I'm not sure who all has made these kinds of plots... 

I have gene expression data from individual crabs across time and want to make a figure of relatedness. 

Any examples from your own work of how to make a PCA and/or NMDS?

**Comment by yaaminiv** [comment]
NMDS code: https://github.com/RobertsLab/paper-gigas-DNR-proteomics/blob/master/analyses/7-SRM/2018-02-15-DNR-Paper-Figure/2018-02-15-DNR-Paper-Figure.R
PCA code: https://github.com/epigeneticstoocean/paper-gonad-meth/blob/master/code/04-methylkit.Rmd

Can also send code from the multivariate class!

**Comment by laurahspencer** [comment]
I've used the DESeq2 tutorial to compare expression by groups, and it includes some PCA plots which can be customized via ggplot tools: http://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html

From Julian's Multivariate class, here are materials related to PCA (and NMDS, PCoA). I think i've included all the data files needed to follow the tutorials - if you're missing something important let me know!:
[PCA-materials.zip](https://github.com/RobertsLab/resources/files/4631341/PCA-materials.zip)
