### ISSUE TITLE
Create another crab transcriptome (v3)

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#936]
For this one please use only pooled, stranded libraries. (no taxa filtering)

**Comment by kubu4** [comment]
Deets (all info is also on Genomic Resources wiki):

- [FastA](https://owl.fish.washington.edu/halfshell/genomic-databank/cbai_transcriptome_v3.0.fasta)

  - MD5 = `5516789cbad5fa9009c3566003557875`

- [FastA index](https://owl.fish.washington.edu/halfshell/genomic-databank/cbai_transcriptome_v3.0.fasta.fai)

- [BLASTx](https://gannet.fish.washington.edu/Atumefaciens/20200519_cbai_diamond_blastx_transcriptome_v3.0/20200518.C_bairdi.Trinity.blastx.outfmt6) (outfmt 6)

- BUSCO scores:

  - `C:97.6%[S:39.1%,D:58.5%],F:1.6%,M:0.8%,n:978`


Assembly notebook:

https://robertslab.github.io/sams-notebook/2020/05/18/Transcriptome-Assembly-C.bairdi-All-Pooled-RNAseq-Data-Without-Taxonomic-Filters-with-Trinity-on-Mox.html
