### ISSUE TITLE
2020 genewiz (individual crabs) transcript abundance with isoforms? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#941]
@kubu4 - 2 questions for you 

In Issue # [934](https://github.com/RobertsLab/resources/issues/934) you link a gene count matrix for the 2020 Genewiz individual crabs : https://github.com/RobertsLab/code/blob/master/r_projects/sam/20200430_cbai_deg_multiple_conditions/data/salmon.gene.counts.matrix 

1. I think this is from the transcriptome v. 1.5, yes? 

2. Also: is there a way to include the isoforms in that count matrix? I'm trying to `join` the counts with the transcriptome v. 1.5 `blast` output and uniprot-SP-GO for heat maps of genes of interest ([Rmd](https://github.com/RobertsLab/paper-crab/blob/master/scripts/annotate-indiv_crab-genecounts.Rmd)). 

This video ([here](https://d.pr/v/sf04NA)) shows that the tables can't be `join`-ed because the Trinity IDs for the individual crab counts are missing the isoforms (_i#), whereas the transcriptome `blast` output with uniprot-SP-GO Trinity IDs all have isoforms.

**Comment by kubu4** [comment]
1. Yes

See the [`README.md`](https://github.com/RobertsLab/code/blob/master/r_projects/sam/20200430_cbai_deg_multiple_conditions/data/README.md) in that R Project.

2. Yes, you can make a matrix of isoforms. Use the individual `quant.sf` files (also in that R Project).

**Comment by grace-ac** [comment]
Awesome! Thanks- I'll try it out and will re-open issue if i have q's

**Comment by kubu4** [comment]
You can either use the Trinity built-in script `abundance_estimates_to_matrix.pl` (this is installed on Mox).

or try out the R package `Tximport`.

**Comment by kubu4** [comment]
Also, I _do_ have the isoforms matrix, but am having technical difficulties that are preventing me from getting it to you ATM... Sorry!

**Comment by sr320** [comment]
The obvious disconnect here is we have annotation for - isoforms (as this is the fasta provided) thus count matrix really has no value for annotation if at “gene” level? UNLESS I am missing something?

**Comment by kubu4** [comment]
I think I follow what you're asking...

The `salmon.gene.counts.matrix` is not useful with the BLASTx results from the transcriptome FastA. Instead, you'd want `salmon.isoforms.counts.matrx`. I have this, but can't retrieve it at the moment (it's a longer story than is worth typing out why). However, it is quickly generated [using one of the two suggestions listed above](https://github.com/RobertsLab/resources/issues/941#issuecomment-631642468).

**Comment by grace-ac** [comment]
@kubu4 where is the `abundance_estimates_to_matrix.pl` script on mox? I tried looking through `/gscratch/srlab/programs/` ... `/gscratch/srlab/scripts/`...

**Comment by kubu4** [comment]
It's part of Trinity. While in `/gscratch/srlab/programs/` run the following:

`find . -name "abundance_estimates_to_matrix.pl"`

That should tell you where it is. Sorry, can't look it up ATM.

**Comment by grace-ac** [comment]
thanks! and no problem :)

**Comment by kubu4** [comment]
I see you reopened this, but no additional comment.

Anyway, if you want the isoforms matrix file that I generated when I made the gene counts file, it's on Mox in the following location:

`/gscratch/scrubbed/samwhite/outputs/20200501_cbai_salmon_to_matrix/salmon.isoform.counts.matrix`

**Comment by grace-ac** [comment]
ha, yeah - i forgot to comment why i was opening it. basically, i couldn't get the isoform matrix and just focused on other things yesterday. 

I thought it might be in there based on some of your notebook posts! trying to `rsync` it now, but it isn't working... could it be because I don't have access to `/gscratch/scrubbed/samwhite/outputs/` directory? 

`[graceac9@mox2 ~]$ cd /gscratch/scrubbed/samwhite/outputs/
-bash: cd: /gscratch/scrubbed/samwhite/outputs/: Permission denied
[graceac9@mox2 ~]$ `      



Here's what I put in to try to `rsync`, but it just keeps asking for my password, even though I'm able to log in to gannet on my web browser with the same password. 
`rsync --archive --progress --verbose graceac9@mox.hyak.uw.edu:/gscratch/scrubbed/samwhite/outputs/20200501_cbai_salmon_to_matrix/salmon.isoform.counts.matrix grace@gannet.fish.washington.edu`

**Comment by kubu4** [comment]
You need to specify the location on Gannet that you want to save the file:

> grace@gannet.fish.washington.edu

By default, `rsync` is trying to save to the root directory of Gannet. You need to tell it where to put the file, like the command where you told Mox where to find the file. Something like:

`grace@gannet.fish.washington.edu:/volume2/web/<your_folder_>/<desired_subdirectory>`

**Comment by grace-ac** [comment]
ah of course!! thanks

Now it's telling me:    

`The source and destination cannot both be remote.
rsync error: syntax or usage error (code 1) at main.c(1274) [Receiver=3.1.2]`

Here's what I put in: 
`[graceac9@mox2 gscratch]$ rsync --archive --progress --verbose graceac9@mox.hyak.uw.edu:/gscratch/scrubbed/samwhite/outputs/20200501_cbai_salmon_to_matrix/salmon.isoform.counts.matrix grace@gannet.fish.washington.edu:/volume2/web/hydatina`

**Comment by kubu4** [comment]
Sorry, I should have caught this previously. You can't use `rsync` to send files between two "remote" locations. You have to be on (in?) one of the locations.
