### ISSUE TITLE
Targeted BS Seq options?

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#942]
Talking with Tim G today re Targeted BS options.

He will try amplicon based approach but there must be some limitation? To my knowledge I have not come across any such approaches in the literature. 

The question being if there are only 20 genes you are interested in, what is the best way to get methylation data for those genes?

**Comment by kubu4** [comment]
Hmmmm. It certainly _seems_ straight-forward enough (i.e. bisulfite-treat DNA, PCR, PCR+barcodes-adaptors, sequence). The primer design is tricky though and you'd probably want/need to take some additional steps to verify that your primers are amplifying the expected targets (probably Sanger sequencing).

It doesn't seem particularly cost efficient, in regards to the amount of data that will be generated vs. what one would actually need for confidence in the coverage/results.

Depending on genome size, you could perform WGBS for a few grand and get sufficient sequencing depth/coverage for most genes in the genome.

However, if those targets are going to be assessed in numerous samples, it could be more cost efficient in the long run. Especially if only doing MiSeq or something on the 20 amplicons...
