### ISSUE TITLE
file of just counts for 2020 individual crabs somewhere?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#943]
### **Does a file of 2020 Genewiz individual crab RNAseq count data exist somewhere?** 

I may be mistaken... but I don't think that [individual_crab-salmon.isoform.counts.matrix](https://raw.githubusercontent.com/RobertsLab/paper-crab/master/data/individual_crab-salmon.isoform.counts.matrix) are counts... because there's decimals... 

`DESeq2` needs [un-normalized count data](http://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#why-un-normalized-counts) in order to run... and I'm currently getting this error:   

```
Error in DESeqDataSet(se, design = design, ignoreRank) : some values in assay are not integers 
```

Link to Rmd for this `DESeq` analysis: [DESeq-ABC-GHI.Rmd](https://github.com/RobertsLab/paper-crab/blob/master/scripts/DESeq-ABC-GHI.Rmd)

**Comment by sr320** [comment]
Just round those to integers

**Comment by grace-ac** [comment]
cool! done
