### ISSUE TITLE
Create Crab transcriptome Comparison table

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#944]

**Comment by kubu4** [comment]
Working on this, but I'm probably making it more complicated than it should be. Putting the table together is relatively quick, but figured I'd run some programs that are specifically designed for transcriptome assembly comparisons to get deeper insight. However, all of these programs require a transcriptome assembly of a related species.

I'm in the midst of assembling a blue crab transcriptome (couldn't find a previously assembled transcriptome for another crab species with a quick search), but hit a snag with Trinity. It appears to be a somewhat "common" issue, but doesn't have a generic solution. I'll probably have to send the partial Trinity results to the developer (based on previous responses to this type of problem).

With all of that said, I'll get an initial table put together to use as an initial means of comparison.

**Comment by kubu4** [comment]
Table attached.

In process of running more detailed transcriptome comparisons using software like DETONATE and TransRate.

Will also be running BUSCO built-in plotting tool for comparing BUSCO scores across multiple samples.

[20200526_cbai_transcriptome_comp.txt](https://github.com/RobertsLab/resources/files/4690689/20200526_cbai_transcriptome_comp.txt)

**Comment by kubu4** [comment]
Adding link to [Google Sheet version](https://docs.google.com/spreadsheets/d/1XAgU_xQKJjWk4ThJHn1wLDtPuW6X7s6Jjh_373bMc0U/edit?usp=sharing) to allow for updating.
