### ISSUE TITLE
Add Crab metadata to portal 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#949]
started a metadata record, attached to your "Data" folder, which you can find here (if you're logged in to the Research Workspace):  https://researchworkspace.com/project/2577354/folder/2577356 . 

We have a lot of online documentation to help, good ones for getting started are:

• For organizing your project/folders, see Working with Data Files
• And, if you need a jump-start in writing scientific metadata, see our Metadata Cheat Sheet.

**Comment by kubu4** [comment]
Was an OSF repo ever established for this project? Kind of looking for a more concise/focused set of tables/data/analysis to use for metadata without having to sift through the original crab GitHub repo.

**Comment by sr320** [comment]
No - I honestly am not even sure on what the “data” will be/is?
What were you thinking?

**Comment by kubu4** [comment]
Ha! Excellent question! That's why I was hoping we had an OSF repo with a canonical data set - then I could just provide all of that!

I need to read through more of the portal info to get a better feel about types of data they're expecting and where that data should be stored.

However, with that said, I imagine the data we provide should match the data that's discussed in the final report. Things like SRA accession numbers, transcriptome assemblies, and code for subsequent analysis discussed in the report. From some of what I've read so far, we'll definitely need a master spreadsheet detailing the crab sampling during the course of the experiment.

**Comment by sr320** [comment]
Certainly a master spreadsheet of all crab samples is of value to us (and should in the portal)

Maybe also a simple spreadsheet of RNAs-seq libraries?

**Comment by kubu4** [comment]
@grace-ac Is the [Chapter 2](https://docs.google.com/document/d/1xZjT_2ix39jhFGhPjUqjOIubCEZfnl9yDddIjR3nY38/edit) Google Doc the most up-to-date version of the crab paper?

**Comment by grace-ac** [comment]
No, I'm going to leave Chapter 2 as is. 

"New" version is: [here](https://docs.google.com/document/d/1L2Iil705Qu-GeZOtdV5STjDevfpHHHWcrgMiqw1Wn7Y/edit?usp=sharing) (also listed on Pubathon page)     

VERY bare bones, but will be used going forward.

**Comment by sr320** [comment]
@kubu4 you can use this as the primary datasheet...
https://github.com/RobertsLab/resources/issues/310#issuecomment-645607494

**Comment by kubu4** [comment]
> @kubu4 you can use this as the primary datasheet...
#310 (comment)

Are we leaving out qPCR Hemat copy number data or will that be in a different sheet?

**Comment by kubu4** [comment]
Adding link to  qPCR spreadsheet so that most of this stuff is in a single location:

https://docs.google.com/spreadsheets/d/1d17yg5F5gKKC66O8QkTIlPxljJeuX7ZsG46pkBr1lNQ/edit?usp=sharing

**Comment by kubu4** [comment]
@grace-ac Do we have a spreadsheet that indicates which crabs/tube numbers were used for RNAseq? If yes, could you please link in this issue? If not, could you please create and link in this issue? :)

**Comment by grace-ac** [comment]
Yep! The columns H and I tell which samples were sent and sequenced (column H = yes), and the starting quantity from qPCR (column I). 

https://docs.google.com/spreadsheets/d/1rNZHVpHgYLVX9--i4Wtsn_vDtrNcKauqa7WAYwDJ6D8/edit?usp=sharing 

Let me know if you need any clarifications on the spreadsheet!!

**Comment by kubu4** [comment]
Thanks. That only seems to include Genewiz samples. Also need samples used in pooled sequencing runs (with corresponding "SeqID" column in [nightingales](https://docs.google.com/spreadsheets/d/1_XqIOPVHSBVGscnjzDSWUeRL7HUHXfaHxVzec-I-8Xk/edit#gid=0&fvid=1528794880)).

**Comment by grace-ac** [comment]
Ah, right. I'll get those other sample lists for you - may take a bit!

**Comment by grace-ac** [comment]
here's sample information linked with SeqIDs for the samples I've submitted: 
https://docs.google.com/spreadsheets/d/1lSoG1U_Yjf5OmTuOcfxN5TUKCN16N1Ro1vVgLy1SNt4/edit?usp=sharing 

I'm looking through your notebooks to find which samples were used for libraries 304428, 329774, 329775, 329776, 329777 and will add those once I find them!

**Comment by grace-ac** [comment]
updated the spreadsheet with all samples for each library!

**Comment by kubu4** [comment]
@grace-ac For qPCR data shared above (https://docs.google.com/spreadsheets/d/1rNZHVpHgYLVX9--i4Wtsn_vDtrNcKauqa7WAYwDJ6D8/edit#gid=0), do you have Mean SQ data for all samples that were qPCR'd? If yes, where can I find that data?

**Comment by kubu4** [comment]
@grace-ac Any idea on the qPCR data question I posed last week?

**Comment by grace-ac** [comment]
Sorry! Forgot about this completely. I have this: https://github.com/RobertsLab/project-crab/blob/master/analyses/qpcr_hemat-new.csv

**Comment by kubu4** [comment]
Does that sheet have Mean SQ data for all samples that were qPCR'd?

**Comment by grace-ac** [comment]
ah, probably not - the number of rows is too low... i never ended up using that spreadsheet for anything, so it's probably best to base the means off of what Pam provided in the excel spreadsheet to get all samples

**Comment by kubu4** [comment]
@grace-ac Do you have code that you used for calculating mean Cq values previously? Would like to do this without "re-inventing the wheel", so to speak. 

If yes, can you please direct met to its location?

**Comment by grace-ac** [comment]
Yeah! Here's link to script: [here](https://github.com/RobertsLab/project-crab/blob/master/scripts/020520-hematqPCR_crabRNA.Rmd)

but basically I did: 

Made an object called "qpcr"; grouped rows by FRP (FRP is listed for each qPCR run), then mutate makes a new column (I think...?) called "sq_all.runs_mean"; and the means from the grouped FRPs is put in that column.... 

```{r}
qpcr <- qpcr %>%
  group_by(FRP) %>%
  mutate(sq_all.runs_mean = mean(sq))
```

**Comment by kubu4** [comment]
@grace-ac Do you know what the "run" column represents in these qPCR sheets? And, why are there multiple runs for a given FRP (e.g. one run without a tube number and then an additional run _with_ a tube number)?

**Comment by grace-ac** [comment]
I have some explanations of things from Pam in emails... digging through them now. Here's one comment that caught my eye:

>If a std was poor, I reran the samples on either side (on the curve) of the std (to get a better quantification), unless out of DNA. For unkn with 30- thru 34- in sample name, the DNA was extracted from the early plates (plates 30, 31, 32, 33 & 34) with the lumpy etoh-preserved blood -- that made getting a homogenous aliquot unlikely, which is probably a bigger error than those that occur on a qPCR run, so I kept that in mind when deciding whether to rerun a sample. For samples with 37- & 38- in sample names, the extracted material came from the aliquots of blood in RNAlater that you gave me.

**Comment by grace-ac** [comment]
@kubu4 which spreadsheet has one run without a tube number and then an additional run with a tube number?

**Comment by kubu4** [comment]
`20180518-Hemato_qPCR_results.xlsx`

Don't know if this in the repo or not. I think it's one that Pam sent over a couple of weeks ago.

**Comment by grace-ac** [comment]
i don't see any tube numbers in that one... i'm looking at the tab called "all runs"

**Comment by kubu4** [comment]
Ah! I was (am?) looking at the "As of 050218" tab. Probably makes more sense to look at that tab (duh)!

**Comment by kubu4** [comment]
Still, not sure what the "run" column indicates. For example how do we interpret the results from the selected rows here:

![Selection_065](https://user-images.githubusercontent.com/4514104/88701833-6c264600-d0bf-11ea-903c-f484c21f3d12.png)

**Comment by grace-ac** [comment]
hm... we may have to ask Pam about this.

**Comment by kubu4** [comment]
@grace-ac What does "FRP" actually stand for?

**Comment by grace-ac** [comment]
never thought to ask! it could be something Pam usually does with crabs, or it could be something ADF&G does since they were the ones that harvested them...

**Comment by kubu4** [comment]
From Pam:

>   FRP is Fisheries Resource Pathology. It's what a former boss called the Pathobiology group. After he left we went back to Pathobiology, but the databases stayed FRP. Too much trouble to change.
Pam

**Comment by kubu4** [comment]
@grace-ac Does the "Infection Status" column in the initial spreadsheet correspond to a crab (i.e. FRP) or to a hemolymph sample (i.e. tube numer)?

**Comment by grace-ac** [comment]
Crab (FRP). Samples to determine infection status were taken when the crabs arrived at facility and conventional PCR was done to determine infection status.

**Comment by kubu4** [comment]
@grace-ac Can you please point me to qPCR methods that I can copy to metadata portal?

**Comment by grace-ac** [comment]
yep! it's in the paper: 

https://docs.google.com/document/d/1dKwKKFfLoBPAswzMlaJ7Fk5BKDAN6C4ldv-6xpWIr9s/edit?usp=sharing

**Comment by kubu4** [comment]
Email from metadata portal person:

> Good morning!
> Awesome, this looks great, thanks for the edits.
>
> I edited your abstract a bit, if you could give it a quick look I'd feel better. In particular, can you confirm for me that your crab > > specimens from the 2017 Fall ADFG survey? Just want that to be absolutely correct before publishing.
> And that's it!
> thank you for your perseverance, I'm moving this project on from our side, so congrats to you and the team!
> If you have further questions or concerns, we'll be here so don't hesitate to reach out.
> 
> All the best,
> Adrienne

Confirmed that the Abstract looks good, so we're all set!
