### ISSUE TITLE
blast tutorial, step 7

### ISSUE THREAD

**Issue by meganewing** [RobertsLab/resources#951]
I'm trying to check the output of step 7 in the blast tutorial, which is to compare a sequence to a created database. The tutorial says to check the output with head, but when I run the head command nothing is returned. I've tried opening the .tab file created to check but the file was empty/blank. 
Is there something I'm doing/did wrong that is causing the output to be blank? 

Tutorial link and what I have in the terminal are listed below. 

I have a mac if that helps clarify anything.

https://github.com/eimd-2019/tutorials/blob/00f1062667608e1c6ece945d6e7bb44d520b8201/2019-07-09-Uniprot-blastx-Tutorial.md
(The file I used for example.fasta was the 'AC.fasta' file from this folder --> https://gannet.fish.washington.edu/spartina/2019-07-05-eimd/ )

---------------------------------------
```
Megans-MBP-3:~ meganewing$ /Users/meganewing/ncbi-blast-2.10.1+/bin/makeblastdb -in /Users/meganewing/BlastTutorial/example.fasta -dbtype prot -out uniprot_sprot_database2_DATE


Building a new DB, current time: 06/15/2020 16:20:48
New DB name:   /Users/meganewing/uniprot_sprot_database2_DATE
New DB title:  /Users/meganewing/BlastTutorial/example.fasta
Sequence type: Protein
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 1 sequences in 0.000285864 seconds.


Megans-MBP-3:~ meganewing$ ls
2020-06-15-Megan-uniprot-blastx.tab	uniprot_sprot_database2_DATE.pdb
2020-06-15-Megan-uniprot-blastx.tsv	uniprot_sprot_database2_DATE.phr
Applications				uniprot_sprot_database2_DATE.pin
BlastTutorial				uniprot_sprot_database2_DATE.pot
Desktop					uniprot_sprot_database2_DATE.psq
Documents				uniprot_sprot_database2_DATE.ptf
Downloads				uniprot_sprot_database2_DATE.pto
Library					uniprot_sprot_database_DATE.pdb
Movies					uniprot_sprot_database_DATE.phr
Music					uniprot_sprot_database_DATE.pin
Pictures				uniprot_sprot_database_DATE.pot
Projects				uniprot_sprot_database_DATE.psq
Public					uniprot_sprot_database_DATE.ptf
SimUText 2019-2020			uniprot_sprot_database_DATE.pto
ncbi-blast-2.10.1+
Megans-MBP-3:~ meganewing$ /Users/meganewing/ncbi-blast-2.10.1+/bin/blastx -query /Users/meganewing/uniprot_sprot_database2_DATE -out 2020-03-12-Megan-uniprot-blastx.tab -evalue 1E-10 -outfmt 6
BLAST query/options error: Either a BLAST database or subject sequence(s) must be specified
Please refer to the BLAST+ user manual.
Megans-MBP-3:~ meganewing$ /Users/meganewing/ncbi-blast-2.10.1+/bin/blastx -query /Users/meganewing/BlastTutorial/example.fasta -db /Users/meganewing/uniprot_sprot_database2_DATE -out 2020-03-12-Megan-uniprot-blastx.tab -evalue 1E-10 -outfmt 6
Megans-MBP-3:~ meganewing$ head /Users/meganewing/2020-03-12-Megan-uniprot-blastx.tab 
Megans-MBP-3:~ meganewing$ 
```

**Comment by kubu4** [comment]
Sorry for the delay in response.

Everything is correct, including your results. You have an empty output file which means your `blastx` job didn't have any matches in the database that fell within the criteria you specified.

To convince yourself that the commands actually worked, run the same command _without_ the e-value cutoff. You should get six matches (albeit, with poor e-values).

Additionally, if you ran the command and did _not_ receive an error message, then you can almost always be certain that things worked properly and that your output file/results are real.
