### ISSUE TITLE
unable to read in blastx outfmt6 from transcriptome v 3.1 into R

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#952]
Trying to read in the [blastx output transcriptome V3.1](https://gannet.fish.washington.edu/Atumefaciens/20200608_cbai_diamond_blastx_v2.1_v3.1/cbai_transcriptome_v3.1.blastx.outfmt6) into R to `join` with some gene lists I have. 

When I run this:       
```
blastout <- read.delim("https://gannet.fish.washington.edu/Atumefaciens/20200608_cbai_diamond_blastx_v2.1_v3.1/cbai_transcriptome_v3.1.blastx.outfmt6", sep = '\t', header = FALSE)
head(blastout)
```

I get this Error, and it doesn't work:      
Error in file(file, "rt") : cannot open the connection to 'https://gannet.fish.washington.edu/Atumefaciens/20200608_cbai_diamond_blastx_v2.1_v3.1/cbai_transcriptome_v3.1.blastx.outfmt6'

It also didn't work in my jupyter notebook.     
`!curl` didn't work in my [Jupyter notebook](https://github.com/RobertsLab/paper-crab/blob/master/notebooks/transcriptome_v3.1-blast-sep.ipynb).

**Comment by kubu4** [comment]
Jupyter notebook error suggests a certificate issue. Try using the error message suggestion of running `curl` with the `--insecure` argument.

With that said, I had no issues downloading the file using your `curl` command, nor when I used `wget`.

**Comment by grace-ac** [comment]
the `--insecure` worked perfectly! i literally didn't even read that far... thanks!
