### ISSUE TITLE
Analyze female new geoduck gonad histo pics with micrometer

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#953]
following protocol outlined here ([https://shellytrigg.github.io/183th-post/](https://shellytrigg.github.io/183th-post/)), quantify egg area and follicle area using ImageJ. 

Add the data to this spreadsheet (create new tabs and name 'male_date-photos-taken' and 'female_date-photos-taken' included): [HistologyScores.xlsx](https://drive.google.com/file/d/1T-wnwF4mptBODFvxzLTe3Bpz0ph2IrfD/view?usp=sharing)

**Comment by sr320** [comment]
Recall @H-Ra has made a lot of improvements on this front.

**Comment by shellytrigg** [comment]
can @H-Ra help with this?
