### ISSUE TITLE
Develop scoring protocol for male gonad histology

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#954]
@kaitlynrm got this up to this point:  [https://genefish.wordpress.com/2019/05/21/kaitlyns-notebook-quantifying-geoduck-histology/](https://genefish.wordpress.com/2019/05/21/kaitlyns-notebook-quantifying-geoduck-histology/)

Need to develop a similar scoring method through imageJ or some other software to quantify development in male gonad slides related to this issue https://github.com/RobertsLab/resources/issues/929

**Comment by sr320** [comment]
good to check in with @H-Ra protocols

**Comment by shellytrigg** [comment]
here's a link to Hana's notebook: [https://h-ra.github.io/](https://h-ra.github.io/)
