### ISSUE TITLE
Stats for crab v3.1 transcriptome

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#955]
What are median contig length, average contig length and N50 for v3.1

**Comment by kubu4** [comment]
I created a [Google Sheet](https://docs.google.com/spreadsheets/d/1XAgU_xQKJjWk4ThJHn1wLDtPuW6X7s6Jjh_373bMc0U/edit?usp=sharing) for these transcriptome stats (not sure why I didn't previously).

TL;DR:

Median: 1522
Average: 1825.11
N50: 2580

**Comment by grace-ac** [comment]
Is the column "genes(counts)" the same as the number of contigs?

**Comment by kubu4** [comment]
No. You want isoform data. The isoform data are direct measurements of all the data in the FastA file.

**Comment by grace-ac** [comment]
Ok! Thanks!
