### ISSUE TITLE
citation and version of MEGAN6 used to make bairdi transcriptome 3.1? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#957]
@kubu4 do you know which version of MEGAN6 you used to make transcriptome 3.1 (bairdi)? 

Also, do you know of the citation for it?

**Comment by kubu4** [comment]
Trimmed sequencing reads were functionally annotated with a combination of DIAMOND BLASTx (0.9.26; Huson et al. 2016) and MEGAN6 (6.18.3; Huson et al. 2016). Annotation with DIAMOND BLASTx was run against NCBI nr database (downloaded 20190925). The resulting DAA files were converted to RMA6 files for importing into MEGAN6 with the daa2rma utility, using the following MEGAN6 mapping files: prot_acc2tax-Jul2019X1.abin, acc2interpro-Jul2019X.abin, acc2eggnog-Jul2019X.abin. This work was facilitated through the use of advanced computational, storage, and networking infrastructure provided by the Hyak supercomputer system at the University of Washington.

To perform taxonomic classification, RMA6 files were imported into MEGAN6 using the default Naive LCA settings and the following mapping files: prot_acc2tax-Jul2019X1.abin, acc2interpro-Jul2019X.abin, acc2eggnog-Jul2019X.abin, acc2seed-May2015xx.abin. All mapping files were downloaded from the MEGAN6 website (https://software-ab.informatik.uni-tuebingen.de/download/megan6/old.html).

Huson, Daniel H., Sina Beier, Isabell Flade, Anna Górska, Mohamed El-Hadidi, Suparna Mitra, Hans-Joachim Ruscheweyh, and Rewati Tappu. 2016. “MEGAN Community Edition - Interactive Exploration and Analysis of Large-Scale Microbiome Sequencing Data.” PLoS Computational Biology 12 (6): e1004957.

Buchfink, Benjamin, Chao Xie, and Daniel H. Huson. 2015. “Fast and Sensitive Protein Alignment Using DIAMOND.” Nature Methods. https://doi.org/10.1038/nmeth.3176.

**Comment by grace-ac** [comment]
Thanks so much, Sam!!
