### ISSUE TITLE
Add Uniprot Accession #s to Oly gene.gff feature file 

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/resources#959]
We need to add uniprot access numbers to the Oly gene feature file ([.gff](https://github.com/sr320/paper-oly-mbdbs-gen/blob/master/genome-features/Olurida_v081-20190709.gene.gff?raw=true)) so @ksil91 and I can have a common list of genes to assess for enrichment, etc.

**Comment by kubu4** [comment]
I've finally had time to look at this a bit. Firstly, here're are corresponding UniProt IDs for each of the genes. It's a FastA file, but the headers have the corresponding gene name and it's UniProt ID.

https://gannet.fish.washington.edu/Atumefaciens/20190109_oly_maker_functional_annotation/20181127_oly_genome_snap02.all.maker.proteins.renamed.putative_function.fasta

I _think_ there's a script built-in to MAKER (the annotation/gene prediction software used to make the Oly GFF) to incorporate this info directly into the final GFFs. I just have to refresh my memory on how the whole thing works...

**Comment by sr320** [comment]
A list of Heare targets

```
CARM_comp7220_c0_seq2	Olurida_00013909-RA	87.671	511	13	3	1	1533	10	470	0.0	902
TLR_comp23747_c0_seq1	Olurida_00019635-RA	36.952	525	314	10	1603	65	205	724	5.02e-93	298
H2AV_comp25000_c0_seq1	Olurida_00000537-RA	64.286	98	33	2	645	355	79	175	9.59e-32	115
PGRP_comp24065_c0_seq1	Olurida_00010629-RA	85.294	272	2	1	84	899	171	404	4.76e-164	462
BMP2_comp7183_c0_seq1	Olurida_00003179-RA	100.000	421	0	0	506	1768	1	421	0.0	782
GRB2_comp10127_c0_seq1	Olurida_00000932-RA	80.180	111	20	1	371	703	2	110	2.01e-56	187
PGEEP4_comp6939_c0_seq1	Olurida_00002438-RA	91.289	287	1	1	394	1254	41	303	3.72e-160	463
CRAF_comp25313_c0_seq1	Olurida_00014696-RA	100.000	556	0	0	2277	610	1	556	0.0	1123
Actin_comp30443_c0_seq2	Olurida_00012924-RA	98.936	376	4	0	1353	226	1	376	0.0	779
HSP70_comp44273_c0_seq2	Olurida_00005351-RA	57.886	615	251	5	2130	298	34	644	0.0	704
```

**Comment by sr320** [comment]
https://github.com/sr320/nb-2020/blob/master/O_lurida/analyses/Olur_gene_UPacc.gff

```
Contig19646	maker	gene	40779	49671	.	-	.	OLUR_00000001;Q9IA16
Contig3	maker	gene	24250	27760	.	-	.	OLUR_00000003;Q9R1R2
Contig3	maker	gene	59654	70404	.	-	.	OLUR_00000005;Q9HCR9
Contig2	maker	gene	47324	50372	.	-	.	OLUR_00000007;P47238
Contig2	maker	gene	54928	65038	.	-	.	OLUR_00000008;A2BHJ4
Contig2	maker	gene	131900	137322	.	+	.	OLUR_00000009;Q49B93
Contig34578	maker	gene	126544	135381	.	+	.	OLUR_00000010;Q6BZG7
Contig22814	maker	gene	10285	30517	.	+	.	OLUR_00000011;Q7ZWA3
Contig22814	maker	gene	80061	105099	.	+	.	OLUR_00000014;Q9H0F5
Contig22814	maker	gene	103284	111624	.	-	.	OLUR_00000015;Q6IV57
Contig22814	maker	gene	107421	130584	.	+	.	OLUR_00000016;Q8CJ96
```

**Comment by sr320** [comment]
related here is a slop of Heare qPCR target https://raw.githubusercontent.com/sr320/nb-2020/master/O_lurida/analyses/Heare-PCRtargets-2kslop.gff
