### ISSUE TITLE
Update New COVID Health and Safety Plan

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#961]
Used the Tornabene lab template. So needs several revisions and customizations

https://docs.google.com/document/d/1UUBcdH3TZaXo-mOX_RXsrBZFwby0ctqShee4merHWPI/edit?usp=sharing

**Comment by sr320** [comment]
Here is the policy we need to be in minimum compliance with

**Comment by sr320** [comment]
points need to make sure addressed

Some minor comments:

1. Plan will be maintained on the SharePoint server too?
2. I may have missed it, but is there a statement what to do if a lab member feels that the safety plan is not followed?
3. Face coverings: didn’t that policy change? Isnt it now required in shared indoor spaces whether 6’ distance can be maintained or not, and also outdoors if it cant be maintained?
4. I seem to remember that Andre wanted a statement that work cannot proceed if PPE is not available

**Comment by kubu4** [comment]
1. ?

2. No.

3. In the lab-specific info, a face mask requirement is bolded in the "Personal hygiene and safety in the lab during “Stay Home, Stay Healthy” section. However, the SAFS policy only indicates:
 > "Cloth face coverings are required when indoors and others are present,..."

4. Yes, that requirement is listed in the SAFS policy.

**Comment by sr320** [comment]
1)  Needs to include the plan will live on the Lab Wiki and SAFS Sharepoint..

2) Statement needs to be added.

4) We need to make sure that phrase is listed in our plan.

**Comment by sr320** [comment]
Training https://www.ehs.washington.edu/training/covid-19-safety-training-back-workplace

**Comment by yaaminiv** [comment]
Added the safety + cloth face covering statement to the plan as well as the EH&S training
