### ISSUE TITLE
Trouble understanding BioAnalyzer results

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#966]
I got the following results from the BioAnalyzer when I ran some *C. virginica* sperm DNA samples:

![Capture2](https://user-images.githubusercontent.com/22335838/88115106-456d8a00-cb6a-11ea-836a-ad4265b5161d.PNG)

![Capture3](https://user-images.githubusercontent.com/22335838/88115109-47374d80-cb6a-11ea-81f6-c7ee4a7a3ec8.PNG)

### 1. @kubu4 (or anyone) Is there a guide to interpreting the results somewhere? I know I'm looking for where the peaks are, but I don't understand what [s] on the x-axis means (previously I've seen [bp] on that axis).

Also, I got an instrument error notification even though data were collected from all wells:

![Capture](https://user-images.githubusercontent.com/22335838/88115271-a2694000-cb6a-11ea-9f9a-23eec0f5f4fb.PNG)

### 2. Does this mean I should run the BioAnalyzer again?

**Comment by kubu4** [comment]
To change the axis from time (seconds) to size (bp) look for a button in the software that has a stop watch and ruler. That will switch between time and size. 

To me, it looks like sonication did not work. There are a variety of possibilities. Can review deets with you tomorrow and see if we can figure it out. I know I have an old notebook post somewhere where sonication failed and a subsequent remedy; that might be useful.

**Comment by yaaminiv** [comment]
Reran the BioAnalyzer this morning and ended up with similar crappy results and errors (ladder not reading, upper markers not detected, split peaks):

![Capture](https://user-images.githubusercontent.com/22335838/88238492-a95d8480-cc36-11ea-9502-c5ad234849dc.PNG)

Ran a blank chip (markers and ladders only) to confirm ladder wasn't degraded:

![Capture2](https://user-images.githubusercontent.com/22335838/88238627-ff322c80-cc36-11ea-897d-b560a47c7a2b.PNG)

Samples were also evaporated, meaning that they were more concentrated and had higher salt content. This could be affecting the split peaks. Will run a chip tomorrow after diluting an aliquot of each sample.

**Comment by yaaminiv** [comment]
Reran the BioAnalyzer and got the following results:

![Capture](https://user-images.githubusercontent.com/22335838/88323246-cd70a280-ccd6-11ea-91e2-8add7dde9aeb.PNG)

![Capture2](https://user-images.githubusercontent.com/22335838/88323250-cea1cf80-ccd6-11ea-9f03-5f1061c19c72.PNG)

The electropherograms look similar to one you ran previously:

![Capture3](https://user-images.githubusercontent.com/22335838/88323253-cea1cf80-ccd6-11ea-8fb7-b89482953a87.PNG)

@kubu4  Should I just assume I still have really concentrated DNA and proceed?

**Comment by kubu4** [comment]
I'm a bit confused what you are referencing regarding DNA concentration. Can you clarify what you're asking about DNA concentration in relation to the BioAnalyzer results?

Regardless, it looks like there are only a few samples that will require sonication:

- 6
- 12
- 57
- 48

Note, you will not be able to sonicate all of these using the same parameters, due to their differences in average fragment size. Each one will likely have to be done separately.


Then, the following samples show odd profiles. They're odd in their appearance: strange peak pattern _and_ they all look exactly the same:

- 9
- 13
- 31
- 63

I'm not exactly sure what's happening with these. Signal is low. Are they all very low concentrations?

**Comment by yaaminiv** [comment]
> Can you clarify what you're asking about DNA concentration in relation to the BioAnalyzer results?

Probably more confusion on my part interpreting the results. I remember you saying that if the concentration is too high it won't read properly on the chip. Seems like that's not the case for these samples...so ignore my previous comment.

> Note, you will not be able to sonicate all of these using the same parameters, due to their differences in average fragment size. Each one will likely have to be done separately.

Got it. Is there a systematic way of determining how many cycles to run each sample for? Or is it better to run a few cycles, check on a BioAnalyzer, and run again?

> I'm not exactly sure what's happening with these. Signal is low. Are they all very low concentrations?

Interestingly these are the four samples that were fully evaporated that I needed to reconstitute. Concentrations are [here](https://yaaminiv.github.io/Sperm-DNA-MBD-Enrichment-Day2/). 31 is my sample with the lowest concentration and 9, 13, and 63 are within the bounds of some of my other samples. For a sanity check, I can rerun the Qubit with these samples and then run it on the BioAnalyzer?

**Comment by yaaminiv** [comment]
@kubu4  Looking at my electropherograms again, 59 seems like it should be sonicated again (peak at 3000 bp). You suggested sonicating 48, but that peak is pretty level from 200 to 2000 bp. Will sonicating it again (even for a few cycles) degrade what are already smaller fragments?

**Comment by kubu4** [comment]
Yep, 59 needs to be sonicated again (sorry I missed that; previous response was written trying to view stuff on my phone).

In regards to 48, the mean peak size is much larger than ~350bp; that's why it needs to be sonicated again.

**Comment by yaaminiv** [comment]
I reran the samples after shearing but there was an issue detecting the upper marker with one sample, so I can't change from s to bp. Here are the electropherograms and gels:

![Capture2](https://user-images.githubusercontent.com/22335838/88716339-c92bf700-d0d3-11ea-881c-c08aea6e0e9a.PNG)

![Capture3](https://user-images.githubusercontent.com/22335838/88716341-ca5d2400-d0d3-11ea-9bad-17dda66d1e76.PNG)

And here is the electropherogram from my previous run with s instead of bp:

![Capture](https://user-images.githubusercontent.com/22335838/88716298-bb767180-d0d3-11ea-9a78-53a91fc7b17c.PNG)

Could I use my previous electropherogram to estimate what the fragment size of my samples are for my most recent run? We only have 1 HS chip left (but we have other DNA chips...could I use those for a HS assay) so I don't want to use another chip if there's a way to salvage these results.
