### ISSUE TITLE
put hatchery microbiome 'omics data in repositories

### ISSUE THREAD

**Issue by emmats** [RobertsLab/resources#968]
@kubu4 needs to submit metagenomics data to SRA and emma needs to submit metaproteomics data to PRIDE. post accession numbers here when complete.

**Comment by kubu4** [comment]
Metagenomics have been submitted to NCBI SRA:

- https://www.ncbi.nlm.nih.gov/bioproject/PRJNA649049

Will add this to manuscript in just a moment....

**Comment by emmats** [comment]
Metaproteomics are on PRIDE (not public at this very moment, but logging on now to make public)
Project Name: Washington state shellfish hatchery microbiome
 Project accession: PXD020692

**Comment by emmats** [comment]
Metaproteomics dataset is not public because PRIDE has changed their protocol and will not allow making public until there is a corresponding pubmed ID or DOI. This is stupid.

**Comment by kubu4** [comment]
Could put data on OSF and create DOI?

https://help.osf.io/hc/en-us/articles/360019931013-Create-DOIs

**Comment by emmats** [comment]
This would be a separate location for all the data files? 
I can make the dataset accessible to reviewers and then publish it as soon as the paper is accepted. Unless Steven really needs it public now, I'd prefer to save myself the extra work.

**Comment by kubu4** [comment]
Yes, it would be a separate location for the data files. The only work required would really be just uploading the files.

> I can make the dataset accessible to reviewers and then publish it as soon as the paper is accepted.

Then why did you re-open this issue?

**Comment by emmats** [comment]
In case someone tried to look at it before publication. I didn't want there to be any confusion as to why it isn't public yet.

**Comment by kubu4** [comment]
Gotcha. For future reference, you can comment on closed issues (like this). :smiley:
