### ISSUE TITLE
assist with literature search for single cell data

### ISSUE THREAD

**Issue by mgavery** [RobertsLab/resources#969]
I am looking to solicit some help with the scRNA-Seq data for gigas embryos.  I'm pretty focused on germline clusters, but no idea what the other clusters are (like the cool cluster highlighted in the UMAP), but I do I have a list of 'marker genes' for each cluster.  If anyone has time/was interested in doing a bit of searching around in the literature for these genes in order to interpret function in very early bivalve embryos, please let me know.  Thanks!

![Pacific_oyster_scRNA-Seq_r2_-_Google_Docs](https://user-images.githubusercontent.com/4512578/88438734-41d24100-cdbe-11ea-943b-89fd8d20f0b8.png)

**Comment by sr320** [comment]
@mgavery can you provide the list of marker genes here?

**Comment by mgavery** [comment]
[top25markers_allcells_072720.txt](https://github.com/RobertsLab/resources/files/4984276/top25markers_allcells_072720.txt)

**Comment by mgavery** [comment]
These are top 25 'specific' genes for each cluster (some clusters don't have genes with high specificity).  Cluster 7 is the interesting one to start with.  There is another way to identify genes and that is by gene modules.  I can pull that data together next week if I can't get to it today.

**Comment by mgavery** [comment]
[geneModules_allcells_072720.txt](https://github.com/RobertsLab/resources/files/4984872/geneModules_allcells_072720.txt)
![heatmap_genemodules_072720](https://user-images.githubusercontent.com/4512578/88598701-b2779880-d01e-11ea-8986-3fda64f026de.png)
This one isn't as straight forward, but if the focus is on cluster 7 then, based on the heatmap, module 12 genes are the ones to focus on.

**Comment by sr320** [comment]
@mgavery do you only have protein names, eg no associated IDs?

**Comment by meganewing** [comment]
I've been primarily searching for the different genes on UniProt, but are there any other websites or sources that would be good to look into? A plain google search of the different genes mostly just has UniProt results.

**Comment by mgavery** [comment]
I used the RefSeq annotations file associated with the genome so there are no associated ID's.  Giles did a blast for me, but this included multiple databases so ID's not consistent.  Would these blast results files be helpful?

**Comment by sr320** [comment]
Yes those blast results would be helpful

**Comment by mgavery** [comment]
[bestblast_.zip](https://github.com/RobertsLab/resources/files/5024255/bestblast_.zip)

There are 2 files in here because I haven't merged the LOC# (from my single cell data) with the ID# associated with the blast table, but that merge is possible with the "LOC_seqID_key" file.

**Comment by sr320** [comment]
@mgavery my take is you are looking for a functional description for each cluster (excluding the germline clusters you have undercontrol)? 

or just a binning of all genes into some meaningful category?  Also do you have fasta file for each cluster?

**Comment by mgavery** [comment]
[GCF_000297895.1_oyster_v9_cds_from_genomic.fna.gz](https://github.com/RobertsLab/resources/files/5029803/GCF_000297895.1_oyster_v9_cds_from_genomic.fna.gz)

This fasta is transcript level (i.e. may have >1 sequence per LOC ID number)

**Comment by mgavery** [comment]
Yes, ideally looking for cell-type identification of each cluster.  If this were an adult oyster sample it would be something like, cluster 7 is muscle, clusters 6-9 are different hemocyte populations etc.  However, because these are very early embryos (up through blastula) these clusters may be harder to define.  Regardless, it will likely take manual curation of the marker genes from each cluster to try to identify cell types.

**Comment by mgavery** [comment]
This paper from urchin gastrula might be helpful [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6690749/].  Supplement shows the marker genes for each cluster.

**Comment by mgavery** [comment]
@sr320, per our discussion yesterday: For the purposes of cell type identification it makes the most sense to limit the cells to the blastula library (this is the latest developmental stage we sampled).  These cells are going to be the most 'differentiated'.  We can still visualize these blastula clusters in the context of all the cells.  For example, in the UMAP below (1st plot) all cells are plotted but only cells from the blastula sample are colored and they are labeled by their associated cluster in the blastula only UMAP (2nd plot).  This means if I'm looking to identify the cell type of cluster 7 as mentioned in the first post, I would look at genes in the 'top marker' and 'gene module' files for cluster 6 of the blastula only data.
![allcellsUMAP_labeledBYblasutaClsuters](https://user-images.githubusercontent.com/4512578/89689774-f8075180-d8b9-11ea-9606-2c7884de3ed4.png)

<img width="555" alt="Pacific_oyster_scRNA-Seq_r2_-_Google_Docs" src="https://user-images.githubusercontent.com/4512578/89689915-3d2b8380-d8ba-11ea-9401-8384f866d4e4.png">

**Comment by mgavery** [comment]
Below are files containing the 30 top marker genes for each blastula cluster and also the gene module analysis. 

[blastulaOnly.genemodules.txt](https://github.com/RobertsLab/resources/files/5043736/blastulaOnly.genemodules.txt)
[blastulaOnly.topmarker.txt](https://github.com/RobertsLab/resources/files/5043738/blastulaOnly.topmarker.txt)

Here is the heatmap which associates the clusters with the gene modules
<img width="580" alt="blastulaOnly_genemodules_png_and_allcellsUMAP_labeledBYblasutaClsuters_png" src="https://user-images.githubusercontent.com/4512578/89690200-cba00500-d8ba-11ea-9ff1-b87a1f3afc60.png">

**Comment by mgavery** [comment]
Update: 
1. I will have to provide new topmarker files for the blastula samples.  I've remapped the data to include the mitochondrial genes.  I will do that today.
2. This sea urchin paper may also be helpful for annotations.  I'll check with the authors today to see if I can get marker genes for each cluster.
[https://www.biorxiv.org/content/10.1101/2020.11.12.380675v1.full](url)

**Comment by sr320** [comment]
I am going to close this issue and lets re-open with a defined next step as we have some major complications with this path as the LOC # are not matching
