### ISSUE TITLE
pH Buffer solutions: from Mettler Toledo

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#97]
There's [these](https://www.mt.com/us/en/home/products/Laboratory_Analytics_Browse/pH/buffers/pH_buffers/technical_buffers.html) that the manual recommends purchasing. 
![screen shot 2017-10-12 at 2 07 17 pm](https://user-images.githubusercontent.com/14934314/31519268-c10e8322-af56-11e7-82c6-73211af0c941.png)

If we don't want to, other buffers that we have will likely work...?

**Comment by sr320** [comment]
Order the recommended ones...

**Comment by grace-ac** [comment]
@kubu4 do you know what the UW price is for these and #98 ?

**Comment by kubu4** [comment]
Metler Toledo is not in the UW system, so use list price. See #98 for UW pricing on that item.

**Comment by grace-ac** [comment]
@sr320 - I emailed you two PDFs of purchasing forms for this and for #98
