### ISSUE TITLE
optimize + control qPCR primers for gduck repro. dev. assessment

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#970]
related to https://github.com/RobertsLab/resources/issues/864

We still need a positive expression control since neither of the two housekeeping genes (RPL5  and TIF3s6B) produced acceptable melting curves.

@kubu4 do you think redesigning primers would improve the melt curves for RPL5 and TIF3s6B? 

If so, the full seqeunces for RPL5 and TIF3s6B can be found here: https://docs.google.com/spreadsheets/d/1vkUQvqNUN-9ntv0NoVDAtD8zA-p9e3xosGwsWSFV0qk/edit#gid=0

Alternatively, @SamGurr had designed some positive expression qPCR primers in geoduck using your protocol, but did not end up ordering them yet because he's doing RNAseq instead of qPCR now. @SamGurr could you paste the details about the primers you designed?

**Comment by SamGurr** [comment]
Here are primers from five possible 
normalization genes -each has the primer3 and emboss outputs. https://github.com/SamGurr/Pgenerosa_primers/tree/master/qPCR/Primer3_EMBOSS/Normalization_genes

**Comment by shellytrigg** [comment]
awesome thanks @SamGurr! I suggest we avoid GAPDH, Actin, and Tubulin to avoid transcripts that may be influenced by the pCO2 treatment, but the other two seem like good candidates.

**Comment by kubu4** [comment]
> We still need a positive expression control

You want some target(s) for normalization, is that correct?

I can't remember how the original sets of primers were selected. Presumably they were selected based off of some RNAseq data that suggested their expression doesn't change in response to some experimental treatment?

> do you think redesigning primers would improve the melt curves for RPL5 and TIF3s6B?

Certainly a possibility. Do you know where Kaitlyn's primer design notebook entry is? Do you know if she BLASTed the primers against the genome?

Also, looking at the spreadsheet you linked in your initial post, it seems like there are some additional primer sets that look good (e.g. TIF3s8_FWD/REV-1, TIF3s12_FWD/REV). Why not use them?

**Comment by shellytrigg** [comment]
> > We still need a positive expression control
> 
> You want some target(s) for normalization, is that correct?
> 

That is correct. We just need one primer pair that is reliable for normalization.

> I can't remember how the original sets of primers were selected. Presumably they were selected based off of some RNAseq data that suggested their expression doesn't change in response to some experimental treatment?

The original sets of normalization primers were selected based on the normalizing genes targeted in this paper: https://bioone.org/journals/journal-of-shellfish-research/volume-34/issue-1/035.034.0110/Biochemical-And-Histochemical-Changes-Associated-with-Gonad-Development-of-the/10.2983/035.034.0110.short
> 
> > do you think redesigning primers would improve the melt curves for RPL5 and TIF3s6B?
> 
> Certainly a possibility. Do you know where Kaitlyn's primer design notebook entry is? Do you know if she BLASTed the primers against the genome?

I found Kaitlyn's notebook post here https://genefish.wordpress.com/2020/01/23/kaitlyns-notebook-geoduck-reproductive-development-primer-design/ . It does not seem like EMBOSS was run successfully according to her notes, but I can't find her jupyter notebook. 

> Also, looking at the spreadsheet you linked in your initial post, it seems like there are some additional primer sets that look good (e.g. TIF3s8_FWD/REV-1, TIF3s12_FWD/REV). Why not use them?

Based on Kaitlyn's qPCR results (https://genefish.wordpress.com/2020/02/12/kaitlyns-notebook-testing-new-primers-on-geoduck-hemolymph-rna/), we collectively decided that RPL5_FWD/REV and TIF3s6B_FWD/REV primers gave better results with lower Cq values (18.5 and 18.2, respectively) that TIF3s8-FWD/REV-1 and  TIF3s12_FWD/REV (Cq values 36 and 32.4, respectively).

**Comment by kubu4** [comment]
If expression isn't expected to change with treatment(s), then I wouldn't expect the Cq values for TIF3s8-FWD/REV-1 and TIF3s12_FWD/REV to change. So, having Cq values of 36 and 32.4 should be fine. Admittedly, I'd go for TIF3s12_FWD/REV. That could accommodate ~100 fold change in expression (i.e. increase of 6.62 Cq) and still be detectable.

**Comment by shellytrigg** [comment]
Ok, let's plan to use TIF3s12_FWD/REV. It would be great to test this pair with NTC and with the cDNA pool you used previously. But I'm not sure it makes sense to run the qPCR just for only a few reactions. What do you think @kubu4 ?

**Comment by kubu4** [comment]
Nothing wrong wrong with running qPCR with only a few samples. No resources are wasted.

I'll drop in tomorrow to run them.

**Comment by kubu4** [comment]
Tested `TIF3s12_FWD/REV`, `TIF3s8-FWD/REV-1` (and, accidentally, `TIF3s8-FWD/REV-2`).

`TIF3s8-FWD/REV-1` will be the one to use. Cq ~32, and excellent melt curve.




Notebook:

https://robertslab.github.io/sams-notebook/2020/07/29/qPCR-Testing-P.generosa-Reproduction-related-Primers.html
