### ISSUE TITLE
lab website inconsistent with .md files

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#973]
@sr320 I  recently updated the [People.md](https://github.com/RobertsLab/website/blob/master/People.md), [Products.md](https://github.com/RobertsLab/website/blob/master/Products.md), and [Publications.md](https://github.com/RobertsLab/website/blob/master/Publications.md), but I do not see the changes reflected on the [website](https://faculty.washington.edu/sr320/). 

Does another step need to happen before the website reflects the changes to the .md files?

**Comment by sr320** [comment]
Still a manual step involved. I should be able to get to today.

**Comment by sr320** [comment]
done!
