### ISSUE TITLE
Potassium Hydrogen Phthalate

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#98]
We need 50 mg of it.

From [Fisher](https://www.fishersci.com/shop/products/potassium-hydrogen-phthalate-primary-standard-meets-acs-specifications-fisher-chemical-3/p-219337#?keyword=potassium+hydrogen+phthalate), there are 100g and 500g glass bottles. 

![screen shot 2017-10-12 at 2 12 07 pm](https://user-images.githubusercontent.com/14934314/31519470-61542d50-af57-11e7-9049-3b78a8408dea.png)

**Comment by sr320** [comment]
500g please

**Comment by kubu4** [comment]
$105 is UW pricing.

**Comment by grace-ac** [comment]
@kubu4 will Lisa accept it if I put them all on one request sheet? or should i separate by vendor?

**Comment by kubu4** [comment]
Don't know. The sheet only has one spot for a single vendor...

**Comment by grace-ac** [comment]
I'll just do it separate just in case! thanks
