### ISSUE TITLE
Upload DecaPod podcast audio files to Research Workspace and add metadata for each file

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/resources#981]
Upload the audio files here (the "Media Products" folder):

https://researchworkspace.com/project/2577354/folder/2577357/media-products

Add metadata for each file under the `Resource Content/Data Tables` section.

Don't worry about other sections of the metadata.

**Comment by grace-ac** [comment]
added all episodes! have one more i'll edit and post and add to portal this week.
