### ISSUE TITLE
qPCR pilot samples for geoduck repro dev. assay

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#982]
Run qPCR on the following samples using APLP fwd/rev and TIF3s8-1 fwd/rev

cDNA Samples are stored in the -20C fridge in 209 in 20190107 Kaitlyn’s Box (https://genefish.wordpress.com/?s=kaitlyn).

**Sample\_name**|**Sex**|**Stage**
:-----:|:-----:|:-----:
19|F|2
21|F|2
27|M|2
28|M|1
31|F|4
37|F|6
39|F|5
43|M|4
54|M|3
57|F|7
59|M|4
61|F|7
55(2)|F|3
1|Unk|Unk
2|Unk|Unk
11/15 H Chewy|Unk|Unk
11/15 H Star|Unk|Unk
11/21 H Chewy|Unk|Unk
11/21 H Star|Unk|Unk

Known sex/stage sample details are here:
https://docs.google.com/spreadsheets/d/1IJVpFhyLKabC_9cItnaJGcOipiFOX6706xwPo95lNNQ/edit#gid=0

And unknown sex/stage sample details here:
https://docs.google.com/spreadsheets/d/14GpBXCQZ1uL6NdVoEY7kvbsFv9_SfMY7Ozbd6cqj684/edit#gid=0

**Comment by kubu4** [comment]
Alrighty, ran those qPCRs. Notebook is here:

https://robertslab.github.io/sams-notebook/2020/08/06/qPCR-P.generosa-APLP-and-TIF3s8-1-with-cDNA.html

However, using `TIF3s8-1` as a normalizing gene is not going to work, as it failed to amplify in most samples,

NOTE: `APLP` _did_ amplify in many of the samples that `TIF3s8-1` did not amplify in - so lack of amplification with `TIF3s8-1` isn't due to a general problem with the samples themselves).

**Comment by shellytrigg** [comment]
Interesting, it seems like we need to redesign the normalization gene primers since none of our current primer pairs are optimal. I suggest we just target RPL5 (PGEN_.00g287540-vv0.74.a). 

Because the sequence is coming from a gene fasta, do we need to confirm that we are target coding regions and not regions that might get spliced out? Or does the software take this into account?

**Comment by shellytrigg** [comment]
Also, not sure the APLP qPCR product is going to distinguish male from female as the APLP protein did in Emma's paper. I'm wondering if we are amplifying sequence that corresponds to the actual peptide sequences she identified.
![APLP_qPCR_results_known_samples](https://user-images.githubusercontent.com/4720221/89573319-47c51a80-d7df-11ea-8305-53a52ebdf483.jpg)

![](https://user-images.githubusercontent.com/4720221/70191630-3d7dda00-16ae-11ea-9790-7e32d8e5688b.png)

**Comment by kubu4** [comment]
> do we need to confirm that we are target coding regions and not regions that might get spliced out?

We don't need to, but it's certainly ideal. We do know that APLP _does_ amplify gDNA. Usually, due to the relatively small size of the qPCR amplicons, that indicates that there aren't any introns present in the targeted region. However, [we can see that the melt curve differs slightly between cDNA and gDNA](https://robertslab.github.io/sams-notebook/2020/07/23/qPCR-Testing-P.generosa-Reproduction-related-Primers.html), suggesting that the region being targeted might differ between gDNA and cDNA.

> Or does the software take this into account?

Nope. The software is, essentially, BLASTing the primers against whatever sequences you provide it with.


> as the APLP protein did in Emma's paper.

Can we see this from that heatmap you posted above? I don't see APLP anywhere on there.

**Comment by shellytrigg** [comment]
APLP (PGEN_.00g070040-vv0.74.a) is the gene from where the vitellogenin peptides (cds.comp144315_c0_seq1|m.50928) Emma identified came. The actual peptide transitions in the heatmap are the vitellogenin amino acid sequences SPDGSPSMDIEK and TVSPMEQELLK (listed in table S4 https://pubs.acs.org/doi/suppl/10.1021/acs.jproteome.7b00288). 

The APLP gene was retrieved from tblastn using the cds.comp144315_c0_seq1|m.50928 fasta sequence as described here (https://github.com/RobertsLab/resources/issues/822). 

When I tblastn the cds.comp144315_c0_seq1|m.50928 fasta to the PGEN_.00g070040-vv0.74.a fasta I get the following 4 hits: https://github.com/shellytrigg/P_generosa/blob/master/amb_v_constantlow_brood_data/qPCR/NCBI_Blast_cds.comp144315.pdf

Here's the protein sequence for cds.comp144315_c0_seq1|m.50928 with blast hits and peptide transition sequences (denoted as "Pep_mark_1" and "Pep_mark_2") annotated:  https://github.com/shellytrigg/P_generosa/blob/master/amb_v_constantlow_brood_data/qPCR/cds.comp144315_c1_seq1_prot.pdf

Here's the DNA sequence for PGEN_.00g070040-vv0.74.a with the blast hits and APLP primer sequences/qPCR product annotated. ORFs are also annotated in orange and green. I also annotated where one peptide transition sequence should be (denoted as "probable_pep_mark_2") although this sequence was not really a blast hit. https://github.com/shellytrigg/P_generosa/blob/master/amb_v_constantlow_brood_data/qPCR/PGEN_.00g070040-vv0.74_dna.pdf

**All that to say:**

-  our current primers target a region far downstream (~ 20kb) of the peptides Emma identified from the same gene. 

- The peptide sequences Emma identified are not blast hits in the gene fasta 

**Moving forward, we can:**

A. redesign primers to attempt to target the specific region around where we think the peptide transition should be (e.g. the end region of blast_hit_1 like somewhere between 5600-5697 bp in the PGEN_.00g070040-vv0.74.a sequence).
     - we have to redesign the normalization gene primer anyways
     - this might give us a better shot at distinguishing between male and female samples (unless we don't care about this)

B. continue with our current APLP primers and hope the real samples show more consistent results
     - although not distinguishing between male and female, the trend generally shows increasing expression with stage with the exception of samples 27 and 37
     - these pilot samples are pretty old and could contain contamination from other tissues so maybe the real samples will show cleaner results

**Comment by shellytrigg** [comment]
decided to just redesign and order primers for the normalization genes and will repeat pilot qPCR with the new normalization genes once we test the new normalization gene primers
