### ISSUE TITLE
microbial community taxa influenced by pCO2

### ISSUE THREAD

**Issue by emmats** [RobertsLab/resources#984]
I just read this paper: http://plymsea.ac.uk/id/eprint/5564/1/Roy%20et%20al%20Biogeosciences%202013.pdf
They found that there was no overall impact of pCO2, except in 15 rare taxa. They used 16S data. I'm wondering if we can replicate part of their analysis to see if we can detect a similar signal in our data @kubu4 
Here is the paragraph from their methods that describes what I think we could replicate. Wondering if MEGAN can do something similar?
<img width="338" alt="Screen Shot 2020-08-07 at 11 47 07 AM" src="https://user-images.githubusercontent.com/4564812/89678491-1c583380-d8a4-11ea-9eff-ec5a92143840.png">

**Comment by kubu4** [comment]
MEGAN cannot do this type of statistical analysis.

However, I'd think this should be doable outside of MEGAN.

**Comment by kubu4** [comment]
Per today's meeting, I'll play around with this type of analysis.
