### ISSUE TITLE
Losing DNA doing ethanol precipitations?

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#985]
I am preparing samples for WGBS. 5 samples had DNA concentrations < 20 ng/µL, so I followed [this ethanol precipitation procedure](https://github.com/RobertsLab/resources/blob/master/protocols/ethanol_precipitation_DNA.md). When I measured my DNA concentrations on the Qubit, I somehow lost DNA? Did I do something wrong when doing my ethanol precipitations? [Here](https://yaaminiv.github.io/WGBS-Samples-Part6/) is my lab notebook post. I (stupidly) didn't save any of the supernatant when I was doing these, so unless I re-extract DNA from the samples I don't have any way of getting it back. I just want to ensure that I don't make a mistake the next time I do these precipitations!

**Comment by kubu4** [comment]
You will always lose some DNA when doing EtOH precipitation.

**Comment by yaaminiv** [comment]
@kubu4 Darn. I’ve now lost so much DNA I can’t use those samples anymore. I’ll look into re-extraction. Is there a better way to concentrate DNA and not lose so much?

**Comment by shellytrigg** [comment]
That's like a 50% loss each time though, which seems like a lot. It would likely help to incubate initially for a longer time in the freezer with 100% EtOH then spin at 4C for 30 min to avoid degradation that could occur at room temp. Check out this article for some tips: 
https://bitesizebio.com/2839/dna-precipitation-ethanol-vs-isopropanol/#:~:text=DNA%20is%20less%20soluble%20in,faster%20even%20at%20low%20concentrations.&text=Using%20ethanol%2C%20the%20final%20concentration,2-2.5%20volumes%20of%20sample.

I'm sorry for your loss @yaaminiv , thats frustrating.

**Comment by kubu4** [comment]
Speed Vac is the only way to concentrate without loss of DNA.

**Comment by shellytrigg** [comment]
You could always test your % loss from EtOH vs Isopropanol vs speedvac with DNA that you have a lot of (e.g. BR standard DNA from qubit kit if there is extra) to decide what concentration method you want to use and estimate the starting amount you'd need

**Comment by yaaminiv** [comment]
Thanks for the tips! I'll keep this in mind if I ever have to do an ethanol precipitation in the future.
