### ISSUE TITLE
Obtain RNA-seq quote

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#986]
For 32 samples (coral); stranded libraries.

**Comment by kubu4** [comment]
Do you happen to have genus/species?

**Comment by kubu4** [comment]
Oh, and estimated genome size?

**Comment by kubu4** [comment]
Coral: _Pocillopora verrucosa_

Size: 245Mbp

Per lab meeting discussion.

**Comment by kubu4** [comment]
Genewiz:

- $11,376

- 15 - 20 business days turnaround.

**Comment by kubu4** [comment]
Zymo:

- $10,400

**Comment by sr320** [comment]
@kubu4 can you get a corresponding PO for Genewiz on 61-0552

**Comment by hputnam** [comment]
@kubu4 Here are the quotes for Genewiz. Could you please request POs? Thank you!

[30-409963846_RNASeq_Stranded.pdf](https://github.com/RobertsLab/resources/files/5209211/30-409963846_RNASeq_Stranded.pdf)
[30-409975266_R9_BSSeq.pdf](https://github.com/RobertsLab/resources/files/5209212/30-409975266_R9_BSSeq.pdf)

**Comment by kubu4** [comment]
CR51281 - 30-409963846

CR51282 - 30-409975266

**Comment by hputnam** [comment]
@kubu4 Can you please send your fiscal contact information (name, email, phone) for where the POs are paid through? Genewiz is trying to bill these two POs but has send to the URI email instead. Thank you!

**Comment by kubu4** [comment]
Genewiz will need to submit via the Ariba eProcurement system. Instructions are supplied with the purchase order that gets sent to them upon order initiation.

That's about all I can help with. They can send an email to `pcshelp@uw.edu`, if they need help.

**Comment by hputnam** [comment]
Thank you!
