### ISSUE TITLE
where did indiv. crab count data come from? 

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#989]
- Where did this file come from: https://github.com/RobertsLab/paper-crab/blob/master/data/salmon.isoform.TMM.EXPR.matrix ?       
- What transcriptome version are these counts associated with?

It's count data for the individual crab RNAseq... and I've been using it for new heatmaps and enrichment with transcriptome v 3.1. However, the 2020 Genewiz individual crab RNAseq data was not used in the assembly of transcriptome v 3.1... so I'm getting confused. 

I thought that I made this file, but now I'm thinking I may have gotten it from @kubu4 ...?

**Comment by kubu4** [comment]
I think deets are in Issue #941 and it used v1.5.

**Comment by grace-ac** [comment]
oh wow, totally forgot about that. Thanks!!
