### ISSUE TITLE
Download RStudio on new computer?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/resources#99]
Is it ok if I download RStudio on the new computer in 228?

**Comment by kubu4** [comment]
Of course! Don't forget to add that information (including version number) to the Lab Software list for that computer.

**Comment by grace-ac** [comment]
Ok!

I downloaded R (3. 4. 2) and I am not sure which RStudio to download:
![capture2](https://user-images.githubusercontent.com/14934314/31522925-64be82ac-af65-11e7-8a1f-99e402794082.PNG)

I originally tried the Windows Vista one, but I'm not sure that's right because it didn't end up installing...?

**Comment by kubu4** [comment]
You can use the Lab Software list and/or the Lab Computers for operating system info.

However, you are on Windows 7 64-bit.

What do you mean by "didn't end up installing"? Need more specific info.

**Comment by kubu4** [comment]
I just checked and RStudio starts up without issue (I didn't modify or install anything; just clicked on "RStudio" in Programs list). Re-open issue if it presents itself again.
