### ISSUE TITLE
MBD-BS library prep for Dungeness OA project

### ISSUE THREAD

**Issue by mgavery** [RobertsLab/resources#990]
Requesting MBD-BS library prep for Dungeness crab OA samples (MethylMiner enrichment -> PicoMethylSeq) for Laura's internship. There are 28 samples total. 
 
What I can provide:
-Isolated DNA and respective quants/QC for 28 samples
-MethylMiner kits, PicoMethylSeq kits and Ampure beads (if needed)

Question:
What should I purchase for QC of libraries? Are you still using a Bioanalyzer?  If you let me know which items to purchase I can provide those reagents as well.

**Comment by kubu4** [comment]
> Are you still using a Bioanalyzer?

Yes. Please order 1 of: high sensitivity DNA kit (cat: 5067-4626)

Also, please wait to order until we are close to using it.

Also, please give us a couple of days notice so we can arrange for someone to be at lab to receive the package.

**Comment by sr320** [comment]
Reopening as Libraries still need to be prepped.

**Comment by sr320** [comment]
@kubu4 is it possible to get these going in the next week or so?

**Comment by kubu4** [comment]
Sure. You need/want me to do it instead of Laura?

**Comment by sr320** [comment]
yes please

**Comment by kubu4** [comment]
@mgavery Can you please send me a spreadsheet with sample info (tube labels, concentrations, total DNA, etc)? Or, do we have a repo for this project where this info already resides?

**Comment by kubu4** [comment]
Also, do we have any samples I can test the MBD on? Not sure what type of recoveries to expect from Dungeness crab.

**Comment by mgavery** [comment]
Hiya, yes! I just shared the Gdoc with you and Steven that has all of that information.  I also suggested in the 'notes' column that CH05-21 would be a good sample for an MBD test.  We've done WGBS on a single sample and we're getting 7% CG methylation overall.  I was thinking (hoping!) that starting 1ug of DNA would be enough to provide sufficient yields after MBD to go into library prep.  Please let me know if you'd like to chat about this further. Thanks!

**Comment by kubu4** [comment]
Thanks. If you've already tested, then no need for me to do so. Thanks.

However, if using 1ug of DNA then the kit can process 25 samples. There are a total of 28 samples. Did you bring over one or two kits?

**Comment by mgavery** [comment]
We did whole genome bisulfite sequencing, so I think it would still be worth testing the recovery of MBD since we haven't done that before.  Just to be safe - that was my plan at least since I hadn't done MBD in years :)

There are 28 sample, but a few had crummy yields.  I made a comment in the notes section to not process those. That leaves 24 samples.  Nothing like cutting it close!

**Comment by kubu4** [comment]
Adding spreadsheet URL to help keep this project centralized:

https://docs.google.com/spreadsheets/d/1ym0XnYVts98tIUCn0kIaU6VuvqxzV7LoSx9RHwLdiIs/edit?usp=sharing

**Comment by kubu4** [comment]
@mgavery These DNA samples have _not_ been fragmented yet, correct?

**Comment by mgavery** [comment]
Correct. They have not been fragmented.

**Comment by kubu4** [comment]
@mgavery A few more quick questions:

1. What's the current sample volume?

2. It looks like you ran these on a TapeStation. Could you please share the electropherograms for these samples?

3. Is the "practice" sample also intended as an actual library sample, or I can it be completely used up for practice?

4. Is there a central location (e.g. a GitHub repo) where this data resides (or will reside) so that I can share relevant data from library prep (e.g. electropherograms, MBD calculations, library calculations, etc.)?

**Comment by sr320** [comment]
repo for this project 
https://github.com/RobertsLab/project-dungeness-crab

**Comment by mgavery** [comment]
1. sample volume ~45uL

2. attached my Evernote with the e.pherograms

3. the practice sample is lowest priority, so fine to use all the way if needed.

4. Github and I are not the best of friends. Just a heads up..
[Evernote_crab_DNAisolations.pdf](https://github.com/RobertsLab/resources/files/5411326/Evernote_crab_DNAisolations.pdf)

**Comment by kubu4** [comment]
@mgavery Do you have the actual electropherograms, instead of the gel representation?

**Comment by mgavery** [comment]
Good point, and no. My terrible notes are all I have. They original files on the machine in the lab.  If it would help with fragmentation I can try to get them to you by next week.  Note sure what your timing is.

**Comment by kubu4** [comment]
No biggie. For me, I just find it easier to evaluate the sample profiles.

**Comment by kubu4** [comment]
Out of curiosity, what tissue(s) was the DNA extracted from? Doesn't have any impact on what I'm doing, just interested.

**Comment by mgavery** [comment]
Teeny, tiny little gills.  The crabs were about the size of a quarter (J6 and J7 developmental stage). Fun dissection day :)

**Comment by kubu4** [comment]
@sr320 and @mgavery 

I'll have MDB finished next week and will be moving on to library prep. 

What is the sequencing strategy? Specifically, the PicoMethylSeq Kit (Zymo) being used for library prep only comes with 6 index primers; meaning we could only multiplex 6 samples per lane, which would required 4 lanes of sequencing (plus, what ever amount of "coverage" we're wanting).

Is this how you guys planned the sequencing?

Alternatively, I'm fairly certain that Shelly has previously ordered a supplementary set of Illumina index primers (based on guidance from Zymo) to allow for more multiplexing options. Do we need/want to use additional index primers? Of course, using additional index primers might be a moot point, if we still have to sequence in 4 lanes to achieve the desired coverage. One benefit, though, is that all libraries would be on the same flow cells; reducing the impact of variation across flow cells....

**Comment by mgavery** [comment]
Drats, that was an oversight. I didn't realize there were only 6 indices.  We have 2 lanes budgeted for this. 

Should I reach out to Shelly to get the info on what she ordered or do you know?  I have a lot of indices in my lab, but not sure if they're the right one.  I think I have a set of 24. 

It would be great to get all 24 in one library and run on duplicate lanes!

**Comment by kubu4** [comment]
We have the additional indices. Will prepare them for 24 multiplexing.

**Comment by mgavery** [comment]
So awesome! Thank you!

**Comment by mgavery** [comment]
@kubu4, the Zymo kit doesn't come with a lambda control for bisulfite conversion does it?   I have a lambda to spike if there isn't one. ..I could also just look up the protocol myself ;)

**Comment by kubu4** [comment]
No lambda DNA provided.

**Comment by mgavery** [comment]
Any chance of doing a lambda phage DNA drop off for you?  A 0.1 or 0.05% spike would be great to include for bisulfite conversion efficiency.  Our crab WGBS library was challenging to estimate using non-CG methylation and we don't yet have access to the mt genome to estimate conversion that way.

**Comment by kubu4** [comment]
> Any chance of doing a lambda phage DNA drop off for you?

Of course. I was planning on being in lab on Monday to prepare libraries, so it'd be great to drop off tomorrow, if possible. It looks like Yaamini and Grace will be there tomorrow starting at 9AM. Maybe you can coordinate with them?

Also, we've never dealt with the lamda spike ourselves. What's needed (e.g. do I need to create a "library"? If yes, that would mean a multiplex of 25 samples, right?)?

**Comment by mgavery** [comment]
Great, I need to check in to see if I can get access to the lab briefly tomorrow and I will coordinate.  

The lambda just needs to be spiked into the DNA before library prep.  I think 0.05% of the total DNA would be good.  Then there will be a few reads from each library that will map to the unmethylated lambda genome (I'll include that in my reference genome) to check conversion.

**Comment by kubu4** [comment]
Gotcha! Thanks!

**Comment by kubu4** [comment]
@mgavery 

Also, one sample (CH09-13) didn't have any MBD DNA recovery. I still have the wash fractions, so could try to re-capture. However, I doubt that's the issue, as all other samples in this batch had MBD DNA.

Should I give this one another go (there's a bit less than <1ug remaining) or just move forward with what we have?

**Comment by mgavery** [comment]
Re. CH09-13 I would say move forward with what we have

Re. lambda - that genome is ginormous and would have needed to be sheared :). How big are the MBD fragments?  I do have unmethylated control DNA from the other kit, but it's 134bp long.  Maybe that's too short?  I don't want to preferentially sequence the tiny little control DNA. 

 ..alternatively, I think we will have access to the mt genome through our assembly, just have to find it.

**Comment by kubu4** [comment]
> How big are the MBD fragments?

I think the range is from 250 - 500.

> it's 134bp long. Maybe that's too short?

I don't know.

**Comment by mgavery** [comment]
Hiya, please go ahead with library prep without spike.  Will use non-CpG methylation or mitochondrial DNA as proxy.  Thanks for letting me talk it through though :)

**Comment by kubu4** [comment]
@mgavery - Was getting library prep started and just discovered that the PicoMethylSeq Kit you gave us is for only 10 libraries. How would you like to proceed? Only prep 10 libraries or do you want to purchase an additional kit (e.g. 25 prep kit [Cat: D5456](https://www.zymoresearch.com/products/pico-methyl-seq-library-prep-kit))?

**Comment by mgavery** [comment]
The 25 prep kit will arrive tomorrow morning. Lets chat about a good day/time for handoff.  Sorry about that!

**Comment by kubu4** [comment]
Libraries are complete. Do you need/want me to send these out for sequencing? Is anything lined up?

**Comment by mgavery** [comment]
Sweet!! That's awesome!  

Do you have quant/bioanalyzer info available?  Have you done any library pooling yet?

**Comment by kubu4** [comment]
> Do you have quant/bioanalyzer info available?

Yes.

> Have you done any library pooling yet?

No. Need to find out what the sequencing facility needs/wants.

**Comment by mgavery** [comment]
Great!  Could you share the quant/bioanalyzer info with me?  

Are there any samples that didn't perform as well other than CH09-13?  We don't have an even number of samples per treatment, so maybe we can whittle down if any other libraries seem 'off'

**Comment by kubu4** [comment]
Output directory is here (which has images of individual electropherograms):

https://gannet.fish.washington.edu/Atumefaciens/20201125_mmag_bioanalyzer_mbd-bsseq-libraries/

Here are the three runs (CHO9-13 actually generated a library - I decided to try to make a library anyway, as the kit can handle such low input DNA):

##### DE72902486_2020-11-25_05-16-07

![Bioanalyzer electrophergrams for all samples in DE72902486_2020-11-25_05-16-07](https://gannet.fish.washington.edu/Atumefaciens/20201125_mmag_bioanalyzer_mbd-bsseq-libraries/2100-expert_High-Sensitivity-DNA-Assay_DE72902486_2020-11-25_05-16-07_EGRAM.png)


##### DE72902486_2020-11-25_06-12-38

![Bioanalyzer electrophergrams for all samples in DE72902486_2020-11-25_06-12-38](https://gannet.fish.washington.edu/Atumefaciens/20201125_mmag_bioanalyzer_mbd-bsseq-libraries/2100-expert_High-Sensitivity-DNA-Assay_DE72902486_2020-11-25_06-12-38_EGRAM.png)


##### DE72902486_2020-11-25_07-00-25

![Bioanalyzer electrophergrams for all samples in DE72902486_2020-11-25_07-00-25](https://gannet.fish.washington.edu/Atumefaciens/20201125_mmag_bioanalyzer_mbd-bsseq-libraries/2100-expert_High-Sensitivity-DNA-Assay_DE72902486_2020-11-25_07-00-25_EGRAM.png)

**Comment by mgavery** [comment]
Thanks! looks like CH10-19 may be a little funky, but others look similar.  Do you have the quants for these?  and if yes, are they data from Qubit?

**Comment by kubu4** [comment]
CH10-19 failed - it will not be submitted.

Quants are from Bioanalyzer (per the kit instructions - allows exclusion of primer dimers in quantification), but can easily be quanted with Qubit.

**Comment by mgavery** [comment]
Would you mind putting the final quants in the spreadsheet so I can see the range?

Do you have experience normalizing libraries using the Bioanalyzer quants? Does it work out pretty well?  I've always been wary of quants from TapeStation and never used them

**Comment by kubu4** [comment]
> Would you mind putting the final quants in the spreadsheet so I can see the range?

Yep, that's the plan. Finishing up notebook, data entry, etc. is on the agenda for tomorrow. I'll post here when all of this stuff is organized.

> Do you have experience normalizing libraries using the Bioanalyzer quants? 

Nope. Have only normalized libraries using qPCR quants.

So, are there any sequencing plans yet? I figured I'd just consult with the sequence facility regarding all of this and then get the pool prepped per their recommendations.

**Comment by laurahspencer** [comment]
@kubu4 - 
We ran the MiSeq data through the trimming/filtering/alignment pipeline, and a handful of the samples have very low %CpG methylation compared to the others: samples 5, 6, 9, 13, 14, & kind-of 19. Check out the [Bismark summary report](https://nbviewer.jupyter.org/github/laurahspencer/C.magister_methyl-oa/blob/master/qc-processing/MiSeq-QC/bismark/bismark_summary_report.html). In an effort to identify possible causes, we looked at correlations among %CpG meth and various library prep and sequencing metrics (from [this table,](https://raw.githubusercontent.com/laurahspencer/C.magister_methyl-oa/master/qc-processing/MiSeq-QC/mbdall.txt) processed in [this RMarkdown notebook](https://nbviewer.jupyter.org/github/laurahspencer/C.magister_methyl-oa/blob/master/notebooks/Notebook-03_MiSeq-QC-Analysis.html)). Here's a big correlation plot with all library prep / sequencing metrics (CpGmeth is 3rd from the bottom/right). Do you have any thoughts regarding library prep, and possible impacts to alignment and %meth?  Should you be interested, here's the [MultiQC report](https://nbviewer.jupyter.org/github/laurahspencer/C.magister_methyl-oa/blob/master/qc-processing/MiSeq-QC/FastQC/multiqc_report.html) (on trimmed/filtered reads) 

![image](https://user-images.githubusercontent.com/17264765/103317298-de3ce700-49df-11eb-9284-c6bc12b9b579.png)

#### The strongest correlation is with "%total reads that are unique": 
![image](https://user-images.githubusercontent.com/17264765/103317305-e2690480-49df-11eb-8d89-9f68f73d9f5b.png)

#### But some other factors also correlate loosely with %CpG meth 

![image](https://user-images.githubusercontent.com/17264765/103317308-e6952200-49df-11eb-9d8c-e44fea5d4b30.png)
![image](https://user-images.githubusercontent.com/17264765/103317316-eb59d600-49df-11eb-9586-f2fba7c2b77a.png)
![image](https://user-images.githubusercontent.com/17264765/103317324-eeed5d00-49df-11eb-8fe8-ef501ead4fe9.png)
![image](https://user-images.githubusercontent.com/17264765/103317337-f280e400-49df-11eb-9148-83fc046d07e6.png)

#### Here's also %meth ~ coverage for each sample separately, which also seem related 

![image](https://user-images.githubusercontent.com/17264765/103317735-e8abb080-49e0-11eb-9df9-0ab68b76821c.png)

**Comment by kubu4** [comment]
I don't have any thoughts. I'll let you @mgavery decide what you want to do next.

**Comment by sr320** [comment]
@laurahspencer This is probably best as a new issue..

**Comment by laurahspencer** [comment]
@kubu4 thanks, just figured we'd check!
