### ISSUE TITLE
Question regarding published dataset PXD000835

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#991]
I have a question regarding the raw file names of one of your published datasets (PXD000835; C. gigas; 400/2800 µatm). http://proteomecentral.proteomexchange.org/cgi/GetDataset?ID=PXD000835-2&test=no Could you explain to me the naming scheme of the raw files? I understand those are technical triplicates, so 24 files are from the acidification experiment without mechanical stimulation at the end of the month and the other 24 are with mechanical stimulation. Could you kindly explain to me which raw files belong to which treatment(s)?

via email

**Comment by emmats** [comment]
This is going to take me a minute. Luckily, I provide much more metadata with my PRIDE uploads now, but this was my first and I didn't do a great job. I need to track down my external hard drive that has my old computer on it. Last I saw it, Izzy was using it as part of his equipment for recon missions around the house.

**Comment by emmats** [comment]
Related: Does anyone have a cable that will connect my LaCie hard drive to my Mac?
![LaCie](https://user-images.githubusercontent.com/4564812/90420048-46f87800-e06c-11ea-96ef-e86f23106021.JPG)

**Comment by sr320** [comment]
I would imagine we have cables that would work in the conference room.

**Comment by kubu4** [comment]
Yes, but you'd probably get it faster if you just order what you need/want from Amazon. (FYI, the one on the far right is a USB connector; you might have one lying around)

**Comment by emmats** [comment]
I've looked at my lying around cables and came up with nothing. If my dad doesn't have one I'll order it.

**Comment by kubu4** [comment]
This may seem like a dumb question, but you do have the power cable for that drive, right?

**Comment by emmats** [comment]
Not a dumb question. I don't remember it ever having a power cable. It doesn't seem to come with one - https://www.apple.com/shop/product/HKVD2ZM/A/lacie-1tb-rugged-usb-c-portable-drive?afid=p238%7Cs7c5F8Ep7-dc_mtid_1870765e38482_pcrid_246387003753_pgrid_15434682490_&cid=aos-us-kwgo-pla-btb-catchall--slid---product-HKVD2ZM/A

**Comment by kubu4** [comment]
That's not the drive you have.

**Comment by emmats** [comment]
I know that, but mine is super old and I figured it is pretty similar. If I need a power cord I will hunt that down too. As I mentioned earlier, Izzy decided this was his toy a while back (I blame the orange and social isolation) so the entire situation is a bit of a disaster.

**Comment by kubu4** [comment]
You will need a power cable.

**Comment by emmats** [comment]
.raw mass spec file names follow this pattern: date of experiment_tank#_oyster#_replicate#
Tank# 103B are ambient pH
Tank# 101B are low pH
Oysters that were mechanically stressed: 32, 29, 26, 35, 242, 245, 251, 248
Oysters that were not mechanically stressed: 5,8,2,11,227,221,230,224
