### ISSUE TITLE
Trim oyster WGBS reads

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#992]
Can you please trim Roberto's WGBS reads https://d.pr/i/m8M9ge

following his methods

![image](https://user-images.githubusercontent.com/4442039/90417947-4f02e880-e069-11ea-9104-9a6ddc9793ff.png)

**Comment by kubu4** [comment]
Trimmed data is here: https://gannet.fish.washington.edu/Atumefaciens/20200818_cgig_wgbs_roberto_fastp_trimming/

All trimmed files are labeled like so: *fastp-trim*.fq.gz

There are FastQC reports.

MulitQC report is here: https://gannet.fish.washington.edu/Atumefaciens/20200818_cgig_wgbs_roberto_fastp_trimming/multiqc_report.html

Haven't had a chance to review data, nor put together notebook entry yet. Will post notebook entry here when completed.

**Comment by kubu4** [comment]
Notebook entry:

https://robertslab.github.io/sams-notebook/2020/08/18/Trimming-FastQC-MultiQC-Robertos-C.gigas-WGBS-FastQ-Data-with-fastp-FastQC-and-MultiQC-on-Mox.html
