### ISSUE TITLE
gDNA from Adductor 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#993]
_via email_ ..

I am having a hell of a time getting good DNA out of surfclam adductor muscle. DNA concentration is low and our 230/260 is very low; it looks like contaminants are inhibiting restriction digestion (our assay for likely problems in library preps). 

I notice that folks in your lab have used Geoduck adductor, so I’m wondering if you have found need for a change of protocol, or if you have learned to avoid it?

Or maybe you are getting good results with the E.Z.N.A Mollusc DNA Kit?

**Comment by kubu4** [comment]
We get satisfactory results with the E.Z.N.A. Mollusc DNA Kit with adductor muscle. Somewhat low 260/280 (~1.8) and similarly for 260/230 (~1.65).

However, we've done limited isolations on geoduck adductor muscle.

If I were to repeat, I'd homogenize tissue under LN2 (previously, just minced with razor blade and performed lysis/ProK step, per kit protocol).

Subsequent cleanup (kit or EtOH precip) might be useful.

**Comment by sr320** [comment]
Thanks!
