### ISSUE TITLE
Large differences in global methylation between samples: ARTIFACT???

### ISSUE THREAD

**Issue by jarcasariego** [RobertsLab/resources#999]
Hi All, 
I'm sorry for the many issues, but here is another. I was doing the QC on the final alignment of the MBD-BS data and noticed these large differences in %CpG methylation between samples (multiqc report attached). I looked through it and could not find any explanation to it from differences in sample processing, treatments or genotypes. I have no idea how this will affect my data analysis, but if it is an artifact of the alignment I will need to solve it. Any idea???

[multiqc_report_-09_align.html.txt](https://github.com/RobertsLab/resources/files/5158882/multiqc_report_-09_align.html.txt)

**Comment by shellytrigg** [comment]
@jarcasariego this is also apparent in the alignment comparison report you previously shared here https://github.com/RobertsLab/resources/issues/967. Your plots consistently show about 7 samples have lower CpG methylation regardless of alignment score threshold, aligner (bowtie/hisat), trimming, etc. That tells us it is likely not your alignment parameters.

Could it be a biological difference (e.g. different tissue, different age, etc.)?

**Comment by jarcasariego** [comment]
@shellytrigg 
> Could it be a biological difference (e.g. different tissue, different age, etc.)?
 It seems not, two genotypes and all treatments are represented in the seven samples with low methylation. Initially I thought it could be related with a response to stress (5 of the samples were heated corals) but two controls showed the same pattern. 
Do you think I should filter or normalize somehow to make the datasets comparable? 
See the scatterplots for the correlation %CpG methylation between treatments. BH show a very different global pattern maybe because three of the six samples of the treatment have low methylation. 

![BCvsBH](https://user-images.githubusercontent.com/30119953/91919950-a1f9b400-ec95-11ea-9944-d471c44051e4.png)
![BCvsCC](https://user-images.githubusercontent.com/30119953/91919952-a2924a80-ec95-11ea-99c0-9ca2ee337962.png)
![BHvsCH](https://user-images.githubusercontent.com/30119953/91919954-a32ae100-ec95-11ea-842c-d7a930c6399e.png)
![CCvsCH](https://user-images.githubusercontent.com/30119953/91919955-a32ae100-ec95-11ea-9f4d-d62cf26c3e24.png)

**Comment by shellytrigg** [comment]
I'm not sure I would filter or normalize the data at this point since it's not clear where the methylation differences are coming from. If I'm understanding correctly, the correlation plots are showing commonly covered loci across different treatment groups, half the BH group tends to have lower methylation which causes the curve in the first and third corrplot, and 2/6 of the control group show similar trend? 

Did you apply any read depth threshold before comparing loci in your corrplots (e.g. 5x or 10x)? It's possible that methylation calls for CpGs with low coverage may not be reliable. 

I'm also wondering if there is a difference in coverage of particular genome regions in your samples that show low global methylation compared to your other samples?

**Comment by jarcasariego** [comment]
> If I'm understanding correctly, the correlation plots are showing commonly covered loci across different treatment groups, half the BH group tends to have lower methylation which causes the curve in the first and third corrplot, and 2/6 of the control group show similar trend?
Yes, I got three BH samples, 2 CH, 1 CC and 1 BC showing a similar low methylation pattern. So 5 heated and 2 controls for both symbiont states.
> Did you apply any read depth threshold before comparing loci in your corrplots (e.g. 5x or 10x)? It's possible that methylation calls for CpGs with low coverage may not be reliable. 
The graphs I added were without coverage filtering but I did 5x and the pattern is the same.  
> I'm also wondering if there is a difference in coverage of particular genome regions in your samples that show low global methylation compared to your other samples?
I compared coverage (in 2kb windows) between grouped HiMeth and LowMeth and it seems fairly similar (see image: darkblue was set for 5x coverage and clearer values show higher coverage) 
![image](https://user-images.githubusercontent.com/30119953/92309667-82081000-ef75-11ea-9cbf-a4031afccc81.png)
